### ISSUE TITLE
Traefik preferring ACME over provided certificates for configured sites

### ISSUE THREAD

**Issue by nathantreid** [containous/traefik#1003]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
traefik.toml:
```
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/ssl/certs/deployed/wildcard.mysite.com.crt"
        KeyFile = "/etc/ssl/certs/deployed/wildcard.mysite.com.key"

[acme]
  email = "<redacted>"
  storage = "acme.json"
  storageFile = "acme.json"
  onDemand = true
  onHostRule = true
  entryPoint = "https"
  caServer = "https://acme-staging.api.letsencrypt.org/directory"

[docker]
  exposedbydefault = false
```
docker service:
```
docker service create \
    --name traefik \
    --constraint=node.role==manager \
    --constraint 'node.labels.hosting-shared == 1' \
    --constraint 'node.labels.production == 1' \
    --publish 80:80 --publish 8080:8080 --publish 443:443 \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --mount type=bind,source=/docker/traefik/lets-encrypt,target=/etc/traefik/acme \
    --mount type=bind,source=/docker/traefik/certs,target=/etc/ssl/certs/deployed \
    --mount type=bind,source=/docker/traefik/traefik.toml,target=/traefik.toml \
    --network web \
    traefik \
    --docker \
    --docker.swarmmode \
    --docker.domain=traefik \
    --docker.watch \
    --web
```

### What did you do?
I set up a default wildcard certificate, *.mysite.com. I set up a hosts entry on my machine so I could test whoam1.mysite.com. I browsed to the site and as expected received the "404 page not found" message. My certificate loaded correctly.

Then I set up a container and browsed to the site again:
```
docker service create \
    --name whoami1 \
    --label traefik.port=80 \
    --label traefik.frontend.rule=Host:whoami1.mysite.com \
    --network web \
    emilevauge/whoami
```

### What did you expect to see?
I expected to see the whoami page, with my certificate correctly loading.

### What did you see instead?
 Instead, I received an ERR_SSL_PROTOCOL_ERROR. 
"This site can’t provide a secure connection. whoami1.mysite.com sent an invalid response."

Inspecting the logs revealed that Traefik is requesting a Let's Encrypt certificate instead of using the one I provided (and of course failing, since the DNS entry isn't pointing to this server): 
```
server.go:2317: http: TLS handshake error from 10.255.0.3:53634: Cannot obtain certificates map[whoami1.mysite.com:acme: Error 400 - urn:acme:error:connection - Failed to connect to x.x.x.x:443 for TLS-SNI-01 challenge
```

**Comment by dtomcej** [comment]
This is a duplicate of https://github.com/containous/traefik/issues/672. Currently working on a fix.

**Comment by dtomcej** [comment]
Resolved with https://github.com/containous/traefik/pull/1018

**Comment by anton-johansson** [comment]
Not sure if I should open a new issue for this or not, but I seem to have the exact same problem. I run version `1.7.3` and this issue should be fixed from as early as `1.2.0`.

The only difference between me and the OP is that I've configured it with command line arguments instead, running inside Docker swarm (but the Swarm-part shouldn't be relevant). Here is my Swarm stack deploy file:

```yml
version: '3.3'

services:
  consul:
    image: consul:1.3.0
    command: agent -server -bootstrap-expect=1
    networks:
      - consul-net
    volumes:
      - type: bind
        source: /var/traefik-data/consul-data/
        target: /consul/data/
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
  initiation:
    image: traefik:1.7
    networks:
      - consul-net
    depends_on:
      - consul
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - storeconfig
      - --entryPoints=Name:http Address::80
      - --entryPoints=Name:https Address::443 TLS:/cert/star.service.example.local.crt,/cert/star.service.example.local.key
      - --defaultentrypoints=http,https
      - --api
      - --api.entryPoint=traefik
      - --api.dashboard=true
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.exposedByDefault=false
      - --docker.endpoint=tcp://swarm.service.example.local:2376
      - --acme
      - --acme.storage=traefik/acme/account
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.onHostRule=true
      - --acme.onDemand=false
      - --acme.email=something@example.com
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
      - --logLevel=WARN
      - --traefikLog.format=json
      - --accessLog.format=json
  app:
    image: traefik:1.7
    networks:
      - consul-net
      - traefik-net
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/traefik-data/certificates/
        target: /cert/
    depends_on:
      - consul
      - initiation
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik-net"
        traefik.port: 8080
        traefik.frontend.rule: "Host:traefik.service.example.local"
        traefik.frontend.entryPoints: "https"
        traefik.frontend.whitelist.sourceRange: "192.168.0.0/16, 10.0.0.0/8"
    command:
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
      - --logLevel=WARN
      - --traefikLog.format=json

networks:
  traefik-net:
    external:
      name: traefik-net
  consul-net:
    driver: overlay
```

As you can see, I have a wildcard certificate for `*.service.example.local`, which is self-signed. Obviously because I cannot use Lets Encrypt for these. However, when I run ACME for other services (that are publically available), I get the following in my logs:

```
Error getting ACME certificates [traefik.service.example.local] : cannot obtain certificates: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix
Error getting ACME certificates [elasticsearch.service.example.local] : cannot obtain certificates: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix
...
```
