### ISSUE TITLE
Non-TLS content on HTTPS endpoint for AWS NLB with Proxy protocol v2

### ISSUE THREAD

**Issue by beranm14** [containous/traefik#10047]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Every time our Traefik instance reaches a higher number (1k>) of connections, it starts to return non-TLS content on the HTTPS endpoint.

Once Proxy protocol v2 is disabled, the problem disappears.

https://community.traefik.io/t/non-tls-content-on-https-endpoint/19330/2

### What did you see instead?

Body contains:

```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close
400 Bad Request
```

### What version of Traefik are you using?

 * Traefik docker image version: [docker.io/traefik:v2.10.1](http://docker.io/traefik:v2.10.1)
 * Helm chart version: v23.1.0
 
 I tried versions 20.8.0, 21.2.1, 22.0.0, and 22.3.0 charts with the same result.

Our setup is running as NodePort behind AWS NLB.

We use arm instances, but the issue also happens for the amd64 architecture.

### What is your environment & configuration?

We tried following arguments:

```yaml
 {
    name: 'service.type',
    value: 'NodePort',
  },
  {
    name: 'service.spec.externalTrafficPolicy',
    value: 'Local',
  },
  {
    name: 'service.spec.internalTrafficPolicy',
    value: 'Local',
  },
  {
    name: 'ingressClass.isDefaultClass',
    value: 'false',
  },
  {
    name: 'ports.web.nodePort',
    value: '30080',
  },
  {
    name: 'ports.web.proxyProtocol.trustedIPs',
    value: '10.100.0.0/16',
  },
  {
    name: 'ports.web.middlewares[0]',
    value: 'traefik-default@kubernetescrd',
  },
  {
    name: 'ports.websecure.nodePort',
    value: '30443',
  },
  {
    name: 'ports.websecure.proxyProtocol.trustedIPs',
    value: '10.100.0.0/16',
  },
  {
    name: 'ports.metrics.expose',
    value: 'true',
  },
  {
    name: 'ports.metrics.nodePort',
    value: '30100',
  },
  {
    name: 'ports.traefik.healthchecksPort',
    value: '8000',
  },
  {
    name: 'providers.kubernetesIngress.allowEmptyServices',
    value: 'true',
  },
  {
    name: 'providers.kubernetesIngress.allowExternalNameServices',
    value: 'true',
  },
  {
    name: 'additionalArguments[0]',
    value: '--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1',
  },
  {
    name: 'additionalArguments[1]',
    value: '--serversTransport.insecureSkipVerify=true',
  },
  {
    name: 'additionalArguments[2]',
    value: '--serversTransport.maxIdleConnsPerHost=1000',
  },
  {
    name: 'additionalArguments[3]',
    value: '--entryPoints.web.transport.respondingTimeouts.readTimeout=300',
  },
  {
    name: 'additionalArguments[4]',
    value: '--entryPoints.web.transport.respondingTimeouts.writeTimeout=300',
  },
  {
    name: 'additionalArguments[5]',
    value: '--entryPoints.web.transport.respondingTimeouts.idleTimeout=300',
  },
  {
    name: 'additionalArguments[6]',
    value: '--entryPoints.web.transport.lifeCycle.graceTimeOut=60',
  },
  {
    name: 'additionalArguments[7]',
    value: '--entryPoints.web.http2.maxConcurrentStreams=2000',
  },
  {
    name: 'additionalArguments[8]',
    value: '--entryPoints.websecure.transport.respondingTimeouts.readTimeout=300',
  },
  {
    name: 'additionalArguments[9]',
    value: '--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=300',
  },
  {
    name: 'additionalArguments[10]',
    value: '--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=300',
  },
  {
    name: 'additionalArguments[11]',
    value: '--entryPoints.websecure.transport.lifeCycle.graceTimeOut=60',
  },
  {
    name: 'additionalArguments[12]',
    value: '--entryPoints.websecure.http2.maxConcurrentStreams=2000',
  },
```

To be sure there are no cross-wires, I disabled metrics and web endpoint, leaving only websecure entrypoint. The result was the same.

The issue happens regardless of the number of replicas.

### If applicable, please paste the log output in DEBUG level

There was nothing in the logs related to the issue.
