### ISSUE TITLE
Exclude OPTIONS requests from Basic Auth

### ISSUE THREAD

**Issue by smelchior** [containous/traefik#1019]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
Traefik in a Kubernetes Cluster with [web.auth.basic] enabled

### What did you do?
We send an OPTIONS request to one of our backend services. 

### What did you expect to see?
OPTIONS Requests should be passed through without authentication, as the browser does not send it for OPTIONS requests. 

### What did you see instead?
401 Error from Traefik

I know that disabling the auth for OPTIONS requests is not always a good idea, but there should be an option to disable it 
This is somewhat related to #160 but i still want to define the OPTIONS header rules in my application and not in traefik.

**Comment by osixia** [comment]
Same here with our angular frontent :(

**Comment by Cinerar** [comment]
Any workarounds?

**Comment by MichaelEFlip** [comment]
> 
> 
> Any workarounds?
> ok as a workaround
> https://docs.traefik.io/v1.5/configuration/backends/docker/#on-service
> Created another service for same backend matched Method:OPTIONS and forwarded this request without auth.

Sample for a working configuration with docker-compose labels.
To get it working it is especially important that the order of the rules is correct.

```
labels:
  - traefik.servicewithauth.frontend.rule=Method:GET,POST,Host:mydomain.de
  - traefik.servicewithauth.frontend.auth.basic=myusername:mypasswordhash
  - traefik.servicewithauth.port=8080
  - traefik.servicewithoutauth.frontend.rule=Method:OPTIONS,Host:mydomain.de
  - traefik.servicewithoutauth.port=8080
  - traefik.docker.network=traefik-proxy
```

**Comment by gentunian** [comment]
Is this issue resolved without workaround? Traefik is handling `OPTION` request as a `GET` request when frontend has authentication set and it's returning 401 despite that custom header for allowing CORS is set:

my labels:

```
      labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:myapi.my.domain"
      - "traefik.docker.network=webgateway"
      - "traefik.backend=my-backend"
      - "traefik.frontend.auth.basic.users=<user:httpasswd>"
      - "traefik.domain=myapi.my.domain"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
      - "traefik.frontend.headers.customRequestHeaders=Access-Control-Allow-Origin:*"
```

Response:
```
content-length: 17
content-type: text/plain
date: Wed, 06 Feb 2019 19:40:47 GMT
status: 401
www-authenticate: Basic realm="traefik"
```

**Comment by gentunian** [comment]
This is my ugly workaround, the above didn't work for my service:

```
  real-service:
    deploy:
      labels:
          # container labels (defaults)
        - "traefik.enable=true"
        - "traefik.backend=real-service"
        - "traefik.docker.network=webgateway"
        - "traefik.port=8080"
        - "traefik.protocol=http"
        - "traefik.domain=my.domain.com"
        -  "traefik.frontend.rule=Method:GET,POST,PUT,PATCH,DELETE;Host:my.domain.com"
        - "traefik.frontend.auth.basic.users=<user:httpasswd>"

  dummy:
    image: emilevauge/whoami
    networks:
      - webgateway
    deploy:
      labels:
          # container labels (defaults)
        - "traefik.enable=true"
        - "traefik.backend=dummy"
        - "traefik.docker.network=webgateway"
        - "traefik.port=80"
        - "traefik.protocol=http"
        - "traefik.domain=my.domain.com"
        - "traefik.cors.frontend.rule=Method:OPTIONS;Host:my.domain.com
        - "traefik.cors.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Method:GET,POST,PUT,PATCH,DELETE,OPTIONS||Access-Control-Allow-Headers:apikey,authorization,content-type||Access-Control-Allow-Credentials:true"
```

**Comment by gentunian** [comment]
finally, for future reference, I ended up writing a simple express app that allowed cors:

```nodejs
const express = require('express')
const cors = require('cors')
const morgan = require('morgan')
const app = express()
// log requests
app.use(morgan('combined'))
app.use(cors())

app.listen(8000, function () {
  console.log('CORS-enabled web server listening on port 8000')
})
```

with these labels:

```yml
...
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=my-service"
        - "traefik.docker.network=webgateway"
        - "traefik.domain=my.domain.com"
        - "traefik.port=8080"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=Method:GET,POST,PUT,PATCH,DELETE;Host:my.domain.com"
        - "traefik.frontend.auth.basic.users=<user:htpasswd>"
        - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Method:GET,POST,PUT,PATCH,DELETE,OPTIONS||Access-Control-Allow-Headers:authorization,content-type||Access-Control-Allow-Credentials:true"

  cors:
    image: gentunian/cors
    networks:
      - webgateway
    environment:
      - NODE_ENV=production
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=cors"
        - "traefik.docker.network=webgateway"
        - "traefik.domain=my.domain.com"
        - "traefik.port=80"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=Method:OPTIONS;Host:my.domain.com"
```
