### ISSUE TITLE
HTTP basic auth per entrypoint

### ISSUE THREAD

**Issue by vaboston** [containous/traefik#1020]
Hello, I have a problem when I configure an authentication on a "personal" entrypoint, is it normal?
Here my traefik.toml: 
```[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.auth.basic]
  users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]
  [entryPoints.service2]
  address = ":8081"
  [entryPoints.service2.auth.basic]
  users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]
```
and my docker-compose.yml:
```
service 1:
  image: linuxserver/xxxx
  privileged: true
  restart: always
  volumes:
    - "/dock/downloads/:/downloads/"
    - "/dock/config/:/config/"
  labels:
    - "traefik.port=http"
    - "traefik.backend=back1"
    - "traefik.frontend.rule=Host:test.localhost"
    - "traefik.frontend.entryPoints=http"
service2:
  image: xxxxxxx
  privileged: true
  restart: always
  volumes:
    - "/test/config/:/config/"
  labels:
    - "traefik.port=8081"
    - "traefik.backend=back2"
    - "traefik.frontend.rule=Host:test2.localhost"
    - "traefik.frontend.entryPoints=service2"
```
But when I try auth on test2.localhost, a 404 response is send and traefik log "Auth failed ".
Can you help me ?
