### ISSUE TITLE
missing source of error. in logs

### ISSUE THREAD

**Issue by wibed** [containous/traefik#10202]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

start an empty cluster with limited resources

### What did you see instead?

logs create output
```text
"Error while adding route for host: invalid value for \"HostSNI\" matcher, \"/\" is not a valid hostname or IP"
```

### What version of Traefik are you using?

23.2.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by kevinpollet** [comment]
Hello @wibed and thanks for opening the issue,

What information is missing in the log?
Could you provide us the dynamic configuration or Ingress/IngressRoute resource?

**Comment by wibed** [comment]
> what information is missing in the log?
- i would like to know the source of the problem

> could you provide us the dynamic configuration or ingress/ingressroute resource?
i cannot there is no configuration that could cause such an output

**Comment by ldez** [comment]
What do you call the "source"?
The error appears because Traefik tries to create a router based on something inside your cluster (Ingress/IngressRoute), I think your cluster is not really empty.

Can you provide a fully reproducible example? (helm files, full logs, etc.)

**Comment by wibed** [comment]
these are the only ingress i have:


```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: cluster0
    app.kubernetes.io/name: traefik
    app.kubernetes.io/namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: selfsignedtls
  name: cluster0-traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - traefik
  routes:
  - kind: Rule
    match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    services:
      - kind: TraefikService
        name: dashboard@internal
        namespace: traefik
  tls:
    secretName: tlscertificatesecret
    ```


```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: cluster0
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/namespace: docker-registry
  annotations:
    cert-manager.io/cluster-issuer: selfsignedtls
  name: cluster0-docker-registry
  namespace: docker-registry
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`/`)
    services:
      - name: cluster0-docker-registry
        namespace: docker-registry
        port: 5000
  tls:
    secretName: tlscertificatesecret
    ```


```yaml
{{- if .Values.ingressRoute.ssh.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "gitsrv.fullname" . }}
  namespace: {{ template "gitsrv.name" .}}
spec:
  entryPoints:
    - ssh
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ template "gitsrv.fullname" . }}
      namespace: {{ template "gitsrv.name" . }}
      port: 2222
{{- end -}}
```


none of those have a hostsni, that would not change the output of the log upon changing.
thats why i could exclude those
