### ISSUE TITLE
Cannot start traefik docker service

### ISSUE THREAD

**Issue by HazCod** [containous/traefik#1021]
### What version of Traefik are you using (`traefik version`)?
v.1.1.2

### What is your environment & configuration (arguments, toml...)?
```dockerfile
FROM traefik

ADD traefik.toml /etc/traefik/traefik.toml

EXPOSE 8080 8081
VOLUME /config
```

config:
```toml
debug = true
logLevel = "DEBUG"

## LetsEncrypt
[acme]
email = "xxx"
storage = "/config/acme.json"
entryPoint = "https"
dnsProvider = "namecheap"
# NAMECHEAP_API_USER, NAMECHEAP_API_KEY
onDemand = true

## Entrypoints
[entryPoints]
	[entryPoints.http]
	address = ":8080"
	compress = true
		[entryPoints.http.redirect]
		regex = "^http://(.*)"
		replacement = "https://$1"

	[entryPoints.https]
	address = ":8081"
	compress = true

## Backends
[docker]
endpoint = "tcp://sockproxy:9090"
domain = "hazcod.com"
watch = true
swarmmode = true
constraints = ["tag==expose"]
#[docker.tls]
#	ca = ""
#	cert = ""
#	key = ""
```

And sockproxy:
```dockerfile
FROM alpine

# Make sure docker has gid 101 on  your host
RUN addgroup -g 101 docker \
	&& adduser -H -D -G docker -s /bin/true socat

RUN apk add -U socat \
	&& rm -rf /var/cache/apk*

USER socat
EXPOSE 9090
CMD /usr/bin/socat -d -d TCP-L:9090,fork UNIX:/var/run/docker.sock
```

### What did you do?
While sockproxy service is running, try to run swarmproxy service.
Commands: `docker service create --name sockproxy --network internal-net --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,readonly --constraint 'node.role==manager' sockproxy` & `docker service create --name swarmproxy --network internal-net --network external-net -p 80:8080 -p 443:8081 swarmproxy`

### What did you expect to see?
swarmproxy service running.

### What did you see instead?
swarmproxy service continually stays at 0/1 replicas, even when scaling.
Docker event log shows continually re-creating: http://pastebin.com/raw/UFh7B9Gd
No active containers in `docker ps` for swarmproxy.
Both containers can run with `docker run`, albeit without networks.
