### ISSUE TITLE
[Configuration help] Round trip (error code 200) when connecting to a service through path

### ISSUE THREAD

**Issue by peperunas** [containous/traefik#1032]
# UPDATED, SEE BELOW!

### What version of Traefik are you using (`traefik version`)?
`1.1.2`

### What is your environment & configuration (arguments, toml...)?
This is my `.toml`:

```
################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "docker.localhost"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/fullchain.pem"
      keyFile = "/etc/traefik/ssl/privkey.pem"

```

This is my `docker-compose.yml`:

```
version: '2'

services:
  traefik:
    image: traefik
    command: accessLogsFile='/etc/traefik/log/access.log'
    network_mode: "host"
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    volumes:
    - traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock

  gitea:    
    restart: always
    image: gitea/gitea
#    ports:
#    - "10022:22"
#    - "10000:10000"
    volumes:
    - gitea:/data
    labels:
    - traefik.backend=gitea
    - traefik.frontend.rule=Host:mydomain.com;Path:/gitea
    - traefik.port=10000

volumes:
  gitea:
  traefik:

```
### What did you do?

I've set up the `toml` file and I'm trying to access to `gitea` through `mydomain.com/gitea`.

### What did you expect to see?
The `gitea` web service

### What did you see instead?
`404 not found`

What am I missing? Thanks!

**Comment by dknell** [comment]
Why is this closed? What was the fix?

**Comment by peperunas** [comment]
Never received an answer.

**Comment by timoreimann** [comment]
@peperunas apologies for not getting back to your issue. If you are (or anyone else is) still interesting in an answer, we should reopen the issue and drive for a resolution.

**Comment by timoreimann** [comment]
@peperunas thanks for reopening.

@containous/traefik let's investigate.

**Comment by timoreimann** [comment]
@peperunas Starting the gitea Docker locally, it seems that it runs on port 3000. Could that be your problem?

If that's not the problem: Could you please start Traefik with the additional `--debug` parameter and then post the output of your docker-compose log?

**Comment by peperunas** [comment]
@timoreimann, I configured `gitea` to work on port 10000. I'll post the debug log asap.

**Comment by peperunas** [comment]
@timoreimann, here is an updated scenario.

### What version of Traefik are you using (`traefik version`)?
`1.2.0`

### What is your environment & configuration (arguments, toml...)?
This is my `.toml`:

```
# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/traefik/fullchain.pem"
      KeyFile = "/etc/ssl/traefik/privkey.pem"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/traefik/fullchain.pem"
      KeyFile = "/etc/ssl/traefik/privkey.pem"
```

This is my `docker-compose.yml`:

```
version: '2'

services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=domain.com --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
#      - /dev/null:/traefik.toml
      - ./traefik/ssl:/etc/ssl/traefik


  gitea:    
    restart: always
    image: gitea/gitea
    ports:
    - "10022:22"
    - "10000:10000"
    volumes:
    - gitea:/data
    labels:
    - "traefik.frontend.rule=Host:domain.com;PathStrip:/gitea/"
    - "traefik.port=10000"

volumes:
  gitea:
  traefik:

```
### What did you do?

I've set up the `toml` file and I'm trying to access to `gitea` through `domain.com/gitea`.

### What did you expect to see?
The `gitea` web service

### What did you see instead?
`gitea` is actually reached but the page is heavily incomplete (see screenshot).
The only error I get is:

```
traefik_1    | time="2017-03-27T10:11:28Z" level=debug msg="Round trip: http://172.18.0.3:10000, code: 200, duration: 15.113091ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:domain.com" 
```

### Screenshot

![image](https://cloud.githubusercontent.com/assets/6033387/24351945/00a659a8-12e8-11e7-8920-a44a912516fa.png)
