### ISSUE TITLE
Traefik with Consul catalog backend + Registrator

### ISSUE THREAD

**Issue by mindnuts** [containous/traefik#1039]
### What version of Traefik are you using (`traefik version`)?
1.1.2 camembert

### What is your environment & configuration (arguments, toml...)?
Config.toml to enable Consul Catalog backend
```toml
[consulCatalog]
endpoint = "172.17.8.101:8500"
domain = "service.consul"
prefix = "traefik"
```
Rules.toml (File backend which works correctly)
```toml
# rules
[backends]  
  [backends.backend2]
    [backends.backend2.maxconn]
      amount = 10
      extractorfunc = "request.host"
    [backends.backend2.LoadBalancer]
      method = "drr"
    [backends.backend2.servers.server1]
    url = "http://172.17.8.101:4040/"
    weight = 1
    [backends.backend2.servers.server2]
    url = "http://172.17.8.101:4000/"
    weight = 2

  [backends.backend3]    
    [backends.backend3.servers.server1]
    url = "http://172.17.8.101:5030/"
    weight = 1

  [backends.backend4]    
    [backends.backend4.servers.server1]
    url = "http://172.17.8.101:7050/"
    weight = 1 
  [backends.web-backend]
    [backends.web-backend.servers.server1]
      url = "http://172.17.8.101:3080/"
      weight = 1 
    [backends.web-backend.servers.server2]
      url = "http://172.17.8.101:3088/"
      weight = 1 

[frontends]  
  [frontends.frontend2]
    backend = "backend2"
    passHostHeader = true
    priority = 10    
      [frontends.frontend2.routes.test_1]
      rule = "Host:admin-ewr.com"
  

  [frontends.frontend3]
    backend = "backend3"
    passHostHeader = true    
      [frontends.frontend3.routes.path1]
      rule = "PathPrefix:/search"


  [frontends.storage]
    backend = "backend4"
    passHostHeader = true    
      [frontends.storage.routes.path1]
      rule = "Path:/files/new;Method: POST"

  [frontends.web]
    backend = "web-backend"
    passHostHeader = true    
      [frontends.web.routes.path1]
      rule = "HostRegexp:{subdomain:[a-z]+}.ewr.com"
```
### What did you do?

Trying to get Traefik working with consul catalog backend working. The file backend works correctly. The Consul Catalog node endpoint reports the Service data correctly:
```
"core-01:web1:80":{
    "ID":"core-01:web1:80",
    "Service":"web",
    "Tags":[
    "traefik.frontends.web.backend=web-backend",
    "traefik.frontends.web.passHostHeader=true",
    "traefik.frontends.web.routes.path1.rule=HostRegexp:{subdomain:[a-z]+}.ewr.com",
    "traefik.backends.web-backend.servers.server1.url=http://172.17.8.101:46755/",
    "traefik.backends.web-backend.servers.server1.weight=1"
    ],
    "Address":"",
    "Port":46755,
    "EnableTagOverride":false,
    "CreateIndex":883,
    "ModifyIndex":883
}
```

### What did you expect to see?

The path1 rule to be picked
### What did you see instead?
![image](https://cloud.githubusercontent.com/assets/8411896/21985385/60c0f798-dc20-11e6-9b36-30786def240d.png)
Traefik route is default one instead of path1 rule

Not sure what i am doing wrong.

EDIT: Pasting the screenshot of Backend for Web and it seems it is creating the name with the tags: 
![image](https://cloud.githubusercontent.com/assets/8411896/22019268/d8c78172-dcd8-11e6-9cd9-b4718c9d073f.png)
