### ISSUE TITLE
Docker hostnames in backends url configuration

### ISSUE THREAD

**Issue by Crempa** [containous/traefik#1040]
### What version of Traefik are you using (`traefik version`)?

 v 1.1.2

### What is your environment & configuration (arguments, toml...)?

```toml
[backends]
  [backends.test]
    [backends.test.servers.node1]
      url = "http://test:9000"

[frontends]
  [frontends.test]
    backend = "test"
    passHostHeader = true
        [frontends.test.routes.entry]
            rule = "Host: test.mydomain.com"
```

### What did you do?

I sent request from browser to domain **test.mydomain.com**

### What did you expect to see?

I expect to see result from service runnning on port 9000 in local private docker network in container with hostname "test". Traefik is running in container joined to the same private network.

### What did you see instead?

Traefik did not sent request to IP of container running under hostname "test" but to public IP obtained from dns-search. Host machine is configured to use "something.com" as dns-search suffix so request was sent to "test.something.com" instead of to local container service.

I'm not sure if it is bug or feature and if it is traefik or docker related issue, but I expect higher priority to local network hostname instead of dns-search result.
