### ISSUE TITLE
Support for default route for k8s backend

### ISSUE THREAD

**Issue by sheerun** [containous/traefik#1051]
Traefik current doesn't recognize default backend of kubernetes ingress, showing 404 instead:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: deis
  name: deis
spec:
  backend:
    serviceName: deis-router
    servicePort: 80
```

Is it reasonable to configure catch-all in traefik if following ingress is present? I'd say so.
