### ISSUE TITLE
Error forwarding with err: EOF in logs when using pathprefixstrip on / route in kubernetes setup

### ISSUE THREAD

**Issue by christianhuening** [containous/traefik#1054]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
Running Daemon Set Ingress in 6-node kubernetes cluster (1.5.2) hosted on-prem using Weave as pod network. Communication between nodes and pods is working quite fine (checked with cURL etc.)

Toml:
``` toml
# traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
```
ingress-controller.yaml:
``` yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller-v1
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.1.2
        name: traefik-ingress-lb
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8081
        volumeMounts:
          - mountPath: "/config"
            name: "config"
        args:
        - --web
        - --web.address=:8081
        - --configfile=/config/traefik.toml
        - --kubernetes
      volumes:
        - name: config
          configMap:
            name: traefik-configmap
```
ingress.yaml
``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: pathprefixstrip
  name: mars-ingress
spec:
  backend:
        serviceName: webui-svc
        servicePort: http
  rules:
  - http:
      paths:
      - path: /file
        backend:
          serviceName: file-svc
          servicePort: http
      - path: /metadata
        backend:
            serviceName: metadata-svc
            servicePort: http
      - path: /result-config
        backend:
            serviceName: resultcfg-svc
            servicePort: http
      - path: /scenario-management
        backend:
            serviceName: scenario-svc
            servicePort: http
      - path: /timeseriesimport
        backend:
            serviceName: timeseries-svc
            servicePort: http
      - path: /
        backend:
            serviceName: webui-svc
            servicePort: http

```

### What did you do?
Setup traefik as ingress controller to rout to our services. The routing works fine for all services except for the WebUI. Due to the structure of our service apis we are using pathprefixstrip'ping.
The WebUI is hosted by npm packages connect (3.4.1) and static-serve (1.11.1) like so: 
```javascript
var connect = require('connect');
var serveStatic = require('serve-static');

connect().use(serveStatic('./dist')).listen(8080, function () {
  console.log('Server running on port 8080 in production mode ...');
});
```

### What did you expect to see?
Accessing my URL at <ip>:80/ I would expect to see our UI come up. 

### What did you see instead?
Instead I see a blank page in browser and 502 http errors while requesting the page:
![error](https://cloud.githubusercontent.com/assets/738953/22182047/6db2cc36-e09b-11e6-875b-dd3a1496eaab.png)

The log from Traefik at debug level shows this:
```
time="2017-01-22T11:01:12Z" level=debug msg="Round trip: http://10.33.0.1:8080, code: 200, duration: 79.02539ms"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
time="2017-01-22T11:01:12Z" level=warning msg="Error forwarding to http://10.33.0.1:8080, err: EOF"
```

Note: The page loads when not using pathprefixstrip as the rule type! In that case our other api's are not reachable though.
