### ISSUE TITLE
Traefik creating backends & mappings for ingress annotated with ingress.class: nginx

### ISSUE THREAD

**Issue by roffe** [containous/traefik#1058]
### What version of Traefik are you using (`traefik version`)?
1.1.2-camembert

### What is your environment & configuration (arguments, toml...)?

Kubernetes 1.5.1

```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: traefik-ingress
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        version: v1.1.2
    spec:
      nodeSelector:
        role: internal-ingress
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik:v1.1.2
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 8080
          hostPort: 8080
        args:
        - --web
        - --kubernetes
        - --logLevel=DEBUG
```

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "false"
  name: communication-fe-test
  namespace: hptest
spec:
  rules:
  - host: notsupposedtolistintraefik.tld
    http:
      paths:
      - backend:
          serviceName: communication-fe
          servicePort: 80
        path: /
```

### What did you expect to see?

No ingress rule in traffic since ingres.class = nginx

### What did you see instead?

![screen shot 2017-01-23 at 15 24 46](https://cloud.githubusercontent.com/assets/5434736/22207629/1f6a92a8-e180-11e6-8c46-06b22dc84c5d.png)
