### ISSUE TITLE
websockets not working when compress = true in toml config.

### ISSUE THREAD

**Issue by JamesKyburz** [containous/traefik#1059]
### What version of Traefik are you using (`traefik version`)?

traefik:v1.1.2-alpine

### What is your environment & configuration (arguments, toml...)?

using docker

toml
```
logLevel = "DEBUG"
debug = true
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/cert.pem"
      KeyFile = "/ssl/cert.key"

[docker]
  domain = "local.awesome.jsmentor.se"
  endpoint = "unix:///var/run/docker.sock"
  exposedbydefault = false
```

docker-compose
```
version: '2'
services:
  ws:
    networks:
      - awesome
    environment:
      - TZ=Europe/Stockholm
      - PORT=5000
    build:
      context: ./src/ws
    labels:
      - "traefik.enable=true"
      - "traefik.backend=machine-ws"
      - "traefik.frontend.rule=Host:local.awesome.jsmentor.se;PathPrefix:/ws"
      - "traefik.frontend.passHostHeader=true"

  proxy:
    networks:
      - awesome
    environment:
      - TZ=Europe/Stockholm
    command: --web
    image: traefik:v1.1.2-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/proxy/traefik-dev.toml:/traefik.toml
      - ./src/proxy/ssl/dev:/ssl
    labels:
      - "traefik.frontend.rule=Host:local.awesome.jsmentor.se;PathPrefixStrip:/dashboard"
    ports:
      - "80:80"
      - "443:443"
      - "9443:9443"

networks:
  awesome:
    driver: bridge
```

### What did you do?

```javascript
var ws = new WebSocket('wss://local.awesome.jsmentor.se/ws')
```

### What did you expect to see?

a succesful update and working websocket connection.

### What did you see instead?

```
WebSocket {url: "wss://local.awesome.jsmentor.se/ws", readyState: 0, bufferedAmount: 0, onopen: null, onerror: null…}
VM234:1 WebSocket connection to 'wss://local.awesome.jsmentor.se/ws' failed: Error during WebSocket handshake: Unexpected response code: 500
```

```
proxy_1    | time="2017-01-23T16:54:44Z" level=warning msg="Unable to hijack the connection: *negroni.responseWriter the ResponseWriter doesn't support the Hijacker interface"
```

If I turn compression off in my toml file everything works. But I want compression :)

My guess is that the gzip middleware processes http upgrade which it shouldn't.

I have been unable to verify if this problem persists using the latest code in master.

New to go, would like to submit a PR if a fix is needed, but need some pointers to get me started.
