### ISSUE TITLE
Traefik should prompt for MTLs client certificates in the browser

### ISSUE THREAD

**Issue by Daniel-dev22** [containous/traefik#10643]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When using `RequireAndVerifyClientCert` traefik doesn't request the certificate from clients such as in the browser. 

I'm not sure if `RequestClientCert` would work to trigger a browser prompt but it's not something I would even consider using because `RequestClientCert` doesn't require and # verify certificates. It simply lets you provide anything or nothing which defeats the purpose of MTLs authentication in my opinion.

Cloudflare for example properly does MTLs prompts and if the client certificate is not provided/not verified you can block the client from accessing the resource. Cloudflare isn't the only service that implements this correctly.

A quick Google search for "browser MTLs prompt" will show what I'm referring to.

Traefik never prompts for a certificate resulting in it failing with `ERR_BAD_SSL_CLIENT_AUTH_CERT`

Similar issues have been posted in the past however for some reason this still hasn't been implemented. Essentially limiting MTLs to server to server communication vs also being compatible with clients such as end user devices.

It's surprisingly hard to find how Cloudflare even does this.

Not sure this is the same thing as the server requesting this since this seems more frontend related and what Cloudflare and others do is not frontend related it happens before frontend connection even occurs.
https://www.electronjs.org/docs/latest/api/app#event-select-client-certificate

Here's how the prompt looks.
![Screenshot_20240419_205422_Key Chain](https://github.com/traefik/traefik/assets/47092714/775be52f-1daf-4bbc-b6d1-4635e0a91e87)

**Comment by emilevauge** [comment]
Hi @Daniel-dev22, thanks for your contribution :). This is an interesting proposal, let's see what the community thinks about it, and depending on the feedback, we might implement an enhancement in the future.

**Comment by Scribing** [comment]
Everything works fine for me with v2.11. You probably have the certificate set incorrectly and need to set it to the intermediate CA that issued the client certificate.

**Comment by Scribing** [comment]
> > Everything works fine for me with v2.11. You probably have the certificate set incorrectly and need to set it to the intermediate CA that issued the client certificate.
> 
> Can you share your MTLs configuration? Are you requiring and verifying the certificate?
> 
> MTLs works for me but doesn't prompt in the browser. I have traefik communicFing to another host running traefik and passing MTLs and it works. But if I try to go to that endpoint in the browser it doesn't prompt so I get the certificate verify failed error in the browser.

This part of the configuration looks like this:

```yaml
tls:
    options:
        default:
            minVersion: VersionTLS12
            sniStrict: true
          
        cert:
            minVersion: VersionTLS12
            sniStrict: true
            clientAuth:
                clientAuthType: RequireAndVerifyClientCert
                caFiles:
                   - /etc/traefik/cert/example.com.crt
             
entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"
        http:
            tls:
                options: cert
                certresolver: letsencrypt
                domains:
                  - main: "example.com"
                    sans:
                      - "*.example.com"
            middlewares:
               - gzip

http:
    routers: 
        foo:
            rule: Host(`example.com`) 
            entryPoints: https
            service: foo

    services: 
        foo:
          loadBalancer:
            servers:
              - url: "http://server-foo:80"
```

It works fine on Chrome and other mobile browsers:
![image](https://github.com/traefik/traefik/assets/58354388/150969a3-209e-45b5-b0ae-b204a20286fe)
