### ISSUE TITLE
Accessing WebUI through PathPrefixStrip frontend returns 404

### ISSUE THREAD

**Issue by davendesai** [containous/traefik#1081]
### What version of Traefik are you using (`traefik version`)?

`Traefik version v1.1.2 built on 2016-12-15`

### What is your environment & configuration (arguments, toml...)?

```yml
traefik:
    container_name: traefik
    image: hypriot/rpi-traefik:latest
    command: --web --docker --docker.domain=rpi.home --logLevel=DEBUG
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/etc/traefik/traefik.toml
    ports:
      - 80:80
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/traefik
      - traefik.port=8080
```

### What did you do?

Try to access the WebUI via Traefik frontend.

### What did you expect to see?

The have the URL http://rpi.home/traefik take me to the WebUI via appending `/dashboard/` - i.e. http://rpi.home/traefik/dashboard/

### What did you see instead?

Instead of appending the subdirectory `/dashboard/` to the current URL, the following HTML is received:
```
<a href="/dashboard/">Found</a>.
```
This breaks the PathPrefixStrip frontend rule and instead directs to http://rpi.home/dashboard/ which results in a 404.
