### ISSUE TITLE
Traefik doesn't detect services when using Docker Swarm, Docker Stack

### ISSUE THREAD

**Issue by peterfraedrich** [containous/traefik#1086]
### What version of Traefik are you using (`traefik version`)?
1.1.2 Camembert

### What is your environment & configuration (arguments, toml...)?
Docker version 1.13.0, build 49bf474 

### What did you do?
When starting traefik using `docker stack deploy app` Traefik is unable to detect any services. 

Debugging revealed in Traefik logs:
```time="2017-01-30T20:51:50Z" level=debug msg="Configuration received from provider docker: {}" 
time="2017-01-30T20:51:50Z" level=info msg="Skipping same configuration for provider docker" 
time="2017-01-30T20:52:05Z" level=debug msg="Filtering container without port and no traefik.port label test_who0" 
time="2017-01-30T20:52:05Z" level=debug msg="Filtering container without port and no traefik.port label test_traefik" 
time="2017-01-30T20:52:05Z" level=debug msg="Filtering container without port and no traefik.port label test_who1" 
```

Ports are not published to the Docker daemon (https://github.com/docker/docker/issues/24304) but are published to the swarm nodes for load balancing. 

### docker-cloud.yaml
```yaml
version: "3.0"

services:
  traefik:
    image: traefik
    networks: 
      - net0
    command: --web --docker.swarmmode --docker.domain=traefik --docker.watch --docker.endpoint=unix://var/run/docker.sock -l DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  who0:
    networks: 
      - net0
    image: jwilder/whoami
    labels:
      - "traefik.backend=who0"
      - "traefik.frontend.rule=PathPrefixStrip:/who0"
      - "traefik.port=80"
    deploy:
      replicas: 1

  who1:
    networks: 
      - net0
    image: jwilder/whoami
    labels:
      - "traefik.backend=who1"
      - "traefik.frontend.rule=PathPrefixStrip:/who1"
      - "traefik.port=80"
    deploy:
      replicas: 1

networks:
  net0:
    driver: overlay
```

**Comment by peterfraedrich** [comment]
Full `Traefik` logfile:
```
time="2017-01-30T20:49:05Z" level=info msg="Traefik version v1.1.2 built on 2016-12-15_10:21:15AM" 
time="2017-01-30T20:49:05Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix://var/run/docker.sock\",\"Domain\":\"traefik\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":true},\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null}" 
time="2017-01-30T20:49:05Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}" 
time="2017-01-30T20:49:05Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix://var/run/docker.sock\",\"Domain\":\"traefik\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":true}" 
time="2017-01-30T20:49:05Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}" 
time="2017-01-30T20:49:05Z" level=info msg="Starting server on :80" 
time="2017-01-30T20:49:05Z" level=debug msg="Docker connection established with docker 1.13.0 (API 1.25)" 
time="2017-01-30T20:49:05Z" level=debug msg="Filtering container without port and no traefik.port label test_who0" 
time="2017-01-30T20:49:05Z" level=debug msg="Filtering container without port and no traefik.port label test_traefik" 
time="2017-01-30T20:49:05Z" level=debug msg="Filtering container without port and no traefik.port label test_who1" 
time="2017-01-30T20:49:05Z" level=debug msg="Configuration received from provider docker: {}" 
time="2017-01-30T20:49:05Z" level=debug msg="Last docker config received more than 2s, OK" 
time="2017-01-30T20:49:05Z" level=info msg="Server configuration reloaded on :80" 
time="2017-01-30T20:49:20Z" level=warning msg="Error checking new version: Get https://update.traefik.io/repos/containous/traefik/releases: dial tcp 104.27.185.74:443: i/o timeout"
```

**Comment by Multiply** [comment]
You didn't expose any ports for your two services it seems.

**Comment by WTFKr0** [comment]
Hi !

In swarm mode, you have to place services labels, and not containers labels.
In compose, this looks like : 
```
  who0:
    networks: 
      - net0
    image: jwilder/whoami
    deploy:
      labels:
        - "traefik.backend=who0"
        - "traefik.frontend.rule=PathPrefixStrip:/who0"
        - "traefik.port=80"
      replicas: 1
```
