### ISSUE TITLE
acme.json in an invalid JSON, Traefik can't read certs

### ISSUE THREAD

**Issue by Clovel** [containous/traefik#10984]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I use Traefik as a Docker container on several servers, with both the Docker Provider and the File Provider working side by side (the File Provider will soon be deprecated). 

Each Traefik container handles about 100 services (websites in their own Docker containers). I use the HTTP challenge.

My configuration works fine, and generates certificates accordingly. The certs are written to the `acme.json` file automatically by Traefik. This is where the problem lies. 

### What did you see instead?

For unknown reasons and at (apparently) random times, Traefik fails to correctly and coimpletely write the certs to the `acme.json` file, resulting in an incomplete ans so invalid JSON file. 

If I `cat` the `acme.json` file, I can clearly see that the file is invalid, like so :

```jsonc
{
  "acmeResolver": {
    "Account": {
      "Email": "[REDACTED]",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:[REDACTED]"
          ]
        },
        "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/[REDACTED]"
      },
      "PrivateKey": "[REDACTED]",
      "KeyType": "4096"
    },
    "Certificates": [
      // For simplicity, only one shown here, but imagine ~100 elements in the array.
      {
        "domain": {
          "main": "[REDACTED]"
        },
        "certificate": "[REDACTED]",
        "key": "someKeyStringThatsRedacted....dISnJVMF
>>EOF

// OBVIOUSLY SOME STUFF IS MISSING HERE
// EOF is indicative, it doesn't appear when using `cat`
```
The cut certificate array element is the $`N`$th one in the array, where $`1 < N < 100`$

I have found no clue to why this occurs. Theories I've come up with up until now are :

- Concurrency issues if Traefik attempts two cert writes simultaneously, or any other concurrency issue
- Traefik crashes during the write process
- Traefik container restarts during the write process

I haven't looked over Traefik's code yet, but if the write process is streamed or chunked, a single sync write to the `acme.json` might fix this. Of course this might cause other issues.

### What version of Traefik are you using?

This issue has occurred over the years since I've updated Traefik from v1.7 to v2.5.
This issue has occurred on v2.5, v2.10 & v2.11.

### What is your environment & configuration?

```yml
log:
  level: ERROR
global:
  checkNewVersion: false
  sendAnonymousUsage: false
api:
  insecure: false
  dashboard: true
  debug: false
ping:
  entryPoint: traefik
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
certificatesResolvers:
  acmeResolver:
    acme:
      email: [REDACTED]
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
      caServer: https://acme-v02.api.letsencrypt.org/directory
defaultEntryPoints:
  - websecure
  - web
  - traefik
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        certResolver: acmeResolver
  traefik:
    address: :8080
```

### If applicable, please paste the log output in DEBUG level

No really obvious log can be found relating to this issue except the "Can't read ACME file" once the issue has occured. 

My Traefik containers are configured to automatically restart on crashes (Docker's `restart: always` policy). Logs often get squashed by repeated crash logs.

**Comment by emilevauge** [comment]
Hi @Clovel,
Is the `acme.json` shared across multiple Traefik instances?
If yes, that's the reason of your issue:
https://doc.traefik.io/traefik/https/acme/#storage
> For concurrency reasons, this file cannot be shared across multiple instances of Traefik.

**Comment by Clovel** [comment]
Hi @emilevauge,

No, the `acme.json` file is not shared across multiple Traefik instances. 

I do have another container reading that file on rare occasions to check if it has been proken or not to restore a backup of the file if necessary, but this bug existed before this feature in my app. This feature is a workaround to fall back on my feet if the `acme.json` file is corrupt. 
Can reading the file cause these concurrency issues ? To read it I use a basic `fs.promises.readFile` call in NodeJS v14 :

```ts
const lACMEFileContents: string = await fs.promises.readFile(
  TRAEFIK_ACME_CONFIG_FILE_PATH,
  {
    encoding: 'utf8',
    flag: 'r',
  },
);
```

I then backup the file as such just in case (mind that this will not be the backup I restore if it is broken) :
```ts
/* Write the ACME file to the backup directory */
await fs.promises.writeFile(
  `${TRAEFIK_ACME_CONFIG_FILE_PATH}.backup`,
  lACMEFileContents,
  {
    encoding: 'utf8',
    flag: 'w',
  },
);
```

Maybe the fact that it is in the same directoy might cause issues ?

Then I try to parse the file, and if it fails I then rewrite it :

```ts
let lParsedACMEFileContents: TraefikACME | null = null;
try {
  lParsedACMEFileContents = JSON.parse(lACMEFileContents) as TraefikACME;
} catch(pException) {
  console.error(`[ERROR] <TraefikManager.backupACMEFile> Failed to parse ACME file contents :`, pException);
  throw pException;
}
```

I only rewrite to the file if it is broken, using a previous backup that is valid.

**Comment by nmengin** [comment]
Hey @Clovel,

Thank you for your feedback.

To move forward on the analysis, we'd like to know if you have an idea of the best way to reproduce the issue and if you could provide a reproducible case (for instance, full Kubernetes manifest to reproduce the issue).

In the meantime, if any community member can help us find verified steps to reproduce and fix the issue if possible, we would love the help.

Thanks in advance.

**Comment by Clovel** [comment]
> To move forward on the analysis, we'd like to know if you have an idea of the best way to reproduce the issue and if you could provide a reproducible case

To be honest, I don't have a reproduction process for this bug. For the moment, it appears to be random (of course it most likely isn't). I haven't found a specific case that causes this issue. 

If I find anything, I'll be sure to update you on this thread. 

> for instance, full Kubernetes manifest to reproduce the issue

I don't use K8s, but raw Docker on Linux (Debian 12). I deploy the various proxied apps via a (containerized) NodeJS app that uses the [Dockerode](https://github.com/apocas/dockerode) library. 

Here is an excerpts of the dynamic configuration (File Provider) : 

```yml
http:
  routers:
    FXw8Xfh7brjjkNo4p:
      rule: Host(`[REDACTED]`,`[REDACTED]`)
      service: FXw8Xfh7brjjkNo4p
      tls:
        certResolver: acmeResolver
        domains:
          - main: [REDACTED]
            sans:
              - [REDACTED]
      middlewares:
        - waf
...
...
  services:
    FXw8Xfh7brjjkNo4p:
      loadBalancer:
        servers:
          - url: http://172.18.0.11:80
...
  middlewares:
    waf:
      plugin:
        traefik-modsecurity-plugin:
          MaxBodySize: 10485760
          # And more redacted variables related to ModSecurity plugin
```

I'd like to point out that all the middleware stuff about ModSecurity was added later. The bug this thread is all about predates these features.
