### ISSUE TITLE
ACME + Docker-compose labels

### ISSUE THREAD

**Issue by AurelienLavorel** [containous/traefik#1099]
### What version of Traefik are you using (`traefik version`)?
````
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:21:15AM
OS/Arch:      linux/amd64
````

### What is your environment & configuration (arguments, toml...)?
1st _docker-compose.yml_
````
version: "2"
services:
  traefik:
    image: traefik:v1.1.2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - ./ssl:/etc/traefik/ssl
      - ./acme:/etc/traefik/acme
    command: --web -c /dev/null  --docker --logLevel=INFO --docker.watch --acme --acme.storage=/etc/traefik/acme/acme.json --acme.email=aurelien@lavoweb.net --acme.entryPoint=https --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443 TLS' --defaultentrypoints=http,https --acme.domains="unstickers.com"
    restart: always
    environment:
      - "affinity:container!=traefik*"
    networks:
      - web
networks:
  web:
    external:
      name: web
````

### What did you do?
2nd _docker-compose.yml_
````
version: "2"
services:
  unstickers:
    image: httpd:2.4-alpine
    expose:
     - 80
     - 443
    volumes:
     - ./data:/usr/local/apache2/htdocs/
    labels:
     - "traefik.port=80"
     - "traefik.backend=unstickers"
     - "traefik.frontend.rule=Host:unstickers.com,www.unstickers.com"
     - "traefik.acme.domains=unstickers.com,www.unstickers.com"
    networks:
     - web
networks:
  web:
    external:
      name: web
````

### What did you expect to see?
Creation of ACME certificate with unstickers.com AND www.unstickers.com.

### What did you see instead?
Creation of ACME certificate with unstickers.com. 

We can't configure ACME certificate outside of the main _docker-compose.yml_ file, it's a design leak.
