### ISSUE TITLE
Incomplete metrics in Traefik v3

### ISSUE THREAD

**Issue by bryanhorstmann** [containous/traefik#11006]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In Traefik v3.1.0, the new `traefik_open_connections` has replaced `traefik_service_open_connections`. But this metric is missing crucial labels. Namely: `exported_service`, `method` and `protocol`.

I've looked at https://github.com/traefik/traefik/issues/10928, but this does not address the missing labels.

### What did you see instead?

`traefik_open_connections` has limited labels:
```traefik_open_connections{container="traefik", endpoint="metrics", entrypoint="web", instance="10.1.204.153:9100", job="traefik-metrics", namespace="ingress", pod="traefik-75d56bbd64-kb62z", protocol="TCP", service="traefik-metrics"}```

### What version of Traefik are you using?

```
→ kubectl exec -it deploy/traefik -- traefik version
Version:      3.1.0
Codename:     comte
Go version:   go1.22.5
Built:        2024-07-15T14:44:04Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Helm `values.yaml`
```yaml
  ports:
    metrics:
      expose:
        default: false

  metrics:
    addInternals: false
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enabled: true
        namespace: ingress
```

Add more configuration information here.
