### ISSUE TITLE
Traefik not respecting file middleware

### ISSUE THREAD

**Issue by Exitium-DEV** [containous/traefik#11079]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created a Traefik container in Docker.

Configured it as follows
```yaml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command: 
      - --api.dashboard
      - --log.level=DEBUG
      - --providers.file.directory=/traefik
      - --providers.file.watch
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=debug@exitium.uk
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 443:443
    networks:
      - traefik-internal
      - traefik-external
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.traefik:/traefik:ro
      - ./.letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`dev.exitium.uk`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))
      - traefik.http.middlewares.traefik.stripprefix.prefixes=/traefik
      - traefik.http.routers.traefik.middlewares=traefik
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.traefik.service=api@internal

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - traefik-internal
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`dev.exitium.uk`) && PathPrefix(`/portainer`)
      - traefik.http.middlewares.portainer.stripprefix.prefixes=/portainer
      - traefik.http.routers.portainer.middlewares=portainer
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.tls.certresolver=myresolver

volumes:
  portainer_data:
    external: true

networks:
  traefik-internal:
    external: true

  traefik-external:
    external: true
```

I then created a coder/code-server service on **the host**, listening on `0.0.0.0:8080`

To direct traffic from https://dev.exitium.uk/code tom the container I enabled the file provider and set the following config
```yaml
http:
  routers:
    vs-code:
      rule: Host(`dev.exitium.uk`) && PathPrefix(`/code`)
      service: vs-code
      middlewares:
        - vs-code
      entrypoints:
        - websecure
      tls:
        certresolver: myresolver

  services:
    vs-code:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8080/
  
  middlewares:
    vs-code:
      stripprefix:
        prefixes:
          - /code
```

As you can see, the file provider follows the exact same format and configuration as the portainer service in the compose.yml

### What did you see instead?

When I visit the domain, I find that I am greeted with "Not found." which indicates that Traefik is successfully directing traffic to the service, but not stripping "/code" from the request. I tested this exact same setup with code-server in a container instead; and found it to work perfectly, ruling out code-server as the issue.

I then went to check the Traefik dashboard and found that everything was green, so I went to "HTTP" -> "Middlewares" -> "vscode@file"

The page did not load.
It turns out that the Traefik dashboard will not show details for services, or middleware created in the file provider; but has no issues with the docker provider. (It can show the general stats and pull data howevers, so it's not a permissions issue)

In summary Traefik is not executing the stripprefix middleware on the file provider, and will not show details of services created in the file provider, on the dashboard.

### What version of Traefik are you using?

Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
http:
  routers:
    vs-code:
      rule: Host(`dev.exitium.uk`) && PathPrefix(`/code`)
      service: vs-code
      middlewares:
        - vs-code
      entrypoints:
        - websecure
      tls:
        certresolver: myresolver

  services:
    vs-code:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8080/
  
  middlewares:
    vs-code:
      stripPrefix:
        prefixes:
          - /code
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

[traefik_logs.txt](https://github.com/user-attachments/files/16968608/traefik_logs.txt)
