### ISSUE TITLE
Does Traefik honour http_proxy for corporate proxies?

### ISSUE THREAD

**Issue by lhaig** [containous/traefik#1110]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:27:40AM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml...)?

Standard traefik toml file with acme enabled
### What did you do?
I tested a connection on http and this worked connecting to the proxied server.
I enabled https and letsencrypt on a separate entrypoint with the staging server

### What did you expect to see?
To get a staging certificate from letsencrypt.

### What did you see instead?
```shell
time="2017-02-03T17:37:02+01:00" level=fatal msg="Error preparing server: get directory at 'https://acme-staging.api.letsencrypt.org/directory': failed to get \"https://acme-staging.api.letsencrypt.org/directory\": Get https://acme-staging.api.letsencrypt.org/directory: dial tcp: lookup acme-staging.api.letsencrypt.org on X.X.X.X:53: no such host"
```
This error is due to their being no access to the internet directly from hosts. we have to use a corporate proxy.

I configured http_proxy and https_proxy within the system environment variables but it seems that the traefik binary does not honour these variables.

**Comment by dtomcej** [comment]
@lhaig Are your hosts externally accessible?

Lets Encrypt uses a TLS challenge to issue certificates, which requires external (separate) TLS access to the client. The bigger question is, does your corporate proxy allow Let's Encrypt access to your binary?

**Comment by lhaig** [comment]
Hi,

Yes the access back is not proxied just the access out.
The request is successful when you use the standard client.

So traefik does not seem to honour the http_proxy environment variables
Thanks

Lance

**Comment by andrejvanderzee** [comment]
Looks like this is still the case :-( 

Will this be solved anytime soon?

**Comment by lhaig** [comment]
I had to go with an Nginx reverse proxy for now until this can be solved.
If I can help with debugging this let me know

**Comment by grealish** [comment]
Bumping Issue as it also block's a deployment i'm working one where they use a outbound http_proxy

**Comment by nmengin** [comment]
Hello @lhaig @andrejvanderzee @grealish .

Many thanks for your interest in our project.

Can you give me more information about your environments? Do you use Traefik directly on the host where you declared your environment variables (`HTTP_PROXY` and `HTTPS_PROXY`) or do you use containers? If you use containers, how do you declare the environment variables?

Indeed, I tam currently trying to reproduce your problem on my own machine but I can't!
I use Traefik directly on my host and I have a Docker environment with boulder and a squid server. 
I added some debug logs into [lego](https://github.com/xenolf/lego/) and apparently the `HTTP_PROXY` and `HTTPS_PROXY` variables are set when it does the HTTP requests...

Many thanks in advance.

**Comment by grealish** [comment]
Hi @nmengin 
After I wrote my message, I anyways included traefik into my docker deployment where `HTTP_PROXY `was set as a `ENV`, intending to use traefik without Lets Encrypt.  
Good news is GoLang HTTP client respects `HTTP_PROXY` variable if it's set before it starts. 

It will be a difficult environment to reproduce, as this customer is using a commercial http proxy that only respects specific HTTPS URL's that are white-listed so, 
from the error messages that sometimes are returned, i'm pretty sure it's this: https://www.mcafee.com/us/products/web-gateway.aspx 

The setup is as simple as this:
```
services:                 
  traefik:                
    build: .              
    command: --logLevel=DEBUG                       
    ports:                
      - "80:80"           
      - "443:443"         
      - "127.0.0.1:8484:8484"                       
    restart: always       
    environment:          
      - HTTP_PROXY=http://proxyoutbound.corp-network.com:8080/                                                    
      - HTTPS_PROXY=http://proxyoutbound.corp-network.com:8080/                                                   
    volumes:              
      - /var/run/docker.sock:/var/run/docker.sock   

```

For now, that makes lego work, i'll provider more feedback if I get traefik up and running fully
