### ISSUE TITLE
Error creating server: listen tcp: unknown port tcp/80

### ISSUE THREAD

**Issue by r0bj** [containous/traefik#1118]
traefik 1.1.2
kubernetes: 1.5.2
docker: 1.12.6

Starting traefik in kubernetes as:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: traefik-ingress-controller
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-controller
    spec:
      nodeSelector:
        k8s-role: k8s-lb
      containers:
      - image: traefik:v1.1.2
        name: traefik-ingress-controller
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: admin
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 20
        args:
        - --defaultentrypoints=http
        - --entrypoints='Name:http Address::80'
        - --kubernetes
        - --web
        - -d
        resources:
          requests:
            cpu: 1
            memory: 30Mi
```

Traefik cannot start due to:
```
time="2017-02-05T15:12:54Z" level=fatal msg="Error creating server: listen tcp: unknown port tcp/80'"
```

Full log:
```
time="2017-02-05T15:12:54Z" level=info msg="Traefik version v1.1.2 built on 2016-12-15_10:21:15AM"
time="2017-02-05T15:12:54Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":true,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80'\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"},\"Mesos\":null}"
time="2017-02-05T15:12:54Z" level=info msg="Preparing server http &{Network: Address::80' TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}"
time="2017-02-05T15:12:54Z" level=info msg="Starting server on :80'"
time="2017-02-05T15:12:54Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}"
time="2017-02-05T15:12:54Z" level=info msg="Starting provider *provider.Kubernetes {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"}"
time="2017-02-05T15:12:54Z" level=debug msg="Kubernetes token:XXX"
time="2017-02-05T15:12:54Z" level=debug msg="Kubernetes CA cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
time="2017-02-05T15:12:54Z" level=debug msg="Using environment provided kubernetes endpoint"
time="2017-02-05T15:12:54Z" level=debug msg="Kubernetes endpoint: https://10.223.0.1:443"
time="2017-02-05T15:12:54Z" level=debug msg="Using label selector: ''"
time="2017-02-05T15:12:54Z" level=fatal msg="Error creating server: listen tcp: unknown port tcp/80'"
```
(kubernetes tokes has been redacted)

Traefik start as expected after options were removed:
```
        - --defaultentrypoints=http
        - --entrypoints='Name:http Address::80'
```
