### ISSUE TITLE
Service name collision

### ISSUE THREAD

**Issue by rtribotte** [containous/traefik#11257]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

While reviewing PR https://github.com/traefik/traefik/pull/11166, we have noticed with @kevinpollet that service names produced by the Kubernetes CRD provider can collide because not taking the specific service configuration (e.g.: the cookie configuration) into account.

In the following example, the Kubernetes Service `whoami` is referenced by multiple resources, and last resource processed by the Kubernetes CRD provider will override any previous service definition produced before:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default

spec:
  ports:
    - name: web
      port: 80

---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: sticky-default
  namespace: default
spec:
  weighted:
    sticky:
      cookie:
        httpOnly: true
        name: cookie
        secure: true
        sameSite: none
        maxAge: 42
    services:
      - name: whoami
        port: 80

---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: sticky
  namespace: default
spec:
  weighted:
    sticky:
      cookie:
        httpOnly: true
        name: cookie
        secure: true
        sameSite: none
        maxAge: 42
        path: /foo
    services:
      - name: whoami
        port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test2.route
  namespace: default

spec:
  entryPoints:
    - web

  routes:
    - match: Host(`traefik-service`)
      kind: Rule
      services:
        - name: sticky
          kind: TraefikService
        - name: sticky-default
          kind: TraefikService

    - match: Host(`k8s-service`)
      kind: Rule
      services:
        - name: whoami
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              secure: true
              sameSite: none
              maxAge: 42
              path: /foo
        - name: whoami
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              secure: true
              sameSite: none
              maxAge: 42
```

### What did you see instead?

-

### What version of Traefik are you using?

v2.11

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
