### ISSUE TITLE
Are there plans to support the service type ExternalName in Kubernetes?

### ISSUE THREAD

**Issue by Regner** [containous/traefik#1142]
### What version of Traefik are you using (`traefik version`)?
traefik:v1.1.2

### What is your environment & configuration (arguments, toml...)?
Kubernetes
```
# traefik.toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
  entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
[acme]
email = "shadowdf@gmail.com"
storageFile = "/acme/acme.json"
entryPoint = "https"
onDemand = true
onHostRule = true
[[acme.domains]]
main = "ctcpredatorfeed.ca"
[[acme.domains]]
main = "regnerba.com"
```

### What did you do?
Point an ingress at a backend service that has a type of ExternalName.
```
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
  - name: https
    port: 443
  type: ExternalName
  externalName: something.regnerba.com  # Google Cloud Storage bucket
```
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: test
spec:
  rules:
    - host: eve.regnerba.com
      http:
        paths:
          - path: /test
            backend:
              serviceName: test
              servicePort: https
```

### What did you expect to see?
My hope was that Traefik would route requests to the external name

### What did you see instead?
These errors:
```
time="2017-02-08T21:03:58Z" level=error msg="Error retrieving endpoints: failed to create endpoints request: GET \"https://10.3.240.1:443/api/v1/namespaces/default/endpoints/test\" : http error 404 GET \"https://10.3.240.1:443/api/v1/namespaces/default/endpoints/test\": \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"endpoints \\\\\\\"test\\\\\\\" not found\\\",\\\"reason\\\":\\\"NotFound\\\",\\\"details\\\":{\\\"name\\\":\\\"test\\\",\\\"kind\\\":\\\"endpoints\\\"},\\\"code\\\":404}\\n\""
```

The errors make sense as I assume Traefik has no understanding that the ExternalName service type is a thing not hosted in the Kube cluster. Mostly just curious if this is something Traefik might potentially support in the future or if it is considered out side the scope of what Traefik is for.
