### ISSUE TITLE
Parsing error on --entryPoints

### ISSUE THREAD

**Issue by yangm97** [containous/traefik#1153]
### What version of Traefik are you using (`traefik version`)?
FROM traefik:latest

### What is your environment & configuration (arguments, toml...)?
docker: 1.13.1
docker-compose: 1.10.0

http://pastebin.com/u6YSnYBM

### What did you do?
Enable SSL

### What did you expect to see?
Traefik routing traffic

### What did you see instead?
When SSL is enabled (uncomment relevant strings from the first docker-compose.yml), rules stop working, as in everything returns 404 and no traffic is routed (either from 443 or 80).

EDIT: Jump to [this comment](https://github.com/containous/traefik/issues/1153#issuecomment-279587316).

**Comment by dtomcej** [comment]
Is this environment publicly accessible? If not, Lets Encrypt will not issue a certificate.

Can you please attach a snippet of the debug logs to show what error the letsencrypt client is returning?

**Comment by yangm97** [comment]
The certificate works fine, the 404 page has the usual green lock on it.

**Comment by yangm97** [comment]
Lines commented (http)
http://pastebin.com/Ga6ZvzpJ

Lines uncommented (https)
http://pastebin.com/d36HzX7i

![screen shot 2017-02-13 at 17 26 13](https://cloud.githubusercontent.com/assets/4412002/22899385/cfcc68be-f211-11e6-927b-938d2701389d.png)

**Comment by dtomcej** [comment]
The error logs that you pasted showed that you did not specify a default entrypoint for your docker containers. Since there are 2 when you enabled https, you need to specify which/or both of them.

Can you try with  "traefik.entrypoints=http, https" on your nginx pod?

**Comment by yangm97** [comment]
Yup, looks like some problem with entrypoints. I tried adding "traefik.entrypoints=http, https" to the nginx service but it didn’t work.

What worked though was setting defaultEntryPoints on traefik service, and adding a space before ' on the http entrypoint, looks like the parser has some problems with the last argument (...`Unknown entrypoint https'"`).

This is working now, although on demand certificates sometimes trows a `server.go:2317: http: TLS handshake error from 187.180.209.182:46515: EOF`.

```
  proxy:
    image: traefik
    command:
      - --acme=true
      - --acme.email=yangm97@gmail.com
      - --acme.entryPoint=https
      - --acme.ondemand=true
      - --acme.storage=/certs/acme.json
      - --defaultEntryPoints=https,http
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=synko.com.br
      - --entryPoints='Name:http Address::80 Redirect.EntryPoint:https '
      - --entryPoints='Name:https Address::443 TLS'
      - --logLevel=DEBUG
      - --web
```
