### ISSUE TITLE
Docker container w. multiple networks, route to wrong IP

### ISSUE THREAD

**Issue by kristoferlundgren** [containous/traefik#1156]
### What version of Traefik are you using (`traefik version`)?
1.1.2 (docker "traefik:latest" as of 20170213)

### What is your environment & configuration (arguments, toml...)?
docker 1.13.1
docker-compose-traefik.yml

```yaml
version: "3"

services:

  traefik:
    image: traefik:latest
    command:
      --web --docker --docker.watch --docker.swarmmode --docker.domain=traefik --logLevel=DEBUG --accesslogsfile=/dev/stdout
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-1:
    image: nginx:latest
    networks:
      - traefik-net
      - db-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=PathStrip:/nginx-1"
        - "traefik.docker.network=traefik-net"

  nginx-2:
    image: nginx:latest
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=PathStrip:/nginx-2"
        - "traefik.docker.network=traefik-net"

  db:
    image: alpine:latest
    networks:
      - db-net
    command:
      sleep 120

networks:
  traefik-net:
    driver: overlay
  db-net:
    driver: overlay
```

### What did you do?
Start a docker service with multiple networks (multiple virtual IPs), one for frontend and one backend network for database connectivity.

```
docker swarm init
docker stack deploy -c docker-compose-traefik.yml traefik
```

### What did you expect to see?
Accessing http://localhost/nginx-1 and http://localhost/nginx-2 should consistently get a web page.

### What did you see instead?
http://localhost/nginx-1 access is not routed to designated network set by "traefik.docker.network=traefik-net". Instead, traffic is routed to wrong virtual IP. No access, i.e. "Gateway Timeout".

Traffic is occasionally directed to the right network, docker log of traefik container includes:
```shell
time="2017-02-12T23:55:44Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-nginx-1\":{\"servers\":{\"server-traefik_nginx-1\":{\"url\":\"http://10.0.1.2:80\" [...]
time="2017-02-12T23:55:59Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-nginx-1\":{\"servers\":{\"server-traefik_nginx-1\":{\"url\":\"http://10.0.0.2:80\" [...]
time="2017-02-12T23:56:14Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-nginx-1\":{\"servers\":{\"server-traefik_nginx-1\":{\"url\":\"http://10.0.1.2:80\" [...]
```

Typing "docker service inspect traefik_nginx-1" reveals (amongst other) the two virtual IPs:
```
[...]
            "VirtualIPs": [
                {
                    "NetworkID": "v6ashuultlonotwo4o4lhx390",
                    "Addr": "10.0.1.2/24"
                },
                {
                    "NetworkID": "507sn1hhj5biksrildthrvgeb",
                    "Addr": "10.0.0.2/24"
                }
[...]
```

**Comment by donnex** [comment]
I'm having the same issue. This problem makes it impossible to use traefik in both prod and dev.

I'm also using multiple networks with Docker and traefik seems to pick a random IP when routing the backend. For example in this docker-compose setup it picked my hard coded IP instead of the IP the container was assigned when joining the traefik_webgateway network.

```
    networks:
      default:
        ipv4_address: 172.26.0.5
      traefik_webgateway:
```

**Comment by SantoDE** [comment]
This is possibly related (and to be fixed by #1171) I guess?

**Comment by kristoferlundgren** [comment]
@donnex, this issue relates to docker services. Happy to see you found the traefik.docker.network= option!

@SantoDE, #1171 does indeed look related. Although the original issue it solves (#979) only mentions setting a default network to connect to. Hopefully the fix also includes actively selecting the network per service as well.

**Comment by zweizeichen** [comment]
I can confirm this issue. Same with Docker `17.03.0-ce`. Setting `traefik.docker.network`on the service's containers has no effect. Traefik seems to pick a random IP each time I start the services, so sometimes it will pick the correct IP and sometimes not. Interestingly this seems to only affect services connected to multiple networks.

**Comment by CyrilPeponnet** [comment]
I'm hitting the same issue but from code I can see

```
			network := networkSettings.Networks[label]
```

If you check your container with inspect the network is prefixed with the stack name. So try with `stack`-`network_name` instead especially if you are using the same stack for both traefik and a container as backend.

In my case I have stack for traefik with:

```
networks:
  backend:
      driver: overlay
```

When deploying the stack with `docker stack deploy -c traefik.yaml proxy` it's named proxy_backend.

On another stack publishing services I have:

```
networks:
  backend:
    driver: overlay
  traefik_backend:
    external:
      name: proxy_backend
  workers:
    external:
      name: workers
```

The service I want to publish have:

```
    networks:
      - traefik_backend
      - backend
      - workers
```

So I added the label `traefik.docker.network=proxy_backend` and it works fine now.
