### ISSUE TITLE
Possible to listen to both www.example.com and example.com?

### ISSUE THREAD

**Issue by polds** [containous/traefik#116]
Using the wildcard subdomain you can listen to `{subdomain: [a-z]+}.example.com`, that however does not also include `example.com`. Is it possible to listen to both?

**Comment by emilevauge** [comment]
@polds, you can add another frontend with `Host` : `example.com`, it should work. Can you confirm ?

**Comment by rogierlommers** [comment]
I'm also having trouble setting this up. I have a backend defined:
```
[backends.mysite]
  [backends.mysite.servers.server1]
  url = "http://127.0.0.1:81"
```

Now I want this backend to be accessable through both mysite.nl and www.mysite.nl. I tried to do this:

```
[frontends.mysite]
backend = "mysite"
passHostHeader = true
  [frontends.mysite.routes.host1]
  rule = "Host"
  value = "www.mysite.nl"
  [frontends.mysite.routes.host2]
  rule = "Host"
  value = "mysite.nl"
```

Unfortunately this does not work, both mysite.nl and www.mysite.nl is resolving in `HTTP/1.1 404 Not Found`. When I remove the 2nd frontend, the first one will work again.

**Comment by emilevauge** [comment]
Hi @polds @rogierlommers, it's seems to be a bug :( Will look at it.

**Comment by hd-deman** [comment]
same bug with consul provider and file provider.

**Comment by hd-deman** [comment]
this is absolutely crazy to create new frontend for each rote, instead  of creating routes for one frontend.

**Comment by emilevauge** [comment]
And this kind of comment makes me wonder why this project is open source and free to use...

**Comment by hd-deman** [comment]
I feel your pain.

**Comment by emilevauge** [comment]
I just tested it using docker backend, and it seems to work (on the latest version):

```sh
$ docker run -d -l traefik.backend=test -l traefik.frontend.rule=Host -l traefik.frontend.value=docker.localhost emilevauge/whoami
$ docker run -d -l traefik.backend=test -l traefik.frontend.rule=Host -l traefik.frontend.value=test.docker.localhost emilevauge/whoami

$ curl -s http://localhost:8080/api/providers | jq .
{
  "docker": {
    "frontends": {
      "\"frontend-Host-test-docker-localhost\"": {
        "routes": {
          "\"route-frontend-Host-test-docker-localhost\"": {
            "value": "test.docker.localhost",
            "rule": "Host"
          }
        },
        "backend": "backend-test"
      },
      "\"frontend-Host-docker-localhost\"": {
        "routes": {
          "\"route-frontend-Host-docker-localhost\"": {
            "value": "docker.localhost",
            "rule": "Host"
          }
        },
        "backend": "backend-test"
      }
    },
    "backends": {
      "backend-test": {
        "loadBalancer": {
          "method": "wrr"
        },
        "servers": {
          "server-cranky_kalam": {
            "url": "http://172.17.0.3:80"
          },
          "server-admiring_cori": {
            "url": "http://172.17.0.2:80"
          }
        }
      }
    }
  }
}


$ curl http://docker.localhost
Hostname: 538097d25c11
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.3
IP: fe80::42:acff:fe11:3
GET / HTTP/1.1
Host: 172.17.0.3:80
User-Agent: curl/7.35.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.0.1.18
X-Forwarded-Host: 172.17.0.3:80
X-Forwarded-Proto: http
X-Forwarded-Server: petiteboite

$ curl http://test.docker.localhost
Hostname: 9fbf1562c1f6
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.2
IP: fe80::42:acff:fe11:2
GET / HTTP/1.1
Host: 172.17.0.2:80
User-Agent: curl/7.35.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.0.1.18
X-Forwarded-Host: 172.17.0.2:80
X-Forwarded-Proto: http
X-Forwarded-Server: petiteboite
```

Using file backend with these rules seems also OK:

```toml
  [backends]
    [backends.backend1]
      [backends.backend1.LoadBalancer]
        method = "wrr"
      [backends.backend1.servers.server1]
      url = "http://172.17.0.2:80"
      weight = 1

  [frontends]
    [frontends.frontend1]
    backend = "backend1"
      [frontends.frontend1.routes.test_1]
      rule = "Host"
      value = "localhost"
    [frontends.frontend2]
    backend = "backend1"
      [frontends.frontend2.routes.test_1]
      rule = "Host"
      value = "test.localhost"
```

```sh
$ curl http://localhost
Hostname: 9fbf1562c1f6
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.2
IP: fe80::42:acff:fe11:2
GET / HTTP/1.1
Host: 172.17.0.2:80
User-Agent: curl/7.35.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: 172.17.0.2:80
X-Forwarded-Proto: http
X-Forwarded-Server: petiteboite

$ curl http://test.localhost
Hostname: 9fbf1562c1f6
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.2
IP: fe80::42:acff:fe11:2
GET / HTTP/1.1
Host: 172.17.0.2:80
User-Agent: curl/7.35.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.0.1.18
X-Forwarded-Host: 172.17.0.2:80
X-Forwarded-Proto: http
X-Forwarded-Server: petiteboite
```

Could you give more info on your conf? Could you test using my exemple?
