### ISSUE TITLE
traefik doesn't register itself into the list of kubernetes controllers

### ISSUE THREAD

**Issue by r0bj** [containous/traefik#1165]
traefik: 1.1.2
kubernetes: 1.5.2
OS: ubuntu 14.04

Running traefik from:
```yml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: traefik-ingress-controller
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-controller
    spec:
      nodeSelector:
        k8s-role: k8s-lb
      containers:
      - image: traefik:v1.1.2
        name: traefik-ingress-controller
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: admin
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 20
        args:
        - --kubernetes
        - --web
        resources:
          requests:
            cpu: 1
            memory: 30Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: traefik-ingress-controller
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  ports:
  - port: 8080
    name: web
    targetPort: 8080
  - port: 80
    name: entrypoint
    targetPort: 80
  selector:
    k8s-app: traefik-ingress-controller
  externalIPs:
  - 10.8.34.110
  - 10.8.40.111
```

Traefik starts, creates frontends, backends from kubernetes API but doesn't register itself into the list of kubernetes controller via API service. There is no entry in etcd store under `/registry/controllers`:
```
etcdctl --ca-file /var/lib/kubernetes/etcd-ca.pem ls /registry/controllers/kube-system
```

It should probably do something like nginx-ingress-controller:
```
etcdctl --ca-file /var/lib/kubernetes/etcd-ca.pem ls /registry/controllers/kube-system
/registry/controllers/kube-system/default-http-backend
/registry/controllers/kube-system/nginx-ingress-controller
```

Without registration in the list of k8s controllers commands like `kubectl describe ing` can't fill fields with data related to IP addresses of ingress controllers, events, etc.

In case of using nginx-ingerss-controller there is valid content in address fields:
```
# kubectl describe ing nginx
Name:			nginx
Namespace:		ops
Address:		10.8.76.162,10.8.70.128,10.8.70.128
[...]
```

And also it isn't quite kubernetes compliant.
