### ISSUE TITLE
Fast proxy upload issues with TUS chunked upload

### ISSUE THREAD

**Issue by Daniel-dev22** [containous/traefik#11664]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I use [filebrowser](https://github.com/filebrowser/filebrowser) behind Traefik on multiple instances with the same configuration except for fast proxy.

I noticed on the 2 with fast proxy enabled I'm unable to upload files. The 2 with it disabled I can upload files.
```
experimental:
  fastProxy: {}
```

Filebrowser uses TUS so I assume there might be an issue with the fast proxy implementation and TUS?

### What did you see instead?

Files were unable to be uploaded when fast proxy is enabled using TUS.

### What version of Traefik are you using?

3.3.1

### What is your environment & configuration?

```yaml
api: {insecure: true}
certificatesResolvers:
  le:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers: ['1.1.1.1:53', '8.8.8.8:53']
      email: email.com
      storage: /letsencrypt/acme.json
entryPoints:
  adguard-ingress:
    address: 192.168.10.2:3000
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  cameras-ingress:
    address: 192.168.10.2:6000
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  dns:
    address: :53/tcp
    forwardedHeaders:
      trustedIPs: [192.168.10.0/24, 192.168.128.0/24]
  dns-dot:
    address: 192.168.8.11:853
    proxyProtocol:
      trustedIPs: [192.168.8.0/24]
  dns-udp:
    address: :53/udp
    forwardedHeaders:
      trustedIPs: [192.168.10.0/24, 192.168.128.0/24]
  eda-ingress:
    address: 192.168.10.2:9331
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  glinet-api:
    address: 192.168.10.2:7080
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  glinet-ssh: {address: '192.168.10.2:23'}
  iot-network-websecure:
    address: 192.168.4.2:443
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  mqtt-ingress:
    address: 192.168.10.2:8443
    transport:
      respondingTimeouts: {idleTimeout: 90s}
  ping:
    address: 192.168.8.11:8081
    proxyProtocol:
      trustedIPs: [192.168.8.0/24]
  portainer-ingress:
    address: 192.168.10.2:9443
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  sonos-network-websecure:
    address: 192.168.14.50:443
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
  vip-ingress:
    address: 192.168.8.11:443
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
    http3: {}
    proxyProtocol:
      trustedIPs: [192.168.8.0/24]
  vip-ingress-health-check:
    address: 192.168.8.11:80
    proxyProtocol:
      trustedIPs: [192.168.8.0/24]
  web: {address: '192.168.10.2:80'}
  websecure:
    address: 192.168.10.2:443
    http:
      tls:
        certResolver: le
        domains:
        - main: domain.com
          sans: ['*.domain.com']
    http3: {}
    proxyProtocol:
      trustedIPs: [192.168.8.0/24]
experimental:
  fastProxy: {}
log: {level: DEBUG}
ping: {manualrouting: true}
providers:
  docker: {exposedByDefault: false, network: traefik-network}
  file: {directory: /etc/traefik/dynamic_configuration}

```

Add more configuration information here.
