### ISSUE TITLE
Incorrect Case in Documentation for IngressRoute accessLogs

### ISSUE THREAD

**Issue by neilclark-bgn** [containous/traefik#11726]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using Traefik Proxy version v3.3.6 deployed via Helm chart version 35.0.1. 

I decided to test out the new IngressRoute observability by adding the following to an IngressRoute as per the documentation [here](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute).

```
    observability:
      accesslogs: false
      metrics: true
      tracing: true
```

### What did you see instead?

The IngressRoute failed to apply with an error as follows:

strict decoding error: unknown field "spec.routes[0].observability.accesslogs"

This looks to be as simple as the documentation specifies accesslogs, but the CRD expects accessLogs (capital L).

### What version of Traefik are you using?

v3.3.6

### What is your environment & configuration?

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/ingressprovider: traefik.traefik
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`^.+\.example\.net$`) && PathPrefix(`/oauth2/`)
    services:
    - name: oauth2-proxy
      port: 80
    middlewares:
      - name: oauth2-proxy-auth-headers
    observability:
      accesslogs: false
      metrics: true
      tracing: true
  tls: {}
```

Add more configuration information here.
