### ISSUE TITLE
Slower Container Local Network Access with Traefik

### ISSUE THREAD

**Issue by thebigjoe1** [containous/traefik#11730]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm soley using Traefik to route traffic to internal container IPs based on subdomains. I use AdGuard Home for DNS rewrites, directing those subdomains to Traefik's container IP. My Traefik configuration appears to be working for basic routing, as confirmed by successful routing to several containers now routing internally via Traefik. I can ping the subdomains, and they resolve to Traefik's IP with very low latency (<1ms) compared to those not managed by Traefik.

### What did you see instead?

While basic routing and DNS resolution work, I've observed slower download/upload speeds when transferring large files to/from containers via the Traefik-managed subdomains compared to accessing the containers directly using their internal IP and port. The speed is better than before Traefik, but still significantly slower than a direct connection.

### What version of Traefik are you using?

3.3.6

### What is your environment & configuration?

Deployment: Docker Compose
Traefik Docker Compose: 
Provider: Docker
Platform: ArchLinux

```yaml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true" # Enable the Traefik dashboard (for local access only, secure it later if needed)
      - "--providers.docker=true" # Enable Docker provider
      - "--providers.docker.exposedbydefault=false" # Don't expose all containers by default
      - "--entrypoints.web.address=:80" # HTTP entrypoint
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint (even if Cloudflare handles SSL externally)
      - "--providers.redis=true" # Enable Redis provider
      - "--providers.redis.endpoints=traefik-redis:6379"
      - "--providers.redis.rootKey=traefik"
    ports:
      - "7480:80" # Host port 80 forwarded to container port 80
      - "7443:443" # Host port 443 forwarded to container port 443
      - "8880:8080" # Host port 8080 forwarded to the Traefik dashboard (for local access)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Allow Traefik to listen to Docker events

    networks:
      - traefik-net

  redis:
    image: redis:alpine
    container_name: traefik-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"  # Publish Redis on the host
    networks:
      - traefik-net
      
networks:
  traefik-net:
    name: traefik-net

volumes:
  redis-data:
```

**Comment by rtribotte** [comment]
Hi @thebigjoe1,

Thanks for reporting this!

Can you please provide us with a reproducible case, as well as more specifics on the overhead you were able to conclude?

**Comment by thebigjoe1** [comment]
Ill do my best. 

For example, Immich. Here is part of my docker-compose.yml that contains traefik labels:
```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-network
      - traefik-net
    labels:
      - "traefik.enable=true" 
      # HTTP
      - "traefik.http.routers.immich-http.rule=Host(`immich.domain.com`)"
      - "traefik.http.routers.immich-http.entrypoints=web"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.immich-http.middlewares=https-redirect@docker" 
      
      # HTTPS
      - "traefik.http.routers.immich-https.rule=Host(`immich.domain.com`)"
      - "traefik.http.routers.immich-https.entrypoints=websecure"
      - "traefik.http.routers.immich-https.tls=true"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
```
Now, if i connect to immich.domain.com, and upload or download a picture or video while on a device on my internal network, it of course works, and faster then prior to traefik implementation. But if i use the direct internal ip address and port, it is significantly faster. 
Pings to immich.domain.com return traefiks container's ip address, and show latency of <1 ms. Prior to traefik internally using my domain, id see 30-50ms. Again, routing seems to work just fine, but the speeds while improved, are nowhere near what they should be. 

I hope that makes sense.
