### ISSUE TITLE
Swarm Mode + Letsecrypt + KV Store

### ISSUE THREAD

**Issue by Berndinox** [containous/traefik#1176]
### What version of Traefik are you using (`traefik version`)?
traefik:latest

### What is your environment & configuration (arguments, toml...)?
3 Node Swarm Cluster (Docker 1.13 - Swarm Mode)
```
version: "3"
 
services:
  traefik:
    image: traefik
    command: --web --docker --docker.swarmmode --docker.domain=docker.localhost --docker.watch --logLevel=WARN --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --acme.entryPoint=https --acme.email=admin@MYDOMAIN.at --acme.storage=/etc/traefik/acme/acme.json --acme.domains=MYDOMAIN.at --acme.ondemand=true --acme.onhostrule=true
    networks:
      - proxy
      - consul
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefikdata:/etc/traefik/acme
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  traefikdata:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/glusterfs/docker/proxy/
```

### What did you do?
Would like to store config into the Consul Cluster, cause with a local shared volume i'm not able to scale traefik.

Tried with appending the followong commands to the compose (above):
`--consul --consul.endpoint=consul:8500 storeconfig`

As descripte here: https://docs.traefik.io/user-guide/kv-config/#store-configuration-in-key-value-store
you have to specify **acme.storage & acme.storagefile** 

So i put the .acme path under acme.storageFile and changed to acme.storage="traefik/acme/account".

### What did you expect to see?
Letsencrypt Certificates in the KV Cluster, so that i can scale the traefik service

### What did you see instead?
`Error here : unknown flag: --acme.storagefile`
I'm not able to specify storage file, so i just can point to the .acme file with acme.storage=, but then the storage location for the KV Store is missed.

Is there a straight forward way to scale Traefik on Docker Swarm Mode (+Letsencrypt)
How can i upload the certs?

Thanks BR
