### ISSUE TITLE
Set default mirroring percentage to 100

### ISSUE THREAD

**Issue by SkytAsul** [containous/traefik#11818]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Following up the discussion on #11781 

Create a `mirroring` service with some mirrors and do not set explicit `percent` values. One would expect that all traffic would be mirrored to the mirrors.

### What did you see instead?

No traffic is mirrored because the default value of the `mirror` option is 0.

In the next major version, the default value should be changed to 100.

### What version of Traefik are you using?

3.3.6

### What is your environment & configuration?

```yaml
http:
  services:
    myservice-mirroring:
      mirroring:
        service: myservice
        mirrors:
        - mirror1
```
