### ISSUE TITLE
Feature Request - Kubernetes Ingress Rewrite to https

### ISSUE THREAD

**Issue by tsupertramp** [containous/traefik#1181]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
Kubernetes, Ingress, AWS, ELB

### What did you do?
Create a working ingress controller which forwards http/https traffic to some docker container running in Kubernetes. Everything worked really great. First of all thanks for your great tool!

### What i would like to do?
I would like to be able to add a rewrite from http to https. Maybe something like this.
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana.ivx.cloud
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/ingress.rewrite-to-https: "true"
spec:
  rules:
  - host: kibana.ivx.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
```

Elb is not capable to rewrite from http to https.

Or am i capable to do this already with some tricks? :)

Greetings, Thomas
