### ISSUE TITLE
`{url}` placeholder in customErrors middleware is only writing the `/path` portion of the requested URL during substitution (but full URL expected)

### ISSUE THREAD

**Issue by geudrik** [containous/traefik#11829]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### tl;dr Jun 16 2025
The CustomErrors middleware `{url}` placeholder in the `query:` spec, does _not_ replace with the full request URL. It only replaces with the request path (the scheme and hostname portions are missing). 

### What did you do?

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-catch-auth-error
spec:
  errors:
    status:
      - "401-403"
    statusRewrites:
      "401": 302
      "403": 302
    query: "/oauth2/start?rd={url}"
    service:
      name: oauth2-proxy
      namespace: traefik
      port: 80
```

This results in calls being made to only the path portion of the original requested URL. 

For example, `curl https://whoami.domain.com/api` -> `"/oauth2/start?rd=%2Fapi"` In this case, the substituted placeholder `{url}` is being replaced with `%2Fapi`, instead of the expected `https%3a%2f%2fwhoami.domain.com%2fapi`

Either the placeholder needs renaming to `{path}` and the docs updated accordingly (if the functionality is as intended), or the logic needs to be fixed to actually URL encode the entire URL being requested (what I hope is the intent here)

Functionality was introduced by @tomMoulard at https://github.com/traefik/traefik/commit/ae6e84414360a8ac2aac488349cdbceaf2bf12b2

### What did you see instead?

Only the `path` is being URL encoded, not the `url`

### What version of Traefik are you using?

3.4.1

```
traefik-b6bc779d4-g82fl traefik {"level":"info","version":"3.4.1","time":"2025-06-10T16:45:47Z","message":"Traefik version 3.4.1 built on 2025-05-27T12:45:16Z"}
```

### What is your environment & configuration?

k8's

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-catch-auth-error
spec:
  errors:
    status:
      - "401-403"
    statusRewrites:
      "401": 302
      "403": 302
    query: "/oauth2/start?rd={url}"
    service:
      name: oauth2-proxy
      namespace: traefik
      port: 80
```

### If applicable, please paste the log output in DEBUG level

`curl -v https://whoami.domain.com/api`

```
traefik-685c8f6d5b-95v5c traefik {"level":"debug","providerName":"kubernetescrd","time":"2025-06-10T16:53:57Z","caller":"github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/kubernetes.go:179","message":"Skipping Kubernetes event kind *v1.ConfigMap"}
traefik-685c8f6d5b-95v5c traefik {"level":"debug","entryPointName":"websecure","time":"2025-06-10T16:54:01Z","caller":"github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:456","message":"IP X.X.X.X is not in trusted IPs list, ignoring ProxyProtocol Headers and bypass connection"}
traefik-685c8f6d5b-95v5c traefik {"level":"debug","middlewareName":"traefik-forward-auth-without-redirect@kubernetescrd","middlewareType":"ForwardAuth","time":"2025-06-10T16:54:02Z","caller":"github.com/traefik/traefik/v3/pkg/middlewares/auth/forward.go:230","message":"Remote error http://oauth2-proxy.traefik.svc.cluster.local/oauth2/auth. StatusCode: 401"}
traefik-685c8f6d5b-95v5c traefik {"level":"debug","middlewareName":"traefik-forward-auth-catch-auth-error@kubernetescrd","middlewareType":"CustomError","time":"2025-06-10T16:54:02Z","caller":"github.com/traefik/traefik/v3/pkg/middlewares/customerrors/custom_errors.go:120","message":"Caught HTTP Status Code 401 (rewritten to 302), returning error page"}
traefik-685c8f6d5b-95v5c traefik {"level":"debug","time":"2025-06-10T16:54:02Z","caller":"github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:173","message":"Service selected by WRR: http://10.109.0.2:4180"}
traefik-685c8f6d5b-95v5c traefik {"ClientAddr":"X.X.X.X:1739","ClientHost":"X.X.X.X","ClientPort":"1739","ClientUsername":"-","DownstreamContentSize":419,"DownstreamStatus":302,"Duration":4739117,"OriginContentSize":419,"OriginDuration":1660237,"OriginStatus":302,"Overhead":3078880,"RequestAddr":"whoami.domain.com","RequestContentSize":0,"RequestCount":2,"RequestHost":"whoami.domain.com","RequestMethod":"GET","RequestPath":"/api","RequestPort":"-","RequestProtocol":"HTTP/2.0","RequestScheme":"https","RetryAttempts":0,"RouterName":"websecure-traefik-whoami-83aea900ea66000e7d84@kubernetescrd","ServiceAddr":"10.109.0.2:4180","ServiceName":"traefik-forward-auth-catch-auth-error-errorpage-service@kubernetescrd","ServiceURL":"http://10.109.0.2:4180","StartLocal":"2025-06-10T16:54:02.018316219Z","StartUTC":"2025-06-10T16:54:02.018316219Z","TLSCipher":"TLS_CHACHA20_POLY1305_SHA256","TLSVersion":"1.3","entryPointName":"websecure","level":"info","msg":"","time":"2025-06-10T16:54:02Z"}
```

The `oauth2-proxy` logs then show the following two calls

```
│ oauth2-proxy-6c5d49df77-2r684 oauth2-proxy X.X.X.X - c2a5406a-a26e-4ae5-8503-e28863121f40 - - [2025/06/10 16:38:24] whoami.domain.com GET - "/oauth2/auth" HTTP/1.1 "curl/8.7.1" 401 13 0.000                                              │
│ oauth2-proxy-6c5d49df77-2r684 oauth2-proxy X.X.X.X - 6d0cd84f-a520-4f77-8007-0886c15c80b8 - - [2025/06/10 16:38:24] whoami.domain.com GET - "/oauth2/start?rd=%2Fapi" HTTP/1.1 "curl/8.7.1" 302 419 0.000  
```

**Comment by geudrik** [comment]
Here are all three middlewares that are in play

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-with-redirect
spec:
  chain:
    middlewares:
    - name: forward-auth-catch-auth-error
      namespace: traefik
    - name: forward-auth-without-redirect
      namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-without-redirect
spec:
  forwardAuth:
    address: "http://oauth2-proxy.traefik.svc.cluster.local/oauth2/auth"
    trustForwardHeader: true
    preserveLocationHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
---
# This middleware actually catches a 401 or 403 from forward-auth-without-redirect
# and changes the status to a 302, along with the redirect info from oauth2-proxy
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-catch-auth-error
spec:
  errors:
    status:
      - "401-403"
    statusRewrites:
      "401": 302
      "403": 302
    query: "/oauth2/start?rd={url}"
    service:
      name: oauth2-proxy
      namespace: traefik
      port: 80
```

And here's the `IngressRoute` def

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`whoami.domain.com`)
    kind: Rule
    middlewares:
    - name: forward-auth-with-redirect
      namespace: traefik
    services:
    - name: whoami
      port: 80
```

Is this issue possibly a collision somewhere with the chaining where the original request is being mutated?

**Comment by nmengin** [comment]
Hey @geudrik,

Thanks for the bug report.
If any community member can help us find verified steps to reproduce and fix the issue, if possible, we would love the help.

**Comment by geudrik** [comment]
I've done this twice now. Deploy a forward auth as you see fit - I'm using oauth2-proxy (or just use whoami's `/health` route to return a 401 on request and update the middleware accordingly - all we need is a 401 returned on request to ensure the errors middleware has something to catch). Ensure the whoami service is deployed with ingress routes (see manifest below). Then use the three Middlewares and IngressRoute as outlined https://github.com/traefik/traefik/issues/11829#issuecomment-2960056451 to see the issue.

I'm using the following values file for deployment of Traefik (Helm Chart Version 35.4.0)
```yaml
.TrustedIPs: &TrustedIPs
  - 127.0.0.1/32
  - 10.108.0.0/16  # DO VPC IP Space
  - 100.0.0.0/8  # CG-NAT space

image:
  tag: "3.4"

podSecurityContext:
  fsGroup: 65532

deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/traefik/traefik-helm-chart/issues/396
    - name: volume-permissions
      image: busybox:latest
      command: [ "sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json" ]
      volumeMounts:
        - name: data
          mountPath: /data

logs:
  general:
    format: "json"  # common or json
    level: "INFO"
    noColor: true
  access:
    enabled: true
    format: "json"
    bufferingSize: 50

env:
  - name: DO_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: do-dns
        key: token

certificatesResolvers:
  letsencrypt:
    acme:
      email: "noreply@domain.com"
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 5
      storage: /data/acme.json

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowEmptyServices: true
    publishedService:
      enabled: true

service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations:
    # Ref: https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/
    service.beta.kubernetes.io/do-loadbalancer-type: "REGIONAL_NETWORK"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"

  spec:
    externalTrafficPolicy: Cluster

persistence:
  enabled: true
  size: 1Gi

globalArguments:
  - "--global.checknewversion=true"

ingressRoute:
  dashboard:
    enabled: true

healthcheck:
  enabled: false

ports:
  metrics: null

  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
    forwardedHeaders:
      trustedIPs: *TrustedIPs
    proxyProtocol:
      trustedIPs: *TrustedIPs

  websecure:
    middlewares: [ ]
    allowACMEByPass: false
    forwardedHeaders:
      trustedIPs: *TrustedIPs
    proxyProtocol:
      trustedIPs: *TrustedIPs
    tls:
      enabled: true
      certResolver: "letsencrypt"
      domains:
        - main: "domain.com"
          sans:
            - "*.domain.com"
```

My test WhoAmI manifests are

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`whoami.domain.com`)
    kind: Rule
    middlewares:
    - name: forward-auth-with-redirect
      namespace: traefik
    services:
    - name: whoami
      port: 80
```

Then, the important middleware is the third one here: https://github.com/traefik/traefik/issues/11829#issuecomment-2960056451 This middleware catches a 401 and calls and constructs a URL to `{define service}/oauth2/start?rd={url}`. The important part to pay attention to is whatever the `{url}` placeholder gets changed to. It should be the entire URL encoded request URL, not just the path portion.

I believe the code logic is https://github.com/traefik/traefik/blob/b39ee8ede5b64e7e1c6e78c276b79d3dd13e7a34/pkg/middlewares/customerrors/custom_errors.go#L130 but in theory that _should_ work as expected, which leads me to suspect that `req.URL` is being clobbered somewhere before this middleware actually gets called. Not knowing enough about how the dynamic middlewares are chained together internally though makes further troubleshooting difficult.
