### ISSUE TITLE
Do not reload when rules.toml file is changed

### ISSUE THREAD

**Issue by James-Dao** [containous/traefik#1183]
### What version of Traefik are you using (`traefik version`)?
Traefik version v1.1.2 built on 2016-12-15_10:21:15AM"

### What is your environment & configuration (arguments, toml...)?
OS: UBUNTU16.04 
Docker: 1.13
docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml -v $PWD/rules.toml:/etc/traefik/rules.toml traefik

traefik.toml
```toml
debug = true
traefikLogsFile = "log/traefik.log"
accessLogsFile = "log/access.log"

[web]
address = ":8080"

################################################################
# File configuration backend
################################################################

[file]
filename = "/etc/traefik/rules.toml"
watch = true 
```
rules.toml
```toml
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://192.168.2.168:8081"
    weight = 2
    [backends.backend1.servers.server2]
    url = "http://192.168.2.168:8082"
    weight = 1
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://192.168.2.168:8084"
    weight = 1
    [backends.backend2.servers.server2]
    url = "http://192.168.2.168:8085"
    weight = 2

[frontends]
  [frontends.frontend1]
  backend = "backend2"
  entrypoints = ["http"]
    [frontends.frontend1.routes.test]
    rule = "Host:test0.localhost"
  [frontends.frontend2]
  backend = "backend1"
  entrypoints = ["http"]
    [frontends.frontend2.routes.test]
    rule = "Host:test1.localhost"
```

### What did you do?
test  reload rules when rules.toml file is changed

### What did you expect to see?
should reload when rules.toml file is changed

### What did you see instead?
do not reload when rules.toml file is changed
