### ISSUE TITLE
Traefik stops working when Nextcloud iOS app connects (setsockopt: operation not supported)

### ISSUE THREAD

**Issue by Chartman123** [containous/traefik#11869]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Since the last update to 3.4.3, traefik crashes multiple times a day. I can't say if there were some other updates involved, too.

Having a look at the logs, this is what I see:

```
2025-06-29T16:38:07+02:00 ERR error="set tcp 172.18.0.16:443->80.187.71.29:31600: setsockopt: operation not supported" entryPointName=websecure

2025-06-29T16:38:07+02:00 ERR Error while starting server error="set tcp 172.18.0.16:443->80.187.71.29:31600: setsockopt: operation not supported" entryPointName=websecure

2025-06-29T16:38:07+02:00 ERR Error while starting server error="set tcp 172.18.0.16:443->80.187.71.29:31600: setsockopt: operation not supported" entryPointName=websecure
```

There's nothing more in the logs.

### What did you see instead?

Opening any URL that is served through traefik can't be reached anymore.

### What version of Traefik are you using?

v3.4.3

### What is your environment & configuration?

traefik.yml

```yaml
api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs: 
        - "10.0.0.0/8"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik_default"
  file:
    filename: "./dynamic_conf.yml"

certificatesResolvers:
  le:
    acme:
      email: info@tsmd.de
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

```

dynamic_conf.yml

``` yaml
tls:
  options:
    default:
      minVersion: VersionTLS12

      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

      curvePreferences:
        - CurveP521
        - CurveP384

      sniStrict: true


http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```

Traefik is running in a docker swarm environment

### If applicable, please paste the log output in DEBUG level

Nothing relevant/related in the debug logs.
