### ISSUE TITLE
Set gateway timeout

### ISSUE THREAD

**Issue by rafilkmp3** [containous/traefik#1187]
### What version of Traefik are you using (`traefik version`)?

v1.1.2 / camembert

### What is your environment & configuration (arguments, toml...)?

```toml
# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

# https is the default
[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "daniel@xxxxcinio.com"
storage = "acme.json" # or "traefik/acme/account" if using KV store
entryPoint = "https"
onDemand = false
OnHostRule = true


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "xxxxrocinio.com"
watch = true
exposedbydefault = false
```

### What did you do?

i have a app with long response time like a 300 seconds

but i cant find a place where a i can set this timeout in documentation

### What did you expect to see?

app waits forever

### What did you see instead?

geteway timeout
