### ISSUE TITLE
Serve based on default domain in kubernetes like in consulcatalog?

### ISSUE THREAD

**Issue by deitch** [containous/traefik#1195]
### What version of Traefik are you using (`traefik version`)?
1.1.2 (docker image)

### What is your environment & configuration (arguments, toml...)?
kubernetes, default, `--kubernetes --web`

### What did you do?
Run as a kubernetes ingress controller

### What did you expect to see?
Enable flexible parent domain like with consul-catalog

In consul catalog mode, I can set `consulcatalog.domain=foo.mydomain.com`, and every service that is registered will be a sub of that service. Registering service `bar` means traefik will serve `bar.foo.mydomain.com`.

In kubernetes (and some others) it doesn't do that. Rather, if using the `host: ` rule in the Ingress, it just treats the value of `host: ` as absolute.

Is there a way to get it to say, "I have been configured with a parent domain, so all host will be subdomains of the parent", similar to how consul does it?

Technically, kubernetes ingress _do_ support wildcard, but only as the subdomain, not the parent.

The use case: portable configs. If I put the entire parent domain in my config, my config file no longer is portable across deployments, unlike my container app deploys. I would prefer to configure my Ingress as just `host: myservice`, and Traefik itself in one of two modes:

1. `--traefik.domain=some.domain.com` which would cause traefik to match  `myservice.some.domain.com`
2 .`--traefik.domain='*'` which would cause traefik to match `myservice.<anything>`

Traefik can make apps and configs highly portable.

**Comment by deitch** [comment]
Any thoughts?

**Comment by deitch** [comment]
FYI, I overrode the `kubernetes.tmpl` to get it to do what I wanted. I don't love it, but it works.

**Comment by tylerjl** [comment]
Hey @deitch, do you happen to have an example that implements what you're describing? I had a similar question when I moved from consul catalog over to kubernetes and am looking for a similar solution to get that behavior in kubernetes (automatically routing to an app name as a subdomain).

**Comment by deitch** [comment]
@tylerjl sure. I tried to do a wildcard like `mysub.*`, but kube's ingress rejects that as invalid. So instead I defined a string that would be treated as wildcard. In my case, `anyrootdomain123`. If that appears on the Ingress, it is replaced as `*`, so `mysub.anyrootdomain123` becomes `mysub.*`. Here is my template override:

```yml
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-tmpl
  namespace: kube-system
data:
  kubernetes.tmpl: |-
    [backends]{{range $backendName, $backend := .Backends}}
        {{if $backend.CircuitBreaker}}
        [backends."{{$backendName}}".circuitbreaker]
          expression = "{{$backend.CircuitBreaker.Expression}}"
        {{end}}
        [backends."{{$backendName}}".loadbalancer]
          method = "{{$backend.LoadBalancer.Method}}"
          {{if $backend.LoadBalancer.Sticky}}
              sticky = true
          {{end}}
        {{range $serverName, $server := $backend.Servers}}
        [backends."{{$backendName}}".servers."{{$serverName}}"]
        url = "{{$server.URL}}"
        weight = {{$server.Weight}}
        {{end}}
    {{end}}

    [frontends]{{range $frontendName, $frontend := .Frontends}}
      [frontends."{{$frontendName}}"]
      backend = "{{$frontend.Backend}}"
      priority = {{$frontend.Priority}}
      passHostHeader = {{$frontend.PassHostHeader}}
        {{range $routeName, $route := $frontend.Routes}}
        [frontends."{{$frontendName}}".routes."{{$routeName}}"]
        {{ $rulewithreplace := replace $route.Rule 'anyrootdomain123' '{subdomain:.*}' }}
        rule = "{{ replace $rulewithreplace 'Host:' 'HostRegexp:' }}"
        {{end}}
    {{end}}
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    name: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --kubernetes.filename=/etc/traefik/kubernetes.tmpl
      volumeMounts:
         - name: traefik-tmpl
           mountPath: /etc/traefik/kubernetes.tmpl
            readOnly: true
  volumes:
     - name: traefik-tmpl
       configMap:
         name: traefik-tmpl
         items:
         - key: kubernetes.tmpl
           path: kubernetes.tmpl
```
