### ISSUE TITLE
Rancher provider does not work when configured to use environment agent role

### ISSUE THREAD

**Issue by kelchm** [containous/traefik#1221]
### What version of Traefik are you using (`traefik version`)?
Traefik v1.2.0-rc2 / morbier
Rancher v1.4.1

### What is your environment & configuration (arguments, toml...)?
`--web --rancher --rancher.domain=development.cluster.rancher.foo.com --logLevel=DEBUG`

**docker-compose.yml**
```yaml
version: '2'
services:
  traefik:
    image: traefik:v1.2.0-rc2
    stdin_open: true
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 8080:8080/tcp
    command:
    - --web
    - --rancher
    - --rancher.domain=development.cluster.rancher.foo.com
    - --logLevel=DEBUG
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
```

**rancher-compose.yml**
```yaml
version: '2'
services:
  traefik:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/health" "HTTP/1.0"
      reinitializing_timeout: 60000
```

### What did you do?
Tried to utilize the `io.rancher.container.agent.role` and `io.rancher.container.create_agent` labels in Rancher rather than passing in `endpoint`, `accesskey` and `secretkey`. This is documented in the [rancher backend](https://github.com/containous/traefik/blob/v1.2/docs/toml.md#rancher-backend) documentation.

### What did you expect to see?
I expected traefik to gain the correct API access to Rancher to generate a configuration.

### What did you see instead?
```
3/2/2017 1:57:25 PMERRO[2017-03-02T18:57:25Z] Cannot get Rancher Environments Unknown schema type [environment]
3/2/2017 1:57:25 PMgithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClientImpl).doList
3/2/2017 1:57:25 PM	/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/common.go:299
3/2/2017 1:57:25 PMgithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*EnvironmentClient).List
3/2/2017 1:57:25 PM	/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/generated_environment.go:119
3/2/2017 1:57:25 PMgithub.com/containous/traefik/provider.listRancherEnvironments
3/2/2017 1:57:25 PM	/go/src/github.com/containous/traefik/provider/rancher.go:293
3/2/2017 1:57:25 PMgithub.com/containous/traefik/provider.(*Rancher).Provide.func1.1.1
3/2/2017 1:57:25 PM	/go/src/github.com/containous/traefik/provider/rancher.go:253
3/2/2017 1:57:25 PMgithub.com/containous/traefik/safe.(*Pool).Go.func1
3/2/2017 1:57:25 PM	/go/src/github.com/containous/traefik/safe/routine.go:77
3/2/2017 1:57:25 PMgithub.com/containous/traefik/safe.GoWithRecover.func1
3/2/2017 1:57:25 PM	/go/src/github.com/containous/traefik/safe/routine.go:141
3/2/2017 1:57:25 PMruntime.goexit
```
