### ISSUE TITLE
Cannot load TOML value of type []interface {} into a Go string

### ISSUE THREAD

**Issue by klud1** [containous/traefik#1237]
So i'm trying to learn how to use Traefik, i'm testing in a small cluster i have in swarm mode.

Thing is when i create the service in CLI (following the [official user guide for swarm mode](https://docs.traefik.io/user-guide/swarm-mode/)) it works like a charm.

### What version of Traefik are you using (`traefik version`)?

- docker image from official registry using ```latest``` tag

### What is your environment & configuration (arguments, toml...)?

Using a plain config file for learning purposes

#### traefik.toml
```toml
graceTimeOut = 10
checkNewVersion = true
traefikLogsFile = "log/traefik.log"
accessLogsFile = "log/access.log"
logLevel = "ERROR"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
```

#### docker-compose.yml
```yml
version: "3"
services:
  traefik:
    image: traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/data/etc/traefik:/etc/traefik" # traefik.toml and acme.json location
      # - "/var/lib/data/var/log/traefik:/log/traefik"
    # command: "--docker --docker.swarmmode --docker.domain=traefik --docker.watch --web"
    ports:
      - "80:80"
      # - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

networks:
  traefik-net:
    external: true
```

### What did you do?
First used the example from the [official user guide for swarm mode](https://docs.traefik.io/user-guide/swarm-mode/), and then used a docker-compose.yml file with ```docker stack deploy traefik -c=./docker-compose.yml```.

When using the traefik.toml file i got an error, but when not using the traefik.toml and either using the ```command```paramater in the docker-compose.yml or not using anything at all the service starts with no problem.

### What did you expect to see?
The service being deployed in the manager node.

### What did you see instead?
```docker logs {container_attempted_to_be_deployed}``` outputs:
```Error reading TOML config file /etc/traefik/traefik.toml : toml: cannot load TOML value of type []interface {} into a Go string```
