### ISSUE TITLE
Rancher provider does not correctly handle unhealthy containers

### ISSUE THREAD

**Issue by kelchm** [containous/traefik#1253]
### What version of Traefik are you using (`traefik version`)?
Traefik: v1.2.0-rc2 / morbier
Rancher: v1.4.1

### What is your environment & configuration (arguments, toml...)?
**docker-compose.yml**
```yaml
version: '2'
services:
  traefik:
    image: traefik:v1.2.0-rc2
    stdin_open: true
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 8080:8080/tcp
    command:
    - --web
    - --rancher
    - --rancher.domain=development.cluster.rancher.foo.com
    - --rancher.endpoint=https://ui.cluster.rancher.foo.com
    - --rancher.accesskey=...
    - --rancher.secretkey=...
    - --logLevel=DEBUG
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
```

### What did you do?
Upgraded a service via the Rancher UI, enabling the `Start before Stopping` toggle. This service is configured with a health check.

### What did you expect to see?
The 'old' containers should be removed from the backend config when they are stopped by Rancher.

### What did you see instead?
Containers which have been stopped by Rancher remain in the backend config until they are **removed,** leading to failed requests.
