### ISSUE TITLE
"Gateway Timeout" with docker

### ISSUE THREAD

**Issue by Netmisa** [containous/traefik#1254]
### What version of Traefik are you using (`traefik version`)?

`1.2.0-rc2`

### What is your environment & configuration (arguments, toml...)?

`--web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG`

### What did you do?

I have this configuration in `docker-compose.yml` file for traefik container
```yml
version: '2'

services:
  proxy:
    image: traefik:1.2.0-rc2
    command: --web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  webgateway:
    driver: bridge
```

When I run `docker-compose up` from my projet I have `Gateway Timeout`.
Here my `docker-compose.yml` of my project (simplified)

```yml
version: '2'

services:
  nginx:
    container_name: nginx-my_network
    image: nginx:stable
    networks:
      - traefik
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:my_project.local"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"
    networks:
      - traefik
      - my_network

  php-fpm:
    container_name: php-my_network
    image: php:7.1-fpm
    command: '-F'
    networks:
      - my_network

  init-my_project:   # _/!\ Important - This service starts at the beginning and then ends when it finishes initialization processing, if i remove this It works all the time._
    container_name: my_project
    build:
      context: ../../..
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
  traefik:
    external:
      name: traefik_webgateway
```

`init-my_project` service starts at the beginning and then exit when it finishes initialization processing, if i remove this It works all the time.

### What did you expect to see?

I should see my website all the time.

### What did you see instead?

It works randomly and rarely.

I can see this warning only
```shell
proxy_1  | time="2017-03-08T07:32:48Z" level=warning msg="Error forwarding to http://172.19.0.2:80, err: dial tcp 172.19.0.2:80: i/o timeout"
```
I put more logs here: https://gist.github.com/Netmisa/266885e4429a2a09feb1ca95e76c5239

If I go here `http://172.19.0.2:80` it works.

I think the problem comes from the `init-my_project`, because when I remove this it works.
I tested binary (same version), It works correctly.

**Comment by dtomcej** [comment]
Can you create a gist with the debug logs showing the failures?

**Comment by Netmisa** [comment]
Hi @dtomcej 

I have only this error:
```
proxy_1  | time="2017-03-08T07:32:48Z" level=warning msg="Error forwarding to http://172.19.0.2:80, err: dial tcp 172.19.0.2:80: i/o timeout"
```
I put more logs here: https://gist.github.com/Netmisa/266885e4429a2a09feb1ca95e76c5239

If I go here `http://172.19.0.2:80` it works.

_Description updated with this additionals informations._

**Comment by Netmisa** [comment]
Hi @dtomcej 

I found a concrete exemple:

`docker-compose.yml` (not work)
```
version: '2'

services:
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:test.local"
    networks:
      - my_network
      - traefik

  hello_world:
    image: library/hello-world
    networks:
      - my_network

  hello_world_1:
    image: library/hello-world
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
  traefik:
    external:
      name: traefik_webgateway
```

`docker-compose.yml` (work)
```
version: '2'

services:
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:test.local"
    networks:
      - traefik

  hello_world:
    image: library/hello-world

  hello_world_1:
    image: library/hello-world

networks:
  traefik:
    external:
      name: traefik_webgateway
```

If I remove `my_network` it will work fine.

I hope this will help you
