### ISSUE TITLE
Authorization header not passed

### ISSUE THREAD

**Issue by mvdstam** [containous/traefik#1264]
### What version of Traefik are you using (`traefik version`)?
latest

### What did you do?
Send a HTTP request containing an `Authorization: Bearer [token]` header to a backend.

### What did you expect to see?
A valid result based on the bearer token I sent.

### What did you see instead?
An error indicating the complete lack of the `Authorization` header being passed to the backend. In short, the `Authorization` header seems to be stripped completely.

**Comment by piteur** [comment]
Hey,

did you set the `traefik.frontend.passHostHeader` rule to `true` ?
Also, what adapter are you using ?

**Comment by mvdstam** [comment]
Hey @piteur,

I'm using the Docker provider if that's what you mean with "adapter", which seems to default to setting the `passHostHeader` to true. This is what I'm seeing in the debug logs:

```json
{
    "backends": {
        "backend-hd-api": {
            "servers": {
                "server-hdapi_app_1": {
                    "url": "http://172.18.0.4:80",
                    "weight": 0
                }
            },
            "loadBalancer": {
                "method": "wrr"
            }
        }
    },
    "frontends": {
        "frontend-Host-hd-api-docker-local": {
            "entryPoints": [
                "http"
            ],
            "backend": "backend-hd-api",
            "routes": {
                "route-frontend-Host-hd-api-docker-local": {
                    "rule": "Host:hd-api.docker.local"
                }
            },
            "passHostHeader": true,
            "priority": 0
        }
    }
}
```

This is (a part of) my `docker-compose.yml` which creates the application:

```yaml
app:
    image: my-app-image
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - web
    labels:
      - "traefik.backend=hd-api"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:hd-api.docker.local"
      - "traefik.enable=true"
```
