### ISSUE TITLE
Connection to Consul fails if Consul is behind proxy with basic authentication

### ISSUE THREAD

**Issue by mcapuccini** [containous/traefik#1275]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
```toml
################################################################
# Defaults
################################################################
defaultEntryPoints = ["http","https"]
################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# ACME
################################################################
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "my@mail.com"
storage = "traefik/acme/account"
entryPoint = "https"
onHostRule = true
caServer = "https://acme-staging.api.letsencrypt.org/directory"
################################################################
# Consul backend
################################################################
[consul]
endpoint = "[user:password@consul.mydomain.com]:80"
watch = true
prefix = "traefik"
```

### What did you do?
I am try to using a central Consul to store ACME certificates. My Consul endpoint is exposed to the internet, behind basic authentication. 

### What did you expect to see?
I am expecting Traeifik to connect to my Consul endpoint: `[user:password@consul.mydomain.com]:80`

### What did you see instead?
```
2017/03/12 14:27:31 Error loading configuration: Get http://[user:passwordA%40consul.mydomain.com]:80/v1/kv/traefik?recurse=&wait=30000ms: dial tcp: lookup user:password@consul.mydomain.com: invalid domain name
```
If I specify the endpoint without the square brackets I get this error: http://stackoverflow.com/questions/8854682/go-json-rpc-too-many-colons

Thanks in advance!!! :)

**Comment by mcapuccini** [comment]
Trying to do this https://github.com/containous/traefik/issues/767 with `CONSUL_HTTP_AUTH` might do the trick, I'll test tomorrow!

**Comment by mcapuccini** [comment]
No luck setting the environment variable:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      hostNetwork: true # workaround
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.1.2-alpine
        name: traefik-ingress-lb
        imagePullPolicy: Always
        env:
        - name: CONSUL_HTTP_AUTH
          value: "myuser:asdasdasd"
        - name: CONSUL_HTTP_SSL
          value: "true"
        volumeMounts:
          - mountPath: /etc/traefik
            name: traefik-volume
            readOnly: false
        resources:
          requests:
            cpu: 1
            memory: 1G
        args:
        - --web
        - --kubernetes
        - --configFile=/etc/traefik/traefik.toml
        - --logLevel=DEBUG
      volumes:
        - hostPath:
            path: /etc/traefik
          name: traefik-volume
      nodeSelector:
        role: edge
```

**Comment by mcapuccini** [comment]
I can't really get why it doesn't work passing the environment variables. Looking at the Traefik code, it seems like this should work.

```bash
ocker run -v $PWD:/conf -e "CONSUL_HTTP_AUTH=user:test" -e "CONSUL_HTTP_SSL=true" traefik:1.1.2-alpine --configFile=/conf/traefik.toml
2017/03/14 09:42:58 Error loading configuration: Unexpected response code: 401
```

## traefik.toml
```toml
[consul]
endpoint = "consul.mydomain.com"
watch = true
prefix = "traefik"
```
