### ISSUE TITLE
ExternalName services not working

### ISSUE THREAD

**Issue by simt2** [containous/traefik#1277]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.2.0-rc2
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-01_01:03:26PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml...)?
Running on Kubernetes 1.5.3. 

traefik.yml
```yaml
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  template:
    metadata:
      name: traefik
      labels:
        app: traefik
    spec:
      nodeSelector: 
        kubernetes.io/hostname: cluster-master-1
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:morbier
        name: traefik
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        args:
        - --debug
        - --web
        - --configfile=/config/traefik.toml
        volumeMounts:
          - name: config
            mountPath: /config
          - name: acme
            mountPath: /acme
      volumes:
        - name: acme
          nfs:
            server: 10.100.2.0
            path: /storage/system/traefik-acme
        - name: config
          configMap:
            name: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  externalIPs: 
  - 10.100.2.0
  ports:
    - name: http
      port: 80
    - name: status
      port: 8080
  selector:
    app: traefik
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
  labels:
    app: traefik
spec:
  rules:
  - host: proxy.domain.tld
    http:
      paths:
      - backend:
          serviceName: traefik
          servicePort: 8080
```
traefik.toml
```toml
defaultEntryPoints = ["http"]

[entryPoints]
[entryPoints.http]
address = ":80"

[kubernetes]
namespaces = ["default"]
```

### What did you do?
Created the following service and ingress:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: volumes
spec:
  ports:
  - name: http
    port: 8080
  type: ExternalName
  externalName: 10.100.2.0
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: volumes
  annotations:
    kubernetes.io/ingress.class: "traefik"
  labels:
    name: volumes
spec:
  rules:
  - host: api.domain.tld
    http:
      paths:
      - path: /volumes
        backend:
          serviceName: volumes
          servicePort: http
```

### What did you expect to see?
My service reachable under `api.domain.tld/volumes`. 

### What did you see instead?
The following error message:
`time="2017-03-13T06:39:56Z" level=error msg="Error retrieving endpoints default/volumes: <nil>"`

The example given in kubernetes.md also does not work for me and fails with the same error.

**Comment by timoreimann** [comment]
@simt2 Support for ExternalName was added in #1149 by @Regner and (AFAICS) won't be part of the next release yet. (The feature was merged after the v1.2 code freeze.)

Unfortunately, the published docs do not match the latest stable release; I have created #1279 to track improvement in this regard.

If you have a chance to build and try out master, we'd love to see if it works for you.

**Comment by simt2** [comment]
I'm not using stable but 1.2.0-rc2. The confusing thing is that the feature is listed under "Implemented enhancements" in CHANGELOG.md.

**Comment by timoreimann** [comment]
The docs also don't match the latest release candidate. :( It's the master state, which is why you see the change announced in the change log.

**Comment by timoreimann** [comment]
Closing for now. @simt2, if you get a chance to try out the feature with 1.3.0 and find it to be buggy / erroneous, feel free to post again and we'll reopen the issue.

**Comment by caseeker** [comment]
externalName is showing up after upgrading to 1.3.1, however the port mapping is not working properly.
The problem might be coming from Kubernetes it self.

```
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: traefik
    name: external-name-svc-example
  spec:
    rules:
    - host: example.com
      http:
        paths:
        - backend:
            serviceName: external-name-service-example
            servicePort: 3000
```

The backend url that gets created is still port 80
