### ISSUE TITLE
storeconfig doesn't create all keys from configuration file

### ISSUE THREAD

**Issue by grosendorf** [containous/traefik#1283]
### What version of Traefik are you using (`traefik version`)?
1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
k8s + consul kv

### What did you do?
Created traefik.toml ConfigMap, and run `storeconfig` as a k8s job. 

### What did you expect to see?
All keys specified in traefik.toml created in kv store. toml file used:
```toml
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [kubernetes]
    [web]
    address = ":8080"
    [acme]
    acmeLogging = true
    dnsProvider = "route53"
    email = "<redacted>"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onDemand = true
    OnHostRule = true
    [[acme.domains]]
    main = "<redacted>"
    [consul]
    endpoint = "consul-0.consul:8500"
    watch = true
    prefix = "traefik"
```

### What did you see instead?
Most of the keys were created, but some were not. Specifically `traefik/acme/acmelogging` and `traefik/acme/dnsprovider` were not created.
