### ISSUE TITLE
Provide means to get to a specific backend

### ISSUE THREAD

**Issue by alwaysastudent** [containous/traefik#1297]
### What version of Traefik are you using (`traefik version`)?
```
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:27:40AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?

Traefik configs
```yml
traefik:
    command: -c /dev/null --web --docker --docker.watch --docker.domain= mycompany.com
      --entryPoints='Name:http Address::80'
      --defaultEntryPoints='http' --logLevel=DEBUG --accessLogsFile=/var/log/traefik-access.log
    image: mycompany/traefik:latest
    ports:
    - 80:80
    - 8080:8080
    - 443:443
    userns_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /dev/null:/traefik.toml:rw
```

Using scalable docker backends  
```yml
      traefik.backend: searcht
      traefik.frontend.entrypoints: =http
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: PathPrefix:/search/v1, /maintenance/
      traefik.port: '10010'
```
### What did you do?

Say, if I want to go to a specific backend based off a Host header `Host: container_01.mycompany.com` or `Host: container_01.mycompany.com` I can use them as a label in a frontend rule on my backend containers and make this happen. 

But container names generated are unpredictable if scaled using say something like `docker-compose` or any other cluster managers.

PS. I dynamically scale my backend docker containers using `docker-compose` which you would know would create random container-names as it spins up the cluster.  

### What did you expect to see?

My request is if you add means to hit a specific host on backend via traefik, it will be very handy in a dynamic environment where you would be able to reach directly a host and say its management console.
  
My requirement would have met, if the default frontend rule (Default: Host:{containerName}.{domain}). was always/or on demand appended to the labelled frontend rule.

https://github.com/containous/traefik/blob/1158eba7acc5c9f97703676cd952b7116a43ca8c/provider/docker.go#L528
