### ISSUE TITLE
How to redirect an url to another ?

### ISSUE THREAD

**Issue by tbouvet** [containous/traefik#1302]
### What version of Traefik are you using (`traefik version`)?
v1.1.0

### What is your environment & configuration (arguments, toml...)?
```toml
[entryPoints]
   [entryPoints.http]
   address = ":80"
     [entryPoints.http.redirect]
       regex = "^http://(.*).domain.com"
       replacement = "http://$1.staging.newdomain.com"
```

### What did you do?
I want to redirect all url *.domain.com to *.staging.newdomain.com

### What did you expect to see?
url redirected

### What did you see instead?
all url are now in 404

Is it possible to do that please ?
