### ISSUE TITLE
traefik.frontend.rule NOT working as expected combination rules.

### ISSUE THREAD

**Issue by alwaysastudent** [containous/traefik#1312]
### What version of Traefik are you using (`traefik version`)?
```
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:27:40AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?

Traefik configs
```yml
traefik:
    command: -c /dev/null --web --docker --docker.watch --docker.domain= mycompany.com
      --entryPoints='Name:http Address::80'
      --defaultEntryPoints='http' --logLevel=DEBUG --accessLogsFile=/var/log/traefik-access.log
    image: mycompany/traefik:latest
    ports:
    - 80:80
    - 8080:8080
    - 443:443
    userns_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /dev/null:/traefik.toml:rw
```

Using scalable docker backends  
```yml
      traefik.backend: foo
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule=Host:bar.com,PathPrefix:/foo/
      traefik.port: '10010'
```
### What did you do?

I tried to hit the /foo/blah resource over traefik and I got 404. I didn't pass the host header. If I pass the host header I get a resource back from backend.

### What did you expect to see?

The following rule does not work as expected. `traefik.frontend.rule=Host:bar.com,PathPrefix:/foo/`
My expectation was the rule would match if the request has the `Host:bar.com` *OR* if the path prefix matches `foo/` but it is *NOT* working like that.  

I have to send the Host: bar.com for accessing the /foo/ resources; Kindly help on this
