### ISSUE TITLE
acme (letsencrypt) question

### ISSUE THREAD

**Issue by dstroot** [containous/traefik#1313]
### What version of Traefik are you using (`traefik version`)?

docker container: traefik latest (official):

```
spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: traefik-ingress-lb
          image: traefik  
```

### What is your environment & configuration (arguments, toml...)

GKE Kubernetes Cluster latest (1.5.3 I think).  See below for complete toml and yaml config.

### What did you do?

Trying to use Traefik for ingress and the acme support for automatic TLS

### What did you expect to see?

I expected Traefik to get and use the acme certificate

### What did you see instead?

I see in the logs that it appears to get the certificates:

```
2017-03-18T18:29:39.415062479Z time="2017-03-18T18:29:39Z" level=info msg="Starting server on :80" 
2017-03-18T18:29:40.869677733Z time="2017-03-18T18:29:40Z" level=info msg="Loading ACME Account..." 
2017-03-18T18:29:40.875675117Z time="2017-03-18T18:29:40Z" level=info msg="Loaded ACME config from store /acme/acme.json" 
2017-03-18T18:29:40.875713025Z time="2017-03-18T18:29:40Z" level=debug msg="Building ACME client..." 
2017-03-18T18:29:41.651997124Z time="2017-03-18T18:29:41Z" level=debug msg=AgreeToTOS... 
2017-03-18T18:29:42.671746285Z time="2017-03-18T18:29:42Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}" 
2017-03-18T18:29:42.671833812Z time="2017-03-18T18:29:42Z" level=info msg="Starting provider *provider.Kubernetes {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"}" 
2017-03-18T18:29:42.671953693Z time="2017-03-18T18:29:42Z" level=info msg="Retrieving ACME certificates..." 
2017-03-18T18:29:42.672063872Z time="2017-03-18T18:29:42Z" level=debug msg="Loading ACME certificates [thepishoppe.com traefik.thepishoppe.com]..." 
2017-03-18T18:29:42.686212586Z time="2017-03-18T18:29:42Z" level=info msg="Starting server on :443" 
```

However the certificate is listed as the "TRAEFIK DEFAULT CERT" and does not work properly:

![image](https://cloud.githubusercontent.com/assets/1438457/24074939/9e300450-0bcf-11e7-91e4-47cf972a36f1.png)

Complete config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      # [entryPoints.https.auth.basic]
      # users = ["dstroot:e33af7471e19f8c0bdae6184784f9c125d4ee73a"]
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

    # Træfik can be configured using a RESTful api. To enable it:
    [web]
    address = ":8080"

    # Optional
    # ReadOnly = false
    # To enable more detailed statistics
    # [web.statistics]
    #   RecentErrors = 10
    # To enable Traefik to export internal metrics to Prometheus
    # [web.metrics.prometheus]
    #   Buckets=[0.1,0.3,1.2,5.0]
    # To enable basic auth on the webui
    # with 2 user/pass: test:test and test2:test2
    # Passwords can be encoded in MD5, SHA1 and BCrypt: you can use htpasswd to generate those ones
    #   [web.auth.basic]
    #     users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]
    # To enable digest auth on the webui
    # with 2 user/realm/pass: test:traefik:test and test2:traefik:test2
    # You can use htdigest to generate those ones
    #   [web.auth.digest]
    #     users = ["test:traefik:a2688e031edb4be6a3797f3882655c05 ", "test2:traefik:518845800f9e2bfb1f1f740ec24f074e"]

    [kubernetes]

    [acme]
    email = "dan.stroot@gmail.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    acmeLogging = true
    # onDemand = true
    # onHostRule = true

    # CA server to use
    # Uncomment the line to run on the staging let's encrypt server
    # Comment out to go to prod
    # caServer = "https://acme-staging.api.letsencrypt.org/directory"

    # Domains list
    # You can provide SANs (alternative domains) to each main domain
    # All domains must have A/AAAA records pointing to Traefik
    # WARNING, Take note that Let's Encrypt have rate limiting: https://letsencrypt.org/docs/rate-limits
    # Each domain & SANs will lead to a certificate request.
    [[acme.domains]]
       main = "thepishoppe.com"
       sans = ["traefik.thepishoppe.com"]
    # [[acme.domains]]
    #   main = "local3.com"
    # [[acme.domains]]
    #   main = "local4.com"
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik-ingress-lb
spec:
  type: LoadBalancer
  selector:
    app: traefik-ingress-lb
  # This is optional but Google Container Engine supports a 
  # static loadBalancer IP address. 
  # just mark the auto-assigned IP as static first!
  loadBalancerIP: 104.198.107.147
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-console
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - port: 8080
      name: webui
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: traefik.thepishoppe.com
      http:
        paths:
          - backend:
              serviceName: traefik-console
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress-lb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: traefik-ingress-lb
          image: traefik  
          # "containous/traefik:v1.1.2"
          # imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: acme
              mountPath: /acme
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
          args:
            - --configfile=/config/traefik.toml
            - --logLevel=DEBUG
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          gcePersistentDisk:
            # This GCE persistent disk must already exist.
            pdName: acme
            fsType: ext4
```
