### ISSUE TITLE
accept4: too many open files

### ISSUE THREAD

**Issue by IncSW** [containous/traefik#1322]
### What version of Traefik are you using (`traefik version`)?
```
Version:      v1.2.0-rc2
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-01_01:03:26PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
Docker container with `traefik:morbier-alpine`
`MaxIdleConnsPerHost` 200
`ulimit -n` 65536

Had problem like a #127 #157.
With ~100rps, after ~24h takes limit.
`server.go:2317: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s`.

**Comment by emilevauge** [comment]
@IncSW Could you give use the whole configuration (flags, toml) ?

**Comment by IncSW** [comment]
```toml
defaultEntryPoints = ["http"]
MaxIdleConnsPerHost = 200

accessLogsFile = "/var/log/access.log"

[web]
address = ":8080"
  [web.statistics]
    RecentErrors = 10
  [web.metrics.prometheus]
    Buckets = [0.1, 0.3, 1.2, 5.0]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[frontends]
  [frontends.gateway-frontend]
  backend = "gateway-backend"
  passHostHeader = true
    [frontends.gateway-frontend.routes.host]
    rule = "Host:gateway.domain.com"
  [frontends.frontend-frontend]
  backend = "frontend-backend"
  passHostHeader = true
    [frontends.frontend-frontend.routes.host]
    rule = "Host:domain.com"

[file]
[backends]
  [backends.gateway-backend]
    [backends.gateway-backend.servers.server]
    url = "http://gateway:80"
  [backends.frontend-backend]
    [backends.frontend-backend.servers.server]
    url = "http://frontend:80"
```
