### ISSUE TITLE
Healthcheck example

### ISSUE THREAD

**Issue by joshuacox** [containous/traefik#1326]
### What did you do?
created my own catalog templates:
https://github.com/ohmydocker/ohmydocker-catalog/tree/master/templates/meanshop-traefik

with this healthcheck:
```
services:
  meanshop-nginx:
    scale: 1
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 9
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
```

### What did you expect to see?

traefik serving my stuff

### What did you see instead?

"initializing" and constant purging and rebooting of my containers

original issue [here](https://github.com/rancher/rancher/issues/7969) 

and recently opsforge had [this issue](https://github.com/rancher/rancher/issues/8234) which I believe is related.

Are there any known working good examples of a healthcheck?  Or perhaps a simple hello world template with which to test traefik?

EDIT: I moved this version into its own directory to explore other methods
https://github.com/ohmydocker/ohmydocker-catalog/tree/master/templates/meanshop-traefik
I updated the link above as well and got rid of the extraneous ones

**Comment by kelchm** [comment]
@timoreimann Can you explain exactly what you are trying to do? Traefik doesn't have anything to do with Rancher health checks.

In other words, if your health check works correctly without traefik it will continue to work correctly when you are running traefik in that environment. Health checks run directly against the internal ip/port of the container.

**Comment by joshuacox** [comment]
I wasn't using healthchecks at all until I tried to get traefik to work. And according to the readme:

```
WARNING: Only services with healthy state are added to traefik, so health checks are mandatory.
```

I merely want to serve my containers content through a single port 80 or 443 portal.  Apparently, I need a working healthcheck.   Which leads to the continuous rebooting situation as described in my post [here](https://github.com/rancher/rancher/issues/7969).  I also, noticed another issue [here](https://github.com/rancher/rancher/issues/8234), while that one does not mention traefik, it does indicate I'm not alone in this bizaar behavior.

So traefik, might not have anything to do with the healthcheck, it certainly depends on it working.  Does anyone have a working 'hello world' example that I can compare against my own for sanity's sake?

**Comment by timoreimann** [comment]
@SantoDE can you possibly help?

**Comment by joshuacox** [comment]
I have a helloworld example that is both working on one ranch, and broken in another.  I think I have an issue that is outside the context of traefik.

for reference here is a tiny example with which to test traefik out:
https://github.com/ohmydocker/ohmydocker-catalog/tree/master/templates/traefik-helloworld

**Comment by kelchm** [comment]
@joshuacox, it sounds like you actually using [this project](https://github.com/rawmind0/rancher-traefik) rather than the official rancher provider integration within traefik (just added in v1.2.0). FWIW, the official rancher provider does **not** require rancher healthchecks for traefik to function.

_That said, the issue you are having is entirely within your rancher-compose configuration._ As an example, here's the health check I'm using for one of my services:

```yaml
version: '2'
services:
  web:
    scale: 3
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
```
