### ISSUE TITLE
ACME stopped working

### ISSUE THREAD

**Issue by amq** [containous/traefik#1334]
### What version of Traefik are you using (`traefik version`)?

1.2.0

### What is your environment & configuration (arguments, toml...)?

```
version: "2"

services:
  traefik:
    image: traefik
    restart: always
    command: |-
      --logLevel=DEBUG
      --web
      --entrypoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entrypoints='Name:https Address::443 TLS'
      --docker
      --docker.domain=traefik
      --docker.exposedbydefault=false
      --acme
      --acme.entrypoint=https
      --acme.email=amq@users.noreply.github.com
      --acme.storage=acme.json
      --acme.ondemand=false
      --acme.onhostrule=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/traefik.toml
      - acme:/etc/traefik/acme

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.sam101.amq.space"
      - "traefik.frontend.entryPoints=http,https"

volumes:
  acme:
    driver: local
  portainer:
    driver: local
```

### What did you do?

`docker-compose up -d`

### What did you expect to see?

A valid Let's Encrypt certificate.

### What did you see instead?

```
time="2017-03-23T13:01:58Z" level=debug msg="LoadCertificateForDomains [portainer.sam101.amq.space]..."
time="2017-03-23T13:01:58Z" level=debug msg="Loading ACME certificates [portainer.sam101.amq.space]..."
time="2017-03-23T13:01:58Z" level=debug msg="Challenge Present portainer.sam101.amq.space"
time="2017-03-23T13:01:59Z" level=debug msg="Challenge GetCertificate cba7077d9549b5769fdb8fa6e9d32463.ce734350c371080d9668ad986429bd72.acme.invalid"
time="2017-03-23T13:01:59Z" level=debug msg="ACME got challenge cba7077d9549b5769fdb8fa6e9d32463.ce734350c371080d9668ad986429bd72.acme.invalid"
2017/03/23 13:01:59 server.go:2317: http: TLS handshake error from 66.133.109.36:59762: read tcp 172.18.0.3:443->66.133.109.36:59762: read: connection reset by peer
time="2017-03-23T13:02:00Z" level=debug msg="Challenge CleanUp portainer.sam101.amq.space"
time="2017-03-23T13:02:00Z" level=error msg="map[portainer.sam101.amq.space:acme: Error 400 - urn:acme:error:connection - Failed to connect to 34.204.113.250:443 for TLS-SNI-01 challenge\nError Detail:\n\tValidation for portainer.sam101.amq.space:443\n\tResolved to:\n\t\t34.204.113.250\n\tUsed: 34.204.113.250\n\n]"
time="2017-03-23T13:02:00Z" level=error msg="Error getting ACME certificates [portainer.sam101.amq.space] : Cannot obtain certificates map[portainer.sam101.amq.space:acme: Error 400 - urn:acme:error:connection - Failed to connect to 34.204.113.250:443 for TLS-SNI-01 challenge\nError Detail:\n\tValidation for portainer.sam101.amq.space:443\n\tResolved to:\n\t\t34.204.113.250\n\tUsed: 34.204.113.250\n\n]+v"
```

It worked on Monday.

I think I have tried everything already.
- completely disabled firewall
- `docker-compose stop`, `docker-compose rm`, `docker system prune -a`
- experimented with different configuration options (`ondemand`, `exposedbydefault`, `domain`...)
- used a different domain
- changed the IP
- launched a fresh ubuntu 16.04 instance and provisioned it with `docker-machine`
- changed `CNAME` records to `A`
- removed the http->https redirect

Maybe a helpful observation:
- ` --acme.caserver='https://acme-v01.api.letsencrypt.org/directory'` produces the above error
- ` --acme.caserver='https://acme-staging.api.letsencrypt.org/directory'` works, but the certificate is obviously not usable
