### ISSUE TITLE
Traefik unable to handle Websocket

### ISSUE THREAD

**Issue by jkaberg** [containous/traefik#1358]
### What version of Traefik are you using (`traefik version`)?
1.2.1

### What is your environment & configuration (arguments, toml...)?

traefik.toml:

```toml
debug = true
logLevel = "debug"

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = false
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = false
    [entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "xxx.xxx"
watch = true

[acme]
email = "xxxx@xxxx"
storage = "/acme.json"
entryPoint = "https"
onDemand = true
#OnHostRule = true

[web]
address = ":8080"
ReadOnly = true

```

backend nginx proxy:

```
#limit_req_zone $binary_remote_addr zone=weechat:10m rate=5r/m;
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream wee-upstream {
    server weechat:13337;
}

server {
    location / {
        root /usr/share/nginx/html/;
    }

    location /weechat {
        proxy_pass http://wee-upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 8h;
#        limit_req zone=weechat burst=1 nodelay;
    }
}
```

docker-compose:

```yml
version: "3.0"
services:
  traefik:
    image: traefik:1.2.1-alpine
    command: -c /traefik.toml
    volumes:
      - ./traefik.toml:/traefik.toml:ro
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=false'
    networks:
      traefik:
      majolan:
        ipv4_address: 192.168.1.9

  weechat:
    image: jkaberg/weechat
    tty: true
    volumes:
      - /xxxxx/weechat:/home/weechat/.weechat
    labels:
      - 'traefik.enable=false'
    networks:
      backend:

  glowingbear:
    image: jkaberg/glowingbear
    depends_on:
      - weechat
    ports:
      - '8080:80'
    labels:
      - 'traefik.frontend.rule=Host:irc.xxx.xxx'
      - 'traefik.port=80'
      - 'traefik.protocol=http'
      - 'traefik.docker.network=traefik'
    networks:
      traefik:
      backend:

networks:
  majolan:
    external: true
  backend:
    driver: overlay
  traefik:
    external: true

```
### Relevant Traefik log

```shell
time="2017-03-28T16:46:55Z" level=debug msg="Challenge GetCertificate irc.xxx.xxx"
time="2017-03-28T16:46:55Z" level=debug msg="ACME got domain cert irc.xxx.xxx"
time="2017-03-28T16:46:55Z" level=debug msg="Writing outgoing Websocket request to target connection: &{Method:GET URL:ws:/weechat Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept-Encoding:[gzip, deflate, sdch, br] Connection:[Upgrade] Cache-Control:[no-cache] Sec-Websocket-Version:[13] Cookie:[connect.sid=s%3A3ex21QyYGtYDtUX-F-If1Xg_819LpAWR.sHKb5OGfFk05eoiYPbZPgqGBWWdO3tAaCDZHezoeotU; _TRAEFIK_BACKEND=http://10.0.2.8:80] Pragma:[no-cache] Origin:[https://irc.xxx.xxx] Upgrade:[websocket] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36] Sec-Websocket-Key:[mSJsbaddL+QvClPVv/rVSw==] Sec-Websocket-Extensions:[permessage-deflate; client_max_window_bits] Accept-Language:[nb-NO,nb;q=0.8,no;q=0.6,nn;q=0.4,en-US;q=0.2,en;q=0.2]] Body:0x2b93c10 ContentLength:0 TransferEncoding:[] Close:false Host:irc.xxx.xxx Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:10.0.2.13:49866 RequestURI:/weechat TLS:0xc4209ab8c0 Cancel:<nil> Response:<nil> ctx:0xc420226840}"
time="2017-03-28T16:46:56Z" level=debug msg="Round trip: http://10.0.2.8:80, code: 304, duration: 432.353µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:irc.xxx.xxx"
```

chrome console log:

```
Service Worker is supported
angular.js:14110Connecting to URL:  wss://irc.xxx.xxx:443/weechat
angular.js:14110Notification permission status:  denied
angular.js:14110Service Worker install: ServiceWorkerRegistration
websockets.js:121 WebSocket connection to 'wss://irc.xxx.xxx/weechat' failed: Error during WebSocket handshake: Unexpected response code: 400
connect @ websockets.js:121
angular.min.js:119 Relay error Event
(anonymous) @ angular.min.js:119
angular.min.js:119 Disconnected from relay
```

### What did you do?
"Login" via web page which does request to irc.xxx.xxx/weechat (websocket upgrade)

### What did you expect to see?
Traefik reverse proxying the request to internal proxy which makes the request to weechat relay.

### What did you see instead?
Nothing (see above traefik and chrome console logs). 

Visiting host:8080 (see docker-compose config above) and trying the same thing (only nginx reverse proxy, without traefk) works fine. 

**Not working**: traefik->nginx->websocket->weechat relay
**Working**: nginx->websocket->weechat relay
