### ISSUE TITLE
Feature Req: need healthcheck app in Docker Image to check traefik

### ISSUE THREAD

**Issue by composer22** [containous/traefik#1359]
Using docker-compose.yml and stack deploy, need the ability to perform self health check on the service to make sure it is running. This is standard practice now within our environment to make sure the app is still working. It may be up but it isn't necessarily healthy. In this case the container will restart based on a policy.

example:
```
healthcheck:
      test: "curl -s -f http://localhost:8080/health || exit 1"
      interval: 20s
      timeout: 20s
      retries: 3
```
If you won't install curl, how about another app?
