### ISSUE TITLE
Docker connection error Error response from daemon: This node is not a swarm manager.

### ISSUE THREAD

**Issue by DaBlitzStein** [containous/traefik#1361]
### What version of Traefik are you using (`traefik version`)?

1.2.1 docker version.

### What is your environment & configuration (arguments, toml...)?

```toml
################################################################
# Global configuration
################################################################
# Log level
logLevel = "DEBUG"
accessLogsFile = "/etc/log/access.log"
traefikLogsFile = "/etc/log/traefik.log"

#
# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
defaultEntryPoints = ["http", "https"]
#

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]
    address = ":443"
  # certs used as default certs
  # [[entryPoints.https.tls.certificates]]
  # certFile = "/etc/certs/traefik.crt"
  # keyFile = "/etc/certs/traefik.key"

################################################################
# ACME (Let's Encrypt): automatic SSL
################################################################
[acme]

email = "qwdqwdqwd"
storageFile = "/etc/acme/encrypt/acme.json"
entryPoint = "https"
onDemand = true
acmeLogging = true

OnHostRule = true

[[acme.domains]]
  main = "serviuntts.com"
  sans = ["chatops.sqwdqwdm","kanboard.serqwdqwcom","hunttersqwdqwd.ntts.com","qwdqwd.rviuntts.com","untts.qwdqwds.com"]

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
# Web administration port
address = ":8080"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
endpoint = "unix:///var/run/docker.sock"
#endpoint = "tcp://192.168.0.111:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
domain = "serviuntts.com"
swarmmode = true
# Enable watch docker changes
watch = true
```

### What did you do?

Run it.
### What did you expect to see?

Working dashboard. 

### What did you see instead?

Empty dashboard.

```
level=error msg="Docker connection error Error response from daemon: This node is not a swarm manager. Worker nodes can't be used to view or modify cluster state. Please run this command on a manager node or promote the current node to a manager., retrying in 1.10588891s"
```
