### ISSUE TITLE
ACME fails with runtime error and segmentation violation when using etcd as backend with kubernetes

### ISSUE THREAD

**Issue by mbocevski** [containous/traefik#1366]
### What version of Traefik are you using (`traefik version`)?
v1.2.1

### What is your environment & configuration (arguments, toml...)?
We are running trafik on a kubernetes v1.5.3 cluster and want to use etcd as a backend for ACME certificates. 

The arguments we use: `--configfile=/config/traefik.toml --web --kubernetes --insecureskipverify=true`

traefik.toml:

```toml
# traefik.toml
    debug = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/server.crt"
          KeyFile = "/ssl/server.key"

    [acme]
    email = "noto@spam.com"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onDemand = true
    acmeLogging = true

    [etcd]
    endpoint = "XXX.XXX.XXX.XXX:2379,XXX.XXX.XXX.XXX:XXX.XXX.XXX.XXX:2379"
    prefix = "/traefik"
    watch = true
```

### What did you do?
Request an https page.

### What did you expect to see?
An ACME lets encrypt certificate obtained and served onDemand.

### What did you see instead?
```shell
time="2017-03-30T13:53:16Z" level=debug msg="Challenge GetCertificate intentionally.changed.domain.tld"
time="2017-03-30T13:53:16Z" level=debug msg="Loading ACME certificates [intentionally.changed.domain.tld]..."
legolog: 2017/03/30 13:53:16 [INFO][intentionally.changed.domain.tld] acme: Obtaining bundled SAN certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x776238]

goroutine 305 [running]:
panic(0x1af03e0, 0xc420014020)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0x0, 0xc420806d20, 0xc420806cc0, 0xc42094e360, 0x13)
	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:543 +0xf8
created by github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges
	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:557 +0x15b
```
