### ISSUE TITLE
Traefik service tries to start on http2 by itself and fails

### ISSUE THREAD

**Issue by gvilarino** [containous/traefik#1371]
### What version of Traefik are you using (`traefik version`)?
```
Version:      v1.2.1
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-27_03:19:40PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
```toml
defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    CipherSuites = ["TLS_RSA_WITH_AES_256_GCM_SHA384"]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/traefik/tls/some.cert"
      KeyFile = "/etc/traefik/tls/some.key"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "my.domain.com"
watch = true
exposedbydefault = false
swarmmode = true

```

### What did you do?
```shell
docker service create \
    --name traefik \
    --constraint=node.role==manager \
    --publish 80:80 --publish 443:443 --publish 8080:8080 \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --network traefik-net \
   my-traefik-image-with-the-toml-file-and-certs-inside \
    --web
```

### What did you expect to see?
A running traefik service with regular http->https and NO http2.

### What did you see instead?
The service failing to start, and the following error log:

```shell
time="2017-03-31T18:39:02Z" level=fatal msg="Error creating server: http2: TLSConfig.CipherSuites is missing HTTP/2-required TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
```

Buuut I never wanted to activate or did activate http2. I don't want it and it's killing my service startup.

What am I missing? I found nearly 0 docs about troubleshooting trafik, or understanding how http2 works, or is enabled/disabled.

Thanks in advance.
