### ISSUE TITLE
client-go 1.5 not compatible with kubernetes 1.6

### ISSUE THREAD

**Issue by patte** [containous/traefik#1379]
### What version of Traefik are you using (`traefik version`)?
1.2.1 (or 1.2.0-rc2)

### What is your environment & configuration (arguments, toml...)?
Kubernetes Cluster (v. 1.6.1)

### What did you do?
Deploy Traefik as described in the docs. Because my cluster is self hosted, I use `hostNetwork: true` see config

### What did you expect to see?
Traefik up and running happily... as it was the case with Kubernetes 1.5.3

### What did you see instead?
No backend / frontend showing up in the dashboard. Pages not serving. Errors in the logs. [client-go](https://github.com/kubernetes/client-go) tells me, client-go 1.5 is not compatible with Kubernetes 1.6. True?

### If applicable, please paste the log output in debug mode (`--debug` switch)
kubectl logs traefik-ingress-controller-vn21d
```
ERROR: logging before flag.Parse: E0404 07:57:02.404571       1 reflector.go:214] github.com/containous/traefik/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Service: the server does not allow access to the requested resource (get services)
ERROR: logging before flag.Parse: E0404 07:57:02.404589       1 reflector.go:214] github.com/containous/traefik/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Endpoints: the server does not allow access to the requested resource (get endpoints)
ERROR: logging before flag.Parse: E0404 07:57:02.404719       1 reflector.go:214] github.com/containous/traefik/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1beta1.Ingress: the server does not allow access to the requested resource (get ingresses.extensions)
```

traefik.yaml
```
# We run this with hostnetwork as a workaround for
# hostPort not beeing available with CNI networking
# https://github.com/kubernetes/kubernetes/issues/23920
# https://github.com/kubernetes/kubernetes/issues/31307
# https://github.com/containernetworking/cni/issues/46
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      #
      hostNetwork: true
      #
      nodeSelector:
        role: edge-router
      terminationGracePeriodSeconds: 60
      volumes:
        - name: acme
          hostPath:
            path: /k8s/traefik/acme/
        - name: config
          configMap:
            name: traefik-conf
      containers:
      - image: traefik:v1.2.1
        name: traefik-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/acme/"
            name: "acme"
          - mountPath: "/config"
            name: "config"
        env:
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: cloudflare-secrets
                key: CLOUDFLARE_EMAIL
          - name: CLOUDFLARE_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-secrets
                key: CLOUDFLARE_API_KEY
        args:
        - --web
        - --kubernetes
        - --configFile=/config/traefik.toml
        #- --logLevel=DEBUG
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
omitted stuff
```

sample service
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: whoami
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: whoami
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
spec:
  rules:
  - host: whoami.project-r.space
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80

```

**Comment by timoreimann** [comment]
`the server does not allow access to the requested resource` sounds more like an auth configuration problem on your cluster part. Are you sure things are set up correctly in this regard?

/cc @dtomcej who I think helped someone with a similar situation problem on Slack the other day.

**Comment by JesusMtnez** [comment]
I have had the same problem trying to deploy Traefik in my 5 RPis Cluster with a `kubeadm` standard installation. The logs are the same:

```
ERROR: logging before flag.Parse: E0405 15:53:57.460231       1 reflector.go:214] github.com/containous/traefik/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Service: the server does not allow access to the requested resource (get services)
ERROR: logging before flag.Parse: E0405 15:53:57.478878       1 reflector.go:214] github.com/containous/traefik/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1beta1.Ingress: the server does not allow access to the requested resource (get ingresses.extensions)
ERROR: logging before flag.Parse: E0405 15:53:57.490720       1 reflector.go:214] github.com/containous/traefik/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Endpoints: the server does not allow access to the requested resource (get endpoints)
```

**Comment by emilevauge** [comment]
Maybe due to RBAC https://github.com/kubernetes/kubeadm/issues/212#issuecomment-290908868

**Comment by patte** [comment]
First I found a workaround I don't recommend:
https://kubernetes.io/docs/admin/authorization/rbac/#permissive-rbac-permissions
`WARNING: The following policy allows ALL service accounts to act as cluster administrators. Any application running in a container receives service account credentials automatically, and could perform any action against the API, including viewing secrets and modifying permissions. This is not a recommended policy.`
```
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts
```

Here I'm trying to create a proper ClusterRole, but with no success so far. Does anyone know how to set the params properly. I'm too busy to get into it right now.
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - nodes
    verbs:
      - get
      - list
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: default
```
