### ISSUE TITLE
Client certificate flag per service?

### ISSUE THREAD

**Issue by tj-kev** [containous/traefik#1382]
Is it currently possible to enable the client certificate on a per service basis? Looking at the traefik.toml file documentation I see the following section.

```toml
[entryPoints]
   [entryPoints.https]
   address = ":443"
   [entryPoints.https.tls]
   ClientCAFiles = ["tests/clientca1.crt", "tests/clientca2.crt"]
     [[entryPoints.https.tls.certificates]]
     CertFile = "integration/fixtures/https/snitest.com.cert"
     KeyFile = "integration/fixtures/https/snitest.com.key"
     [[entryPoints.https.tls.certificates]]
     CertFile = "integration/fixtures/https/snitest.org.cert"
     KeyFile = "integration/fixtures/https/snitest.org.key"
```

I am trying to use this with AWS API Gateway to secure access to an API. However I also want to serve standard HTML content outside of API Gateway from the same Docker Swarm. 

If the client certificate setting is global then that would prevent me from doing this. If I can set a single client certificate (provided by AWS API Gateway) and enable it per service based on a flag in docker swarm that would be perfect.

Is this possible? Hope that makes sense.

Thanks
