### ISSUE TITLE
502 bad gateway with k8s when setting image

### ISSUE THREAD

**Issue by shengis** [containous/traefik#1384]
### What version of Traefik are you using (`traefik version`)?
Traefik v1.2.1
Kubernetes 1.4.9
Docker 1.12.6

### What is your environment & configuration (arguments, toml...)?
```toml
    # traefik.toml
    defaultEntryPoints = ["http"]
    
    [entryPoints]
      [entryPoints.http]
      address = ":80"
    
    [kubernetes]
```

### What did you do?
I'm using **three** instances of traefik and **three** instances of "emilevauge/whoami" in a testing namespace of kubernetes

```
$ kubectl get deploy,rc,svc,po --namespace tst-traefik -o wide

NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/whoami   3         3         3            3           50m
NAME         DESIRED   CURRENT   READY     AGE       CONTAINER(S)   IMAGE(S)               SELECTOR
rc/traefik   3         3         3         2h        traefik        traefik:1.2.1-alpine   k8s-app=traefik
NAME          CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE       SELECTOR
svc/traefik   10.115.11.13    <nodes>       80/TCP,8080/TCP   1d        k8s-app=traefik
svc/whoami    10.115.14.178   <none>        80/TCP            50m       app=whoami,environment=tst-traefik
NAME                         READY     STATUS    RESTARTS   AGE       IP             NODE
po/traefik-07ldg             1/1       Running   0          58m       10.110.85.21   worker04
po/traefik-4rpbf             1/1       Running   0          2h        10.110.98.19   worker06
po/traefik-l3m8f             1/1       Running   0          58m       10.110.8.14    worker02
po/whoami-1006074904-25w25   1/1       Running   0          4m        10.110.43.22   worker05
po/whoami-1006074904-e7x0a   1/1       Running   0          4m        10.110.98.22   worker06
po/whoami-1006074904-fdw4u   1/1       Running   0          4m        10.110.8.5     worker02
```

When I'm rolling-update with a set image on the deploy resource :

`kubectl set image deploy/whoami whoami=paulkling/whoami --namespace tst-traefik`

New pods with new internal IPs are sets and old pods are destroyed.

```
$ kubectl get deploy,rc,svc,po --namespace tst-traefik -o wide

NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/whoami   3         3         3            3           52m
NAME         DESIRED   CURRENT   READY     AGE       CONTAINER(S)   IMAGE(S)               SELECTOR
rc/traefik   3         3         3         2h        traefik        traefik:1.2.1-alpine   k8s-app=traefik
NAME          CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE       SELECTOR
svc/traefik   10.115.11.13    <nodes>       80/TCP,8080/TCP   1d        k8s-app=traefik
svc/whoami    10.115.14.178   <none>        80/TCP            52m       app=whoami,environment=tst-traefik
NAME                         READY     STATUS        RESTARTS   AGE       IP             NODE
po/traefik-07ldg             1/1       Running       0          1h        10.110.85.21   worker04
po/traefik-4rpbf             1/1       Running       0          2h        10.110.98.19   worker06
po/traefik-l3m8f             1/1       Running       0          1h        10.110.8.14    worker02
po/whoami-1006074904-25w25   1/1       Terminating   0          7m        10.110.43.22   worker05
po/whoami-1006074904-e7x0a   1/1       Terminating   0          7m        10.110.98.22   worker06
po/whoami-1006074904-fdw4u   1/1       Terminating   0          7m        10.110.8.5     worker02
po/whoami-3264642165-32o2h   1/1       Running       0          6s        10.110.8.21    worker02
po/whoami-3264642165-3yvok   1/1       Running       0          11s       10.110.35.16   worker03
po/whoami-3264642165-rcy3h   1/1       Running       0          11s       10.110.29.17   worker01
```

Traefik webui is showing the changes correctly for some instances of traefik, and sometimes one of the traefik instances is showing old pod informations (see screenshot).

![capture d ecran de 2017-04-04 17-34-53](https://cloud.githubusercontent.com/assets/20049990/24668154/2ef66ddc-1966-11e7-96ab-ba276a85132e.png)

testing :

```
$ while true; do curl -H 'Host: whoami.***.net' http://traefik-tst.***.net ; done

Hostname: whoami-3264642165-rcy3h
IP: 127.0.0.1
IP: ::1
IP: 10.110.29.17
IP: fe80::42:aff:fe6e:1d11
GET / HTTP/1.1
Host: whoami.***.net
User-Agent: curl/7.51.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.110.29.0
X-Forwarded-Host: whoami.***.net
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-07ldg

Hostname: whoami-3264642165-3yvok
IP: 127.0.0.1
IP: ::1
IP: 10.110.35.16
IP: fe80::42:aff:fe6e:2310
GET / HTTP/1.1
Host: whoami.***.net
User-Agent: curl/7.51.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.110.8.0
X-Forwarded-Host: whoami.***.net
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-4rpbf

Bad Gateway

Hostname: whoami-3264642165-32o2h
IP: 127.0.0.1
IP: ::1
IP: 10.110.8.21
IP: fe80::42:aff:fe6e:815
GET / HTTP/1.1
Host: whoami.***.net
User-Agent: curl/7.51.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.110.29.0
X-Forwarded-Host: whoami.***.net
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-07ldg
```

tcpdump from inside traefik:1.2.1-alpine container :
```
15:40:08.090947 IP (tos 0x0, ttl 42, id 14127, offset 0, flags [DF], proto TCP (6), length 134)
    10.110.43.0.58476 > traefik-l3m8f.80: Flags [P.], cksum 0x0fdd (correct), seq 1:83, ack 1, win 229, options [nop,nop,TS val 833353296 ecr 100729358], length 82: HTTP, length: 82
	GET / HTTP/1.1
	Host: whoami.***.net
	User-Agent: curl/7.51.0
	Accept: */*
	
15:40:08.091156 IP (tos 0x0, ttl 64, id 5800, offset 0, flags [DF], proto TCP (6), length 60)
    traefik-l3m8f.52712 > 10.110.98.22.80: Flags [S], cksum 0x7f2e (incorrect -> 0xee54), seq 2145195196, win 28640, options [mss 1432,sackOK,TS val 100729364 ecr 0,nop,wscale 7], length 0
[...]
15:40:09.856737 IP (tos 0x0, ttl 64, id 13218, offset 0, flags [DF], proto TCP (6), length 189)
    traefik-l3m8f.80 > 10.110.43.0.58476: Flags [P.], cksum 0x4899 (incorrect -> 0x4532), seq 1:138, ack 84, win 222, options [nop,nop,TS val 100729819 ecr 833354265], length 137: HTTP, length: 137
	HTTP/1.1 502 Bad Gateway
	Date: Tue, 04 Apr 2017 15:40:09 GMT
	Content-Length: 11
	Content-Type: text/plain; charset=utf-8
	
	Bad Gateway[!http]
```

### Whoami deployment file
```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: whoami
    environment: tst-traefik
  name: whoami
  namespace: tst-traefik
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: whoami
        environment: tst-traefik
    spec:
      containers:
      - name: whoami
        image: emilevauge/whoami
        imagePullPolicy: Always
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
```

### Whoami ingress file
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: tst-traefik
spec:
  rules:
  - host: whoami.***.net
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80
```

### Whoami service file

```yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami
    environment: tst-traefik
  name: whoami
  namespace: tst-traefik
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: whoami
    environment: tst-traefik
```
