### ISSUE TITLE
Status Code based redirection

### ISSUE THREAD

**Issue by vasumathyseenuvasan** [containous/traefik#1387]
### What version of Traefik are you using (`traefik version`)?
v1alpha1

### What is your environment & configuration (arguments, toml...)?

```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
	[entryPoints.http.redirect]
	  entryPoint = "https"
  [entryPoints.https]
  address = ":443"
	[entryPoints.https.tls]
	  [[entryPoints.https.tls.certificates]]
	  CertFile = "**.crt"
	  KeyFile = "**.key"
[web]
address = ":8080"
ReadOnly = true
```

### What did you do?
We have configured Traefik as Load Balancer and for https redirection

### What did you expect to see?
I would like to implement a status code based redirection using Traefik. Similar to how it can be implemented in Nginx now. For instance, if  a entry point return 404/500 i would like to redirect it to our application's custom error page. 

### What did you see instead?
Could not find any documentation/ examples to do status code based redirection
