### ISSUE TITLE
ECS Provider does not offer health check configuration

### ISSUE THREAD

**Issue by bbl232** [containous/traefik#1400]
### What version of Traefik are you using (`traefik version`)?
1.2.0

### What is your environment & configuration (arguments, toml...)?
We're running many instances of Traefik in many ECS clusters...
```toml
accessLogsFile = "/var/log/traefik/access.log"

[web]
address = ":8080"

[ecs]

domain = "$CUSTOMER.$STACK"
Cluster = "$CUSTOMER-$STACK"
Watch = true
RefreshSeconds = 15
ExposedByDefault = true
```

### What did you do?
Searched documentation and code for how to configure the health checks

### What did you expect to see?
A label that I could apply to the containers to configure the health check endpoint and interval

### What did you see instead?
The ecs.tmpl and provider code did not show support for health checks

It seems like this wouldn't be too hard to add, but would be great to support. It would be even better if the health check failure could trigger a re-schedule of the task in ecs... or some sort of configurable hook that would execute on a failed health check.
