### ISSUE TITLE
Enable/Fix rancher-metadata backend config method

### ISSUE THREAD

**Issue by gaieges** [containous/traefik#1402]
It's my understanding that @SantoDE is working on something to enable the ability to have traefik pull from rancher-metadata in the local environment (the fix for the method to pull from the API is in another ticket) as a backend for configuring rules.  

This ticket is to track that as I didn't see another ticket open for it.  Feel free to close if there is.

### What version of Traefik are you using (`traefik version`)?

```
Version:      v1.2.1
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-27_03:19:40PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?

docker-compose handles all this and rancher cli deploys it:

```yml
version: '2'
services:
  traefik:
    image: traefik:1.2-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '443:443'
      - '80:80'
      - '8000:8000'
    command: 
      - --loglevel=debug
      - --rancher
    labels:
      traefik.enabled: 'false'
      io.rancher.container.pull_image: always
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
      io.rancher.container.global: 'true'
```

### What did you do?

Spun up stack in rancher via cli. 

### What did you expect to see?

Expected it to see all of the local environment instances that have `traefik.port` or `traefik.frontend.rule` labels to be present in the traefik web ui

### What did you see instead?

Exception in traefik logs:

```
level=error msg="Cannot get Rancher Environments Unknown schema type [environment]\ngithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClientImpl).doList\n\t/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/common.go:299\ngithub.com/containous/traefik/vendor/github.com/rancher/go-rancher/client.(*EnvironmentClient).List\n\t/go/src/github.com/containous/traefik/vendor/github.com/rancher/go-rancher/client/generated_environment.go:119\ngithub.com/containous/traefik/provider.listRancherEnvironments\n\t/go/src/github.com/containous/traefik/provider/rancher.go:293\ngithub.com/containous/traefik/provider.(*Rancher).Provide.func1.1.1\n\t/go/src/github.com/containous/traefik/provider/rancher.go:253\ngithub.com/containous/traefik/safe.(*Pool).Go.func1\n\t/go/src/github.com/containous/traefik/safe/routine.go:77\ngithub.com/containous/traefik/safe.GoWithRecover.func1\n\t/go/src/github.com/containous/traefik/safe/routine.go:141\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2086"
```
