### ISSUE TITLE
Traefik sending request to ip in ingress network

### ISSUE THREAD

**Issue by mwaaas** [containous/traefik#1403]
### What version of Traefik are you using (`traefik version`)?
Version:      v1.2.1
Codename:     morbier

### What is your environment & configuration (arguments, toml...)?
Using swarm cluster in http://labs.play-with-docker.com/

```yml
version: '3'
services:
  lb:
    image: traefik:latest
    command: >
      --web --docker --docker.swarmmode
      --docker.domain=traefik --docker.watch
      --accesslogsfile=/dev/stdout --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager

  nginx:
    image: 'nginx'
    ports:
      - "7000:80"
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.backend=nginx"
        - "traefik.port=80"
        - "traefik.weight=5"
```

### What did you do?

deployed stack in swarm cluster
### What did you expect to see?

See nginx hello world
### What did you see instead?
Gateway timeout

**NB** It works if I remove ports in nginx. 

After digging for a while noticed that if you define, ports the service will have two networks, the default one and ingress network. 

Traefik is trying to send traffic to the ingress one.
