### ISSUE TITLE
429 Too Many Requests error from acme

### ISSUE THREAD

**Issue by sweber83** [containous/traefik#1425]
### What version of Traefik are you using (`traefik version`)?
1.2.2

### What is your environment & configuration (arguments, toml...)?

```toml
OnHostRule = true
caServer = "https://acme-staging.api.letsencrypt.org/directory"
...
[frontends]
  [frontends.old_dev]
  backend = "old_dev"
    [frontends.old_dev.routes.route_1]
    rule = "Host:..."
```

The Host rule consists of 17 (sub)domains.

### What did you do?
I commented caServer, to use letsencrypt prod server.

### What did you expect to see?
A new production certificate created with 16 SANs.

### What did you see instead?
`Error "429 Too Many Requests"`
