### ISSUE TITLE
Traefik's integration with Marathon is broken after upgrading to Marathon 1.4.2

### ISSUE THREAD

**Issue by erickrmz** [containous/traefik#1427]
### What version of Traefik are you using (`traefik version`)?
v1.2.1

### What is your environment & configuration (arguments, toml...)?

```toml
################################################################
# Global configuration
################################################################

graceTimeOut = 10
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/traefik-access.log"
logLevel = "DEBUG"
ProvidersThrottleDuration = 1
MaxIdleConnsPerHost = 200
InsecureSkipVerify = false
defaultEntryPoints = ["http"]

[web]
address = ":8080"

[marathon]

endpoint = "http://10.20.0.201:8080,10.20.10.201:8080,10.20.20.201:8080"
watch = true
domain = "traefik.service.consul"
exposedByDefault = false
groupsAsSubDomains = false

[marathon.basic]
httpBasicAuthUser = "XXXXX"
httpBasicPassword = "XXXXX"

[retry]
```

### What did you do?

We had Traefik 1.2.1 using Marathon 1.39 as a backend. It's been working fine for the last weeks. We recently decided to upgrade Marathon to version 1.4.2. Once we did that, I checked the Traefik dashboard and we lost all the backends.

### What did you expect to see?

Configuration received from provider marathon should be a big hash containing all of our apps. We want to continue to see the backends in the dashboard of course.

### What did you see instead?

Dashboard looks totally empty. The logs are saying that it's not receiving anything from Marathon:
Configuration received from provider marathon: {}

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-04-12T15:39:10-07:00" level=debug msg="Configuration received from provider marathon: {}" 
time="2017-04-12T15:39:10-07:00" level=info msg="Skipping same configuration for provider marathon" 
time="2017-04-12T15:39:12-07:00" level=debug msg="Marathon event receveivedtype: status_update_event, event: &{status_update_event 2017-04-12T22:39:12.153Z 9e473fe9-01c5-409a-91f6-ff65a208014b-S7 sami_qamr1_apps_abacus-errors-qamr1.d8e7fbb7-1fd0-11e7-a77e-4a8e00763272 TASK_RUNNING  /sami/qamr1/apps/abacus-errors-qamr1 appmr01-nops-us-east-1a.ec2.ssic.internal [%!s(int=31252)] [%!s(*marathon.IPAddress=&{10.20.104.100 IPv4})] 2017-04-12T05:00:33.977Z}" 
time="2017-04-12T15:39:12-07:00" level=debug msg="Configuration received from provider marathon: {}" 
time="2017-04-12T15:39:12-07:00" level=info msg="Skipping same configuration for provider marathon" 
time="2017-04-12T15:39:17-07:00" level=debug msg="Marathon event receveivedtype: status_update_event, event: &{status_update_event 2017-04-12T22:39:17.436Z 9e473fe9-01c5-409a-91f6-ff65a208014b-S7 sami_qamr1_apps_abacus-errors-qamr1.d8e7fbb7-1fd0-11e7-a77e-4a8e00763272 TASK_FAILED Container exited with status 1 /sami/qamr1/apps/abacus-errors-qamr1 appmr01-nops-us-east-1a.ec2.ssic.internal [%!s(int=31252)] [%!s(*marathon.IPAddress=&{10.20.104.100 IPv4})] 2017-04-12T05:00:33.977Z}"
```
