### ISSUE TITLE
tls: unsupported SSLv2 handshake received

### ISSUE THREAD

**Issue by goodforever** [containous/traefik#1428]
### What version of Traefik are you using (`traefik version`)?
1.2.1

### What is your environment & configuration (arguments, toml...)?

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = false
    [entryPoints.https.tls]


[acme]
email = "xxxx@xxxx"
storage = "/acme.json"
entryPoint = "https"
#onDemand = true
#OnHostRule = true

[web]
address = ":8080"
```

### What did you do?
```
time="2017-04-13T03:12:54Z" level=debug msg="ACME got nothing www.domain.com" 
2017/04/13 03:13:00 server.go:2317: http: TLS handshake error from 10.255.0.4:31499: tls: unsupported SSLv2 handshake received
```
