### ISSUE TITLE
Does Traefik support Swarm?

### ISSUE THREAD

**Issue by jakobrosenberg** [containous/traefik#143]
I tried spinning up a master and a few agents with the virtualbox driver. Traefik seems to only see the containers running locally on master.

Am I doing something wrong or is swarm not supported?

**Comment by emilevauge** [comment]
Hi @jakobrosenberg, it seems to be a bug. But it should work with Swarm as it is the same API. Could you provide traefik `debug` logs while starting ?

**Comment by vdemeester** [comment]
@jakobrosenberg I'm also working on adding integration test on swarm to make sure it works and keep working, so logs/repro./… would be super useful :wink:

**Comment by jakobrosenberg** [comment]
To my recollection I followed the instructions on this page. https://docs.docker.com/swarm/install-w-machine

this is my docker-compose.yml
```
web:
    build: . 
    labels:
     - "traefik.port=80"
     - "traefik.backend=mysite"
     - "traefik.frontend.passHostHeader=true"
     - "traefik.frontend.rule=Host"
     - "traefik.frontend.value=mysite.com"
    restart: always
```

The container only shows on the master through docker-machine and the --swarm parameter. ``docker-machine env mysite --swarm``
