### ISSUE TITLE
Default template for kubernetes configuration backend doesn't provide entrypoints

### ISSUE THREAD

**Issue by andrexus** [containous/traefik#1450]
### What version of Traefik are you using (`traefik version`)?
v1.2.3 / morbier

### What is your environment & configuration (arguments, toml...)?

```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Kubernetes configuration backend
[kubernetes]

# Consul catalog configuration backend
[consulCatalog]
endpoint = "10.1.0.101:8500"
domain = "xxx"

# Letsencrypt config
[acme]
email = "xxx"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
...
```

### What did you do?
Configured 2 configuration backends:
  - consulCatalog
  - kubernetes

### What did you expect to see?
both configuration backends have entrypoints

### What did you see instead?
only consulCatalog has entrypoints

---

All default templates besides kubernetes.tmpl declare entrypoints configuration. Having multiple configuration backends with ACME leads to the situation where kubernetes frontends don't have any entrypoint.
Providing custom templates as a workaround fixes the issue.
```toml
[kubernetes]
filename = "/etc/traefik/kubernetes_custom.tmpl"
```
```
[frontends]{{range $frontendName, $frontend := .Frontends}}
  [frontends."{{$frontendName}}"]
  backend = "{{$frontend.Backend}}"
  priority = {{$frontend.Priority}}
  passHostHeader = {{$frontend.PassHostHeader}}
    entrypoints = ["http", "https"] {{/* !!! Workaround !!! */}}
    {{range $routeName, $route := $frontend.Routes}}
    [frontends."{{$frontendName}}".routes."{{$routeName}}"]
    rule = "{{$route.Rule}}"
    {{end}}
{{end}}
```
