### ISSUE TITLE
Traefik on Kubernetes (via. helm) not forwarding the response headers (`Content-Type`, `Content-Encoding`, `Transfer-Encoding`...)

### ISSUE THREAD

**Issue by kminehart** [containous/traefik#1457]
### What version of Traefik are you using (`traefik version`)?
`v1.2.1`

### What is your environment & configuration (arguments, toml...)?

`helm install stable/traefik`

values:

```yaml
dashboard:
  enabled: true
  domain: traefik.redacted.io
  auth:
    basic:
      kminehart: redacted
```

### What did you do?

Started Prometheus via. helm, and added the following options:

```yml
server:
  ingress:                                               
    enabled: true                                        
    annotations: {                                       
      kubernetes.io/ingress.class: "traefik"             
    }                                                           
    hosts: [                                             
      "prometheus.redacted.io"                    
    ]                                                    
```

The ingress is created successfully and is visible in the Traefik dashboard.

### What did you expect to see?

Prometheus' main API endpoint should return valid data (which is called via. ajax).

When using kubectl port-forward to the pod itself, you receive the response headers: (/api/v1/label/__name__/values)

```
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json
Date: Tue, 18 Apr 2017 14:49:44 GMT
Transfer-Encoding: chunked
access-control-allow-headers: Accept, Authorization, Content-Type, Origin
access-control-expose-headers: Date
```
### What did you see instead?

When accessing that same endpoint through Traefik, I see:

```
Date: Tue, 18 Apr 2017 14:47:03 GMT
Vary: Accept-Encoding
X-Firefox-Spdy: h2
```

And the response looks like: (a jumbled mess of bad encoding).

```
‹��	nˆ�ÿœ][“#+rþ/óì‡=g}"ûÖGÝ½31Ó#Ií	Ûá h*UÅŠ†‹Ô:ÿ÷
 ªT.Õû6ß—™@rÅüß'm°±úÓß>iKhýéß>UØàOûŸO¸j©ÖTpôÓ
ƒÜ(Á(„«Ê13Œ
¤iò”Ÿ, †
prû�a¹ùˆ‚¶mž~êŒ*«°¡‚€ºÆ”©BgŠ¤ÔRðÓ‚6÷‚Hp‚‚Fo–œ¡DZSPÊˆ	£Åê¶Žµ¶NÏíê¶¦n(Á*dõ]Åõ+‚«ÕB¡(TÊOÂÉ7˜rPˆH‹ÈI#	ŠŠJ##fQ†i”0†Aõ!®"x’«oÚ@[ Yk(r@e('(htR�	(®&±Jo–9bh›3lDº­“ÇI#F[jÐÛÍ€žC
pAÙ14jAÕPåQH1B­`\5©X…†ŠšïÕòöw%çHVÎ°6Hð‰´…V¸A…I1à„)#³†AVEëêJë˜X_±ŒÉS±é`—Û(¯‘†Xûs0>ù) @/]1Óæ<PJ¨5D‰]BÔ¨RBÊhôSi¦Q˜ë¡?¯!Í˜ëí]¨,©š(,»`M	Äg—ðâ˜Ÿ¦ân°šµ¤Çº6Oö1Çu§4Ñ`e&Ih¬ÏÚ‘Œëý`H…`ÒeL7"p3šr–xCMuÓôf`ãªŠNƒk©.»›#ôâ3òZjÎ”¸B0ÅaFœá¾º¹K\‚¹‹ªÉhi34f(èõµT%¬¡º²Zh]wÐ3&ÈÐ£È0TÆ¸[:¡ëÆÍÝÑÜ×­IR©,3Vy˜V2(·:‹·�1QH¬¡Êxíy)ÛýäS“ù@œP„8[/»õn'°ÐÉÒ¾u„”i­–˜çÔ=žÒæðî‹aÂ4.%4µÁäœ©7àIí‘¼1FCnèé-%JÜC]&

```
