### ISSUE TITLE
Permissions issues with Kubernetes ConfigMap

### ISSUE THREAD

**Issue by mellotron** [containous/traefik#1459]
### What version of Traefik are you using (`traefik version`)?

v1.2.3

### What is your environment & configuration (arguments, toml...)?

Kubernetes configuration YAML of:

<details>

```yml
---
apiVersion:
extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          hostPath:
            path: /srv/configs/acme.json
      containers:
        - image: containous/traefik:v1.2.3
          name: traefik-ingress-lb
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/acme/acme.json"
              name: "acme"
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
            - containerPort: 8080
          args:
            - --configfile=/config/traefik.toml
            - --web
            - --kubernetes
            - --logLevel=DEBUG
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "myemail@domain.com"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "domain.com"
```
</details>

### What did you do?

I'm trying to deploy Traefik as the ingress controller with my Kubernetes cluster to use Let's Encrypt, however, when I use the above configuration, I see the following error in my logs:

```
time="2017-04-18T20:13:53Z" level=info msg="Starting server on :80" 
time="2017-04-18T20:13:53Z" level=warning msg="ACME.StorageFile is deprecated, use ACME.Storage instead" 
time="2017-04-18T20:13:53Z" level=info msg="Loading ACME Account..." 
time="2017-04-18T20:13:53Z" level=error msg="Error creating TLS config: permissions 755 for /acme/acme.json are too open, please use 600" 
time="2017-04-18T20:13:53Z" level=fatal msg="Error preparing server: permissions 755 for /acme/acme.json are too open, please use 600"
```

It isn't clear to me how I can set the permissions with Kubernetes, I found references to defaultMode and mode options in the API but none of these work with the above config, nor could I find pointers in any docs online.

The above config is taken from https://blog.osones.com/en/kubernetes-ingress-controller-with-traefik-and-lets-encrypt.html
