### ISSUE TITLE
Docker swarm mode behind Traefik

### ISSUE THREAD

**Issue by da4nik** [containous/traefik#1463]
Hello !

I am trying to run configuration with docker swarm cluster behind traefik. Traefik is outside of docker cluster. I am using docker backend and autoconfiguring works fine besides one thing, it returns service IPs inside swarm network, but not docker node ips. As a result services are not accessible.

Is it possible to implement this scheme currently, or I am missing something in config ?

Services will be in different networks, so I can't run traefik inside swarm
docker config
```toml
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.ru"
watch = true
swarmmode = true
exposedbydefault = true
```

and instead of `http://192.168.1.33:4945`, I am getting `http://10.255.0.2:4945` for service
