### ISSUE TITLE
Implement Auth by frontend for other providers

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#1465]
Implement the "Auth by Frontend" Configuration into the others provider.

References: #1147 

- [x] Docker
- [x] Rancher
- [x] Marathon
- [x] Kubernetes
- [x] ECS
- [ ] Eureka
- [x] Consul catalog
- [x] Mesos
- [x] ZooKeeper

**Comment by timoreimann** [comment]
Feature is available on Marathon. Updated the issue description to better see what we've got and what's yet missing.

**Comment by joanayma** [comment]
Why isn't file provider listed?

**Comment by ldez** [comment]
@joanayma because it's the first implementation.

> for other providers

**Comment by joanayma** [comment]
@ldez Ok, thanks. I thought it. But I was trying to implement [frontend-based auth basic] and did not find any docs.

**Comment by ldez** [comment]
@joanayma
```toml
[frontends]
 [frontends.frontend1]
 backend = "backend1"
   [frontends.frontend1]
    basicAuth = ["user1:pass1", "user2:pass2", "user3:pass3"]
```

**Comment by joanayma** [comment]
Thanks a lot!

El dia 29 set. 2017 20:56, "Ludovic Fernandez" <notifications@github.com>
va escriure:

@joanayma <https://github.com/joanayma>

[frontends]
 [frontends.frontend1]
 backend = "backend1"
   [frontends.frontend1]
    basicAuth = ["user1:pass1", "user2:pass2", "user3:pass3"]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/containous/traefik/issues/1465#issuecomment-333209893>,
or mute the thread

**Comment by joanayma** [comment]
A more complex example for specific rule on example.org:
```toml
[frontends]
  [frontends.example1]
    rule = "Host: example.org, www.example.org"
    priority = 10
    passHostHeader = true
    basicAuth = ["user1:$basicauth", "user2:$basicauth"]
    backend = "backend1"
  [frontends.default]
    priority = 1
    passHostHeader = true
    backend = "backend1"
```

Maybe will be good to add it to documentation.
