### ISSUE TITLE
Urls whose path begin '//' don't route properly.

### ISSUE THREAD

**Issue by kobeyu** [containous/traefik#1472]
When trying to access paths like `www.example.com//test`, this gets through to the end webserver as a request for `GET http://test HTTP/1.1` instead of `GET //test HTTP/1.1`

the example server I'm using here doesn't mind this, since it ignores the requested path. But [the server I am using](https://github.com/vassilvk/nuget-feed-docker) gets **really** confused.

### What version of Traefik are you using (`traefik version`)?
v1.2.3 (docker)

### What is your environment & configuration (arguments, toml...)?
docker compose:
```yml
version: '2'
services:
  testtraefik:
    image: traefik
    command: --web --docker --loglevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  hello:
    image: 'crccheck/hello-world'
    restart: always
    labels:
        - "traefik.backend=hello"
        - "traefik.frontend.rule=Host:hello.example.com"
```
### What did you do?
visited `hello.example.com//test` (yes, double slash) (hosts file overridden to the appropriate IP address), and viewed the logs of the hello world container with `docker logs dir_hello_1`

### What did you expect to see?
`GET //test HTTP/1.1...`

### What did you see instead?
`GET http://test HTTP/1.1`

### If applicable, please paste the log output in debug mode (`--debug` switch)
```
time="2017-04-20T14:54:29Z" level=debug msg="Round trip: http://172.21.0.3:8000, code: 200, duration: 2.9879ms"
time="2017-04-20T14:54:33Z" level=debug msg="Round trip: http://172.21.0.3:8000, code: 200, duration: 1.9899ms"
time="2017-04-20T14:54:37Z" level=debug msg="Round trip: http://172.21.0.3:8000, code: 200, duration: 1.2465ms"
time="2017-04-20T14:54:39Z" level=debug msg="Round trip: http://172.21.0.3:8000, code: 200, duration: 2.248ms"
time="2017-04-20T14:55:02Z" level=debug msg="Round trip: http://172.21.0.3:8000, code: 200, duration: 2.2853ms"
```
