### ISSUE TITLE
docker.lts option seems not functional

### ISSUE THREAD

**Issue by SLE-TheRealOne** [containous/traefik#1478]
Hi,

Looked the 350+ opened issues without finding answer so opening another one

### Context

Trying to use a Sonatype Nexus 3 instance, running on a docker container, as a private registry.
Traefik is used to declare the nexus container as a backend.

### What version of Traefik are you using (`traefik version`)?

1.2.3 morbier

### What is your environment & configuration (arguments, toml...)?

```toml
# traefik.toml
 
# Set Debug
debug = true
 
# Default EntryPoint
defaultEntryPoints = ["http", "https"]
 
# Docker configuration
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "${myDomain}"
# Auto update Traefik configuration
watch = true
exposedbydefault = true
cdusebindportip = true

[docker.tls]
ca = "/etc/traefik/IR.crt"
cert = "/etc/traefik/${hostName}.pem"
key = "/etc/traefik/${hostName}.key"
insecureskipverify = true
 
# Entrypoints http and https
[entryPoints]
  [entryPoints.http]
  address = ":${httpPort}"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":${httpsPort}"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
     certFile = "/etc/traefik/${hostName}.pem"
      keyFile = "/etc/traefik/${hostName}.key"
 
# Traefik interface
[web]
address = ":${webPort}"

```

### What did you do?

Just try to run with following command

```
 docker run -d -p ${httpPort}:${httpPort}-p ${webPort}:${webPort}-p ${httpsPort}:${httpsPort}-v /sources/traefik:/etc/traefik:Z -v /var/run/docker.sock:/var/run/docker.sock:Z --name traefik --restart=always traefik
````

### What did you expect to see?

A working instance of traefik with functional dashboard. A log like this

`root@docker:~# docker logs traefik`
```shell
time="2017-04-21T15:52:50Z" level=info msg="Traefik version v1.2.3 built on 2017-04-13_07:21:10PM"
time="2017-04-21T15:52:50Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2017-04-21T15:52:50Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":true,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":${httpPort}\",\"TLS\":null,\"Redirect\":{\"EntryPoint\":\"https\",\"Regex\":\"\",\"Replacement\":\"\"},\"Auth\":null,\"Compress\":false},\"https\":{\"Network\":\"\",\"Address\":\":${httpsPort}\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":[{\"CertFile\":\"/etc/traefik/ouranos.pem\",\"KeyFile\":\"/etc/traefik/ouranos.key\"}],\"ClientCAFiles\":null},\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"${myDomain}\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false},\"File\":null,\"Web\":{\"Address\":\":${webPort}\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null}"
time="2017-04-21T15:52:50Z" level=info msg="Preparing server http &{Network: Address::${httpPort} TLS:<nil> Redirect:0xc42046e270 Auth:<nil> Compress:false}"
time="2017-04-21T15:52:50Z" level=info msg="Preparing server https &{Network: Address::${httpsPort} TLS:0xc420338e40 Redirect:<nil> Auth:<nil> Compress:false}"
time="2017-04-21T15:52:50Z" level=info msg="Starting server on :${httpPort}"
time="2017-04-21T15:52:50Z" level=warning msg="Error checking new version: Get https://update.traefik.io/repos/containous/traefik/releases: dial tcp: lookup update.traefik.io on 10.75.70.149:53: no such host"
time="2017-04-21T15:52:50Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"${myDomain}\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false}"
time="2017-04-21T15:52:50Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":${webPort}\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Auth\":null}"
time="2017-04-21T15:52:50Z" level=info msg="Starting server on :${httpsPort}"
time="2017-04-21T15:52:50Z" level=debug msg="Docker connection established with docker 1.9.1 (API 1.21)"
time="2017-04-21T15:52:50Z" level=debug msg="Load balancer method '<nil>' for backend backend-traefik: Invalid method, using default. Using default wrr."
time="2017-04-21T15:52:50Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik\":{\"servers\":{\"server-traefik\":{\"url\":\"http://172.17.0.2:${httpsPort}\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-Host-traefik-docker-ls-fr-ingdirect-intranet\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-traefik\",\"routes\":{\"route-frontend-Host-traefik-docker-ls-fr-ingdirect-intranet\":{\"rule\":\"Host:traefik.${myDomain}\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2017-04-21T15:52:50Z" level=debug msg="Last docker config received more than 2s, OK"
time="2017-04-21T15:52:50Z" level=debug msg="Creating frontend frontend-Host-traefik-docker-ls-fr-ingdirect-intranet"
time="2017-04-21T15:52:50Z" level=debug msg="Wiring frontend frontend-Host-traefik-docker-ls-fr-ingdirect-intranet to entryPoint http"
time="2017-04-21T15:52:50Z" level=debug msg="Creating route route-frontend-Host-traefik-docker-ls-fr-ingdirect-intranet Host:traefik.${myDomain}"
time="2017-04-21T15:52:50Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\\/\\/)?([\\w\\._-]+)(?::\\d+)?(.*)$ -> https://$1:${httpsPort}$2"
time="2017-04-21T15:52:50Z" level=debug msg="Creating backend backend-traefik"
time="2017-04-21T15:52:50Z" level=debug msg="Creating load-balancer wrr"
time="2017-04-21T15:52:50Z" level=debug msg="Creating server server-traefik at http://172.17.0.2:${httpsPort} with weight 0"
time="2017-04-21T15:52:50Z" level=debug msg="Wiring frontend frontend-Host-traefik-docker-ls-fr-ingdirect-intranet to entryPoint https"
time="2017-04-21T15:52:50Z" level=debug msg="Creating route route-frontend-Host-traefik-docker-ls-fr-ingdirect-intranet Host:traefik.${myDomain}"
time="2017-04-21T15:52:50Z" level=debug msg="Creating backend backend-traefik"
time="2017-04-21T15:52:50Z" level=debug msg="Creating load-balancer wrr"
time="2017-04-21T15:52:50Z" level=debug msg="Creating server server-traefik at http://172.17.0.2:${httpsPort} with weight 0"
time="2017-04-21T15:52:50Z" level=info msg="Server configuration reloaded on :${httpPort}"
time="2017-04-21T15:52:50Z" level=info msg="Server configuration reloaded on :${httpsPort}"
```

### What did you see instead?

```
time="2017-04-21T15:40:44Z" level=debug msg="Docker connection established with docker  (API )"
time="2017-04-21T15:40:44Z" level=error msg="Failed to list containers for docker, error An error occurred trying to connect: Get https://%2Fvar%2Frun%2Fdocker.sock/v1.21/containers/json?limit=0: http: server gave HTTP response to HTTPS client"
```

### Interesting notes

Problem is clearly related to trying to activate tls for docker

```toml
[docker.tls]
ca = "/etc/traefik/IR.crt"
cert = "/etc/traefik/${hostName}.pem"
key = "/etc/traefik/${hostName}.key"
insecureskipverify = true
```
If commenting those lines, we got a functional traefik without problem.
IR.crt is a concatenation of all certificates from all the CA chain (Intermediate first, then Root)
* Intermediate signs ${hostName}.pem
* Root signs intermediate

### First analysis

Seems that, with docker.lts option activated in toml configuration file, than https is used rather than unix protocol to retrieve containers. Seems a bug to me
