### ISSUE TITLE
[Help] TLS certs and HTTPS redirection 

### ISSUE THREAD

**Issue by klud1** [containous/traefik#1479]
I'm starting with traefik, and testing it today i in a RPi 3 i've faced the following problem.
### What version of Traefik are you using (`traefik version`)?
1.2.3
### What is your environment & configuration (arguments, toml...)?
Deploying using `docker stack deploy ...`
```yml
version: "3"
services:
  traefik:
    image: hypriot/rpi-traefik:v1.2.3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/xt-str/traefik/log:/log/traefik"
    command: "--accesslogsfile=/log/traefik/traefik.log \
    --traefiklogsfile=/log/traefik/access.log \
    --checknewversion \
    --loglevel='ERROR' \
    --entrypoints='Name:http Address::80 Redirect.EntryPoint:https' \
    --entrypoints='Name:https Address::443' \
    --defaultentrypoints='http,https' \
    --acme \
    --acme.email='amailname@maildomain.tld' \
    --acme.onhostrule \
    --web \
    --docker \
    --docker.swarmmode \
    --docker.domain=traefik.local \
    --docker.watch"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - network-name
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  network-name:
    external: true
```
### What did you do?
Enable acme tag for let's encrypt certs generation and https redirection.
### What did you expect to see?
a domain with `https` enabled.
### What did you see instead?
No certs are generated, and the redirection sends me to `http://sub.domain.tld:443` instead of `https://sub.domain.tld`

### Here's an example of one of the services i'm deploying
```yml
version: "3"
networks:
 network-name:
    external: true
  network-2-name:
    external: true
services:
  db:
    image: klud/postgres:9.6-alpine-armhf
    networks:
      - network-2-name
    volumes:
      - /var/lib/xt-str/dbs/postgres/gitea:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    deploy:
      placement:
        constraints:
         - node.hostname == worker_name
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
  backend:
    image: registry.gitlab.com/klud/gitea:1.1.0-133-g4bea219
    networks:
      - network-name
      - network-2-name
    ports:
      - 23:22
    volumes:
      - /var/lib/xt-str/gitea/data:/data
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=network-name"
        - "traefik.frontend.rule=Host:sub.domain.tld"
      placement:
        constraints:
          - node.hostname == worker_name
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
```
