### ISSUE TITLE
Traefik do not get frontend/backend from traefik.toml

### ISSUE THREAD

**Issue by comprateur** [containous/traefik#1492]
### What version of Traefik are you using (`traefik version`)?
Morbier

### What is your environment & configuration (arguments, toml...)?

`docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`

traefik.toml 
```toml
################################################################
# Global configuration
################################################################
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
################################################################
# Web configuration backend
################################################################
# Enable web configuration backend
# Optional
	[web]
# Web administration port
# Required
	address = "8080"
################################################################
# File configuration backend
################################################################
# Enable file configuration backend
# Optional
	[file]
	filename = "servers.toml"

# Enable watch file changes
	watch = true
```

servers.toml
```toml
[backends]
## Traefik WebUI
[backends.traefik]
        [backends.traefik.servers.server1]
            url = "http://192.168.1.102:8080"
## Router
[backends.router]
        [backends.router.servers.server1]
            url = "http://192.168.1.1"
## Plex
[backends.plex]
        [backends.plex.servers.server1]
            url = "http://192.168.1.2:32400"
## External sites
[backends.pastebin]
        [backends.pastebin.servers.server1]
            url = "http://www.google.com"

[frontends]
## Traefik WebUI
[frontends.traefik]
    backend = "traefik"
    entrypoints = ["http"]
        [frontends.traefik.routes.traefik_1]
        rule = "Host:traefik.mydomain.com"
## Router
    [frontends.router]
    backend = "router"
    entrypoints = ["http"]
        [frontends.router.routes.router_1]
        rule = "Host:router.mydomain.com"
## Plex 
[frontends.plex]
    backend = "plex"
    entrypoints = ["http"]
        [frontends.plex.routes.plex_1]
        rule = "Host:plex.mydomain.com"
## External sites
[frontends.pastebin]
    backend = "pastebin"
    entrypoints = ["http"]
        [frontends.pastebin.routes.pastebin_1]
        rule = "Host:pastebin.mydomain.com"
```

### What did you expect to see?
To access to the backends using the rules/

### What did you see instead?
404 page

### If applicable, please paste the log output in debug mode (`--debug` switch)
How to setup the log?
