### ISSUE TITLE
Traefik doesn't `hot` detect newly added containers when using the consul_catalog provider

### ISSUE THREAD

**Issue by makeittotop** [containous/traefik#1514]
### Do you want to request a *feature* or report a *bug*?
Bug. 

### What did you do?
Up-scaling the number of web-app docker containers via Nomad, traefik picks up the changes from the consul catalog only after a restart.

On the other hand, down-scaling changes are picked up immediately. 

I wonder what exactly am I doing wrong? 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Using traefik ver1.2.3 (latest) with consul_catalog + nomad as  container orchestrator.

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
checkNewVersion = false
traefikLogsFile = "log/traefik.log"
accessLogsFile = "log/access.log"
logLevel = "DEBUG"
ProvidersThrottleDuration = 5
defaultEntryPoints = ["http"]

[consulCatalog]
  endpoint = "192.168.39.203:8500"
  constraints = ["tag==public"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

[web]
  address = ":8080"

[web.statistics]
   RecentErrors = 10

[consul]
  endpoint = "192.168.39.203:8500"
  watch = true
  prefix = "traefik"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
INFO[0062] Skipping same configuration for provider consul_catalog
```
