### ISSUE TITLE
Traefik not starting qnap tvs-682 4.3.3

### ISSUE THREAD

**Issue by mdhwoods** [containous/traefik#1518]
### Do you want to request a *feature* or report a *bug*?

Traefik does not seem to be starting.  

### What did you do?

Installed Traefik, modified just the listening ip.  Set apache to listen on a different ip.

### What did you expect to see?

access to the Traefik web gui

### What did you see instead?
Nothing. Traefik does not seem to be starting at all.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Entrypoints definition
#
# Optional
# Default:
 [entryPoints]
   [entryPoints.http]
   address = "192.168.1.11:80"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
#
# Optional
#
 [web]

# Web administration port
#
# Required
#
 address = "192.168.1.11:8080"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
