### ISSUE TITLE
Cloudflare domain record generation

### ISSUE THREAD

**Issue by thomas15v** [containous/traefik#1536]
Now that we have the ability to create any docker container and assign it to a domain, wouldn't it be amazing that traefik also could create the domain in question using the cloudflare api?

This has a pretty powerful use case if you work with dynamic test servers that need to be assigned to specified domains and don't want to be bothered to setup domain addresses. 

Example: 
```toml
[cloudflare]
# authentication block (haven't looked in how it works)
key = "Some random key"

# generate domain names on defined host rules
onHostrule = true

# Clean up older domains when not being used anymore
cleanUp = false

# static domain definitions
[cloudflare.domains]
```
