### ISSUE TITLE
How to make traefik listen on more than one network for many services within many networks

### ISSUE THREAD

**Issue by gdeverlant** [containous/traefik#1543]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

**In DOCKER SWARM MODE**

I created a cluster of 3 dbs instance with docker-compose

in one of the instance inside the yml I have set the following ;

```yml
coordinator1:
    image: arangodb/arangodb:3.2
environment:
      - ARANGO_NO_AUTH=1
    labels:
      - traefik.port = 8529
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator1:8529 --cluster.my-local-info coord1  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
      - /mnt/virtual/docker/containers/arangodb3/data/coordinator1:/var/lib/arangodb3
      - /mnt/virtual/docker/containers/arangodb3/apps/coordinator1:/var/lib/arangodb3-apps
      - /mnt/virtual/docker/containers/arangodb3/logs/coordinator1:/var/log/arangodb3
    networks:
      - arango-net
    ports: ['8529:8529']

```

I've created a traefik service with 2 ingress network
 1. new traefik-net
 2. arangodb3-cluster_arango-net which was **automatically** created earlier from the CLI
**docker stack deploy -c docker-compose.yml arangodb3-cluster**

```
docker service create \
    --name traefik \
    --constraint=node.role==manager \
	--publish 80:80 --publish 8080:8080 \
	--mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
	--network traefik-net \
	--network arangodb3-cluster_arango-net \
    hypriot/rpi-traefik \
    --docker \
    --docker.swarmmode=true \
    --docker.watch=true \
	--docker.domain=traefik \
	--docker.exposedbydefault=true \
    --web
```

### What did you expect to see?

The service listed inside traefik admin control panel
I thought that traefik will scan both networks and check services with label traefik.port = 8529

### What did you see instead?

Nothing listed to port 8529

### Output of `traefik version`:

```
 1.2.3 morbier
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
dynanic settings via labels
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by gdeverlant** [comment]
Idez this is not a feature it is a BUG

**Comment by gdeverlant** [comment]
I tested again and I tried to run...

- Traefik
- Whoami

On both networks and it works well

```
docker service create \
    --name traefik \
    --constraint=node.role==manager \
	--publish 80:80 --publish 8080:8080 \
	--mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
	--network arangodb3-cluster_traefik-net \
	--network arangodb3-cluster_arango-net \
    hypriot/rpi-traefik \
    --docker \
    --docker.swarmmode=true \
    --docker.watch=true \
	--docker.domain=traefik \
	--docker.exposedbydefault=true \
    --web
```

```
docker service create \
    --name whoami0 \
    --label traefik.port=80 \
    --network arangodb3-cluster_traefik-net \
    --network arangodb3-cluster_arango-net \
    admiralobvious/whoami-aarch64
```

![traefik whoami-2networks](https://cloud.githubusercontent.com/assets/26530975/25741336/8dc560f2-318a-11e7-91ef-a7f5a2ecf0e9.png)

The problem arises when I run a docker stack command with:
**docker stack deploy -c docker-compose.yml arangodb3-cluster**

with the content of the yaml file:

```
version: "3"
services:
  agency1: 
    image: arangodb/arangodb-arm64:3.2
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address tcp://agency1:8529 --server.authentication false --agency.size 1 --agency.activate true --agency.supervision true --log.file /var/log/arangodb3/arangod.log
    volumes:
      - /mnt/virtual/docker/containers/arangodb3/logs/agency1:/var/log/arangodb3
    networks:
      - traefik-net
      - arango-net
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm64
          - node.labels.db-systems == arangodb3.rethinkdb
          - node.labels.db-node == master
          - node.labels.isAgency == true
          - node.labels.isCoordinator == false
          - node.labels.isDBReplicate == false
          - node.labels.hasHDD == true
          
  coordinator1:
    image: arangodb/arangodb-arm64:3.2
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator1:8529 --cluster.my-local-info coord1  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
      - /mnt/virtual/docker/containers/arangodb3/data/coordinator1:/var/lib/arangodb3
      - /mnt/virtual/docker/containers/arangodb3/apps/coordinator1:/var/lib/arangodb3-apps
      - /mnt/virtual/docker/containers/arangodb3/logs/coordinator1:/var/log/arangodb3
    networks:
      - traefik-net
      - arango-net
    deploy:
      labels:
        - traefik.port = 8529
      placement:
        constraints:
          - node.labels.arch == arm64
          - node.labels.db-systems == arangodb3.rethinkdb
          - node.labels.db-node == slave
          - node.labels.isAgency == false
          - node.labels.isCoordinator == true
          - node.labels.isDBReplicate == false
          - node.labels.hasHDD == true
          
    ports: ['8529:8529']
    depends_on:
      - agency1
      
  db1:
    image: arangodb/arangodb-arm64:3.2
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db1:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
    volumes:
      - /mnt/virtual/docker/containers/arangodb3/data/db1:/var/lib/arangodb3
      - /mnt/virtual/docker/containers/arangodb3/logs/db1:/var/log/arangodb3
    networks:
      - traefik-net
      - arango-net
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm64
          - node.labels.db-systems == arangodb3.rethinkdb
          - node.labels.db-node == slave
          - node.labels.isAgency == false
          - node.labels.isCoordinator == false
          - node.labels.isDBReplicate == true
          - node.labels.hasHDD == true
    depends_on:
      - agency1
      - coordinator1
      
networks:
    traefik-net:
        driver: overlay
        ipam:
            driver: default
    arango-net:
        driver: overlay
        ipam:
            driver: default
```

![traefik whoami-2networks](https://cloud.githubusercontent.com/assets/26530975/25741038/4d1d6ece-3189-11e7-9992-a0b939cc5ae7.png)

As you can see the **arangodb3-cluster_coordinator1** service is not detected by traefik.

If you look at the details of the **arangodb3-cluster_coordinator1** service you can see that it has the **traefik.port = 8529** label.

![service_view](https://cloud.githubusercontent.com/assets/26530975/25741421/17805892-318b-11e7-8255-44e5e28ab039.png)
