### ISSUE TITLE
Traefik cannot connect to /var/run/docker.sock while Portainer container on same host can (Docker swarm Mode)

### ISSUE THREAD

**Issue by Routhinator** [containous/traefik#1545]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Mounted /var/run/docker.sock to the container.

### What did you expect to see?
Working Traefik proxying Portainer.

### What did you see instead?
Errors connecting to the docker daemon on Traefik, successful start of Portainer.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Latest
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Relevant traefik.toml
```toml
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedbydefault = false
swarmmode = true
```

Relevant docker-compose
```yaml

  proxy:
    image: custom-repo/traefik
    deploy:
      mode: global
      restart_policy:
        condition: any
    environment:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

  portainer:
    image: portainer/portainer
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
      - "traefik.enable=true"
      - "traefik.backend=microbot"
      - "traefik.frontend.rule=Host:portainer.example.com"
      - "traefik.frontend.entryPoints=https"
      - "traefik.docker.network=infrastructure_proxy"
    expose:
      - "9000"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-05-04T02:53:37Z" level=error msg="Failed to list services for docker swarm mode, error Cannot connect to the Docker daemon. Is the docker daemon running on this host?" 
time="2017-05-04T02:53:37Z" level=error msg="Docker connection error Cannot connect to the Docker daemon. Is the docker daemon running on this host?, retrying in 917.800683ms" 
time="2017-05-04T02:53:38Z" level=error msg="Failed to list services for docker swarm mode, error Cannot connect to the Docker daemon. Is the docker daemon running on this host?" 
time="2017-05-04T02:53:38Z" level=error msg="Docker connection error Cannot connect to the Docker daemon. Is the docker daemon running on this host?, retrying in 2.726923256s" 
time="2017-05-04T02:53:41Z" level=error msg="Failed to list services for docker swarm mode, error Cannot connect to the Docker daemon. Is the docker daemon running on this host?" 
time="2017-05-04T02:53:41Z" level=error msg="Docker connection error Cannot connect to the Docker daemon. Is the docker daemon running on this host?, retrying in 3.720770743s" 
time="2017-05-04T02:53:45Z" level=error msg="Failed to list services for docker swarm mode, error Cannot connect to the Docker daemon. Is the docker daemon running on this host?" 
time="2017-05-04T02:53:45Z" level=error msg="Docker connection error Cannot connect to the Docker daemon. Is the docker daemon running on this host?, retrying in 6.081475629s" 
time="2017-05-04T02:53:51Z" level=error msg="Failed to list services for docker swarm mode, error Cannot connect to the Docker daemon. Is the docker daemon running on this host?" 
time="2017-05-04T02:53:51Z" level=error msg="Docker connection error Cannot connect to the Docker daemon. Is the docker daemon running on this host?, retrying in 8.128386818s" 
time="2017-05-04T02:53:59Z" level=error msg="Failed to list services for docker swarm mode, error Cannot connect to the Docker daemon. Is the docker daemon running on this host?" 
time="2017-05-04T02:53:59Z" level=error msg="Docker connection error Cannot connect to the Docker daemon. Is the docker daemon running on this host?, retrying in 18.514221469s" 
```
