### ISSUE TITLE
Garbage response?

### ISSUE THREAD

**Issue by olalonde** [containous/traefik#1547]
I just installed traeffik through Helm / K8s. I can access the dashboard at (traefik.mydomain.com). However, when trying to set up an Ingress resource, the response I'm getting is garbage:

```
��;�v�8������u�-ۉ�#�I��v2�3����HX$��e��/�������-�ɢ/��ޓ=3>IL U�B�p�������% d�����B����}'������Bn��X1�/���?��=� ��ȁ�ʙ�g��]�@��&_Rz5�~�?�1�,�*.,�$���/��I��Gd`]Q�H��!��`��+�[7��TR���!t(��4J�� �u��� �`LJ���	�1�¯q��l'xuK"~	!�L��`I.Wh9!v��8a�HS.H�_�%�!yq����iW��i"�\& �$ײu����Z��hAc�-�9�cR�	����0��+aB��|{�LCa�(	=�|���|�+,�ayT$!^��(��NC ���Zh��F1V�������- ��	����u+T�,�ځ�P�)�Me@��=���~9��SRa������ɧˢy-Y��H22д������!)p�L��$��d��@Ve���T�C�p��G �� nʉ�ۘ���mN&'[?���B���B�p(���G�X�B����nX�7��q�#X)�}T]�P�I�99�fpжn/�>�W ��F=��	���Km�-Pum�C��sั��g��w1�5���g�8�~l��R5c�"6H�H�WkfDڒF�+��uq۰|�|�R.%u�C�,��Mk
```

I tried curl'ing the service from within the cluster and it works. Any idea what might cause traefik to return such garbage data?

Here's my Ingress resource:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "metabase-ingress"
  labels:
    app: "metabase"
spec:
  rules:
  - host: metabase.staging.mydomain.com
    http:
      paths:
      - backend:
          serviceName: metabase
          servicePort: 80
```
