### ISSUE TITLE
Handle external TLS certs using a directory

### ISSUE THREAD

**Issue by papey** [containous/traefik#1557]
### Do you want to request a *feature* or report a *bug*?

feature

### Context

In Traefik 1.2 and 1.3 you can add external TLS certificates by adding config lines like : 

```toml
     [entryPoints.https.tls]
       [[entryPoints.https.tls.certificates]]
       CertFile = "integration/fixtures/https/snitest.com.cert"
       KeyFile = "integration/fixtures/https/snitest.com.key"
       [[entryPoints.https.tls.certificates]]
       CertFile = "integration/fixtures/https/snitest.org.cert"
       KeyFile = "integration/fixtures/https/snitest.org.key"
```
(example taken from [docs](https://docs.traefik.io/toml/))

In a situation where i'm not allowed to use LE, a part of the automated process falls appart when I want to add a new cert because I need to edit config file + restart traefik.

### What do you want ?

I want to provide a path to a directory where I store certs and keys, typically /etc/ssl/certs and /etc/ssl/private instead of a full path to keys and certs files. For example, HAproxy is able to handle this situation. 

I have multiple ideas regarding the way this feature can be implemented and i'm open to discussion.

Thanks.
