### ISSUE TITLE
Encountered an unthinkable question.

### ISSUE THREAD

**Issue by barnettZQG** [containous/traefik#1564]
ErrorLog:
```
No entrypoint defined for frontend frontend-Host-api-faas-pro, defaultEntryPoints:[]
```
But:
![image](https://cloud.githubusercontent.com/assets/18493394/25791811/79578aa6-33f5-11e7-86a3-788ebc9865e2.png)
traefik.toml
```toml
[entryPoints]
   [entryPoints.http]
   address = ":80"
   [entryPoints.https]
   address = ":443"
     [entryPoints.https.tls]
       [[entryPoints.https.tls.certificates]]
       CertFile = "/cert/hub.faas.pro.pem"
       KeyFile = "/cert/hub.faas.pro.key"

traefikLogsFile = "log/traefik.log"
accessLogsFile = "log/access.log"

[docker]
constraints = ["tag==function-*"]
# Requiredi
endpoint = "unix:///var/run/docker.sock"
# Required
domain = "faas.pro"
watch = true
exposedbydefault = true
```
