### ISSUE TITLE
1.3.0-rc1 not working with consul backend

### ISSUE THREAD

**Issue by ballad89** [containous/traefik#1583]
### Do you want to request a *feature* or report a *bug*?
Reporting a bug

### What did you do?
I upgraded to 1.3.0-rc1 using consul backend 

### What did you expect to see?
I expected it to work as usual

### What did you see instead?

```
'Consul.Kvclient' expected type 'store.Store', got 'string'
Error loading configuration: 1 error(s) decoding:
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.0-rc1
Codename:     raclette   
Go version:   go1.8.1         
Built:        2017-05-05_02:03:01PM      
OS/Arch:      linux/amd64
```

### Steps to reproduce
```
mkdir ~/test_traefik
cd ~/test_traefik
touch docker-compose.yml #Content below
```
```yaml
version: '3'

services:
  consul:
    image: 'consul:0.8.1'
    expose:
      - '8500'
    restart: on-failure

  traefik:
    image: 'traefik:1.3.0-rc1'
    command: "--consul --consul.endpoint=consul:8500 --consul.watch --consulcatalog --consulcatalog.endpoint=consul:8500 --consulcatalog.watch"
    links:
      - 'consul'
    ports:
      - '8080:8080'
    restart: on-failure

```
then 
```
docker-compose up
```
in another terminal
```
cd ~/test_traefik
docker-compose exec traefik /traefik storeconfig --acme --acme.email='test@email.com' --acme.storage='traefik/acme/account' --acme.entrypoint=https --acme.onhostrule --acme.ondemand --consul --consul.endpoint=consul:8500 --consul.watch --consulcatalog --consulcatalog.endpoint=consul:8500 --consulcatalog.watch --consulcatalog.constraints='tag==traefik' --defaultentrypoints='http,https' --web --web.metrics.prometheus --entrypoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS'
docker-compose restart traefik
docker-compose logs traefik
```
You should the errors below
```
* 'Consul.Kvclient' expected type 'store.Store', got 'string'
 2017/05/10 20:11:02 Error loading configuration: 1 error(s) decoding:

 * 'Consul.Kvclient' expected type 'store.Store', got 'string'
 2017/05/10 20:11:04 Error loading configuration: 1 error(s) decoding:

 * 'Consul.Kvclient' expected type 'store.Store', got 'string'
 2017/05/10 20:11:06 Error loading configuration: 1 error(s) decoding:

 * 'Consul.Kvclient' expected type 'store.Store', got 'string'
```
