### ISSUE TITLE
Docker stack service are not discovered

### ISSUE THREAD

**Issue by tcoupin** [containous/traefik#1586]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When I deploy a stack using a compose file, services are not discovered by traefik

### What did you expect to see?

Frontend, backend, server etc...

### What did you see instead?

Nothing

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.2.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

* docker: 17.03.1-ce
* traefik image: traefik:morbier-alpine
* Compose file:
```
version: "3.0"

services:
  traefik:
    image: traefik:morbier-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "8080:8080" #DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.port: "8080"
      traefik.frontend.rule: "Host:traefik.domain"
      traefik.backend: "traefik"
      portainer: "hide"
    networks:
      - traefik-net
    command: --docker --docker.watch --docker.swarmmode --logLevel=DEBUG --docker.domain=domain --web --web.readonly

  portainer:
    image: portainer/portainer:linux-amd64-1.12.3
    volumes:
      - "/mnt/ide-share/data/portainer:/data"
    labels: 
      traefik.port: "9000"
      traefik.frontend.rule: "Host:portainer.domain"
      traefik.backend: portainer
      portainer: "hide"
    networks:
      - traefik-net
    command: -l portainer=hide

    
networks:
  traefik-net:
```
* command: `docker stack deploy -c docker-compose.yml main`

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-05-11T06:24:44Z" level=debug msg="Filtering container without port and no traefik.port label main_traefik.1" 
```

Regarding https://github.com/containous/traefik/blob/master/provider/docker/docker.go#L830, traefik seems to look at wrong place, labels are in tasktemplate and note directly in spec:

```
$ docker inspect main_traefik
[
    {
        "ID": "owcrktgwqbn8j1sc6sspvodp9",
        "Version": {
            "Index": 874375
        },
        "CreatedAt": "2017-05-11T05:40:33.981354499Z",
        "UpdatedAt": "2017-05-11T06:01:20.711686419Z",
        "Spec": {
            "Name": "main_traefik",
            "Labels": {
                "com.docker.stack.namespace": "main"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "traefik:morbier-alpine@sha256:1df256566b63967e6564e32dd70037169101b11b9a028f4d5225cea62f7cc777",
                    "Labels": {
                        "com.docker.stack.namespace": "main",
                        "portainer": "hide",
                        "traefik.backend": "traefik",
                        "traefik.frontend.rule": "Host:traefik.domain",
                        "traefik.port": "8080"
                    },
                    "Args": [
                        "--docker",
                        "--docker.watch",
                        "--docker.swarmmode",
                        "--logLevel=DEBUG",
                        "--docker.domain=domain",
                        "--web",
                        "--web.readonly"
                    ],
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/var/run/docker.sock",
                            "Target": "/var/run/docker.sock"
                        }
...
```

**Comment by tcoupin** [comment]
When I lauch a service:

```
docker service create --name traefik -p 80:80 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock  --label traefik.port=8080 traefik:morbier-alpine --docker --docker.watch --docker.swarmmode --logLevel=DEBUG --docker.domain=domain --web --web.readonly
```

Label are in Spec and not in TaskTemplate:

```
$ docker inspect traefik
[
    {
        "ID": "mqy9dnw6tz07m69zb39zlczrz",
        "Version": {
            "Index": 874391
        },
        "CreatedAt": "2017-05-11T06:57:57.922730447Z",
        "UpdatedAt": "2017-05-11T06:57:57.934415336Z",
        "Spec": {
            "Name": "traefik",
            "Labels": {
                "traefik.port": "8080"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "traefik:morbier-alpine@sha256:1df256566b63967e6564e32dd70037169101b11b9a028f4d5225cea62f7cc777",
                    "Args": [
                        "--docker",
                        "--docker.watch",
                        "--docker.swarmmode",
                        "--logLevel=DEBUG",
                        "--docker.domain=domain",
                        "--web",
                        "--web.readonly"
                    ],
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/var/run/docker.sock",
                            "Target": "/var/run/docker.sock"
                        }
                    ],
                    "DNSConfig": {}

```

**Comment by tcoupin** [comment]
Same on me... I simply put labels in deploy part.

https://docs.docker.com/compose/compose-file/#labels:

> Specify labels for the service. These labels will only be set on the service, and not on any containers for the service.

```
version: "3.0"

services:

  traefik:
    image: traefik:morbier-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.port: "8080"
        traefik.frontend.rule: "Host:traefik.domain"
        traefik.backend: "traefik"
        portainer: "hide"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
```
