### ISSUE TITLE
Traefik crash when failing to parse Basic Authentication information

### ISSUE THREAD

**Issue by pliljenberg** [containous/traefik#1592]
Version: `Traefik version v1.3.0-rc1 built on 2017-05-05_02:03:01PM`

### Scenario
Starting traefik in docker and trying to route to another docker container using `labels`.
If incorrect (or in the test case empty) authentication information is used in the container I try to route to - traefik outputs:
`level=fatal msg="Error creating Auth: Error parsing Authenticator user: "`
and crashes.

### Expected outcome
If traefik fails to parse authentication information it should (probably) ignore the frontend mapping and not add the routing to the container.

### What did you see instead?
Traefik crashes causing all routing to stop working.

### Steps to reproduce?
`docker-compose up`

With the following compose file:
```yml
version: '3'

services:
  webgateway:
    image: traefik:1.3.0-rc1-alpine
    command:
      - --docker
      - --web
      - --logLevel=DEBUG
    ports:
      - "8080:8080"
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  error:
    image: nginx:alpine
    labels:
      - traefik.port=80
      - traefik.frontend.auth.basic=
```
