### ISSUE TITLE
DynamoDB support is broken

### ISSUE THREAD

**Issue by zyzop** [containous/traefik#1607]
### Do you want to request a *feature* or report a *bug*?
bug
### What did you do?
trying to storeconfig to DynamoDB 

### What did you see instead?
Hello,
i have a following section in my traefik.toml - 
```toml
[dynamodb]
TableName = "traefik"
Watch = true
RefreshSeconds = 15
Region = "eu-west-1"
```

Then I did - 
```
[root@calypso traefikdev]# ./traefik13rc1 storeconfig -c /vol/traefikdev/traefik.toml
```
and received
```
2017/05/16 11:31:11 Error running traefik: Error using command storeconfig, no Key-value store defined
```

I also tried like 
```
[root@calypso traefikdev]# ./traefik13rc1 storeconfig --dynamodb=true --dynamodb.tablename=traefik
```
with the same result.

### Output of `traefik version`: (_What version of Traefik are you using?_)
tried v1.2.3 and 1.3rc1
