### ISSUE TITLE
Mysterious "getsockopt: connection refused" in Kubernetes

### ISSUE THREAD

**Issue by olalonde** [containous/traefik#1624]
When I query my service directly (not through traefik) from within my cluster, the server is responding correctly:

```bash
$ kubectl run -i --restart=Never --rm --tty curl --image=byrnedo/alpine-curl -- http://my-app/
<html>
...etc
</html>
```

However, when the request goes through traefik, I am getting a "getsockopt: connection refused" error.

```bash
$ kubectl run -i --restart=Never --rm --tty curl --image=byrnedo/alpine-curl -- http://my-app.domain.com
Bad Gateway
```

And here's the corresponding log in Traefik:

```
time="2017-05-18T08:38:11Z" level=warning msg="Error forwarding to http://100.96.2.63:5000, err: dial tcp 100.96.2.63:5000: getsockopt: connection refused"
```

If I try to curl `100.96.2.63:5000` directly, I am also getting a connection error:

```
$ kubectl run -i --restart=Never --rm --tty curl --image=byrnedo/alpine-curl --
 http://100.96.2.63:5000/
curl: (7) Failed to connect to 100.96.2.63 port 5000: Connection refused
```

Here's how my Ingress resource looks like:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: 2017-05-15T22:33:57Z
  generation: 1
  labels:
    app: my-app
  name: my-app-ingress
  namespace: default
spec:
  rules:
  - host: my-app.mydomain.com
    http:
      paths:
      - backend:
          serviceName: my-app
          servicePort: 80
  - host: beta.mydomain.com
    http:
      paths:
      - backend:
          serviceName: my-app
          servicePort: 80
```

I was wondering if this might be a bug with Traefik and if there's any way to troubleshoot the issue further.
