### ISSUE TITLE
AddPrefix not working with kubernetes Ingress annotations

### ISSUE THREAD

**Issue by jpweber** [containous/traefik#1627]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Created a Kubernetes Ingress that attempts to add a prefix to a path.
```yml
apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: notes-ui 
    namespace: dev
    annotations:
      traefik.frontend.rule.type: "AddPrefix: /notes"
```

### What did you expect to see?

No errors and if I went to `hostname.com` it would turn that in to `hostname.com/notes`

### What did you see instead?

In the traefik ingress controller logs I got the following error
`level=warning msg="Unknown RuleType AddPrefix: /notes for dev/notes-ui, falling back to PathPrefix" `

Also the prefix was not added to the path when I hit the configured url

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.2.3 / morbier 
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#traefik.toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/chain.crt"
      KeyFile = "/ssl/chain.key"

[kubernetes]
# Optional
namespaces = ["default","dev","kube-system"]
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
