### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#1634]
### Do you want to request a *feature* or report a *bug*?

feature

### Description

This issue is a proposal following the PR https://github.com/containous/traefik/pull/1576 on custom error pages. See comment https://github.com/containous/traefik/pull/1576#issuecomment-302450897.

By frontend, we could delegate error page rendering on status code. For example, if I get a `500` status on frontend `website`, I query the frontend `error` with path `/500.html` and the error page would then be rendered by a specific service in your infrastructure with a webserver, Nginx for example.

```toml
 [frontends]
   [frontends.website]
   backend = "website"
   [errors]
     [error.network]
     status = "[500-600]"
     backend = "error"
     query = "/{status}.html"
   [frontends.website.routes.website]
   rule = "Host: website.mydomain.com"

 [backends]
   [backends.website]
     [backends.website.servers.website]
     url = "https://1.2.3.4"
   [backends.error]
     [backends.error.servers.error]
     url = "http://2.3.4.5"
```

/cc @bparli
