### ISSUE TITLE
Support for ACME DNS challenge

### ISSUE THREAD

**Issue by tlvenn** [containous/traefik#1659]
It would be very neat and useful for Traefik to support DNS challenge similarly to how Caddy is doing it for example.
> https://godoc.org/github.com/xenolf/lego/providers/dns

My use case is a given domain that is proxied by cloudfare, in such situation, the classic HTTP challenge cannot work.

**Comment by ldez** [comment]
This option already exists: https://github.com/containous/traefik/blob/b67a27d0c77959f67abd81c3b0567f23cb2b4cb5/traefik.sample.toml#L144

```toml
# Use a DNS based acme challenge rather than external HTTPS access, e.g. for a firewalled server
# Select the provider that matches the DNS domain that will host the challenge TXT record,
# and provide environment variables with access keys to enable setting it:
#  - cloudflare: CLOUDFLARE_EMAIL, CLOUDFLARE_API_KEY
#  - digitalocean: DO_AUTH_TOKEN
#  - dnsimple: DNSIMPLE_EMAIL, DNSIMPLE_API_KEY
#  - dnsmadeeasy: DNSMADEEASY_API_KEY, DNSMADEEASY_API_SECRET
#  - exoscale: EXOSCALE_API_KEY, EXOSCALE_API_SECRET
#  - gandi: GANDI_API_KEY
#  - linode: LINODE_API_KEY
#  - manual: none, but run traefik interactively & turn on acmeLogging to see instructions & press Enter
#  - namecheap: NAMECHEAP_API_USER, NAMECHEAP_API_KEY
#  - rfc2136: RFC2136_TSIG_KEY, RFC2136_TSIG_SECRET, RFC2136_TSIG_ALGORITHM, RFC2136_NAMESERVER
#  - route53: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, or configured user/instance IAM profile
#  - dyn: DYN_CUSTOMER_NAME, DYN_USER_NAME, DYN_PASSWORD
#  - vultr: VULTR_API_KEY
#  - ovh: OVH_ENDPOINT, OVH_APPLICATION_KEY, OVH_APPLICATION_SECRET, OVH_CONSUMER_KEY
#  - pdns: PDNS_API_KEY, PDNS_API_URL
#
# Optional
#
# dnsProvider = "digitalocean"
```

**Comment by tlvenn** [comment]
Ha awesome, I somehow missed it from the changelog.

How do you configure a DNS provider for a given hostname ? It seems that right now this is a global property or am i missing something ?

**Comment by kevinjqiu** [comment]
@tlvenn You can specify the variables as environment variables to the traefik pod. More appropriately, use store them using kube secret, e.g., with 'route53':

Create a secret object:
```
kubectl create secret generic -n kube-system aws --from-literal="AWS_ACCESS_KEY_ID=***" --from-literal="AWS_SECRET_ACCESS_KEY=**********"
```

use it in your pod definition:
```
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            value: "us-east-1"
```
