### ISSUE TITLE
ACME got nothing tracking.instnode.com

### ISSUE THREAD

**Issue by olalonde** [containous/traefik#1668]
On Kubernetes, I am repeatedly seeing those log lines:

```
time="2017-05-25T08:38:39Z" level=debug msg="Challenge GetCertificate tracking.instnode.com"
time="2017-05-25T08:38:39Z" level=debug msg="Challenge GetCertificate tracking.instnode.com"
time="2017-05-25T08:38:39Z" level=debug msg="ACME got nothing tracking.instnode.com"
time="2017-05-25T08:38:39Z" level=debug msg="ACME got nothing tracking.instnode.com"
time="2017-05-25T08:38:41Z" level=debug msg="Challenge GetCertificate tracking.instnode.com"
time="2017-05-25T08:38:41Z" level=debug msg="ACME got nothing tracking.instnode.com"
time="2017-05-25T08:38:41Z" level=debug msg="Challenge GetCertificate tracking.instnode.com"
```

I have no Ingress for `tracking.instnode.com`.... Anyone knows why this just won't stop repeating over and over? And how to stop traefik from trying to get that certificate?

**Comment by dtomcej** [comment]
Can you provide your Traefik Toml or configuration json blob?

**Comment by olalonde** [comment]
Had too many issues with Traefik, stopped using.

**Comment by emilevauge** [comment]
Too bad you didn't give us more details...

**Comment by olalonde** [comment]
Couldn't afford to keep my production router down for 6 days until someone replied here! I was using the traefik helm chart for Kubernetes with following config:

```yaml
traefik:
  # see https://github.com/containous/traefik/issues/1547
  gzip:
    enabled: false
  dashboard:
    enabled: true
  ssl:
    enabled: true
  acme:
    enabled: true
    email: info@mydomain.com
    staging: false
```

**Comment by schoren** [comment]
I'm having this exact same issue. I deployed it manually. This is my traefik.toml

```toml
defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "admin@example.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onDemand = false
    OnHostRule = true
    acmelogging = true
    caServer = "https://acme-v01.api.letsencrypt.org/directory"
    acmeLogging = true
```
