### ISSUE TITLE
Pathing with new StripPrefixPath is still missing paths (1.3 branch)

### ISSUE THREAD

**Issue by seryl** [containous/traefik#1670]
I'm trying to identify why, but for all paths: https://pack.io and https://pack.io/api; I'm still seeing all 404's with the 1.3 branch.

**Comment by seryl** [comment]
the two paths that are configured are:

/ -> packwebsite
/api -> packapi

both are returning 404's although it doesn't seem to make sense why

**Comment by ldez** [comment]
Could you provide your configuration?

**Comment by seryl** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pack-web-app
  namespace: pack
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: pathprefixstrip
spec:
  rules:
  - host: api.pack.io
    http:
      paths:
        - backend:
            serviceName: packapi
            servicePort: 80

  - host: pack.io
    http:
      paths:
       - path: /api
         backend:
           serviceName: packapi
           servicePort: 80

       - path: /
         backend:
           serviceName: pack-maint-site
           servicePort: 80
```
