### ISSUE TITLE
Request: Port ranges for entrypoints

### ISSUE THREAD

**Issue by Kenji-K** [containous/traefik#1677]
Here to make a request, hopefully it isn't to complicated.

I have to expose about 150 ports for a single application (traccar). The issue is, there is apparently no syntax for port ranges, so I would have to list each entrypoint individually

```toml
[entryPoints]
  [entryPoints.port1]
  address = ":5000"
  [entryPoints.port2]
  address = ":5001"
  [entryPoints.port3]
  address = ":5002"
  ...
  [entryPoints.port150]
  address = ":5150"
```
And from there even reference every entryPoint in the frontends. Could there instead be a way to specify a port range like so?

```toml
[entryPoints]
  [entryPoints.portRange1]
  address = ":5000-5150"
```
