### ISSUE TITLE
NO_PROXY environment Variable

### ISSUE THREAD

**Issue by jamroks** [containous/traefik#1681]
### What did you do?

I Setup traffic container in docker-compose file with : 
```yml
environment: 
     - HTTP_PROXY=http://corporate_proxy_adress:8080
     - HTTPS_PROXY=https://corporate_proxy_adress:8080
     - NO_PROXY=mycorporate.domain.com
```
### What did you expect to see?

I expected traeffik to be able to handle no_proxy variable, but that doesn't seem the case, because all my request to corporate domain that goes through Traefik end up in Error 404 http.

### What did you see instead?

I got 404 http error 

### Trafic Version is : 

Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64

debug log doesn't show much, here is what I see in debug log. 

```
time="2017-05-29T13:16:37Z" level=debug msg="Round trip: http://172.33.0.5:80, code: 200, duration: 214.509878ms"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
proxy:
          image: traefik
          container_name: traefik-proxy
          privileged: true
          networks:
            traefik:
              aliases:
                  - traefik.devlabs.ops
          ports:
                  - "80:80"
                  - "443:443"
          expose:
                  - "8080"
          environment:
                  - HTTP_PROXY=http://mycorporate_proxy:8080
                  - HTTPS_PROXY=https://mycorporate_proxy:8080
                  - NO_PROXY=.mycorporate_domain.com,localhost,127.0.0.0/8
          volumes:
                  - type: bind
                    source: /stor/traefik/etc/traefik.toml
                    target: /etc/traefik/traefik.toml
                  - type: volume
                    source: /stor/traefik/acme
                    target: /etc/traefik/acme
                  - type: volume
                    source: /stor/traefik/logs
                    target: /var/log/traefik
                  - type: bind
                    source: /var/run/docker.sock
                    target: /var/run/docker.sock
          restart: always
          labels:
                  - "traefik.enable=true"
                  - "traefik.logLevel=DEBUG"
                  - "traefik.frontend.rule=Host:traefik.devlabs.ops"
                  - "traefik.port=8080"
                  - "traefik.backend=traefik"
                  - "traefik.passHostHeader=true"
                  - "traefik.frontend.entryPoints=http"
          depends_on:
                  - jenkins
                  - portainer
```
