### ISSUE TITLE
storeconfig doesn't store backends and frontends to Consul

### ISSUE THREAD

**Issue by zyzop** [containous/traefik#1682]
### What did you do?
I wanted to upload my `traefik.toml` to a Consul. I have several backends and frontends configured under `[file]` section, and it all runs fine.
So I've added a `[consul]` section in the end of traefil toml and did `storeconfig`

### What did you expect to see?
whole traefik.toml uploaded to Consul

### What did you see instead?
Everything is uploaded except my backends and frontends. There's simply no frontends or backends keys in Consul.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
1.3 rc3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
checkNewVersion = false
logLevel = "WARN"
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
[entryPoints.https.tls]
[acme]
email = "konstantin@somehost.io"
storage = "traefik/acme/account"
storageFile = "acme.json"
entryPoint = "https"
acmeLogging = true
onDemand = true
[[acme.domains]]
main = "somehost1.io"
[[acme.domains]]
main = "elib.somehost.ru"
[[acme.domains]]
main = "somehost.io"
sans = ["www.somehost.io"]
[file]
[backends]
[backends.backend1]
[backends.backend1.servers.server1]
url = "http://somehost1:80"
[backends.backend2]
[backends.backend2.servers.server1]
url = "http://somehost2.s3-website-eu-west-1.amazonaws.com:80"
[backends.backend3]
[backends.backend3.servers.server1]
url = "http://somehost3.s3-website-eu-west-1.amazonaws.com:80"
[frontends]
[frontends.frontend1]
backend = "backend1"
passHostHeader = true
[frontends.frontend1.routes.test_1]
rule = "PathPrefix: /"
[frontends.frontend2]
backend = "backend2"
passHostHeader = true
[frontends.frontend2.routes.test_1]
rule = "Host: somehost.io, www.somehost.io"
[frontends.frontend3]
backend = "backend3"
passHostHeader = true
[frontends.frontend3.routes.test_1]
rule = "Host:elib.somehost.ru"
[consul]
prefix = "traefik"
```
