### ISSUE TITLE
Traefik clears configuration if Rancher API goes offline

### ISSUE THREAD

**Issue by fabiorauber** [containous/traefik#1703]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I took Rancher down for maintenance. 

### What did you expect to see?

Traefik continuing to work with previous configuration, serving clients normally.

### What did you see instead?

Traefik cleared the configuration and left all services offline.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.0
Codename:     raclette
Go version:   go1.8.3
Built:        2017-05-31_05:48:42PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
traefik:
    image: traefik:1.3.0-alpine
    volumes:
    - traefik_acme:/mnt
    ports:
    - 8000:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
    command:
    - --web
    - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
    - --entryPoints=Name:https Address::443 TLS
    - --defaultentrypoints=http,https
    - --rancher
    - --rancher.domain=rancher.domain
    - --rancher.endpoint=https://rancher.domain/v1/projects/1x000
    - --rancher.accesskey=KEY
    - --rancher.secretkey=SECRETKEY
    - --rancher.exposedbydefault=false
    - --acme
    - --acme.email=email@mail.com
    - --acme.storage=/mnt/acme.json
    - --acme.entrypoint=https
    - --acme.ondemand=true
    - --logLevel=INFO

```
