### ISSUE TITLE
AddPrefix Modifier for Kubernetes Ingress appends extraneous path

### ISSUE THREAD

**Issue by skormos-lv** [containous/traefik#1704]
Minikube v0.19.0
Traefik v1.3

I setup a basic node container to echo the host and path information as requested when routed through Traefik. The following Ingress was created:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: add-prefix-test
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: "Path:/this;AddPrefix:/test"
spec:
  rules:
  - host: minikube.dev
    http:
      paths:
      - path: /this
        backend:
          serviceName: echo-path
          servicePort: http
```

A snapshot of the route and rule reported in the Traefik Dashboard. 
![screen shot 2017-06-02 at 10 57 32 am](https://cloud.githubusercontent.com/assets/19916351/26733020/951ba90c-4787-11e7-8a91-93c8f60d8242.png)

When requesting `http://minikube.dev/this`, I get the following remapped path in the result:
```
url: /test:/this/this
originalUrl: /test:/this/this
origin: http://minikube.dev
hostname: minikube.dev
```

It should map `/this` --> `/test/this`.
