### ISSUE TITLE
consul.tls ca, cert and key options should be optional

### ISSUE THREAD

**Issue by bitsofinfo** [containous/traefik#1718]
### What did you do?

Attempt to connect traefik to a consul endpoint running TLS that presents a legit CA signed SSL certificate.

I have no need to present my own certificate when connecting to consul as a client over TLS. Other tools support this fine, such as https://github.com/hashicorp/consul-template

```toml
[consul]
  endpoint = "myconsul.mydomain.com:8501" # SSL port
  watch = true
  prefix = "traefik-stage"

[consul.tls]
```

### What did you expect to see?

Traefik should be able to connect via SSL to a consul backend presenting a legit CA signed SSL certificate without issue.

I should not have to specify the `ca, cert, and key` options

### What did you see instead?

`2017-06-08T16:23:17.882619269Z 2017/06/08 16:23:17 Error creating kv store: Failed to load TLS keypair: tls: failed to find any PEM data in certificate input`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.3.0 built on 2017-05-31_05:48:42PM
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

relevant TOML config section

```toml
.....
[consul]
  endpoint = "myconsul.mydomain.com:8501" SSL port
  watch = true
  prefix = "traefik-stage"

[consul.tls]

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

see above
