### ISSUE TITLE
Let's Encrypt (acme) doesn't work with http redirect to https

### ISSUE THREAD

**Issue by BenoitAverty** [containous/traefik#1731]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I configured traefik to use let's encrypt and redirect all http trafic to https entrypoint. Here's my traefik.toml file : 
```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
ReadOnly = true
  [web.auth.basic]
  users = ["{{ traefik_basic_auth_user }}:{{ traefik_basic_auth_password }}"]

[docker]
endpoint = "unix:///var/run/docker.sock"
swarmmode = true
watch = true
domain = "{{ docker_url }}"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "{{ acme_email }}"
storageFile = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = true
```

### What did you expect to see?

HTTPS access to my services authenticated
HTTP redirect to the https equivalent

### What did you see instead?

When I access the https url of a service, traefik gives me the default certificate instead of the let's encrypt one. When I go to the http url, it redirects me to the https url and the same problem occurs.

I found this article : http://niels.nu/blog/2017/traefik-https-letsencrypt.html which solved my problem partially. I disabled the http redirection, and it works when I access the https url. But I'm not redirected when i access http.
Then I re-enabled the http redirection, and everything works fine because the certificate is already present and valid.
However, it won't work on new urls for which I don't have the certificate yet.

I'm using the latest version of traefik from the docker official image.
