### ISSUE TITLE
Docker exposedbydefault not working

### ISSUE THREAD

**Issue by gaui** [containous/traefik#1770]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Ran traefik in Docker Swarm Mode on a manager node and had `exposedbydefault=false` in the traefik.toml config file. Then added some containers to the Swarm with `traefik.enable=true`. Worked well, but then added a standalone Docker container on port 80 (not in Swarm) on one of the nodes and got:

```
404 page not found
```

### What did you expect to see?

The contents from the container.

### What did you see instead?

```
404 page not found
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.1
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-16_11:21:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
traefikLogsFile = "/logs/traefik.log"
accessLogsFile = "/logs/access.log"

[web]
address = ":8080"

[web.auth.basic]
  usersFile = "/.htpasswd"

[docker]
exposedbydefault = false
watch = true
domain = "mydomain"
swarmmode = true

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
```
