### ISSUE TITLE
URL rewriting for path routing

### ISSUE THREAD

**Issue by peperunas** [containous/traefik#1771]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you do?
Installed a service through docker which does not support the editing of it `base path`. Using traefik's `PathPrefixStrip` works and I'm able to reach the service but a lot of resources aren't loaded.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.1
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-16_11:21:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
version: '2'

services:
  irc:
      image: thelounge/lounge
      restart: always
      volumes:
      - irc:/home/lounge/data
      restart: always
      labels:
      - "traefik.frontend.rule=Host:example.com;PathPrefixStrip:/irc"
  traefik:
    restart: always
    image: traefik
    command: --web --docker --docker.domain=example.com --logLevel=DEBUG
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/ssl:/etc/ssl/traefik
```
