### ISSUE TITLE
Option to use old Host Name standard for Docker Images

### ISSUE THREAD

**Issue by JaronrH** [containous/traefik#1787]
Is there a way to fall back to the old Host:{containerName}.{domain} as opposed to the new Host:{service}.{project_name}.{domain} format for Docker containers created with docker-compose?  I just updated from 1.1.1 to 1.3.1 and this change in the host template is really making migration a pain!  Thanks!

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Every question in the issues means features less 😉.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, refer to one of the following:

- [Stack Overflow](https://stackoverflow.com/questions/tagged/traefik) using the "traefik" tag
- the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Comment by JaronrH** [comment]
Ok, let me try it this way! :) 

**Bug:**  The change made here (https://github.com/containous/traefik/pull/1235/files) is causing issues in my docker system due to the change in default naming.

**Feature Request:**  Allow me to define the templates used for docker host creation in the config file using variables such as {project_name, {containerName}, and {domain} so I can work around this problem as well as allow others to customize Traefik to a greater degree.

**Comment by jasonrm** [comment]
I running into this as well with `v1.3.1 / raclette`. Setting `traefik.frontend.rule=Host` would be a lot more useful if variable replacement worked.

Where the [documentations mentions](https://docs.traefik.io/toml/#docker-backend) of a `default` being `Host:{containerName}.{domain} or Host:{service}.{project_name}.{domain}`, I read that to mean that it was using those exact template-looking strings as the default, when in fact it assembles the resulting string directly.

So, given the following `docker-compose.yml`

```yaml
version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.exposedbydefault=false --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
  whoami2:
    image: emilevauge/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami2"
      - "traefik.frontend.rule=Host:{service}.{project_name}.{domain}"
```

Results in the following frontends in the web UI,

|Route | Rule |
|------|------|
|route-frontend-Host-service-project-name-domain|Host:{service}.{project_name}.{domain}|
|route-frontend-Host-whoami-docker-localhost|Host:whoami.docker.localhost|

It's possible to work around using docker-compose variable substituion, but would sure feel a lot cleaner if it could be done all in Traefik.
