### ISSUE TITLE
Gateway timeout after updating Docker service

### ISSUE THREAD

**Issue by nathantreid** [containous/traefik#1808]
### Do you want to request a *feature* or report a *bug*?
Bug 

### What did you do?
Our build process automatically deploys the latest build to our test environment. This is performed via `docker stack deploy`. The site's configuration is handled via Docker labels. After the update, we are unable to access the site anymore. Instead, we receive a "gateway timeout" error in the web browser. If we then stop the container, the swarm automatically restarts it and the site begins to work. We only just recently began experiencing this behavior, and it only happened after we updated to Traefik 1.3.1 (from 1.2.3).

### What did you expect to see?
The site should work immediately after deploy.

### What did you see instead?
A "gateway timeout" error message in the web browser.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.1
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-16_11:21:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Note: SSL certificate names have been replace with "somecert" for privacy. The acme email has also been replaced.

```toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.crt"
        KeyFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.key"
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.crt"
        KeyFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.key"
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.crt"
        KeyFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.key"
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.crt"
        KeyFile = "/etc/ssl/certs/deployed/wildcard.somecert.com.key"

[file]
  watch = true

[acme]
  email = "someemail"
  storage = "acme.json"
  storageFile = "acme.json"
#  onDemand = true
  onHostRule = true
  entryPoint = "https"
#  caServer = "https://acme-staging.api.letsencrypt.org/directory"

[docker]
  exposedbydefault = false

```

Args from `docker service inspect traefik`:
```
"--docker",
"--docker.swarmmode",
"--docker.domain=traefik",
"--docker.watch",
"--web"
```

Traefik labels on the Docker service:
```
traefik.docker.network=traefik-net-no-tls
traefik.frontend.passHostHeader=true
traefik.frontend.rule=Host:somesite.com
traefik.port=80
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
level=warning msg="Error forwarding to http://10.0.17.5:80, err: dial tcp 10.0.17.5:80: getsockopt: connection refused" 
```
