### ISSUE TITLE
Kubernetes ExternalNames cannot be mapped to custom ports via the Service port

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1816]
### Do you want to request a *feature* or report a *bug*?
Bug.

### What did you do?
Create an Ingress and a Service object in Kubernetes where the latter specifies an ExternalName and a Service port/target port mapping.

### What did you expect to see?
The ExternalName URL is being requested on the mapped target port.

### What did you see instead?
The target port is always 80.

### Output of `traefik version`: (_What version of Traefik are you using?_)
master.

### Details

Right now, the Service port is only required to determine if the protocol should be HTTPS or HTTP (depending on the port being 443 or not). It'd be convenient if the target port was used when forwarding requests to the external name.

FWIW, the Nginx controller [does the same](https://github.com/kubernetes/ingress/issues/621).

**Comment by timoreimann** [comment]
I discovered the status quo while formulating a [response on a different issue](https://github.com/containous/traefik/issues/1277#issuecomment-312121758).

@dtomcej have been discussing options. I went ahead a filed a feature request for a direction that looked legitimate to me. Happy to discuss.

**Comment by trnl** [comment]
To me it looks like it is fixed in https://github.com/kubernetes/ingress/pull/629/files

**Comment by timoreimann** [comment]
@trnl you are right that ExternalNames don't provide endpoints -- their sole purpose is to redirect to some DNS name.

What this issue is about though is to extend Traefik such that any Service port mapping will be incorporated into the forwarded request. Right now, all ExternalName requests may only hit port 80. We want to make it possible that requests may go to an arbitrary port as defined by the Service object.

**Comment by wojciech12** [comment]
@timoreimann  You can achieve  using Service and Enpoint objects, see https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service :

```
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
---
kind: Endpoints
apiVersion: v1
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 1.2.3.4
    ports:
      - port: 9376
```
