### ISSUE TITLE
Traefik with Rancher backend: Gateway Timeout trying to connect to Services 

### ISSUE THREAD

**Issue by VP2405** [containous/traefik#1820]
Hi everyone.

### What did you do?

I have a host with Traefik running (not container, but binary), reachable at a specific domain, e.g [traefik.mydomain.com](url) (configured with Route 53)  in order to behave like a proxy for a Rancher Server backend. 
Rancher Server runs on another node, and Rancher's hosts are other 3 nodes.
I want to make all the services running on Rancher's host reachable through Traefik.

I created a stack on Rancher, called it 'traefik' and added a service with nginx (two containers).

<img width="233" alt="schermata 2017-07-04 alle 11 20 05" src="https://user-images.githubusercontent.com/10478244/27823954-2839c354-60ab-11e7-91ed-38f73900c928.png">

The configuration labels of the service are:
```
traefik.port = 8080
traefik.enable = true

Network: Managed
```

### What I see on Traefik Dashboard

The backend related to the frontend rule **Host:traefik.nginx.traefik.mydomain.com** is the following:
<img width="461" alt="schermata 2017-07-04 alle 11 18 45" src="https://user-images.githubusercontent.com/10478244/27824031-69a081fc-60ab-11e7-88e6-6431b1e21564.png">

### Problem
When I type on the browser the address: [traefik.nginx.traefik.mydomain.com](url) i get the message:
Gateway Timeout
I cannot reach nginx service in any way.
I tried to make Network with **bridge** mode, but without success.

### Output of `traefik version`: 

```
Version:      v1.3.2
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-29_04:31:40PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (toml)?

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"


[web]
address = ":9090"
 
################################################################
# Rancher configuration backend
################################################################

# Enable Rancher configuration backend
#
# Optional
#

[rancher]

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on an service.
#
# Required
#
domain = "traefik.mydomain.com"

# Enable watch Rancher changes
#
# Optional
# Default: true
#
Watch = true

# Polling interval (in seconds)
#
# Optional
#
RefreshSeconds = 15

# Expose Rancher services by default in traefik
#
# Optional
# Default: true
#
ExposedByDefault = true

# Filter services with unhealthy states and health states
#
# Optional
# Default: false
#
EnableServiceHealthFilter = false

# Endpoint to use when connecting to Rancher
#
# Required
Endpoint = "http://myrancherip:8080/v1"

# AccessKey to use when connecting to Rancher
#
# Required
AccessKey = "myaccesskey"

# SecretKey to use when connecting to Rancher
#
# Required
SecretKey = "mysecretkey"

```
