### ISSUE TITLE
traefik stops processing Ingresses if RBAC permissions for Secrets are not granted

### ISSUE THREAD

**Issue by jeroenjacobs1205** [containous/traefik#1826]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Install the latest version of the official traeffik docker container in kubernetes

### What did you expect to see?

traeffik processing k8s ingress rules. Our current k8s yaml files used to work until last week to deploy traeffik as k8s ingress controller

### What did you see instead?

this message:

`github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: the server does not allow access to the requested resource (get secrets)
`
Wy would traefik suddenly require access to the secrets resource? This is nowhere mentioned in the official rbac rules either: https://github.com/containous/traefik/blob/master/examples/k8s/traefik-rbac.yaml

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.2
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-29_04:52:35PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We run it inside k8s 1.6.6

No toml file used. 

This is the k8s yaml file:

<details>

```yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        args:
        - --web
        - --kubernetes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: traefik-ingress-controller
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    name: http
  selector:
    k8s-app: traefik-ingress-lb

```
</details>
