### ISSUE TITLE
Traefik with rancher-metadata backend is not behaving like with rancher API backend

### ISSUE THREAD

**Issue by fabiorauber** [containous/traefik#1852]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using traefik with the latest experimental build (containous/traefik:experimental) to test rancher-metadata integration. 

### What did you expect to see?

Each frontend having its own backend, like when using integration via Rancher API, even though every backend container is named 'plone'. 
Traefik 1.3 configured with Rancher API creates several backends based on the stack name, like "backend-site1-plone", "backend-site2-plone", etc.

### What did you see instead?

Each frontend is pointing to a single backend, "backend-plone", when using integration via rancher-metadata.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
containous/traefik:779eeba650b1bd9a9228cf17da7ed4ba02ed93c9 
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
traefik:
  ports:
    - 8000:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: role=traefik
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  image: containous/traefik:779eeba650b1bd9a9228cf17da7ed4ba02ed93c9
  command:
    - "--web"
    - "--entryPoints=Name:http\ Address::80\ Redirect.EntryPoint:https"
    - "--entryPoints=Name:https\ Address::443\ TLS"
    - "--defaultentrypoints=http,https"
    - "--rancher"
    - "--rancher.exposedbydefault=false"
    - "--rancher.metadata=true"
    - "--acme"
    - "--acme.email=email@domain.com"
    - "--acme.storage=/mnt/acme.json"
    - "--acme.entrypoint=https"
    - "--acme.ondemand=true"
    - "--logLevel=INFO"
  volumes:
    - "traefik_acme:/mnt:nocopy"

```
Every traefik backend container has the following rancher labels:

    labels:
      traefik.port: 8080
      traefik.enable: true
      traefik.frontend.rule: "Host:www.domain.com,domain.com"
      traefik.acme.domains: "www.domain.com,domain.com"
