### ISSUE TITLE
Traefik docker websocket configuration

### ISSUE THREAD

**Issue by AndreasHohn** [containous/traefik#1864]
**What version of Traefik are you using (traefik version)?**

latest

**What is your environment & configuration (arguments, toml...)?**

```yml
 traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - '80:80'
    - '8080:8080'
    - '443:443'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
presenceservice:
  image: 'imagename'
  labels:
    - 'traefik.api.backend=presenceapi'
    - 'traefik.api.port=3000'
    - 'traefik.api.frontend.rule=PathPrefixStrip:/presenceapi,/alksjdfllkajsflkajsdlkfjaslkdfjaslkdjflkasjdflkasjdflkasdjf67'
    - 'traefik.websocket.backend=presencesocket'
    - 'traefik.websocket.protocol=ws'
    - 'traefik.websocket.port=3001'   
    - 'traefik.websocket.frontend.rule=PathPrefixStrip:/presencesocket,/alksjdfllkajsflkajsdlkfjaslkdfjaslkdjflkasjdflkasjdflkasdjf68'
    - 'traefik.websocket.frontend.entryPoints=ws,wss'
```

**What do you want to do?**
I am currently trying to use traefik with a custom websocket service. I need to deploy it in docker cloud.
But trying to connect to the websocket with C# (SocketIoClientDotNet) only causes connection errors. It worked before when deploying the presenceservice with ports.

Any suggestion on the docker compose file? Looking at the traefik git issues I only came up with this configuration but it does not work.

Thanks in advance - Andreas
