### ISSUE TITLE
Healthcheck RemoveServer does not work proper with multiple entrypoints

### ISSUE THREAD

**Issue by chrigl** [containous/traefik#1866]
### Do you want to request a *feature* or report a *bug*?

Bug

Note: I will create two PRs with different ways to resolve this.

### What did you do?

Configured multiple entrypoints, and using a single backend with a healthcheck. There are two servers in a backend (config see below). I "broke" the healthcheck on one of the servers.

### What did you expect to see?

No matter which entrypoint I hit, I expect the "broken" server to be excluded.

### What did you see instead?

Actually. The server is only removed from the last configured entrypoint. Here `https`.  So hitting the `http`-Entrypoint always hits both servers.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.3
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-06_05:32:56PM
OS/Arch:      linux/amd64
```

But master is affected as well.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = "10.1.1.30:80"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[frontends]
  [frontends.test1]
    backend = "test1"
    passHostHeader = true
    [frontends.test1.routes.default]
      rule = "Host:test1.example.com"

[backends]
  [backends.test1]
    [backends.test1.healthcheck]
      path = "/healthcheck"
    [backends.test1.Loadbalancer]
      method = "drr"
    [backends.test1.servers.controller1]
      url = "http://10.1.1.100:8774"
    [backends.test1.servers.controller2]
      url = "http://10.1.1.101:8774"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
