### ISSUE TITLE
expecting X-Forwarded-For: users-real-public-ip

### ISSUE THREAD

**Issue by lvnilesh** [containous/traefik#1880]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

STEP 1:

```
docker run -p 81:80 emilevauge/whoami
```
and visit http://host:81 to see this

```
Hostname: bbe52f769ea9
IP: 127.0.0.1
IP: 172.17.0.2
GET / HTTP/1.1
Host: host:81
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.28 (KHTML, like Gecko) Version/11.0 Safari/604.1.28
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us
Connection: keep-alive
Upgrade-Insecure-Requests: 1

```

STEP 2: let me put this whoami behind traefik and retest

```
Hostname: 7d8e174108d1
IP: 127.0.0.1
IP: 10.0.1.12
IP: 10.0.1.11
IP: 172.18.0.10
GET / HTTP/1.1
Host: a.cloudgeni.us
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.28 (KHTML, like Gecko) Version/11.0 Safari/604.1.28
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: br, gzip, deflate
Accept-Language: en-us
Dnt: 1
X-Forwarded-For: 10.255.0.2
X-Forwarded-Host: a.cloudgeni.us
X-Forwarded-Proto: https
X-Forwarded-Server: 87832a3661da

```

### What did you expect to see?

I expect to see this.

```
X-Forwarded-For: users-real-public-ip,10.255.0.2,192.168.0.1,whatever
X-Forwarded-Host: a.cloudgeni.us
X-Forwarded-Proto: https
X-Forwarded-Server: I-dont-care
```

### What did you see instead?

[I see this](https://a.cloudgeni.us)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: traefik:v1.3.3
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

A single box in vultr cloud running traefik > whoami

**Comment by lvnilesh** [comment]
Thanks @dtomcej

**Comment by snc** [comment]
Here the question is how you exactly run the traefik container... especially the chosen network mode.

**Comment by lvnilesh** [comment]
run
```
docker stack deploy -c traefik.yml traefik
```
yml
```
version: "3.2"
services:

  traefik:
    image: traefik:v1.3.3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - 443:443
    volumes:
      - /traefik_vol:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
      - /traefik_vol/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:tra.example.com"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=traefik"
        - "traefik.backend.loadbalancer.method=wrr"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true
```
TOML
```
checkNewVersion = false
debug=true
logLevel="DEBUG"
InsecureSkipVerify=true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
#    CipherSuites = ["TLS_RSA_WITH_AES_256_GCM_SHA384"]

[acme]
  acmeLogging=true
  onDemand=true
  entryPoint="https"
  OnHostRule=true
  caServer="https://acme-v01.api.letsencrypt.org/directory"
  email="email@example.com"
  storage="/etc/traefik/acme/acme.json"

[[acme.domains]]
   main = "example.com"
   sans = ["viz.example.com","tra.example.com"]
[[acme.domains]]
   main = "d1.com"
   sans = ["a.d1.com"]
[[acme.domains]]
   main = "d2.us"
   sans = ["b.d2.us", "www.bd2.us" ]

[docker]
  swarmmode=true
  domain="traefik"
  watch=true

[web]
  address = ":8080"

```

**Comment by vonloh** [comment]
this issue is related to or probably caused by https://github.com/moby/moby/issues/25526.
we have been able to solve it with this config:
```
version: "3.3"
services:
  proxy:
    image: traefik
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

networks:
  traefik-net:
    external: true

```
the main difference to your config is the deploy mode set to global

**Comment by lvnilesh** [comment]
Resolved. Thank you.

**Comment by jgallen23** [comment]
I tried global and mode host, but now I'm getting the ip of the box (172.*) instead of the container ip (10.*)  Any ideas?  In the nginx world, people said I need to set this: `set_real_ip_from 0.0.0.0/0;`

**Comment by jgallen23** [comment]
seems like this might be an issue if AWS ELB is in front of swarm

**Comment by mavimo** [comment]
@jgallen23 with AWS ELB you need to enable Proxy-Protocol, but the actual version of traefik don't support it. See https://github.com/containous/traefik/issues/384

**Comment by schoren** [comment]
Hi, I'm having the same problem using traefik as Kubernetes Ingress controller. Any ideas? Thanks

**Comment by JesusIslam** [comment]
@schoren you can try setting the container publish mode to host `--publish mode=host,target=80,published=80`, and set the service mode `--mode global` to global. I've tried it and succeed using those at a Digital Ocean box using Docker Swarm.

**Comment by c4m4** [comment]
--publish mode=host,target=80,published=80 solved without using global mode

**Comment by JesusIslam** [comment]
@c4m4 you don't have to set it to `--mode global`, but you couldn't scale it anyway since port 443 and 80 on a host are already bound to the first container.

**Comment by hillbun** [comment]
how to solve it if create treafik with docker service create , but not compose file?

it seems no mode=host

**Comment by JesusIslam** [comment]
@hillbun see my comments above

**Comment by hillbun** [comment]
@JesusIslam 
I mean there is no options of "--publish mode=host,target=80,published=80" when use "docker service create" command.
this option can be used only in compose file?

**Comment by JesusIslam** [comment]
@hillbun There is, check this [link](https://docs.docker.com/engine/reference/commandline/service_create/#options).

**Comment by hillbun** [comment]
@JesusIslam 

--mode     Service mode (replicated or global)

I see this option, but it is not mode=host this option?

**Comment by JesusIslam** [comment]
@hillbun you can see the that `mode=host` is part of `--publish` option argument [here.](https://docs.docker.com/engine/swarm/services/#publish-a-services-ports-directly-on-the-swarm-node)

**Comment by schoren** [comment]
In my case (Kubernetes running on Azure with Azure LoadBalancers), I fixed it by configuring my traefik service like this:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
  type: LoadBalancer
```

the lines `externalTrafficPolicy: Local` and `service.beta.kubernetes.io/external-traffic: OnlyLocal` forces Azure LoadBalancers to forward the original IP. 

I believe this same solution should work for GKE and AWS, but I didn't test it.
