### ISSUE TITLE
API basic auth not working

### ISSUE THREAD

**Issue by gulien** [containous/traefik#1882]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I'd like to have a basic auth before accessing to the Traefik dashboard.
I've followed the official documentation for the [API backend](https://docs.traefik.io/toml/#api-backend).

### What did you expect to see?

My browser authentication pop-up before accessing https://traefik.my-awesome-project.local.

### What did you see instead?

The nice Traefik dashboard 😄 !

### Output of `traefik version`:

```
Version:      v1.3.3
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-06_05:32:56PM
OS/Arch:      linux/amd64
```

Using the latest image from Docker Hub: traefik:1.3.3-alpine.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here is my docker-compose file:

```yaml
version: '3.3'


services:


  proxy:
    image: traefik:1.3.3-alpine
    container_name: kickoff-proxy
    restart: "no"
    command: --web --docker --logLevel=DEBUG
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.frontend.rule=Host:traefik.my-awesome-project.local
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml:ro
      - ./traefik/certs:/tests:ro

networks:


  proxy:
    driver: bridge
```

And my configuration file:

```toml
# Entry points definition
defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
certFile = "tests/my-awesome-project.local.crt"
keyFile = "tests/my-awesome-project.local.key"

# API backend
[web]
address = ":8080"
#
[web.auth.basic]
users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]

# Docker backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "my-awesome-project.local"
watch = true
exposedbydefault = false
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-07-20T17:18:09Z" level=info msg="Traefik version v1.3.3 built on 2017-07-06_05:32:56PM" 
time="2017-07-20T17:18:09Z" level=info msg="Using TOML configuration file //traefik.toml" 
time="2017-07-20T17:18:09Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":{"EntryPoint":"https","Regex":"","Replacement":""},"Auth":null,"Compress":false},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":[{"CertFile":"tests/my-awesome-project.local.crt","KeyFile":"tests/my-awesome-project.local.key"}],"ClientCAFiles":null},"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http","https"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":{"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false},"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}" 
time="2017-07-20T17:18:09Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc42026fcb0 Auth:<nil> Compress:false}" 
time="2017-07-20T17:18:09Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc42007b8c0 Redirect:<nil> Auth:<nil> Compress:false}" 
time="2017-07-20T17:18:09Z" level=info msg="Starting server on :80" 
time="2017-07-20T17:18:09Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false}" 
time="2017-07-20T17:18:09Z" level=info msg="Starting provider *server.WebProvider {"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null}" 
time="2017-07-20T17:18:09Z" level=info msg="Starting server on :443" 
time="2017-07-20T17:18:09Z" level=debug msg="Provider connection established with docker 17.06.0-ce (API 1.30)" 
time="2017-07-20T17:18:09Z" level=debug msg="Filtering container without port and no traefik.port label /local-myawesomeproject-toolbox" 
time="2017-07-20T17:18:09Z" level=debug msg="Validation of load balancer method for backend backend-proxy-kickoff failed: invalid load-balancing method ''. Using default method wrr." 
time="2017-07-20T17:18:09Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-proxy-kickoff":{"servers":{"server-kickoff-proxy":{"url":"http://172.20.0.2:8080","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-Host-traefik-my-awesome-project-local":{"entryPoints":["http","https"],"backend":"backend-proxy-kickoff","routes":{"route-frontend-Host-traefik-my-awesome-project-local":{"rule":"Host:traefik.my-awesome-project.local"}},"passHostHeader":true,"priority":0,"basicAuth":[]}}}" 
time="2017-07-20T17:18:09Z" level=debug msg="Last docker config received more than 2s, OK" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating frontend frontend-Host-traefik-my-awesome-project-local" 
time="2017-07-20T17:18:09Z" level=debug msg="Wiring frontend frontend-Host-traefik-my-awesome-project-local to entryPoint http" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating route route-frontend-Host-traefik-my-awesome-project-local Host:traefik.my-awesome-project.local" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\/\/)?([\w\._-]+)(?::\d+)?(.*)$ -> https://$1:443$2" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating backend backend-proxy-kickoff" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating load-balancer wrr" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating server server-kickoff-proxy at http://172.20.0.2:8080 with weight 0" 
time="2017-07-20T17:18:09Z" level=debug msg="Wiring frontend frontend-Host-traefik-my-awesome-project-local to entryPoint https" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating route route-frontend-Host-traefik-my-awesome-project-local Host:traefik.my-awesome-project.local" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating backend backend-proxy-kickoff" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating load-balancer wrr" 
time="2017-07-20T17:18:09Z" level=debug msg="Creating server server-kickoff-proxy at http://172.20.0.2:8080 with weight 0" 
time="2017-07-20T17:18:09Z" level=info msg="Server configuration reloaded on :443" 
time="2017-07-20T17:18:09Z" level=info msg="Server configuration reloaded on :80" 
time="2017-07-20T17:18:09Z" level=debug msg="Round trip: http://172.20.0.2:8080, code: 200, duration: 12.558749ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:traefik.my-awesome-project.local" 
time="2017-07-20T17:18:09Z" level=warning msg="Error checking new version: Get https://update-traefik.containous.cloud/repos/containous/traefik/releases: x509: certificate has expired or is not yet valid" 
time="2017-07-20T17:18:10Z" level=debug msg="Round trip: http://172.20.0.2:8080, code: 200, duration: 1.084795ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:traefik.my-awesome-project.local" 

[others containers binding]

time="2017-07-20T17:21:19Z" level=debug msg="Round trip: http://172.20.0.2:8080, code: 200, duration: 844.461µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:traefik.my-awesome-project.local" 
time="2017-07-20T17:21:19Z" level=debug msg="Round trip: http://172.20.0.2:8080, code: 200, duration: 1.266692ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:traefik.my-awesome-project.local" 
time="2017-07-20T17:21:21Z" level=debug msg="Round trip: http://172.20.0.2:8080, code: 200, duration: 1.078201ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:traefik.my-awesome-project.local" 
time="2017-07-20T17:21:23Z" level=debug msg="Round trip: http://172.20.0.2:8080, code: 200, duration: 1.04394ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:traefik.my-awesome-project.local" 
```
