### ISSUE TITLE
port '80' is already in use by service 'foo'

### ISSUE THREAD

**Issue by prologic** [containous/traefik#1888]
This may in fact be an issue in Docker / Swarm but here it is anyway...

Trying to set up a 2nd traefik instance with the following Docker stack config:

```yaml
version: "3.2"

services:
  traefik:
    image: traefik
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - intern_traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - intern_traefik:/data
      - intern_sslcerts:/ssl
    command:
      - --accesslogsfile=/data/access.log
      - --web
      - --docker
      - --docker.watch
      - --docker.swarmmode
      - --docker.domain=intern.mydomain.com
      - --docker.exposedbydefault=false
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS:/ssl/ssl.crt,/ssl/ssl.key
      - --defaultentrypoints=http,https
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == dm2.mydomain.com"
      replicas: 1

  todo:
    image: prologic/todo
    command: -dbpath /data/todo.db
    networks:
      - intern_traefik
    volumes:
      - intern_todo:/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=todo"
        - "traefik.docker.network=intern_traefik"
        - "traefik.frontend.rule=PathStrip:/todo"
      placement:
        constraints:
          - "node.hostname == dm2.mydomain.com"
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  intern_traefik:
    external: true

volumes:
  intern_sslcerts:
    external: true
  intern_traefik:
    driver: local
  intern_todo:
    driver: local
```

And run into:

```#!bash
$ docker stack deploy -c intern.yml intern
Creating service intern_traefik
Error response from daemon: rpc error: code = 3 desc = port '80' is already in use by service 'lb_traefik' (nhrfy6qkon3gdrw7rqrhzko16)
```

The error you get is from the traefik instance running on node `dm1`. I find this rather confusing that you can't seem to bind ports to a specific interface. Even with a port binding of `10.0.0.10:80:80/tcp` in `lb_traefik` (*the service that this 2nd config is colliding with*) doesn't work.

Besides completely choosing different port bindings for the 2nd instance (*unideal*) is there any other way / work-around?
