### ISSUE TITLE
HostRegexp not routing to backend

### ISSUE THREAD

**Issue by lasley** [containous/traefik#1897]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created a host with the following rule (Traefik 1.3.3-alpine):
```
HostRegexp:{subdomain:.+}.runbot.laslabs.io;Host:traefik.runbot.runbot.laslabs.io;
```

Navigating to `test.runbot.laslabs.io` yields a 404. `traefik.runbot.runbot.laslabs.io` works fine.

Update host rule to:

```
HostRegexp:test.runbot.laslabs.io;Host:traefik.runbot.runbot.laslabs.io;
```
Still a 404. Switch to using Host rule only:

```
Host:test.runbot.laslabs.io,traefik.runbot.runbot.laslabs.io;
```

Works as expected.

### What did you expect to see?

Traefik routing to the backend based on a positive match for a host regex

### What did you see instead?

A 404 error

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
bash-4.3$ traefik version
Version:      v1.3.3
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-06_05:12:20PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml
```toml
# traefik.toml
debug = false
logLevel = "INFO"
traefikLogsFile = "/opt/traefik/log/traefik.log"
accessLogsFile = "/opt/traefik/log/access.log"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/traefik.crt"
      keyFile = "/opt/traefik/certs/traefik.key"

[web]
address = ":8000"

[file]
filename = "/opt/traefik/etc/rules.toml"
watch = true
```

rules.toml
```toml
[backends]
  [backends.longpolling__Runbot]
    [backends.longpolling__Runbot.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.longpolling__Runbot.LoadBalancer]
      method = "drr"
    [backends.longpolling__Runbot.servers.Runbot-longpolling-1]
      url = "http://10.42.111.66:8072"
      weight = 0
  [backends.traefik__Runbot]
    [backends.traefik__Runbot.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.traefik__Runbot.LoadBalancer]
      method = "drr"
    [backends.traefik__Runbot.servers.Runbot-traefik-1]
      url = "http://10.42.75.99:80"
      weight = 0
  [backends.web__Runbot]
    [backends.web__Runbot.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.web__Runbot.LoadBalancer]
      method = "drr"
    [backends.web__Runbot.servers.Runbot-web-1]
      url = "http://10.42.40.64:8069"
      weight = 0
[frontends]
  [frontends.longpolling__Runbot]
    backend = "longpolling__Runbot"
    passHostHeader = true
    priority =  5
    [frontends.longpolling__Runbot.routes.service]
      rule = "Host:longpolling.runbot.runbot.laslabs.io,runbot.laslabs.io;PathPrefix:/longpolling;"
  [frontends.traefik__Runbot]
    backend = "traefik__Runbot"
    passHostHeader = true
    priority =  5
    [frontends.traefik__Runbot.routes.service]
      rule = "HostRegexp:{subdomain:.+}.runbot.laslabs.io;Host:traefik.runbot.runbot.laslabs.io;"
  [frontends.web__Runbot]
    backend = "web__Runbot"
    passHostHeader = true
    priority =  5
    [frontends.web__Runbot.routes.service]
      rule = "Host:web.runbot.runbot.laslabs.io,runbot.laslabs.io;"
```
