### ISSUE TITLE
Rancher Backend: Containers from different services cannot be registered to the same backend

### ISSUE THREAD

**Issue by Starfox64** [containous/traefik#1904]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am setting up a minio cluster however I'm using multiple services to have fine grained controls over the configuration of each minio instance (volume paths). To do this I used the `traefik.backend=minio` label to try and put all the services in the same backend.

### What did you expect to see?
A backend with all containers in every service marked with the `traefik.backend=minio` label.

### What did you see instead?
A backend containing all containers of the last service marked with the `traefik.backend=minio` label. The first service is overwritten. (Caused by this [line](https://github.com/containous/traefik/blob/d653a348b1d6ec352ef2c341636153a5f45619f1/provider/rancher/rancher.go#L240))

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.4
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-27_03:52:53PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

debug = true
logLevel = "ERROR"


MaxIdleConnsPerHost = 200

defaultEntryPoints = ["http", "https"]


[acme]
email = "XXX"
storage = "/config/acme.json"
entryPoint = "https"
acmeLogging = true
OnHostRule = true
onDemand = false


# Entrypoints definition
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[retry]
attempts = 3


################################################################
# Web configuration backend
################################################################

[web]

address = ":8080"
ReadOnly = true
[web.auth.basic]
   users = ["XXX:XXX"]


################################################################
# Rancher configuration backend
################################################################

[rancher]

domain = "XXX"
Watch = true
RefreshSeconds = 15
ExposedByDefault = false
EnableServiceHealthFilter = true
Endpoint = "XXX"
AccessKey = "XXX"
SecretKey = "XXX"


################################################################
# Static rules
################################################################

[file]

[backends]
   [backends.traefik]
     [backends.traefik.servers.self]
     url = "http://127.0.0.1:8080"

[frontends]
   [frontends.traefik]
   backend = "traefik"
     [frontends.traefik.routes.host]
     rule = "Host: traefik.XXX.com"
```

docker-compose.yml
```yml
version: '2'
services:
  minio2:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: XXX
      MINIO_SECRET_KEY: XXX
    stdin_open: true
    volumes:
    - /var/minio2_export1:/export1
    - /var/minio2_export2:/export2
    - /var/minio2_config/root/.minio
    tty: true
    command:
    - server
    - http://minio1/export1
    - http://minio1/export2
    - http://minio2/export1
    - http://minio2/export2
    labels:
      traefik.frontend.rule: 'Host: minio.XXX.com'
      traefik.enable: 'true'
      traefik.backend: minio
      traefik.port: '9000'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  minio1:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: XXX
      MINIO_SECRET_KEY: XXX
    stdin_open: true
    volumes:
    - /var/minio1_export1:/export1
    - /var/minio1_export2:/export2
    - /var/minio1_config:/root/.minio
    tty: true
    command:
    - server
    - http://minio1/export1
    - http://minio1/export2
    - http://minio2/export1
    - http://minio2/export2
    labels:
      traefik.frontend.rule: 'Host: minio.XXX.com'
      traefik.enable: 'true'
      traefik.backend: minio
      traefik.port: '9000'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

```
