### ISSUE TITLE
Performance drop when using HTTPS together with compression

### ISSUE THREAD

**Issue by miadabrin** [containous/traefik#1908]
### Do you want to request a *feature* or report a *bug*?

Report a bug

### What did you do?

I have been using the version 1.3.4 with kubernetes as an ingress controller and compression enabled.
The performance becomes very bad after 3 or 4 hours

### What did you expect to see?

I expected the performance to remain the same .

### What did you see instead?

requests take too long to respond. especially static resources like js files. The issue is gone when I restart the pod 

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.3.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
logLevel = "WARN"
MaxIdleConnsPerHost = 1000

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
```
