### ISSUE TITLE
Traefik  & https  err  "bad TLS Certificate KeyFile format"

### ISSUE THREAD

**Issue by catfish34** [containous/traefik#1914]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Traefik works excellent with http on my docker-swarm. However I want to use traefik  with https support.  So I generated certificates and use them

### What did you expect to see?
I expect that traefik will work

### What did you see instead?
However after I run command #docker stack deploy --compose-file ./compose-traefik.yml traefik
traefik  cintainer does not up and service have err in log:

```shell
level=fatal msg="Error preparing server: bad TLS Certificate KeyFile format, expected a path"
level=info msg="Preparing server https &{Network: Address::443 TLS:0xc420429f20 Redirect:<nil> Auth:<nil> Compress:false}"
level=fatal msg="Error preparing server: bad TLS Certificate KeyFile format, expected a path"
```

 ### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.3.5 / raclette
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

compose-traefik.yml file:
```yml
version: '3'

services:
  traefik:
    image: traefik
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /traefik:/data
      - /sslcerts:/ssl
      - /usr/bin:/usr/bin
    command:
      - --accesslogsfile=/data/access.log
      - --web
      - --docker
      - --debug
      - --docker.swarmmode
      - --docker.domain="traefik"
      - --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"    #Redirect
      - --entryPoints="Name:https Address::443 TLS:/ssl/tls.crt,/ssl/tls.key" # cert files
      - --defaultEntryPoints="http,https"                                                       # EntryPoints**
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3
      placement:
        constraints:
          - "node.role == manager"

networks:
  traefik-net:
    external: true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
Full debug log:
```shell
 time="2017-08-03T11:37:36Z" level=info msg="Traefik version v1.3.5 built on 2017-08-01_04:18:59PM"
 time="2017-08-03T11:37:36Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"/data/access.log","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":{"EntryPoint":"https\"","Regex":"","Replacement":""},"Auth":null,"Compress":false},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":[{"CertFile":"/ssl/tls.crt","KeyFile":"/ssl/tls.key\""}],"ClientCAFiles":null},"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["\"http","https\""],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":{"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"\"traefik\"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":true},"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}"
 time="2017-08-03T11:37:36Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc42074fec0 Redirect:<nil> Auth:<nil> Compress:false}"
 time="2017-08-03T11:37:36Z" level=error msg="Error creating TLS config: bad TLS Certificate KeyFile format, expected a path"
 time="2017-08-03T11:37:36Z" level=fatal msg="Error preparing server: bad TLS Certificate KeyFile format, expected a path"
 time="2017-08-03T11:37:36Z" level=info msg="Traefik version v1.3.5 built on 2017-08-01_04:18:59PM"
 time="2017-08-03T11:37:36Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"/data/access.log","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":{"EntryPoint":"https\"","Regex":"","Replacement":""},"Auth":null,"Compress":false},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":[{"CertFile":"/ssl/tls.crt","KeyFile":"/ssl/tls.key\""}],"ClientCAFiles":null},"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["\"http","https\""],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":{"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"\"traefik\"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":true},"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}"
 time="2017-08-03T11:37:36Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc420252360 Auth:<nil> Compress:false}"
 time="2017-08-03T11:37:36Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4200434a0 Redirect:<nil> Auth:<nil> Compress:false}"
 time="2017-08-03T11:37:36Z" level=error msg="Error creating TLS config: bad TLS Certificate KeyFile format, expected a path"
 time="2017-08-03T11:37:38Z" level=info msg="Traefik version v1.3.5 built on 2017-08-01_04:18:59PM"
 time="2017-08-03T11:37:38Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"/data/access.log","TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":{"EntryPoint":"https\"","Regex":"","Replacement":""},"Auth":null,"Compress":false},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":[{"CertFile":"/ssl/tls.crt","KeyFile":"/ssl/tls.key\""}],"ClientCAFiles":null},"Redirect":null,"Auth":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["\"http","https\""],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":{"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"\"traefik\"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":true},"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}"
 time="2017-08-03T11:37:38Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc4205a5800 Auth:<nil> Compress:false}"
 time="2017-08-03T11:37:36Z" level=fatal msg="Error preparing server: bad TLS Certificate KeyFile format, expected a path"
 time="2017-08-03T11:37:38Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc420429f20 Redirect:<nil> Auth:<nil> Compress:false}"
 time="2017-08-03T11:37:38Z" level=error msg="Error creating TLS config: bad TLS Certificate KeyFile format, expected a path"
 time="2017-08-03T11:37:38Z" level=fatal msg="Error preparing server: bad TLS Certificate KeyFile format, expected a path"
 time="2017-08-03T11:37:38Z" level=info msg="Starting server on :80"

```

As I understand problem with "bad TLS Certificate KeyFile format". But this cert files works good with nginx on my server.
I generated it by command:
`#openssl req         -newkey rsa:2048 -nodes -keyout tls.key         -x509 -days 365 -out tls.crt`

**Comment by dtomcej** [comment]
@catfish34 first of all, your compose file does not specify an image tag, you should specify one manually when debugging. If you run the alpine image instead of the production image, you can shell in, and verify that your certificates are mounting properly.

Can you verify the permissions of the files mounted in the container?

**Comment by robertgartman** [comment]
I see the same error.

compose file:

```
version: '3.3'

services:

  socketproxy:
    image: rancher/socat-docker
    networks:
      - socketproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]                                           
      restart_policy:
        condition: on-failure

  traefik:
    image: traefik:1.3.5-alpine
    command: >
      --web
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.domain=traefik
      --docker.endpoint=tcp://socketproxy:2375
      --entryPoints='Name:https Address::443 TLS:/run/secrets/cert-dotnet-chain-without-key, /run/secrets/cert-dotnet-key'
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - proxy
      - socketproxy
    depends_on:
      - "socketproxy"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    secrets:
      - source: cert-dotnet-key
        target: cert-dotnet-key
        mode: 0777
      - source: cert-dotnet-chain-without-key
        target: cert-dotnet-chain-without-key
        mode: 0777

networks:
  proxy:
    external: true
  socketproxy:
    external: true


secrets:
  cert-dotnet-key:
    external: true
  cert-dotnet-chain-without-key:
    external: true
```

Verifying the permissions of the TLS files within a  traefik task container:
```
root:/# docker exec -ti daee618d0e56 /bin/sh
/ # ls -la /run/secrets/
total 12
drwxr-xr-x    2 root     root            66 Aug  6 11:59 .
drwxr-xr-x    3 root     root            21 Aug  6 11:59 ..
-rwxr-xr-x    1 root     root          7547 Aug  6 11:59 cert-dotnet-chain-without-key
-rwxr-xr-x    1 root     root          1679 Aug  6 11:59 cert-dotnet-key 
```
