### ISSUE TITLE
Provide health check information in API response

### ISSUE THREAD

**Issue by maclover7** [containous/traefik#1916]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

GET /api

### What did you expect to see?

I have health checks configured for my various different backends via `traefik.backend.healthcheck.path` and `traefik.backend.healthcheck.interval`, and expected to see the results of those health checks somewhere within the API response.

### What did you see instead?

This data was not present in the API response. It looks like there is an already an open issue (#1783) to present this data in the dashboard interface, which would be amazing as well.

I've been spelunking around the Traefik codebase trying to figure out how to provide this data through the API, and I'm not entirely sure it's possible without a refactoring. Whether the backend is up or down is already stored via `BackendHealthCheck.LB.UpsertServer` and `BackendHealthCheck.LB.RemoveServer`. I am not super familiar with Go (I'm a Rubyist at heart), but if anyone can provide some pointers about how I might be able to make this change, I would be happy to open up a pull request.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_04:18:59PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Fairly stock setup with the Docker provider:

```toml
# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[web]
address = ":8080"

# Connection to docker host system (docker.sock)
[docker]
```
