### ISSUE TITLE
ACME udp i/o timeout

### ISSUE THREAD

**Issue by navinSing** [containous/traefik#1921]
After trying out for more than 7 hours : 
I am getting a udp error.. Not sure what is the reason.. do i need to open more ports ..
note i am running this in docker swarm(exposed ports, hence it was able to connect and request for certs).
Also, not clear from the documentation, where the certificates gets created, is it a new file .pem or within the acmee.json

```toml
[entryPoints]
   	[entryPoints.http]
	address = ":80"
   	[entryPoints.https]
   	address = ":443"
     	[entryPoints.https.tls]

defaultEntryPoints = ["http", "https"]
[acme]
entryPoint = "https"
email = "xxxxxxxx.b@gmail.com"
#delayDontCheckDNS = 0
#acmeLogging = false
onDemand = true
#dnsProvider = "manual"
#storage = "traefik/acme/account"
# https://letsencrypt.status.io/
caServer = "https://acme-v01.api.letsencrypt.org/directory"
storage = "/etc/traefik/acme.json" 
# or "traefik/acme/account" if using KV store
[[acme.domains]]
   main = "aaaaaaaa.com"
   sans = ["www.aaaaaaa.com"]

```

 
Using traefik:latest
within docker 
```
| 2017/08/06 00:08:06 server.go:2753: http: TLS handshake error from 10.255.0.2:59452: Cannot obtain certificates map[aaaaa.com:Time limit exceeded. Last error: NS ns15.domaincontrol.com. returned NXDOMAIN for _acme-challenge.api.remitgulf.com.]+v
 | 2017/08/06 00:08:10 server.go:2753: http: TLS handshake error from 10.255.0.2:59822: Cannot obtain certificates map[aaaaa.com:Error presenting token: read udp 127.0.0.1:57243->127.0.0.11:53: i/o timeout]+v
```
