### ISSUE TITLE
Config resets when Rancher is unavailable

### ISSUE THREAD

**Issue by adamgraves-choices** [containous/traefik#1927]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deployed a Traefik instance in my Rancher configuration, which uses the Rancher API backend to generate it's config. Repo here: https://github.com/nhsuk/traefik-rancher/

When the API is activated and Rancher is available it works correctly. If I deactivate the API key or the Rancher service is unavailable the config is reset and is empty.

### What did you expect to see?

I would expect the config to remain the same, until the API is available again.

### What did you see instead?

The frontend and backend config was cleared.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_03:55:31PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

debug = false
logLevel = "INFO"
traefikLogsFile = "/opt/traefik/log/traefik.log"
accessLogsFile = "/opt/traefik/log/access.log"


defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
       compress = true
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/ssl.crt"
      keyFile = "/opt/traefik/certs/ssl.key"

[rancher]
domain = "XXXXXX"
Watch = true
Endpoint = "https://XXXXX"
AccessKey = "XXXXX"
SecretKey = "XXXXX"

ExposedByDefault = false
EnableServiceHealthFilter = false
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
