### ISSUE TITLE
treafik 1.3.5, traefikui not found providers...

### ISSUE THREAD

**Issue by icyblazek** [containous/traefik#1928]
this is pod logs...
```
ERROR: logging before flag.Parse: E0808 11:57:09.535791      11 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.Ingress: Get https://10.8.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=0: dial tcp 10.8.0.1:443: i/o timeout
ERROR: logging before flag.Parse: E0808 11:57:09.535883      11 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: Get https://10.8.0.1:443/api/v1/secrets?resourceVersion=0: dial tcp 10.8.0.1:443: i/o timeout
```

traefik version:  v1.3.5
Docker Server:
 Version:      17.07.0-ce-rc1
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 03:50:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
Kubernetes: v1.7.3

```
//Kuberentes api config
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.8.0.0/16"
```

==================================================
//DaemonSet config 
```yaml
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-lb
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      restartPolicy: Always
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8580
        args:
        - --web
        - --web.address=:8580
        - --kubernetes
```
