### ISSUE TITLE
Marathon Backend is not started when Consul and File Backend exists.

### ISSUE THREAD

**Issue by hikoz** [containous/traefik#1931]
### Do you want to request a *feature* or report a *bug*?
*bug*

### What did you do?

Marathon-provider is not started correctly when started traefik with Marathon, Consul and File Backend.
But after changed app in marathon, traefik caught event like below and marathon provider start running correctly.
```
DEBU[xxxxxxxx] Provider event receveivedtype: status_update_event, event: &{status_update_event ....
```

### What did you expect to see?
```
$ curl -s 0:8081/api | jq -r 'keys|join(",")'
consul,file,marathon
```

### What did you see instead?
```
$ curl -s 0:8081/api | jq -r 'keys|join(",")'
consul,file
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_03:55:31PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":8080"

[web]
address = ":8081"

[marathon]
endpoint = "http://marathon.example.com"
domain = "sub.example.com"

[consul]
prefix = "traefik"

[file]
  [frontends]
    [frontends.mm]
    backend = "mm"
      [frontends.mm.routes.mm]
      rule = "Host:mm.example.com"
  
  [backends]
    [backends.mm]
      [backends.mm.servers.server1]
      url = "http://10.0.0.2:2080"
```
