### ISSUE TITLE
Websocket based on headers 

### ISSUE THREAD

**Issue by navinSing** [containous/traefik#1936]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
https://www.haproxy.com/blog/websockets-load-balancing-with-haproxy/

want to connect to websocket using http headers, similar to what is provided by haproxy : 
```
frontend public
  bind *:80
  ## routing based on websocket protocol header
  acl hdr_connection_upgrade hdr(Connection)  -i upgrade
  acl hdr_upgrade_websocket  hdr(Upgrade)     -i websocket
 
  use_backend bk_ws if hdr_connection_upgrade hdr_upgrade_websocket
  default_backend bk_web
```

### What did you expect to see?
using socket.io 
The client is able to connect directly without traefik
client --> (ws-http) --> server

But fails 
client --> traefik(wss-https) --> (ws-http) -->  server

### What did you see instead?
the client starts to poll and then fails with 404 

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.3.5

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
using docker swarm on ubuntu 17

```toml
[entryPoints]
		[entryPoints.http]
		address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https" 
   	[entryPoints.https]
   		address = ":443" 
     	[entryPoints.https.tls]

[acme]
entryPoint = "https"
onDemand = true
#...
[file]
watch = true

  [backends.b_socket]
    [backends.b_socket.servers.server1]
    url = "http://m_chat:80"
    weight = 10

  [frontends.f_socket1]
   entrypoints = ["http","https"]
   priority = 8
	 passHostHeader = true
   backend = "b_socket"
   	[frontends.f_socket1.routes.test_1]
   	rule = "Headers:Connection, Upgrade"

  [frontends.f_socket2]
   entrypoints = ["http","https"]
   priority = 8
	 passHostHeader = true
   backend = "b_socket"
   	[frontends.f_socket2.routes.test_1]
   	rule = "Headers:Upgrade, websocket"

  [frontends.f_socket0]
   entrypoints = ["http","https"]
   priority = 8
	 passHostHeader = true
   backend = "b_socket"
   	[frontends.f_socket0.routes.test_1]
   	rule = "Path:/socket.io"

# few other rules based on path 

```

### If applicable, please paste the log output in debug mode (`--debug` switch)
```shell
time="2017-08-10T08:37:38Z" level=debug msg="Round trip: http://m_chat:80, code: 404, duration: 1.775782ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:xxx.com" 
time="2017-08-10T08:37:40Z" level=debug msg="Round trip: http://m_chat:80, code: 404, duration: 2.754365ms tls:version: 303, tls:resume:true, tls:csuite:c02f, tls:server:xxx.com" 
```
