### ISSUE TITLE
entryPoints not implemented in Kubernetes provider

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#1941]
As far as I can see, the kubernetes provider ignores any entryPoints settings defined on the ingress.
Example ingress definition:
```yml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-v1-internal
  annotations:
     traefik.frontend.rule.type: PathPrefixStrip
     traefik.frontend.entryPoints: http-secure
     traefik.frontend.passHostHeader: "true"
```

### What did you expect to see?
Traefik whould wire up the frontend on the named entryPoint

### What did you see instead?
Traefik wires up the frontend using the default entryPoint(s)
```shell
[2017-08-11T12:41:37+02:00] Wiring frontend catchall.dev.domain.com/ to entryPoint http 
DEBU[2017-08-11T12:41:37+02:00] Creating route catchall.dev.domain.com Host:catchall.dev.domain.com 
DEBU[2017-08-11T12:41:37+02:00] Creating route / PathPrefixStrip:/
```
### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_03:55:31PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Testing locally on Ubuntu 17, usinge kubectl proxy.

```toml
debug = true
defaultEntryPoints = ["http"]

[web]
address = ":30002"

[entryPoints]
  [entryPoints.http]
  address = ":30000"
  compress = true
  [entryPoints.http-secure]
  address = ":30001"
  compress = true

[kubernetes]
endpoint = "http://localhost:8001"
```
