### ISSUE TITLE
Page keeps reloading when using websockets since 1.3.5

### ISSUE THREAD

**Issue by pstreef** [containous/traefik#1959]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've recently updated from 1.3.2 to 1.3.5 and my (Vaadin) web application which uses Websocket (XHR) push went from working well to constantly reloading.

When I change the Push protocol to long polling (basically not using websockets at all) it works normally again.

I've been able to reproduce this by going back and forth between 1.3.2 and 1.3.5 (currently latest)

I'm aware this is a pretty thin explanation of this bug. So if any additional info is needed please ask!

### What did you expect to see?

Page loading normally and updating via push.

### What did you see instead?

Page constantly reloading (every few hundred ms)

### Output of `traefik version`: (_What version of Traefik are you using?_)

__Working docker image tag__ traefik:1.3.2
__NOT Working docker image tag__ traefik:1.3.5 (or latest)

my output for `docker run traefik version` (not sure if this is for the correct image though..)
```
Version:      v1.3.1
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-16_11:21:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

running in docker. My toml:

```toml
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log//traefik/access.log"
logLevel = "DEBUG"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedbydefault = false
swarmmode = true

[web]
address = ":8080"
  [web.auth.basic]
    users = ["admin:thisisnotmypassword"]
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

nothing special in logs.
