### ISSUE TITLE
Route sorting is not working as expected

### ISSUE THREAD

**Issue by Vad1mo** [containous/traefik#1962]
According to the docs routes are sorted using routes length.

> By default, routes will be sorted (in descending order) using rules length (to avoid path overlap): PathPrefix:/12345 will be matched before PathPrefix:/1234 that will be matched before PathPrefix:/1.

When I run the below  compose example and curl the url ` curl http://sample.127.0.0.1.xip.io/v2/asdf`
then it routes to the  backend **web** however I was expecting to get a route to **api** because of the v2 prefix that is longer in the api then in web.

```
  version: '2'
  services:
#---#
    proxy:
      image: traefik:1.3-alpine
      command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --docker.endpoint=unix:///var/run/docker.sock
      ports:
        - 80:80
        - 443:443
      labels:
        - traefik.enable=false
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml
#---#
    service_web:
      image: vad1mo/hello-world-rest
      hostname: web
      labels:
        - traefik.backend=web
        - traefik.port=5050
        - traefik.frontend.rule=Host:sample.127.0.0.1.xip.io;PathPrefix:/,/v2/webhook,/v2/token
        - traefik.frontend.entryPoints=http
#        - traefik.priority = 5
#---#
    service_api:
      image: vad1mo/hello-world-rest
      hostname: api
      labels:
        - traefik.backend=api
        - traefik.port=5050
        - traefik.frontend.rule=Host:sample.127.0.0.1.xip.io;PathPrefix:/v2
        - traefik.frontend.entryPoints=http
       # - traefik.priority = 10
```
