### ISSUE TITLE
Traefik camel cases response headers

### ISSUE THREAD

**Issue by davidgenn** [containous/traefik#1969]
### Do you want to request a *feature* or report a *bug*?

Bug
### What did you do?
Traefik in consul-catalogue mode.

### What did you expect to see?
Traefik returns backend response headers un-altered.

### What did you see instead?
Headers are camel cased eg:

X-MY-APPLICATION-HEADER: 12345

is returned as:

X-My-Application-Header: 12345

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.3.5

### TOML
```toml
[consulCatalog]

endpoint = "127.0.0.1:8500"
domain = "service.consul"

frontEndRule = "Host:{{ServiceName}}.{{Domain}},PathPrefixStrip:/{{ServiceName}}"
prefix = "traefik"
```
