### ISSUE TITLE
Error dialing `${HOST}`: websocket: bad handshake

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#1973]
### What did you do?

set up a service with web-socket support provided by **socket.io** library

### What did you expect to see?

Web Socket working

### What did you see instead?

```Error dialing `${HOST}`: websocket: bad handshake"``` message in the log

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_04:18:59PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#######################################################
# Global configuration
#######################################################

defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

#######################################################
# Entrypoints definition
#######################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    compress = false
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    compress = false

#######################################################
# Management interface
#######################################################

[web]
address = ":8080"
[web.statistics]
  RecentErrors = 10

#######################################################
# Docker configuration backend
#######################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ traefik_docker_domain }}"
watch = true
exposedbydefault = true
swarmmode = true

#######################################################
# ACME (Let's Encrypt) configuration
#######################################################

[acme]
email = "{{ traefik_acme_email }}"
entryPoint = "https"
onDemand = true
onHostRule = false 
{% if traefik_acme_dns_provider is defined %}
dnsProvider = "{{ traefik_acme_dns_provider }}"
{% endif %}
storage = "/acme/acme.json"

```
