### ISSUE TITLE
Let's Encrypt not renewing

### ISSUE THREAD

**Issue by Russell-IO** [containous/traefik#1987]
### Do you want to request a *feature* or report a *bug*?
Report a Bug

### What version of Traefik are you using?
```
Version:      v1.2.0
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-21_09:50:01AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
```json
{
 "GraceTimeOut": 10,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "",
 "TraefikLogsFile": "",
 "LogLevel": "ERROR",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": {
    "EntryPoint": "https",
    "Regex": "",
    "Replacement": ""
   },
   "Auth": null,
   "Compress": false
  },
  "https": {
   "Network": "",
   "Address": ":443",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": null,
    "ClientCAFiles": null
   },
   "Redirect": null,
   "Auth": null,
   "Compress": false
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": {
  "Email": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Domains": null,
  "Storage": "traefik/acme/account",
  "StorageFile": "",
  "OnDemand": true,
  "OnHostRule": false,
  "CAServer": "",
  "EntryPoint": "https",
  "DNSProvider": "",
  "DelayDontCheckDNS": 0,
  "ACMELogging": true,
  "TLSConfig": null
 },
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "InsecureSkipVerify": false,
 "Retry": null,
 "Docker": null,
 "File": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": null,
  "Metrics": null,
  "Auth": null
 },
 "Marathon": null,
 "Consul": {
  "Watch": true,
  "Filename": "",
  "Constraints": [],
  "Endpoint": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Prefix": "traefik",
  "TLS": null
 },
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

### What did you do?
Left Traefik running

### What did you expect to see?
Let's Encrypt certificate renewed

### What did you see instead?
Certificate expired

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.2.0
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-21_09:50:01AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#logLevel = "DEBUG"
#logLevel = "INFO"
#logLevel = "WARN"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[web]
address = ":8080"

[consul]
endpoint = "127.0.0.1:8500"
watch = true
prefix = "traefik"

[acme]
email = "hostmaster@REMOVED.net"
storage = "traefik/acme/account"
entryPoint = "https"
onDemand = true
acmeLogging = true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
Unable to get debug output, if I restart Traefik, the certificate renews, but this happened every 3 months
These logs are repeated:

```{
  "log": "2017/08/22 08:28:28 server.go:2317: http: TLS handshake error from 138.201.47.186:35312: remote error: tls: unknown certificate\n",
  "stream": "stderr",
  "time": "2017-08-22T08:28:28.093810763Z"
}
{
  "log": "time=\"2017-08-22T08:28:45Z\" level=debug msg=\"Challenge GetCertificate removed.net\" \n",
  "stream": "stderr",
  "time": "2017-08-22T08:28:45.707229073Z"
}
{
  "log": "time=\"2017-08-22T08:28:45Z\" level=debug msg=\"ACME got domain cert removed.net\" \n",
  "stream": "stderr",
  "time": "2017-08-22T08:28:45.707284615Z"
}
```

And after updating 1.3.5, it's still providing the old certificate and not renewing
```
time="2017-08-22T08:34:35Z" level=debug msg="Look for provided certificate to validate [removed.net]..."
time="2017-08-22T08:34:35Z" level=debug msg="No provided certificate found for domains [removed.net], get ACME certificate."
time="2017-08-22T08:34:35Z" level=debug msg="Challenge GetCertificate removed.net"
time="2017-08-22T08:34:35Z" level=debug msg="ACME got domain cert removed.net"
```
