### ISSUE TITLE
Error starting provider *kubernetes.Provider: endpoint missing for external cluster client

### ISSUE THREAD

**Issue by Starefossen** [containous/traefik#1989]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Deployed Træfik to Kubernetes as a DaemonSet.

### What did you expect to see?

I expected all instances (Pods) of Træfik to have the same configuration.

### What did you see instead?

One of the pods had the following console log error message and no other configuration:

```
Error starting provider *kubernetes.Provider: endpoint missing for external cluster client
``` 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.3.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
checkNewVersion = false                                    
                                                           
logLevel = "WARN"                                          
                                                           
InsecureSkipVerify = true                                  
                                                           
defaultEntryPoints = ["http", "https"]                     
                                                           
[entryPoints]                                              
  [entryPoints.http]                                       
  address = ":80"                                          
                                                           
  [entryPoints.https]                                      
  address = ":443"                                         
    [entryPoints.https.tls]                                
      [[entryPoints.https.tls.certificates]]               
      CertFile = "**REDACTED**.pem"
      KeyFile = "**REDACTED**.key" 
                                                           
[web]                                                      
address = ":8181"                                          
                                                           
[web.metrics.prometheus]                                   
Buckets=[0.1,0.3,1.2,5.0]                                  
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
