### ISSUE TITLE
empty acme.json ({}) cause bootloop to traefik

### ISSUE THREAD

**Issue by dottgonzo** [containous/traefik#1991]
Hi,
thanks for this wonderful piece of software!

There is an issue with acme and swarm mode if i want to use the acme.json file (no consul).

I've tried several modes to be able to use traefik in swarm mode + acme, after many hours, i see that the only working method is NOT passing EMPTY acme.json ({})! 

To get traefik working in swarm mode start the service without the file (but writing the path on the toml),  wait until traefik generate the new acme file, then copy IT outside to be able to use the file as traefik generate it, and store it outside the container

**Comment by nmengin** [comment]
Hello @dottgonzo, thank you for your interest for the project.
Can you give more precision about your `acme.json` file. Is it empty or does it contain `{}`?
Has it the good rights (600)?

**Comment by dottgonzo** [comment]
@nmengin 
sorry for this misunderstood, but first i've written the post, then by myself was thinking about the issue and effectively "empty file was not correct", i've used an empty json inside the file acme.json (sure, permission 600). That because in past i've used traefik, thanks to a guide in which the docker-compose had an acme.json file that contains an empty json (and it worked). Now i've not effectively tried with an empty file (not an empty json), if i will find the time, i will retry with an empty file also. In meanwhile thanks for all, next days i will try to use consul to switch from my current system to a redundant swarm.

**Comment by turbo** [comment]
I get the same error, a completely empty acme.json, with the right permissions will cause traefik to enter a fail and restart loop. Config for reference:

```yaml
traefik:
    restart: always
    image: traefik
    command: --docker --logLevel=DEBUG
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:router.[REDACTED]'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    logging:
      driver: gelf
      options:
        gelf-address: "udp://[REDACTED]:12201"
        tag: "Server: Traefik"
```

TOML:

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "[REDACTED]"
storage = "/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
```
