### ISSUE TITLE
Persist X-Forwarded-Proto header from upstream

### ISSUE THREAD

**Issue by taiidani** [containous/traefik#1997]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Spun up a service with an AWS ELB that terminates SSL in front of Traefik. In the below diagram the ELB:
* Passes port 80 through so that Traefik issues a 302 redirect to port 443.
* Terminates port 443 and passes it to Traefik on port 81, which is configured to pass through to the service.

![temporary_for_traefik 1](https://user-images.githubusercontent.com/902500/29581169-5c97a0a0-872d-11e7-988e-bcd33326f477.png)

### What did you expect to see?

The X-Forwarded-Proto header from the AWS LB would pass through to the final service as "https", which is what the AWS LB set.

### What did you see instead?

Traefik appears to be replacing this header with its own X-Forwarded-Proto header when it passes through port 81. The final service sees "http" for the value of the header and incorrectly assumes that it is being served insecurely.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.3.6

Or for the exact image:
traefik:latest@sha256:83dc4274db668b6b0d0685ae53a5517eb8e2245f949e6072747cec428d3faf4a
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

From the Docker Swarm stack definition:
```yml
app:
    image: traefik:latest
    command: --web --docker --docker.swarmmode --docker.watch --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --entryPoints='Name:internal Address::81' --defaultEntryPoints=http,https --acme.entryPoint=https --acme.email=devops+traefik@domain.com --acme.storage=/etc/traefik/acme/acme.json --acme.onHostRule=true
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
```
