### ISSUE TITLE
Dashboard is returned broken as a template when redirected through the proxy port

### ISSUE THREAD

**Issue by omerxx** [containous/traefik#1998]
### What did you do?

I serve traefik with one port (80) on production so in order to receive `api`, `health` and `dashboard` I redirected them all using traefik file backend:

``` toml
[backends]
  [backends.health]
    [backends.health.servers.server]
    url = "http://127.0.0.1:8080/health"
    weight = 1
  [backends.dashboard]
    [backends.dashboard.servers.server]
    url = "http://127.0.0.1:8080"
    weight = 1
  [backends.api]
    [backends.api.servers.server]
    url = "http://127.0.0.1:8080/api"
    weight = 1

[frontends]
  [frontends.health]
  backend = "health"
    [frontends.health.routes.default]
    rule = "Path:/health"
  [frontends.dashboard]
  backend = "dashboard"
    [frontends.dashboard.routes.default]
    rule = "Path:/dashboard/"
  [frontends.api]
  backend = "api"
    [frontends.api.routes.default]
    rule = "Path:/api"
```

### What did you expect to see?

I expected to see all three being returned as if I was actualy sending the request to port `8080`.

### What did you see instead?
`api` and `health` are being returned as expected, while dashboard is broken.
I looked at the code, and I've noticed a redirection, yet I can't explain the broken response.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/12237955/29604001-c523fc4c-87ee-11e7-9771-405619285aa9.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_04:18:59PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
My `rules.toml` is provided above, here's my `traefik.toml`:
```toml
# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"

[file]
filename = "/etc/traefik/rules.toml"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
Running locally, trying to reach `127.0.0.1/dashboard` (using traefik for routing the dashboard):
```
traefik_1  | time="2017-08-23T07:37:55Z" level=debug msg="Round trip: http://127.0.0.1:8080, code: 200, duration: 4.660818ms"
```
