### ISSUE TITLE
Wrong HTTPS redirect when also using AddPrefix

### ISSUE THREAD

**Issue by schoren** [containous/traefik#2024]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using traefik as a kubernetes ingress controller. I have configured HTTPS redirect as follows in the TOML config file:

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
```

I have also configured an ingress like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: "AddPrefix"
spec:
  tls:
  - hosts:
    - demo.example.com
    secretName: tls
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /path
        backend:
          serviceName: myservice
          servicePort: 80
```

### What did you expect to see?

When accessing `http://demo.example.com`, I wanted it to redirect to `https://demo.example.com`.

### What did you see instead?

When accessing `http://demo.example.com`, I wanted it to redirect to `https://demo.example.com/path`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.7
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-25_08:56:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
[acme]
email = "certmaster@example.com"
storage = "/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
acmelogging = true
caServer = "https://acme-v01.api.letsencrypt.org/directory"
acmeLogging = true
```
