### ISSUE TITLE
replicated traefik + acme cause issues

### ISSUE THREAD

**Issue by dottgonzo** [containous/traefik#2025]
**Do you want to request a feature or report a bug?**

Bug

**What did you do?**

I've replicated traefik over multiple managers on docker swarm (traefik is deployed with mode global), with toml and acme placed on a replicated folder on same path of every node

**What did you expect to see?**

acme and traefik still continue to works

**What did you see instead?**

the web ui has errors on page Health (because of replica rotation), but this is the minor problem.

Every time a new service start, every container start it's request to acme for a new certificate, one request per traefik replica (so if something goes wrong i've many certificate issues with acme)

the process log show this repeated for every replica:

```
acme: Obtaining bundled SAN certificate 
AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/...........................
acme: Trying to solve TLS-SNI-01
```

```
Error getting ACME certificates ......: Cannot obtain certificates......
Error 400 - urn:acme:error:connection - Timeout
proxy_traefik.0.3r8bmgawria5@swarman    | Error Detail:
proxy_traefik.0.3r8bmgawria5@swarman    | 	Validation for XXXXXXX.com:443
proxy_traefik.0.3r8bmgawria5@swarman    | 	Resolved to:
proxy_traefik.0.3r8bmgawria5@swarman    | 		XXX.XXX.XXX.XXX
proxy_traefik.0.3r8bmgawria5@swarman    | 	Used: XXX.XXX.XXX.XXX
proxy_traefik.0.3r8bmgawria5@swarman    | 
```
the XXX.XXX.XXX.XXX ip are equals

**Output of traefik version: (What version of Traefik are you using?)**

v1.3.7 / raclette docker image

**What is your environment & configuration (arguments, toml, provider, platform, ...)?**

this is my compose

```yml
version: '3.3'

networks:
  traefik-net:
    external: true

services:
  traefik:
    image: traefik
    command: --web --docker --docker.swarmmode --logLevel=INFO
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /cloud/volumes/services/traefik/traefik.toml:/traefik.toml
      - /cloud/volumes/services/traefik/acme.json:/acme.json
    deploy:
      mode: global
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:XXXX.XXX.XXX
        - traefik.docker.network=traefik-net
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 10s
      placement:
        constraints:
          - node.role == manager
```

this is my toml

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[web]
address = ":8080"

# Connection to docker host system (docker.sock)
[docker]

watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  
# Let's encrypt configuration
[acme]
  email="XXX@XXXXX.XXX"
  storage="/acme.json"
  entryPoint="https"
  acmeLogging=true
  onDemand=true
  OnHostRule=true
```
