### ISSUE TITLE
Use labels to set custom HTTP headers in Docker backend

### ISSUE THREAD

**Issue by DamiaPoquet** [containous/traefik#2028]
### Do you want to request a *feature* or report a *bug*?

Request a feature

### What did you do?

Add a label to the Docker container like this:

traefik.frontend.customResponseHeaders=X-Custom-Header: foo; bar

### What did you expect to see?

Traefik should use the Header Middleware described in #1236 to serve the application with the desired header.

### What did you see instead?

Nothing happens.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc1
Codename:     roquefort
Go version:   go1.9
Built:        2017-08-29_08:35:24AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
graceTimeOut = "10s"
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/access.log"
logLevel = "WARN"

[acme]
email = "test@test.test"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
OnHostRule = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.domain"
watch = true
exposedbydefault = false

```
