### ISSUE TITLE
Stickiness info in the Web UI

### ISSUE THREAD

**Issue by voidengineer** [containous/traefik#2032]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Configured `"traefik.backend.loadbalancer.sticky": "true"` as marathon label and enabled Web UI

### What did you expect to see?

The configured stickiness of a backend load balancer (maybe next to the used loadbalancing method)

### What did you see instead?

No indication about stickiness

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.7
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-25_08:36:23PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"

[marathon]
endpoint = "http://172.17.0.1:8000"
exposedByDefault = false
domain = "traefik.local"
groupsAsSubDomains = true

[marathon.basic]
httpBasicAuthUser = "<redacted>"
httpBasicPassword = "<redacted>"

[web]
address = ":8080"
readonly = true
```
Ubuntu-16.04-LTS, Marathon Version 0.11.1
