### ISSUE TITLE
Multiple frontend generate duplicate key

### ISSUE THREAD

**Issue by GabKlein** [containous/traefik#2037]
When I'm using the multiple frontend feature on docker swarm using traefik 1.3.7 and 3 replicas containers, it generates the following error message ` Key 'backends.backend-websocket.servers.service' has already been defined.`

### What did you do?

```yml
deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 10s
      labels:
        - traefik.external.port=3000
        - traefik.external.docker.network=external-network
        - traefik.external.frontend.entryPoints=public
        - traefik.external.frontend.rule=Host:websocket.public.com
        - traefik.external.frontend.passHostHeader=true
        - traefik.external.backend.loadbalancer.method=wrr
        - traefik.external.backend.maxconn.amount=1000
        - traefik.internal.port=3000
        - traefik.internal.docker.network=external-network
        - traefik.internal.frontend.entryPoints=private
        - traefik.internal.frontend.rule=Host:websocket.private.com
        - traefik.internal.frontend.passHostHeader=true
        - traefik.internal.backend.loadbalancer.method=wrr
        - traefik.internal.backend.maxconn.amount=1000
```

### What did you see instead?

```
traefik_app.0.alrpgmozqphd@production-blue-node-3    | time="2017-08-31T17:54:39Z" level=error msg="Near line 287 (last key parsed 'backends.backend-websocket.servers'): Key 'backends.backend-websocket.servers.service' has already been defined."
```
