### ISSUE TITLE
error pages doesn't seem to work generically

### ISSUE THREAD

**Issue by miadabrin** [containous/traefik#2047]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
I used this toml file in order to setup traefik as kubernetes ingress controller

```toml
defaultEntryPoints = ["http"]
logLevel = "WARN"
MaxIdleConnsPerHost = 1000

[frontends]
  [errors]
    [error.network]
    status = ["404-405"]
    backend = "error"
    query = "/api/v1/default_backend/not_found"

[backends]
  [backends.error]
    [backends.error.servers.error]
    url = "http://{my_service_ip_here}:{my_service_port}"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://www.(.*)"
      replacement = "http://$1"
```

### What did you expect to see?
I expected the 404 page to show according to my configured backend 

### What did you see instead?
it just uses the old 404 page

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.4-rc1

**Comment by ldez** [comment]
You have a problem with you configuration, please follow this:

```toml
[frontends]
   [frontends.website]
   backend = "website"
  [frontends.website.errors]
    [frontends.website.errors.network]
     status = ["500-599"]
     backend = "error"
     query = "/{status}.html"
```

We had an error in the documentation, it's already fixed by https://github.com/containous/traefik/pull/2038/commits/a05a78c812ce07946f4746eb815a34f05963d370
