### ISSUE TITLE
ProxyProtocol not working on Version 1.4RC1

### ISSUE THREAD

**Issue by cc250080** [containous/traefik#2051]
### What did you expect to see?

Between AWS ELB and traefik a TCP communication which results with traefik being able to receive the external IPs of the requests on the ELB

### What did you see instead?

After I enabled ProxyProtocol on the AWS ELB (I am unsure if this is a bug of traefik or of AWS ELB actually) following this documentation: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html

The traffic on port 443 starts showing below log messages and all communication from traefik to the microservices gets broken. 
```
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:14 server.go:2848: http: TLS handshake error from 10.255.0.2:23666: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:14 server.go:2848: http: TLS handshake error from 10.255.0.3:58006: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:18 server.go:2848: http: TLS handshake error from 10.255.0.4:54219: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:18 server.go:2848: http: TLS handshake error from 10.255.0.5:44426: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:19 server.go:2848: http: TLS handshake error from 10.255.0.5:24596: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:19 server.go:2848: http: TLS handshake error from 10.255.0.2:23678: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:19 server.go:2848: http: TLS handshake error from 10.255.0.3:58020: tls: oversized record received with length 22617
fairgarage_traefik.1.6xim2wre0irk@ip-172-28-44-177.eu-central-1.compute.internal    | 2017/09/04 09:11:21 server.go:2848: http: TLS handshake error from 10.255.0.4:54233: tls: oversized record received with length 22617
```
If I enable ProxyProtocol on port 80 and the entryPoint on http, then http traffic also stops working with error 400.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```yml
 traefik:
    image: traefik:1.4
    command: --web --docker --docker.swarmmode --docker.watch \
      --docker.domain=example.com \
      --logLevel=INFO \
      --defaultEntryPoints='http,https' \
      --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443 TLS:certs/_.example.com.crt,certs/_.example.com.key'
    networks:
      - proxy
      - default
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - /home/docker/certs:/certs
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.id == 6c4foxqulot80ajrpgz7itbzz
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
```
