### ISSUE TITLE
`%!d(<nil>)` instead of dash in access log for unavailable status and content size

### ISSUE THREAD

**Issue by chrif** [containous/traefik#2055]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Enabled access log to file with common format. Tried to parse them with grok but got unusual characters when status and content size are not set.

### What did you expect to see?

A `-` if `OriginStatus` and `OriginContentSize` are not set.

### What did you see instead?

`%!d(<nil>)`

sample:
`12.34.56.78 - - [04/Sep/2017:23:50:10 +0000] "GET / HTTP/1.1" %!d(<nil>) %!d(<nil>) - - 624 - - 0ms`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc1
Codename:     roquefort
Go version:   go1.9
Built:        2017-08-29_08:35:24AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# https://docs.traefik.io/toml/
# https://github.com/containous/traefik/blob/v1.4.0-rc1/docs/configuration/commons.md

logLevel = "INFO"
checkNewVersion = false
defaultEntryPoints = ["http", "https"]

traefikLogsFile = "/opt/log/traefik.log"

[accessLog]
	filePath = "/opt/log/access.log"

[entryPoints]
	[entryPoints.http]
		address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https"
	[entryPoints.https]
		address = ":443"
		[entryPoints.https.tls]

[retry]

[web]
	address = ":8080"
		[web.statistics]
			RecentErrors = 10
		[web.auth.basic]
			users = ["admin:redacted"]

[docker]
	endpoint = "unix:///var/run/docker.sock"
	domain = "redacted"
	watch = true
	exposedbydefault = false

[acme]
	email = "redatced"
	entryPoint = "https"
	OnHostRule = true

	# prod
	storage = "/opt/ssl/acme/acme.json"

	# staging
	# storage = "/opt/ssl/acme/acme-staging.json"
	# caServer = "https://acme-staging.api.letsencrypt.org/directory"

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
