### ISSUE TITLE
the web ui not show multiple frontends/backends placed on the same container

### ISSUE THREAD

**Issue by dottgonzo** [containous/traefik#2065]
### Do you want to request a *feature* or report a *bug*?

minor bug

### What did you do?

this is a service with multiple frontends:

```yml
  master:
    image: arungupta/couchbase
    networks:
      - traefik-net
      - couchdb
    environment:
      TYPE: MASTER
    volumes:
      - /cloud/localdb/couchdb0/dbdata:/common
    deploy:
      labels:
        - traefik.port=11211
        - traefik.frontend.rule=Host:couchdb.XXXXX
        - traefik.docker.network=traefik-net
        - traefik.cluster.port=8091
        - traefik.cluster.frontend.rule=Host:couchadmin.XXXXX
        - traefik.cluster.docker.network=traefik-net
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 5s


```

### What did you expect to see?

All working, and i can see 2 frontends/backends on web ui

### What did you see instead?

I see only 1 frontend/backend, the one labelled with `Host:couchadmin`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik 1.3.7 / raclette

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[web]
address = ":8080"

  [web.auth.digest]
  users = ["admin:traefik:84f9382ed03395f57bb0522555f2bd65"]

# Connection to docker host system (docker.sock)
[docker]

watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  
# Let's encrypt configuration
[acme]
  email="XXX@XXX.XXX"
  storage="/acme.json"
  entryPoint="https"
  acmeLogging=true
  onDemand=true
  OnHostRule=true
```
