### ISSUE TITLE
Traefik does not pickup changes to Consul Catalog in v1.4.0-rc1

### ISSUE THREAD

**Issue by davidgenn** [containous/traefik#2072]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Had traefik successfully running in front of Consul/Nomad under v1.3.5.
Whenever a Nomad deploy updated the Consul catalog, this was reflected in Traefik.

Upgraded to v1.4.0-rc1 of Traefik.
The initial Consul catalog was loaded successfully.
Subsequent changes to Consul eg new service, updated service were not picked up by Traefik.

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.4.0-rc1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug=true
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/access.log"
logLevel = "DEBUG"


[consulCatalog]

endpoint = "127.0.0.1:8500"

domain = "service.consul"

frontEndRule = "Host:{{ServiceName}}.{{Domain}},PathPrefixStrip:/{{ServiceName}}"

prefix = "traefik"
```
