### ISSUE TITLE
Websocket handshake errors

### ISSUE THREAD

**Issue by eskp** [containous/traefik#2078]
### Do you want to request a *feature* or report a *bug*?
Bug.

Possibly related to https://github.com/containous/traefik/issues/1835 and https://github.com/containous/traefik/issues/1900

### What did you do?
Upgrade Traefik to 1.3.6 from 1.3.1 and watch websocket connection no longer working.

Our applications POST request times out with 504 on the new version. 1.3.1 works, returning successfully.

### What did you expect to see?
No errors.

### What did you see instead?
Errors described below.

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.3.1 upgrading to 1.3.6 and up, including 1.4 RC

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker Swarm with Traefik routing to Swarm services from the outside.

```toml
[backends]
  [backends.static]
    [backends.static.servers.server1]
    url = "http://frontend:80"

  [backends.backend]
    [backends.backend.servers.server1]
    url = "http://backend:8080"

[frontends]
  [frontends.backend]
  backend = "backend"
  priority = 5
    [frontends.backend.routes.new]
    rule = "PathPrefix:/api,/wss"

  [frontends.static]
  backend = "static"
  priority = 1
    [frontends.static.routes.new]
    rule = "PathPrefix:/"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

When upgraded to 1.3.6 stopped seeing the following which I presume is a successful handshake:
```
level=debug msg="Writing outgoing Websocket request to target connection: &{Method:GET URL:ws:/wss Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[User-Agent:[Go-http-client/1.1] Connection:[Upgrade] Sec-Websocket-Key:[key_here==] Sec-Websocket-Version:[13] Upgrade:[websocket] X-Device-Token:[token_here]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:host.cloud Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:84.1.1.22:34992 RequestURI:/wss TLS:0xc4208096b0 Cancel:<nil> Response:<nil> ctx:0xc4205c5c80}"
```

Seeing lots of these in both versions:
```
server.go:2753: http: TLS handshake error from 18.6.6.152:39254: read tcp 172.18.0.3:443->18.6.6.152:39254: read: connection reset by peer
server.go:2753: http: TLS handshake error from 18.6.6.152:39272: EOF
```
