### ISSUE TITLE
failed to overriding the port for healthchecks

### ISSUE THREAD

**Issue by fredix** [containous/traefik#2099]
### Do you want to request a *feature* or report a *bug*?

report a bug

### What did you do?

added option port with healthcheck according to this commit : https://github.com/containous/traefik/pull/1567/commits/39e45d0b1bcc34b647bfa5ce412e8cfaef8b2dac

### What did you expect to see?

traefik should use the specified port to check healthcheck of the backends 

### What did you see instead?

traefik ignore the specified port, so it used the path on the backend port which failed

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc2
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-08_07:31:37PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
  [frontends]
    [frontends.toto]
    backend = "toto-services"
      [frontends.toto.routes.test_1]
      rule = "Host:test.toto"
      [frontends.toto.routes.test_2]
      rule = "PathPrefix:/toto-services/path/private"

  [backends]
    [backends.toto-services]
      [backends.toto-services.healthcheck]
        path = "/toto-services/path/health/"
        interval = "10s"
        port = 6667
      [backends.toto-services.servers.server1]
        url = "http://X.X.X.X:6666"
        weight = 1
      [backends.toto-services.servers.server2]
        url = "http://X.X.X.X:6666"
        weight = 1
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

/var/log/traefik/traefik.log

```
"healthCheck":{"path":"/toto-services/path/healthcheck","interval":"10s"}}
```
port is missing
