### ISSUE TITLE
Traefik 1.4.0-rc2 missing on some of my stacks

### ISSUE THREAD

**Issue by fabiorauber** [containous/traefik#2100]
### Do you want to request a *feature* or report a *bug*?

Bug 

### What did you do?

Upgraded traefik from version 1.3.3 - raclette to 1.4.0-rc2, using Rancher 1.4.3 as backend.

### What did you expect to see?

All my Rancher stacks working normally, as was before the upgrade.

### What did you see instead?

Traefik simply did not recognize some of my Rancher stacks, apparently at random. They appear as if were non existing.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc2
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-08_07:31:37PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Rancher version 1.4.3
```yml
traefik:
  ports:
    - 8000:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
  image: traefik:1.4.0-rc2-alpine
  command:
    - "--web"
    - "--entryPoints=Name:http\ Address::80\ Redirect.EntryPoint:https"
    - "--entryPoints=Name:https\ Address::443\ TLS"
    - "--defaultentrypoints=http,https"
    - "--rancher"
    - "--rancher.domain=${RANCHER_DOMAIN}"
    - "--rancher.endpoint=${RANCHER_ENDPOINT}"
    - "--rancher.accesskey=${RANCHER_ACCESSKEY}"
    - "--rancher.secretkey=${RANCHER_SECRETKEY}"
    - "--rancher.exposedbydefault=false"
    - "--acme"
    - "--acme.email=${ACME_EMAIL}"
    - "--acme.storage=/mnt/acme.json"
    - "--acme.entrypoint=https"
    - "--acme.ondemand=true"
    - "--logLevel=INFO"
  volumes:
    - "traefik_acme:/mnt:nocopy"
  volume_driver: ${VOLUME_DRIVER}

```
