### ISSUE TITLE
Allow configuration of auth.headerField via labels

### ISSUE THREAD

**Issue by rbayliss** [containous/traefik#2116]
This is a feature request.  In configuring authentication, I can pass the authenticated user to the frontend via an HTTP header using configuration like this:

```toml
# traefik.toml
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.http.auth.basic]
    users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"]
  [entryPoints.http.auth]
    headerField = "X-Webauth-User"
```
This works great when I specify the basic auth users in the entrypoint, but fails when I remove the `[entryPoints.http.auth.basic]` block in order to move that configuration back into a label specified in docker-compose.yml.  I'd like to be able to set a custom headerField for each application using a docker label such as:

```yml
  # docker-compose.yml
  myservice:
    image: myimage
    labels:
      traefik.frontend.auth.headerField: "X-Webauth-User"
      traefik.frontend.auth.basic: "test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
```

### Output of `traefik version`: 

```
Version:      v1.3.8
Codename:     raclette
Go version:   go1.8.3
Built:        2017-09-07_08:46:19PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.http.redirect]
    entryPoint= "https"
  [entryPoints.https]
    address = ":8011"
  [entryPoints.https.auth.basic]
  #[entryPoints.https.tls]

[web]
address=":8080"

[docker]
domain="docker.local"
watch=true
exposedbydefault = false
```
