### ISSUE TITLE
Traefik doesn't detect labels under Swarm Mode 17.06

### ISSUE THREAD

**Issue by gcavalcante8808** [containous/traefik#2128]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?

I'm trying to use traefik in a docker swarm mode cluster. For now, I created a semaphore image with the following definition:

```yml
version: '3'
volumes:
 db:
   driver: convoy
 db-backup:
   external: true


services:
    db:
        image: mysql:5.7
        deploy:
          replicas: 1
          labels:
           - com.ansible.role=mysql
           - traefik.enabled=false
        volumes:
         - db:/var/lib/mysql
        networks:
         - default
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_DATABASE: semaphore
            MYSQL_USER: semaphore
            MYSQL_PASSWORD: semaphore
            MYSQL_DATABASE: semaphore

    app:
        depends_on:
         - db
        image: gcavalcante8808/semaphore:2.4.1
        deploy:
          replicas: 1
          labels:
            - com.ansible.role=semaphore
            - "traefik.backend=http"
            - "traefik.backend=semaphore"
            - "traefik.frontend.rule=Host:semaphore.raleduc.com.br;PathPrefix:/"
            - "traefik.port=3000"
            - "traefik.docker.network=proxy"
            - "traefik.enabled=true"
        networks:
         - default
         - proxy
        environment:
          MYSQL_HOST: semaphore_db
          MYSQL_USER: semaphore
          MYSQL_PASSWORD: semaphore
          MYSQL_DATABASE: semaphore
          SEMAPHORE_USER: semaphore
          SEMAPHORE_PASS: semaphore

networks:
  default:
    driver: overlay
    external: false
  proxy:
    external: true

```

And then, deploy through:

```
docker stack deploy --compose-file docker-compose.file.yml semaphore
```

```yml
version: '3.1'

services:
  proxy:
    image: traefik:1.4
    restart: always
    networks:
     - proxy
    deploy:
      replicas: 1
    command: --web --docker --docker.domain=raleduc.com.br docker.swarmmode=true --loglevel=DEBUG --docker.watch
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  proxy:
    external: True
```

### What did you expect to see?

Traefik under Swarm Mode should detect correct label values and apply them.

### What did you see instead?

Traefik doesn't detect values and create default ones which cannot be used.

On web interface, the correct backend, network and Regexp Rule should be avaiable, but instead just default values are used:

![interface](https://image.ibb.co/idQUM5/semaphore.png)

The network is wrong as well, because "proxy" network uses 10.0.0.0 and "semaphore_default" uses 10.0.2.0 and the traefik is picking an 10.0.2.0 address for container (which doesnt honour traefik.docker.network label as well).

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.4.0-rc2
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-08_07:31:37PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No Toml file, just Docker labels.

### If applicable, please paste the log output in debug mode (`--debug` switch)

`docker service logs proxy_proxy`

```shell
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Creating frontend frontend-Host-semaphore-app-1-954z7me9j7wonlfboq6t4xypx-raleduc-com-br" 
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Wiring frontend frontend-Host-semaphore-app-1-954z7me9j7wonlfboq6t4xypx-raleduc-com-br to entryPoint http" 
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Creating route route-frontend-Host-semaphore-app-1-954z7me9j7wonlfboq6t4xypx-raleduc-com-br Host:semaphore-app.1.954z7me9j7wonlfboq6t4xypx.raleduc.com.br" 
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Creating backend backend-semaphore-app-1-954z7me9j7wonlfboq6t4xypx" 
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Creating load-balancer wrr" 
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Creating server server-semaphore_app-1-954z7me9j7wonlfboq6t4xypx at http://10.0.0.15:3000 with weight 0" 
proxy_proxy.1.4vr0c64lqx2a@raleduc-services    | time="2017-09-16T14:16:07Z" level=debug msg="Creating frontend frontend-Host-semaphore-db-1-5s0zw309xjqtb8tq6282ey0nv-raleduc-com-br" 
```
### Other info

Semaphore service inspect:

```json
[
    {
        "ID": "zgkz7enz11bbiyrk05jxu1wer",
        "Version": {
            "Index": 31188
        },
        "CreatedAt": "2017-09-16T14:25:02.222645122Z",
        "UpdatedAt": "2017-09-16T14:25:02.241252744Z",
        "Spec": {
            "Name": "semaphore_app",
            "Labels": {
                "com.ansible.role": "semaphore",
                "com.docker.stack.image": "gcavalcante8808/semaphore:2.4.1",
                "com.docker.stack.namespace": "semaphore",
                "traefik.backend": "semaphore",
                "traefik.docker.network": "proxy",
                "traefik.enabled": "true",
                "traefik.frontend.rule": "Host:semaphore.raleduc.com.br;PathPrefix:/",
                "traefik.port": "3000"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "gcavalcante8808/semaphore:2.4.1@sha256:c722e6481585b374b335b481a84922ebe9a2c2b02c83fac84547da383f97c8e7",
                    "Labels": {
                        "com.docker.stack.namespace": "semaphore"
                    },
                    "Env": [
                        "ANSIBLE_HOST_KEY_CHECKING=False",
                        "MYSQL_DATABASE=semaphore",
                        "MYSQL_HOST=semaphore_db",
                        "MYSQL_PASSWORD=semaphore",
                        "MYSQL_USER=semaphore",
                        "SEMAPHORE_PASS=bjork8d336",
                        "SEMAPHORE_USER=semaphore",
                        "VIRTUAL_HOST=semaphore.ts3corp.com.br",
                        "VIRTUAL_PORT=3000"
                    ],
                    "Privileges": {
                        "CredentialSpec": null,
                        "SELinuxContext": null
                    },
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "Networks": [
                    {
                        "Target": "ul4qirowky1tx1vhnprmsfplc",
                        "Aliases": [
                            "app"
                        ]
                    },
                    {
                        "Target": "inhea0w1wxb3nm9p199y36rur",
                        "Aliases": [
                            "app"
                        ]
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip"
            },
            "VirtualIPs": [
                {
                    "NetworkID": "ul4qirowky1tx1vhnprmsfplc",
                    "Addr": "10.0.0.8/24"
                },
                {
                    "NetworkID": "inhea0w1wxb3nm9p199y36rur",
                    "Addr": "10.0.2.4/24"
                }
            ]
        }
    }
]
```

**Comment by 0xbaadf00d** [comment]
Strange issue, no problem with our Docker 1.6+ swarm and Traefik 1.4RC1

**Comment by ldez** [comment]
@gcavalcante8808 do you have try with docker version <17.06 ?

**Comment by ldez** [comment]
@gcavalcante8808 could you edit your description to add the Traefik version?

**Comment by thaJeztah** [comment]
Be aware that labels can be specified both for the _service_ and the _container_ (task) backing the service. To set a label for the _container_, specify it through the `labels:` option below the compose service. To specify it for the (swarm) service, specify the label below the `deploy` section.

For example, using this docker-compose.yml:

```yaml
version: "3.2"
services:
  foo:
    image: nginx:alpine
    labels:
      - containerlabel=containerlabel
    deploy:
      labels:
        - servicelabel=servicelabel
```

Deploy the stack:

```bash
docker stack deploy -c docker-compose.yml test
```

Inspect the _service_ : 

```bash
docker service inspect test_foo -f '{{json .Spec}}' | jq .

{
  "Name": "test_foo",
  "Labels": {
    "com.docker.stack.image": "nginx:alpine",
    "com.docker.stack.namespace": "test",
    "servicelabel": "servicelabel"
  },
  "TaskTemplate": {
    "ContainerSpec": {
      "Image": "nginx:alpine@sha256:83f10f82722087e6944e0348b2e64a95baf247135de7c237f4dec7729a386d7f",
      "Labels": {
        "com.docker.stack.namespace": "test",
        "containerlabel": "containerlabel"
      },
      "Privileges": {
        "CredentialSpec": null,
        "SELinuxContext": null
      },
      "StopGracePeriod": 10000000000,
      "DNSConfig": {}
    },
    "Resources": {},
    "RestartPolicy": {
      "Condition": "any",
      "Delay": 5000000000,
      "MaxAttempts": 0
    },
    "Placement": {
      "Platforms": [
        {
          "Architecture": "amd64",
          "OS": "linux"
        }
      ]
    },
    "Networks": [
      {
        "Target": "zgaua9kzp47eygkta5hlkyr8h",
        "Aliases": [
          "foo"
        ]
      }
    ],
    "ForceUpdate": 0,
    "Runtime": "container"
  },
  "Mode": {
    "Replicated": {
      "Replicas": 1
    }
  },
  "UpdateConfig": {
    "Parallelism": 1,
    "FailureAction": "pause",
    "Monitor": 5000000000,
    "MaxFailureRatio": 0,
    "Order": "stop-first"
  },
  "RollbackConfig": {
    "Parallelism": 1,
    "FailureAction": "pause",
    "Monitor": 5000000000,
    "MaxFailureRatio": 0,
    "Order": "stop-first"
  },
  "EndpointSpec": {
    "Mode": "vip"
  }
}
```

And inspect the container backing the service:

```bash
docker inspect -f '{{json .Config.Labels}}' test_foo.1.t18k1cff9driayzmv0tpnc75r | jq . 

{
  "com.docker.stack.namespace": "test",
  "com.docker.swarm.node.id": "drfinwj2um6lv0pbprh0gzzfm",
  "com.docker.swarm.service.id": "m71kaxtsnpzbungqrvdjynm10",
  "com.docker.swarm.service.name": "test_foo",
  "com.docker.swarm.task": "",
  "com.docker.swarm.task.id": "t18k1cff9driayzmv0tpnc75r",
  "com.docker.swarm.task.name": "test_foo.1.t18k1cff9driayzmv0tpnc75r",
  "containerlabel": "containerlabel",
  "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>"
}
```

The container will only have the "container" label
