### ISSUE TITLE
Fallback to another backend

### ISSUE THREAD

**Issue by 0xbaadf00d** [containous/traefik#2136]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Update a docker swarm service (with scale >= 2) via the command `docker service update --image=xxx yyy`

### What did you expect to see?

Traefik have to detect a lost backend or to switch to another available backend if the current don't respond within 5 seconds (by exampel) or if Traefik can't open connection on it.

### What did you see instead?

Nothing, browser (or curl) stay stuck on "waiting response" and Traefik never try to use another available backend, even when the `docker service update` command is finished...

Currently, with a scale = 2: 1 request / 2 stay stuck cause Traefik can't join available backends, traefik continue to trying to connect to a dead backend

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik 1.4RC1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
###############################################################################
## Entry points
# ~~~~~
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/ssl/xxxx.io.crt"
    KeyFile = "/etc/ssl/xxxx.io.key"
  [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/ssl/yyyy.ski.crt"
    KeyFile = "/etc/ssl/yyyy.ski.key"



###############################################################################
## Web administration port
# ~~~~~
[web]

# Web administration port
address = ":8080"

# Set REST API to read-only mode
ReadOnly = true

# Authentication
# https://websistent.com/tools/htdigest-generator-tool/
[web.auth.digest]
users = [
  "xxxx:traefik:xxxxx"
]




###############################################################################
## Docker configuration backend
# ~~~~~
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
domain = "xxxx.io"

# Enable watch docker changes
watch = true

# Expose containers by default in traefik
# If set to false, containers that don't have `traefik.enable=true` will be ignored
exposedbydefault = false

# Use Swarm Mode services as data provider
swarmmode = true




###############################################################################
## Custom health check options
# ~~~~~
[healthcheck]

# Set the default health check interval. Will only be effective if health check
# paths are defined. Given provider-specific support, the value may be
# overridden on a per-backend basis.
# Can be provided in a format supported by [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration) or as raw
# values (digits). If no units are provided, the value is parsed assuming
# seconds
interval = "15s"




###############################################################################
## Access log
# ~~~~~
[accessLog]
```
