### ISSUE TITLE
Kubernetes ingress always uses IP for backend

### ISSUE THREAD

**Issue by japettyjohn** [containous/traefik#2141]
### What did you do?

Tried to setup traefik as an ingress controller for gRPC over http2, tls from client to frontend and from frontend to backend. Self signed certs, go client and server.

### What did you expect to see?

That the auto configuration of traefik via an ingress would use pass the header in the request to the backend, were passing the header not enabled it would fail back on the pod DNS.

### What did you see instead?

It resolves the endpoint IPs referenced in the service and does not any hostname.
See [kubernetes.go](https://github.com/containous/traefik/blob/f9225c54ff07925ba0ccd835a12ffc2c21133a4d/provider/kubernetes/kubernetes.go#L288).

The issue comes in with the certs, without a hostname, it expects an IP address in the cert.
I'm not sure if there is a workaround to this, using an IP in the cert would only work with automation as there is no guessing the IP of the pods on deployment.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc3
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-18_04:38:27PM
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
accessLogsFile = "access.log"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
   
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
[web]
address = ":8080"
```

Running on k8s 1.6 - baremetal installation on centos7.

```yaml
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vc
  name: vc
spec:
  ports:
  - name: grpc
    port: 10000
    protocol: TCP
    # targetPort: 10000
  selector:
    app: vc

# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vc
  namespace: development
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: vc
spec:
  rules:
    - host: vc.myhost.net
      http:
        paths:
        - backend:
            serviceName: vc
            servicePort: grpc
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-09-18T23:59:56Z" level=warning msg="Error forwarding to https://10.244.1.197:10000, err: x509: cannot validate certificate for 10.244.1.197 because it doesn't contain any IP SANs"
```
