### ISSUE TITLE
Feature request : basic auth file specified via docker label

### ISSUE THREAD

**Issue by rgarrigue** [containous/traefik#2144]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

tried to auth against a .htpasswd file via a docker container's label

### What did you expect to see?

logging prompt

### What did you see instead?

no prompt

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.8
Codename:     raclette
Go version:   go1.8.3
Built:        2017-09-07_08:46:19PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

# Optionnal debug
debug = true

[web]
 # Port for the status page
 address = ":8080"

 [web.auth.basic]
   usersFile = "/etc/traefik/htpasswd/traefik.my.domain"

# Static (ansible or other generated) rules can be dropped in this folder
[file]
 directory = "/etc/traefik/rules.d"
 watch = true

# Entrypoints, http and https
[entryPoints]

 # http should be redirected to https
 [entryPoints.http]
   address = ":80"
   [entryPoints.http.redirect]
     entryPoint = "https"

 # https is the default
 [entryPoints.https]
   address = ":443"
   [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
 email = "me@my.domain"
   caServer = "https://acme-staging.api.letsencrypt.org/directory"
 storage = "/etc/traefik/acme-staging.json"
 acmeLogging = true
   entryPoint = "https"
 # onDemand = true # not necessary since frontend / backend are included as labels in docker
 OnHostRule = true

[docker]
 endpoint = "unix:///var/run/docker.sock"
 domain = "my.domain"
 watch = true
 exposedbydefault = false
```

Just routing a jwilder/whoami container via traefik using docker label, via ansible, like this

```
- name: Container
  docker_container:
    name: traefik
    image: traefik
    restart_policy: unless-stopped
    published_ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /srv/traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock
    capabilities:
    - net_bind_service
    labels:
      traefik.enable: "true"
      traefik.backend: traefik
      traefik.frontend.rule: "Host:traefik.{{domain}}"
      traefik.port: "8080"

- name: Whoami container for test
  docker_container:
    name: whoami
    image: jwilder/whoami
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.backend: whoami
      traefik.frontend.rule: "Host:whoami.{{domain}}"
      traefik.port: "8000"
  when: traefik_testing
```
