### ISSUE TITLE
Feature Request: Forward auth per frontend

### ISSUE THREAD

**Issue by jkaberg** [containous/traefik#2162]
### Do you want to request a *feature* or report a *bug*?
**Feature**:

I'd like to see an label option to pass forward auth per frontend instead of per entrypoint, something like ```traefik.frontend.auth.forward=https://auth.domain.tld/verify``` (Docker label example), as you don't always want to authenticate all frontends of an entrypoint.

### What did you do?
Write feature request

### What did you expect to see?
New feature

### What did you see instead?
No feature

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
root@docker01:~# docker exec -it traefik traefik version
Version:      v1.4.0-rc3
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-18_04:38:27PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "info"
InsecureSkipVerify = true

defaultEntryPoints = ["https"]
[entryPoints]
  [entryPoints.https]
  address = ":443"
  compress = true
  ProxyProtocol = true
  [entryPoints.https.tls]
  MinVersion = "VersionTLS12"

[docker]
# https://docs.traefik.io/toml/#docker-backend
endpoint = "unix:///var/run/docker.sock"
domain = "xxx.xxx"
watch = true
exposedbydefault = false

[acme]
email = "xxxx@xxx.xxx"
storage = "/config/acme.json"
entryPoint = "https"
onDemand = true
OnHostRule = true
#caServer = "https://acme-staging.api.letsencrypt.org/directory"

[web]
address = ":8080"
ReadOnly = true
```
Masked obvious settings.
