### ISSUE TITLE
Feature Request: Implement delay on ACME registration (TLS Provider)

### ISSUE THREAD

**Issue by micahhausler** [containous/traefik#2174]
I'm using [Kubernetes external-dns](https://github.com/kubernetes-incubator/external-dns) with Traefik as an Ingress controller + ACME, and I'm running into an issue where the external-DNS has not created the DNS record before traefik tries to create the ACME cert.

I'm wary of using [`onDemand`](https://docs.traefik.io/user-guide/examples/#ondemand-option) as it seems it will create an ACME request for any domain (forged `Host` headers too), and I don't want to open myself to being rate limited.

Even though I could use a DNS based challenge, I still have the possibility of the domain not yet being created. I could set `acme.delayDontCheckDNS = 61`, but I'd prefer to not mess with using my DNS provider.

My current workaround is to:

* Create an Ingress rule
* Wait 60 seconds to allow the DNS to get created
* Delete the ingress rule
* Recreate the ingress rule 

### Do you want to request a *feature* or report a *bug*?

Feature Request

### What did you do?

I created an ingress rule with ACME turned on.

### What did you expect to see?

Traefik retry or wait until my new domain name propagates.

### What did you see instead?

```
time="2017-09-15T20:21:02Z" level=error msg="map[coffee.skuid.com:acme: Error 400 - urn:acme:error:unknownHost - No valid IP addresses found for coffee.skuid.com
Error Detail:
	Validation for coffee.skuid.com:443
	Resolved to:
		
	Used: 

]" 
time="2017-09-15T20:21:02Z" level=error msg="Error getting ACME certificates [coffee.skuid.com] : Cannot obtain certificates map[coffee.skuid.com:acme: Error 400 - urn:acme:error:unknownHost - No valid IP addresses found for coffee.skuid.com
Error Detail:
	Validation for coffee.skuid.com:443
	Resolved to:
		
	Used: 

]+v" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc3
Codename:     roquefort
Go version:   go1.9
Built:        2017-09-18_04:38:27PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes DaemonSet (1 pod per node) + AWS

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.https]
  address = ":443"
  proxyprotocol = true
  [entryPoints.https.tls]
  [entryPoints.http]
  address = ":80"
  proxyprotocol = true
  compress = false
[kubernetes]
labelselector = "kubernetes.io/ingress.class = traefik"
[accessLogs]
format = "json"
[acme]
email = "me@example.com"
storage = "traefik/acme/account"
entryPoint = "https"
onHostRule = true
[web]
address = ":8080"
[web.metrics.prometheus]
  Buckets = [0.1,0.3,1.2,5.0]
[consul]
  prefix = "traefik"
  endpoint = "consul.default.svc.cluster.local"
```

**Comment by dtomcej** [comment]
Could this not be accomplished by a k8s job instead?

**Comment by micahhausler** [comment]
No, I'm not sure I follow. What are you suggesting a k8s job do?

**Comment by allamand** [comment]
If we could traefik to wait some sort of timeout at startup to let networks be available before making any ACME challenge would be very helpful.

**Comment by djeeg** [comment]
Same situation on docker-for-azure when provisioning by stacks

With a config like this:

```
  traefikedge:
    image: traefik:1.4.3-alpine
    command: "--acme.domains='www.domain.com,static.domain.com'"
    ports:
      - "80:80"
      - "443:443"
```

Its takes 10-30s for the exposed ports to be regsitered with the azure load balancer.

Sometimes the ACME challenge works
Sometimes I get 400 errors
Similar to these 
- https://github.com/containous/traefik/issues/1334
- https://github.com/containous/traefik/issues/1833  (yamalight gave me a clue)

My current workaround is to initally provision the service with zero replicas

```
deploy:
      mode: replicated
      replicas: 0
```

Then wait for azure to provision the port mappings
Then scale up the traefikedge container

A configurable delay similar to delayDontCheckDNS would be quite helpful
