### ISSUE TITLE
Override ports in Docker/Swarm mode

### ISSUE THREAD

**Issue by molszanski** [containous/traefik#2179]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

I might be totally missing something. Anyway, this not obvious from the docs. 

Assume I have docker image that exposes a port 8080.
And I want to expose it via traefik at 80

With a **file backend** I would do it like this:
```toml
# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]
# rules
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://10.0.0.5:8080"


[frontends]
  [frontends.frontend1]
  backend = "backend1"
  entrypoints = ["http"]
    [frontends.frontend1.routes.test_1]
    rule = "Host:sub.example.com"

```
But there is no way to express that with **docker/swarm backend**. 

If there is, I will be happy to some docs around it.
