### ISSUE TITLE
Nginx 407 — Proxy Authentication Required

### ISSUE THREAD

**Issue by tienthanh2509** [containous/traefik#2185]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?
Before use Traefik, I use Nginx/HAProxy to reverse proxy another Nginx server work well
After use Traefik reverse proxy another Nginx server

### What did you see instead?
Nginx return a lot of errors "407 - Proxy Authentication Required" while client download file but proxy config without password.
**Screenshot from Traefik Stats**
![screenshot from 2017-09-29 14-55-13](https://user-images.githubusercontent.com/1713444/31006722-198d659c-a528-11e7-8969-2a1ef4b088c8.png)

### Output of `traefik version`:

```
v1.3.8 / raclette
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global Configuration
################################################################
debug = false
checkNewVersion = true
logLevel = "ERROR"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

################################################################
# Web Backend
################################################################
# Enable web configuration backend
[web]

# Web administration port.
address = ":8080"

# Basic Authentication
[web.auth.basic]
usersFile = "/tmp/.htpasswd"

# Enable more detailed statistics.
[web.statistics]
# Number of recent errors logged.
recentErrors = 10

################################################################
# File Backends
################################################################
[file]
filename = "/rules.toml"
watch = true

################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "d13ht01.tk"
watch = true
exposedbydefault = false

################################################################
# ACME (Let's Encrypt) configuration
################################################################
[acme]
onDemand = true
email = "xxxx@gmail.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
```

```toml
# rules.toml

[backends]
  [backends.fit_tdmu]
    [backends.fit_tdmu.LoadBalancer]
    method = "drr"
    [backends.fit_tdmu.servers.server1]
    url = "http://192.168.56.101:80"
    weight = 10

[frontends]
  [frontends.fit_tdmu]
  backend = "fit_tdmu"
  entrypoints = ["http"]
    [frontends.fit_tdmu.headers]
    SSLRedirect = false
    [frontends.fit_tdmu.routes.test_1]
    rule = "Host:test.d13ht01.tk"
```

```
user  www-data;
worker_processes  auto;

# number of file descriptors used for nginx
# the limit for the maximum FDs on the server is usually set by the OS.
# if you don't set FD's then OS settings will be used which is by default 2000
#worker_rlimit_nofile 1000;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
	# determines how much clients will be served per worker
	# max clients = worker_connections * worker_processes
	# max clients is also limited by the number of socket connections available on the system (~64k)
	# ulimit -n
    worker_connections  10000;

	# optmized to serve many clients with each thread, essential for linux
	use epoll;

	# accept as many connections as possible, may flood worker connections if set too low
	multi_accept on;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

	# to boost IO on HDD we can disable access logs
    access_log off;

	# disable http server headers infomation
	server_tokens off;

    # copies data between one FD and other from within the kernel
    # faster then read() + write()
    sendfile on;

    # send headers in one peace, its better then sending them one by one
    tcp_nopush on;

    # don't buffer data sent, good for small data bursts in real time
    tcp_nodelay on;

	# server will close connection after this time
	send_timeout 10;

	# server will close connection after this time
    keepalive_timeout 30;

    # number of requests client can make over keep-alive -- for testing
    keepalive_requests 100000;

	# allow the server to close connection on non responding client, this will free up memory
    reset_timedout_connection on;

	client_body_buffer_size 16K;
	client_header_buffer_size 1k;
	large_client_header_buffers 4 8k;

	client_body_timeout 12;
	client_header_timeout 12;

	# max upload site
	client_max_body_size 64m;

    # size on server_name
    server_names_hash_bucket_size 2048;

	# send file in UTF-8 by default
    charset UTF-8;

    include /etc/nginx/conf.d/*.conf;
}

```
