### ISSUE TITLE
Support watching for custom values of kubernetes.io/ingress.class

### ISSUE THREAD

**Issue by yuvipanda** [containous/traefik#2221]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

I have multiple traefik servers installed on a kubernetes cluster using Ingress objects as backend. Since this is running on Google Cloud, there is also a default Kubernetes Ingress provider. Currently I can specify that an Ingress object should only be processed by traefik with the `kubernetes.io/ingress.class` annotation to `traefik`. This is good - however, not good enough. I'd like to be able to customize the `ingress.class` of each traefik server to be something different, so they can be more specifically targeted.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.3.8
 
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
     # traefik.toml
      logLevel = "INFO"
      defaultEntryPoints = ["http"]
      [entryPoints]
        [entryPoints.http]
        address = ":80"
        compress = true
      [kubernetes]
```
