### ISSUE TITLE
Kubernetes Priority Annotation Doesn't Work

### ISSUE THREAD

**Issue by rawkode** [containous/traefik#2225]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

Configure ingress as such:

```yml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: api-service-ingress-api-gateway
  namespace: myapp
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.priority: 2
spec:
  tls:
  - hosts:
    - api.myapp.com
    secretName: api-tls
  rules:
  - host: api.myapp.com
    http:
      paths:
        - backend:
            serviceName: api-service
            servicePort: 10000
```
### What did you expect to see?

Priority applied to rule

### What did you see instead?

Priority 1 and no anotation listed under `kubectl describe`

### Output of `traefik version`: (_What version of Traefik are you using?_)

`1.4`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes / Helm Chart

**Comment by timoreimann** [comment]
This should work to the best of my knowledge and from taking a quick look at the code.

I'll run some tests locally to verify.

**Comment by timoreimann** [comment]
Wild guess: try specifying the priority as `"2"` instead of `2`?

**Comment by rawkode** [comment]
@timoreimann Let me run it again with the quotes and I'll get back to you

**Comment by rawkode** [comment]
@timoreimann It made no difference I'm afraid

**Comment by timoreimann** [comment]
@rawkode thanks for checking. I'll dig into the matter either tonight or some time tomorrow.

**Comment by timoreimann** [comment]
In the meantime, if you have some interesting DEBUG level logs to share, I'd be curious to see.

**Comment by timoreimann** [comment]
The feature is working as intended for me: I took the examples from [our guide](https://docs.traefik.io/user-guide/kubernetes/) and added the priority annotation to the Traefik UI Ingress object. The priority value was then reflected in the `/api` endpoint.

I did notice though that the priority value **must be quoted**: Missing that, it will be interpreted as a number and ignored by the API server since annotations must always be strings. Trying to `kubectl apply` such an ill-formated will simply drop the illegal annotation; with `kubectl edit` (or `kubectl patch`), you'd actually see this error message:

```
error: ingresses "traefik-web-ui" could not be patched: cannot convert int64 to string
```

Could you double-check again that you specified the annotation correctly? If you are really certain, then I'd need a reproducible set of manifests (Deployment/Pod, Ingress, Service) for further analysis.

**Comment by rawkode** [comment]
Thanks for investigating, @timoreimann. I'll delete the resources and force a refresh and see if this helps.

Thanks again

**Comment by rawkode** [comment]
Still can't get this to work. `kubectl` shows the annotations, but Traefik doesn't do anything with them.

![screenshot from 2017-10-09 18-07-57](https://user-images.githubusercontent.com/145816/31349903-eedeab88-ad1c-11e7-920b-079e79fef12e.png)

![screenshot from 2017-10-09 18-08-21](https://user-images.githubusercontent.com/145816/31349909-f26c16e6-ad1c-11e7-849c-0135aab268bb.png)


Traefik is installed via the Helm chart, version `1.3.8`

```
# Ingress
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: app-user-service-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.priority: "20"
```

```
# Ingress
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: app-api-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.priority: "40"
```
