### ISSUE TITLE
error loading configuration: client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by simon-k8s** [containous/traefik#2240]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What did you do?**

I am trying to configure traefik as a kubernetes daemon set with an etcd backend. I am using the etc operator. I created a configmap and a store job. I can see the configuration data in the etcd cluster. Once i try and start the daemon set the pods crash after a few seconds with the error:

error loading configuration: client: etcd cluster is unavailable or misconfigured

**What did you expect to see?**

I expected to see a traefik daemon set with an 

**What did you see instead?**

A crashed pod and the error message i mentioned

**Traefik Docker image:**

```
I tried 1.38-alpine and 1.4.0-rc4-alpine
```

**What is your environment & configuration (arguments, toml, provider, platform, ...)?**

I am using kubernetes v1.7.0

**ConfigMap**

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |-
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "simon@example.com"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    acmeLogging = true
    [[acme.domains]]
    main = "example.com"
    [etcd]
    endpoint = "etcd-cluster-client:2379"
    watch = true
    [web]
    address = ":8080"
```

**Job**

```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: traefik-config
  namespace: kube-system
spec:
  template:
    metadata:
      name: traefik-config
    spec:
      containers:
      - name: traefik-config
        image:  traefik:1.3.8-alpine
        args:
        - storeconfig
        - --configfile=/etc/traefik/traefik.toml
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
      restartPolicy: Never
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-conf
```

**ServiceAccount - DaemonSet - Service**

```yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image:  traefik:1.3.8-alpine
        name: traefik-ingress-lb
        resources:
            limits:
              cpu: 200m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        securityContext:
          privileged: true
        args:
        - -d
        - --etcd
        - --etcd.endpoint=etcd-cluster-client:2379
        - --web
        - --kubernetes
        - --logLevel=DEBUG
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: NodePort
  ports:
    - name: http 
      port: 80
      protocol: TCP 
    - name: https 
      port: 443
      protocol: TCP 
    - name: admin
      port: 8080
      protocol: TCP
```

**etcd query:**

```
/ # etcdctl --endpoints http://etcd-cluster-client:2379 ls / --recursive
/traefik
/traefik/etcd
/traefik/etcd/filename
/traefik/etcd/password
/traefik/etcd/prefix
/traefik/etcd/trace
/traefik/etcd/username
/traefik/etcd/watch
/traefik/etcd/debugloggeneratedtemplate
/traefik/etcd/endpoint
/traefik/accesslogsfile
/traefik/debug
/traefik/healthcheck
/traefik/healthcheck/interval
/traefik/maxidleconnsperhost
/traefik/providersthrottleduration
/traefik/acme
/traefik/acme/acmelogging
/traefik/acme/delaydontcheckdns
/traefik/acme/entrypoint
/traefik/acme/ondemand
/traefik/acme/onhostrule
/traefik/acme/storage
/traefik/acme/caserver
/traefik/acme/dnsprovider
/traefik/acme/domains
/traefik/acme/domains/0
/traefik/acme/domains/0/main
/traefik/acme/email
/traefik/defaultentrypoints
/traefik/defaultentrypoints/0
/traefik/defaultentrypoints/1
/traefik/idletimeout
/traefik/loglevel
/traefik/traefiklogsfile
/traefik/web
/traefik/web/readonly
/traefik/web/address
/traefik/web/certfile
/traefik/web/debug
/traefik/web/keyfile
/traefik/web/path
/traefik/checknewversion
/traefik/gracetimeout
/traefik/insecureskipverify
/traefik/entrypoints
/traefik/entrypoints/http
/traefik/entrypoints/http/address
/traefik/entrypoints/http/compress
/traefik/entrypoints/http/network
/traefik/entrypoints/http/proxyprotocol
/traefik/entrypoints/http/redirect
/traefik/entrypoints/http/redirect/entrypoint
/traefik/entrypoints/http/redirect/regex
/traefik/entrypoints/http/redirect/replacement
/traefik/entrypoints/https
/traefik/entrypoints/https/network
/traefik/entrypoints/https/proxyprotocol
/traefik/entrypoints/https/tls
/traefik/entrypoints/https/tls/minversion
/traefik/entrypoints/https/address
/traefik/entrypoints/https/compress
```

**If applicable, please paste the log output in debug mode (--debug switch)**

```
Error loading configuration: client: etcd cluster is unavailable or misconfigured
```
