### ISSUE TITLE
Version 1.4 has a heavy network load in Rancher

### ISSUE THREAD

**Issue by rayout** [containous/traefik#2255]
I will show in the screenshots.

Version 1.3.8:
![1 3 8](https://user-images.githubusercontent.com/2248162/31485831-e605f8f4-af3d-11e7-84c9-b8dd541a593d.png)

Version v1.4.0-rc5:
![img-2017-10-12-11-04-03](https://user-images.githubusercontent.com/2248162/31485820-db474210-af3d-11e7-8718-9f5d6251dbb0.png)

My traefik.toml:

```toml
debug = false
logLevel = "INFO"
traefikLogsFile = "/opt/traefik/log/traefik.log"
accessLogsFile = "/opt/traefik/log/access.log"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/traefik.crt"
      keyFile = "/opt/traefik/certs/traefik.key"

[web]
address = ":8000"
ReadOnly = false
[web.statistics]
  RecentErrors = 10

[rancher]
domain = "dev.rz"
Watch = true
RefreshSeconds = 15
ExposedByDefault = false
EnableServiceHealthFilter = false

[rancher.metadata]
IntervalPoll = true
Prefix = "/2016-07-29"

[file]
filename = "/opt/traefik/etc/rules.toml"
watch = true

[acme]
email = "develop@kodeks.ru"
storage = "/opt/traefik/acme/acme.json"
onDemand = true
OnHostRule = true
entryPoint = "https"
caServer = "https://acme-staging.api.letsencrypt.org/directory"

```
