### ISSUE TITLE
RDS Gateway MSRPC reverse proxy

### ISSUE THREAD

**Issue by RoeeJ** [containous/traefik#2257]
### Do you want to request a *feature* or report a *bug*?
A feature

### What did you do?
set up Traefik using file backend and pointed it at my RDS Gateway

### What did you expect to see?
RDS RPC traffic passed through to the gateway

### What did you see instead?
RDS RPC traffic not passed through, making RDP over HTTPS fail

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.0-rc5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [backends.rds]
     [backends.rds.servers.prod]
      url = "https://rds.external.domain"
   [frontends.rds]
    backend = "rds"
    passHostHeader = true
    passTLSCert = true
      [frontends.rds.routes.prod]
      rule = "Host: rds.external.domain"
```
