### ISSUE TITLE
Mixed content https with lets encrypt

### ISSUE THREAD

**Issue by ichasco** [containous/traefik#2267]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

Put a nginx behind traefik

### What did you expect to see?

full https connection

### What did you see instead?

Https connection with mixed-content

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.8
Codename:     raclette
Go version:   go1.8.3
Built:        2017-09-07_08:46:19PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
accessLogsFile = "log/access.log"
logLevel = "ERROR"
checkNewVersion = true
debug = false

defaultEntryPoints = ["http", "https"]

[acme]
  email = "info@example.com"
  storageFile = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  acmeLogging = true
  onDemand = true
  OnHostRule = true
  
 [entryPoints]
  [entryPoints.http]
    address = ":80"
     [entryPoints.http.redirect]
       entryPoint = "https"
   [entryPoints.https]
     address = ":443"
       [entryPoints.https.tls]

[retry]
       
################################################################
# Web configuration backend
################################################################

[web]
  address = ":8080"
  
################################################################
# Docker configuration backend
################################################################

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "example.com"
  watch = true
  swarmmode = false

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```

```
