### ISSUE TITLE
WebSocket with TLS backend doesn't work

### ISSUE THREAD

**Issue by ViBiOh** [containous/traefik#2280]
### What did you do?

I bumped Traefik version from `1.3.3` to `roquefort`(docker images `traefik:roquefort db126a450043`) and I have some issue with **WebSocket over TLS**. Server is not behind any proxy, my backend has a self-signed certificate (but I’ve set the option `--insecureskipverify`) and WebSocket is handled by `gorilla` on backend and by native client on browsers. Everything worked before, but not after bumping.

### What did you expect to see?

WebSocket should work with and without TLS enabled in the backend.

### What did you see instead?

WebSocket doesn't work when backend listen over TLS (golang ListenAndServeTLS), but work as usual when TLS is off.

The backend error I got is the following (nothing changed when bumping version).

```
http2: server: error reading preface from client 172.18.0.5:59866: bogus greeting "GET /echo?encoding=text "
```

I've set [a simple echo WebSocket api](https://github.com/ViBiOh/go-api/blob/master/docker-compose.yml), easy to use with [echo websocket website](https://www.websocket.org/echo.html). Requests on WebSocket `wss://api.vibioh.fr/echo` works but not `wss://api-tls.vibioh.fr/echo`. Requests on HTTP works both (e.g. https://api.vibioh.fr/hello and https://api-tls.vibioh.fr/hello )

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-16_04:52:07PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My traefik configuration is the following one (I only have changed `TLSACME` to `TLS` when bumping version)

```yaml
  traefik:
    image: traefik:roquefort
    command:
    - --loglevel=DEBUG
    - --web
    - --web.metrics
    - --web.metrics.prometheus
    - --web.readonly
    - --web.statistics
    - --insecureskipverify
    - --acme
    - --acme.ondemand
    - --acme.email=xxx@vibioh.fr
    - --acme.storage=/etc/traefik/acme/acme.json
    - --acme.domains=vibioh.fr
    - --acme.entrypoint=https
    - --defaultEntrypoints=https,http
    - --entryPoints=Name:https Address::443 TLS
    - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
    - --docker
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-10-19T11:34:41Z" level=debug msg="Look for provided certificate to validate [api-tls.vibioh.fr]..." 
time="2017-10-19T11:34:41Z" level=debug msg="No provided certificate found for domains [api-tls.vibioh.fr], get ACME certificate." 
time="2017-10-19T11:34:41Z" level=debug msg="Challenge GetCertificate api-tls.vibioh.fr" 
time="2017-10-19T11:34:41Z" level=debug msg="ACME got domain cert api-tls.vibioh.fr" 
time="2017-10-19T11:34:41Z" level=debug msg="Round trip: https://172.18.0.14:1080, code: 200, duration: 1.261138ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:api-tls.vibioh.fr" 
time="2017-10-19T11:34:49Z" level=debug msg="Look for provided certificate to validate [api-tls.vibioh.fr]..." 
time="2017-10-19T11:34:49Z" level=debug msg="No provided certificate found for domains [api-tls.vibioh.fr], get ACME certificate." 
time="2017-10-19T11:34:49Z" level=debug msg="Challenge GetCertificate api-tls.vibioh.fr" 
time="2017-10-19T11:34:49Z" level=debug msg="ACME got domain cert api-tls.vibioh.fr"
```
