### ISSUE TITLE
Docker service labels prevent assigning multiple containers to a backend

### ISSUE THREAD

**Issue by newswangerd** [containous/traefik#2293]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I need to use [Docker service labels](https://docs.traefik.io/configuration/backends/docker/#on-service) so that I can map multiple ports to my container.
I also need to be able to run two identical instances of the same image for high availability reasons.
Using Docker service labels seems to prevent traefik from assigning two containers to a backend.

Consider the following:
```yml
version: '2'

services:
  whoami1:
    image: emilevauge/whoami
    networks:
      - web
    labels:
      - "traefik.backend=whoami"
      - "traefik.whoami.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.whoami.port=80"
      - "traefik.whoami.frontend.entryPoints=http"
      # - "traefik.whoami.frontend.backend=whoami"

  whoami2:
    image: emilevauge/whoami
    networks:
      - web
    labels:
      - "traefik.backend=whoami"
      - "traefik.whoami1.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.whoami1.port=80"
      - "traefik.whoami1.frontend.entryPoints=http"
      # - "traefik.whoami1.frontend.backend=whoami"


networks:
  web:
    external:
      name: traefik_webgateway
```
This creates two separate backends: `backend-whoami-whoami` and `backend-whoami-whoami1`.
When the` whoami.docker.localhost` entry point is accessed it always resolves to` whoami1` rather than dividing the requests between the two containers.

Uncommenting ` - "traefik.whoami1.frontend.backend=whoami"` or using the same service label (`traeffik.whoami.x`) throws `level=error msg="Near line 39 (last key parsed 'backends.backend-whoami.servers'): Key 'backends.backend-whoami.servers.service' has already been defined." 
` 

### What did you expect to see?
I would expect to see Traefik create one backend with two servers in it as it does when docker service labels aren't used as shown here:

```yml
version: '2'

services:
  whoami1:
    image: emilevauge/whoami
    networks:
      - web
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"

  whoami2:
    image: emilevauge/whoami
    networks:
      - web
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"

networks:
  web:
    external:
      name: traefik_webgateway
```

### What did you see instead?
Two backends each with one server in them.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.8
Codename:     raclette
Go version:   go1.8.3
Built:        2017-09-07_08:46:19PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik Docker Compose:
```yml
version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

networks:
  webgateway:
    driver: bridge
```

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.soap]
  address = ":8443"

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
Thanks for reporting 👍 

Could you try with the latest release (1.4.0)?

**Comment by newswangerd** [comment]
This seems to still be an issue in the latest docker image.
```
david@nebula:~/code/traefik$ docker run --rm traefik version
Version:      v1.4.0
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-16_04:52:07PM
OS/Arch:      linux/amd64
```

What part of the codebase would have to look in to find the code for the service labels if I wanted to try and fix this myself?

**Comment by ldez** [comment]
Don't think this be a bug, it's the expected behavior.

**Comment by newswangerd** [comment]
In that case there another way to use the docker service labels and still assign multiple containers to a backend?

Apologies if this isn't a bug. I was torn between posting here or on stack overflow.

**Comment by ldez** [comment]
In your case I think you can use scale (via Docker or Warm mode) instead create 2 identical services.

**Comment by newswangerd** [comment]
Scaling doesn't seem to work either. Plus I don't think that we can use scaling in our current use case, but I need to research this some more/

```
proxy_1  | time="2017-10-20T17:53:44Z" level=debug msg="Provider event received {Status:start ID:4c1773a6c7be634055e863625a53390ef13c764d6587bad6aee0a5cc163d9bc8 From:emilevauge/whoami Type:container Action:start Actor:{ID:4c1773a6c7be634055e863625a53390ef13c764d6587bad6aee0a5cc163d9bc8 Attributes:map[com.docker.compose.oneoff:False com.docker.compose.version:1.8.0 traefik.whoami.frontend.backend:whoami traefik.whoami.frontend.entryPoints:http traefik.whoami.frontend.rule:Host:whoami.docker.localhost com.docker.compose.config-hash:cebd0db471624b0e3e4ba23ad117407b5c2feb3392a1a5e73ef3fe51ef4af576 com.docker.compose.container-number:2 com.docker.compose.project:whoami com.docker.compose.service:whoami1 image:emilevauge/whoami name:whoami_whoami1_2 traefik.backend:whoami traefik.whoami.port:80]} Scope:local Time:1508522024 TimeNano:1508522024876444671}" 
proxy_1  | time="2017-10-20T17:53:44Z" level=error msg="Near line 39 (last key parsed 'backends.backend-whoami.servers'): Key 'backends.backend-whoami.servers.service' has already been defined." 
```

**Comment by ldez** [comment]
```yml
version: '2'

services:
  whoami1:
    image: emilevauge/whoami
    networks:
      - web
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.port=80"

networks:
  web:
    external:
      name: traefik_webgateway
```

**Comment by ldez** [comment]
or 

```yml
version: '2'

services:
  whoami1:
    image: emilevauge/whoami
    networks:
      - web
    labels:
      - "traefik.backend=whoami"
      - "traefik.whoami1.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.whoami1.port=80"
      - "traefik.whoami1.frontend.entryPoints=http"
      - "traefik.whoami1.frontend.backend=whoami"

networks:
  web:
    external:
      name: traefik_webgateway
```
