### ISSUE TITLE
Honor GOMAXPROCS

### ISSUE THREAD

**Issue by amq** [containous/traefik#2316]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

I want to limit the number of CPUs traefik uses to the number of physical cores. A usual way to do this in Go is to set an environment variable `GOMAXPROCS`. I have a 4-core CPU with 8 threads, so I've set `GOMAXPROCS=4` in my `docker-compose.yml`.

### What did you expect to see?

Before performing the change I've noticed that traefik started 20 threads. I was expecting the number to be at least twice as low after the change.

### What did you see instead?

traefik started with 15 threads, but then quickly grew to 19, so I suspected that it doesn't honor `GOMAXPROCS`. After a quick search I found in [cmd/traefik/traefik.go](https://github.com/containous/traefik/blob/7192aa86b5264e014ceabceb6367d8e6ce9a2fe6/cmd/traefik/traefik.go):

```
runtime.GOMAXPROCS(runtime.NumCPU())
```

Since Go 1.5 `GOMAXPROCS` is [already set](https://golang.org/doc/go1.5#runtime) to `NumCPU()`, so it seems unnecessary and hard-coded.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
  traefik:
    image: traefik:1.4
    command: |-
      --logLevel=WARN
      --entrypoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entrypoints='Name:https Address::443 TLS'
      --docker
      --docker.swarmmode
      --docker.exposedbydefault=false
      --acme
      --acme.entrypoint=https
      --acme.email=
      --acme.storage=/acme/acme.json
      --acme.ondemand=false
      --acme.onhostrule=true
    environment:
      - GOMAXPROCS=4
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/traefik.toml
      - acme:/acme
    networks:
      - overlay
      - private
    deploy:
      placement:
        constraints:
          - node.role == manager
```
