### ISSUE TITLE
Traefik on Kubernetes presents just the first static TLS certificate from EndPoint definition

### ISSUE THREAD

**Issue by zxpower** [containous/traefik#2329]
### Do you want to request a *feature* or report a *bug*?

Yes, based on my findings this could be an BUG related to Traefik and Kubernetes.

### What version of Traefik are you using?

v1.4.1

### What did you do?

I've setup bare metal Kubernetes v1.8.1 cluster with 1 master and 3 nodes. Followed [this guide](https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948) with slight modifications to add Traefik with static TLS wildcard certificates as ingress controller. While there was just one certificate and one or multiple hosts from the same domain - everything worked fine. When I configured additional TLS certs and hosts (see configs below) to Kubernetes and defined them in Traefik ingress - only the first static TLS certificate gets presented to user accessing it from outside. The same config works OK on standalone Traefik.

All certs are created separately as secrets (cert + key) as well one secret that has all certs and keys using following command: `kubectl create secret generic ssl-cert1 --from-file=cert1.crt --from-file=cert1.key`

As a side issue - Traefik Dashboard loads, but it's empty.

### What did you expect to see?

When the site corresponding to second static TLS certificate is accessed it should present it correctly and not warn users that they are accessing insecure site.

### What did you see instead?

Only the first static TLS certificate gets presented to user accessing it from outside. Tested with Firefox and `openssl s_client -connect host2.tld:443`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik config stored as K8s ConfigMap:

```toml
# traefik config
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/dir1/cert1.crt"
      KeyFile = "/ssl/dir1/cert1.key"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/dir2/cert2.crt"
      KeyFile = "/ssl/dir2/cert2.key"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/dir3/cert3.crt"
      KeyFile = "/ssl/dir3/cert3.key"

[web]
address = ":8080"

[kubernetes]
namespaces = [ "default", "kube-system" ]
```

Traefik K8s ServiceAccount:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: default
```

Traefik K8s Deployment:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: ssl-dir1
          secret:
            secretName: ssl-cert1
        - name: ssl-dir2
          secret:
            secretName: ssl-cert2
        - name: ssl-dir3
          secret:
            secretName: ssl-cert3
        - name: config
          configMap:
            name: traefik-conf
      containers:
        - image: traefik:latest
          name: traefik-ingress-lb
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/ssl/dir1"
              name: "ssl-dir1"
            - mountPath: "/ssl/dir2"
              name: "ssl-dir2"
            - mountPath: "/ssl/dir3"
              name: "ssl-dir3"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
          args:
            - --configfile=/config/traefik.toml
            - --web
            - --kubernetes
            - --logLevel=DEBUG
```

Traefik K8s Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
  externalIPs:
    - 192.168.0.2
```

Traefik Console K8s Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-console-service
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      name: webui
```

Traefik K8s Ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-reverse-proxy
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - secretName: ssl-cert1
      hosts:
        - host1.tld
        - www.host1.tld
    - secretName: ssl-cert2
      hosts:
        - host2.tld
        - www.host2.tld
    - secretName: ssl-cert3
      hosts:
        - host3.tld
        - www.host3.tld
  rules:
    - host: host1.tld
      http:
        paths:
          - path: /dashboard
            backend:
              serviceName: traefik-console-service
              servicePort: 8080
          - path: /
            backend:
              serviceName: test-nginx-1
              servicePort: 80
    - host: host2.tld
      http:
        paths:
          - path: /
            backend:
              serviceName: test-nginx-2
              servicePort: 80
    - host: host3.tld
      http:
        paths:
          - path: /
            backend:
              serviceName: test-nginx-3
              servicePort: 80
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

In logs - nothing special - no errors. Upon request, could provide them, too.

K8s Services output

```
$ kubectl get svc
NAME                      TYPE           CLUSTER-IP   EXTERNAL-IP       PORT(S)                      AGE
kubernetes                ClusterIP      10.4.0.1     <none>            443/TCP                      12d
test-nginx1               ClusterIP      10.4.0.125   <none>            80/TCP                       1d
test-nginx2               ClusterIP      10.4.0.127   <none>            80/TCP                       1d
test-nginx3               ClusterIP      10.4.0.129   <none>            80/TCP                       1d
traefik-console-service   ClusterIP      10.4.0.148   <none>            8080/TCP                     16h
traefik-ingress-service   LoadBalancer   10.4.0.43    192.168.0.2       80:32264/TCP,443:31098/TCP   16h
```

K8s EndPoints output

```
$ kubectl get ep
NAME                      ENDPOINTS                    AGE
kubernetes                10.1.0.55:443                12d
test-nginx1               10.3.86.7:80                 1d
test-nginx2               10.3.86.9:80                 1d
test-nginx3               10.3.86.11:80                1d
traefik-console-service   10.3.86.8:8080               16h
traefik-ingress-service   10.3.86.8:443,10.3.86.8:80   16h
```

K8s Ingress output:

```
$ kubectl get ing
NAME                       HOSTS                           ADDRESS   PORTS     AGE
traefik-reverse-proxy      host1.tld,host2.tld,host3.tld             80, 443   16h
```
