### ISSUE TITLE
traefik.docker.network should work without the docker-compose prefix

### ISSUE THREAD

**Issue by victornoel** [containous/traefik#2348]
Basically, when using `traefik.docker.network` in a simple `docker-compose` situation, it seems that the value passed to the label must include the full network name.

This means that with the following `docker-compose.yml` file:
```yml
version: '2'

services:

  ### SERVICE: cloud

  cloud_db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - cloud/.env
    networks:
      - cloud
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql

  cloud_app:
    image: nextcloud
    restart: always
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:cloud.domain.net"
      - "traefik.enable=true"
      - "traefik.port=80"
    networks:
      - cloud
      - traefik
    volumes:
      - /srv/nextcloud/app:/var/www/html
  traefik:
    image: traefik
    command: --docker.domain=domain.net --acme.email=mail@domain.net
    restart: always
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/traefik/acme.json:/acme.json
      - ./traefik/traefik.toml:/traefik.toml

### NETWORKS

networks:
  traefik:
  cloud:
```

Traefik won't work because `traefik.docker.network` refers to a network declared in the file and not outside, hence its full name will be prefixed by the `docker-compose` project's name.
Which is unknown at the time of writing the `docker-compose.yml` file :)

This was already highlighted by https://github.com/containous/traefik/issues/970#issuecomment-267795260 in the past.

We should either introduce another label for this situation or find a way for traefik to decide which one to use. I don't think that having traefik take first global then local network (or the inverse) is a good solution, because there will always be cases that won't work if we do that.

**Comment by centerorbit** [comment]
Related: https://github.com/containous/traefik/issues/979

**Comment by carlosedp** [comment]
What I do is define in a file called `.env` in the same dir as `docker-compose.yml` a variable for the project name (that ends as the prefix for all containers/networks/etc). It should only contain characters, no spaces, dashes, etc.

    COMPOSE_PROJECT_NAME=myproject

Then, in your application label, you use the variable name appended with the created network separated by "_":

     - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_mynetwork"

**Comment by victornoel** [comment]
@carlosedp thanks for the workaround (for other readers: `COMPOSE_PROJECT_NAME` is an environment variable `compose` uses to determine the project name instead of via command line).

**Comment by stephanprobst** [comment]
Its only a workaround if you are using `docker-compose` since `.env` files are unfortunately not supported if you deploy a stack.

**Comment by MetalArend** [comment]
Another possible workaround is to define an alias for the network provided to the traefik service, as documented at https://docs.docker.com/compose/compose-file/#aliases

The definition of the traefik service in the yaml would thus change at the networks key to be:

```
  traefik:
    image: traefik
    command: --docker.domain=domain.net --acme.email=mail@domain.net
    restart: always
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    networks:
      traefik:
        aliases:
          - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/traefik/acme.json:/acme.json
      - ./traefik/traefik.toml:/traefik.toml
```

By doing this, the container will find the traefik network via the alias as long as it is connected to that same network as the traefik service that defines that alias.

**Comment by BSchwetzel** [comment]
I just stumbled over this as well. Some solution for `docker stack` would be much appreciated.

**Comment by defcon8** [comment]
I can't get this workaround to work. I created an .env file:

`TRAEFIK_HOST=www.testhost.com
COMPOSE_PROJECT_NAME=tmrrwmedia`

And using the following docker-compose.yml:
`
version: '3'
services:
  odoo:
    image: odoo:latest
    container_name: odoo
    networks:
      - tmrrwmedia_proxy
    volumes:
      - 'filestore:/var/lib/odoo/filestore'
      - 'extra_addons:/mnt/extra-addons'
      - 'odoo:/var/lib/odoo'
    environment:
        - HOST=database
        - PORT=5432
        - USER=*****
        - PASSWORD=*****
    labels:
        - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxy"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
        - "traefik.port=8069"
  database:
    image: postgres:9.4
    container_name: database
    networks:
      - ${COMPOSE_PROJECT_NAME}_proxy
    volumes:
      - 'data:/var/lib/postgresql/data'
      - 'pgdata:/var/lib/postgresql/data/pgdata'
    environment:
        - POSTGRES_USER=*****
        - POSTGRES_PASSWORD=*****
        - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
   filestore:
   extra_addons:
   odoo:
   data:
   pgdata:
networks:
   proxy:
`
So when i try to create the stack using compose-up i get:

WARNING: Some networks were defined but are not used by any service: proxy
ERROR: Service "odoo" uses an undefined network "tmrrwmedia_proxy"

Please help...

**Comment by carlosedp** [comment]
Actually, in the "networks" section you keep the base name of the network, "proxy" in you case.

You only need to prefix the project name on the "traefik.docker.network=....." line.

Try this:

```yaml
version: '3'

services:
  odoo:
    image: odoo:latest
    container_name: odoo
    networks:
      - proxy
    volumes:
      - 'filestore:/var/lib/odoo/filestore'
      - 'extra_addons:/mnt/extra-addons'
      - 'odoo:/var/lib/odoo'
    environment:
        - HOST=database
        - PORT=5432
        - USER=*****
        - PASSWORD=*****
    labels:
        - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxy"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
        - "traefik.port=8069"
  database:
    image: postgres:9.4
    container_name: database
    networks:
      - ${COMPOSE_PROJECT_NAME}_proxy
    volumes:
      - 'data:/var/lib/postgresql/data'
      - 'pgdata:/var/lib/postgresql/data/pgdata'
    environment:
        - POSTGRES_USER=*****
        - POSTGRES_PASSWORD=*****
        - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
   filestore:
   extra_addons:
   odoo:
   data:
   pgdata:
networks:
   proxy:
```

For reference, this is what I used back then: https://github.com/carlosedp/container-mgmt/blob/master/docker-compose.yml
