### ISSUE TITLE
backend changes are not detected using consul_catalog

### ISSUE THREAD

**Issue by jaychris** [containous/traefik#2361]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
We deployed a new version of several containers that are used in the backends of Traefik, which is using consul_catalog for discovery.  Traefik did not discover the change and update it's backends.  We had to manually stop and re-deploy Traefik to pick up the changes.

### What did you expect to see?
The backends for Traefik frontends should automatically update when new versions are deployed and registered in Consul.

### What did you see instead?
Traefik did not update.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.4.0-rc4
Codename:     roquefort
Go version:   go1.9
Built:        2017-10-02_02:19:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  clientCAFiles = ["certs/platform-ca.crt"]
    [[entryPoints.https.tls.certificates]]
    certFile = "certs/server.crt"
    keyFile = "certs/server.key"

[web]
address = ":8080"

[consulCatalog]
endpoint = "172.17.0.1:8500"
domain = "service.gemini"
exposedByDefault = false
prefix = "traefik"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
