### ISSUE TITLE
forwardedHeaders does not appear to work in 1.4.2

### ISSUE THREAD

**Issue by c-knowles** [containous/traefik#2364]
### What did you do?

I tried to setup a list trusted IPs in front of Traefik which are allowed to forward the `X-Forwarded-*` headers. The setup is a k8s Ingress with an IP whitelist in the Ingress. Adding trusted IPs as per the documentation does not seem to work, only marking it as insecure or whitelisting `0.0.0.0/0` in the Ingress allows traffic in.

### What did you expect to see?

`trustedIPs` inside `entryPoints.http.forwardedHeaders` should allow the IPs in the list to be trusted to send `X-Forwarded-*` HTTP headers.

### What did you see instead?

`trustedIPs` inside `entryPoints.http.forwardedHeaders` does not seem to have much effect at all.

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.4.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I'm setting this up via the Helm chart in Kubernetes. Relevant part of the config is:

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["10.2.0.0/16"]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["10.2.0.0/16"]
[kubernetes]
```

`10.2.0.0/16` is the IP range of pods within my k8s cluster (kube-proxy based traffic would get routed from this range).

Note, the latest stable Helm chart does not support `forwardedHeaders` yet - I was working on that when I found this problem.

### Additional info.

The reason this appears to be Traefik side is I ran `brndnmtthws/nginx-echo-headers` from docker hub with a very basic k8s Ingress backed by Traefik and I get this back from it when the setup has `ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"` regardless of what is in the Traefik toml config:

```
GET / HTTP/1.1
Host: echo-test.OBFUSCATED
User-Agent: curl/7.54.0
Accept: */*
X-Forwarded-For: MY_IP_OBFUSCATED, 10.2.12.0
X-Forwarded-Host: echo-test.OBFUSCATED
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-master-traefik-2076230234-bxss6
X-Real-Ip: 10.2.12.0
Accept-Encoding: gzip
```

It shows `MY_IP_OBFUSCATED` with the correct external source IP address where I hit it, followed by an IP in the range I'm trying to whitelist - this IP varies depending on the request but always in the `10.2.0.0/16` range.

If I then set `ingress.kubernetes.io/whitelist-source-range: "MY_IP_OBFUSCATED/32"` in the Ingress I start to get HTTP 403 from Traefik.

Side note - I also do not see the 403s in the recent errors UI but I do see them in Traefik metrics. Probably a separate problem.

**Comment by ldez** [comment]
@c-knowles could you try this?

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.http.forwardedHeaders]
      insecure = false
      trustedIPs = ["10.2.0.0/16"]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.forwardedHeaders]
      insecure = false
      trustedIPs = ["10.2.0.0/16"]

[kubernetes]
```
