### ISSUE TITLE
Traefik rewriting HTTP status codes

### ISSUE THREAD

**Issue by adepretis** [containous/traefik#2365]
### Do you want to request a *feature* or report a *bug*?

bug (?)

### What did you do?

Access an URL that results in a HTTP error code 403 (not authorized) in the backend - which is perfectly fine and OK! The underlying Angular application recognises the HTTP error code 403 and reacts accordingly (e.g. displaying a login window).

### What did you expect to see?

The login window and HTTP error code 403 for the corresponding request.

Traefik <- nginx <- python application
403 <- 403 <- 403

### What did you see instead?

A failing Angular application because traefik rewrites the HTTP error code 403 to 200 - which fucks up everything else.

Traefik <- nginx <- python application
200 <- 403 <- 403

### Output of `traefik version`:

```
bash-4.3$ traefik version
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
debug = true
logLevel = "INFO"
traefikLogsFile = "/opt/traefik/log/traefik.log"
accessLogsFile = "/opt/traefik/log/access.log"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/foobar.crt"
      keyFile = "/opt/traefik/certs/foobar.key"

      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/traefik.crt"
      keyFile = "/opt/traefik/certs/traefik.key"

[web]
address = ":8000"
ReadOnly = false
[web.statistics]
RecentErrors = 10


[rancher]
domain = "rancher.internal"
Watch = true
RefreshSeconds = 15
ExposedByDefault = false
EnableServiceHealthFilter = true

[rancher.metadata]
IntervalPoll = false
Prefix = "/2016-07-29"

[file]
filename = "/opt/traefik/etc/rules.toml"
watch = true
```

**Comment by dtomcej** [comment]
Can you please provide us with a snippet of the debug log while you are making these requests?

I am curious as to what gets logged when the backend status code of 403 is returned.

**Comment by dtomcej** [comment]
@ldez is this possibly related to #2351 ?

**Comment by o1ek** [comment]
We have the same issue. 
With traefik:1.4.0 is returning 202 until results from queries are ready, and then 200. With traefik:1.4.1 or traefik:1.4.2 in immediately returns 200 and empty results. 

Here is my config:
```
version: '3.3'

services:
  traefik:
    image: traefik:1.4.0
    command: -c --docker --docker.swarmmode --docker.domain=some.project.com  --docker.watch --web --acme --web.statistics --acme.storage=/etc/traefik/acme/acme.json --acme.email=some.project.com@gmail.com --acme.entryPoint=https --entryPoints='Name:http Address::80 Compress:on' --entryPoints='Name:https Address::443 TLS Compress:on' --defaultentrypoints=http,https --accessLog --acme.domains="some.project.com"
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
    networks:
      - appnet
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

networks:
  appnet:
    external: true

volumes:
  acme:
    driver: local
```
