### ISSUE TITLE
Traefik stopped displaying health data in dashboard

### ISSUE THREAD

**Issue by shadycuz** [containous/traefik#2368]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?
Ran Traefik on Kubernetes as ingress controller

### What did you expect to see?
I expected to see information in /health

### What did you see instead?
![image](https://user-images.githubusercontent.com/17090999/32462149-5fbc52a2-c306-11e7-9d2d-dbdcf50f9c77.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.4.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Kubernetes 1.8.1, deployed with kube-spray. Traefik deployed with helm stable chart.
```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
[web]
address = ":8080"
  [web.auth.basic]
    users = ["xxxxxxxx:xxxxxxxxxxxx",]

[web.metrics.prometheus]
  Buckets = [0.1,0.3,1.2,5.0]
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

This was working when first deployed an only 1 item was being proxied (traefik dashboard) it stopped working when I added more things to be proxied or when I turned on prometheus metrics. Not sure which.
