### ISSUE TITLE
X-REQUEST-ID Header

### ISSUE THREAD

**Issue by ntoljic** [containous/traefik#2377]
### Do you want to request a *feature* or report a *bug*?

Request a feature

### What did you do?

I setup traefik as a basic reverse proxy for a microservice stack and started to work on a centralized logging approach.

### What did you expect to see?

To be able to group individual request between microservices for better traceability I would have expected traefik to be able to generate a unique request ID, preferably as a header of the form `X-REQUEST-ID`. I would have imagined the value to be a UUID v4

### What did you see instead?

I found issue https://github.com/containous/traefik/issues/1333 where the `X-Traefik-Reqid` header is discussed. However, since it is a) undocumented and b) apparently is only a counter that resets when traefik restarts, it does not qualify for my use case.

Even if those two issues where resolved, it would not support the use case where one wants to run a traefik cluster, since the counters of different instance would somehow need to be synchronized. A UUID v4 as the value would solve this issue as well.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.2
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-02_01:47:46PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "XXXXXXXX"
      KeyFile = "XXXXXXXX"
[web]
  [web.metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]

```

Commands passed to container:

`--docker --docker.swarmmode --logLevel=DEBUG --accesslog --insecureskipverify`

The current setup has traefik set up as the reverse proxy for all our microservices, and would thus be the ideal candidate to manage the request ID header.
