### ISSUE TITLE
Let's Encrypt issue with Traefik in Docker Swarm Mode

### ISSUE THREAD

**Issue by NiklasA** [containous/traefik#2395]
Hi,

I tried to use Traefik / Let's Encrypt with Docker in swarm mode (deploying stacks). My issue is that I won't be able to access my website,  because Let's Encrypt throw errors, while validating provided certificates (see Logs). Any idea / suggestion, what I did wrong? 

### My Workbench:
- Docker: 17.09.0-ce
- Docker-Compose: 1.17.1
- Traefik: v1.4.2-alpine

#### traefik.toml:
```toml
checkNewVersion = true
debug = false
defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

[acme]
caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "info@red-sky.de"
entryPoint = "https"
onDemand = true
onHostRule = true
storageFile = "/etc/traefik/acme.json"
[[acme.domains]]
  main = "stage.red-sky.de"

[docker]
domain = "localhost"
endpoint = "unix:///var/run/docker.sock"
swarmmode = true
watch = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
```

#### docker-compose.yml:
```
version: "3.3"

services:
  traefik-web:
    deploy:
      labels:
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.stickiness.cookieName=S_SESSION"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend=traefik-site-rsk"
        - "traefik.docker.network=traefik"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host: ${ENVIRONMENT}.red-sky.de"
        - "traefik.port=80"
        - "traefix.port=443"
        - "traefik.weight=1"
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 15s
    image: ${DOCKER_IMAGE}:latest
    networks:
      traefik:
        aliases:
          - ${ENVIRONMENT}.red-sky.de
    volumes:
      - "./www-root/:/var/www/html"
```

#### Logs:
```
time="2017-11-11T14:18:08Z" level=debug msg="LoadCertificateForDomains [stage.red-sky.de]..." 
time="2017-11-11T14:18:08Z" level=debug msg="Look for provided certificate to validate [stage.red-sky.de]..." 
time="2017-11-11T14:18:08Z" level=debug msg="No provided certificate found for domains [stage.red-sky.de], get ACME certificate." 
time="2017-11-11T14:18:08Z" level=debug msg="Loading ACME certificates [stage.red-sky.de]..." 
time="2017-11-11T14:18:08Z" level=debug msg="Challenge Present stage.red-sky.de" 
time="2017-11-11T14:18:18Z" level=debug msg="Look for provided certificate to validate [3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid]..." 
time="2017-11-11T14:18:18Z" level=debug msg="No provided certificate found for domains [3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid], get ACME certificate." 
time="2017-11-11T14:18:18Z" level=debug msg="Challenge GetCertificate 3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid" 
time="2017-11-11T14:18:18Z" level=debug msg="ACME got challenge 3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid" 
time="2017-11-11T14:18:18Z" level=debug msg="Look for provided certificate to validate [3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid]..." 
time="2017-11-11T14:18:18Z" level=debug msg="No provided certificate found for domains [3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid], get ACME certificate." 
time="2017-11-11T14:18:18Z" level=debug msg="Challenge GetCertificate 3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid" 
time="2017-11-11T14:18:18Z" level=debug msg="ACME got challenge 3cbb32c097b82ebe2957c8071993a57e.f8c6b4a6f11ba89f1c8c3a2034c94a2d.acme.invalid" 
time="2017-11-11T14:18:24Z" level=debug msg="Challenge CleanUp stage.red-sky.de" 
time="2017-11-11T14:18:24Z" level=error msg="map[stage.red-sky.de:acme: Error 400 - urn:acme:error:connection - Timeout
Error Detail:
	Validation for stage.red-sky.de:443
	Resolved to:
		85.25.243.232
	Used: 85.25.243.232

]"
```

Thank you in advance.

Niklas

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

Every question asked in issues means less features 😉.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, refer to one of the following:

- [Stack Overflow](https://stackoverflow.com/questions/tagged/traefik) using the "traefik" tag
- the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Comment by NiklasA** [comment]
@ldez:

Hi,

I read the documentation carefully and configured it in the described way. Therefore for me it is a bug report?!?

Niklas

**Comment by mikeburgh** [comment]
If it helps anyone else who finds this, I got it working by mapping the acme.json to a /var/tmp mount when running in a swarm..

```yaml
version: '3.1'

services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    command:
      - --acme
      - --acme.email=YOUREMAIL
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.storage=/etc/traefik/acme/acme.json
      - --acme.acmelogging=true
      - --docker
      - --docker.watch
      - --docker.swarmmode
      - --docker.domain=example.org
      - --defaultEntryPoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --logLevel=DEBUG
      - --web
      - --web.statistics
      - --checknewversion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/tmp:/etc/traefik/acme
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  web:
    external: true

```

Then run 

```bash
docker stack deploy --compose-file ./docker-compose.yml core
```

I realize this is not ideal if we end up with multiple replicas of traefik as they will recreate the SSL files, rather than share them. But for my use case that's okay.

**Comment by tannerchung** [comment]
@NiklasA would you mind linking to how you integrated it with Consul?

**Comment by NiklasA** [comment]
Hi @tannerchung,

I only get it working on a test server. I hope the following lines helps you to get it running nd I don't miss anything.

Information that helped me:
- https://docs.traefik.io/configuration/backends/consul/
- https://docs.traefik.io/user-guide/kv-config/#docker-compose-file-for-consul
- http://blog.ruanbekker.com/blog/2017/10/24/managing-traefik-configuration-with-consul-on-docker-swarm/

**traefik.toml:**
```
[acme]
storage = "traefik/acme/account"

[consul]
endpoint = "consul.local:8500"
prefix = "traefik"
watch = true
```

**docker-compose.yml:**
```
  consul:
    command: -server -bootstrap -log-level debug -ui-dir /ui
    deploy:
      labels:
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.stickiness.cookieName=S_SESSION"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend=traefik-consul"
        - "traefik.docker.network=traefik"
        - "traefik.enable=true"
        - 'traefik.traefik-swarm_consul.frontend.auth.basic=<user>:<passwordhash>'
        - "traefik.traefik-swarm_consul.frontend.entryPoints=http,https"
        - "traefik.traefik-swarm_consul.frontend.rule=Host:{HOSTNAME}"
        - "traefik.traefik-swarm_consul.port=8500"
        - "traefik.traefik-swarm_consul.weight=1"
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 15s
    image: progrium/consul
    networks:
      traefik:
        aliases:
          - consul.local
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
```

Niklas
