### ISSUE TITLE
Let's encrypt missing info on error

### ISSUE THREAD

**Issue by deimosfr** [containous/traefik#2396]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

I configured Traefik on Kubernetes with let's encrypt and Cloudflare API. I've 3 FQDN for the moment to declare to Treafik. For all of them it's ok, but for one specific FQDN, it tooks several hours (~ 1 day) to be active.

I tried to find the issue but did not get enough details (even in debug mode) in the logs to figure out what's wrong. Here is an example of what I've got:
```
Error getting ACME certificates [my.failed.fqdn] : Cannot obtain certificates map[my.failed.fqdn:Error presenting token: Cloudflare API Error 
legolog: 2017/11/08 09:18:06 [INFO][my.failed.fqdn] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/BRmkwz5gNUUSvHfAkTjX5qxt_wd5kBiua6hhkmxFtUw
legolog: 2017/11/08 09:18:06 [INFO][my.failed.fqdn] acme: Trying to solve DNS-01
[INFO][my.failed.fqdn] acme: Obtaining bundled SAN certificate
```

### What did you expect to see?

I'm expecting to see more information on the Cloudflare API error. Impossible here to understand what's wrong.

### What did you see instead?

The certificate couldn't be generated. I had to wait several hours but it doesn't looks like to be an API limitation. I just don't have enough information at that point.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.2
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-02_01:47:46PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    checkNewVersion = false
    IdleTimeout = "180s"
    MaxIdleConnsPerHost = 500
    logLevel = "INFO"
    defaultEntryPoints = ["http", "https"]

    [retry]
    attempts = 3

    [web]
    address = ":8081"

    [kubernetes]
    endpoint = "http://localhost:8080"

    [consul]
    endpoint = "consul:8500"
    watch = true
    prefix = "traefik"

    [acme]
    email = "username@myfqdn"
    storage = "traefik/acme/account"
    entryPoint = "https"
    OnHostRule = true
    onDemand = true
    acmeLogging = true
    dnsProvider = "cloudflare"
    delaydontcheckdns = 20
    #caServer = "https://acme-staging.api.letsencrypt.org/directory"

    [[acme.domains]]
      main = "first.domain.com"
    [[acme.domains]]
      main = "second.domain.com"
    [[acme.domains]]
      main = "third.domain.com"

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
```
