### ISSUE TITLE
Supports full regexes when using Kubernetes as a backend

### ISSUE THREAD

**Issue by kedare** [containous/traefik#2408]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

When trying to setup a pseudo wildcard or a regex on a Kubernetes ingress, the Kubernetes validation on the "host" field reject anything complicated (That is supported by Traefik, like regexes)

Example of ingress controller

````yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: templates-ssr-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.backend.circuitbreaker.expression: "NetworkErrorRatio() > 0.5"
spec:
  rules:
  - host: "npreview-{subdomain:[a-z]+}.xxxx.com"
    http:
      paths:
      - backend:
          serviceName: templates-ssr-service
          servicePort: 5050

````
### What did you expect to see?

The correct information passed to Traefik, and the frontend set correctly

### What did you see instead?

When trying to use regexes
````
The Ingress "templates-ssr-ingress" is invalid: spec.rules[0].host: Invalid value: "npreview-{subdomain:[a-z]+}.xxxx.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
````

When trying to use pseudo-wildcards
````
The Ingress "templates-ssr-ingress" is invalid: spec.rules[0].host: Invalid value: "npreview-*.xxx.com": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
````

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.4.2 (as Kubernetes Ingress Controller)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using Kubernetes as backend.
Traefik a Ingress Controller

### If applicable, please paste the log output in debug mode (`--debug` switch)

No log to show as the config doesn't reach Traefik
