### ISSUE TITLE
docker stack with macvlan network: backend server url http://<nil>:80

### ISSUE THREAD

**Issue by ezkrg** [containous/traefik#2412]
### Do you want to request a *feature* or report a *bug*?

~bug~ feature

### What did you do?

docker stack deploy with macvlan network based on local network config template and traefik with backend docker

### What did you expect to see?

Expect backend url http://*stack*_*service*:80 in my case http://traefik_nginx:80 or  replicas ip address from macvlan pool one by one

### What did you see instead?

backend url: http://\<nil\>:80

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.3
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-14_11:14:24AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "GraceTimeOut": 10000000000,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "LogLevel": "ERROR",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Docker": null,
 "File": null,
 "Web": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ConfigFile": "//traefik.toml"
}
```
docker-compose.yml
```yaml
version: '3.4'

services:
  traefik:
    image: traefik:alpine
    command: --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web --accessLog --debug
    networks:
      - public
      - private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - 88:80
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=false"

  nginx:
    image: nginx:alpine
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=vlan"
        - "traefik.frontend.rule=Host:test.traefik"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=wrr"

networks:
  public:
    external:
      name: ingress
  private:
    external:
      name: vlan
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
traefik_traefik.1.fagrrez14ing@docker01-vhg    | time="2017-11-15T14:46:33Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-traefik-nginx":{"servers":{"server-traefik_nginx":{"url":"http://\u003cnil\u003e:80","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-Host-test-traefik-0":{"entryPoints":["http"],"backend":"backend-traefik-nginx","routes":{"route-frontend-Host-test-traefik-0":{"rule":"Host:test.traefik"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}}}}"
traefik_traefik.1.fagrrez14ing@docker01-vhg    | time="2017-11-15T14:46:33Z" level=info msg="Skipping same configuration for provider docker"
traefik_traefik.1.fagrrez14ing@docker01-vhg    | time="2017-11-15T14:46:45Z" level=warning msg="Error forwarding to http://<nil>:80, err: dial tcp: lookup <nil>: no such host"
traefik_traefik.1.fagrrez14ing@docker01-vhg    | 10.255.0.2 - - [15/Nov/2017:14:46:45 +0000] "GET / HTTP/1.1" 502 11 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5" 16 "Host-test-traefik-0" "http://<nil>:80" 0ms
```
