### ISSUE TITLE
Combining frontend matchers is only using the first matcher

### ISSUE THREAD

**Issue by Gabology** [containous/traefik#2417]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I added a service label for a docker service, combining two different frontend matchers as follows:

```
    deploy:
      replicas: 2
      labels:
        traefik.port: 8080
        traefik.frontend.rule: "Host:foo.bar,PathPrefixStrip:/foo/"
```

### What did you expect to see?

Requests going to both `foo.bar/` and `bar/foo` to go to the backend.

### What did you see instead?

Requests with `Host: foo.bar` will go to the backend, requests with `Host: bar` and url `/foo` get a 404.

If I switch places on the matcher rules like so:

```
traefik.frontend.rule: "PathPrefixStrip:/foo/,Host:foo.bar"
```

Then requests going to url `bar/foo` will go the backend while requests with `Host: foo.bar` and no path prefix will get a 404.

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.4.3
