### ISSUE TITLE
Option to store letsencrypt certificates as .pem files, instead of  (or next to) acme.json?

### ISSUE THREAD

**Issue by Gwend4l** [containous/traefik#2418]
### Do you want to request a *feature* or report a *bug*?

feature

### Description

Could we imagine an option to store the letsencrypt certificates as `.pem` files instead of  (or next to)  the `acme.json` file? 

This would be very useful to be able to directly reuse certificates in other non-web applications that rely on TLS (eg. [synapse](https://github.com/matrix-org/synapse) or [prosody](https://prosody.im/)).

At the moment, a workaround could be to use the [`dumpcerts.sh`](https://github.com/containous/traefik/blob/master/contrib/scripts/dumpcerts.sh) script that you provide, and to call it with a *systemd.path* monitoring service  (eg. something like http://www.ocsmag.com/2015/09/02/monitoring-file-access-for-dummies/ ). But having træfik directly producing the right output would be neat.

thanks for the work on træfik!

**Comment by emilevauge** [comment]
Sorry @Gwend4l, we don't plan to implement this feature into Traefik. We recommend to use an external tool like https://certbot.eff.org to retrieve your ACME certificates.

**Comment by Gwend4l** [comment]
Noted, thanks for answering though!

**Comment by flesser** [comment]
This is a simple (and slightly hacky(?)) `docker-compose.yml` to have a small dedicated container monitor `acme.json` and automatically dump the certificates to files every time something changes:

```yml
version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/etc/traefik
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DASHBOARD_HOST}"
      - "traefik.port=8080"
    restart: unless-stopped

  # Watch acme.json and dump certificates to files
  certdumper:
    container_name: traefik_certdumper
    image: alpine:latest
    depends_on:
      - traefik
    volumes:
      - data:/traefik
    command: >
      ash -c " \
        apk --no-cache add inotify-tools jq openssl util-linux bash && \
        wget https://raw.githubusercontent.com/containous/traefik/master/contrib/scripts/dumpcerts.sh && \
        mkdir -p /traefik/ssl/ && \
        while true; do \
          inotifywait -e modify /traefik/acme.json && \
            bash dumpcerts.sh /traefik/acme.json /traefik/ssl/; \
        done"

volumes:
  data:

networks:
  web:
    external: true
```
