### ISSUE TITLE
Error creating server: http2: TLSConfig.CipherSuites index 1 contains an HTTP/2-approved cipher suite

### ISSUE THREAD

**Issue by ichasco** [containous/traefik#2422]
### Do you want to request a *feature* or report a *bug*?

A bug

### What did you do?

Configure TLS and ciphers

### What did you expect to see?
TLS ciphers well configurated

### What did you see instead?
Traefik doesn't show any web

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.4.3

```
Version:      v1.4.3
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-14_11:14:24AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

 [entryPoints]
  [entryPoints.http]
    address = ":80"
     [entryPoints.http.redirect]
       entryPoint = "https"
   [entryPoints.https]
     address = ":443"
       [entryPoints.https.tls]
         minVersion = "VersionTLS12"
         cipherSuites = ["TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA"]



```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
proxy_1  | time="2017-11-18T13:40:28+01:00" level=error msg="Error creating server: http2: TLSConfig.CipherSuites index 1 contains an HTTP/2-approved cipher suite (0xc030), but it comes after unapproved cipher suites. With this configuration, clients that don't support previous, approved cipher suites may be given an unapproved one and reject the connection."
```
