### ISSUE TITLE
traefik.toml file seems not to be read by docker-compose configuration

### ISSUE THREAD

**Issue by rsoika** [containous/traefik#2430]
My goal is to protect the traefik front-end with basic authentication.

I am running Traefik version v1.4.3 built on 2017-11-14_11:14:24AM in a Docker container.

My docker-compose.yml file looks like this:

```
version: "3"

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/git/imixs-docker/cloud/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ~/git/imixs-docker/cloud/traefik/.htpasswd:/etc/traefik/.htpasswd

networks:
  default:
    external:
      name: my_nw
```

The section for the web frontend in my traefik.toml file looks like this:

```
 ....
 # Enable web configuration backend
 [web]
 address = ":8080"
 [web.auth.basic]
 usersFile = "/etc/traefik/.htpasswd"
 ....
```

But my custom traefik.toml file seems not to be mountet/read by traefik - still no authentication necessary for the traefik front-end.

I followed the docu from here: http://docs.traefik.io/configuration/backends/web/#authentication
