### ISSUE TITLE
kubernetes use traefik loadbalance，need sticky session ,How should I configure?

### ISSUE THREAD

**Issue by cycwll** [containous/traefik#2431]
### What did you expect to see?

sticky session

### What did you see instead?
not  sticky session 

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.43

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
[web]
address = ":8880"
[kubernetes]
endpoint = "https://192.168.1.138:6443"
certAuthFilePath = "/etc/kubernetes/pki/ca.crt"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
