### ISSUE TITLE
Traefik HTTPS not fully secure

### ISSUE THREAD

**Issue by Hurobaki** [containous/traefik#2435]
### What did you do?

I try to configure my server with Traefik using Docker containers. I configured Traefik so it works, I got the dashboard page. The thing is I would like to have my own GitLab server. I pulled GitLab docker image and I created a docker-compose file.

Even if GitLab container takes long time to start, it seems to work. I'm able to see the Gitlab backend from Traefik dashboard.

### What did you expect to see?

I would like to have a full secure page on my GitLab page. 

### What did you see instead?

The problem is when I try to go on Gitlab's address, my browser (Firefox and Chrome) tells me that my page is not fully secure. Here's the exact error:

`Connection is not secure. Parts of this page are not secure (such as images)`

I guess I missed something in my Traefik configuration.

### Traefik Version : (_What version of Traefik are you using?_)

I'm running Traefik 1.3.6-alpine. I'm using a docker image.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here's my traefik.toml config

```toml
defaultEntryPoints = ["http", "https"]

# Web section is for the dashboard interface
[web]
address = ":8080"
  [web.auth.basic]
    users = ["admin:$apr1$TF1rGQz9$OdtHJ15PT6LGWObE4tXuK0"]

# entryPoints section configures the addresses that Traefik and the proxied containers can listen on
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect] 
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Acme section is for Let's Encrypt configuration
[acme]
email = "email@email.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[[acme.domains]]
main = "domain.com"
```
This is the docker-compose.yml file : 

```yml
version: '3.3'

networks:
   proxy: 
     external: true
   internal:
     external: false

services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    labels:
        - traefik.backend=gitlab
        - traefik.frontend.rule=Host:git.domain.com
        - traefik.docker.network=proxy
        - traefik.port=80
    networks:
        - internal
        - proxy
```
And the docker run command I used to create the Traefik container : 

```shell
docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $PWD/traefik.toml:/traefik.toml \
  -v $PWD/acme.json:/acme.json \
  -e TZ="Europe/Paris" \
  -p 80:80 \
  -p 443:443 \
  -l traefik.frontend.rule=Host:monitor.domain.com \
  -l traefik.port=8080 \
  --network proxy \
  --name traefik \
  traefik:1.3.6-alpine --docker --logLevel=DEBUG
```

As you can see it's a very basic configuration, I don't get why I can't get a fully secure GitLab page. In acme.json file I see my main domain "domain.com" and my sub-domain "git.domain.com". So it should be secure.

What am I missing ? :/ Please me to point out what I am doing wrong here. Thanks
