### ISSUE TITLE
Configuration help needed

### ISSUE THREAD

**Issue by keras** [containous/traefik#244]
I'm having problems trying to configure traefik. I can't even get the following minimal test setup to work.

Traefik always returns 404. It doesn't seem to forward requests to backends.

traefik.toml
```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"

defaultEntryPoints = ["http"]

[web]
address = ":8000"

[file]
filename = "/rules.toml"
watch = true
```

rules.toml
```toml
[backends]
    [backends.blue]
    [backends.blue.servers.blue-001]
    url = "http://blue-001:80"
    weight = 1


[frontends]
    [frontends.fe1]
    backend = "blue"
    [frontends.fe1.routes.localhost]
    rule = "Host"
    value = "localhost"
```

Run backend:
```ShellSession
$ docker run -it --rm --name blue-001 emilevauge/whoami                                                                
Starting up on 80
```

Run traefik:
```ShellSession
$ docker run -it --rm --name traefik -p 8000:8000 -p 80:80 --link blue-001 -v $PWD/traefik.toml:/traefik.toml -v $PWD/rules.toml:/rules.toml containous/traefik:v1.0.alpha.3af21612b65fc578585a98c30090d1e613f791eb
```

Get page:
```ShellSesion
$ curl -s localhost
404 page not found
```
