### ISSUE TITLE
Traefik support for Trusted SSL Certificates

### ISSUE THREAD

**Issue by adam-kosseck** [containous/traefik#2454]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Attempted to start Traefik with a trusted SSL certificate specified in traefik.toml.
Trusted SSL certificates have slightly different header/footer text compared to regular SSL certificates:

```
-----BEGIN TRUSTED CERTIFICATE-----
-----END TRUSTED CERTIFICATE-----
```
### What did you expect to see?
Traefik start successfully

### What did you see instead?
Traefik failed to start. The following errors were shown in the log:
```
"Error creating TLS config: tls: failed to find "CERTIFICATE" PEM block in certificate input after skipping PEM blocks of the following types: [TRUSTED CERTIFICATE]" 
"Error preparing server: tls: failed to find "CERTIFICATE" PEM block in certificate input after skipping PEM blocks of the following types: [TRUSTED CERTIFICATE]" 
```

***Note:*** If I manually edit the certificate file and remove the word "TRUSTED" from both the header and the footer, then Traefik will start successfully.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.4.3
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-14_11:14:24AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik is running under the 1.4.3 Alpine docker image.
The following is the docker-compose.yml entry for Traefik:

```yaml
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:1.4.3-alpine
    command: --web --docker --docker.domain=${DOMAIN} --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ${CERTS}:/etc/ssl/traefik
    labels:
      - "traefik.domain=${DOMAIN}"
    restart: always
```

```toml
# traefik.toml
################################################################
# Global configuration
################################################################
logLevel = "ERROR"

# Set HTTP Entrypoint that redirects to HTTPS
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/traefik/traefik.cert.pem"
      KeyFile = "/etc/ssl/traefik/traefik.key.pem"

################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
```
