### ISSUE TITLE
Traefik basic auth not work with https

### ISSUE THREAD

**Issue by giwery** [containous/traefik#2458]
### Do you want to request a *feature* or report a *bug*?
*bug*

### What did you do?
 I run service in docker swarm with next labels:
```
- "traefik.docker.network=proxy"
- "traefik.backend=kibana"
- "traefik.frontend.entryPoints=https,http"
- "traefik.frontend.rule=Host:mydomain"
- "traefik.port=5601"
- "traefik.frontend.auth.basic=test:098f6bcd4621d373cade4e832627b4f6"
```
### What did you expect to see?

I want to use basic auth for my application

### What did you see instead?

Basic auth don't work with https protocol:
```
curl -u test:test https://my-domain.com
401 Unauthorized
```
But for http it's ok:
```
curl -u test:test http://my-domain.com
Found
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.3
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-14_11:14:24AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[acme]
email = "my@email.com"
storage = "acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true


[web]
address = ":8080"

[docker]
watch = true
exposedbydefault = false
endpoint = "unix:///var/run/docker.sock"
domain = "my-domain.com"



```
