### ISSUE TITLE
Scaling down with docker compose seems to mess up routing

### ISSUE THREAD

**Issue by Gui13** [containous/traefik#2459]
### What did you do?

I have a docker-compose file for my service:

```yaml
version: "2"

services:
  dokuwiki:
    image: bitnami/dokuwiki:latest
    restart: always
    volumes:
      - /opt/dokuwiki:/bitnami
    networks:
      - web
    expose:
      - "80"
    labels:
      - "traefik.backend=dokuwiki"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=PathPrefixStrip:/wiki"
      - "traefik.enable=true"
      - "traefik.port=80"
networks:
  web:
    external: true
```

I start with one instance (`docker-compose up -d`), traefik sees it, auto configures, and curl sees the wiki on mydomain.com/wiki/
With two instances (`docker-compose scale dokuwiki=2`), traefik handles the routing correctly as well.

Now if I execute `docker-compose scale dokuwiki=1` to scale down, traefik seems to still see my 2nd instance but without any IP. See logs below for details.

Curl now fails and reaches the main server (not the sub-path).

### What did you expect to see?

Traefik retrieves a correct configuration from docker and only sees one instance of my service.

### What did you see instead?

It looks like traefik still sees the second instance of dokuwiki, and tries to map it to `http://:80`.

Curl now fails and reaches the main server (not the sub-path).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik:roquefort version
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
checkNewVersion = true

logLevel = "ERROR"

defaultEntryPoints = ["http","https"]

[accessLog]

[web]
#  address = "127.0.0.1:8080"
  readonly = true
  
  [web.auth.basic]
  users = ["XXX"]
  
  [web.metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "XXX"
watch = true
exposedbydefault = false

[acme]
email = "XXX"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true

[[acme.domains]]
  main = "XXX"
  sans = ["YYY"]


[file]
filename = "/static.toml"
watch=true

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

 I see this in the logs of traefik:

```

traefik    | time="2017-11-23T22:07:03Z" level=debug msg="Provider event received {Status:die ID:54254cf6ec0b09cf05dbe7040d8a18a46578ea60b0e817842f9b949c7cbf8b0a From:bitnami/dokuwiki:latest Type:container Action:die Actor:{ID:54254cf6ec0b09cf05dbe7040d8a18a46578ea60b0e817842f9b949c7cbf8b0a Attributes:map[traefik.port:80 com.docker.compose.container-number:2 name:doku_dokuwiki_2 traefik.enable:true com.docker.compose.config-hash:f1af6c6d166ecd02086e4357fca2d94071b99badcb197a46d83ed08f19cf3ff0 traefik.backend:dokuwiki traefik.frontend.rule:PathPrefixStrip:/wiki maintainer:Bitnami <containers@bitnami.com> com.docker.compose.oneoff:False com.docker.compose.project:doku exitCode:0 traefik.docker.network:web com.docker.compose.service:dokuwiki com.docker.compose.version:1.8.0 image:bitnami/dokuwiki:latest]} Scope:local Time:1511474823 TimeNano:1511474823821285998}" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Validation of load balancer method for backend backend-dokuwiki failed: invalid load-balancing method ''. Using default method wrr." 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-dokuwiki":{"servers":{"server-doku_dokuwiki_1":{"url":"http://172.19.0.4:80","weight":0},"server-doku_dokuwiki_2":{"url":"http://:80","weight":0}},"loadBalancer":{"method":"wrr"}}, [...snip, contains my other docker containers...] "backend":"backend-dokuwiki","routes":{"route-frontend-PathPrefixStrip-wiki":{"rule":"PathPrefixStrip:/wiki"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}}}}" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Last docker config received more than 2s, OK" 

[snip, other services]

traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating frontend frontend-PathPrefixStrip-wiki" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Wiring frontend frontend-PathPrefixStrip-wiki to entryPoint http" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating route route-frontend-PathPrefixStrip-wiki PathPrefixStrip:/wiki" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating backend backend-dokuwiki" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating load-balancer wrr" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating server server-doku_dokuwiki_1 at http://172.19.0.4:80 with weight 0" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating server server-doku_dokuwiki_2 at http://:80 with weight 0" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating retries max attempts 2" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Wiring frontend frontend-PathPrefixStrip-wiki to entryPoint https" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating route route-frontend-PathPrefixStrip-wiki PathPrefixStrip:/wiki" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating backend backend-dokuwiki" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating load-balancer wrr" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating server server-doku_dokuwiki_1 at http://172.19.0.4:80 with weight 0" 
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating server server-doku_dokuwiki_2 at http://:80 with weight 0"
traefik    | time="2017-11-23T22:07:04Z" level=debug msg="Creating retries max attempts 2" 
```

It looks like traefik still sees the second instance of dokuwiki, and tries to map it to `http://:80`.

I have a suspicion that it is the fault of the configuration that docker shows (the JSON still contains the second instance), but I don't know how traefik retrieves that config.
