### ISSUE TITLE
Documentation of CipherSuites, http2 and TLSv1.3

### ISSUE THREAD

**Issue by bmhm** [containous/traefik#2466]
I need to disable those cipherSuites (taken from ssllabs test):
* TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK
* TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   WEAK

### What did you expect to see?
On page: https://docs.traefik.io/configuration/entrypoints/
* A list of CipherSuites or at least how to obtain the names.
* A list of values for minVersion.
* sth about http2
* info about TLSv1.3 (like: experimental, unsupported, how to enable if supported...)

### What did you see instead?
Nothing of the above.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.4.3
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-14_11:14:24AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
            entryPoint = "https"

    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
      minVersion = "VersionTLS11"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
N/A
