### ISSUE TITLE
Health API endpoint not returning stats

### ISSUE THREAD

**Issue by lawrencegripper** [containous/traefik#2489]
### Do you want to request a *feature* or report a *bug*?

A bug.

### What did you do?

1. Start Traefik v1.5rc1
2. Send requests through traefik
3. Check both `/health` endpoint and dashboard

### What did you expect to see?

Stats populated for `TotalRequestCount` etc

### What did you see instead?

No stats populated. The `/metrics` endpoint does appear to have some stats. 

### Output of `traefik version`:

```
15:08 $ ./traefik_darwin-amd64 version
Version:      v1.5.0-rc1
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-11-28_02:11:24PM
OS/Arch:      darwin/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Tested on Windows and Mac

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
# traefikLogsFile = "log/traefik.log"

# Log level
#
# Optional
# Default: "ERROR"

logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
[entryPoints.http]
address = ":8000"
[entryPoints.logs]
address = ":9000"

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Web configuration backend
################################################################
[metrics]

  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]

    # Name of the related entry point
    #
    # Optional
    # Default: "traefik"
    #
    entryPoint = "logs"

# Enable web configuration backend
# API definition
[api]
  entryPoint = "logs"
  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

  # Enable more detailed statistics.
  [api.statistics]

    # Number of recent errors logged.
    #
    # Default: 10
    #
    recentErrors = 10
```
