### ISSUE TITLE
Redirect 302 with respect to PathPrefixStrip

### ISSUE THREAD

**Issue by MrOerni** [containous/traefik#2510]
### Do you want to request a *feature* or report a *bug*?
A bug

### What did you do?

When getting redirected on a route with a matched PathPrefix, the Prefix should be included in the redirect.
As you can see below this bothers me when using prometheus. 

### What did you expect to see?
Visiting Path `/prometheus/` [with PathPrefixStrip `/prometheus`]. 
Which is a redirect to `/graph`
Traefik should redirect to `/prometheus/graph`, because of the PathPrefix

### What did you see instead?
It redirects to just `/graph`.
(Curl returns a 302 with `location: /graph`)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
[entryPoints]
	[entryPoints.http]
	address = ":80"
		[entryPoints.http.redirect]
		entryPoint = "https"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]

[acme]
email = "xxx@xxx.de"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[[acme.domains]]
  main = "xxxxx.de"

# Enable web configuration backend
[web]
address = ":8080"
path = "/traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]
domain = "XXXXX.de"
exposedbydefault = true
watch = true
```
