### ISSUE TITLE
Traefik keeps showing 404 Error for Docker Containers

### ISSUE THREAD

**Issue by c0fe** [containous/traefik#2511]
### Do you want to request a *feature* or report a *bug*?

Bug 

### What did you do?

I have a number of docker containers that are running a number of applications including:
Nextcloud
Wordpress
OSTicket

Which I want to be accessible from a browser for each specific URL.

I used Portainer to set everything up

I used Traefik's docs to set this up.

### What did you expect to see?

I expected to see the various services show up depending on the requested URLs.

### What did you see instead?

404 Page Not Found

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.4.4
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-23_10:53:58AM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

TOML Configuration:
https://hastebin.com/diqigabofe.toml

https://i.stack.imgur.com/bEu5n.png

https://i.stack.imgur.com/E90OR.png

**Comment by traefiker** [comment]
Thanks for your interest in Traefik !

Every question asked in issues means less features 😉.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, refer to one of the following:

- [Stack Overflow](https://stackoverflow.com/questions/tagged/traefik) using the "traefik" tag
- the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Comment by c0fe** [comment]
@traefiker why close the issue? I followed the documentation exactly and error persists. Either there is a bug or the documentation is lacking or incorrect.

I also already asked on there several weeks ago and days ago and no answer.

**Comment by ldez** [comment]
@c0fe try to add `defaultEntryPoints = ["http"]` in your configuration.

duplicate of #2494 #680 #427
See also #2501

**Comment by c0fe** [comment]
@ldez added:

https://hastebin.com/ovagenekaz.cfg

but same result

I also just ran this on a new installation (virtualbox) and same result, 404.

**Comment by c0fe** [comment]
It seems that the automated portion of Traefik Docker configuration isn't working. It appears to be a bug.

**Comment by mmatur** [comment]
@c0fe Do you have some backends registered in your Træfik ?

**Comment by c0fe** [comment]
@mmatur you mean in the container labels?

**Comment by ldez** [comment]
```toml
# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":80"
```
