### ISSUE TITLE
kubernetes + acme open traefik/acme/account: not a directory

### ISSUE THREAD

**Issue by Thermi** [containous/traefik#2521]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

The following `traefik.toml` file is supposed to use the KV store (etcd here) to store the acme related stuff. But it doesn't do that. It instead tries to open this path in the file system, which obviously doesn't work.

```shell
time="2017-12-04T16:41:34Z" level=error msg="Error creating TLS config: open traefik/acme/account: not a directory" 
time="2017-12-04T16:41:34Z" level=fatal msg="Error preparing server: open traefik/acme/account: not a directory" 
```

### What did you expect to see?

That traefik uses the KV store.

### What did you see instead?

That it doesn't use it, breaking lets encrypt support.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
apiVersion: v1
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]

    # get config from kubernetes ingress configs
    [kubernetes]

    # tell traefik where to get the TLS cert for api.rimoto.net
    [entryPoints]
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            CertFile = "certificate"
            KeyFile = "key"
      [entryPoints.http]
        address = ":80"
    [web]
    address = ":8080"
    ReadOnly = true
    
    [acme]
    email = "myemail"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onHostRule = true
    acmeLogging = true

    [[acme.domains]]
   <internal stuff 1>
    [[acme.domains]]
   <internal stuff 2>

kind: ConfigMap
metadata:
  name: traefik-config
```

Logs:

```shell
time="2017-12-04T16:43:23Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml" 
legolog: 2017/12/04 16:44:44 [INFO] acme: Registering account for myemail
time="2017-12-04T16:44:45Z" level=error msg="Error creating TLS config: open traefik/acme/account: not a directory" 
time="2017-12-04T16:44:45Z" level=fatal msg="Error preparing server: open traefik/acme/account: not a directory" 
```
