### ISSUE TITLE
how to use X-Forwarded-Prefix in kubernetes

### ISSUE THREAD

**Issue by colinlabs** [containous/traefik#2537]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
docs show:
>Continuing on the example, the backend should return `/products/shoes/image.png` (and not `/images.png` which Traefik would likely not be able to associate with the same backend).
The `X-Forwarded-Prefix` header (available since Traefik 1.3) can be queried to build such URLs dynamically.

### What did you expect to see?
i want to access traefik dashboard with url `my.cluster.local/traefik` , but traefik return 302 to `/dashboard/`, may be return `my.cluster.local/traefik/dashboard`, how to implemente or use   `X-Forwarded-Prefix` in **kubernetes** backend

may be like #2510

**Comment by colinlabs** [comment]
solved, `ingress` yaml like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  labels:
    app: traefik
    chart: traefik-1.14.2
    heritage: Tiller
    release: traefik
  name: traefik-dashboard
  namespace: kube-system
spec:
  rules:
  - host: infra.cluster.local
    http:
      paths:
      - backend:
          serviceName: traefik-dashboard
          servicePort: 80
        path: /traefik
```

access url must be: http://infra.cluster.local/traefik/dashboard, use http://infra.cluster.local/traefik will be ruturn 302 by dashboard.

close!!
