### ISSUE TITLE
Rancher backend behaviour is inconsistent with Docker backend

### ISSUE THREAD

**Issue by PaulGallon** [containous/traefik#2541]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Added a Rancher environment to a fresh Traefik container.

### What did you expect to see?

I expected the same behaviour as the Docker backend where it will automatically expose containers based on their exposed port if there is only one.

### What did you see instead?

Log messages telling me that traefik.port was not set on the services.

### Output of `traefik version`:

```
Version:      v1.5.0-rc2
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-12-06_03:07:42PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration:

```toml
logLegel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"

[rancher]
domain = "subdomain.example.co.uk"
  [rancher.api]
  endpoint = "https://rancher.example.co.uk/v1"
  accessKey = "EXAMPLEKEY"
  secretKey = "EXAMPLESECRETKEY"
```
Port 80 is exposed on the `web` services within the Rancher stacks that are running

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
DEBU[2017-12-07T17:29:48Z] Filtering service web/stack-name-1 without traefik.port label 
```
The above is repeated for each service within each stack.
