### ISSUE TITLE
404 for any path on service other than '/'

### ISSUE THREAD

**Issue by murbanowicz** [containous/traefik#2551]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?
I did bind Auth service to mydomain.com/auth.

from docker-compose.yml

```
labels:
      traefik.backend: "AuthService"
      traefik.frontend.rule: "Host:mydomain.com;Path:/auth"
      traefik.port: "5000"
      traefik.enable: "true"
    networks:
      - traefik
```

### What did you expect to see?

Any requests under mydomain.com/auth being forwarded to the service

### What did you see instead?

404 returned by Traefik for any path under `/auth` other that pure `mydomain.com/auth`
Only path '/auth' (which is home path for the service) is working.
Any requests with any path e.g. 'mydomain.com/auth/swagger' are not working.
404 is returned by Traefik, not by my app.
My app is tested on localhost so e.g. localhost:5001/auth/swagger will return swagger or POST to localhost:5001/auth/register will return appropriate response instead of 404.

Looks like definitely Traefik not forwarding ALL TRAFIC under /auth to the service, but just exact path mydomain.com/auth

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.4.5 or 1.5-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true

[web]
  [web.auth.basic]
  users = ["admin:$apr1$pvQMoFGp$3RqJag8rMQolFsBsA7aGx."]



################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend.
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "docker.localhost"

# Enable watch docker changes.
#
# Optional
#
watch = true

# Override default configuration template.
# For advanced users :)
#
# Optional
#
# filename = "docker.tmpl"

# Expose containers by default in Traefik.
# If set to false, containers that don't have `traefik.enable=true` will be ignored.
#
# Optional
# Default: true
#
exposedbydefault = false

# Use the IP address from the binded port instead of the inner network one.
# For specific use-case :)
#
# Optional
# Default: false
#
usebindportip = true

swarmmode = false

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
