### ISSUE TITLE
Traefik doesnt auto-update based on Consul Catalog changes - verified on v1.5.0-rc2

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#2552]
*bug*

### What did you do?
I've posted about this before, but due to time limitations were unable to provide enough feedback so the bug got closed. Just for fun I wanted to verify that the issue was gone in the latest traefik release (v1.5.0-rc2) and was surprised to see that it wasn't. 
Simply put, traefik doesn't update when the underlying Consul Catalog changes.

I tested this by adding two servers to the same Consul service. These show up in Traefik as they should. I then ran `consul leave` on one of the servers, before stopping the consul service. At this point the consul web ui showed that the stopped node was gone, while Traefik continued to show both nodes. If I stop the web server (in addition to the stopped consul service) on the "down" node, traffic into Traefik will naturally get about a 50% error rate.

If I restart the Traefik service, then the changes are picked up, and the single backend is reflected correctly.

Also if I re-add the "downed" server (and after verifying that it shows up in Consul) the same happens - changes are not reflected in Traefik until I restart the traefik service.

### What did you expect to see?
Traefik should pick up Consul changes very quickly

### What did you see instead?
Had to restart the Traefik service in order to make it pick up changes.

### Output of `traefik version`: 

```
v1.5.0-rc2
```
(tried multiple in the 1.4.x range aswell.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik host: Ubuntu 16.04
Consul agent on host: tested both 0.7.4 and 1.0.1 with same result

```toml
traefikLogsFile = "/var/log/traefik/traefik.log"
checkNewVersion = false
ProvidersThrottleDuration = "5s"
logLevel = "INFO"

defaultEntryPoints = ["http"]
[entryPoints]
    [entryPoints.http]
    address = ":80"

[web]
address = ":8080"

[consulCatalog]
constraints = ["tag==environment:dev","tag==lb_id:external-api01"]
watch = true
endpoint = "127.0.0.1:8500"
```

The Consul service is registered with the following tags:
```json
{
    "service": {
        "checks": [
            {
                "http": "http://localhost:80/healthz",
                "interval": "3s"
            }
        ],
        "name": "services-external-api-dev-proddev-playapi",
        "port": 80,
        "tags": [
            "environment:dev",
            "traefik.frontend.rule=Host:play-api-aws.dev.domain.com;PathPrefixStrip: /play/1",
            "traefik.frontend.entryPoints=http",
            "traefik.enable=true",
            "traefik.tags=environment:dev,lb_id:external-api01"
        ]
    }
}
```
Traefik running in systemd with the following config:
```
[Unit]
Description=traefik
Requires=network-online.target
After=network-online.target

[Service]
EnvironmentFile=-/etc/sysconfig/traefik
Environment=GOMAXPROCS=2
Restart=on-failure
ExecStart=/usr/local/bin/traefik --configFile=/opt/traefik/config/traefik_config.toml --consulcatalog.domain=domain.com
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
```

When running in debug mode, it simply doesn't show any signs of listening to Consul changes, there's only "request logging" going on.
