### ISSUE TITLE
Storeconfig breaks when executed according to documentation/guides

### ISSUE THREAD

**Issue by Overbryd** [containous/traefik#2561]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I ran storeconfig as documented.

### What did you expect to see?

Traefik configured against etcd.

### What did you see instead?

Errors.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    defaultEntryPoints = ["http", "https"]
    logLevel = "ERROR"

    [web]
    address = ":8080"

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [etcd]
    endpoint = "etcd-cluster-client:2379"

    [acme]
    email = "redacted@redacted.com"
    storage = "traefik/acme/account"
    storageFile = "acme.json"
    entryPoint = "https"
    OnHostRule = true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
2017/12/12 07:38:02 Storing configuration: {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","LogLevel":"ERROR","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":null},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":null,"ClientCAFiles":null},"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":null}},"Cluster":null,"Constraints":[],"ACME":{"Email":"redacted@redacted.com","Domains":null,"Storage":"traefik/acme/account","StorageFile":"acme.json","OnDemand":false,"OnHostRule":true,"CAServer":"","EntryPoint":"https","DNSProvider":"","DelayDontCheckDNS":0,"ACMELogging":false,"TLSConfig":null},"DefaultEntryPoints":["http","https"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Docker":null,"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null,"Debug":false,"CurrentConfigurations":null,"Stats":null,"StatsRecorder":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":{"Watch":true,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"etcd-cluster-client:2379","Prefix":"/traefik","TLS":null,"Username":"","Password":""},"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}
2017/12/12 07:38:02 Error running traefik: 102: Not a file (/traefik/acme) [239]
```
