### ISSUE TITLE
Expose Https Service Error

### ISSUE THREAD

**Issue by ZQiannnn** [containous/traefik#2563]
Kubernetes Version:v1.8.4
Kubernetes Dashboard Version: v1.8.0
traefik Version: v1.4.5

### What did you do?

When I Use traefik ingress to expose a https service (like dashboard),recevied a ssl error:
2017/12/13 02:21:24 http: TLS handshake error from 10.233.102.165:43074: remote error: tls: bad certificate

When I Expose Dashboard With NodePort.SSL is fine.

My Step: 
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ~/ssl/traefik/tls.key -out  ~/ssl/traefik/tls.crt -subj "/CN=traefik/O=traefik"
kubectl create secret tls traefik-cert --key ~/ssl/traefik/tls.key --cert ~/ssl/traefik/tls.crt -n kube-system

 kubectl create configmap traefik-conf --from-file=traefik.toml -n kube-system

kubectl apply -f  traefik-deployment.yaml
```
traefik.toml:
```
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/tls.crt"
      keyFile = "/certs/tls.key"
```
certs is dashboard's cert

**Comment by ZQiannnn** [comment]
```
InsecureSkipVerify = true
passHostHeader = true
```
fix this problem, but the kube dashboard is using traefik's cert, not itself，look like my ingress tls not work:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - dashboard.k8s
    secretName: kubernetes-dashboard-certs
  rules:
  - host: dashboard.k8s
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
```
