### ISSUE TITLE
Redirect generate wrong access logs

### ISSUE THREAD

**Issue by jdel** [containous/traefik#2565]
### Do you want to request a *feature* or report a *bug*?

Reporting a bug

### What did you do?

Run traefik with http redirected to https and examine access logs.

### What did you expect to see?

A single curl on nginx1 generates 1 line in the access log:

```
172.17.0.1 - - [13/Dec/2017:19:49:27 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 34 "Host-nginx1-test-tld-3" "http://172.17.0.3:80" 0ms
```

A single curl on nginx2 generates 1 line in the access log:

```
172.17.0.1 - - [13/Dec/2017:19:50:41 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 42 "Host-nginx2-test-tld-2" "http://172.17.0.4:80" 0ms
```

### What did you see instead?

A single curl on nginx1 generates 2 lines in the access log:

```
172.17.0.1 - - [13/Dec/2017:19:49:27 +0000] "GET / HTTP/1.1" - - - "curl/7.54.0" 33 "Host-nginx1-test-tld-3" - 0ms
172.17.0.1 - - [13/Dec/2017:19:49:27 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 34 "Host-nginx1-test-tld-3" "http://172.17.0.3:80" 0ms
```

Now a curl on nginx2 shows a erroneous output in the first line:

```
172.17.0.1 - - [13/Dec/2017:19:50:41 +0000] "GET / HTTP/1.1" - - - "curl/7.54.0" 41 "Host-nginx1-test-tld-3" - 0ms
172.17.0.1 - - [13/Dec/2017:19:50:41 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 42 "Host-nginx2-test-tld-2" "http://172.17.0.4:80" 0ms
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run --rm traefik:v1.4 version
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
logLevel = "ERROR"
InsecureSkipVerify = true

[accessLog]
filePath = "/var/log/traefik/access.log"

################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
[web.statistics]
recentErrors = 20

################################################################
# Docker configuration backend
################################################################
[docker]
domain = "test.tld"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":8443"
```

Traefik run with:

```
docker rm -fv traefik; docker run --detach \
    --name       traefik \
    --publish    8080:8080 \
    --publish    8880:80 \
    --publish    8443:443 \
    --volume     /Users/jdel/data/traefik/logs/:/var/log/traefik/:rw \
    --volume     /Users/jdel/data/traefik/traefik.toml:/etc/traefik/traefik.toml:ro \
    --volume     /var/run/docker.sock:/var/run/docker.sock:ro \
    --memory     300m \
    traefik:v1.4 --web
```

Now run 3 nginx:

```
docker run -d --name nginx1 nginx:stable-alpine
docker run -d --name nginx2 nginx:stable-alpine
docker run -d --name nginx3 nginx:stable-alpine
```

A single curl on nginx1 generates 2 lines in the access log:

```
172.17.0.1 - - [13/Dec/2017:19:49:27 +0000] "GET / HTTP/1.1" - - - "curl/7.54.0" 33 "Host-nginx1-test-tld-3" - 0ms
172.17.0.1 - - [13/Dec/2017:19:49:27 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 34 "Host-nginx1-test-tld-3" "http://172.17.0.3:80" 0ms
```

Now a curl on nginx2 shows a weird behaviour:

```
172.17.0.1 - - [13/Dec/2017:19:50:41 +0000] "GET / HTTP/1.1" - - - "curl/7.54.0" 41 "Host-nginx1-test-tld-3" - 0ms
172.17.0.1 - - [13/Dec/2017:19:50:41 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 42 "Host-nginx2-test-tld-2" "http://172.17.0.4:80" 0ms
```

The first lime says we're hitting `Host-nginx1-test-tld-3` which is not correct.

Same goes with nginx3:

```
172.17.0.1 - - [13/Dec/2017:19:52:07 +0000] "GET / HTTP/1.1" - - - "curl/7.54.0" 43 "Host-nginx1-test-tld-3" - 0ms
172.17.0.1 - - [13/Dec/2017:19:52:07 +0000] "GET / HTTP/1.1" 200 612 - "curl/7.54.0" 44 "Host-nginx3-test-tld-1" "http://172.17.0.5:80" 0ms
```
