### ISSUE TITLE
Wrong routing for two frontends with same backend

### ISSUE THREAD

**Issue by hpello** [containous/traefik#2569]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I declared two frontends linked to the same backend.
Each frontend has a rule for a specific host.
Each frontend is supposed to add a specific response header.

### What did you expect to see?

I expected the header for frontend 2 to be added to a request made with the host for frontend 2.
```console
$ curl -H 'Host: my.host.2' -i localhost
HTTP/1.1 200 OK
Content-Length: 17
Date: Thu, 14 Dec 2017 15:31:27 GMT
My-Header: 2
Content-Type: text/plain; charset=utf-8

hello from server
```

### What did you see instead?

In the end, the header for frontend 1 was added to the response of a request made to frontend 2.
```console
$ curl -H 'Host: my.host.2' -i localhost
HTTP/1.1 200 OK
Content-Length: 17
Date: Thu, 14 Dec 2017 15:31:27 GMT
My-Header: 1
Content-Type: text/plain; charset=utf-8

hello from server
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`traefik.toml`:
```toml
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[backends]
  [backends.backend]
    [backends.backend.servers.server1]
    url = "http://server"

[frontends]
  [frontends.frontend1]
  entryPoints = ["http"]
  passHostHeader = true
  backend = "backend"
    [frontends.frontend1.routes.match-host]
    rule = "Host:my.host.1"
    [frontends.frontend1.headers.customresponseheaders]
    My-Header = "1"

  [frontends.frontend2]
  entryPoints = ["http"]
  passHostHeader = true
  backend = "backend"
    [frontends.frontend2.routes.match-host]
    rule = "Host:my.host.2"
    [frontends.frontend2.headers.customresponseheaders]
    My-Header = "2"
```

`docker-compose.yml`:
```yml
version: '3'

services:
  traefik:
    image: traefik:roquefort
    command:
      --logLevel=DEBUG
      --accesslog
      --accesslog.filepath=/dev/stderr
    volumes:
      - ./traefik.toml:/traefik.toml:ro
    ports:
      - 127.0.0.1:80:80

  server:
    image: node:alpine
    command: [node, -e, "require('http').createServer((req, res) => res.end('hello from server')).listen(80)"]
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
traefik_1  | time="2017-12-14T15:31:17Z" level=info msg="Using TOML configuration file //traefik.toml"
traefik_1  | time="2017-12-14T15:31:17Z" level=info msg="Traefik version v1.4.5 built on 2017-12-06_10:16:48AM"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":false,"CheckNewVersion":true,"AccessLogsFile":"","AccessLog":{"file":"/dev/stderr","format":"common"},"TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Docker":null,"File":{"Watch":true,"Filename":"//traefik.toml","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Directory":""},"Web":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}"
traefik_1  | time="2017-12-14T15:31:17Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4204287c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik_1  | time="2017-12-14T15:31:17Z" level=info msg="Starting provider *file.Provider {"Watch":true,"Filename":"//traefik.toml","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Directory":""}"
traefik_1  | time="2017-12-14T15:31:17Z" level=info msg="Starting server on :80"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Validation of load balancer method for backend backend failed: invalid load-balancing method ''. Using default method wrr."
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Configuration received from provider file: {"backends":{"backend":{"servers":{"server1":{"url":"http://server","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend1":{"entryPoints":["http"],"backend":"backend","routes":{"match-host":{"rule":"Host:my.host.1"}},"passHostHeader":true,"priority":0,"basicAuth":null,"headers":{"customResponseHeaders":{"My-Header":"1"}}},"frontend2":{"entryPoints":["http"],"backend":"backend","routes":{"match-host":{"rule":"Host:my.host.2"}},"passHostHeader":true,"priority":0,"basicAuth":null,"headers":{"customResponseHeaders":{"My-Header":"2"}}}}}"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Last file config received more than 2s, OK"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating frontend frontend1"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Wiring frontend frontend1 to entryPoint http"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating route match-host Host:my.host.1"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating backend backend"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating load-balancer wrr"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating server server1 at http://server with weight 0"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Adding header middleware for frontend frontend1"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating frontend frontend2"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Wiring frontend frontend2 to entryPoint http"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Creating route match-host Host:my.host.2"
traefik_1  | time="2017-12-14T15:31:17Z" level=debug msg="Reusing backend backend"
traefik_1  | time="2017-12-14T15:31:17Z" level=info msg="Server configuration reloaded on :80"

traefik_1  | time="2017-12-14T15:31:27Z" level=debug msg="Round trip: http://server, code: 200, duration: 9.210963ms"
traefik_1  | 172.19.0.1 - - [14/Dec/2017:15:31:27 +0000] "GET / HTTP/1.1" 200 17 - "curl/7.54.0" 1 "frontend1" "http://server" 9ms
```
