### ISSUE TITLE
Traefik and docker compose

### ISSUE THREAD

**Issue by Spy-Seth** [containous/traefik#260]
I'm trying to use traefik with docker compose and docker machine

I do not see how to configure the socket path to works in this configuration. On my machine (osx), the default path `endpoint = "unix:///var/run/docker.sock"` do not exist.

**Comment by emilevauge** [comment]
Hi @Spy-Seth, I need a bit more details on your config. Could you provide your docker compose file for example ?

**Comment by Spy-Seth** [comment]
Of course, here a simplified version:

```yml
# docker-compose.yml
version: '2'

services:
    reader:
        image: jenserat/selfoss:latest
        ports:
            - "8101:80"
        volumes:
            - selfoss-data:/var/www/html/data
            - ./selfoss/config.ini:/var/www/html/data/config.ini
        expose:
            - "8101"

    proxy:
        image: containous/traefik:latest
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - ./proxy/traefik.toml:/traefik.toml
            - ./proxy/rules.toml:/rules.toml
        links:
            - reader:reader

volumes:
    selfoss-data:
        driver: local
```

My `traefik.toml` and `rules.toml` have IP hard coded for now. I want to use the traefic dynamic configurations.
