### ISSUE TITLE
Forward POST headers to forward authentication servers

### ISSUE THREAD

**Issue by hjbotha** [containous/traefik#2620]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

I have a PHP script on the backend handling authentication. I set up a form on it, where I could enter a username and password and click Log in, and the credentials would be POSTed to the script.

### What did you expect to see?

POST headers should be passed to the forward authentication server. This would allow for secure authentication and the creation of cookies, allowing access not just to the app you're attempting to access, but whatever other subdomains the cookie allows access to, simplifying the authentication flow and enabling users to create more attractive logon pages.

### What did you see instead?

The POST header gets stripped out by Traefik on the way to the forward authentication server. So I have to use basic authentication using the solution from #2504

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc3
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-12-20_02:24:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = [ "http","https" ]

watch = true

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
     address = ":80"
        [entryPoints.http.redirect]
           entryPoint = "https"

        # Traefik logs
        # Enabled by default and log to stdout
        #
        # Optional
        #
        # [traefikLog]

        # Sets the filepath for the traefik log. If not specified, stdout will be used.
        # Intermediate directories are created if necessary.
        #
        # Optional
        # Default: os.Stdout
        #
        # filePath = "log/traefik.log"

        # Format is either "json" or "common".
        #
        # Optional
        # Default: "common"
        #
        # format = "common"

        # Enable access logs
        # By default it will write to stdout and produce logs in the textual
        # Common Log Format (CLF), extended with additional fields.
        #
        # Optional
        #
        # [accessLog]

        # Sets the file path for the access log. If not specified, stdout will be used.
        # Intermediate directories are created if necessary.
        #
        # Optional
        # Default: os.Stdout
        #
        # filePath = "/path/to/log/log.txt"

        # Format is either "json" or "common".
        #
        # Optional
        # Default: "common"
        #
        # format = "common"

        ################################################################
        # Web configuration backend
        ################################################################

        # Enable web configuration backend
        [web]

        # Web administration port
        #
        # Required
        #
        address = ":8080"

        ################################################################
        # Docker configuration backend
        ################################################################

        # Enable Docker configuration backend
        [docker]

        # Docker server endpoint. Can be a tcp or a unix socket endpoint.
        #
        # Required
        # Default: "unix:///var/run/docker.sock"
        #
        # endpoint = "tcp://10.10.10.10:2375"

        # Default domain used.
        # Can be overridden by setting the "traefik.domain" label on a container.
        #
        # Optional
        # Default: ""
        #
        domain = "stripped"

        # Expose containers by default in traefik
        #
        # Optional
        # Default: true
        #
        exposedbydefault = true

        [entryPoints.https]
           address = ":443"
           [entryPoints.https.tls]
              [[entryPoints.https.tls.certificates]]
               certfile = "/volume1/docker/letsencrypt/config/keys/letsencrypt/fullchain.pem"
               keyfile = "/volume1/docker/letsencrypt/config/keys/letsencrypt/privkey.pem"

              [entryPoints.https.auth.forward]
               address = "http://192.168.1.4:82/"

           #[entryPoints.https.auth.basic]
           #users = ["stripped"]


[acme]

# Email address used for registration.
#
# Required
#
email = "stripped"

# File or key used for certificates storage.
#
# Required
#
storage = "conf/acme.json"
# or `storage = "traefik/acme/account"` if using KV store.

# Entrypoint to proxy acme challenge/apply certificates to.
# WARNING, must point to an entrypoint on port 443
#
# Required
#
entryPoint = "https"

# Use a DNS based acme challenge rather than external HTTPS access
#
#
# Optional
#
# dnsProvider = "digitalocean"

# By default, the dnsProvider will verify the TXT DNS challenge record before letting ACME verify.
# If delayDontCheckDNS is greater than zero, avoid this & instead just wait so many seconds.
# Useful if internal networks block external DNS queries.
#
# Optional
#
# delayDontCheckDNS = 0

# If true, display debug log messages from the acme client library.
#
# Optional
#
# acmeLogging = true

# Enable on demand certificate.
#
# Optional
#
# onDemand = true

# Enable certificate generation on frontends Host rules.
#
# Optional
#
# onHostRule = true

# CA server to use.
# - Uncomment the line to run on the staging let's encrypt server.
# - Leave comment to go to prod.
#
# Optional
#
# caServer = "https://acme-staging.api.letsencrypt.org/directory"

# Domains list.
#
# [[acme.domains]]
# main = "local1.com"
# sans = ["test1.local1.com", "test2.local1.com"]
# [[acme.domains]]
# main = "local2.com"
# sans = ["test1.local2.com", "test2.local2.com"]
# [[acme.domains]]
# main = "local3.com"
# [[acme.domains]]
# main = "local4.com"

[file]
directory = "sites"
watch = true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
