### ISSUE TITLE
http/2 over plaintext

### ISSUE THREAD

**Issue by venth** [containous/traefik#2625]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you expect to see?

According to [the documentation http/2 traffic can be run over plaintext](https://tools.ietf.org/html/rfc7540#section-3.1) 
> The string “h2c” identifies the protocol where HTTP/2 is run over cleartext TCP.

I expect to run grpc over plaintext.

### What did you see instead?

Currently SSL is required to run http/2 traffic.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
    checkNewVersion = false
    logLevel = "INFO"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
    [kubernetes]
      labelselector = "traffic-type=internal"
    [accessLogs]
      format = "common"
    [web]
      address = ":8080"
      path="/deployment/traefik"
      ReadOnly = true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
