### ISSUE TITLE
onHostRule ACME generation for Consul catalog does not work for the "traefik.frontend.rule" override tag

### ISSUE THREAD

**Issue by rvaidya** [containous/traefik#2647]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Consul catalog entry:
```json
{
    "service": {
        "name": "application-java",
        "tags": ["application-java", "env-SUBDOMAIN", "traefik.tags=loadbalanced", "traefik.frontend.rule=Host:SUBDOMAIN.domain.com"],
        "address": "",
        "port": 8080,
        "enable_tag_override": false,
        "checks": [{
            "http": "http://localhost:8080/api/health",
            "interval": "10s"
        }]
    }
}
```

`onHostRule = true`
`onDemand = false`

### What did you expect to see?

LetsEncrypt certificate generated for SUBDOMAIN.domain.com

### What did you see instead?

Can see host rule in Traefik UI and can access using browser.
No certificate generated using `onHostRule`.  Certificate does get generated when using `onDemand` but `onDemand` is being deprecated.
Subdomain gets `TRAEFIK DEFAULT CERT`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.5.0-rc3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Consul catalog on Google Cloud

<details>
<summary>traefik.toml</summary>

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.https]
    address = ":443"
    compress = true
        [entryPoints.https.tls]
    [entryPoints.http]
    address = ":80"
    compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"

# LetsEncrypt configuration
[acme]

email = "acmesetup@DOMAIN.com"
storage = "traefik/acme/account"
entryPoint = "https"
onHostRule = true
onDemand = false
# Comment the following line to go to PROD
caServer = "https://acme-staging.api.letsencrypt.org/directory"

[[acme.domains]]
    main = "DOMAIN.com"

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
# [traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "log/traefik.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8080"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
# [docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
# domain = "docker.localhost"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedbydefault = true

################################################################
# Consul KV configuration backend
################################################################

# Enable Consul KV configuration backend.
[consul]

# Consul server endpoint.
#
# Required
# Default: "127.0.0.1:8500"
#
endpoint = "127.0.0.1:8500"

# Enable watch Consul changes.
#
# Optional
# Default: true
#
watch = true

# Prefix used for KV store.
#
# Optional
# Default: traefik
#
prefix = "traefik"

# Override default configuration template.
# For advanced users :)
#
# Optional
#
# filename = "consul.tmpl"

# Use Consul user/pass authentication.
#
# Optional
#
# username = foo
# password = bar

# Enable Consul TLS connection.
#
# Optional
#
#    [consul.tls]
#    ca = "/etc/ssl/ca.crt"
#    cert = "/etc/ssl/consul.crt"
#    key = "/etc/ssl/consul.key"
#    insecureskipverify = true

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend.
[consulCatalog]
constraints = ["tag==loadbalanced"]

# Default domain used.
#
# Optional
#
domain = "DOMAIN.com"

# Consul server endpoint.
#
# Required
# Default: "127.0.0.1:8500"
#
endpoint = "127.0.0.1:8500"

# Expose Consul catalog services by default in Traefik.
#
# Optional
# Default: true
#
exposedByDefault = true

# Prefix for Consul catalog tags.
#
# Optional
# Default: "traefik"
#
prefix = "traefik"

# Default frontEnd Rule for Consul services.
#
# The format is a Go Template with:
# - ".ServiceName", ".Domain" and ".Attributes" available
# - "getTag(name, tags, defaultValue)", "hasTag(name, tags)" and "getAttribute(name, tags, defaultValue)" functions are available
# - "getAttribute(...)" function uses prefixed tag names based on "prefix" value
#
# Optional
# Default: "Host:{{.ServiceName}}.{{.Domain}}"
#
# frontEndRule = "Host:{{getTag \"traefik.subdomain\" .Attributes .ServiceName }}.{{.Domain}}"
```

</details>

### Other notes

See StackOverflow post here: https://stackoverflow.com/questions/48065628/how-do-you-use-letsencrypt-onhostrule-with-the-consul-catalog-backend-for-letsen/48066101#48066101

`onHostRule` does seem to work if I use the frontEndRule config option:

```toml
frontEndRule = "Host:{{getTag \"traefik.subdomain\" .Attributes .ServiceName }}.{{.Domain}}"
```
