### ISSUE TITLE
Access log with Swarm mode always shows the same IP

### ISSUE THREAD

**Issue by jeanblanchard** [containous/traefik#2660]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Traefik is running inside a Docker swarm. Access log is enabled.

### What did you expect to see?

I expect the access log file to show the actual external IPs for all requests.

### What did you see instead?

Instead, the IP of the `ingress-sbox` pseudo-container, from the `ingress` network is shown, so all requests have the same IP.

Any processing of the access log is useless. This could end up in blacklisting the ingress IP, which would be pretty bad...

sample:
```
10.255.0.3 - - [05/Jan/2018:07:01:43 +0000] "POST /login HTTP/1.1" 204 0 - "Java/1.8.0_121" 9692 "Host-app1-com-0" "http://10.0.2.9:9000" 1001ms
10.255.0.3 - - [05/Jan/2018:07:01:43 +0000] "POST /login HTTP/1.1" 204 0 - "Java/1.8.0_121" 9690 "Host-app1-com-0" "http://10.0.2.9:9000" 1341ms
10.255.0.3 - - [05/Jan/2018:07:01:43 +0000] "POST /login HTTP/1.1" 204 0 - "Java/1.8.0_121" 9691 "Host-tapp1-com-0" "http://10.0.2.9:9000" 1133ms
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.6
Codename:     roquefort
Go version:   go1.9.2
Built:        2018-01-02_12:27:08PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`traefik.toml`:
```toml
defaultEntryPoints = ["http", "https"]

[accessLog]
filePath = "/etc/traefik/logs/access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
swarmmode = true
domain = "traefik"
watch = true

[web]
address = ":8080"

[acme]
email = "redacted@redacted.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
acmeLogging = true
OnHostRule = true

```

`traefik-stack.yml`:
```yml
version: "3"

networks:
  app1-proxy:
    external: true
  app2-proxy:
    external: true

services:
  proxy:
    image: traefik:1.4
    networks:
      - app1-proxy
      - app2-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
```

"appA1 and "app2" have their own stack, with the appropriate traefik labels on the web services.
