### ISSUE TITLE
ACME onHostRule creating invalid certificate requests

### ISSUE THREAD

**Issue by andig** [containous/traefik#2664]
I want traefik with acme as reverse proxy. I'm expecting `onHostRule` to configure certificates for domains that have a corresponding rule

```toml
defaultEntryPoints = ["https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[frontends]
  [frontends.vz]
  backend = "vz"
    [frontends.vz.routes.raspi1]
    rule = "Host:mydomain.io"

  [frontends.fritz]
  backend = "fritz"
    [frontends.fritz.routes.fritzbox]
    rule = "Host:fritz.mydomain.io"

[acme]
email = "..."
entryPoint = "https"
onHostRule = true
```

Note there are two `Host` rules. 

### What did you expect to see?

Now when requesting an unconfigured subdomain like `foo` I'm expecting traefik to not hit LetsEncrypt for that domain. I'm afraid that might be exploitable via rate limiting.

### What did you see instead?

Instead, traefik will still try to obtain a certificate which it imho shouldn't:

```shell
DEBU[2018-01-06T11:54:50Z] Look for provided certificate to validate [foo.mydomain.io]...
DEBU[2018-01-06T11:54:50Z] No provided certificate found for domains [foo.mydomain.io], get ACME certificate.
DEBU[2018-01-06T11:54:50Z] Challenge GetCertificate foo.mydomain.io
DEBU[2018-01-06T11:54:50Z] ACME got nothing foo.mydomain.io
DEBU[2018-01-06T11:54:50Z] http: TLS handshake error from 172.17.0.1:51722: EOF
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.4.6 built on 2018-01-02_12:27:08PM
```
