### ISSUE TITLE
Support 301 redirects in frontend regex redirects

### ISSUE THREAD

**Issue by dimrozakis** [containous/traefik#2666]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

I'm using the frontend regex redirects introduced in https://github.com/containous/traefik/pull/2570 . In particular I'm using them via docker labels to remove the www prefix.

### What did you expect to see?

I'd like to configure permanent 301 redirects instead of the temporary 302 redirects that are currently being returned. I'd like to able to configure that using docker labels.

### What did you see instead?

Temporary 302 redirects.

### Output of `traefik version`: 

I'm running traefik inside a docker container using the official image:
```
Version:      v1.5.0-rc4
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2018-01-04_02:28:22PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# Define entrypoints.
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    # Don't pass X-Forwarded-* headers sent from clients.
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["127.0.0.1/32"]
  [entryPoints.https.tls]

# Letsencrypt configuration.
[acme]
email = "admin@example.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
OnHostRule = true

# Enable the web backend.
[web]
address = ":8080"
readOnly = true

# Enable Docker configuration backend.
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
```

I'm running a docker container using the following docker-compose file:
```yaml
version: '2'

networks:
  traefik:
    external: true

services:

  nginx:
    image: nginx
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik
      traefik.port: '80'
      traefik.frontend.rule: Host:example.com,www.example.com
      traefik.frontend.headers.SSLRedirect: 'true'
      traefik.frontend.redirect.regex: ^https://www.example.com/(.*)$$
      traefik.frontend.redirect.replacement: https://example.com/$$1
    networks:
      - traefik
```
