### ISSUE TITLE
storeconfig writes consul configuration for a frontend's entrypoints in a different place than the consul provider reads them from

### ISSUE THREAD

**Issue by wryfi** [containous/traefik#2667]
### Do you want to request a *feature* or report a *bug*?

Report a bug.

### What did you do?

1. I created a working `traefik.toml` (see below).
1. I uploaded it to consul by running `traefik storeconfig`.
1. I restarted traefik.

### What did you expect to see?

1. I expected to see the same entrypoints in the frontends configured by the consul provider, as I saw in the frontends configured by the file provider.
1. I did not expect to see any errors in `traefik.log` related to the entrypoints configured in consul.

Frontends configured from the file provider, with the specified `frontend1` and `frontend1-unlimited` entrypoints:

![file-correct-entrypoints](https://user-images.githubusercontent.com/1550854/34652407-279481bc-f392-11e7-8467-2f351d11b5d5.png)

### What did you see instead?

1. The frontends configured from the consul provider only had the default `http` entrypoints:
![consul-wrong-entrypoints](https://user-images.githubusercontent.com/1550854/34652415-4c5e4d98-f392-11e7-8be0-d61d2db0b9c1.png)
1. `traefik.log` contains messages about loading the entrypoints configuration from consul:
```
time="2018-01-07T09:42:51-08:00" level=debug msg="Cannot get key traefik/frontends/frontend1/entrypoints Key not found in store, setting default empty"
time="2018-01-07T09:42:51-08:00" level=debug msg="Cannot get key traefik/frontends/frontend1-unlimited/entrypoints Key not found in store, setting default empty"
```

### Additional Information

I examined the configuration stored in consul, and found the following (note the last two lines):

```
$ consul kv get -recurse | grep entrypoints
traefik/defaultentrypoints/0:http
traefik/entrypoints/frontend1-unlimited/:
traefik/entrypoints/frontend1-unlimited/address::81
traefik/entrypoints/frontend1-unlimited/compress:false
traefik/entrypoints/frontend1-unlimited/network:
traefik/entrypoints/frontend1/:
traefik/entrypoints/frontend1/address::80
traefik/entrypoints/frontend1/compress:false
traefik/entrypoints/frontend1/network:
traefik/frontends/frontend1-unlimited/entrypoints/0:frontend1-unlimited
traefik/frontends/frontend1/entrypoints/0:frontend1
```

Inferring from the log output, I suspected that traefik was not expecting the numbered entries under 
`traefik/frontends/<frontend>/entrypoints/<N>`.

I then deleted the numbered entries under `traefik/frontends/<frontend>/entrypoints/<N>`, and set `traefik/frontends/<frontend>/entrypoints` to string values:

```
$ consul kv delete traefik/frontends/frontend1/entrypoints/0
Success! Deleted key: traefik/frontends/frontend1/entrypoints/0
$ consul kv delete traefik/frontends/frontend1-unlimited/entrypoints/0
Success! Deleted key: traefik/frontends/frontend1-unlimited/entrypoints/0
$ consul kv put traefik/frontends/frontend1/entrypoints frontend1
Success! Data written to: traefik/frontends/frontend1/entrypoints
$ consul kv put traefik/frontends/frontend1-unlimited/entrypoints frontend1-unlimited
Success! Data written to: traefik/frontends/frontend1-unlimited/entrypoints
```

This resulted in the following updated consul values (note the change in the last two lines):

```
$ consul kv get -recurse | grep entrypoints
traefik/defaultentrypoints/0:http
traefik/entrypoints/frontend1-unlimited/:
traefik/entrypoints/frontend1-unlimited/address::81
traefik/entrypoints/frontend1-unlimited/compress:false
traefik/entrypoints/frontend1-unlimited/network:
traefik/entrypoints/frontend1/:
traefik/entrypoints/frontend1/address::80
traefik/entrypoints/frontend1/compress:false
traefik/entrypoints/frontend1/network:
traefik/frontends/frontend1-unlimited/entrypoints:frontend1-unlimited
traefik/frontends/frontend1/entrypoints:frontend1
```

💡 **After the above changes, traefik assigned the expected entrypoints to my frontends!**

![consul-correct-entrypoints](https://user-images.githubusercontent.com/1550854/34652451-0e4194e2-f393-11e7-9303-dd2400b786a6.png)

🗒 _I also found that I could set entrypoints to a comma-separated string to specify multiple entrypoints._

### Conclusions

1. `storeconfig` writes consul configuration for a frontend's entrypoints in a different place than the consul provider reads them from.
1. This can be worked around by manually setting `traefik/frontends/<frontend>/entrypoints` to a string value using the `consul` CLI.
1. `traefik/frontends/<frontend>/entrypoints` can be a comma-separated list to set multiple entrypoints on a frontend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc4
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2018-01-04_02:28:22PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "DEBUG"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"


[accessLog]
  filePath = "/var/log/traefik/access.log"


[entryPoints]

  [entryPoints.frontend1]
  address = ":80"

  [entryPoints.frontend1-unlimited]
  address = ":81"


[frontends]

  [frontends.frontend1]
  backend = "backend1"
  passHostHeader = true
  entrypoints = ["frontend1"]

  [frontends.frontend1.ratelimit]
  extractorfunc = "client.ip"
    [frontends.frontend1.ratelimit.rateset.rateset1]
    period = "10s"
    average = 100
    burst = 500

  [frontends.frontend1-unlimited]
  backend = "backend1"
  passHostHeader = true
  entrypoints = ["frontend1-unlimited"]


[backends]

  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://192.168.123.45:80"
    weight = 100


[metrics]

  [metrics.prometheus]


[api]


[ping]


[rest]

[consul]

[file]
```
