### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tipruzs** [containous/traefik#2673]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

When using traefik in front of dynamic web applications (e.g. nextcloud, speedtest) i see very high cpu usage up to 100%, when data is transferred (e.g. large downloads or speedtests).

Note: traefik and web apps run both in docker swarm

**Update 1:** disable compression on entrypoint. cpu usage still at 50-60% -  is this expected?

### What did you expect to see?

no cpu spikes (e.g. like general load balancers / reverse proxies)

### What did you see instead?

cpu rises up to 100% cpu load

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
services:
  traefik:
    image: ${IMAGE}:${RELEASE}
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      ACME_DEFAULT_HOST: ${ACME_DEFAULT_HOST}
    command:
      - --configfile=/run/secrets/traefik_admin
      - --loglevel=WARN
      - --checknewversion=false
      - --insecureskipverify=true
      - --defaultentrypoints=http,https
      - "--entrypoints=Name:http Address::80 Compress:true Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS Compress:true"
      - --acme
      - --acme.email=${ACME_EMAIL}
      - --acme.domains=${ACME_DEFAULT_HOST}
      - --acme.onhostrule
      - --acme.entrypoint=https
      - --acme.storage=/data/acme.json
      - --docker
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.swarmmode
      # - --debug
    networks:
     - traefik
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/data
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --web"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 30s
    deploy:
      restart_policy:
        condition: any
        delay: 2s
      update_config:
        monitor: 120s
        failure_action: continue
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=org_traefik"
        - "traefik.port=8080"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=Host:${ACME_DEFAULT_HOST};PathPrefixStrip:/traefik"
    secrets:
      - traefik_admin
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
