### ISSUE TITLE
Make healthcheck backends protocol configurable

### ISSUE THREAD

**Issue by Miouge1** [containous/traefik#2683]
### What did you do?

```toml
[backends]
  [backends.backend1]
    [backends.backend1.healthcheck]
    path = "/health"
    interval = "10s"
    port = 8081
```

### What did you expect to see?

```toml
[backends]
  [backends.backend1]
    [backends.backend1.healthcheck]
    path = "/health"
    interval = "10s"
    port = 8081
    proto = "http" # or "https"
```

### What did you see instead?

So such option available.

### Output of `traefik version`:

```
Version:      v1.4.2
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-11-02_01:47:46PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Application is running over HTTPS but the monitoring port is HTTP only.
