### ISSUE TITLE
Traefik can't resolve Route53 DNS domain SOA record during ACME dns-route53 record validation

### ISSUE THREAD

**Issue by igoratencompass** [containous/traefik#2699]
### Do you want to request a *feature* or report a *bug*?
*bug*

### What did you do?

Attempting DNS-01 LE challenge with Route53.

An IAM role with appropriate ZONE_ID permissions has been created:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EditOfficeZone",
            "Effect": "Allow",
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:GetChange"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/MY_ZONE_ID"
            ]
        },
        {
            "Sid": "ListMainAndOfficeZone",
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones",
                "route53:ListHostedZonesByName",
                "route53:ListResourceRecordSets"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
and passed to traefik via env variables (see below). Manual test with the IAM keys set in the local aws config file:
```console
root@k9s01:~# aws route53 list-resource-record-sets --hosted-zone-id ZONE_ID --out text
RESOURCERECORDSETS	office.encompasshost.com.	172800	NS
RESOURCERECORDS	ns-814.awsdns-37.net.
RESOURCERECORDS	ns-1701.awsdns-20.co.uk.
RESOURCERECORDS	ns-229.awsdns-28.com.
RESOURCERECORDS	ns-1245.awsdns-27.org.
RESOURCERECORDSETS	office.encompasshost.com.	900	SOA
RESOURCERECORDS	ns-814.awsdns-37.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
```

### What did you expect to see?
The dns-route53 TXT record(s) to get created and validated in the given main domain in the configuration.

### What did you see instead?
Saw an error about resolving the domain SOA record, see the log at the bottom. The SOA record for the domain can definitely be retrieved, this is from inside the traefik pod itself:

```console
igorc@igor-laptop:~$ kc get pods -o wide
NAME                                              READY     STATUS    RESTARTS   AGE       IP          NODE
dnstools                                          1/1       Running   0          4m        10.2.43.2   k9s01.virtual.local
traefik-external-ingress-proxy-7f996f4f44-s592j   1/1       Running   0          12m       10.2.50.4   k9s02.virtual.local

igorc@igor-laptop:~$ kc exec -ti traefik-external-ingress-proxy-7f996f4f44-s592j -- bash
bash-4.3# 
bash-4.3# dig +short -t ns office.encompasshost.com
ns-229.awsdns-28.com.
ns-1245.awsdns-27.org.
ns-1701.awsdns-20.co.uk.
ns-814.awsdns-37.net.
bash-4.3# dig +short -t soa @ns-229.awsdns-28.com. office.encompasshost.com
ns-814.awsdns-37.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
```
It is not clear why is traefik looking for SOA of the SAN's (if I'm reading the log error correctly) instead of the main root domain `office.encompasshost.com` only:

```
Could not find the start of authority nodejs-app.office.encompasshost.com
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.5.0-rc4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

The relevant part of the traefik Pod manifest:

```yaml
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-key
              name: aws-le-dns-acc
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-key
              name: aws-le-dns-acc
        - name: AWS_REGION
          value: MY_AWS_REGION_HERE
```
The relevant part of the ACME Configuration:
```toml
    [acme]
    email = "VALID_EMAIL"
    storage = "traefik/acme/account"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    #onDemand = true
    acmeLogging = true
    # For Staging, comment out to go to Prod
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    # DNS-01 challenge
    dnsProvider = "route53"
    [[acme.domains]]
    main = "office.encompasshost.com"
    sans = ["nodejs-app.office.encompasshost.com", "encompass.office.encompasshost.com"]
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
time="2018-01-12T03:50:49Z" level=error msg="Error getting ACME certificate for domain [office.encompasshost.com nodejs-app.office.encompasshost.com encompass.office.encompasshost.com]: Cannot obtain certificates map[office.encompasshost.com:Error presenting token: Failed to determine Route 53 hosted zone ID: Could not find the start of authority nodejs-app.office.encompasshost.com:Error presenting token: Failed to determine Route 53 hosted zone ID: Could not find the start of authority encompass.office.encompasshost.com:Error presenting token: Failed to determine Route 53 hosted zone ID: Could not find the start of authority]+v"
```
