### ISSUE TITLE
Traefik does not recognize network label

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#2700]
### Do you want to request a *feature* or report a *bug*?

A bug

### What did you do?

I am running confluence behind traefik. It looks like if:
- you are using services
- you point your services on the same container
- your container has more than one network attached (traefik network and some other)
traefik then does not correctly recognize the network it should communicate with service through. If your service has just one network it works fine.

```yml
services:
  confluence:
    image: registry.example.com/confluence
    deploy:
      labels:
        - traefik.confluence.port=8090
        - traefik.confluence.docker.network=traefik_net
        - traefik.confluence.frontend.rule=Host:confluence.example.com
        - traefik.synchrony.port=8091
        - traefik.synchrony.docker.network=traefik_net
        - traefik.synchrony.frontend.rule=Host:Host:confluence.example.com;PathPrefix:/synchrony
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - confluence_home:/var/lib/confluence
    networks:
      - traefik_net
      - mysql_net
  mysql:
...
```
```console
$ docker network ls
NETWORK ID          NAME                        DRIVER            SCOPE
gktjuya0fozy        mysql_net                overlay            swarm
fy438bzwy875        traefik_net               overlay             swarm 
```
```console
$ docker version
Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:54 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
### What did you expect to see?

Web page

### What did you see instead?

Gateway timeout, because traefik uses wrong network trying to communicate with container through different interface.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```console
$ traefik version
Version:      v1.4.6
Codename:     roquefort
Go version:   go1.9.2
Built:        2018-01-02_12:27:08PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`cat /traefik.toml`
```toml
#
#
#

################################################################
# Global configuration
################################################################

defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

################################################################
# Entrypoints definition
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    compress = false
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    compress = false

################################################################
# Management interface
################################################################

[web]
address = ":8080"
[web.statistics]
  RecentErrors = 100

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "omitted.com"
watch = true
exposedbydefault = true
swarmmode = true

################################################################
# ACME (Let's Encrypt) configuration
################################################################

[acme]
email = "support@omitted.com"
entryPoint = "https"
onDemand = true
onHostRule = false
dnsProvider = "rfc2136"
storage = "/acme/acme.json"
```
