### ISSUE TITLE
traefik does not forward requests to a “normal” (non-docker) backend

### ISSUE THREAD

**Issue by maxim-ge** [containous/traefik#2704]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you expect to see?

Answer from backend

### What did you see instead?

Page not found

### Output of `traefik version`: (_What version of Traefik are you using?_)

https://github.com/containous/traefik/releases/download/v1.5.0-rc4/traefik_linux-386
```
Version:      v1.4.6
Codename:     roquefort
Go version:   go1.9.2
Built:        2018-01-02_12:27:08PM
OS/Arch:      linux/386
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug=true
logLevel = "DEBUG"

[traefikLog]
filePath = "tl.txt"

[accessLog]
filePath = "al.txt"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":88"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  [frontends.frontend1.routes.backend1]
  rule = "Host:myhost"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8080"
```

- traefik is executed as `sudo  ./traefik --logLevel=DEBUG --debug -c traefik.toml`
- backend is `sudo docker service create -d --name whoami     --constraint=node.role==manager --publish 8080:80 --replicas 1 emilevauge/whoami`

# frondend test

Does not work as expected, by idea should follow requests to backend

```console
$ curl -v -H Host:myhost  127.0.0.1:88
* Rebuilt URL to: 127.0.0.1:88/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 88 (#0)
> GET / HTTP/1.1
> Host:myhost
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sat, 13 Jan 2018 13:47:52 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 127.0.0.1 left intact
```

# backend test

```console
$ curl 127.0.0.1:8080
Hostname: 9134668598ed
IP: 127.0.0.1
IP: 10.255.0.7
IP: 10.255.0.8
IP: 172.18.0.3
GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/7.47.0
Accept: */*
```

# Access log
```
192.168.99.1 - - [13/Jan/2018:13:37:08 +0000] "GET / HTTP/1.1" - - - "curl/7.57.0" 1 - - 0ms
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
time="2018-01-13T13:36:57Z" level=info msg="Using TOML configuration file /home/cluster/traefik.toml"
time="2018-01-13T13:36:57Z" level=info msg="Traefik version v1.4.6 built on 2018-01-02_12:27:08PM"
time="2018-01-13T13:36:57Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"","AccessLog":{"file":"al.txt","format":"common"},"TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":88","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders"{"Insecure":true,"TrustedIPs":null}}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":[],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Docker":null,"File":null,"Web":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}"
time="2018-01-13T13:36:57Z" level=info msg="Preparing server http &{Network: Address::88 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0x1c25ccd0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-01-13T13:36:57Z" level=info msg="Starting server on :88"
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

You must activate the [file backend](https://docs.traefik.io/configuration/backends/file/):

```toml
debug=true
logLevel = "DEBUG"

[traefikLog]
filePath = "tl.txt"

[accessLog]
filePath = "al.txt"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":88"

[file] # <------------------------------------------------------------------------

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  [frontends.frontend1.routes.backend1]
  rule = "Host:myhost"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8080"
```

Every question asked in issues means less features 😉.

Next time please, try to ask your question in the [Traefik community Slack channel](https://traefik.herokuapp.com).
