### ISSUE TITLE
Kubernetes ingress not working when using proxy other than standard one

### ISSUE THREAD

**Issue by dimm0** [containous/traefik#2721]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?
Installed traefik with kube-router (https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/kubeadm.md#kube-router-providing-service-proxy-firewall-and-pod-networking) with proxy enabled, and deleted the proxy coming with kubernetes.

Added an ingress config which used to work.

### What did you expect to see?

Frontend and backend in traefik dashboard

### What did you see instead?

No backends were appearing. Even the tab with cluster name was missing. No errors in logs. Applications didn't work through ingress, although the service was working fine.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Tried 1.3.3, 1.5.0-rc5, 1.4.6

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
InsecureSkipVerify = true
defaultEntryPoints = ["http","https"]
debug = true
logLevel = "DEBUG"
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/k8s_cert.cer"
      KeyFile = "/ssl/k8s.key"
[web]
  CertFile = "/ssl/k8s_cert.cer"
  KeyFile = "/ssl/k8s.key"
  address = ":8081"
  readOnly = true
```

Cluster is installed with kubeadm 1.9.1
