### ISSUE TITLE
Retries should use a different backend instance than the previous attempt

### ISSUE THREAD

**Issue by willgorman** [containous/traefik#2723]
Retries may be more likely to succeed if they are sent to a different backend instance than the one that they failed to connect to.  However, the current behavior seems to allow the retry to use the same instance consecutively. 

[Related Slack thread](https://traefik.slack.com/archives/C0CDT22PJ/p1516294959000522)

### Do you want to request a *feature* or report a *bug*?

An improvement to the retry feature.

### What did you do?

Enabled retries and sent requests at a constant rate to a frontend while causing 1 of 2 backend instances (using the default wrr strategy) to fail on purpose.  The failure mode was such that the backend would not be routable and so Traefik would hit the dial timeout when attempting to connect to it.

### What did you expect to see?

I expected that with one of the two backends down we would see a roughly even mix of requests that succeeded with normal latency (because they were routed to the good backend first) and requests that succeeded with a latency close to the dialTimeout (because they were first routed to the bad backend and then retried to the good backend).  I assumed that a request would always retry to a different backend instance than the one that had just failed.

### What did you see instead?

While I did see requests that succeeded with normal latency and requests that succeeded with a latency close to the dialTimeout, there were also a number of requests that failed with a latency ~ 2x the dialTimeout.  I think this indicates that some of the requests were:

* getting routed first to the bad backend instance
* waiting for the dial timeout
* getting retried but being sent to the same bad backend instance
* waiting for the dial timeout again
* being returned as an error by Traefik since it was configured to only make as many tries as the number of instances so it would give up after 2 attempts.

This is a graph of the behavior seen with a dial timeout of 3 seconds.

![](https://www.evernote.com/l/AAHH4ezfasdBkIPm3ofIF5xM6Kln0eDBf9QB/image.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

InsecureSkipVerify = true
defaultEntryPoints = ["http","https"]
email = "test@traefik.io"
storage = "traefik/acme/account"
entryPoint = "https"

[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/traefik.crt"
      KeyFile = "/etc/ssl/traefik.key"

[retry]
attempts = -1

[forwardingTimeouts]

# dialTimeout is the amount of time to wait until a connection to a backend server can be established.
#
# Optional
# Default: "30s"
#
dialTimeout = "3s"

################################################################
# Web configuration backend
################################################################

[web]
address = ":9090"

################################################################
# File configuration backend
################################################################
trace = true

################################################################
# Mesos/Marathon configuration backend
################################################################

[marathon]
endpoint = "https://leader.mesos/marathon"
watch = true
domain = "marathon.localhost"
exposedByDefault = true
marathonLBCompatibility = true

[marathon.DCOSCredentials]
UID = "svc-traefik"
PrivateKey = "/etc/ssl/service-account.key"
LoginEndpoint = "https://leader.mesos/acs/api/v1/auth/login"

[marathon.TLS]
InsecureSkipVerify = true
```
