### ISSUE TITLE
WebSocket Issue : Invalid server key

### ISSUE THREAD

**Issue by Baccanno** [containous/traefik#273]
Hello, Is there any guidelines for WS ?

I'm getting an Invalid Server Key whenever I try to open a socket through traefik. I'm not using SSL yet

The docker container is well exposed and I can see the request being received but then it get closed directly. The problem does not occur if the container port is directly mapped without traefik

I'm using this configuration in my docker compose

```
icons:
  container_name: icons
  image: morphiks/icons
  labels:
    - traefik.backend=icons
    - traefik.frontend.rule=Host
    - traefik.frontend.value=icons-server.morphiks.com
    - traefik.port=2012
    - traefik.frontend.pathHostHeader=true
```

Using this, it should point to the latest traefik master ?

```
traefik:
  container_name: traefik
  image: containous/traefik
```

My test case is super simple : 

```
 wscat -c icons-server.morphiks.com

error: invalid server key
```

**Comment by emilevauge** [comment]
It works using:

```yaml
traefik:
  image: containous/traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"
```

```bash
wscat -H Host:whoami.docker.localhost -c ws://127.0.0.1:80/echo
connected (press CTRL+C to quit)
> hello
< hello
> ⏎     
```

**Comment by Baccanno** [comment]
I will wireshark this.

**Comment by Baccanno** [comment]
I get a 400 Bad Request on the client side. I have no clue why

**Comment by Baccanno** [comment]
When I do this `docker run -p 2012:2012 morphiks/icons`

Then `wscat -c icons-server.morphiks.com:2012`

It works like a charm

**Comment by emilevauge** [comment]
It doesn''t work using the exact compose file I gave you (with whoami)?

**Comment by Baccanno** [comment]
I will test this, I'll tell the result

**Comment by Baccanno** [comment]
Using your file and latest ( build id from Docker Hub : bhw5uwovtvkpmoxnkzivzet ) it works with your sample. But trying to replicate with our config it still throws us with an Invalid Key Error.

Here is the updated docker-compose, it still works with normal docker run.

It infers the ports automagically (probably because the container exposes only one)

```
traefik:
  container_name: traefik
  image: containous/traefik
  command: --web --docker --logLevel=DEBUG
  ports:
    - 8080:8080
    - 80:80
  volumes:
    - /dev/null:/etc/traefik/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock

synchrom:
  container_name: synchrom
  image: morphiks/synchrom
  labels:
    - "traefik.backend=synchrom"
    - "traefik.frontend.rule=Host:synchrom-server.morphiks.com"

icons:
  container_name: icons
  image: morphiks/icons
  labels:
    - "traefik.backend=icons"
    - "traefik.frontend.rule=Host:icons-server.morphiks.com"
```
