### ISSUE TITLE
Feature Request: Option to reset X-Real-IP & X-Forwarded-For headers on incoming requests

### ISSUE THREAD

**Issue by boRk3D** [containous/traefik#2730]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

traefik is exposed to the world (no loadbalancer or other proxy in front) and proxies the requests to some docker containers.

There seems to be no good way to extract the real client ip in the backend from the headers `X-Real-Ip` or `X-Forwarded-For` as the headers can't be trusted.

Imho an option to reset the headers and send only the values set by traefik to the backends would improve the situation. If both headers can be trusted (contain only information from the controlled setup) it should be easy to get the client ip from one of the two headers.

### What did you expect to see?

Any http server in a docker container gets the real client ip in `X-Real-Ip` and finds only the client ip in `X-Forwarded-For` header.
Any service behind a reverse proxy (nginx) in a docker container finds the traefik ip in `X-Real-Ip` (depends on reverse proxy configuration) and  the client ip & traefik ip in the `X-Forwarded-For` header.

headers received by backend:
```
X-Real-Ip: real_client_ip
X-Forwarded-For: real_client_ip
```

headers received by backend (service behind reverse proxy)
```
X-Real-Ip: treafik_ip
X-Forwarded-For: real_client_ip, traefik_ip
```

### What did you see instead?

The client can set `X-Real-Ip` and `X-Forwarded-For` headers with any request. These are used by traefik.
For any http server in a docker container the `X-Real-Ip` will be the value set by the client, and the first entries in `X-Forwarded-For` can be set by the client too.
Any service behind a reverse proxy (nginx) will get the traefik ip in `X-Real-Ip` (depends on reverse proxy configuration) and the first entries for `X-Forwarded-For` can be set by the client.

headers received by backend:
```
X-Real-Ip: value_provided_by_client
X-Forwarded-For: value_provided_by_client, real_client_ip
```

headers received by backend (service behind reverse proxy)
```
X-Real-Ip: treafik_ip
X-Forwarded-For: value_provided_by_client, real_client_ip, traefik_ip
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc5
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2018-01-15_03:59:03PM
OS/Arch:      linux/amd64
```
and
```
Version:      v1.4.6
Codename:     roquefort
Go version:   go1.9.2
Built:        2018-01-02_12:27:08PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik is running via the provided docker container on linux.

I'm using traefik with the docker backend. my entry points are pretty standard:
```toml
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/certs/some.server.net.cert"
      KeyFile = "/certs/some.server.net.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "some.server.net"
watch = true
exposedbydefault = false
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

na
