### ISSUE TITLE
Metrics: 404 not found. (V1.5) can't get it working!

### ISSUE THREAD

**Issue by MaartenMol96** [containous/traefik#2732]
### Do you want to request a *feature* or report a *bug*?

I think a bug, or I am doing something very wrong?

### What did you do?

Configured METRIC as follows in my TOML:

```
[metrics]
  [web.metrics.prometheus]
    entryPoint = "traefik"
    buckets=[0.1,0.3,1.2,5.0]
```

### What did you expect to see?

Prometheus could get data from traefik metrics

### What did you see instead?

When I browse to http://IP_TRAEFIK:8080/metrics I get: 404 not found
Prometheus gives: `server returned HTTP status 404 Not Found`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
V1.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Default protocols for undefined rules
defaultEntryPoints = ["http", "https"]

# Rules for metrics
[metrics]
  [web.metrics.prometheus]
    entryPoint = "traefik"
    buckets=[0.1,0.3,1.2,5.0]

# Rules for API/Web interface
[api]
  dashboard = true
  debug = false
  [api.statistics]
    recentErrors = 10

# Rules for docker backend
[docker]
  exposedbydefault = false
  watch = true
  endpoint = "unix:///var/run/docker.sock"
  domain = "example.com"
```
```yml
  traefik:
    image: traefik:v1.5
    container_name: traefik
    restart: always
    command: --logLevel=WARNING
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/traefik/logs:/var/log/traefik
      - ./traefik/traefik.toml:/traefik.toml
      - /opt/appdata/traefik/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - frontend
      - backend
      - monitor-net
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

Also getting the following: While not even using WEB providers? (As seen in my TOML file?)
```
time="2018-01-21T23:33:57Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics" 
time="2018-01-21T23:33:57Z" level=warning msg="web option is ignored if you use it with one of these options : api, rest provider, ping or metrics" 
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik 😃 

As suggested in the documentation (http://v1-5.archive.docs.traefik.io/configuration/metrics/):
```toml
# Rules for metrics
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets=[0.1,0.3,1.2,5.0]
```

You made a mistake by using `[web.metrics.prometheus]` instead of `[metrics.prometheus]`.
