### ISSUE TITLE
Multiple Docker Swarm services sharing backends not working

### ISSUE THREAD

**Issue by robertgartman** [containous/traefik#2752]
### Do you want to request a *feature* or report a *bug*?

It seems like a bug. But if it is a lack of functionality then let's consider this a feature request.

### What did you do?

The real business need is related to an Elasticsearch cluster where we need to load balance both port 9200 and 9300. We have two Elasticsearch services (Docker Swarm setup, 17.12.0-ce, each service scaled to one replica), but no success putting these behind Traefik. To simply things, we have reproduced the issue with a simple whoami setup.

Let's first cover what works fine. Consider this setup with two different services where load balancing work as expected:

<details>

```yml
version: '3.3'

#----- DEPLOY WITH --------------------------------------------------------------
# MY_SERVICE_DOMAIN=alphabeta.<my domain> MY_SERVICE1_ENTRYPOINT=https docker stack deploy -c "docker-compose.yml" alphabeta
#--------------------------------------------------------------------------------
services:

  # ==================================
  # ALPHA
  # ==================================
  alpha:
    image: emilevauge/whoami
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        # Container labels
        - "traefik.docker.network=myNetwork"
        - "traefik.frontend.rule=Host:$MY_SERVICE_DOMAIN"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.protocol=http"
        - "traefik.port=80"
        - "traefik.entryPoints=$MY_SERVICE1_ENTRYPOINT"
        - "traefik.frontend.backend=whoami_on_service1_backend"
        - "traefik.backend=whoami_on_service1_backend"


  # ==================================
  # BETA
  # ==================================
  beta:
    image: emilevauge/whoami
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        # Container labels
        - "traefik.docker.network=myNetwork"
        - "traefik.frontend.rule=Host:$MY_SERVICE_DOMAIN"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.protocol=http"
        - "traefik.port=80"
        - "traefik.entryPoints=$MY_SERVICE1_ENTRYPOINT"
        - "traefik.frontend.backend=whoami_on_service1_backend"
        - "traefik.backend=whoami_on_service1_backend"

networks:
  proxy:
    external: true

```

</details>
<br>
We keep the Traefik TOML file to a minimum and rely heavily on labels in the docker-compose files. This specific example reuses the same backend port simply because multi-port-whoami-docker-images were not to be found. Using different entry points saves us and we can successfully access the url on both http and https with the expected load balancing in play. Looking into the Trafik admin ui we see the expected:

2 frontend entries
1 backend entry with two servers

Next, we m4odify the Docker compose by adding service labels to support both service1 and service2:

<details>

```yml
version: '3.3'

#----- DEPLOY WITH --------------------------------------------------------------
# MY_SERVICE_DOMAIN=alphabeta.<my domain> MY_SERVICE1_ENTRYPOINT=https MY_SERVICE2_ENTRYPOINT=http stack deploy -c "docker-compose.yml" alphabeta
#--------------------------------------------------------------------------------
services:

  # ==================================
  # ALPHA
  # ==================================
  alpha:
    image: emilevauge/whoami
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        # Container labels
        - "traefik.docker.network=myNetwork"
        - "traefik.frontend.rule=Host:$MY_SERVICE_DOMAIN"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.protocol=http"
        # Service labels
        - "traefik.myservice1.port=80"
        - "traefik.myservice1.entryPoints=$MY_SERVICE1_ENTRYPOINT"
        - "traefik.myservice1.frontend.backend=whoami_on_service1_backend"
        - "traefik.myservice1.backend=whoami_on_service1_backend"
        # Service labels
        - "traefik.myservice2.port=80"
        - "traefik.myservice2.frontend.entryPoints=$MY_SERVICE2_ENTRYPOINT"
        - "traefik.myservice2.backend=whoami_on_service2_backend"
        - "traefik.myservice2.frontend.backend=whoami_on_service2_backend"

  # ==================================
  # BETA
  # ==================================
  beta:
    image: emilevauge/whoami
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        # Container labels
        - "traefik.docker.network=myNetwork"
        - "traefik.frontend.rule=Host:$MY_SERVICE_DOMAIN"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.protocol=http"
        # Service labels
        - "traefik.myservice1.port=80"
        - "traefik.myservice1.entryPoints=$MY_SERVICE1_ENTRYPOINT"
        - "traefik.myservice1.frontend.backend=whoami_on_service1_backend"
        - "traefik.myservice1.backend=whoami_on_service1_backend"
        # Service labels
        - "traefik.myservice2.port=80"
        - "traefik.myservice2.frontend.entryPoints=$MY_SERVICE2_ENTRYPOINT"
        - "traefik.myservice2.backend=whoami_on_service2_backend"
        - "traefik.myservice2.frontend.backend=whoami_on_service2_backend"

networks:
  proxy:
    external: true
```

</details>

### What did you expect to see?

Load balancing of both service1 (HTTPS) and service2 (HTTP).

### What did you see instead?

Neither service1 nor service2 get load balanced. The same Docker container responds every time and Traefik's web admin UI now states 4 frontends and 4 backends.

I see a lack of documentation for cases like this - how to configure separate frontends sharing the same backend. Is this case even meant to be supported or shall this ticket be considered a feature request?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2018-01-23_04:42:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

To reproduce - a basic Docker swarm setup will do. Examples above use constraints to spread the containers on separate nodes but

Configure Traefik as a Docker Swarm service and bind it to the same overlay network as used in the example above ("proxy"). The Traefik TOML file needs 2 [entryPoints], which you use as argument to launch the docker stack.
