### ISSUE TITLE
Commercial SSL Files failed on traefik 1.5.0 ?

### ISSUE THREAD

**Issue by mroberty8** [containous/traefik#2764]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have update traefik from 1.3.8 to 1.5.0.
During this update i didn't change the config file, because some site use commercial SSL files.
And with 1.5.0 is not working but in 1.3.8 is working

With the 1.5.0 with got this error : 
```
time="2018-01-25T11:10:32Z" level=info msg="Starting server on :8080" 
time="2018-01-25T11:10:32Z" level=info msg="Starting server on :80" 
time="2018-01-25T11:10:32Z" level=error msg="Error creating TLS config: tls: private key does not match public key" 
time="2018-01-25T11:10:32Z" level=fatal msg="Error preparing server: tls: private key does not match public key"
```

At this step I tried to remove the SSL configuration with the 1.5.0 version and it's work.

If a set again the SSL configuration is not working.

### What did you expect to see?

I would like to use traefik 1.5.0 with our commercial ssl files.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik for docker 1.5.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Debug mode ?
debug = true

# Check if new version of traefik exist
checkNewVersion = false

# logLevel of information
logLevel = "INFO"

# Default entryPoints
defaultEntryPoints = ["http", "https"]

# Log file
traefikLogsFile = "/var/log/traefik.log"

# Access log
[accessLog]
filePath = "/var/log/access.log"

# Dashbord config
[web]
address = ":8080"
[web.auth.basic]
  usersFile = '/etc/.htpasswd'

# Entry points for redirection
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/ssl/web/ourmdomain.com/your-cert-file.pem"
        KeyFile = "/etc/ssl/web/ourdomain.com/your-cert-key.key"

# Docker config
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "our.docker.domain"
watch = true
exposedbydefault = false

# Letsencrypt configuration
[acme]
email = "our@email.com"
storage = "acme.json"
onHostRule = true
entryPoint = "https"

# Enable HTTP-01 method to create/renew ACME cert
[acme.httpChallenge]
  entryPoint = "http"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2018-01-25T11:10:32Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:0xc42062a000 WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205ce6e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-01-25T11:10:32Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc42042f230 Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205ce6a0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-01-25T11:10:32Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4202b6280 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205ce6c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-01-25T11:10:32Z" level=info msg="Starting server on :8080" 
time="2018-01-25T11:10:32Z" level=info msg="Starting server on :80" 
time="2018-01-25T11:10:32Z" level=error msg="Error creating TLS config: tls: private key does not match public key" 
time="2018-01-25T11:10:32Z" level=fatal msg="Error preparing server: tls: private key does not match public key"
```

Thanks in advance.

Regards
