### ISSUE TITLE
Support of https backend with wildcard certificates ?

### ISSUE THREAD

**Issue by nsteinmetz** [containous/traefik#2770]
### Do you want to request a *feature* or report a *bug*?

Report a bug

### What did you do?

Run nginx https endpoint in http2 mode behind traefik.

### What did you expect to see?

Access to the nginx endpoint

### What did you see instead?

`Internal Server Error`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2018-01-23_04:42:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            certFile = "//wildcard.mycorp.com.crt"
            keyFile = "/wildcard.mycorp.com.key"
```

`docker-compose.yml` file is :

### If applicable, please paste the log output in debug mode (`--debug` switch)

```yml
version: '2'
services:
  traefik:
    image: traefik:cancoillotte-alpine
    command: --api --docker
    networks:
      - mycorp
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/traefik.toml:/traefik.toml
      - ${PWD}/traefik/ssl/wildcard.mycorm.com.key:/wildcard.mycorp.com.key
      - ${PWD}/traefik/ssl/wildcard.mycorp.com.crt:/wildcard.mycorp.com.crt
  nginx:
    build: nginx
    networks:
      mycorp:
        aliases:
         - docker.mycorp.com
    labels:
      traefik.frontend.rule: "Host:docker.mycorp.com"
      traefik.frontend.entryPoints: "http,https"
      traefik.port: "443"
      traefik.protocol: "https"
networks:
  mycorp:
    driver: bridge
```
and `Dockerfile`:

```
FROM nginx
ADD ssl /etc/nginx/ssl
ADD default.conf /etc/nginx/conf.d/default.conf
```

and `default.conf`:

```
server {
    listen 80;
    server_name _ default_server;
    root /usr/share/nginx/html;
    index index.html;
 }
server {
     listen 443 ssl http2;
     server_name _ default_server;
     ssl_certificate /etc/nginx/ssl/wildcard.mycorp.com.chained.crt;
     ssl_certificate_key /etc/nginx/ssl/wildcard.mycorp.com.key;
    root /usr/share/nginx/html;
    index index.html;
}
```

If I switch back nginx https endpoint to http/1.1, it works as expected.

Output of debug mode:

```shell
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}"
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}" ForwardURL=https://172.18.0.3:443
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"https","Opaque":"","User":null,"Host":"172.18.0.3:443","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}"
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"https","Opaque":"","User":null,"Host":"172.18.0.3:443","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}"
traefik_1  | time="2018-01-26T14:04:45Z" level=info msg="vulcand/oxy/forward/http: Round trip: https://172.18.0.3:443, code: 500, Length: 21, duration: 4.925836ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:docker.mycorp.com"
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"https","Opaque":"","User":null,"Host":"172.18.0.3:443","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}"
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"https","Opaque":"","User":null,"Host":"172.18.0.3:443","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}"
traefik_1  | time="2018-01-26T14:04:45Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.54.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"docker.mycorp.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"172.18.0.1:36652","RequestURI":"/","TLS":null}"
```

What is really weird is that when you connect on traefik container (alpine mode), you can `curl https://docker.mycorp.com` and it works as expected...

Let me know if you need more details.
