### ISSUE TITLE
oxy outputs duplicate access logs when logLevel is set to INFO

### ISSUE THREAD

**Issue by ReillyProcentive** [containous/traefik#2782]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Set `logLevel` to `INFO`

### What did you expect to see?
More verbose controller level logs, like when ACME processes run and when backends are added/removed.

### What did you see instead?
Logging entries from vulcand for every single HTTP request that Traefik handles, which essentially duplicates the access logs.

```shell
time="2018-01-29T22:03:00Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://100.104.0.1:8080, code: 200, Length: 0, duration: 2.015332ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:our.domain" 
time="2018-01-29T22:03:01Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://100.104.0.1:8080, code: 200, Length: 0, duration: 1.991752ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:our.domain" 
time="2018-01-29T22:03:29Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://100.104.0.1:8080, code: 200, Length: 0, duration: 2.094348ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:our.domain" 
time="2018-01-29T22:03:29Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://100.104.0.1:8080, code: 200, Length: 0, duration: 2.096226ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:our.domain" 
time="2018-01-29T22:03:29Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://100.104.0.1:8080, code: 200, Length: 0, duration: 1.984957ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:our.domain" 
time="2018-01-29T22:12:33Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://100.104.0.1:8080, code: 200, Length: 60, duration: 9.75096ms tls:version: 303, tls:resume:true, tls:csuite:c02f, tls:server:our.domain" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
checkNewVersion = false
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      [[entryPoints.https.tls.certificates]]
        CertFile = "/ssl/wildcard.our.domain/wildcard.our.domain.crt"
        KeyFile = "/ssl/wildcard.our.domain/wildcard.our.domain.key"
  [entryPoints.admin]
    address = ":8080"
[api]
  entrypoint = "admin"
[ping]
  entrypoint = "admin"
[metrics]
  [metrics.prometheus]
    entrypoint = "admin"
    buckets = [0.1,0.3,1.2,5.0]
[lifeCycle]
  requestAcceptGraceTimeout = "30s"
[kubernetes]
```
