### ISSUE TITLE
a simple request return 302 via traefik

### ISSUE THREAD

**Issue by aximo** [containous/traefik#2784]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
i user docker to run latest traefik image

```shell
docker run -d -p 8888:8080 -p 8880:80 -v $PWD/traefik.sample.toml:/etc/traefik/traefik.toml traefik
```

and the config file is
```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"
[web]
address = ":8080"

[file]
    [backends]
        [backends.local]
            [backends.local.servers.all]
            url = "http://172.18.49.244:9000/"

    [frontends]
        [frontends.local]
        backend = "local"
            [frontends.local.routes.all]
            rule = "Path:/appmonitor/"
```

than i use chrome to acess http://172.25.16.190:8880/appmonitor/

### What did you expect to see?

i want to see web page and browser address should be keep as http://172.25.16.190:8880/appmonitor/

### What did you see instead?

i see the web pages , but browser address is http://172.18.49.244:9000/

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.5.1

 latest image
```

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
linux

![image](https://user-images.githubusercontent.com/5916314/35554652-77efe6f4-05d7-11e8-8881-35164465ad70.png)

![ee](https://user-images.githubusercontent.com/5916314/35554972-90113764-05d8-11e8-9ad5-c7f9c61b454a.jpg)

but in nginx, there is no error and everything matchs my expect
```nginx
location /appmonitor/ {
            proxy_pass http://localhost:9000/;
        }
```
it's a bug or any config error?
