### ISSUE TITLE
HealthCheck, UI Indication

### ISSUE THREAD

**Issue by wahmedswl** [containous/traefik#2792]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
Traefik dashboard list eg: http://localhost:9090/dashboard/#/ list available frontends, backends but it didn't indicate if some backend is unhealthy. I have healthcheck configured as

```
[backends]
  [backends.backend1]
    [backends.backend1.healthCheck]
      path = "/Health.aspx"
      interval = "30s"
```
It returns 200 when Healthy and 500 when not.

### What did you expect to see?
Dashboard should Indicate Healthy/Unhealthy backends

### What did you see instead?
No indicator for unhealthy backends

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.5.1 / cancoillotte
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[file]
  watch = true

[api]

[entryPoints]
  [entryPoints.http]
    address = ":8080"
    compress = true
  [entryPoints.traefik]
    address = ":9090"

[frontends]
  [frontends.frontend1]
  backend = "backend1"

[backends]
  [backends.backend1]
    [backends.backend1.healthCheck]
      path = "/Health.aspx"
      interval = "30s"
    [backends.backend1.servers.server1]
    url = "http://localhost/WebEMREx"
    weight = 10

```
