### ISSUE TITLE
No provided certificate found for domains

### ISSUE THREAD

**Issue by ichasco** [containous/traefik#2804]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?

Nothing

### What did you expect to see?

Get Let's Encrypt cert

### What did you see instead?

Error getting it

### Output of `traefik version`: (_What version of Traefik are you using?_)

```Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

accessLogsFile = "log/access.log"
logLevel = "INFO"
checkNewVersion = true
debug = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS11"
      cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA" ]

[acme]
  email = "info@domain.com"
  storageFile = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
  [acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 0
  acmeLogging = true
  onDemand = false
  OnHostRule = true

[retry]

################################################################
# Web configuration backend
################################################################

[web]
  address = ":8080"
    [web.auth.basic]
    users = ["yuser:$apr1$oijUZadada0Dh$y2rvpB24s/XB9huaPvsvs."]


################################################################
# Docker configuration backend
################################################################

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "domain.com"
  watch = true
  swarmmode = false


```

```yml
version: '3'

services:
  proxy:
    image: traefik
    restart: unless-stopped
    environment:
      - OVH_ENDPOINT=ovh-eu
      - OVH_APPLICATION_KEY=key
      - OVH_APPLICATION_SECRET=secret
      - OVH_CONSUMER_KEY=consumer
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/conf/traefik.toml:/etc/traefik/traefik.toml
      - acme:/etc/traefik/acme
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.domain.com"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"

networks:
  traefik:
    external:
      name: traefik

volumes:
  acme:
```
### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
ime="2018-02-04T17:11:39Z" level=debug msg="Looking for provided certificate to validate [monitor.domain.com]..."
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="No provided certificate found for domains [monitor.domain.com], get ACME certificate."
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="Looking for an existing ACME challenge for monitor.domain.com..."
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="No certificate found or generated for monitor.domain.com"
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="Looking for provided certificate to validate [monitor.domain.com]..."
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="No provided certificate found for domains [monitor.domain.com], get ACME certificate."
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="Looking for an existing ACME challenge for monitor.domain.com..."
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="No certificate found or generated for monitor.domain.com"
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="http2: server: error reading preface from client IP:37594: remote error: tls: unknown certificate authority"
proxy_1  | time="2018-02-04T17:11:39Z" level=debug msg="http2: server: error reading preface from client IP:37592: remote error: tls: unknown certificate authority"

```

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

In TOML, the attribute order are important:
```toml
[acme]
  email = "info@domain.com"
  storageFile = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  acmeLogging = true
  onDemand = false
  OnHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

# you cannot use both challenge.
#  [acme.dnsChallenge]
#    provider = "ovh"
#    delayBeforeCheck = 0
```

Every question asked in issues means less features 😉.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, refer to one of the following:

- [Stack Overflow](https://stackoverflow.com/questions/tagged/traefik) using the "traefik" tag
- the [Traefik community Slack channel](https://traefik.herokuapp.com)
