### ISSUE TITLE
passHostHeader doesn't seems to be forward to https request

### ISSUE THREAD

**Issue by pluque** [containous/traefik#2809]
I have a MVC controller decorated with the [RequiredHttps] attribute which force the a redirection from http to https at the client side.

As you can see in my configuration below, I have set the passHostHeader = true in the frontend config. I have also set the url of my backend service to http://...

I have set it to http:// because when I set the backend service url to https://, the host header does not seems to be forward.

I should be able to combine passHostHeader to https://

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[frontends]
    [frontends.subs]
        backend = "subs"
        passHostHeader = true
        [frontends.subs.routes.any]
            rule = "Host:suba.mysite.com,subb.mysite.com"
...
[backends]
    [backends.subs]
        [backends.subs.servers.1]
        url = "http://172.29.244.248"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc3
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-12-20_02:24:44PM
OS/Arch:      windows/amd64
```
