### ISSUE TITLE
Traefik does not route traffic when order is defined in docker compose file

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#2810]
### Do you want to request a *feature* or report a *bug*?

/bug

### What did you do?

We started using new compose feature called startup order. You need to define in docker-compose.yml
```
order: start-first
```
This feature looks very useful, but traefik becomes confused then and starts routing traffic to containers from different services, means you are requesting one web site, getting another. I am not sure if it is a traefik bug or docker itself, but when we delete this option from our compose files everything normalized immediately.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
######################################################
# Global configuration
######################################################

defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

######################################################
# Entrypoints definition
######################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    compress = false
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    compress = false

######################################################
# Management interface
######################################################

[web]
address = ":8080"
[web.statistics]
  RecentErrors = 100

######################################################
# Docker configuration backend
######################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.org"
watch = true
exposedbydefault = true
swarmmode = true

######################################################
# ACME (Let's Encrypt) configuration
######################################################

[acme]
email = "support@example.com"
entryPoint = "https"
onDemand = true
onHostRule = false
dnsProvider = "rfc2136"
storage = "/acme/acme.json"

```
