### ISSUE TITLE
[API] Weight is not working after some updates

### ISSUE THREAD

**Issue by cocorossello** [containous/traefik#2812]
### Do you want to request a *feature* or report a *bug*?
Bug
### What did you do?
We use to traefik to do blue/green deployment of a stateful web application. Every time we deploy a new server we set up (in the API) a new backend with weight 999999 and we set the weight of the others to 0 so their sessions are drained until we shut them down.

We use a sticky cookie to set the backend. It works most of the time, new sessions are routed to the correct backend (cookie is set with the correct value).

But sometimes, after un update traefik keeps assigning new sessions in a round robin fashion, it makes no sense because I can clearly see that there is one backend with 999999 weight and the others have 0 weight. 

Every time this happens I can clearly see (via a GET to the api) that the setup is ok with only one backend with a high weight. It works again after a few PUTs (it's weird) 

### What did you expect to see?

New sessions should be routed to the backend with the high weight, or at least most of them.

### What did you see instead?
New sessions are routed in a round robin fashion. Each new session to a random backend

### Output of `traefik version`: (_What version of Traefik are you using?_)

Tested in 1.4.4 and in 1.5.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
[rest]
[file]
 watch = true
 [backends]
   [backends.initback]
     [backends.initback.loadbalancer.stickiness]
       cookieName = "backend"
     [backends.initback.servers.S000]
      url = "http://HOST_IP_ADDRESS:30000"
      weight = 0

[frontends]
  [frontends.initfront]
  priority = 1
  backend = "initback"
  passHostHeader  = true
```
When a new server is deployed we do a PUT to  /api/providers/rest with

```json
{
    "backends": {
        "ourbackend": {
            "servers": {
                "S000": {
                    "url": "http://192.168.132.5:30000",
                    "weight": 0
                },
                "S001": {
                    "url": "http://192.168.132.5:30001",
                    "weight": 0
                },
                "S002": {
                    "url": "http://192.168.132.5:30002",
                    "weight": 0
                },
                "S003": {
                    "url": "http://192.168.132.5:30003",
                    "weight": 0
                },
                "S004": {
                    "url": "http://192.168.132.5:30004",
                    "weight": 9999999
                }
            },
            "loadBalancer": {
                "method": "wrr",
                "stickiness": {
                    "cookieName": "backend"
                }
            },
            "healthCheck": {
                "path": "/resources/manager/healthcheck",
                "interval": "3s"
            }
        }
    },
    "frontends": {
        "travelc": {
            "entryPoints": [
                "http"
            ],
            "backend": "ourbackend",
            "passHostHeader": true,
            "priority": 999,
            "basicAuth": null,
            "headers": {}
        }
    }
}
```

The only thing that changes between PUTs is which server has the high weight.

### If applicable, please paste the log output in debug mode (`--debug` switch)

I have no relevant logs, I'm not able to reproduce in local, it only happens from time to time
