### ISSUE TITLE
Let's encrypt configuration in multiple files does not get request certificates

### ISSUE THREAD

**Issue by jonaslewin** [containous/traefik#2816]
### Do you want to request a *feature* or report a *bug*?
Report a bug

### What did you do?

I used the 
```toml
[file]
  directory = "..."
```
feature to split configuration to one file per site. 
The general acme configuration is in the main file, and the domains in each of the site files.

### What did you expect to see?

Issuer: Fake LE Intermediate X1, and Traefik to request certificates for all sites.

### What did you see instead?

Issuer: TRAEFIK DEFAULT CERT, and no requests to Let's Encrypt DNS challange

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
traefik.toml
```toml
debug = true

[traefikLog]
  filePath = "/etc/logs/traefik.log"

[file]
  directory = "/etc/traefik/sites/"
  watch = true

[entrypoints.traefik]
  address=":8080"

[api]
  dashboard = true
  entryPoint = "traefik"

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  
[acme]
email = "my@email.com"
storage = "acme.json"
entryPoint = "https"
caServer = "https://acme-staging.api.letsencrypt.org/directory"
acmeLogging = true
  [acme.dnsChallenge]
  provider = "cloudflare"
```
site1.toml
```toml
[backends]
  [backends.site]
    [backends.site.LoadBalancer]
    method = "wrr"
    [backends.site.servers.server1]
    url = "http://site1"

[frontends]
  [frontends.site]
  entrypoints = ["http","https"]
  backend = "site"
  passHostHeader = true
    [frontends.site.routes.host]
    rule = "Host:site.com,www.site.com"

[[acme.domains]]
  main = "site.com"
  sans = ["www.site.com"]

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

docker logs:
```
docker : legolog: 2018/02/06 20:02:27 [INFO] acme: Registering account for my@email.com
    + CategoryInfo          : NotSpecified: (legolog: 2018/0...my@email.com:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
traefik.log:
```shell
time="2018-02-06T20:02:21+01:00" level=info msg="Using TOML configuration file C:\traefik\traefik.toml" 
time="2018-02-06T20:02:21+01:00" level=info msg="Traefik version v1.5.1 built on 2018-01-29_02:14:02PM" 
time="2018-02-06T20:02:21+01:00" level=debug msg="Global configuration loaded {"LifeCycle":{"RequestAcceptGraceTimeout":0,"GraceTimeOut":0},"GraceTimeOut":0,...}" 
time="2018-02-06T20:02:21+01:00" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc042731e40} with readTimeout=0s writeTimeo
ut=0s idleTimeout=3m0s" 
time="2018-02-06T20:02:21+01:00" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc042731e00} with readTimeout=0s writeTimeout=0s
 idleTimeout=3m0s" 
time="2018-02-06T20:02:21+01:00" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc0426e0080 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc042731e20} with readTimeout=0s writeT
imeout=0s idleTimeout=3m0s" 
time="2018-02-06T20:02:21+01:00" level=info msg="Starting server on :80" 
time="2018-02-06T20:02:21+01:00" level=info msg="Starting server on :8080" 
time="2018-02-06T20:02:22+01:00" level=info msg="Generating ACME Account..." 
time="2018-02-06T20:02:23+01:00" level=debug msg="Building ACME client..." 
time="2018-02-06T20:02:27+01:00" level=debug msg="Using DNS Challenge provider: cloudflare" 
time="2018-02-06T20:02:27+01:00" level=info msg=Register... 
time="2018-02-06T20:02:27+01:00" level=debug msg=AgreeToTOS... 
time="2018-02-06T20:02:27+01:00" level=info msg="Retrieving ACME certificates..." 
time="2018-02-06T20:02:27+01:00" level=info msg="Retrieved ACME certificates" 
time="2018-02-06T20:02:27+01:00" level=info msg="Testing certificate renew..." 
time="2018-02-06T20:02:27+01:00" level=info msg="Starting provider *file.Provider {"Watch":true,"Filename":"C:\\traefik\\traefik.toml","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Directory":"/traefik/sites/"}" 
time="2018-02-06T20:02:27+01:00" level=info msg="Starting server on :443" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Configuration received from provider file: {"backends":{"site":{"servers":{"server1":{"url":"http://site1","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"site":{"entryPoints":["
http","https"],"backend":"site","routes":{"host":{"rule":"Host:site.com,www.site.com"}},"passHostHeader":true,"priority":0,"basicAuth":null}}}" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating frontend site" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Wiring frontend site to entryPoint http" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating route host Host:site.com,www.site.com" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating backend site" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating load-balancer wrr" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating server server1 at http://site1 with weight 0" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Wiring frontend site to entryPoint https" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating route host Host:site.com,www.site.com" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating backend site" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating load-balancer wrr" 
time="2018-02-06T20:02:27+01:00" level=debug msg="Creating server server1 at http://site1 with weight 0" 
time="2018-02-06T20:02:27+01:00" level=info msg="Server configuration reloaded on :8080" 
time="2018-02-06T20:02:27+01:00" level=info msg="Server configuration reloaded on :80" 
time="2018-02-06T20:02:27+01:00" level=info msg="Server configuration reloaded on :443" 
```
### temporary workaround

If I move everything to traefik.toml, I get the expected behavior but without the separation of concerns.
