### ISSUE TITLE
Forward Authentication should also forward the requested URL.

### ISSUE THREAD

**Issue by oresot** [containous/traefik#2820]
### Feature

The current approach of forward authentication is very limited without forwarding the requested URL to the authentication backend. This forces us to serve the authentication backend outside Traefik.

### What did you do?

I have implemented an OAuth2 client similar to this one: http://requests-oauthlib.readthedocs.io/en/latest/examples/real_world_example.html

My setup is like the one in the docs:
```toml
    [entryPoints.http.auth.forward]
    address = "https://myoauthclient.mydomain.com/auth"
```

My OAuth client is a container served by Traefik, so every request will be redirected to that container, even the callback ones. The OAuth2 callback includes a field "code" in the URL (generated by Google OAuth) that must be passed to the client I made, but the request I get does not contain the URL path.

ie: Accessing to this URL: https://myfinalservice.mydomain.com/oauthcallback/auth?code=XXXXXXX&moreparameters

I just get this, with no trace of the "code" I need to validate.

```
{'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
  'HTTP_ACCEPT_LANGUAGE': 'en-GB,en-US;q=0.9,en;q=0.8',
  'HTTP_AUTHORIZATION': 'Basic ZZZZZZZZZZZ',
  'HTTP_COOKIE': 'session=YYYYYYYYYYYY',
  'HTTP_DNT': '1',
  'HTTP_FORWARDED': 'for=1.2.3.4; proto=https; by=172.17.0.2; '
                    'httpproto=http/2.0; tlsver=tls12; tlscipher=0xc02f',
  'HTTP_HOST': 'oauth.service.consul.mydomain.com:5090',
  'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
  'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) '
                     'AppleWebKit/537.36 (KHTML, like Gecko) '
                     'Chrome/63.0.3239.132 Safari/537.36',
  'HTTP_X_FORWARDED_FOR': '1.2.3.4, 5.6.7.8',
  'HTTP_X_FORWARDED_HOST': 'myfinalservice.mydomain.com',
  'HTTP_X_FORWARDED_PORT': '443',
  'HTTP_X_FORWARDED_PROTO': 'https',
  'HTTP_X_REAL_IP': '1.2.3.4',
  'PATH_INFO': '/auth',
  'QUERY_STRING': '',
  'REMOTE_ADDR': '5.6.7.8',
  'REMOTE_PORT': 36738,
  'REQUEST_METHOD': 'GET',
  'SCRIPT_NAME': '',
  'SERVER_NAME': '0.0.0.0',
  'SERVER_PORT': '5000',
  'SERVER_PROTOCOL': 'HTTP/1.1',
  'SERVER_SOFTWARE': 'Werkzeug/0.14.1',
  'werkzeug.server.shutdown': <function WSGIRequestHandler.make_environ.<locals>.shutdown_server at 0x7fe4a731fae8>,
  'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
  'wsgi.input': <_io.BufferedReader name=4>,
  'wsgi.multiprocess': False,
  'wsgi.multithread': False,
  'wsgi.run_once': False,
  'wsgi.url_scheme': 'http',
  'wsgi.version': (1, 0)}
```

The only solution I've found is serving the callback outside Traefik, with fabiolb. But this makes no sense.

### What did you expect to see?

Together with HTTP_X_FORWARDED_HOST an HTTP_X_FORWARDED_URL with the original URL requested by the client.

### What did you see instead?

Just HTTP_X_FORWARDED_HOST

### Output of `traefik version`: 

```
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "WARN"
defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":9951"
	[entryPoints.http.auth.forward]
	address = "http://oauth.service.consul.mydomain.com:5090/auth"
	trustForwardHeader = true

[web]
    [web.auth.basic]
    users = ["user:pw"]
address = ":8080"

[consul]
endpoint = "consul.service.consul.mydomain.com:8500"
watch = true
prefix = "traefik"

[consulCatalog]
watch = true
endpoint = "consul.service.consul.mydomain.com:8500"
prefix = "traefik"
```
