### ISSUE TITLE
Websocket connections from Iphone browsers cannot be forwarded

### ISSUE THREAD

**Issue by tianhai82** [containous/traefik#2828]
### Do you want to request a *feature* or report a *bug*?
Bug.

### What did you do?
I deployed Traefik to Google Kubernetes Engine and configured it as a Ingress. I have a websocket backend which Traefik is configured to forward connections to. When I use a desktop browser and an Android phone browser to connect to this websocket connection, Traefik manages to forwards it successfully. However, when I use a browser in IPhone 7 to access this websocket connection, Traefik fails to forward it. 

### What did you expect to see?
Traefik is able to forward websocket connections from IPhone clients successfully

### What did you see instead?
Traefik fails to forward websocket connections from IPhone with the following errors logged
```
time="2018-02-07T03:42:41Z" level=error msg="vulcand/oxy/forward/websocket: Error when copying from client to backend: websocket: close 1006 (abnormal closure): unexpected EOF"
time="2018-02-07T06:03:59Z" level=error msg="vulcand/oxy/forward/websocket: Error when copying from client to backend: read tcp 10.56.4.3:443->10.138.0.2:49209: read: connection timed out" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Docker image: traefik:1.5.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
[acme]
acmeLogging = true
email = "xxx@xxxcom"
storageFile = "/acme/acme.json"
entryPoint = "https"
onDemand = true
onHostRule = true
# caServer = "https://acme-v01.api.letsencrypt.org/directory"
[[acme.domains]]
main = "xxx.com"
sans = ["www.xxx.com","internal.xxx.com","staging.xxx.com"]
[acme.httpChallenge]
entryPoint = "http"
```
