### ISSUE TITLE
TLS handshake without SNI delivers TRAEFIK DEFAULT CERT instead ACME generated certificate

### ISSUE THREAD

**Issue by x-gnn** [containous/traefik#2829]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Setting up Traefik with Let's Encrypt ACME certificate and check the certificate with and without TLS SNI (Server Name Indication).

### What did you expect to see?

Check certficate with SNI:

```bash
echo "quit" | openssl s_client -tls1 -connect '<my-domain>:443' -servername <my-domain> 2>/dev/null | grep 'subject'
subject=/CN=<my-domain>
```

Check certficate without SNI:

```bash
echo "quit" | openssl s_client -tls1 -connect '<my-domain>:443' 2>/dev/null | grep 'subject'
subject=/CN=<my-domain>
```

### What did you see instead?

Check certficate with SNI:

```bash
echo "quit" | openssl s_client -tls1 -connect '<my-domain>:443' -servername <my-domain> 2>/dev/null | grep 'subject'
subject=/CN=<my-domain>
```

Check certficate without SNI:

```bash
echo "quit" | openssl s_client -tls1 -connect '<my-domain>:443' 2>/dev/null | grep 'subject'
subject=/CN=TRAEFIK DEFAULT CERT
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using Docker Swarm Mode to set up a stack with Consul and Traefik by this compose file:

```yaml
version: '3.2'

services:
  consul:
    image: docker.io/consul:1.0.3
    command: agent -server -bootstrap-expect 1 -node lb-consul -data-dir /consul/data -client 0.0.0.0 -advertise '{{ GetInterfaceIP "eth2" }}' -datacenter loadbalancer -ui
    ports:
      - "8500:8500"
    networks:
      - local
    deploy:
      resources:
        limits:
          memory: 32M
      restart_policy:
        condition: any
        delay: 10s

  traefik:
    image: docker.io/traefik:1.5-alpine
    command:
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--respondingtimeouts.idletimeout=120s"
      - "--respondingtimeouts.readtimeout=60s"
      - "--respondingtimeouts.writetimeout=60s"
      - "--forwardingtimeouts.dialtimeout=15s"
      - "--forwardingtimeouts.responseheadertimeout=30s"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=<my-domain>"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--web"
      - "--web.address=:8080"
      - "--web.readonly"
      - "--web.statistics"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
      - "--consul.watch=false"
      - "--acme"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.email=hostmaster@<my-company>"
      - "--acme.onhostrule=false"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.domains=<my-domain>,sub1.<my-domain>,sub2.<my-domain>,sub3.<my-domain>"
      - "--acme.acmelogging"
    depends_on:
      - consul
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GOMAXPROCS: 1
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: any
        delay: 10s

networks:
  local:
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

none

### Description

We are missing the possibility to replace the TRAEFIK DEFAULT CERT by the ACME generated certificate for clients which does not support TLS SNI. Maybe it is useful to control this by an option like ```acme.useAsDefault``` or something else.
