### ISSUE TITLE
Front-end basic auth is ignored for the traefik docker container

### ISSUE THREAD

**Issue by Cajga** [containous/traefik#2833]
### What did you do?
Wanted to enable basic auth for the API back-end while using the https entrypoint

### What did you expect to see?
As you can see from the first log line the docker provider gave the proper configuration ("basicAuth":["myuser:$apr1$Rglur..e$imodifiedthispartonly/"]). So, I expected to see the auth form when I access the api dashboard.

### What did you see instead?
The dashboard is properly shown without any authentication

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
$ docker exec -ti 19073ce00f74 /traefik version
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
defaultEntryPoints = ["https","http"]

InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
entrypoint = "https"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.org"
watch = true
exposedbydefault = false

[acme]
email = "myname@,ydomain.org"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"
```
Docker compose conf:
```yml
version: '3'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - traefikext
      - federationweb
    labels:
      - traefik.backend=traefik
      - traefik.docker.network=traefikext
      - traefik.frontend.rule=Host:traefik.mydomain.org
      - traefik.port=443
      - traefik.enable=true
      - traefik.frontend.auth.basic=myuser:$$apr1$$Rglur..e$$imodifiedthispartonly/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik

networks:
  traefikext:
    external: true
  federationweb:
    external: true
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
Relevant debug log output
```shell
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-traefik":{"servers":{"server-traefik":{"url":"http://172.18.0.2:443","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-Host-traefik-mydomain-org-0":{"entryPoints":["https","http"],"backend":"backend-traefik","routes":{"route-frontend-Host-traefik-mydomain-org-0":{"rule":"Host:traefik.mydomain.org"}},"passHostHeader":true,"priority":0,"basicAuth":["myuser:$apr1$Rglur..e$imodifiedthispartonly/"]}}}" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating frontend frontend-Host-traefik-mydomain-org-0" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Wiring frontend frontend-Host-traefik-mydomain-org-0 to entryPoint https" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating route route-frontend-Host-traefik-mydomain-org-0 Host:traefik.mydomain.org" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating backend backend-traefik" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating load-balancer wrr" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating server server-traefik at http://172.18.0.2:443 with weight 0" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating retries max attempts 1" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Wiring frontend frontend-Host-traefik-mydomain-org-0 to entryPoint http" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating route route-frontend-Host-traefik-mydomain-org-0 Host:traefik.mydomain.org" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\/\/)?([\w\._-]+)(?::\d+)?(.*)$ -> https://$1:443$2" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating backend backend-traefik" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating load-balancer wrr" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating server server-traefik at http://172.18.0.2:443 with weight 0" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Creating retries max attempts 1" 
traefik    | time="2018-02-09T11:35:27Z" level=info msg="Server configuration reloaded on :443" 
traefik    | time="2018-02-09T11:35:27Z" level=info msg="Server configuration reloaded on :80" 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="LoadCertificateForDomains [traefik.mydomain.org]..." 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="Looking for provided certificate to validate [traefik.mydomain.org]..." 
traefik    | time="2018-02-09T11:35:27Z" level=debug msg="No provided certificate found for domains [traefik.mydomain.org], get ACME certificate." 
```

**Comment by nmengin** [comment]
Hello @cajga.

Many thanks for your interest in the project.

Indeed, it's not possible adding dynamically a `basic auth` on Træfik dashboard.
But you can add it statically, which is, almot, the same thing because Træfik will restart if you restart your container.

In this way, you can provide the configuration described below :

**traefik.toml** :

```toml
...
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth.basic]
    users = ["user:pwd"]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
entryPoint = "traefik"

...
```

**docker-compose.yaml** :

```yaml

...

traefik:
  image: traefik
  restart: always
  ports:
    - 80:80
    - 443:443
  expose:
    - 8080
  networks:
    - traefikext
    - federationweb
  labels:
    - traefik.backend="traefik"
    - traefik.docker.network="traefikext"
    - traefik.port="8080"
    - traefik.frontend.rule="Host:traefik.mydomain.org"
    - traefik.enable="true"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /opt/traefik/traefik.toml:/traefik.toml
    - /opt/traefik/acme.json:/acme.json
  container_name: traefik

...
```

A Pull Request will be created to add an example in the documentation.

**Comment by Cajga** [comment]
Hi @nmengin,

Thanks for the reply. Yes, that was my original solution but I think this has some limitations that I could not overcome:
* I would like to use TLS for the basic auth to the dashboard so my username and password hash does not travel through clear text. My Let's encrypt works well on the https entrypoint but I could not get it working on two entry points (https and traefik in your example)
* I personally does not like to use a different port for such solution. I tried to set it up with a different entry point on port 8443 (used TLS with the default certificate) and use static front-end configuration to proxy it from port 443 (like proxying https://traefik.mydomain.org to the 8443 entrypoint ) but could not figure out how to do it (is it possible to proxy to a different entry point?)
* with a separate entry point, in case I visit any of my sites on port 8443 (let's stick with TLS) I will end up with the dashboard

So, all in all what I would like to achieve is to have https://traefik.mydomain.org pointing to my traefik dashboard with basic authentication and it does not listen on any other port (and this is done with the docker image and docker back-ends). Is this possible somehow?

**Comment by nmengin** [comment]
Hello @Cajga.

If I correctly understood your need, the solution I proposed should work for you.

Indeed, in the TOML file, we defined the blocks : 

```toml
defaultEntryPoints = ["http", "https"]

...

  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth.basic]
    users = ["user:pwd"]
```

It allows defining an entrypoint with basic auth and no TLS for the dashboard, but it does not expose the port 8080 of your Træfik instance.

In the YAML file, we added these options : 

```yaml
ports:
    - 80:80
    - 443:443
  expose:
    - 8080
...
labels:
    - traefik.port="8080"
    - traefik.frontend.rule="Host:traefik.mydomain.org"
```

They allow : 

* Binding ports 80 and 443 from your Træfik container to your host
* Exposing the port 8080 into your Docker network with no binding
* Configuring Træfik to bind requests with the hostname `traefik.mydomain.org` to the port 8080 of the container.

But, as no specific entryPoints are specified in the Træfik labels, it will use the `default entryPoints` defined in the TOML file.

Thanks to this configuration you can access to the dashboard from the ports 80 and 443 of your host.
As you definied a redirection between the entrypoints `http` and `https`, all your requests will be in HTTPS.

I hope I answered your question, otherwise, son't hesitate to come on the [Traefik Slack](https://traefik.herokuapp.com) and we will try to help you.
