### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jayfk** [containous/traefik#284]
**Stacktrace**
---
```
level=info msg="Server configuration reloaded on :80"
traefik_1 | time="2016-04-06T08:39:24Z" level=debug msg="Docker event receveived &{Status:die ID:dd45b34614bae349d8b45fbfa5a9bd7f1500fb2ccff14837fb84aec5675a406d From:emilevauge/whoami Time:1459931964}"
2016/04/06 08:39:26 safe.go:26: runtime error: invalid memory address or nil pointer dereference
goroutine 39 [running]:
untime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
 runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
 github.com/containous/traefik/safe.defaultRecoverGoroutine(0xc21260, 0xc820010060)
 	/go/src/github.com/containous/traefik/safe/safe.go:27 +0x81
 github.com/containous/traefik/safe.GoWithRecover.func1.1(0xeb3240)
 	/go/src/github.com/containous/traefik/safe/safe.go:18 +0x4e
 panic(0xc21260, 0xc820010060)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
 github.com/containous/traefik/provider.listContainers(0xc8201cc120, 0x0, 0x0, 0x0)
	/go/src/github.com/containous/traefik/provider/docker.go:266 +0x2f7
 github.com/containous/traefik/provider.(*Docker).Provide.func1.1(0x0, 0x0)
 	/go/src/github.com/containous/traefik/provider/docker.go:78 +0x897
 github.com/containous/traefik/vendor/github.com/cenkalti/backoff.RetryNotify(0xc8203a9f40, 0x7f35eb8d5218, 0xc8201bc060, 0xeb3210, 0x0, 0x0)
 	/go/src/github.com/containous/traefik/vendor/github.com/cenkalti/backoff/retry.go:32 +0x4d
 github.com/containous/traefik/provider.(*Docker).Provide.func1()
 	/go/src/github.com/containous/traefik/provider/docker.go:93 +0xbd
 github.com/containous/traefik/safe.GoWithRecover.func1(0xeb3240, 0xc8201b4380)
 	/go/src/github.com/containous/traefik/safe/safe.go:21 +0x44
 created by github.com/containous/traefik/safe.GoWithRecover
	/go/src/github.com/containous/traefik/safe/safe.go:22 +0x3f
```

To reproduce, create the following `docker-compose.yml`

```
traefik:
  image: containous/traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

app:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=app"
    - "traefik.frontend.rule=Path:/app"
```

Then, run:

```
docker-compose up 
```

Open a second terminal and run:

```
docker-compose scale app=100
docker-compose scale app=1
```

**Comment by emilevauge** [comment]
@jayfk: oO
Thanks for reporting :'(
Which version are you using?

**Comment by jayfk** [comment]
```
docker-compose run traefik version                                                                                       
2016/04/06 09:02:37 v1.0.0-beta.355 built on the 2016-04-04_08:40:30AM
```

```
docker-compose version                                                                                                  
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2e 3 Dec 2015
```

```
docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Comment by emilevauge** [comment]
OK, it will be fixed by PR #278.
I will merge it today.

**Comment by jayfk** [comment]
Excellent!

**Comment by trivoallan** [comment]
I still have the problem with this docker-compose.yml when scaling down (from 10 to 1 for instance) :

```
version: '2'

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    networks:
      - public
    labels:
      - traefik.backend=web
      - traefik.port=80
      - traefik.frontend.rule=Host:daheardit.docker.local

  mysql:
    build: docker/mysql/
    networks:
      - public
    labels:
      - traefik.enable=false

  proxy:
    image: traefik:v1.0.0-beta.704
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - public
    labels:
      - traefik.enable=false

networks:
  public:
```
