### ISSUE TITLE
Need a way to refer to container port instead of host port

### ISSUE THREAD

**Issue by OlivierCazade** [containous/traefik#2854]
Hi,

### Do you want to request a *feature* or report a *bug*?

Request a feature

### What did you do?

We are using traefik with ecs backend.

Our services are using dynamic host port (host port is dynamically set by ecs). As long as services are only exporting one port, Traefik is doing great.

When using multiple ports, we can not tell traefik which port to use since using traefik.port label is about host port.

### What did you expect to see?

A way to refer to internal port.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$docker run traefik:v1.5 version
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"

[ecs]
clusters = ["default"]
watch = true
domain = "docker.test"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = false
```

Here is how we set container ports in Task definition files
```json
"portMappings": [
  {
    "containerPort": 80
  },
  {
    "containerPort": 8080
  }
]
```
