### ISSUE TITLE
Custom headers on authentication

### ISSUE THREAD

**Issue by supermock** [containous/traefik#2861]
### Do you want to request a feature or report a bug?
I would like to request a new feature.

### What did you do?
I've set up 4 services in Docker:
- Traefik
- Prometheus
- AlertManager
- Grafana

### What did you expect to see?
I was hoping to add Prometheus to the Grafana **data source**.

### What did you see instead?
Just a CORS error. (No 'Access-Control-Allow-Origin' header is present on the requested resource.)

### Output of `traefik version`:
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
It is not necessary, it is a feature.

### If applicable, please paste the log output in debug mode (`--debug` switch)
There are no logs, it's a feature.

### Feature:
The problem faced is as follows. I am using a Trafik authentication system (Basic Auth) in Prometheus, and when Grafana makes the request, gives the CORS error, I believe this happens because when authenticating it does not have the CORS header, so I looked for some way to add the CORS header, but I did not find anything on it, so I'm here to ask this feature to handle custom headers (in my case CORS) in authentication. If you have a better idea to solve this, I'm open to suggestions.

**Note:** I'm using Docker, and in this case I use the **labels** to configure the settings.

Thank you very much in advance

**Comment by ldez** [comment]
I think what you are searching is https://docs.traefik.io/configuration/backends/docker/#security-headers

**Comment by supermock** [comment]
I configured this, but the added header is not available at the time of authentication.

```yml
labels:
  traefik.frontend.headers.customResponseHeaders: 'Access-Control-Allow-Origin: *'
  traefik.frontend.auth.basic: 'user:**********'
```

**Comment by supermock** [comment]
I wrote a test to help:

**docker-compose.yml**
```yml
version: '2.2'

services:
  traefik:
    container_name: traefik
    image: traefik:v1.5
    labels:
      traefik.enable: 'false'
    volumes: 
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '8080:8080'
  
  whoami:
    container_name: whoami
    image: emilevauge/whoami
    labels:
      traefik.frontend.headers.customResponseHeaders: 'Access-Control-Allow-Origin: *'
      traefik.frontend.auth.basic: 'admin:$$apr1$$GNAg6UHc$$kNAZOac7mB26nGP1XPwVO.'
    expose:
      - '80'
```

**traefik.toml**
```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.traefik]
    address = ":8080"

    [entryPoints.traefik.auth]
      headerField = "X-WebAuth-User"
      [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$GNAg6UHc$kNAZOac7mB26nGP1XPwVO."]

[api]
  entryPoint = "traefik"
  dashboard = true

[docker]
  domain = "localhost"
  watch = true
```

Here I made a call with cURL:
```sh
$ curl -v http://admin:admin@whoami.poc.localhost/health
*   Trying ::1...
* TCP_NODELAY set
* Connected to whoami.poc.localhost (::1) port 80 (#0)
* Server auth using Basic with user 'admin'
> GET /health HTTP/1.1
> Host: whoami.poc.localhost
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< Date: Fri, 16 Feb 2018 14:16:51 GMT
< 
* Curl_http_done: called premature == 0
* Connection #0 to host whoami.poc.localhost left intact
```
