### ISSUE TITLE
Ultimate Access log filter

### ISSUE THREAD

**Issue by mmatur** [containous/traefik#2875]
### Do you want to request a *feature* or report a *bug*?

Feature

## Description
This issue is a proposal following PRs #2853 and #2397 on modifying access logs. 

```toml
[accessLog]
filepath = "..."
type = "..."

# filter access log line
[accessLog.filter]
# Keep on only access logs with status code in the range
statusCode = ["..."]

[accessLog.fields]
  defaultMode = "drop|keep"
  [accessLog.fields.names]
    host = "drop"
    # ...

  [accessLog.fields.headers]
   defaultMode = "drop|keep|redact"
   [accessLog.fields.headers.names]
     User-Agent = "redact"
     Authorization = "drop"
     Content-Type = "keep"
     # ...
```

## Filter

`statusCode` range format:
    
- `["200"]` :  only page with status code 200
- `["400-499"]`: only page with status code between 400 and 499
- `["200", "400-499"]`: page with status code 200 or status code between 400 and 499

#### Fields

In this example we will drop all fields except `DownstreamStatus`:
    
```toml
[accessLog.fields]
  defaultMode = "drop"
  [accessLog.fields.names]
    DownstreamStatus = "keep"
```

In this  example we will keep all fields except `DownstreamStatus`:
    
```toml
[accessLog.fields]
  defaultMode = "keep"
  [accessLog.fields.names]
    DownstreamStatus = "drop"
```

All available fields:

- `BackendAddr`
- `BackendName`
- `BackendURL`
- `ClientAddr`
- `ClientHost`
- `ClientPort`
- `ClientUsername`
- `DownstreamContentSize`
- `DownstreamStatus`
- `DownstreamStatusLine`
- `Duration`
- `FrontendName`
- `OriginContentSize`
- `OriginDuration`
- `OriginStatus`
- `OriginStatusLine`
- `Overhead`
- `RequestAddr`
- `RequestContentSize`
- `RequestCount`
- `RequestHost`
- `RequestLine`
- `RequestMethod`
- `RequestPath`
- `RequestPort`
- `RequestProtocol`
- `RetryAttempts`
- `StartLocal`
- `StartUTC`
- `level`
- `msg`
- `time`

### Headers

In this example we will drop all headers except:
- `User-Agent` that will be redacted
- `Authorization` that will be kept with original data
- `Content-Type` that will be kept with original data

```toml
[accessLog.fields.headers]
defaultMode = "drop"
  [accessLog.fields.headers.names]
    User-Agent = "redact"
    Authorization = "keep"
    Content-Type = "keep"
```

In this example we will keep all headers:
- `User-Agent` that will be redacted
- `Authorization` that will be dropped
- `Content-Type` that will be dropped

```toml
[accessLog.fields.headers]
defaultMode = "keep"
  [accessLog.fields.headers.names]
    User-Agent = "redact"
    Authorization = "drop"
    Content-Type = "drop"
```

In this example we will redact all headers:
- `User-Agent` that will be kept with original data
- `Authorization` that will be dropped
- `Content-Type` that will be dropped

```toml
[accessLog.fields.headers]
defaultMode = "redact"
  [accessLog.fields.headers.names]
    User-Agent = "keep"
    Authorization = "drop"
    Content-Type = "drop"
```

Related to #1079, #1902, #2067
