### ISSUE TITLE
Resolve domain names to Punycode before requesting a TLS certificate with acme

### ISSUE THREAD

**Issue by funkyfuture** [containous/traefik#2879]
### Do you want to request a *feature* or report a *bug*?

depends on perspective.

### What did you do?

i configured a Docker container with a label `traefik.frontend.rule=Host:<hostname>` where the hostname includes a non-ascii character.

traefik is configured to automatically request tls-certificates from Let's Encrypt:

```toml
[acme]
email = "…"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

  [acme.httpChallenge]
  entryPoint = "http"
```

the error message is similar to the one reported in #2703, but also preceeded by this line:

    level=error msg="Near line 28 (last key parsed 'backends.backend-gitea.servers.server-gitea_gitea_1'): expected '.' or ']' to end table name, but got 'ä' instead" 

### What did you expect to see?

no error messages, but an automatic conversion of the hostname to Punycode as discussed in #2703.
