### ISSUE TITLE
Placeholder that resolve Host IP from inside Docker Container

### ISSUE THREAD

**Issue by arubacao** [containous/traefik#2884]
### Do you want to request a *feature* or report a *bug*?

Feature

### Explain Feature

Option to resolve the hosts IP when starting traefik via Docker.
E.g.
```toml
# config.toml
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8001" # <-- doesn't work
    url = "http://hostos:8001" #<-- 'hostos' resolves host ip address 
```

### What did you do?

1. Start traefik via docker listen on port 80 & 443
2. Start http server on port 8001 on host os
3. Tried to add the http server on port 8001 as a backend
```toml
# config.toml
[file]

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  [frontends.frontend1.routes.backend1]
  rule = "Host:thedomain.org"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8001"
```

### What did you expect to see?

See response from `http://127.0.0.1:8001` (localhost of host os) when requesting `thedomain.org:80`

### What did you see instead?

Obvs. `502 Bad Gateway`. The config works when I start traefik via the binary instead of docker.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```
