### ISSUE TITLE
https redirect with docker labels

### ISSUE THREAD

**Issue by jfjallid** [containous/traefik#2885]
#541 brought up a feature request for redirecting http to https on a per container/frontend basis using labels. The ticket is closed and was added to the milestone of 1.5. I'm running traefik in 1.5.2 and it seems as the label `traefik.frontend.redirect.entryPoint=https` is ignored and the redirect is not functional.

### What did you do?
I have installed traefik using the official docker image and I have setup a different container with labels to redirect to https, but when visiting the http site I'm not redirected.

### What did you expect to see?
I would expect to be redirected to https when browsing to the http address.

### What did you see instead?
No redirect. If I go to the http address I visit the http version of the site and if I go to the https address I visit the https version of the site.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
I'm running this setup in Fedora 24.

traefik.toml:
```toml
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[traefiklog]
filepath = "/var/log/traefik/traefik.log"

[web]
address = ":5555"

[entryPoints]
    [entryPoints.http]
    address = ":80"

    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[acme]
email = "xxxxxxx@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"

[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
main = "example.com"
sans = ["wiki.example.com"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
watch = true
exposedbydefault = true
```
Docker labels on container that should redirect to https:
```
traefik.backend: "wiki"
traefik.frontend.rule: "Host:wiki.example.com"
traefik.docker.network: "traefik-proxy"
traefik.backend.port: "80"
traefik.enable: "true"
traefik.frontend.redirect.entryPoint: "https"
```

**Comment by dac388** [comment]
traefik.frontend.headers.SSLRedirect=true | Forces the frontend to redirect to SSL if a non-SSL request is sent.

**Comment by jfjallid** [comment]
@dac388 No change from what I can see using that label. Still no redirect to https.

**Comment by dac388** [comment]
did you try w/o traefik.frontend.redirect.entryPoint: "https"

**Comment by jfjallid** [comment]
@dac388 Tried it now and it did not seem to change anything. Still no redirect.

**Comment by ldez** [comment]
could you provide your docker-compose file.

**Comment by jfjallid** [comment]
@ldez I use ansible and not docker-compose, but this is my ansible task if that is relevant:
```
- name: setup wiki container
  docker_container:
    name: wiki
    image: tutum/apache-php
    ports:
      - "8989:80"
    state: present
    networks:
      - name: "traefik-proxy"
    labels:
      traefik.backend: "wiki"
      traefik.frontend.rule: "Host:wiki.example.com"
      traefik.docker.network: "traefik-proxy"
      traefik.backend.port: "80"
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
    volumes:
      - "{{ docker_config }}wiki:/var/www/html"
    env:
      ALLOW_OVERRIDE: true
    pull: true
  tags:
    - wiki
  notify:
    - restart wiki
```
