### ISSUE TITLE
Trigger action when the health state of a backend changes

### ISSUE THREAD

**Issue by PeterBurner** [containous/traefik#2893]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

Added healthchecks to my backends

### What did you expect to see?

A action property which accepts for example an url which is called if a backend/server goes offline/online

### What did you see instead?

No posibility to trigger an action when the state of a backend changes

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[backends]
  [backends.backend1]
    [backends.backend1.healthcheck]
    path = "/health"
    interval = "10s"
    port = 8080
    action = "POST: https://do.stuff.com/"
```
--> body should contain event details like backend name, server name, state etc.

```toml
[backends]
  [backends.backend1]
    [backends.backend1.healthcheck]
    path = "/health"
    interval = "10s"
    port = 8080
    action = "GET: https://do.stuff.com/log?info1={info1}&..."
```
--> placeholder `{info1}` should be replaced by event detail1, ...

```toml
[backends]
  [backends.backend1]
    [backends.backend1.healthcheck]
    path = "/health"
    interval = "10s"
    port = 8080
    action = "CMD: /usr/bin/my_executable -data {data}"
```
--> placeholder `{data}` should be replaced by event details
