### ISSUE TITLE
Issues with Loaded/Or Not Load certificates make Traefik Stop working (also enhancing logging)

### ISSUE THREAD

**Issue by mstenz** [containous/traefik#2897]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Added a tls certificate with a typo in the filename

### What did you expect to see?
After restart of Traefik is serving all other pages and load all the valid settings and report an valid error in the log that specifies:
- which file wanted to be loaded and was not possible
- if the file was possible to load what was exactly the issue why the certificate validation failed

### What did you see instead?
After restart of Traefik it was not able to run, instead i received this log entry

```
time="2018-02-20T11:47:45Z" level=error msg="Error creating TLS config: tls: failed to find any PEM data in certificate input"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker endpoint configuration with certificates written manually in traefik.toml file:

```toml
[entryPoints.https]
    address = ":443"
    #compress = true
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
	CipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384"
    ]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/cert.crt"
      keyFile = "/etc/traefik/ssl/key.key"
```
