### ISSUE TITLE
Forward Authentication Endless Loop

### ISSUE THREAD

**Issue by mtgerb** [containous/traefik#2919]
### Do you want to request a *feature* or report a *bug*?

A bug.

### What did you do?

Configured traefik to use forward authentication, with a URL pointing to the same traefik.

### What did you expect to see?

Traefik should not try to authenticate the requests against the forward authentication endpoint.

### What did you see instead?

Endless loop.

### Output of `traefik version`: 

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

EntryPoint definition
```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
      [entryPoints.http.auth.forward]
      address = "http://DOMAIN/auth"
      trustForwardHeader = true
```
ECS backend
```toml
[ecs]
clusters = ["CLUSTER"]
watch = true
domain = "DOMAIN"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = false
region = "us-east-1"
```
Labels of my authentication service
```
 "traefik.enable": "true",
 "traefik.frontend.rule": "PathPrefix:/saml,/user,/auth",
 "traefik.backend.healthcheck.path": "/health"
```
Concrete steps:
1. User calls http://mydomain/
2. Traefik calls http://mydomain/auth
3. Authentication service redirects http://mydomain/saml
4. Traefik returns the redirect to the browser
5. Browser calls http://mydomain/saml
6. Traefik tries to authenticate the request to http://mydomain/saml and calls again http://mydomain/auth
