### ISSUE TITLE
The --web.statistic argument does not work for DeamonSet in Kubernetes

### ISSUE THREAD

**Issue by DmitriyProkhorov** [containous/traefik#2937]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you see instead?

When I run DeamonSet on kubernetes with config:
```yml
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik:1.5.2
        name: traefik-ingress-lb
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8080
        securityContext:
          privileged: true
        args:
        - --api
        - --kubernetes
        - --logLevel=ERROR
        - --web.statistics
        - --web.statistics.recenterrors=15
```
Statistics records do not appear on UI

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
