### ISSUE TITLE
Response headers from backend are dropped when custom error page feature is enabled

### ISSUE THREAD

**Issue by glennschmidt** [containous/traefik#2939]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configure a frontend which has a custom error page handler. eg:
```toml
[frontends]
  [frontends.test1]
  backend = "test1"
  [frontends.test1.errors]
    [frontends.test1.errors.upstream]
    status = ["502-504"]
    backend = "errorhandler"
    query = "/{status}.html"
  [frontends.test1.routes.default]
  rule = "Host:www.myapp.com"
```

Make a HTTP request to the new frontend (a valid one which won't trigger the error handler).

### What did you expect to see?

The request is proxied through to the backend, and the backend's response is forwarded to the client as normal.

### What did you see instead?

The backend's response is forwarded to the client, but all HTTP response headers are missing other than `Content-Type` and `Content-Length`. For example, `Set-Cookie` is missing, even though the backend is sending it.

Note that this problem affects **normal, non-error responses**. But the problem goes away if the error page feature is disabled.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### Possible cause

Without being an expert on the codebase, i'm suspicious of this code in `middlewares/error_pages.go`:

```go
func (ep *ErrorPagesHandler) ServeHTTP(w http.ResponseWriter, req *http.Request, next http.HandlerFunc) {
	recorder := newRetryResponseRecorder(w)

	next.ServeHTTP(recorder, req)

	w.WriteHeader(recorder.GetCode())
	//check the recorder code against the configured http status code ranges
	___SNIP___

	//did not catch a configured status code so proceed with the request
	utils.CopyHeaders(w.Header(), recorder.Header())
	w.Write(recorder.GetBody().Bytes())
}
```

I notice that `w.WriteHeader` is being called prior to `utils.CopyHeaders`.
