### ISSUE TITLE
Whitelisting with unexpected X-FORWARDED-FOR / X-REAL-IP

### ISSUE THREAD

**Issue by fragtom** [containous/traefik#2942]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?

Setup different stacks with traefik controller to manage ingresses. Tried out to use whitelisting 

```yml
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/whitelist-source-range: my-ip/32
    creationTimestamp: 2018-02-27T11:40:00Z
    generation: 2
    name: fragtom-protected
    namespace: fragtom
```

will get always "Forbidden"... 

```console
$ curl https://echo.fragtom.baz/
CLIENT VALUES:
client_address=10.244.115.4
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://echo.fragtom.baz:8080/
...
HEADERS RECEIVED:
accept=*/*
accept-encoding=gzip
host=echo.fragtom.baz
user-agent=curl/7.47.0
x-forwarded-for=10.244.60.0
x-forwarded-host=echo.fragtom.baz
x-forwarded-port=80
x-forwarded-proto=http
x-forwarded-server=traefik-with-ui-traefik-6f4b95d74d-rds99
x-real-ip=10.244.60.0
BODY:

 ```

### What did you expect to see?
```X-FORWARDED-FOR``` and ```X-REAL-IP``` of my external IP.. 

I see in Kibana log 2 IPs in ```X-FORWARDED-FOR``` - first one is correct and would to use.. 2nd ip is 10.244.60.0 - internal k8s IP.. 

### What did you see instead?
In logs (kibana) of our services we could see, in ```X-FORWARDED-FOR```  2 IPs are collected, 1 origin id, which we would use for whitelist.. and the 2nd IP of 10.244.60.0 (kubernetes internal ip)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik/stable v1.5.1 / cancoillotte
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.forwardedHeaders]
        trustedIPs = ["172.31.0.0/20", "172.31.16.0/20","127.0.0.1"]
        [entryPoints.http.proxyProtocol]
        trustedIPs = ["172.31.0.0/20", "172.31.16.0/20","127.0.0.1"]
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
    [kubernetes]
    [web]
    address = ":8080"
      [web.auth.basic]
        users = ["traefik:secret",]
```

Tested with AWS ELB and proxyProtocol.. also on a HAProxy .. standard configuration.

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
