### ISSUE TITLE
Wrong documentation example for labels and compose 3

### ISSUE THREAD

**Issue by sbrattla** [containous/traefik#2947]
This issue relates to https://docs.traefik.io/configuration/backends/docker/#labels-overriding-default-behaviour

What I see:
```
version: "3"
services:
  whoami:
    deploy:
      labels:
        traefik.docker.network: traefik
```
What I expect to see:

```
version: "3"
services:
  whoami:
    deploy:
      labels:
        traefik.docker.network=traefik
```

The format for labels is `key=value`, and not `key:value`. This works when I deploy a stack.

**Comment by traefiker** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

    <details>

    ![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
    ![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

    </details>
    <br>

    Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by sbrattla** [comment]
Please, with all respect for the time and effort you put into making this product : have you read the issue description? 

It's a documentation correction, and it's simple. There's a `:` character which needs to be replaced with an `=` character. 

I've made a little modification to the issue, but I am not going to take the time to follow the template as 90% of the details in that template would be meaningless for this issue.

**Comment by mmatur** [comment]
@sbrattla 

```yaml
version: "3"
services:
  whoami:
    deploy:
      labels:
        traefik.docker.network: traefik
```
This is a valid syntax please refer to [docker documentation](https://docs.docker.com/compose/compose-file/#labels-1)

I will close this issue because I think the question is answered
