### ISSUE TITLE
Traefik running in swarm / one container is not

### ISSUE THREAD

**Issue by mscbpi** [containous/traefik#2952]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
- Deployed Traefik inside swarm cluster 
- Service detected and f-e / b-e created for swarm services (`docker stack deploy`) 
- Deployed container with `docker-compose up`, attached to traefik overlay network

### What did you expect to see?

- Front-end and back-end created for swarm services 👍 
- Front-end and back-end created for container 👎 

### What did you see instead?
- Only the services 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.6 / roquefort
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker version 17.06.0-ce, build 02c1d87

Traefik:

```yml
version: "3.1"

services:

  traefik:
    image: traefik:roquefort
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssl:/ssl:ro
    command:
      - --web
      - --docker
      - --docker.watch
      - --InsecureSkipVerify
      - --docker.swarmmode
      - --docker.domain=docker.localhost
      - --entrypoints=Name:http Address::80
      - --entryPoints=Name:https Address::443 TLS:/ssl/ssl.crt,/ssl/ssl.key
      - --defaultentrypoints=http,https
      - --accessLog
      - --accessLog.format=json
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
    logging:
       driver: fluentd
       options:
        tag: traefik


networks:
  traefik-net:
    external: true

volumes:
  ssl:
   external: true
```
My App:

```yml
version: '2.1'

volumes:
  db_data:
   driver: nutanix:latest
   driver_opts:
    sizeMb: 10000
  data:
   driver: nutanix:latest
   driver_opts:
    sizeMb: 10000
  etc:
   driver: nutanix:latest
   driver_opts:
    sizeMb: 1000
  grafana_data:
   driver: nutanix:latest
   driver_opts:
    sizeMb: 10000
  grafana_plugins:
   driver: nutanix:latest
   driver_opts:
    sizeMb: 10000

networks:
  opennms.net:
    driver: bridge
  traefik-net:
    external: true

services:
  database:
    container_name: opennms.psql
    image: postgres:9.6
    env_file:
      - .postgres.env
    networks:
      - opennms.net
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: fluentd
      options:
        tag: opennms-postgresql

  opennms:
    container_name: opennms.hzn.core.web
    image: opennms/horizon-core-web:21.0.3-1
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - opennms.net
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - etc:/opt/opennms/etc
      - data:/opennms-data
      - ./etc-overlay:/opt/opennms-etc-overlay
    command: ["-s"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp"]
      interval: 1m
      timeout: 5s
      retries: 50
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616"
      - "162:162/udp"
    logging:
      driver: fluentd
      options:
        tag: opennms

  grafana:
    image: grafana/grafana:4.6.3
    container_name: opennms.grafana
    env_file:
      - .grafana.env
    networks:
      - opennms.net
      - traefik-net
    expose:
      - "9000"
    labels:
      - "traefik.port=3000"
      - "traefik.backend=backend-grafana"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:monitoring"
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
    depends_on:
      opennms:
        condition: service_healthy
    volumes:
      - grafana_data:/var/lib/grafana:nocopy
      - grafana_plugins:/var/lib/grafana/plugins:nocopy
    ports:
      - "3000:3000"
    logging:
      driver: fluentd
      options:
        tag: opennms_grafana
```

Network works:
```console
$ docker exec -it opennms.grafana /bin/sh
# ping traefik
PING traefik (10.0.0.4): 56 data bytes
64 bytes from 10.0.0.4: icmp_seq=0 ttl=64 time=0.093 ms
64 bytes from 10.0.0.4: icmp_seq=1 ttl=64 time=0.097 ms
64 bytes from 10.0.0.4: icmp_seq=2 ttl=64 time=0.084 ms
64 bytes from 10.0.0.4: icmp_seq=3 ttl=64 time=0.072 ms
```

But no frontend/backend created.
