### ISSUE TITLE
Random values for Traefik metrics in cluster mode

### ISSUE THREAD

**Issue by frenchviking** [containous/traefik#2966]
### Do you want to request a *feature* or report a *bug*?
A bug

### What did you do?
Traefik configuration is store in Consul. Working in cluster mode with 3 traefik instances.
Configured traefik container service to expose metrics on port 8090. Port is published (--publish-add 8090:8080).
Metrics are availables.

### What did you expect to see?
Requesting from the docker host localhost:8090/metrics should only send incremental counters for metric traefik_requests_total.

### What did you see instead?
Sending multiple curl requests randomly report values from the 3 traefik instances (**supposed**).
This issue is true for every code, method and service.

$ curl -sS localhost:8090/metrics | grep "traefik_requests_total{code=\"200\",method=\"GET\",service=\"https\"}"
traefik_requests_total{code="200",method="GET",service="https"} **289957**
$ curl -sS localhost:8090/metrics | grep "traefik_requests_total{code=\"200\",method=\"GET\",service=\"https\"}"
traefik_requests_total{code="200",method="GET",service="https"} **289963**
$ curl -sS localhost:8090/metrics | grep "traefik_requests_total{code=\"200\",method=\"GET\",service=\"https\"}"
traefik_requests_total{code="200",method="GET",service="https"} **304457**
$ curl -sS localhost:8090/metrics | grep "traefik_requests_total{code=\"200\",method=\"GET\",service=\"https\"}"
traefik_requests_total{code="200",method="GET",service="https"} **235465**
$ curl -sS localhost:8090/metrics | grep "traefik_requests_total{code=\"200\",method=\"GET\",service=\"https\"}"
traefik_requests_total{code="200",method="GET",service="https"} **304460**

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v1.5.3-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
docker run --rm --network traefik-kv traefik:latest \
storeconfig --entrypoints=Name:http\ Address::80\ Redirect.EntryPoint:https \
--entrypoints=Name:https\ Address::443\ TLS --defaultentrypoints=http,https \
--acme --acme.storage=traefik/acme/account --acme.entryPoint=https \
--acme.httpChallenge.entryPoint=http --acme.OnHostRule=true --acme.onDemand=false \
--acme.email=myemail@mycompany.com --acme.logging=true --consul \
--consul.endpoint=admin_consul:8500 --consul.prefix=traefik --api --api.dashboard \
--api.statistics --api.statistics.recenterrors=10 --docker --docker.swarmmode \
--docker.domain=traefik --docker.watch --metrics --metrics.prometheus --loglevel WARN

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```
