### ISSUE TITLE
Enable graceful rotation of traefik servers behind a load balancer

### ISSUE THREAD

**Issue by ravilr** [containous/traefik#2969]
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
Do a rolling-upgrade of several traefik instances all receiving a constant stream of requests through an external load-balancer.

### What did you expect to see?

No requests failures to be observed.

### What did you see instead?

Observed few request failures.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.5.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

provider : Kubernetes  with lifecycle configuration defined
```toml
[lifeCycle]
  # Duration to keep accepting requests prior to initiating the graceful
  # termination period (as defined by the `graceTimeOut` option). This
  # option is meant to give downstream load-balancers sufficient time to
  # take Traefik out of rotation.
  requestAcceptGraceTimeout = "15s"

  # Duration to give active requests a chance to finish before Traefik stops.
  graceTimeOut = "15s"
```
### Feature request

Please see https://github.com/containous/traefik/issues/1942 for the detailed explanation of the feature and rationale.  
https://github.com/containous/traefik/pull/1971 added only `requestAcceptGraceTimeout`  without implementing item 1 : 'Toggle a pre-defined health check to artificially return unhealthy responses on SIGTERM during requestAcceptGraceTimout interval'.  https://github.com/containous/traefik/pull/2003 was closed. 

This issue is to enhance /ping handler to return non-200 response upon requestAcceptGraceTimeout initiation, iff it is set. 

/cc @timoreimann
