### ISSUE TITLE
Error writing response in retryResponseRecorder: http2: stream closed

### ISSUE THREAD

**Issue by ichasco** [containous/traefik#2979]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?
Nothing

### What did you expect to see?
Traefik working properly

### What did you see instead?
When traefik starts, it works for a few seconds and then it doesn't answer. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

accessLogsFile = "log/access.log"
logLevel = "INFO"
checkNewVersion = true
debug = false

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS11"
      cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA" ]


[acme]
  email = "info@example.com"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  acmeLogging = true
  onDemand = false
  OnHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

[retry]

################################################################
# Web configuration backend
################################################################

[web]
  address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "example.com"
  watch = true
  swarmmode = false

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```

proxy_1  | time="2018-03-07T13:58:42Z" level=warning msg="Renewed certificate storage error: error renewing certificate in datastore: tls: failed to find any PEM data in certificate input , retrying in 448.568635ms"
proxy_1  | time="2018-03-07T13:58:52Z" level=error msg="Error writing response in retryResponseRecorder: http2: stream closed"
proxy_1  | time="2018-03-07T13:59:42Z" level=info msg="Skipping same configuration for provider docker"


```
