### ISSUE TITLE
Incorrect frontend modifiers in Kubernetes

### ISSUE THREAD

**Issue by calummoore** [containous/traefik#2985]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Create an Ingress for Kubernetes and add a path prefix to the request using `ReplacePathRegex` rule - `"ReplacePathRegex: ^/(.*) /api/v1/$1"`.

I also tried using AddPrefix - `"AddPrefix: /api/v1`.

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-api
  namespace: graphlog
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: "ReplacePathRegex: ^/(.*) /api/v1/$1"
spec:
  rules:
  - host: api.graphlog.co
    http:
      paths:
      - path: /
        backend:
          serviceName: server-core
          servicePort: http
```

### What did you expect to see?

Forward all requests from `https://api.graphlog.co` to server-core with prefixed path `/api/v1`

`https://api.graphlog.co/events` -> `/api/v1/events`

### What did you see instead?

**`ReplacePathRegex: ^/(.*) /api/v1/$1`**
Additional `:/` is added to the end of the forwarded path:
`https://api.graphlog.co/events` -> `/api/v1/events:/`

**`AddPrefix: /api/v1`**
Additional `:/` is added between the prefix and the path
`/api/v1://events`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```
