### ISSUE TITLE
Health Check dont invalidate node

### ISSUE THREAD

**Issue by Escaflow** [containous/traefik#2994]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Create 3VM, 1 Swarm Master 2 Worker.

deploy a stack:
```
docker stack deploy swarm -c docker-stack.yml
```
curl the swarm:
```
watch -n 0,5 "curl -m 1 http://whoami.example.com/"
```

### What did you expect to see?
Traefik dropping the backends not in its net since it can not connect to them.

### What did you see instead?
Timeout on frontend since backed is not accessible.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": "0s",
  "GraceTimeOut": "0s"
 },
 "GraceTimeOut": "0s",
 "Debug": false,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "LogLevel": "ERROR",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http"
 ],
 "ProvidersThrottleDuration": "2s",
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": "0s",
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": "30s"
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Web": null,
 "Docker": null,
 "File": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": "//traefik.toml"
}
```
</details>

<br>

```yml
compose file:
version:             '3.4'
services:
  traefik:
    image:           'traefik:alpine'
    command:
      - '--api'
      - '--docker'
      - '--docker.swarmmode'
      - '--docker.domain=example.com'
      - '--docker.watch'
      - '--accesslogsfile=/dev/stdout'
      - '--logLevel=DEBUG'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/dev/null:/traefik.toml'
    networks:
     - 'swarm'
    ports:
      - '80:80'
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
         - 'traefik.frontend.rule=Host:traefik.example.com'
         - 'traefik.port=8080'
         - 'traefik.docker.network=swarm_swarm'

  whoami_swarm:
   image:          'emilevauge/whoami'
   networks:
    - 'swarm'
   deploy:
      labels:
       - 'traefik.backend=whoami'
       - 'traefik.frontend.rule=Host:whoami.example.com'
       - 'traefik.port=80'
       - 'traefik.docker.network=swarm_swarm'
      mode:        replicated
      replicas:    2
      placement:
        constraints:
         - node.role != manager

  whoami_flock:
   image:          'emilevauge/whoami'
   networks:
     - 'flock'
   deploy:
     labels:
      - 'traefik.backend=whoami'
      - 'traefik.frontend.rule=Host:whoami.example.com'
      - 'traefik.port=80'
      - 'traefik.docker.network=swarm_flock'
     mode:        replicated
     replicas:    2
     placement:
       constraints:
        - node.role != manager

networks:
  swarm:
    driver: overlay
    attachable: true
  flock:
    driver: overlay
    attachable: true
```
### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
time="2018-03-11T00:37:39Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://10.0.0.7:80, code: 500, Length: 21, duration: 997.072069ms" 
time="2018-03-11T00:37:39Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.0.0.7:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.55.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"whoami.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.255.0.70:44234","RequestURI":"/","TLS":null}" 
time="2018-03-11T00:37:39Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.0.0.7:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.55.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"whoami.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.255.0.70:44234","RequestURI":"/","TLS":null}" 
time="2018-03-11T00:37:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.55.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"whoami.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.255.0.70:44234","RequestURI":"/","TLS":null}" 
10.255.0.70 - - [11/Mar/2018:00:37:38 +0000] "GET / HTTP/1.1" 500 21 - "curl/7.55.1" 1094 "Host-whoami-hal-fritz-box-1" "http://10.0.0.7:80" 997ms
time="2018-03-11T00:37:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.55.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"whoami.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.255.0.70:44238","RequestURI":"/","TLS":null}" 
time="2018-03-11T00:37:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"User-Agent":["curl/7.55.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"whoami.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.255.0.70:44238","RequestURI":"/","TLS":null}" ForwardURL=http://10.0.1.9:80 

```

**Comment by brodkin** [comment]
I believe that Traefik exclusively uses Docker's HEALTHCHECK when determining container state in a Docker Swarm. Containers are added Traefik only when they pass a check and removed when they fail.

**Comment by Escaflow** [comment]
[From the docs:](https://docs.traefik.io/basics/#backends)

>  A health check can be configured in order to remove a backend from LB rotation as long as it keeps returning HTTP status codes other than 200 OK to HTTP GET requests periodically carried out by Traefik.
> The check is defined by a pathappended to the backend URL and an interval (given in a format understood by time.ParseDuration) specifying how often the health check should be executed (the default being 30 seconds). Each backend must respond to the health check within 5 seconds.
> By default, the port of the backend server is used, however, this may be overridden.
> 
> A recovering backend returning 200 OK responses again is being returned to the LB rotation pool.

You can read it as "default enabled" or "enable if needed" so i tried it with:
```
[backends]
  [backends.backend-whoami]
    [backends.backend-whoami.healthcheck]
    interval = "5s"
```
but no Cigar.

I only started with traefik a few days ago so it could just be a misunderstanding on my side or my inability to make sense from the docs.

**Comment by ldez** [comment]
@Escaflow you need to define a `path`:

```toml
[backends]
  [backends.backend1]
    [backends.backend1.healthcheck]
    path = "/health"
    interval = "10s"
```

https://docs.traefik.io/basics/#health-check

Without a path the health check doesn't work.

---

@brodkin Traefik doesn't use Docker's [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) but you can use the command `traefik healthcheck` in the Docker's [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck)
