### ISSUE TITLE
WebSocket 500

### ISSUE THREAD

**Issue by rawkode** [containous/traefik#2998]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Trying to get web-sockets to work.

### What did you expect to see?

Successful connection to a web-socket

### What did you see instead?

500 error

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
I've tried: 1.5.3, 1.5.1, 1.4.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
debug = true
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = false
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  compress = false
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
[acme]
email = "developers@gt8.online"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
[web]
address = ":8080"

```

Kubernetes Service:
```yml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: mindetic-api-ingress
  namespace: mindetic
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.priority: "1"
    traefik.frontend.entryPoints: "http,https"
    traefik.wss.protocol: "https"
spec:
  tls:
    - hosts:
        - api.mindetic.com
  rules:
  - host: api.mindetic.com
    http:
      paths:
        - path: /socket
          backend:
            serviceName: thought-service-api
            servicePort: 4000
        - backend:
            serviceName: api-gateway
            servicePort: 4000

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/socket","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL=http://10.52.28.14:4000 Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/socket","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.52.28.14:4000","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/forward/websocket: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.52.28.14:4000","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/forward/websocket: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.52.28.14:4000","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.52.28.14:4000","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
time="2018-03-11T23:03:03Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/socket","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Sec-Websocket-Key":["0Fy0MWqNarLirqZEuUY5Lw=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"]},"ContentLength":0,"TransferEncoding":null,"Host":"api.mindetic.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.52.28.1:38782","RequestURI":"/socket","TLS":null}" 
```
