### ISSUE TITLE
Option to use YAML instead of TOML for configuration

### ISSUE THREAD

**Issue by gaui** [containous/traefik#2999]
### Do you want to request a *feature* or report a *bug*?

feature

### Description

YAML is becoming the industry standard configuration format. Docker uses it for Compose/Stack, Kubernetes, GitLab CI, Travis CI, Drone CI, Google App Engine, etc. Wouldn't it be ok to support both configuration formats, for those who prefer YAML instead of TOML.

Let's take the following example, a configuration in both TOML and YAML [from here](https://docs.traefik.io/configuration/entrypoints/#toml). In my opinion YAML is more readable, better structured (with indent as context) and with less noise (less repetitions of parent elements).

#### TOML

```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"
    whitelistSourceRange = ["10.42.0.0/16", "152.89.1.33/32", "afed:be44::/16"]
    compress = true

    [entryPoints.http.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
       ]
      [[entryPoints.http.tls.certificates]]
        certFile = "path/to/my.cert"
        keyFile = "path/to/my.key"
      [[entryPoints.http.tls.certificates]]
        certFile = "path/to/other.cert"
        keyFile = "path/to/other.key"
      # ...
      [entryPoints.http.tls.clientCA]
        files = ["path/to/ca1.crt", "path/to/ca2.crt"]
        optional = false

    [entryPoints.http.redirect]
      entryPoint = "https"
      regex = "^http://localhost/(.*)"
      replacement = "http://mydomain/$1"

    [entryPoints.http.auth]
      headerField = "X-WebAuth-User"
      [entryPoints.http.auth.basic]
        users = [
          "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/",
          "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0",
        ]
        usersFile = "/path/to/.htpasswd"
      [entryPoints.http.auth.digest]
        users = [
          "test:traefik:a2688e031edb4be6a3797f3882655c05",
          "test2:traefik:518845800f9e2bfb1f1f740ec24f074e",
        ]
        usersFile = "/path/to/.htdigest"
      [entryPoints.http.auth.forward]
        address = "https://authserver.com/auth"
        trustForwardHeader = true
        [entryPoints.http.auth.forward.tls]
          ca =  [ "path/to/local.crt"]
          caOptional = true
          cert = "path/to/foo.cert"
          key = "path/to/foo.key"
          insecureSkipVerify = true

    [entryPoints.http.proxyProtocol]
      insecure = true
      trustedIPs = ["10.10.10.1", "10.10.10.2"]

    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["10.10.10.1", "10.10.10.2"]
```

#### YAML

```yaml
entryPoints:
  http:
    address: ':80'
    whitelistSourceRange:
      - 10.42.0.0/16
      - 152.89.1.33/32
      - 'afed:be44::/16'
    compress: true
    tls:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
      certificates:
        - certFile: path/to/my.cert
          keyFile: path/to/my.key
        - certFile: path/to/other.cert
          keyFile: path/to/other.key
      clientCA:
        files:
          - path/to/ca1.crt
          - path/to/ca2.crt
        optional: false
    redirect:
      entryPoint: https
      regex: '^http://localhost/(.*)'
      replacement: 'http://mydomain/$1'
    auth:
      headerField: X-WebAuth-User
      basic:
        users:
          - 'test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/'
          - 'test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0'
        usersFile: /path/to/.htpasswd
      digest:
        users:
          - 'test:traefik:a2688e031edb4be6a3797f3882655c05'
          - 'test2:traefik:518845800f9e2bfb1f1f740ec24f074e'
        usersFile: /path/to/.htdigest
      forward:
        address: 'https://authserver.com/auth'
        trustForwardHeader: true
        tls:
          ca:
            - path/to/local.crt
          caOptional: true
          cert: path/to/foo.cert
          key: path/to/foo.key
          insecureSkipVerify: true
    proxyProtocol:
      insecure: true
      trustedIPs:
        - 10.10.10.1
        - 10.10.10.2
    forwardedHeaders:
      trustedIPs:
        - 10.10.10.1
        - 10.10.10.2
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```
