### ISSUE TITLE
Allow frontend routes to be treated separately instead of combined with AND

### ISSUE THREAD

**Issue by kinghuang** [containous/traefik#3026]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Frontends currently combine rules from all routes together using **AND**, as documented in [Combining multiple rules](https://docs.traefik.io/basics/#combining-multiple-rules). I find this counter-intuitive and forces the use of multiple front-ends to match multiple distinct routes that otherwise share the same frontend configuration.

For example, the following config defines two routes that are intended to be evaluated separately, not combined together.

```toml
[frontends]
  [frontends.frontend1]
  entrypoints = ["http", "https"]
  backend = "oi-api"
    [frontends.frontend1.headers.customresponseheaders]
    X-Custom-Response-Header = "True"
    [frontends.frontend1.headers.customrequestheaders]
    X-Script-Name = "test"
    [frontends.frontend1.routes.route-1]
    rule = "Host:host1;PathPrefixStrip:/cheese;AddPrefix:/example"
    [frontends.frontend1.routes.route-2]
    rule = "Host:host2;PathPrefix:/mouse"
```

The way it's displayed in the UI gives the impression that `http://host1/cheese` and `http://host2/mouse` would both work. However, the two routes are and-ed together, and can't match anything in this example.

![screen shot 2018-03-15 at 3 42 37 pm](https://user-images.githubusercontent.com/27340/37492623-ac9e410e-2867-11e8-8cc2-45f6cd1eb75f.png)

The routes have to be broken up into two separate frontends, resulting in a lot of duplication in config.

```toml
[frontends]
  [frontends.frontend1]
  entrypoints = ["http", "https"]
  backend = "oi-api"
    [frontends.frontend1.headers.customresponseheaders]
    X-Custom-Response-Header = "True"
    [frontends.frontend1.headers.customrequestheaders]
    X-Script-Name = "test"
    [frontends.frontend1.routes.route-1]
    rule = "Host:host1;PathPrefixStrip:/cheese;AddPrefix:/example"

  [frontends.frontend2]
  entrypoints = ["http", "https"]
  backend = "oi-api"
    [frontends.frontend2.headers.customresponseheaders]
    X-Custom-Response-Header = "True"
    [frontends.frontend2.headers.customrequestheaders]
    X-Script-Name = "test"
    [frontends.frontend2.routes.route-2]
    rule = "Host:host2;PathPrefix:/mouse"
```

### What did you expect to see?

I would like a way to configure a frontend to treat the rules in each route separately (basically **or** instead of **and**).

### What did you see instead?

Traefik combines rules from multiple routes together using **and**, [as documented](https://docs.traefik.io/basics/#combining-multiple-rules).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See static configuration above.

### If applicable, please paste the log output in debug mode (`--debug` switch)

Not applicable.

### Related issues

#2189
