### ISSUE TITLE
Header seems missing when proxying Transmission

### ISSUE THREAD

**Issue by devster31** [containous/traefik#3029]
### Do you want to request a *feature* or report a *bug*?

Bug I presume.

### What did you do?

I'm trying to proxy `transmission`.

### What did you expect to see?

The `transmission` WEB UI.

### What did you see instead?

I got back a webpage with the following:

> 409: Conflict
> Your request had an invalid session-id header.
> 
> To fix this, follow these steps:
> 
> 1. When reading a response, get its X-Transmission-Session-Id header and remember it
> 2. Add the updated header to your outgoing requests
> 3. When you get this 409 error message, resend your request with the updated header
> 
> This requirement has been added to help prevent [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks.
> `X-Transmission-Session-Id: <SessionID>`

I'm a bit stumped, where could this come from?

### Output of `traefik version`:

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: '3.3'
services:
  traefik:
    command:
      # - --debug
      - --loglevel=INFO
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 Compress:true
          TLS:/certs/${DOMAIN}.crt,/certs/${DOMAIN}.key TLS.MinVersion:VersionTLS12
          TLS.CipherSuites:["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"]
      - --entryPoints=Name:api Address::8080
      - --api.entrypoint=api
      - --acme=true
      - --acme.acmelogging=true
      - --acme.email=${EMAIL}
      - --acme.domains=${DOMAIN}
      - --acme.storage=/etc/traefik/acme.json
      - --acme.entrypoint=https
      - --acme.onhostrule=true
      - --acme.dnschallenge=true
      - --acme.dnschallenge.provider=cloudflare
      - --acme.tlsconfig=true
      - --docker=true
      - --docker.debugloggeneratedtemplate=true
      - --docker.domain='${DOMAIN}'
      - --docker.exposedbydefault=false
      - --docker.usebindportip=true
      - --docker.watch=true
      - --file=true
      - --file.filename=/etc/traefik/external.toml
      - --file.watch=true
```
And the `external.toml` file:
```toml
[backends.transmission.servers.server0]
url = "http://<username>:<password>@<docker_IP>:9091"

[frontends]
  [frontends.transmission]
  backend = "transmission"
  passHostHeader = true
    [frontends.transmission.routes.route1]
    rule = "Host:alioth.ovh,rpi3.local;PathPrefix:/transmission,/transmission/"
```
