### ISSUE TITLE
docker-compose 1.17.0 not working with traefik examples

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [containous/traefik#3030]
### Do you want to request a *feature* or report a *bug*?
*Bug* - `docker-compose up` (version 1.17.0) not working with examples label [compose-traefik.yml](https://github.com/containous/traefik/blob/master/examples/compose-traefik.yml)

### What did you do?
I just created and docker-compose following traefik documentation and I ran it. I didn't add any configraution file.

### What did you expect to see?
`docker-compose up` needs to run

### What did you see instead?
`docker-compose up` threw an error.

```
ERROR: for libriy_redis_monitor_1  dictionary update sequence element #0 has length 27; 2 is required
ERROR: for redis_monitor  dictionary update sequence element #0 has length 27; 2 is required
```
### Output of `traefik version`:
traefik:alpine (1.5.4) as a docker container

### What is your environment & configuration?
I just used default settings. I didn't add anything into container.

### If applicable, please paste the log output in debug mode
```
redis_monitor:
  depends_on:
    - redis
  image: vieux/redmon
  command: "redmon --redis redis://redis:6379"
  labels:
    - "proxy.backend=redis_monitor"
    - "proxy.frontend.rule=Host:redis_monitor.docker.localhost"
  networks:
    - internal
    - proxy
```

Those outputs from this part of `docker-compose.yml`

```
ERROR: for libriy_redis_monitor_1  dictionary update sequence element #0 has length 27; 2 is required
ERROR: for redis_monitor  dictionary update sequence element #0 has length 27; 2 is required
```

### Solution from person who getting this error
[solution](https://github.com/docker/compose/issues/5336#issuecomment-344823678)

I found this solution and I solved. Simply it just delete `-` beginning of the label. 

### Comments from person who getting this error
Thank you for this awesome project. I just wanna understand the structure of traefik so created an docker-compose by following examples/compose-traefic.yml

Also, I would like to share to you an example usage for traefik. If you check my [fork](https://github.com/BerkhanBerkdemir/traefik/blob/BerkhanBerkdemir-examples-compose/examples/compose-traefik.yml) you can see the fix.

Thank you again.
