### ISSUE TITLE
Very high response times using traefik as kubernetes ingress controller with many hosts

### ISSUE THREAD

**Issue by stefanobaldo** [containous/traefik#3049]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Created 1,000 ingresses in a kubernetes cluster using traefik as the ingress controller - all ingresses has a single host rule pointing to a very simple test backend ([emilevauge/whoamI](https://github.com/emilevauge/whoamI)). Why did I do that? I did not create 1 single ingress with 1,000 rules because I need to add a custom header for each host, so I have to use `ingress.kubernetes.io/custom-request-headers` that is general Ingress annotation, but the problem also occurs if I create a single ingress with 1,000 rules.

### What did you expect to see?
A reasonable response time when I make subsequent requests to one of the hosts.

### What did you see instead?
If I make 100 subsequent requests, for example, almost all of them will have a normal response time like 30ms, but 2 or 3 will always have a very high response time like 3000ms or even 5000ms. This happens only when I create a lot of ingresses (1000 in this case), or even if I create one single ingress with 1000 rules.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.5.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: ssl
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        securityContext:
          privileged: true
        args:
        - -d
        - --api
        - --kubernetes
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: ssl
    - protocol: TCP
      port: 8080
      name: admin
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: host1.mydomain.com
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/custom-request-headers: X-CustomHeader:1
spec:
  rules:
  - host: host1.mydomain.com
    http:
      paths:
      - backend:
          serviceName: whoami-app
          servicePort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: host2.mydomain.com
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/custom-request-headers: X-CustomHeader:2
spec:
  rules:
  - host: host2.mydomain.com
    http:
      paths:
      - backend:
          serviceName: whoami-app
          servicePort: 8000
---
[+998 ingress entries]
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2018-03-19T19:12:07Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-03-19T19:12:07Z" level=debug msg="Could not load traefik.frontend.entryPoints annotation, skipping..."
time="2018-03-19T19:12:07Z" level=debug msg="Could not load ingress.kubernetes.io/whitelist-source-range annotation, skipping..."
time="2018-03-19T19:12:07Z" level=debug msg="Could not load ingress.kubernetes.io/allowed-hosts annotation, skipping..."
time="2018-03-19T19:12:07Z" level=debug msg="Could not load ingress.kubernetes.io/proxy-headers annotation, skipping..."
[+999 "Could not load..." entries]
time="2018-03-19T19:12:07Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
```
