### ISSUE TITLE
passTLSCert passes server instead of client certificate to the backend

### ISSUE THREAD

**Issue by steffkes** [containous/traefik#3052]
given that [the docs explain](https://docs.traefik.io/basics/) that

> You can also optionally enable `passTLSCert` to forward TLS Client certificates to the backend.

i'm trying to use traefik as ssl-proxy and a simple golang https server as dummy-endpoint to demonstrate the problem. as far as i'm aware there is no other tool that allows passing an entire client certificate forward .. i'm not even sure this could work as advertised?

i've created my own ca, a server and a client certificate signed from it (nothing special) - the whole thing is running in a docker compose environment:

```yaml 
version: '3.3'
services:

  proxy:
    image: traefik:1.5.4-alpine
    volumes:
      - .:/app
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
    ports:
      - '127.0.0.1:5443:443'
      - '127.0.0.1:5088:8080'

  server:
    image: golang:1.10.0-alpine3.7
    command: sh -c 'go get -d -v ./... && go install -v ./... && app'
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
      - .:/app
    ports:
      - '127.0.0.1:5447:8080'
```

the traefik configuration in question:

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["https"]
debug = true
RootCAs = ["/app/certs/ca/crt.pem"]

[api]
  [api.statistics]

[file]
  watch = true

[entryPoints]

  [entryPoints.https]
  address = ":443"

    [entryPoints.https.tls]
      
      [entryPoints.https.tls.ClientCA]
      files = ["/app/certs/ca/crt.pem"]
      optional = false

      [[entryPoints.https.tls.certificates]]
      certFile = "/app/certs/server/crt.pem"
      keyFile = "/app/certs/server/key.pem"

[frontends]

  [frontends.frontend-server]
    backend = "backend-server"
    passHostHeader = true
    passTLSCert = true

    [frontends.frontend-server.routes]
      [frontends.frontend-server.routes.route0]
        rule = "Host: server"

[backends]

  [backends.backend-server]
    [backends.backend-server.servers]
      [backends.backend-server.servers.server0]
        url = "https://server:8080"
``` 
the dummy endpoint's code:

```go
package main

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io/ioutil"
	"net/http"
)

func main() {
	caCert, _ := ioutil.ReadFile("/app/certs/ca/crt.pem")
	caPool := x509.NewCertPool()
	caPool.AppendCertsFromPEM(caCert)

	tlsConfig := &tls.Config{
		ClientAuth: tls.RequireAndVerifyClientCert,
		ClientCAs:  caPool,
	}
	tlsConfig.BuildNameToCertificate()

	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		fmt.Fprintf(
			w,
			"cert/subject: %v (%d)\n",
			req.TLS.PeerCertificates[0].Subject,
			req.TLS.PeerCertificates[0].SerialNumber,
		)
	})

	httpServer := &http.Server{
		Addr:      ":8080",
		TLSConfig: tlsConfig,
	}

	httpServer.ListenAndServeTLS(
		"/app/certs/server/crt.pem",
		"/app/certs/server/key.pem",
	)
}
```

and the actual testing:

request with the server certificate (for reference) directly towards the dummy endpoint:
```bash
$ curl https://localhost:5447 \
       --cacert certs/ca/crt.pem \
       --cert certs/server/crt.pem --key certs/server/key.pem
cert/subject: CN=server,OU=my-ou,O=my-o,L=my-l,ST=my-st,C=my-c (26161435)
```

using the client certificate which is what we really wanted ..
```bash
$ curl https://localhost:5447 \
       --cacert certs/ca/crt.pem \
       --cert certs/client1/crt.pem --key certs/client1/key.pem
cert/subject: CN=client1,OU=my-ou,O=my-o,L=my-l,ST=my-st,C=my-c (26161436)
```

trying the same client certificate via traefik shows the configured server certificate on the backend:
```bash
$ curl https://localhost:5443 -H 'Host: server' \
       --cacert certs/ca/crt.pem \
       --cert certs/client1/crt.pem --key certs/client1/key.pem
cert/subject: CN=server,OU=my-ou,O=my-o,L=my-l,ST=my-st,C=my-c (26161435)
``` 
i've checked the PR #2324 where this feature originated from, walked through the relevant code path and i wasn't able to see the section where we're actually accessing the clients certificate to pipe it forward. additionally i didn't find a test case which verifies this feature (all test-backends i've found are http based only), so i'm not even sure that ever worked?

or am i simple misreading the docs and therefore expecting something completely different?
