### ISSUE TITLE
Error 500 for parallel requests via traefik.

### ISSUE THREAD

**Issue by unglaublicherdude** [containous/traefik#3054]
report a *bug*

### What did you do?

We did parallel requests against a service in our swarm - with a c# application and parallel foreach - when we set the parallelism to 3 we encounter several error 500. The same script works sending the request to the service directly - via exposed port on the servers it runs on.

The URL we request is a download URL for files that are in average 2 MB big.

The service itself does not answer with an error 500 but with the file contend and the status code 200.

### What did you expect to see?

The file content.

### What did you see instead?

Error 500 - Internal Server Error

### What version of Traefik are you using?

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I already "played" with some values like the timeouts. It did not change the behaviour.

```toml
defaultEntryPoints = ["http","https"]
checkNewVersion = false
ProvidersThrottleDuration = 5
MaxIdleConnsPerHost = 400
RootCAs = [ "/usr/local/share/ca-certificates/*[munched]*.crt" ]

[traefikLog]
  filePath = "/dev/stdout"
  format   = "json"

[accessLog]
  filePath = "/dev/stdout"
  format = "json"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/*[munched]*.crt"
      KeyFile = "/etc/ssl/*[munched]*.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
swarmmode = true
domain = "*[munched]*"
watch = true

[web]
address = ":8080"

[lifeCycle]
requestAcceptGraceTimeout = "60s"
graceTimeOut = "720s"

[respondingTimeouts]
readTimeout = "60s"
writeTimeout = "60s"
idleTimeout = "720s"

[forwardingTimeouts]
dialTimeout = "360s"
```

Our Docker swarm has 15 nodes with 3 of them are manager nodes.

<details>
<summary>Stack-File:</summary>

```yml
version: '3'
services: 
  traefik:
    image: *[munched]*
    command: --configfile=/etc/traefik/traefik.toml
    networks: 
     - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
      labels:
       - traefik.port=8080
       - traefik.docker.network=atam_ata-management
      placement:
        constraints:
         - node.role == manager
networks:
  default:
  traefik:
    external:
      name: atam_ata-management
```

</details>

<details>
<summary>Stack of the Service:</summary>

```yml
version: '3'
services:
  *[munched]*:
    image: *[munched]*
    networks:
     traefik:
     default:
       aliases:
        - *[munched]*
    deploy:
      labels:
        traefik.port: 8080
        traefik.backend.maxconn.amount: 200
        traefik.backend.maxconn.extractorfunc: client.ip	
        traefik.docker.network: atam_ata-management
        traefik.backend.loadbalancer.swarm: "true"
        traefik.frontend.passHostHeader: "true"
      mode: replicated
      replicas: 12
      placement:
        constraints:
         - node.labels.fileserver == true
         - node.labels.os == linux
    volumes:
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
     - *[munched]*
networks:
  default:
  traefik:
    external:
      name: atam_ata-management
```

</details>

<details>
<summary>Docker inspect of the traefik overlay network:</summary>

```json
[
    {
        "Name": "atam_ata-management",
        "Id": "60s7dkowl737sby957jlb1w44",
        "Created": "2018-03-16T17:40:53.928194481+01:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "82be609085dd3149b3b7a3831200444c55333d565d0a8cb9988b05c1b0befbd5": {
                "Name": "atam_traefik.mzjsw8wtkb0clj3txi2b0q1dw.q0n1e7zqoe3u4md4djy8x9bpy",
                "EndpointID": "198f6f2207a7d31f5ec268816a83c44df4e234e2d44eb6b449f1fec59f076ceb",
                "MacAddress": "02:42:0a:00:00:ed",
                "IPv4Address": "10.0.0.237/24",
                "IPv6Address": ""
            },
            "b1b46b795431df88d4bca805613d666bd68ee3da709a797e5e809bdc5f108ace": {
                "Name": "swarm_weave.mzjsw8wtkb0clj3txi2b0q1dw.iotwqg1jngysxz5u02ieny8am",
                "EndpointID": "a9c624767ea366d8794f569fbf8cb41743ee583c06fa42ddf8fee5deaa7c2b6b",
                "MacAddress": "02:42:0a:00:00:29",
                "IPv4Address": "10.0.0.41/24",
                "IPv6Address": ""
            },
            "fbfc766913a94078bdd3562a6268ff3ccef94798260f9e673aaeeedb8004f1d0": {
                "Name": "swarm_portainer.1.oeijbavgsrujkq8uuw2bkb7wy",
                "EndpointID": "c88c13eff2aa43a93b3789c06ea8e8009d2ff7b227e814b46304863a069a49a0",
                "MacAddress": "02:42:0a:00:00:32",
                "IPv4Address": "10.0.0.50/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "e015486d9ae5",
                "IP": "10.10.11.108"
            },
            {
                "Name": "8093bbbb968a",
                "IP": "10.10.12.73"
            },
            {
                "Name": "ff1d19a9f660",
                "IP": "10.131.4.32"
            },
            {
                "Name": "48206a080716",
                "IP": "10.10.11.113"
            },
            {
                "Name": "de463f919f9b",
                "IP": "10.131.4.33"
            },
            {
                "Name": "4c4a8e644aa5",
                "IP": "10.10.11.107"
            },
            {
                "Name": "1c3336e193cf",
                "IP": "10.131.4.35"
            },
            {
                "Name": "bcff64b059df",
                "IP": "10.10.11.114"
            },
            {
                "Name": "b11eb0d288b9",
                "IP": "10.131.4.31"
            },
            {
                "Name": "91d9aabbff9e",
                "IP": "10.10.12.72"
            },
            {
                "Name": "2bd47092ad8e",
                "IP": "10.131.4.34"
            },
            {
                "Name": "1d204c14ce4b",
                "IP": "10.10.11.66"
            },
            {
                "Name": "799d3a87e548",
                "IP": "10.10.11.106"
            }
        ]
    }
]
```

</details>

### If applicable, please paste the log output in debug mode (`--debug` switch)

```json
{"BackendAddr":"10.0.0.24:8080","BackendName":"*[munched]*","BackendURL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.0.0.24:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"ClientAddr":"10.255.0.10:58811","ClientHost":"10.255.0.10","ClientPort":"58811","ClientUsername":"-","DownstreamContentSize":21,"DownstreamStatus":500,"DownstreamStatusLine":"500 Internal Server Error","traefikDuration":65840578,"FrontendName":"*[munched]*","OriginContentSize":21,"OriginDuration":65512033,"OriginStatus":500,"OriginStatusLine":"500 Internal Server Error","Overhead":328545,"RequestAddr":"*[munched]*","RequestContentSize":0,"RequestCount":351,"RequestHost":"*[munched]*","RequestLine":"GET *[munched]* HTTP/1.1","RequestMethod":"GET","RequestPath":"/d/472CEA45EE404E22191E52FC6A620D62C06572BCB2B8B0DDEF0517EE5A87E426","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2018-03-20T10:01:29.980041729Z","StartUTC":"2018-03-20T10:01:29.980041729Z","traefiklog":"info","msg":"","time":"2018-03-20T10:01:30Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/d/472CEA45EE404E22191E52FC6A620D62C06572BCB2B8B0DDEF0517EE5A87E426\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"*[munched]*\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.10:58811\",\"RequestURI\":\"/d/472CEA45EE404E22191E52FC6A620D62C06572BCB2B8B0DDEF0517EE5A87E426\",\"TLS\":null}","traefiklog":"debug","msg":"vulcand/oxy/roundrobin/rr: competed ServeHttp on request","time":"2018-03-20T10:01:30Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.0.24:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"*[munched]*\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.10:58811\",\"RequestURI\":\"/d/472CEA45EE404E22191E52FC6A620D62C06572BCB2B8B0DDEF0517EE5A87E426\",\"TLS\":null}","traefiklog":"debug","msg":"vulcand/oxy/forward/http: completed ServeHttp on request","time":"2018-03-20T10:01:30Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.0.24:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"*[munched]*\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.10:58811\",\"RequestURI\":\"/d/472CEA45EE404E22191E52FC6A620D62C06572BCB2B8B0DDEF0517EE5A87E426\",\"TLS\":null}","traefiklog":"debug","msg":"vulcand/oxy/forward: completed ServeHttp on request","time":"2018-03-20T10:01:30Z"}
```

If you need more information just ask.
