### ISSUE TITLE
Certificates are not issuing when ingress is hot altered 

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#3068]
### Do you want to request a *feature* or report a *bug*?

/feature
/bug

### What did you do?

Well. I have deployed a web site. Traefik has successfully  issued a certificate. Then I did
```kubectl edit ingress .....```
and added new hostname to ingress. Pod did not restart. Traefik does not attempt to issue certificate for freshly added hostname UNTIL I restarted the pod (```kubectl delete pod ....```). I was managed to reproduce the issue once again after that

### What did you expect to see?

Certificates issued regardless of pod restart

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- kubernetes 1.9
- Traefik in cluster mode based on etcd

**Comment by mmatur** [comment]
Hi @tiukhtinvladimir,

Thanks for your interest on Træfik

Could you please provide us more information about your configuration, like:

- ingress
- DEBUG log
- Træfik configuration

**Comment by tiukhtinvladimir** [comment]
Hi @mmatur 
Well, all traefik configuration is in etcd. I can provide some keys, but I don't know how to dump it all. What about ingress - initially it looked like
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: nexus.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nexus
              servicePort: frontend
    - host: registry.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nexus
              servicePort: registry

```
Then using ```kubectl edit ingress ....``` I altered it to:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: nexus.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nexus
              servicePort: frontend
    - host: npm-proxy.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nexus
              servicePort: frontend
    - host: registry.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nexus
              servicePort: registry
```
So I have added new hostname. And traefik did not try to issue a certificate for this new host until pod being restarted
