### ISSUE TITLE
Error while using Safari on OSX 10.11.3 (HTTP/2)

### ISSUE THREAD

**Issue by zeroware** [containous/traefik#307]
I'm using Safari on OSX 10.11.3.
I believe this version of Safari is using HTTP/2.
traefik tries to send HTTP/2 request to my backend which is not HTTP/2 compatible.

Here is the error from traefik log : 

`Error copying upstream response Body: http2: stream closed`

Is is possible to transform HTTP/2 request into HTTP 1.1 ?
Or maybe disable HTTP/2 entirely ?

**Comment by emilevauge** [comment]
Hi @zeroware, do you have SSL on your backend ?

**Comment by zeroware** [comment]
Hello @emilevauge ,
I don't have SSL on my backend (nginx).

Here is my traefik.toml

```toml

accessLogsFile = "/var/log/traefik-access.log"
logLevel = "INFO"
defaultEntryPoints = ["https", "http"]

[acme]

email = "************"
storageFile = "acme.json"
entryPoint = "https"
onDemand = true

[[acme.domains]]
  main = "domain.com"
  sans = ["cloud.domain.com"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]

filename = "rules.toml"
watch = true

```

And here is my `rules.toml`

```toml
[backends]
  [backends.owncloud]
    [backends.owncloud.LoadBalancer]
      method = "drr"
    [backends.owncloud.servers.server1]
    url = "http://127.0.0.1:8000"
    weight = 1

[frontends]
  [frontends.owncloud]
  backend = "owncloud"
  passHostHeader = true
    [frontends.owncloud.routes.test_1]
    rule = "Host: cloud.domain.com"
```
