### ISSUE TITLE
Forwarding to ExternalNames ignores port

### ISSUE THREAD

**Issue by joshuacox** [containous/traefik#3071]
I have sought support on this issue, on [stackoverflow](https://stackoverflow.com/questions/49431284/forward-to-externalname-with-traefik-in-kubernetes-as-the-documenation-suggests/49434310?noredirect=1#comment85878366_49434310) and the [slack channel](https://traefik.slack.com/archives/C0CDT22PJ/p1521762460000087)

However, this appears to be a bug. 

### What did you do?

Added traefik to a cluster:
```console
kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-ds.yaml
```

And set an ingress for an externalname with an alternate port:
```yml
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-exp
  namespace: kube-system
spec:
  type: ExternalName
  ports:
  - name: app-port
    port: 4080
  externalName: 10.33.33.87
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-exp
  namespace: kube-system
  annotations:
    traefik.frontend.passHostHeader: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gitlab.example.com
    http:
      paths:
      - backend:
          serviceName: gitlab-exp
          servicePort: app-port
```

### What did you expect to see?

Traefik serving the externalname from 4080 on it's port 80

### What did you see instead?

Traefik serving 10.33.33.87's port 80 and not port 4080

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.4
from the latest docker image:
```
traefik                                                  latest              fde722950ccf        7 days ago          49.7MB
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

default for kubernetes, the kubectl commands above have been run on many freshly built clusters on many different machines and data centers.  Including https://labs.play-with-k8s.com/ upon which this can be replicated easily.
