### ISSUE TITLE
frontends.<service>.redirect doesn't work for last service alphabetically

### ISSUE THREAD

**Issue by attie** [containous/traefik#3074]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using [`d2766b1`](https://github.com/containous/traefik/tree/d2766b1b4fc653cce4ee44b66e794d744b5e9b66), setup traefik with two services, A and B:

``` toml
[entrypoints]
[entrypoints.http]
address = ":80"
compress = true

[file]

[backends.noop.servers._]
# something simple, for the demo
url = "http://ifconfig.co/"

[frontends.A]
backend = "noop"
[frontends.A.routes._]
rule = "Host: hosta"
[frontends.A.redirect]
regex = "^http://hosta/(.*)$"
replacement = "http://example.com/a/${1}"

[frontends.B]
backend = "noop"
[frontends.B.routes._]
rule = "Host: hostb"
[frontends.B.redirect]
regex = "^http://hostb/(.*)$"
replacement = "http://example.com/b/${1}"
```

``` yml
services:
    traefik:
        container_name: traefik
        restart: always

        image: containous/traefik:latest

        volumes:
            # config
            - ${PATH_TO_CONFIG}/traefik.toml:/etc/traefik/traefik.toml:ro
            # docker support stuff
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 80:80/tcp
```

Then, issue a request to localhost asking for `hosta` and `hostb`... Both should redirect, but the "_last_" (`hostb`) doesn't.

```console
$ curl -D - --header 'Host: hosta' http://10.42.0.1:80/
HTTP/1.1 302 Found
Location: http://example.com/a/
Vary: Accept-Encoding
Date: Sat, 24 Mar 2018 23:04:54 GMT
Content-Length: 5
Content-Type: text/plain; charset=utf-8

Found
```

```console
$ curl -D - --header 'Host: hostb' http://10.42.0.1:80/
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: text/plain; charset=utf-8
Date: Sat, 24 Mar 2018 23:04:55 GMT
Server: nginx
Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
Vary: Accept-Encoding

86.156.143.165
```

I've shuffled them around, and it appears to always be the _last_ as sorted alphabetically.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      d2766b1b4fc653cce4ee44b66e794d744b5e9b66
Codename:     cheddar
Go version:   go1.10
Built:        2018-03-24_10:20:27PM
OS/Arch:      linux/amd64
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

Adding `debug = true` to the top of the config above...

`hosta` request produces no logging output.

`hostb` produces this:
```
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://ifconfig.co/"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"ifconfig.co\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"ifconfig.co\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://ifconfig.co/, code: 200, Length: 15, duration: 42.9843ms"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"ifconfig.co\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"ifconfig.co\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-03-24T23:09:13Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.47.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"hostb\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.48.1:56278\",\"RequestURI\":\"/\",\"TLS\":null}"
```
