### ISSUE TITLE
Segment labels - frontend rule doesn't work on Rancher

### ISSUE THREAD

**Issue by charandas** [containous/traefik#3089]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In #3073, support for containers with multiple ports was added for rancher and marathon using segment labels. I am using the latest RC 1.6.0-rc1, and am experiencing trouble getting it to work.

There is a slight indirection involved in my usecase, which is that I am using traefik with this [Dockerfile](https://github.com/rawmind0/alpine-traefik/blob/master/Dockerfile). All I change is the `SERVICE_BUILD` to `1.6.0-rc1` (essentially the same as `1.6.0-rc2` tag).

### What did you expect to see?

I expect to be able to use segment labels. However, the `echoApi.frontend.rule` is never taken into account when using them.

```yml
version: '2'

services:
  echotest:
    image: jmalloc/echo-server
    labels:
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.echoApi.port: 8080
      traefik.echoApi.frontend.rule: 'PathPrefixStrip:/echo'
  traefik:
    image: myRegistry:8443/alpine-traefik:use-v1.6.0-rc1
    environment:
      TRAEFIK_ADMIN_AUTH_METHOD: basic
      TRAEFIK_ADMIN_AUTH_USERS: ''
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_READ_ONLY: 'true'
      TRAEFIK_ADMIN_STATISTICS: '10'
      TRAEFIK_HTTPS_COMPRESSION: 'true'
      TRAEFIK_HTTPS_ENABLE: 'true'
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_COMPRESSION: 'true'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_INSECURE_SKIP: 'false'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_MODE: metadata
      TRAEFIK_RANCHER_DOMAIN: rancher.internal
      TRAEFIK_DEBUG: 'true'
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 8000:8000/tcp
    labels:
      io.rancher.container.hostname_override: container_name
```

My rule itself registers perfectly, if I change the above labels like so:
```yml
services:
  echotest:
    image: jmalloc/echo-server
    labels:
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: 'PathPrefixStrip:/echo'
  --- rest is the same ---
```

### What did you see instead?

![image](https://user-images.githubusercontent.com/542168/37978142-59c4e12c-31b3-11e8-99c5-ab0620841b6f.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6.0-rc1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

TOML is autogenerated by the `rawmind/alpine-traefik`. I got this out of the container in any case.

```toml
 # traefik.toml
debug = true
logLevel = "INFO"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]
sendAnonymousUsage = false

[traefikLog]
  filePath = "/opt/traefik/log/traefik.log"

[accessLog]
  filePath = "/opt/traefik/log/access.log"

[respondingTimeouts]
  readTimeout = "0s"
  writeTimeout = "0s"
  idleTimeout = "180s"

[forwardingTimeouts]
  dialTimeout = "30s"
  responseHeaderTimeout = "0s"

[entryPoints]
  [entryPoints.traefik]
    address = ":8000"
    compress = true
  [entryPoints.http]
    address = ":80"
    compress = true
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      MinVersion = "VersionTLS12"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/traefik.crt"
          keyFile = "/opt/traefik/certs/traefik.key"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
  [api.statistics]
    RecentErrors = 10

[rest]
  entryPoint = "traefik"

[ping]
  entryPoint = "traefik"


[rancher]
  domain = "rancher.internal"
  Watch = true
  RefreshSeconds = 15
  ExposedByDefault = false
  EnableServiceHealthFilter = false
  [rancher.metadata]
    IntervalPoll = false
    Prefix = "/2016-07-29"
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```shell
# Only pertinent output:
test-platform-traefik-1  | 2018-03-27T15:46:31.496406533Z time="2018-03-27T15:46:31Z" level=debug msg="map[traefik.echoApi.frontend.rule:PathPrefixStrip:/echo traefik.echoApi.port:8080 traefik.enable:true io.rancher.container.pull_image:always io.rancher.service.hash:935abe2d05e52b2a1fe994849097f0b0d5fd888e] map[:map[traefik.enable:true] echoApi:map[traefik.port:8080 traefik.frontend.rule:PathPrefixStrip:/echo]]"

test-platform-traefik-1  | 2018-03-27T15:46:31.496778748Z time="2018-03-27T15:46:31Z" level=debug msg="map[io.rancher.service.hash:935abe2d05e52b2a1fe994849097f0b0d5fd888e traefik.echoApi.frontend.rule:PathPrefixStrip:/echo traefik.echoApi.port:8080 traefik.enable:true io.rancher.container.pull_image:always] map[echoApi:map[traefik.frontend.rule:PathPrefixStrip:/echo traefik.port:8080] :map[traefik.enable:true]]"
test-platform-traefik-1  | 2018-03-27T15:46:31.497851290Z time="2018-03-27T15:46:31Z" level=debug msg="Validation of load balancer method for backend backend-echotest-test-platform-echotest-test-platform-echoApi failed: invalid load-balancing method ''. Using default method wrr."
test-platform-traefik-1  | 2018-03-27T15:46:31.497867119Z time="2018-03-27T15:46:31Z" level=debug msg="Configuration received from provider rancher: {\"backends\":{\"backend-echotest-test-platform-echotest-test-platform-echoApi\":{\"servers\":{\"server-0\":{\"url\":\"http://10.42.29.38:8080\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-echotest-test-platform-echotest-test-platform-echoApi\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-echotest-test-platform-echotest-test-platform-echoApi\",\"routes\":{\"route-frontend-echotest-test-platform-echotest-test-platform-echoApi\":{\"rule\":\"Host:echotest.test-platform.rancher.internal\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":[]}}}

test-platform-traefik-1  | 2018-03-27T15:46:39.132713545Z time="2018-03-27T15:46:39Z" level=debug msg="map[io.rancher.container.pull_image:always io.rancher.service.hash:935abe2d05e52b2a1fe994849097f0b0d5fd888e traefik.echoApi.frontend.rule:PathPrefixStrip:/echo traefik.echoApi.port:8080 traefik.enable:true] map[:map[traefik.enable:true] echoApi:map[traefik.frontend.rule:PathPrefixStrip:/echo traefik.port:8080]]"
test-platform-traefik-1  | 2018-03-27T15:46:39.143976831Z time="2018-03-27T15:46:39Z" level=debug msg="Validation of load balancer method for backend backend-echotest-test-platform-echotest-test-platform-echoApi failed: invalid load-balancing method ''. Using default method wrr."
test-platform-traefik-1  | 2018-03-27T15:46:39.143990211Z time="2018-03-27T15:46:39Z" level=debug msg="Configuration received from provider rancher: {\"backends\":{\"backend-echotest-test-platform-echotest-test-platform-echoApi\":{\"servers\":{\"server-0\":{\"url\":\"http://10.42.29.38:8080\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-echotest-test-platform-echotest-test-platform-echoApi\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-echotest-test-platform-echotest-test-platform-echoApi\",\"routes\":{\"route-frontend-echotest-test-platform-echotest-test-platform-echoApi\":{\"rule\":\"Host:echotest.test-platform.rancher.internal\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":[]}}}"
```
