### ISSUE TITLE
Consul Catalog templating issue

### ISSUE THREAD

**Issue by albertogg** [containous/traefik#3090]
### Do you want to request a *feature* or report a *bug*?

Possible bug

### What did you do?

I'm configuring traefik to work with Consul Catalog backend and the templating system is not picking up the service name from consul. The weird thing here is that if I don't touch the `frontEndRule` in the configuration the service name is picked and I see `Host:admin.`.

I've tested the `frontEndRule` using `PathPrefix:/{{.ServiceName}}`, `Host:{{.ServiceName}}` and even `Host:{{.ServiceName}}.{{.Domain}}` which you expect to see working because it's the default, but it doesn't.

### What did you expect to see?

```json
"routes":{"route-host-admin":{"rule":"PathPrefix:/admin"}}
```

### What did you see instead?

```json
"routes":{"route-host-admin":{"rule":"PathPrefix:/\u003cno value\u003e"}}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run traefik:1.5 version
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
[web]
  address = ":9997"
  [web.statistics]
    RecentErrors = 10
  [web.metrics.prometheus]
    Buckets=[0.1,0.3,1.2,5.0,10.0,20.0]
[entryPoints]
  [entryPoints.http]
    address = ":9996"
[consulCatalog]
  endpoint = "127.0.0.1:8500"
  frontEndRule = "PathPrefix:/{{.ServiceName}}"
  constraints = ["tag==dev", "tag==external"]
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```shell
time="2018-03-27T16:25:07Z" level=debug msg="List of services changed"                                                                                                                                                                                                                   
time="2018-03-27T16:25:07Z" level=debug msg="Fetching service" service=admin                                                                                                             
time="2018-03-27T16:25:07Z" level=debug msg="Service admin pruned by 'tag==dev' constraint"
time="2018-03-27T16:25:08Z" level=debug msg="Configuration received from provider consul_catalog: {"backends":{"backend-admin":{"servers":{"admin--[REDACTED]--59030--dev--microservic
e--urlprefix-admin--traefik-tags-dev--traefik-tags-external--traefik-tags-internal--0":{"url":"http://[REDACTED]:59030","weight":0},"admin--[REDACTED]--50487--dev--microservice--traefik-tags-dev--traefik-tags-external--traefik-tags-internal--1":{"url":"http://[REDACTED]:50487","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"fronten
d-admin":{"entryPoints":["http"],"backend":"backend-admin","routes":{"route-host-admin":{"rule":"PathPrefix:/\u003cno value\u003e"}},"passHostHeader":true,"priority":0,"basicAuth":[]}}}
"   
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

To have a value for `{{.Domain}}` you need to define the domain in the Consul Catalog configuration section: https://docs.traefik.io/configuration/backends/consulcatalog/
```toml
[consulCatalog]
# ...
domain = "my_domain"
```


The value `\u003cno value\u003e` (`<no value>`) appears because your service seems don't have service name, please check the service information in your Consul.

Join us on the [Traefik community Slack](https://traefik.herokuapp.com) is you need more support.
