### ISSUE TITLE
Ability to set ciphersuites and MinTLSVersion by CLI

### ISSUE THREAD

**Issue by Baklap4** [containous/traefik#3103]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you do?
I wanted to change my TLS MinVersion to V1.1 and change my ciphersuites to the following:

- `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`
- `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA384`
- `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305`
- `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`
- `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`

### What did you expect to see?
The settings provided through docker-compose.yml (as command) being respected and used.

### What did you see instead?
These settings were not used, however certificates were used.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
version: '2'
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    volumes:
      - /etc/ssl/cert:/etc/ssl/cert
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - 80:80
      - 443:443
    command:
      - --api
      - --logLevel=INFO
      - --entryPoints=Name:https Address::443 TLS:MinVersion:VersionTLS11 TLS:CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA TLS:/etc/ssl/cert/star_domain_org.crt,/etc/ssl/private/star_domain_nl.key
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --defaultEntryPoints=https,http      
      - --rancher.api.endpoint=https://rancher.domain.org/v1
      - --rancher.watch=true
      - --rancher.domain=rancher.domain.org
      - --rancher.api.accesskey=${ACCESS_KEY}
      - --rancher.api.secretkey=${SECRECT_KEY}
      - --rancher.exposedbydefault=false
    labels:   
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.frontend.rule: 'Host:domain.org'
      traefik.frontend.auth.basic: "admin:${WEB_UI_PASSWORD}"
```

As provided by the [current docs](https://docs.traefik.io/configuration/entrypoints/#all-available-options) these are the available cli options. Would it be possible to extend this with `TLS:MinVersion` and `TLS:CipherSuites`?
