### ISSUE TITLE
whiteList.useXForwardedFor is not working!

### ISSUE THREAD

**Issue by yatki** [containous/traefik#3104]
### Do you want to request a *feature* or report a *bug*?

bug 

### What did you do?

I am using  traefik v1.6.0-rc3 version in docker swarm mode. I'm applying the labels to one of my docker services like below:
```
traefik.port=8080
traefik.frontend.rule=Host:sub.domain.com
traefik.frontend.whiteList.sourceRange=80.x.x.x
traefik.frontend.whiteList.useXForwardedFor=true
```
### What did you expect to see?

- I want to see that all requests to my `sub.domain.com` are *rejected* **except** the ones from my ip `80.x.x.x`
- I was expecting to see applied labels on WEB UI

### What did you see instead?

1) I'm still getting the same error message:
```
time="2018-03-29T14:17:00Z" level=debug msg="source-IP 10.255.0.2 matched none of the white list - rejecting"
```

2) I **can not** see my labels in WEB UI.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker image: traefik:1.6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
    users = ["user:$apr1$Yb2MBtLH$xcni8/KPOfPk4NTeAcb/Q/"]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.com"
watch = true
swarmmode = true
exposedbydefault = false
usebindportip = true
```
Docker version 17.12.1-ce, build 7390fc6
