### ISSUE TITLE
Kubernetes provider generate incorrect settings for ingress with named ports

### ISSUE THREAD

**Issue by div-by-zero** [containous/traefik#3118]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Create ingress for single multiport service. Ingress and service has named ports.

Single service cheese example
```yml
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: stilton
  labels:
    app: cheese
    cheese: stilton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cheese
      task: stilton
  template:
    metadata:
      labels:
        app: cheese
        task: stilton
        version: v0.0.1
    spec:
      containers:
      - name: cheese
        image: errm/cheese:stilton
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 80
          name: stilton
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cheddar
  labels:
    app: cheese
    cheese: cheddar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cheese
      task: cheddar
  template:
    metadata:
      labels:
        app: cheese
        task: cheddar
        version: v0.0.1
    spec:
      containers:
      - name: cheese
        image: errm/cheese:cheddar
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 80
          name: cheddar
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: wensleydale
  labels:
    app: cheese
    cheese: wensleydale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cheese
      task: wensleydale
  template:
    metadata:
      labels:
        app: cheese
        task: wensleydale
        version: v0.0.1
    spec:
      containers:
      - name: cheese
        image: errm/cheese:wensleydale
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 80
          name: wensleydale
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /stilton
        backend:
          serviceName: cheese-svc
          servicePort: stilton
      - path: /cheddar
        backend:
          serviceName: cheese-svc
          servicePort: cheddar
      - path: /wensleydale
        backend:
          serviceName: cheese-svc
          servicePort: wensleydale
---
apiVersion: v1
kind: Service
metadata:
  name: cheese-svc
spec:
  ports:
  - name: stilton
    targetPort: stilton
    port: 80
  - name: wensleydale
    targetPort: wensleydale
    port: 81
  - name: cheddar
    targetPort: cheddar
    port: 82
  selector:
    app: cheese
```

### What did you expect to see?
When create ingress for service with two (or many) ports and different routes, each route has entrypoints only with servicePort describe for route.

`/cheddar` response only `cheddar`
`/stilton` response only `stilton`
`/wensleydale` response only `wensleydale`

### What did you see instead?
When create ingress each route has all service entrypoints.
Pages `/cheddar`, `/stilton`, `/wensleydale` randomly response from all pods in service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
CoreOS 1688.4.0
Kubernetes v1.9.3

```toml
    logLevel = "DEBUG"
    checkNewVersion = false
    defaultEntryPoints = ["http", "https"]

    [kubernetes]

    [api]

    [metrics]
      [metrics.prometheus]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
        minVersion = "VersionTLS12"
        cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384" ]
      [entryPoints.traefik]
        address = ":8080"
        compress = true

    [etcd]
    endpoint="example.com:2379"
    useAPIV3 = true
      [etcd.tls]
      ca = "/etc/etcd/ssl/ca.pem"
      cert = "/etc/etcd/ssl/etcd.pem"
      key = "/etc/etcd/ssl/etcd-key.pem"

    [acme]
    acmeLogging = true
    email = "letsencrypt@example.com"
    entryPoint = "https"
    storage = "/traefik/acme/account"
    onDemand = true
    onHostRule = true
    [acme.httpChallenge]
      entryPoint = "http"
    [[acme.domains]]
      main = "example.com"
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```shell
time="2018-04-02T16:12:16Z" level=debug msg="Configuration received from provider kubernetes: {"backends":{"example.com/cheddar":{"servers":{"cheddar-75b5c9f657-f8vrd":{"url":"http://10.10.3.33:80","weight":1},"cheddar-75b5c9f657-ns4kz":{"url":"http://10.10.4.35:80","weight":1},"stilton-6fc9f7dc55-9d2dv":{"url":"http://10.10.4.34:80","weight":1},"stilton-6fc9f7dc55-dlnl8":{"url":"http://10.10.3.32:80","weight":1},"wensleydale-5b58bc978c-blqpd":{"url":"http://10.10.4.36:80","weight":1},"wensleydale-5b58bc978c-k5n2d":{"url":"http://10.10.3.34:80","weight":1}},"loadBalancer":{"method":"wrr"}},"example.com/stilton":{"servers":{"cheddar-75b5c9f657-f8vrd":{"url":"http://10.10.3.33:80","weight":1},"cheddar-75b5c9f657-ns4kz":{"url":"http://10.10.4.35:80","weight":1},"stilton-6fc9f7dc55-9d2dv":{"url":"http://10.10.4.34:80","weight":1},"stilton-6fc9f7dc55-dlnl8":{"url":"http://10.10.3.32:80","weight":1},"wensleydale-5b58bc978c-blqpd":{"url":"http://10.10.4.36:80","weight":1},"wensleydale-5b58bc978c-k5n2d":{"url":"http://10.10.3.34:80","weight":1}},"loadBalancer":{"method":"wrr"}},"example.com/wensleydale":{"servers":{"cheddar-75b5c9f657-f8vrd":{"url":"http://10.10.3.33:80","weight":1},"cheddar-75b5c9f657-ns4kz":{"url":"http://10.10.4.35:80","weight":1},"stilton-6fc9f7dc55-9d2dv":{"url":"http://10.10.4.34:80","weight":1},"stilton-6fc9f7dc55-dlnl8":{"url":"http://10.10.3.32:80","weight":1},"wensleydale-5b58bc978c-blqpd":{"url":"http://10.10.4.36:80","weight":1},"wensleydale-5b58bc978c-k5n2d":{"url":"http://10.10.3.34:80","weight":1}},"loadBalancer":{"method":"wrr"}}},"frontends":{"example.com/cheddar":{"entryPoints":["http","https"],"backend":"example.com/cheddar","routes":{"/cheddar":{"rule":"PathPrefixStrip:/cheddar"},"example.com":{"rule":"Host:example.com"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}},"example.com/stilton":{"entryPoints":["http","https"],"backend":"example.com/stilton","routes":{"/stilton":{"rule":"PathPrefixStrip:/stilton"},"example.com":{"rule":"Host:example.com"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}},"example.com/wensleydale":{"entryPoints":["http","https"],"backend":"example.com/wensleydale","routes":{"/wensleydale":{"rule":"PathPrefixStrip:/wensleydale"},"example.com":{"rule":"Host:example.com"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}}}}"
time="2018-04-02T16:12:16Z" level=debug msg="Creating frontend example.com/cheddar"
time="2018-04-02T16:12:16Z" level=debug msg="Wiring frontend example.com/cheddar to entryPoint http"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route /cheddar PathPrefixStrip:/cheddar"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route example.com Host:example.com"
time="2018-04-02T16:12:16Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\/\/)?([\w\._-]+)(?::\d+)?(.*)$ -> https://${1}:443${2}"
time="2018-04-02T16:12:16Z" level=debug msg="Creating backend example.com/cheddar"
time="2018-04-02T16:12:16Z" level=debug msg="Creating load-balancer wrr"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-f8vrd at http://10.10.3.33:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-ns4kz at http://10.10.4.35:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-9d2dv at http://10.10.4.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-dlnl8 at http://10.10.3.32:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-blqpd at http://10.10.4.36:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-k5n2d at http://10.10.3.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Wiring frontend example.com/cheddar to entryPoint https"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route /cheddar PathPrefixStrip:/cheddar"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route example.com Host:example.com"
time="2018-04-02T16:12:16Z" level=debug msg="Creating backend example.com/cheddar"
time="2018-04-02T16:12:16Z" level=debug msg="Creating load-balancer wrr"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-blqpd at http://10.10.4.36:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-k5n2d at http://10.10.3.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-f8vrd at http://10.10.3.33:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-ns4kz at http://10.10.4.35:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-9d2dv at http://10.10.4.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-dlnl8 at http://10.10.3.32:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating frontend example.com/stilton"
time="2018-04-02T16:12:16Z" level=debug msg="Wiring frontend example.com/stilton to entryPoint http"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route /stilton PathPrefixStrip:/stilton"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route example.com Host:example.com"
time="2018-04-02T16:12:16Z" level=debug msg="Creating backend example.com/stilton"
time="2018-04-02T16:12:16Z" level=debug msg="Creating load-balancer wrr"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-9d2dv at http://10.10.4.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-dlnl8 at http://10.10.3.32:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-blqpd at http://10.10.4.36:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-k5n2d at http://10.10.3.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-f8vrd at http://10.10.3.33:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-ns4kz at http://10.10.4.35:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Wiring frontend example.com/stilton to entryPoint https"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route /stilton PathPrefixStrip:/stilton"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route example.com Host:example.com"
time="2018-04-02T16:12:16Z" level=debug msg="Creating backend example.com/stilton"
time="2018-04-02T16:12:16Z" level=debug msg="Creating load-balancer wrr"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-9d2dv at http://10.10.4.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-dlnl8 at http://10.10.3.32:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-blqpd at http://10.10.4.36:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-k5n2d at http://10.10.3.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-f8vrd at http://10.10.3.33:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-ns4kz at http://10.10.4.35:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating frontend example.com/wensleydale"
time="2018-04-02T16:12:16Z" level=debug msg="Wiring frontend example.com/wensleydale to entryPoint http"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route /wensleydale PathPrefixStrip:/wensleydale"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route example.com Host:example.com"
time="2018-04-02T16:12:16Z" level=debug msg="Creating backend example.com/wensleydale"
time="2018-04-02T16:12:16Z" level=debug msg="Creating load-balancer wrr"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-9d2dv at http://10.10.4.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-dlnl8 at http://10.10.3.32:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-blqpd at http://10.10.4.36:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-k5n2d at http://10.10.3.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-f8vrd at http://10.10.3.33:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-ns4kz at http://10.10.4.35:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Wiring frontend example.com/wensleydale to entryPoint https"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route example.com Host:example.com"
time="2018-04-02T16:12:16Z" level=debug msg="Creating route /wensleydale PathPrefixStrip:/wensleydale"
time="2018-04-02T16:12:16Z" level=debug msg="Creating backend example.com/wensleydale"
time="2018-04-02T16:12:16Z" level=debug msg="Creating load-balancer wrr"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-blqpd at http://10.10.4.36:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server wensleydale-5b58bc978c-k5n2d at http://10.10.3.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-f8vrd at http://10.10.3.33:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server cheddar-75b5c9f657-ns4kz at http://10.10.4.35:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-9d2dv at http://10.10.4.34:80 with weight 1"
time="2018-04-02T16:12:16Z" level=debug msg="Creating server stilton-6fc9f7dc55-dlnl8 at http://10.10.3.32:80 with weight 1"
```

**Comment by timoreimann** [comment]
Traefik does not take the service port names into account when fetching the backend IP addresses from the associated endpoints object. I think we should do so, given that the service object does it as well.

@dtomcej WDYT?

**Comment by timoreimann** [comment]
Also: We _could_ argue that this is more of a feature request than a bug. At least, a workaround should be possible by specifying multiple services.

**Comment by dtomcej** [comment]
@timoreimann I would view the handling of named `targetPort`s as a feature request, since they work fine with specified port numbers.

I agree that we _should_ handle it properly, since we bypass services. It should be a simple spec lookup (_in theory_ ;) ), but the named ports are spec'd on the backend pods, so it may be a little trickier to implement.

Either way, due to the fact that we never implemented named `targetPort`s, I would view it as a feature request.

**Comment by timoreimann** [comment]
@dtomcej I don't think this needs to involve targetPorts necessarily.

Sorry, I should have probably added an example endpoints object to make it clearer. So here it is:

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-04-02T22:48:31Z
  name: cheese-svc
  namespace: default
  resourceVersion: "320"
  selfLink: /api/v1/namespaces/default/endpoints/cheese-svc
  uid: f788aa9a-36c7-11e8-9ce2-080027864714
subsets:
- addresses:
  - ip: 172.17.0.6
    nodeName: debug-traefik-ports2
    targetRef:
      kind: Pod
      name: stilton-6fc9f7dc55-nh6mj
      namespace: default
      resourceVersion: "285"
      uid: f74c6ecf-36c7-11e8-9ce2-080027864714
  - ip: 172.17.0.9
    nodeName: debug-traefik-ports2
    targetRef:
      kind: Pod
      name: stilton-6fc9f7dc55-nq28j
      namespace: default
      resourceVersion: "311"
      uid: f74cfdcc-36c7-11e8-9ce2-080027864714
  ports:
  - name: stilton
    port: 80
    protocol: TCP
- addresses:
  - ip: 172.17.0.10
    nodeName: debug-traefik-ports2
    targetRef:
      kind: Pod
      name: wensleydale-5b58bc978c-pbv5l
      namespace: default
      resourceVersion: "319"
      uid: f75b3d52-36c7-11e8-9ce2-080027864714
  - ip: 172.17.0.5
    nodeName: debug-traefik-ports2
    targetRef:
      kind: Pod
      name: wensleydale-5b58bc978c-zn4sr
      namespace: default
      resourceVersion: "276"
      uid: f761ead2-36c7-11e8-9ce2-080027864714
  ports:
  - name: wensleydale
    port: 80
    protocol: TCP
- addresses:
  - ip: 172.17.0.7
    nodeName: debug-traefik-ports2
    targetRef:
      kind: Pod
      name: cheddar-75b5c9f657-lktlz
      namespace: default
      resourceVersion: "294"
      uid: f751d7ba-36c7-11e8-9ce2-080027864714
  - ip: 172.17.0.8
    nodeName: debug-traefik-ports2
    targetRef:
      kind: Pod
      name: cheddar-75b5c9f657-9lv2s
      namespace: default
      resourceVersion: "302"
      uid: f7560596-36c7-11e8-9ce2-080027864714
  ports:
  - name: cheddar
    port: 80
    protocol: TCP
```

Notice how there's one "cheese-specific" port name per corresponding subset. Traefik does not take it into account though when collecting all pod cluster IP addresses from the endpoints controller. The result is that we route to the backing pods across all deployments (e.g., even if you send a request for `/cheddar`, you could possibly end up in a stilton pod).

The k8s service object gets this right: If you hit it for port 80, you always end up in stilton; port 81 always takes you to wensleydale; and port 82 always reaches cheddar. I think we just need to have an extra filtering step based on the service port name when going through the endpoints subsets.

**Comment by kadisi** [comment]
@div-by-zero  i think , the reason is that you use the svc label select : app: cheese,   when you use the single select for  svc port: 80,81,82, k8s will choose all pod which has label "app: cheese" for the endpoints,  so /cheddar, /stilton, /wensleydale randomly response from all pods in service.

i think you should create 3 svc , for example ：
```
apiVersion: v1
kind: Service
metadata:
  name: stilton
spec:
  ports:
  - name: stilton
    targetPort: stilton
    port: 80
  - name: wensleydale
    targetPort: wensleydale
  selector:
    app: cheese
     task: stilton
---
apiVersion: v1
kind: Service
metadata:
  name: wensleydale
spec:
  ports:
  - name: wensleydale
    targetPort: wensleydale
    port: 81
  selector:
    app: cheese
     task: wensleydale

---
apiVersion: v1
kind: Service
metadata:
  name: cheddar
spec:
  ports:
  - name: cheddar
    targetPort: cheddar
    port: 82
  selector:
    app: cheese
    task: cheddar
```

and your ingress file ：
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /stilton
        backend:
          serviceName: stilton
          servicePort: stilton
      - path: /cheddar
        backend:
          serviceName: cheddar
          servicePort: cheddar
      - path: /wensleydale
        backend:
          serviceName: wensleydale
          servicePort: wensleydale
```
