### ISSUE TITLE
Ingress TLS definitions are ignored

### ISSUE THREAD

**Issue by gorootde** [containous/traefik#3119]
### Do you want to request a *feature* or report a *bug*?
Bug
### What did you do?

- Deployed traefik to k8s as described in https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md
- Created a "default" secret that is configured as volume mount in traefik deployment
- Added this ingress resource:

```yml
apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: my-ingress
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.frontend.entryPoints: "http,https"
    spec:
      tls:
        - secretName: service1-tls-cert
        - secretName: service2-tls-cert
    
      rules:
        - host: service1.example.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: service1
                  servicePort: http
        - host: service2.example.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: service2
                  servicePort: http
```

### What did you expect to see?
Certificate stored in secret "service1-tls-cert" is used when accessing https://service1.example.com

### What did you see instead?
Default certificate (defined as volume mount in traefik deployment resource) is used instead. Same for service2.example.com

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
    v1.5.4 / cancoillotte
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
          regex = "^http://(.*)"
          replacement = "https://$1"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
    [kubernetes]
```
The certificates stored in service1-tls-cert and service2-tls-cert both follow the `tls.key` & `tls.crt` structure. The certificates itself are only valid for their corresponding hostnames. No wildcards in there.
