### ISSUE TITLE
Cannot set admin ui port configuration

### ISSUE THREAD

**Issue by remipassmoilesel** [containous/traefik#3140]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

I use a Kubespray/k8s cluster on which port 8080 is already used by Hyperkube. I'm trying to set admin ui port at 8090 but I can't get it work.

I tried to configure Web backend (deprecated), api, ping, ... But there is always a service which want to run on 8080.

My toml config:

```
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.webadmin]
  address = ":8090"

[api]
  dashboard = true
  entryPoint = "webadmin"

```
I tried to use command line arguments too, without success.

### What did you expect to see?

Traefik using another port than 8080

### What did you see instead?

Traefik using port 8080

### Output of `traefik version`: (_What version of Traefik are you using?_)

I tried with traefik:v1.6-alpine and 1.5.4

```
$ 😻 docker run traefik-dev version
/entrypoint.sh: exec: line 15: version: not found
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.webadmin]
  address = ":8090"

[api]
  dashboard = true
  entryPoint = "webadmin"
```

Pod output after startup:

```

time="2018-04-06T07:14:21Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml" 
time="2018-04-06T07:14:21Z" level=info msg="Traefik version v1.5.4 built on 2018-03-15_01:35:21PM" 
time="2018-04-06T07:14:21Z" level=info msg="
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/basics/#collected-data
" 
time="2018-04-06T07:14:21Z" level=info msg="Preparing server http &amp;{Network: Address::80 TLS:&lt;nil&gt; Redirect:&lt;nil&gt; Auth:&lt;nil&gt; WhitelistSourceRange:[] Compress:false ProxyProtocol:&lt;nil&gt; ForwardedHeaders:0xc4206723e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-04-06T07:14:21Z" level=info msg="Preparing server webadmin &amp;{Network: Address::8090 TLS:&lt;nil&gt; Redirect:&lt;nil&gt; Auth:&lt;nil&gt; WhitelistSourceRange:[] Compress:false ProxyProtocol:&lt;nil&gt; ForwardedHeaders:0xc420672400} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-04-06T07:14:21Z" level=info msg="Preparing server traefik &amp;{Network: Address::8080 TLS:&lt;nil&gt; Redirect:&lt;nil&gt; Auth:&lt;nil&gt; WhitelistSourceRange:[] Compress:false ProxyProtocol:&lt;nil&gt; ForwardedHeaders:0xc420672420} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-04-06T07:14:21Z" level=info msg="Starting server on :80" 
time="2018-04-06T07:14:21Z" level=error msg="Error opening listener listen tcp :8080: bind: address already in use" 
time="2018-04-06T07:14:21Z" level=fatal msg="Error preparing server: listen tcp :8080: bind: address already in use" 
```

Thanks for your help !

**Comment by remipassmoilesel** [comment]
Hi @Juliens, I fixed it with this configuration:

```
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.webadmin]
  address = ":8090"

  [entryPoints.traefik] # The entrypoint which fix the problem, but I don't know what is its purpose
  address = ":8100"
```

Here is my deployment:
```
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: remipassmoilesel-traefik:v1.6-alpine
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8090
        securityContext:
          privileged: true
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
```

But traefik entry point is not documented. Maybe a line or two somewhere in documentation can help people to use traefik with Kubespray (a popular way to install kubernetes) Maybe it can be described quickly on this page: https://docs.traefik.io/configuration/entrypoints/

If you think it is a good idea I can post a MR.

Thanks

**Comment by remipassmoilesel** [comment]
This is my whole configuration file, all values are default except entryPoints:

```
################################################################
# Global configuration
################################################################

# Timeout in seconds.
# Duration to give active requests a chance to finish during hot-reloads
#
# Optional
# Default: 10
#
# graceTimeOut = 10

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
# traefikLogsFile = "log/traefik.log"

# Access logs file
#
# Optional
#
# accessLogsFile = "log/access.log"

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "ERROR"

logLevel = "DEBUG"

# Backends throttle duration: minimum duration between 2 events from providers
# before applying a new configuration. It avoids unnecessary reloads if multiples events
# are sent in a short amount of time.
#
# Optional
# Default: "2s"
#
# ProvidersThrottleDuration = "5s"

# If non-zero, controls the maximum idle (keep-alive) to keep per-host.  If zero, DefaultMaxIdleConnsPerHost is used.
# If you encounter 'too many open files' errors, you can either change this value, or change `ulimit` value.
#
# Optional
# Default: http.DefaultMaxIdleConnsPerHost
#
# MaxIdleConnsPerHost = 200

# Enable ACME (Let's Encrypt): automatic SSL
#
# Optional
#
# [acme]

# Email address used for registration
#
# Required
#
# email = "test@traefik.io"

# File used for certificates storage.
# WARNING, if you use Traefik in Docker, don't forget to mount this file as a volume.
#
# Required
#
# storageFile = "acme.json"

# Entrypoint to proxy acme challenge to.
# WARNING, must point to an entrypoint on port 443 
#
# Required
#
# entryPoint = "https"

# Enable on demand certificate. This will request a certificate from Let's Encrypt during the first TLS handshake for a hostname that does not yet have a certificate.
# WARNING, TLS handshakes will be slow when requesting a hostname certificate for the first time, this can leads to DoS attacks.
# WARNING, Take note that Let's Encrypt have rate limiting: https://community.letsencrypt.org/t/quick-start-guide/1631
#
# Optional
#
# onDemand = true

# CA server to use
# Uncomment the line to run on the staging let's encrypt server
# Leave comment to go to prod
#
# Optional
#
# caServer = "https://acme-staging.api.letsencrypt.org/directory"

# Domains list
# You can provide SANs (alternative domains) to each main domain
#
# [[acme.domains]]
#   main = "local1.com"
#   sans = ["test1.local1.com", "test2.local1.com"]
# [[acme.domains]]
#   main = "local2.com"
#   sans = ["test1.local2.com", "test2x.local2.com"]
# [[acme.domains]]
#   main = "local3.com"
# [[acme.domains]]
#   main = "local4.com"


# Entrypoints definition
#
# Optional
# Default:
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#
# To redirect an http entrypoint to an https entrypoint (with SNI support):
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#       entryPoint = "https"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]
#       [[entryPoints.https.tls.certificates]]
#       CertFile = "integration/fixtures/https/snitest.com.cert"
#       KeyFile = "integration/fixtures/https/snitest.com.key"
#       [[entryPoints.https.tls.certificates]]
#       CertFile = "integration/fixtures/https/snitest.org.cert"
#       KeyFile = "integration/fixtures/https/snitest.org.key"
#
# To redirect an entrypoint rewriting the URL:
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#       regex = "^http://localhost/(.*)"
#       replacement = "http://mydomain/$1"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.traefik]
  address = ":8100"


# Enable retry sending request if network error
#
# Optional
#
# [retry]

# Number of attempts
#
# Optional
# Default: (number servers in backend) -1
#
# attempts = 3

# Sets the maximum request body to be stored in memory in Mo
#
# Optional
# Default: 2
#
# maxMem = 3

################################################################
# API configuration backend
################################################################

[api]
  dashboard = true
  entryPoint = "traefik"

[ping]
  entryPoint = "traefik"

[metrics]
  entryPoint = "traefik"

################################################################
# File configuration backend
################################################################

# Enable file configuration backend
#
# Optional
#

[file]

# Rules file
# If defined, traefik will load rules from this file,
# otherwise, it will load rules from current file (cf Sample rules below).
#
# Optional
#
# filename = "rules.toml"

filename = "/config/rules.toml"

# Enable watch file changes
#
# Optional
#

watch = true


################################################################
# Kubernetes Ingress configuration backend
################################################################
# Enable Kubernetes Ingress configuration backend
#
# Optional
#
# [kubernetes]

# Kubernetes server endpoint
#
# When deployed as a replication controller in Kubernetes,
# Traefik will use env variable KUBERNETES_SERVICE_HOST
# and KUBERNETES_SERVICE_PORT_HTTPS as endpoint
# Secure token will be found in /var/run/secrets/kubernetes.io/serviceaccount/token
# and SSL CA cert in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
# 
# Optional
#
#
# endpoint = "http://localhost:8080"

# namespaces = ["default"]


################################################################
# Sample rules
################################################################
# [backends]
#   [backends.backend1]
#     [backends.backend1.circuitbreaker]
#       expression = "NetworkErrorRatio() > 0.5"
#     [backends.backend1.servers.server1]
#     url = "http://172.17.0.2:80"
#     weight = 10
#     [backends.backend1.servers.server2]
#     url = "http://172.17.0.3:80"
#     weight = 1
#   [backends.backend2]
#     [backends.backend2.LoadBalancer]
#       method = "drr"
#     [backends.backend2.servers.server1]
#     url = "http://172.17.0.4:80"
#     weight = 1
#     [backends.backend2.servers.server2]
#     url = "http://172.17.0.5:80"
#     weight = 2
#
# [frontends]
#   [frontends.frontend1]
#   backend = "backend2"
#     [frontends.frontend1.routes.test_1]
#     rule = "Host: test.localhost, other.localhost"
#   [frontends.frontend2]
#   backend = "backend1"
#   passHostHeader = true
#   entrypoints = ["https"] # overrides defaultEntryPoints
#     [frontends.frontend2.routes.test_1]
#     rule = "Host:{subdomain:[a-z]+}.localhost"
#   [frontends.frontend3]
#   entrypoints = ["http", "https"] # overrides defaultEntryPoints
#   backend = "backend2"
#     rule = "Path: /test, /other"
```

And the associated deployment:

```
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: remipassmoilesel-traefik:v1.6-alpine
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8090
        securityContext:
          privileged: true
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO

```

**Comment by ldez** [comment]
Your problem is here:
```yml
        args:
        - --api
```

```toml
[api]
  dashboard = true
  entryPoint = "traefik"
```

You cannot defined 2 options in CLI and TOML

Remove `--api` and your problem will be solved.
