### ISSUE TITLE
Traefik not updated in Docker Swarm Mode

### ISSUE THREAD

**Issue by jaschaio** [containous/traefik#3142]
When I make a change to the labels on one of my service I have to completely remove the traefik service and deploy it again until the changes have any effect.

Even so in the logs it says that it has successfully received the configuration.

I am simply changing the `traefik.frontend.rule` label from `xyz.example.org` to `test.example.org`.

If I inspect the service afterwards the label is successfully applied. But traefik still only proxies traffic through `http://xyz.example.org/` and not `http://test.example.org/`

Even in the dashboard it still says `http://xyz.example.org/` instead of `http://test.example.org/`

Watch is obviously enabled.

Not sure what's wrong.

traefik.toml:
```
# Define Entrypoints
defaultEntryPoints = ["http", "https"]

# Debug Mode
debug = true

[entryPoints]

    # http:// traffic
    [entryPoints.http]
        address = ":80"

    # https:// traffic
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]

    # Dashboard
    [entryPoints.traefik]
        address = ":8080"
        
        # Basic Authentication
        [entryPoints.traefik.auth]
            [entryPoints.traefik.auth.basic]
                users = [
                    "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
                ]

# Let's Encrypt
[acme]
    email = "example@example.org"
    storage = "/etc/traefik/acme/acme.json"
    # Staging
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    # Generate for newly added hosts
    onHostRule = true
    entryPoint = "https"

    [acme.httpChallenge]
        entryPoint = "http"

# Enable API & Dashboard
[api]
    entryPoint = "traefik"
    dashboard = true

# Docker Configuration
[docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "docker.localhost"
    watch = true
    swarmmode = true
    exposedbydefault = false
```

traeffik docker compose file:
```
version: '3.6'

services:
    proxy:
        image: traefik:1.6-alpine
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 433
              published: 433
              protocol: tcp
              mode: host
            - target: 8080
        volumes:
            - $HOME/traefik/traefik.toml:/etc/traefik/traefik.toml
            - /etc/letsencrypt/traefik/acme:/etc/traefik/acme
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - node.role==manager
            labels:
                - traefik.port=8080
                - traefik.docker.network=proxy
                - traefik.frontend.rule=Host:monitor.example.org
                - traefik.enable=true
        networks:
            - proxy

networks:
    proxy:
        external: true
```

nginx compose:
```
version: '3.6'

services:
    nginx:
        image: nginx
        ports:
            - 80
        deploy:
            placement:
                constraints:
                    - node.role==manager
            labels:
                - traefik.port=80
                - traefik.docker.network=proxy
                - traefik.frontend.rule=Host:test.example.org
                - traefik.enable=true
        networks:
            - proxy

networks:
    proxy:
        external: true
```

Log:
```
Configuration received from provider docker: {\"backends\":{\"backend-nginx-nginx\":{\"servers\":{\"server-nginx-nginx-1\":{\"url\":\"http://10.0.0.106:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}},\"backend-traefik-proxy\":{\"servers\":{\"server-traefik-proxy-1\":{\"url\":\"http://10.0.0.112:8080\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-Host-monitor-example-org-1\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-traefik-proxy\",\"routes\":{\"route-frontend-Host-monitor-example-org-1\":{\"rule\":\"Host:monitor.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":[]},\"frontend-Host-test-example-org-0\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-nginx-nginx\",\"routes\":{\"route-frontend-Host-test-example-org-0\":{\"rule\":\"Host:test.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":[]}}}
```
