### ISSUE TITLE
Scaling with docker-compose --scale results in multiple frontends and backends

### ISSUE THREAD

**Issue by dabide** [containous/traefik#3145]
### Do you want to request a *feature* or report a *bug*?
As far as I can understand, this must be a bug.

### What did you do?
I created a simple `docker-compose.yaml`:

```yaml
version: '3'

services:
  scaler:
    image: registry:5000/static/master:latest

    restart: unless-stopped

    networks:
      - web

    labels:
      - "traefik.backend=foo"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host: scaler.test.ab.cd"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

networks:
  web:
    external: true
```

I then ran it with `docker-compose -d --scale scaler=3`.

### What did you expect to see?
I expected to see one frontend and one backend, the latter containing three docker instances.

### What did you see instead?

Træfik creates three separate frontends and three separate backends, and no load balancing takes place. The frontends are named `frontend-scaletest-scaler-1-foo-default`, `frontend-scaletest-scaler-2-foo-default` and so on, and the backends are named `backend-scaletest-scaler-1-foo-default` and so on.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "test.kxweb.no"
watch = true
exposedbydefault = false

[acme]
email = "ola.nordmann@ab.cd"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[web]
address = ":8080"

# [accessLog]
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
