### ISSUE TITLE
Traefik doesn't auto re-add re-enabled service based on Consul Catalog changes

### ISSUE THREAD

**Issue by xmackex** [containous/traefik#3157]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- register service -> service comes available in traefik
- stop service -> service is gone from traefik
- start same service -> service is not available in traefik but alive in Consul
- wait 5-20 minutes -> service is not available in traefik
- restart traefik -> service comes available in traefik

### What did you expect to see?

It seems to be a sub-issue of [previously closed issue](https://github.com/containous/traefik/issues/2552)

### What did you see instead?

Changes are properly updated, but in case of deregistering and registering same service there are issues.

Also I believe I could misconfigured something, would appreciate for hints

### Output of `traefik version`: (_What version of Traefik are you using?_)

Consul version: 1.0.6
Traefik version: v1.5.4, v1.6.0-rc4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My Traefik config is:

```toml
[entryPoints]
  [entryPoints.http]
    address = ":5555"
    compress = false
    [entryPoints.http.proxyProtocol]
        trustedIPs = ["10.0.0.0/8"]
  [entryPoints.traefik_api]
    address = ":1111"
    compress = false
    
[ping]
  entryPoint = "http"

[consulCatalog]
endpoint = "127.0.0.1:8450"
exposedByDefault = false
prefix = "traefik"

[api]
  entryPoint = "traefik_api"
  dashboard = true
  debug = true
[traefikLog]
  format   = "json"
[accessLog]
  format   = "json"
defaultEntryPoints = ["http"]
```

Frontend rule is exposed via service tag: `traefik.frontend.rule=Host:example.com`
