### ISSUE TITLE
Setting a subdomain in labels for Traefik eventually makes my server freeze

### ISSUE THREAD

**Issue by Drillan767** [containous/traefik#3164]
### Do you want to request a *feature* or report a *bug*?
I would like to report a bug

### What did you do?
I have a "main" docker-compose.yml file where I setup everything that's not related to my projects. I want to be able to reach Traefik via a subdomain without having to add ":8080" at the end of my domain name. (ie: monitor.mydomain.me instead of mydomain.me:8080)

Here is my docker-compose.yml file:

```yml
version: '3'

services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:monitor.mydomain.me"
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=http,https"
# some other services, they all work
```

### What did you expect to see?

When reaching "monitor.mydomain.me", I expected to see the Traefik dashboard

### What did you see instead?

When reaching "monitor.mydomain.me", Traefik hangs forever. However, reaching "mydomain.me:8080" is still possible for a couple minutes. After a while, however, it doesn't respond anymore and my ssh session stops by itself, or I just can't write anything anymore on my console. I generally have to manually reboot my server

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I'm using Debian 9 x64, with nothing else but Git and Docker installed on it. Also, I'm using the "traefik.toml" that Traefik puts at disposal.

As a bottom note, I did some researches but I didn't find anything that seems close to what I'm experiencing.
Thank you in advance
