### ISSUE TITLE
Traefik does not purge closed incoming connections

### ISSUE THREAD

**Issue by imcitius** [containous/traefik#3165]
### Do you want to request a *feature* or report a *bug*?
*bug*

### What did you do?
Expose services via consul service catalog.
One of services is websocket server.

### What did you expect to see?
Correct reverse proxying.

### What did you see instead?
A lot of not closed network connections in ESTABLISHED state.
Connections number is grow until all kernel's sockets is used, and traefik throw a 'maximum number of open files is reached' error.
Restart of traefik service flushes old connections, and start normal operations until limit reached again.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
MaxIdleConnsPerHost = 100000

[consul]
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "traefik"

[entrypoints]
  [entrypoints.traefik]
      address="127.0.0.1:8081"

[api]
  entrypoint = "traefik"

[ping]
  entryPoint = "http"

[consulcatalog]
  endpoint="127.0.0.1:8500"
  watch = true
  domain = "app.com"
  prefix = "traefik"
  exposedbydefault = false

[metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]

```

Platform is Centos 7, Consul 1.0.2.
Services is published into Consul catalog using simple json configs.
