### ISSUE TITLE
Traefik deployed in swarm but using host port would lead to significant loss of performance due to ACME at least?

### ISSUE THREAD

**Issue by nsteinmetz** [containous/traefik#3174]
### Do you want to request a *feature* or report a *bug*?

Seems a bug - asked yesterday on slack.

### What did you do?

I have a 2 nodes swarm cluster, based on docker 17.12.1-ce on ubuntu 16.04.

I use Traefik 1.5.4, deployed within the swarm cluster. So far it worked well but for the app deployed in the cluster, I need to have the public ip to enable/disable a debug mode on app side. So I had to change port configuration to be at host level and not trough ingress.

My traefik compose file: 

``` yaml
version: '3.4'
services:
  traefik:
    image: traefik:1.5.4
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
#      - "80:80"
#      - "443:443"
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /opt/traefik/conf/traefik.toml
        target: /traefik.toml
      - type: bind
        source: /opt/traefik/acme/acme.json
        target: /acme.json
    networks:
      - traefik-net
networks:
  traefik-net:
    driver: overlay
    attachable: true
```

My traefik.toml file

```toml
defaultEntryPoints = ["http", "https"]

logLevel = "INFO"

# Disable certs validation as traefik will use IP to connect containres instead of hostnames, which will never validate.
InsecureSkipVerify = true

[traefikLog]
  filePath = "/traefik.log"
  format = "json"

[accessLog]
filePath = "/access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address = "127.0.0.1:8080"
    [entryPoints.api.auth.basic]
    users = [
      "xxx:xxx"
    ]

[acme]
email = "sysadmin@xxx.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"

[api]
entryPoint = "api"
dashboard = true
debug = false

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik"
watch = true
exposedbydefault = true
swarmmode = true

[file]
  [backends]
    [backends.backend1]
      [backends.backend1.servers.server0]
      url = "http://127.0.0.1:8080"

  [frontends]
    [frontends.frontend1]
    backend = "backend1"
      [frontends.frontend1.routes.test_0]
      rule = "Host:traefik.xxx.com"
      [frontends.frontend1.redirect]
      entryPoint = "https"
```

### What did you expect to see?

With ingress mode:

```
10.255.0.2 - - [10/Apr/2018:15:12:12 +0000] "GET / HTTP/2.0" 200 20088 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0" 1 "Host-sample-recette-xxx-com-0" "https://10.0.2.19:443" 208ms
```

208ms is fine

### What did you see instead?

With host mode:

```
xxx.xxx.xxx.xxx - - [10/Apr/2018:15:02:30 +0000] "GET / HTTP/2.0" 200 20088 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0" 136 "Host-sample-recette-xxxxx-com-0" "https://10.0.2.19:443" 50145ms
```
50s is not fine.

reviewing the logs, I would say that it generates certs when on host mode whereas it finds them when on ingress mode. Could it be sufficient to explain the issue or could there be something else ?

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
grep -i acme traefik.log.debug
"level":"debug","msg":"No ACME certificate to generate for domains [\"traefik.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No ACME certificate to generate for domains [\"traefik.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No ACME certificate to generate for domains [\"portainer.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No ACME certificate to generate for domains [\"sample-backoffice.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No ACME certificate to generate for domains [\"sample-batches.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No ACME certificate to generate for domains [\"sample.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No ACME certificate to generate for domains [\"sample-static.recette.corp.com\"].","time":"2018-04-11T08:59:21Z"}
{"level":"debug","msg":"No provided certificate found for domains sample.recette.corp.com, get ACME certificate.","time":"2018-04-11T08:59:36Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for sample.recette.corp.com...","time":"2018-04-11T08:59:36Z"}
{"level":"debug","msg":"ACME got domain cert sample.recette.corp.com","time":"2018-04-11T08:59:36Z"}
{"level":"debug","msg":"No provided certificate found for domains sample-static.recette.corp.com, get ACME certificate.","time":"2018-04-11T09:00:27Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for sample-static.recette.corp.com...","time":"2018-04-11T09:00:27Z"}
{"level":"debug","msg":"ACME got domain cert sample-static.recette.corp.com","time":"2018-04-11T09:00:27Z"}
{"level":"debug","msg":"No provided certificate found for domains sample-static.recette.corp.com, get ACME certificate.","time":"2018-04-11T09:00:27Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for sample-static.recette.corp.com...","time":"2018-04-11T09:00:27Z"}
{"level":"debug","msg":"ACME got domain cert sample-static.recette.corp.com","time":"2018-04-11T09:00:27Z"}
```
