### ISSUE TITLE
Feature request - use matched regex in frontend as variable in backend

### ISSUE THREAD

**Issue by acvejic** [containous/traefik#3177]
### Feature request
```toml
[file]
[frontends]
  [frontends.frontend1]
      backend = "backend1"
      [frontends.frontend1.routes.example1]
          rule = "HostRegexp:{env:[A-Za-z0-9_-]+}-app1.example1.com"
[backends]
  [backends.backend1]
    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://$1-app1.example2.com"
```
# Is it possible to implement feature like this?
 - Use matched string from frontend as variable inside backend

 - This is kind of basic reverse proxy function and would be neat to have in traefik. I do have a workaround to point all this kind of frontends to different reverse proxy and implement it there. But it is an "ugly" solution.
