### ISSUE TITLE
301 redirect from http to https for Host rule frontends needs to write same frontend configuration for both http and https parts

### ISSUE THREAD

**Issue by chxzqw** [containous/traefik#3181]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Set up http to https redirect for frontends which use Host rule

### What did you expect to see?
301 redirect from http to https for certain domains by using [entryPoints.http.redirect]

### What did you see instead?
For 301 redirect from http to https to work, I need to write both http and https same Host rules for a frontend, otherwise when accessing the http it just gives a 404 error. I am not sure if this is by design or a bug.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]

[file]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "my@address.com"
  storage = "acme.json"
  onHostRule = true
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"

[frontends]

  # without the following http part, when accessing http link it doesn't redirect to https instead it just gives a 404 error
  # So not sure is this just by design that we need to write seperate part for both http and https or it is just a bug 
  [frontends.frontend1_http]
    backend = "backend1"
    passHostHeader = true
    entrypoints = ["http"]
    [frontends.frontend1_http.routes.domain]
      rule = "Host:www.mydomain.com"
  #http part ends

  [frontends.frontend1_https]
    backend = "backend1"
    passHostHeader = true
    passTLSCert = true
    entrypoints = ["https"]
    [frontends.frontend1_https.routes.domain]
      rule = "Host:www.mydomain.com"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
      url = "http://backend_url"

```
I have also tried using `entrypoints = ["http", "https"]` in frontend section, which doesn't work either.

**Comment by ldez** [comment]
You can try something like that:
```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "my@address.com"
  storage = "acme.json"
  onHostRule = true
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"

[api]

[file]

[frontends]

  [frontends.frontend1]
    backend = "backend1"
    passHostHeader = true
    # entrypoints = ["http", "https"]
    [frontends.frontend1.routes.domain]
      rule = "Host:www.mydomain.com"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
      url = "http://backend_url"
```
