### ISSUE TITLE
Traefik doesn't play nice with Rancher v1.6.16/v1.6.14 and/or Docker 17.12

### ISSUE THREAD

**Issue by dbsanfte** [containous/traefik#3186]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Upgraded from Rancher/server 1.6.12 to 1.6.16, and Docker 17.06 to 17.12 (in one go).

### What did you expect to see?

Traefik should have continued to pick up stacks/services and functioned as it did before the upgrade.

### What did you see instead?

Had to revert down to v1.6.14/Docker17.12 and then back to v1.6.12/Docker17.06 again, due to several issues:

1) Connections to Traefik randomly hanging (just times out)
2) Traefik missing Rancher services, backends not showing up properly, seemed random

Before rolling back Rancher/Docker changes, I tried reverting Traefik from 1.6.0-rc5 to 1.5.4, which seemed better for (2), (though maybe only because the upgrade process bounced the Traefik stack), but 1.5.4 still seemed to have problems with (1).

Reversion back to 1.6.12/17.06 resolved all these problems for both 1.5.4/1.6.0-rc5 with no other changes. There's obviously some sort of issue with Rancher v1.6.14+ and/or Docker 17.12. 

Apologies I wasn't able to nail it down to either Rancher/server or Docker, but it was a live platform and we had to revert quickly as the devs were getting antsy.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6.0-rc5 was definitely missing backends, no doubt. But both 1.6.0-rc5 and 1.5.4 would display the "connection randomly times out" issue. 

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

VMs themselves were running the Ubuntu 16.04-LTS (latest) version from Azure marketplace. Standard_DS11_v2 size.

Rancher Server v1.6.16 / Docker 17.12 ---> both problems
Rancher Server v1.6.14 / Docker 17.12 ---> both problems

```toml
################################################################
# Global configuration
################################################################

# Duration to give active requests a chance to finish during hot-reloads.
# Can be provided in a format supported by Go's time.ParseDuration function or
# as raw values (digits). If no units are provided, the value is parsed assuming
# seconds.
#
# Optional
# Default: "10s"
#
# graceTimeOut = "10s"

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
logLevel = "DEBUG"

# Backends throttle duration: minimum duration in seconds between 2 events from providers
# before applying a new configuration. It avoids unnecessary reloads if multiples events
# are sent in a short amount of time.
# Can be provided in a format supported by Go's time.ParseDuration function or
# as raw values (digits). If no units are provided, the value is parsed assuming
# seconds.
#
# Optional
# Default: "2s"
#
# ProvidersThrottleDuration = "5s"

# Controls the maximum idle (keep-alive) connections to keep per-host. If zero, DefaultMaxIdleConnsPerHost
# from the Go standard library net/http module is used.
# If you encounter 'too many open files' errors, you can either increase this
# value or change the `ulimit`.
#
# Optional
# Default: 200
#
# MaxIdleConnsPerHost = 200

# If set to true invalid SSL certificates are accepted for backends.
# Note: This disables detection of man-in-the-middle attacks so should only be used on secure backend networks.
# Optional
# Default: false
#
InsecureSkipVerify = true

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Web Dashboard port config
[web]
address = ":8000"

# Entrypoints definition
#
# Optional
# Default:
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#
# To redirect an http entrypoint to an https entrypoint (with SNI support):

[entryPoints]
  [entryPoints.http]
  address = ":80"

[entryPoints.https]
address = ":443"
  [entryPoints.https.tls]
  MinVersion = "VersionTLS12"
  CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/opt/config/ssl.cert"
    KeyFile = "/opt/config/ssl.key"

# To bind to a particular IP address only:
# [entryPoints]
#   [entryPoints.http]
#   address = "10.42.13.37:80"

# Enable retry sending request if network error
#
# Optional
#
[retry]

# Number of attempts
#
# Optional
# Default: (number servers in backend) -1
#
# attempts = 3


################################################################
# Rancher configuration backend
################################################################

# Enable Rancher configuration backend
#
# Optional
#
[rancher]

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on an service.
#
# Required
#
Domain = "rancher.localhost"

# Enable watch Rancher changes
#
# Optional
# Default: true
#
Watch = true

# Polling interval (in seconds)
#
# Optional
#
RefreshSeconds = 10

# Expose Rancher services by default in traefik
#
# Optional
# Default: true
#
# ExposedByDefault = false

# Filter services with unhealthy states and inactive states
#
# Optional
# Default: false
#
# EnableServiceHealthFilter = true

# Endpoint to use when connecting to the Rancher API
#
# Required
Endpoint = "http://rancher/v1/"

# AccessKey to use when connecting to the Rancher API
#
# Required
AccessKey = "**********************"

# SecretKey to use when connecting to the Rancher API
#
# Required
SecretKey = "**************************"



```
