### ISSUE TITLE
500 Error when metrics.prometheus is enabled

### ISSUE THREAD

**Issue by mavidser** [containous/traefik#3193]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Enabled `metrics.prometheus`

### What did you expect to see?
Metrics in prometheus, and a working server

### What did you see instead?
Metrics in prometheus, but no working server

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.0-rc5
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-12_09:50:36AM
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "DEBUG"
[entryPoints]
    [entryPoints.http]
    address = ":80"
[api]
[ping]
[docker]
endpoint = "tcp://192.168.1.8:2375"
[metrics]
[metrics.prometheus]
  entryPoint = "traefik"
  buckets = [0.1,0.3,1.2,5.0]
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-04-16T16:54:13Z" level=error msg="Recovered from panic in http handler: runtime error: invalid memory address or nil pointer dereference"
```
