### ISSUE TITLE
Regex/Replace strips parts of URL

### ISSUE THREAD

**Issue by SuperSandro2000** [containous/traefik#3212]
### What did you expect to see?

``http://sandro.example.net/portrainer/#/containers``
->
``https://sandro.example.net/portrainer/#/containers``

### What did you see instead?

``http://sandro.example.net/portrainer/#/containers``
->
``https://sandro.example.net/#/containers``

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/arm

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"

defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "sandro.example.net"
watch = true
exposedbydefault = false

[acme]
email = "[REMOVED]"
storage = "/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"

```
RPI 3b with Raspian Stretch

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

Edit: I tested it with Regex101 and it works there.
