### ISSUE TITLE
Using an external docker-compose.yml file from the one that contains Traefik returns "gateway timeout"

### ISSUE THREAD

**Issue by Drillan767** [containous/traefik#3214]
I'm currently setting up my server with Traefik where I launched Gogs, Portainer, Jenkins and some other similar tools with reverse proxy, so that Jenkins would be available at the address `jenkins.mydomain.me` and Portainer at `docker.mydomain.me` (for example)

I also would like to store my web projects, but it would be "better" for me not to use the same docker-compose.yml file and use another one that contains the specific environment files for the website for example.

So far, here is my "main" docker-compose.yml file:

```
version: '3.5'

services:
  traefik:
    image: traefik
    command: --api --docker
    networks:
      - default
    ports:
      - "80:80"
      - 8080
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:monitor.mydomain.me"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http,https"
# My other services (portainer, gogs, jenkins, etc)
```

And here is my "custom" docker-compose file:

version: '3'

```
services:
  stadium:
    image: my-repo/le-stadium
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=Stadium"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:le-stadium.mydomain.me"
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env.mysql
    labels:
      - "traefik.backend=MariaDB"
```

![capture du 2018-04-17 17-09-28](https://user-images.githubusercontent.com/16261166/39038223-3e0732fe-4483-11e8-9dd0-c793cb5b7981.png)

So, my database managed to start but not my website (it should appear in green on the right), and when I get to `le-stadium.mydomain.me`, I get "Gateway Timeout".

My question is the following: what can I do to link them both? I thought passing the port as a volume would be enough? Should I use a network? (I tried it once, it didn't go well so I guess I didn't set it up correctly)

Thank you in advance

**Comment by chrizzly123** [comment]
Hey,
I think you need to [add the services to the same network](https://docs.docker.com/compose/compose-file/#external-1) to create the connection between two stacks ([examples](https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects/)). 
Also, dont forget to add the  ["traefik.docker.network" label](https://docs.traefik.io/configuration/backends/docker/#using-docker-with-swarm-mode). 

Notice that with the current docker version 18.03, [this example](https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects/48024244#48024244)  with a constant network name [doesnt work yet for docker stack deploy](https://github.com/docker/cli/issues/938) but only for docker compose up. So in case you use docker stack deploy, you should take care that you use the correct network name which adds the stack name as prefix. As a temporary workaround for this, you could also use docker version 18.04 on the edge channel. 


Hope that could help at least a little bit and saves some time :)

**Comment by Drillan767** [comment]
Hello, I deeply apologize for answering only now !

I read your links and added the following line to each of my services' label (inside the main "docker-compose.yml" file)

```
- "traefik.docker.networks=default"
```

And added the following lines at the end of the file:

```
networks:
  default:
    external:
      name: some_network
```

In my other docker-compose file, I added the following line to both my services:

```
- "traefik.docker.networks=some_network"
```

I'm using docker-compose to run my images (not docker stack deploy), but I'm still having the same "Gateway timeout" problem.

Did I forget anything?
Thank you in advance
