### ISSUE TITLE
Troubles connecting two docker-compose files through docker network ("Gateway timeout")

### ISSUE THREAD

**Issue by Drillan767** [containous/traefik#3222]
(This issue follows up [#3214](https://github.com/containous/traefik/issues/3214), but I took too much time answering it so it got closed)

I'm currently trying to set up several docker-compose.yml files under the same Traefik system, but I'm getting the "Gateway Timeout" error.

According to the links provided  by @chrizzly123, when running a docker-compose file, a `default` networks gets set up for the docker-compose file and all the services it contains only, and it's not available for any external docker-compose.yml. However, you can make it available by adding the following after the `services` part of the file:

```
networks:
  default:
    external:
      name: custom_network
```

In my other docker-compose.yml file, I added the main docker-compose's network as follows:

```
version: '3'

services:
  stadium:
    image: jaeger767/le-stadium
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=Stadium"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:le-stadium.mydomain.me"
      - "traefik.docker.networks=custom_network" # I gave it the "external name" defined in the main docker-compose file
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env.mysql
    labels:
      - "traefik.backend=MariaDB"
      - "traefik.docker.networks=default"
      - "traefik.docker.networks=custom_network"
```

Maybe it's not relevant, but I had to manually create the network to give it its custom name, but after that, everything went fine, and all my services in the "main" docker-compose file got loaded without any trouble. However, this still gets me a "Gateway Timeout" error when trying to reach my subdomain

I added both my files in the following [Gist](https://gist.github.com/Drillan767/79af6a0e6ea8248a0bc7a073ecbcb3dd) just in case. I just don't know if I did well when setting up the "default" network for each service in the "main" file, it seems a bit useless: it works without adding the network part, but I didn't try while trying to connect another docker-compose file.

Thank you in advance, and sorry for the "spam"
