### ISSUE TITLE
Traefik with Kubernetes Ingress is unable to prepend uri path

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#3230]
*bug*

Given this config:
```yml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: util-testproxy-v0-prod-main-httpsecure
  namespace: volum
  annotations:
     traefik.frontend.rule.type: PathPrefix
     traefik.frontend.passHostHeader: "true"
     ingress.kubernetes.io/rewrite-target: /integration.test/2/
  labels:
    expose: external-httpsecure
spec:
  rules:
  - host: test-api.api.domain.no
    http:
      paths:
      - path: /
        backend:
          serviceName: util-testproxy-v0-prod-main
          servicePort: http

```
### What did you expect to see?
I would expect Traefik to to rewrite urls as such:
original url: `https://test-api.api.domain.no/things` --> url sent to backend: `http://<backend-ip>/integration.test/2/things`

### What did you see instead?
Instead, the original uri stem is simply stripped away, so the actual request sent to the backend becomes:
`http://<backend-ip>/integration.test/2/`

This isn't problematic in itself, but it seems that using Traefik with Kubernetes-ingress there's no way to prepend a "base path" to the request, while retaining (appending) the original uri.

Current functionality aligns well with the nginx ingress `nginx.ingress.kubernetes.io/rewrite-target`. However, nginx has the `nginx.ingress.kubernetes.io/add-base-url` annotation for prepending urls. It seems that Traefik is lacking this functionality.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.5.2
```

**Comment by giggio** [comment]
I can confirm the problem with `1.6.3`.

**Comment by qct** [comment]
any way to achieve this goal before the issue being fixed ?

**Comment by qct** [comment]
I found the solution described here: [gh-863](https://github.com/containous/traefik/issues/863):
```
annotations:
kubernetes.io/ingress.class: traefik
traefik.frontend.rule.type: ReplacePathRegex

 - backend:
     serviceName: aServer
     servicePort: 80
   path: /prefix/aServer/(.*) /aServer/$1
 - backend:
     serviceName: aSecondServer
     servicePort: 80
   path: /prefix/aSecondServer/(.*) /aSecondServer/$1
```
