### ISSUE TITLE
Support for a hard coded hostname for a Marathon app

### ISSUE THREAD

**Issue by raravena80** [containous/traefik#3232]
Feature.

### What did you do?

Setup marathon in basic config so that tasks get the following hostname:

`marathon-app-id`.mycustomdomain.com

### What did you expect to see?

I'd like to be able to configure the hostname dynamically or through some config file. I'm not sure if you can do this with the tmpl file, but couldn't find it documented anywhere.

So instead of 

`marathon-app-id`.mycustomdomain.com

I can configure something like

`my-custom-name`.mycustomdomain.com is an alias for `marathon-app-id`.mycustomdomain.com

This is similar to the behavior in [bamboo](https://github.com/QubitProducts/bamboo) in which you can configure an haproxy rule.

### What did you see instead?

hostnames are assigned the task id in marathon or if they are in subgroup, a combination of the task id with the subgroup name.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64```
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
    [entryPoints.http]
       address = ":81"

    [entryPoints.dash]
       address = ":8081"

[api]
entrypoint = "dash"
dashboard = true

################################################################
# Mesos/Marathon configuration backend
################################################################

[marathon]
endpoint = "http://marathon.mydomain.com"
watch = true
domain = "mydomain.com"

```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
