### ISSUE TITLE
frontends overlaps despite of priority setting

### ISSUE THREAD

**Issue by tipruzs** [containous/traefik#3255]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

- created single backend with two frontends and overlapping PathPrefixes
- added priorities and whitelistSourceRange

### What did you expect to see?

- frontend with whitelistSourceRange should work when source IP matches

### What did you see instead?

- frontend with whitelistSourceRange is ignorred

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[backends]
  [backends.backend0]
    [backends.backend0.servers]
      [backends.backend0.servers.server0]
        url = "http://x.x.x.x:8080"

[frontends]
  [frontends.public]
    backend = "backend0"
    passHostHeader = true
    priority = 20
    [frontends.public.routes]
      [frontends.public.routes.uri]
        rule = "PathPrefix:/app/rest"
  [frondends.protected]
    backend = "backend0"
    passHostHeader = true
    whitelistSourceRange = ["192.168.1.1/32"]
    priority = 10
    [frontends.protected.routes]
      [frontends.protected.routes.uri]
        rule = "PathPrefix:/app/rest/path/XXXX/args/"
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by arnested** [comment]
Could be a duplicate of #2323.

**Comment by geraldcroes** [comment]
Hi,

Thanks for reporting an issue.

Two problems in the provided configuration file : 
1) "frondend" instead of "frontend"
```
[frondends.protected] #must be [frontends.protected]
```

Since there is a typo here, your protected frontend ends up "not" having a backend and ignored.

You should see messages like these in traefik's logs
```
time="..." level=error msg="Undefined backend '' for frontend protected" 
time="..." level=error msg="Skipping frontend protected..." 
```


2) Priorities
A higher priority will be checked before a lower priority. Hence, since you gave `PathPrefix:/app/rest` a higher priority than `PathPrefix:/app/rest/.../`, the latter will never handle the request.

Could you confirm that these fix your problem?

**Comment by tipruzs** [comment]
@geraldcroes 
you wrote, it works for you. can you provide your working sample config for a review please?

**Comment by geraldcroes** [comment]
Sure, 

I've tweaked the example so you can easily try for yourself.

docker-compose.yml
```yml
version: '3'
  
services:
  traefik:
    image: traefik
    command: --api --file --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace/issue_3255/traefik.toml:/traefik.toml #replace with the path to your toml file
  service_1:
    image: emilevauge/whoami
  service_2:
    image: emilevauge/whoami
```

traefik.toml
```toml
[api]
  
[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://service_1/"
  [backends.backend2]
    [backends.backend2.servers]
      [backends.backend2.servers.server0]
        url = "http://service_2/"

[frontends]
  [frontends.public]
    backend = "backend1"
    passHostHeader = true
    priority = 10
    [frontends.public.routes]
      [frontends.public.routes.uri]
        rule = "PathPrefix:/app/rest"
  [frontends.protected]
    backend = "backend2"
    passHostHeader = true
    whitelistSourceRange = ["172.20.0.1/32"]
    priority = 20
    [frontends.protected.routes]
      [frontends.protected.routes.uri]
        rule = "PathPrefix:/app/rest/path/"
```
