### ISSUE TITLE
Authorization based on TLS client certificate

### ISSUE THREAD

**Issue by davidepedranz** [containous/traefik#3259]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
I am using Traefik with TLS Mutual Authentication to authenticate the devices allowed to access the services behind Traefik. I would like to use the content of the provided TLS client certificate to implement some kind of authorization based on the `Subject Name`. For example, allow the access only to clients with TLS certificates issued to a given `Organisation`. This should be dependent on the backend that handles the requests.

I tried to implement this with an external authentication server by enabling the feature "Forward Authentication" of Traefik and the option `passTLSCert` (as described here #2645).

### What did you expect to see?
I expected the external authentication server to receive some headers with the TLS client certificate used for the authentication.

### What did you see instead?
The external authentication server did not receive any information about the TLS client certificate used for the authentication. Optionally, it would be nice to also have the matching backend (in order not to repeat the routing logic in the external authentication server)/

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.0-rc6
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-17_11:59:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik is running inside the official Docker container (tag `v1.6.0-rc6`) on an Ubuntu 17.10 host.
It is configured to use Docker discovery to automatically set the routes. No options from the command line are used, just the following configuration file.

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    ]
    [entryPoints.https.tls.ClientCA]
      files = ["/client-ca.crt"]
      optional = false

# enable Let's Encrypt
[acme]
email = "some-email@example.com"
storage = "/acme.json"
acmeLogging = true
onHostRule = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"
[[acme.domains]]
  main = "{{ domain }}"

# discover services in Docker
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
swarmmode = false

# gui
[api]
dashboard = true

# metrics
[metrics]
  [metrics.prometheus]
  entryPoint = "traefik"
  buckets = [0.1,0.3,1.2,5.0]
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)
Nothing relevant to show.
