### ISSUE TITLE
Health check with hostname

### ISSUE THREAD

**Issue by mangareader** [containous/traefik#3260]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
setup traefik with file config
```toml
    [backends.insideapi_backend.servers]
      [backends.insideapi_backend.servers.server0]
      url = "http://ip:80"
      [backends.insideapi_backend.servers.server1]
      url = "http://ip:80"
    [backends.insideapi_backend.healthCheck]
      path = "/api/integrate/status"
      port = 80
      interval = "1s"
      hostname = "insideapi.local"
```
### What did you expect to see?
Traefik health check with url like this http://ip/api/integrate/status (with header Host:insideapi.local)

### What did you see instead?
Traefik health check with url like this http://ip/api/integrate/status (without hostname header)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.0
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-30_09:28:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": 0,
  "GraceTimeOut": 0
 },
 "GraceTimeOut": 0,
 "Debug": false,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "Tracing": null,
 "LogLevel": "",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "AllowMinWeightZero": false,
 "Web": null,
 "Docker": null,
 "File": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": ""
}
```
