### ISSUE TITLE
ECS Fargate

### ISSUE THREAD

**Issue by boskiv** [containous/traefik#3270]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When I start treafik on fargate with next configuration:
```toml
################################################################
# ECS configuration backend
################################################################

# Enable ECS configuration backend.
[ecs]
clusters = ["testTraefik"]
domain = "ecs.localhost"
```
I've got an error in logs:
```
time="2018-05-05T12:30:34Z" level=error msg="Provider connection error EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: dial tcp 169.254.169.254:80: connect: invalid argument, retrying in 1.097723019s"
```

Is it possible to run traefik as LB in Fargate instances ?
