### ISSUE TITLE
Unable to access services after upgrading to 1.6.0 on Docker Swarm

### ISSUE THREAD

**Issue by ulm0** [containous/traefik#3271]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Upgraded from 1.5.4 to 1.6.0

### What did you expect to see?

Be able to access services proxied by Traefik

### What did you see instead?

`404` error pages on every single service (but the traefik one)

### Output of `traefik version`:

```sh
Version:      v1.6.0
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-30_09:28:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- Bare metal docker swarm.
- Docker CE v18.03
- docker-compose.yml for traefik

```yaml
# Stack name: watch
version: "3.6"
networks:
  the-force:
    external: true
  monitoring:
    external: true
configs:
  traefik_config:
    file: ./traefik/data/traefik.toml
volumes:
  traefik-acme:
    driver: nfs
    driver_opts:
      share: "192.168.0.20:/traefik/acme"
  traefik-logs:
    driver: nfs
    driver_opts:
      share: "192.168.0.20:/traefik/log"
services:
  traefik:
    image: traefik:1.6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
      - traefik-logs:/log
    command: -c /config/traefik.toml
    configs:
      - source: traefik_config
        target: /config/traefik.toml
    environment:
      - DNSIMPLE_EMAIL=[MAIL]
      - DNSIMPLE_OAUTH_TOKEN=[REDACTED]
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    networks:
      - the-force
      - monitoring
    deploy:
      labels:
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=proxy"
        - "traefik.docker.network=the-force"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:b.innersea.xyz"
        - "traefik.port=8080"
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
```

- config.toml for traefik

```toml
logLevel = "DEBUG"
debug = true
checkNewVersion = true
ProvidersThrottleDuration = "5s"
MaxIdleConnsPerHost = 200
defaultEntryPoints = ["http", "https"]
[lifeCycle]
requestAcceptGraceTimeout = "10s"
graceTimeOut = "10s"
[traefikLog]
filePath = "log/traefik.log"
format = "json"
[accessLog]
filePath = "log/access.log"
format = "json"
[retry]
attempts = 3
[healthcheck]
interval = "30s"
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
    address=":8080"
    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
      users = ["USER:REDACTED"]
[api]
  entryPoint = "api"
  dashboard = true
  debug = true
[api.statistics]
  RecentErrors = 10
[metrics]
  [metrics.statistics]
    recentErrors = 10
  [metrics.prometheus]
    entryPoint = "api"
    buckets = [0.1,0.3,1.2,5.0]
[rest]
  entryPoint = "api"
[ping]
  entryPoint = "api"
[acme]
email = "[MAIL]"
storage = "acme/acme.json"
entryPoint = "https"
OnHostRule = true
acmeLogging = true
  [acme.dnsChallenge]
  provider = "dnsimple"
  delayDontCheckDNS = 0
  [acme.httpChallenge]
  entryPoint = "http"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "b.innersea.xyz"
watch = true
swarmmode = true
```

- After upgrading one more `acme` file appeared

```sh
$ sudo ls -lsh traefik/acme
total 184K
88K -rw------- 1 root root 88K may  6 00:32 acme.json
96K -rw------- 1 root root 94K may  6 00:32 acme.json.bak
```

- As you can see, I've exposed my traefik dashboard so i can access it from the outside world, but for some reason this is the only service i can access (e.g: when trying to access my minio instance i get a 404 error page)

![image](https://user-images.githubusercontent.com/13160093/39669731-c190ea9a-50ca-11e8-9526-12bc9978f88a.png)

Yet it shows up in my traefik dashboard

![image](https://user-images.githubusercontent.com/13160093/39669740-f6939e90-50ca-11e8-87ed-6b3d11b4761a.png)

- minio compose file

```yaml
# Stack name: minio
version: "3.6"
networks:
  the-force:
    external: true
volumes:
  minio-data:
    driver: nfs
    driver_opts:
      share: "192.168.0.20:/minio/data"
  minio-config:
    driver: nfs
    driver_opts:
      share: "192.168.0.20:/minio/config"
secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
services:
  storage:
    image: minio/minio:RELEASE.2018-05-04T23-13-12Z
    networks:
      - the-force
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    secrets:
      - minio_access_key
      - minio_secret_key
    command: server /data
    environment:
      - "MINIO_ACCESS_KEY_FILE=minio_access_key"
      - "MINIO_SECRET_KEY_FILE=minio_secret_key"
    deploy:
      labels:
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=minio"
        - "traefik.docker.network=the-force"
        - "traefik.entrypoints=https"
        - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-For:https"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.customrequestheaders=X-Forwarded-Ssl:on"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.passTLSCert=true"
        - "traefik.frontend.rule=Host:s.ulm0.xyz"
        - "traefik.port=9000"
      placement:
        constraints:
          - node.labels.arch == amd64
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first

```
