### ISSUE TITLE
Unsolicited response received on idle HTTP channel

### ISSUE THREAD

**Issue by Overbryd** [containous/traefik#3295]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Running traefik `1.6.0` under Kubernetes
- Checked the logs
- Found this message

### What did you expect to see?

- Not this message

### What did you see instead?

```
2018/05/09 09:50:45 transport.go:1748: Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 100 Continue\r\n\r\n"; err=<nil>
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

`1.6.0`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    defaultEntryPoints = ["http", "https"]
    logLevel = "ERROR"

    [web]
    address = ":8080"
      [web.metrics.datadog]
      # will be overwritten by --web.metrics.datadog.address=$STATSD_HOST
      address = "localhost:8125"
      pushinterval = "1s"
      # enable more detailed statistics
      [web.statistics]
      recentErrors = 100

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]

    [consul]
    prefix = "traefik"
    endpoint = "consul:8500"

    [acme]
    acmeLogging = true
    email = "private@email.com"
    storage = "traefik/acme/account"
    onHostRule = true
    entryPoint = "https"
    [acme.httpChallenge]
      entryPoint = "http"
```
