### ISSUE TITLE
Traefik 1.6 ACME error: Cannot get ACME client directory missing new registration URL

### ISSUE THREAD

**Issue by NDevox** [containous/traefik#3296]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Setup Traefik 1.6 in a 1.8 k8s cluster using helm with staging ACME enabled.

### What did you expect to see?

Successful calls to lets encrypt in the logs - confirming ACME is setup properly.

### What did you see instead?

Errors such as:

```
time="2018-05-09T10:06:31Z" level=error msg="Unable to obtain ACME certificate for domains \"<ur>\" detected thanks to rule \"Host:<url>\" : cannot get ACME client directory missing new registration URL"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.6.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`helm install stable/traefik --values traefik.yaml --name traefik --namespace kube-system`

and values:

```yml
# traefik.yaml
imageTag: 1.6.0
ssl:
        enabled: true
        enforced: true
acme:
        enabled: true
        email: <email>
        challengeType: http-01
        staging: true
dashboard:
        enabled: true
        domain: <url>
        auth:
                basic: 
                        <auth mapping>
rbac:
        enabled: true
```
