### ISSUE TITLE
Traefik fails to start after enabling redirect to https via CLI

### ISSUE THREAD

**Issue by flokli** [containous/traefik#3298]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I wanted to set up traefik inside a docker container, configuring backends and frontends via a separate `rules.toml`.
I used an old example configuration before #2798 got in, so used the configuration from below, but without the single quotes at the `--entrypoints=` arguments. This kinda worked, with the exception of the SSL redirect not happening.

After following up with #2798, I changed my configuration as shown below.

### What did you expect to see?
Traefik now trying to redirect from HTTP to HTTPS

### What did you see instead?
Traefik failing to start:
```
time="2018-05-09T13:57:33Z" level=fatal msg="Unknown entrypoint \"'https'\" for provider ACME configuration"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.0
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-30_09:28:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`docker-compose.yaml`:
```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:alpine
    command:
      - "--api"
      - "--entrypoints='Name:http Address::80 Redirect.EntryPoint:https'"
      - "--entrypoints='Name:https Address::443 TLS'"
      - "--defaultentrypoints=http,https"

      - "--acme" 
      - "--acme.storage=/etc/traefik/acme/acme.json" 
      - "--acme.entryPoint=https" 
      - "--acme.httpChallenge.entryPoint=http" 
      - "--acme.OnHostRule=true" 
      - "--acme.onDemand=false" 
      - "--acme.email=my@email.invalid" 
      - "--file.filename=/etc/traefik/rules.toml"
    ports: 
      - "80:80" 
      - "443:443" 
      - "8080:8080" 
    volumes: 
      - acme-storage:/etc/traefik/acme 
      - ./rules.toml:/etc/traefik/rules.toml 
volumes: 
  acme-storage:
```

`rules.toml` only contains `[backend]` and `[frontend]` sections, no enty-point specifics here.
