### ISSUE TITLE
kubernetes with port redirect in service

### ISSUE THREAD

**Issue by damoon** [containous/traefik#330]
```
# 3 Services for the 3 endpoints of the Ingress
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: whoami
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: whoami
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: whoami
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app: whoami
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: echoserver
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: whoami
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: emilevauge/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.3
        ports:
        - containerPort: 8080
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
  rules:
  - host: foo.localhost
    http:
      paths:
      - path: /bar
        backend:
          serviceName: service3
          servicePort: 8080
  - host: bar.localhost
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 80
      - backend:
          serviceName: service1
          servicePort: 80
```
