### ISSUE TITLE
Trying to use custom error pages show errors in Traefik logs

### ISSUE THREAD

**Issue by claflico** [containous/traefik#3301]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Attempt to utilize the custom error pages with Rancher that was introduced in 1.6. Added the new labels to the Rancher service. Created a custom error pages container, added a host rule, confirmed that the error pages are browsable via that host rule url. Browse to an known invalid url for the test service with the new custom error config. 

### What did you expect to see?

Our custom 404 error page.

### What did you see instead?

"Internal Server Error" and errors in the logs. Some other api services started producing a 404. After removing custom error config labels from the test service I had to restart the traefik container before the test service or the other api services would load properly.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.0
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-30_09:28:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>
<summary>Docker-compose from Rancher interface:</summary>

```yaml
version: '2'
services:
  error:
    image: docker.ops.domain2.com/ops-errorpages:latest
    labels:
      traefik.frontend.rule: Host:errorpages.qa.domain2.xyz
      traefik.enable: 'true'
      traefik.backend: errorpages
      traefik.tags: external
      logforwarding: 'true'
      io.rancher.scheduler.affinity:host_label: web=true
      traefik.port: '80'
      io.rancher.container.hostname_override: container_name
  webtest:
    image: docker.ops.domain2.com/bou-web:latest
    labels:
      role: web
      traefik.enable: 'true'
      traefik.tags: external,web,bou
      logforwarding: 'true'
      project: bou
      traefik.port: '80'
      io.rancher.container.pull_image: always
      traefik.frontend.rule: Host:bouweb.qa.domain2.xyz
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      traefik.frontend.errors.bouweb404.status: '["404"]' 
      ####NOTE: I'VE TRIED BOTH WITH AND WITHOUT QUOTES & JUST THE NUMBER ALONE###
      io.rancher.scheduler.affinity:host_label: web=true
      io.rancher.container.hostname_override: container_name
      traefik.frontend.errors.bouweb404.query: /bou/error_404.html
      traefik.frontend.errors.bouweb404.backend: errorpages
```

</details>

<details>
<summary># traefik.toml</summary>

```toml

debug = true
logLevel = "INFO"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]
sendAnonymousUsage = false

[traefikLog]
  filePath = "/opt/traefik/log/traefik.log"

[accessLog]
  filePath = "/opt/traefik/log/access.log"

[respondingTimeouts]
  readTimeout = "0s"
  writeTimeout = "0s"
  idleTimeout = "180s"

[forwardingTimeouts]
  dialTimeout = "30s"
  responseHeaderTimeout = "0s"

[entryPoints]
  [entryPoints.traefik]
    address = ":8000"
    compress = true
  [entryPoints.http]
    address = ":80"
    compress = true
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      MinVersion = "VersionTLS12"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.domain1.com.crt"
          keyFile = "/opt/traefik/certs/star.domain1.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.corp.domain2.com.crt"
          keyFile = "/opt/traefik/certs/star.corp.domain2.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.dev.domain2.xyz.crt"
          keyFile = "/opt/traefik/certs/star.dev.domain2.xyz.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.ops.domain2.com.crt"
          keyFile = "/opt/traefik/certs/star.ops.domain2.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.prd.domain2.com.crt"
          keyFile = "/opt/traefik/certs/star.prd.domain2.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.qa.domain2.xyz.crt"
          keyFile = "/opt/traefik/certs/star.qa.domain2.xyz.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.domain3.com.crt"
          keyFile = "/opt/traefik/certs/star.domain3.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.domain2.com.crt"
          keyFile = "/opt/traefik/certs/star.domain2.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.uat.domain3.com.crt"
          keyFile = "/opt/traefik/certs/star.uat.domain3.com.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/star.uat.domain2.xyz.crt"
          keyFile = "/opt/traefik/certs/star.uat.domain2.xyz.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/opt/traefik/certs/traefik.crt"
          keyFile = "/opt/traefik/certs/traefik.key"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
  [api.statistics]
    RecentErrors = 10

[rest]
  entryPoint = "traefik"

[ping]
  entryPoint = "traefik"


[rancher]
  domain = "qa.domain2.xyz"
  Watch = true
  RefreshSeconds = 15
  ExposedByDefault = false
  EnableServiceHealthFilter = false
  constraints = [ "tag==external" ]
  [rancher.metadata]
    IntervalPoll = false
    Prefix = "/2016-07-29"
```

</details>

<details>
<summary>json</summary>

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": 0,
  "GraceTimeOut": 0
 },
 "GraceTimeOut": 0,
 "Debug": false,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "Tracing": null,
 "LogLevel": "",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "AllowMinWeightZero": false,
 "Web": null,
 "Docker": null,
 "File": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": ""
}
```

</details>

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

<details>
<summary>logs</summary>

```
5/9/2018 2:09:43 PM'traefik' process is not running
5/9/2018 2:09:43 PM'traefik' process is not running
5/9/2018 2:09:43 PM'traefik' trying to restart
5/9/2018 2:09:43 PM'traefik' start: '/opt/traefik/bin/traefik-service.sh start'
5/9/2018 2:09:43 PMWed May 9 14:09:43 CDT 2018 - [ Generating traefik configuration... ]
5/9/2018 2:09:43 PMWed May 9 14:09:43 CDT 2018 - [ Redirecting traefik log... ]
5/9/2018 2:09:43 PMWed May 9 14:09:43 CDT 2018 - [ Redirecting traefik log... ]
5/9/2018 2:09:43 PMWed May 9 14:09:43 CDT 2018 - [ Starting traefik... ]
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Using TOML configuration file /opt/traefik/etc/traefik.toml"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Traefik version v1.6.0 built on 2018-04-30_09:28:44PM"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Preparing server traefik &{Address::8000 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc420568080} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc4205680a0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Preparing server https &{Address::443 TLS:0xc420365c80 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc4205680c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Starting server on :8000"
5/9/2018 2:09:43 PMtime="2018-05-09T14:09:43-05:00" level=info msg="Starting server on :80"
5/9/2018 2:09:44 PMtime="2018-05-09T14:09:44-05:00" level=info msg="Starting provider configuration.providerAggregator {}"
5/9/2018 2:09:44 PMtime="2018-05-09T14:09:44-05:00" level=info msg="Starting server on :443"
5/9/2018 2:09:44 PMtime="2018-05-09T14:09:44-05:00" level=info msg="Starting provider *rest.Provider {\"EntryPoint\":\"traefik\"}"
5/9/2018 2:09:44 PMtime="2018-05-09T14:09:44-05:00" level=info msg="Starting provider *rancher.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[\"tag==external\"],\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"AccessKey\":\"\",\"SecretKey\":\"\",\"API\":null,\"Metadata\":{\"IntervalPoll\":false,\"Prefix\":\"/2016-07-29\"},\"Domain\":\"qa.domain2.xyz\",\"RefreshSeconds\":15,\"ExposedByDefault\":false,\"EnableServiceHealthFilter\":false}"
5/9/2018 2:09:44 PMtime="2018-05-09T14:09:44-05:00" level=error msg="Near line 569 (last key parsed 'frontends.frontend-Host-bouweb-qa-domain2-xyz.errors.bouweb404.status'): expected a comma or array terminator ']', but got '4' instead"
5/9/2018 2:09:46 PMtime="2018-05-09T14:09:46-05:00" level=error msg="Near line 569 (last key parsed 'frontends.frontend-Host-bouweb-qa-domain2-xyz.errors.bouweb404.status'): expected a comma or array terminator ']', but got '4' instead"
5/9/2018 2:09:47 PMtime="2018-05-09T14:09:47-05:00" level=error msg="Near line 569 (last key parsed 'frontends.frontend-Host-bouweb-qa-domain2-xyz.errors.bouweb404.status'): expected a comma or array terminator ']', but got '4' instead"
5/9/2018 2:09:50 PMtime="2018-05-09T14:09:50-05:00" level=error msg="Near line 569 (last key parsed 'frontends.frontend-Host-bouweb-qa-domain2-xyz.errors.bouweb404.status'): expected a comma or array terminator ']', but got '4' instead"
5/9/2018 2:09:52 PMtime="2018-05-09T14:09:52-05:00" level=error msg="Near line 569 (last key parsed 'frontends.frontend-Host-bouweb-qa-domain2-xyz.errors.bouweb404.status'): expected a comma or array terminator ']', but got '4' instead"
```

</details>

I've tried following the examples I found here:
https://docs.traefik.io/v1.6/configuration/commons/
https://github.com/containous/traefik/issues/3144
