### ISSUE TITLE
Unable to obtain ACME certificate for domains: generate certificate with no value

### ISSUE THREAD

**Issue by stepankuzmin** [containous/traefik#3303]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've setup two services `gulagmap.ru` and `mygulag.ru` and traefik as as proxy. They both obtained valid certificates, but the next day, without any changes, one of the services lost a certificate. I've tried to regenerate it with restarting both traefik and `mygulag.ru`, but it had no effect.

### What did you expect to see?

traefik generates valid certificate

### What did you see instead?

traefik generates certificate with no value

### Output of `traefik version`:

```
Version:      v1.6.0
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-30_09:28:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose.yml

```yml
version: '3.6'

services:
  traefik:
    image: traefik:1.6.0-alpine
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik:/etc/traefik:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    command:
      - --logLevel=DEBUG
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.email=hello@urbica.co
      - --acme.storage=/etc/traefik/acme.json
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.OnHostRule=true
      - --acme.onDemand=false
      - --acme.acmeLogging=true
      - --web
      - --docker
      - --docker.watch
      - --docker.exposedbydefault=false

networks:
  proxy:
    external: true
```

docker-compose.yml for `mygulag.ru` service

```yml
version: '3.6'

services:
  mygulag-archivist:
    build: .
    container_name: mygulag-archivist
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=5000
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:mygulag.ru
    networks:
      - proxy
      - internal
    depends_on:
      - mygulag-db

  mygulag-db:
    image: mdillon/postgis:9.6-alpine
    container_name: mygulag-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    external: false
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Creating route route-frontend-Host-mygulag-ru-0 Host:mygulag.ru"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Creating backend backend-mygulag-archivist-mygulag"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Creating load-balancer wrr"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Creating server server-mygulag-archivist at http://172.19.0.2:5000 with weight 1"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Add certificate for domains gulagmap.ru"
traefik    | time="2018-05-10T14:31:52Z" level=info msg="Server configuration reloaded on :443"
traefik    | time="2018-05-10T14:31:52Z" level=info msg="Server configuration reloaded on :8080"
traefik    | time="2018-05-10T14:31:52Z" level=info msg="Server configuration reloaded on :80"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Try to challenge certificate for domain [mygulag.ru] founded in Host rule"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Try to challenge certificate for domain [gulagmap.ru] founded in Host rule"
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Looking for provided certificate(s) to validate [\"gulagmap.ru\"]..."
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="No ACME certificate to generate for domains [\"gulagmap.ru\"]."
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Looking for provided certificate(s) to validate [\"mygulag.ru\"]..."
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Domains [\"mygulag.ru\"] need ACME certificates generation for domains \"mygulag.ru\"."
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Loading ACME certificates [mygulag.ru]..."
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="Building ACME client..."
traefik    | time="2018-05-10T14:31:52Z" level=debug msg="https://acme-v02.api.letsencrypt.org/directory"
traefik    | time="2018-05-10T14:31:53Z" level=debug msg="Using HTTP Challenge provider."
traefik    | legolog: 2018/05/10 14:31:53 [INFO][mygulag.ru] acme: Obtaining bundled SAN certificate
traefik    | time="2018-05-10T14:31:53Z" level=error msg="Unable to obtain ACME certificate for domains \"mygulag.ru\" detected thanks to rule \"Host:mygulag.ru\" : domains [mygulag.ru] generate certificate with no value: {    [] [] [] []}"
```
