### ISSUE TITLE
Traefik does not find my backend service when used as ingress controller

### ISSUE THREAD

**Issue by vahidfar7** [containous/traefik#3309]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I created traefik deployment , service and ingress as follows in aws cluster:
```yml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - image: traefik
        name: traefik
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --web
        ports:
        - containerPort: 8080
          name: traefikweb
        - containerPort: 80
          name: traefikproxy

---

apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy
spec:
  selector:
    app: traefik
  ports:
  - port: 80
    targetPort: traefikproxy
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
spec:
  selector:
    app: traefik
  ports:
  - name: http
    targetPort: 8080
    nodePort: 30001
    port: 80
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ing 
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
        - path: /ui
          backend:
            serviceName: traefik-web-ui
            servicePort: 80
```

### What did you expect to see?

I expected to hit my loadbalanncer/ui and get to traefik ui

### What did you see instead?
404
