### ISSUE TITLE
Traefik does not register backend services when any service has a configuration error

### ISSUE THREAD

**Issue by littleninja** [containous/traefik#3313]
### Do you want to request a *feature* or report a *bug*?
BUG

### What did you do?

1. Deploy a service (BorkService) to Service Fabric cluster with an invalid ServiceManifest.xml

```xml
<StatelessServiceType ServiceTypeName="BorkServiceType" UseImplicitHost="true">
  <Extensions>
    <Extension Name="Traefik">
      <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
        <Label Key="traefik.frontend.rule.borkservice">PathPrefixStrip: /bork</Label>
        <Label Key="traefik.enable">true</Label>
        <Label Key="traefik.frontend.entryPoints">["https","http"]</Label>
      </Labels>
    </Extension>
  </Extensions>
</StatelessServiceType>
```

2. Deploy another service (GoodService) to cluster with a valid ServiceManifest.xml
3. Deploy Traefik to cluster.

### What did you expect to see?
Traefik should register GoodService but not BorkService.

### What did you see instead?
Neither backend service registers. Traefik Dashboard UI is entirely blank except for header. Errors are not visible unless viewing Traefik logs on server.

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.6.0

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

*Provider: Service Fabric v6.1.480.9494*
*Platform: Windows Server 2016 Datacenter*

```toml
################################################################
# Global configuration
################################################################

InsecureSkipVerify = true

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#

[traefikLog]
  filePath = "traefik.log"

# Log level
#
# Optional
# Default: "ERROR"

logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["https","http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":30080"
  [entryPoints.https]
  address = ":30443"
    [entryPoints.https.proxyProtocol]
      insecure = true
    [entryPoints.https.tls]
      [entryPoints.https.tls.ClientCA]
      optional = true
      [[entryPoints.https.tls.certificates]]
      certFile = "localhost.cert"
      keyFile = "localhost.key"
[entryPoints.traefik]
address = ":38080"


################################################################
# API definition
################################################################

[api]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

################################################################
# Service Fabric provider
################################################################

# Enable Service Fabric configuration backend
[servicefabric]

# Service Fabric Management Endpoint
clustermanagementurl = "https://localhost:19080"

# Service Fabric Management Endpoint API Version
apiversion = "3.0"

# Enable TLS connection.
#
# Optional
#
[serviceFabric.tls]
  cert = "traefikcert.crt"
  key = "traefikkey.key"
  insecureskipverify = true
  caoptional = true


```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-05-11T19:54:07Z" level=error msg="Provider connection error: Near line 133 (last key parsed 'frontends.frontend-fabric:/BorkService/BorkService.entryPoints'): expected a comma or array terminator ']', but got 'h' instead; retrying in 1.008273491s"
```

**Comment by ldez** [comment]
Thanks for your interest in Traefik !

It's the expected behavior.

----

Note your configuration contains errors:

```toml
InsecureSkipVerify = true

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#

[traefikLog]
  filePath = "traefik.log"

# Log level
#
# Optional
# Default: "ERROR"

logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["https","http"]

# ...
```

I remove comments:
```toml
InsecureSkipVerify = true
debug = true

[traefikLog]
  filePath = "traefik.log"
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

# ...
```

**TOML is not base on indentation.**

You must write your configuration like that:

```toml
InsecureSkipVerify = true
debug = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[traefikLog]
  filePath = "traefik.log"

# ...
```

**Comment by littleninja** [comment]
Thanks and good find, @ldez. We fixed our toml and redeployed but we're still seeing this issue. Our thought's that this is probably an issue with ServiceManifest.xml, removing the entrypoints label resolved the issue in our case.

Here is our current toml:

```toml
################################################################
# Global configuration
################################################################

InsecureSkipVerify = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

#debug = true
#[traefikLog]
#  filePath = "traefik.log"

[entryPoints]
  [entryPoints.http]
  address = ":30080"
    [entryPoints.http.proxyProtocol]
      insecure = true
  [entryPoints.https]
  address = ":30443"
    [entryPoints.https.proxyProtocol]
      insecure = true
    [entryPoints.https.tls]
      [entryPoints.https.tls.ClientCA]
      optional = true
      [[entryPoints.https.tls.certificates]]
      certFile = "localhost.cert"
      keyFile = "localhost.key"
[entryPoints.traefik]
address = ":38080"

################################################################
# API definition
################################################################

[api]
  entryPoint = "traefik"
  dashboard = true

################################################################
# Service Fabric provider
################################################################

[servicefabric]
clustermanagementurl = "https://localhost:19080"
apiversion = "3.0"

[serviceFabric.tls]
  cert = "traefikcert.crt"
  key = "traefikkey.key"
  insecureskipverify = true
  caoptional = true

```
