### ISSUE TITLE
reverse proxy web ui with path routing

### ISSUE THREAD

**Issue by chinakevinguo** [containous/traefik#3318]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: k8s.com
    http:
      paths:
      - path: /traefik
        backend:
          serviceName: traefik-web-ui
          servicePort: 80
      - path: /k8s-dashboard
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
```

### What did you expect to see?
normal result like access root path

### What did you see instead?
http://k8s.com/api/version 
404 not found

but access http://k8s.com/traefik/api/version is ok 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
kubernetes cluster
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
