### ISSUE TITLE
File frontend and Docker backend

### ISSUE THREAD

**Issue by AvoMMH** [containous/traefik#3320]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?
I have set up a large scaled micro service with many replicas per backend.
Using the default way to organize the frontendrules, with labels, I get a mess of frontends in my dashboard.
So I tried to configure my frontends within a traefik.toml, it now creates the frontends properly, as I can see in my dashboard, but it wont connect the file-configured frontends to the docker backends.

### What did you expect to see?
My frontends which I defined in a .toml file connected with my backends from docker.

### What did you see instead?
Independent backends and frontends for file and docker configuration.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# rules.toml
[backends]
  [backends.whoamiMassBack]

[frontends]
  [frontends.whoamiMassFront]
  backend = "whoamiMassBack"
    [frontends.whoamiMassFront.routes.test_1]
    rule = "Host:whoami.localhost"
```

```toml
# traefik.toml

 traefikLogsFile = "/var/log/traefik.log"
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true

[file]
watch = true
filename = "/etc/traefik/rules.toml"
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```

```
