### ISSUE TITLE
Kubernetes scheme bug

### ISSUE THREAD

**Issue by ekozan** [containous/traefik#333]
Some of my service as shown as ://x.x.x.x:80  and traefik fail 

you can check the logs http://pasted.co/18838070

**Comment by mgoodness** [comment]
I got around this one by naming each port in my backend services with its scheme:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wip
    branch: andy
    environment: stage
  name: wip-stage-test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: wip
    branch: andy
    environment: stage
```
