### ISSUE TITLE
PathPrefixStrip does not work without a trailing slash "/" as part of the path

### ISSUE THREAD

**Issue by BroBan** [containous/traefik#3330]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Created a kubernetes traefik ingress to handle multiple versions of the backend like below:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: balance
 namespace: sit
 annotations:
   kubernetes.io/ingress.class: traefik
   traefik.frontend.rule.type: PathPrefixStrip
spec:
 rules:
   - host: xx.domain.com
   http:
     paths:
     - path: /v1
       backend:
         serviceName: service1
         servicePort: http
     - path: /v2
       backend:
         serviceName: service2
         servicePort: http
```

### What did you expect to see?

| URL Passed | URL Post Prefix strip |
| ------------- | ------------- |
| xx.domain.com/v1/docs | xx.domain.com/v1/docs  |
| xx.domain.com/v2/docs | xx.domain.com/v2/docs |
| xx.domain.com/v1/docs/ | xx.domain.com/v1/docs  |
| xx.domain.com/v2/docs/ | xx.domain.com/v2/docs |

### What did you see instead?

| URL Passed | URL Post Prefix strip |
| ------------- | ------------- |
| xx.domain.com/v1/docs | xx.domain.com/docs  |
| xx.domain.com/v2/docs | xx.domain.com/docs |
| xx.domain.com/v1/docs/ | xx.domain.com/v1/docs  |
| xx.domain.com/v2/docs/ | xx.domain.com/v2/docs |

Since my ingress object is defined to listen to paths starting with /v1 and /v2 - the first 2 examples end up requesting /docs and therefore a 404 is returned.

If i put the trailing slash then everything gets routed correctly and to the correct backend service, but as soon as the trailing slash is removed - it causes hell.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
"Traefik version v1.6.1 built on 2018-05-14_07:16:56PM"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
traefik.toml
```
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [acme]
    email = "info@domain.com"
    storage = "/etc/traefik/acme.json"
    entryPoint = "https"
    [acme.httpChallenge]
    entryPoint = "http"
    onHostRule = true
    caServer = "https://acme-v01.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "domain.com"
    sans = ["xx.domain.com"]

```
