### ISSUE TITLE
High disk read usage

### ISSUE THREAD

**Issue by colinlabs** [containous/traefik#3341]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
traefik running in kubernetes,traefik had read 50G+ data，but i don't known what it is, it's normal when restart traefik,but A few minutes later, it cause high disk read usage too

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.0-rc6
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-17_11:59:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
labelselector = "realm=internal"
[accessLog]
format = "json"
```

![wx20180517-144019](https://user-images.githubusercontent.com/10361796/40164090-33e3710c-59eb-11e8-819f-bc9936fe532b.png)
