### ISSUE TITLE
Missing frontend and backend (docker provider)

### ISSUE THREAD

**Issue by rpieciorak** [containous/traefik#3360]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

After upgrade to `traefik-1.6.1` some of my frontends and backends are missing.
Before upgrade I've had following labels:

```
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:api.localapp.com"
    - "traefik.default.protocol=http"
    - "traefik.private.frontend.rule=Host:studio.localapp.com"
    - "traefik.private.frontend.auth.basic=user:$$apr1$$qTZTddGQ$Vsom07noptUAR0yGpld8Q."
```

and following frontends:

```
{
   ...,
  "frontend-traefik-whoami1-1-whoami-default": {
    "entryPoints": [
      "http"
    ],
    "backend": "backend-traefik-whoami1-1-whoami-default",
    "routes": {
      "route-frontend-traefik-whoami1-1-whoami-default": {
        "rule": "Host:api.localapp.com"
      }
    },
    "passHostHeader": true,
    "priority": 0,
    "basicAuth": []
  },
  "frontend-traefik-whoami1-1-whoami-private": {
    "entryPoints": [
      "http"
    ],
    "backend": "backend-traefik-whoami1-1-whoami-private",
    "routes": {
      "route-frontend-traefik-whoami1-1-whoami-private": {
        "rule": "Host:studio.localapp.com"
      }
    },
    "passHostHeader": true,
    "priority": 0,
    "basicAuth": [
      "user:$apr1$qTZTddGQ."
    ]
  }
}
```

and following backends:

```
{
   ...,
  "backend-traefik-whoami1-1-whoami-default": {
    "servers": {
      "server-default-traefik-whoami1-1-0": {
        "url": "http://172.17.0.3:80",
        "weight": 1
      }
    },
    "loadBalancer": {
      "method": "wrr"
    }
  },
  "backend-traefik-whoami1-1-whoami-private": {
    "servers": {
      "server-private-traefik-whoami1-1-0": {
        "url": "http://172.17.0.3:80",
        "weight": 1
      }
    },
    "loadBalancer": {
      "method": "wrr"
    }
  }
}
```

After upgrading to `traefik 1.6.1` there are only one frontend and backend defined and `whoami` service is available only on one of the domain (usually the last one).

frontend:

```
{
   ...,
  "frontend-traefik-whoami1-1-whoami": {
    "entryPoints": [
      "http"
    ],
    "backend": "backend-traefik-whoami1-1-whoami",
    "routes": {
      "route-frontend-traefik-whoami1-1-whoami": {
        "rule": "Host:studio.localapp.com"
      }
    },
    "passHostHeader": true,
    "priority": 0,
    "basicAuth": [
      "user:$apr1$qTZTddGQ."
    ]
  }
}
```

backend:

```
{
   ...,
  "backend-traefik-whoami1-1-whoami": {
    "servers": {
      "server-default-traefik-whoami1-1-1": {
        "url": "http://172.17.0.3:80",
        "weight": 1
      },
      "server-private-traefik-whoami1-1-0": {
        "url": "http://172.17.0.3:80",
        "weight": 1
      }
    },
    "loadBalancer": {
      "method": "wrr"
    }
  }
}
```

### What did you expect to see?

The same behaviour as in `traefik-1.6.0`.
`whoami` service should be available on both domains:

- `api.localapp.com`
- and `studio.localapp.com`

### What did you see instead?

`whoami` service is available only on one domain, usually the last one according to labels order.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.1
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-05-14_07:16:56PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

only docker-compose file:

```yml
version: "2.2"
services:
  traefik:
    image: traefik:1.6.1-alpine
    command: -c /dev/null --api --docker --docker.domain=localapp.com --debug --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.private.frontend.rule=Host:studio.localapp.com"
      - "traefik.private.frontend.auth.basic=user:$$apr1$$qTZTddGQ$Vsom07noptUAR0yGpld8Q."
      - "traefik.frontend.rule=Host:api.localapp.com"
      - "traefik.default.protocol=http"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
