### ISSUE TITLE
Missing backend metrics

### ISSUE THREAD

**Issue by ncgee** [containous/traefik#3365]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Roll out traefik 1.6.1 in a Kubernetes cluster with Prometheus metrics scraping, using ingress resources for dynamic configuration.

### What did you expect to see?

The value of `traefik_entrypoint_requests_total{code="500"}` equal to the value of `sum(traefik_backend_requests_total{code="500"})`.

### What did you see instead?

`traefik_entrypoint_requests_total{code="500"}` had a value of around 8000, whereas the total for `traefik_backend_requests_total{code="500"}` was around 8. The value of the entrypoints metric was reflected in the access log. Additionally, running `traefik bug` as suggested completely removed these stats which preventing me from providing more exact values. Oddly, stats for other status codes (200, 302) are still present.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.1
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-05-14_07:15:23PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    defaultEntryPoints = ["http","https"]
    logLevel = "INFO"
    [respondingTimeouts]
      readTimeout = "60s"
      writeTimeout = "60s"
    [traefikLog]
      format = "json"
    [accessLog]
      format = "json"
      [accessLog.fields]
        [accessLog.fields.names]
          "ClientAddr" = "drop"
          "ClientPort" = "drop"
          "RequestPath" = "drop"
          "RequestProtocol" = "drop"
          "StartLocal" = "drop"
        [accessLog.fields.headers]
          [accessLog.fields.headers.names]
            "Etag" = "drop"
    [kubernetes]
      namespaces = ["redacted"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.proxyProtocol]
          trustedIPs = ["redacted"]
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.proxyProtocol]
          trustedIPs = ["redacted"]
        [entryPoints.https.tls]
        MinVersion = "VersionTLS11"
          CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA","TLS_RSA_WITH_AES_128_GCM_SHA256","TLS_RSA_WITH_AES_256_GCM_SHA384","TLS_RSA_WITH_AES_128_CBC_SHA","TLS_RSA_WITH_AES_256_CBC_SHA"]
          [[entryPoints.https.tls.certificates]]
            CertFile = "/etc/tls/tls.crt"
            KeyFile = "/etc/tls/tls.key"
    [api]
      dashboard = true
      [api.statistics]
        recentErrors = 10
    [ping]
    [metrics]
      [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
      [metrics.statistics]
        recentErrors = 10
    [acme]
      email = "redacted"
      storage = "/acme/acme.json"
      entryPoint = "https"
      onDemand = false
      onHostRule = true
      acmeLogging = true
      [acme.httpChallenge]
        entryPoint = "http"
```
