### ISSUE TITLE
multiple hosts inside ingress object results in multiple certs

### ISSUE THREAD

**Issue by JohnnyCrazy** [containous/traefik#3375]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I added a new Ingress object, which contained 2 rules, one with and one without `www`. (see ingress rule below)

### What did you expect to see?

I expected that Traefik will just request one certificate, which will include both host names. 

### What did you see instead?

2 different certificates were generated, both only containing one SAN.

Since it's just a test setup, here are both crt.sh outputs:
[helloworld2.johnnycrazydev.de](https://crt.sh/?id=479894151)
[www.helloworld2.johnnycrazydev.de](https://crt.sh/?id=479896285)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.2
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-05-22_03:19:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes Bare metal cluster

```toml
# none
```

Ingress object:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: ^https://www.helloworld2.johnnycrazydev.de/(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://helloworld2.johnnycrazydev.de/$1
  name: helloworld2
  namespace: default
spec:
  rules:
  - host: helloworld2.johnnycrazydev.de
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 80
        path: /
  - host: www.helloworld2.johnnycrazydev.de
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 80
        path: /
status:
  loadBalancer: {}
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
```
