### ISSUE TITLE
Traefik does not update the kubernetes ingress status or address

### ISSUE THREAD

**Issue by r0fls** [containous/traefik#3377]
Bug

### What did you do?
I deployed the [stable/traefik] helm chart to a 1.8.9 kubernetes cluster in AWS. I added the annotation `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` to the resulting traefik service, so that it creates an external load balancer (this may not be needed in your cluster). I then deployed a basic hello world deployment/svc/ingress with the traefik ingress class set. If I manually retrieve the hostname of the traefik service ELB, `kubectl get svc traefik-test -o yaml | grep -A 3 status` (assuming the deployment was named `traefik-test`), then curl it with the host header set to my ingress hostname, then I see the hello world app:

```
curl -H "Host: hello-word-test.cluster-adminsitered-domain.example.com" internal-a7e28d2a05ebd11e8ae62129f627ab16-1418276853.us-east-1.elb.amazonaws.com
hello world
```

So, things work up to there.

### What did you expect to see?

Status of my ingress should be filled in with the ELB from the traefik controller.  For example, a similar ingress fulfilled by the nginx ingress controller shows:

```
status:
  loadBalancer:
    ingress:
    - hostname: internal-a82f61a2b549411e8a3c60246d84323b-1415175647.us-east-1.elb.amazonaws.com
```

### What did you see instead?

Traefik does not set the ingress status of the fulfilled ingress, or address (a field in `kubectl get ing <INGRESS_NAME>`), which means it won't play nicely with things like external-dns:

```
kubectl get ing  hello-world-test -o yaml | grep status -A 3
status:
  loadBalancer: {}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

I tried the version specified in the [stable/traefik] helm chart (1.5.4) and the latest recommended version by traefik, 1.6.2.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I'm using the [stable/traefik] controller with no relevant modifications. The only modification was the one made to the service annotations.

**Comment by dtomcej** [comment]
Hello @r0fls!

Thank you so much for your interest in traefik!

The functionality of traefik to update ingress status was added via https://github.com/containous/traefik/pull/3324. This feature will be available on traefik version 1.7.

If you want to try out the feature with an experimental build, you can use the `containous/traefik:experimental` image, which is built off the `master` branch. Please note that this experimental build is not considered stable enough for production use.

Thanks!

**Comment by micw** [comment]
@dtomcej Looks that one piece is missing in your change. The RBAC needs to be extended to update the ingress.

https://github.com/containous/traefik/blob/master/examples/k8s/traefik-rbac.yaml needs:

  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update

**Comment by rbq** [comment]
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  [...]
  - apiGroups:
    - extensions
    resources:
    - ingresses/status
    verbs:
    - update
```
