### ISSUE TITLE
I can't successfuly  send certificate content via curl command to etcd2 for traefik

### ISSUE THREAD

**Issue by vinpel** [containous/traefik#3381]
### Do you want to request a *feature* or report a *bug*?

Bug (maybe  a curl => etcd => traefik interpretation)

### What did you do?

I use with **succes** traefik for expose container when they start : 
  * 1 pod with traefik &  etcd 3.2.5
  * X pod, each a container with a __sidekick__ script who send via curl the informations being alive

In my local network I  want to be able to access site with _https_.
for example i want to expose the container via **http://myapp.domain.loc**

i have a root CA to domaine.loc installed on my computer.

i have a certificate for "myapp.domain.loc" (crt & key) stored in the __sidekick__  

sample of the script (full script at the end of the bug report)
```bash
#i read the content of the files :
  CertFile=`cat /$CONFIG_HOSTNAME.$CONFIG_DOMAINE.crt`
  KeyFile=`cat /$CONFIG_HOSTNAME.$CONFIG_DOMAINE.key`
# Uncomment this to make https work
#CertFile=`/$CONFIG_HOSTNAME.$CONFIG_DOMAINE.crt`
#KeyFile=`/$CONFIG_HOSTNAME.$CONFIG_DOMAINE.key`

# i prepare the relevant keys
TRK_CONFIG["tls/$CN/certificate/entrypoints"]="http, https"
TRK_CONFIG["tls/$CN/entrypoints"]="https"
TRK_CONFIG["tls/$CN/certificate/certfile"]="$CertFile"
TRK_CONFIG["tls/$CN/certificate/keyfile"]="$KeyFile"

# Send the configuration
update_etcd(){
  for Key in "${!TRK_CONFIG[@]}"; do
  maValue=${TRK_CONFIG[$Key]}
  curl --show-error  --request PUT \
    --trace-ascii debugdump.txt \
    --silent --output /dev/null \
    --data ttl=$CONFIG_TTL \
    --data-binary value=$"$maValue" \
    "$TRAEFIK_KV/$Key"
  done
}
```

### What did you expect to see?

configuration accepted and https accessible.

# i can make it work if i uncomment the 2 lines

In this case, curl  "just" send the filename (placed in the traefik conteneur file ssytem ).
the certificate for the subdomain is correctly used.

If i put a wildcard certificate in the traefik conteneur and remove the HTTPS configuration it work too.

My guess is i don't send correctly the content of the crt/key file correctly
OR 
ETCD change my text and traefik can't analyse and accept the certificate

### What did you see instead?

```bash"
Error loading new configuration, aborted unable to generate TLS certificate : tls: failed to find any PEM data in certificate input"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.2
Codename:     têtedemoine
Go version:   go1.10.2
Built:        2018-05-22_03:17:30PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
#debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
logLevel = "INFO"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http","https"]


################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
 [entryPoints.http]
 address = ":80"
 compress = false
   [entryPoints.http.redirect]
      entryPoint = "https"
 [entryPoints.https]
 address = ":443"
 compress = true
  [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/domain.loc.crt"
        KeyFile = "/domain.loc.key"
[[tls]]
  [tls.certificate]
  #Wildcard
    CertFile = "/domain.loc.crt"
    KeyFile = "/domain.loc.key"
[web]
address = ":8080"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
# [traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "log/traefik.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  [api.statistics]
   recentErrors = 10
################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
# domain = "docker.localhost"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedByDefault = true

################################################################
# Etcd configuration backend
################################################################

# Enable Etcd configuration backend
#
# Optional
#
 [etcd]

# Etcd server endpoint
#
# Required
#
 endpoint = "172.16.28.200:2379"

# Enable watch Etcd changes.
#
# Optional
# Default: true
#
watch = true

# Prefix used for KV store.
#
# Optional
# Default: "/traefik"
#
prefix = "/traefik"

# Force to use API V3 (otherwise still use API V2)
#
# Deprecated
#
# Optional
# Default: false
#
useAPIV3 = false


# Override default configuration template.
# For advanced users :)
#
# Optional
#
# filename = "etcd.tmpl"

# Use etcd user/pass authentication.
#
# Optional
#
# username = foo
# password = bar

# Enable etcd TLS connection.
#
# Optional
#
#    [etcd.tls]
#    ca = "/etc/ssl/ca.crt"
#    cert = "/etc/ssl/etcd.crt"
#    key = "/etc/ssl/etcd.key"
#    insecureSkipVerify = true

# Enable REST Provider.
[rest]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "traefik"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
i have try a lot of possibility none workd for me

With "\" --- BEGIN --- \n dazokdazdaz ---END ---\"" i make traefik crash :

```
goroutine 47 [running]:
.045816] traefik[7]: time="2018-05-24T11:30:12Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
.044813] traefik[7]: time="2018-05-24T11:30:12Z" level=error msg="Near line 80 (last key parsed 'tls.certificate'): expected a top-level item to end with a newline, comment, or EOF,
.935857] traefik[7]: time="2018-05-24T11:30:11Z" level=error msg="KV connection error: Panic in operation: %!s(<nil>), retrying in 1.020605982s"
.935063] traefik[7]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
.934261] traefik[7]: created by github.com/containous/traefik/safe.GoWithRecover
.933420] traefik[7]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
.932616] traefik[7]: github.com/containous/traefik/safe.GoWithRecover.func1(0x226cd40, 0xc42063f950)
.931793] traefik[7]:         /go/src/github.com/containous/traefik/safe/routine.go:78 +0x3a
.930849] traefik[7]: github.com/containous/traefik/safe.(*Pool).Go.func1()
.930054] traefik[7]:         /go/src/github.com/containous/traefik/provider/kv/kv.go:108 +0x53
.929256] traefik[7]: github.com/containous/traefik/provider/kv.(*Provider).Provide.func1.1(0xc420280a10)
.928424] traefik[7]:         /go/src/github.com/containous/traefik/provider/kv/kv.go:92 +0x105
.927607] traefik[7]: github.com/containous/traefik/provider/kv.(*Provider).watchKv(0xc4201f2600, 0xc42042e7e0, 0xc42068e350, 0x8, 0xc420280a10, 0x115dc55, 0x1)
.926459] traefik[7]:         /go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37 +0x88
.925640] traefik[7]: github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc42073a8f0, 0x238ce40, 0xc42073a900, 0x226cbc8, 0x0, 0xc420091a40)
.924805] traefik[7]:         /go/src/github.com/containous/traefik/safe/routine.go:160 +0x62
.923996] traefik[7]: github.com/containous/traefik/safe.OperationWithRecover.func1(0x0, 0x0)
.923200] traefik[7]:         /go/src/github.com/containous/traefik/provider/kv/kv.go:78 +0x20e
.922391] traefik[7]: github.com/containous/traefik/provider/kv.(*Provider).watchKv.func1(0xc400000008, 0x226cd38)
.921541] traefik[7]:         /go/src/github.com/containous/traefik/provider/kv/kv_config.go:74 +0x1608
.920702] traefik[7]: github.com/containous/traefik/provider/kv.(*Provider).buildConfiguration(0xc4201f2600, 0x1)
.919883] traefik[7]:         /usr/local/go/src/runtime/panic.go:502 +0x229
.919105] traefik[7]: panic(0x1ddd2a0, 0x359b2b0)
.918252] traefik[7]:         /go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
.917449] traefik[7]: github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc4205c7dd8)
.916595] traefik[7]:         /go/src/github.com/containous/traefik/safe/routine.go:148 +0x73
.915811] traefik[7]: github.com/containous/traefik/safe.defaultRecoverGoroutine(0x1ddd2a0, 0x359b2b0)
.914979] traefik[7]:         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
.914190] traefik[7]: runtime/debug.PrintStack()
.913327] traefik[7]:         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
.912499] traefik[7]: runtime/debug.Stack(0x73837f, 0xc4200a42d0, 0x21cdd31)


```

The full sidekick script :
```bash
#!/bin/bash

function aff() {
    if [ -z $2 ];then
        COLOR=94 # vert
    else
        COLOR=$2
    fi
   echo -e "\e[${COLOR}m# $1 \e[0m"
}

if [ -z "$ETCD_IP" ]; then
  ETCD_IP=172.16.28.200
fi

if [ -z "$CONFIG_PRIVATE_PORT" ]; then
  CONFIG_PRIVATE_PORT=80
fi
CONFIG_HOSTNAME=`hostname`
CONFIG_DOMAINE="domaine.loc"

TRAEFIK_KV=http://$ETCD_IP:2379/v2/keys/traefik


CONFIG_PRIVATE_IP=`ip route get 1 | awk '{print $NF;exit}'`

aff "traefik-sidekick : $CONFIG_HOSTNAME.$CONFIG_DOMAINE => $CONFIG_PRIVATE_IP:$CONFIG_PRIVATE_PORT"

declare -A TRK_CONFIG

#Backend
TRK_CONFIG["backends/b_$CONFIG_HOSTNAME/circuitbreaker/expression"]="NetworkErrorRatio() > 0.5"
TRK_CONFIG["backends/b_$CONFIG_HOSTNAME/servers/backend_1/url"]="http://$CONFIG_PRIVATE_IP:80"
TRK_CONFIG["backends/b_$CONFIG_HOSTNAME/servers/backend_1/weight"]="10"

#Frontend (route OR route)
TRK_CONFIG["frontends/f_${CONFIG_HOSTNAME}/routes/frontend_1/rule"]="Host:$CONFIG_HOSTNAME.$CONFIG_DOMAINE,$CONFIG_HOSTNAME"
TRK_CONFIG["frontends/f_${CONFIG_HOSTNAME}/backend"]="b_$CONFIG_HOSTNAME"
TRK_CONFIG["frontends/f_${CONFIG_HOSTNAME}/passHostHeader"]="true"
TRK_CONFIG["frontends/f_${CONFIG_HOSTNAME}/priority"]="1"



# Ajout d'une configuration SSL si demandé avec le Hostname

if [  -f "/data/htdocs/scripts_rkt/ssl_traefik/$CONFIG_HOSTNAME.$CONFIG_DOMAINE.crt" ];then

  CN=`echo "$CONFIG_PRIVATE_IP" | sed 's/^.*\.\([^.]*\)$/\1/'`

  aff "Utilisation de la configuration SSL ($CN)"
  #| tr -d '\r'
  CertFile=`cat //ssl_traefik/$CONFIG_HOSTNAME.$CONFIG_DOMAINE.crt`
  KeyFile=`cat //ssl_traefik/$CONFIG_HOSTNAME.$CONFIG_DOMAINE.key`

  #CertFile="/a.crt"
  #KeyFile="/a.key"
TRK_CONFIG["tls/$CN/certificate/entrypoints"]="http, https"
TRK_CONFIG["tls/$CN/entrypoints"]="https"
TRK_CONFIG["tls/$CN/certificate/certfile"]="$CertFile"
TRK_CONFIG["tls/$CN/certificate/keyfile"]="$KeyFile"
  
fi

if [ -z "$CONFIG_TTL" ]; then
  CONFIG_TTL=30
fi

## Enregistre le conteneur avec un TTL de 10 seconde toute les 7 secondes
update_etcd(){
  for Key in "${!TRK_CONFIG[@]}"; do
  
  maValue=${TRK_CONFIG[$Key]}
  curl --show-error  --request PUT \
    --trace-ascii debugdump.txt \
    --silent --output /dev/null \
    --data ttl=$CONFIG_TTL \
    --data-binary value=$"$maValue" \
    "$TRAEFIK_KV/$Key"
  done
}
#Clean avant lancement
curl --show-error --silent --output /dev/null --header "Accept: application/json" --request DELETE $TRAEFIK_KV/backends/b_$CONFIG_HOSTNAME/?recursive=true
curl --show-error --silent --output /dev/null --header "Accept: application/json" --request DELETE $TRAEFIK_KV/frontends/f_$CONFIG_HOSTNAME/?recursive=true
# Debut boucle
while true
do
  update_etcd
  sleep 25
done
```bash
