### ISSUE TITLE
docker-compose services issues

### ISSUE THREAD

**Issue by DanielBoettner** [containous/traefik#3384]
### Do you want to request a *feature* or report a *bug*?
* Bug

### What did you do?
As an example I use a plantuml container.

While this works:

```
plantuml:
 image: plantuml/plantuml-server
 labels:
  - "traefik.frontend.rule=Host:plantuml.tld"
  - "traefik.frontend.port=8080"
  - "traefik.backend=Plantuml"
 environment:
  - PLANTUML_LIMIT_SIZE=8192
```

This does not:

```
version: "3" //or 2 , no difference

networks:
 default:
  external:
   name: proxy

services:
 plantuml:
  image: plantuml/plantuml-server
   labels:
    - "traefik.frontend.rule=Host:plantuml.tld"
    - "traefik.frontend.port=8080"
    - "traefik.backend=Plantuml"
  environment:
   - PLANTUML_LIMIT_SIZE=8192
~                                
```
### What did you expect to see?

That i can access the container via plantuml.tld via port 80.
But it seems that traefik does not properly forward the ports if the port are set in a services label.

Everything else seems fine. The containers are listed on the dashboard.

### What did you see instead?

gateway timeout

### Output of `traefik version`: (_What version of Traefik are you using?_)

docker image hash "deeeb64f5636" ~ v1.6.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

defaultEntryPoints = ["http", "https"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]


################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]
domain = "~~~~~~~~~~~~"

# Let's encrypt configuration
[acme]
  email="~~~~~~~~~~~~~"
  storage="/etc/traefik/acme.json"
  entryPoint="https"
  acmeLogging=true
  onDemand=true
  OnHostRule=true

```
Some information on the host:

* `Linux ~~~ 4.16.11-1.el7.elrepo.x86_64 #1 SMP Tue May 22 15:34:16 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
* `Docker version 18.03.1-ce, build 9ee9f40`
* `docker-compose version 1.21.2, build a133471`
