### ISSUE TITLE
traefik cannot find secrets, errors as 'doesnt exist'

### ISSUE THREAD

**Issue by amit-handa** [containous/traefik#3402]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

created traefik ingress controller via helm/stable/traefik.

Unfortunately, it shows error while accessing the secrets.
```
kubectl get secret dex-tls -oyaml --as gem-lb-traefik
Error from server (Forbidden): secrets "dex-tls" is forbidden: User "gem-lb-traefik" cannot get secrets in the namespace "default"
$ kubectl describe clusterrolebinding gem-lb-traefik
Name:         gem-lb-traefik
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  gem-lb-traefik
Subjects:
  Kind            Name            Namespace
  ----            ----            ---------
  ServiceAccount  gem-lb-traefik  default
$ kubectl describe clusterrole gem-lb-traefik
Name:         gem-lb-traefik
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources             Non-Resource URLs  Resource Names  Verbs
  ---------             -----------------  --------------  -----
  endpoints             []                 []              [get list watch]
  pods                  []                 []              [get list watch]
  secrets               []                 []              [get list watch]
  services              []                 []              [get list watch]
  ingresses.extensions  []                 []              [get list watch]
```

```
kubectl auth can-i get secrets --namespace default --as system:serviceaccount:default:gem-lb-traefik
yes
```

Discussion on slack channel below:
https://traefik.slack.com/archives/C0CDT22PJ/p1527504010000220

traefik deployment:
/ kubectl get deployment gem-lb-traefik -oyaml  
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-05-28T10:13:59Z
  generation: 1
  labels:
    app: traefik
    chart: traefik-1.31.1
    heritage: Tiller
    release: gem-lb
  name: gem-lb-traefik
  namespace: default
  resourceVersion: "2861633"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gem-lb-traefik
  uid: d695eb90-625f-11e8-8747-dc4a3e6bd0d7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traefik
      release: gem-lb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: f89e10ab419c8f18994f55f7e8255175c845386c0d3adc7ac386e2bf024f4289
      creationTimestamp: null
      labels:
        app: traefik
        chart: traefik-1.31.1
        heritage: Tiller
        release: gem-lb
    spec:
      containers:
      - args:
        - --configfile=/config/traefik.toml
        image: traefik:1.6.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 2
        name: gem-lb-traefik
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 8880
          name: httpn
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: dash
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /ssl
          name: ssl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gem-lb-traefik
      serviceAccountName: gem-lb-traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: gem-lb-traefik
        name: config
      - name: ssl
        secret:
          defaultMode: 420
          secretName: gem-lb-traefik-default-cert
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-05-28T10:13:59Z
    lastUpdateTime: 2018-05-28T10:13:59Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-05-28T10:13:59Z
    lastUpdateTime: 2018-05-28T10:14:20Z
    message: ReplicaSet "gem-lb-traefik-54bc87db7b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

### What did you expect to see?
Expected the controller to get the secrets.

### What did you see instead?

Error from server (Forbidden): secrets "dex-tls" is forbidden: User "gem-lb-traefik" cannot get secrets in the namespace "default"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    # traefik.toml
    logLevel = "INFO"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
    [kubernetes]
    [web]
    address = ":8080"
      [web.auth.basic]
        users = ["k8s-lb:Gemini@123",]
```

**Comment by dtomcej** [comment]
Hello @amit-handa,

I attempted to recreate your configuration, but was unable to recreate your error. When I used the latest helm chart to access secrets, there was no issue. Even when the secrets were in another namespace.

Is it possible for you to provide a list of steps to take to recreate your issue?

Thanks!

**Comment by amit-handa** [comment]
Thanks for your input.
PFA my values.yaml. Note that replace the defaultCert,defaultKey values.

Installed via helm as follows:
```helm install --name gem-lb ./```
It completes successfully. and I see the mentioned errors in traefik pod logs.

**Comment by amit-handa** [comment]
Hi Daniel,

I have base64 encoded the certificate. I am sorry if it doesnt need to be. please confirm.
echo defaultCert.value | base64 -d => gives the certificate beginning with MII...

Thanks,

**Comment by dtomcej** [comment]
Hello @amit-handa, you are correct, the secrets are created manually, and therefore needed to be base64 encoded. I missed that when I first reviewed.

**Comment by dustinphipps** [comment]
This may be an upstream issue with Traefik. I have the same problem and I'm not using this project.

**Comment by dtomcej** [comment]
@ncgee are you able to consistently reproduce that error message? My attempts to recreate have all failed...

Can't fix something I can't reproduce...

**Comment by ncgee** [comment]
@dtomcej yes I can, scaling up the deployment results in the same error messages in the new pod (although I was wrong about it throwing the message twice for each ingress):

```
{"level":"error","msg":"Error configuring TLS for ingress b/ingress-name: secret b/secret-name does not exist","time":"2018-06-06T09:39:23Z"}
```

Do you need any more information?

**Comment by The-Loeki** [comment]
I'm having the same issue; utilizing traefik 1.6.3

Possibly smells like #3128

**Comment by dtomcej** [comment]
Thanks for the information all!

I managed to reproduce this issue, and will be working on a fix!

**Comment by ncgee** [comment]
Yes they do, in my case at least. I had accidentally forgotten to include the intermediate in the secret, while also having the same key/certificate with intermediate mounted as files in the pod.
When connecting both curl and SSL Labs complained about an incomplete chain. So it seems that the secret actually takes precedence over the key/certificate in the files, despite the error message.

**Comment by w1ndy** [comment]
@dtomcej No it's not working... Redirection from http to https works as expected, but https returns 404 not found. My configuration is as follows.

The secret is created via:
```bash
kubectl create secret generic traefik-ui-tls-cert --from-file=tls.crt=/etc/dehydrated/certs/example.com/cert.pem --from-file=tls.key=/etc/dehydrated/certs/example.com/privkey.pem -n kube-system
```

<details><summary>Traefik DaemonSet YAML</summary><p>

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-configmap
      containers:
      - image: traefik
        name: traefik-ingress-lb
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
```
</p></details>

<details><summary>Traefik Config</summary><p>

```
[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
```
</p></details>

<details><summary>Traefik UI YAML</summary><p>

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: 80
  tls:
  - secretName: traefik-ui-tls-cert
```
</p></details>

<details><summary>Traefik Log</summary><p>

```
time="2018-07-12T11:26:39Z" level=info msg="Using TOML configuration file /config/traefik.toml"
time="2018-07-12T11:26:39Z" level=info msg="Traefik version v1.6.5 built on 2018-07-10_03:54:03PM"
time="2018-07-12T11:26:39Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-07-12T11:26:39Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420715260} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-07-12T11:26:39Z" level=info msg="Preparing server https &{Address::443 TLS:0xc420700d00 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420715220} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-07-12T11:26:39Z" level=info msg="Starting server on :8080"
time="2018-07-12T11:26:39Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc4205dfe00 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420715240} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-07-12T11:26:39Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\"}"
time="2018-07-12T11:26:39Z" level=info msg="ingress label selector is: \"\""
time="2018-07-12T11:26:39Z" level=info msg="Creating in-cluster Provider client"
time="2018-07-12T11:26:39Z" level=info msg="Starting server on :80"
time="2018-07-12T11:26:39Z" level=info msg="Starting server on :443"
time="2018-07-12T11:26:39Z" level=error msg="Error configuring TLS for ingress kube-system/traefik-web-ui: secret kube-system/traefik-ui-tls-cert does not exist"
time="2018-07-12T11:26:39Z" level=info msg="Server configuration reloaded on :8080"
time="2018-07-12T11:26:39Z" level=info msg="Server configuration reloaded on :443"
time="2018-07-12T11:26:39Z" level=info msg="Server configuration reloaded on :80"
time="2018-07-12T11:26:39Z" level=error msg="Error configuring TLS for ingress kube-system/traefik-web-ui: secret kube-system/traefik-ui-tls-cert does not exist"
time="2018-07-12T11:26:39Z" level=error msg="Error configuring TLS for ingress kube-system/traefik-web-ui: secret kube-system/traefik-ui-tls-cert does not exist"
time="2018-07-12T11:26:39Z" level=warning msg="Endpoints not available for kube-system/traefik-web-ui"
time="2018-07-12T11:26:39Z" level=warning msg="Endpoints not available for kube-system/traefik-web-ui"
time="2018-07-12T11:26:41Z" level=info msg="Server configuration reloaded on :443"
time="2018-07-12T11:26:41Z" level=info msg="Server configuration reloaded on :80"
time="2018-07-12T11:26:41Z" level=info msg="Server configuration reloaded on :8080"
```
</p></details>

<details><summary>kubectl -n kube-system describe secret traefik-ui-tls-cert</summary><p>

```
Name:         traefik-ui-tls-cert
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
tls.crt:  2508 bytes
tls.key:  3243 bytes
```
</p></details>

**Comment by w1ndy** [comment]
It turns out the certificate is added to the wrong endpoint.... After enabling debug logging, the log says
```
time="2018-07-13T18:24:37Z" level=debug msg="No entryPoint is defined to add the certificate xxx, it will be added to the default entryPoints: http"
```
Prepending the configuration with ``defaultEntryPoints = ["https"]`` resolved my issue.

**Comment by dicarlo2** [comment]
I'm seeing this happen with the "ingress.kubernetes.io/auth-secret" annotation. Any ideas? Do I have a configuration issue or is this a bug in traefik? One thing that seems suspicious is the extra quotes around the namespace/secret name, though perhaps that's just how it's formatted into the log string.

Error message:
```
time="2018-07-22T07:48:24Z" level=error msg="Failed to retrieve basic auth configuration for ingress default/traefik-dashboard: failed to load auth credentials: secret \"default\"/\"basic-admin\" not found"
```

Ingress config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-dashboard
  labels:
    app: traefik-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-admin
    ingress.kubernetes.io/auth-header-field: X-WebAuth-User
spec:
  rules:
  - host: https://mydomain.com
    http:
      paths:
      - path: /traefik
        backend:
          serviceName: traefik-dashboard
          servicePort: dashboard
```

Secret exists:
```
dicarlo$ kubectl get secret basic-admin
NAME          TYPE      DATA      AGE
basic-admin   Opaque    1         25m
```

**Comment by zyf0330** [comment]
I have this error log too
```
time="2018-08-06T08:59:40Z" level=error msg="Failed to retrieve basic auth configuration for ingress namespace/traefik-web-ui: failed to load auth credentials: secret \"namespace\"/\"traefik-ui\" not found"
```

**Comment by zyf0330** [comment]
I have this error log too
```
time="2018-08-06T08:59:40Z" level=error msg="Failed to retrieve basic auth configuration for ingress namespace/traefik-web-ui: failed to load auth credentials: secret \"namespace\"/\"traefik-ui\" not found"
```

**Comment by paheld** [comment]
I observed, that if I enable acme I have the same error. Disabling acme and the auth-secret works.

**Comment by PeterGrace** [comment]
As @w1ndy alluded to in a prior post, this may have something to do with the order of entrypoints in the config.  On a hunch from their message, I moved the https entrypoint section to be first in the config file, above the http entrypoint section, and ACME worked.  I'd have a hard time believing that this was the real fix and am suspect that maybe a restart was the actual fix, but for what its worth, if other people are having this issue (especially those using the helm deploy of traefik), try editing the configmap (`kubectl edit configmap traefik -n <traefik-namespace>`) and move the entrypoints.https section so that it is the first one in the entrypoints list and see if that helps.

@w1ndy's comment was to make sure the defaultEntryPoints has https first, but as you can see in my config, I left it at http, https, reordered the entrypoints and it started working (again, it really smells like the restart was the magic sauce, not the changing of the configs)  either way, edit the configmap and fiddle with defaultEntryPoints or the order of entries in the entryPoints section of the toml, and may the odds be ever in your favor.

Excerpt from my configmap:
```
...
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
      [entryPoints.http]
      address = ":80"
      compress = true
    [kubernetes]
...
```

**Comment by clalbus** [comment]
Is your traefik crashing with due to this?

I've managed to resolve it by increasing `resources.limits.memory`

**Comment by ToroNZ** [comment]
I'm experiencing this issue. Daemonset was deployed, secrets (basic/tls) created and everything was great. Until I had to limit the TLS ciphers to remove 3DES (BTW why on earth is that default?).

As soon as I re-deployed one of them (of 4), saw logs related to non-existing secrets... these are used fine by the other 3 pods. None of the solutions mentioned here or in #3128 helped.

Here's my daemonset yaml:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      containers:
      - args:
        - --logLevel=INFO
        - --kubernetes
        - --entryPoints=Name:tls Address::443 TLS TLS.MinVersion:VersionTLS11 TLS.CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - --entryPoints=Name:web Address::80 Redirect.EntryPoint:tls
        - --defaultentrypoints=tls,web
        - --api
        image: image.blackhole.evilcloud.xyz:5140/k8s-management/traefik:1.6.6-alpine
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: tls
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: admin
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
  updateStrategy:
    type: OnDelete
```

Tried 1.6.5, 1.6.6, 1.7.0-rc3.. they all error out in the same way:

```
time="2018-09-04T22:57:41Z" level=error msg="Error configuring TLS for ingress kube-system/traefik-web-ui: secret kube-system/traefik-ui-tls-cert does not exist"
time="2018-09-04T22:57:41Z" level=error msg="Error configuring TLS for ingress tiller-world/pushgateway-web-ui: secret tiller-world/pushgateway-ui-tls-cert does not exist"
time="2018-09-04T22:57:41Z" level=error msg="Error configuring TLS for ingress tiller-world/alertmanager-web-ui: secret tiller-world/alertmanager-ui-tls-cert does not exist"
time="2018-09-04T22:57:41Z" level=error msg="Error configuring TLS for ingress tiller-world/monitoring-web-ui: secret tiller-world/prometheus-ui-tls-cert does not exist"
```

As I said before, the other 3 pods running 1.6.5 are working fine. They only thing worth mentioning is that these 3 pods were created before creating the secrets (that's the only difference I can think of).

Anyway, I'll keep poking at this and see if I can get something more.
