### ISSUE TITLE
unable to parse address

### ISSUE THREAD

**Issue by Gabology** [containous/traefik#3407]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Update to traefik 1.6.2 from 1.5.4

### What did you expect to see?

That everything would work as expected

### What did you see instead?

A lot of logs with the following messages:

```
time="2018-05-29T09:27:15Z" level=error msg="unable to parse address: 123.45.67.891, 55.111.50.11: can't parse IP from address 123.45.67.891, 55.111.50.11"
```

### Configuration

Relevant bits with forwarded headers.

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["123.211.0.0/22", "1.2.3.4/16"]
  [entryPoints.internal]
  address = ":8081"
    [entryPoints.internal.forwardedHeaders]
      trustedIPs = ["123.211.0.0/22", "1.2.3.4/16"]
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.6.2
```

It seems to me that there has been some regression in the way that traefik parses multiple ip address, as is the case in our environment when traefik itself is behind an external load balancer. This worked prior to v1.6. Looking at the commit history I am guessing that it is related to the changes introduced in `d2766b1` or `edb53rd`.
