### ISSUE TITLE
redirection does not work

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#3408]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have created an ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-regex: ^https://example.com/(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://www.example.com/$1
  creationTimestamp: 2018-02-21T14:21:09Z
  generation: 2
  name: test
  namespace: test
spec:
  rules:
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: http
        path: /
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: http
        path: /
status:
  loadBalancer: {}
```
But nothing actually happens. Site is available on both www and www-less entrypoints

### What did you expect to see?

example.com redirected to www.example.com

### What did you see instead?

Both entrypoints are available on www and www-less URL

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```
