### ISSUE TITLE
Invalid escape character '.' in redirect-regex

### ISSUE THREAD

**Issue by tiukhtinvladimir** [containous/traefik#3409]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to create a rule for redirection from http to https + add 'www' if missing. Following ingress annotations I have tried
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/redirect-regex: ^(?:http|https)://(?:www\.)?(.*)
    ingress.kubernetes.io/redirect-replacement: https://www.${1}
    kubernetes.io/ingress.class: traefik
  name: test
spec:
  rules:
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: http
        path: /
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: http
        path: /
```

### What did you expect to see?
Traefik starts and follows regex rule

### What did you see instead?
Traefik stops looking at kubernetes API, it can not find any objects at all.Following appears in the log:

```
time="2018-05-29T12:19:41Z" level=error msg="Near line 2392 (last key parsed 'frontends.example.com/.redirect.regex'): invalid escape character '.'; only the following escape characters are allowed: \\b, \\t, \\n, \\f, \\r, \\\", \\\\, \\uXXXX, and \\UXXXXXXXX"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.2
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-05-22_03:19:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- kubernetes
- etcd

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-05-29T12:19:40Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\"}"
time="2018-05-29T12:19:40Z" level=debug msg="Using Ingress label selector: \"\""
time="2018-05-29T12:19:40Z" level=info msg="ingress label selector is: \"\""
time="2018-05-29T12:19:40Z" level=info msg="Creating in-cluster Provider client"
time="2018-05-29T12:19:40Z" level=info msg="Node 3b867ce0-8dd5-4524-8217-533c2b64b541 elected worker ♝"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot get key /traefik/alias Key not found in store, setting default /traefik"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot list keys under \"/traefik/backends/\": Key not found in store"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot list keys under \"/traefik/frontends/\": Key not found in store"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot list keys under \"/traefik/tls/\": Key not found in store"
time="2018-05-29T12:19:40Z" level=debug msg="Configuration received from provider etcdv3: {}"
time="2018-05-29T12:19:40Z" level=info msg="Server configuration reloaded on :80"
time="2018-05-29T12:19:40Z" level=info msg="Server configuration reloaded on :8080"
time="2018-05-29T12:19:40Z" level=info msg="Server configuration reloaded on :443"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot get key /traefik/alias Key not found in store, setting default /traefik"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot list keys under \"/traefik/backends/\": Key not found in store"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot list keys under \"/traefik/frontends/\": Key not found in store"
time="2018-05-29T12:19:40Z" level=debug msg="Cannot list keys under \"/traefik/tls/\": Key not found in store"
time="2018-05-29T12:19:40Z" level=debug msg="Configuration received from provider etcdv3: {}"
time="2018-05-29T12:19:40Z" level=info msg="Skipping same configuration for provider etcdv3"
time="2018-05-29T12:19:41Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-05-29T12:19:41Z" level=error msg="Near line 2392 (last key parsed 'frontends.example.com/.redirect.regex'): invalid escape character '.'; only the following escape characters are allowed: \\b, \\t, \\n, \\f, \\r, \\\", \\\\, \\uXXXX, and \\UXXXXXXXX"
time="2018-05-29T12:19:41Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-05-29T12:19:41Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2018-05-29T12:19:41Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-05-29T12:19:41Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2018-05-29T12:19:41Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-05-29T12:19:41Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-05-29T12:19:42Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-05-29T12:19:42Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
```
