### ISSUE TITLE
Whitelist of large amount of IPs break the new admin area

### ISSUE THREAD

**Issue by mavimo** [containous/traefik#3410]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Create a frontend with large number of whitelisted source range, like:

```
services:
  foo:
    image: foo/bar
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.website.frontend.priority=1"
      - "traefik.website.frontend.rule=Host:foo.demo.com"
      - "traefik.website.frontend.whiteList.sourceRange=100.100.100.10/32,100.100.100.20/32,100.100.100.30/32,100.100.100.40/32,100.100.100.50/32,100.100.100.60/32,100.100.100.70/32,100.100.100.80/32,100.100.100.90/32"
      - "traefik.webhook.frontend.priority=10"
      - "traefik.website.frontend.rule=Host:bar.demo.com"
      - "traefik.webhook.frontend.whitelist.sourceRange=0.0.0.0/0"
```

### What did you expect to see?

![image](https://user-images.githubusercontent.com/43941/40676045-cf390634-6379-11e8-89b8-3b4d66bc20fe.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/43941/40676001-a4ec9fbc-6379-11e8-84de-8b3bcf7baa84.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
logLevel = "ERROR"
checkNewVersion = false
defaultEntryPoints = ["https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[frontends]
passHostHeader = true

[docker]
domain = "bar.com"
exposedbydefault = false

[acme]
email = "foo@bar.com"
storageFile = "/etc/traefik/acme.json"
onDemand = true
onHostRule = true
entryPoint = "https"
```
