### ISSUE TITLE
Malformed account ID in KeyID header URL

### ISSUE THREAD

**Issue by r-moiseev** [containous/traefik#3416]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deployed traefik in kubernetes using helm chart. 
Configured http-01 acme challenge

### What did you expect to see?

Traefik able to issue certs from letsencrypt

### What did you see instead?

```
time="2018-05-30T12:30:30Z" level=error msg="Unable to obtain ACME certificate for domains \"<MY_DOMAIN>\" detected thanks to rule \"Host:<MY_DOMAIN>\" : cannot obtain certificates: acme: Error 400 - urn:ietf:params:acme:error:malformed - Malformed account ID in KeyID header URL"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
[acme]
email = "roman.a.moiseev@gmail.com"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
  [acme.httpChallenge]
  entryPoint = "http"
[web]
address = ":8080"
[web.metrics.prometheus]
```

there is helm values
```yaml
rbac:
  enabled: ture
dashboard:
  enabled: true
  domain: <DOMAIN>
  ingress:
    annotations:
      ingress.kubernetes.io/auth-type: "basic"
      ingress.kubernetes.io/auth-secret: "basic-auth"
metrics:
  prometheus:
    enabled: ture

ssl:
  enabled: true
  enforced: false

acme:
  enabled: true
  email: <MY_EMAIL>
  staging: false
  logging: true
  challengeType: http-01
  persistence:
    enabled: true
    storageClass: "premium"
```
