### ISSUE TITLE
Traefik performs health check against root instead of configured health check path

### ISSUE THREAD

**Issue by rfeltis** [containous/traefik#3417]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured service health check to URL of /api/v1/health. Service will return 404 if requests are sent to /.

### What did you expect to see?

A healthy service exposed via Traefik and logs that reflect that health check.

### What did you see instead?

A service that only responds with "Service Unavailable." Traefik logs and dashboard both show the correct health check path, but actual health queries are logged going against root instead of the configured path.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.1
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-05-14_07:16:56PM
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

toml
```toml
################################################################
# Global configuration
################################################################

InsecureSkipVerify = true
defaultEntryPoints = ["https","http"]

debug = true
[traefikLog]
  filePath = "traefik.log"

[entryPoints]
  [entryPoints.http]
  address = ":30080"
    [entryPoints.http.proxyProtocol]
    insecure = true
  [entryPoints.httpInternal]
  address = ":80"
    [entryPoints.httpInternal.proxyProtocol]
    insecure = true
    [entryPoints.httpInternal.whitelist]
    sourceRange = ["10.0.0.0/8", "127.0.0.1", "::1"]
  [entryPoints.https]
  address = ":30443"
    [entryPoints.https.proxyProtocol]
    insecure = true
    [entryPoints.https.tls]
      [entryPoints.https.tls.ClientCA]
      optional = true
      [[entryPoints.https.tls.certificates]]
      certFile = "localhost.cert"
      keyFile = "localhost.key"
[entryPoints.traefik]
address = ":38080"
    [entryPoints.traefik.whitelist]
    sourceRange = ["10.0.0.0/8", "127.0.0.1", "::1"]

[retry]
attempts = 3

[forwardingTimeouts]
dialTimeout = "5s"

[healthcheck]
interval = "5s"

################################################################
# API definition
################################################################

[api]
  entryPoint = "traefik"
  dashboard = true

################################################################
# Service Fabric provider
################################################################

[servicefabric]
clustermanagementurl = "https://localhost:19080"
apiversion = "3.0"

[serviceFabric.tls]
  cert = "traefikcert.crt"
  key = "traefikkey.key"
  insecureskipverify = true
  caoptional = true


```

Here is the Traefik configuration in the service manifest. We have both expose and enable set to facilitate migration to 1.6.
```xml
<Extension Name="Traefik">
	<Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
		<Label Key="traefik.frontend.rule.MyApp">PathPrefixStrip: /MyApp</Label>
		<Label Key="traefik.backend.healthcheck.path">/api/v1/health</Label>
		<Label Key="traefik.backend.healthcheck.interval">10s</Label>
		<Label Key="traefik.backend.healthcheck.port">12021</Label>
		<Label Key="traefik.expose">true</Label>
		<Label Key="traefik.enable">true</Label>
	</Labels>
</Extension>

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-05-30T21:57:56Z" level=info msg="Using TOML configuration file D:\\SvcFab\\_App\\TraefikType_App1\\TraefikPkg.Code.1.6.1.c25f37fe\\traefik.toml"
time="2018-05-30T21:57:56Z" level=info msg="Traefik version v1.6.1 built on 2018-05-14_07:16:56PM"
time="2018-05-30T21:57:56Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-05-30T21:57:56Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":true,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":{\"file\":\"traefik.log\",\"format\":\"common\"},\"Tracing\":null,\"LogLevel\":\"\",\"EntryPoints\":{\"http\":{\"Address\":\":30080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":{\"Insecure\":true,\"TrustedIPs\":null},\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"httpInternal\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":{\"sourceRange\":[\"10.0.0.0/8\",\"127.0.0.1\",\"::1\"]},\"Compress\":false,\"ProxyProtocol\":{\"Insecure\":true,\"TrustedIPs\":null},\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":30443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":[{\"CertFile\":\"localhost.cert\",\"KeyFile\":\"localhost.key\"}],\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":null,\"Optional\":true}},\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":{\"Insecure\":true,\"TrustedIPs\":null},\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":38080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":{\"sourceRange\":[\"159.49.0.0/16\",\"10.0.0.0/8\",\"127.0.0.1\",\"::1\"]},\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"https\",\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":true,\"RootCAs\":null,\"Retry\":{\"Attempts\":3},\"HealthCheck\":{\"Interval\":5000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":{\"DialTimeout\":5000000000,\"ResponseHeaderTimeout\":0},\"AllowMinWeightZero\":false,\"Web\":null,\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":{\"Watch\":false,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"ClusterManagementURL\":\"https://localhost:19080\",\"APIVersion\":\"3.0\",\"RefreshSeconds\":0,\"TLS\":{\"CA\":\"\",\"CAOptional\":true,\"Cert\":\"traefikcert.crt\",\"Key\":\"traefikkey.key\",\"InsecureSkipVerify\":true}},\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":true,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":null}"
time="2018-05-30T21:57:56Z" level=debug msg="configured IP white list: [10.0.0.0/8 127.0.0.1 ::1]"
time="2018-05-30T21:57:56Z" level=info msg="Preparing server httpInternal &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:0xc0429013a0 Compress:false ProxyProtocol:0xc042901320 ForwardedHeaders:0xc0428b64c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-05-30T21:57:56Z" level=info msg="Enabling ProxyProtocol for trusted IPs []"
time="2018-05-30T21:57:56Z" level=info msg="Preparing server https &{Address::30443 TLS:0xc0428c1800 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:0xc042900dc0 ForwardedHeaders:0xc0428b64e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-05-30T21:57:56Z" level=info msg="Starting server on :80"
time="2018-05-30T21:57:56Z" level=debug msg="Add certificate for domains localhost"
time="2018-05-30T21:57:56Z" level=info msg="Enabling ProxyProtocol for trusted IPs []"
time="2018-05-30T21:57:56Z" level=debug msg="configured IP white list: [159.49.0.0/16 10.0.0.0/8 127.0.0.1 ::1]"
time="2018-05-30T21:57:56Z" level=info msg="Preparing server traefik &{Address::38080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:0xc042901060 Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0428b6500} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-05-30T21:57:56Z" level=info msg="Preparing server http &{Address::30080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:0xc042901220 ForwardedHeaders:0xc0428b64a0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-05-30T21:57:56Z" level=info msg="Enabling ProxyProtocol for trusted IPs []"
time="2018-05-30T21:57:56Z" level=info msg="Starting provider *servicefabric.Provider {\"Watch\":false,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"ClusterManagementURL\":\"https://localhost:19080\",\"APIVersion\":\"3.0\",\"RefreshSeconds\":0,\"TLS\":{\"CA\":\"\",\"CAOptional\":true,\"Cert\":\"traefikcert.crt\",\"Key\":\"traefikkey.key\",\"InsecureSkipVerify\":true}}"
time="2018-05-30T21:57:56Z" level=info msg="Starting server on :30443"
time="2018-05-30T21:57:56Z" level=info msg="Starting server on :38080"
time="2018-05-30T21:57:56Z" level=info msg="Starting server on :30080"
time="2018-05-30T21:58:06Z" level=info msg="Checking service fabric config"
time="2018-05-30T21:58:06Z" level=debug msg="Validation of load balancer method for backend fabric:/MyApp/MyApp failed: invalid load-balancing method ''. Using default method wrr."
time="2018-05-30T21:58:06Z" level=debug msg="Configuration received from provider servicefabric: {\"backends\":{\"fabric:/MyApp/MyApp\":{\"servers\":{\"131721799608519753\":{\"url\":\"http://10.0.0.4:12021//\",\"weight\":1},\"131721800963813340\":{\"url\":\"http://10.0.0.5:12021//\",\"weight\":1},\"131721802109741370\":{\"url\":\"http://10.0.0.6:12021//\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"},\"healthCheck\":{\"path\":\"/api/v1/health\",\"port\":12021,\"interval\":\"10s\"}}}}"
time="2018-05-30T21:58:06Z" level=debug msg="Creating frontend frontend-fabric:/MyApp/MyApp"
time="2018-05-30T21:58:06Z" level=debug msg="Wiring frontend frontend-fabric:/MyApp/MyApp to entryPoint https"
time="2018-05-30T21:58:06Z" level=debug msg="Creating route traefik.frontend.rule.MyApp PathPrefixStrip: /MyApp"
time="2018-05-30T21:58:06Z" level=debug msg="Creating backend fabric:/MyApp/MyApp"
time="2018-05-30T21:58:06Z" level=debug msg="Creating load-balancer wrr"
time="2018-05-30T21:58:06Z" level=debug msg="Creating server 131721799608519753 at http://10.0.0.4:12021// with weight 1"
time="2018-05-30T21:58:06Z" level=debug msg="Creating server 131721800963813340 at http://10.0.0.5:12021// with weight 1"
time="2018-05-30T21:58:06Z" level=debug msg="Creating server 131721802109741370 at http://10.0.0.6:12021// with weight 1"
time="2018-05-30T21:58:06Z" level=debug msg="Setting up backend health check [Path: /api/v1/health Port: 12021 Interval: 10s]"
time="2018-05-30T21:58:06Z" level=debug msg="Creating retries max attempts 3"
time="2018-05-30T21:58:06Z" level=debug msg="Wiring frontend frontend-fabric:/MyApp/MyApp to entryPoint http"
time="2018-05-30T21:58:06Z" level=debug msg="Creating route traefik.frontend.rule.MyApp PathPrefixStrip: /MyApp"
time="2018-05-30T21:58:06Z" level=debug msg="Creating backend fabric:/MyApp/MyApp"
time="2018-05-30T21:58:06Z" level=debug msg="Creating load-balancer wrr"
time="2018-05-30T21:58:06Z" level=debug msg="Creating server 131721799608519753 at http://10.0.0.4:12021// with weight 1"
time="2018-05-30T21:58:06Z" level=debug msg="Creating server 131721800963813340 at http://10.0.0.5:12021// with weight 1"
time="2018-05-30T21:58:06Z" level=debug msg="Creating server 131721802109741370 at http://10.0.0.6:12021// with weight 1"
time="2018-05-30T21:58:06Z" level=debug msg="Setting up backend health check [Path: /api/v1/health Port: 12021 Interval: 10s]"
time="2018-05-30T21:58:06Z" level=debug msg="Creating retries max attempts 3"
time="2018-05-30T21:58:06Z" level=info msg="Server configuration reloaded on :30080"
time="2018-05-30T21:58:06Z" level=info msg="Server configuration reloaded on :80"
time="2018-05-30T21:58:06Z" level=info msg="Server configuration reloaded on :30443"
time="2018-05-30T21:58:06Z" level=info msg="Server configuration reloaded on :38080"
time="2018-05-30T21:58:06Z" level=debug msg="Initial health check for backend: \"fabric:/MyApp/MyApp\""
time="2018-05-30T21:58:06Z" level=debug msg="Initial health check for backend: \"fabric:/MyApp/MyApp\""
time="2018-05-30T21:58:06Z" level=warning msg="Health check failed: Remove from server list. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.4:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:06Z" level=warning msg="Health check failed: Remove from server list. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.4:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:06Z" level=warning msg="Health check failed: Remove from server list. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.5:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:06Z" level=warning msg="Health check failed: Remove from server list. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.6:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:06Z" level=warning msg="Health check failed: Remove from server list. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.5:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:06Z" level=warning msg="Health check failed: Remove from server list. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.6:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:16Z" level=debug msg="Refreshing health check for backend: fabric:/MyApp/MyApp"
time="2018-05-30T21:58:16Z" level=warning msg="Health check still failing. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.4:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:16Z" level=warning msg="Health check still failing. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.5:12021//\" Reason: received non-200 status code: 404"
time="2018-05-30T21:58:16Z" level=warning msg="Health check still failing. Backend: \"fabric:/MyApp/MyApp\" URL: \"http://10.0.0.6:12021//\" Reason: received non-200 status code: 404"

```
