### ISSUE TITLE
Redirecting from host to host and rewriting headers

### ISSUE THREAD

**Issue by Nicnl** [containous/traefik#3436]
I'm trying to redirect all requests to a backend app.  
The backend app uses randomly generated subdomains, example:
 - `96b143bf932de035.backendapp.local:8080`
 - `2a28ab7da3dee699.backendapp.local:8080`
 - `509325a0d8435dde.backendapp.local:8080`
 - `c0669b001b5f653f.backendapp.local:8080`

I want to use for instance the `frontendapp.com` domain as a frontend, so that requesting  
`96b143bf932de035.frontendapp.com`  
to traefik will request the backend with the following host header:  
`Host: 96b143bf932de035.backendapp.local:8080`

### traefik.toml example

```toml
[frontends]

  [frontends.front]
    entrypoint = ["http", "https"]
    backend = "back"
    [frontends.front.routes]
      [frontends.front.routes.route0]
        rule = "HostRegexp:{subdomain:[-A-z0-9.]*}.frontendapp.com"

[backends]

  [backends.back]
    [backends.back.servers]
      [backends.back.servers.server0]
        url = "http://10.0.13.37:8080"
```
The HostRegexp correctly matches all requests to `*.frontendapp.com`  
but Traefik is not forwarding the request with the wanted host header.

### With `passHostHeader = true`

The backend server will receive a request with the following host header:  
`Host: 96b143bf932de035.frontendapp.com`  
so the backend won't send the proper response.

### With `passHostHeader = false`

The backend server will receive a request with the following host header:
`Host: 10.0.13.37:8080`  
so the backend won't send the proper response.

### What would be nice

One of the following features would be nice and would solve this kind of problem.

#### Creating a `ReplaceHeaderRegex` modifier rule that works just like `ReplacePathRegex`
Example toml:
```toml
# ...
      [frontends.front.routes.route0]
        rule = "HostRegexp:{sd1:[-A-z0-9.]*}.frontendapp.com,
                ReplaceHeaderRegex: Host ([-A-z0-9.]*)\.frontendapp\.com $1\.backendapp\.local:9999"

```

#### Using the regex from `HostRegexp` as a variable in the backend

Example toml:
```toml
# ...
      [frontends.front.routes.route0]
        rule = "HostRegexp:{subdomain:[-A-z0-9.]*}.frontendapp.com"

# ...
      [backends.back.servers.server0]
        url = "http://${subdomain}.backendapp.local:9999"

```
