### ISSUE TITLE
LetsEncrypt DNS-01 fails when mixing domains with wildcard subdomains.

### ISSUE THREAD

**Issue by CharlesStover** [containous/traefik#3468]
This may be a bug with ACME, but I'm not technical enough to know, and I'm using Traefik, so reporting it here.

### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using the traefik docker image. I configured and run it, and immediately the certificates are rejected _only when mixing wildcard domains_.

### What did you expect to see?
Wildcard subdomains to be allowed.

### What did you see instead?
```
time="2018-06-10T21:15:43Z" level=error msg="Unable to obtain ACME certificate for domains \"*.EVERYDOMAIN.com,EVERYDOMAIN.com\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[EVERYDOMAIN.com] acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Incorrect TXT record \"HASH HERE\" found at _acme-challenge.EVERYDOMAIN.com\n"
```
Points of interest:
This only happens if the wildcard domains is listed with the main domain.
Setting a delay of 5s did not fix this.
It is apparently able to set the TXT record; I'm not getting a permission error.
I believe the provider (Cloudflare) has to verify that TXT record is set before ACME even checks?

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
defaultEntryPoints = ["http", "https"]

[acme]
  email = "..."
  entryPoint = "https"
  onHostRule = true
  storage = "acme.json"
  [acme.dnsChallenge]
    delayBeforeCheck = 0
    provider = "cloudflare"

[[acme.domains]]
  main = "*.MYDOMAIN.com"
  sans = ["MYDOMAIN.com"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[web]
  address = ":8080"
  [web.auth.basic]
    users = ["..."]
```

The environment has cloudflare email and cloudflare api key in it.

When I set the wildcard subdomains to be their own `main` entry and the domain to be its own `main` entry, it works without error.
