### ISSUE TITLE
500 ERROR in accesslog

### ISSUE THREAD

**Issue by ymyjohnny** [containous/traefik#3476]
### Do you want to request a *feature* or report a *bug*?

Report a bug

### What did you see instead

i have the 500 error in accesslog,The error rate is around 1/1000
request qps is  100/s

```
223.150.95.33 - - [12/Jun/2018:07:26:11 +0000] "GET /ad HTTP/1.1" 500 21 "http://xxx.xxx.com/index.html" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E)" 7375 "xxx.xxx.com/" "http://10.255.57.12:80" 0ms
```

I use apache ab to press the results as follows
```
Server Software:        nginx
Server Hostname:        xx.xx.com
Server Port:            8090

Document Path:          /ad
Document Length:        0 bytes

Concurrency Level:      2000
Time taken for tests:   7.156 seconds
Complete requests:      10000
Failed requests:        3273
   (Connect: 0, Receive: 0, Length: 3273, Exceptions: 0)
Write errors:           0
Non-2xx responses:      3273
Total transferred:      905437 bytes
HTML transferred:       49257 bytes
Requests per second:    1397.45 [#/sec] (mean)
Time per request:       1431.182 [ms] (mean)
Time per request:       0.716 [ms] (mean, across all concurrent requests)
Transfer rate:          123.56 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       22   33  12.4     27      69
Processing:    23 1111 1376.6    260    3431
Waiting:       23 1111 1376.7    259    3431
Total:         46 1144 1377.5    300    3474

Percentage of the requests served within a certain time (ms)
  50%    300
  66%    648
  75%   3060
  80%   3066
  90%   3110
  95%   3224
  98%   3305
  99%   3316
 100%   3474 (longest request)
```

ab-log
```
46.62.65.40 - - [12/Jun/2018:07:50:12 +0000] "GET /ad HTTP/1.0" 500 21 "-" "ApacheBench/2.3" 161448 "xxx.xxx.com/ad" "http://10.255.61.10:8088" 1ms
```

### What version of Traefik are you using?

```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:27:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration

**my k8-ingress config**

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xx-igress
spec:
  rules:
  - host: xx.xxxx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc1
          servicePort: 80
      - path: /ad
        backend:
          serviceName: svc2
          servicePort: 8088
      - path: /mz
        backend:
          serviceName: svc3
          servicePort: 8088
      - path: /fuge
        backend:
          serviceName: svc4
          servicePort: 8088
```

```toml
debug = false
logLevel = "INFO"
defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":8090"
    [entryPoints.dashboard]
    address = ":8091"

[traefikLog]
filepath = "/data/algorithm/log/traefik/traefik.log"
format = "common"

[accessLog]
filePath = "/data/algorithm/log/traefik/traefik_access.log"
format = "common"

[api]
  entryPoint = "dashboard"
  dashboard = true

[ping]
  entryPoint = "dashboard"

[kubernetes]
endpoint = "http://x.x.x.x:8080"

[forwardingTimeouts]
dialTimeout = "360s"

[lifeCycle]
requestAcceptGraceTimeout = "60s"
graceTimeOut = "720s"

[respondingTimeouts]
readTimeout = "60s"
writeTimeout = "60s"
idleTimeout = "720s"
```
