### ISSUE TITLE
Docker segment_name labels not work when scale containers

### ISSUE THREAD

**Issue by migueltercero** [containous/traefik#3482]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

We use docker backend to configure traefik with docker compose like this:
```yml
version: '3'
services:
  traefik:
    image: traefik
    command: 
      --web 
      --docker 
      --docker.domain=dev.local 
      --docker.watch 
      --docker.exposedbydefault=false
      --entryPoints='Name:http Address::80' 
      --defaultEntryPoints='http'
    ports:
      - "10000:80"
      - "10001:443"
      - "10002:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: billsb/alpine-python-whoami
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mydomain.com"
      - "traefik.frontend.backend=whoami"
```
When we scale whoami service:

docker-compose up -d --scale whoami=2

traefik generate one backend with 2 containers like we expect:

![image](https://user-images.githubusercontent.com/20397404/41302728-87c50a30-6e6b-11e8-957b-e00a3f138b34.png)

But when we use segment_name (ours containers have multiple ports) like this:
```yml
version: '3'
services:
  traefik:
    image: traefik
    command: 
      --web 
      --docker 
      --docker.domain=dev.local 
      --docker.watch 
      --docker.exposedbydefault=false
      --entryPoints='Name:http Address::80' 
      --defaultEntryPoints='http'
    ports:
      - "10000:80"
      - "10001:443"
      - "10002:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: billsb/alpine-python-whoami
    labels:
      - "traefik.enable=true"
      - "traefik.**service1**.frontend.rule=Host:mydomain.com"
      - "traefik.**service1**.backend=whoami"
```
traefik creates two backends with one container each and ignores traefik.<segment_name>.backend label:

![image](https://user-images.githubusercontent.com/20397404/41302844-dd0a43d4-6e6b-11e8-83ad-21d790899f44.png)

so traefik can´t balance request between instances.

### What did you expect to see?
![image](https://user-images.githubusercontent.com/20397404/41302889-f9077cfa-6e6b-11e8-98d1-af0cf1ba8815.png)

### What did you see instead?
![image](https://user-images.githubusercontent.com/20397404/41302897-ff78c4d6-6e6b-11e8-8d45-b98378100f69.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64
```
