### ISSUE TITLE
Panic after setting ingress endpoint

### ISSUE THREAD

**Issue by alapidas** [containous/traefik#3490]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was running the traefik ingress controller on kubernetes (1.5.4), and created some ingress rules.  I then upgraded to current master (d5b649bf1cb19f8b2aa72ac00dfe6b01e6c3beeb) and set a `publishedService` name in the config a la https://github.com/containous/traefik/pull/3324 - after doing this, traefik started panicing constantly:

```
time="2018-06-13T19:08:41Z" level=error msg="Error in Go routine: runtime error: index out of range"
goroutine 46 [running]:
runtime/debug.Stack(0x73c72f, 0xc4200c82d0, 0x2304fb2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x1ef4240, 0x37a5420)
	/go/src/github.com/containous/traefik/safe/routine.go:148 +0x73
github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc420967e18)
	/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
panic(0x1ef4240, 0x37a5420)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/containous/traefik/provider/kubernetes.(*clientImpl).UpdateIngressStatus(0xc420206e40, 0xc420ee2110, 0xb, 0xc420dcb9e0, 0x17, 0xc42058da50, 0xd, 0x0, 0x0, 0x8, ...)
	/go/src/github.com/containous/traefik/provider/kubernetes/client.go:183 +0x7f6
github.com/containous/traefik/provider/kubernetes.(*Provider).updateIngressStatus(0xc420376690, 0xc420cf6158, 0x251c080, 0xc420206e40, 0x2, 0xc420e74700)
	/go/src/github.com/containous/traefik/provider/kubernetes/kubernetes.go:385 +0x373
github.com/containous/traefik/provider/kubernetes.(*Provider).loadIngresses(0xc420376690, 0x251c080, 0xc420206e40, 0x1, 0x1, 0xc4204b0720)
	/go/src/github.com/containous/traefik/provider/kubernetes/kubernetes.go:342 +0x24d2
time="2018-06-13T19:08:41Z" level=error msg="Provider connection error: Panic in operation: %!s(<nil>); retrying in 1.970514418s"
github.com/containous/traefik/provider/kubernetes.(*Provider).Provide.func1.1(0x0, 0x0)
	/go/src/github.com/containous/traefik/provider/kubernetes/kubernetes.go:139 +0x402
github.com/containous/traefik/safe.OperationWithRecover.func1(0x0, 0x0)
	/go/src/github.com/containous/traefik/safe/routine.go:160 +0x62
github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc42046f0d0, 0x24f1000, 0xc42046f0e0, 0x23a85a8, 0xc420462880, 0xc4204fcb40)
	/go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37 +0x88
github.com/containous/traefik/provider/kubernetes.(*Provider).Provide.func1(0xc420520620)
	/go/src/github.com/containous/traefik/provider/kubernetes/kubernetes.go:161 +0x13f
github.com/containous/traefik/safe.(*Pool).Go.func1()
	/go/src/github.com/containous/traefik/safe/routine.go:78 +0x3a
github.com/containous/traefik/safe.GoWithRecover.func1(0x23a8738, 0xc420206ea0)
	/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
created by github.com/containous/traefik/safe.GoWithRecover
	/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
```

Looks like the client is expecting the ingress status to exist already - this may be as easy as fixing via a nil check.
https://github.com/containous/traefik/blob/master/provider/kubernetes/client.go#L183

### What did you expect to see?

I expect my ingress rules to get annotated w/ LB status.

### What did you see instead?

Traefik panic'd constnatly.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# original config pre-upgrade
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
          regex = "^http://(.*)"
          replacement = "https://$1"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
    [kubernetes]

# config post-upgrade simply added this to kubernetes section:
      [kubernetes.ingressEndpoint]
      publishedService = "default/ingress-controller-traefik"
```

Running on Kubernetes 1.9.5 on bare metal.

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
