### ISSUE TITLE
Wrong elapsed time shown by Duration in accesslog

### ISSUE THREAD

**Issue by zong400** [containous/traefik#3493]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I want to know requests elapsed time.

### What did you expect to see?
a time like my browser shown

```console
$ time curl -vo /dev/null http://bxr.eduwxt.com/dmc/index.26938449.css
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.144.174.48...
* Connected to bxr.eduwxt.com (192.144.174.48) port 80 (#0)
> GET /dmc/index.26938449.css HTTP/1.1
> Host: bxr.eduwxt.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 418399
< Content-Type: text/css
< Date: Thu, 14 Jun 2018 01:37:43 GMT
< Etag: "5b20fd0e-6625f"
< Last-Modified: Wed, 13 Jun 2018 11:16:30 GMT
< Server: nginx/1.15.0
< 
{ [12492 bytes data]
100  408k  100  408k    0     0  8798k      0 --:--:-- --:--:-- --:--:-- 8693k
* Connection #0 to host bxr.eduwxt.com left intact

real    0m0.055s
user    0m0.004s
sys     0m0.004s
```

### What did you see instead?
a large number shown by Duration in accesslog
```shell
"4th 2018, 09:37:44.004 bxr.eduwxt.com" "GET /dmc/index.26938449.css HTTP/1.1" "200" "24,534,228" "220,354"
```
Duration:24,534,228

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
 defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/etc/traefikssl/1_bxr.eduwxt.com_bundle.crt"
        keyFile = "/etc/traefikssl/2_bxr.eduwxt.com.key"
      [entryPoints.secure]
      address = ":8443"
      [entryPoints.secure.tls]
        [entryPoints.secure.tls.ClientCA]
        files = ["/etc/traefikssl/clientca.crt"]
        optional = false
        [[entryPoints.secure.tls.certificates]]
        certFile = "/etc/traefikssl/bxr.cn.crt"
        keyFile = "/etc/traefikssl/bxr.cn.key"
    [accessLog]
    filePath = "/accesslog/access.log"
    format = "json"
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets=[0.1,0.3,1.2,5.0]
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
