### ISSUE TITLE
rewrite-target has a strange behavior on k8s

### ISSUE THREAD

**Issue by liyanliang1994** [containous/traefik#3494]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I try to replace nginx-ingress with traefik-ingress on k8s. And I find that rewrite-target has a strange behavior.
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
  name: traefik-test
spec:
  rules:
  - host: <traefik-domain>
    http:
      paths:
      - backend:
          serviceName: tomcat-service
          servicePort: 8080
        path: /qwe/asd
```
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: nginx-test
spec:
  rules:
  - host: <nginx-domain>
    http:
      paths:
      - backend:
          serviceName: tomcat-service
          servicePort: 8080
        path: /qwe/asd
```
send request
http://\<traefik-domain\>/qwe/asd/api?token=12345
http://\<nginx-domain\>/qwe/asd/api?token=12345
### What did you expect to see?
nginx:
backend recieve "GET /api?token=12345 HTTP/1.1"

### What did you see instead?
traefik:
backend recieve "GET / HTTP/1.1"

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik:1.6.3
nginx-ingress-controller:0.15.0
