### ISSUE TITLE
Multiple ReplacePathRegex evaluation fail

### ISSUE THREAD

**Issue by abrugnon** [containous/traefik#3508]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I implement these rewriting rules to set up an artifactory behind traefik. It needs several rewriting rules to work (at most one, no cascading rewrites).  Frontend priority has been added (suggested by @dtomcej ) but without success.

Only one regex is evaluated.

A compose file is available to reproduce this "behavior".

### What did you expect to see?

- Frontend dns
  - curl localhost/fake         passing as  /fake
- Frontend repo
  - curl localhost/v2/token  rewritten as  /artifactory/api/docker/docker-login/v2/token
- Frontend auth
  - curl localhost/repo/test  rewritten as /artifactory/api/docker/repo/test

### What did you see instead?

Here are the outputs of my tests :

curl localhost/repo/test    "path": "/artifactory/api/docker/repo/" OK
curl localhost/v2/token     "path": "/v2/token"  (KO : Not translated)
curl localhost/fake            "path": "/fake" OK

So, only one rewrites succeeds
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

[accessLog]
  filePath = "/dev/stdout"
[traefikLog]
   filePath = "/dev/stdout"

[entryPoints]
  [entryPoints.http]
  address = ":80"
defaultEntryPoints = ["http"]

[docker]
domain = "docker.localhost"
watch = true
exposedbydefault = false
```

A docker compose to reproduce the lab
```yaml
version: '2.0'
services:

  traefik:
    image: traefik:1.6.3
    ports:
      - 80:80

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/abrugnon/bugreport/conf:/etc/traefik

  echosvc:
    image: mendhak/http-https-echo
    labels:
       traefik.backend: 'artifactory'
       traefik.enable: 'true'
       traefik.port: '80'

       traefik.dns.frontend.entryPoints: 'http'
       traefik.dns.frontend.backend: 'artifactory'
       traefik.dns.frontend.rule: "Host:localhost"
       traefik.dns.frontend.priority: "10"

       traefik.repo.frontend.entryPoints: 'http'
       traefik.repo.frontend.backend: 'artifactory'
       traefik.repo.frontend.rule: "Host:localhost; ReplacePathRegex: ^/repo/(.*) /artifactory/api/docker/repo/$$2"
       traefik.repo.frontend.priority: "500"
       
       traefik.auth.frontend.entryPoints: 'http'
       traefik.auth.frontend.backend: 'artifactory'
       traefik.auth.frontend.rule: "Host:localhost; ReplacePathRegex: ^/v2/token$$ /artifactory/api/docker/docker-login/v2/token"
       traefik.auth.frontend.priority: "400"
```
