### ISSUE TITLE
Traefik does not respect the NO_PROXY env var (but does respect HTTP_PROXY)

### ISSUE THREAD

**Issue by MaggNorway** [containous/traefik#3509]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I started traefik as specified in the quick-start.
```
docker run --name traff -p 8080:8080 -p 80:80 -v <PATH>.toml:/etc/traefik/traefik.toml -v /var/run/docker.sock:/var/run/docker.sock traefik:alpine
```

My .docker/config.json contains:
```
     "httpProxy": "http://<IP>:8000",
     "httpsProxy": "https://<IP>:8000",
     "ftpProxy": "ftp://<IP>:8000",
     "noProxy": "127.0.0.1,172.16.0.0/12,*.docker.local,localhost"
```
(tried without the * as well)

This leads to these env vars:
```console
$ docker exec -i -t traff /bin/sh
/ # env
HTTPS_PROXY=https://<IP>:8000
no_proxy=127.0.0.1,172.16.0.0/12,*.docker.local,localhost
HOSTNAME=2fb9ba497344
SHLVL=1
HOME=/root
NO_PROXY=127.0.0.1,172.16.0.0/12,*.docker.local,localhost
https_proxy=https://<IP>:8000
http_proxy=http://<IP>:8000
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ftp_proxy=ftp://<IP>:8000
PWD=/
FTP_PROXY=ftp://<IP>:8000
HTTP_PROXY=http://<IP>:8000
```

### What did you expect to see?

With this command:

```
curl --header 'Host: test.docker.local' 'http://localhost/'
```
I excpected this result:
```
Hostname: d7fb516ed2d2
IP: 127.0.0.1
IP: 172.17.0.2
GET / HTTP/1.1
Host: test.docker.local
User-Agent: curl/7.58.0
```
### What did you see instead?

When starting the whoami test container, Traefik resolves the IP correctly but sends the HTTP request to the proxy instead of test.docker.local or 172.17.0.2 (which was the ip of the container), and I get an error message from the corp proxy server.

When removing .docker/config.json I get the expected result.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
I tried with these two images:

$ docker run traefik version
Version:      v1.6.4
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-06-15_03:12:50PM
OS/Arch:      linux/amd64


$ docker run traefik:alpine traefik version
Version:      v1.6.4
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-06-15_03:12:50PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":80"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
# [traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "log/traefik.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  # dashboard = false

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
domain = "docker.local"
watch = true

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedByDefault = true
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

As you can see, the proxy responds with 504, and the requests takes about 50ms indicating that it's on another machine. (when running locally it takes < 1 ms)

```
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://172.17.0.2:80"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.17.0.2:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.17.0.2:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://172.17.0.2:80, code: 504, Length: 2716, duration: 55.935475ms"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.17.0.2:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.17.0.2:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-06-18T13:03:52Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.docker.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:47230\",\"RequestURI\":\"/\",\"TLS\":null}"

```
