### ISSUE TITLE
Traefik not responsive after number of requests

### ISSUE THREAD

**Issue by IvanJosipovic** [containous/traefik#3524]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
We're running Traefik 1.6.4 on Windows Server Core 1709 (Also tested on 1803) in Docker Swarm Mode. After a certain number of requests from a single machine, Traefik will no longer accept traffic from this machine. Other machines are able to connect and will be routed to the right container, but the original machine will not until Traefik is restarted.

We have reproduced this on several machines, including on-premises, and cloud IaaS machines.

### What did you expect to see?
Traefik should keep routing requests

### What did you see instead?
After a certain amount of connections from a single IP, Traefik will no longer proxy connections from that IP.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.4
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-06-15_03:12:50PM
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Windows Version
```
Microsoft Windows [Version 10.0.16299.492]
Windows Server Core 1709
```
docker version
```
 Version:       17.06.2-ee-13
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    ac44d73
 Built: Mon Jun  4 16:46:59 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-13
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   ac44d73
  Built:        Mon Jun  4 16:58:47 2018
  OS/Arch:      windows/amd64
  Experimental: false
```
Docker daemon.json
```json
{
    "fixed-cidr":  "192.168.1.254/24",
    "hosts":  [
                  "tcp://0.0.0.0:2375",
                  "npipe://"
              ]
}
```

Traefik Dockerfile, based on https://github.com/StefanScherer/dockerfiles-windows/blob/master/traefik/Dockerfile.1709
```dockerfile
FROM microsoft/windowsservercore:1709 as core
FROM microsoft/nanoserver:1709
COPY --from=core /windows/system32/netapi32.dll /windows/system32/netapi32.dll

ENV TRAEFIK_VERSION 1.6.4

ADD https://github.com/containous/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_windows-amd64.exe /traefik.exe

VOLUME C:/etc/traefik
VOLUME C:/etc/ssl

EXPOSE 80
ENTRYPOINT ["/traefik", "--configfile=C:/etc/traefik/traefik.toml"]

# Metadata
LABEL org.label-schema.vendor="Containous" \
      org.label-schema.url="https://traefik.io" \
      org.label-schema.name="Traefik" \
      org.label-schema.description="A modern reverse-proxy" \
      org.label-schema.version="v${TRAEFIK_VERSION}" \
      org.label-schema.docker.schema-version="1.0"
```

docker-compose.yml
```yml
version: '3.3'

services:
  traefik:
    image: ivanjosipovic/public:traefik-v1.6.4-1709
    command:
      - "--logLevel=DEBUG"
      - "--docker"
      - "--docker.domain=docker.local"
      - "--docker.endpoint=tcp://192.168.1.1:2375"
      - "--docker.swarmMode"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--entrypoints=Name:http Address::80"
      - "--defaultentrypoints=http"
    ports:
      - target: 80
        published: 80
        mode: host

  webapp:
    image: microsoft/dotnet-samples:aspnetapp-nanoserver-1709
    depends_on:
      - traefik
    deploy:
      endpoint_mode: dnsrr
      labels:
       - "traefik.enable=true"
       - "traefik.port=80"
       - "traefik.frontend.rule=Host:tst-app.com"
       - "traefik.backend.loadbalancer.method=drr"
       - "traefik.docker.network: traefik"
    ports:
      - target: 80
        published: 8080
        mode: host

networks:
  default:
    external:
      name: traefik
```

#### On Docker Host:
Install Windows Server Core 1709

```
Install-Module DockerMsftProvider -Force
Install-Package Docker -ProviderName DockerMsftProvider  -Force
```

Copy `daemon.json` above to `C:\ProgramData\docker\config`

```
start-service docker
docker swarm init
docker network create --driver=overlay traefik
docker stack deploy --compose-file docker-compose.yml --prune Base
````

#### On a remote machine:

Add a entry to the hosts file for, {docker host ip } tst-app.com

Download bombardier, https://github.com/codesenberg/bombardier/releases
Run:
```
.\bombardier-windows-amd64.exe -c 100 -n 5000 http://tst-app.com
```

Once this is complete, try loading the site through a browser, it will not work.
However, if you try http://tst-app.com:8080 this will work as it bypasses Traefik

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Log is too large to paste here, a zip can be grabbed here, https://1drv.ms/u/s!ArrmDf0NziYphOZhvuh8p6Xk9eflqw
