### ISSUE TITLE
Kubernetes configmap for [file] rules.toml can't be hot update

### ISSUE THREAD

**Issue by swqmaven** [containous/traefik#3525]
Bug ?

used kubernets config for [file] rules.toml and set watch=ture when i update configmap the traefik can't be reload for new rule config?

kubernetes version
```
1.10
```

traefik version
```
1.6
```

ds.yaml
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      nodeSelector:
        edgenode: "true"
      volumes:
#      - name: ssl
#        secret:
#          secretName: traefik-cert
      - name: config
        configMap:
          name: traefik-conf
      - name: rules
        configMap:
          name: traefik-rules
      containers:
      - image: image.rightcloud.com.cn/library/traefik:1.6
        name: traefik-ingress-lb
        volumeMounts:
#        - mountPath: "/ssl"
#          name: "ssl"
        - mountPath: "/config"
          name: "config"
        - mountPath: "/rules"
          name: "rules"
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --configfile=/config/traefik.toml
        - --api
        - --kubernetes
        - --file
        - --file.filename=/rules/rules.toml
        - --file.watch=true
        - --logLevel=INFO
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
```

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]
#accessLogsFile = "/etc/traefik/log/access.log"
################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":80"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
#[traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
#filePath = "/etc/traefik/log/traefik.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
#[file]
#filename = "/rules/rules.toml"
#watch = true

[retry]
attempts = 3

[api]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  # dashboard = false

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
# domain = "docker.localhost"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedByDefault = true

```

rule.toml
```


# 测试环境demo配置前端配置
[frontends]
  # 定义接入点
  [frontends.rdtest]
  passHostHeader = true
  priority = 10
  # 定义后端名称
  backend = "rdtest"
    # 前端监听域名,可以监听多域名
    [frontends.rdtest.routes.service]
      rule = "Host:test.rd.rightcloud.com.cn;"

  [frontends.rdtestprotal]
  passHostHeader = true
  priority = 10
  # 定义后端名称
  backend = "rdtestprotal"
    # 前端监听域名,可以监听多域名
    [frontends.rdtestprotal.routes.service]
      rule = "Host:portal.test.rd.rightcloud.com.cn;"

# 后端配置
[backends]
  [backends.rdtest]
    # 后端网络错误率>0.5 停止转发；
    [backends.rdtest.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    # 轮训方式，method=drr（加权轮训调度）default：wrr（队列轮转算法）
    [backends.rdtest.LoadBalancer]
      method = "wrr"
    # 安全限制，单个主机连接数大于指定值
    [backends.rdtest.maxconn]
      amount = 10
      extractorfunc = "request.host"
    [backends.rdtest.servers.server1]
      url = "http://10.68.7.94:8445"
      weight = 1

  [backends.rdtestprotal]
    # 后端网络错误率>0.5 停止转发；
    [backends.rdtestprotal.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    # 轮训方式，method=drr（加权轮训调度）default：wrr（队列轮转算法）
    [backends.rdtestprotal.LoadBalancer]
      method = "wrr"
    # 安全限制，单个主机连接数大于指定值
    [backends.rdtestprotal.maxconn]
      amount = 10
      extractorfunc = "request.host"
    [backends.rdtestprotal.servers.server1]
      url = "http://10.68.7.94"
      weight = 1

```
