### ISSUE TITLE
Traefik always looks for tls.crt and tls.key regardless of settings

### ISSUE THREAD

**Issue by ferrarimarco** [containous/traefik#3527]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Created a Kubernetes secret holding the certificate (`ingress.crt`) and the key (`ingress.key`)
1. Created a Kubernetes deployment with a volume mounted @ /tls with the above files
1. Configured Traefik TLS endpoint to use the specified crt and key via configuration file (see below)

### What did you expect to see?

Traefik to use the specified crt and key.

### What did you see instead?

Traefik looks for `tls.cr` and `tls.key` regardless of the file name you set in the configuration file.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
[vagrant@kubernetes-master-1 ~]$ kubectl exec traefik-ingress-controller-688444c656-cvd5w --namespace kube-system -it -- /traefik version
Version:      v1.6.4
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-06-15_03:12:50PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    logLevel = "INFO"
    [api]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/tls/ingress.crt"
          KeyFile = "/tls/ingress.key"
    [kubernetes]
    [metrics]
      [metrics.prometheus]
```

Running in Kubernetes 1.10 with the following configuration:

```yaml
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        volumeMounts:
        - mountPath: "/tls"
          name: "tls"
        - mountPath: "/config"
          name: "config"
        args:
        - --configfile=/config/traefik.toml
      volumes:
      - name: tls
        secret:
          secretName: traefik-cert
      - name: config
        configMap:
          name: traefik-ingress-config
```

The secret is created with:

```
kubectl create secret generic traefik-cert --from-file=/opt/tls/self_signed/ingress.crt --from-file=/opt/tls/self_signed/ingress.key --namespace kube-system
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-06-22T08:48:53Z" level=info msg="Using TOML configuration file /config/traefik.toml"
time="2018-06-22T08:48:53Z" level=info msg="Traefik version v1.6.4 built on 2018-06-15_03:12:50PM"
time="2018-06-22T08:48:53Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-06-22T08:48:53Z" level=info msg="Preparing server https &{Address::443 TLS:0xc4205d4c00 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4202bf0e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-06-22T08:48:53Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4202bf100} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-06-22T08:48:53Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4202bf0c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-06-22T08:48:53Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\"}"
time="2018-06-22T08:48:53Z" level=info msg="Starting server on :443"
time="2018-06-22T08:48:53Z" level=info msg="Starting server on :8080"
time="2018-06-22T08:48:53Z" level=info msg="Starting server on :80"
time="2018-06-22T08:48:53Z" level=info msg="ingress label selector is: \"\""
time="2018-06-22T08:48:53Z" level=info msg="Creating in-cluster Provider client"
time="2018-06-22T08:48:54Z" level=error msg="Error configuring TLS for ingress kube-system/traefik-web-ui: secret kube-system/traefik-cert does not exist"
time="2018-06-22T08:48:54Z" level=info msg="Server configuration reloaded on :8080"
time="2018-06-22T08:48:54Z" level=info msg="Server configuration reloaded on :80"
time="2018-06-22T08:48:54Z" level=info msg="Server configuration reloaded on :443"
time="2018-06-22T08:48:54Z" level=error msg="Error configuring TLS for ingress kube-system/traefik-web-ui: secret kube-system/traefik-cert is missing the following TLS data entries: tls.crt, tls.key"
```
