### ISSUE TITLE
traefik:latest image is not working with separate file for rules.

### ISSUE THREAD

**Issue by xiaods** [containous/traefik#3550]
### Do you want to request a *feature* or report a *bug*?

traefik can't hot load the rules on separate file.

### What did you do?

Aliyun Cloud, ECS server, Ubuntu 16.04, docker run traefik image, it can't hot reload the config file.

### What did you expect to see?
following the Traefik docs, support separate file feature.

### What did you see instead?
currently i have to add all rules in on configuration, traefik.toml, it works fine. i can't separate the rules in another files.
below config is not working.
```
[file]
  directory = "/path/to/config/"
  watch = true
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker image latest version, 1.6.4 latest version

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by geraldcroes** [comment]
Hi and thanks for your question!

Are you sure that Traefik can access the directory `/path/to/config/` and that it contains files with the .toml extension?

Bellow is an example using docker-compose, could you confirm that it works on your system?

The `/workspace/issue_3550/docker.compose.yml` file:

```yml
version: '3'
  
services:
  reverse-proxy:
     image: traefik:1.6.4
     ports:
       - "80:80"
       - "8082:8082"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /workspace/tests/traefik/issue_3550/traefik.toml:/traefik.toml
       - /workspace/tests/traefik/issue_3550/toml/:/toml/
```

The `/workspace/issue_3550/traefik.toml` file:

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[api]

[file]
watch = true
directory = "/toml/"

[entryPoints]
  [entryPoints.traefik]
  address = ":8082"

  [entryPoints.http]
  address = ":80"
```

And finally a `/workspace/toml/test.toml` file you can add / update "after" Traefik is started ...

```toml
[frontends]
  [frontends.frontend1]
    entryPoints = ["http"]
    backend = "backend1"

[backends]
   [backends.backend1]
      [backends.backend1.servers.server0]
        url = "http://10.10.10.1:80"
      [backends.backend1.servers.server1]
        url = "http://10.10.10.2:80"
```

Everything shows up in the dashboard, as expected ... and the corresponding logs: 

```json
reverse-proxy_1  | time="2018-07-02T13:29:21Z" level=debug msg="Configuration received from provider file: {\"backends\":{\"backend1\":{\"servers\":{\"server0\":{\"url\":\"http://10.10.10.1:80\",\"weight\":0},\"server1\":{\"url\":\"http://10.10.10.2:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend1\":{\"entryPoints\":[\"http\"],\"backend\":\"backend1\",\"priority\":0,\"basicAuth\":null}}}"
```
