### ISSUE TITLE
Traefik Dashboard listening on custom context root

### ISSUE THREAD

**Issue by sbueringer** [containous/traefik#3552]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hi,

I tried to get the Traefik dashboard to listen on another context root then `/`, but afaik it's not possible. I added the following lines to the .toml file:
```toml
    [frontends]
      [frontends.traefikAPI]
        backend = "traefik"
        [frontends.traefikAPI.routes.traefikAPI]
          rule = "PathPrefixStrip:/traefik"
          
    [backends]
      [backends.traefik]
        [backends.traefik.servers.traefik]
          url = "http://localhost:8080"
```
The UI itself is rendered now but there are problems with the backend calls e.g. to `/api/providers`, because the dashboard is not aware of the changed context root.

**Comment by geraldcroes** [comment]
Hi, and thank you for your feedback.

I cannot reproduce your issue. Are you using the latest version of Traefik?

I used your exact configuration file with success, here is the whole docker-compose & traefik.toml if you want to see for yourself.

```yml
version: '3'

services:
  reverse-proxy:
     image: traefik:1.6.4
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /workspace/tests/traefik/issue_3552/traefik.toml:/traefik.toml
```

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[api]

[file]

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"

  [entryPoints.http]
    address = ":80"

[frontends]
  [frontends.traefikAPI]
    backend = "traefik"
    [frontends.traefikAPI.routes.traefikAPI]
      rule = "PathPrefixStrip:/traefik"

[backends]
  [backends.traefik]
    [backends.traefik.servers.traefik]
      url = "http://localhost:8080"
```

Let us know if this works for you.

In the meantime, if you allow me, I will close the issue.

If you need further assistance, don't hesitate to come to our [slack support channel](https://slack.traefik.io/) where we'll be happy to help 😀
