### ISSUE TITLE
Combine Host rules on Kubernetes Ingress to request single cert

### ISSUE THREAD

**Issue by bradjones1** [containous/traefik#3557]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When using Let's Encrypt with Kubernetes, it's possible to set `onHostRule` in the main ACME configuration to have Let's Encrypt request certificates for the host rules. The Kubernetes API spec specifies that the host value in each ingress rule must generally conform to the RFC on hostnames, precluding for instance a comma-separated list. The general Traefik Let's Encrypt implementation allows for alternate names to be provided in that fashion, but we can't due to this limitation on the Ingress spec.

I would propose we add a configuration or annotation option that could be specified on the ingress to instruct Traefik to request a single cert for all the hosts specified in the ingress's rules.

**Comment by marc-j** [comment]
I'm currently testing a system implemented in version 1.5 with annotations to use a rules with multiple hosts, so only one certificate is generated:

[provider/kubernetes/kubernetes.go](https://github.com/containous/traefik/blob/482afed4a6b2ccc547170968b6b65ebc40fde904/provider/kubernetes/kubernetes.go#L247):
```go
if len(r.Host) > 0 {
    rule := "Host:" + r.Host

    hostsAnnotation, ok := i.Annotations["traefik.frontend.routes." + r.Host]
    if ok && len(hostsAnnotation) > 0 {
        log.Debugf("Ingress rules hosts : %s (%s)", "traefik.frontend.routes." + r.Host, hostsAnnotation)
	rule = "Host: " + hostsAnnotation
    } else if strings.Contains(r.Host, "*") {
	rule = "HostRegexp:" + strings.Replace(r.Host, "*", "{subdomain:[A-Za-z0-9-_]+}", 1)
   }
 ...
```
ingress.yml :
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.routes.mydomain.tld: "mydomain.tld,www.mydomain.tld"
spec:
  rules:
    - host: mydomain.tld
      http:
        paths:
          - backend:
              serviceName: website
              servicePort: 80
```
