### ISSUE TITLE
Using command line to configure TLS fails

### ISSUE THREAD

**Issue by trajano** [containous/traefik#3569]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```yml
services:
  traefik:
    image: traefik:alpine
    command:
    - --entryPoints='Name:http Address::80 Compress:true Redirect.EntryPoint:https' 
    - --entryPoints='Name:https Address::443 Compress:true TLS:/ssl/tls.crt,/ssl/tls.key'
    secrets:
    - source: star_key
      target: /ssl/tls.key
    - source: star_cert
      target: /ssl/tls.crt
secrets:
  star_key:
    external: true
  star_cert:
    external: true
```

I also tried creating a toml file and embed it in the container and that one works.

### What did you expect to see?

No errors, same as using a toml configuration file.

### What did you see instead?

```
time="2018-07-06T21:38:35Z" level=error msg="Unable to add a certificate to the entryPoint \"\" : unable to generate TLS certificate : tls: failed to find any PEM data in key input"
time="2018-07-06T21:38:35Z" level=error msg="Error creating TLS config: No certificates found for TLS entrypoint "
time="2018-07-06T21:38:35Z" level=fatal msg="Error preparing server: No certificates found for TLS entrypoint "

```
### Output of `traefik version`: (_What version of Traefik are you using?_)

`traefik:latest`
`traefik:alpine`

### Configuration

```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
      [entryPoints.http.redirect]
      entryPoint = "https"

    [entryPoints.https]
    address = ":443"
    compress = true

        [[entryPoints.https.tls.certificates]]
        certFile = "/ssl/tls.crt"
        keyFile = "/ssl/tls.key"
[api]
[ping]
[docker]
watch = true
swarmMode = true
```

### Command line

```
    command:
    - --api
    - --api.dashboard
    - --ping
    - --docker
    - --docker.swarmmode
    - --docker.watch
    - --docker.exposedbydefault=false
    - --entryPoints='Name:http Address::80 Compress:true Redirect.EntryPoint:https' 
    - --entryPoints='Name:https Address::443 Compress:true TLS:/ssl/tls.crt,/ssl/tls.key'

```
