### ISSUE TITLE
HTTP to HTTPS redirect not working as expected with docker

### ISSUE THREAD

**Issue by andig** [containous/traefik#3573]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm running traefik 1.6.3 in docker on a NAS; using ports 8080 and 8443 as 80 and 443 were already taken. My router is redirecting 80 -> nas:8080 and 443 -> nas:8443. This is already working fine for HTTPS access.

The goal is to implement HTTP to HTTPS redirect. Since the traefik HTTPS port in docker is 8443 I've added a secondary entrypoint using 443 to "redirect" to in order for the port numbers- when accessed externally- to match.

```toml
    defaultEntryPoints = ["https"]
    [entryPoints]
      [entryPoints.traefik]
      address = ":8000"
      [entryPoints.http]
      address = ":8080"
        [entryPoints.http.redirect]
        entryPoint = "httpsExternal"
      [entryPoints.https]
      address = ":8443"
        [entryPoints.https.tls]
      [entryPoints.httpsExternal]
      address = ":443"
        [entryPoints.httpsExternal.tls]
```
I then 

    curl http://volkszaehler.io

### What did you expect to see?

Redirect to https://volkszaehler.io at port 443

### What did you see instead?

    ❯ curl -v http://volkszaehler.io
    * Rebuilt URL to: http://volkszaehler.io/
    *   Trying 77.23.37.87...
    * TCP_NODELAY set
    * Connected to volkszaehler.io (77.23.37.87) port 80 (#0)
    > GET / HTTP/1.1
    > Host: volkszaehler.io
    > User-Agent: curl/7.54.0
    > Accept: */*
    >
    < HTTP/1.1 302 Found
    < Location: https://volkszaehler.io:8443/
    < Date: Sun, 08 Jul 2018 20:38:14 GMT
    < Content-Length: 5
    < Content-Type: text/plain; charset=utf-8
    <

This is still using the wrong port 8443.

### Output of `traefik version`: (_What version of Traefik are you using?_)

    v1.6.3
