### ISSUE TITLE
[Swarm][Encrypted network] Traefik doesn't work on swarm mode with --opt encrypted network

### ISSUE THREAD

**Issue by mikafouenski** [containous/traefik#3581]
<!--
DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, please refer to one of the following:

- Stack Overflow (using the "traefik" tag): https://stackoverflow.com/questions/tagged/traefik
- the Traefik community Slack channel: https://slack.traefik.io

-->

Hello, 

### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I'm trying to setup the [basic tuto](https://docs.traefik.io/user-guide/swarm-mode/) with encrypted overlay to evaluate the solution.

I have created a tree "machines" cluster, with my own as manager and two with docker machine as follow:

`docker-machine create minion2`
`docker-machine create minion2`

Init the swarm:
`192.168.1.111` = my ip on my local network
```shell
docker swarm init --advertise-addr 192.168.1.111 --listen-addr 192.168.1.111
a=$(docker swarm join-token worker -q)
docker-machine ssh minion1 "docker swarm join --token=${a} --listen-addr $(docker-machine ip minion1) --advertise-addr $(docker-machine ip minion1) 192.168.1.111"
docker-machine ssh minion2 "docker swarm join --token=${a} --listen-addr $(docker-machine ip minion2) --advertise-addr $(docker-machine ip minion2) 192.168.1.111"
```
The result cluster:
```console
$ docker node ls                                                                                                                                                                                                                             
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
262tijbfjzvixah7leb9r85i4 *   chevreuil           Ready               Active              Leader              18.05.0-ce
k0kvfg1vu8qbnjweomty7xdjp     minion1             Ready               Active                                  18.05.0-ce
5e81xbwlzgbdyqcglxs98zy4y     minion2             Ready               Active                                  18.05.0-ce
```

I wrote a tiny `test.yml` stack file who run a traefik and whoami:
```yml
version: "3.5"

networks:
  traefik-net:
    name: traefik-net
    driver: overlay
    driver_opts:
      encrypted: "true"

services:

  whoami:
    image: emilevauge/whoami
    networks:
      - traefik-net
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.backend=whoami"
        - "traefik.frontend.rule=Host:whoami.traefik"
        - "traefik.backend.loadbalancer.sticky=true"

  traefik:
    image: traefik:1.6.4
    command: -c /dev/null --api --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG
    networks:
      - traefik-net
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels: &labels
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-net"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.traefik"
      - "traefik.enable=true"
    deploy:
      placement:
        constraints: [node.role == manager]
      labels: *labels
```

Which one I run with:
```console
$ docker stack deploy -c test.yml test                                                                                                                                                                                                        
Creating network traefik-net                                                                                                                                                                                                                  
Creating service test_traefik                                                                                                                                                                                                                 
Creating service test_whoami  
```
When I check on the minions I see the container. All container are created.

But when I run:
```console
$ curl -v -L -H "Host:whoami.traefik" http://192.168.1.111
* Rebuilt URL to: http://192.168.1.111/
*   Trying 192.168.1.111...
* TCP_NODELAY set
* Connected to 192.168.1.111 (192.168.1.111) port 80 (#0)
> GET / HTTP/1.1
> Host:whoami.traefik
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 504 Gateway Timeout
< Set-Cookie: _TRAEFIK_BACKEND=http://10.0.0.21:80; Path=/
< Date: Mon, 09 Jul 2018 14:47:35 GMT
< Content-Length: 15
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 192.168.1.111 left intact
Gateway Timeout
```
I get "Gateway Timeout", instead of whoami output.

No useful log from traefik unfortunately...
Running the same file and commenting 
```yml
    driver_opts:
      encrypted: "true"
```
everything is working as expected.

### Output of `traefik version`: 
docker image latest(1.6.4) sha256:98d82a5fa9a27382de1666ecd385d32fdaa89266a8426b378b040c68c345bf85


### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker version 18.05.0-ce, build f150324782
Kernel: 4.17.3-1-ARCH

Thanks for your time,
Mickaël

EDIT 1: copy/paste error.
