### ISSUE TITLE
Default Service For Consul Catalog

### ISSUE THREAD

**Issue by CbrandVendini** [containous/traefik#3588]
## Feature Request ##

When using the consulCatalog backend there is no way to set a default ServiceName.

## Use Case ##

We have a traefik instance in which all hostnames should go to the same consul service. It would be great to be able to set a default service for a hypothetical service named http-service
```toml
[consulCatalog]
endpoint = "172.17.0.1:8500"
exposedByDefault = false
prefix = "traefik"
frontEndRule = "Backend: http-service"
```

Or
```toml
[consulCatalog]
endpoint = "172.17.0.1:8500"
exposedByDefault = false
prefix = "traefik"
frontEndRule = "ServiceName: http-service"
```

The advantage of this over setting a static backend is to allow consul to dictate the nodes that are part of the service group as well as the ports on which they operate. We can use a static backend and frontend but this then requires that we maintain the list of nodes as well as know what port they operate on.
