### ISSUE TITLE
Cross Docker Compose Project Proxy

### ISSUE THREAD

**Issue by Southclaws** [containous/traefik#3599]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I currently deploy a bunch of services from a single compose project - this includes a couple of wordpress sites, some API servers, some frontends, databases and, of course, Traefik.

I'm currently splitting that monolithic compose file into separate projects so I can move individual projects to other servers in future.

I've started with [one project](https://github.com/Southclaws/samp-servers-api) to test the waters but it seems Traefik doesn't seem to work the same with cross-project deployments.

### What did you expect to see?

Traefik proxy my services.

### What did you see instead?

Traefik not proxy my services.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.4
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-06-15_03:12:50PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# -
# Global configuration
# -

debug = false
logLevel = "WARN"
defaultEntryPoints = ["http", "https"]
format = "common"


[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
    address=":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic
        # omitted

[acme]
  email = "-" # omitted
  entryPoint = "https"
  storage = "/etc/traefik/acme/acme.json"
  acmeLogging = true
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

# -
# Web configuration backend
# -

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true

# -
# Docker configuration backend
# -

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedbydefault = true
  watch = true

# -
# Metrics
# -

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
```

This is the compose file for the main service, I've omitted all the other services and left just the Traefik configuration:

```yaml
version: '3.5'
networks:
    default:
        driver: bridge
        internal: false
    mongodb:
        driver: bridge
        internal: true
services:
    traefik:
        image: 'traefik:1.6.4'
        command: '--api --docker'
        restart: on-failure
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
            - '${DASH_PORT}:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './traefik.toml:/etc/traefik/traefik.toml'
            - './acme:/etc/traefik/acme'
        labels:
            - 'traefik.frontend.rule=Host:traefik.southcla.ws'
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.port=8080
```

And [this is the configuration](https://github.com/Southclaws/samp-servers-api/blob/master/docker-compose.yml) for the other project I'm trying to split off - it originally existed in the above compose file but, as I said, I want to separate these configurations.

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

I have monitoring requests (`/metrics` style) setup for most services and debug logs seem to log every request so I'll only grab this if absolutely necessary.

If necessary I could try and reproduce this on an empty server, if it is actually a bug and not a configuration problem.

**Comment by dduportal** [comment]
Hello @Southclaws !

Thank you for your interest in the Træfik project and for you detailed feedback.

I tried to reproduce your case with the following Gist - https://gist.github.com/dduportal/7ad661227defd28f791ac3a99600c3c2 (a `traefik.toml`, a `docker-compose.yml` for Træfik and an `app.yml` for your application + the `.env` file) .

(Un)Fortunately, I see the services appearing in Traefik's WebUI (except the sample-api server because the container is restarting due to some go panics), so I am not sure about what is happening in your case:
<img width="1217" alt="capture d ecran 2018-07-12 a 12 16 17" src="https://user-images.githubusercontent.com/1522731/42627483-79ba8da6-85cd-11e8-933f-6535a5384958.png">


Could you check Traefik's log and show us also the status of containers and network if you stil have the issue?

N.B. you might want to use the docker-compose network's external reference, to avoid some namespacing issues

**Comment by Southclaws** [comment]
In my case, the services still appear on the Traefik frontend but when I hit the URL with curl/browser I get a 504 "Gateway Timeout" - sorry I actually completely forgot to mention that in my original issue!

Could it be that Traefik is running in a different project so it's on a different network? In my setup, I have `deployments` which is my monolithic compose project and then `samp-servers` which is the first "offshoot" (which, hopefully, everything else will also copy this separate project setup).

So I have Traefik connected to `deployments_default` and samp-servers (api server, frontend, mongodb) connected to `samplist_default` and `samplist_mongodb`.

Could this be resolved by creating an external network `web` and connecting both projects to that? I recently came across the problems outlined in #1254 and resolved that by explicitly setting everything to use the `deployments_default` network. I *did* actually try to use an external network but that resulted in every single servive getting 504'd

**Comment by Southclaws** [comment]
I figured it out! Just in case anyone finds this via search, my solution:

It turned out that an external network is the way to do this, the first time I tried this I forgot to set `--internal=false` in the `docker network create` command. Once I did this, I switched *every* docker-compose file to use:

```yml
networks:
  default:
    external:
      name: gateway
```

Where gateway was created with:

```bash
docker network create \
    --driver=bridge \
    --attachable \
    --internal=false \
    gateway
```
