### ISSUE TITLE
wildcard subdomain for Docker backend

### ISSUE THREAD

**Issue by pilgrim2go** [containous/traefik#361]
Hi,

I would like to have wildcard subdomain   *.vinceredev.com.
I tried config
```
traefik:
  image: traefik
  command: -c /dev/null --web --docker --docker.domain=vinceredev.com --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:{subdomain:[a-z]+}.vinceredev.com"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:{subdomain:[a-z]+}.vinceredev.com"

```

and expect

```
url -H Host:xxx.vinceredev.com http://127.0.0.1

```
return result page 
but got 
```
404 page not found
```

Does traefik support wildcard subdomain with Docker label?

Regards,
Van
