### ISSUE TITLE
docker.UseBindPortIP ignored

### ISSUE THREAD

**Issue by systemmonkey42** [containous/traefik#3622]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created traefik.toml file containing;
```toml
[docker]
   endpoint = "unix:///var/run/docker.sock"
   domain = "xxxxxxxxxxxxxxxxxxxx"
   exposedbydefault = true
   watch = true
   usebindportip = true
```

Configured docker container as
```yml
service:
    test:
        image: xxxxxx
         ports:
             -  192.168.0.10:8080:8080
```

### What did you expect to see?

In traefik dashboard - backend for `test` should be `192.168.0.10:8080`

### What did you see instead?

in traefik dashboard - backend for `test` was `172.18.0.2:8080`

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

Assuming I was using the option usebindportip incorrectly, I jumped into the source and added some diagnostics, what I found was that the bound ports returned by docker were `8080/tcp` and the `docker/config.go`  was performing a case sensitive comparison against `port+"/TCP"`.   This resulted in no bound ports ever matching.

Once I fixed this, and the ports matched, all containers which did not explicitly include port IP bindings inherited the ip address `0.0.0.0` which would not work.

The following fixes both problems; starting at https://github.com/containous/traefik/blob/dbe720f0f10369d60fd8a81f2d62bfd33db4fa99/provider/docker/config.go#L240-L244

```diff
       if strings.EqualFold(string(netPort), port+"/TCP") || strings.EqualFold(string(netPort), port+"/UDP") {
                  for _, p := range portBindings {
~                     if p.HostIP != "0.0.0.0" {
+                         return p.HostIP
+                     }
        
```

This ensures the comparison is not case sensitive, and ports without an explicit HostIP get the correct IP.

Note that fixes my current issue, however once the 'useportbindip' works, you have a new issue;

The following docker compose fragment;
```yml
service:
    test:
        image: xxxxxx
         ports:
             -  192.168.0.10:8080:8080
```
results in a backend pointing to `192.168.0.10:8080` (assuming the aforementioned patch) which is correct.

The following docker compose fragment;
```yml
service:
    test:
        image: xxxxxx
         ports:
             -  192.168.0.10:80:8080
```
also results in a backend pointing to `192.168.0.10:8080` which is no longer correct.

When `UsePortBindIP` is active, and an alternative `BindIP` is found, it must use the associated bound port, not the internal port.

Note that adding the label
```yml
       labels:
          - traefik.port=80
```
resulted in a backend pointing to `172.18.0.2:80` which I assume is because it could not find an existing port 80 in the set of bound ports since it only looks at the internal port value, not the mapped port value.

Tracking this down was beyond what I could do in the time I had.

Kind Regards
David
