### ISSUE TITLE
ACME Client can't validate with override DNS ip

### ISSUE THREAD

**Issue by trustfather** [containous/traefik#3626]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
acme dns challenge.
Traefik's acme client can't validate my domain when I override the ip on a machine on my local network

More precisely, I have an A machine. On this machine there's Traefik with services.
When I try to connect to this machine from the internet. the DNS A of my domain will redirect to my wan IP address. necessarily to be able to access it from the internet. However, when I am on my local network, I asked my router to router for my domain's IP address to my local network's IP address. To avoid using the internet when I want to consult the domain. That way everything can pass only over LAN. Unfortunately traefik's acme client doesn't seem to like it too much when I override the domain ip. So he loses the area, I think.
**I want to clarify that when I don't override the ip, everything works very well (thanks traefik :) )**

Translated with www.DeepL.com/Translator

### What did you expect to see?
Get the certificate like when i didn't override my DNS

### What did you see instead?
I expressly replaced my domain by SECRETDOMAIN

traefik    | time="2018-07-16T13:09:05Z" level=error msg="Unable to obtain ACME certificate for domains \"*.SECRETDOMAIN.net\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[plerion.net] Error presenting token: Zone net. not found in CloudFlare for domain _acme-challenge.plerion.net.\n"

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "SECRETDOMAIN.net"
watch = true
exposedByDefault = true

[acme]
email = "secret@secret.net"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.SECRETDOMAIN.net"


```
