### ISSUE TITLE
Add label matching for kubernetes ingests

### ISSUE THREAD

**Issue by pnegahdar** [containous/traefik#363]
I want to add label (or annotation) matching to kubernetes. i.e 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app_name
  labels:
     - traeffik/balancer-name: load-balancer-1
spec:
  rules:
  - host: news.site.com
    http:
      paths:
      - backend:
          serviceName: "app_service"
          servicePort:  80 
```

`traefik --web --kubernetes --kubernetes.label-filter "traefik/balancer-name=load-balancer-1"` would then ensure only those with that label join the balancer. 

See: http://kubernetes.io/docs/user-guide/labels/#label-selectors

I know namespaces are currently supported but thats not fine-grained enough for most kube deploy systems. Thoughts on this?
