### ISSUE TITLE
Losing data when requesting larger files over traefik with limited bandwidth

### ISSUE THREAD

**Issue by kdrblkbs** [containous/traefik#3633]
### Do you want to request a *feature* or report a *bug*?

I want to report a bug.

### What did you do?
In our "real" processing we have a service that simply provides arbitrary downloads. To be able to reproduce the issue reliably, we replaced it with a dummy service that simply responds with random 55mb for each request. We requested data from this service with simulated limited bandwidth. We used `wget` to accomplish this with `--limit-rate` as follows:
```bash
wget --limit-rate=100k traefiktest-provider.*[munched]*.de --no-check-certificate
```

### What did you expect to see?
Successfully download the whole random 55mb.

### What did you see instead?
The download aborts after a short time and the downloaded data is not complete. Most of the time, during our local tests, we were only able to download something in the range of 3-6mb. Without the 
```bash
--limit-rate=100k
```
this just works fine.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Our toml looks like this:
```toml
defaultEntryPoints = ["http","https"]
checkNewVersion = false
ProvidersThrottleDuration = 5
MaxIdleConnsPerHost = 400
RootCAs = [ "/usr/local/share/ca-certificates/*[munched]*.crt" ]
debug = true
logLevel = "DEBUG"

[traefikLog]
  filePath = "/dev/stdout"
  format   = "json"

[accessLog]
  filePath = "/dev/stdout"
  format = "json"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/*[munched]*crt"
      KeyFile = "/etc/ssl/*[munched]*.key"
  [entryPoints.traefik]
    address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
swarmmode = true
domain = "*[munched]*.de"
watch = true

[lifeCycle]
requestAcceptGraceTimeout = "60s"
graceTimeOut = "720s"

[respondingTimeouts]
idleTimeout = "720s"

[forwardingTimeouts]
dialTimeout = "720s"

[api]
  entryPoint = "traefik"
  dashboard = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
```
Our productive swarm has 15 nodes. Three of them are managers and we enforced that on each manager we have a running traefik instance. But this is also reproducible in a simple test setup with two nodes
```console
root@*[munched]*-001:~# docker node ls
ID                            HOSTNAME                   STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
u27he9xn9v9qqjdrh1vvi5wr6 *   *[munched]*-001                Ready               Active              Leader              18.03.1-ce
7vu86tuubo2bpsg9w1btwynlz    *[munched]*-002               Ready               Active                                  18.03.1-ce
```
with a running traefik instance on the manager in a dedicated management stack:
```yml
version: '3'
####
####
services:
  traefik:
    image: *[munched]*/traefik/dev
    command: --configfile=/etc/traefik/traefik.toml
    networks:
     - traefik
    ports:
      - 80:80
      - 443:443
      - 8182:8182
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
      labels:
       - traefik.port=8080
       - traefik.docker.network=atam_ata-management
      placement:
        constraints:
         - node.role == manager
networks:
  default:
  traefik:
    external:
      name: atam_ata-management
```
The service that provides the downloads runs in its own stack:

```yml
version: '3'
services:
  provider:
    image: *[munched]*/traefikdebug/provider
    networks:
      traefik:
    deploy:
      labels:
       - traefik.port=8080
       - traefik.docker.network=atam_ata-management
networks:
  default:
  traefik:
    external:
      name: atam_ata-management

```

Here follows the output of docker inspect on the traefik overlay network:
```json
[
    {
        "Name": "atam_ata-management",
        "Id": "kik489j6sm08255lxo6wo2qrd",
        "Created": "2018-06-20T14:48:44.302796415+02:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1c995534754792d8d59458463318d99e8e9745460cfa5e9c44e7a19e899f8e0c": {
                "Name": "faas_gateway.1.2y44dbk1ast9mvy5kl8sf5dqv",
                "EndpointID": "69c2af8d2ada3b51850ae180a8d420b1ba5dea96a63b3ebd4739e2edd6a569c6",
                "MacAddress": "02:42:0a:00:00:f1",
                "IPv4Address": "10.0.0.241/24",
                "IPv6Address": ""
            },
            "39cfe435313e88b424526fc8ec92131d404efa243bf270fe1da4c4e54144749c": {
                "Name": "management_portainer.1.0d7m38vo2n8p4wywo57kevjd3",
                "EndpointID": "f8794af8c9f3c5869c3dacdff9bc35fd11c3e1b63762df4530d698f0e498900b",
                "MacAddress": "02:42:0a:00:00:f6",
                "IPv4Address": "10.0.0.246/24",
                "IPv6Address": ""
            },
            "6afda6a332a48fe6f6cb4f9eb331629cf85f3bb84d8ed2fd99164ef4b86d31d5": {
                "Name": "management_manager.1.qo2k2m2qcs89szddycut2q46j",
                "EndpointID": "087878e8267e8b886fd87503972dff9cadaf72e63fcf165c313763957666f8b3",
                "MacAddress": "02:42:0a:00:00:ed",
                "IPv4Address": "10.0.0.237/24",
                "IPv6Address": ""
            },
            "f75216e6df56af7c15dcb09863d2c4f330017a933a6be63bb13c777bf5795f26": {
                "Name": "management_traefik.u27he9xn9v9qqjdrh1vvi5wr6.qsro6e1lbfxwqgejfkzlvoboo",
                "EndpointID": "c0b141fd31a8fba3073c427fb3b7ad9fa4a884483f303888755659a5a1152f39",
                "MacAddress": "02:42:0a:00:00:f7",
                "IPv4Address": "10.0.0.247/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "a4c5fde4205f",
                "IP": "10.10.11.66"
            },
            {
                "Name": "98f46de40d03",
                "IP": "10.10.11.113"
            }
        ]
    }
]
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

Here are the logs:
[logs.txt](https://github.com/containous/traefik/files/2201642/logs.txt)
