### ISSUE TITLE
gRPC application with h2c backend for Kubernetes ingress is not working

### ISSUE THREAD

**Issue by alexleigh** [containous/traefik#3640]
I have Traefik 1.7.0-rc1 deployed as a Kubernetes ingress controller and am following https://docs.traefik.io/v1.7/user-guide/grpc/ to get a h2c backend to work for gRPC. However, I am unable to force the backend to use h2c instead of http. The guide mentions the use of a traefik.protocol=h2c label. So I first tried to use that as a annotation:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.protocol: h2c
  name: myapp
spec:
  rules:
  - host: myapp.mydomain
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: grpc
        path: /
```

Which did not work. In the Traefik dashboard I can see that the backend is still using http. Then I tried to use it as a label:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    traefik.protocol: h2c
  name: myapp
spec:
  rules:
  - host: myapp.mydomain
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: grpc
        path: /
```

Which also did not work. Is this a bug with trying to use h2c backends with Kubernetes? Or is there some other way of specifying the backend protocol that I'm missing?
