### ISSUE TITLE
Wrong domain format in DuckDNS TXT update for ACME DNS-01 challenge

### ISSUE THREAD

**Issue by mvdwetering** [containous/traefik#3656]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to configure LetsEncrypt with DuckDNS on traefik.
After configuring in traefik I see an error in the logs for the TXT DNS update on DuckDNS. 
It turns out the format of the request to DuckDNS is wrong.

The request done to DuckDNS (from the logfiles, but with possibly  sensitive parts replaced)
```
time="2018-07-21T14:00:52Z" level=error msg="Unable to obtain ACME certificate for domains \"mysubdomain.duckdns.com\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[mysubdomain.duckdns.com] Error presenting token: Request to change TXT record for duckdns returned the following result (KO) this does not match expectation (OK) used url [https://www.duckdns.org/update?domains=mysubdomain.duckdns.com&token=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee&txt=random_text]\n"
```

The problematic part is `domains=mysubdomain.duckdns.com` part of the request.  This should be just the subdomain. The spec onduckdns.org seems to imply that both formats should work, but only subdomain works. 

If I manually do the request with just the subdomain I get OK back (instead of KO with the previously mentioned format). So "https://www.duckdns.org/update?domains=mysubdomain&token=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee&txt=random_text" works.

I tried to find the code for the DuckDNS ACME configuration, but I could not find it. If someone could point me there maybe I could provide a PR  (even though Go is a new language for me).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# API and dashboard configuration
################################################################
[api]

################################################################
# Docker configuration backend
################################################################
[docker]
domain = "local"
watch = true

[file]
  watch = true
  filename = "/etc/traefik/traefik.toml"

# Expose containers by default in Traefik.
# If set to false, containers that don't have `traefik.enable=true` will be ignored.
#
# Optional
# Default: true
#
#exposedByDefault = false

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


# Enable ACME (Let's Encrypt): automatic SSL.
[acme]

# Email address used for registration.
#
# Required
#
email = "my.email@example.com"

# File or key used for certificates storage.
#
# Required
#
storage = "acme.json"
# or `storage = "traefik/acme/account"` if using KV store.

# Entrypoint to proxy acme apply certificates to.
#
# Required
#
entryPoint = "https"

# If true, display debug log messages from the acme client library.
#
# Optional
# Default: false
#
acmeLogging = true

# Enable certificate generation on frontends host rules.
#
# Optional
# Default: false
#
# onHostRule = true

# CA server to use.
# Uncomment the line to use Let's Encrypt's staging server,
# leave commented to go to prod.
#
# Optional
# Default: "https://acme-v02.api.letsencrypt.org/directory"
#
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

# Domains list.
# Only domains defined here can generate wildcard certificates.
#
# [[acme.domains]]
#   main = "local1.com"
#   sans = ["test1.local1.com", "test2.local1.com"]
# [[acme.domains]]
#   main = "local2.com"
# [[acme.domains]]
#   main = "*.local3.com"
#   sans = ["local3.com", "test1.test1.local3.com"]
[[acme.domains]]
#   main = "*.mysubdomain.duckdns.com"
   main = "mysubdomain.duckdns.com"

# Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
# Note: mandatory for wildcard certificate generation.
#
# Optional
#
[acme.dnsChallenge]

  # DNS provider used.
  #
  # Required
  #
  provider = "duckdns"

  # By default, the provider will verify the TXT DNS challenge record before letting ACME verify.
  # If delayBeforeCheck is greater than zero, this check is delayed for the configured duration in seconds.
  # Useful if internal networks block external DNS queries.
  #
  # Optional
  # Default: 0
  #
  # delayBeforeCheck = 0
 ```
