### ISSUE TITLE
Unable to change default cert

### ISSUE THREAD

**Issue by stanleyyuenyiu** [containous/traefik#3658]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

deploy traefik in kubernetes 1.6 on AWS

1. open a new namespace 
2. import godaddy cert to secret at new namespace, where the cert is already exist from other namespace
3. define a traefik with clusterRole
```yml
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: traefik-ingress-clusterrole
  rules:
    - apiGroups:
        - ""
      resources:
        - configmaps
        - endpoints
        - nodes
        - pods
        - secrets
      verbs:
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - get
    - apiGroups:
        - ""
      resources:
        - services
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - "extensions"
      resources:
        - ingresses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
    - apiGroups:
        - "extensions"
      resources:
        - ingresses/status
      verbs:
        - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-clusterrole
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-serviceaccount
    namespace: traefik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-serviceaccount
  namespace: traefik
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-serviceaccount
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          secretName: lkkhpgdi-ssl-cert-secret
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: traefik
        name: traefik-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - --api
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=INFO
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service-internal
  namespace: traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      name: admin
      targetPort: 8080
  type: ClusterIP
```

4. define entry point config and store in configmap
5. define ssl crt and key at entryPoints.http.tls.certificates as below
         certFile = "/ssl/tls.crt"
          keyFile = "/ssl/tls.key"
6. mount the entry point config
6. mount the ssl/ to the cert stored at kube secret 
7. deploy the traefik to new namespace instead of global
8. deploy my application with ssl defined in ingress file to the namespace
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: traefik
  name: mydomain
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: aaa.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mydomain-service
          servicePort: svc-port
  tls:
  - hosts:
    - aaa.mydomain.com
    secretName: mydomain-ssl-cert-secret
```
9. point aaa.domain.com to my application

### What did you expect to see?
when i run below command 

echo "quit" | openssl s_client -tls1 -connect 'aaa.mydomain.com:443' 2>/dev/null | grep 'subject'

i should see

subject=/CN=*.mydomain.com

### What did you see instead?

subject=/CN=TRAEFIK DEFAULT CERT

### Output of `traefik version`: (_What version of Traefik are you using?_)
latest master image pull at 23/7/2018

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: traefik
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    logLevel = "INFO"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]
          [[entryPoints.http.tls.certificates]]
          certFile = "/ssl/tls.crt"
          keyFile = "/ssl/tls.key"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-07-23T04:25:32Z" level=warning msg="Into EntryPoint http, try to add certificate for domains which already have this certificate (*.mydomain.com,mydomain.com). The new certificate will not be append to the EntryPoint."
```
