### ISSUE TITLE
Multiples Frontends & Backends for one docker service

### ISSUE THREAD

**Issue by alemairebe** [containous/traefik#3661]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

I run docker swarm cluster.
I saw expecting to see 1 frontend and 1 backend with multiples docker containers included in that backend.

### What did you see instead?

On my latest traefik config (with using `traefik.backend: "my-service"` and `swarmMode = false`);
I have 2 frontends for 1 backend and my 2 docker containers are in that single backend.

When I enable swarmMode , result is worse as nothing show up; logs shows : `level=debug msg="Filtering disabled container dns_dns.1"` but that container doesn't exist, full container id is : `dns_dns.1.ekwzo1qts6r5dutab8m1ykjal` and service name is dns_dns

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]
[traefikLog]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
    ]
[api]
dashboard = true
[acme]
email = "removed for spam reason"
storage = "/acme/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
[docker]
watch = true
domain = "removed.local"
exposedbydefault = false
```
docker:  
Server Version: 18.06.0-ce

compose file used by `docker service up -c config.yml shared` : 

```yml
version: "3.6"

services:
  loadbalancer:
    image: traefik:1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: traefik_data
        target: /acme
        volume:
          nocopy: true
    configs:
      - source: traefik
        target: /etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "81:8080"
    networks:
      - webgateway
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  tools:
    image: nginx
    configs:
      - source: tools_index
        target: /usr/share/nginx/html/index.html
      - source: tools_style
        target: /usr/share/nginx/html/style.css
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:tools.example.org"
      traefik.backend: "tools"
    networks:
      - webgateway
    deploy:
      replicas: 2

.....
config & volumes details
```
