### ISSUE TITLE
Access logs won't print in stdout

### ISSUE THREAD

**Issue by lomkju** [containous/traefik#3672]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Try to get access logs in stdout

### What did you expect to see?

Access logs to get pushed to stdout

### What did you see instead?

Access logs don't get pushed to stdout

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.6-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[accessLog]
[traefikLog]

[api]
  dashboard = true
  debug = true
[entryPoints]
  [entryPoints.http]
  address = ":80"
   [entryPoints.http.redirect]
   entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik-certificates/tls.crt"
      keyFile = "/etc/traefik-certificates/tls.key"
      
[kubernetes]
ingressClass = "traefik-internal"

```

```
Running on minikube
```
