### ISSUE TITLE
Traefik backends not registered and not showing in UI dashboard on Azure service fabric cluster

### ISSUE THREAD

**Issue by ran80** [containous/traefik#3684]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Deploy a service (Asp.net web api) to Service Fabric cluster. Traefik does not show the backend on UI dashboard and deployed service cant be accessed from traefik port 8080. 

<StatelessServiceType ServiceTypeName="AspNetCoreContainerServiceType" UseImplicitHost="true">
      <Extensions>
        <Extension Name="Traefik">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="traefik.frontend.rule">PathPrefix: /api/values</Label>
            <Label Key="traefik.enable">true</Label>
            <Label Key="traefik.frontend.passHostHeader">true</Label>            
          </Labels>
        </Extension>
      </Extensions>
    </StatelessServiceType>

Deploy service to Azure service fabric cluster.

### What did you expect to see?
Traefik should register the service and should be able to show in dashboard. Should be able to access the deployed api. 

### What did you see instead?
Traefik showing the front-end configuration on left, but on the right-end  it does not show any backend details. Server,URL, Weight al are blank. It shows Load Balancer : wrr

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.6.0-rc6

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Service Fabric v6.1.480.9494
Platform: Windows Server 2016 Datacenter
```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
#traefikLogsFile = "log/traefik.log"

[traefikLog]
  filePath = "traefik.log"
  format   = "json"

# Log level
#
# Optional
# Default: "ERROR"

logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.traefik]
address = ":8080"

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
[accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
 filePath = "accesslog.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
format = "json"

################################################################
# API definition
################################################################

[api]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

  # Enable debug mode.
  # This will install HTTP handlers to expose Go expvars under /debug/vars and
  # pprof profiling data under /debug/pprof.
  # Additionally, the log level will be set to DEBUG.
  #
  # Optional
  # Default: false
  #
  debug = true

################################################################
# Service Fabric provider
################################################################

# Enable Service Fabric configuration backend
[servicefabric]

# Service Fabric Management Endpoint
clustermanagementurl = "https://localhost:19080"
# Note: use "https://localhost:19080" if you're using a secure cluster

# Service Fabric Management Endpoint API Version
apiversion = "3.0"

# Enable TLS connection.
#
# Optional
#
[serviceFabric.tls]
cert = "certs/servicefabric.crt"
key = "certs/servicefabric.key"
insecureskipverify = true


```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
\"certs/servicefabric.crt\",\"Key\":\"certs/servicefabric.key\",\"InsecureSkipVerify\":true}}","time":"2018-07-27T07:10:50Z"}
{"level":"info","msg":"Checking service fabric config","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Validation of load balancer method for backend fabric:/AspNetCoreContainerApp/AspNetCoreContainerService failed: invalid load-balancing method ''. Using default method wrr.","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Configuration received from provider servicefabric: {\"backends\":{\"fabric:/AspNetCoreContainerApp/AspNetCoreContainerService\":{\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-fabric:/AspNetCoreContainerApp/AspNetCoreContainerService\":{\"entryPoints\":[\"http\"],\"backend\":\"fabric:/AspNetCoreContainerApp/AspNetCoreContainerService\",\"routes\":{\"traefik.frontend.rule\":{\"rule\":\"PathPrefix: /api/values\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Creating frontend frontend-fabric:/AspNetCoreContainerApp/AspNetCoreContainerService","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Wiring frontend frontend-fabric:/AspNetCoreContainerApp/AspNetCoreContainerService to entryPoint http","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Creating route traefik.frontend.rule PathPrefix: /api/values","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Creating backend fabric:/AspNetCoreContainerApp/AspNetCoreContainerService","time":"2018-07-27T07:11:00Z"}
{"level":"debug","msg":"Creating load-balancer wrr","time":"2018-07-27T07:11:00Z"}
{"level":"info","msg":"Server configuration reloaded on :80","time":"2018-07-27T07:11:00Z"}
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2018-07-27T07:11:00Z"}
{"level":"info","msg":"Checking service fabric config","time":"2018-07-27T07:11:10Z"}
{"level":"debug","msg":"Validation of load balancer method for backend fabric:/AspNetCoreContainerApp/AspNetCoreContainerService failed: invalid load-balancing method ''. Using default method wrr.","time":"2018-07-27T07:11:10Z"}
{"level":"debug","msg":"Configuration received from provider servicefabric: {\"backends\":{\"fabric:/AspNetCoreContainerApp/AspNetCoreContainerService\":{\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-fabric:/AspNetCoreContainerApp/AspNetCoreContainerService\":{\"entryPoints\":[\"http\"],\"backend\":\"fabric:/AspNetCoreContainerApp/AspNetCoreContainerService\",\"routes\":{\"traefik.frontend.rule\":{\"rule\":\"PathPrefix: /api/values\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}","time":"2018-07-27T07:11:10Z"}
{"level":"info","msg":"Skipping same configuration for provider servicefabric","time":"2018-07-27T07:11:10Z"}
{"level":"info","msg":"Checking service fabric config","time":"2018-07-27T07:11:20Z"}
{"level":"debug","msg":"Validation of load balancer method for backend fabric:/AspNetCoreContainerApp/AspNetCoreContainerService failed: invalid load-balancing method ''. Using default method wrr.","time":"2018-07-27T07:11:20Z"}


```
