### ISSUE TITLE
entryPoints.http.redirect always results in a loop

### ISSUE THREAD

**Issue by JoooostB** [containous/traefik#3693]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I've set entryPoints.http.redirect to redirect all requests to HTTPS.

### What did you expect to see?
Automatic redirection from HTTP to HTTPS for my entrypoints defined in rules.toml

### What did you see instead?
ERR_TOO_MANY_REDIRECTS
![image](https://user-images.githubusercontent.com/8641236/43368239-8a7ad8d6-935a-11e8-8fbb-9341a878390a.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
**traefik.toml:**
```toml
# Global configuration
logLevel = "DEBUG"
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]

# Entrypoints configuration
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Let's Encrypt support
[acme]
email = "me@example.nl"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.example.nl"

# Rules configs
[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Traefik logs configuration
filePath = "log/traefik.log"

# Enable API and dashboard
[api]
dashboard = true

# Docker configuration backend
# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain="example.nl"
watch=true
exposedByDefault = false
```

**rules.toml**
```toml
[backends]
  [backends.backend-example]
    [backends.backend-example.servers.server1]
    url = "http://192.168.1.224:80"

[frontends]
  [frontends.example]
  backend = "backend-example"
    [frontends.example.routes.hostname]
    rule = "Host:example.dog"
```
