### ISSUE TITLE
accessLog.fields.headers.names does not seem to work

### ISSUE THREAD

**Issue by dazoot** [containous/traefik#3697]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to configure accessLog format by using the online documentation. traefik daemon does not want to start.

### What did you expect to see?

Updated accessLog formatting.

### What did you see instead?

2018/07/30 23:26:46 Error reading TOML config file /etc/traefik/traefik.toml : toml: cannot load TOML value of type []interface {} into a Go string

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc2
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-07-17_12:40:52PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[accessLog.filters]
    statusCodes = ["200", "300-302"]
    retryAttempts = true
    minDuration = "10ms"

  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.names]
      "ClientUsername" = "drop"

    [accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "User-Agent" = "redact"
        "Authorization" = "drop"
        "Content-Type" = "keep"
```

**Comment by mmatur** [comment]
Hi @dazoot ,

Thanks for your interest in Træfik.

After some investigation I am not able to reproduce your issue.

Could you please send us you full `traefik.toml` file

**Comment by dazoot** [comment]
```toml
logLevel = "DEBUG"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"

[accessLog.filters]
    statusCodes = ["200", "300-302"]
    retryAttempts = true
    minDuration = "10ms"

  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.names]
      "ClientUsername" = "drop"

    [accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "User-Agent" = "redact"
        "Authorization" = "drop"
        "Content-Type" = "keep"

defaultEntryPoints = [ "http", "https" ]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

    [entryPoints.traefik]
    address = ":9955"

[acme]
email = "me@example.com"
storage = "/etc/traefik/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
onHostRule = true

    [acme.httpChallenge]
    entryPoint = "http"

[api]
    entryPoint = "traefik"
    dashboard = true

[file]
    directory = "/etc/traefik/sites/"
    watch = true
```

And in sites/ folder i have defined some backends and frontends.
I can't start traefik unless i remove the `accessLog.fields` parts.
