### ISSUE TITLE
Rewrite rule annotation does not work as expected on Kubernetes provider

### ISSUE THREAD

**Issue by timurkhafizov** [containous/traefik#3698]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We discussed this issue with @dtomcej in Slack, and he asked if I could create an issue. So here I am.

I run Traefik on K8S. Recently I decided to try `rewrite-rule` and `request-modifier` annotations for Ingress. I defined very simple Ingress as follows
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # Extend with used-defined annotations
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rewrite-target: /api/v1/products
  name: "my-rewrite-ingress"
spec:
  rules:
  - host: api.my-domain.com
    http:
      paths:
      - path: /v1/my-subpath/products
        backend:
          serviceName: products
          servicePort: http
```
After creating this Ingress I can see frontend pointing to the backend.
I make a request to `api.my-domain.com/v1/my-subpath/products`.

### What did you expect to see?
1. Response from backend - HTTP 200 Success
2. Traefik to send all requests with URL starting with `/v1/my-subpath/products` to my backend and rewrite path:
    - `v1/my-subpath/products` -> `/api/v1/products`
    - `v1/my-subpath/products/` -> `/api/v1/products/`
    - `v1/my-subpath/products/100` -> `/api/v1/products/100`

### What did you see instead?
1. In case of request to `api.my-domain.com/v1/my-subpath/products`: 
    - HTTP 404 Not Found
    - The request is being routed to `/v1/my-subpath/products`
2. In case of request to `api.my-domain.com/v1/my-subpath/products/`: 
    - HTTP 200 Success
    - The request is being routed to `/api/v1/products/`
3. Route rule (as written on dashboard) - `ReplacePathRegex ^/v1/my-subpath/products/(.*) /api/v1/products/$1`

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
1.7.0-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
  [kubernetes.ingressEndpoint]
    publishedservice = "kube-system/traefik-internal"
[web]
address = ":8080"
  [web.statistics]
    RecentErrors = 15
```

I am using K8S 1.9.8.
