### ISSUE TITLE
log RequestHost in accesslog common format

### ISSUE THREAD

**Issue by dazoot** [containous/traefik#3704]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I want to log in RequestHost in access log format = common.

```toml
[accessLog]
  filePath = "/var/log/traefik/access.log"
  format = "common"

[accessLog.fields]
  defaultMode = "keep"

[accessLog.fields.names]
  "RequestHost" = "keep"
```

`RequestHost` pops up in the log only if accesslog `format = "json"`.

**Comment by totti4ever** [comment]
Any news on this or any other chance to get an idea, what people try to access (i.e. which host they addressed) when they reach traefik but none of the routers?!
This must be of more peoples interest, I'd reckon

**Comment by doc75** [comment]
This is really important if you want to use tools like Awstats and have several domain served by Traefik.

Another solution would be to allow custom log format by having a configuration option like:
```ini
[accessLog]
  format = "common"
  formatFields = "RequestHost ClientHost - ClientUsername [timestamp] \"RequestMethod RequestPath RequestProtocol\" OriginStatus OriginContentSize..."
```

This would allow anyone to choose the fields included in the Logs.

**Comment by codecat** [comment]
I have a number of log entries that don't show a hostname, but are very likely to be providing a hostname, I just don't know which.

In other words, I'm practically blind without the ability to see the hostname in my access logs!

**Comment by bigwheels16** [comment]
I would also be interested in this.  I had to change to json format in order to see the RequestHost, which is a workaround for this issue, but having it included in the common format would be better.

**Comment by yongzhang** [comment]
It's very very important to have this in the log, also expecting this feature.

**Comment by m-kus** [comment]
Any updates on this?

**Comment by somnium78** [comment]
a custom log format would be very nice!

**Comment by sethlinnkuleuven** [comment]
I would really like to see this!

**Comment by d03j** [comment]
+1 without if I can't tell which of my subdomains are being probed. Having RequestHost on the log would allow me to fine tune my crowdsec scenarios.

**Comment by vtmocanu** [comment]
Anyone found any workarounds for this?

**Comment by sethlinnkuleuven** [comment]
> Anyone found any workarounds for this?

My workaround is not direct, but it works.

I made an alias in `.bashrc` that reads the Traefik access log (in JSON format) and outputs each line in 'common' format.

```yaml
# traefik.yml
accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100
  format: json
  fields:   # These settings should keep all headers
    defaultMode: keep
    headers:
      defaultMode: keep
```

```bash
# .bashrc (replace the path with your own)
alias traefiklog='cat /path/to/traefik/access.log | jq -r --arg hyphen "-" "\"\(.time) \u001b[32m\\\"\(.RequestMethod) \(.RequestPath) \(.RequestHost)\\\"\u001b[0m \u001b[31m\(.DownstreamStatus)\u001b[0m \(."request_User-Agent") \(."request_X-Lb-Forwarded-For") \u001b[36m\(.entryPointName)\u001b[0m \u001b[36m\(.RouterName)\u001b[0m \u001b[36m\(.ServiceName)\u001b[0m\""'
```

just type this and you get colorized 'common' style output
```bash
traefiklog | grep my.site.com | grep /my/path
```

**Comment by rossnick** [comment]
Here's my traefik.yml :

#traefik.yml
```yml
accessLog:
  filePath: /var/log/traefik/access_log
  format: json
  filters:
    minDuration: "500us"
  fields:
    names:
      ClientUsername: keep
      StartUTC: keep
      RequestHost: keep
    headers:
      defaultMode: keep
      names:
          RequestHost: keep
          User-Agent: keep
          Authorization: keep
          Content-Type: keep
```

The min duration is only to filter out the ping requests.

And my typical tail command :

```bash
#bash
tail -f /var/log/traefik/access_log | jq -j '(.ClientHost | split(",")[0] | . + (15 - length | if . > 0 then " " * . else "" end))[0:15], " ",  (.RequestHost | . + (20 - length | if . > 0 then " " * . else "" end))[0:20], " [", (.StartLocal | sub("T"; " ") | sub("\\.[0-9]+"; "") | sub("Z"; "")) ,"]", " \"", .RequestMethod, " ", .RequestPath, " ", .RequestProtocol, "\" ", .OriginStatus, " ", .OriginContentSize, " \"", .request_Referer // "-","\"", " \"", ."request_User-Agent" // "-","\"", "\n"'
```
