### ISSUE TITLE
PathPrefixStrip can be defined by ingress annotation

### ISSUE THREAD

**Issue by AlmogBaku** [containous/traefik#372]
Since https://github.com/containous/traefik/pull/355#issuecomment-219272995 broke deployments without anyway to regain the same behavior(without toml file), I suggest to allow configuration of this feature by using annotations:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api--my-svc
  annotations:
    PathPrefixStrip: "true"
spec:
  rules:
    - host: api.example.net
      http:
        paths:
          - path: /v1/mySvc
            backend:
              serviceName: mySvc
              servicePort: 80
```
