### ISSUE TITLE
Documentation wrongly reports Gandiv5 provider as working for wildcard

### ISSUE THREAD

**Issue by tchabaud** [containous/traefik#3748]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

According to the doc, trying to generate a wildcard certificate using gandiv5 as provider

### What did you expect to see?

A successful wildcard cert generation

### What did you see instead?

The following error message :

```sh
time="2018-08-08T17:46:15Z" level=error msg="Unable to obtain ACME certificate for domains \"*.mydomain.com\" : unable to generate a certificate for the domains [*.mydomain.com]: acme: Error -> One or more domains had a problem:\n[mydomain.com] error presenting token: Gandi DNS: findZoneByFqdn failure: Could not find the start of authority\n"    
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
defaultEntryPoints = ["http","https"]

[traefiklog]
filePath = "/logs/traefik.log"
logLevel = "WARN"

[accessLog]
filePath = "/logs/traefik_access.log"
logLevel = "WARN"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[api]
debug=false

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.com"
watch = true
exposedByDefault = false

[acme]
email = "me@mydomain.com"
storage = "/acme.json"
entryPoint = "https"
acmeLogging = true
# caServer = "https://acme-v02.api.letsencrypt.org/directory"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.dnsChallenge]
  provider = "gandiv5"
  delayBeforeCheck = 90

[[acme.domains]]
  main = "*.mydomain.com"
```

I think you should [update the doc](https://docs.traefik.io/v1.6/configuration/acme/#dns-provider-support), and flag gandi v5 as not working for wildcard, because of https://github.com/xenolf/lego/issues/472
