### ISSUE TITLE
be able to specify a "unmatched" container for unmatched URLs

### ISSUE THREAD

**Issue by kenyee** [containous/traefik#3763]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik version: v1.7.0-rc3

```
version: "3"
  
services:
  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost;whoami1.docker.localhost;PathPrefix:/{path:(?i)servlet},/{path:(?i)some.php"

  whoami2:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
```

I realize Traefik is originally for handling REST APIs, but support for a fallback container would be useful.  E.g., in the above, I'm trying to do "if any of the pathprefixes match, use whoami1, but if it doesn't, use whoami2".  From what I understand after lots of digging and experimenting, you can't do this.  The use case is: a set of machines needs to handle some servlets (using paths that can include query strings) and some PHP pages etc. but once the URL prefix matches or any subdirectories under it, it should stay on that machine.  There are another set of machines that just handle static files (the "default" container, aka whoami2).

Maybe something like this added on whoami2 to indicate that it will handle anything not matching on the other containers to indicate it should be used to match last:
  traefik.frontend.rule.matchlast=true
I also tried using the traefik.frontend.priority and setting it to different numbers, but that didn't seem to work right either.  Some of the URLs that should have matched whoami1, ended up going to whoami2 for some reason.

Possibly related to #3026 and #1663.  The path matching should not be an AND of rules and it shouldn't be dependent on length.  I know it'll slow things down, but the way it works now is counterintuitive once you start using it to route normal websites you're trying to break up into separate docker instances...works great for REST APIs though :-)
