### ISSUE TITLE
traefik don't know label when the service is on a other stack-compose and on other serveur (worker)

### ISSUE THREAD

**Issue by pguichon** [containous/traefik#3765]
Hi, 
Sorry for my bad english.

I try to use portainer + traefik.
First try : 
In the same manage i create a Portainer stack + a Traefik stack + a Whoami stack.
I add a worker, and the stack of Whoami is at the worker (cluster1)
And traefik don't detect the whoami.

First, in the manager I create a network overlay
```bash
docker network create --driver=overlay --subnet=172.16.14.0/24 proxy_net
```

I create a portainer-agent-stack.yml

```yml
version: '3.6'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
```
and i deploy it 

```bash
docker stack deploy --compose-file=portainer-agent-stack.yml portainer
```
after I create the traefik stack

```yml
version: '3.6'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/traefik/traefik.toml:/etc/traefik/traefik.toml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy_net
```

and the whoami stack

```yml
version: '3.6'

services:
  whoami:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Host:whoami.infra.home"
      - "traefik.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy_net
```

the config of traefik
```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"
[api]
[ping]
[docker]
watch = true
swarmMode = true
exposedByDefault=true

endpoint = "unix:///var/run/docker.sock"

domain = "infra.home"
```

* Question : 
I do something wrong ?
It's a bug of portainer ?
It's a bug of traefik ?
It's not the right place to ask ?

Thanks for your reply
