### ISSUE TITLE
Traefik does not work with own certificates

### ISSUE THREAD

**Issue by Loader23** [containous/traefik#3769]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Trying to start traefik with my own Certificates

### What did you expect to see?

a running traefik

### What did you see instead?

me loosing hair and this error:
```
time="2018-08-16T15:47:38Z" level=error msg="Unable to add a certificate to the entryPoint \"https\" : unable to generate TLS certifica
te : tls: failed to find any PEM data in key input"                                                                                    
time="2018-08-16T15:47:38Z" level=error msg="Error creating TLS config: No certificates found for TLS entrypoint https"                
time="2018-08-16T15:47:38Z" level=fatal msg="Error preparing server: No certificates found for TLS entrypoint https"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:alpine, can't say what version exactly, it does not start :-)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["http", "https"]

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/cert.pem"
      keyFile = "/etc/traefik/certs/privkey.key"

# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "xxx"
watch = true
exposedbydefault = false
```

Compose File:

```
version: '3.3'

services:
  Traefik:
    hostname: traefik
    image: traefik:alpine
    command: --api --docker
    domainname: xxx
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:xxx;PathPrefixStrip: /traefik"
      - "traefik.frontend.rule=Host:NAS;PathPrefixStrip: /traefik"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /share/CACHEDEV1_DATA/.qpkg/Traefik/traefik.toml:/etc/traefik/traefik.toml
      - /share/CACHEDEV1_DATA/.qpkg/Traefik/certs:/etc/traefik/certs
```

I tried several things but nothing helps.
