### ISSUE TITLE
Backend stickiness not working

### ISSUE THREAD

**Issue by LukeMauldin** [containous/traefik#3770]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Using traefik 1.7.0 rc3, and the load balancer stickiness setting, it is not applying the stickiness when proxying two IIS web servers that are using Windows Authentication. The windows authentication piece sends two 401 requests to the backend server to establish the "session" but traefik is sending the two requests to the two different backend servers. I have verified in the logs that it says "Sticky session with cookie " and so I think the configuration is being read correctly by traefik. Could traefik not be inserting the cookie on 401 requests?

### What did you expect to see?
Expected to see the multiple requests from the same client directed to the same backend server

### What did you see instead?
Multiple requests from the same client went to different backend servers

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
  [backends.XXX]
    [backends.XXX.loadbalancer]
      method = "wrr"
    [backends.XXX.loadbalancer.stickiness]
      cookieName = "__trae_proxy"
    [backends.XXX.healthcheck]
      path = "/"
      interval = "5s"
    [backends.XXX.servers.test01]
      url = "http://test01:80"
    [backends.XXX.servers.test0]
      url = "http://test02:80"
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-08-16T13:04:49-05:00" level=debug msg="Creating backend test"
time="2018-08-16T13:04:49-05:00" level=debug msg="Creating load-balancer drr"
time="2018-08-16T13:04:49-05:00" level=debug msg="Sticky session with cookie __trae_proxy"
time="2018-08-16T13:04:49-05:00" level=debug msg="Creating server test02 at http://test02:80 with weight 0"
time="2018-08-16T13:04:49-05:00" level=debug msg="Creating server test01 at http://test01:80 with weight 0"
```

**Comment by LukeMauldin** [comment]
I have also been able to duplicate this when using session stickiness in front of two nginx web servers serving static http content.

**Comment by LukeMauldin** [comment]
Confirmed that this is a regression. Sticky sessions work as expected in 1.6.5.

**Comment by dduportal** [comment]
@LukeMauldin , not able to reproduce, here is my reproduction case (on Docker 18.06, with Traefik 1.7.0-rc3): https://gist.github.com/dduportal/6248b31fb32d98997d85c65975decd8e . 
I see the curl operation sticked to the server specified in the cookies.txt file.
=> Same behavior with Chrome and Firefox.


It looks like a configuration issue, or something in your web browser / network which is removing the Cookie or some HTTP headers. Could you provide us more HTTP client-side information to see what is happening ?

You can also (and should consider) asking for help in our community Slack channel at https://slack.traefik.io/ .

**Comment by dduportal** [comment]
Also, can you please check #3792 ? It might be related to this (IIS server as backend, with some special behaviours)

**Comment by YoranSys** [comment]
Have you try with  `method = "drr"` ?

**Comment by LukeMauldin** [comment]
Yes, I tried with both methods.

**Comment by meishd** [comment]
I run into the same case.
In my case, stickness in v1.7 can not work, but in v1.6.5 or v1.6.6, it works fine.

My case:
[frontends]
    [frontends.frontend1]
    backend = "backend1"
        [frontends.frontend1.routes.test_1]
        rule = "Host:mydomain.com"
[backends]
    [backends.backend1]
        [backends.backend1.loadBalancer]
        method = "drr"
        [backends.backend1.loadBalancer.stickiness]
        cookieName = "lbcookie"
        [backends.backend1.servers.server1]
        url = "http://10.46.200.93:9114"
        [backends.backend1.servers.server2]
        url = "http://10.46.211.34:9114"

when the backends are nginx, curl -b cookie.txt can generate the file, but it doesn't contain the pod ip.
Just like this:
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.
mydoamin.com     FALSE   /       FALSE   0       CookieName      CookieValue

when the backend are tomcat, curl -b cookie.txt cat not generate the file at all.

**Comment by sreitscope** [comment]
I have the same problem. Backend stickyness as described in the documentation does not work with 1.7, while it works with 1.6 with the same configuration.

**Comment by fkgre** [comment]
I have the same problem.

**Comment by seeruk** [comment]
I'm also having this problem, but I will add that if I use the supposed _deprecated_ method of enabling stickiness then it does work. I'm using Traefik 1.7.4. It's a shame that the deprecated method doesn't actually support changing the cookie name.

As an aside, 'm using Consul for configuration, and it's pretty awkward to translate configuration that looks like this...

```toml
[backends]
  [backends.backend1]
    [backends.backend1.loadbalancer.stickiness]
```

...into Consul's key/value store, because you have to make a random key under that "folder" for it to think something is there (i.e. I normally make a key called `noop` with no value just to make Consul respond to say that the folder exists for Traefik's sake...)

**Comment by siyu6974** [comment]
Adding more info to the thread, the issue persists on v1.7.4

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10
```

Config toml

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "tcp://127.0.0.1:2376"
domain = "my.domain"
watch = true
exposedByDefault = false
swarmMode = true

[acme]
email = "email@test.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
```

compose file

```
version: '3'
services:
  whoami:
    image: jwilder/whoami
    networks:
      traefik-net:
        aliases:
        - whoami-${SUBDOMAIN}
    deploy:
      labels:
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:whoami.${SUBDOMAIN}.${DOMAIN}"
      - "traefik.backend=whoami-${SUBDOMAIN}"
#      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.stickiness=true"
#      - "traefik.backend.loadbalancer.stickiness.cookieName=lb_test"
      - "traefik.port=8000"
      - "traefik.protocol=http"
      - "traefik.enable=true"
networks:
  traefik-net:
    external: true
```

(It does not work regardless those commented lines are uncommented or not)

**Observation**

I deployed the compose file, with 1 `whoami` container, I can see the cookie in my browser.

Clean the cookie, docker service scale to 2, no cookie.
