### ISSUE TITLE
Unexpected HTTP redirect when routing /callback url

### ISSUE THREAD

**Issue by mindcrash** [containous/traefik#3775]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Currently testing Traefik using the File provider for a web app which will use federated authentication and thus needs a callback url for said authentication.

### What did you expect to see?

When navigating to **/callback** a standard HTTP GET request to **/callback** is executed

### What did you see instead?

When navigating to **/callback** a HTTP redirect is executed, using the internal backend address as its location.

Note that I also exposed the backend server publically to test where this behavior occurs, and when navigating to **/callback** through this route everything seems to work as required.

### Output of `traefik version`:

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Tools used:  

Docker with two containers running Nginx and Traefik

Configuration used:

```toml
debug = true
insecureSkipVerify = true

[entryPoints]
 [entryPoints.https]
 address = ":443"
  [entryPoints.https.tls]

[file]

[backends]
 [backends.home]
  [backends.home.servers]
   [backends.home.servers.server0]
   url = "http://192.168.0.2"
   weight = 1

[frontends]
 [frontends.home]
 entryPoints = ["https"]
 backend = "home"
 [frontends.home.routes.app]
 rule = "Path:/,/callback"
```
