### ISSUE TITLE
Traefik won't add auto restarted container to backend

### ISSUE THREAD

**Issue by minhdanh** [containous/traefik#3780]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have Traefik and a Drone server running in Docker (with Docker Compose).
After upgrading Traefik to version 1.7 (image: `traefik:v1.7`), sometimes when the Drone server exits because of a mysterious bug, Drone is restarted automatically by Docker Compose. But Traefik would fail to add Drone to backend again.
At this time we have to restart Treafik manually.

### What did you expect to see?
Traefik would see restarted container and add it to backend correctly.

Traefik logs:
```
time="2018-07-27T11:01:56Z" level=warning msg="Unable to find the IP address for the container \"/drone-server\": the server is ignored."
time="2018-07-27T11:01:56Z" level=error msg="undefined backend 'backend-drone-server' for frontend frontend-Host-ci-example-com-0. Skipping frontend frontend-Host-ci-example
```

### What did you see instead?
Traefik failed to get the Drone container's IP, and won't add it to backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.0-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

checkNewVersion = false
InsecureSkipVerify = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]

[api]
  entryPoint = "traefik"
  dashboard = true

[docker]
exposedbydefault = false

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/tls.cert"
      keyFile = "/etc/traefik/tls.key"

[acme]
storage = "/data/acme.json"
email = "email@example.com"
entryPoint = "https"
onHostRule = true
ondemand = false
  [acme.httpChallenge]
  entryPoint = "http"
```

docker-compose.yml:
```yml
version: '3.4'

  drone-server:
    container_name: drone-server
    image: drone/drone:0.8.5
    restart: unless-stopped
    ports:
      - "9000:9000"

﻿  proxy:
    container_name: proxy
    # https://hub.docker.com/r/library/traefik/tags/
    image: traefik:v1.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
```
