### ISSUE TITLE
traefik removes trailing slash, redirect loop with nginx and others behind

### ISSUE THREAD

**Issue by fRzzy** [containous/traefik#3782]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have Traefik setup with consulCatalog as provider, Docker Registry 2 and other Nginx services all registered successfully.

Docker pull/push doesn't work, resulted in "Get /v2/: stopped after 10 redirects" error, tried to go to the same URL with browser resulted in redirect loop between "/v2" and "/v2/"

Go to any other site served by Nginx doesn't work if the URL doesn't end in an existed file. For example "/dir/index.html" works but "/dir" got redirected to "/dir/" by Nginx and again to "/dir" by Treafik.

### What did you expect to see?

Traefik preserve and forward the exact request path.

### What did you see instead?

Traefik remove trailing slash from path.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ['https', 'http']

[entryPoints]
  [entryPoints.https]
  address = ':443'
    [entryPoints.https.tls]
    [entryPoints.https.proxyProtocol]
    trustedIPs = ['haproxy IP']
  [entryPoints.http]
  address = ':80'
    [entryPoints.http.redirect]
    entryPoint = 'https'

[api]
[ping]
[metrics]
  [metrics.prometheus]

[acme]
email = 'me@example.com'
entryPoint = 'https'
onHostRule = true
storage = '/acme/storage'
```

Traefik docker container started with:
```
"--consul --consul.endpoint='consul:8500' --consul.prefix='production/traefik' --consul.watch=true --consulcatalog --consulcatalog.endpoint='consul:8500' --consulcatalog.exposedbydefault=false --consulcatalog.watch=true --api"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

sorry I can't turn on DEBUG log on production server
