### ISSUE TITLE
Some applications isn't working like without traefik

### ISSUE THREAD

**Issue by bitdegree67** [containous/traefik#3785]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Running nextcloud docker image and connect to nextcloud sync client.

### What did you expect to see?
can connect it with nextcloud sync client.
Some apps (like nextcloud sync client) isn't working good with traefik reverse proxy.
Why is traefik reverse proxy not transparent and not the same working with or without it? because if I try my nextcloud image without traefik then it works well. with traefik i get this bug:  https://github.com/nextcloud/desktop/issues/279

### What did you see instead?
This error : https://github.com/nextcloud/desktop/issues/279

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug=true

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]
[api]
[docker]
watch = true

[acme]
email = "HIDEDIT"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
[acme.dnsChallenge]
provider = "cloudflare"

[[acme.domains]]
  main = "HIDEDIT"
  sans = ["HIDEDIT"]
```
