### ISSUE TITLE
Traefik logs users in as someone else when infront of Kerberos and IIS

### ISSUE THREAD

**Issue by evolvedlight** [containous/traefik#3792]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have an IIS server that uses Kerberos authentication for a site. We have traefik infront of the server with relatively default settings. When I go to the site I get given another user's session.

### What did you expect to see?

My own user information

### What did you see instead?

Another user's information

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

main file:
```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"

  [entryPoints.http.proxyProtocol]
  insecure = true

  [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "certs/xxx.pem"
      keyFile = "certs/xxx.key"

  [entryPoints.traefik]
  address = ":9001"

[file]
  directory = "conf"
  watch = true

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
```

file in conf/xxx.toml:
```toml
[backends]
    [backends.xxx]
        # ...
        [backends.xxx.servers.server1]
        url = "http://test-xxx.firm:8000"
        weight = 100


[frontends]

    [frontends.xxx]
    entryPoints = ["http", "https"]
    backend = "xxx"
    passHostHeader = true

    
    [frontends.xxx.routes]
        [frontends.xxx.routes.route0]
        rule = "Host:test-xxx.firm"

    [frontends.xxx.headers]
    SSLRedirect = true
```
I was trying this instead of nginx - nginx doesn't have this behaviour. Is there anything about this config that might lead to mixed sessions?
