### ISSUE TITLE
Error page of kubernetes ingress default route not showing

### ISSUE THREAD

**Issue by geekgonecrazy** [containous/traefik#3810]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
```yml
apiVersion: v1
kind: Service
metadata:
  name: default-route
  namespace: my-namespace
  annotations:
    traefik.backend.circuitbreaker: "NetworkErrorRatio() > 0.5"
spec:
  ports:
  - name: http
    targetPort: 5000
    port: 5000
  selector:
    app: default-route

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-route
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/error-pages: |-
        foo:
          status:
          - "400-600"
          backend: default-route
          query: "/{status}.html"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: default-route
          servicePort: 5000
```
I've also tried setting with priority no luck.

### What did you expect to see?
If I have an ingress route and service  defined.. and I  remove all pods.  I would expect to see my default route error page instead of `service unavailable`

### What did you see instead?
`service unavailable`

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker image: `traefik:v1.6.5`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Running as kubernetes ingress provider

```toml
defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/wildcard.crt"
          KeyFile = "/ssl/wildcard.key"
      [entryPoints.api]
      address = ":8080"
      [entryPoints.ping]
      address = ":8082"

    [kubernetes]

    [api]
    entryPoint = "api"
    dashboard = true

      [api.statistics]

    [metrics]
      [metrics.prometheus]
        entryPoint = "api"

    [ping]
    entryPoint = "ping"
```
