### ISSUE TITLE
Dockerized traefik doesn't honour traefik.enabled / default setting

### ISSUE THREAD

**Issue by ma-ver-ick** [containous/traefik#3819]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Created a docker compose container 
```yml
version: '3.5'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image 1.6.6
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/etc/traefik/traefik.toml
    networks:
      - inside

networks:
  inside:
     name: traefik_network
```

with the default configuration example file from the documentation.
2. Enabled this configuration entry
```toml
exposedByDefault = false
```

3. Created an additional application whoami

```yml
version: '3.5'

services:
  whoami:
    image: emilevauge/whoami
    networks:
       - outside
  whoami2:
    image: emilevauge/whoami

networks:
  outside:
    external:
      name: traefik_network
```

### What did you expect to see?

Both of the required container shouldn't have a route assigned and should show up in the traefik dashboard.

### What did you see instead?

Both whoami containers have routes assigned and are only hidden in the dashboard, if "traefik.enabled=false" is added in the docker-compose file to the whoami containers.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[docker]
exposedByDefault = false
```
