### ISSUE TITLE
Cannot pass host header

### ISSUE THREAD

**Issue by john199604** [containous/traefik#3822]
Hello,

I have a .NET Core API and Angular 5 app which i am using traefik for the requests to go throught.

Here's my traefik.toml
```toml
debug = false
defaultEntryPoints = ["http", "https"]
[entryPoints]
   [entryPoints.http]
   address = ":80"
   [entryPoints.https]
   address = ":443"
     [entryPoints.https.tls]
       [[entryPoints.https.tls.certificates]]
       CertFile = "/etc//ssl/cert.pem"
       KeyFile = "/etc/ssl/key.pem"
[web]
ReadOnly = true
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
```

My docker-compose file looks like this:
```yml
version: '2'

services:
  servercore:
    build: ./ServerCore
    restart: unless-stopped
    environment:
      DisplayName: ${DisplayName}
    labels:
      - traefik.backend=servercore
      - traefik.frontend.rule=Host:servercore.docker.localhost

  angular:
    build: ../actibook-frontend
    restart: unless-stopped
    labels:
      - traefik.backend=angular
      - traefik.frontend.rule=PathPrefix:/
      - traefik.enable=true
      - traefik.port=4200
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.customRequestHeaders=Host:servercore.docker.localhost

  traefik:
    build: ./traefik
    ports:
      - "80:80"
      - "443:443"
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

But when I am adding "Host" header to requests when sending from Angular to Servercore it shows me this error:
```
Refused to set unsafe header "Host"
```

Shouldnt `traefik.frontend.passHostHeader=true` or `traefik.frontend.headers.customRequestHeaders=Host:servercore.docker.localhost` make that possible?

Thank you.
