### ISSUE TITLE
Traefik don't work with docker swarm stack and websocket

### ISSUE THREAD

**Issue by Fabryprog** [containous/traefik#3828]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am creating a docker stack with this docker-compose file:

```yml
version: "3.2"

services:
  whoami:
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "5"
    image: emilevauge/whoami
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-network"
        - "traefik.frontend.rule=PathPrefixStrip:/whoami"
    networks:
      - traefik-network

  mqtt:
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "5"
    image: toke/mosquitto
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=9001"
        - "traefik.docker.network=traefik-network"
        - "traefik.frontend.rule=PathPrefixStrip:/mqtt"
    networks:
      - traefik-network
    ports:
      - "1883:1883"

  traefik:
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "5"
    image: traefik:latest
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network
    ports:
      - "8080:8080"
      - "80:80"

networks:
  traefik-network:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
```

To create docker stack i am using this command

```
 docker stack deploy -c example-compose.yml --with-registry-auth example
```

Docker service output:

```
ID                  NAME                MODE                REPLICAS            IMAGE                      PORTS
cyp157akly2z        example_mqtt        replicated          1/1                 toke/mosquitto:latest      *:1883->1883/tcp
2b08nnqdyqnp        example_traefik     replicated          1/1                 traefik:latest             *:80->80/tcp, *:8080->8080/tcp
uuq7qvug78jj        example_whoami      replicated          1/1                 emilevauge/whoami:latest   
```
**_N.B: toke/mosquitto is a cointainer that support mqtt + websocket and working fine!_**

### What did you expect to see?

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: ihweY8bYXav5P+yMf5Sy6OnMoUc=
```

### What did you see instead?

```
HTTP/1.1 504 Gateway Timeout
Date: Tue, 28 Aug 2018 08:16:16 GMT
Content-Length: 15
Content-Type: text/plain; charset=utf-8

Gateway Timeout
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]
  dashboard = true
  debug = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
swarmMode = true
exposedByDefault = true
```

### My OS Version

```
16.04.3 LTS (Xenial Xerus)
```

### My docker version

```
18.05.0-ce
```

**Comment by Fabryprog** [comment]
Hello. There are any news?

**Comment by linucksrox** [comment]
Any chance the problem is related to #10?
If I had to guess, this doesn't work because Traefik only supports HTTP at the moment, and you're trying to proxy MQTT through it which won't work.

**Comment by Fabryprog** [comment]
UP

**Comment by mmatur** [comment]
Hi @Fabryprog ,

Thanks for your interest in Traefik.

If you create your stack with the command 
```console
docker stack deploy -c example-compose.yml --with-registry-auth example
```
The network name will be : `example_traefik-network`
```console
docker network ls
NETWORK ID          NAME                      DRIVER              SCOPE
ae148e67b312        bridge                    bridge              local
97df5569b630        docker_gwbridge           bridge              local
vncnyhe3pevh        example_traefik-network                       swarm
```

So if you use the label `traefik.docker.network=traefik-network` traefik will be not able to find the network because the network name is `example_traefik-network`. 

## Fix

Few possibilities to fix your issue. 
1. In your label change `traefik.docker.network=traefik-network` to ``traefik.docker.network=example_traefik-network``
2. Create a network with the command `docker network create --driver=overlay traefik-network` and reference this network in your compose file like this:
```yaml
networks:
  traefik-network:
    external: true
```

I think that your question is answered, so I will close your issue
