### ISSUE TITLE
User IP is not forwarding to container (swarm mode)

### ISSUE THREAD

**Issue by cmizzi** [containous/traefik#3829]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm currently trying to see real user IP with the following configuration : 

- docker swarm (18.06.1-ce)
- traefik (1.6)

```yaml
version: "3.4"
services:
    traefik_init:
        image: traefik:1.6
        command:
            - "storeconfig"
            - "--api"
            - "--debug"
            - "--entrypoints=Name:http Address::80 ForwardedHeaders.trustedIPs=0.0.0.0/0"
            - "--defaultentrypoints=http"
            - "--acme"
            - "--acme.storage=traefik/acme/account"
            - "--acme.entryPoint=https"
            - "--acme.httpChallenge.entryPoint=http"
            - "--acme.onHostRule=true"
            - "--acme.onDemand=false"
            - "--acme.email=test@domain.com"
            - "--docker"
            - "--docker.swarmMode"
            - "--docker.domain=traefik"
            - "--docker.endpoint=tcp://docker-proxy:2375"
            - "--docker.watch"
            - "--consul"
            - "--consul.endpoint=consul:8500"
            - "--consul.prefix=traefik"
        networks:
            - traefik-proxy
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
        depends_on:
            - consul

    docker-proxy:
        image: rancher/socat-docker
        networks:
            - traefik-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    cpus: '0.10'
                    memory: 8M
                reservations:
                    cpus: '0.10'
                    memory: 8M

    traefik:
        image: traefik:1.6
        depends_on:
            - traefik_init
            - consul
        command:
            - "--consul"
            - "--consul.endpoint=consul:8500"
            - "--consul.prefix=traefik"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik-proxy
        ports:
            - target: 80
              published: 80
              mode: host
            - target: 443
              published: 443
              mode: host
        deploy:
            mode: global
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure

    consul:
        image: consul
        command: agent -server -bootstrap-expect=1
        volumes:
            - "consul-data:/consul/data"
        environment:
            - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
            - CONSUL_BIND_INTERFACE=eth0
            - CONSUL_CLIENT_INTERFACE=eth0
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
        networks:
            - traefik-proxy

    whoami:
        image: emilevauge/whoami
        deploy:
            labels:
                - "traefik.port=80"
                - "traefik.frontend.rule=whoami.domain.com"
                - "traefik.docker.network=traefik-proxy"

networks:
    traefik-proxy:
        external: true

volumes:
    consul-data:
```
This compose file is used on server. Also, `traefik-proxy` is an overlay network.

### What did you expect to see?

```
Hostname: 0820ff98540d
IP: __userip__
IP: 10.0.0.132
IP: 172.18.0.12
IP: 10.0.16.8
GET / HTTP/1.1
Host: whoami.domain.com
User-Agent: curl/7.58.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: __userip__
X-Forwarded-Host: whoami.domain.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 24e0e3be604b
X-Real-Ip: __userip__
```

### What did you see instead?

```
Hostname: 0820ff98540d
IP: 127.0.0.1
IP: 10.0.0.132
IP: 172.18.0.12
IP: 10.0.16.8
GET / HTTP/1.1
Host: whoami.domain.com
User-Agent: curl/7.58.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.17.0.1
X-Forwarded-Host: whoami.domain.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 24e0e3be604b
X-Real-Ip: 172.17.0.1
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:42884\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://10.0.0.132:80"
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.0.132:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:42884\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.0.132:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:42884\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-08-28T10:21:08Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://10.0.0.132:80, code: 200, Length: 354, duration: 1.536318ms"
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.0.132:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:42884\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.0.132:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:42884\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2018-08-28T10:21:08Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.58.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:42884\",\"RequestURI\":\"/\",\"TLS\":null}"
```
