### ISSUE TITLE
traefik + consul acme.tlsChallenge invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dazoot** [containous/traefik#3830]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am testing traefik + consul backend and trying to generate a ACME Certificate by using `acme.tlsChallenge` method. We are trying to switch to `consul` from `file` backend. In `file` backend mode all works fine.

### What did you expect to see?

A valid SSL certificate.

### What did you see instead?

No certificate was generated and had `Error in Go routine: runtime error: invalid memory address or nil pointer dereference` in the log.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:36:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
defaultEntryPoints = [ "https" ]

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  format = "json"

[accessLog.fields]
  defaultMode = "drop"

[accessLog.fields.names]
  "RequestHost" = "keep"
  "ClientHost" = "keep"
  "RequestLine" = "keep"
  "FrontendName" = "keep"
  "BackendAddr" = "keep"
  "RequestProtocol" = "keep"

[accessLog.fields.headers]
  defaultMode = "drop"

[accessLog.fields.headers.names]
  "User-Agent" = "keep"

[entryPoints]
    #[entryPoints.http]
    #address = ":80"
    #[entryPoints.http.redirect]
    #    entryPoint = "https"

    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

    [entryPoints.traefik]
    address = ":9955"

[acme]
email = "acme@site.ro"
# storageFile = "/etc/traefik/acme.json"
storage = "traefikstatic/acme/account"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
acmeLogging = true
onHostRule = true
# onDemand = true

[acme.tlsChallenge]
#[acme.httpChallenge]
#entryPoint = "http"

[consul]
endpoint = "127.0.0.1:8500"
watch = true
prefix = "traefikstatic"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-08-28T15:31:42+03:00" level=debug msg="LoadCertificateForDomains [static.site.ro]..."
time="2018-08-28T15:31:42+03:00" level=debug msg="Looking for provided certificate to validate [static.site.ro]..."
time="2018-08-28T15:31:42+03:00" level=debug msg="Domains [\"static.site.ro\"] need ACME certificates generation for domains \"static.site.ro\"."
time="2018-08-28T15:31:42+03:00" level=debug msg="Loading ACME certificates [static.site.ro]..."
time="2018-08-28T15:31:42+03:00" level=info msg="legolog: [INFO] [static.site.ro] acme: Obtaining bundled SAN certificate"
time="2018-08-28T15:31:43+03:00" level=info msg="legolog: [INFO] [static.site.ro] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/a08dUyyaOP2VlHb-.....................9n-uT8pXxEJqHA"
time="2018-08-28T15:31:43+03:00" level=info msg="legolog: [INFO] [static.site.ro] acme: Trying to solve TLS-ALPN-01"
time="2018-08-28T15:31:43+03:00" level=debug msg="Challenge Present static.site.ro"
time="2018-08-28T15:31:44+03:00" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
```
