### ISSUE TITLE
Provider connection error SerializationException

### ISSUE THREAD

**Issue by hridyeshpant** [containous/traefik#3831]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
docker run -it -p 80:80 -p 8080:8080 -v $PWD/traefik_ecs.toml:/etc/traefik/traefik.toml traefik:1.6.1

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(docker run -it -p 80:80 -p 8080:8080 -v $PWD/traefik_ecs.toml:/etc/traefik/traefik.toml traefik:1.6.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "DEBUG"

[web]
address = ":8080"
readOnly = true
[web.metrics.prometheus]
buckets=[0.1,0.3,1.2,5.0]


[ecs]
clusters = ["default"]
watch = true
domain = "test.XYZ.com"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = true
region = "us-west-2"

[traefikLog]
filePath = "log/traefik.log"
format = "common"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
DEBU[2018-08-28T12:55:25Z] ECS Clusters: [default]
ERRO[2018-08-28T12:55:25Z] Provider connection error SerializationException:
	status code: 400, request id: a1fa5e0b-aac1-11e8-910a-23fcf137d915, retrying in 370.370382ms
DEBU[2018-08-28T12:55:26Z] ECS Clusters: [default]
ERRO[2018-08-28T12:55:26Z] Provider connection error SerializationException:
	status code: 400, request id: a23f2f59-aac1-11e8-910a-23fcf137d915, retrying in 462.559151ms
DEBU[2018-08-28T12:55:26Z] ECS Clusters: [default]
ERRO[2018-08-28T12:55:26Z] Provider connection error SerializationException:
```
