### ISSUE TITLE
Allow per domain ACME email address.

### ISSUE THREAD

**Issue by luckcolors** [containous/traefik#3838]
### Do you want to request a *feature* or report a *bug*?

Feature

### Use case

I'm currently using traefik for hosting multiple sites, each managed by a different person.
Because of this i don't actually own the other peoples SSL certificates so it would be better if each was registered with it's proper admin's email address.

This issue could be solved by using the solution proposed here for multiple DNS challenges by also adding the email field next to the dns challenge field. #3378

### What did you expect to see?
To be able to set specific email for each domain.
A possible implementation would be to add an override property in the domain itself.
```toml
[acme]
  email = "admin@example.com" #Global email setting
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
#  [acme.httpChallenge]
#    entryPoint = "http"

  [[acme.domains]]
    main = "example.com" #This domain will use the global setting

  [[acme.domains]]
    main = "othersite.org"
    email = "admin@othersite.org" #Override the email for this domain
```
This could technically be done for other settings too like ```onHostRule``` or ```entryPoint```.

If you consider this issue duplicated and covered by issue #3378 feel free to close it and i'll move the discussion there. :smile:
