### ISSUE TITLE
Kubernetes Access Logs - Final Field In Config Not Dropped

### ISSUE THREAD

**Issue by WillJCJ** [containous/traefik#3841]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I enabled access logging on my Tæfik ingress controller. I do not want to log `Username`, `Hostname`, `ClientUsername` and `ClientHost`.

To do this, I passed the command line arguments:

```console
--accessLog.fields.defaultMode="keep"
--accessLog.fields.names="Username=drop Hostname=drop ClientUsername=drop ClientHost=drop"
```

The same thing occurs with headers:

```console
--accessLog.fields.headers.defaultMode=keep
--accessLog.fields.headers.names="Authorization=redact Cookie=redact Set-Cookie=redact X-Csrftoken=redact X-Forwarded-For=redact"
```

### What did you expect to see?

I expected `ClientHost` to not appear in the logs.

I expected to see `"request_X-Forwarded-For":"REDACTED"` in the JSON logs.

### What did you see instead?

`ClientHost` was present in the access logs.
`request_X-Forwarded-For` had an IP address.

All other fields were dropped and redacted.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Noticed the problem on `1.6.4`

Recreated the issue on `1.6.6`

Recreated the issue on `v1.7.0-rc3`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

The environment is a Kops cluster in AWS running `v1.9.7` of Kubernetes.

I'm not using a TOML file, just the command line args in a Kubernetes `yaml` file.

Below is my `yaml` file for the deployment.

```yaml
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: traefik-ingress-lb
  labels:
    app: traefik-ingress-lb
    tier: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik-ingress-lb
      tier: proxy
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        tier: proxy
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      serviceAccountName: traefik-ingress
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7
        name: traefik-ingress-lb

        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080

        args:
        - --traefikLog.format=json
        - --accessLog.format=json
        - --accessLog.fields.defaultMode="keep"
        - --accessLog.fields.names="Username=drop Hostname=drop ClientUsername=drop ClientHost=drop"
        - --accessLog.fields.headers.defaultMode=keep
        - --accessLog.fields.headers.names="Authorization=redact Cookie=redact Set-Cookie=redact X-Csrftoken=redact X-Forwarded-For=redact"
        - --api
        - --api.dashboard
        - --api.statistics
        - --kubernetes
        - --kubernetes.ingressClass=traefik-external
        - --kubernetes.namespaces=app
        - --metrics.prometheus
        - --logLevel=INFO
        - --entryPoints=Name:http Address::80
        - --entryPoints=Name:https Address::443 TLS
        - --defaultentrypoints=http

        resources:
          requests:
            cpu: "100m"
            memory: "20Mi"
          limits:
            cpu: "150m"
            memory: "40Mi"

        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
```

#### Logs
Each request makes an access log for the pod, containing

`"request_X-Forwarded-For":"12.34.45.67"` (Should be REDACTED)
`"ClientHost":"12.34.56.78"` (Shouldn't be here)

### Fix

A dirty fix is to add an extra field to each command line arg:

```console
--accessLog.fields.names="Username=drop Hostname=drop ClientUsername=drop ClientHost=drop FakeField=drop"
--accessLog.fields.headers.names="Authorization=redact Cookie=redact Set-Cookie=redact X-Csrftoken=redact X-Forwarded-For=redact X-Clacks-Overhead=keep"
```

This then makes the logs function as expected.

### Recreation

I can only re-create this bug with the exact `yaml` file I put above.

I tried just using `docker run`  with the same args. The log fields were removed and redacted as expected.

I tried running træfik with the same args by itself in `minikube` cluster on my laptop and again, the fields were dropped and redacted.
