### ISSUE TITLE
Traefik routing to zero weight servers with AllowMinWeightZero = true and HealthCheck

### ISSUE THREAD

**Issue by EdToro74** [containous/traefik#3842]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured traefik with AllowMinWeightZero = true.
Configured a frontend/backend pair (Pair A) with **no** HealthCheck. There are two servers in the backend, one with weight 1, one with weight 0. Both servers were running and able to process traffic.
Configured a frontend/backend pair (Pair B) with a HealthCheck. There are two servers in the backend, one with weight 1, one with weight 0. Both servers were running and able to process traffic.

### What did you expect to see?

Pair A: All requests should be routed to the server with weight 1. The server with weight 0 should not have any requests routed to it.

Pair B: All requests should be routed to the server with weight 1 as long as it passes the HealthCheck. The server with weight 0 should not have any requests routed to it.

### What did you see instead?

Pair A: The expected behavior.

Pair B: HealthChecks hitting both servers (this might be OK), requests routing to both servers. I'm guessing the HealthCheck code is overriding the AllowMinWeightZero code.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": 0,
  "GraceTimeOut": 0
 },
 "GraceTimeOut": 0,
 "Debug": false,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "Tracing": null,
 "LogLevel": "",
 "EntryPoints": {
  "http": {
   "Address": "xxxx",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "https": {
   "Address": "xxxx",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": null,
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    }
   },
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "AllowMinWeightZero": true,
 "Web": null,
 "Docker": null,
 "File": null,
 "Marathon": null,
 "Consul": {
  "Watch": true,
  "Filename": "",
  "Constraints": [],
  "Trace": false,
  "TemplateVersion": 0,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxx",
  "Prefix": "traefik",
  "TLS": null,
  "Username": "",
  "Password": ""
 },
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": {
  "EntryPoint": "traefik",
  "Dashboard": true,
  "Debug": false,
  "CurrentConfigurations": null,
  "Statistics": null
 },
 "Metrics": null,
 "Ping": {
  "EntryPoint": "traefik"
 },
 "ConfigFile": "/etc/traefik.toml"
}
```

```toml
# Allow the use of 0 as server weight.
# - false: a weight 0 means internally a weight of 1.
# - true: a weight 0 means internally a weight of 0 (a server with a weight of 0 is removed from the available servers).
#
# Optional
# Default: false
#
AllowMinWeightZero = true

############################################################
# Frontends configuration
############################################################
[frontends]
	[frontends.PairA]
	backend = "PairA"
	passHostHeader = true

		[frontends.PairA.routes.hostMatch]
		rule = "Host:paira.local"

	[frontends.PairB]
	backend = "PairB"
	passHostHeader = true

		[frontends.PairB.routes.hostMatch]
		rule = "Host:pairb.local"

############################################################
# Backends configuration
############################################################
[backends]
	[backends.PairA]
		[backends.PairA.servers.Server1]
		url = "http://localhost:10000"
		weight = 1

		[backends.PairA.servers.Server2]
		url = "http://localhost:10001"
		weight = 0

	[backends.PairB]
		[backends.PairB.healthcheck]
		path = "/"

		[backends.PairB.servers.Server1]
		url = "http://localhost:10003"
		weight = 1

		[backends.PairB.servers.Server2]
		url = "http://localhost:10004"
		weight = 0
```
[config.txt](https://github.com/containous/traefik/files/2337360/config.txt)
