### ISSUE TITLE
[Documentation] Improve Entry Points definition reference to avoid "tls" key on HTTP entrypoint

### ISSUE THREAD

**Issue by C-Duv** [containous/traefik#3845]
This issue is about possible improve in the documentation.

# Facts

The [Entry Points Definition documentation file `/docs/configuration/entrypoints.md`](../blob/00728e711c76e66d35077c41245b4e713b80baeb/docs/configuration/entrypoints.md) includes a *Reference* section that conveniently gives all possible TOML key for `[entryPoints]`.

It contains the following snippet:

```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.tls]
      # ...
      [[entryPoints.http.tls.certificates]]
        certFile = "path/to/my.cert"
        keyFile = "path/to/my.key"

  [entryPoints.https]
    # ...
```

# The possible issue

While being a *reference* (not practical, functional code) this snippet tends to say that one can declare TLS certificates on a entrypoint binded to port 80 (thus, generally a HTTP -non-HTTPS- traffic).

# Reason to improve

I have no proof but some readers (seen one on Træfik's Slack channel) may have stumbled upon this documentation (from a search engine, looking for how TLS/certificates TOML keys are named) and simply copy/pasted this snippet.
I had such typo and got:
* "TLS handshake error from *<remote_client_ip>*:*<remote_client_port>*: tls: first record does not look like a TLS handshake" error in Træfik log
* "Failed writing body (0 != 7)" error when requesting via `curl`.

I think a minor change in documentation could avoid theses issues.

# Possible solutions

I don't know what is the proper way to avoid such issue, it could be:

* Add a text warning that this code (the reference block) does not really work: it only list all keys.
* Rename `[entryPoints.http]` to `[entryPoints.foobar]`
* Some other thing...
