### ISSUE TITLE
ETCD v3 + configstore does not seem to work.

### ISSUE THREAD

**Issue by firefixmaarten** [containous/traefik#3859]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I followed the documentation to use ETCD v3 as backend.

### What did you expect to see?
Working as it should.

### What did you see instead?
```
etcd permission issues.
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v1.7.0-rc3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      initContainers:
      # this will load the config from the configmap into etcd v3 (locking support).
      # Locking prevents that the config is use in a half state (during replica rollout)
      # The configmap is NOT monitored for changes, etcd is.
      # running this storeconfig on it own allows changing the config of running instances ;)
      - name: storeconfig
        image: traefik:v1.7.0-rc3
        imagePullPolicy: IfNotPresent
        args:
        - storeconfig
        - -c
        - /config/config.toml
        volumeMounts:
        - name: config-etcd
          mountPath: /config
          readOnly: true
      containers:
      - name: traefik-ingress-lb
        image: traefik:v1.7.0-rc3
        args:
        # only the etcd config is needed here!
        - --configFile=/config/config.toml
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        volumeMounts:
        - name: config
          mountPath: /config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        # make sure to give this a good name starting with role-ingress-traefik-*.
        role-ingress-traefik-test: "true"
      volumes:
      - name: config
        configMap:
          name: traefik-config
          items:
          - key: config.toml
            path: config.toml
      - name: config-etcd
        configMap:
          name: traefik-config-etcd
          items:
          - key: config.toml
            path: config.toml
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: web-secure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config-etcd
data:
  config.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "DEBUG"

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        # enable redirrect
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]
      [entryPoints.http-metrics]
        address = ":5555"
    [metrics]
      # enable metrics endpoint
      [metrics.prometheus]
        entryPoint = "http-metrics"
        buckets=[0.1,0.3,1.2,5.0]
    # enable ping for healthcheck
    [ping]
      entryPoint = "https"

    [etcd]
      endpoint = "[redacted]"
      # look for changes, needed in cluster setup.
      watch = true
      # etcd prefix /k8s/[clustername]/traefik-[purpose]. Look out for trailing slashes.
      prefix = "/k8s/[redacted]/traefik-test"
      # Will soon be the default and is needed for atomic operations
      useAPIV3 = true
      # Username configured in etc k8s_[clustername]_traefik
      username = "k8s_[redacted]_traefik"
      password = "[redacted]"
    [etcd.tls]
      # enable tls but skip securitycheck, can be used if certificates are provided..
      insecureSkipVerify = true

    [acme]
      entryPoint = "https"
      # email on lets encryp issues
      email = "[redacted]"
      # Look out for trailing slashes and match the correct ETCD path.
      storage = "/k8s/[redacted]/traefik-test/acme/account"
      # log this in the pod logs
      acmeLogging = true
      OnHostRule = true
      # override default if needed, for testing for example
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [acme.httpChallenge]
        entryPoint="http"

    [kubernetes]
    # Make this ingressClass specific so that you can use kubernetes.io/ingress.class: traefik-test. Start with "traefik-*"
    ingressClass = "traefik-test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  config.toml: |
    debug = true
    logLevel = "DEBUG"
    [etcd]
      endpoint = "[redacted]"
      # look for changes, needed in cluster setup.
      watch = true
      # etcd prefix /k8s/[clustername]/traefik-[purpose]. Look out for trailing slashes.
      prefix = "/k8s/[redacted]/traefik-test"
      # Will soon be the default and is needed for atomic operations
      useAPIV3 = true
      # Username configured in etc k8s_[clustername]_traefik
      username = "k8s_[redacted]_traefik"
      password = "[redacted]"
    [etcd.tls]
      # enable tls but skip securitycheck, can be used if certificates are provided..
      insecureSkipVerify = true

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
initcontainer:
2018/09/06 08:04:52 Storing configuration: {"LifeCycle":{"RequestAcceptGraceTimeout":0,"GraceTimeOut":10000000000},"GraceTimeOut":0,"Debug":false,"CheckNewVersion":true,"SendAnonymousUsage":false,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","TraefikLog":null,"Tracing":null,"LogLevel":"DEBUG","EntryPoints":{"http":{"Address":":80","TLS":null,"Redirect":{"entryPoint":"https"},"Auth":null,"WhitelistSourceRange":null,"WhiteList":null,"Compress":true,"ProxyProtocol":null,"ForwardedHeaders":null},"http-metrics":{"Address":":5555","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"WhiteList":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":null},"https":{"Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":null,"ClientCAFiles":null,"ClientCA":{"Files":null,"Optional":false},"DefaultCertificate":null,"SniStrict":false},"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"WhiteList":null,"Compress":true,"ProxyProtocol":null,"ForwardedHeaders":null}},"Cluster":null,"Constraints":[],"ACME":{"Email":"[redacted]","Domains":null,"Storage":"/k8s/[redacted]/traefik-test/acme/account","StorageFile":"","OnDemand":false,"OnHostRule":true,"CAServer":"https://acme-staging-v02.api.letsencrypt.org/directory","EntryPoint":"https","KeyType":"","DNSChallenge":null,"HTTPChallenge":{"EntryPoint":"http"},"TLSChallenge":null,"DNSProvider":"","DelayDontCheckDNS":0,"ACMELogging":true,"OverrideCertificates":false,"TLSConfig":null},"DefaultEntryPoints":["http","https"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"AllowMinWeightZero":false,"Web":null,"Docker":null,"File":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":{"Watch":true,"Filename":"","Constraints":[],"Trace":false,"TemplateVersion":0,"DebugLogGeneratedTemplate":false,"Endpoint":"[redacted]","Prefix":"/k8s/[redacted]/traefik-test","TLS":{"insecureSkipVerify":true},"Username":"k8s_[redacted]_traefik","Password":"[redacted]","UseAPIV3":true},"Zookeeper":null,"Boltdb":null,"Kubernetes":{"Watch":true,"Filename":"","Constraints":[],"Trace":false,"TemplateVersion":0,"DebugLogGeneratedTemplate":false,"Endpoint":"","Token":"","CertAuthFilePath":"","DisablePassHostHeaders":false,"EnablePassTLSCert":false,"Namespaces":null,"LabelSelector":"","IngressClass":"traefik-test","IngressEndpoint":null},"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null,"ServiceFabric":null,"Rest":null,"API":null,"Metrics":{"Prometheus":{"Buckets":[0.1,0.3,1.2,5],"EntryPoint":"http-metrics"},"Datadog":null,"StatsD":null,"InfluxDB":null},"Ping":{"EntryPoint":"https"},"HostResolver":null}

logs of traefik itself:
time="2018-09-06T08:04:53Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 502.230034ms"
time="2018-09-06T08:04:54Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 1.008861805s"
time="2018-09-06T08:04:55Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 1.529148714s"
time="2018-09-06T08:04:56Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 2.387034683s"
time="2018-09-06T08:04:59Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 2.109027876s"
time="2018-09-06T08:05:01Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 4.636596763s"
time="2018-09-06T08:05:05Z" level=error msg="Load config error: etcdserver: permission denied, retrying in 6.729177868s"

```
