### ISSUE TITLE
overlapping certificates on different endpoints prevent acme cert request

### ISSUE THREAD

**Issue by zyclonite** [containous/traefik#3866]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
we use traefik with multiple tls enabled entrypoints configured
* https (with acme)
* traefik (for the admin ui, with our internal selfsigned certificates)
* potentially more internally signed endpoints, like for clientssl, not listed in this report

**important is**, the internal certificates sometimes contain wildcard certificates which overlap with the acme configured entrypoint

### What did you expect to see?
**working**: accessing the admin api via the same hostname but on a different port
* i would expect to get the internal certificate

**working**: accessing the https endpoint
* i would expect to get the newly acquired lets encrypt certificate

**not working**: in my particular case
* one services registers a frontend with the domain service1.anotherdomain.com
* this should trigger an acme cert request because the anotherdomains.com has no wildcard certificate configured
* but i only get the traefik dummy certificate on that entrypoint (and the server did not even try to request one)

### What did you see instead?
**short version**
* randomly initiated traefik instances, some have an acme certificate some not
* if the acme cert was not acquired the entrypoint falls back to the traefik dummy cert

**long version**
* i did a 1.7 latest build with added logging 
`docker run zyclonite/traefik:acme_cert_resolve_issue` (https://github.com/zyclonite/traefik/commit/a8490d128b92c63442f9fc5d599e31274d6b16c4)
* this shows that before an acme cert is requested, traefik checks for several existing certificates (static, dynamic, acme, resolved...)
* it seems this list of certificates is not always the same, due to async loading and resolving during startup... in one scenario, below the logs, an internal cert matches one of the acme entrypoint hostnames and so it's not getting requested from the lets encrypt service
* i would have expected to see only the acme certificates to be matched in the first place, because there is anyway an entrypoint in the acme configuration

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["https"]
rootCAs = [ "/etc/ssl/certs/internal.pem" ]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.tls]
      [[entryPoints.traefik.tls.certificates]]
      certFile = "/etc/ssl/certs/server.cert.pem"
      keyFile = "/etc/ssl/certs/server.key.pem"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "internal@domain.com"
  storage = "/etc/traefik/acme.json"
  entryPoint = "https"
  acmeLogging = false
  onHostRule = true
  keyType = "EC256"
  [acme.dnsChallenge]
    provider = "exec"
    delayBeforeCheck = 0
  [[acme.domains]]
    main = "*.domain.com"
  [[acme.domains]]
    main = "*.dev.domain.com"
  [[acme.domains]]
    main = "*.test.domain.com"

[consulCatalog]
  endpoint = "172.17.0.1:8500"
  exposedByDefault = false
  domain = "domain.com"

[consulCatalog.tls]
  ca = "/etc/ssl/certs/intermediate.pem"
  cert = "/etc/ssl/certs/internal/client.cert.pem"
  key = "/etc/ssl/certs/internal/client.key.pem"

[api]
  entryPoint = "traefik"
  dashboard = true
  [api.statistics]
    recentErrors = 10

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets=[0.1,0.3,1.2,5.0]
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

from traefik 1.7.0-rc3
```
time="2018-09-07T07:23:10Z" level=debug msg="Add certificate for domains *.domain.com"
time="2018-09-07T07:23:10Z" level=debug msg="Add certificate for domains *.dev.domain.com"
time="2018-09-07T07:23:10Z" level=debug msg="Add certificate for domains *.test.domain.com"
time="2018-09-07T07:23:12Z" level=debug msg="Add certificate for domains *.dev.domain.com,*.anotherdomain.com,*.domain.com,*.test.domain.com,127.0.0.1,172.17.0.1"
time="2018-09-07T07:23:12Z" level=debug msg="Try to challenge certificate for domain [service1.anotherdomain.com] founded in Host rule"
time="2018-09-07T07:23:12Z" level=debug msg="Looking for provided certificate(s) to validate [\"service1.anotherdomain.com\"]..."
time="2018-09-07T07:23:12Z" level=debug msg="No ACME certificate to generate for domains [\"service1.anotherdomain.com\"]."
```
from my own latest 1.7 build (only my added loglines for the cert resolution, removed the redundant array values so you can see what was added)
```
"acme-provider GetAllDomains [\"127.0.0.1\" \"172.17.0.1\" \"*.domain.com\" \"*.test.domain.com\" \"*.dev.domain.com\" \"*.anotherdomain.com\"]"
"acme-provider +ACME         [\"*.domain.com\" \"*.dev.domain.com\" \"*.test.domain.com\"]"
"acme-provider +resolved     []"
"acme-provider +configured   [\"*.domain.com\" \"*.dev.domain.com\" \"*.test.domain.com\"]"
"acme-provider isDomainAlreadyChecked service1.anotherdomain.com != 127.0.0.1"
"acme-provider isDomainAlreadyChecked service1.anotherdomain.com != 172.17.0.1"
"acme-provider isDomainAlreadyChecked service1.anotherdomain.com != *.domain.com"
"acme-provider isDomainAlreadyChecked service1.anotherdomain.com != *.test.domain.com"
"acme-provider isDomainAlreadyChecked service1.anotherdomain.com != *.dev.domain.com"
"acme-provider isDomainAlreadyChecked service1.anotherdomain.com == *.anotherdomain.com"
```
### possible solution
only check entrypoints configured for acme against "acme stored or generated" certificates and not against all existing
at least as long as a fallback to that existing "non acme" certificate is not allowed
