### ISSUE TITLE
DNS-01 attempts to add TXT record to wrong zone.

### ISSUE THREAD

**Issue by precision** [containous/traefik#3869]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have a domain in gcloud 'k8s.domain.tld' the root of this domain is hosted on another DNS provider with proper IN NS records pointing k8s.domain.tld to gcloud.  While trying to configure acme I noticed it was throwing the following error.
```
time="2018-09-08T04:48:57Z" level=error msg="Unable to obtain ACME certificate for domains \"*.k8s.domain.tld\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[k8s.domain.tld] Error presenting token: No matching GoogleCloud domain found for domain domain.tld.\n"
```

To test a theory, I created a dummy gcloud dns zone for domain.tld and restarted, I saw the _acme-challenge.k8s txt record added to the dummy root zone.

### What did you expect to see?

Add _acme-challenge TXT Record to the k8s.domain.tld gcloud zone.

### What did you see instead?

Added _acme-challenge.k8s TXT record to domain.tld instead.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.6.6 built on 2018-08-20_01:10:06PM
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
InsecureSkipVerify = true
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[kubernetes]
[acme]
email = "user@domain.tld"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
acmeLogging = true
  [acme.dnsChallenge]
  provider = "gcloud"
[[acme.domains]]
   main = "*.k8s.domain.tld"
[api]
  entryPoint = "traefik"
  dashboard = true
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
