### ISSUE TITLE
Traefik log can't switch the timezone

### ISSUE THREAD

**Issue by maifusha** [containous/traefik#3870]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In my case, I wonder if I can switch the time zone to use the local time, and the traefik log and access log will make more sense and easier to understand

But I search over the  traefik official document or github issues, i cant find any options to achieve it

**Comment by jpalczewski** [comment]
For me:
```
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /var/run/log/traefik/access.log:/tmp/access.log
                        - "/etc/timezone:/etc/timezone:ro"
                        - "/etc/localtime:/etc/localtime:ro"
```
did the trick - `StartLocal` in json-formatted access log became true `StartLocal`.

**Comment by v7lin** [comment]
for me:

docker-compose.yml
````
  traefik:
    container_name: traefik
    image: traefik:1.7.5-alpine
    restart: always
    hostname: traefik
    ports:
      - 80:80
      - 443:443
#      - 8080:8080
    volumes:
      - ../dev-ops-repo/traefik/acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/entrypoint-fixed.sh:/entrypoint-fixed.sh
    environment:
      - TZ=${TIME_ZONE}
    command:
      - "--loglevel=WARN"
      - "--api"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--docker"
    entrypoint:
      - /entrypoint-fixed.sh
````

traefik/entrypoint-fixed.sh
````
#!/bin/sh
apk update && apk add curl bash tree tzdata
./entrypoint.sh
````

````
/ # ls
bin                  entrypoint.sh        lib                  proc                 sbin                 tmp
dev                  etc                  media                root                 srv                  usr
entrypoint-fixed.sh  home                 mnt                  run                  sys                  var
/ # date -R
Thu, 13 Dec 2018 10:12:45 +0800
````

**Comment by ycharron** [comment]
My Traefik access logs shows a different time (zone) than my system. There's a 5h difference, where Traefik is 5 hours ahead of my system's time. I'm running Traefik as a binary, not in Docker.

How can this be resolved?

**Comment by mbleichner** [comment]
Same problem here. My host machine is using CEST, yet all access log entries are shown in UTC.
Using trafik:1.7 image with:

    environment:
      - TZ=Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

**Comment by natlibfi-arlehiko** [comment]
> Same problem here. My host machine is using CEST, yet all access log entries are shown in UTC.
> Using trafik:1.7 image with:
> 
> ```
> environment:
>   - TZ=Europe/Berlin
> volumes:
>   - /var/run/docker.sock:/var/run/docker.sock
>   - /etc/timezone:/etc/timezone:ro
>   - /etc/localtime:/etc/localtime:ro
> ```

So does this work for you? Setting `TZ` and mounting `/etc/localtime` doesn't help (Either both or separately).

My host (CentOS) doesn't have `/etc/timezone` but tried creating & mounting that to no avail.

**Comment by mbleichner** [comment]
No, it doesn't work. That's why I was posting here.

**Comment by dduportal** [comment]
Hi @mbleichner and @natlibfi-arlehiko, thanks for letting us know.
My memories of CentOS (I might be rusty tough) remind me that `/etc/localtime` was a symlink to the timezone file  located in `/usr/share/zoneinfo/`.

I'm currently trying to reproduce this, but could you also try to mount the "right" TZ directory?
If it is not working, maybe mounting the file as `localtime` instead:

* Test 1:

```yaml
volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
  - /etc/localtime:/etc/localtime:ro
```

* Test 2:

```yaml
volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/share/zoneinfo/Europe/Berlin:/etc/localtime:ro
```

**Comment by mbleichner** [comment]
Thx for investigating this @dduportal!
I tried your suggestions, but unfortunately they both don't work - times are still in UTC.

**Comment by mbleichner** [comment]
FYI: if I execute the date command inside the traefik alpine container, I get the correct result (CEST timezone). The traefik logs still show UTC times, though.

Tested with the setup described in https://github.com/containous/traefik/issues/3870#issuecomment-487913015

**Comment by dduportal** [comment]
@mbleichner thanks for the feedback. As you can confirm that the Traefik container is having the right TZ, the "technical part" is solved.

As for Traefik v1.7, the `timestamp` field of the logs is in UTC (ref. ). However you can still use the field `StartLocal`, as referenced in the documentation: https://docs.traefik.io/configuration/logs/#list-of-all-available-fields .

Let us know the result?

**Comment by natlibfi-arlehiko** [comment]
Seems to be the problem is with using logrus's default formatter which doesn't take the timezone in to consideration: https://github.com/sirupsen/logrus/issues/293

Would it be possible to implement/use a module that uses the OS timezone by default (Or by configuration option)?

**Comment by dduportal** [comment]
@natlibfi-arlehiko , this would be a breaking change, so it cannot be done for the `1.7.x` version of Traefik: let's wait for the `v2.x` release :)

**Comment by mbleichner** [comment]
> As for Traefik v1.7, the `timestamp` field of the logs is in UTC (ref. https://github.com/containous/traefik/blob/v1.7/middlewares/accesslog/logger_formatters.go#L25). However you can still use the field `StartLocal`, as referenced in the documentation: https://docs.traefik.io/configuration/logs/#list-of-all-available-fields .

Maybe I'm missing something here, but how would I configure this? I tried adding
`--accesslog.fields.names='StartLocal=keep StartUTC=drop'`
but this just removes the UTC time. The local time doesn't even seem to be there to begin with.

**Comment by ldez** [comment]
If you are using CLF it's possible to change the "field source" for the start time.
You have to use `json` formater to get `StartLocal` value.

**Comment by dduportal** [comment]
@mbleichner based on @ldez feedbacks, here is an example of working configuration:

```yaml
version: '3.7'

services:
  reverse-proxy:
    image: traefik:1.7.12-alpine
    command:
      - --docker
      - --api
      - --accesslog
      - --accesslog.format=json
      - --accesslog.fields.names="StartLocal=keep StartUTC=keep"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /usr/share/zoneinfo/US/Alaska:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
```

**Comment by natlibfi-arlehiko** [comment]
@dduportal So you have to use `JSON`-formatted logs if wanting to use custom timezone?

**Comment by mbleichner** [comment]
@dduportal Thanks, your example works (but oddly enough only with the alpine image, not with the from-scratch one).

Unfortunately, JSON formatted logs are extremely hard to read, so this isn't an alternative for me :(

**Comment by natlibfi-arlehiko** [comment]
> @dduportal Thanks, your example works (but oddly enough only with the alpine image, not with the from-scratch one).
> 
> Unfortunately, JSON formatted logs are extremely hard to read, so this isn't an alternative for me :(

Exactly. Hopefully the timezone will be taken into consideration as commented [here.](https://github.com/containous/traefik/issues/3870#issuecomment-501208093)

**Comment by dduportal** [comment]
Hi @mbleichner @natlibfi-arlehiko ,

Thanks to @ldez good ideas, we've tried a tiny fix that might be non breaking and such integrated in the `v1.7` in #4954. If you want to test it, check the documentation update in this PR, and try the provided configuration with the image `dduportal/traefik:gh-3870` which contains the fix.

A side note: the Traefik image based on Alpine should not require to mount your host local's timezone, as the package `tzdata` is installed (ref. https://github.com/containous/traefik-library-image/blob/master/alpine/Dockerfile#L2).
But as you discovered, this files are absent in the `scratch` image, hence the need to mount the directory `/usr/share/zoneinfo`. 
In both cases, you have to set the environment variable `TZ` to your timezone, so Go will get the right file in the `/usr/share/zoneinfo` directory.

**Comment by mbleichner** [comment]
@dduportal Thank you very much, I tested your image and it works great!

As a side note:
`--accesslog.fields.names="StartUTC=drop"`
is sufficient to get the desired behavior.

The relevant parts of my working configuration now look like this:
```yaml
  proxy:
    image: dduportal/traefik:gh-3870
    command:
      ...
      --accesslog
      --accesslog.fields.names="StartUTC=drop"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
```
