### ISSUE TITLE
Redirect none www to www not working , Aws k8 setup , Kubectl see no changes on apply

### ISSUE THREAD

**Issue by devypt** [containous/traefik#3874]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I want to redirect non-www and none SSL to www SSL

I tried also to comment traefik.frontend.rule.type without any result and tried multiple regex formats but didn't worked

### What did you expect to see?

I expect the redirect to work

### What did you see instead?
redirect didn't worked , Also kubectl apply showing that no changes most of the time

```
kubectl apply -f k8/traefik/ingress-controller-test.yaml
ingress.extensions/testraefik unchanged
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.0 (rc4)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: https://auth.test.com/auth
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/redirect-permanent: true
    traefik.ingress.kubernetes.io/redirect-regex: (http://example.com|https://example.com|http://www.example.com)
    traefik.ingress.kubernetes.io/redirect-replacement: https://www.example.com

spec:
  tls:
  - secretName: traefik-letsencrypt
    hosts:
    - www.example.com
    - example.com
    - admin.example.com
  rules:

  - host: example.com
    http:
      paths:

      - path: /
        backend:
          serviceName: www-frontend
          servicePort: http

      - path: /api/test
        backend:
          serviceName: test-api
          servicePort: http

```

I used the official helm chart for the setup

**Comment by dtomcej** [comment]
Hello @devypt 

I notice that you have regex hosts that you do not define in your ingress.

You never define `www.example.com` in your ingress, and therefore it it not matched for your regex.

This is why `https://www.example.com` does not work for you.

Try adding a `www.example.com` host section in your ingress, and it should work fine for you.

Please let us know if this works for you.

Thanks!

**Comment by devypt** [comment]
Thanks @dtomcej , Fixed!

**Comment by devypt** [comment]
just for refernece this is a full working example

```yamel 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-temporary-redirect: "true"
    ingress.kubernetes.io/ssl-host: "example.com"
    traefik.ingress.kubernetes.io/redirect-regex: "^https://example.com(.*)"
    traefik.ingress.kubernetes.io/redirect-replacement: "https://www.example.com/$1"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/frame-deny: "false"

spec:
  tls:
  - secretName: traefik-letsencrypt
    hosts:
    - www.example.com
    - example.com
  rules:

  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: www-frontend
          servicePort: http

  - host: www.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: www-frontend
          servicePort: http
```

**Comment by deshetti** [comment]
I have the following for my ingress, but the www is not redirecting to non-www site. Is there anything that I am doing wrong? I am using helm chart for Traefik and enabled SSL on the site.

Here is the links for reference: [www.gateway.factly.in](http://www.gateway.factly.in)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: "^http://www.(.*)"
    traefik.ingress.kubernetes.io/redirect-replacement: "http://$1"

spec:
  rules:
    - host: gateway.factly.in
      http:
        paths:
          - path: /
            backend:
              serviceName: gateway
              servicePort: http
    - host: www.gateway.factly.in
      http:
        paths:
          - path: /
            backend:
              serviceName: gateway
              servicePort: http
```

Any help is greatly appreciated. Thanks.
