### ISSUE TITLE
[entryPoints.https.tls.ClientCA] Problem

### ISSUE THREAD

**Issue by alpertandogan** [containous/traefik#3875]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Usinng configuration below . SSL site defined in entryPoints  works with Client using Browser.But dont work if client doesnot have CA boundle. 
https:/www.xxxx.com  On browser works well.
But using
```console
curl -X GET -H '' 'https://www.xxxx.com' like that get an error.
```

### What did you expect to see?
Standalone web site using Apache2.4 with SSL defination work with CURL .. This site  comminicate with port 80 work behind Treafik configured SSL defination Using CURL must be work also.

### What did you see instead?
Using CURL (or webhook from dialogflow.com .,aws.)  does not get CA boundle from treafik.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Final Latest version

on CURL 

```console
$ curl -X GET -H '' 'https://www.xxxxx.com/wh/g.php'
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs)
```
```
DEBU[2018-09-11T11:12:09+03:00] http: TLS handshake error from 31.xx.xx.122:57286: remote error: tls: unknown certificate authority
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"
#logLevel = "ERROR"

#[traefikLog]
#  filePath = "/tmp/logs/traefik.log"
#  format   = "json"

#[accessLog]
#  filePath = "/tmp/logs/access.log"
#  format = "json"


[web]
address = ":8080"
[healthcheck]

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
   address = "31.6.89.120:80"
   [entryPoints.http.redirect]
    entryPoint = "https"  
   [entryPoints.https]
    address = "31.xx.xx.120:443"
    compress = true
   [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
       ]
       
    #[entryPoints.https.tls.ClientCA]
    #  files = ["COMODORSADomainValidationSecureServerCA.crt"]
      #, "COMODORSAAddTrustCA.crt", "AddTrustExternalCARoot.crt"
    #  optional = false
      
   [[entryPoints.https.tls.certificates]]
      certFile = "xxxx_com.crt"
      keyFile = "xxxx_com_nopass.key"    
   #[[entryPoints.http.tls.defaultCertificate]]
   #   certFile = "xxxx_com.crt"
   #   keyFile = "xxxx_com_nopass.key"    

     

        
#consul.tls.ca="AddTrustExternalCARoot.crt"
#consul.tls.cert="xxxx_com.crt"
#consul.tls.key="xxxx_com_nopass.key"
# args = [
#          "--consul",
 #         "--consul.endpoint=127.0.0.1:8443",
#          "--consul.prefix=traefik",
 #         "--consul.watch=true",
 #         "--consul.tls",
 #         "--consul.tls.ca=AddTrustExternalCARoot.crt",
#          "--consul.tls.cert=xxxx_com.crt",
#          "--consul.tls.key=xxxx_com_nopass.key",
#
#          "--consulCatalog.tls.ca=/tls/root-ca.cert",
#        ]

[file]
[backends]
  [backends.xxxxserver]       
    [backends.xxxxserver.buffering]
      maxRequestBodyBytes = 10485760  
      memRequestBodyBytes = 2097152  
      maxResponseBodyBytes = 10485760
      memResponseBodyBytes = 2097152 
    [backends.xxxxserver.loadbalancer.stickiness]
    [backends.xxxxserver.healthcheck]
      path = "/favicon.ico"
      interval = "1000s"
    [backends.xxxxserver.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5" 
    [backends.xxxxserver.servers.server1]
      url = "http://31.xx.xx.121"
        weight = 10
#    [backends.xxxxserver.servers.server2]
#      url = "http://31.xx.xx.122"
#        weight = 10

  [frontends]
  [frontends.xxxxserver_app]
  entrypoints = ["http","https"]
  backend = "xxxxserver"
  passHostHeader = true
    [frontends.xxxxserver_app.routes.all]
     rule = "HostRegexp:www.xxxx.com"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
DEBU[2018-09-11T11:12:09+03:00] http: TLS handshake error from 31.xxx.xxx122:57286: remote error: tls: unknown certificate authority
```
