### ISSUE TITLE
Enable export of internal metrics

### ISSUE THREAD

**Issue by renaudhager** [containous/traefik#3877]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Hello guys,

I tried to enbale `/metrics` endpoint.

I created the following question on stackoverflow: https://stackoverflow.com/questions/52170952/traefik-expose-internal-metrics and asked on slack ( https://traefik.slack.com/archives/C0CDT22PJ/p1536061443000100 ).

Ultimately my goal is to get metrics per frontend (don't know if it's possible).

I'm probably missing something in the documentation.

### What did you expect to see?
I expect to be able to retrieve internal metrics from API endpoint with the following path: `/metrics`

### What did you see instead?
I got a `404` return code `page not found`.

```
curl localhost:8080/metrics
404 page not found
```

API endpoint works well:
```
curl localhost:8080/health | jq
{
  "pid": 1,
  "uptime": "13.9991115s",
  "uptime_sec": 13.9991115,
  "time": "2018-09-11 10:35:06.8140708 +0000 UTC m=+14.079866401",
  "unixtime": 1536662106,
  "status_code_count": {},
  "total_status_code_count": {
    "404": 1
  },
  "count": 0,
  "total_count": 1,
  "total_response_time": "100.9µs",
  "total_response_time_sec": 0.0001009,
  "average_response_time": "100.9µs",
  "average_response_time_sec": 0.0001009,
  "recent_errors": [
    {
      "status_code": 404,
      "status": "Not Found",
      "method": "GET",
      "host": "localhost:8080",
      "path": "/metrics",
      "time": "2018-09-11T10:34:57.0948272Z"
    }
  ]
}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run -it traefik:v1.6 version
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
logLevel = "DEBUG"

[entryPoints]
    [entryPoints.http]
    address = ":80"

[traefikLog]
  format = "json"

[accessLog]
  format = "json"

# API definition
[api]

  entryPoint = "traefik"
  dashboard = true
  debug = true

  [api.statistics]
    recentErrors = 10

  [api.accessLog]
    format = "json"
# Metrics definition
[metrics]

  [metrics.datadog]

    address = "172.17.0.1:8125"

    pushInterval = "10s"

# enable /ping on the API port
[ping]
entryPoint = "traefik"

################################################################
# Mesos/Marathon Provider
################################################################

# Enable Marathon Provider.
[marathon]

endpoint = "http://mesos.lan:8080/"

watch = true

domain = "service.lan"

exposedByDefault = false
```
