### ISSUE TITLE
Wildcard support for kubernetes ingress

### ISSUE THREAD

**Issue by astromahi** [containous/traefik#3884]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to setup a kubernetes ingress rules that work based on subdomain. But when I use wildcard for pointing subdomain(`*.domain.com`). It is not recognising the rule and rest of the rules were disappeared from traefik dashboard.

### What did you expect to see?

Traefik should recognise the wildcard rules and associated back-end

### What did you see instead?

All of the exisiting rules were not recognised and respective back-ends disappeared from traefik dashboard

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.6.6 tetedemoine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
Kubernetes v1.9.6
```

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: domain-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
  - host: "accounts.domain.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: account-service
          servicePort: 9001
  - host: "admin.domain.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: admin-service
          servicePort: 9002
  - host: "*.domain.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: client-service
          servicePort: 9003
```
