### ISSUE TITLE
Traefik access logs, add option to obfuscate authorization header

### ISSUE THREAD

**Issue by bitsofinfo** [containous/traefik#3890]
### Do you want to request a *feature* or report a *bug*?

Feature. Add an option that will OMIT or Obfuscate the Authorization header value in traefik access logs

### What did you do?

Enabled access logs

### What did you expect to see?

Access logs, but not authorization header contents in the clear logged on disk

### What did you see instead?

Access logs with authorization header values in access log

```
.....":"gzip","request_Authorization":"Basic REMOVED_FOR_THIS_ISSUE","request_Content-Type":"text/plain",....
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6.6

**Comment by peloncano** [comment]
yes, this is important!

**Comment by geraldcroes** [comment]
https://docs.traefik.io/configuration/logs/#access-logs

```toml
[accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "User-Agent" = "redact"
        "Authorization" = "drop"
        "Content-Type" = "keep"
        # ...
```
