### ISSUE TITLE
Chrome can not open asp.net page by treafik

### ISSUE THREAD

**Issue by Bulls1986** [containous/traefik#3905]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

open correctly

### What did you see instead?

I can't find the page when I use chrome to access the traefik proxy address.But I can open the page when I use edge or firefox, or if I use chrome to open the backend address, it will open correctly.

In chrome
`
Request URL: http://aspnet-demo1.marathon.localhost/

Referrer Policy: no-referrer-when-downgrade

Provisional headers are shown

Upgrade-Insecure-Requests: 1

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/69.0.3497.100 Safari/537.36
`

In firefox
`
GET / HTTP/1.1
Host: aspnet-demo1.marathon.localhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1

HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 3197
Content-Type: text/html; charset=utf-8
Date: Wed, 19 Sep 2018 05:58:23 GMT
Server: Microsoft-IIS/10.0
X-Aspnet-Version: 4.0.30319
X-Aspnetmvc-Version: 5.2
X-Powered-By: ASP.NET
`

In edge
`
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US, en; q=0.8, zh-Hans-CN; q=0.5, zh-Hans; q=0.3
Connection: Keep-Alive
Host: aspnet-demo1.marathon.localhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

Cache-Control: private
Content-Length: 3197
Content-Type: text/html; charset=utf-8
Date: Wed, 19 Sep 2018 05:59:10 GMT
Server: Microsoft-IIS/10.0
X-Aspnetmvc-Version: 5.2
X-Aspnet-Version: 4.0.30319
X-Powered-By: ASP.NET
`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
port = ":80"
graceTimeOut = 10
logLevel = "DEBUG"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  format = "json"

[web]
address = ":8081"

[marathon]
endpoint = "http://marathon.service.consul:18080"
domain = "marathon.localhost"
watch = true
ExposedByDefault = true
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
I can not find any access or traefik log when I use chrome to access frontend address
```
