### ISSUE TITLE
x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by FernandoMiguel** [containous/traefik#3906]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?
to load upstream to load via HTTPS

### What did you see instead?
`500 Internal Server Error' caused by: x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run --rm  traefik:v1.7-alpine version
Version:      v1.7.0-rc5
Codename:     maroilles
Go version:   go1.11
Built:        2018-09-18_01:50:00PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

debug = false
# defaultEntryPoints = ["http", "https"]

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/private/fullchain.pem"
      keyFile = "/etc/ssl/private/cert.key"


# Enable Docker configuration backend
[docker]

# domain = "docker.localhost"
domain = "docker.dev.XXXXX.com"
network = "traefik-web"

# exposedByDefault = true
exposedByDefault = false

# InsecureSkipVerify = true
```

```YAML
version: "3.6"

services:
  tls-volume:
    image: myrepo/acme-tls
    container_name: tls-volume
    # networks:
    #   - VOID
    volumes:
      - tls:/acme-tls/tls:ro
    command: ["sleep", "1"]
    user: nobody

  traefik:
    image: traefik:v1.7-alpine #The official Traefik docker image
    container_name: traefik
    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    ports:
      - "8080:8080" #The Web UI (enabled by --api)
      - "172.16.29.29:80:80"     #The HTTP port
      - "172.16.29.29:443:443"
      # - "80:80"     #The HTTP port
      # - "443:443"
    networks:
      - traefik-web
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - tls:/etc/ssl/private:ro
    depends_on:
      - tls-volume

  frontend-storage:
    image: myrepo/storage
    container_name: frontend-storage
    volumes:
      - frontend:/var/www
    user: nobody

  frontend-nginx:
    image: myrepo/nginx
    container_name: frontend-nginx
    labels:
      - "traefik.backend=frontend-nginx"
      - "traefik.frontend.rule=Host:docker.dev.XXXX.com"
      - "traefik.docker.network=traefik-web"
      - "traefik.port=443"
      - "traefik.protocol=https"
    expose:
      - "443"
    networks:
      - traefik-web
      - frontend
    volumes:
      - tls:/etc/ssl/private:ro
      - frontend:/var/www
    depends_on:
      - traefik
      - frontend-storage
      - frontend-php
      - tls-volume

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="https://192.168.16.7:443"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="'500 Internal Server Error' caused by: x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward/http: Round trip: https://192.168.16.7:443, code: 500, Length: 21, duration: 162.4747ms tls:version: 303, tls:resume:false, tls:csuite:c02b, tls:server:docker.dev.XXXX.com"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}" ForwardURL="https://192.168.16.7:443"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="'500 Internal Server Error' caused by: x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward/http: Round trip: https://192.168.16.7:443, code: 500, Length: 21, duration: 2.2809ms tls:version: 303, tls:resume:false, tls:csuite:c02b, tls:server:docker.dev.XXXX.com"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
```
