### ISSUE TITLE
Traefik-Ingress sticky sessions are not working with HTTPS

### ISSUE THREAD

**Issue by SubhakarKotta** [containous/traefik#3926]
### Issue:
When I ran the application on Traefik Node Port HTTPS Service the sticky sessions are not working properly

## Able to access URL properly but Sticky Sessions **doesnt** work Node Port (HTTPS)
https://myapp-82.sm.k8s.dev.myapp.io:**31946**

### Working properly with out any issues with Sticky Sessions Node Port (HTTP)
http://myapp-82.sm.k8s.dev.myapp.io:**30548**

### Kubernetes Bare Metal Version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
### Operating System
Ubuntu

### Application Service Configuration
```json
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "myapp-web",
    "namespace": "myapp",
    "selfLink": "/api/v1/namespaces/pega/services/myapp-web",
    "uid": "5ad2fe01-bf24-11e8-9466-00505623bd42",
    "resourceVersion": "272065",
    "creationTimestamp": "2018-09-23T11:32:29Z",
    "annotations": {
 ###     "traefik.ingress.kubernetes.io/affinity": "true",
 ###     "traefik.ingress.kubernetes.io/load-balancer-method": "drr",
 ###   "traefik.ingress.kubernetes.io/max-conn-amount": "10",
 ###      "traefik.ingress.kubernetes.io/session-cookie-name": "JSESSIONID"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 80,
        "targetPort": 8080
      }
    ],
    "selector": {
      "app": "myapp-web"
    },
    "clusterIP": "10.106.245.124",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}
```
### Ingress Configuration
```json
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "traefik-ingress-myapp",
    "namespace": "pega",
    "selfLink": "/apis/extensions/v1beta1/namespaces/myapp/ingresses/myapp-ingress-pega",
    "uid": "8485d85a-c088-11e8-9466-00505623bd42",
    "resourceVersion": "250419",
    "generation": 1,
    "creationTimestamp": "2018-09-25T06:02:00Z",
    "annotations": {
      "kubernetes.io/ingress.class": "traefik"
    }
  },
  "spec": {
    "tls": [
      {
        "hosts": [
          "myapp-82.sm.k8s.dev.myapp.io"
        ],
        **"secretName": "myapp-82.sm.k8s.dev.myapp.io.tls"**
      }
    ],
    "rules": [
      {
        "host": "myapp-82.sm.k8s.dev.myapp.io",
        "http": {
          "paths": [
            {
              "backend": {
                "serviceName": "myapp-web",
                "servicePort": 80
              }
            }
          ]
        }
      }
    ]
  },
  "status": {
    "loadBalancer": {}
  }
}
```
### Traefik Service Configuration
```json
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "traefik",
    "namespace": "traefik",
    "selfLink": "/api/v1/namespaces/traefik/services/traefik",
    "uid": "a8978ab5-c07f-11e8-9466-00505623bd42",
    "resourceVersion": "250107",
    "creationTimestamp": "2018-09-25T04:58:35Z",
    "labels": {
      "app": "traefik",
      "chart": "traefik-1.43.0",
      "heritage": "Tiller",
      "release": "traefik"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 80,
        "targetPort": "http",
        "nodePort": **30548**
      },
      {
        "name": "https",
        "protocol": "TCP",
        "port": 443,
        "targetPort": 443,
        "nodePort": **31946**
      },
      {
        "name": "metrics",
        "protocol": "TCP",
        "port": 8080,
        "targetPort": "dash",
        "nodePort": 31746
      }
    ],
    "selector": {
      "app": "traefik",
      "release": "traefik"
    },
    "clusterIP": "10.103.139.201",
    "type": "LoadBalancer",
    "sessionAffinity": "None",
    "externalTrafficPolicy": "Cluster"
  },
  "status": {
    "loadBalancer": {}
  }
}
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
debug = true
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[kubernetes]
[api]
  entryPoint = "traefik"
  dashboard = true
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
```
