### ISSUE TITLE
Bug: accept4: too many open files

### ISSUE THREAD

**Issue by Poeschl** [containous/traefik#3933]
Unfortunately, the `to many open files` of #1322 is still a thing.
Tonight the traefik on a prod environment showed us tones of this log:

```
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 5ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 10ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 20ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 40ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 80ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 160ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 320ms"
time="2018-09-25T23:04:33Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 640ms"
time="2018-09-25T23:04:34Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:35Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:36Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:37Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:38Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:39Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:40Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:41Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
time="2018-09-25T23:04:42Z" level=debug msg="http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s"
```
Until the container runs out of its memory.
At that time we had just a low load with around 85 Requests/min.

![image](https://user-images.githubusercontent.com/5469257/46063571-86aed180-c16d-11e8-929c-b8ab850088b5.png)
The red line is the RAM soft-limit of 32MB

### What version of Traefik are you using (traefik version)?
version: we use the official `traefik:1.6.4-alpine` docker image.

### What is your environment & configuration (arguments, toml...)?

```toml
# traefik.toml
logLevel = "DEBUG"
#traefikLogsFile = "/log/traefik.log"
defaultEntryPoints = ["http", "https"]

[accessLog]

# Web configuration backend
[web]
address = ":8080"
[web.auth.basic]
users = ["admin:$2a$12$E8bd5WdgnNxGFo6z3k/zV.zz8In9/Oa/mBDf/p4oHDWcl.2sydaU6"]

# Docker configuration backend
[docker]
watch = true
exposedbydefault = false

#Entrypoints
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/traefik/cert.pem"
      KeyFile = "/etc/traefik/key.unencrypted.pem"

[acme]
email = "******@pixel.de"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
#onDemand = true
acmeLogging = true
#OnHostRule = true

[acme.httpChallenge]
  entrypoint = "http"

```
This config contains some obfuscated data and the backends are configured inside of their docker config.
