### ISSUE TITLE
Consul Catalog: Traefik doesnt recover from comm error with Consul

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#3944]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
We've noticed Traefik containing an outdated configuration on several occasions. We haven't been able to identify the problem before, but yesterday we experienced that two instances which should be identical were running with different config, and were able to dig in a little bit.

On the "outdated" node, we can see this error:
```
{"error":"Unexpected response code: 500 (rpc error making call: EOF)","level":"error","msg":"Failed to fetch details of logstash-prod-beat-app-log-nonprod","time":"2018-09-24T06:50:24Z"}
{"error":"Unexpected response code: 500 (rpc error making call: EOF)","level":"error","msg":"Failed to retrieve health checks","time":"2018-09-24T06:50:24Z"}
```

After this entry, it looks like Traefik completely stops attempting to reload/listen to changes in Consul, leaving it with a stale config. On the "other" node, we can see multiple "config reloads".

This aligns well with troubleshooting we've done in the past, where we've seen that even restarting Consul fails to trigger Traefik to reload its configuration. This fact combined with what we're seeing in the current issue leads me to believe that Traefik completely stops communicating with Consul when this issue occurs.

### What did you expect to see?
We need to figure out why Consul is throwing 500s, but we're very concerned with the fact that Traefik doesn't seem to gracefully recover. I guess I'd expect Traefik to go into a retrying state.

### What did you see instead?
Traefik seems to "hang up" on Consul, leaving it in a completely disconnected state.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Traefik 1.6.3 on Ubuntu 16.04 LTS
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
checkNewVersion = false
ProvidersThrottleDuration = "5s"
logLevel = "INFO"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"
  format = "json"

[accessLog]
filePath = "/var/log/traefik/access.log"
format = "json"

defaultEntryPoints = ["http"]
[entryPoints]
    [entryPoints.httpredirect]
    address = ":81"
    [entryPoints.http]
    address = ":80"

[web]
address = ":8080"
[web.metrics.datadog]
address = "localhost:8125"
pushinterval = "10s"

[consulCatalog]
constraints = ["tag==environment:prod","tag==lb_id:external-api01"]
watch = true
endpoint = "127.0.0.1:8500"
exposedByDefault = false


[lifeCycle]
  requestAcceptGraceTimeout = "30s"
  graceTimeOut = "15s"
```
