### ISSUE TITLE
UseBindPortIP on swarm mode ? (vs publishing on host port)

### ISSUE THREAD

**Issue by nsteinmetz** [containous/traefik#3960]
Asked [here](https://traefik.slack.com/archives/C355DDFFG/p1538038317000100)

### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to test useBindortIP to avoid having the container publishing port in host mode but rather in ingress mode.

* Question 1 : is the variable `usebindportip` or `useBindortIP` ? Cf https://github.com/containous/traefik/blob/master/docs/configuration/backends/docker.md#L65 vs https://github.com/containous/traefik/search?utf8=%E2%9C%93&q=usebindportip
* Question 2 : The variable is not mentionned in the docker swarm part of the docker backend. Does it mean it's not available in the swarm mode ?
* Question 3 : Using useBindPortIP (lower or camel case) with ingress mode will provide the IP of the traefik interal IP and not the external one.

Steps to reproduce:

Output of my nginx log server:

With `mode:host`, without `useBindPortIP`, you see the header set to my LAN IP (10.251.0.100)

```
# From my LAN
web_web.1.dxe3rxefxdin@picocluster4    | 10.0.8.9 - - [28/Sep/2018:14:28:01 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:62.0) Gecko/20100101 Firefox/62.0" "10.251.0.100"
# From outside 
web_web.1.dxe3rxefxdin@picocluster4    | 10.0.8.9 - - [28/Sep/2018:14:31:28 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:62.0) Gecko/20100101 Firefox/62.0" "151.127.XXX.XXX"
```

Same with `mode:ingress` and `useBindPortIP=true`:

```
# From LAN
web_web.1.dxe3rxefxdin@picocluster4    | 10.0.8.12 - - [28/Sep/2018:14:40:01 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:62.0) Gecko/20100101 Firefox/62.0" "10.255.0.2"
# From external access
web_web.1.dxe3rxefxdin@picocluster4    | 10.0.8.12 - - [28/Sep/2018:14:40:25 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:62.0) Gecko/20100101 Firefox/62.0" "10.255.0.2"
```

10.0.8.x = network where my nginx container is deployed
10.255.0.2 is the IP of the traefik container.

`traefik/docker-compose.yml`

```yaml
cat compose/docker-compose.yml
version: '3.2'
services:
  traefik:
    image: traefik:1.6.6
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress (or host depending on test)
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress (or host depending on test)
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/me/traefik/conf/traefik.toml
        target: /traefik.toml
    networks:
      - traefik-net
networks:
  traefik-net:
    driver: overlay
    attachable: true
```

`conf/traefik.toml`

```toml
defaultEntryPoints = ["http", "https"]

logLevel = "ERROR"

# Disable certs validation as traefik will use IP to connect containres instead of hostnames, which will never validate.
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik"
watch = true
exposedByDefault = true
swarmMode = true
useBindPortIP = true (or not mentionned depending on tests)
```

and `nginx/docker-compose.yml`

```yaml
version: '3.2'
services:
  web:
    image: nginx:stable-alpine
    deploy:
      labels:
        traefik.docker.network: "web"
        traefik.frontend.rule: "Host:picocluster1.xxx.lan,picocluster1.home.xxx.fr"
        traefik.frontend.entryPoints: "http,https"
        traefik.port: "80"
        traefik.protocol: "http"
        traefik.frontend.passHostHeader: "true"
    networks:
      - web
networks:
  web:
    driver: overlay
```

### What did you expect to see?

I expected to see my computer IP from LAN or my public IP from outside.

### What did you see instead?

The IP of traefik container in the traefik network.
