### ISSUE TITLE
Operation timeout randomly

### ISSUE THREAD

**Issue by psychonetic** [containous/traefik#3969]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have setup traefik on kubernetes cluster running in gke. 
My configs:
```yml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: default
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: traefik-ingress-controller
      volumes:
        - name: config
          configMap:
            name: traefik-config
      containers:
      - image: traefik
        name: traefik-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/config"
            name: "config"
        ports:
        - name: admin
          containerPort: 8080
          hostPort: 8080
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        args:
        - --web
        - --kubernetes
        - --logLevel=DEBUG
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: admin
      protocol: TCP
      port: 8080
```
```yml
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: default
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: 8080
```

### What did you expect to see?
Having no problems, when accessing my services and also the dashboard. 

### What did you see instead?
Sometimes, like every second or third request traefik does not respond and I get a operation timeout. 
This happens to all my services and also to the dashboard of traefik. There aren't any special logs or events, which give me a clue why this happens. This issue happens when using the browser, curl, postman etc. So it's definitely an issue with traefik (or my configuration). The service to service communications works as expected, when sending requests within the cluster to service-name.namespace.cluster.local. So kubernetes works as expected.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [kubernetes]
    [kubernetes.ingressEndpoint]
        publishedService = "default/traefik-ingress-controller
```
