### ISSUE TITLE
Upgrade vom 1.6.0-RC6 to 1.7.X doesn't work

### ISSUE THREAD

**Issue by MichaelF25** [containous/traefik#3970]
### What did you do?
Upgraded traefik from 1.6.0-RC6 to 1.7.0 (tried also 1.7.1)

### What did you expect to see?
Running traefik with rules from separate `rules.toml` file as it was with 1.6.0-RC6 

### What did you see instead?
No running traefik at all. After changing startup parameter --config**F**ile to --config**f**ile, startup worked but no providers were found.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
`/usr/local/bin/traefik --configFile=/etc/traefik/traefik.toml`

```toml
# ...

[file]
  filename = "/etc/traefik/rules.toml"
  watch = true
```
rules.toml:

```toml
[backends]
  [backends.first]
    [backends.first.servers.default]
      url = "http://localhost:81"

# ...

[frontends]
  [frontends.first]
    passHostHeader = true
    whitelistSourceRange = ["192.168.0.0/16", "10.0.0.0/8"]
    backend = "first"
    [frontends.first.routes]
      [frontends.first.routes.default]
        rule = "Host:first.local"
```
