### ISSUE TITLE
Kubernetes Ingress: Buffering annotation is not recognised.

### ISSUE THREAD

**Issue by Flyffies** [containous/traefik#3972]
### Do you want to request a *feature* or report a *bug*?

(Potential) Bug

### What did you do?

I tried to configure buffering for an Kubernetes Ingress.

### What did you expect to see?

The buffering annotation getting recognised and applied.

### What did you see instead?

Nothing, no error in the log, nothing in the dashboard.
I tried removing "traefik" from the annotation. I added it back, tried different things I found online.
Traefik does not seem to notice the annotation at all.
And the documentation was not very percise how it should be configured correctly, it only dokuments that the annotation exists.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik docker container 1.7.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```
Kubernetes Ingress Annotation
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/buffering: |
      maxrequestbodybytes: 10485760
      memrequestbodybytes: 2097153
      maxresponsebodybytes: 10485761
      memresponsebodybytes: 2097152
      retryexpression: IsNetworkError() && Attempts() <= 2
    kubernetes.io/ingress.class: traefik
```

**Comment by jbdoumenjou** [comment]
Hi @Flyffies , 
We think that your problem is in your yaml configuration file because we tested this option here https://github.com/containous/traefik/blob/v1.7/provider/kubernetes/kubernetes_test.go#L908 
Could you use https://yaml-multiline.info/ and double check your configuration?

**Comment by Flyffies** [comment]
Hi @jbdoumenjou,
I put my YAML through a yaml validator, and it is valid. The multiline part gets read correct.
However, the newlines get converted into '\n's. Maybe they dont get read correctly when inside the annotation? I extracted the annottion and ran it through the validator as well. When replacing the \n with a newline it was also valid...

I just get it to work and the log contains nothing...

**Comment by ldez** [comment]
could try:
```yml
    traefik.ingress.kubernetes.io/buffering: |-
      maxrequestbodybytes: 10485760
      memrequestbodybytes: 2097153
      maxresponsebodybytes: 10485761
      memresponsebodybytes: 2097152
      retryexpression: IsNetworkError() && Attempts() <= 2
```
