### ISSUE TITLE
1.7.1 failed to generate wildcard with base domain as SAN (with Gandiv5 api key)

### ISSUE THREAD

**Issue by ylbeethoven** [containous/traefik#3977]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I've got a new domain from Gandi.net using gandiv5 api key to test if traefik can generate a wildcard with base domain as SAN.

### What did you expect to see?
I expect the certificate can be generated successfully.

### What did you see instead?
I can see a DNS record being created, but it seems that treafik failed to verified hence the certificate could not be issued.

Here is the entry from Gandi
`_acme-challenge	TXT	300	"CgZfMkwMxPE8CH4tOWrR6Lgr2rrnKZ0qW7vV_Q398v8"`

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker version 1.7.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here is Traefik.toml file
```toml
debug = true

defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "admin@aufomm.pw"
storage = "acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "gandiv5" 
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.aufomm.pw"
  sans = ["aufomm.pw"]
```

Provider : Google Cloud Instance in Singapore
OS : Debian 9

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-10-04T06:29:08Z" level=debug msg="Using DNS Challenge provider: gandiv5"
time="2018-10-04T06:45:12Z" level=debug msg="Serving default cert for request: \"traefik.aufomm.pw\""
time="2018-10-04T06:45:13Z" level=debug msg="Serving default cert for request: \"traefik.aufomm.pw\""
time="2018-10-04T06:45:13Z" level=debug msg="http2: server: error reading preface from client 113.29.30.137:52853: remote error: tls: bad certificate"
time="2018-10-04T06:45:13Z" level=debug msg="http2: server: error reading preface from client 113.29.30.137:34382: remote error: tls: bad certificate"
time="2018-10-04T06:49:31Z" level=error msg="Error obtaining certificate retrying in 387.776384ms"
time="2018-10-04T07:09:53Z" level=error msg="Error obtaining certificate: acme:Error -> One or more domains had a problem:\n[aufomm.pw] Time limit exceeded. Last error: NS ns-231-b.gandi.net. did not return the expected TXT record\n"
time="2018-10-04T07:09:53Z" level=error msg="Unable to obtain ACME certificate for domains \"*.aufomm.pw,aufomm.pw\" : unable to generate a certificate for thedomains [*.aufomm.pw aufomm.pw]: acme: Error -> One or more domains had a problem:\n[aufomm.pw] Time limit exceeded. Last error: NS ns-231-b.gandi.net. did notreturn the expected TXT record\n"
```
