### ISSUE TITLE
Frequent "Server configuration reloaded on" with no obvious reason

### ISSUE THREAD

**Issue by Fabian-K** [containous/traefik#3980]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I´m using traefik as a kubernetes ingress controller. 

### What did you expect to see?

Traefik configuration is only reloaded when there is a change in the cluster

### What did you see instead?

Config reloads every few seconds
```
time="2018-10-04T13:43:02Z" level=info msg="Server configuration reloaded on :443"
time="2018-10-04T13:43:04Z" level=info msg="Server configuration reloaded on :80"
time="2018-10-04T13:43:04Z" level=info msg="Server configuration reloaded on :443"
time="2018-10-04T13:43:06Z" level=info msg="Server configuration reloaded on :80"
time="2018-10-04T13:43:06Z" level=info msg="Server configuration reloaded on :443"
time="2018-10-04T13:43:10Z" level=info msg="Server configuration reloaded on :80"
time="2018-10-04T13:43:10Z" level=info msg="Server configuration reloaded on :443"
time="2018-10-04T13:43:12Z" level=info msg="Server configuration reloaded on :443"
time="2018-10-04T13:43:12Z" level=info msg="Server configuration reloaded on :80"
time="2018-10-04T13:43:14Z" level=info msg="Server configuration reloaded on :80"
 ```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Official docker image
```
Version:      v1.7.1
Codename:     maroilles
Go version:   go1.11
Built:        2018-09-28_10:24:34PM
OS/Arch:      linux/amd64
```

I had the same issue with 1.6.6.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[traefikLog]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
ingressClass = "traefik"
[accessLog]
format = "json"
  [accessLog.fields]
  defaultMode = "drop"
  [accessLog.fields.names]
    "RequestHost" = "keep"
    "Duration" = "keep"
    "RequestMethod" = "keep"
    "RequestPath" = "keep"
    "RequestContentSize" = "keep"
    "DownstreamStatus" = "keep"
    "StartUTC" = "keep"
    "ClientHost" = "keep"
  [accessLog.fields.headers]
    defaultMode = "drop"
    [accessLog.fields.headers.names]
      "User-Agent" = "keep"
```

Here is an example of my ingress definitions
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/error-pages: |-
      specific:
        status:
        - "404"
        - "429"
        backend: error.domain.de
        query: "/{status}.html"
      fallback:
        status:
        - "500-599"
        backend: error.domain.de
        query: "/5xx.html"
    traefik.ingress.kubernetes.io/rate-limit: |-
      extractorfunc: client.ip
      rateset:
        default:
          period: 30s
          average: 300
          burst: 450
  name: ing-homepage
  namespace: default
spec:
  rules:
  - host: www.domain.de
    http:
      paths:
      - backend:
          serviceName: svc-homepage
          servicePort: 80
  tls:
  - hosts:
    - www.domain.de
    secretName: sec-homepage-domain-tls
```
