### ISSUE TITLE
Error while closing Hijacked conn

### ISSUE THREAD

**Issue by rinokadijk** [containous/traefik#3993]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Something triggered a reload.

### What did you expect to see?

No error

AND

Marathon provider is available after reload

### What did you see instead?

{"level":"error","msg":"Error while closing Hijacked conn: close tcp *.*.*.*:80-\u003e*.*.*.*:59596: use of closed network connection","time":"2018-10-08T18:12:07+02:00"}

AND

Marathon provider is not available after reload

### Output of `traefik version`: Version:      v1.7.0 Codename:     maroilles

```
{"level":"info","msg":"Skipping same configuration for provider marathon","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"Server configuration reloaded on :8099","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"Server configuration reloaded on :6565","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"Server configuration reloaded on :8001","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"Server configuration reloaded on :80","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"Server configuration reloaded on :443","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"Skipping same configuration for provider marathon","time":"2018-10-08T18:11:48+02:00"}
{"level":"info","msg":"I have to go...","time":"2018-10-08T18:11:57+02:00"}
{"level":"info","msg":"Stopping server gracefully","time":"2018-10-08T18:11:57+02:00"}
{"level":"error","msg":"Error while closing Hijacked conn: close tcp *.*.*.*:80-\u003e*.*.*.*:59596: use of closed network connection","time":"2018-10-08T18:12:07+02:00"}
{"level":"info","msg":"Server stopped","time":"2018-10-08T18:12:07+02:00"}
{"level":"info","msg":"Shutting down","time":"2018-10-08T18:12:07+02:00"}
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

debug = true

logLevel = "INFO"

checkNewVersion = false

[api]
entryPoint = "api"

[entryPoints]
    [entryPoints.http]
    address = ":80"

    [entryPoints.https]
    address = ":443"

    [entryPoints.api]
    address = ":8099"

    [entryPoints.grpc]
    address = ":6565"

    [entryPoints.ping]
    address = ":8001"

[retry]

[marathon]
    endpoint = "http://localhost:8080"
    domain = "marathon.localhost"
    exposedbydefault = true
    respectReadinessChecks = true

[tracing]
    backend = "zipkin"
    serviceName = "traefik"

    [tracing.zipkin]
        sameSpan = false
        id128Bit = true

[accessLog]
    filePath = "access.log"
    format = "json"

[traefikLog]
  filePath = "traefik.log"
  format   = "json"

[ping]
  entryPoint = "ping"

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
not running debug and not able to reproduce 
```
