### ISSUE TITLE
DNS-01 fails with Cloudflare provider and .pw ccTLD

### ISSUE THREAD

**Issue by tobiebooth** [containous/traefik#3994]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured Traefik to proxy content for subdomains of a .pw domain I own using DNS-01 validation configured with my Cloudflare credentials.

### What did you expect to see?

A valid certificate generated and provided when visiting the domain.

### What did you see instead?

`Unable to obtain ACME certificate for domains \"lychee.56k.pw\" detected thanks to rule \"Host:Lychee.56k.pw\" : unable to generate a certificate for the domains [lychee.56k.pw]: acme: Error -> One or more domains had a problem:\n[lychee.56k.pw] error presenting token: cloudflare: zone pw. not found for domain _acme-challenge.lychee.56k.pw.`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.2
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-04_01:44:36PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[docker]
domain = "56k.pw"
watch = true
exposedbydefault = false
[acme]
acmeLogging = true
email = "xxx"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
[acme.dnsChallenge]
provider = "cloudflare"
[[acme.domains]]
main = "*.56k.pw"
sans = ["56k.pw"]
```
