### ISSUE TITLE
Panic in http handler: invalid memory address or nil pointer dereference using buffering annotation on service object in kubernetes

### ISSUE THREAD

**Issue by oivindoh** [containous/traefik#4005]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Trying to use [Buffering](https://docs.traefik.io/configuration/commons/#buffering) to keep oversized request bodies out of my backend services, using Traefik 1.7.2 (alpine and non-alpine images).

Running in Kubernetes 1.10.4 on Azure (not AKS).

### What did you expect to see?

- GET requests to this ingress should go through as long as the request body is less than 8B.
- GET requests to this ingress should be rejected if request body is greater than 8B.

### What did you see instead?

- GET requests to this ingress without a request body lead to panic in traefik: `Recovered from panic in http handler: runtime error: invalid memory address or nil pointer dereference`
- GET requests to this ingress with a request body greater than 8B get rejected as expected.

Here I'm using httpie to generate three requests to a simple python service that should just repeat request data and headers to the client when serving a GET request:

No body data - causes http 500 to be returned to the client:

```console
$ http GET https://oho.domain.com/api/k8s/body
HTTP/1.1 500 Internal Server Error
Content-Length: 22
Content-Type: text/plain; charset=utf-8
Date: Wed, 10 Oct 2018 08:59:32 GMT
Vary: Accept-Encoding
X-Content-Type-Options: nosniff

Internal Server Error
```

Adding file larger than 8B to body:

```console
$ http GET https://oho.domain.com/api/k8s/body < largerfile.txt
HTTP/1.1 413 Request Entity Too Large
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Date: Wed, 10 Oct 2018 08:59:36 GMT
Vary: Accept-Encoding

Request Entity Too Large
```

Sending file smaller than 8B:

```console
$ http GET https://oho.domain.com/api/k8s/body < smallfile.txt
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 486
Content-Type: application/json
Date: Wed, 10 Oct 2018 08:59:45 GMT
Server: 0.0.0.0
Strict-Transport-Security: max-age=15553000
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{
    "request.data": "sadasd\n",
    "request.headers": {
        "Accept": "application/json, */*",
        "Accept-Encoding": "gzip, deflate",
        "Content-Length": "7",
        "Content-Type": "application/json",
        "Host": "oho.domain.com",
        "User-Agent": "HTTPie/0.9.9",
        "X-Forwarded-For": "8.8.8.8",
        "X-Forwarded-Host": "oho.domain.com",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Prefix": "/api",
        "X-Forwarded-Proto": "https",
        "X-Forwarded-Server": "traefik-ingress-controller-86949d84c5-p9m8w",
        "X-Real-Ip": "8.8.8.8"
    }
}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      v1.7.2
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-04_01:44:36PM
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.10.4 on Azure. Traefik fronted by a LoadBalancer service object.

Backend service object:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "5555"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    traefik.ingress.kubernetes.io/buffering: |
      maxrequestbodybytes: 8
  labels:
    app: frontend
    appComponent: api
    environment: oho
    helm-app: frontend-oho
  name: frontend-oho-api
  namespace: oho
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 5555
  selector:
    app: frontend
    appComponent: api
    environment: oho
  sessionAffinity: None
  type: ClusterIP
```

Ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/hsts-max-age: "15553000"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rate-limit: |-
      extractorfunc: client.ip
      rateset:
        protectourselves:
          period: 2s
          average: 50
          burst: 150
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  labels:
    helm-app: frontend-oho
  name: ingress-api-traefik
  namespace: oho
spec:
  rules:
  - host: oho.domain.com
    http:
      paths:
      - backend:
          serviceName: frontend-oho-api
          servicePort: 80
        path: /api
  tls:
  - hosts:
    - oho.domain.com
    secretName: oho-domain.com
```

configmap mounted in traefik container:

```yaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    traefik.toml: |
      # traefik.toml
      logLevel = "DEBUG"
      debug = false
      sendAnonymousUsage = true
      defaultEntryPoints = ["http","https"]

      [entryPoints]
        [entryPoints.http]
          address = ":80"
          compress = true
          [entryPoints.http.redirect]
            regex = "^http://(.*)"
            replacement = "https://$1"
          [entryPoints.http.forwardedHeaders]
            trustedIPs = ["127.0.0.1/32"]
        [entryPoints.https]
          address = ":443"
          compress = true
          [entryPoints.https.forwardedHeaders]
            trustedIPs = ["127.0.0.1/32"]
          [entryPoints.https.tls]
            # Exclude old tls versions, whitelist known still-strong cipher suites
            minVersion = "VersionTLS12"
            cipherSuites = [
              "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
              "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
              "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
              "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
            ]
        [entryPoints.httpn]
          address = ":8880"
          compress = true
      [kubernetes]

      [traefikLog]

      [accessLog]

      [metrics]
        [metrics.prometheus]
        [metrics.statistics]

      [ping]

      [api]

      [retry]
        attempts = 2
  kind: ConfigMap
  metadata:
    name: traefik-config
    namespace: ingress
```

Traefik pod:

```yaml
```apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      checksum/config: bd0bd0dafbb6f0ae3b471f35e0c73750f887121d0494eee81fb55a2e25520459
      cni.projectcalico.org/podIP: 10.244.7.111/32
    labels:
      name: traefik-ingress-controller
    name: traefik-ingress-controller-86949d84c5-p9m8w
    namespace: ingress
  spec:
    containers:
    - args:
      - --configfile=/config/traefik.toml
      image: traefik:1.7.2-alpine
      imagePullPolicy: Always
      name: traefik-ingress-controller
      ports:
      - containerPort: 80
        name: http
        protocol: TCP
      - containerPort: 443
        name: https
        protocol: TCP
      - containerPort: 8880
        name: httpn
        protocol: TCP
      - containerPort: 8080
        name: dashboard
        protocol: TCP
      volumeMounts:
      - mountPath: /config
        name: config
        readOnly: true
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    volumes:
    - configMap:
        defaultMode: 420
        name: traefik-config
      name: config
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-10-10T09:02:44Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-10-10T09:02:44Z" level=debug msg="vulcand/oxy/buffer: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/body\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Connection\":[\"keep-alive\"],\"User-Agent\":[\"HTTPie/0.9.9\"],\"X-Forwarded-Prefix\":[\"/api\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"oho.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"8.8.8.8:54802\",\"RequestURI\":\"/k8s/body\",\"TLS\":null}"
time="2018-10-10T09:02:44Z" level=debug msg="vulcand/oxy/buffer: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/body\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Connection\":[\"keep-alive\"],\"User-Agent\":[\"HTTPie/0.9.9\"],\"X-Forwarded-Prefix\":[\"/api\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"oho.domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"8.8.8.8:54802\",\"RequestURI\":\"/k8s/body\",\"TLS\":null}"
time="2018-10-10T09:02:44Z" level=error msg="Recovered from panic in http handler: runtime error: invalid memory address or nil pointer dereference"
time="2018-10-10T09:02:45Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"

```
