### ISSUE TITLE
Traefik Using Rancher API is Unable to See Rancher Sidekick Containers

### ISSUE THREAD

**Issue by WilliamMiceli** [containous/traefik#4029]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When using Traefik on Docker with the Rancher API provider, Traefik does not seem to be able to detect sidekick containers, only the primary ones.

For example, the docker-compose I was using:
https://github.com/WilliamMiceli/Personal-Rancher-Catalog/blob/master/templates/InvoiceNinja/0/docker-compose.yml
The Nginx container is a sidekick and never shows up in the Traefik logs for having detected it, and so no frontend/backend is created.

When I change it so that Nginx container is the primary, it works.
Example:
https://github.com/WilliamMiceli/Personal-Rancher-Catalog/blob/master/templates/InvoiceNinja-TraefikFix/0/docker-compose.yml

### What did you expect to see?

A frontend/backend be created for the Nginx container that was a Rancher Sidekick to the main service.

### What did you see instead?

Nothing would happen as if it was never launched and only able to see the primary container.

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.7.2/Maroilles

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
################################################################
#Logging
################################################################

logLevel = "INFO"   # "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"

################################################################
#Entry Points
################################################################

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]


################################################################
#ACME
################################################################

[acme]
email = "<redacted>"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

acmeLogging = true

################################################################
#Rancher Provider
################################################################

[rancher]
domain = "rancher.localhost"
watch = true
exposedByDefault = false
enableServiceHealthFilter = true

##########################
[rancher.api]
##########################

endpoint = "<redacted>"
accessKey = "<redacted>"
secretKey = "<redacted>"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Will paste if requested, will take some time to get.
