### ISSUE TITLE
Config hot-reload for acme.domains not working

### ISSUE THREAD

**Issue by gbhrdt** [containous/traefik#4039]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured Let's Encrypt with acme.domains like here: https://docs.traefik.io/configuration/acme/

### What did you expect to see?

When I modify `traefik.toml` and add new `acme.domains`, I expect traefik to hot reload them and generate LE certificates.
We have a big list of domains from our customers and provide hosting from them so we need to dynamically change the acme.domains. We do not use Docker Service Labels, so `onHostRule` is not an option for us.
We were using `onDemand` before, but it is deprecated and was generating many unused certificates for subdomains when they were only requested once.

### What did you see instead?

Nothing happens, only after a restart certificates are being generated.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We use Docker Swarm.

```toml
defaultEntryPoints = ["https","http"]

[file]
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/certs/example.com.crt"
    keyFile = "/certs/example.com.key"

[acme]
email = "support@example.com"
storage = "/certs/acme.json"
entryPoint = "https"
acmeLogging = true

[[acme.domains]]
main = "example1.com"
sans = ["www.example1.com"]
[[acme.domains]]
main = "example2.com"
sans = ["www.example2.com"]
```
