### ISSUE TITLE
ingress-weight: have service weights across services on different namespacs

### ISSUE THREAD

**Issue by tasdikrahman** [containous/traefik#4043]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Having service weights on services across namespaces

for example 
```
metadata:
  name: stage-ingress
  namespace: stage
  annotations:
    traefik.ingress.kubernetes.io/service-weights: |
      api: 90%
      api-canary: 10%
```

is what would work in a case where both the services are on the same namespace, but is there a way to do it on services on different namespaces

docs: https://docs.traefik.io/configuration/backends/kubernetes/
