### ISSUE TITLE
passTLSCert doesn't forward client certificate in Kubernetes

### ISSUE THREAD

**Issue by Oblynx** [containous/traefik#4048]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I evaluated the resolution of issue #3052 in Kubernetes by following a similar test to the original reporter. Having set up traefik as a Kubernetes Ingress, I tried:

1. curl with a custom client certificate
2. backend is a golang server that dumps the HTTP request (made after the example in the #3052 )

### What did you expect to see?

According to #3826 , I expected the backend to see an HTTP header `X-Forwarded-Ssl-Client-Cert`, or in any case the client's certificate in the header.

### What did you see instead?

```console
$ curl --insecure https://cert-experiments.cern.ch/ -H 'Host: server'  --cacert certs/ca/crt.pem --cert certs/cli/crt.pem --key certs/cli/key.pem
cert/subject: CN=cert-experiments.cern.ch,O=my AWESOME org,C=ch (15392751396577182173)
GET / HTTP/1.1
Host: server
Accept: */*
Accept-Encoding: gzip
User-Agent: curl/7.58.0
X-Forwarded-For: 128.141.194.164
X-Forwarded-Host: server
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: cert-experiments-3eenymnvlt3a-minion-0.cern.ch
X-Real-Ip: 128.141.194.164
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.2
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-04_01:44:36PM
OS/Arch:      linux/amd64
```

#### Traefik config

Traefik is deployed as a daemonset.

* Image: registry.hub.docker.com/library/traefik:v1.7.2-alpine
* config: arguments:
```
        - --debug
        - --api
        - --kubernetes
        - --logLevel=DEBUG
        - --entrypoints=Name:http Address::80
        - --entrypoints=Name:https Address::443 TLS:/app/certs/srv/crt.pem,/app/certs/srv/key.pem
          CA:/app/certs/ca/crt.pem
        - --kubernetes.enablepasstlscert=true
```

#### Ingress

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "https"
    traefik.ingress.kubernetes.io/pass-tls-cert: "true"
    #ingress.kubernetes.io/passTLSClientCert: "true"
    #traefik.frontend.passTLSClientCert.pem: "true"
...
```

#### Certificates

I created a custom CA and derived from it a server and client certificate.

#### Backend server code

```go
package main

import (
  "crypto/tls"
  "crypto/x509"
  "fmt"
  "io/ioutil"
  "net/http"
  "net/http/httputil"
)

func main() {
  caCert, _ := ioutil.ReadFile("/app/certs/ca/crt.pem")
  caPool := x509.NewCertPool()
  caPool.AppendCertsFromPEM(caCert)

  tlsConfig := &tls.Config{
    ClientAuth: tls.RequireAndVerifyClientCert,
    ClientCAs:  caPool,
  }
  tlsConfig.BuildNameToCertificate()

  http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
    reqDump, _ := httputil.DumpRequest(req,true)

    fmt.Fprintf(
      w,
      "cert/subject: %v (%d)\n",
      req.TLS.PeerCertificates[0].Subject,
      req.TLS.PeerCertificates[0].SerialNumber,
    )

    fmt.Fprintf(
      w,
      string(reqDump),
    )
  })

  httpServer := &http.Server{
    Addr:      ":8080",
    TLSConfig: tlsConfig,
  }

  httpServer.ListenAndServeTLS(
    "/app/certs/server/crt.pem",
    "/app/certs/server/key.pem",
  )
}
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Complete log attached. Snippets:

```
time="2018-10-15T13:38:41Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":true,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":null,\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":[{\"CertFile\":\"/app/certs/srv/crt.pem\",\"KeyFile\":\"/app/certs/srv/key.pem\"}],\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":[\"/app/certs/ca/crt.pem\"],\"Optional\":false},\"DefaultCertificate\":{\"CertFile\":\"/app/certs/srv/crt.pem\",\"KeyFile\":\"/app/certs/srv/key.pem\"},\"SniStrict\":false},\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"Web\":null,\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":true,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null},\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":true,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":null,\"HostResolver\":null}"
```

```
time="2018-10-15T13:38:41Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"cert-experiments.cern.ch/gb\":{\"servers\":{\"ircrelay-glowingbear-744bc84b9d-5ll62\":{\"url\":\"http://10.100.30.5:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"cert-experiments.cern.ch/traefik-ui\":{\"servers\":{\"ingress-traefik-ghdmc\":{\"url\":\"http://188.184.91.175:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"cert-experiments.cern.ch/weechat\":{\"servers\":{\"ircrelay-weechat-6585bbcfff-zqbp6\":{\"url\":\"http://10.100.30.14:9000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"server\":{\"servers\":{\"server-app\":{\"url\":\"https://10.100.30.15:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"cert-experiments.cern.ch/gb\":{\"entryPoints\":[\"https\"],\"backend\":\"cert-experiments.cern.ch/gb\",\"routes\":{\"/gb\":{\"rule\":\"PathPrefixStrip:/gb\"},\"cert-experiments.cern.ch\":{\"rule\":\"Host:cert-experiments.cern.ch\"}},\"passHostHeader\":true,\"passTLSCert\":true,\"priority\":0,\"basicAuth\":null},\"cert-experiments.cern.ch/traefik-ui\":{\"entryPoints\":[\"https\"],\"backend\":\"cert-experiments.cern.ch/traefik-ui\",\"routes\":{\"/traefik-ui\":{\"rule\":\"PathPrefixStrip:/traefik-ui\"},\"cert-experiments.cern.ch\":{\"rule\":\"Host:cert-experiments.cern.ch\"}},\"passHostHeader\":true,\"passTLSCert\":true,\"priority\":0,\"basicAuth\":null},\"cert-experiments.cern.ch/weechat\":{\"entryPoints\":[\"https\"],\"backend\":\"cert-experiments.cern.ch/weechat\",\"routes\":{\"/weechat\":{\"rule\":\"PathPrefixStrip:/weechat\"},\"cert-experiments.cern.ch\":{\"rule\":\"Host:cert-experiments.cern.ch\"}},\"passHostHeader\":true,\"passTLSCert\":true,\"priority\":0,\"basicAuth\":null},\"server\":{\"entryPoints\":[\"https\"],\"backend\":\"server\",\"routes\":{\"server\":{\"rule\":\"Host:server\"}},\"passHostHeader\":true,\"passTLSCert\":true,\"priority\":0,\"basicAuth\":null}}}"
```

[traefik.log](https://github.com/containous/traefik/files/2478966/traefik.log)

**Comment by Oblynx** [comment]
Note: I used the traefik config argument ` - --kubernetes.enablepasstlscert=true` only as a last resort. I also tried without it in the beginning and the ingress that has the pass-tls-cert annotation is the only one that appears in the logs with `"passTLSCert":true,` (as it should be).

**Comment by traefiker** [comment]
Closed by #4118.

**Comment by rochaporto** [comment]
Hi.

This is still not working as far as i can tell.
```
kubectl -n kube-system exec ingress-traefik traefik version
traefik version
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64

kubectl -n kube-system exec ingress-traefik ps auxw
PID   USER     TIME  COMMAND
    1 root      0:08 traefik traefik --api --traefikLog=true --kubernetes --kubernetes.enablepasstlscert=true --logLevel=DEBUG --entrypoints=Name:http Address::80 --entrypoints=Name:https Address::443 TLS
```

TLS secret:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=passtlstest001.cern.ch"
kubectl  create secret tls go-headers-secret --key=tls.key --cert=tls.crt
```

Sample deployment and ingress:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-headers-deployment
spec:
  selector:
    matchLabels:
      app: go-headers
  replicas: 1
  template:
    metadata:
      labels:
        app: go-headers
    spec:
      containers:
      - name: go-headers
        image: go-headers
        ports:
        - containerPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-headers
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: https
    traefik.ingress.kubernetes.io/pass-client-tls-cert: |
      pem: true
      infos:
        notafter: true
        notbefore: true
        sans: true
        subject:
          country: true
          province: true
          locality: true
          organization: true
          commonname: true
          serialnumber: true
          domaincomponent: true
        issuer:
          country: true
          province: true
          locality: true
          organization: true
          commonname: true
          serialnumber: true
          domaincomponent: true
spec:
  rules:
  - host: passtlstest001.cern.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: go-headers
          servicePort: 8000
  tls:
   - secretName: go-headers-secret
```

If i take the above the logs look like (not sure where the example.com comes from?):
```
time="2019-02-12T22:31:42Z" level=debug msg="Wiring frontend passtlstest001.cern.ch/ to entryPoint https"
time="2019-02-12T22:31:42Z" level=debug msg="Creating backend passtlstest001.cern.ch/"
time="2019-02-12T22:31:42Z" level=debug msg="Adding TLSClientHeaders middleware for frontend passtlstest001.cern.ch/"
time="2019-02-12T22:31:43Z" level=debug msg="Creating load-balancer wrr"
time="2019-02-12T22:31:43Z" level=debug msg="Creating route passtlstest001.cern.ch Host:passtlstest001.cern.ch"
time="2019-02-12T22:31:43Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-02-12T22:31:43Z" level=debug msg="Wiring frontend traefik.example.com to entryPoint http"
time="2019-02-12T22:31:43Z" level=debug msg="Creating backend traefik.example.com"
time="2019-02-12T22:31:43Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com"
time="2019-02-12T22:31:43Z" level=error msg="failed to create the forwarder for frontend traefik.example.com: failed to create RoundTripper for frontend traefik.example.com: failed to create TLSClientConfig: no TLS provided. Skipping frontend traefik.example.com..."
time="2019-02-12T22:31:43Z" level=debug msg="Add certificate for domains passtlstest001.cern.ch"
```

And the TLS request seems to work ok:
```
echo | openssl s_client -showcerts -servername passtlstest001.cern.ch -connect passtlstest001.cern.ch:443 2>/dev/null  > ca.crt

curl --cacert ca.crt  https://passtlstest001.cern.ch
GET / HTTP/1.1 
Header field "X-Forwarded-For", Value ["<redacted>"]
Header field "X-Forwarded-Host", Value ["passtlstest001.cern.ch"]
Header field "X-Forwarded-Port", Value ["443"]
Header field "X-Real-Ip", Value ["<redacted>"]
Header field "User-Agent", Value ["curl/7.29.0"]
Header field "Accept", Value ["*/*"]
Header field "X-Forwarded-Proto", Value ["https"]
Header field "X-Forwarded-Server", Value ["<redacted>"]
Header field "Accept-Encoding", Value ["gzip"]
Host = "passtlstest001.cern.ch"
RemoteAddr= "10.100.50.1:42458"

Finding value of "Accept" ["*/*"]
```

But it's still missing the pass tls headers. Looking at the logs this looks wrong:
```
time="2019-02-12T22:34:54Z" level=warning msg="Try to extract certificate on a request without TLS"
time="2019-02-12T22:34:54Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"passtlstest001.cern.ch\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<redacted>:54616\",\"RequestURI\":\"/\",\"TLS\":null}"
```

The [relevant code](https://github.com/containous/traefik/blob/master/middlewares/passtlsclientcert/pass_tls_client_cert.go#L217) seems to indicate the TLS field in the request is being passed empty.

Should i keep this in this issue or you want me to open a new one?

Thanks.
