### ISSUE TITLE
Authentication not working properly (multiple login prompts)

### ISSUE THREAD

**Issue by MaartenMol96** [containous/traefik#4051]
### What did you do?
I have setup basic auth and digestauth. Both setups give no errors. But when I get the login prompt, I login, then the page begins to load and I have to login again every XX seconds. I want to login once, I have read all logs but I can't find anything why this is happening.

### What did you expect to see?
Login after first login and no more prompts

### What did you see instead?
Login prompts every XX seconds

ALSO: when clicking cancel on second or later prompts I get errors from the web application or css issues

EXCEPT: traefik authentication for treafik web interface, this works perfectly!

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
V1.7.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Default protocols for undefined rules
defaultEntryPoints = ["http", "https"]

# Skip backend SSL cert verification
InsecureSkipVerify = true

# Rules for metrics
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets=[0.1,0.3,1.2,5.0]

# Rules for API/Web interface
[api]
  dashboard = true
  debug = false
  [api.statistics]
    recentErrors = 10

# Rules for docker backend
[docker]
  exposedbydefault = false
  watch = true
  endpoint = "unix:///var/run/docker.sock"
  domain = "*****"

# Rules for protocols & redirection
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

# letsencrypt rules
[acme]
  email = "***"
#  caServer = "https://acme-staging.api.letsencrypt.org/directory"
  acmeLogging = true
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
```

One app from my docker-compose:

```
  compose-ui:
    image: francescou/docker-compose-ui
    container_name: compose-ui
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/compose:/opt/docker-compose-projects
    ports:
      - 5104:5000
    networks:
      - frontend
      - backend
    logging:
      driver: gelf
      options:
        gelf-address: udp://172.50.0.100:12201
        labels: com.docker.compose.project
    labels:
      - traefik.enable=true
      - traefik.backend=compose-ui
      - traefik.frontend.rule=Host:*****
      - traefik.docker.network=infrastack_backend
      - traefik.port=5000
      - traefik.frontend.auth.digest.usersFile=/auth.htdigest
```

**Comment by jbdoumenjou** [comment]
Hello @MaartenMol96 , thanks for your interest in the project!

Unfortunately I can’t reproduce your issue (you’ll see bellow my test-case for documentation purpose) which makes me believe what you see is related to your environment.

```
debug = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    # let the automagic self-signed certificate generation
    [entryPoints.https.tls]

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
```

```
version: '3.5'
services:

  rproxy:
    image: traefik:1.7.3-alpine
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro           # træfik static configuration
      - ./.htdigest:/etc/traefik/.htdigest:ro                 # digest auth user/password file
      - /var/run/docker.sock:/var/run/docker.sock             # So that traefik can listen to the Docker events
      - ./.htpasswd:/etc/traefik/.htpasswd:ro                 # basic auth user/password file
    ports:
      - '443:443'                                             # https port
      - '80:80'                                               # http port
      - '8080:8080'                                           # for the træfik dashboard
    labels:
      - traefik.enable=false                                  # hide traefik from traefik
    networks:
      - net

  basicapi:
    image: emilevauge/whoami
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:who01.localhost.com
      - traefik.frontend.auth.basic.usersFile=/etc/traefik/.htpasswd
    networks:
      net:
        ipv4_address: 10.0.1.4


  digestapi:
    image: emilevauge/whoami
    labels:
    - traefik.port=80
    - traefik.frontend.rule=Host:who02.localhost.com
    - traefik.frontend.auth.digest.usersFile=/etc/traefik/.htdigest
    networks:
      net:
        ipv4_address: 10.0.1.5

networks:
  net:
    name: "net"
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/28
```

I encourage you to join the #support channel on our slack: https://slack.traefik.io/.
I’ll close the issue for now, but let us know when you’ve found the problem!
