### ISSUE TITLE
Access WebUI through Path

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4054]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using docker swarm, I tried to access the Traefik API via the rule `traefik.frontend.rule=Path:/traefik` on localhost (127.0.0.1), but it does not work.

### What did you expect to see?

I was expecting to be able to enter http://127.0.0.1/traefik to reach the API. Note that reaching http://127.0.0.1/whoami does work in this setup.

### What did you see instead?

The browser keeps trying for a while until it loads a blank page with the text `Gateway Timeout`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
latest: Pulling from library/traefik
Digest: sha256:c25ac3c2736dc41b08c6f40ef3393d03dd7640a037cd53d681af459ccfa95c28
Status: Downloaded newer image for traefik:latest
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Windows 10 Pro, with Docker for Windows Version 18.06.1-ce-win73 (19507)

**traefik.toml**

```toml
logLevel = "DEBUG"
 
defaultEntryPoints = ["http","https"]
 
[api]
  entryPoint = "http"
 
[entryPoints]
  [entryPoints.http]
    address = ":80"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  swarmmode = true
```

**docker-stack.yml**

```yaml
version: '3'

services:
  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Path:/traefik
  whoami:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    labels:
      - traefik.frontend.rule=Path:/whoami
```
