### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by OsamaJBR** [containous/traefik#4066]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

**Create proxy network**
```
docker network create -d overlay proxy
```
**Traefik Dockerfile**
```Dockerfile
FROM traefik:1.7
RUN mkdir /customssl/

ADD devops-ssl/cert.pem /customssl/
ADD devops-ssl/cert.key /customssl/
```

**Stack.yaml**
```yml
version: "3.4"
services:
  traefik_init:
    image: registry.xxx.xxx/aw-traefik:1.7
    command:
      - "traefik"
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS:/customssl/cert.pem,/customssl/cert.key;"
      - "--defaultentrypoints=http"
      - "--accesslog"
      - "--accesslog.format=json"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=swarmqa.xxx.xxx"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul.xxx.xxx:8500"
      - "--consul.prefix=traefikqa"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure

  traefik:
    image: registry.xxx.xxx/aw-traefik:1.7
    depends_on:
      - traefik_init
    command:
      - "--consul"
      - "--consul.endpoint=consul.xxx.xxx:8500"
      - "--consul.prefix=traefikqa"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  proxy:
    driver: overlay
    external: true
  traefik:
    driver: overlay
```
### What did you expect to see?
traefik_init service to be completed and store config in the consul.

### What did you see instead?
```
time="2018-10-17T09:02:04Z" level=error msg="Failed to retrieve information of the docker client and server host: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
time="2018-10-17T09:02:04Z" level=error msg="Provider connection error Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?, retrying in 3.6780511s"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
Ubuntu 18.04 
Docker version 18.06.1-ce, build e68fc7a
Swarm with 3 nodes, all nodes are Manager
```
