### ISSUE TITLE
Missing acme storage file gives cryptic error message

### ISSUE THREAD

**Issue by koliyo** [containous/traefik#4068]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was trying to deploy traefik with acme but got stuck on
```
Unknown entrypoint \"\" for ACME configuration
```
After a while I was able to figure out that this was because the acme storage file did not yet exist
```toml
[acme]
  storage = "/var/traefik/acme.json"
```

This was resolved with `touch /var/traefik/acme.json`

### What did you expect to see?

A more descriptive error message

### What did you see instead?
```
Unknown entrypoint \"\" for ACME configuration
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
$ docker run traefik version
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by juliens** [comment]
Thanks for your interest!

I am unable to reproduce the bug.

Can you provide us with a complete configuration to reproduce this bug?

**Comment by koliyo** [comment]
Hmm, not able to reproduce here either.

Maybe missing some part of the setup. I am using docker swarm and traefik data mounted in a docker volume `traefik_data:/var/traefik`

So we can probably close this for now, and I will reopen if I discover it again!

**Comment by richardbrinkman** [comment]
Way to reproduce is this:

Create `docker-compose.yml` with this content:

```
version: "3.1"

services:

  traefik:
    command: --acme --acme.onhostrule --docker
    image: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    labels:
      - traefik.basic.frontend.rule=Host:www.example.com
```

Then run `docker-compose up -d && docker-compose logs`.
This will produce an error message like:

```
traefik_1  | time="2019-05-25T09:07:04Z" level=fatal msg="Unknown entrypoint \"\" for ACME configuration"
traefik_traefik_1 exited with code 1
```
