### ISSUE TITLE
HTTPS backend not found (When HTTP backend wokring) with Kubernetes Ingress  

### ISSUE THREAD

**Issue by fengjingzhun** [containous/traefik#4071]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

visit https://traefik.domain.com/dashboard/

### What did you expect to see?

dashboard page

### What did you see instead?

404 page

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.3-alpine

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml
```
logLevel = "DEBUG"
[traefikLog]
filePath = "/data/traefik.log"
#format = "json"
[accessLog]
filePath = "/data/access.log"
#format = "json"

defaultEntryPoints = ["http","https"]
#insecureskipverify = true 
[entryPoints]
[entryPoints.http]
address = ":80"
compress = true
#[entryPoints.http.redirect]
#entryPoint = "https"
[entryPoints.https]
address = ":443"
compress = true
[entryPoints.https.tls]

[acme]
email = "devops@domain.com" # username
storage = "/data/acme.json" # certificates storage
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https" # entrypoint whre ACME is enabled
[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "cloud.domain.net"
[[acme.domains]]
main = "traefik.domain.com"
sans = ["nexus.domain.com", "gitlab.domain.com", "jenkins.domain.com"]
```

**kubernetes  v1.11.1 docker v17.03.2**

kubernetes DaemonSet.yaml
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7.3-alpine
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80 
        - name: https
          containerPort: 443
          hostPort: 443 
        - name: admin
          containerPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configFile=/config/traefik.toml
        volumeMounts:
          - mountPath: /config
            name: config
      volumes:
        - name: config
          configMap:
             name: traefik-config
      nodeSelector:
        edgenode: "true" 
```

kubernetes Ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik   
spec:
  rules:
  - host: traefik.domain.com
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

access.log
```
180.109.81.244 - - [18/Oct/2018:06:33:32 +0000] "GET /dashboard/ HTTP/1.1" 404 19 "-" "PostmanRuntime/7.3.0" 1 "backend not found" "/dashboard/" 0ms
180.109.81.244 - - [18/Oct/2018:06:33:39 +0000] "GET /dashboard/ HTTP/1.1" 200 716 "-" "PostmanRuntime/7.3.0" 2 "traefik.domain.com/" "http://10.244.1.167:8080" 1ms
```
first row is visit https://traefik.tele-sing.com/dashboard/
second row is visit http://traefik.tele-sing.com/dashboard/
