### ISSUE TITLE
Support for multiple ports with one backend

### ISSUE THREAD

**Issue by praqmaTim** [containous/traefik#4074]
### Do you want to request a *feature* or report a *bug*?

Feature

### What I see

I have a Jenkins container running in an on-premise kubernetes cluster. Jenkins is exposed as a service with ingress.

```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
  - port: 8080
    name: web
  - port: 50000
    name: agent
  selector:
    app: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: build.remoteiv.dk
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
---
```
I have traefik running on a stand alone machine **outside the cluster** with the endpoint pinting towards my kubernetes api-server. 

This works **great** when I add a new service and ingress, traefik picks it up beautifully.
But Jenkins allows build agents to connect over port 50000.

`java -jar agent.jar -jnlpUrl http://build.remoteiv.dk/computer/<agentName>/slave-agent.jnlp -secret 33efcc3840c1e15475ec727283ba331187ced976feff3871cb5912f4371120f6 -workDir "C:\Jenkins"
`  

If I add a new ingress and service for the agent connection port then the original is overwritten in treafik.

```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
  - port: 8080
    name: web
  selector:
    app: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: build.remoteiv.dk
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agents
  labels:
    app: jenkins
spec:
  ports:
  - port: 50000
    name: agents
  selector:
    app: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-agents
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: build.remoteiv.dk
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-agents
          servicePort: 50000
```

<img width="520" alt="traefikoverwrite" src="https://user-images.githubusercontent.com/8044990/47151972-9ab4a180-d2db-11e8-9312-bbdf5f4a588c.png">

### What I would expect
That traefik would **not** overwrite the frontend and requests hitting traefik on port 50000 were routed to build.remoteiv.dk:50000
