### ISSUE TITLE
Issue with ingresses with empty host and path

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#4076]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created an ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard
  namespace: default
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
    http:
      paths:
        backend:
          serviceName: dashboard
          servicePort: 8080
```
### What did you expect to see?

A working frontend and backend in the dashboard.

### What did you see instead?

The frontend rule is missing in the API and dashboard. This results in a "non functioning" frontend in the dashboard and API result.

### Additional Details

It appears that the key for the frontend/backend is `host + path` when host _and_ path are empty, this may end up being "unparseable"
