### ISSUE TITLE
PathPrefixStrip rule does not work with SSL redirection

### ISSUE THREAD

**Issue by sagikazarmark** [containous/traefik#4085]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I specified an ingress for my service in Kubernetes:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
  name: myingress
  namespace: default
spec:
  rules:
  - host: myhost
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /mypath
```

Inspecting the service on the dashboard shows it gets created properly with the correct rule.

### What did you expect to see?

I expected `http://myhost/mypath` to be redirected to `https://myhost/mypath`

### What did you see instead?

Traefik redirected the request to `https://myhost`

Removing the `PathPrefixStrip` properly redirects the request.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.2-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    logLevel = "INFO"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
      [entryPoints.prometheus]
      address = ":9120"
      compress = true
      [entryPoints.ping]
      address = ":81"
      [entryPoints.dashboard]
      address = ":8080"
      compress = true
    [ping]
    entryPoint = "ping"
    [kubernetes]
    [kubernetes.ingressEndpoint]
      publishedService = "kube-system/ingress-traefik"
    [acme]
    email = "my@email.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    acmeLogging = true
      [acme.dnsChallenge]
      provider = "route53"
    [api]
    dashboard = true
    entryPoint = "dashboard"
    # Metrics definition
    [metrics]
      [metrics.prometheus]
        entryPoint = "prometheus"
```

### Additional context

This issue was first reported in #1957 and a solution was proposed in #3631, released as 1.7

Since then, this issue was reported multiple times (#3876, #3999), but got closed automatically by the @traefiker bot without any response at all. I really hope it won't get closed again.
