### ISSUE TITLE
traefik wrongly says that page was moved pernamently

### ISSUE THREAD

**Issue by raven-wing** [containous/traefik#4104]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created three compose files: 2 with wordpress  and one with traefik
```yml
version: '3.5'

services:
  db:
    image: mysql:5.7
    networks:
      - proxynet
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: changemetoo
    deploy:
      placement:
        constraints:
          - node.role == manager

  word:
    depends_on:
      - db
    image: wordpress
    networks:
      - proxynet
    volumes:
      - wp-content:/var/www/html/wp-content
    ports:
      - "80"
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: changemetoo
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxynet"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:page.pg"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.entryPoints=http"
        - "traefik.backend=page_word"
      placement:
        constraints:
          - node.role == manager

volumes:
  db-data:
  wp-content:


networks:
  proxynet:
    external: true
    name: proxynet
```

Traefik configuration:
```yml
version: '3.5'

services:
  proxy:
    image: traefik:latest
    networks:
      - proxynet
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.toml
    deploy:
      labels:
        - "traefik.enable:true"
        - "traefik.frontend.passHostHeader:true"
        - "traefik.docker.network=proxynet"
        - "traefik.frontend.rule=Host:proxy.page.pg"
        - "traefik.port=8080"
      placement:
        constraints:
          - node.role == manager

configs:
  traefik-config:
    file: config.toml

networks:
  proxynet:
    name: proxynet
```

second wordpress containers differs only in that it has page2 in frontend rule.

### What did you expect to see?

When I go to page.pg I get app on first wordpress container
When I go to page2.pg I get app on second wordpress container
When I go to proxy.page.pg I get traefik dashboard

### What did you see instead?

When I go to page.pg I get app on first wordpress container, but after refreshing 3 times I get contents of the second container. I get response 301 which is redirecting to first container.
Same goes for page2.pg addres.

Traefik container works always right.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

config.toml:
```toml
logLevel="DEBUG"
debug=true

defaultEntryPoints = ["http", "https"]

[web]
address=":8080"



[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint="unix://var/run/docker.sock"
watch=true
swarmmode=true
```
