### ISSUE TITLE
Traefik rewrites the status text of a 404 page

### ISSUE THREAD

**Issue by roverwolf** [containous/traefik#4114]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When proxied through Traefik the request
`curl -i --http1.1 -H "Accept: application/json" https://....?invalid_uuid`
returns
`HTTP/1.1 404 Not Found` with the correct headers and body

but when **not** going through Traefik the request
`curl -i --http1.1 -H "Accept: application/json" https://....?invalid_uuid`
returns
`HTTP/1.1 404 Invalid UUID` with the correct headers and body

### What did you expect to see?

I expected Traefik to forward the status text of the backend for a page with a 404 status (`Invalid UUID`).

### What did you see instead?

Traefik rewrites the status text send by the backend to be `Not Found` for a page with a 404 status.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

All configuration is in the `docker-compose.yml` file:
```yaml
version: '3'

services:
  proxy:
    image: traefik:1.7
    restart: always
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=email-address@here.com"
      - "--docker"
      - "--docker.exposedByDefault=false"
      - "--docker.watch"
    ports:
      - "80:80"      # The HTTP port
      - "443:443"      # The HTTP port
      - "8080:8080"  # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/data/traefik/acme:/etc/traefik/acme"
    networks:
      - default
```
