### ISSUE TITLE
traefik.ingress.kubernetes.io/load-balancer-method:  drr  don't work

### ISSUE THREAD

**Issue by SFHfeihong** [containous/traefik#4115]
k8s version:1.9.3
treafik version:  (latest)1.7.3
I user the example cheeses.

cheeses-ingress.yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheeses
  annotations:
    #traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    traefik.ingress.kubernetes.io/load-balancer-method: drr
spec:
  rules:
  - host: traefik-ui.k8s
    http:
      paths:
      - path: /stilton
        backend:
          serviceName: stilton
          servicePort: http
      - path: /cheddar
        backend:
          serviceName: cheddar
          servicePort: http
      - path: /wensleydale
        backend:
          serviceName: wensleydale
          servicePort: http
```
But the loadbalancer method don't work. I use "traefik.backend.loadbalancer.method: drr". It also bad. The result as the following picture.
I want to know is there something wrong in my config.Thank you !
![ingress](https://user-images.githubusercontent.com/27404167/47550110-bef22d00-d930-11e8-9ed6-538bf7a84d77.PNG)
