### ISSUE TITLE
Documentation: traefik.port is required, but documentation seems to indicate it is not

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4126]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

https://docs.traefik.io/v1.7/configuration/backends/docker/ seems to indicate that the `traefik.port` label in docker compose/stack is optional. However, trying to configure as below (see bottom of post) will give the following error:

```sh
scrapy_traefik.1.izvf1nw6nfwi@linuxkit-00155d03b71d    | time="2018-10-28T17:23:39Z" level=debug msg="Filtering container without port, scrapy_whoami.1: port label is missing, please use traefik.port as default value or define port label for all segments ('traefik.<segment_name>.port')"
```

If `- "traefik.port=80"` is added back to the whoami service, it works.

Please also note that other instances of documentation might need to change, such as https://docs.traefik.io/v1.7/user-guide/docker-and-lets-encrypt/#gotchas-and-tips that does mention `traefik.port` as well.

```yaml
version: '3.7'

services:
  traefik:
    image: traefik
    command: --api --docker --docker.swarmmode --loglevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=PathPrefixStrip:/traefik"
        - "traefik.docker.network=scrapy_traefik-net"
    networks:
      - traefik-net

  whoami:
    image: emilevauge/whoami
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefixStrip:/whoami"
        - "traefik.docker.network=scrapy_traefik-net"
    networks:
      - traefik-net
networks:
  traefik-net:
```
