### ISSUE TITLE
Docker: Traefik preferring ACME over provided certificates

### ISSUE THREAD

**Issue by anton-johansson** [containous/traefik#4131]
Note: This might seem like a duplicate of #1003, however I'm coming across the same issue with the latest version. I've asked for help in the Slack channel without success, so I figured I'd try here.

### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I supply Traefik with a self-signed wildcard SSL certificate for my internal services. I configure Traefik to support ACME. I add Traefik services both for my internal domain (`*.service.example.local`) and for external domains.

### What did you expect to see?

I expect Traefik to **not** try to get ACME certificates for the internal services.

### What did you see instead?

I can see in the logs that it tries to get ACME certificates for internal services, even though those services already have a provided certificate.

It's worth noting that everything still works as expected. The internal services use the self signed wildcard certificate while external domains get ACME certfificates. I just don't like that Traefik attempts to generate certificates for them, because I'm afraid to hit the rate limiting.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Ubuntu 18.04
Traefik 1.7.3
Docker Swarm 18.03.1-ce, build 9ee9f40

Configuration:

```yml
version: '3.3'

services:
  consul:
    image: consul:1.3.0
    command: agent -server -bootstrap-expect=1
    networks:
      - consul-net
    volumes:
      - type: bind
        source: /var/traefik-data/consul-data/
        target: /consul/data/
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
  initiation:
    image: traefik:1.7
    networks:
      - consul-net
    depends_on:
      - consul
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - storeconfig
      - --entryPoints=Name:http Address::80
      - --entryPoints=Name:https Address::443 TLS:/cert/star.service.example.local.crt,/cert/star.service.example.local.key
      - --defaultentrypoints=http,https
      - --api
      - --api.entryPoint=traefik
      - --api.dashboard=true
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.exposedByDefault=false
      - --docker.endpoint=tcp://swarm.service.example.local:2376
      - --acme
      - --acme.storage=traefik/acme/account
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.onHostRule=true
      - --acme.onDemand=false
      - --acme.email=something@example.com
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
      - --logLevel=WARN
      - --traefikLog.format=json
      - --accessLog.format=json
  app:
    image: traefik:1.7
    networks:
      - consul-net
      - traefik-net
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/traefik-data/certificates/
        target: /cert/
    depends_on:
      - consul
      - initiation
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik-net"
        traefik.port: 8080
        traefik.frontend.rule: "Host:traefik.service.example.local"
        traefik.frontend.entryPoints: "https"
        traefik.frontend.whiteList.sourceRange: "192.168.0.0/16, 10.0.0.0/8"
    command:
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
      - --logLevel=WARN
      - --traefikLog.format=json

networks:
  traefik-net:
    external:
      name: traefik-net
  consul-net:
    driver: overlay
```

I also have services created like this (both with internal domains and external domains):
```yml
version: '3.3'

services:
  thumbor:
    image: some-image
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik-net"
        traefik.port: 8000
        traefik.frontend.rule: "Host:some-service.service.example.local"
        traefik.frontend.entryPoints: "https"
        traefik.frontend.whiteList.sourceRange: "192.168.0.0/16, 10.0.0.0/8"

networks:
  traefik-net:
    external:
      name: traefik-net
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

I see Traefik trying to get ACME certificates for domains that already have a provided wildcard certificate:

```
Error getting ACME certificates [traefik.service.example.local] : cannot obtain certificates: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix
Error getting ACME certificates [some-service.service.example.local] : cannot obtain certificates: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Name does not end in a public suffix
...
```
