### ISSUE TITLE
Multiple frontends for one backend Docker

### ISSUE THREAD

**Issue by AvoMMH** [containous/traefik#4140]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I started my service and scaled it up to 10 replicas. Then I took a look at the Dashboard

### What did you expect to see?
 I expected to see one Frontend and one Backend with 10 servers.

### What did you see instead?
I got 10 Frontends(same config, but different names) one Backend with 10 servers.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.3 
maroilles
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entrypoints.traefik]
  address = ":8080"

[api]
entrypoint = "traefik"

[docker]
endpoint="unix:///var/run/docker.sock"
watch=true
domain="docker.localhost"
exposedByDefault=false
```

```yml
version: '3.5'
services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 8080:8080
  spam:
    image: nginx
    deploy:
      replicas: 10
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefix:/
      - traefik.backend=nginx

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by SantoDE** [comment]
Hey @AvoMMH ,

am I correct that you're running it on swarm mode? (based on the deploy key).

If so, please enable the swarm mode option in your `traefik.toml` as well and try again.

```

[docker]
endpoint="unix:///var/run/docker.sock"
watch=true
domain="docker.localhost"
exposedByDefault=false
swarmMode = true
```

**Comment by AvoMMH** [comment]
When I enable the Swarmmode none of my Services show up

**Comment by SantoDE** [comment]
And on what are you trying to run it? Just compose or swarm (mode)?

**Comment by AvoMMH** [comment]
To run the compose file I use ```docker stack deploy -c docker-compose.yml traefik_test```

**Comment by mmatur** [comment]
https://docs.traefik.io/configuration/backends/docker/#using-docker-with-swarm-mode

**Comment by SantoDE** [comment]
Hey @AvoMMH,

@mmatur is right. If you want to run it with `docker stack deploy` its gonna be spawned in swarm mode, which requires you to set the labels below `deploy` (thats needed by the docker api to have the labels at the correct place).

In your case, it would look like that
```
  spam:
    image: nginx
    deploy:
      replicas: 3
      labels:
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.enable=true"
        - "traefik.port=80"
```
