### ISSUE TITLE
Path-based routing: "exceptions" (or how-to block a path in a normal frontend)

### ISSUE THREAD

**Issue by jesusofsuburbia** [containous/traefik#4143]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I run traefik as a kubernetes Ingress provider.

In my cluster I have Pods with 3rd party applications that expose a prometheus `/metrics` endpoint.
This endpoint is usually exposed on the same port as the rest of the application.

Now, when I generate a Service + Ingress for this port, I automatically open this `/metrics` up to the internet.

--> This is what I want to avoid.

The problem is even a bit more complex: the endpoint is not always exactly `/metrics`, it can be:

* https://my.external.domain/metrics
* https://my.external.domain/some/subpath/metrics

Now I'm thinking about how I can effectively allow acces to `my.external.domain/*` (= everything)
**except** `my.external.domain/some/subpath/metrics`.

I thought about using path-based routing.
But as far as I understand, this doesn't support *exceptions*.

In the documentation I couldn't find something like a "blacklist".

I think of something like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: my.external.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: test-service
          servicePort: http
      - path: /metrics
        backend: deny   # return FORBIDDEN or so
```

Is this a valid need or am I just logically on the wrong track?
