### ISSUE TITLE
Provided TLS certificates as path won't work with consul k/v enabled

### ISSUE THREAD

**Issue by gionn** [containous/traefik#4144]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

A wildcard certificate (*.domain.com) and a single domain certificate (different.domain.net) configured on the https entrypoint, ACME enabled (even if with onHost = false).

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    sniStrict = true
      [[entryPoints.https.tls.certificates]]
        keyFile  = "/usr/local/share/ssl/private/wildcard.key"
        certFile = "/usr/local/share/ssl/certs/wildcard.pem"
      [[entryPoints.https.tls.certificates]]
        keyFile  = "/usr/local/share/ssl/private/different_domain_com.key"
        certFile = "/usr/local/share/ssl/certs/different_domain_com.crt"
```

### What did you expect to see?

Certificates correctly offered depending on the request Host when using static configuration, then switched to Consul shared configuration, expecting no changes in behaviour.

### What did you see instead?

Wrong certificate offered with requests to different.domain.net (it looks like is always returning the default certificate since flipping configuration order also flip the results)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

static configuration (working):

```
traefik -c traefik.toml
```

shared configuration on consul (misbehaving):

```
traefik storeconfig -c traefik.toml
```

then:

```
--consul
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-10-31T14:57:32Z" level=debug msg="Looking for an existing ACME challenge for [redacted]..."
time="2018-10-31T14:57:32Z" level=debug msg="Looking for provided certificate to validate [redacted]..."
time="2018-10-31T14:57:32Z" level=debug msg="No provided certificate found for domains [redacted], get ACME certificate."
time="2018-10-31T14:57:32Z" level=debug msg="No certificate found or generated for [redacted]"

```

**Comment by geraldcroes** [comment]
Hi and thank you for taking the time to report this issue.

Could you provide the full log (since traefik startup in consul mode), as well as your configuration file at the time of the store config (and the eventual logs when you call store config)

Could you check your KV store and confirm that you find the binaries of the certificates there (and not their path).

Thank you

**Comment by gionn** [comment]
> Could you check your KV store and confirm that you find the binaries of the certificates there (and not their path).

I was taking a look of what was stored on consul while testing with `consul kv get -recurse` and I remember that cert and key was stored as string path.

Will provide full logs in a few days (sorry, vacation days ahead).

Thanks!

**Comment by JamesGuthrie** [comment]
I seem to be running into this problem as well, I'm using traefik v1.7.3, docker swarm, and the etcd backend. I was able to get the exact same configuration working with v1.6.6.

I have a provided cert for `mydomain.com` and `www.mydomain.com`. I want traefik to use Let's Encrypt to issue certs dynamically for `*.mydomain.com` (and potentially other domains).

I'm configuring traefik with the following command-line config:

```
storeconfig
--debug
--accesslog=true
--accessLog.format=json
--traefikLog=true
--traefikLog.format=json
--defaultentrypoints=http,https
--entrypoints=Name:http Address::80 Redirect.EntryPoint:https Compress:true
--entrypoints=Name:https Address::443 Compress:true TLS:/path/to/cert.pem,/path/to/key.pem
--api
--docker
--docker.swarmmode=true
--docker.domain=mydomain.com
--docker.watch=true
--acme=true
--acme.acmelogging=true
--acme.email=admin@mydomain.com
--acme.entrypoint=https
--acme.storage=/traefik/acme/account
--acme.dnschallenge=true
--acme.httpchallenge=false
--acme.dnschallenge.provider=route53
--acme.domains=*.mydomain.com
--acme.onhostrule=true
--etcd
--etcd.endpoint=etcd:2379
--etcd.watch=true
--etcd.prefix=/traefik
--etcd.useAPIV3=true
```

When I access `mydomain.com` running traefik v1.7.3, I see the following log entries:
```
Looking for provided certificate to validate mydomain.com...
No provided certificate found for domains mydomain.com, get ACME certificate
```

When I access `mydomain.com` running traefik v1.6.6 I see the following log entries:
```
Looking for provided certificate to validate mydomain.com...
Domain "mydomain.com" checked by provided certificate "mydomain.com"
```

**Comment by JamesGuthrie** [comment]
Is there anything I can do to help with tracking this one down? It's still an issue for us.

**Comment by kaotika** [comment]
The issue still exists. 
A current workaround seem to be to switch back to v1.6. (1.6.6 currently)

**Comment by JamesGuthrie** [comment]
Indeed. We're still running v1.6 because of this bug. (and hoping that it is resolved in v2, but we haven't tested it yet).

**Comment by pengu-fr** [comment]
Same issue here. We wanted to use consul to store config. After importing our working traefik.toml file into K/V (using storeconfig), our certificates defined in /traefik/entrypoints/https/tls/certificates/[X]/certfile couldn't be served (traefik use the default certificate instead).
We tried to use certificate file path or content in the K/V store, but same result.

**Comment by suslovsergey** [comment]
any news?

**Comment by ryaneorth** [comment]
any update on this? This still seems to be a problem with this version. I recently had a change merged into the official Helm chart that is unusable unless I use traefik version <= 1.6.x 😞 

https://github.com/helm/charts/pull/18565

**Comment by JohnStarich** [comment]
I'm seeing a very similar symptom, also with consul and traefik 1.7:
(I'm using a prefix of "proxy/traefik")

>time="2019-12-13T06:23:14Z" level=debug msg="Cannot list keys under \"proxy/traefik/tls/\": Key not found in store"
>time="2019-12-13T06:23:14Z" level=info msg="Skipping same configuration for provider consul"
>time="2019-12-13T06:23:33Z" level=debug msg="Looking for an existing ACME challenge for [redacted]..."
>time="2019-12-13T06:23:33Z" level=debug msg="Looking for provided certificate to validate [redacted]..."
>time="2019-12-13T06:23:33Z" level=debug msg="No provided certificate found for domains [redacted], get ACME certificate."
>time="2019-12-13T06:23:33Z" level=debug msg="ACME got domain cert [redacted]"

I've tried wiping out my consul DB a few times, generated my certs differently, and dumped out the certs to disk for inspection (with [this tool](https://github.com/ldez/traefik-certs-dumper)). The certs look okay, but the certificate traefik chooses to reply with is always the default, self-signed cert. 😕 

@geraldcroes Please let me know if you need more info from me, I'm happy to help/contribute where I can.

**Comment by JohnStarich** [comment]
It's been difficult dealing with this bug, given that my system simply restarted and stopped working. This was affecting my production systems, so I've since moved on to a standalone certbot service and traefik with CLI args plus a file watch:

<details>
<summary>

(Expand for full working config)
```yaml
version: "3.4"

services:
  traefik:
    image: traefik:1.7
    command:
    - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
    - --entryPoints=Name:https Address::443 TLS:/data/config/live/example.com/fullchain.pem,/data/config/live/example.com/privkey.pem
    - --file
    - --file.directory=/data/config/  # Watch 'poke_traefik.toml' to reload certificates when certbot completes renewals: https://github.com/containous/traefik/pull/4022
    - --file.watch
    ...
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - certificates:/data:ro

  certbot:
    image: certbot/dns-cloudflare:v1.0.0
    volumes:
    - certificates:/data
    command:
    - certonly
    - --config-dir=/data/config
    - --deploy-hook=touch /data/config/poke_traefik.toml && sleep $$(( 60 * 60 * 24 * 20 ))  # Sleeping for 20 days...
    ...
    deploy:
      restart_policy:
        delay: 1h
```
</summary>

```yaml
version: "3.4"

services:
  traefik:
    image: traefik:1.7
    command:
    - --api
    - --api.dashboard
    #- --debug
    - --defaultEntrypoints=http,https
    - --docker
    - --docker.exposedByDefault=false
    - --docker.swarmMode
    - --docker.watch
    - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
    - --entryPoints=Name:https Address::443 TLS:/data/config/live/example.com/fullchain.pem,/data/config/live/example.com/privkey.pem
    - --file
    - --file.directory=/data/config/  # Watch 'poke_traefik.toml' to reload certificates when certbot completes renewals: https://github.com/containous/traefik/pull/4022
    - --file.watch
    - --loglevel=INFO  # Set to DEBUG for more info
    - --ping
    - --retry
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"  # Dashboard
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - certificates:/data:ro
    deploy:
      mode: global
      update_config:
        order: start-first
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 10M
      placement:
        constraints:
        - node.role == manager
    healthcheck:
      test: ["CMD", "/traefik", "healthcheck", "--ping"]

  certbot:
    # Certbot terminates and restarts periodically
    #   * Sleep for 20 days between successful runs
    #   * Only re-attempt start container an hour after exiting (both success and failure)
    image: certbot/dns-cloudflare:v1.0.0
    dns:
    - 1.0.0.1
    - 1.1.1.1
    volumes:
    - certificates:/data
    command:
    - certonly
    - --config-dir=/data/config
    - --work-dir=/data/work

    - --agree-tos
    - --deploy-hook=touch /data/config/poke_traefik.toml && sleep $$(( 60 * 60 * 24 * 20 ))  # Sleeping for 20 days...
    - --dns-cloudflare
    - --dns-cloudflare-credentials=/data/cloudflare.ini
    - --dns-cloudflare-propagation-seconds=60
    - --email=[redacted:email]
    - --expand        # Try and reuse existing certs when adding new domains
    #- --force-renew  # Toggle this on temporarily when switching on/off staging server
    #- --test-cert    # Use Let's Encrypt staging server
    - -d=*.example.com,example.com
    - -n
    deploy:
      replicas: 1
      update_config:
        order: stop-first
      restart_policy:
        condition: any
        delay: 1h
```
</details>
