### ISSUE TITLE
traefik with swarm 

### ISSUE THREAD

**Issue by michelLammensSmart** [containous/traefik#4152]
use this docker compose : 

```yml
version: "3.4"
services:
traefik:
  image: traefik:v1.7
  command:
    - "--api"
    - "--docker"
    - "--docker.swarmmode"
    - "--docker.domain=home.pw"
    - "--docker.watch"
    - "--logLevel=DEBUG"
    - "--web"
  networks:
    - appnet
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 80:80
    - 8080:8080
  deploy:
    mode: global
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.role == manager]
portainer:
  image: hypriot/rpi-portainer
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - appnet
  ports:
    - "9000:9000"
  deploy:
   replicas: 1
   placement:
    constraints: [node.role == manager]
   labels:
    - "traefik.port=9000"
    - "traefik.backend.loadbalancer.method=wrr"
    - "traefik.backend=portainer"
    - "traefik.frontend.rule=Host:portainer.home.pw"
viz:
   image: alexellis2/visualizer-arm:latest
   volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
   networks:
    - appnet
   ports:
    - "8081:8080"
   deploy:
     replicas: 1
     labels:
        - "traefik.port=8080"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend=viz"
        - "traefik.frontend.rule=Host:viz.home.pw"
     placement:
        constraints:
          - node.role==manager
networks:
appnet:
 driver:  overlay`
```

and i have this error message : 

```
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:01Z" level=info msg="Skipping same configuration for provider docker"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="originLabelsmap[com.docker.stack.image:traefik:v1.7 com.docker.stack.namespace:proxy]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="allLabelsmap[:map[]]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="Filtering container without port, proxy_traefik.vud0tllygz9piigdihyk9o7d5: port label is missing, please use traefik.port as default value or define port label for all segments ('traefik.<segment_name>.port')"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="originLabelsmap[com.docker.stack.image:alexellis2/visualizer-arm:latest com.docker.stack.namespace:proxy traefik.backend:viz traefik.backend.loadbalancer.method:wrr traefik.frontend.rule:Host:viz.home.pw traefik.port:8080]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="allLabelsmap[:map[traefik.frontend.rule:Host:viz.home.pw traefik.port:8080 traefik.backend:viz traefik.backend.loadbalancer.method:wrr]]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="originLabelsmap[traefik.frontend.rule:Host:portainer.home.pw traefik.port:9000 com.docker.stack.image:hypriot/rpi-portainer com.docker.stack.namespace:proxy traefik.backend:portainer traefik.backend.loadbalancer.method:wrr]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="allLabelsmap[:map[traefik.frontend.rule:Host:portainer.home.pw traefik.port:9000 traefik.backend:portainer traefik.backend.loadbalancer.method:wrr]]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="originLabelsmap[com.docker.stack.image:alexellis2/visualizer-arm:latest com.docker.stack.namespace:proxy traefik.backend:viz traefik.backend.loadbalancer.method:wrr traefik.frontend.rule:Host:viz.home.pw traefik.port:8080]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:15Z" level=debug msg="allLabelsmap[:map[traefik.backend:viz traefik.backend.loadbalancer.method:wrr traefik.frontend.rule:Host:viz.home.pw traefik.port:8080]]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="originLabelsmap[com.docker.stack.namespace:proxy traefik.backend:portainer traefik.backend.loadbalancer.method:wrr traefik.frontend.rule:Host:portainer.home.pw traefik.port:9000 com.docker.stack.image:hypriot/rpi-portainer]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="allLabelsmap[:map[traefik.frontend.rule:Host:portainer.home.pw traefik.port:9000 traefik.backend:portainer traefik.backend.loadbalancer.method:wrr]]"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-portainer\":{\"servers\":{\"server-proxy-portainer-1-ca8cd5c9799b9b1da8a664ea46eb558b\":{\"url\":\"http://10.0.3.15:9000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"backend-viz\":{\"servers\":{\"server-proxy-viz-1-eb130754c8b2c83e457ae835ff68c9ff\":{\"url\":\"http://10.255.0.23:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-Host-portainer-home-pw-1\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-portainer\",\"routes\":{\"route-frontend-Host-portainer-home-pw-1\":{\"rule\":\"Host:portainer.home.pw\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null},\"frontend-Host-viz-home-pw-0\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-viz\",\"routes\":{\"route-frontend-Host-viz-home-pw-0\":{\"rule\":\"Host:viz.home.pw\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Wiring frontend frontend-Host-portainer-home-pw-1 to entryPoint http"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating backend backend-portainer"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-portainer-home-pw-1"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating load-balancer wrr"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating server server-proxy-portainer-1-ca8cd5c9799b9b1da8a664ea46eb558b at http://10.0.3.15:9000 with weight 1"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating route route-frontend-Host-portainer-home-pw-1 Host:portainer.home.pw"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Wiring frontend frontend-Host-viz-home-pw-0 to entryPoint http"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating backend backend-viz"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-viz-home-pw-0"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating load-balancer wrr"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating server server-proxy-viz-1-eb130754c8b2c83e457ae835ff68c9ff at http://10.255.0.23:8080 with weight 1"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=debug msg="Creating route route-frontend-Host-viz-home-pw-0 Host:viz.home.pw"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=info msg="Server configuration reloaded on :80"
proxy_traefik.0.vud0tllygz9p@rpiManager    | time="2018-11-01T08:29:16Z" level=info msg="Server configuration reloaded on :8080"
```

thans you for your helps
