### ISSUE TITLE
Consul catalog is not checking all datacenters.

### ISSUE THREAD

**Issue by Armatorix** [containous/traefik#4155]
Bug

### What did you do?
I've got 3 DC's (`DC_A`, `DC_B`, `DC_C`) declared in consul and some services with tags like here:

```
DC_A:
-service1 (tags=[traefik.fronted.rule=Host:domainA, traefik.protocol=https, traefik.enable=true])
-serviceA (tags=[traefik.fronted.rule=Host:domainA, traefik.protocol=https, traefik.enable=true])
-...
DC_B:
-serviceB (tags=[traefik.fronted.rule=Host:domainB, traefik.protocol=https, traefik.enable=true]
-...
DC_C:
-serviceC (tags=[traefik.fronted.rule=Host:domainC, traefik.protocol=https, traefik.enable=true]
-...
```
I've configured traefik with service discovery in consul, and traefik see only services from `DC_A`.

### What did you expect to see?
I expected to see `service1`, `serviceA`, `serviceB`, `serviceC`.

### What did you see instead?
`service1`, `serviceA`

### Traefik version:

docker `v1.7.3` alpine on marathon

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        ...
[consulCatalog]
    endpoint = "$CONSUL_URL"
    exposedByDefault = false
    constraints=[]
    watch=true
    [consulCatalog.tls]
        ...
        insecureSkipVerify = true
[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
```
