### ISSUE TITLE
usersFile does not allow comments

### ISSUE THREAD

**Issue by thde** [containous/traefik#4157]
### Do you want to request a *feature* or report a *bug*?

Bug

If OK for you, I'd have a try fixing it myself :)

### What did you do?

Used comments in a basic auth users file.

It looks like Traefik is not handling comments at the moment:
https://github.com/containous/traefik/blob/master/middlewares/auth/parser.go#L10
https://github.com/containous/traefik/blob/master/middlewares/auth/authenticator.go#L130:6

### What did you expect to see?

Lines that begin with the hash character "#" are considered comments, and are ignored. Comments may not be included on the same line as a configuration directive. White space occurring before a directive is ignored, so you may indent directives for clarity. Blank lines are also ignored.
https://httpd.apache.org/docs/2.4/configuring.html#syntax

### What did you see instead?

```
Nov 02 15:53:52 host traefik[2916]: time="2018-11-02T15:53:52+01:00" level=error msg="error parsing Authenticator user: ##################################. Skipping frontend frontend1..."
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.https]
  address = ":10501"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384"
    ]

[[tls]]
 entryPoints = ["https"]
 [tls.certificate]
   certFile = "....pem"
   keyFile = "....key"

[accessLog]

[file]
  directory = "/etc/traefik/conf.d"
  watch = true
```

```toml
[frontends.frontend1]
    backend = "backend1"
[frontends.frontend1.routes.backend]
    rule = "Host: host.example"
[frontends.mysql.auth.basic]
    usersFile = "/etc/traefik/auth"
```

```
##################################
# THIS FILE IS MANAGED BY PUPPET #
##################################
admin:abc
```
