### ISSUE TITLE
Kubernetes ingress prioritization causes wildcards to take precedence

### ISSUE THREAD

**Issue by atombender** [containous/traefik#4161]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Ingress structure:

```yaml
- rules:
   - host: bar.foo.com
     http:
       # ...
   - host: *.foo.com
     http:
       # ...
```

### What did you expect to see?

`bar.foo.com` should take precedence since it is _semantically_ more specific than the wildcard. This is behaviour of other ingress controllers, including the Nginx ingress controller and Google's GCE ingress controller. While Traefik supports priorities, these can only be specified in the main config, which defeats the purpose of using Kubernetes ingresses.

### What did you see instead?

`*.foo.com` takes precedence.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.3
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-15_10:13:00AM
OS/Arch:      linux/amd64
```
