### ISSUE TITLE
Use of `traefik.ingress.kubernetes.io/preserve-host: true` discards other annotations like auth

### ISSUE THREAD

**Issue by rosskevin** [containous/traefik#4173]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

Deployed the traefik dashboard ingress with `traefik.ingress.kubernetes.io/preserve-host: true`

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-secret: traefik-dashboard-admin-credentials
    ingress.kubernetes.io/auth-type: basic
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/priority: "100"
    # !!!offending line
    traefik.ingress.kubernetes.io/preserve-host: true
  labels:
    app: traefik-dashboard
    ksonnet.io/component: traefik.traefik-dashboard
  name: traefik-dashboard
  namespace: prod-inf
spec:
  rules:
  - host: traefik.advisorintake.com
    http:
      paths:
      - backend:
          serviceName: traefik-dashboard
          servicePort: 80
  tls:
  - hosts:
    - traefik.advisorintake.com
    secretName: crt-wildcard
```

### What did you expect to see?
A dashboard challenged by basic auth

### What did you see instead?
- No basic auth - allowed in to the dashboard
- Checked kubernetes and my annotations were missing
- Commented out `traefik.ingress.kubernetes.io/preserve-host: true` and redeployed - all good

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
gke
```toml
logLevel = "INFO"
sendAnonymousUsage = true
defaultEntryPoints = ["http","https"]
[entryPoints]
    [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.redirect]
            regex = "^http://(.*)"
            replacement = "https://$1"
            permanent = true
    [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]  
    [entryPoints.traefik]
        address = ":8080"          
[kubernetes]
[api]
    entryPoint = "traefik"
    dashboard = true    
    [api.statistics]
        recentErrors = 10
```
