### ISSUE TITLE
only one backend when loadbalancer.swarm=true

### ISSUE THREAD

**Issue by siyu6974** [containous/traefik#4179]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Running 2+ backends (Docker swarm 18.09) with the label traefik.backend.loadbalancer.swarm=true

### What did you expect to see?

Get 1 frontend with 2+ backends

### What did you see instead?

1 frontend with only 1 backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "tcp://127.0.0.1:2376"
domain = "my.domain"
watch = true
exposedByDefault = false
swarmMode = true

[acme]
email = "email@test.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
This is the exact same issue as #2138, and yes I shamelessly copied "What did you expect to see" and "What did you see instead", however using the latest version, the issue is still there.

Everything is working when traefik.backend.loadbalancer.swarm is set to false.
When loadbalancer.swarm=true, the LB is actually working, when I make requests to the endpoint, by inspecting the log, I can see backends taking their turn logging the response.
