### ISSUE TITLE
healthcheck parameter

### ISSUE THREAD

**Issue by siyu6974** [containous/traefik#4182]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

A healthcheck on my container with 

1)
```
 traefik.backend.healthcheck.path: '/primus?access_token=healthcheck&transport=polling'
```

1')

```
- "traefik.backend.healthcheck.path='/primus?access_token=healthcheck&transport=polling'"
```
and 

2)
```
 - "traefik.backend.healthcheck.path=/primus?access_token=healthcheck&transport=polling"
```

### What did you expect to see?

Healthcheck pinging `/primus?access_token=healthcheck&transport=polling`

### What did you see instead?

Case 2) was pinging `/primus` without parameters
Case 1) and 1') converted `?` and `&`, result in `/primus%3Faccess_token=healthcheck&transport=polling`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "tcp://127.0.0.1:2376"
domain = "my.domain"
watch = true
exposedByDefault = false
swarmMode = true

[acme]
email = "email@test.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```yml
version: '3'
services:
  primus:
    image: ${REGISTRY_URL}primus-${SUBDOMAIN}:${GIT_HASH:-latest}
    networks:
      traefik-net:
        aliases:
        - primus-${SUBDOMAIN}
    env_file: env_${SUBDOMAIN}/primus.env
    command: npm start
    deploy:
      labels:
      traefik.docker.network: "traefik-net"
      traefik.frontend.rule=Host:primus.${SUBDOMAIN}.${DOMAIN}"
      traefik.backend=primus-${SUBDOMAIN}"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend.healthcheck.path='/primus?access_token=healthcheck&transport=polling'"
      - "traefik.backend.healthcheck.interval=10s"
      - "traefik.backend.healthcheck.timeout=2s"
      - "traefik.port=2333"
      - "traefik.protocol=http"
      - "traefik.enable=true"
    ports:
    - "2333"
```
