### ISSUE TITLE
Multiple ports with same host

### ISSUE THREAD

**Issue by tristanleboss** [containous/traefik#4186]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a container which exposes 2 ports: http 80 and https 443
Indeed, the web app should be available on both ports: I don't want to redirect from 80 to 443 like most examples found on Internet.

So, I read the documentation (https://docs.traefik.io/configuration/backends/docker/) and ended up with this:

```
docker run --detach \
--network backend \
--name "my_app.localhost" \
--label "traefik.frontend.rule=Host:my_app.localhost" \
--label "traefik.port=80" \
--label "traefik.protocol=http" \
--label "traefik.frontend.entryPoints=http" \
--label "traefik.backend=my_app-http" \
--label "traefik.https.frontend.rule=Host:my_app.localhost" \
--label "traefik.https.port=443" \
--label "traefik.https.protocol=https" \
--label "traefik.https.frontend.entryPoints=https" \
--label "traefik.https.backend=my_app-https" \
my_image

```

### What did you expect to see?

I was expecting to have 2 frontends and 2 backends: one for https and one for http.

### What did you see instead?

I just see the https frontend and the https backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# API and dashboard configuration
################################################################
[api]
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "docker.local"
watch = true
```

Traefik is started this way:

```
docker run --detach \
--publish 8080:8080 \
--publish 443:443 \
--publish 80:80 \
--network backend \
--name traefik.localhost \
--restart always \
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume C:\DockerData\Traefik\traefik.toml:/etc/traefik/traefik.toml \
traefik \
--entrypoints='Name:http Address::80' \
--entrypoints='Name:https Address::443 TLS' \
--defaultentrypoints=http,https \
--logLevel=DEBUG
````
