### ISSUE TITLE
Regression on kubernetes headless service backend

### ISSUE THREAD

**Issue by kpichardie** [containous/traefik#4193]
Hi,

I see a regression on traefik as ingress controller on 1.7.X to 1.7.4.

I was able to use traefik as ingress controller to point on a headless service on traefik 1.6.5, but in 1.7.X it seems that traefik isn't able to recognise the endpoint behind the service. 

Here is the sample of declaration of my endpoint, service, ingress and ingress-controller :

``` 
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: test
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: http
  namespace: test
  labels:
    app: http
subsets:
- addresses:
  - ip: 10.0.0.1
  - ip: 10.0.0.2
  ports:
  - name: http
    port: 80
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-http
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: test.mydomain.test
    http:
      paths:
      - path: /
        backend:
          serviceName: http
          servicePort: 80

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-controller
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-controller
        name: traefik-ingress-controller
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: "traefik:1.7.4"
        name: traefik-ingress-controller
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        ports:
        - containerPort: 80
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
        - --kubernetes.namespaces=test
```

In versions 1.7.X the backend is shown as red and appears as "Service Unavailable".
With this configuration but image version 1.6.5, there is no problem, traefik correctly route the traffic to my service and reference the two endpoints. 

I see a difference in logs that could help.
In 1.6.X :
```
time="2018-11-13T14:01:38Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":[\"test\"],\"LabelSelector\":\"\",\"IngressClass\":\"\"}"
```
In 1.7.X :
```
time="2018-11-13T14:28:37Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":[\"test\"],\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null}"
```

For services managed buy kubernetes i have no issues, only headless service is not working in 1.7.X.

Best regards,
Kévin

**Comment by nmengin** [comment]
Hello @kpichardie .

Many thanks for your interest in the project.

Indeed, there is a regression we are going to fix quickly to implement correctly the K8s [endpoint specification](https://godoc.org/k8s.io/api/core/v1#EndpointPort).

By waiting the new bugfix version, as a workaround, you can set a `service.port.name` by using the same name you specified as `endpoint.port.name` (`http` in your example):

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: test
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    name: http
```

**Comment by kpichardie** [comment]
Hi @nmengin,

Ok thanks i will check if it's correctly working with port name. 

Thanks for quick reply.
Kévin

**Comment by nmengin** [comment]
Hello @kpichardie , after a deeper analyze, I can say that the way to configure the link between the `ServicePort` and the `EndpointPort` in Traefik before the version 1.7 was wrong.

By following the [Kubernetes specification about Headless services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services), the workaround I described is definitively the way to configure correctly your service.

Happy to see that it is OK for you know.
I close the issue which is, IMO, solved.

**Comment by charandas** [comment]
@nmengin are you sure about this? It's working for me on 1.7.4 without needing `ServicePort` and `EndpointPort` being the same. For me, the `ServicePort` is `grpc`, and `EndpointPort` is `http`.

Also on `kubectl get endpoints`, I get below:
```
apiVersion: v1
kind: Endpoints
subsets:
- addresses:
  - ip: 10.233.89.151
    nodeName: dev-k8s-node-04
    targetRef:
      kind: Pod
      name: traefik-lb-7fdff4b754-9f2qs
      namespace: kube-system
      resourceVersion: "34662414"
      uid: 8105c261-f7f4-11e8-8cc7-0050569a87bc
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
```

Here is my service:

```
apiVersion: v1
kind: Service
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 3000
    protocol: TCP
    targetPort: grpc
  selector:
    name: my-service
    role: service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Lastly, I remember reading months ago that `servicePort` in ingress definition needs to be `grpc` for GRPC services? Is that no longer true?

Because I tried renaming it to `http`, and it still works.
