### ISSUE TITLE
CipherSuite configuration does not seem to work correctly

### ISSUE THREAD

**Issue by mrkiii** [containous/traefik#4196]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I want to restrict the supported ciphersuites via my TOML

### What did you expect to see?

1. When using curl without cipher specification, that a valid negotiated cipher was negotiated
2. When using curl with one of the configured cipher specifications, that the specified cipher was negotiated
3. When using curl with a not-configured cipher specification, that the SSL handshake fails

### What did you see instead?
```
$ curl -v --location -H Host:mytest.xxx.nl --ciphers "dhe_dss_aes_128_cbc_sha" --tlsv1.2  https://mytest.xxx.nl
* About to connect() to mytest.xxx.nl port 443 (#0)
*   Trying 10.0.3.x...
* Connected to mytest.xxx.nl (10.0.3.x) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Operation timed out after 300798 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 300798 milliseconds with 0 out of 0 bytes received
```

Then I changed the configuration location from the TOMP to the docker-compose:
```
    command: --api --docker --entryPoints="TLS.CipherSuites:TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
```
and it worked as expected.

I reverted my docker-compose to:
```
 command: --api --docker --
```

and the cipherSuite section in the TOML to:
```
  cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384"
    ]
```

and it worked as expected.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  minVersion = "VersionTLS12"
  cipherSuites = [
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
  ]
    <certificate section here>
```

docker compose file
```
version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./ssl:/ssl

  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Host:mytest.xxxx.nl"
      - "traefik.enable=true"
      - "traefik.port=80"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
$ docker compose up
....
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Wiring frontend frontend-Host-reverse-proxy-traefik-0 to entryPoint https"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating backend backend-reverse-proxy-traefik"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-reverse-proxy-traefik-0"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating load-balancer wrr"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating server server-traefik-reverse-proxy-1-88f9d9f951dd584cd0a102fa8e4dc8ff at http://172.20.0.2:80 with weight 1"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating route route-frontend-Host-reverse-proxy-traefik-0 Host:reverse-proxy.traefik"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Wiring frontend frontend-Host-reverse-proxy-traefik-0 to entryPoint http"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating backend backend-reverse-proxy-traefik"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-reverse-proxy-traefik-0"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating load-balancer wrr"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating server server-traefik-reverse-proxy-1-88f9d9f951dd584cd0a102fa8e4dc8ff at http://172.20.0.2:80 with weight 1"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=debug msg="Creating route route-frontend-Host-reverse-proxy-traefik-0 Host:reverse-proxy.traefik"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=info msg="Server configuration reloaded on :8080"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=info msg="Server configuration reloaded on :80"
reverse-proxy_1  | time="2018-11-14T14:32:27Z" level=info msg="Server configuration reloaded on :443"
```
