### ISSUE TITLE
Traefik doesn't seem to renew wild card certificates when provider changes

### ISSUE THREAD

**Issue by svyotov** [containous/traefik#4216]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Use the staging Let's encrypt URl
```
caServer = "https://acme-staging.api.letsencrypt.org/directory"
```
and then switch to the production one
```
caServer = "https://acme-v02.api.letsencrypt.org/directory"
```

### What did you expect to see?

The certificate to get renewed for the production ACME provider

![image](https://user-images.githubusercontent.com/29090864/48859018-3cd51700-edbd-11e8-998a-bb51fcde422f.png)

### What did you see instead?

The certificate did not get renewed.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Enable ACME (Let's Encrypt): automatic SSL.
[acme]
email = "user@dmain.com"
storage = "traefik/acme/account" 
entryPoint = "https"
acmeLogging =  true
caServer = "https://acme-staging.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
  provider =  "route53"
[[acme.domains]]
   main = "*.domain.com"
   sans = ["domain.com"]
```
with etcd as KV store.
