### ISSUE TITLE
Bind all missing frontends rules to custom error pages

### ISSUE THREAD

**Issue by guillaumebriday** [containous/traefik#4218]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I wish we could use the custom error pages for all missing frontends rules. It could be very useful when Traefik is used for review apps and dynamic subdomains.

For exemple:

https://existing-frontend.example.org should work as usual

but

https://not-existing-frontend.example.org should use 404 custom page on another server.

Maybe a configuration like that : 

```toml
 [frontends.*]
   [errors]
     [error.network]
     status = "[500-600]"
     backend = "error"
     query = "/{status}.html"
     rule = "Host: website.mydomain.com"
```

Thank you in advance !
