### ISSUE TITLE
[Kubernetes] Custom HostRegexp ingress

### ISSUE THREAD

**Issue by kesslerdev** [containous/traefik#4219]
### Do you want to request a *feature* or report a *bug*?

Feature Custom HostRegexp rule on kubernetes ingress

### What did you expect to see?

when a `*` is present on host traefik replace by a regex
(`*.domain.tld` => `{subdomain:[A-Za-z0-9-_]+}.domain.tld`)

but on kubernetes, wildcard can be only on a subdomain: `*.domain.tld` 
but i need a `*-someparam.domain.tld` Host

it can be fixed with an annotation to support all request [matchers](https://docs.traefik.io/basics/#matchers)

**Comment by dtomcej** [comment]
This is an upstream issue of https://github.com/kubernetes/kubernetes/issues/41881.

The k8s validator does not allow wildcards as regexes. They are treated as DNS wildcards, providing they are properly formatted.

The ingress spec requires a FQDN for the host. `*.example.com` works, but `*-test.example.com` is not a valid DNS record.

**Comment by kesslerdev** [comment]
i'm ok for wildcard usage in host part of ingress, 
but no annotations can alter matchers (in order to customize HostRegexp rule)

**Comment by ayosec** [comment]
> The k8s validator does not allow wildcards as regexes. They are treated as DNS wildcards, providing they are properly formatted.

Could be possible to set the regular expression using annotations?

For example,

```yaml
metadata:
  annotations:
    traefik.frontend.host.regexp: foo.bar.{subdomain:.*}
spec:
  rules:
  - host: foo.bar.subdomain
    http:
      paths:
      - path: "/"
        backend:
          serviceName: foo-bar
          servicePort: http
```
