### ISSUE TITLE
Entrypoint open connections metric reports phantom connections

### ISSUE THREAD

**Issue by erhudy** [containous/traefik#4226]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Prometheus metrics for a given Traefik instance often indicate there are open connections on the entrypoint that don't exist, confirmed by `lsof`.

### What did you expect to see?

The numbers in the Prometheus metrics should match the current activity.

### What did you see instead?

The Prometheus metrics indicate the presence of phantom connections. See Prometheus output from a cluster below which indicates 5 open connections on one instance and 1 on another:
```
traefik_entrypoint_open_connections{entrypoint="https",instance="api-xyz:6443",job="kubernetes-pods-xyz",kubernetes_namespace="kube-system",kubernetes_pod_controller_kind="DaemonSet",kubernetes_pod_controller_name="traefik-ingress-controller",kubernetes_pod_name="traefik-ingress-controller-fts2g",method="TRACK",protocol="http"}	2
traefik_entrypoint_open_connections{entrypoint="http",instance="api-xyz:6443",job="kubernetes-pods-xyz",kubernetes_namespace="kube-system",kubernetes_pod_controller_kind="DaemonSet",kubernetes_pod_controller_name="traefik-ingress-controller",kubernetes_pod_name="traefik-ingress-controller-r48zm",method="TRACE",protocol="http"}	1
traefik_entrypoint_open_connections{entrypoint="https",instance="api-xyz:6443",job="kubernetes-pods-xyz",kubernetes_namespace="kube-system",kubernetes_pod_controller_kind="DaemonSet",kubernetes_pod_controller_name="traefik-ingress-controller",kubernetes_pod_name="traefik-ingress-controller-fts2g",method="GET",protocol="http"}	1
traefik_entrypoint_open_connections{entrypoint="https",instance="api-xyz:6443",job="kubernetes-pods-xyz",kubernetes_namespace="kube-system",kubernetes_pod_controller_kind="DaemonSet",kubernetes_pod_controller_name="traefik-ingress-controller",kubernetes_pod_name="traefik-ingress-controller-fts2g",method="POST",protocol="http"}	1
traefik_entrypoint_open_connections{entrypoint="https",instance="api-xyz:6443",job="kubernetes-pods-xyz",kubernetes_namespace="kube-system",kubernetes_pod_controller_kind="DaemonSet",kubernetes_pod_controller_name="traefik-ingress-controller",kubernetes_pod_name="traefik-ingress-controller-fts2g",method="GET",protocol="websocket"}	 1
```

Now compare to `lsof` output of the Traefik process corresponding to **traefik-ingress-controller-fts2g**:

```
$ sudo lsof -p $(pgrep traefik)
COMMAND    PID USER   FD      TYPE    DEVICE SIZE/OFF     NODE NAME
traefik 156241 root  cwd       DIR     0,111      127        2 /
traefik 156241 root  rtd       DIR     0,111      127        2 /
traefik 156241 root  txt       REG     0,111 67387168       25 /traefik
traefik 156241 root    0r     FIFO      0,10      0t0 17261110 pipe
traefik 156241 root    1w     FIFO      0,10      0t0 17261111 pipe
traefik 156241 root    2w     FIFO      0,10      0t0 17261112 pipe
traefik 156241 root    3u     IPv6  17373888      0t0      TCP *:https (LISTEN)
traefik 156241 root    4u  a_inode      0,11        0    12178 [eventpoll]
traefik 156241 root    5u     IPv6  17373889      0t0      TCP *:http (LISTEN)
traefik 156241 root    6u     IPv6  17373890      0t0      TCP *:9301 (LISTEN)
traefik 156241 root    8u     IPv4  17401391      0t0      TCP node-1:45568->10.96.0.1:https (ESTABLISHED)
traefik 156241 root    9u     IPv6 116863254      0t0      TCP node-1:https->node-2:51700 (ESTABLISHED)
traefik 156241 root   10u     IPv4 116863256      0t0      TCP node-1:44468->kube-state-metrics:http-alt (ESTABLISHED)
traefik 156241 root   12u     IPv6 320210977      0t0      TCP node-1:9301->node-3:38950 (ESTABLISHED)
```

`lsof` here indicates, in order:
* a connection with the Kubernetes API server
* a connection with the Prometheus scrape server (probably scraping KSM through an ingress)
* a connection with kube-state-metrics
* a connection with the Kubernetes API server for metrics scraping

Other Traefik instances in different Kubernetes clusters show similar behavior, but the count and disposition of open connections being reported in the Prometheus metrics varies. As I write this, another 2 clusters with similar configuration to the one I pulled metrics from above are each showing 1 consistently open connection (all are being monitored identically from the same Prometheus instance).

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.0
Codename:     maroilles
Go version:   go1.11
Built:        2018-09-24_09:57:21AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[traefikLog]

[accessLog]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.metrics]
    address = ":9301"

  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"

[kubernetes]

[lifecycle]
  requestAcceptGraceTimeout = "10s"
  graceTimeOut = "7200s"

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

N/A
