### ISSUE TITLE
[Kuberbetes]  Allow to set custom headers on specific paths in ingress

### ISSUE THREAD

**Issue by osamamaruf** [containous/traefik#4228]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
ATM annotations cannot be applied on specific paths like e.g. `	ingress.kubernetes.io/custom-response-headers` . For example take the case of applying `cache-control` headers on static resources like .js, .png files.
We can 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-ingress
  namespace: abc
  annotations:
    kubernetes.io/ingress.class: 'traefik'    
	ingress.kubernetes.io/custom-response-headers: Cache-Control: private || Cache-Control: max-age=31536000
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /abc1
        backend:
          serviceName: sabc1
          servicePort: 443
      - path: /abc2
        backend:
          serviceName: sabc2
          servicePort: 443
```

However the headers will be applied to all the paths.  If possible we can apply a regex before specifying the each header to indicate on what files the header should be applied. If no regex is defined then it should apply on all something like this 
```
  annotations:
    kubernetes.io/ingress.class: 'traefik'    
	ingress.kubernetes.io/custom-response-headers: (.js|.png)$ Cache-Control: private || (.js|.png)$ Cache-Control: max-age=31536000
```
would be good.

Further it would be great if this can be applied to specific path e.g.

```
- path: /abc1
        annotations:
          ingress.kubernetes.io/custom-response-headers: annotation for specific path
        backend:
          serviceName: sabc1
          servicePort: 443

```

**Comment by izern** [comment]
mark

**Comment by codeman9** [comment]
I would also like a feature like this, but so that I can support custom request headers while doing `service-weights`. If the `ingress.kubernetes.io/custom-[response,request]-headers` was of type `map[string]map[string]string`, then traefik could support something like:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-ingress
  namespace: abc
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    ingress.kubernetes.io/custom-response-headers: |
        sabc1: X-Custom-Response-Header:sabc1
        sabc2: X-Custom-Response-Header:sabc2
    ingress.kubernetes.io/custom-request-headers: |
        sabc1: X-Custom-Host-Header:sabc1.namespace1.svc.cluster.local
        sabc2: X-Custom-Host-Header:sabc2.namespace2.svc.cluster.local
    traefik.ingress.kubernetes.io/service-weights |
        sabc1: 25%
        sabc2: 75%
spec:
  rules:
  - host: mydomain.com
    http:
      paths:
      - path: /abc1
        backend:
          serviceName: sabc1
          servicePort: 443
      - path: /abc1
        backend:
          serviceName: sabc2
          servicePort: 443
```

because the ingress object can define multiple services in one, it seems to make sense that different headers could be provided to/from each service differently. The key for me is to be able to specify a different custom host header per service so that the next downstream proxy can route accordingly.
