### ISSUE TITLE
can not use multi frontend rule in a swarm service

### ISSUE THREAD

**Issue by dennis0721** [containous/traefik#4242]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

i used traefik with a docker swarm cluster, and i want to set multi frontend rule to a backend service, my config looks like:
<img width="1146" alt="20181128171455" src="https://user-images.githubusercontent.com/23226155/49141570-df4b4800-f331-11e8-859c-99ff0356163e.png">
but, when i set both Host and PathPrefixStrip rules, no one worked

### What did you expect to see?
i hope i can visit my backend service with Host rule or PathPrefixStrip rule

### What did you see instead?
if i set both, no one worked; but, if i remove anyone, the other one worked

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

debug = false

logLevel = "INFO"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]

[ping]

[docker]
endpoint = "tcp://10.0.1.72:2376"
domain = "traefik"
exposedByDefault = true
watch = true
swarmMode = true
network = "traefik"
  [docker.tls]
  ca = "/etc/ssl/ca.pem"
  cert = "/etc/ssl/cert.pem"
  key = "/etc/ssl/key.pem"
  insecureskipverify = true

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
