### ISSUE TITLE
Traefik killed by OOM killer in Kubernetes

### ISSUE THREAD

**Issue by coufalja** [containous/traefik#4245]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Running Traefik as Deployment (ingress controller) in K8s
- Having bunch of Services targeting no Pods (thus having no related Endpoints object)
- Our setup is specific in way that we downscale tens of deployments to 0 on some schedule to not waste resources of K8s cluster.
 
### What did you expect to see?

- Traefik to work and reply with error when tried to access such a service

### What did you see instead?

- Traefik leaking memory and eventually being killed by OOM killer

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.proxyProtocol]
        trustedIPs = ["xxxx"]
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.proxyProtocol]
        trustedIPs = ["xxxx"]
        [entryPoints.https.tls]
        minVersion = "VersionTLS11"
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
          "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
          "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
          "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
          "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
        ]
    [respondingTimeouts]
      idleTimeout = "900s"
    [lifeCycle]
      requestAcceptGraceTimeout = "10s"
      graceTimeOut = "10s"
    [api]
    [rest]
    [kubernetes]
    [kubernetes.ingressEndpoint]
      hostname = "xxxx.xxxx"
    [metrics]
      [metrics.prometheus]
    [accessLog]
```

### Logs
```
time="2018-11-28T11:44:33Z" level=warning msg="Endpoints not available for xxx"
time="2018-11-28T11:44:33Z" level=warning msg="Endpoints not available for xxx"
time="2018-11-28T11:44:33Z" level=warning msg="Endpoints not available for xxx"
```
Tons of those ^

I suspect it being a memory leak in watcher watching the Services/Endpoints as this memory growth is specific just in this case, on our other clusters where we don't downscale Deployments like this Traefik works just fine.
