### ISSUE TITLE
Memory error when creating wildcard acme certificate

### ISSUE THREAD

**Issue by jostrander** [containous/traefik#4250]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I enabled acme wildcard certs at startup in Traefik using a custom build of traefik-alpine by rawmind0. 

### What did you expect to see?

I expected the acme challenge to succeed and provide a working wildcard ssl certificate. 

### What did you see instead?

The request starts to work, creates the text entries in Cloudflare, then fails with a stack trace when fetching the result:

```
11/29/2018 12:11:24 AMtime="2018-11-29T05:11:24Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
11/29/2018 12:11:24 AMtime="2018-11-29T05:11:24Z" level=error msg="Stack: goroutine 53 [running]:
runtime/debug.Stack(0x265ea80, 0x17, 0xc0014bade0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x21e5ca0, 0x4551d40)
	/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89
github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc000557b68)
	/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
panic(0x21e5ca0, 0x4551d40)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/cloudflare.(*DNSProvider).Present(0xc0009fe200, 0xc0000a7260, 0xe, 0xc0000a3aa0, 0x2b, 0xc000a523c0, 0x57, 0x0, 0xc0005573f8)
	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/cloudflare/cloudflare.go:134 +0x3ca
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*dnsChallenge).PreSolve(0xc000750300, 0xc0000cc300, 0x71, 0xc0000a72a8, 0x6, 0xc0000a72b0, 0x7, 0xc0000a3aa0, 0x2b, 0x0, ...)
	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:102 +0x17d
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).solveChallengeForAuthz(0xc0001b4000, 0xc00013c0c0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:603 +0x3c6
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).ObtainCertificate(0xc0001b4000, 0xc000813120, 0x2, 0x2, 0xc000557b01, 0x0, 0x0, 0xc000557b00, 0x42b1f2, 0x8, ...)
	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:437 +0x2b3
github.com/containous/traefik/provider/acme.obtainCertificateWithRetry.func1(0xc000000008, 0x2714770)
	/go/src/github.com/containous/traefik/provider/acme/provider.go:487 +0x76
github.com/containous/traefik/safe.OperationWithRecover.func1(0x0, 0x0)
	/go/src/github.com/containous/traefik/safe/routine.go:160 +0x62
github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc0007406f0, 0x2951d20, 0xc00073cea0, 0x2714448, 0xc0003c5d00, 0xe)
	/go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37 +0xa2
github.com/containous/traefik/provider/acme.obtainCertificateWithRetry(0xc000813120, 0x2, 0x2, 0xc0001b4000, 0x1bf08eb000, 0x77359400, 0x1, 0x2, 0x2, 0x2)
	/go/src/github.com/containous/traefik/provider/acme/provider.go:501 +0x193
github.com/containous/traefik/provider/acme.(*Provider).resolveCertificate(0xc000293290, 0xc0003c5ca0, 0x10, 0xc00082c010, 0x1, 0x1, 0x1f53701, 0x0, 0x0, 0x0)
	/go/src/github.com/containous/traefik/provider/acme/provider.go:411 +0x3ba
github.com/containous/traefik/provider/acme.(*Provider).Provide.func1()
	/go/src/github.com/containous/traefik/provider/acme/provider.go:186 +0x72
github.com/containous/traefik/safe.GoWithRecover.func1(0x2714778, 0xc00082c040)
	/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
created by github.com/containous/traefik/safe.GoWithRecover
	/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
"
11/29/2018 12:11:24 AMtime="2018-11-29T05:11:24Z" level=error msg="Error obtaining certificate: panic in operation: %!s(<nil>)"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
bash-4.4$ traefik version
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
debug = false
logLevel = "INFO"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]
sendAnonymousUsage = true

[traefikLog]
  filePath = "/opt/traefik/log/traefik.log"

[accessLog]
  filePath = "/opt/traefik/log/access.log"

[respondingTimeouts]
  readTimeout = "0s"
  writeTimeout = "0s"
  idleTimeout = "180s"

[forwardingTimeouts]
  dialTimeout = "30s"
  responseHeaderTimeout = "0s"

[lifecycle]
  requestAcceptGraceTimeout = "0s"
  graceTimeOut = "10s"

[entryPoints]
  [entryPoints.traefik]
    address = ":8000"
    compress = true
  [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      MinVersion = "VersionTLS12"

        [[entryPoints.https.tls.certificates]]
          certFile = "/run/secrets//traefik.crt"
          keyFile = "/run/secrets//traefik.key"

        [[entryPoints.https.tls.certificates]]
          certFile = "/run/secrets//domain1-old.com.crt"
          keyFile = "/run/secrets//domain1-old.com.key"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = false
  [api.statistics]
    RecentErrors = 10

[rest]
  entryPoint = "traefik"

[ping]
  entryPoint = "traefik"


[rancher]
  domain = "rancher.internal"
  Watch = true
  RefreshSeconds = 15
  ExposedByDefault = false
  EnableServiceHealthFilter = false
  [rancher.api]
    Endpoint = "****"
    AccessKey = "****"
    SecretKey = "*****"


[acme]
  email = "me@myemail.com"
  storage = "/opt/traefik/acme/acme.json"
  OnHostRule = false
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  entryPoint = "https"
  acmeLogging = true
  [acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0
    [[acme.domains]]
      main = "*.workingdomain.com"
      sans = ["workingdomain.com"]
    [[acme.domains]]
      main = "*.domain2notworking.com"
      sans = ["domain2notworking.com"]
```
