### ISSUE TITLE
I want to route with kubernetes and traefik for more header information or specific IP

### ISSUE THREAD

**Issue by vperson** [containous/traefik#4259]
When launching a new APP we need an environment that is completely consistent with the online environment, except, of course, that our back-end APP version is up to date. At this time we do not want users to access our application, want to set the header information or IP to do traffic cutting. In kubernetes, I can use the same ing binding to bind different servicename, servicename A followed by the old service, and servicename B followed by the new service. All are accessed using api.xxx.com.

This is what I saw in aliyun's help document

![aliyun](https://help.aliyun.com/document_detail/85948.html?spm=5176.10695662.1996646101.searchclickresult.633831c6SQluBz)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gray-release
  annotations:
    # 请求头中满足正则匹配foo=bar的请求才会被路由到新版本服务new-nginx中
    #nginx.ingress.kubernetes.io/service-match: | 
    #  new-nginx: header("foo", /^bar$/)
    nginx.ingress.kubernetes.io/service-weight: |
        new-nginx: ${NEW_PER}, old-nginx: ${OLD_PER}
spec:
  rules:
  - host: www.example.com
    http:
      paths:
      # 老版本服务
      - path: /
        backend:
          serviceName: old-nginx
          servicePort: 80
      # 新版本服务
      - path: /
        backend:
          serviceName: new-nginx
          servicePort: 80
```

Can see that he has a configuration
```
    #nginx.ingress.kubernetes.io/service-match: | 
    #  new-nginx: header("foo", /^bar$/)
```
