### ISSUE TITLE
Add the ability to configure global-default-backend

### ISSUE THREAD

**Issue by lukibahr** [containous/traefik#4266]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?

I've got a wildcard dns and wildcard ssl certificate, let's call it "example.company.com" running on a single master/worker instance, for testing purposes. 

I've got three ingresses with applications to publish: frontend, backend and the dashboard ingress of traefik. 
```console
$ kubectl get ingresses --all-namespaces
NAMESPACE     NAME               HOSTS                       ADDRESS   PORTS   AGE
dev   backend-ingress    backend.example.company.com              80      96m
dev   frontend-ingress   frontend.example.company.com             80      77m
kube-system   traefik-web-ui     traefik.example.company.com              80      107s
```
Applying those, results in the following error message, prompted in the traefik ingress controller pod:
```
time="2018-12-03T16:34:05Z" level=error msg="Error creating global backend for ingress dev/frontend-ingress: duplicate frontend: global-default-frontend"
time="2018-12-03T16:34:05Z" level=error msg="Error creating global backend for ingress dev/frontend-ingress: duplicate frontend: global-default-frontend"
```

Having a look at the backends and frontends of the traefik dashboard, I'll notice that they're flapping and the global-default-frontend is in error state. I see no way to configure the global-default-backend either.

Kind regards

### What did you expect to see?

Ingress resources can be created

### What did you see instead?

Error message
```
time="2018-12-03T16:34:05Z" level=error msg="Error creating global backend for ingress dev/frontend-ingress: duplicate frontend: global-default-frontend"
time="2018-12-03T16:34:05Z" level=error msg="Error creating global backend for ingress dev/frontend-ingress: duplicate frontend: global-default-frontend"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
"Image": "sha256:3d6a43085f4ffcfa837f011000682b678cc1d1081c1e24573475d57ecf93f0e5",
"Labels": {
                "org.label-schema.description": "A modern reverse-proxy",
                "org.label-schema.docker.schema-version": "1.0",
                "org.label-schema.name": "Traefik",
                "org.label-schema.url": "https://traefik.io",
                "org.label-schema.vendor": "Containous",
                "org.label-schema.version": "v1.7.4"
            }
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
data:
  traefik.toml: |-
    InsecureSkipVerify = true 
    defaultEntryPoints = ["http","https"]
    #logLevel = "DEBUG" # Debug Log Level 
    [kubernetes]
    [api]
    address = ":8081"
    dashboard = true
    #Config to redirect http to https
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        #[entryPoints.http.redirect]
        #entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        compress = true
        [entryPoints.https.tls] 
          [[entryPoints.https.tls.certificates]]
          certFile = "/etc/traefik/ssl/tls.crt"
          keyFile = "/etc/traefik/ssl/tls.key"
    [accessLog]
```

**Comment by lukibahr** [comment]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: traefik    
spec:
  backend:
    serviceName: backend-service
    servicePort: 8081
  rules:
  - host: backend.company.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: backend-service
          servicePort: 8081

```

and the second ingress here: 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: traefik

spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
  rules:
  - host: frontend.company.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 80
```

both ingresses will be deployed via kubectl apply -f ingress.yaml --namespace=development
