### ISSUE TITLE
Traefik-consul failed to get the key and values with docker swarm

### ISSUE THREAD

**Issue by RamjiVE** [containous/traefik#4278]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to deploy a traefik stack on docker with consul as a key / value store. My cluster is made of three nodes (three masters) :

Following this documentation, traefik works perfectly for docker swarm https://docs.traefik.io/user-guide/cluster-docker-consul/ Certificates are created and I can route to different services also. No issues at all. But in consul , I could not find any key values and it is empty as seen below. When I click the docker option as below, I can see all services being listed.
Kindly let me know if there any additions configs that I have to perfrom.

### What did you expect to see?
The values get stored in the consul

### What did you see instead?
Empty values at the consul
https://stackoverflow.com/questions/53667041/traefik-consul-failed-to-get-the-key-and-values-with-docker-swarm

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.5

```

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
# version: "3.2"
services:
  traefik_init:
    image: traefik:1.5
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=foobar@example.com"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=mycompany.com"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul
  traefik:
    image: traefik:1.5
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik

networks:
  webgateway:
    driver: overlay
    external: true
  traefik:
    driver: overlay

volumes:
  consul-data:
      driver: local
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] serf: EventMemberJoin: 636badc2c448 10.0.9.127
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/05 10:54:36 [INFO] raft: Node at 10.0.5.7:8300 [Leader] entering Leader state
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/05 10:54:36 [INFO] consul: cluster leadership acquired
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/05 10:54:36 [INFO] consul: New leader elected: 053068134e4b
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] consul: Handled member-join event for server "636badc2c448.us_east2" in area "wan"
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] consul: Adding LAN server 636badc2c448 (Addr: tcp/10.0.9.127:8300) (DC: us_east2)
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/05 10:54:36 [INFO] consul: member '053068134e4b' joined, marking health alive
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] agent: Started DNS server 10.0.9.127:8600 (udp)
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] agent: Started DNS server 10.0.9.127:8600 (tcp)
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/05 10:54:37 [INFO] agent: Synced node info
traefik_consul.1.vx3sp9vvv5zc@example1100    | ==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=40feeaea-1ebd-e2a2-009d-312ad3acd2aa&version=1.4.0: dial tcp: lookup checkpoint-api.hashicorp.com on 127.0.0.11:53: no such host
traefik_consul.1.vx3sp9vvv5zc@example1100    | ==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=40feeaea-1ebd-e2a2-009d-312ad3acd2aa&version=1.4.0: dial tcp: lookup checkpoint-api.hashicorp.com on 127.0.0.11:53: no such host
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] agent: Started HTTP server on 10.0.9.127:8500 (tcp)
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: Caught signal:  terminated
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:28:58 [INFO] agent: started state syncer
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:06 [ERR] agent: failed to sync remote state: No cluster leader
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: Graceful shutdown disabled. Exiting
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [WARN] raft: Heartbeat timeout from "" reached, starting election
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: Requesting shutdown
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] consul: shutting down server
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [INFO] raft: Node at 10.0.9.127:8300 [Candidate] entering Candidate state in term 2
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [WARN] serf: Shutdown without a Leave
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [WARN] serf: Shutdown without a Leave
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [INFO] raft: Election won. Tally: 1
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] manager: shutting down
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [INFO] raft: Node at 10.0.9.127:8300 [Leader] entering Leader state
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: consul server down
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: shutdown complete
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [INFO] consul: cluster leadership acquired
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: Stopping DNS server 10.0.5.7:8600 (tcp)
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [INFO] consul: New leader elected: 636badc2c448
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:07 [INFO] consul: member '636badc2c448' joined, marking health alive
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: Stopping DNS server 10.0.5.7:8600 (udp)
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:47 [INFO] agent: Stopping HTTP server 10.0.5.7:8500 (tcp)
traefik_consul.1.q7egi9lzz6e9@example1099    |     2018/12/07 09:29:08 [INFO] agent: Synced node info
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:48 [WARN] agent: Timeout stopping HTTP server 10.0.5.7:8500 (tcp)
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:48 [INFO] agent: Waiting for endpoints to shut down
traefik_consul.1.q7egi9lzz6e9@example1099    | ==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=6568c199-30b7-ba60-5c35-470a72c434ba&version=1.4.0: dial tcp: lookup checkpoint-api.hashicorp.com on 127.0.0.11:53: no such host
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:48 [INFO] agent: Endpoints down
traefik_consul.1.vx3sp9vvv5zc@example1100    |     2018/12/07 09:28:48 [INFO] agent: Exit code: 1

```
