### ISSUE TITLE
[Kubernetes] If a "tls" section is specified in an Ingress, but a secret is not specified, Traefik will fail to load the Ingress

### ISSUE THREAD

**Issue by DrEsteban** [containous/traefik#4280]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We deployed Traefik with a "default certificate" specified, so that we didn't have to specify a TLS cert on every Ingress resource.  (We have a wildcard TLS cert so we'd prefer to just specify in one place - at the Traefik level.)  Our Ingress `spec` sections look like the following:

```yaml
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
        <paths...>
  tls:
  - hosts:
    - foo.bar.com
```
^ Notice the "tls" section, which simply has the host listed but not any secret info. This is because we are relying on the default certificate.

### What did you expect to see?

Traefik would load the Ingress rule, and would present its default certificate since a different one wasn't specified in the Ingress.  For reference, this works as expected with the Nginx Ingress controller.

### What did you see instead?

Traefik error logs:
```
{"level":"error","msg":"Error configuring TLS for ingress mynamespace/myservice: secret mynamespace/ does not exist","time":"2018-12-07T19:38:38Z"}
```
^Notice the empty secret name.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.5
Codename:     maroilles
Go version:   go1.11.2
Built:        2018-12-03_11:01:00AM
OS/Arch:      linux/amd64
```
(Note, also repros on v1.7.4)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
      permanent = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
      ]
    [entryPoints.https.tls.defaultCertificate]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[kubernetes]
[traefikLog]
  format = "json"
[api]
  entryPoint = "traefik"
  dashboard = true
```
