### ISSUE TITLE
traefik:1.7.4 stops detecting/watching docker changes without error

### ISSUE THREAD

**Issue by thetheodoros** [containous/traefik#4287]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I started traefik with a docker-compose.yml like this:
```yml
version: '3.6'
services:
  traefik:
    image: traefik:1.7.4
    command: --docker
    restart: always
    networks:
      - web
      - fe
      - core
      - neo4j
      - soap
      - adapter
    ports:
      - 80:80
      - 443:443
      - 7474:7474
      - 7687:7687
    labels:
      - "traefik.frontend.rule=Host:traefik.domain.com"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH_USERS}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
    container_name: traefik
networks:
  web:
    external: true
  core:
    external: true
  fe:
    external: true
  neo4j:
    external: true
  soap:
    external: true
  adapter:
    external: true
```

after about 4 weeks running, it stopped detecting new rules but keeps working for existing rules.
### What did you expect to see?

traefik detecting new rules.

### What did you see instead?

traefik being stuck with old rules where the origin container having those rules was removed already and new containers with new rules aren't being detected.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
   [entryPoints.https.tls]
  [entryPoints.bolt]
  address = ":7687"
  [entryPoints.neo]
  address = ":7474"
[accessLog]

[retry]

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "domain.com"
  watch = true
  exposedbydefault = false
[acme]
  email = "office@domain.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

no error output in the logs.
