### ISSUE TITLE
Recreate traefik/access log file if it was deleted from volume by someone instead of stopping logging.

### ISSUE THREAD

**Issue by Vinigas** [containous/traefik#4295]
### Do you want to request a *feature* or report a *bug*?

Minor bug

### What did you do?

Deleted file from filesystem where traefik do logs.

### What did you expect to see?

The deleted logging file getting recreated as empty file and logging continues normally.

### What did you see instead?

Traefik stops logging to the file until restarted.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.5
Codename:     maroilles
Go version:   go1.11.2
Built:        2018-12-03_11:01:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
  traefik_init:
    image: traefik:1.7.5
    command:
      storeconfig
      - --accesslog=true
      - --accesslog.bufferingsize=100000
      - --accesslog.fields=true
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers=false
      - --accesslog.fields.headers.defaultmode=keep
      - --accesslog.filepath=/mlog/maccesslog.log
      - --accesslog.filters=false
      - --accesslog.filters.minduration=0s
      - --accesslog.filters.retryattempts=false
      - --accesslog.format=json
<--some non related config cutted out-->
      - --sendanonymoususage=true
      - --traefiklog=true
      - --traefiklog.filepath=/mlog/mtraefiklog.log
      - --traefiklog.format=json
```
