### ISSUE TITLE
Not setting ingress address on AWS

### ISSUE THREAD

**Issue by nmiculinic** [containous/traefik#4300]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created ingress controller on AWS. Got 

```
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP                                                                  PORT(S)                                     AGE
traefik   LoadBalancer   10.233.52.166   adfbab98201d811e999b6029038839d8-2028404494.eu-central-1.elb.amazonaws.com   80:32756/TCP,443:30656/TCP,8080:32169/TCP   86m
```

Created ingress resource `test-ingress` with host `test.fn.kraken.hr`

### What did you expect to see?
```
NAME           HOSTS               ADDRESS                                                                     PORTS   AGE
test-ingress   test.fn.kraken.hr   adfbab98201d811e999b6029038839d8-2028404494.eu-central-1.elb.amazonaws.com  80      17m
```

### What did you see instead?

```
NAME           HOSTS               ADDRESS   PORTS   AGE
test-ingress   test.fn.kraken.hr             80      17m
```

missing address field. 

This presents problems further down the line for the `external-dns` since it cannot get the IP address which should populate the DNS server. See: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#which-service-and-ingress-controllers-are-supported

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker image: `traefik:1.7.4`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

AWS k8s

```toml
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
      [entryPoints.traefik]
      address = ":8080"
    [kubernetes]
    ingressClass = "traefik"
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
```

I've verified on the dashboard that traefik discovered the ingress resource.

Related:
https://github.com/kubernetes/ingress-nginx/issues/3567

https://github.com/containous/traefik/issues/3377 --> It says the release should make it 1.7, but it's not working in 1.7.4.
