### ISSUE TITLE
Using Custom Headers for frontend matching in Kubernetes Ingress fails

### ISSUE THREAD

**Issue by FireDrunk** [containous/traefik#4304]
### Do you want to request a *feature* or report a *bug*?

Bug (kind of)

### What did you do?

I'm trying to get the Azure Application Gateway to work in front of AKS with Traefik as the Ingress Controller.

<details>
<summary>Created a demo application with:</summary>

```yml
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
```

</details>

<details>
<summary>Created traefik ingress controller:</summary>

```yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
  type: LoadBalancer
```

</details>

<details>
<summary>And created the ingress rules with:</summary>

```yml
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/proxy-headers: X-Original-Host
spec:
  rules:
  - host: demo.cloud.eeplug.com
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-service
          servicePort: 80
```

</details>

### What did you expect to see?

The demo app.

### What did you see instead?
Traefik's 404

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.6 (MAROILLES)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Default Kubernetes Ingress from docs

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

<details>
<summary>logs</summary>

```shell
time="2018-12-17T16:12:15Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"demo.cloud.eeplug.com/\":{\"servers\":{\"demo-app-5c86b76b45-f6whb\":{\"url\":\"http://10.2.4.80:8080\",\"weight\":1},\"demo-app-5c86b76b45-fxfx5\":{\"url\":\"http://10.2.4.48:8080\",\"weight\":1},\"demo-app-5c86b76b45-rsp2k\":{\"url\":\"http://10.2.4.90:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"demo.cloud.eeplug.com/\":{\"entryPoints\":[\"http\"],\"backend\":\"demo.cloud.eeplug.com/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"demo.cloud.eeplug.com\":{\"rule\":\"Host:demo.cloud.eeplug.com\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2018-12-17T16:12:15Z" level=debug msg="Wiring frontend demo.cloud.eeplug.com/ to entryPoint http"
time="2018-12-17T16:12:15Z" level=debug msg="Creating backend demo.cloud.eeplug.com/"
time="2018-12-17T16:12:15Z" level=debug msg="Adding TLSClientHeaders middleware for frontend demo.cloud.eeplug.com/"
time="2018-12-17T16:12:15Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-17T16:12:15Z" level=debug msg="Creating server demo-app-5c86b76b45-rsp2k at http://10.2.4.90:8080 with weight 1"
time="2018-12-17T16:12:15Z" level=debug msg="Creating server demo-app-5c86b76b45-f6whb at http://10.2.4.80:8080 with weight 1"
time="2018-12-17T16:12:15Z" level=debug msg="Creating server demo-app-5c86b76b45-fxfx5 at http://10.2.4.48:8080 with weight 1"
time="2018-12-17T16:12:15Z" level=debug msg="Creating route demo.cloud.eeplug.com Host:demo.cloud.eeplug.com"
time="2018-12-17T16:12:15Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-17T16:12:15Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-17T16:12:15Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:15Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:17Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:17Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:18Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:18Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:19Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:19Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:20Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:20Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:21Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:21Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:22Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:22Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:23Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:23Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:24Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:24Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:25Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:25Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:26Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:26Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:27Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:27Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:28Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:28Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:29Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:29Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:30Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:30Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:31Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:31Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:32Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:32Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:33Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:33Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:34Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:34Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:35Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:35Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:36Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:36Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:37Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:37Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:38Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:38Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:39Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:40Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:40Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:41Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:41Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:42Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:42Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:43Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:43Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:44Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:44Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:45Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:45Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:46Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:46Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:47Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:47Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:48Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:48Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
I1217 16:12:49.306300   17128 log.go:172] http: proxy error: context canceled
time="2018-12-17T16:12:49Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:49Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:50Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:50Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:51Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:51Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:52Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:52Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:53Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:53Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:54Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:54Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:55Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:55Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:56Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:56Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:57Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:57Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:58Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-17T16:12:58Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
```

</details>
<br>
Probably the biggest issue is the Azure Application Gateway which is in front of Traefik. It uses a custom header to pass the "Host" variable. I've tried both kubernetes.io/proxy-headers: X-Original-Host and ingress.kubernetes.io/proxy-headers: X-Original-Host, no result.

I couldn't find anything regarding switching on a custom header in the default "Ingress" type in Kubernetes in the docs. So it's either a bug that the annotation doesn't work here, or a feature request.

I'm not sure...
