### ISSUE TITLE
ERR_BAD_SSL_CLIENT_AUTH_CERT in traefik:1.7.6

### ISSUE THREAD

**Issue by Finkes** [containous/traefik#4316]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I switched from using the docker image **traefik:1.7.5** to **traefik:1.7.6**. Then SSO client certificate authentication stopped working. I receive an **ERR_BAD_SSL_CLIENT_AUTH_CERT** error.

### What did you expect to see?
The client certificate should be accepted and my backend should be loaded.

### What did you see instead?
 **ERR_BAD_SSL_CLIENT_AUTH_CERT** error

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.6

```
traefik:1.7.6 docker image
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
        [entryPoints.https.tls.ClientCA]
        files = ["/app/CA.crt"]
        optional = true
        [[entryPoints.https.tls.certificates]]
        certFile = "/app/tls.crt"
        keyFile = "/app/tls.key"

[api]

[Docker]
swarmmode = true
watch = true
network = "traefik"
```
Docker Swarm stack:
(deploy with docker stack deploy -c stack.yml traefk
```yml
version: "3.3"
services:
  whoami:
    image: containous/whoami
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        traefik.port: '80'
        traefik.frontend.rule: 'Host: whoami.local'
        traefik.frontend.passTLSClientCert.infos.sans: 'true'
        traefik.frontend.passTLSClientCert.infos.subject.commonName: 'true'
        traefik.frontend.passTLSClientCert.infos.subject.country: 'true'
        traefik.frontend.passTLSClientCert.infos.subject.locality: 'true'
        traefik.frontend.passTLSClientCert.infos.subject.country: 'true'
        traefik.frontend.passTLSClientCert.infos.subject.organization: 'true'
        traefik.frontend.passTLSClientCert.pem: 'true'
  traefik-test:
    image:  traefik:1.7.6
    deploy:
      replicas: 1
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: ingress
    - target: 443
      published: 443
      protocol: tcp
      mode: ingress
    - target: 8080
      published: 8080
      protocol: tcp
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/CA.crt:/app/CA.crt
      - ./certs/tls.cert:/app/tls.crt
      - ./certs/tls.key:/app/tls.key
      - ./traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik

networks:
  traefik:
```

Also make sure to point whoami.local to 127.0.0.1 (e.g. on Mac OS: /etc/hosts)
You also need your own client certificate CA and a TLS cert & key

open https://whoami.local to see the issue.

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
