### ISSUE TITLE
K8s - enable app root on ingress without explicit root path

### ISSUE THREAD

**Issue by doctori** [containous/traefik#4322]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

taking this ingress : 
```yaml   
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  anotations:
      traefik.ingress.kubernetes.io/app-root: /my-app/login
  name: cheese
spec:
  rules:
  - host: stilton.minikube
    http:
      paths:
      - backend:
          serviceName: stilton
          servicePort: http
```
when `GET /` I should expect to have a `302` (or `301`) redirect to `/my-app/login`  
today (`traefik 1.7.5`) we have a `200` (or whatever the application behind respond)  

I guess it's linked to this condition : 
https://github.com/containous/traefik/blob/9203ba5f950c306f2c58cc20b9f90381c056450d/provider/kubernetes/kubernetes.go#L906

Is it possible to handle empty path ?  
Given the K8 documentation : 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#httpingresspath-v1beta1-extensions  
`Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend.`  
It's not a major request but it would be a nice to have :)  
It's working fine when adding explicitly the path.  

Thank you for your great work on Traefik.
