### ISSUE TITLE
kubernetes reloading configuration

### ISSUE THREAD

**Issue by monester** [containous/traefik#4333]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've added traefik as a default ingress in cluster. It is working fine if there is only 1-2 ingresses resources defined. As soon as I add more resources traefik begins reloading configuration every few seconds. 

### What did you expect to see?

Configuration is applied once

### What did you see instead?

Loop of reloading configuration and increased load. I've also did kubectl replace --force to check that even after restart problem exists.

![traefik](https://user-images.githubusercontent.com/569475/50382715-24029e80-06a6-11e9-8d7c-31deeee588b6.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

Whole traefik DaemonSet definition in my environment:

```yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: traefik
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: traefik
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: traefik
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        namespace: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7.6
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --kubernetes
        - --logLevel=DEBUG
        - --entrypoints=Name:https Address::443 TLS
        - --entrypoints=Name:http Address::80
        - --defaultentrypoints=http
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: traefik
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
spec:
  rules:
  - host: in.kube.example.org
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: 80
  tls:
  - hosts:
    - in.kube.example.org
    secretName: traefik-ssl-prod
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Platform: DigitalOcean Kubernetes
3 Nodes: 2cpu, 4Gb ram
Kubenetes version: 1.12

Deployed 2 more services:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
spec:
  rules:
  - host: mon.example.org
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
        path: /
  tls:
  - hosts:
    - mon.example.org
    secretName: grafana-cert
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wiki-app-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/frontend-entry-points: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: wiki-test.example.org
    http:
      paths:
      - path: /
        backend:
          serviceName: wiki-test-wiki
          servicePort: 80
  tls:
  - hosts:
    - wiki-test.example.org
    secretName: wiki-test-prod
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-12-23T10:25:17Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"global-default-backend\":{\"loadBalancer\":{\"method\":\"wrr\"}},\"in.kube.example.org/\":{\"servers\":{\"traefik-ingress-controller-jkmgj\":{\"url\":\"http://10.244.49.2:8080\",\"weight\":1},\"traefik-ingress-controller-lk8ts\":{\"url\":\"http://10.244.53.2:8080\",\"weight\":1},\"traefik-ingress-controller-ltpt9\":{\"url\":\"http://10.244.71.4:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"mon.example.org/\":{\"servers\":{\"grafana-9b9868574-q59kr\":{\"url\":\"http://10.244.53.6:3000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"wiki-test.example.org/\":{\"servers\":{\"wiki-app-6dcc45468b-zk7ll\":{\"url\":\"http://10.244.53.4:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"in.kube.example.org/\":{\"entryPoints\":[\"https\"],\"backend\":\"in.kube.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"in.kube.example.org\":{\"rule\":\"Host:in.kube.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null},\"mon.example.org/\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"mon.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"mon.example.org\":{\"rule\":\"Host:mon.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"redirect\":{\"entryPoint\":\"https\"}},\"wiki-test.example.org/\":{\"entryPoints\":[\"https\"],\"backend\":\"wiki-test.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"wiki-test.example.org\":{\"rule\":\"Host:wiki-test.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}"
time="2018-12-23T10:25:17Z" level=debug msg="Wiring frontend in.kube.example.org/ to entryPoint https"
time="2018-12-23T10:25:17Z" level=debug msg="Creating backend in.kube.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Adding TLSClientHeaders middleware for frontend in.kube.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:17Z" level=debug msg="Creating server traefik-ingress-controller-lk8ts at http://10.244.53.2:8080 with weight 1"
time="2018-12-23T10:25:17Z" level=debug msg="Creating server traefik-ingress-controller-ltpt9 at http://10.244.71.4:8080 with weight 1"
time="2018-12-23T10:25:17Z" level=debug msg="Creating server traefik-ingress-controller-jkmgj at http://10.244.49.2:8080 with weight 1"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route in.kube.example.org Host:in.kube.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Wiring frontend mon.example.org/ to entryPoint http"
time="2018-12-23T10:25:17Z" level=debug msg="Creating backend mon.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating entry point redirect http -> https"
time="2018-12-23T10:25:17Z" level=debug msg="Frontend mon.example.org/ redirect created"
time="2018-12-23T10:25:17Z" level=debug msg="Adding TLSClientHeaders middleware for frontend mon.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:17Z" level=debug msg="Creating server grafana-9b9868574-q59kr at http://10.244.53.6:3000 with weight 1"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route mon.example.org Host:mon.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Wiring frontend mon.example.org/ to entryPoint https"
time="2018-12-23T10:25:17Z" level=debug msg="Creating backend mon.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Adding TLSClientHeaders middleware for frontend mon.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:17Z" level=debug msg="Creating server grafana-9b9868574-q59kr at http://10.244.53.6:3000 with weight 1"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route mon.example.org Host:mon.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Wiring frontend wiki-test.example.org/ to entryPoint https"
time="2018-12-23T10:25:17Z" level=debug msg="Creating backend wiki-test.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Adding TLSClientHeaders middleware for frontend wiki-test.example.org/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:17Z" level=debug msg="Creating server wiki-app-6dcc45468b-zk7ll at http://10.244.53.4:80 with weight 1"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:17Z" level=debug msg="Creating route wiki-test.example.org Host:wiki-test.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Add certificate for domains wiki-test.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Add certificate for domains mon.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Add certificate for domains mon.example.org"
time="2018-12-23T10:25:17Z" level=debug msg="Add certificate for domains in.kube.example.org"
time="2018-12-23T10:25:17Z" level=info msg="Server configuration reloaded on :443"
time="2018-12-23T10:25:17Z" level=debug msg="Certificates not added to non-TLS entryPoint http."
time="2018-12-23T10:25:17Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-23T10:25:17Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-23T10:25:18Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:18Z" level=error msg="Error creating global backend for ingress ws-demo/ws-example-ing: service not found for ws-demo/ws-example-svc"
time="2018-12-23T10:25:18Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"global-default-backend\":{\"loadBalancer\":{\"method\":\"wrr\"}},\"in.kube.example.org/\":{\"servers\":{\"traefik-ingress-controller-jkmgj\":{\"url\":\"http://10.244.49.2:8080\",\"weight\":1},\"traefik-ingress-controller-lk8ts\":{\"url\":\"http://10.244.53.2:8080\",\"weight\":1},\"traefik-ingress-controller-ltpt9\":{\"url\":\"http://10.244.71.4:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"mon.example.org/\":{\"servers\":{\"grafana-9b9868574-q59kr\":{\"url\":\"http://10.244.53.6:3000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"wiki-test.example.org/\":{\"servers\":{\"wiki-app-6dcc45468b-zk7ll\":{\"url\":\"http://10.244.53.4:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"in.kube.example.org/\":{\"entryPoints\":[\"https\"],\"backend\":\"in.kube.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"in.kube.example.org\":{\"rule\":\"Host:in.kube.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null},\"mon.example.org/\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"mon.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"mon.example.org\":{\"rule\":\"Host:mon.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"redirect\":{\"entryPoint\":\"https\"}},\"wiki-test.example.org/\":{\"entryPoints\":[\"https\"],\"backend\":\"wiki-test.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"wiki-test.example.org\":{\"rule\":\"Host:wiki-test.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}"
time="2018-12-23T10:25:19Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:19Z" level=error msg="Error creating global backend for ingress ws-demo/ws-example-ing: service not found for ws-demo/ws-example-svc"
time="2018-12-23T10:25:19Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:19Z" level=debug msg="Wiring frontend in.kube.example.org/ to entryPoint https"
time="2018-12-23T10:25:19Z" level=debug msg="Creating backend in.kube.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Adding TLSClientHeaders middleware for frontend in.kube.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:19Z" level=debug msg="Creating server traefik-ingress-controller-jkmgj at http://10.244.49.2:8080 with weight 1"
time="2018-12-23T10:25:19Z" level=debug msg="Creating server traefik-ingress-controller-lk8ts at http://10.244.53.2:8080 with weight 1"
time="2018-12-23T10:25:19Z" level=debug msg="Creating server traefik-ingress-controller-ltpt9 at http://10.244.71.4:8080 with weight 1"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route in.kube.example.org Host:in.kube.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Wiring frontend mon.example.org/ to entryPoint http"
time="2018-12-23T10:25:19Z" level=debug msg="Creating backend mon.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating entry point redirect http -> https"
time="2018-12-23T10:25:19Z" level=debug msg="Frontend mon.example.org/ redirect created"
time="2018-12-23T10:25:19Z" level=debug msg="Adding TLSClientHeaders middleware for frontend mon.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:19Z" level=debug msg="Creating server grafana-9b9868574-q59kr at http://10.244.53.6:3000 with weight 1"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route mon.example.org Host:mon.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Wiring frontend mon.example.org/ to entryPoint https"
time="2018-12-23T10:25:19Z" level=debug msg="Creating backend mon.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Adding TLSClientHeaders middleware for frontend mon.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:19Z" level=debug msg="Creating server grafana-9b9868574-q59kr at http://10.244.53.6:3000 with weight 1"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route mon.example.org Host:mon.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:19Z" level=debug msg="Wiring frontend wiki-test.example.org/ to entryPoint https"
time="2018-12-23T10:25:19Z" level=debug msg="Creating backend wiki-test.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Adding TLSClientHeaders middleware for frontend wiki-test.example.org/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:19Z" level=debug msg="Creating server wiki-app-6dcc45468b-zk7ll at http://10.244.53.4:80 with weight 1"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:19Z" level=debug msg="Creating route wiki-test.example.org Host:wiki-test.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Add certificate for domains mon.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Add certificate for domains mon.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Add certificate for domains in.kube.example.org"
time="2018-12-23T10:25:19Z" level=debug msg="Add certificate for domains wiki-test.example.org"
time="2018-12-23T10:25:19Z" level=info msg="Server configuration reloaded on :443"
time="2018-12-23T10:25:19Z" level=debug msg="Certificates not added to non-TLS entryPoint http."
time="2018-12-23T10:25:19Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-23T10:25:19Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-23T10:25:20Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:20Z" level=error msg="Error creating global backend for ingress ws-demo/ws-example-ing: service not found for ws-demo/ws-example-svc"
time="2018-12-23T10:25:20Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:21Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:21Z" level=error msg="Error creating global backend for ingress ws-demo/ws-example-ing: service not found for ws-demo/ws-example-svc"
time="2018-12-23T10:25:21Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:22Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:22Z" level=error msg="Error creating global backend for ingress ws-demo/ws-example-ing: service not found for ws-demo/ws-example-svc"
time="2018-12-23T10:25:22Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"global-default-backend\":{\"loadBalancer\":{\"method\":\"wrr\"}},\"in.kube.example.org/\":{\"servers\":{\"traefik-ingress-controller-jkmgj\":{\"url\":\"http://10.244.49.2:8080\",\"weight\":1},\"traefik-ingress-controller-lk8ts\":{\"url\":\"http://10.244.53.2:8080\",\"weight\":1},\"traefik-ingress-controller-ltpt9\":{\"url\":\"http://10.244.71.4:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"mon.example.org/\":{\"servers\":{\"grafana-9b9868574-q59kr\":{\"url\":\"http://10.244.53.6:3000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"wiki-test.example.org/\":{\"servers\":{\"wiki-app-6dcc45468b-zk7ll\":{\"url\":\"http://10.244.53.4:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"in.kube.example.org/\":{\"entryPoints\":[\"https\"],\"backend\":\"in.kube.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"in.kube.example.org\":{\"rule\":\"Host:in.kube.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null},\"mon.example.org/\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"mon.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"mon.example.org\":{\"rule\":\"Host:mon.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"redirect\":{\"entryPoint\":\"https\"}},\"wiki-test.example.org/\":{\"entryPoints\":[\"https\"],\"backend\":\"wiki-test.example.org/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"wiki-test.example.org\":{\"rule\":\"Host:wiki-test.example.org\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}"
time="2018-12-23T10:25:22Z" level=debug msg="Wiring frontend in.kube.example.org/ to entryPoint https"
time="2018-12-23T10:25:22Z" level=debug msg="Creating backend in.kube.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Adding TLSClientHeaders middleware for frontend in.kube.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:22Z" level=debug msg="Creating server traefik-ingress-controller-lk8ts at http://10.244.53.2:8080 with weight 1"
time="2018-12-23T10:25:22Z" level=debug msg="Creating server traefik-ingress-controller-ltpt9 at http://10.244.71.4:8080 with weight 1"
time="2018-12-23T10:25:22Z" level=debug msg="Creating server traefik-ingress-controller-jkmgj at http://10.244.49.2:8080 with weight 1"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route in.kube.example.org Host:in.kube.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Wiring frontend mon.example.org/ to entryPoint http"
time="2018-12-23T10:25:22Z" level=debug msg="Creating backend mon.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating entry point redirect http -> https"
time="2018-12-23T10:25:22Z" level=debug msg="Frontend mon.example.org/ redirect created"
time="2018-12-23T10:25:22Z" level=debug msg="Adding TLSClientHeaders middleware for frontend mon.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:22Z" level=debug msg="Creating server grafana-9b9868574-q59kr at http://10.244.53.6:3000 with weight 1"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route mon.example.org Host:mon.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Wiring frontend mon.example.org/ to entryPoint https"
time="2018-12-23T10:25:22Z" level=debug msg="Creating backend mon.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Adding TLSClientHeaders middleware for frontend mon.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:22Z" level=debug msg="Creating server grafana-9b9868574-q59kr at http://10.244.53.6:3000 with weight 1"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route mon.example.org Host:mon.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Wiring frontend wiki-test.example.org/ to entryPoint https"
time="2018-12-23T10:25:22Z" level=debug msg="Creating backend wiki-test.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Adding TLSClientHeaders middleware for frontend wiki-test.example.org/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating load-balancer wrr"
time="2018-12-23T10:25:22Z" level=debug msg="Creating server wiki-app-6dcc45468b-zk7ll at http://10.244.53.4:80 with weight 1"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-12-23T10:25:22Z" level=debug msg="Creating route wiki-test.example.org Host:wiki-test.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Add certificate for domains wiki-test.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Add certificate for domains mon.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Add certificate for domains mon.example.org"
time="2018-12-23T10:25:22Z" level=debug msg="Add certificate for domains in.kube.example.org"
time="2018-12-23T10:25:22Z" level=info msg="Server configuration reloaded on :443"
time="2018-12-23T10:25:22Z" level=debug msg="Certificates not added to non-TLS entryPoint http."
time="2018-12-23T10:25:22Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-23T10:25:22Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-23T10:25:23Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2018-12-23T10:25:23Z" level=error msg="Error creating global backend for ingress ws-demo/ws-example-ing: service not found for ws-demo/ws-example-svc"
time="2018-12-23T10:25:23Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"


```
