### ISSUE TITLE
kubernetes grpc ingress not work

### ISSUE THREAD

**Issue by yangxikun** [containous/traefik#4334]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

grpc request success

### What did you see instead?

rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Follow `https://docs.traefik.io/user-guide/kubernetes/` installation guide.

kubernetes ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: face
  namespace: web
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
  - host: face-test.aibee.cn
    http:
      paths:
      - backend:
          serviceName: face
          servicePort: 80
```

![image](https://user-images.githubusercontent.com/3364160/50384969-dcacfa00-0707-11e9-9171-d360f931398f.png)

I can successfully access my grpc service by kubernetes service.

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
