### ISSUE TITLE
Unexpected behavior of "traefik.frontend.priority"

### ISSUE THREAD

**Issue by waahhhh** [containous/traefik#4343]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

<details>
  <summary>first docker-compose.yml</summary>

```yaml
version: "3.7"

services:
    webserver:
    labels:
      - "traefik.frontend.rule=Host:xxxxx.de,www.xxxxx.de"
```
</details>

<details>
  <summary>second docker-compose.yml</summary>

```yaml
version: "3.7"

services:
    webserver:
    labels:
      - "traefik.frontend.rule=Host:xxxxx.de; Path:/api/{query:.+}.json"
      - "traefik.frontend.priority=1"
```
</details>

### What did you expect to see?

* Request to **"xxxxx.de"** should match the **first docker-compose.yml**.
* Request to **"xxxxx.de/api/example.json"** should match the **second docker-compose.yml**.

### What did you see instead?

* Request to **"xxxxx.de"** matches the **first docker-compose.yml**.
* Request to **"xxxxx.de/api/example.json"** matches the **first docker-compose.yml**.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.6
Codename:     maroilles
Go version:   go1.11.3
Built:        2018-12-14_06:43:37AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": 0,
  "GraceTimeOut": 0
 },
 "GraceTimeOut": 0,
 "Debug": false,
 "CheckNewVersion": false,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": {
  "file": "/logs/access.log",
  "format": "common"
 },
 "TraefikLogsFile": "",
 "TraefikLog": {
  "file": "xxxx",
  "format": "xxxx"
 },
 "Tracing": null,
 "LogLevel": "INFO",
 "EntryPoints": {
  "http": {
   "Address": "xxxx",
   "TLS": null,
   "Redirect": {
    "entryPoint": "xxxx"
   },
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "https": {
   "Address": "xxxx",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": null,
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    },
    "DefaultCertificate": null,
    "SniStrict": false
   },
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": {
  "Email": "xxxx",
  "Domains": [],
  "Storage": "xxxx",
  "StorageFile": "",
  "OnDemand": false,
  "OnHostRule": false,
  "CAServer": "",
  "EntryPoint": "xxxx",
  "KeyType": "",
  "DNSChallenge": null,
  "HTTPChallenge": null,
  "TLSChallenge": null,
  "DNSProvider": "",
  "DelayDontCheckDNS": 0,
  "ACMELogging": false,
  "OverrideCertificates": false,
  "TLSConfig": null
 },
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "AllowMinWeightZero": false,
 "KeepTrailingSlash": false,
 "Web": null,
 "Docker": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "TemplateVersion": 0,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxx",
  "Domain": "xxxx",
  "TLS": null,
  "ExposedByDefault": true,
  "UseBindPortIP": false,
  "SwarmMode": false,
  "Network": "",
  "SwarmModeRefreshSeconds": 15
 },
 "File": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": {
  "EntryPoint": "traefik",
  "Dashboard": true,
  "Debug": false,
  "CurrentConfigurations": null,
  "Statistics": null
 },
 "Metrics": null,
 "Ping": null,
 "HostResolver": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

</details>

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by waahhhh** [comment]
<details>
  <summary>first docker-compose.yml</summary>

```yaml
version: "3.7"

services:
    webserver:
    labels:
      - "traefik.frontend.rule=Host:xxxxx.de,www.xxxxx.de"
      - "traefik.frontend.priority=1"
```
</details>

<details>
  <summary>second docker-compose.yml</summary>

```yaml
version: "3.7"

services:
    webserver:
    labels:
      - "traefik.frontend.rule=Host:xxxxx.de; Path:/api/{query:.+}.json"
      - "traefik.frontend.priority=2"
```
</details>

Doesn't change the currently behavior.

My workaround currently:
<details>
  <summary>first docker-compose.yml</summary>

```yaml
version: "3.7"

services:
    webserver:
    labels:
      - "traefik.frontend.rule=Host:xxxxx.de,www.xxxxx.de"
      - "traefik.frontend.priority=1"
```
</details>

<details>
  <summary>second docker-compose.yml</summary>

```yaml
version: "3.7"

services:
    webserver:
    labels:
      - "traefik.frontend.rule=Host:xxxxx.de; Path:/api/{query:.+}.json"
      - "traefik.frontend.priority=1"
```
</details>

* Request to **"xxxxx.de"** matches the **first docker-compose.yml**.
* Request to **"xxxxx.de/api/example.json"** matches the **second docker-compose.yml**.

Also detected in v1.7.5.

**Comment by ldez** [comment]
I don't reproduce:
```yml
version: '3'

services:
  reverse_proxy:
    image: traefik:v1.7
    command: --api --docker --loglevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

  whoami2:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost;Path:/api/{query:.+}.json"
```

```console
$ curl whoami.docker.localhost
Hostname: 419a07090832
IP: 127.0.0.1
IP: 172.20.0.3
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.62.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.20.0.1
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: b0585016a780
X-Real-Ip: 172.20.0.1

$ curl whoami.docker.localhost/api/toto.json
Hostname: 0a1f53c0e44a
IP: 127.0.0.1
IP: 172.20.0.4
GET /api/toto.json HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.62.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.20.0.1
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: b0585016a780
X-Real-Ip: 172.20.0.1
```

```
172.20.0.3: whoami
172.20.0.4: whoami2
```
