### ISSUE TITLE
Traefik ignores configfile settings?

### ISSUE THREAD

**Issue by IamRFC1918** [containous/traefik#4379]
Hi,

I have a kubernetes Traefik Ingress Controller with configured acme feature.

**Kubernets config:**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
       address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
        minVersion = "VersionTLS12"
        cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305" ]
    [acme]
    email = "frank@*******.de"
    storage = "/acme/acme.json"
    acmeLogging = true
    entryPoint = "https"
    [acme.httpChallenge]
      entryPoint = "http"
    onDemand = false
    onHostRule = true
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    [[acme.domains]]
      main = ".f****-l*****.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          persistentVolumeClaim:
            claimName: traefik-pv-claim
      containers:
      - image: traefik:alpine
        name: traefik-ingress-lb
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        - mountPath: "/acme"
          name: "acme"
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        - name: https
          containerPort: 443
        args:
        - --configfile=/config/traefik.toml
        - --api
        - --kubernetes
        - --insecureskipverify
        - --logLevel=DEBUG
        - --metrics
        - --metrics.prometheus
```

**Config file in pod:**
```yaml
# traefik.toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
   address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_W
[acme]
email = "frank@********.de"
storage = "/acme/acme.json"
acmeLogging = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"
onDemand = false
onHostRule = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[[acme.domains]]
  main = ".f****-l*****.com"
```

**Config file will applied in the pod:**

```bash
/config # ps aux | grep traef
    1 root      0:01 traefik traefik --configfile=/config/traefik.toml --api --kubernetes --insecureskipverify --logLevel=DEBUG --metrics --metrics.prometheus`
```

**And this is what the Log says, e.g. OnHostRule is wrong, also the CAServer and so on.**
```
time="2019-01-10T18:20:36Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"frank@porloepp.de\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"/acme/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":false,\"OnDemand\":false,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"*********\",\"SANs\":null}],\"Store\":{}}"
```

Whats the Problem here? Why does Traefik not apply the Config?
Thanks for your help.

BR,

Frank

**Comment by dtomcej** [comment]
@IamRFC1918 

Hello Frank,

```toml
    [acme]
    email = "frank@*******.de"
    storage = "/acme/acme.json"
    acmeLogging = true
    entryPoint = "https"
    [acme.httpChallenge]
      entryPoint = "http"
    onDemand = false
    onHostRule = true
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
```

Is not the same as

```toml
    [acme]
    email = "frank@*******.de"
    storage = "/acme/acme.json"
    acmeLogging = true
    entryPoint = "https"
    onDemand = false
    onHostRule = true
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    [acme.httpChallenge]
      entryPoint = "http"
```

`onHostRule` is a subkey of `[acme]`, not `[acme.httpChallenge]`

Please retry with the updated config!
