### ISSUE TITLE
A few questions about Traefik and Docker configuration

### ISSUE THREAD

**Issue by rfgamaral** [containous/traefik#4387]
I've just started playing with Traefik and Docker and I have a few questions regarding configuration of Traefik and what not. To start, let me show you my current configuration:

### myhomepc-reverse-proxy

**`docker-compose.yml`**

```yml
version: '3.5'

services:
  myhomepc-reverse-proxy:
    container_name: myhomepc-reverse-proxy
    image: traefik:1.7.7-alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      - traefik.backend=dashboard
      - traefik.frontend.rule=Host:dashboard.myhomepc
      - traefik.port=9000
    restart: always

networks:
  default:
    name: myhomepc-developer-network
    driver: bridge
```

**`traefik.toml`**

```toml
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":9000"
  [entryPoints.http]
    address = ":80"

[api]
  entrypoint = "dashboard"
  dashboard = true

[docker]
  network = "myhomepc-developer-network"
  domain = "myhomepc"
  watch = true
```

### myhomepc-app1

**`docker-compose.yml`**

```yml
version: '3.5'

services:
  myhomepc-whoami-app1:
    container_name: myhomepc-whoami-app1
    image: containous/whoami
    labels:
      - traefik.backend=whoami
      - traefik.frontend.rule=Host:app1.myhomepc
      - traefik.docker.network=myhomepc-developer-network
      - traefik.port=80
    restart: always

networks:
  default:
    name: myhomepc-developer-network
    driver: bridge
    external: true

```

### myhomepc-app2

**`docker-compose.yml`**

```yml
version: '3.5'

services:
  myhomepc-whoami-app2:
    container_name: myhomepc-whoami-app2
    image: containous/whoami
    labels:
      - traefik.backend=whoami
      - traefik.frontend.rule=Host:app2.myhomepc
      - traefik.docker.network=myhomepc-developer-network
      - traefik.port=80
    restart: always

networks:
  default:
    name: myhomepc-developer-network
    driver: bridge
    external: true
```

Everything is working fine, here's a screenshot from the dashboard:

![image](https://user-images.githubusercontent.com/96476/51075759-f1860900-1687-11e9-9dd3-b05a70832403.png)

## Questions

1. Since that I have a `traefik.toml` file for `myhomepc-reverse-proxy`, how can I move all those labels to the `traefik.toml` file?
2. How can I have more friendly names for my frontends? (ie: `frontend-Host-app1-myhomepc-1`, `frontend-Host-app2-myhomepc-0` and `frontend-Host-dashboard-myhomepc-2`)
3. Somewhat related to point 2 above, what are the numbered suffixes mean? How are they picked?
4. How can I get the servers list in the dashboard backends to show the hostnames instead of `ip:port`?
5. After rebooting my machine I expect all containers to start automatically because of `restart: always` but only the apps restart, `myhomepc-reverse-proxy` does not and that's the most important one. What am I doing wrong here?
