### ISSUE TITLE
Unable to obtain ACME certificate for domains "*.XXXXXX.com" : cannot get ACME client alicloud: some credentials information are missing: ALICLOUD_ACCESS_KEY,ALICLOUD_SECRET_KEY 

### ISSUE THREAD

**Issue by robinwangrubin** [containous/traefik#4392]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you see instead?
/usr/local/traefik/traefik -c /etc/traefik/traefik.toml
ERRO[2019-01-14T14:08:08+08:00] Unable to obtain ACME certificate for domains "*.XXXX.com" : cannot get ACME client alicloud: some credentials information are missing: ALICLOUD_ACCESS_KEY,ALICLOUD_SECRET_KEY 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":8888"
  compress = true
  [entryPoints.https]
  address = ":4444"
  compress = true
    [entryPoints.https.tls]

[acme]
email = "xxxxxx@xxxxx.com"
storage = "/tmp/acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "alidns" # DNS Provider name (cloudflare, OVH, gandi...)
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.xxxxxx.com"

```

```
grep "ALICLOUD" /etc/profile           
ALICLOUD_ACCESS_KEY="XXXXXXXXXX"
ALICLOUD_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXXXXXX"
ALICLOUD_REGION_ID="cn-XXXXXXX"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
{
    "LifeCycle":{
        "RequestAcceptGraceTimeout":0,
        "GraceTimeOut":10000000000
    },
    "GraceTimeOut":0,
    "Debug":false,
    "CheckNewVersion":true,
    "SendAnonymousUsage":false,
    "AccessLogsFile":"",
    "AccessLog":null,
    "TraefikLogsFile":"",
    "TraefikLog":null,
    "Tracing":null,
    "LogLevel":"DEBUG",
    "EntryPoints":{
        "http":{
            "Address":":8888",
            "TLS":null,
            "Redirect":null,
            "Auth":null,
            "WhitelistSourceRange":null,
            "WhiteList":null,
            "Compress":true,
            "ProxyProtocol":null,
            "ForwardedHeaders":{
                "Insecure":true,
                "TrustedIPs":null
            }
        },
        "https":{
            "Address":":4444",
            "TLS":{
                "MinVersion":"",
                "CipherSuites":null,
                "Certificates":null,
                "ClientCAFiles":null,
                "ClientCA":{
                    "Files":null,
                    "Optional":false
                },
                "DefaultCertificate":null,
                "SniStrict":false
            },
            "Redirect":null,
            "Auth":null,
            "WhitelistSourceRange":null,
            "WhiteList":null,
            "Compress":true,
            "ProxyProtocol":null,
            "ForwardedHeaders":{
                "Insecure":true,
                "TrustedIPs":null
            }
        }
    },
    "Cluster":null,
    "Constraints":[

    ],
    "ACME":{
        "Email":"xxxxx@xxxxxxx",
        "Domains":[
            {
                "Main":"*.xxxxxxx",
                "SANs":null
            }
        ],
        "Storage":"/tmp/acme.json",
        "StorageFile":"",
        "OnDemand":false,
        "OnHostRule":false,
        "CAServer":"https://acme-staging-v02.api.letsencrypt.org/directory",
        "EntryPoint":"https",
        "KeyType":"",
        "DNSChallenge":{
            "Provider":"alidns",
            "DelayBeforeCheck":0,
            "Resolvers":null,
            "DisablePropagationCheck":false
        },
        "HTTPChallenge":null,
        "TLSChallenge":null,
        "DNSProvider":"",
        "DelayDontCheckDNS":0,
        "ACMELogging":false,
        "OverrideCertificates":false,
        "TLSConfig":null
    },
    "DefaultEntryPoints":[
        "http",
        "https"
    ],
    "ProvidersThrottleDuration":2000000000,
    "MaxIdleConnsPerHost":200,
    "IdleTimeout":0,
    "InsecureSkipVerify":false,
    "RootCAs":null,
    "Retry":null,
    "HealthCheck":{
        "Interval":30000000000
    },
    "RespondingTimeouts":null,
    "ForwardingTimeouts":null,
    "AllowMinWeightZero":false,
    "KeepTrailingSlash":false,
    "Web":null,
    "Docker":null,
    "File":{
        "Watch":true,
        "Filename":"",
        "Constraints":null,
        "Trace":false,
        "TemplateVersion":0,
        "DebugLogGeneratedTemplate":false,
        "Directory":"",
        "TraefikFile":"/etc/traefik/traefik.toml"
    },
    "Marathon":null,
    "Consul":null,
    "ConsulCatalog":null,
    "Etcd":null,
    "Zookeeper":null,
    "Boltdb":null,
    "Kubernetes":null,
    "Mesos":null,
    "Eureka":null,
    "ECS":null,
    "Rancher":null,
    "DynamoDB":null,
    "ServiceFabric":null,
    "Rest":null,
    "API":null,
    "Metrics":null,
    "Ping":null,
    "HostResolver":null
}
```
