### ISSUE TITLE
acme.json stays empty, no matter the configuration

### ISSUE THREAD

**Issue by Drillan767** [containous/traefik#4401]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

 In the following order:

- Followed [the documentation](https://docs.traefik.io/user-guide/docker-and-lets-encrypt/) to set up a traefik + let's encrypt configuration (at this point, nothing worked, but it was more a network issue, acme.json located in /opt/traefik was filled with relevant datas)
- Decided to change the traefik.toml, docker-compose.yml and acme.json file to another location (from /opt/traefik to /etc/traefik, then to /home/websites/docker) because of the network issue, and because I have another docker-compose with a lot of images I use.

Here is my docker-compose.yml (relevant part)

```
version: '3.5'

services:
  traefik:
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme/acme.json
    labels:
      - "traefik.frontend.rule=Host:monitor.josephlevarato.me"
      - "traefik.backend=traefik"
      - "traefik.frontend.protocol=http"
      - "traefik.frontend.entryPoint=https"
      - "traefik.port=8080"
      - "traefik.docker.networks=default"
```

My toml configuration is a little lower

### What did you expect to see?

At worst: acme.json containing some datas, at best: my websites covered up with https

### What did you see instead?

This:

![not secured](https://i.imgur.com/1plcCIR.png)
![empty](https://i.imgur.com/mykRwz6.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
debug = true

logLevel = "DEBUG"

[traefikLog]
  filePath = "./traefik.log"
  format   = "json"

[accessLog]
  filePath = "./access.log"
  format = "json"

[web]
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "jlevarato@pm.me"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
storage = "acme.json"
entryPoint = "https"
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "josephlevarato.me"
watch = true
exposedbydefault = false
[[acme.domains]]
  main = "josephlevarato.me"
[[acme.domains]]
  main = "*.josephlevarato.me"
```

``` 
Ubuntu 16.04
Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.20.1, build 5d8c71b
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

I... tried to setup the debug level (see my toml configuration), but unless there is a syntax error in the toml or docker-compose file, nothing shows up. I'm 100% sure I'm doing something wrong or I'm looking at the wrong place.
