### ISSUE TITLE
Traefik Ingress misrouting internal services on Kubernetes

### ISSUE THREAD

**Issue by TaylorChristie** [containous/traefik#4405]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm attempting to use traefik for ingress controlling in my kubernetes cluster, and the external ingressing works fine but when trying to communicate to hosts internally via services if the service is on traefik's ports (80 or 8080) traefik is the endpoint and not the actual service. 

I'm using these two files to apply the ingress then setting up the services and ingress like below:
https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-ds.yaml

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: jenkins-master-http
  - port: 50000
    protocol: TCP
    name: jenkins-master-jnlp
  selector:
    app: jenkins-master

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-master
spec:
  rules:
  - host: build.[redacted]
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-master
          servicePort: 8080
```

When trying to connect to jenkins-master from a different container in a different namespace (ie curl jenkins-master.default:8080) i will be greeted with the traefik dashboard and not jenkins. The external ingress to build.[redacted] works as expected though.

### What did you expect to see?

I expected to be able to connect to containers inside the cluster from other namespaces.

### What did you see instead?

I connect only to the traefik UI. If the service is on a port other than 80/8080 then it isn't a problem and I can properly see the service (ie if I curl the nodeport 30000 internally on the service I will get the proper service).

For instance, i have node-red on my server (with ingress and a service) running on port 1880. I can successfully access it both inside and outside the cluster with the proper DNS entry (node-red.default). 

I also checked DNS entries and they are pointing to the proper service IP (which then points to the proper pod IP(s)).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik logs
```
time="2019-01-17T16:01:34Z" level=info msg="Traefik version v1.7.7 built on 2019-01-08_10:21:03AM"
time="2019-01-17T16:01:34Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-01-17T16:01:34Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil>Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000385be0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-01-17T16:01:34Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000385bc0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-01-17T16:01:34Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2019-01-17T16:01:34Z" level=info msg="Starting server on :8080"
time="2019-01-17T16:01:34Z" level=info msg="Starting server on :80"
time="2019-01-17T16:01:34Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null}"
time="2019-01-17T16:01:34Z" level=info msg="ingress label selector is: \"\""
time="2019-01-17T16:01:34Z" level=info msg="Creating in-cluster Provider client"
time="2019-01-17T16:01:35Z" level=warning msg="Endpoints not available for default/node-red"
time="2019-01-17T16:01:35Z" level=warning msg="Endpoints not available for default/jenkins-master"
time="2019-01-17T16:01:35Z" level=warning msg="Endpoints not available for default/mqtt"
time="2019-01-17T16:01:35Z" level=info msg="Server configuration reloaded on :80"
time="2019-01-17T16:01:35Z" level=info msg="Server configuration reloaded on :8080"

```

The endpoint not available seems to probably be the issue but the svc is associated with the right pod labels.
