### ISSUE TITLE
How unmatched paths are handled

### ISSUE THREAD

**Issue by KhalidDiriye** [containous/traefik#4406]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've setup my backend and frontend as so...

```
  [backends.dr]
    [backends.dr.servers.server1]
    url = "https://server1.test.com:8442"
    [backends.dr.servers.server2]
    url = "https://server2.test.com:8442"
    [backends.dr.servers.server3]
    url = "https://server3.test.com:8442"
    [backends.dr.servers.server4]
    url = "https://server4.test.com:8442"
    [backends.dr.loadbalancer]
      sticky = true
    [backends.dr.healthcheck]
      path = "/gateway/health/api/v1/version"
      interval = "5s"



  [frontends.dev]
  backend = "dr"
  [frontends.dev.routes.test_1]
    rule = "PathPrefixStrip:/hdp/dev/kx;AddPrefix:/gateway/TESTDEV1"
```

**Note**: This works in <1.6.5 but does not in 1.6.5+. 

**Requested URL**

`https://domain.test.com:443/hdp/dev/kx/webhdfs/v1/user/testuser/table.txt?op=OPEN`

### What did you expect to see?

`https://server[x].test.com:8442/gateway/TESTDEV1/webhdfs/data/v1/webhdfs/v1/user/testuser/table.txt?`

### What did you see instead?

`https://server[x].test.com/gateway/TESTDEV1/webhdfs/data/v1/webhdfs/v1/user/testuser/table.txt?`

Request URL is processed fine, the backend generates a redirect which contains unmatched path. The redirect location wasn't modified in <1.6.5 but in 1.6.5+ the redirect location is changed to the traefik host + path 

### Work around? (kudos to @quirogadf)

Define a front end to match the expected redirect path, pass to backend without altering the path

rules.toml
```
  [frontends.dev]
  backend = "dr"
  [frontends.dev.routes.test_1]
    rule = "PathPrefixStrip:/hdp/dev/kx;AddPrefix:/gateway/TESTDEV1"

  [frontends.dev2]
  backend = "dr"
  [frontends.dev2.routes.test_1]
    rule = "PathPrefix:/gateway/TESTDEV1
```

Feel the bug here is a change in how unmatched paths are handled

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

rules.toml 
```toml
[backends]
  [backends.health]
    [backends.health.servers.server1]
    url = "https://server1.test.com:8080"
  [backends.dr]
    [backends.dr.servers.server1]
    url = "https://server1.test.com:8442"
    [backends.dr.servers.server2]
    url = "https://server2.test.com:8442"
    [backends.dr.servers.server3]
    url = "https://server3.test.com:8442"
    [backends.dr.servers.server4]
    url = "https://server4.test.com:8442"
    [backends.dr.loadbalancer]
      sticky = true
    [backends.dr.healthcheck]
      path = "/gateway/health/api/v1/version"
      interval = "5s"
[frontends]
  [frontends.health]
  backend = "health"
  [frontends.health.routes.test_1]
    rule = "Path:/health"
  [frontends.dev]
  backend = "dr"
  [frontends.dev.routes.test_1]
    rule = "PathPrefixStrip:/hdp/dev/kx;AddPrefix:/gateway/TESTDEV1"
```
