### ISSUE TITLE
Some requests failing in dockerized Traefik but working when Traefik is run directly on the host machine

### ISSUE THREAD

**Issue by jminardi** [containous/traefik#4407]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am using Traefik as a reverse proxy to my web application and to automatically general SSL certs with lets encrypt.

My application is a dockerized flask app served with Gunicorn.

I started Traefik in two ways:

1) As a dockerized service running alongside my other docker-compose services. Here is the relevant snippet from my docker-compose file:

```
    traefik:
        container_name: traefik
        image: traefik:1.7.7
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik:/etc/traefik
        ports:
            - "80:80"
            - "443:443"
            - "${TRAEFIK_ADMIN_PORT:-8080}:8080"
```

2) Directly on the host machine using the binary downloaded from GitHub releases:

`sudo ./traefik_linux-386 --configFile=traefik/traefik.toml`

Note how I am using the same toml file in both instances.

### What did you expect to see?

I expected to see no appreciable difference between running Traefik in the docker container and running it directly on the host.

### What did you see instead?

Instead I saw many of the requests fail when running Traefik inside a docker container. When loading my web app some of the resources fail to load, while others load successfully. It is not always the same resources, but almost every page load _some_ of the resources fail to load. Here is a screen grab of the safari network pane:

![network-fail-6](https://user-images.githubusercontent.com/1882746/51352492-c7638b00-1a7b-11e9-9b93-5e3999cf75da.png)

In comparison when I run the binary downloaded on GH releases directly on the host machine (still running my app with docker) then I never see any failed resources.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Dockerized:
```
docker run traefik version
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

On Host Machine:
```
./traefik_linux-386 version
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/386
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[accessLog]

[web]
# Port for the status page
address = ":8080"
  [web.auth.basic]
  users = ["admin:pass"]

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "me"
storageFile = "/etc/traefik/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[retry]

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

Please let me know if any more information is needed.

https://stackoverflow.com/questions/54119727/traefik-request-has-been-aborted-and-tls-handshake-error-error-showing-up-in

**Comment by dtomcej** [comment]
@jminardi Can you try without mounting the docker socket as read only?

If you mount it as read only, Traefik cannot issue commands to it.

**Comment by jminardi** [comment]
@dtomcej I just tried (by removing the `:ro` at the end of the volume share) and that did not fix the issue.

**Comment by ldez** [comment]
Note that you don't use the same version between your host and Docker:
- linux/amd64 -> Docker
- linux/386 -> Host

What's your real arch?

**Comment by jminardi** [comment]
```bash
$ uname -a
Linux ip-172-31-5-250 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jminardi** [comment]
@ldez I downloaded the amd64 release and it works just as the 386 version did.

Which logs would you like to see? Any debug or access level switches I should apply before uploading? Do you want to see the output of `docker-compose logs` immediately after a failure to load event?

**Comment by ldez** [comment]
Note that your don't use the same configuration:

The equivalent configuration of your TOML for Docker (without a TOML) is:
```yml
    traefik:
        container_name: traefik
        image: traefik:1.7.7
        command: --loglevel=INFO --defaultentrypoints=http,https --accessLog --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --acme --acme.storage='/etc/traefik/acme.json' --acme.entrypoint=https --acme.onhostrule --acme.httpchallenge --acme.httpchallenge.entrypoint=http --retry --docker --docker.endpoint='unix:///var/run/docker.sock' --docker.watch --docker.exposedbydefault=false
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik:/etc/traefik
        ports:
            - "80:80"
            - "443:443"
            - "${TRAEFIK_ADMIN_PORT:-8080}:8080"
```
