### ISSUE TITLE
Traefik can't use Windows docker engine named pipe in hyperv isolation

### ISSUE THREAD

**Issue by StefanScherer** [containous/traefik#4409]
Bug

### What did you do?

I've built a Traefik Docker image for Windows Server 2019 / Windows 10 1809.

Someone tried my [docker-compose example](https://github.com/StefanScherer/dockerfiles-windows/tree/master/traefik) on a Windows 10 1809 machine with stable Docker-Desktop 2.0.0.2 (Docker 18.09.1).

Traefik could not communicate with the named pipe of the Windows Docker engine. See https://github.com/StefanScherer/dockerfiles-windows/issues/383 for details how I drilled down the problem before I wrote this issue.

### What did you expect to see?

Traefik should work and communicate with the Windows Docker engine through the mapped named pipe even in hyperv isolation mode. Windows 10 uses hyperv isolation mode by default.

### What did you see instead?

The traefik container shows these error messages:

```
time="2019-01-20T19:52:41Z" level=error msg="Failed to retrieve information of the docker client and server host: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running."
time="2019-01-20T19:52:41Z" level=error msg="Provider connection error Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).doRequest
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/request.go:182
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).sendRequest
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/request.go:122
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).get
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/request.go:37
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).ServerVersion
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/version.go:12
github.com/containous/traefik/provider/docker.(*Provider).Provide.func1.1
  /go/src/github.com/containous/traefik/provider/docker/docker.go:137
github.com/containous/traefik/safe.OperationWithRecover.func1
  /go/src/github.com/containous/traefik/safe/routine.go:160
github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify
  /go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37
github.com/containous/traefik/provider/docker.(*Provider).Provide.func1
  /go/src/github.com/containous/traefik/provider/docker/docker.go:252
github.com/containous/traefik/safe.(*Pool).GoCtx.func1
  /go/src/github.com/containous/traefik/safe/routine.go:62
github.com/containous/traefik/safe.GoWithRecover.func1
  /go/src/github.com/containous/traefik/safe/routine.go:142
runtime.goexit
  /usr/local/go/src/runtime/asm_amd64.s:1333
error during connect
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).doRequest
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/request.go:185
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).sendRequest
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/request.go:122
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).get
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/request.go:37
github.com/containous/traefik/vendor/github.com/docker/docker/client.(*Client).ServerVersion
  /go/src/github.com/containous/traefik/vendor/github.com/docker/docker/client/version.go:12
github.com/containous/traefik/provider/docker.(*Provider).Provide.func1.1
  /go/src/github.com/containous/traefik/provider/docker/docker.go:137
github.com/containous/traefik/safe.OperationWithRecover.func1
  /go/src/github.com/containous/traefik/safe/routine.go:160
github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify
  /go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37
github.com/containous/traefik/provider/docker.(*Provider).Provide.func1
  /go/src/github.com/containous/traefik/provider/docker/docker.go:252
github.com/containous/traefik/safe.(*Pool).GoCtx.func1
  /go/src/github.com/containous/traefik/safe/routine.go:62
github.com/containous/traefik/safe.GoWithRecover.func1
  /go/src/github.com/containous/traefik/safe/routine.go:142
runtime.goexit
  /usr/local/go/src/runtime/asm_amd64.s:1333, retrying in 10.780695475s"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
PS C:\> docker run --entrypoint traefik stefanscherer/traefik-windows version
2019/01/20 20:27:22 Using high precision timer
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml:

```toml
[web]
address = ":8080"
[docker]
domain = "docker.local"
watch = true
endpoint = "npipe:////./pipe/docker_engine"

[entryPoints]
  [entryPoints.http]
  address = ":80"
```

docker-compose.yml:

```yaml
version: '2.4'
services:
  traefik:
    image: stefanscherer/traefik-windows
    command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    volumes:
      - .:C:/etc/traefik
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

  whoami1:
    image: stefanscherer/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:whoami.docker.local"

  whoami2:
    image: stefanscherer/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:whoami.docker.local"

networks:
  default:
    external:
      name: nat
```

### Further information and suggestions

I can reproduce the problem on a Windows Server 2019 when I also run Traefik in hyperv isolation mode. When I use a new Docker CLI inside the same container the Docker CLI can communicate with the Windows Docker engine.

In process isolation mode traefik.exe also works fine, also on Windows 10 1809.

I have seen that the vendoring of github.com/docker/docker/client (and maybe others) is quite behind the upstream repo. 

I have tried a Docker CLI 17.10 inside the container and can reproduce the problem in a hyperv isolated container. My conclusion is that the vendoring should be updated.
