### ISSUE TITLE
minversion and ciphersuites appear to be ignored in consul kvstore

### ISSUE THREAD

**Issue by stevenmunro** [containous/traefik#4410]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I previously had Traefik running using a docker-compose file combined with a TOML file to set the minVersion and cipherSuites. This would work as expected.

```toml
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [ "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA" ]
```
Now I have 3 instances of Traefik running on 3 Docker Swarm Masters, all configured to retrieve configuration from a Consul server. In my `docker-stack-traefik.yml` file I have the `init` container which uses `storeconfig`, followed by the standard traefik container configured to read from Consul.
```yml
    traefik_init:
      image: traefik
      command:
        - "storeconfig"
        - "--configfile=/traefik.toml"
        - "--api"
        - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
        - "--entrypoints=Name:https Address::443 TLS TLS.MinVersion:VersionTLS12 TLS.CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA"
        - "--defaultentrypoints=http,https"
        - "--acme"
        - "--acme.storage=traefik/acme/account"
        - "--acme.entryPoint=https"
        - "--acme.httpChallenge.entryPoint=http"
        - "--acme.onHostRule=true"
        - "--acme.onDemand=false"
        - "--acme.email=xxxxxxx@me.com"
        - "--docker"
        - "--docker.swarmMode"
        - "--docker.watch"
        - "--consul"
        - "--consul.endpoint=consul_server:8500"
        - "--consul.prefix=traefik"
        - "--logLevel=DEBUG"
      volumes:
        - /app/router/traefik.toml:/traefik.toml
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - web
        - consul
      deploy:
        placement:
          constraints:
          - node.role == manager
          - node.labels.ingress == true
        restart_policy:
         condition: on-failure

    traefik:
      image: traefik
      command:
        - "--consul"
        - "--consul.endpoint=consul_server:8500"
        - "--consul.prefix=traefik"
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
        - /logs:/logs
      networks:
        - web
        - consul
      ports:
        - target: 80
          published: 80
          protocol: tcp
         mode: host
        - target: 443
          published: 443
          protocol: tcp
         mode: host
      deploy:
        mode: global
        placement:
          constraints:
          - node.role == manager
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
          delay: 5s
```
The connection to the Consul server is working because I can see the values for `minversion` and `ciphersuites` being populated. However, these values are not being respected. Using [https://www.ssllabs.com/ssltest/](url) to check shows both `TLS 1.1` and `TLS1.0` as being exposed.

I've also tried leaving the minVersion and cipherSuites config in the TOML file. But storeconfig appears to completely ignore these values -- therefore they do not get updated in Consul.

### What did you expect to see?

I expected to see these values being respected. Every other aspect of what is stored in Consul appears to be working just fine.

### What did you see instead?

The values are being stored, but for some reason Traefik is ignoring them. I'm not sure if any changes in Consul requires a restart of the Traefik containers. Despite restarting them anyway, still no banana.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Docker image - 1.77
