### ISSUE TITLE
Why does traefik redirect to docker backend port on subdirectories on apache2 php container?

### ISSUE THREAD

**Issue by thetheodoros** [containous/traefik#4412]
### Do you want to request a *feature* or report a *bug*?

Bug

If this is not a bug but a misconfiguration please close this issue. 
In case of the latter I have also created a stackoverflow post: https://stackoverflow.com/q/54262900/8247069 

### What did you do?

I am using a library PHP 7.0 apache enabled docker container to host my application behind traefik.
This apache is configured to serve port 1025 instead of 80 because openshift won't let you use anything below port 1024.
To keep people out I have configured basic authentication on my frontend using docker-compose labels.

When using a browser (Chrome) http://dev.domain.com/admin will ask for credentials and redirect me to https://dev.domain.com. 
After having input the credentials in the previous step, revisiting http://dev.domain.com/admin will result in a redirect to dev.domain.com:1025/admin.
Not sure if this information helps, but this does not happen when browsing to each page via https:// directly.

### What did you expect to see?

A working redirect, without exposing the internal port.

### What did you see instead?
I tried curl to see what was going on.
It seems that a http 301-redirect was sending my browser to apaches internal port. You can see the output below. 

```
curl -v 'https://some:basicauth@dev.domain.com/admin'
*   Trying 1.1.1.1...
* Connected to dev.domain.com (1.1.1.1) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: dev.domain.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=dev.domain.com
*        start date: Sat, 24 Nov 2018 17:51:49 GMT
*        expire date: Fri, 22 Feb 2019 17:51:49 GMT
*        issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
*        compression: NULL
* ALPN, server accepted to use http/1.1
* Server auth using Basic with user 'some'
> GET /admin HTTP/1.1
> Host: dev.domain.com
> Authorization: Basic dhfkjasdhf==
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 325
< Content-Type: text/html; charset=iso-8859-1
< Date: Fri, 18 Jan 2019 18:02:06 GMT
< Location: http://dev.domain.com:1025/admin/
< Server: Apache/2.4.25 (Debian)
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://dev.domain.com:1025/admin/">here</a>.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at dev.domain.com Port 1025</address>
</body></html>
* Connection #0 to host dev.domain.com left intact
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

I am using the docker image traefik:1.7.7

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
   [entryPoints.https.tls]
[accessLog]

[retry]

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "domain.com"
  watch = true
  exposedbydefault = false
[acme]
  email = "some@email.com"
  storageFile = "acme.json"
  entryPoint = "https"
  onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"
```

my docker-compose.yml 

```
version: '2.4'
networks:
  web:
    external: true
services:
  php:
    image: php:7.0.31-apache-stretch
    restart: always
    networks:
      - web
    labels:
     traefik.frontend.auth.basic: some:basicauth
     traefik.docker.network: web
     traefik.enable: true
     traefik.frontend.rule: Host:dev.domain.com
     traefik.port: 1025
```
