### ISSUE TITLE
Reversed proxied qbittorrent not rendering correctly on iOS devices

### ISSUE THREAD

**Issue by FutureTense** [containous/traefik#4417]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I reversed proxied a qbittorrent container to qbittorrent.example.com.  When browsing to that address, everything appears normal, but clicking on “add a torrent file” brings up a blank window.  It works properly on non iOS machine in the network.  I’ve tried several iOS browsers and they each have the same issue.  When browsing to 172.16.69.66:8085, the website behaves properly.  It’s only on the reversed proxy AND on iOS where this is an issue.

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.7.7

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Virtual Box UBUNTU 18.04
```toml
# (paste your configuration here)
#debug = true

logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true 
defaultEntryPoints = ["https", "http"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"
  usersFile = "/shared/.htpasswd"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "vamichael@gmail.com" #any email id will work
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true 
onDemand = false #create certificate when container is created
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
[[acme.domains]]
   main = "EXAMPLE.COM"
[[acme.domains]]
   main = "*.EXAMPLE.COM"
   
# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "EXAMPLE.COM"
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
