### ISSUE TITLE
HTTPS Redirect not working with dockertoolbox

### ISSUE THREAD

**Issue by johnchristopher** [containous/traefik#4422]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am running a traefik container under windows 7 with dockertools.

This traefik container is only used for local development.

### What did you expect to see?

I expect http://traefik.localhost to redirect to https://traefik.localhost and https://traefik.localhost to display the traefik page.
It works as intended under windows 10 with the standard docker installation, ubuntu and Debian (minus the host file which redirects traefik.localhost to 127.0.0.1).

### What did you see instead?

http://traefik.localhost displays `404 page not found` and doesn't redirect to https.
https://traefik.localhost displays nothing (browser connection error message)

If I modify the toml and docker-compose file like this:

```
logLevel = "DEBUG"
# defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
```

```yml
      - traefik.frontend.entryPoints=http
```
then `http://traefik.localhost` displays the traefik page.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```output
$ docker run traefik version
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Windows 7 Pro with docker tools.

The following traefik.toml:
```toml
logLevel = "DEBUG"
# defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]  
      certfile = "/certs/traefik.localhost.crt"
      keyfile = "/certs/traefik.localhost.key"
```
and the following docker-compose.yml
```yml
version: '3'

services:
  reverse-proxy:
    restart: always
    image: traefik # The official Traefik docker image
    command: --web --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"
    expose:
      # - "8080:8080" # The Web UI (enabled by --api)
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/certs:/certs
    labels:
      - traefik.frontend.rule=Host:traefik.localhost
      - traefik.frontend.entryPoints=https
      - traefik.port=8080
      - traefik.frontend.auth.basic=admin:$$apr1$$Q8Q6i53O$$E/iPn6ivCjldAwWfwAwst0
networks:
  default:
    external: 
      name: traefik
```
The host file:
```ini
127.0.0.1       localhost
172.200.7.2      .local
192.168.99.100 traefik.localhost
```
Certificates are OK.
