### ISSUE TITLE
'504 Gateway Timeout' caused by: dial tcp 192.168.0.3:80: i/o timeout

### ISSUE THREAD

**Issue by TofPlay** [containous/traefik#4426]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I try to create and use a service with docker + treafix
To test the service I launch:
```
curl http://api.mywebsite.com/myapi
```

### What did you expect to see?

Output of the api

### What did you see instead?

```
Gateway Timeout
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik version
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My docker version:
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

docker-compose.yml for traefix:
```
version: "3"
services:
  traefik:
    image: traefik
    restart: always
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - webgateway
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=traefix"
      - "traefik.frontend.rule=Host:traefix.mywebsite.com"
      - "traefik.port=8080"

networks:
  webgateway:
    driver: bridge
```

docker-compose.yml of my service
```
version: "3"
services:
  db:
    image: postgres
    volumes:
      - voldb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MyService
      POSTGRES_USER: me 
      POSTGRES_PASSWORD: **********
    ports:
      - "5432"
    networks:
      - netdb
    labels:
      - "traefik.enable=false"

  api:
    image: myservice
    depends_on:
      - "db"
    ports:
      - "80"
    networks:
      - netdb
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=api.mywebsite"
      - "traefik.frontend.rule=Host:api.mywebsite.com"
      - "traefik.port=80"

volumes:
  voldb:

networks:
  netdb:
    driver: bridge
  traefik:
    external:
      name: traefix_webgateway

```

Traefix network:
```
$ docker container inspect traefix_traefik_1 | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.19.0.4",
```

MyService networks:
```
$ docker container inspect myservice_api_1 | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "192.168.0.3",
                    "IPAddress": "172.19.0.6",
```
```
$ docker container inspect myservice_db_1 | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "192.168.0.2",
```
If I check the service:
```
$ docker-compose ps
           Name                  Command               State            Ports
-----------------------------------------------------------------------------------------
myservice_api_1       /bin/sh -c ./myservice se ...    Up      0.0.0.0:32801->80/tcp
myservice_db_1        docker-entrypoint.sh postgres    Up      0.0.0.0:32800->5432/tcp
```
I can call the service directly from the host:
```
curl http://localhost:32801/myapi
{"name":"myservice","version":"1.0.0"}
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
traefik_1  | time="2019-01-24T14:47:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/myapi\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}"
traefik_1  | time="2019-01-24T14:47:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/myapi\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}" ForwardURL="http://192.168.0.3:80"
traefik_1  | time="2019-01-24T14:47:19Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.0.3:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}"
traefik_1  | time="2019-01-24T14:47:19Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.0.3:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}"
traefik_1  | time="2019-01-24T14:47:19Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
traefik_1  | time="2019-01-24T14:47:49Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 192.168.0.3:80: i/o timeout"
traefik_1  | time="2019-01-24T14:47:49Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://192.168.0.3:80, code: 504, Length: 15, duration: 29.981795149s"
traefik_1  | time="2019-01-24T14:47:49Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.0.3:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}"
traefik_1  | time="2019-01-24T14:47:49Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.0.3:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}"
traefik_1  | time="2019-01-24T14:47:49Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/myapi\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.mywebsite.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:49020\",\"RequestURI\":\"/myapi\",\"TLS\":null}"
```
