### ISSUE TITLE
K8s - app-root on non-explicit path should include "/" in the redirect

### ISSUE THREAD

**Issue by doctori** [containous/traefik#4427]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

this is linked to the issue #4322  and the MR #4326 

When the path of the ingress is empty, this is the redirect rule generated : 
```
From: myhost$
To: myhost/my-super-app/login
```
The issue with this regex : `myhost$` never match anything,  
since refering to the [HTTP 1.1 RFC's](https://tools.ietf.org/html/rfc2616#section-3.2.2) "/" is the minimum required path.  
So the `From:` should always be `myhost/$` 

### What did you expect to see?
given this ingress : 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metdata:
  name: myingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/app-root: /my-supper-app/login
spec:
  rules:
  - host: myhost
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: myport
```
request :
```
GET / HTTP/1.1
Host: myhost
```
Response : 
```
HTTP/1.1 301 Moved Permanently
Location: http://myhost/my-supper-app/login
```

### What did you see instead?
request :
```
GET / HTTP/1.1
Host: myhost
```
Response : 
```
HTTP/1.1 200 
the web server behind

```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.7
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

platform Kubernetes 1.11

This is not a major issue, 
I'll try to submit a PR next week if this issue makes sense to you.
