### ISSUE TITLE
Frontend names are generated with segment name twice

### ISSUE THREAD

**Issue by rfgamaral** [containous/traefik#4435]
### Do you want to request a *feature* or report a *bug*?

I'm not sure if this is intended behavior so I'm reporting it as a bug.

### What did you do?

I have the following `docker-compose.yml`:

```yml
version: '3.5'

services:
  nginx:
    image: nginx:1.14-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - traefik.foo.frontend.rule=Host:myapp.foo.dev.localhost
      - traefik.foo.port=8180
      - traefik.bar.frontend.rule=Host:myapp.bar.dev.localhost
      - traefik.bar.port=8280
```

And I bring this container up with `docker-compose -p myproject up -d`.

### What did you expect to see?

Generated frontend and backend names:

- `frontend-nginx-myproject-foo` / `backend-nginx-myproject-foo`
- `frontend-nginx-myproject-bar` / `backend-nginx-myproject-bar`

### What did you see instead?

- `frontend-foo-nginx-myproject-foo` / `backend-nginx-myproject-foo`
- `frontend-bar-nginx-myproject-bar` / `backend-nginx-myproject-bar`

I'm not sure I looked in the right places but after a quick look to the source code it looks like these names are being generated like this (simplified):

```
backendNameSuffix = "{serviceName}-{projectName}-{segmentName}"
backendName= "backend-{backendNameSuffix}"
frontendNameSuffix = "{segmentName}-{backendNameSuffix}"
frontendName = "frontend-{frontendNameSuffix}"
```

Which results in something like `frontend -`**`foo`**`- nginx - myproject -`**`foo`**.

Is this _actually_ intended or could we get this fixed to display the segment name a single time?

### Output of `traefik version`:

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```
