### ISSUE TITLE
Consul provider ignores defaultEntryPoints set in traefik.toml

### ISSUE THREAD

**Issue by riker09** [containous/traefik#4439]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a setup with both, a Consul provider AND a file provider. In my `traefik.toml` I have the `defaultEntryPoints` set to the default value of `["http", "https"]`. This is completely ignored by the Consul provider, all frontends only get `http` as entryPoint. Note: I do not set a custom entrypoint on my frontends at all.

Once I set the key `traefik/defaultentrypoints/0` to a value of `https` and restart Traefik it picks up that config and creates all frontends in Consul with `https` as entryPoint.

### What did you expect to see?

When I do not specify a value for `defaultentrypoints` in Consul KV store I would assume that the `defaultEntryPoints` configuration value from `traefik.toml` is used instead.

### What did you see instead?

All frontends in Consul where created with an `http` entrypoint.

### Output of `traefik version`:

v1.7.8

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Let's Encrypt
[acme]
  email = "foo@bar.de"
  storage = "traefik/acme/account"
  entryPoint = "https"
  [acme.dnsChallenge]
    provider = "my-dns-provider"
  [[acme.domains]]
    main = "*.my-domain.com"
    sans = ["my-domain.com"]

# Entrypoints
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.tls]
      [[entryPoints.traefik.tls.certificates]]
        certFile = "/certs/my-domain.com.cert"
        keyFile = "/certs/my-domain.com..key"
    [entryPoints.traefik.auth.basic]
      users = [
        "user:$2yblablablahthisissecuretrustme"
      ]

# Enable Traefik webfrontend
[api]

# Enable File provider
[file]
# Define common backends for file provider
[backends]
  [backends.consul]
    [backends.consul.servers.default]
      url = "http://consul:8500"

# Define common frontends for file provider
[frontends]
  # Consul (proxy :8500 to consul, but with BasicAuth)
  [frontends.consul]
    backend = "consul"
    entrypoints = ["https"]
    basicAuth = ["user:$2yblablablahthisissecuretrustme"]
    [frontends.consul.routes.default]
      rule = "Host:consul.my-domain.com"

# Enable Consul provider
[consul]
  endpoint = "consul:8500"
```

**Comment by ldez** [comment]
```toml

# Entrypoints
defaultEntryPoints = ["http", "https"]
```

This must be set a the top of the file, it's related to the TOML syntax (TOML don't care about indentation).



```toml
defaultEntryPoints = ["http", "https"]

# Let's Encrypt
[acme]
  email = "foo@bar.de"
  storage = "traefik/acme/account"
  entryPoint = "https"
  [acme.dnsChallenge]
    provider = "my-dns-provider"
  [[acme.domains]]
    main = "*.my-domain.com"
    sans = ["my-domain.com"]

# Entrypoints

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.tls]
      [[entryPoints.traefik.tls.certificates]]
        certFile = "/certs/my-domain.com.cert"
        keyFile = "/certs/my-domain.com..key"
    [entryPoints.traefik.auth.basic]
      users = [
        "user:$2yblablablahthisissecuretrustme"
      ]

# Enable Traefik webfrontend
[api]

# Enable File provider
[file]
# Define common backends for file provider
[backends]
  [backends.consul]
    [backends.consul.servers.default]
      url = "http://consul:8500"

# Define common frontends for file provider
[frontends]
  # Consul (proxy :8500 to consul, but with BasicAuth)
  [frontends.consul]
    backend = "consul"
    entrypoints = ["https"]
    basicAuth = ["user:$2yblablablahthisissecuretrustme"]
    [frontends.consul.routes.default]
      rule = "Host:consul.my-domain.com"

# Enable Consul provider
[consul]
  endpoint = "consul:8500"
```
