### ISSUE TITLE
Custom realm in ingress annotations don't work

### ISSUE THREAD

**Issue by steve-todorov** [containous/traefik#4447]
### Do you want to request a *feature* or report a *bug*?

Bug (this has been addressed in #3917, but for some reason it's not working with k8s annotations?)

### What did you do?

I've followed the nginx ingress documentation for adding authentication and added the `nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - foo"` annotation ([docs](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#authentication)).
If you don't add this annotation the `Basic Authentication` works, but the realm is `traefik`.

### What did you expect to see?

```
content-type: text/plain
www-authenticate: Basic realm="Authentication Required - foo"
content-length: 17
date: Thu, 31 Jan 2019 16:15:32 GMT
```

### What did you see instead?

No `www-authenticate` header at all.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "INFO"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.dashboard]
  address = ":8090"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = [ ]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
swarmMode = false

[kubernetes]
endpoint = "..."
token = "..."

[api]
  dashboard = true
  entrypoint = "dashboard"
```
