### ISSUE TITLE
502/504 when performing a RollingUpdate with k8s and traefik

### ISSUE THREAD

**Issue by amine7536** [containous/traefik#4452]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We are using Traefik as Ingress controller in our Kubernetes clusters. When perform we deploy new versions of our apps, using RollingUpdate strategy, we are seeing 502 and 504 errors  return by Traefik.

### What did you expect to see?

Zero downtime

### What did you see instead?

```
{
  "BackendAddr": "172.17.0.10:3000",
  "DownstreamStatusLine": "502 Bad Gateway",
  "DownstreamStatus": 502,
  "OriginStatus": 502,
  "OriginStatusLine": "502 Bad Gateway",
  "StartLocal": "2019-02-01T10:37:12.129935275Z"
}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- The issue can be replicated using Minikube

```bash
minikube start \
  --memory 2048 \
  --cpus 2 \
  --kubernetes-version="v1.11.5" \
  --extra-config=apiserver.authorization-mode=RBAC

helm init
```

- Traefik is installed using Helm

```bash
helm install stable/traefik \
  --name traefik \
  --namespace traefik \
  --set 'imageTag=1.7.7-alpine' \
  --set 'rbac.enabled=true' \
  --set 'debug.enabled=true' \
  --set 'serviceType=NodePort' \
  --set 'service.nodePorts.http=30080' \
  --set 'service.nodePorts.https=30443' \
  --set 'accessLogs.enabled=true' \
  --set 'accessLogs.format=json' \
  --set 'dashboard.enabled=true' \
  --set 'dashboard.serviceType=NodePort'
```

- Kubernetes manifests 

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    traefik.backend.loadbalancer.method: "wrr"
    traefik.ingress.kubernetes.io/max-conn-amount: "10000"
    traefik.ingress.kubernetes.io/max-conn-extractor-func: "client.ip"
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        version: v1.0
    spec:
      containers:
      - name: myapp
        image: rubyapp:latest
        imagePullPolicy: IfNotPresent
        args:
          - bundle
          - exec
          - ruby
          - web.rb
          - -s
          - Puma
          - -p
          - "3000"
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/hsts-preload: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
spec:
  rules:
  - host: myapp.minikube.local
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp
          servicePort: 3000
```

> The ruby application deploy is a very simple Sinatra app running with Puma web server, which handles graceful shutdown. 
> Instruction to build and run the app and replicate the issue are in the ZIP attached.  

[traefik-issue-502.zip](https://github.com/containous/traefik/files/2822073/traefik-issue-502.zip)

```
172.17.0.1 - - [01/Feb/2019:10:10:05 +0000] "GET /healthz HTTP/1.1" 200 2 0.0008
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2019-02-01 10:10:05 +0000 ===
- Goodbye!
== Sinatra has ended his set (crowd applauds)
```

- Simulate load 

```bash
#!/usr/bin/env bash

MINIKUBE_IP=$(minikube ip)

while true
do 
    STATUS=$(curl -s \
                -o /dev/null \
                -w "%{http_code}\n" \
                -H 'Host: myapp.minikube.local' \
                http://$MINIKUBE_IP:30080/healthz)
    
    if [[ $STATUS == 50* ]]
    then
        echo $STATUS
    fi

    sleep 1
done
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Traefik receiving Endpoints config  

```
{
  "level": "debug",
  "msg": "Received Kubernetes event kind *v1.Endpoints",
  "time": "2019-02-01T14:29:00Z"
}
{
  "level": "debug",
  "msg": "Configuration received from provider kubernetes: {\"backends\":{\"myapp.minikube.local/\":{\"servers\":{\"myapp-5759b44df4-gn9d9\":{\"url\":\"http://172.17.0.7:3000\",\"weight\":1},\"myapp-5759b44df4-l74gw\":{\"url\":\"http://172.17.0.8:3000\",\"weight\":1},\"myapp-77fb6b655c-ts5t2\":{\"url\":\"http://172.17.0.9:3000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"},\"maxConn\":{\"amount\":10000,\"extractorFunc\":\"client.ip\"}},\"traefik.example.com\":{\"servers\":{\"traefik-584db87664-p4866\":{\"url\":\"http://172.17.0.6:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"myapp.minikube.local/\":{\"entryPoints\":[\"http\",\"httpn\"],\"backend\":\"myapp.minikube.local/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"myapp.minikube.local\":{\"rule\":\"Host:myapp.minikube.local\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"headers\":{\"stsSeconds\":315360000,\"stsIncludeSubdomains\":true,\"stsPreload\":true,\"forceSTSHeader\":true}},\"traefik.example.com\":{\"entryPoints\":[\"http\",\"httpn\"],\"backend\":\"traefik.example.com\",\"routes\":{\"traefik.example.com\":{\"rule\":\"Host:traefik.example.com\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}",
  "time": "2019-02-01T14:29:00Z"
}
{
  "level": "debug",
  "msg": "Received Kubernetes event kind *v1.Endpoints",
  "time": "2019-02-01T14:29:00Z"
}
{
  "level": "debug",
  "msg": "Configuration received from provider kubernetes: {\"backends\":{\"myapp.minikube.local/\":{\"servers\":{\"myapp-5759b44df4-gn9d9\":{\"url\":\"http://172.17.0.7:3000\",\"weight\":1},\"myapp-5759b44df4-l74gw\":{\"url\":\"http://172.17.0.8:3000\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"},\"maxConn\":{\"amount\":10000,\"extractorFunc\":\"client.ip\"}},\"traefik.example.com\":{\"servers\":{\"traefik-584db87664-p4866\":{\"url\":\"http://172.17.0.6:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"myapp.minikube.local/\":{\"entryPoints\":[\"http\",\"httpn\"],\"backend\":\"myapp.minikube.local/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"myapp.minikube.local\":{\"rule\":\"Host:myapp.minikube.local\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"headers\":{\"stsSeconds\":315360000,\"stsIncludeSubdomains\":true,\"stsPreload\":true,\"forceSTSHeader\":true}},\"traefik.example.com\":{\"entryPoints\":[\"http\",\"httpn\"],\"backend\":\"traefik.example.com\",\"routes\":{\"traefik.example.com\":{\"rule\":\"Host:traefik.example.com\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}",
  "time": "2019-02-01T14:29:00Z"
}
```

Traefik is still trying to send connections to the terminated POD.
