### ISSUE TITLE
Wildcard for sub-level subdomains returning errors

### ISSUE THREAD

**Issue by emteedubs** [containous/traefik#4455]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to set up a reverse proxy for my sub- subdomains with wildcard DNS challenge at *.xyz.example.com through Cloudflare. 

### What did you expect to see?

Valid SSL certificates generated for each sub-level subdomain via wildcard DNS challenge (e.g. APP1.xyz.example.com; APP2.xyz.example.com, etc...)

### What did you see instead?

Error code as follows for each sub-level subdomain and no SSL certs generated:
```
level=error msg="Unable to obtain ACME certificate for domains \"APP1.xyz.example.com\" detected thanks to rule \"Host:APP1.xyz.example.com\" : unable to generate a certificate for the domains [APP1.xyz.example.com]: acme: Error -> One or more domains had a problem:\n[APP1.xyz.example.com] [APP1.xyz.example.com] acme: error presenting token: cloudflare: unexpected response code 'SERVFAIL' for _acme-challenge.APP1.xyz.example.com."
```

### Output of `traefik version`: (1.7.8)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "WARN"
defaultEntryPoints = ["https", "http"]
keepTrailingSlash = true
InsecureSkipVerify = true

[retry]
attempts = 2

[traefikLog]
filePath = "/etc/traefik/logs/traefik.log"

[accessLog]
filePath = "/etc/traefik/logs/access.log"
format = "json"

[accessLog.filters]
  statusCodes = ["200", "300-302"]
  retryAttempts = true
  minDuration = "10ms"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = false
  address = ":8080"
  usersFile = "/shared/.htpasswd"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "admin@example.com"
storage="/etc/traefik/acme/acme.json"
acmeLogging = true
onHostRule = true
caServer = "https://acme-v02.api.letsencrypt.org/directory"

[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0

[[acme.domains]]
   main = "EXAMPLE.COM"
[[acme.domains]]
   main = "*.EXAMPLE.COM"
[[acme.domains]]
   main = "*.XYZ.EXAMPLE.COM"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "WONGIT.COM"
watch = true
exposedByDefault = false
usebindportip = true

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
level=error msg="Unable to obtain ACME certificate for domains \"APP1.xyz.example.com\" detected thanks to rule \"Host:APP1.xyz.example.com\" : unable to generate a certificate for the domains [APP1.xyz.example.com]: acme: Error -> One or more domains had a problem:\n[APP1.xyz.example.com] [APP1.xyz.example.com] acme: error presenting token: cloudflare: unexpected response code 'SERVFAIL' for _acme-challenge.APP1.xyz.example.com."
```
