### ISSUE TITLE
Internal server error in buffering

### ISSUE THREAD

**Issue by expiron** [containous/traefik#4456]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I used labels in `docker-compose.yml` to configure the buffering of a backend:
```yml
  nginx:
    image: nginx
    labels:
      traefik.backend: 'nginx'
      traefik.backend.buffering.maxRequestBodyBytes: '8589934592'
      traefik.backend.buffering.maxResponseBodyBytes: '8589934592'
      traefik.backend.buffering.memRequestBodyBytes: '268436456'
      traefik.backend.buffering.memResponseBodyBytes: '268435456'
      traefik.backend.buffering.retryExpression: 'IsNetworkError() && Attempts() <= 2'
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host: nginx.example.com'
      traefik.port: '80'
    networks:
    - web
    restart: always
    volumes:
    - ...
```
And I got an Internal Server Error when accessed the Host: nginx.example.com .
~~The `docker-compose.yml` works well in traefik v1.7.7.~~ And I'm sure that the backend works well too.
When I removed the labels about buffering, the traefik works normally!
### What did you expect to see?

Access the host normally.

### What did you see instead?

500: Internal Server Error

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
defaultEntryPoints = ['https', 'http']
logLevel = 'DEBUG'

[entryPoints]
  [entryPoints.http]
    address = ':80'
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ':443'
    [entryPoints.https.tls]

[traefikLog]
  filePath = 'traefik.log'
  format = 'json'

[accessLog]
  format = 'json'

[docker]
  endpoint = 'unix:///var/run/docker.sock'
  exposedByDefault = false
  domain = 'example.com'
  network = 'web'
  watch = true

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

I found these messages in the debug log:
```json
{
  "level": "debug",
  "msg": "Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.",
  "time": "2019-02-03T11:38:05Z"
}
{
  "level": "error",
  "msg": "vulcand/oxy/buffer: failed to read response, err: no data ready",
  "time": "2019-02-03T11:38:06Z"
}
{
  "level": "debug",
  "msg": "'500 Internal Server Error' caused by: no data ready",
  "time": "2019-02-03T11:38:06Z"
}
```
And I think the `vulcand/oxy/buffer` caused the issue.
The whole DEBUG log is [debug.log](https://github.com/containous/traefik/files/2825498/debug.log).
I think my report will help you!

**Comment by expiron** [comment]
UPDATE: same issue in v1.7.7.
I found that, if I start backend service without buffering config labels, the traefik works well. Then I add buffering config labels to `docker-compose.yml` and run `docker-compose up -d` to update the backend service, traefik still works perfectly. But if I run `docker-compose up -d --force-recreate` with the same `docker-compose.yml` file to restart backend container, traefik responses error. That means: if starting(or restarting) a container with buffering labels will get error, if adding buffering labels to a running container without restart may not get error.

**Comment by expiron** [comment]
UPDATE: maybe traefik cannot process the response of the backend detailed below correctly.
The status code of response is `302 Found`. HTTP Header contains no `Content-Length` and header `Transfer-Encoding` is `chunked`.
The tcpdump log file is [tcpdump.log](https://github.com/containous/traefik/files/2831342/tcpdump.log).

**Comment by mrmachine** [comment]
Same error here when I submit POST request and my backend replies with a 302 (e.g. submit login form and redirect). Otherwise, I can access the backend with GET requests.

**Comment by tehKapa** [comment]
I've the same issues on Kubernetes (v1.7.9)

**Comment by youtous** [comment]
Same issue on `302` responses. Traefik **v1.7.14**

**Comment by Lawouach** [comment]
Saw the same issue with v2.0 too. I will try to investigate.

**Comment by Lawouach** [comment]
This is actually now a real issue because it does obviously happen on any backend server not setting these headers. trafik is broken when it expects to read some data but is redirect somewhere.

**Comment by Lawouach** [comment]
Right. In that last instance, it was actually an error of configuration of my backend. Apologies.

**Comment by mpl** [comment]
@expiron is this issue still relevant?
If yes, could you provide the nginx config needed to reproduce the problem? or even better, a simpler reproduction without nginx?
Also, do you happen to know if the problem occurs with Traefik version 2 as well?

**Comment by mpl** [comment]
I have setup a stack pretty similar to what the OP posted, except I used a custom small httpd (handling a redirect) instead of nginx since we don't have the nginx conf, and I cannot reproduce. And I also don't see what the problem could be. So unless someone can give us a better described repro case, I don't think we can move further on that issue for now.

**Comment by kbaldyga** [comment]
Hey @mpl, hitting the same issue OP posted. Running traefik:2.1.2.
Hopefully I could give some insight on repro steps. 
Run this python script to simulate the 302 redirect (as mentioned above, uncommenting the Content-Length header _fixes_ the problem).
`$ python3 server.py 7777 http://localhost:8080/`
```
#!/usr/bin/env python3

import sys
from http.server import HTTPServer, BaseHTTPRequestHandler

class Redirect(BaseHTTPRequestHandler):
   def do_GET(self):
       self.send_response(302)
       self.send_header('Location', sys.argv[2])
#       self.send_header('Content-Length', 0)
       self.end_headers()

HTTPServer(("", int(sys.argv[1])), Redirect).serve_forever()
```

dynamic_conf.yml (replace LOCAL_IP with something traefik can access)
```
http:
  routers:
    test:
      entryPoints:
        - web
      service: content
      rule: "PathPrefix(`/test`)"
      middlewares:
        - max_request_body_10_megabytes

  middlewares:
    max_request_body_10_megabytes:
      buffering:
        maxRequestBodyBytes: 1000000

  services:
    content:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://LOCAL_IP:7777/"
```
traefik.yml
```
traefik.yml
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

entryPoints:
  web:
    address: ":80"
```

```
$ curl -v localhost/test
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /test HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Thu, 23 Jan 2020 10:34:02 GMT
< Content-Length: 21
< Content-Type: text/plain; charset=utf-8
```
