### ISSUE TITLE
404 page not found after 1-2 days

### ISSUE THREAD

**Issue by v0idp** [containous/traefik#4467]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a new container for bitwarden with all the labels set to work with traefik.

### What did you expect to see?

traefik redirect properly to bitwarden with domain

### What did you see instead?

It works for 1-2 days but for some reason it randomly disappears from the webpanel and when visiting the domain it says 404 page not found. it does work for 1-2 days fine tho. no error logs in bitwarden, neither traefik.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:37PM
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
insecureskipverify = true
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[acme]
acmeLogging = true
email = "voidp@protonmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 30

[[acme.domains]]
  main = "*.viscode.me"
[[acme.domains]]
  main = "viscode.me"

[entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth]
    [entryPoints.traefik.auth.basic]
      removeHeader = true
      users = [
        "BEEPBOOP",
      ]

[api]
entryPoint = "traefik"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "viscode.me"
watch = true
exposedbydefault = false
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

like I said there we no useful logs sadly. The config is set to INFO but I also tried with DEBUG. If you still need these please let me know
