### ISSUE TITLE
High memory usage when using custom error pages

### ISSUE THREAD

**Issue by Aisbergg** [containous/traefik#4474]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Running Traefik as a reverse proxy in front of containerized micro services
- Traefik itself is run in a Docker container as part of the Docker Swarm (only one node)
- creating some traffic (140MBit/s) by downloading data

### What did you expect to see?

- without load the memory footprint is around ~30MB
- when some traffic is generated it should not peek as much as it does

### What did you see instead?

- very high memory usage (450MB) until the memory limit of the cgroup was reached and traefik got killed by the OOM killer

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": 0,
  "GraceTimeOut": 0
 },
 "GraceTimeOut": 0,
 "Debug": false,
 "CheckNewVersion": false,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "Tracing": null,
 "LogLevel": "INFO",
 "EntryPoints": {
  "dashboard": {
   "Address": "xxxx",
   "TLS": {
    "MinVersion": "VersionTLS12",
    "CipherSuites": [],
    "Certificates": null,
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    },
    "DefaultCertificate": null,
    "SniStrict": false
   },
   "Redirect": null,
   "Auth": {
    "basic": {}
   },
   "WhitelistSourceRange": null,
   "WhiteList": {},
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "healthcheck": {
   "Address": "xxxx",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "http": {
   "Address": "xxxx",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": true,
   "ProxyProtocol": null,
   "ForwardedHeaders": {
    "Insecure": false,
    "TrustedIPs": []
   }
  },
  "https": {
   "Address": "xxxx",
   "TLS": {
    "MinVersion": "VersionTLS12",
    "CipherSuites": [],
    "Certificates": null,
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    },
    "DefaultCertificate": null,
    "SniStrict": false
   },
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "WhiteList": null,
   "Compress": true,
   "ProxyProtocol": null,
   "ForwardedHeaders": {
    "Insecure": false,
    "TrustedIPs": []
   }
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": {
  "Email": "xxxx",
  "Domains": null,
  "Storage": "xxxx",
  "StorageFile": "",
  "OnDemand": false,
  "OnHostRule": false,
  "CAServer": "",
  "EntryPoint": "xxxx",
  "KeyType": "xxxx",
  "DNSChallenge": null,
  "HTTPChallenge": null,
  "TLSChallenge": null,
  "DNSProvider": "",
  "DelayDontCheckDNS": 0,
  "ACMELogging": false,
  "OverrideCertificates": false,
  "TLSConfig": null
 },
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": true,
 "RootCAs": null,
 "Retry": {
  "Attempts": 20
 },
 "HealthCheck": {
  "Interval": 60000000000
 },
 "RespondingTimeouts": {
  "ReadTimeout": 0,
  "WriteTimeout": 0,
  "IdleTimeout": 360000000000
 },
 "ForwardingTimeouts": {
  "DialTimeout": 30000000000,
  "ResponseHeaderTimeout": 0
 },
 "AllowMinWeightZero": false,
 "KeepTrailingSlash": false,
 "Web": null,
 "Docker": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "TemplateVersion": 0,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxx",
  "Domain": "",
  "TLS": null,
  "ExposedByDefault": false,
  "UseBindPortIP": false,
  "SwarmMode": true,
  "Network": "",
  "SwarmModeRefreshSeconds": 20
 },
 "File": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "TemplateVersion": 0,
  "DebugLogGeneratedTemplate": false,
  "Directory": "",
  "TraefikFile": ""
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": {
  "EntryPoint": "dashboard",
  "Dashboard": true,
  "Debug": false,
  "CurrentConfigurations": null,
  "Statistics": null
 },
 "Metrics": null,
 "Ping": {
  "EntryPoint": "healthcheck"
 },
 "HostResolver": null,
 "ConfigFile": "/container/traefik.toml"
}
```

The Configuration on each Docker Container looks like:

```yaml
labels:
  - traefik.enable=true
  - traefik.docker.network=xxx
  - traefik.port=8080
  - traefik.weight=10
  - traefik.frontend.errors.network.backend=error
  - traefik.frontend.errors.network.query=/{status}.html
  - traefik.frontend.errors.network.status=400,401,405,408,429,500-599
  - traefik.frontend.headers.STSIncludeSubdomains=true
  - traefik.frontend.headers.STSPreload=true
  - traefik.frontend.headers.STSSeconds=315360000
  - traefik.frontend.passHostHeader=true
  - traefik.frontend.priority=10
  - traefik.frontend.redirect.entryPoint=https
  - traefik.frontend.redirect.permanent=true
  - traefik.frontend.rule=Host:xxx
  - traefik.backend.loadbalancer.method=drr
  - traefik.backend.loadbalancer.stickiness.cookieName=xxx
  - traefik.backend.loadbalancer.stickiness=true
  - traefik.backend.loadbalancer.swarm=true
```

---

I will try to create a pprof statistic. I have to check how this is done first.

**Comment by Aisbergg** [comment]
I tested it on my local machine and the result was the same. When serving big files with Nginx as a webserver and Traefik in front of it, then traefik will kneel down. The CPU usage is very high and the memory usage peaked at 2 GB. I will try to create a vagrant setup that behaves the same. Until then here are my pprof samples: [pprof.zip](https://github.com/containous/traefik/files/2840245/pprof.zip)

The heap:

![heap](https://user-images.githubusercontent.com/14318942/52403985-3dca3a80-2ac8-11e9-9e7c-a06a119ced5d.png)

**Comment by jlevesy** [comment]
Hello @Aisbergg,

Thanks for opening the issue and for the insightful pprof sample, I'm having a look at this right now !

**Comment by jlevesy** [comment]
Hello @Aisbergg,

Can you try to disable the custom error pages for your backend and see if it improves the situation ?

Thanks

**Comment by Aisbergg** [comment]
Yes, without the error pages on a Docker based service the memory issue does not occur. 
I created a little test environment that demonstrates the issue: https://github.com/Aisbergg/Traefik-memory-usage-demonstration . The README.md will tell you more about what I've done.

**Comment by lfniederauer** [comment]
Some thoughts:
Map the files of /var/www/webroot to a volume, they communicate over the swarm overlay.
Is really necessary the attachable on the networks?
Learning traefik, I had some issues with the cipher suite and it´s ordering. I can point to something but can´t help. The cipher TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305" caught my attention. I´ve ended up in this article: https://blog.gopheracademy.com/advent-2016/exposing-go-on-the-internet/
You still can bypass traefik for serving files and run side-by-side with a nginx reverse service.
You can use a redis service on the stack and use nginx cache.

**Comment by Aisbergg** [comment]
I found some time and created a most basic setup consisting only of a webserver and Traefik. Traefiks configuration looks like this:

```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"

[file]
  [frontends]
    # webservice without error pages
    [frontends.frontend1]
      entryPoints = ["http"]
      backend = "backend1"
      [frontends.frontend1.routes]
        [frontends.frontend1.routes.route0]
          rule = "Host:without-errorpages.dev.local"

    # webservice with error pages
    [frontends.frontend2]
      entryPoints = ["http"]
      backend = "backend1"
      [frontends.frontend2.routes]
        [frontends.frontend2.routes.route0]
          rule = "Host:with-errorpages.dev.local"
      [frontends.frontend2.errors]
        [frontends.frontend2.errors.errorPage0]
          status = ["500-599"]
          backend = "backend-error"
          query = "/{status}.html"

    [backends.backend1]
      [backends.backend1.servers]
        [backends.backend1.servers.server0]
          url = "http://127.0.0.1:8080"

    [backends.backend-error]
      [backends.backend-error.servers]
        [backends.backend-error.servers.server0]
          url = "http://127.0.0.1:8080"
```

If querying the webservice 1 everything is fine, but querying the webservice 2 which has custom error pages defined will result in hugh memory usage. So it is indeed the error pages feature described here: https://docs.traefik.io/configuration/commons/#custom-error-pages

The whole setup can be found here: https://github.com/Aisbergg/Traefik-memory-usage-demonstration/tree/master/simple%20setup
