### ISSUE TITLE
Filtering disabled container gitlab,

### ISSUE THREAD

**Issue by MRisto** [containous/traefik#4484]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I configured traefik to redirect subdomains to the containers. But this doesnt work for one container i get the message 
time="2019-02-11T15:08:44Z" level=debug msg="Filtering disabled container gitlab_app.1"

I tried different settings since yesterday, Didn't find a solution.

### What did you expect to see?

There should be a subdomain created for docker container gitlab. A subdomain was created for docker container whoami.

### What did you see instead?

There was not a docker created.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using docker swarm on a single machine (only one manager node at the moment).

```toml
#Traefik Global Configuration
checkNewVersion = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]

#Define Docker Backend Configuration
[docker]
domain = "example.com"
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
network = "traefik_net"
swarmMode = true

[acme]
email = "test@example.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
  main = "example.com"

# (paste your configuration here)
```

gitlab-stack.yml
```
version: "3.6"
services:
  app:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    networks:
      - traefik_net
    ports:
     - "9080:80"
     - "9443:443"
    volumes:
      - "/srv/docker/configs/gitlab/config:/etc/gitlab"
      - "/srv/docker/configs/gitlab/logs:/var/log/gitlab"
      - "/srv/docker/configs/gitlab/data:/var/opt/gitlab"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:gitlab.example.com"
      
networks:
  traefik_net:
    external: true

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```

time="2019-02-11T15:08:44Z" level=debug msg="Filtering disabled container gitlab_app.1"
```

I did not find an issue, which helped me. I dont find information on the docs for filtering disabled. I have 4 more containers, which configuration works fine.
