### ISSUE TITLE
Traefik - Ingress weights not respected

### ISSUE THREAD

**Issue by mathieuherbert** [containous/traefik#4494]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I launch Traefik on K8S as Ingress controller on **minikube** and on **Docker For Mac**

I create 2 services (serviceA, serviceB) (with 3 replicas on each service)
I create 1 ingress with the following annotation
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service-weights: |
      servicea: 30
      serviceb: 70
  name: ingress
spec:
  rules:
  - host: myhost.com
    http:
      paths:  
       - backend:
          serviceName: servicea
          servicePort: 80
         path: /  
       - backend:
          serviceName: serviceb
          servicePort: 80 
         path: /

```
### What did you expect to see?

Traffic should be forwarder to both services with a weight.

### What did you see instead?
Traffic is only routed to the service that has more than 50% as weight. No traffic is routed to the other one. If put 50% on each service, traffic is routed to both services.
I can see on the Dashboard that weights are well configured.
```

Server | Weight
http://172.17.0.10:8080 | 10000
http://172.17.0.9:8080 | 10000
http://172.17.0.11:8080 | 10000
http://172.17.0.12:8080 | 23333
http://172.17.0.16:8080 | 23333
http://172.17.0.15:8080 | 23333
```

I tested also with one replicas for each service and I don't have the issue (weights are ok).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Tested on Traefik version 1.7.9 and 1.7.7
Kubernetes 1.13.2 (for minkube)
```

**Comment by pablokbs** [comment]
I'm getting the same issue too:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: v1.local
    http:
      paths:
      - backend:
          serviceName: hello-v1-svc
          servicePort: 80
  - host: v2.local
    http:
      paths:
      - backend:
          serviceName: hello-v2-svc
          servicePort: 80
```

I'm putting 51% for v1 and I'm not getting a single request going to v2.
