### ISSUE TITLE
Kubernetes Example Broken (Port 80 no longer supported by Minikube)

### ISSUE THREAD

**Issue by patientplatypus** [containous/traefik#4495]
This is a **bug**. 

I'm going through and working through the example here: https://docs.traefik.io/user-guide/kubernetes/, on how to set up a kubernetes ingress controller. After some time I discovered that port 80 is no longer supported by minikube (see here: https://github.com/kubernetes/minikube/issues/3677) as they have now migrated to 8443 for https. However, this means that the example provided in your docs no longer works.

 I've tried taking the naive approach and changing all the ports from 80 to 8443 in your examples (specifically on these files: `kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml`, `kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml`, `kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-deployment.yaml`) and running again. This is the output that I get: 

```
patientplatypus:~/Documents/HomePage:16:59:08$minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
patientplatypus:~/Documents/HomePage:17:06:47$minikube start
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...
Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
patientplatypus:~/Documents/HomePage:17:09:00$kubectl apply -f ./resource-manifests/traefikRole.yaml
clusterrole.rbac.authorization.k8s.io "traefik-ingress-controller" created
clusterrolebinding.rbac.authorization.k8s.io "traefik-ingress-controller" created
patientplatypus:~/Documents/HomePage:17:09:22$kubectl apply -f ./resource-manifests/traefikDeploy.yaml
serviceaccount "traefik-ingress-controller" created
deployment.extensions "traefik-ingress-controller" created
service "traefik-ingress-service" created
patientplatypus:~/Documents/HomePage:17:09:22$kubectl apply -f ./resource-manifests/traefikIngress.yaml
service "traefik-web-ui" created
ingress.extensions "traefik-web-ui" created
patientplatypus:~/Documents/HomePage:17:09:24$kubectl --namespace=kube-system get pods --watch
NAME                                          READY     STATUS    RESTARTS   AGE
coredns-86c58d9df4-jrssv                      1/1       Running   0          1m
coredns-86c58d9df4-rx666                      1/1       Running   0          1m
etcd-minikube                                 1/1       Running   0          22s
kube-addon-manager-minikube                   1/1       Running   0          17s
kube-apiserver-minikube                       1/1       Running   0          24s
kube-controller-manager-minikube              1/1       Running   0          16s
kube-proxy-bgnml                              1/1       Running   0          1m
kube-scheduler-minikube                       1/1       Running   0          27s
kubernetes-dashboard-ccc79bfc9-zpmwj          1/1       Running   0          1m
storage-provisioner                           1/1       Running   0          1m
traefik-ingress-controller-5dd7bc8748-dkn5j   1/1       Running   0          1m
```

So far, so good. Everything appears to be running.

**However:**

```
patientplatypus:~/Documents/HomePage:17:11:32$curl $(minikube ip):8443

patientplatypus:~/Documents/HomePage:17:11:44$
```

Curling shows nothing. You can see the files 

Here are the three files that I use (they are the same in the examples you have online with the change of port 80 to 8443. Note that using port 80 also no longer works as, again, minikube no longer supports port 80).

**traefikRole.yaml**

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
```

**traefikIngress.yaml**

```
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: web
    port: 8443
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
  - host: traefik-ui.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: web
```

**traefikDeploy.yaml**

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 8443
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8443
      name: web
    - protocol: TCP
      port: 8080
      name: admin
  type: NodePort
```
