### ISSUE TITLE
HTTP to HTTPS redirect not working as expected with Docker, Nextcloud and port forwarding

### ISSUE THREAD

**Issue by seth100** [containous/traefik#4501]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In my router I have port `55123` -> `443` (local port) port forwarding. I access my Nextcloud like this:

`https://MYDOMAIN:55123/`

### What did you expect to see?

The request:

`https://MYDOMAIN:55123/`

should be maintained to `https`, in my case Nextcloud does redirect to `[PREFIX]/login` so the result should be:

`https://MYDOMAIN:55123/login`

### What did you see instead?

It redirects now to:

`http://MYDOMAIN:55123/login`

(same thing for many other redirections like when using token authentication etc...)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

      [entryPoints.https]
      address = ":443"

        [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
            CertFile = "/certs/mycert.crt"
            KeyFile = "/certs/mycert.key"

    [docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "MYDOMAIN"
    watch = true
    exposedByDefault = false

      [docker.tls]
      insecureSkipVerify = true
```

(I use my self signed cert).
In the Nextcloud container from `docker-compose.yml` I have:

```yml
labels:
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.backend=nextcloud"
    - "traefik.docker.network=MYNET"
    - "traefik.frontend.rule=Host:MYDOMAIN"
    - "traefik.frontend.passHostHeader=true"
    - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https" # tried this to fix, no luck
    - "traefik.frontend.headers.referrerPolicy=no-referrer"
    - "traefik.frontend.headers.forceSTSHeader=true"
    - "traefik.frontend.headers.STSSeconds=31536000"
    - "traefik.frontend.headers.STSIncludeSubdomains=true"
    - "traefik.frontend.headers.customResponseHeaders=Front-End-Https:on"
    - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
    - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
    - "traefik.frontend.redirect.permanent=true"
```

and in the Traefik container:

```yml
labels:
    - "traefik.enable=true"
    - "traefik.port=8282"
    - "traefik.backend=traefik" 
    - "traefik.docker.network=MYNET"
```

I remember it was working before (a month ago before I updated the Docker images) so I don't know if it's due to Nextcloud or Traefik, but I see around that others have a similar issue with Traefik regarding http to https.

I hope someone can help me!
Thank you!
