### ISSUE TITLE
File watch doesn't work

### ISSUE THREAD

**Issue by Leon99** [containous/traefik#4502]
As seen on the screenshot, servers don't reload on editing dynamic.toml (`server2` was removed after traefik started):

![image](https://user-images.githubusercontent.com/6840381/52927704-ee212400-338f-11e9-851f-32008761d4ff.png)

### Configuration 

docker-compose.yml:
```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:alpine
    ports:
      - "21000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./config/:/config/
```

traefik.toml:

```toml
logLevel = "DEBUG"

[entryPoints]
    [entryPoints.http]
    address = ":80"
[docker]
[api]

[ping]
entryPoint = "http"

[accessLog]

[file]
  watch = true
  directory = "/config/"
  
```

config/dynamic.toml:
```toml
[frontends]
  [frontends.api]
  backend = "api"
    [frontends.api.routes.test_1]
    rule = "PathPrefixStrip: /api"

[backends]
  [backends.api]
    # ...
    [backends.api.servers.server1]
    url = "http://server1"
    [backends.api.servers.server2]
    url = "http://server2"
```

### Environment
Windows 10 v1809
Docker Desktop 2.0.0.3

Any ideas appreciated. Happy to do any additional debugging required.
