### ISSUE TITLE
traefik load certificate but not appear ssl in browser

### ISSUE THREAD

**Issue by xpoveda** [containous/traefik#4514]
Hi, I want to have securized any site with traefik and ssl certificate but not works.

I have, by example, the subdomain `portainer.yourdomain.com`. 

When I go to internet browser and put **https:**//portainer.yourdomain.com the url appears directly as unsafe, does not indicate an incorrect certificate in red or, evidently, the usual green padlock.

I have created the ssl certificates with sslforfree tool with a real subdomain, and now I have the files 
```
portainer.ca_bundle.crt 
portainer.certificate.crt
portainer.private.key
```
I have concatenated `portainer.ca_bundle.crt + portainer.certificate.crt`  in new file `portainer.fullchain.pem`. I have tested this full chain certificate and is correct.

I use `traefik:alpine` or `traefik:latest`, same issue.

Note: I have tested with whoami and same issue.
The server return 301 error.
```
Request URL: https://whoami.yoursite.com/
Request Method: GET
Status Code: 301  (from disk cache)
Remote Address: XXXXXXXXXXX:443
Referrer Policy: no-referrer-when-downgrade
cache-control: max-age=3600
cf-ray: 4ad39db33b97b77d-CDG
date: Fri, 22 Feb 2019 18:46:32 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Fri, 22 Feb 2019 19:46:32 GMT
location: http://whoami.yoursite.com/
server: cloudflare
status: 301
vary: Accept-Encoding
Provisional headers are shown
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
```

My stack.yml (it works with docker swarm) is:
```
version: '3'

services:

  traefik:
    image: traefik:alpine
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --logLevel=DEBUG 

    networks:
      - traefik-net
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/certs:/etc/traefik/certs

    deploy:
      placement:
        constraints: [node.role==manager]      
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure   

  portainer:
    image: portainer/portainer
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    deploy:
      replicas: 1    
      placement:
        constraints: [node.labels.Master== true ]
      labels:
        - traefik.enable=true
        - traefik.port=9000
        - traefik.backend=portainer        
        - traefik.frontend.rule=Host:portainer.yourdomain.com

volumes:
   portainerdata:
   
networks:
  traefik-net:
```

My `traefik.toml` is
```
defaultEntryPoints = ["http", "https"]

[entryPoints]

  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"

    [entryPoints.https.tls]

      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/traefik/certs/portainer.fullchain.pem"
      KeyFile = "/etc/traefik/certs/portainer.private.key"

[traefikLog]
  filePath = "/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/access.log"
  format = "json"
```

In the  `traefik.log` it seems all is ok but not works....
```
[redhat@master1 ~]$ docker exec -it 43779643c6c5 /bin/sh
/ # grep cert traefik.log
{"level":"info","msg":"No tls.defaultCertificate given for https: using the first item in tls.certificates as a fallback.","time":"2019-02-22T13:09:32Z"}
{"level":"debug","msg":"Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":{\"file\":\"/access.log\",\"format\":\"json\"},\"TraefikLogsFile\":\"\",\"TraefikLog\":{\"file\":\"/traefik.log\",\"format\":\"json\"},\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":[{\"CertFile\":\"/etc/traefik/certs/portainer.fullchain.pem\",\"KeyFile\":\"/etc/traefik/certs/portainer.private.key\"}],\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":null,\"Optional\":false},\"DefaultCertificate\":{\"CertFile\":\"/etc/traefik/certs/portainer.fullchain.pem\",\"KeyFile\":\"/etc/traefik/certs/portainer.private.key\"},\"SniStrict\":false},\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Path\":\"/\",\"Auth\":null,\"Debug\":false},\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"traefik\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":true,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15},\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":{\"EntryPoint\":\"traefik\"},\"HostResolver\":null}","time":"2019-02-22T13:09:32Z"}
{"level":"debug","msg":"Add certificate for domains portainer.yourdomain.com","time":"2019-02-22T13:09:32Z"}
{"level":"debug","msg":"Add certificate for domains portainer.yourdomain.com","time":"2019-02-22T13:09:32Z"}
{"level":"debug","msg":"Add certificate for domains portainer.yourdomain.com","time":"2019-02-22T13:09:32Z"}
{"level":"debug","msg":"Add certificate for domains portainer.yourdomain.com","time":"2019-02-22T13:09:47Z"}
```

In my machine
```
[redhat@master1 ~]$ ls -lt *stack*
-rwxrwxrwx. 1 redhat root   3170 Feb 22 13:09 stack.yml
-rwxrwxrwx. 1 redhat redhat   49 Feb 21 16:06 lanza_stack.sh

[redhat@master1 ~]$ cat lanza_stack.sh
docker stack deploy --compose-file stack.yml mi

[redhat@master1 ~]$ cd certs
[redhat@master1 certs]$ ls -lt *portainer*
-rw-rw-r--. 1 redhat redhat 3595 Feb 22 11:35 portainer.fullchain.pem
-rw-rw-r--. 1 redhat redhat 1703 Feb 21 16:50 portainer.private.key
-rw-rw-r--. 1 redhat redhat 1646 Feb 21 16:50 portainer.ca_bundle.crt
-rw-rw-r--. 1 redhat redhat 1947 Feb 21 16:50 portainer.certificate.crt
```

Thanks so much in advance!!.

Xavier.
