### ISSUE TITLE
trailing slash redirect still necessary

### ISSUE THREAD

**Issue by devster31** [containous/traefik#4521]
### Do you want to request a *feature* or report a *bug*?

Possible bug

### What did you do?
Launched an instance of https://github.com/thelounge/thelounge behind traefik.
With labels as follows to serve the instance in a subpath
```yaml
services:
  thelounge:
    ...
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/irc"
    ...
```
requests going to `domain.com/irc` fail to load the required components of the application, while `domain.com/irc/` works as expected.
However, using the following, found in an old issue I can't find anymore, seems to work
```yaml
services:
  thelounge:
    ...
    labels:
      - "traefik.frontend.redirect.regex=^(.*)/irc$$"
      - "traefik.frontend.redirect.replacement=$$1/irc/"
      - "traefik.frontend.rule=PathPrefix:/irc;ReplacePathRegex: ^/irc/(.*) /$$1"
    ...
```
I believe the whole point of the original pull request was to avoid the above and by default redirect to a trailing slash path.
From the browser these seem to be 2 subsequent requests:
```
curl 'http://domain.com/irc'
curl 'http://domain.com/js/bundle.js' -H 'Pragma: no-cache' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en,it;q=0.9,fr;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Cookie: io=tebKKRp1xd5iFlelAAAB' -H 'Connection: keep-alive' --compressed
```
Original issue here https://github.com/thelounge/thelounge/issues/3043
### What did you expect to see?
App regularly served with trailing slash from subpath

### What did you see instead?
App fails to load as original path is stripped from subsequent requests

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
---
version: '3.7'

networks:
  backend: {}

services:
  thelounge:
    # environment:
    #   - DEBUG=express:*
    command: thelounge -c reverseProxy=true start
    container_name: thelounge
    image: thelounge/thelounge:alpine
    labels:
      # - "traefik.frontend.rule=PathPrefixStrip:/irc"
      # traefik doesn't play well with paths
      - "traefik.frontend.redirect.regex=^(.*)/irc$$"
      - "traefik.frontend.redirect.replacement=$$1/irc/"
      - "traefik.frontend.rule=PathPrefix:/irc;ReplacePathRegex: ^/irc/(.*) /$$1"
    networks:
      - backend
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - "${MOUNT}/.thelounge:/var/opt/thelounge" # bind lounge config from the host's file system

  traefik:
    command:
      - --accesslog
      - --api # defaults to port 8080
      - --docker
      - --docker.network=backend
      - --defaultentrypoints=http
    image: traefik:maroilles-alpine
    networks:
      - backend
      - default
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # So that Traefik can listen to the Docker events
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Within the app the following seems to happen with a trailing slash in the original request
```
thelounge    | Mon, 11 Feb 2019 22:29:21 GMT express:router dispatching GET /
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router query  : /
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router expressInit  : /
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router allRequests  : /
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router index  : /
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router dispatching GET /js/bundle.vendor.js
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router query  : /js/bundle.vendor.js
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router expressInit  : /js/bundle.vendor.js
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router allRequests  : /js/bundle.vendor.js
thelounge    | Mon, 11 Feb 2019 22:29:22 GMT express:router index  : /js/bundle.vendor.js
...
```
but not without
```
thelounge    | Mon, 11 Feb 2019 22:38:45 GMT express:router dispatching GET /
thelounge    | Mon, 11 Feb 2019 22:38:45 GMT express:router query  : /
thelounge    | Mon, 11 Feb 2019 22:38:45 GMT express:router expressInit  : /
thelounge    | Mon, 11 Feb 2019 22:38:45 GMT express:router allRequests  : /
```

**Comment by jbdoumenjou** [comment]
Hi @devster31 , 
Have you tried the `keepTrailingSlash` option (cf [doc](https://docs.traefik.io/configuration/commons/#main-section)) ?

**Comment by devster31** [comment]
Behaviour does not seem to change.
I found the pull request: https://github.com/containous/traefik/pull/1638
I was naively expecting the same behaviour of `proxy_pass` in nginx, which means that a `PathPrefixStrip:/irc` returns a 301 to `/irc/` and forwards `/` to the backend.

I tried the following config with the following changes:
```yaml
---
version: '3.7'

services:
  thelounge:
    ...
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/irc"
    ...

  traefik:
    command:
      - --accesslog
      - --api # defaults to port 8080
      - --docker
      - --docker.network=backend
      - --defaultentrypoints=http
      - --keeptrailingslash=true
      ...
```
comparing to the docs you linked, this behaviour in particular > `http://foo.com/path/ | true | Path:/path | 404` does not seem to apply.
```
curl 'http://10.0.0.161/irc' -v
*   Trying 10.0.0.161...
* TCP_NODELAY set
* Connected to 10.0.0.161 (10.0.0.161) port 80 (#0)
> GET /irc HTTP/1.1
> Host: 10.0.0.161
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 5778
< Content-Security-Policy: block-all-mixed-content; default-src 'none'; form-action 'self'; connect-src 'self' ws: wss:; style-src 'self' https: 'unsafe-inline'; script-src 'self'; worker-src 'self'; child-src 'self'; manifest-src 'self'; font-src 'self' https:; media-src 'self' https:; img-src 'self' data: https://user-images.githubusercontent.com
< Content-Type: text/html; charset=utf-8
< Date: Mon, 25 Feb 2019 19:57:18 GMT
< Etag: W/"1692-jD2pvers7HxluZt7pQf+PFOrv4U"
< Referrer-Policy: no-referrer
< X-Content-Type-Options: nosniff
<
...
```
requesting `/irc/` returns an unbroken page, but it did so even before turning on `--keeptrailingslash`.
That was the entire purpose of
```yaml
      - "traefik.frontend.redirect.regex=^(.*)/irc$$"
      - "traefik.frontend.redirect.replacement=$$1/irc/"
      - "traefik.frontend.rule=PathPrefix:/irc;ReplacePathRegex: ^/irc/(.*) /$$1"
```
