### ISSUE TITLE
Error msg in logs "Failed to retrieve auth configuration for ingress / failed to load auth credentials " but ingress rule configured as expected

### ISSUE THREAD

**Issue by looztra** [containous/traefik#4523]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- **Given** I use traefik (v1.7.9) as an Ingress Controller in a Kubernetes instance
- **When** I create a __Kubernetes Ingress Rule__ that refers to a secret holding the basic auth infos (both the ingress rule and the secret are in the same namespace called `ingress-controllers`) with : 

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-secret: traefik-ui-auth
    ingress.kubernetes.io/auth-type: basic
    kubernetes.io/ingress.class: traefik
  name: traefik-web-ui
  namespace: ingress-controllers
spec:
  rules:
  - host: traefik-ui.192.168.99.100.xip.io
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: admin
```

and the secret descriptor is : 

```yaml
apiVersion: v1
data:
  auth: ZW1pbGU6JGFwcjEkV3B2LnRlL0MkZE5FMHQ1NjBkbFBTNUlqNTI5TmNRLgo=
kind: Secret
metadata:
  name: traefik-ui-auth
  namespace: ingress-controllers
type: Opaque
```

### What did you expect to see?

- The ingress rule is applied and protected by basic auth
- Nothing shows up in logs

### What did you see instead?

- The ingress rule is applied and protected by basic auth
- An error message is printed in logs :

```bash
time="2019-02-25T09:29:52Z" level=error msg="Failed to retrieve auth configuration for ingress ingress-controllers/traefik-web-ui: failed to load auth credentials: secret \"ingress-controllers\"/\"traefik-ui-auth\" not found"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Full set of descriptors (minus the secret) to test in minikube (for instance)
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controllers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: ingress-controllers
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: awesome:traefik-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: awesome:traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awesome:traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: ingress-controllers
---
apiVersion: v1
data:
  traefik.toml: |
    insecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "techops@awesome.com"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    [acme.httpChallenge]
      entryPoint = "http"
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: ingress-controllers
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-endpoint
  namespace: ingress-controllers
spec:
  loadBalancerIP: ""
  ports:
  - name: main-http
    port: 80
    targetPort: main-http
  - name: main-https
    port: 443
    targetPort: main-https
  selector:
    app: traefik-ingress-lb
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: ingress-controllers
spec:
  ports:
  - name: admin
    port: 8080
    targetPort: admin
  selector:
    app: traefik-ingress-lb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: traefik-ingress-lb
  name: traefik-ingress-controller
  namespace: ingress-controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
    spec:
      containers:
      - args:
        - --configfile=/config/traefik.toml
        - --web
        - --kubernetes
        image: traefik:v1.7.9
        imagePullPolicy: Always
        name: traefik
        ports:
        - containerPort: 80
          name: main-http
        - containerPort: 443
          name: main-https
        - containerPort: 8080
          name: admin
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
        volumeMounts:
        - mountPath: /acme
          name: traefik-acme
        - mountPath: /config
          name: traefik-config
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: traefik-acme
        persistentVolumeClaim:
          claimName: traefik-acme
      - configMap:
          name: traefik-conf
        name: traefik-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-secret: traefik-ui-auth
    ingress.kubernetes.io/auth-type: basic
    kubernetes.io/ingress.class: traefik
  name: traefik-web-ui
  namespace: ingress-controllers
spec:
  rules:
  - host: traefik-ui.192.168.99.100.xip.io
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme
  namespace: ingress-controllers
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard

```
