### ISSUE TITLE
Namespaces options in Kubernetes provider is not working

### ISSUE THREAD

**Issue by vrobert78** [containous/traefik#4524]
Hi,

i have passed a lot of time about how to use the options namespaces in the kubernetes ingress provider.

In all examples, traefik have args in the daemonset or deployment.
The "--kubernetes" must be remove, otherwise traefik does not take the kubernetes params in its configuration file.

One more thing, a example of a rolebindings could be a good idea:

```
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: traefik-role
    namespace: my-private-namespace
  rules:
    - apiGroups:
        - ""
      resources:
        - services
        - endpoints
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - ingresses
      verbs:
        - get
        - list
        - watch


# create Traefik service account
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: traefik-service-account
    namespace: my-private-namespace 


# bind role with service account
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: traefik-role-binding
    namespace: my-private-namespace
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: traefik-role
  subjects:
  - kind: ServiceAccount
    name: traefik-service-account
    namespace: my-private-namespace 
```

Regards,
