### ISSUE TITLE
Request modifiers not processed for Host only Kubernetes ingress

### ISSUE THREAD

**Issue by mterring** [containous/traefik#4525]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

An ingress configuration such as the following:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: subdomain-backend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/request-modifier: "AddPrefix: /subdomain"
spec:
  rules:
    - host: subdomain.mysite.com
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: http`

### What did you expect to see?

This should route requests prefixed with /subdomain to the backend.

### What did you see instead?

The AddPrefix rule was not passed into Traefik, so the frontend routing did not add the prefix.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes provider

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by mmatur** [comment]
Hi @mterring,

Thanks for your feedback.

After some investigation its due to
https://github.com/containous/traefik/blob/b48ea1e17388f334264a1e15d2de7ac02cf79141/provider/kubernetes/kubernetes.go#L570

As workaround you can use ingress like that (defining :
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: subdomain-backend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/request-modifier: "AddPrefix: /subdomain"
spec:
  rules:
    - host: subdomain.mysite.com
      http:
        paths:
          - path: / ## <---- add this line
            backend: 
              serviceName: backend
              servicePort: http
```
