### ISSUE TITLE
[K8s - Azure K8s Service] Traefik extremely slow on multi node cluster

### ISSUE THREAD

**Issue by StiviiK** [containous/traefik#4533]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Scaled up my AKS cluster to 2 nodes

### What did you expect to see?

Traefik to respond fast as before with a single node

### What did you see instead?

Extremely slow response times and long loading times, often connection timeout

### Output of `traefik version`:
1.7.9

### Additional informations:
Deployed via helm, values:
```
image: traefik
imageTag: 1.7.9
serviceType: LoadBalancer
whiteListSourceRange: []
externalTrafficPolicy: Local
replicas: 1

podDisruptionBudget: {}

resources: {}

debug:
  enabled: false

deploymentStrategy: {}

securityContext: {}
nodeSelector: {}

affinity: {}

tolerations: []

proxyProtocol:
  enabled: false
  trustedIPs: []
forwardedHeaders:
  enabled: false

  trustedIPs: ["0.0.0.0/8"]
ssl:
  enabled: true
  enforced: true
  permanentRedirect: true
  upstream: false
  insecureSkipVerify: false
  generateTLS: false
  defaultSANList: []
  defaultIPList: []
  defaultCert: ***
  defaultKey: ***
  auth: {}

kvprovider:
  storeAcme: false
  importAcme: false

acme:
  enabled: true
  email: <<EMAIL>>
  onHostRule: true
  staging: false
  logging: true
  domains:
    enabled: true
    domainsList:
      - main: "*.<<DOMAIN>>"
      - sans:
        - "<<DOMAIN>>"
  challengeType: dns-01
  delayBeforeCheck: 0
  dnsProvider:
    name: azure
    azure:
      AZURE_CLIENT_ID: "***"
      AZURE_CLIENT_SECRET: "***"
      AZURE_SUBSCRIPTION_ID: "***"
      AZURE_TENANT_ID: "***"
      AZURE_RESOURCE_GROUP: "***"
  persistence:
    enabled: true
    annotations: {}
    storageClass: "managed-premium"
    accessMode: ReadWriteOnce
    size: 1Gi

dashboard:
  enabled: false
  domain: <<DOMAIN>>
  service: {}
  ingress: {}
  auth: {}
  statistics: {}

service:
  nodePorts:
    http: ""
    https: ""

gzip:
  enabled: true

traefikLogFormat: json

accessLogs:
  enabled: false

  format: common
  fields:
    defaultMode: keep
    names: {}
    headers:
      defaultMode: keep
      names: {}
rbac:
  enabled: true

metrics:
  prometheus:
    enabled: false
    restrictAccess: false
  datadog:
    enabled: false
  statsd:
    enabled: false
deployment:
  hostPort:
    httpEnabled: false
    httpsEnabled: false
    dashboardEnabled: false
sendAnonymousUsage: false
tracing:
  enabled: false
  serviceName: traefik
```

traefik.toml
```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
      permanent = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[kubernetes]
[traefikLog]
  format = "json"
[acme]
email = "****"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
  [acme.dnsChallenge]
  provider = "azure"
[api]
  entryPoint = "traefik"
  dashboard = true
```
