### ISSUE TITLE
Traefik for Kubernetes v1.13.3 returns x509: certificate signed by unknown authority on API Endpoint

### ISSUE THREAD

**Issue by shoaibjdev** [containous/traefik#4545]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Have configured Traefik for Kubernetes v1.13.3 and specified the API Endpoint as below:
```
[kubernetes]
# Kubernetes server endpoint
endpoint = "https://MASKED:6443"
namespaces = ["default","kube-system"]
```

### What did you expect to see?
Have configured Traefik for Kubernetes v1.13.3 and created Cluster Role & Binding as instructed in documentation. Expecting it to read all API endpoints for kubernetes without any issues.
Also able to curl Kubernetes API endpoint without any issues with -k option for curl 

`curl -kv https://MASKED:6443 --cert ./k8s.crt --key ./k8s.key --header "Authorization: Bearer $TOKEN"`

> < HTTP/1.1 200 OK
> < Content-Type: application/json
> < Date: Fri, 01 Mar 2019 09:47:49 GMT
> < Transfer-Encoding: chunked

> {
>   "paths": [
>     "/api",
>     "/api/v1",
>     "/apis",
>     "/apis/",
>     "/apis/admissionregistration.k8s.io",
>     "/apis/admissionregistration.k8s.io/v1alpha1",
>     "/apis/admissionregistration.k8s.io/v1beta1",
>     "/apis/apiextensions.k8s.io",
>     "/swagger.json",
>     "/swaggerapi",
>     "/version"
>   ]

### What did you see instead?

> E0301 12:32:42.115274  170960 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: Get https://MASKED:6443/api/v1/namespaces/ke-production/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.8/traefik_linux-amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
InsecureSkipVerify = true

debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https"]
[traefikLog]
  filePath = "/var/log/traefik.log"
  format   = "json"
[accessLog]
  filePath = "/var/log/access.log"
  format = "json"

[entryPoints]
# Default Backend Config
  [entryPoints.https]
     address = ":443"
    [entryPoints.https.whiteList]
      sourceRange = ["MASKED/24"]
     [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/u01/Traefik-LB/certs/tls.crt"
    KeyFile = "/u01/Traefik-LB/certs/tls.key"

# DASHBOARD UI Config
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.whiteList]
      sourceRange = ["MASKED/24"]
      #useXForwardedFor = true
    [entryPoints.traefik.auth.basic]
    users = [
         "truser:$apr1$X9JrNsX7$Oxn1lvhVzX0Zq0zhA4.y70"
           ]

    [entryPoints.traefik.tls]
        minVersion = "VersionTLS12"
    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
           ]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/u01/Traefik-LB/certs/tls.crt"
    KeyFile = "/u01/Traefik-LB/certs/tls.key"

[api]
   entryPoint = "traefik"
   dashboard = true
   ReadOnly = true

[kubernetes]
# Kubernetes server endpoint
insecureSkipVerify = true
endpoint = "https://MASKED:6443"
namespaces = ["default","kube-system"]
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
E0301 12:32:42.115274  170960 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: Get https://MASKED:6443/api/v1/namespaces/ke-production/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E0301 12:32:42.115283  170960 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: Get https://MASKED:6443/api/v1/namespaces/ug-production/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E0301 12:32:42.115421  170960 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: Get https://MASKED:6443/api/v1/namespaces/kube-system/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
```
