### ISSUE TITLE
HTTP basic auth realm not configured from Consul Catalog

### ISSUE THREAD

**Issue by eigengrau** [containous/traefik#4562]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We configured a traefik frontend with HTTP basic auth via the Consul catalog provider, requesting a custom basic auth realm by assigning the tag `traefik.frontend.auth.basic.realm=foo` to the service. (Our use case is avoiding issues when running multiple frontends with basic auth from the same domain.)

### What did you expect to see?

Traefik should return the header `www-authenticate: Basic realm="foo"`.

### What did you see instead?

Traefik returns the header `www-authenticate: Basic realm="traefik"`.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
defaultEntryPoints = ["http", "https"]
[entryPoints]
    # Entrypoint for HTTP-01 challenges.
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]


    [entryPoints.traefik]
    address = ":9996"
[acme]
…
[consulCatalog]
[consul]
```
