### ISSUE TITLE
traefik occasionally delivers default certificate NET::ERR_CERT_AUTHORITY_INVALID instead ACME

### ISSUE THREAD

**Issue by magiquej** [containous/traefik#4563]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Open frontend url in browser.

### What did you expect to see?

secured webpage

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = true

[acme]
email = "XXXXX"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
  resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
[[acme.domains]]
  main = "*.XXX.asia"
  sans = ["XXX.asia"]
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
traefik          | time="2019-03-06T09:50:31Z" level=debug msg="Serving default cert for request: \"XXX.XXXX.asia\""
traefik          | time="2019-03-06T09:50:41Z" level=debug msg="http: TLS handshake error from 121.162.135.125:56733: EOF"
```

yml file 👍 
```yml
services:
  reverse-proxy:
    image: traefik #The official Traefik docker image
    container_name: traefik
#    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker --docker.domain=xxxx.asia --logLevel=DEBUG
    networks:
      - prometheus
    ports:
      - "80:80"     #The HTTP port
      - "443:443"   #The HTTPS port
      - "8080:8080" #The Web UI (enabled by --api)
    expose:
      - "8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - ./traefik2.toml:/traefik.toml
      - ./acme.json:/acme.json
    env_file:
      - ./local.env
[....]
  mariadb2:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - internal

  wordpress2:
    image: 'bitnami/wordpress:latest'
#    ports:
#      - '80:80'
#      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb2
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:XXX.XXXX.asia"
      - "traefik.docker.network=prometheus"
      - "traefik.enable=true"
      - traefik.port=80
    networks:
      - prometheus
      - internal
```

I can access to my other subdomain with no TLS error. 
Cloudflare and lets encrypt provide the certificate considerated as valid by navigator. I tried to recreate acme.json --> no effect. Same behavior all the time.
