### ISSUE TITLE
ACME Error - CloudFlare failed to find zone is.

### ISSUE THREAD

**Issue by b3vis** [containous/traefik#4575]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Unable to browse to applications behind traefik proxy as no certificate available and it's not auto-renewed. Regenerated CloudFlare Global API key and tested the key in another application for updating A records and that works so I think this is a Traefik problem.

### What did you expect to see?

Traefik to complete the dns-01 challenge and pull in a new wildcard

### What did you see instead?

time="2019-03-11T10:01:10Z" level=error msg="Unable to obtain ACME certificate for domains \"*.xxxx.is,xxxx.is\" : unable to generate a certificate for the domains [*.xxxx.is xxxx.is]: acme: Error -> One or more domains had a problem:\n[*.xxxx.is] [*.xxxx.is] acme: error presenting token: cloudflare: failed to find zone is.: Zone could not be found\n[xxxx.is] [xxxx.is] acme: error presenting token: cloudflare: failed to find zone is.: Zone could not be found\n"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
email = "xxxx"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.xxxx.is"
  sans = ["xxxx.is"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "xxxx.is"
watch = true
exposedbydefault = false

[file]
  filename = "/rules.toml"
  watch = true
[api]
entryPoint = "traefik"
dashboard = true
address = ":8080"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2019-03-11T10:01:08Z" level=info msg="legolog: [INFO] [*.xxxx.is, xxxx.is] acme: Obtaining bundled SAN certificate"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [*.xxxx.is] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/<snip>"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [xxxx.is] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/<snip>"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [xxxx.is] acme: Could not find solver for: tls-alpn-01"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [xxxx.is] acme: Could not find solver for: http-01"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [xxxx.is] acme: use dns-01 solver"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [*.xxxx.is] acme: use dns-01 solver"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [xxxx.is] acme: Preparing to solve DNS-01"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [*.xxxx.is] acme: Preparing to solve DNS-01"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [xxxx.is] acme: Cleaning DNS-01 challenge"
time="2019-03-11T10:01:09Z" level=info msg="legolog: [WARN] [xxxx.is] acme: error cleaning up: cloudflare: failed to find zone is.: Zone could not be found "
time="2019-03-11T10:01:09Z" level=info msg="legolog: [INFO] [*.xxxx.is] acme: Cleaning DNS-01 challenge"
time="2019-03-11T10:01:10Z" level=info msg="legolog: [WARN] [*.xxxx.is] acme: error cleaning up: cloudflare: failed to find zone is.: Zone could not be found "
```
