### ISSUE TITLE
Add more explanation to the Quickstart

### ISSUE THREAD

**Issue by johncmunson** [containous/traefik#4581]
In my mind, a quality "quickstart" should very quickly demonstrate a core use case while also thoroughly explaining every step of the way.

The only issue I see with the existing quickstart is the lack of explanation regarding labels.

```
# ... 
  whoami:
    image: containous/whoami
    labels:
      - "traefik.router.rule=Host:whoami.docker.localhost"
```

It's very unclear as to why some sort of router rule is needed in order for traefik to dynamically discover new service instances and add them to the load balancer.

Some more explanation here would be much appreciated!
