### ISSUE TITLE
accessLog.filters does not work?

### ISSUE THREAD

**Issue by AnderssonPeter** [containous/traefik#4584]
Bug

### What did you do?
I'm trying to only log 401 and 403 requests to my accessLog.

It does not seem to respect the filter, it logs all requests.
I'm using 1.7.9 inside a docker container.

### What did you expect to see?
I expect to only get 401 and 403 requests in the log.

### What did you see instead?
All requests are logged.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Enable debug mode
#
# Optional
# Default: false
#
debug = false

# Log level
#
# Optional
# Default: "ERROR"
#
logLevel = "INFO"

#[traefikLog]
#  filePath = "/var/logs/traefik/traefik.log"

[accessLog]
  filePath = "/var/logs/traefik/access.log"
  [accessLog.filters]
    retryAttempts = true
    minDuration = "10ms"
    statusCodes = ["401", "403"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    [entryPoints.https.redirect]
    regex = "^https://www\\.foo\\.bar/(.*)"
    replacement = "https://foo.bar/$1"
    permanent = true
......
```
Docker compose:
```
  traefik:
    image: traefik
    restart: unless-stopped
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/logs:/var/logs/traefik
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
      - 80:80
      - 443:443
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2019-03-13T18:59:12+01:00" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2019-03-13T18:59:12+01:00" level=info msg="Traefik version v1.7.9 built on 2019-02-11_11:36:32AM"
time="2019-03-13T18:59:12+01:00" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":true,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":{\"file\":\"/var/logs/traefik/access.log\",\"format\":\"common\",\"filters\":{\"statusCodes\":[\"401\",\"403\"],\"retryAttempts\":true,\"duration\":10000000}},\"TraefikLogsFile\":\"\",\"TraefikLog\":{\"file\":\"/var/logs/traefik/traefik.log\",\"format\":\"common\"},\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":{\"entryPoint\":\"https\"},\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":true,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"VersionTLS12\",\"CipherSuites\":null,\"Certificates\":null,\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":null,\"Optional\":false},\"DefaultCertificate\":null,\"SniStrict\":false},\"Redirect\":{\"regex\":\"^https://www\\\\.foo\\\\.bar/(.*)\",\"replacement\":\"https://foo.bar/$1\",\"permanent\":true},\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":{\"Email\":\"peter@foo.bar\",\"Domains\":[{\"Main\":\"foo.bar\",\"SANs\":[\"ha.foo.bar\",\"foo.bar\",\"www.foo.bar\",\"portainer.foo.bar\",\"duplicati.foo.bar\"]}],\"Storage\":\"acme.json\",\"StorageFile\":\"\",\"OnDemand\":false,\"OnHostRule\":false,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"DNSProvider\":\"\",\"DelayDontCheckDNS\":0,\"ACMELogging\":true,\"OverrideCertificates\":false,\"TLSConfig\":null},\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":null,\"Docker\":null,\"File\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":true,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":{\"EntryPoint\":\"traefik\"},\"HostResolver\":null}"
time="2019-03-13T18:59:12+01:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-03-13T18:59:12+01:00" level=debug msg="Setting Acme Certificate store from Entrypoint: https"
time="2019-03-13T18:59:13+01:00" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00029ffe0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-03-13T18:59:13+01:00" level=debug msg="Creating entry point redirect http -> https"
time="2019-03-13T18:59:13+01:00" level=debug msg="Creating regex redirect https -> ^https://www\\.foo\\.bar/(.*) -> https://foo.bar/$1"
time="2019-03-13T18:59:13+01:00" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc0008a6580 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc00029ff80} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-03-13T18:59:13+01:00" level=debug msg="Creating entry point redirect http -> https"
time="2019-03-13T18:59:13+01:00" level=debug msg="Creating regex redirect https -> ^https://www\\.foo\\.bar/(.*) -> https://foo.bar/$1"
time="2019-03-13T18:59:13+01:00" level=info msg="Preparing server https &{Address::443 TLS:0xc000252900 Redirect:0xc0008a6680 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00029ffc0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-03-13T18:59:13+01:00" level=info msg="Starting server on :80"
time="2019-03-13T18:59:13+01:00" level=info msg="Starting server on :8080"
time="2019-03-13T18:59:13+01:00" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2019-03-13T18:59:13+01:00" level=info msg="Starting server on :443"
time="2019-03-13T18:59:13+01:00" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"}"
time="2019-03-13T18:59:13+01:00" level=info msg="Starting provider *acme.Provider {\"Email\":\"peter@foo.bar\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":false,\"OnDemand\":false,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"foo.bar\",\"SANs\":[\"ha.foo.bar\",\"foo.bar\",\"www.foo.bar\",\"portainer.foo.bar\",\"duplicati.foo.bar\"}],\"Store\":{}}"
time="2019-03-13T18:59:13+01:00" level=info msg="Testing certificate renew..."
time="2019-03-13T18:59:13+01:00" level=debug msg="Configuration received from provider ACME: {}"
....
```

I tried to search for existing bugs and write in the support channel in slack.
