### ISSUE TITLE
[Kubernetes] ingress path priority in relation with length of path

### ISSUE THREAD

**Issue by aranair** [containous/traefik#4594]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Created a kubernetes ingress, single-hostname, multi-paths (nested tho), with a priority at the ingress level via `traefik.ingress.kubernetes.io/priority: "300"` - 

```
...
metadata:
  annotations:
     traefik.ingress.kubernetes.io/priority: "300"
...
spec:
  rules:
  - host: xxx
    http:
      paths:
      - backend:
          serviceName: models-5184edfb3
          servicePort: 8081
        path: /api/v2/ws/models
      - backend:
          serviceName: apigateway-5184edfb3
          servicePort: 80
        path: /api/v2/
```

### What did you expect to see?
Traffic should route based on the paths. 

E.g. traffic at `xxx/api/v2/ws/models`, the more specified path should go to the first service and `xxx/api/v2/` should go to the 2nd service

### What did you see instead?
The more specified path `/api/v2/ws/models` is getting matched to the more general path. If I remove the other path from this ingress, or create another ingress with a higher priority (e.g. 400), everything routes correctly. 

I also did not see this consistently. There were other similar ingresses behaving in the correct way.

The path length was previously used to calculate the priority, but that's no longer the case. So the priority of both the paths above are the same (e.g. the ingress priority) and depending on the init sequence, could different frontends be served?

Path length priority was [added here previously](https://github.com/containous/traefik/pull/588/files)  but the "priority" in that initialization is [now replaced by the ingress-level priority](https://github.com/containous/traefik/blob/v1.7/provider/kubernetes/kubernetes.go#L228)? 

Given that the priority of the route is basically taken as the [frontend's priority if it exists](https://github.com/containous/traefik/blob/v1.7/server/server_configuration.go#L294-L298), Should the priority for each path be calculated based on (ingress-level priority + path length), instead of just the priority value of the ingress itself? 

E.g. either modified at the provider level, or `serverRoute.Route.Priority(frontend.Priority + priority)` at the serverRoute level.

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.7
(installed with stable helm chart 1.60.0)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
kubernetes  /  ingress

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

No debug info but from the UI it seems like the appropriate backend/frontends are generated:

`300-xxx/api/v2/`
`300-xxx/api/v2/ws/models`

I'm not sure how/if that is sorted further downstream though.
