### ISSUE TITLE
loss data in prometheus v2

### ISSUE THREAD

**Issue by clhlc** [containous/traefik#4599]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

traefik run in my k8s cluster with daemonset

This is my k8s daemonset config containes 

```
   ....
    spec:
      containers:
      - args:
        - --api
        - --kubernetes
        - --metrics
        - --metrics.prometheus
        - --logLevel=INFO
        - --defaultentrypoints=http,https
        - --entrypoints=Name:https Address::443 TLS
        - --entrypoints=Name:http Address::80
        image: traefik
        imagePullPolicy: Always
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          procMount: Default
         ...
```

But loss data in my promethues v2 web query with prom sql when I query traefik backend requests count.

![image](https://user-images.githubusercontent.com/10704095/54413595-3504fe00-4731-11e9-95c3-7ac3b4101056.png)

But prometheus v1 is ok, why?

### What did you expect to see?

no loss data

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#aws ubuntu 16.04
```
