### ISSUE TITLE
Wordpress(wpml) multi site and multi url bug

### ISSUE THREAD

**Issue by Higins** [containous/traefik#4601]
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Word Press (wpml)
There is a multilingual site where SSL is okay.
But, when without www I bring in the site always goes through one language.

### What did you expect to see?
To get xy.sk over to www.xy.sk

### What did you see instead?
xy.sk --> www.xy.sk

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
TOML

```toml
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
  compress = true
    #[entryPoints.https.redirect]
    #regex = "^http://(.*)"
    #replacement = "https://$1"
    #permanent = true
    [entryPoints.https.tls]
[web.statistics]
recentErrors = 100

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
caServer = "https://acme-v02.api.letsencrypt.org/directory"
# Email address used for registration
email = "itdept@naturalswiss.ch"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"
  [[acme.domains]]
    main = "supergreens.hu"
    sans = ["www.supergreens.hu","supergreens.hu"] 
  [[acme.domains]]
    main = "supergreens.sk"
    sans = ["www.supergreens.sk","supergreens.sk"]
# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "www.supergreens.hu"
watch = true
exposedByDefault = true
swarmMode = true
network = "infrastructure_traefik_web"

docker-compose:
      - "traefik.backend=wordpress"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.supergreens.hu,www.supergreens.sk,supergreens.sk,supergreens.hu"
      - "traefik.frontend.redirect.regex=!^www."
      - "traefik.frontend.redirect.replacement=https://www.$${1}"
      - "traefik.frontend.redirect.permanent=true"


```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
