### ISSUE TITLE
Basic authentication realm from docker label not used

### ISSUE THREAD

**Issue by marema31** [containous/traefik#4602]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've created the following docker-compose file

```yml
version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=PathPrefix:/test"
      - "traefik.frontend.auth.basic.realm=Restricted"
      - "traefik.frontend.auth.basic.user=test:$$apr1$$DeqEAHBr$$2UxuPM9MjyFgJAs9AroTE/"
```

Run it by 
    docker-compose up -d
Query it by 
    curl -v http://127.0.0.1/test 2>&1 |grep Www-Authenticate

### What did you expect to see?

< Www-Authenticate: Basic realm="Restricted"

### What did you see instead?

< Www-Authenticate: Basic realm="traefik"

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Only in docker-compose file

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
NOT Applicable

**Comment by websolutions-hamburg** [comment]
It is also not used in the file configuration:

```toml
[frontends]
  [frontends.whoami]
    [frontends.whoami.routes]
      [frontends.whoami.routes.route0]
        rule = "Host:whoami.local"

    [frontends.whoami.auth]
      [frontends.whoami.auth.basic]
        realm = "ExampleName"
```
