### ISSUE TITLE
Entrypoints https redirection will not work for a api dashboard subdomain

### ISSUE THREAD

**Issue by websolutions-hamburg** [containous/traefik#4615]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a subdomain for the api dashboard `http://localhost:8088`. I was guided by this comment: https://github.com/containous/traefik/issues/3076#issuecomment-376209339 and I think this was the original linked file from this comment: https://github.com/containous/traefik/blob/v1.6/examples/acme/docker-compose.yml.  
So now I have this subdomain for the dashboard: `dashboard.test.local`. I also created an entryPoints redirect to my https entryPoint for the api entryPoint.

### What did you expect to see?

If I open the address `http://dashboard.test.local`, I expect a redirect to `https://dashboard.test.local`.

### What did you see instead?

No redirection, the url is still `http://dashboard.test.local`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
`traefik.toml`

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
  address = ":9000"
    [entryPoints.traefik.redirect]
    entryPoint = "https"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"
[accessLog]
  filePath = "/var/log/traefik/access.log"

[api]
  entryPoint = "traefik"
  dashboard = true
  [api.statistics]
    recentErrors = 50

[docker]
  exposedByDefault = false
  watch = true
```

`docker-compose.yml`

```yml
version: '3.7'

services:
  traefik:
    image: traefik:1.7.9
    restart: unless-stopped
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:dashboard.test.local,www.dashboard.test.local"
    expose:
      - "9000"
    volumes:
      - ./traefik:/etc/traefik
      - ./logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    name: traefik
```

### Alternative solution

If I added this label `"traefik.frontend.headers.SSLRedirect=true"` in my `docker-compose.yml`, it works as expected. But I think the redirect solution should also work.
