### ISSUE TITLE
Dashboard via subdomain logs every "/health" & "/api/providers" request

### ISSUE THREAD

**Issue by websolutions-hamburg** [containous/traefik#4618]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a subdomain for the dashboard and open it now via `http://dashboard.test.local`. When I open the dashboard, all requests to `http://dashboard.test.local/api/providers` or `http://dashboard.test.local/health` will be logged. And after a view minutes my HEALTH view looks like this (72 log entries only for the api and helth requests):

<img width="850" alt="dashboard" src="https://user-images.githubusercontent.com/26099903/54543410-e9a35780-499d-11e9-92ec-e89423484361.png">

### What did you expect to see?

No log entries for the api & health requests. My question is now also, is this a bug or a normal behavior. And if it's not a bug, is there a way to stop the logging for this requests?  
If I open the dashboard via `http://localhost:9000`, no api request will be logged.

### What did you see instead?

Log entires for every api & health requests.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
`traefik.toml`

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
  address = ":9000"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"
[accessLog]
  filePath = "/var/log/traefik/access.log"

[api]
  entryPoint = "traefik"
  dashboard = true
  [api.statistics]
    recentErrors = 50

[docker]
  exposedByDefault = false
  watch = true
```

`docker-compose.yml`

```yml
version: '3.7'

services:
  traefik:
    image: traefik:1.7.9
    restart: unless-stopped
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:dashboard.test.local,www.dashboard.test.local"
    expose:
      - "9000"
    volumes:
      - ./traefik:/etc/traefik
      - ./logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    name: traefik
```
