### ISSUE TITLE
Traefik for Kubernetes in Azure (redirect to https for the frontend)

### ISSUE THREAD

**Issue by command0r** [containous/traefik#4634]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
According to the [official documentation](https://docs.traefik.io/configuration/entrypoints/#redirect-http-to-https), the redirect to https should be straightforward. For GKE (Google Kubernetes) it works right away indeed. For Azure Kubermetes (AKS) it worked once and then after Traefik redeployment it didn't get back to normal. Whatever I tried didn't work.
The config looks as the following:
```yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

    [frontends]
      [frontends.frontend2]
        backend = "backend1"
        passHostHeader = true
        # overrides default entry points
        entrypoints = ["http", "https"]

    [backends]
      [backends.backend1]
        [backends.backend1.servers.server1]
           url = "http://login.mynewsite.com"
```

### What did you expect to see?
Expected behaviour: everything should work as advertised.

### What did you see instead?
As I mentioned, whatever I do in the ConfigMap or at the Ingress level doesn't affect the actual behaviour. I have a sense it's been cached somewhere. Also, the annotations I implement are not reflected in the Traefik dashboard for the selected frontend (I expect to see color labels at least which indicate the rules applied). 

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.9

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
A sample of Ingress for my application with annotations

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: identityserver-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: https
    traefik.ingress.kubernetes.io/redirect-permanent: true

spec:
  rules:
  - host: login.mynewsite.com
    http:
      paths:
      - backend:
          serviceName: identityserver-svc
          servicePort: 80
  tls:
    - secretName: traefik-ui-tls-cert
```

One more weird thing the dashboard for Traefik didn't work for two days last week no matter what I've done. It just started working by itself yesterday. Kubernetes supposed to be the same everywhere. I use 1.11.8 in AKS as well as GKE, however, in GKE everything works like a charm in AKS does not.
