### ISSUE TITLE
insecureskipverify storeconfig sets default to false

### ISSUE THREAD

**Issue by webfrank** [containous/traefik#4649]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a traefik cluster with consul starting from a toml file. Every time I change the toml and load to consul using storeconfig the flag insecureSkipVerify got rested to false although I have set to true into the file

### What did you expect to see?

I expect to have in consul the key insecureskipverify = true

### What did you see instead?

I got insecureskipverify = false

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"

[accessLog]

defaultEntryPoints = ["http", "https"]

insecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address = ":81"
    
[api]
entryPoint = "api"
dashboard = true

# Enable ACME (Let's Encrypt): automatic SSL.
[acme]
# Email address used for registration.
#
# Required
#
email = "xxxxxx@xxxxx.xxx"

# File or key used for certificates storage.
#
# Required
#
storage = "acme.json"
# or `storage = "traefik/acme/account"` if using KV store.

# Entrypoint to proxy acme apply certificates to.
# WARNING, if the TLS-SNI-01 challenge is used, it must point to an entrypoint on port 443
#
# Required
#
entryPoint = "https"

# If true, display debug log messages from the acme client library.
#
# Optional
# Default: false
#
acmeLogging = true

# Enable certificate generation on frontends Host rules.
#
# Optional
# Default: false
#
onHostRule = true

# CA server to use.
# - Uncomment the line to run on the staging let's encrypt server.
# - Leave comment to go to prod.
#
# Optional
# Default: "https://acme-v01.api.letsencrypt.org/directory"  
#
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
caServer = "https://acme-v02.api.letsencrypt.org/directory"

#[acme.tlsChallenge]
  
# Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
#
# Optional but recommend
#
#[acme.httpChallenge]
# EntryPoint to use for the challenges.
#
# Required
#
#entryPoint = "http"
[acme.dnsChallenge]
  provider = "ovh"

# Enable Consul KV Provider.
[consul]

# Consul server endpoint.
#
# Required
# Default: "127.0.0.1:8500"
#
endpoint = "tasks.proxy_consul:8500"

# Enable watch Consul changes.
#
# Optional
# Default: true
#
watch = true

# Prefix used for KV store.
#
# Optional
# Default: traefik
#
prefix = "traefik"

[file]
watch = true

# rules
[backends]
  # Apache Web Server
  [backends.apache]
    [backends.apache.servers]
      [backends.apache.servers.server0]
        url = "http://x.x.x.x:80"
  # LigHTTP Web Server
  [backends.lighttp]
    [backends.lighttp.servers]
      [backends.lighttp.servers.server0]
        url = "http://y.y.y.y:80"

  [frontends.catchall]
  entryPoints = ["http"]
  backend = "lighttp"
  passHostHeader = true
  priority = 1
    [frontends.catchall.routes.host]
    rule = "HostRegexp:{catchall:.*}"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
