### ISSUE TITLE
Support HCL as configuration format

### ISSUE THREAD

**Issue by olekukonko** [containous/traefik#4658]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The current `toml` is not suited for a programmable configuration hence will like to suggest using  [HCL](https://github.com/hashicorp/hcl)  for  `2.0`

`HCL` is also fully `JSON` compatible. That is, JSON can be used as completely valid input to a system expecting HCL. This helps makes systems interoperable with other systems.

##### Example   296 bytes

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "tests/traefik.crt"
      keyFile = "tests/traefik.key"
```
 
This can  easily be replaced by  a  more readable format  [HCL](https://github.com/hashicorp/hcl) 

##### Example HCL  249 bytes

```hcl
entryPoints {
  http redirect {
      address = ":80"
      entryPoint = "https"
  }
  https {
       address = ":443"
       tsl certificates {
          certFile = "tests/traefik.crt"
          keyFile = "tests/traefik.key"             
       }
  }
}
```

#####  Example  2 

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik.io"
storage = "traefik/acme/account"
caServer = "http://172.18.0.1:4000/directory"
entryPoint = "https"

[acme.httpChallenge]
    entryPoint = "http"

[[acme.domains]]
  main = "local1.com"
  sans = ["test1.local1.com", "test2.local1.com"]
[[acme.domains]]
  main = "local2.com"
  sans = ["test1.local2.com", "test2x.local2.com"]
[[acme.domains]]
  main = "local3.com"
[[acme.domains]]
  main = "local4.com"

[consul]
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "traefik"
```

#####  Example 2 HCL 

```hcl
entryPoints {
  address = ":80"
  http address ":80" 
  https {
       address = ":443"
       tsl =  true
  }
}

acme {
  email = "test@traefik.io"
  storage = "traefik/acme/account"
  caServer = "http://172.18.0.1:4000/directory"
  entryPoint = "https"
  httpChallenge entryPoint = "http"
  domains {
    main = "local1.com"
    sans = ["test1.local1.com", "test2.local1.com"]
  }
  domains {
    main = "local2.com"
    sans = ["test1.local2.com", "test2x.local2.com"]
  }
  domains {
    sans = "local3.com"
  }
  domains {
    sans = "local3.com"
  }
}

consul {
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "traefik"
}
```

##### Futher simplication of `acme`

```hcl
acme {
  email = "test@traefik.io"
  storage = "traefik/acme/account"
  caServer = "http://172.18.0.1:4000/directory"
  entryPoint = "https"
  httpChallenge entryPoint = "http"

  domains "local1.com" = ["test1.local1.com", "test2.local1.com"]
  domains "local2.com" =  ["test1.local2.com", "test2x.local2.com"]
  domains = "local3.com"
  domains = "local3.com"
}
```

#####  HCL Supports 

- Single line comments start with # or //
-  Multi-line comments are wrapped in /* and */. Nested block comments are not allowed. A multi-line comment (also known as a block comment) terminates at the first */ found.
- Values are assigned with the syntax key = value (whitespace doesn't matter). The value can be any primitive: a string, number, boolean, object, or list.
- Strings are double-quoted and can contain any UTF-8 characters. Example: "Hello, World"
- Multi-line strings start with <<EOF at the end of a line, and end with EOF on its own line (here documents). Any text may be used in place of EOF. Example:
-  Numbers are assumed to be base 10. If you prefix a number with 0x, it is treated as a hexadecimal. If it is prefixed with 0, it is treated as an octal. Numbers can be in scientific notation: "1e10".
-  Boolean values: true, false
- Arrays can be made by wrapping it in []. Example: ["foo", "bar", 42]. Arrays can contain primitives, other arrays, and objects. As an alternative, lists of objects can be created with repeated blocks, using this structure:

 
### Implementation 

- `staert` can  be updated to  support `hcl`
- `hcl` can be backed directly into `traefik` all that is required is `hcl.Decode`
-  Majority of  the work will be done  in documentation  

### Conclusion  

Based on my observation, a large configuration file will gradually become unreadable at first glance and HCL was designed to fit that gap  

**Kindly pardon any errors or assumption in the message above**

**Comment by olekukonko** [comment]
@jbdoumenjou would you like to share how you intend to approach this?

**Comment by olekukonko** [comment]
There is a simple `caddy` vs `traefik` configuration

### caddy

```
www.example.com:80, www.example.com:443 {
  tls self_signed
  log /logs access.log
  errors visible
  proxy /assets nginx:80
  proxy / web:3000 
  
  redir 301 {
    if {>X-Forwarded-Proto} is http
      /  https://{host}{uri}
    }
  }
```


### traefik

```toml

#debug = true

[backends]
  [backends.buffalo]
    [backends.buffalo.loadbalancer.stickiness]
      [backends.buffalo.healthcheck]
      path = "/healthcheck"
      interval = "11s"
    [backends.buffalo.servers.server1]
    url = "http://web:3000"

  [backends.backendNginx]
    [backends.backendNginx.loadbalancer.stickiness]
    [backends.backendNginx.servers.server1]
    url = "http://nginx:80"

[frontends]
  [frontends.frontend1]
  backend = "buffalo"
    [frontends.frontend1.routes.web]
    rule = "Host:www.example.com"
  entrypoints = ["http","https"]
  passHostHeader = true
  #passTLSCert = true
  priority = 10

  [frontends.nginx]
  backend = "backendNginx"
    [frontends.nginx.routes.web]
    rule = "Host:www.example.com;PathPrefix:/assets"
  passHostHeader = true
  #passTLSCert = true
```
