### ISSUE TITLE
Traefik fails to obtain ClouDNS wildcard certificate

### ISSUE THREAD

**Issue by steve-todorov** [containous/traefik#4665]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have configured `traefik 1.7.9` (which should have included cloudns go-acme/lego#183 and is listed in the [docs](https://docs.traefik.io/configuration/acme/#provider))

### What did you expect to see?

Successful obtaining of wildcard letsencrypt certificate.

### What did you see instead?

Failed to obtain the wildcard certificate because of "unrecognized DNS provider".

```
Unable to obtain ACME certificate for domains \"*.domain.com,domain.com\" : cannot get ACME client unrecognised DNS provider: cloudns
```

Full log

```
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Using TOML configuration file /traefik.toml"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Traefik version v1.7.9 built on 2019-02-11_11:36:32AM"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Preparing server dashboard &{Address::8090 TLS:<nil> Redirect:<nil> Auth:redacted WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0003ffe60} with readTimeout=1m0s writeTimeout=1m0s idleTimeout=2m0s"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0003ffe80} with readTimeout=1m0s writeTimeout=1m0s idleTimeout=2m0s"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Starting server on :8090"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Preparing server https &{Address::443 TLS:0xc00025b290 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0003ffe40} with readTimeout=1m0s writeTimeout=1m0s idleTimeout=2m0s"
traefik    | time="2019-03-26T10:46:38Z" level=info msg="Starting server on :80"
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Starting server on :443"
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"redacted\",\"Token\":\"redacted\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null}"
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"email@domain.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"Storage\":\"/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":false,\"OnDemand\":false,\"DNSChallenge\":{\"Provider\":\"cloudns\",\"DelayBeforeCheck\":120000000000,\"Resolvers\":null,\"DisablePropagationCheck\":false},\"HTTPChallenge\":null,\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"*.domain.com\",\"SANs\":[\"domain.com\"]}],\"Store\":{}}"
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Testing certificate renew..."
traefik    | time="2019-03-26T10:46:39Z" level=info msg="ingress label selector is: \"\""
traefik    | time="2019-03-26T10:46:39Z" level=info msg="Creating cluster-external Provider client with endpoint redacted"
traefik    | time="2019-03-26T10:46:39Z" level=error msg="Unable to obtain ACME certificate for domains \"*.domain.com,domain.com\" : cannot get ACME client unrecognised DNS provider: cloudns"
traefik    | time="2019-03-26T10:46:40Z" level=info msg="Server configuration reloaded on :8090"
traefik    | time="2019-03-26T10:46:40Z" level=info msg="Server configuration reloaded on :80"
traefik    | time="2019-03-26T10:46:40Z" level=info msg="Server configuration reloaded on :443"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik version
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker image:  
`traefik:1.7-alpine`

Configuration:  
```toml
debug = false
logLevel = "INFO"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]
    minVersion = "VersionTLS13"

[acme]
email = "email@domain.com"
storage = "/acme.json"
onDemand = false
entryPoint = "https"
acmeLogging = true
# PRODUCTION URL
#caServer = "https://acme-v02.api.letsencrypt.org/directory"
# STAGING URL
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
    provider = "cloudns"
    delayBeforeCheck = 120
  [[acme.domains]]
    main = "*.domain.com"
    sans = ["domain.com"]
```
