### ISSUE TITLE
[K8s - AKS] v2.0, Error while Peeking first byte: EOF

### ISSUE THREAD

**Issue by StiviiK** [containous/traefik#4685]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to upgrade traefik in my k8s cluster from `1.7.9-alpine` to `2.0-alpine`, trying to browse to any url responds with an 404.
In the console logs you can see:
```
[START OF CONTAINER LOGS]
time="2019-03-28T12:27:25Z" level=error msg="\nYou haven't specify the sendAnonymousUsage option, it will be enable by default.\n"
time="2019-03-28T12:27:40Z" level=error msg="Error while Peeking first byte: EOF"
time="2019-03-28T12:27:42Z" level=error msg="Error while Peeking first byte: EOF"
[....]
```

### What did you expect to see?
Version 2.0 to work as fine as 1.7.9 does.

### What did you see instead?
See above.

### Output of `traefik version`:

```
/ # traefik version
Version:      2.0.0-alpha2
Codename:     faisselle
Go version:   go1.12.1
Built:        2019-03-19T18:44:59Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
      permanent = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[kubernetes]
[traefikLog]
  format = "json"
[accessLog]
  format = "common"
[accessLog.fields]
  defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
  defaultMode = "keep"
[accessLog.fields.headers.names]
[acme]
email = "MAIL"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
  [acme.dnsChallenge]
  provider = "azure"
[[acme.domains]]
   main = "*.DOMAIN.tld"
   sans = ["DOMAIN.tld"]
[[acme.domains]]
   main = "*.DOMAIN2.tld"
   sans = ["DOMAIN2.tld"]
[api]
  entryPoint = "traefik"
  dashboard = true
```

Platform: Kubernetes on Azure (AKS), Traefik deployed via Helm chart
[Helm values.yaml](https://pastebin.com/Xg3xdkPm)
