### ISSUE TITLE
traefik v2 RedirectScheme to HTTPS in Docker Provider does not redirect 

### ISSUE THREAD

**Issue by Zaxim** [containous/traefik#4688]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a traefik.toml file below

```toml
[global]
  sendAnonymousUsage = false
  logLevel = "DEBUG" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  debug = true

[entrypoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"

[providers]

  [providers.docker]
    # Connection to docker host system (docker.sock)
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    # This will hide all docker containers that don't have explicitly  
    # set label to "enable"
    exposedbydefault = false
    #network = "traefik_proxy"

[api]

```
and I created a docker-compose file below
```yml
version: "3.6"
services:

  traefik:
    image: traefik:2.0.0-alpha2 # The official v2.0 Traefik docker image
    container_name: traefik
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik1_router.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik1_router.middlewares=https_redirect"
      - "traefik.http.routers.traefik1_router.tls"
      - "traefik.http.services.traefik1_service.loadbalancer.server.port=8080"
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./traefik/docker-config/etc/traefik:/etc/traefik
      - ./docker-shared:/shared

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```
Run `docker-compose up`

Navigate to http://traefik.example.com

### What did you expect to see?

I expected the browser to redirect to https://traefik.example.com and the traefik dashboard placeholder page to load.

### What did you see instead?

I received a `404 page not found`

```console
$ curl -v traefik.example.com
* Expire in 0 ms for 6 (transfer 0x55ed8718b2f0)
*   Trying 192.168.2.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55ed8718b2f0)
* Connected to <SNIPPED> (192.168.2.5) port 80 (#0)
> GET / HTTP/1.1
> Host: <SNIPPED>
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 28 Mar 2019 18:48:09 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host <SNIPPED> left intact
```

If I navigate directly to https://traefik.example.com, the dashboard page does load properly.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha2
Codename:     faisselle
Go version:   go1.12.1
Built:        2019-03-19T18:44:59Z
OS/Arch:      linux/amd64

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
Attaching to traefik                                                                                                                                                         traefik    | time="2019-03-28T19:14:53Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"                                                            
traefik    | time="2019-03-28T19:14:53Z" level=info msg="Traefik version 2.0.0-alpha2 built on 2019-03-19T18:44:59Z"                                                         traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Static configuration loaded {\"Global\":{\"Debug\":true,\"CheckNewVersion\":false,\"SendAnonymousUsage\":false},\"S
erversTransport\":{\"InsecureSkipVerify\":false,\"RootCAs\":null,\"MaxIdleConnsPerHost\":200,\"ForwardingTimeouts\":null},\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":18000000
0000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGra
ceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHea
ders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":1000000000
0},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\"
:null}}},\"Providers\":{\"ProvidersThrottleDuration\":0,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"DebugLogGeneratedTemplate\":false
,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\"
:false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15},\"File\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"DebugLogGeneratedTemplate\":false,\
"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"},\"Marathon\":null,\"Kubernetes\":null,\"KubernetesCRD\":null,\"Rest\":null},\"API\":{\"EntryPoint\":\"traefi
k\",\"Dashboard\":true,\"Statistics\":null,\"Middlewares\":null},\"Metrics\":null,\"Ping\":null,\"Log\":null,\"AccessLog\":null,\"Tracing\":null,\"HostResolver\":null,\"ACME
\":{\"Email\":\"<SNIPPED>@yahoo.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"/etc/traefik/acme/acme.json\",\"Entry
Point\":\"\",\"KeyType\":\"\",\"OnHostRule\":false,\"DNSChallenge\":{\"Provider\":\"cloudflare\",\"DelayBeforeCheck\":0,\"Resolvers\":null,\"DisablePropagationCheck\":false}
,\"HTTPChallenge\":null,\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"*.example.com\",\"SANs\":[\"example.com\"]}]}}"
traefik    | time="2019-03-28T19:14:53Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc
s.traefik.io/basics/#collected-data\n"
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="No default certificate, generate one"
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Start TCP Server" entryPointName=http
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Start TCP Server" entryPointName=traefik
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Start TCP Server" entryPointName=https
traefik    | time="2019-03-28T19:14:53Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik    | time="2019-03-28T19:14:53Z" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"DebugLogGe
neratedTemplate\":false,\"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"}"
traefik    | time="2019-03-28T19:14:53Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\[12/3990]
GeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPor
tIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
traefik    | time="2019-03-28T19:14:53Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"<SNIPPED>@yahoo.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-
v02.api.letsencrypt.org/directory\",\"Storage\":\"/etc/traefik/acme/acme.json\",\"EntryPoint\":\"\",\"KeyType\":\"\",\"OnHostRule\":false,\"DNSChallenge\":{\"Provider\":\"cl
oudflare\",\"DelayBeforeCheck\":0,\"Resolvers\":null,\"DisablePropagationCheck\":false},\"HTTPChallenge\":null,\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"*.example.com\",\"SANs\":[\"example.com\"]}],\"Store\":{}}"
traefik    | time="2019-03-28T19:14:53Z" level=info msg="Testing certificate renew..." providerName=acme
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Looking for provided certificate(s) to validate [\"*.example.com\" \"example.com\"]..." provi
derName=acme
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="No ACME certificate generation required for domains [\"*.example.com\" \"example.com\"]." pro
viderName=acme
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Configuration received from provider file: {\"HTTP\":{\"middlewares\":{\"redirectSSL\":{\"redirectscheme\":{\"schem
e\":\"https\",\"port\":\"443\"}}}},\"TCP\":{},\"TLSOptions\":{},\"TLSStores\":{}}" providerName=file
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Configuration received from provider ACME: {\"HTTP\":{},\"TCP\":null,\"TLSOptions\":null,\"TLSStores\":null}" provi
derName=ACME
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="No default certificate, generate one"
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Provider connection established with docker 18.09.3 (API 1.39)" providerName=docker
traefik    | time="2019-03-28T19:14:53Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"traefik1_router\":{\"entryPoints\":null,\"mi
ddlewares\":[\"https_redirect\"],\"service\":\"traefik1_service\",\"rule\":\"Host(`traefik.example.com`)\",\"tls\":{}}},\"middlewares\":{\"https_redirect\":{\"red
irectscheme\":{\"scheme\":\"https\"}}},\"services\":{\"traefik1_service\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.28.0.2:8080\",\"weight\":1}],\"method\":\"wrr
\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="No store is defined to add the certificate MIIGgTCCBWmgAwIBAgISA/H4XldVQmqr0y+HlNdLZfpbMA0GCS, it will be added to
the default store."
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Add certificate for domains *.example.com,example.com"
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="No default certificate, generate one"
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Add certificate for domains *.example.com,example.com"
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="No default certificate, generate one"
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating middleware" serviceName=traefik1_service routerName=docker.traefik1_router entryPointName=http middlewareN
ame=pipelining middlewareType=Pipelining
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating wrr load-balancer" routerName=docker.traefik1_router entryPointName=http serviceName=traefik1_service
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating server 0 at http://172.28.0.2:8080 with weight 1" entryPointName=http serviceName=traefik1_service routerN
ame=docker.traefik1_router serverName=0
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Added outgoing tracing middleware traefik1_service" routerName=docker.traefik1_router middlewareType=TracingForward
er middlewareName=tracing entryPointName=http
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating middleware" entryPointName=http middlewareType=RedirectScheme routerName=docker.traefik1_router middleware
Name=docker.https_redirect
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Setting up redirection to https " middlewareType=RedirectScheme routerName=docker.traefik1_router middlewareName=do
cker.https_redirect entryPointName=http
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Adding tracing to middleware" routerName=docker.traefik1_router entryPointName=http middlewareName=docker.https_red
irect
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating middleware" entryPointName=https middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik    | time="2019-03-28T19:14:54Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery

```

**Comment by cypx** [comment]
I encounter the same issue when I try to use TLS enabled router on HTTP entrypoint.
Not sure about the reasons but I'm unable to use the same router for HTTP and HTTPS

Maybe not the best way but I use two different routers to fix this, so you can try with

```yml
version: "3.6"
services:

  traefik:
    image: traefik:2.0.0-alpha2 # The official v2.0 Traefik docker image
    container_name: traefik
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik1_router.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik1_router.entryPoints=http"
      - "traefik.http.routers.traefik1_router.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik1_tls_router.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik1_tls_router.entryPoints=https"
      - "traefik.http.routers.traefik1_tls_router.tls"
      - "traefik.http.services.traefik1-tls_service.loadbalancer.server.port=8080"
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./traefik/docker-config/etc/traefik:/etc/traefik
      - ./docker-shared:/shared

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```

**Comment by Zaxim** [comment]
Thanks @cypx. I think I figured it out about the same time you posted.

I ended up getting it to work with this docker-compose file

```
version: "3.6"
services:

  traefik:
    image: traefik:2.0.0-alpha2 # The official v2.0 Traefik docker image
    container_name: traefik
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik1_router_http.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik1_router_http.middlewares=https_redirect"
      - "traefik.http.routers.traefik1_router_https.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik1_router_https.tls"
      - "traefik.http.services.traefik1_service.loadbalancer.server.port=8080"
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./traefik/docker-config/etc/traefik:/etc/traefik
      - ./docker-shared:/shared
```
The hint that I needed was in the docs under [Routers:TLS](https://docs.traefik.io/v2.0/routing/routers/#tls ) and the _Routers for HTTP & HTTPS_ section that states:

> If you need to define the same route for both HTTP and HTTPS requests, you will need to define two different routers: one with the tls section, one without.

This seems kind of silly and overly verbose. traefik v1 allowed you to easily defined a redirect in the entrypoint section. Now we need double the number of labels for every service defined in the docker-compose.
