### ISSUE TITLE
Multiple SSL certificates don't work as per documentation

### ISSUE THREAD

**Issue by vrtechnologies** [containous/traefik#4689]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have been using a single certificate with traefik successfully for a while, I added a second certificate as per the HTTP + HTTPS step here: https://docs.traefik.io/user-guide/examples/ and the server refuses to start. I added the following to my config:
```toml
[[entryPoints.https.tls.certificates]]
      certFile = "/certs/myotherdomain.com.au.crt"
      keyFile = "/certs/myotherdomain.com.au.key"
```

Here is the full traefik.toml file:
```toml
debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/mywildcarddomain.info.crt"
      keyFile = "/certs/mywildcarddomain.info.key"
[[entryPoints.https.tls.certificates]]
      certFile = "/certs/myotherdomain.com.au.crt"
      keyFile = "/certs/myotherdomain.com.au.key"
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dev.gen4.info"
watch = true
exposedByDefault = false

[file]
filename = "servers.toml"
watch = true
```

### What did you expect to see?
I expected to have both of my domains working with the appropriate certificates. Both entries work individually, but not together. The documentation suggests that you can have multiple entries, but it seems to not be functioning this way.

### What did you see instead?
The log file throws the following error:
` Error reading TOML config file /traefik.toml : Near line 19 (last key parsed 'entryPoints.https.tls.certificates.certFile'): Key 'entryPoints.https.tls.certificates.certFile' has already been defined.`

### Output of `traefik version`:

```
Traefik version v1.7.9 built on 2019-02-11_11:36:32AM
```

### traefik.toml
```toml
debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/mywildcarddomain.info.crt"
      keyFile = "/certs/mywildcarddomain.info.key"
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/myotherdomain.com.au.crt"
      keyFile = "/certs/myotherdomain.com.au.key"
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dev.gen4.info"
watch = true
exposedByDefault = false

[file]
filename = "servers.toml"
watch = true
```
### server.toml
```servers.toml
loglevel = "ERROR"
```
