### ISSUE TITLE
Multiple containers serving websockets in docker swarm not working

### ISSUE THREAD

**Issue by visitsb** [containous/traefik#4704]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
Having _one_ container using websockets under Traefik works as expected. But when I add another container that also uses websockets under the same traefik stack, then _neither_ of websockets work. Once I remove either one from these containers, then websocket connectivity works.

These containers also serve http but there is no problem with http.

### What did you expect to see?
When just one container using websocket e.g. `web1` is active in Traefik

| WS |     HTTP      |
|----------|:-------------:|
| wss://mydomain.com/web1/socket.io/?transport=websocket  |  101 Switching protocols |

When both containers - `web1`, `web2` - are active in Traefik

| WS |     HTTP Response      |
|----------|:-------------:|
| wss://mydomain.com/web1/socket.io/?transport=websocket  |  101 Switching protocols |
| wss://mydomain.com/web2/socket.io/?transport=websocket  |  101 Switching protocols |

### What did you see instead?
When just one container using websocket e.g. `web1` is active in Traefik

| WS |     HTTP Response      |
|----------|:-------------:|
| wss://mydomain.com/web1/socket.io/?transport=websocket  |  101 Switching protocols |

When both containers - `web1`, `web2` - are active in Traefik

| WS |     HTTP Response      |
|----------|:-------------:|
| wss://mydomain.com/web1/socket.io/?transport=websocket  |  500 Internal Server Error |
| wss://mydomain.com/web2/socket.io/?transport=websocket  |  500 Internal Server Error |

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
traefik:1.7.9-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https", "ws", "wss"]

[entryPoints]
  [entryPoints.http]
  address = "0.0.0.0:80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
    address = "0.0.0.0:443"
    compress = true
      [entryPoints.https.tls]

[acme]
email = "me@test.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "mydomain.com"

[api]
entryPoint = "traefik"
dashboard = true

[ping]
entryPoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
exposedByDefault = false
watch = true
```
```
Docker version 18.06.1, build e68fc7a
```
```
  web1:
    depends_on:
      - redis
    image: node:11.12.0-alpine
    command: ["npm", "start"]
    working_dir: /home/node/app
    labels:
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.socket.frontend.rule=Query: transport=websocket; PathPrefix: /web1; Host: mydomain.com, www.mydomain.com;"
      - "traefik.spa.frontend.rule=PathPrefixStrip: /web1; Host: mydomain.com, www.mydomain.com;"
      - "traefik.port=80"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https"
      - "traefik.enable=true"
      - "traefik.frontend.priority=1000"
    volumes:
      - /root/data/node/web1:/home/node/app
...
```
```
  web2:
    depends_on:
      - redis
    image: node:11.12.0-alpine
    command: ["npm", "start"]
    working_dir: /home/node/app
    labels:
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.socket.frontend.rule=Query: transport=websocket; PathPrefix: /web2; Host: mydomain.com, www.mydomain.com;"
      - "traefik.spa.frontend.rule=PathPrefixStrip: /web2; Host: mydomain.com, www.mydomain.com;"
      - "traefik.port=80"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https"
      - "traefik.enable=true"
      - "traefik.frontend.priority=1000"
    volumes:
      - /root/data/node/web2:/home/node/app
...
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
