### ISSUE TITLE
Problem when i change [WEB] to [API]

### ISSUE THREAD

**Issue by Nitrosito** [containous/traefik#4705]
Good Morning,
I have traefik 1.7.3 on Docker SWARM 
I use Docker Section in TRAEFIK, not docker swarm.

I was using [WEB] of traefik, but I realized that I was dismantled. I changed to [API] But when I rebooted, nothing works for me. Before, I had FRONTS for HTTP and HTTPS for each STACK deployed. Now I just get HTTP, and the RouteName is formed with The name of the service + name of the stack + name of the container apparently ...
I have the labels defined so that I can put the name from the docker-compose:

```
    labels:
      traefik.enable: "true"
      traefik.port: 80
      traefik.backend.loadbalancer.stickiness: "true"
      traefik.frontend.rule: "Host:elkarbackup.xxx.xxx"
      traefik.docker.network: "traefik"
      #traefik.frontend.redirect.entryPoint: "https"
    networks:
      - traefik
      - elkarbackup
```
