### ISSUE TITLE
websocket: bad handshake with resp: 200 200 OK

### ISSUE THREAD

**Issue by dschuldt** [containous/traefik#4709]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Deployed Rancher 2.2.1 with the following docker-compose file:

```yaml
version: "2"

services:
  rancher2:
    image: rancher/rancher:latest
    container_name: rancher2
    restart: unless-stopped
    environment:
      HTTP_PROXY: http://*:8080
      HTTPS_PROXY: http://******:8080
      NO_PROXY: 127.0.0.1,localhost,******
    volumes:
    - rancher2:/var/lib/rancher
    - /var/lib/docker/volumes/rancher2/_data/******/certbundle.crt:/etc/rancher/ssl/cacerts.pem
    labels:
      io.rancher.scheduler.affinity:host_label: rancher2=true
      traefik.enable: true
      traefik.frontend.entryPoints: http,https
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.redirect.permanent: 'true'
      traefik.frontend.rule: Host:******
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.headers.customRequestHeaders: Host:******||X-Forwarded-Proto:https||X-Forwarded-Port:443||X-Forwarded-Host:******
      traefik.protocol: http
      traefik.port: 80
      traefik.backend: rancher2
```                                         

### What did you expect to see?

Websocket connection should be successfully established

### What did you see instead?

msg="vulcand/oxy/forward/websocket: Error dialing \"rancher2.portals.eos.lcl\": websocket: bad handshake with resp: 200 200 OK"2

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "ERROR"
[api]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/******/traefik/certbundle.crt"
        keyFile  = "/******/traefik/******.key"
  [entryPoints.ping]
    address = ":8082"

[metrics]
  [metrics.prometheus]

[ping]
  entryPoint = "ping"

[rancher]
  watch = true
  refreshSeconds = 10
  exposedByDefault = false
  enableServiceHealthFilter = true

```
