### ISSUE TITLE
zipkin B3 headers Spanid/Traceid occasionally is 15 instead 16 digits long, zipkin-go-opentracing library needs update

### ISSUE THREAD

**Issue by MaxWinterstein** [containous/traefik#4712]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

When using zipkin tracing there are B3 headers added. But, sometimes they are missing one digit.
This has already been fixed https://github.com/openzipkin-contrib/zipkin-go-opentracing/pull/98 but this is not working for 1.7.10. 

I guess, somewhere the build pipeline needs some push to pull the master branch again or something?

### What did you expect to see?

A 16 digit Spanid
`"request_X-B3-Spanid":"03b7e31b3c6e4b4b"` <-- Note the **_0_**

### What did you see instead?

A 15 digit Spanid
`"request_X-B3-Spanid":"3b7e31b3c6e4b4b"` 

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.10-alpine (docker image)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [tracing]
      backend = "zipkin"
      serviceName = "traefik"
      [tracing.zipkin]
        httpEndpoint = "http://XXX"
        debug = true
        sameSpan = false
        id128bit = true
```
