### ISSUE TITLE
Entrypoint redirect to https breaks wss

### ISSUE THREAD

**Issue by tgardner** [containous/traefik#4724]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

After adding a redirect label to a container which requires https using a label, the site redirects correctly, but all subsequent web socket connections begin to fail / hang with a response code of 101 Switch protocols 
      - "traefik.frontend.redirect.entryPoint=https"

Seems to be stuck in a constant redirect loop. Is there an alternative label for only redirecting the http endpoint?

### What did you expect to see?

Successful web socket connection

### What did you see instead?

Request URL: wss://xxx/wss/s/default/events
Request Method: GET
Status Code: 101 Switching Protocols

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
InsecureSkipVerify = true

[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
domain = "nas"
watch = true
network = "proxy"
exposedByDefault = false
```
