### ISSUE TITLE
traefik.tcp.routers.extauth.tls should be bool instead of string in 2.0.0-alpha3

### ISSUE THREAD

**Issue by powerman** [containous/traefik#4741]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

```yaml
        labels:
            traefik.tcp.routers.something.tls: true
```

### What did you expect to see?

No error.

### What did you see instead?

```
level=warning msg="TCP Router ignored, cannot specify a Host rule without TLS" entryPointName=web routerName=docker.something
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha3
Codename:     faisselle
Go version:   go1.12.1
Built:        2019-03-29T17:53:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No config file, only arguments and docker labels:

```yaml
    traefik:
        image: traefik:2.0
        command: >
            --api
            --entrypoints='Name:web Address::8000'
            --metrics
            --metrics.prometheus
            --providers
            --providers.docker
            --providers.docker.exposedbydefault=false
            --providers.docker.watch
            --global.sendAnonymousUsage=true
            --global.debug
            --log.loglevel=debug
            --accesslog
    something:
        image: something
        labels:
            traefik.enable: true
            traefik.tcp.routers.something.entrypoints: "web"
            traefik.tcp.routers.something.rule: "HostSNI(`something.${DOMAIN}`)"
            traefik.tcp.routers.something.tls: true
            traefik.tcp.routers.something.tls.passthrough: true
            traefik.tcp.services.something.loadbalancer.server.port: 8080
```

### Workaround:

```yaml
            traefik.tcp.routers.something.tls: "true" # XXX Must be a string.
```
