### ISSUE TITLE
In Docker Swarm client certs do not work if not placed in /etc/ssl/certs

### ISSUE THREAD

**Issue by rgrubin75** [containous/traefik#4752]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?

Running Docker Swarm, I have 1 application that we need to run in https.  If I create a docker config that loads the crt and key to /etc/ssl/certs on the traefik container and set accordingly my traefik.toml file it works fine.

But if try to use the certs loaded from a Docker secret under /run/secrets/ or from an nfs volume mount such as /var/ssl  I get the following error even though when I ssh into the traefik container I can clearly see the certs and key loaded in the designated locations.

```time="2019-04-09T12:09:09Z" level=debug msg="http: TLS handshake error from 10.255.0.2:58575: tls: no certificates configured"```

I'm assuming there must be some permission issue that I'm just not aware of.

Here is the traefik config in my docker swarm compose file:

```
volumes:
  prometheus_data:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/prometheus_data"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  grafana_data:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/grafana_data"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  redis_data:
    driver_opts:
      device: ":/vol/tdcvnetapp02nfs03/gitlab-dev/redis_data"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  postgresql_data:
    driver: local
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/postgresql_data"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_data_ssh:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_data/.ssh"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_data_uploads:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_data/gitlab-rails/uploads"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_data_shared:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_data/gitlab-rails/shared"
      o: "addr=192.168.xxx.xxxlookupcache=positive,noatime"
      type: "nfs4"
  gitlab_data_builds:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_data/gitlab-ci/builds"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_data_git_data:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_data/git-data"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_config:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_config"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_backup:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_backup"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  gitlab_logs:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/gitlab_logs/{{.Node.ID}}"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  mm_config:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/mm_config"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  mm_data:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/mm_data"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  mm_logs:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/mm_logs"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  mm_plugins:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/mm_plugins"
      o: "addr=192.168.xxx.xxx,lookupcache=positive,noatime"
      type: "nfs4"
  traefik_certs:
    driver_opts:
      device: ":/vol/tdcvnetapp/gitlab-dev/traefik_certs"
      o: "addr=192.168.xxx.xxxlookupcache=positive,noatime"
      type: "nfs4"


configs:
  alertmanager_yml:
    file: ./docker/configs/dev/alertmanager.yml
    name: alertmanager_${ALERT_MGR_CONFIG}

  traefik_toml:
    file: ./docker/configs/dev/traefik.toml
    name: traefik_toml_${TRAEFIK_CONFIG}

  prometheus_yml:
    file: ./docker/configs/dev/prometheus.yml
    name: prometheus_${PROM_CONFIG}

  prometheus_gitlab_rules:
    file: ./docker/configs/dev/gitlab.rules
    name: gitlab_rules_${PROM_GL_RULES_CONFIG}

  prometheus_gitlab_rules_20:
    file: ./docker/configs/dev/gitlab.rules.yml
    name: gitlab_rules_20_${PROM_GL_RULES20_CONFIG}

  blackbox_exporter_yml:
    file: ./docker/configs/dev/blackbox-exporter.yml
    name: blackbox_${BLACKBOX_CONFIG}

  status_page_json:
    file: ./docker/configs/dev/status_page.json
    name: statuspage_json_${STATUS_JSON_CONFIG}

  status_page_js:
    file: ./docker/configs/dev/status_page.js
    name: statuspage_js_${STATUS_JS_CONFIG}

  ca_certificates:
    file: ./docker/configs/dev/ca-certificates.crt
    name: cacerts_${CA_CERTS_CONFIG}

  postgres_exporter_custom_yaml:
    file: ./docker/configs/dev/pgcustom.yml
    name: pgexporter_${PG_EXPORTER_CONFIG}

  grafana_ldap_toml_v2:
    file: ./docker/configs/dev/grafana_ldap.toml
    name: grafana_ldap_${GRAF_LDAP_CONFIG}

  mm_ssl_cert:
    file: ./docker/configs/dev/mattermost.crt
    name: mm_certs_${MM_CONFIG}

  mm_ssl_key:
    file: ./docker/configs/dev/mattermost.key
    name: mm_key_${MM_CONFIG}

secrets:
  gitlab_postgres_password:
    external: true
  gitlab_ldap_password:
    external: true
  gitlab_ssl_crt:
    external: true
  gitlab_ssl_key:
    external: true
  gitlab_new_ssl_crt:
    external: true
  gitlab_new_ssl_key:
    external: true
  gitlab_keytab:
    external: true
  gitlab_backup_pub_key:
    external: true
  artifactory_api_key:
    external: true
  gitlab_pages_ssl_crt:
    external: true
  gitlab_pages_ssl_key:
    external: true
  gitlab_pages_new_ssl_crt:
    external: true
  gitlab_pages_new_ssl_key:
    external: true
  gitlab_inc_email_password:
    external: true
  mm_db_password:
    external: true
  mm_gitlab_secret:
    external: true
  mm_ssl_cert:
    external: true
  mm_ssl_key:
    external: true
    

  traefik:
    image: traefik:1.7.9-alpine
    command:
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --web
      - --web.metrics.prometheus
      - --docker.domain=gitlab-devxxxxx.com
      - --logLevel=DEBUG
    ports:
      - 8080:80
      - 8000:443
      - 9090:8080
    secrets:
      -  source: mm_ssl_cert
          target: mattermost.crt
      -  source: mm_ssl_key
          target: mattermost.key
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
        mode: 0644
      - source: mm_ssl_cert
        target: /etc/ssl/certs/mattermost.crt
        mode: 0444
     - source: mm_ssl_key
        target: /etc/ssl/certs/mattermost.key
        mode: 0444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certs:/var/ssl
    networks:
      - traefik
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
```

So in the docker compose file we don't always have a config, secret, and volume mount running at the same time. I'm just including all the different options we've tried.  Again, the only way it works is using a config that passes the cert and key to /etc/ssl/certs in the traefik container.  But we would prefer to use secrets as we do for other services and point the certs to /run/secrets/ folder instead.

This is my working traefik.toml file:

```defaultEntryPoints = ["https", "http"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/certs/mattermost.crt"
      keyFile = "/etc/ssl/certs/mattermost.key"
```

If I set:

```
    [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/mattermost.crt"
      keyFile = "/run/secrets/mattermost.key"

```
that fails even though the secrets are accessible when I ssh into the container.

### What did you expect to see?

https works with cert and key file pointed to /run/secrets/

### What did you see instead?

tls error: `time="2019-04-09T12:09:09Z" level=debug msg="http: TLS handshake error from 10.255.0.2:58575: tls: no certificates configured"`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
