### ISSUE TITLE
Traefik encodes '#' caractere in the path before sending to the backend

### ISSUE THREAD

**Issue by darviche** [containous/traefik#4758]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I am trying to make a modifier rule as following :
````
- "traefik.docker.network=ovnet_proxy"
- "traefik.frontend.entryPoints=https"
- "traefik.port=8052"
- "traefik.backend.loadbalancer.stickiness=true"
- "traefik.frontend.passHostHeader=true"
- "traefik.backend.healthcheck.path=/api"
- "traefik.backend.loadbalancer.stickiness.cookieName=instance"
- "traefik.frontend.rule=ReplacePathRegex:/app/login /#/login"
- "traefik.frontend.whiteList.useXForwardedFor=true"
````

### What did you expect to see?

When the path is /app/login, Traefik replaces it by /#/login 

### What did you see instead?

When the path is /app/login, Traefik replaces '#' by '%23' so the resulting path is /%23/login

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefk is run as docker service with the following docker-compose file : 
``` 
version: "3.2"
services:
  traefik:
    image: traefik:1.7.10
    command:
      - "--accesslog=true"
      - "--loglevel=DEBUG"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::8443 TLS:/cert/app.crt,/cert/app.key"
      - "--api=true"
      - "--api.dashboard"
      - "--api.entrypoint=http"
      - "--docker"
      - "--docker.watch"
      - "--docker.swarmmode"
      - "--ping"
      - "--ping.entrypoint=http"
    ports:
      - 8443:8443
      - 80:80
    deploy:
      mode: global
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app.crt:/cert/app.crt
      - ./app.key:/cert/app.key
    networks:
     - ovnet_proxy

networks:
  ovnet_proxy:
    external: true
```
