### ISSUE TITLE
V2.0 ACME onhostrule not working

### ISSUE THREAD

**Issue by thomas15v** [containous/traefik#4762]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried setting up a traefik V2.0 server using docker. It worked fine until I started to try getting ACME to work. I can confirm that I am not using swarm.

### What did you expect to see?

I expected that some certificates would be generated. 

### What did you see instead?

acme.json file is empty. When accepting the invalid certificate I get some errors in the logging (see below)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha3
Codename:     faisselle
Go version:   go1.12.1
Built:        2019-03-29T17:53:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
version: '3'
services:
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
  odoo:
    image: mycustomimage.com/customimage:latest
    restart: always
    links:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.odoo.rule: "Host(`website.com`)"
      traefik.http.routers.odoo.service: odoo
      traefik.http.services.odoo.loadbalancer.server.port: 8069
      traefik.http.routers.terminal.rule: "Host(`terminal.website.com`)"
      traefik.http.routers.terminal.service: terminal
      traefik.http.services.terminal.loadbalancer.server.port: 9700
  proxy:
    image: traefik:v2.0
    command: >
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443'      
      --api
      --acme
      --acme.acmelogging
      --acme.email=systems@website.com
      --acme.entrypoint=https
      --acme.httpchallenge
      --acme.httpchallenge.entrypoint=http
      --acme.storage=acme.json
      --acme.onhostrule
      --providers
      --providers.docker
      --providers.docker.exposedbydefault=false
      --providers.docker.watch
      --global.sendAnonymousUsage=false
      --global.debug
      --log.loglevel=debug
      --accesslog
      --serverstransport.insecureskipverify 
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
````

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
proxy_1  | 2019/04/12 15:23:27 server.go:3012: http: TLS handshake error from 84.199.238.11:55160: remote error: tls: illegal parameter
proxy_1  | time="2019-04-12T15:23:27Z" level=debug msg="Serving default certificate for request: \"website.com\""
proxy_1  | 2019/04/12 15:23:27 server.go:3012: http: TLS handshake error from 84.199.238.11:58849: remote error: tls: unknown certificate
proxy_1  | time="2019-04-12T15:23:27Z" level=debug msg="Serving default certificate for request: \"website.com\""
```
