### ISSUE TITLE
Docker secrets does not work while doing dnsChallenge

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [containous/traefik#4766]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

```yml
version: "3.6"

services:
  traefik:
    image: traefik:alpine # or traefik:latest
    command: --api
    environment:
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/traefik.toml:/traefik.toml"
      - "~/acme.json:/acme.json"

volumes:
  mysql-data:

secrets:
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true
```

### What did you expect to see?

I expect it to work just like putting keys directly on compose file.

Reference: https://docs.traefik.io/configuration/acme/#provider

### What did you see instead?

```
level=error msg="Error obtaining certificate retrying in 458.520947ms"
level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:..."
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```sh
echo "my_real_aws_access_key_id_here" | sudo docker secret create aws_access_key_id -
echo "my_real_aws_secret_access_key_here" | sudo docker secret create aws_secret_access_key -
```
