### ISSUE TITLE
Route traffic to a specific server when all weighted servers are down

### ISSUE THREAD

**Issue by mason-mcglothlin** [containous/traefik#4771]
### Do you want to request a *feature* or report a *bug*?

Not sure. Traefik isn't matching my expectations as to how it should perform. But I guess whether it's a bug or feature request depends on how everyone else expects it to work.

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Set up two servers with wrr and health checks. One server having a weight of 1, the other a weight of 0.

### What did you expect to see?

Requests should only be routed to the server with a weight of 1, assuming it's passing the health check. When it's failing the health check, requests should be routed only to the server with a weight of 0.

### What did you see instead?
When the server with a weight of 1 is passing the health check, traffic is routing just to that server as I expected. However when the health check is failing, Traefik returns "Internal Server Error" and does not route traffic to the server with a weight of 0.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.10
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
defaultEntryPoints = ["http"]
AllowMinWeightZero = true

[entryPoints]
  [entryPoints.http]
  address = ":8000"

  [entryPoints.webadmin]
  address = ":8001"

[api]
  dashboard = true
  entryPoint = "webadmin"

[file]

[backends]
  [backends.srweb]
    [backends.srweb.healthcheck]
      path = "/Home/StatusCheck"
      interval = "10s"
    [backends.srweb.servers]
      [backends.srweb.servers.server0]
        url = 'https://stingray.localhost'
        weight = 1
      [backends.srweb.servers.maintenancepage]
        url = 'https://stingraymaintenance.stingray.localhost/'
        weight = 0

[frontends]
  [frontends.frontend1]
    entryPoints = ["http"]
    backend = "srweb"
    passHostHeader = false

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
WARN[2019-04-15T10:43:44-05:00] Health check failed: Remove from server list. Backend: "srweb" URL: "https://stingray.localhost" Reason: received error status code: 500
DEBU[2019-04-15T10:44:03-05:00] '500 Internal Server Error' caused by: all servers have 0 weight
```

What I am trying to achieve is similar to a [Barracuda Last Resort Server](https://campus.barracuda.com/product/loadbalanceradc/knowledgebase/50160000000HB7wAAG/How+should+I+configure+the+Last+Resort+Server+on+my+Barracuda+Load+Balancer/). Basically, if all "real" servers are down (those with a weight > 1) then I want to route traffic to a special server so I can show a maintenance page. But I don't want the maintenance page showing up when any of the "real" servers have a passing health check.
