### ISSUE TITLE
when using rancher as provider, traefik.port=80 is required

### ISSUE THREAD

**Issue by websolutions-hamburg** [containous/traefik#4773]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I run Traefik with Rancher as provider.

### What did you expect to see?

When I start a container with Traefik labels, I expect that I don't need to set the `traefik.port=80` label for the default port.

### What did you see instead?

Traefik ignores the container until I set the label.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I use Rancher: `v1.6.26`

```toml
defaultEntryPoints = ["http","https"]

################################################################
# Entrypoints configuration
################################################################

[entryPoints]

  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.traefik]
    address = ":9000"

################################################################
# API and dashboard configuration
################################################################

[api]

  dashboard = true

  [api.statistics]
    recentErrors = 50

################################################################
# Retry
################################################################

[retry]

################################################################
# Rancher Provider
################################################################

[rancher]

  domain = "rancher.localhost"
  watch = true
  exposedByDefault = false
  enableServiceHealthFilter = true

  [rancher.metadata]

```

To start a container I used this docker-compose.yml

```yml
version: '2'

services:
  whoami:
    image: containous/whoami
    labels:
      traefik.enable: true
      traefik.backend: "whoami"
#      traefik.port: "80"
      traefik.frontend.rule: "Host:whoami.local"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
