### ISSUE TITLE
Traefik 2.0 not loadbalancing http from Docker provider (Swarm mode).

### ISSUE THREAD

**Issue by tundish** [containous/traefik#4774]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

* Create Linode VM with updated Alpine Linux (kernel 5.0.6).
* Install docker from Alpine packages (version 18.0.9.4-ce).
* Create nftables ruleset to permit http traffic.
* Build docker image for web app exposing port 8080 (in this case [carmen](https://github.com/tundish/carmen_brittunculi)).
* Activate docker swarm mode (single manager node only).
* Deploy stack using only a version 3 docker compose file for Traefik configuration (details below).

### What did you expect to see?

* Expect to curl or browse to VM's IPv4 address port 80.
* Expect Traefik to loadbalance back end services via their port 8080.
* Expect sticky sessions when accessed from browser.

### What did you see instead?

_HTTP error 404 page not found_ from both inside and outside the VM.
Question: Is this coming from Traefik's own configuration API?

```
$ curl -4v http://localhost:80
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 16 Apr 2019 06:17:40 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host localhost left intact
* Closing connection 0

```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.0.0-alpha3
Codename:     faisselle
Go version:   go1.12.1
Built:        2019-03-29T17:53:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml

version: "3.2"
services:
  app:
    image:  carmen:201904111618
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=carmen_proxynet
        - traefik.http.routers.app_router.entrypoints=http
        - traefik.http.routers.app_router.rule=Path("/.*")
        - traefik.http.routers.app_router.service=app_service
        - traefik.http.services.app_service.loadbalancer.server.url=http://localhost
        - traefik.http.services.app_service.loadbalancer.server.port=8080
        - traefik.http.services.app_service.loadbalancer.stickiness=true
    networks:
      - proxynet

  balancer:
    image:  traefik:v2.0
    command: >
        --accesslog
        --log.loglevel=debug
        --global.debug
        --global.sendanonymoususage
        --global.checknewversion
        --entrypoints='Name:http Address::80'
        --providers.docker
        --providers.docker.swarmmode=true
        --providers.docker.watch=true
        --providers.docker.exposedbydefault=false
    ports:
      - 80:80
      - 9000:8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxynet

networks:
  proxynet:

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2019-04-16T05:28:21Z" level=info msg="Traefik version 2.0.0-alpha3 built on 2019-03-29T17:53:25Z"
time="2019-04-16T05:28:21Z" level=debug msg="Static configuration loaded {\"Global\":{\"Debug\":true,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false},\"ServersTransport\":{\"InsecureSkipVerify\":false,\"RootCAs\":null,\"MaxIdleConnsPerHost\":200,\"ForwardingTimeouts\":null},\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}}},\"Providers\":{\"ProvidersThrottleDuration\":2000000000,\"Docker\":{\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":true,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15},\"File\":null,\"Marathon\":null,\"Kubernetes\":null,\"KubernetesCRD\":null,\"Rest\":null},\"API\":null,\"Metrics\":null,\"Ping\":null,\"Log\":{\"LogLevel\":\"debug\",\"format\":\"common\"},\"AccessLog\":{\"format\":\"common\"},\"Tracing\":null,\"HostResolver\":null,\"ACME\":null}"
time="2019-04-16T05:28:21Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-04-16T05:28:21Z" level=debug msg="No default certificate, generate one"
time="2019-04-16T05:28:22Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-04-16T05:28:22Z" level=debug msg="Start TCP Server" entryPointName=http
time="2019-04-16T05:28:22Z" level=info msg="Starting provider *docker.Provider {\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":true,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
time="2019-04-16T05:28:22Z" level=debug msg="Provider connection established with docker 18.09.4-ce (API 1.39)" providerName=docker
time="2019-04-16T05:28:22Z" level=debug msg="Filtering disabled container" providerName=docker container=carmen_balancer-yq7379ljr7a43qvgbpz47yc3n
time="2019-04-16T05:28:22Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-16T05:28:22Z" level=debug msg="No default certificate, generate one"
time="2019-04-16T05:28:37Z" level=debug msg="Filtering disabled container" providerName=docker container=carmen_balancer-yq7379ljr7a43qvgbpz47yc3n
time="2019-04-16T05:28:37Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"app_router\":{\"entryPoints\":[\"http\"],\"service\":\"app_service\",\"rule\":\"Path(\\\"/.*\\\")\"}},\"services\":{\"app_service\":{\"loadbalancer\":{\"stickiness\":{},\"servers\":[{\"url\":\"http://10.0.43.6:8080\",\"weight\":1},{\"url\":\"http://10.0.43.4:8080\",\"weight\":1},{\"url\":\"http://10.0.43.7:8080\",\"weight\":1},{\"url\":\"http://10.0.43.5:8080\",\"weight\":1},{\"url\":\"http://10.0.43.3:8080\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-16T05:28:37Z" level=debug msg="Creating middleware" serviceName=app_service middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=docker.app_router
time="2019-04-16T05:28:37Z" level=debug msg="Creating wrr load-balancer" routerName=docker.app_router serviceName=app_service entryPointName=http
time="2019-04-16T05:28:37Z" level=debug msg="Sticky session cookie name: _9fdd5" routerName=docker.app_router serviceName=app_service entryPointName=http
time="2019-04-16T05:28:37Z" level=debug msg="Creating server 0 at http://10.0.43.6:8080 with weight 1" entryPointName=http routerName=docker.app_router serviceName=app_service serverName=0
time="2019-04-16T05:28:37Z" level=debug msg="Creating server 1 at http://10.0.43.4:8080 with weight 1" entryPointName=http routerName=docker.app_router serviceName=app_service serverName=1
time="2019-04-16T05:28:37Z" level=debug msg="Creating server 2 at http://10.0.43.7:8080 with weight 1" serverName=2 entryPointName=http routerName=docker.app_router serviceName=app_service
time="2019-04-16T05:28:37Z" level=debug msg="Creating server 3 at http://10.0.43.5:8080 with weight 1" entryPointName=http routerName=docker.app_router serviceName=app_service serverName=3
time="2019-04-16T05:28:37Z" level=debug msg="Creating server 4 at http://10.0.43.3:8080 with weight 1" serviceName=app_service entryPointName=http routerName=docker.app_router serverName=4
time="2019-04-16T05:28:37Z" level=debug msg="Added outgoing tracing middleware app_service" entryPointName=http routerName=docker.app_router middlewareName=tracing middlewareType=TracingForwarder
time="2019-04-16T05:28:37Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2019-04-16T05:28:37Z" level=debug msg="No default certificate, generate one"
time="2019-04-16T05:28:52Z" level=debug msg="Filtering disabled container" providerName=docker container=carmen_balancer-yq7379ljr7a43qvgbpz47yc3n
time="2019-04-16T05:28:52Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"app_router\":{\"entryPoints\":[\"http\"],\"service\":\"app_service\",\"rule\":\"Path(\\\"/.*\\\")\"}},\"services\":{\"app_service\":{\"loadbalancer\":{\"stickiness\":{},\"servers\":[{\"url\":\"http://10.0.43.6:8080\",\"weight\":1},{\"url\":\"http://10.0.43.4:8080\",\"weight\":1},{\"url\":\"http://10.0.43.7:8080\",\"weight\":1},{\"url\":\"http://10.0.43.5:8080\",\"weight\":1},{\"url\":\"http://10.0.43.3:8080\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker

```
**NB**: The following messages are repeated every 15 seconds in the logs, as Traefik is continually configuring itself.

```
time="2019-04-16T05:47:07Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
time="2019-04-16T05:47:22Z" level=debug msg="Filtering disabled container" providerName=docker container=carmen_balancer-yq7379ljr7a43qvgbpz47yc3n
time="2019-04-16T05:47:22Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"app_router\":{\"entryPoints\":[\"http\"],\"service\":\"app_service\",\"rule\":\"Path(\\\"/.*\\\")\"}},\"services\":{\"app_service\":{\"loadbalancer\":{\"stickiness\":{},\"servers\":[{\"url\":\"http://10.0.43.6:8080\",\"weight\":1},{\"url\":\"http://10.0.43.4:8080\",\"weight\":1},{\"url\":\"http://10.0.43.7:8080\",\"weight\":1},{\"url\":\"http://10.0.43.5:8080\",\"weight\":1},{\"url\":\"http://10.0.43.3:8080\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-16T05:47:22Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
```
