### ISSUE TITLE
Traefik CPU spikes every 2 minutes with many simultaneous websocket connections (GC?)

### ISSUE THREAD

**Issue by Agamnentzar** [containous/traefik#4801]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
Serving 2000-4000 websocket connections sending a lot of small packets both ways

### What did you expect to see?
Stable CPU load

### What did you see instead?
![ss+(2019-04-19+at+07 35 20)](https://user-images.githubusercontent.com/572298/56435913-71042380-62da-11e9-85ce-bc0dbbefbf55.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

openSUSE Leap 15.0 / x86_64

```toml
[backends]
  [backends.example-backend]
    [backends.example-backend.servers.server1]
    url = "http://localhost:8071"
    weight = 1
    [backends.example-s01.servers.server1]
    url = "http://localhost:8072"
    weight = 1
    [backends.example-s02.servers.server1]
    url = "http://localhost:8073"
    weight = 1
    [backends.example-s03.servers.server1]
    url = "http://localhost:8074"
    weight = 1
    [backends.example-s04.servers.server1]
    url = "http://localhost:8075"
    weight = 1
    [backends.example-s05.servers.server1]
    url = "http://localhost:8076"
    weight = 1
    [backends.example-s06.servers.server1]
    url = "http://localhost:8077"
    weight = 1
    [backends.example-s07.servers.server1]
    url = "http://localhost:8078"
    weight = 1
    [backends.example-s08.servers.server1]
    url = "http://localhost:8079"
    weight = 1
    [backends.example-s09.servers.server1]
    url = "http://localhost:8068"
    weight = 1
    [backends.example-adm.servers.server1]
    url = "http://localhost:8067"
    weight = 1

[frontends]
  [frontends.example-s01]
    backend = "example-s01"
    entryPoints = [ "https" ]
    [frontends.example-s01.routes.main]
    rule = "Host: example.com; PathPrefix: /s01"
  [frontends.example-s02]
    backend = "example-s02"
    entryPoints = [ "https" ]
    [frontends.example-s02.routes.main]
    rule = "Host: example.com; PathPrefix: /s02"
  [frontends.example-s03]
    backend = "example-s03"
    entryPoints = [ "https" ]
    [frontends.example-s03.routes.main]
    rule = "Host: example.com; PathPrefix: /s03"
  [frontends.example-s04]
    backend = "example-s04"
    entryPoints = [ "https" ]
    [frontends.example-s04.routes.main]
    rule = "Host: example.com; PathPrefix: /s04"
  [frontends.example-s05]
    backend = "example-s05"
    entryPoints = [ "https" ]
    [frontends.example-s05.routes.main]
    rule = "Host: example.com; PathPrefix: /s05"
  [frontends.example-s06]
    backend = "example-s06"
    entryPoints = [ "https" ]
    [frontends.example-s06.routes.main]
    rule = "Host: example.com; PathPrefix: /s06"
  [frontends.example-s07]
    backend = "example-s07"
    entryPoints = [ "https" ]
    [frontends.example-s07.routes.main]
    rule = "Host: example.com; PathPrefix: /s07"
  [frontends.example-s08]
    backend = "example-s08"
    entryPoints = [ "https" ]
    [frontends.example-s08.routes.main]
    rule = "Host: example.com; PathPrefix: /s08"
  [frontends.example-s09]
    backend = "example-s09"
    entryPoints = [ "https" ]
    [frontends.example-s09.routes.main]
    rule = "Host: example.com; PathPrefix: /s09"

  [frontends.example-frontend]
  backend = "example-backend"
  entryPoints = [ "https", "http" ]

    [frontends.example-frontend.routes.main]
    rule = "Host: example.com"
    [frontends.example-frontend.redirect]
    entryPoint = "https"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
