### ISSUE TITLE
PathPrefix `/` not working

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [containous/traefik#4805]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
read the documentation, tried to catch all requests and pass them to a defined frontend

```toml
      rule = "PathPrefix(`/`)"

# i also tried
      rule = "Host(`127.0.0.1`)"
      rule = "Host(`localhost`)"
      rule = "Host(`*`)"
      rule = "Host(`.*`)"
      rule = "HostRegexp(`.*`)"
```

### What did you expect to see?
traefik to forward the request internally to my nginx on port 8080

### What did you see instead?
404 page not found
or
Internal Server Error

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
/ $ traefik version
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entrypoints]
    [entrypoints.web]
    address = ":40700"
    [entrypoints.admin]
    address = ":40701"

[log]
logLevel = "INFO"
filePath = "/var/log/traefik/traefik.log"
format = "json"

[accessLog]
filePath = "/var/log/traefik/access.log"
format = "json"

[api]
  entryPoint = "admin"
  dashboard = true

[ping]
  entryPoint = "admin"

[providers]
  [providers.file]
    filename = "/etc/traefik/rules.toml"
    watch = true
```

```toml
[http] # http routing section
  [http.routers]
    [http.routers.to-web] # Define a connection between requests and services
      entrypoints = ["web"]
      rule = "HostRegexp(`.*`)"
      service = "web" # If

[http.services]
       [http.services.web.LoadBalancer]
          [[http.services.web.LoadBalancer.servers]]
             url = "http://127.0.0.1:8080"
```

**Comment by ThomasSchoenbeck** [comment]
finally got it to work.

don't skip the weight on the route!

```toml
[http.services]
  [http.services.web.LoadBalancer]
    [[http.services.web.LoadBalancer.servers]]
      url = "http://127.0.0.1:8080"
      weight = 1 # without this it will not work
```
