### ISSUE TITLE
Traefik v2 not forwarding requests to servers on rule Host

### ISSUE THREAD

**Issue by DamiaPoquet** [containous/traefik#4806]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
Deploy Traefik 2.0 and an app (Docker Registry for example) on a Docker Swarm.

### What did you expect to see?
Forward HTTP request to server.

### What did you see instead?
```
404 page not found
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[log]
  logLevel = "debug"

[accessLog]

[global]
  debug = true

[api]

[entrypoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"

  [entrypoints.ping]
    address = ":8082"

[ping]
    entryPoint = "ping"

[acme] 
  email = "redacted@redacted.tld"
  storage = "acme.json"
  onHostRule = true 
  [acme.httpChallenge]
    entryPoint = "http"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = true
    exposedByDefault = false
    network = "traefik_public"
```

### Traefik docker-compose.yml file
```yml
version: "3.4"

services:
  reverse-proxy:
    image: traefik:2.0
    networks:
      - public
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    configs:
      - source: traefik
        target: ./traefik.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    healthcheck:
      test: ["CMD", "/traefik", "healthcheck"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 2
        failure_action: rollback
        delay: 10s
        order: start-first

networks:
  public:
    driver: overlay

configs:
  traefik:
    file: ./traefik.toml
```

### Registry docker-compose.yml file
```yml
version: "3.4"

services:
  registry:
    image: registry:2
    networks:
      - traefik_public
    environment:
      - REGISTRY_HTTP_SECRET=redacted
    volumes:
      - registry:/var/lib/registry
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == redacted
      update_config:
        parallelism: 2
        failure_action: rollback
        delay: 10s
        order: start-first
      labels:
      - traefik.enable=true
      - traefik.http.routers.registry.entrypoints=https
      - traefik.http.routers.registry.rule=Host(`redacted.tld`)
      - traefik.http.services.registry.loadbalancer.server.port=5000

networks:
  traefik_public:
    external: true

volumes:
  registry:
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-04-23T09:33:10Z" level=info msg="Using TOML configuration file /traefik.toml"
time="2019-04-23T09:33:10Z" level=info msg="Traefik version 2.0.0-alpha4 built on 2019-04-17T11:38:21Z"
time="2019-04-23T09:33:10Z" level=debug msg="Static configuration loaded {\"Global\":{\"Debug\":true,\"CheckNewVersion\":false,\"SendAnonymousUsage\":false},\"ServersTransport\":{\"InsecureSkipVerify\":false,\"RootCAs\":null,\"MaxIdleConnsPerHost\":200,\"ForwardingTimeouts\":null},\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"ping\":{\"Address\":\":8082\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}}},\"Providers\":{\"ProvidersThrottleDuration\":0,\"Docker\":{\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":true,\"Network\":\"traefik_public\",\"SwarmModeRefreshSeconds\":15},\"File\":null,\"Marathon\":null,\"Kubernetes\":null,\"KubernetesCRD\":null,\"Rest\":null,\"Rancher\":null},\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Statistics\":null,\"Middlewares\":null},\"Metrics\":null,\"Ping\":{\"EntryPoint\":\"ping\",\"Middlewares\":null},\"Log\":{\"Level\":\"\",\"format\":\"common\"},\"AccessLog\":{\"format\":\"common\"},\"Tracing\":null,\"HostResolver\":null,\"ACME\":{\"Email\":\"redacted@redacted.tld\",\"ACMELogging\":false,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"acme.json\",\"EntryPoint\":\"\",\"KeyType\":\"\",\"OnHostRule\":true,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null}}"
time="2019-04-23T09:33:10Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-04-23T09:33:10Z" level=debug msg="No default certificate, generate one"
time="2019-04-23T09:33:11Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-04-23T09:33:11Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-04-23T09:33:11Z" level=debug msg="Start TCP Server" entryPointName=http
time="2019-04-23T09:33:11Z" level=debug msg="Start TCP Server" entryPointName=https
time="2019-04-23T09:33:11Z" level=debug msg="Start TCP Server" entryPointName=ping
time="2019-04-23T09:33:11Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"redacted@redacted.tld\",\"ACMELogging\":false,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"acme.json\",\"EntryPoint\":\"\",\"KeyType\":\"\",\"OnHostRule\":true,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null,\"Store\":{}}"
time="2019-04-23T09:33:11Z" level=info msg="Testing certificate renew..." providerName=acme
time="2019-04-23T09:33:11Z" level=info msg="Starting provider *docker.Provider {\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":true,\"Network\":\"traefik_public\",\"SwarmModeRefreshSeconds\":15}"
time="2019-04-23T09:33:11Z" level=debug msg="Configuration received from provider ACME: {\"HTTP\":{},\"TCP\":null,\"TLSOptions\":null,\"TLSStores\":null}" providerName=ACME
time="2019-04-23T09:33:11Z" level=debug msg="No store is defined to add the certificate MIIGTjCCBTagAwIBAgISBAVW3J5jvUFPCVwEktQShQF1MA0GCS, it will be added to the default store."
time="2019-04-23T09:33:11Z" level=debug msg="Adding certificate for domain(s) redacted.tld"
time="2019-04-23T09:33:11Z" level=debug msg="No default certificate, generate one"
time="2019-04-23T09:33:11Z" level=debug msg="Provider connection established with docker 18.09.5 (API 1.39)" providerName=docker
time="2019-04-23T09:33:11Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:33:11Z" level=debug msg="Adding certificate for domain(s) redacted.tld"
time="2019-04-23T09:33:11Z" level=debug msg="No default certificate, generate one"
time="2019-04-23T09:33:26Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:33:26Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
time="2019-04-23T09:33:41Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:33:41Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
time="2019-04-23T09:33:56Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:33:56Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
time="2019-04-23T09:34:11Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:34:11Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
time="2019-04-23T09:34:26Z" level=debug msg="Filtering disabled container" providerName=docker container=traefik_reverse-proxy-zut40t1j0bvypcoawl7zqulrb
time="2019-04-23T09:34:26Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"registry\":{\"entryPoints\":[\"https\"],\"service\":\"registry\",\"rule\":\"Host(`redacted.tld`)\"}},\"services\":{\"registry\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://10.0.3.6:5000\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:34:26Z" level=debug msg="Adding certificate for domain(s) redacted.tld"
time="2019-04-23T09:34:26Z" level=debug msg="No default certificate, generate one"
time="2019-04-23T09:34:26Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=https routerName=docker.registry serviceName=registry
time="2019-04-23T09:34:26Z" level=debug msg="Creating wrr load-balancer" entryPointName=https routerName=docker.registry serviceName=registry
time="2019-04-23T09:34:26Z" level=debug msg="Creating server 0 at http://10.0.3.6:5000 with weight 1" serverName=0 entryPointName=https routerName=docker.registry serviceName=registry
time="2019-04-23T09:34:26Z" level=debug msg="Added outgoing tracing middleware registry" routerName=docker.registry middlewareName=tracing middlewareType=TracingForwarder entryPointName=https
time="2019-04-23T09:34:26Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=https middlewareName=traefik-internal-recovery
time="2019-04-23T09:34:41Z" level=debug msg="Filtering disabled container" providerName=docker container=traefik_reverse-proxy-zut40t1j0bvypcoawl7zqulrb
time="2019-04-23T09:34:41Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"registry\":{\"entryPoints\":[\"https\"],\"service\":\"registry\",\"rule\":\"Host(`redacted.tld`)\"}},\"services\":{\"registry\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://10.0.3.6:5000\",\"weight\":1}],\"method\":\"wrr\",\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-04-23T09:34:41Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
```
