### ISSUE TITLE
MOVE does not rewrite "destination" header

### ISSUE THREAD

**Issue by pre-martin** [containous/traefik#4816]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Traefik is configured as a proxy for a WebDAV server. Traefik is configured to match the host name "share.example.org" and is listening on port 443. It proxies requests to the internal WebDAV server "share-internal.intra.org" on port 80.

When a WebDAV client sends a MOVE command, the following arrives at the WebDAV server (just the relevant headers):

```
MOVE /somedir/somefile.txt.tmp HTTP/1.1
Host: share.example.org
User-Agent: Go-http-client/1.1
Destination: https://share.example.org/somedir/somefile.txt
```

The problem is the destination header. Traefik is proxying requests to `http://share-internal.intra.org`, so this target server cannot handle `https://share.example.org`.

### What did you expect to see?

Success of the WebDAV MOVE operation.

### What did you see instead?

The internal WebDAV server (Apache 2.4) responds with `502 Bad Gateway`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [frontends.share]
        backend = "share-internal"
        passHostHeader = true
        [frontends.share.routes.test_1]
            rule = "Host:share.example.org"
        [frontend.share.redirect]
            entryPoints = "https"
            regex = "^http://share.example.org/(.*)"
            replacement = "https://share.example.org/$1"
            permanent = true
        [frontends.share.headers]
            STSSeconds = 31536000
            STSIncludeSubdomains = true
            STSPreload = true

    [backends.share-internal]
        [backends.share-internal.servers.server1]
            url = "http://share-internal.intra.org"
            weight = 1
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/somedir/somefile.txt.tmp\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://share-internal.intra.org" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/somedir/somefile.txt.tmp\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"share-internal.intra.org\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"share-internal.intra.org\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
time="2019-04-25T11:38:44Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://share-internal.intra.org, code: 502, Length: 71, duration: 1.376141ms tls:version: 303, tls:resume:true, tls:csuite:c02f, tls:server:share.example.org"
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"share-internal.intra.org\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"share-internal.intra.org\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
time="2019-04-25T11:38:44Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"MOVE\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/somedir/somefile.txt.tmp\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Destination\":[\"https://share.example.org/somedir/somefile.txt\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"share.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"x.x.x.x:41349\",\"RequestURI\":\"/somedir/somefile.txt.tmp\",\"TLS\":null}"
x.x.x.x - - [25/Apr/2019:11:38:44 +0000] "MOVE /somedir/somefile.txt.tmp HTTP/1.1" 502 71 "-" "-" 6 "share" "http://share-internal.intra.org" 1ms
```

**Comment by pre-martin** [comment]
Update: If a configure traefik to forward to `https://share-internal.intra.org` instead of `http://share-internal.intra.org` the MOVE operation works.

So it looks like the "Bad Gateway" from Apache is because of the wrong scheme in the "Destination" header.

**Comment by ichenhe** [comment]
After 5 years, this problem still exists...

Here's a workaround: the key is that use https to connect to the upstream. So your webDAV server must support https, even if use a self-signed cert (we can ignore the cert verify by `insecureSkipVerify=true`.

```yaml
# dynamic.yml

http:
  services:
    webdav:
      loadBalancer:
        serversTransport: ignore-cert
        servers:
          - url: "https://192.168.1.10:5005/" #use https

  serversTransports:
    ignore-cert:
      insecureSkipVerify: true
```
