### ISSUE TITLE
Nodeports are hanging, while the health checkpoint works

### ISSUE THREAD

**Issue by zoltan-fedor** [containous/traefik#4826]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X ] No

### What did you do?

I have installed Traefik using the "official" Helm chart (https://github.com/helm/charts/tree/master/stable/traefik) with AWS NLB on an AWS EKS cluster 1.12:
```
$ helm install stable/traefik --name traefik-private --namespace kube-system \
--set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=nlb \
--set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"=0.0.0.0/0 \
--set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled"=true \
--set loadBalancerSourceRanges[0]="10.97.32.0/19" \
--set dashboard.enabled=true \
--set kubernetes.ingressClass="traefik-private" \
--set replicas="2" \
--set rbac.enabled=true \
--set accessLogs.enabled=true \
--set externalTrafficPolicy=Local
```

Looking at the traefik-private service created, I see 4 internal endpoints:
```
traefik-private.kube-system:80 TCP
traefik-private.kube-system:31164 TCP
traefik-private.kube-system:443 TCP
traefik-private.kube-system:32391 TCP
```

But when when I try to connect to them from within the cluster, only port 80 and 443 works, port 31164 and 32391 does not.

```
$ curl -H Host:myapp.local http://traefik-private.kube-system:80
You shouldn't really be accessing this directly...
```
```
$curl -H Host:myapp.local http://traefik-private.kube-system:31164
curl: (7) Failed connect to traefik-private.kube-system:31164; Connection timed out
```

This is a problem, as those ports would receive the traffic from the NLB loadbalancer.

### What did you expect to see?

I would expect all 4 internal endpoints to works.

### What did you see instead?
Only port 80 and 443 does work.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http", "httpn"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.httpn]
  address = ":8880"
  compress = true
  [entryPoints.traefik]
  address = ":8080"
[kubernetes]
ingressClass = "traefik-private"
[traefikLog]
  format = "json"
[accessLog]
  format = "common"
[accessLog.fields]
  defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
  defaultMode = "keep"
[accessLog.fields.headers.names]
[api]
  entryPoint = "traefik"
  dashboard = true


```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
