### ISSUE TITLE
Unable to use purchased cert

### ISSUE THREAD

**Issue by venomone** [containous/traefik#4832]
I'm currently trying to use docker-compose to build a wordpress site sadly everytime the traefik reverse proxy is starting, it's using the default cert and not my own ones for that domain and i don't see any reason why its doing this?

```
docker-compose.yml

    version: '3'
    
    networks:
      frontend:
      backend:
    
    volumes:
      vol-wp-db:
      vol-wp-content:
    
    services:
      traefik:
       image: traefik:latest
       command:
        - --api
        - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
        - --entrypoints=Name:https Address::443 TLS
        - --defaultentrypoints=http,https
        - --docker
        - --docker.watch
       restart: always
       networks:
        - backend
        - frontend
       volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /ssl/:/ssl/
        - ./traefik.toml:/traefik.toml
       ports:
        - "80:80"
        - "443:443"
       labels:
          - "traefik.docker.network=frontend"
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:${TRAEFIK_DOMAINS}; PathPrefixStrip:/traefik-stats-monitor"
          - "traefik.protocol=http"
          - "traefik.frontend.auth.basic=${BASIC_AUTH}"

    ...
```

this is my toml file for the settings of traefik, i placed my ssl certs here /root/compose/ssl
and the root the of the compose is /root/compose
```

    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
      	[[entryPoints.https.tls.certificates]]
    	certFile = "/ssl/cert.crt"
    	keyFile = "/ssl/privkey.pem"
    
    
    # These options are for Traefik's integration with Docker.
    [docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "domain.com"
    watch = true
    exposedByDefault = false
    
    # https://docs.traefik.io/configuration/logs/
    # Comment out the next line to enable Traefik's access logs.
    # [accessLog]
```

Docker version 18.09.5, build e8ff056
