### ISSUE TITLE
Traefik not loading multiple routes

### ISSUE THREAD

**Issue by roidelapluie** [containous/traefik#4833]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
I set up multiple http routes:

```
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[accessLog]

[ServersTransport]
  RootCAs = [ "/etc/tlscerts/ca.crt", "/etc/ssl/certs/ca-certificates.crt" ]

[entryPoints]
  [entryPoints.http]
    address = ":8080"
  [entryPoints.https]
    address = ":8443"

[providers.file]

[HTTP]
  [HTTP.Routers]
   [HTTP.Routers.vault]
    EntryPoints = ["https"]
    Rule = "Host(`vault.mgmt.roidelapluie.be`)"
    Service = "vault"
    [http.Routers.vault.tls]
   [HTTP.Routers.jenkins]
    EntryPoints = ["https"]
    Rule = "Host(`ci.mgmt.roidelapluie.be`)"
    Service = "ci"
    [HTTP.Routers.jenkins.tls]

  [HTTP.Services]
    [HTTP.Services.vault]
    [HTTP.Services.vault.LoadBalancer]
       PassHostHeader = true
       [[HTTP.Services.vault.LoadBalancer.servers]]
        url = "https://vault.default.svc.cluster.local"
        weight = 1
    [HTTP.Services.ci]
    [HTTP.Services.ci.LoadBalancer]
       PassHostHeader = true
       [[HTTP.Services.ci.LoadBalancer.servers]]
          url = "http://jenkins.default.svc.cluster.local:8080"
          weight = 1

[[TLS]]
  Stores = ["default"]
  [TLS.Certificate]
    CertFile = "/etc/tlscerts/mgmt.crt"
    KeyFile = "/etc/tlscerts/mgmt.key"

[[TLS]]
  Stores = ["default"]
  [TLS.Certificate]
    CertFile = "/etc/tlscerts/www.crt"
    KeyFile = "/etc/tlscerts/www.key"


[TLSOptions]
  [TLSOptions.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
    ]


[TLSStores]
  [TLSStores.default]
    [TLSStores.default.DefaultCertificate]
    CertFile = "/etc/tlscerts/mgmt.crt"
    KeyFile = "/etc/tlscerts/mgmt.key"
```

### What did you expect to see?

Two routes defined

### What did you see instead?

Only one route defined:

```
level=debug msg="Configuration received from provider file: {\"HTTP\":{\"routers\":{\"jenkins\":{\"entryPoints\":[\"https\"],\"service\":\"ci\",\"rule\":\"Host(`ci.mgmt.roidelapluie.be`)\",\"tls\":{}},\"vault\":{\"entryPoints\":null,\"tls\":{}}},\"services\":{\"ci\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://jenkins.default.svc.cluster.local:8080\",\"weight\":1}],\"passHostHeader\":true}},\"vault\":{\"loadbalancer\":{\"servers\":[{\"url\":\"https://vault.default.svc.cluster.local\",\"weight\":1}],\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":{\"default\":{\"MinVersion\":\"VersionTLS12\",\"CipherSuites\":[\"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\",\"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\",\"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305\",\"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA\",\"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA\"],\"ClientCA\":{\"Files\":null,\"Optional\":false},\"SniStrict\":false}},\"TLSStores\":{\"default\":{\"DefaultCertificate\":{\"CertFile\":\"/etc/tlscerts/mgmt.crt\",\"KeyFile\":\"/etc/tlscerts/mgmt.key\"}}}}" providerName=file
```

(note: \"vault\":{\"entryPoints\":null,\"tls\":{}}})

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik v2.0.0-alpha4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See above

**Comment by ldez** [comment]
Hello,

You have to use the same case an element:

```toml
[HTTP]
  [HTTP.Routers]
   [HTTP.Routers.vault]
    EntryPoints = ["https"]
    Rule = "Host(`vault.mgmt.roidelapluie.be`)"
    Service = "vault"
    [http.Routers.vault.tls] # <-----------------
   [HTTP.Routers.jenkins]
    EntryPoints = ["https"]
    Rule = "Host(`ci.mgmt.roidelapluie.be`)"
    Service = "ci"
    [HTTP.Routers.jenkins.tls]
```

the fix:
```toml
[HTTP]
  [HTTP.Routers]
   [HTTP.Routers.vault]
    EntryPoints = ["https"]
    Rule = "Host(`vault.mgmt.roidelapluie.be`)"
    Service = "vault"
    [HTTP.Routers.vault.tls] # <-----------------
   [HTTP.Routers.jenkins]
    EntryPoints = ["https"]
    Rule = "Host(`ci.mgmt.roidelapluie.be`)"
    Service = "ci"
    [HTTP.Routers.jenkins.tls]
```
