### ISSUE TITLE
Content-Length is discarded by browser if traefik is in front of app

### ISSUE THREAD

**Issue by den-is** [containous/traefik#4839]
### Do you want to request a *feature* or report a *bug*?

Bug

Little bit crazy issue and I don't have super much info but I will try my best.

There is service running in k8s written in Go which is serving content for users. Gives users ability to download file.
Main GateWay LoadBalancer to infrastructure is HAproxy at the edge.
Then Kubernetes with Traefik to manage all that traffic.

So if I serve application with Traefik, response in browser is missing `Content-Length` header, so users can't see size of the downloading file.
While at the same moment `curl` has that header and does SIze/ download ETA just fine. Ridiculous - yes, I think same.

If I do:
`kubectl port-forward --address=0.0.0.0 svc/myapp 8080:80` - works great. Content-Length is present everywhere

If I expose service with `NodePort`, i.e. removing ingress out of the equation - all works great too

### Environment:
Kubernetes v1.12.8
helm chart=traefik-1.67.0
traefik:1.7.11

Traefik chart values
```yaml
image: traefik
imageTag: 1.7.11
serviceType: NodePort
service:
  nodePorts:
    http: 30003

rbac:
  enabled: true

dashboard:
  enabled: true
  domain: myapp.int.example.tld
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik

ssl:
  insecureSkipVerify: true

kubernetes:
  namespaces:
  - default
  labelSelector: app=myapp

cpuRequest: 500m
memoryRequest: 100Mi
cpuLimit: 2000m
memoryLimit: 512Mi
debug:
  enabled: false


tolerations:
- key: myapp
  operator: Exists
  effect: NoSchedule
- key: myapp
  operator: Exists
  effect: NoExecute

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - myapp
        - key: net
          operator: In
          values:
          - int

```

config.toml generated by helm
```toml
apiVersion: v1
kind: ConfigMap
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
      [entryPoints.traefik]
      address = ":8080"
    [kubernetes]
    namespaces = ["default"]
    labelselector = "app=godwnonit"
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
```
curl output (this is from my last try when curl can understand Content-Length and browser somehow completely drops that header, physically not visible in the list of headers)
```
curl -iv "myapp.domain.tld/dwn?oid=108.X.33.X/myvideo.mp4" -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 108.X.33.X...
* TCP_NODELAY set
* Connected to godwn-m.clips4sale.com (108.X.33.X) port 80 (#0)
> GET /dwn?oid=108.X.33.X/myvideo.mp4 HTTP/1.1
> Host: myapp.domain.tld
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: public
< Content-Disposition: attachment; filename="myvid.mp4"
< Content-Length: 248571207
< Content-Range: bytes 0-248571206/248571207
< Content-Transfer-Encoding: binary
< Content-Type: video/mp4;
< Date: Thu, 02 May 2019 11:40:31 GMT
< Last-Modified: Mon, 22 Apr 2019 20:24:04 GMT
< Vary: Accept-Encoding
<
{ [975 bytes data]
  0  237M    0  201k    0     0   108k      0  0:37:10  0:00:01  0:37:09  108k^C
```

Same happens even if i pass browser agent to curl.. curl works.

App is not public and content is little bit sensitive but in general i'm not able to collect much info.
