### ISSUE TITLE
Can't create RedirectScheme middleware with KubernetesCRD provider

### ISSUE THREAD

**Issue by sondabar** [containous/traefik#4854]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I wanted to use the RedirectScheme middleware to redirect from http to https with KubernetesCRD provider.

This bug seems to affect RedirectRegex too.

### What did you expect to see?

IngressRoute can use the RedirectScheme middleware.

output of /api/rawdata
```json
{
  "middlewares": {
    "ingress/https-only": {
      "redirectscheme": {
        "scheme": "https",
        "permanent": true
      }
    }
  }
}
```

### What did you see instead?

IngressRoute can't find the RedirectScheme.

output of /api/rawdata
```json
{
  "middlewares": {
    "ingress/https-only": {}
  }
}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik Deployment/DaemonSet:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
        - name: traefik
          image: traefik:v2.0.0-alpha4-alpine
          args:
            - --log.level=debug
            - --api
            - --ping
            - --accesslog
            - --entrypoints=Name:web Address::80
            - --entrypoints=Name:websecure Address::443
            - --providers.kubernetescrd
            - --acme
            - --acme.dnschallenge
            - --acme.dnschallenge.provider=digitalocean
            - --acme.domains=*.foo.bar,foo.bar
            - --acme.email=bla@bla.biz
            - --acme.entrypoint=websecure
            - --acme.storage=/var/traefik/acme.json
          volumeMounts:
            - mountPath: /var/traefik
              name: traefik-volume
            - mountPath: /etc/traefik
              name: traefik-config
          env:
            - name: DO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digital-ocean
                  key: token
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /ping
              port: traefik
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: traefik
              scheme: HTTP
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: traefik
              containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: traefik-volume
          hostPath:
            path: /var/traefik
            type: DirectoryOrCreate
        - name: traefik-config
          configMap:
            name: traefik
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-only
  namespace: ingress
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adminroute
  namespace: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`foo.bar`)
      kind: Rule
      middlewares:
        - name: https-only
      services:
        - name: traefik
          port: 8080
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
ingress/traefik-hs9r5[traefik]: time="2019-05-07T18:51:20Z" level=error msg="error during instanciation of kubernetescrd.ingress/https-only: middleware does not exist" entryPointName=web routerName=kubernetescrd.ingress/adminroute-5cce5158af11ddf4f0a5
```

**Comment by ldez** [comment]
Hello,

you need to define the namespace:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adminroute
  namespace: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`foo.bar`)
      kind: Rule
      middlewares:
        - name: https-only
          namespace: ingress
      services:
        - name: traefik
          port: 8080
```

**Comment by sondabar** [comment]
That's not working either. :(

The RedirectScheme is not created in the right way as you can see in the output of /api/rawdata. It's missing the scheme and permanent attribute.
If i create the RedirectScheme for example with the file provider the output looks different and right.

**Comment by bill-within** [comment]
Just to +1 this: I'm experiencing something similar. It appears that none of the middlewares I create using custom resources are being correctly parsed, and they're not attached to the routers.

```
---
kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: testheader
  namespace: dev
spec:
  headers:
    CustomRequestHeaders:
      X-Script-Name: "test"
    CustomResponseHeaders:
      X-Custom-Response-Header: "True"
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: echo-dev
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`echo.foo`)
    kind: Rule
    services:
    - name: echo
      port: 80
      middlewares:
        - name: testheader
```

results in:

```
$ curl traefik-admin/api/rawdata
{
    "kubernetescrd": {
        "HTTP": {
            "routers": {
                "dev/echo-dev-b38f1c194cf0f67d05bc": {
                    "entryPoints": [
                        "web"
                    ],
                    "service": "dev/echo-dev-b38f1c194cf0f67d05bc",
                    "rule": "Host(`echo.foo`)"
                },
        ... snip ...
            },
            "middlewares": {
                "dev/testheader": {
                    "headers": {}
                }
            },
        ... snip ...
        },
        "TCP": {},
        "TLSOptions": null,
        "TLSStores": null
    }
}
```

with the same result if I add `namespace: dev` to the middlewares reference in the ingressroute.

**Comment by mpl** [comment]
Hi,

Just to be sure since you don't mention it in the config you pasted above, did you make sure to create and use the RBAC authorization for the middlewares as well (As it's done in https://docs.traefik.io/v2.0/user-guides/crd-acme/) ?

**Comment by bill-within** [comment]
@mpl I have indeed! Because the rawdata endpoint is showing the name of the middleware and knows that it's using the `headers` functionality, it seems like the error may be in parsing this bit:

```
    CustomRequestHeaders:
      X-Script-Name: "test"
    CustomResponseHeaders:
      X-Custom-Response-Header: "True"
```

Perhaps if this fails, then the middleware is not attached to the route. Just a guess though!
