### ISSUE TITLE
Can't reference a middleware from a different provider in IngressRoute 

### ISSUE THREAD

**Issue by sondabar** [containous/traefik#4855]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x ] No

### What did you do?

I wanted to do a work around issue #4854. There is a problem with using RedirectScheme and KubernetesCRD provider. So i tried to reference a RedirectScheme middleware from the file provider.

### What did you expect to see?

It's possible to reference the middleware from the IngressRoute with seeing the name with prefix file..

### What did you see instead?

It's not possible because the name of the middleware is prefixed with namespace. Setting the namespace attribute to empty string doesn't work either.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml
```toml
[HTTP]
  [HTTP.middlewares]
    [http.middlewares.tls-only.redirectscheme]
      scheme = "https"
```

Traefik Deployment
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
        - name: traefik
          image: traefik:v2.0.0-alpha4-alpine
          args:
            - --log.level=debug
            - --api
            - --ping
            - --accesslog
            - --entrypoints=Name:web Address::80
            - --entrypoints=Name:websecure Address::443
            - --providers.kubernetescrd
            - --providers.file.directory=/etc/traefik
            - --acme
            - --acme.dnschallenge
            - --acme.dnschallenge.provider=digitalocean
            - --acme.domains=*.foo.bar,foo.bar
            - --acme.email=foo@bar
            - --acme.entrypoint=websecure
            - --acme.storage=/var/traefik/acme.json
          volumeMounts:
            - mountPath: /var/traefik
              name: traefik-volume
            - mountPath: /etc/traefik
              name: traefik-config
          env:
            - name: DO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digital-ocean
                  key: token
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /ping
              port: traefik
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: traefik
              scheme: HTTP
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: traefik
              containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: traefik-volume
          hostPath:
            path: /var/traefik
            type: DirectoryOrCreate
        - name: traefik-config
          configMap:
            name: traefik
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adminroute
  namespace: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`admin.sondabar.de`)
      kind: Rule
      middlewares:
        - name: file.tls-only
      services:
        - name: traefik
          port: 8080
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
ingress/traefik-4h8rp[traefik]: time="2019-05-07T19:17:58Z" level=error msg="middleware \"ingress/file.tls-only\" does not exist" routerName=kubernetescrd.ingress/adminroute-5cce5158af11ddf4f0a5 entryPointName=web
```
