### ISSUE TITLE
tcp proxy  runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by roidelapluie** [containous/traefik#4856]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Use TCP Proxy to pass SSH traffic

### What did you expect to see?

it works

### What did you see instead?

after some time it does not work (see logs)

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.0.0-apha4

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[accessLog]

[ServersTransport]
  RootCAs = [ "/etc/tlscerts/ca.crt", "/etc/ssl/certs/ca-certificates.crt" ]

[entryPoints]
  [entryPoints.ssh]
    address = ":2222"
  [entryPoints.http]
    address = ":8080"
  [entryPoints.https]
    address = ":8443"

[providers.file]

[HTTP]
  [HTTP.Routers]
   [HTTP.Routers.http]
    Middlewares = ["HttpsRedirect"]
    EntryPoints = ["http", "https"]
    Rule = "PathPrefix(`/`)"
    Service = "empty"
   [HTTP.Routers.vault]
    Middlewares = ["BasicSecurity"]
    EntryPoints = ["https"]
    Rule = "Host(`vault.commands.example.be`)"
    Service = "vault"
    [HTTP.Routers.vault.tls]
   [HTTP.Routers.ci]
    Middlewares = ["BasicSecurity"]
    EntryPoints = ["https"]
    Rule = "Host(`ci.commands.example.be`)"
    Service = "ci"
    [HTTP.Routers.ci.tls]
   [HTTP.Routers.git]
    Middlewares = ["BasicSecurity"]
    EntryPoints = ["https"]
    Rule = "Host(`git.commands.example.be`)"
    Service = "git"
    [HTTP.Routers.git.tls]

  [HTTP.Middlewares.HttpsRedirect.RedirectScheme]
    Scheme = "https"
    Permanent = true

  [HTTP.Middlewares.BasicSecurity.Headers]
    STSSeconds = 31536000
    STSIncludeSubdomains = true
    STSPreload = true
    ForceSTSHeader = true
    FrameDeny = true
    ContentTypeNosniff = true

  [HTTP.Services]
    [HTTP.Services.vault]
    [HTTP.Services.vault.LoadBalancer]
       PassHostHeader = true
       [[HTTP.Services.vault.LoadBalancer.servers]]
        url = "https://vault.default.svc.cluster.local"
        weight = 1
    [HTTP.Services.ci]
    [HTTP.Services.ci.LoadBalancer]
       PassHostHeader = true
       [[HTTP.Services.ci.LoadBalancer.servers]]
          url = "http://jenkins.default.svc.cluster.local:8080"
          weight = 1
    [HTTP.Services.git]
    [HTTP.Services.git.LoadBalancer]
       PassHostHeader = true
       [[HTTP.Services.git.LoadBalancer.servers]]
          url = "https://gitlab.default.svc.cluster.local"
          weight = 1
    [HTTP.Services.empty]
       PassHostHeader = true
       [[HTTP.Services.empty.LoadBalancer.servers]]
          url = "https://none.default.svc.cluster.local"
          weight = 1

[TCP.Routers]
   [TCP.Routers.ssh]
    Rule = "HostSNI(`*`)"
    EntryPoints = ["ssh"]
    Service = "gitlab"

[TCP.Services]
  [TCP.Services.gitlab.LoadBalancer]
     [[TCP.Services.gitlab.LoadBalancer.servers]]
        Address = "gitlab.default.svc.cluster.local:22"

[[TLS]]
  Stores = ["default"]
  [TLS.Certificate]
    CertFile = "/etc/tlscerts/commands.crt"
    KeyFile = "/etc/tlscerts/commands.key"

[[TLS]]
  Stores = ["default"]
  [TLS.Certificate]
    CertFile = "/etc/tlscerts/www.crt"
    KeyFile = "/etc/tlscerts/www.key"


[TLSOptions]
  [TLSOptions.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
    ]


[TLSStores]
  [TLSStores.default]
    [TLSStores.default.DefaultCertificate]
    CertFile = "/etc/tlscerts/commands.crt"
    KeyFile = "/etc/tlscerts/commands.key"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-05-07T20:36:22Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2019-05-07T20:36:22Z" level=error msg="Stack: goroutine 6489 [running]:\nruntime/debug.Stack(0xc0000cc240, 0x1fd8c52, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/containous/traefik/pkg/safe.defaultRecoverGoroutine(0x1c9ab60, 0x3a09680)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:148 +0x9e\ngithub.com/containous/traefik/pkg/safe.GoWithRecover.func1.1(0x207e5c0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:139 +0x57\npanic(0x1c9ab60, 0x3a09680)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/containous/traefik/pkg/tcp.(*Proxy).ServeTCP(0x0, 0x23a9440, 0xc0004d6750)\n\t/go/src/github.com/containous/traefik/pkg/tcp/proxy.go:30 +0x115\ngithub.com/containous/traefik/pkg/tcp.(*RRLoadBalancer).ServeTCP(0xc000089800, 0x23a9440, 0xc0004d6750)\n\t/go/src/github.com/containous/traefik/pkg/tcp/rr_load_balancer.go:24 +0x53\ngithub.com/containous/traefik/pkg/tcp.(*Router).ServeTCP(0xc0008e5440, 0x23a93e0, 0xc000628080)\n\t/go/src/github.com/containous/traefik/pkg/tcp/router.go:35 +0x2c0\ngithub.com/containous/traefik/pkg/tcp.(*HandlerSwitcher).ServeTCP(0xc0003ab320, 0x23a93e0, 0xc000628080)\n\t/go/src/github.com/containous/traefik/pkg/tcp/switcher.go:19 +0x6c\ngithub.com/containous/traefik/pkg/server.(*TCPEntryPoint).startTCP.func1()\n\t/go/src/github.com/containous/traefik/pkg/server/server_entrypoint_tcp.go:108 +0xb4\ngithub.com/containous/traefik/pkg/safe.GoWithRecover.func1(0x207e5c0, 0xc000628060)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:142 +0x4d\ncreated by github.com/containous/traefik/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:136 +0x49\n"
time="2019-05-07T20:36:25Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2019-05-07T20:36:25Z" level=error msg="Stack: goroutine 6490 [running]:\nruntime/debug.Stack(0xc0000cc240, 0x1fd8c52, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/containous/traefik/pkg/safe.defaultRecoverGoroutine(0x1c9ab60, 0x3a09680)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:148 +0x9e\ngithub.com/containous/traefik/pkg/safe.GoWithRecover.func1.1(0x207e5c0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:139 +0x57\npanic(0x1c9ab60, 0x3a09680)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/containous/traefik/pkg/tcp.(*Proxy).ServeTCP(0x0, 0x23a9440, 0xc0004d71d0)\n\t/go/src/github.com/containous/traefik/pkg/tcp/proxy.go:30 +0x115\ngithub.com/containous/traefik/pkg/tcp.(*RRLoadBalancer).ServeTCP(0xc000089800, 0x23a9440, 0xc0004d71d0)\n\t/go/src/github.com/containous/traefik/pkg/tcp/rr_load_balancer.go:24 +0x53\ngithub.com/containous/traefik/pkg/tcp.(*Router).ServeTCP(0xc0008e5440, 0x23a93e0, 0xc0006280e0)\n\t/go/src/github.com/containous/traefik/pkg/tcp/router.go:35 +0x2c0\ngithub.com/containous/traefik/pkg/tcp.(*HandlerSwitcher).ServeTCP(0xc0003ab320, 0x23a93e0, 0xc0006280e0)\n\t/go/src/github.com/containous/traefik/pkg/tcp/switcher.go:19 +0x6c\ngithub.com/containous/traefik/pkg/server.(*TCPEntryPoint).startTCP.func1()\n\t/go/src/github.com/containous/traefik/pkg/server/server_entrypoint_tcp.go:108 +0xb4\ngithub.com/containous/traefik/pkg/safe.GoWithRecover.func1(0x207e5c0, 0xc0006280c0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:142 +0x4d\ncreated by github.com/containous/traefik/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:136 +0x49\n"
```
