### ISSUE TITLE
Traefik 2.0 verbosity in setting up HTTP to HTTPS redirects

### ISSUE THREAD

**Issue by torarnv** [containous/traefik#4863]
One thing that confused me a bit when trying to set up a 2.0 test was the verbosity of supporting both http and https but with redirects:

```yml
  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami_insecure.rule=Host(`whoami.domain.com`)"
      - "traefik.http.routers.whoami_insecure.middlewares=file.https-redirect"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain.com`)"
      - "traefik.http.routers.whoami.tls=true"
```

```toml
[EntryPoints]
  [EntryPoints.HTTP]
    address = ":80"

  [EntryPoints.HTTPS]
    address = ":443"

[Providers]
  [Providers.Docker]
    Watch = true
    ExposedByDefault = false

  [Providers.File]

[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"
```

With the current syntax I'd have to repeat that _insecure route for each service. It would be nice if there was a way to statically configure that as a default in traefik.toml, similar to the old way of adding a redirect to an entrypoint.

Thanks!

**Comment by torarnv** [comment]
An attempt to solve this by a catch-all static route did not seem to work, but would perhaps be an option:
```

[http.services]
  [http.services.dummy.LoadBalancer]
     [[http.services.dummy.LoadBalancer.servers]]
        url = "localhost"

[http.routers]
  [http.routers.https-redirect]
  rule = "Host(`*`)"
  middlewares = ["https-redirect"]
  service = "dummy"

[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"
```
Similar to the "Forwarding all (non-tls) requests on port 3306 to a database service" example here https://docs.traefik.io/v2.0/routing/routers/

**Comment by thebetterjort** [comment]
Have you been able to get TLS store going with 2.0?

**Comment by torarnv** [comment]
Yes, with ACME

**Comment by stkac** [comment]
Hi, have the same issue...

**Comment by torarnv** [comment]
@stkac Use the config I posted in https://github.com/containous/traefik/issues/4863#issue-442458019

**Comment by stkac** [comment]
> @stkac Use the config I posted in [#4863 (comment)](https://github.com/containous/traefik/issues/4863#issue-442458019)

@torarnv it works! thanks
@torarnv @ldez Traefik v2.0 seems to be more complex in that sense but don't get info or real example like @torarnv on the official documentation site...

![image](https://user-images.githubusercontent.com/41887474/57541176-b7372a80-734e-11e9-87ba-834aff69e3cf.png)

**Comment by torarnv** [comment]
@stkac It's in alpha state, so lack of documentation is understandable 😃

**Comment by stkac** [comment]
> @stkac It's in alpha state, so lack of documentation is understandable
Agree with you, I really like traefik and spent all day trying to make it work until found your solution, great work @torarnv @ldez :100:

**Comment by torarnv** [comment]
I noticed you edited my comment from earlier @ldez and this seems to actually work:

```toml
[http.routers]
  [http.routers.https-redirect]
  rule = "HostRegexp(`{any:.*}`)"
  middlewares = ["https-redirect"]
  service = "dummy"

[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"

[http.services]
  [http.services.dummy.LoadBalancer]
     [[http.services.dummy.LoadBalancer.servers]]
        url = ""
```

Thanks!! 😄 

Is `url = ""` safe here for the dummy service?

**Comment by Tiger-zzZ** [comment]
How can i start swarmmode use traefik2.0 , when i use command  `curl -H Host:whoami.docker.localhost localhost`, it's not running

**Comment by apollo13** [comment]
@torarnv how does that play together with other services discovered for instance from docker? If they define a more specific regex/rule, wouldn't that override that router (I guess the main question here is how routers are evaluated and whether they have priorities or not)?

**Comment by denysvitali** [comment]
I'm wondering what's the k8s equivalent of @torarnv's file provider configuration. Obviously there is still no documentation about it, but I can confirm that performing an http -> https redirect for all the hosts is ultra-verbose in Traefik 2.0 (RC)

**Comment by Yivan** [comment]
Hi ! I confirm too this is too much verbose, especially in case of specific port... You cannot even create a generic middleware as redirection is done on 443 if "port" option is not specified.
**It should keep the same port as the original one.**

It ends to something like that (PORTAINER_PORT is 9543 for instance here):
```
- "traefik.http.routers.portainer-http.entrypoints=portainer"
- "traefik.http.routers.portainer-https.entrypoints=portainer"
- "traefik.http.routers.portainer-https.tls=true"
- "traefik.http.routers.portainer-http.middlewares=portainer-redirectscheme@docker"
- "traefik.http.routers.portainer-http.rule=Host(`portainer.${COMPOSE_PROJECT_ENV}.${BASE_DOMAIN}`)"
- "traefik.http.routers.portainer-https.rule=Host(`portainer.${COMPOSE_PROJECT_ENV}.${BASE_DOMAIN}`)"
- "traefik.http.middlewares.portainer-redirectscheme.redirectscheme.scheme=https"
- "traefik.http.middlewares.portainer-redirectscheme.redirectscheme.permanent=true"
- "traefik.http.middlewares.portainer-redirectscheme.redirectscheme.port=${PORTAINER_PORT}"
```

Same in V1:
```
- "traefik.frontend.entryPoints=portainer"
- "traefik.frontend.rule=Host:portainer.${COMPOSE_PROJECT_ENV}.${BASE_DOMAIN}"
- "traefik.frontend.headers.SSLRedirect=true"
```

We have some dockerfile with several services, all those labels in V2 will make them pretty diffult to read.

**Comment by HubbeKing** [comment]
With the way middlewares work in traefik 2.0, I think the ideal solution would be to have some kind of `defaultMiddlewares` setting in the config file.

That way, you could define an HTTPS redirection middleware once, and tell traefik that every router should use that middleware.
Then override it per-router as necessary.

Something like this:
`[global]`
`defaultMiddlewares = ["redirect"]`

`[entryPoints.web]`
`address = ":80"`

`[entryPoints.web-secure]`
`  address = ":443"`

`[http.middlewares]`
`  [http.middlewares.redirect.redirectScheme]`
`    scheme = "https"`

Because honestly, manually adding labels to refer to the redirection middleware on EVERY service is a bit crazy, considering that with LetsEncrypt support there's essentially no reason to NOT do HTTPS redirection in traefik 1.7

**Comment by vtempest** [comment]
```
	image: traefik:v2.0-alpine
    command:
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--global.sendAnonymousUsage=false"
      - "--certificatesresolvers.ssl.acme.httpchallenge=true"
      - "--certificatesresolvers.ssl.acme.httpchallenge.entrypoint=http"


	...



	labels:
      traefik.http.routers.code.rule: Host(`team.${DOMAIN}`)
      traefik.http.routers.code.entrypoints: http
      traefik.http.routers.code.middlewares: redirect
      traefik.http.middlewares.redirect.redirectscheme.scheme: https
      traefik.http.routers.code2.rule: Host(`team.${DOMAIN}`)
      traefik.http.routers.code2.entrypoints: https
      traefik.http.routers.code2.tls.certresolver: ssl



	
```

**Comment by lumir-mrkva** [comment]
you don't have to set it with every service, all you need to do is to set the middleware with the 1st one and rule `HostRegexp(`{any:.*}`)` - that will match every http request

**Comment by reisholmes** [comment]
@lumir-mrkva Do you have a complete example of how it would look?  I'm still quite confused as to which setup is most practical.

**Comment by ldez** [comment]
https://community.containo.us/t/global-http-to-https-redirect-in-v2/1658/3

**Comment by Sarke** [comment]
I would like to submit a proposal that is similar to this, but slightly different solution.  If it's too different let me know and I will open a new issue.

I propose that we add **router options to the entrypoints** that will act as the default router options, unless they are specified by the router in which case those take precedence.

The big complaint is that the v2 config is too verbose for simple tasks.  Specifying default options for the entrypoints would solve:

1. **Simpler HTTP to HTTPS redirect**.  E.g. setting a redirect middleware on the HTTP entrypoint.  That is, this issue.

2. **Combined HTTP and HTTPS routers** would be possible.  For example, I just added this config (which sparked me to make this comment):

```toml
[http.routers."mydomain.com redirect"]
  rule = "Host(`mydomain.com`, `www.mydomain.com`)"
  entryPoints = ["web"]
  priority = 100
  middlewares = ["mydomain-redirect"]
  service = "noop@file"

[http.routers."mydomain.com ssl-redirect"]
  rule = "Host(`mydomain.com`, `www.mydomain.com`)"
  entryPoints = ["websecure"]
  priority = 100
  middlewares = ["mydomain-redirect"]
  service = "noop@file"
  [http.routers."mydomain.com".tls]
```

I can't think of a good reason why these need to be in different routers.

It is the exact same router, other that the HTTPS one has TLS enabled. This doesn't directly deal with HTTP to HTTPS redirect that this issue covers, but many of the issues that raise that concern are marked as duplicates of this issue (e.g. #5183, #5275, #5506 ). 

Having the ability to set router options on the entry point level could solve both of these common scenarios.

---

I see now that my proposal is very similar to this one (https://github.com/containous/traefik/issues/4863#issuecomment-532754911) that @HubbeKing posted above.  The two proposals are compatible, as being able to set default router options would include settings default middleware, bt would also allow setting the TLS option (amongst other things) which would solve the second scenario I posted above.

**Comment by Sarke** [comment]
Actually, YAML already sort of supports this using anchors:

```yaml

x-defaults:
  mydomaincom: &mydomaincom
    rule: 'Host(`mydomain.com`, `www.mydomain.com`)'
    priority: 100
    middlewares: [mydomain-redirect]
    service: noop@file

http:
  routers:
    mydomain.com redirect:
      <<: *mydomaincom
      entryPoints: [web]
    mydomain.com ssl-redirect:
      <<: *mydomaincom
      entryPoints: [websecure]
      tls: {}
```

It can't merge arrays, but it's a start.

**Comment by xanderflood** [comment]
@Sarke YAML functionality is all fine and dandy as a workaround if you're using YAML, but it doesn't buy you anything for most of the dynamic config providers, e.g. Kubernetes or Docker labels

**Comment by Sarke** [comment]
@xanderflood Yes, YAML will only work if you're using YAML.  I'm only offering it as an alternative as something that is available now.

And you can use it with a dynamic config: https://docs.traefik.io/providers/file/#watch

**Comment by FuNK3Y** [comment]
I was also surprised by the verbosity needed for such a common use case. My proposal here would be to add an additional directive to the tls: redirect

If set to true, the router should do the redirection instead of ignoring non TLS traffic. That way several endpoint can be added to the router (or just all endpoints - as in my sample)
```TOML
[http.routers.someservice]
  rule = "Host(`mydomain.com`, `www.mydomain.com`)"
  priority = 100
  middlewares = ["mydomain-redirect"]
  service = "someservice"
  [http.routers."mydomain.com".tls]
  redirect = true
```
The only drawback that I can foresee right now is that precedence with the redirect middleware would need to be clearly defined. I'd naively suggest that the one in TLS should take precedence. Nevertheless having this & RedirectScheme setup on the same router should work just fine

**Comment by eclipticrick** [comment]
> An attempt to solve this by a catch-all static route did not seem to work, but would perhaps be an option:
> 
> ```toml
> [http.routers]
>   [http.routers.https-redirect]
>   rule = "HostRegexp(`{any:.*}`)"
>   middlewares = ["https-redirect"]
>   service = "dummy"
> 
> [http.middlewares]
>   [http.middlewares.https-redirect.redirectscheme]
>     scheme = "https"
> 
> [http.services]
>   [http.services.dummy.LoadBalancer]
>      [[http.services.dummy.LoadBalancer.servers]]
>         url = "localhost"
> ```
> 
> Similar to the "Forwarding all (non-tls) requests on port 3306 to a database service" example here https://docs.traefik.io/v2.0/routing/routers/
> 
> Ideally without the dummy service.

Thanks!! :smile: 

I've used the following to make it work without the dummy service:

(file provider toml)
```toml
[http.middlewares]
  [http.middlewares.HTTPS-REDIRECT.redirectScheme]
    scheme = "https"
```
(traefiks docker-compose file)
```yaml
      - traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)
      - traefik.http.routers.https-redirect.middlewares=HTTPS-REDIRECT@file
      - traefik.http.routers.https-redirect.service=api@internal
```

**Comment by CuBiC3D** [comment]
If you are using a dynamic provider, there is no need to define a middleware in file provider.

I'm using docker with the following labels on traefik:
```
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_public"
      - "traefik.http.routers.https-redirect.entrypoints=http"
      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
```
This creates the redirect middleware and redirects all http requests to https. No dummy service required since docker provider generates service definitions for containers.

Containers using traefik have something like that:
```
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_public"
      - "traefik.http.routers.my-app.entrypoints=https"
      - "traefik.http.routers.my-app.rule=Host(`my-app.example.com`)"
      - "traefik.http.routers.my-app.tls.certresolver=default"
```

**Comment by gaui** [comment]
@CuBiC3D cool but the file provider way works also with Kubernetes.

**Comment by appleboy** [comment]
The only way I think to redirect HTTP to HTTPS in file provider as followings for single service:

```toml
[http.routers]
  [http.routers.to-prometheus]
  rule = "Host(`prometheus.example.com`)"
  middlewares = ["https-redirect"]
  entrypoints = ["web"]
  service = "prometheus"

  [http.routers.to-prometheus-ssl]
  rule = "Host(`prometheus.example.com`)"
  entrypoints = ["web-secure"]
  service = "prometheus"
    [http.routers.to-prometheus-ssl.tls]
      certResolver = "sample"
```

**Comment by GustavoAmerico** [comment]
It's worked for me.

```YAML
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-to-https 
  namespace: traefik
spec:
  entryPoints:
    - http # The entrypoint name for port 80 (no secure)
  routes:
    - match: Host(`*`)
      kind: Rule 
      services:
        - name: traefik #any service in the namespace
          port: 80  
      middlewares:
        - name: redirect-https
          namespace: traefik #case the Middleware has distinct namespace

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware 
metadata:
  name: redirect-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: "true"
    port: 443
`''

**Comment by xanderflood** [comment]
Here's the approach I used:

In my static config:
```
[providers]
  [providers.file]
    watch = true
    filename = "${dynamic_toml_path}"
```

In the dynamic file config:
```
[http]
  # Add the router
  [http.routers]
    [http.routers.http-to-https]
      entryPoints = ["web"]
      middlewares = ["redirect-to-https"]
      rule = "HostRegexp(`{host:.+}`)"

      # Every router needs a service, even if it routes all its
      # traffic elsewhere
      service = "noop"

  [http.middlewares]
    [http.middlewares.redirect-to-https.redirectScheme]
      scheme = "https"

  [http.services]
    # noop service, the URL will be never called
    [http.services.noop.loadBalancer]
      [[http.services.noop.loadBalancer.servers]]
        url = "http://192.168.0.1"
```

Then use whichever other provider you like to provision real services, and those services only need to listen to your HTTPS entrypoint.

**Comment by cupcakearmy** [comment]
```
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305

certificatesResolvers:
  le:
    acme:
      KeyType: RSA4096
      email: hi@nicco.io
      storage: acme.json
      httpChallenge:
        entryPoint: http

middlewares:
  redirect-to-https:
    redirectsheme:
      scheme: "https"

routers:
  redirs:
    rule: "hostregexp(`{host:.+}`)" 
    entrypoint: "web"
    middlewares: "redirect-to-https"
```

I can't get the global redirect to work. Any suggestions?

**Comment by xanderflood** [comment]
@cupcakearmy not sure if this is your issue but all routers need to have a service. Your redirect router will never access it's service, since it routes all traffic elsewhere, but it still needs to have one

**Comment by expelledboy** [comment]
For anyone having issues using the RedirectScheme middleware, be aware that `--providers.docker.exposedbydefault=false` would require that you include `- traefik.enable=true` as a label for traefik to actually pick up the configuration. That took me way too long to figure out..

Here is the complete working solution using only a `docker-compose.yml` file, including a working web service. Its not that verbose imho, and this is a complete drop-in replacement for `jwilder/nginx-proxy` that supports multiple ports per container 🙌 Thank you guys!!

```yml
version: '3'

services:

  reverse-proxy:
    image: traefik:v2.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-acme:/etc/traefik/acme
    command:
      # Enabling docker provider.
      - --providers.docker=true
      # Define entrypoints.
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      # Do not expose containers unless explicitly told so.
      - --providers.docker.exposedbydefault=false
      # Use letsencrypt for https.
      - --certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.le.acme.email=${ADMIN_EMAIL}
      - --certificatesResolvers.le.acme.storage=acme.json
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=http
      - --certificatesResolvers.le.acme.tlsChallenge=true
    labels:
      # Force https everywhere.
      - traefik.enable=true
      - traefik.http.routers.https-redirect.entrypoints=http
      - traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)
      - traefik.http.routers.https-redirect.middlewares=https-only
      - traefik.http.middlewares.https-only.redirectscheme.scheme=https

  whoami:
    image: containous/whoami
    labels:
      # Explicitly tell Traefik to expose this container.
      - traefik.enable=true
      # The domain the service will respond to.
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
      # Use letsencrypt for https.
      - traefik.http.routers.whoami.tls.certresolver=le

networks:

  default:
    external:
      name: reverse-proxy

volumes:

  traefik-acme:
    external: true
```
