### ISSUE TITLE
[Docker] No IP in backend in host networking mode

### ISSUE THREAD

**Issue by Kernald** [containous/traefik#487]
I have a Docker machine set up to use the `host` network mode. Here's the `docker-compose` entry:
```
hass:
  image: 'homeassistant/home-assistant'
  restart: always
  net: 'host'
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/srv/hass/config:/config'
  labels:
    - "traefik.backend=hass"
    - "traefik.frontend.rule=Host:home.redacted.net"
    - "traefik.port=8123"
```

When traefik picks it, the backend's URL is set to `http://:8123`, the IP is missing. Is there any other solution than skipping this docker machine (`traefik.enable=false`) and adding it from somewhere else? A missing label I could hint traefik with?
