### ISSUE TITLE
[Kubernetes] Can't visit backend service, if backend used router HASH

### ISSUE THREAD

**Issue by xiak** [containous/traefik#4871]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- No

### What did you do?
In my k8s cluster, I want to visit the ceph service via https://test.local/ceph, but failed with error 

### What did you expect to see?
I can visit ceph service via https://test.local/ceph

### What did you see instead?
Open the browser console, I can see some error:

Refused to apply style from 'https://test.local/styles.f60c3133717be9029c60.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled

This issue may caused by the ceph dashboard using HASH router, so, the default URL is:
https://xxx/#/login not https://xxx/login

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

This is my Ingress file
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ceph
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: test.local
    http:
      paths:
      - path: /ceph
        backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: 8443
```

I can visit styles.f60c3133717be9029c60.css via URL: https://test.local/ceph/styles.f60c3133717be9029c60.css

But not https://test.local/styles.f60c3133717be9029c60.css

I try to modify Ingress file
from 
```
paths:
      - path: /ceph
```
to 
```
paths:
      - path: /ceph/
```

It works with visiting URI: https://test.local/ceph/

The browser will redirect to https://test.local/ceph/#/login
