### ISSUE TITLE
Traefik unable to route in fargate

### ISSUE THREAD

**Issue by santanu33** [containous/traefik#4879]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Trying to call backend system, hosted on ECS Fargate as same cluster as Traefik

### What did you expect to see?

http://mycompany.domain/api => returns 200 with api description
http://mycompany.domain/dashboard/ => returns dashboard with my backend system

![image](https://user-images.githubusercontent.com/34623133/57806098-bb07ea00-775e-11e9-82b4-dfb9bb4a992a.png)

http://mycompany.domain/foo => should route the request to backend system
### What did you see instead?

http://mycompany.domain/foo => 404 page not found

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.11-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
logLevel = "DEBUG"
watch = true
[accessLog]
    format = "json"

    [accessLog.fields.headers]
      defaultMode = "drop"
      [accessLog.fields.headers.names]
        "Accept" = "keep"
        "Accept-Encoding" = "keep"
        "Accept-Language" = "keep"
        "Referer" = "keep"
        "User-Agent" = "keep"
        "Cache-Control" = "keep"
        "Content-Encoding" = "keep"
        "Content-Type" = "keep"
        "X-Trace-Id" = "keep"

[traefikLog]
    format = "json"

[entryPoints]
    [entryPoints.http]
    address = ":80"

[ecs]
clusters = ["test-traefik"]
watch = true
autoDiscoverClusters = true
refreshSeconds = 15
exposedByDefault = true
region = "eu-central-1"
domain="mycompany.domain"
```
**BackendTaskDefinition**
```
[
    {
        "name": "middleware",
        "image": "backendImage:latest",
        "essential": true,
        "portMappings": [
            {
                "hostPort": 8181,
                "containerPort": 8181
            }
        ],
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-region": "eu-central-1",
                "awslogs-group": "/ecs/middleware",
                "awslogs-stream-prefix": "middleware"
            }
        },
        "dockerLabels": {
            "traefik.backend": "middleware",
            "traefik.enable": "true",
            "traefik.frontend.rule": "PathPrefix:/foo",
            "traefik.frontend.entryPoints": "http",
            "traefik.backend.healthcheck.path": "/actuator/health",
            "traefik.backend.healthcheck.interval": "30s"
        },
        "healthCheck":
        {
            "command" : ["CMD-SHELL", "curl -f localhost:8181/actuator/health"],
            "interval" : 15,
            "timeout" : 30,
            "retries" : 3,
            "startPeriod" : 10
        }
    }
]

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{
    "level": "debug",
    "msg": "Found cached task definition for arn:aws:ecs:eu-central-1:...:task/pp-fra-traefik/....... Skipping the call",
    "time": "2019-05-15T19:57:21Z"
}
{
    "level": "debug",
    "msg": "originLabelsmap[domain:.... traefik.backend:traefik traefik.enable:true]",
    "time": "2019-05-15T19:57:21Z"
}
{
    "level": "debug",
    "msg": "allLabelsmap[:map[traefik.backend:traefik traefik.enable:true]]",
    "time": "2019-05-15T19:57:21Z"
}
{
    "level": "debug",
    "msg": "originLabelsmap[traefik.backend.healthcheck.path:/actuator/health traefik.enable:true traefik.frontend.entryPoints:http traefik.frontend.rule:PathPrefix:/foo traefik.backend:middleware traefik.backend.healthcheck.interval:30s]",
    "time": "2019-05-15T19:57:21Z"
}
{
    "level": "debug",
    "msg": "allLabelsmap[:map[traefik.frontend.rule:PathPrefix:/foo traefik.backend:middleware traefik.backend.healthcheck.interval:30s traefik.backend.healthcheck.path:/actuator/health traefik.enable:true traefik.frontend.entryPoints:http]]",
    "time": "2019-05-15T19:57:21Z"
}
{
    "level": "debug",
    "msg": "Backend backend-traefik: no load-balancer defined, fallback to 'wrr' method",
    "time": "2019-05-15T19:57:21Z"
}
{
    "level": "debug",
    "msg": "Backend backend-middleware: no load-balancer defined, fallback to 'wrr' method",
    "time": "2019-05-15T19:57:21Z"
}
{
    "BackendAddr": "",
    "BackendName": "Traefik",
    "BackendURL": {
        "Scheme": "",
        "Opaque": "",
        "User": null,
        "Host": "",
        "Path": "/foo/",
        "RawPath": "",
        "ForceQuery": false,
        "RawQuery": "",
        "Fragment": ""
    },
    "ClientUsername": "-",
    "DownstreamContentSize": 19,
    "DownstreamStatus": 404,
    "DownstreamStatusLine": "404 Not Found",
    "Duration": 90627,
    "FrontendName": "backend not found",
    "OriginContentSize": 19,
    "OriginDuration": 22925,
    "OriginStatus": 404,
    "OriginStatusLine": "404 Not Found",
    "Overhead": 67702,
    "RequestAddr": "mycompany.domain",
    "RequestContentSize": 0,
    "RequestCount": 8,
    "RequestHost": "mycompany.domain",
    "RequestLine": "GET /foo/ HTTP/1.1",
    "RequestMethod": "GET",
    "RequestPath": "/foo/",
    ...
}
```
