### ISSUE TITLE
failed to load X509 key pair while using self-signed certificate

### ISSUE THREAD

**Issue by MyFlower** [containous/traefik#4883]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I created a self-signed certificate using
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert.key -out cert.crt` and added it to the traefik.toml. 

### What did you expect to see?
Website with my self-signed certificate.

### What did you see instead?
An error message
`level=error msg="failed to load X509 key pair: tls: failed to find any PEM data in certificate input"`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```docker run traefik traefik version
Version:      v1.7.11
Codename:     maroilles
Go version:   go1.11.9
Built:        2019-04-26_08:42:33AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I'm running a Docker `Docker version 18.09.6, build 481bc77` with Docker-compose `docker-compose version 1.24.0, build 0aa59064`.

traefik.toml
```toml
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true

  [entryPoints.https]
    address = ":443"
    compress = true
  [entryPoints.https.tls]

  [entryPoints.administration]
    address = ":1234"
    compress = true
    [entryPoints.administration.tls]
    [[entryPoints.http.tls.certificates]]
        certFile = "/certificates/cert.crt"
        keyFile = "/certificates/cert.key"

[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "docker.domain.tld"
  watch = true
  exposedByDefault = false
  network = "traefik"

[acme]
  email = "email"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
```

docker-compose.yml
```
version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    command: --docker
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1234:1234
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /config/traefik/traefik.toml:/traefik.toml:ro
      - /data/certs/acme.json:/acme.json:rw
    container_name: MAIN_TRAEFIK

  foo:
    build: ./foo
    restart: always
    container_name: FOO
    expose:
      - 3382
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:foo.${ROOT_DOMAIN}
      - traefik.port=1234
      - traefik.frontend.entryPoints=administration

networks:
  traefik:
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
MAIN_TRAEFIK       | time="2019-05-16T22:37:33+02:00" level=error msg="failed to load X509 key pair: tls: failed to find any PEM data in certificate input"
```

**Comment by ldez** [comment]
Hello,

Your certificates need to be mount inside the Traefik container.

```
services:
  traefik:
    image: traefik:1.7-alpine
    command: --docker
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1234:1234
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /config/traefik/traefik.toml:/traefik.toml:ro
      - /data/certs/acme.json:/acme.json:rw
      - /config/certificates:/certificates:ro " <-----
    container_name: MAIN_TRAEFIK
```
