### ISSUE TITLE
ClientAddr does not correspond to Client IP when proxy protocol enabled

### ISSUE THREAD

**Issue by esierrapena** [containous/traefik#4892]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

 ELB AWS (proxy protocol enabled via annotation service.beta.kubernetes.io/aws-load-balancer-proxy-protocol=*) --> Ingress controller Traefik (proxy protocol enabled via trustedIPs in [entryPoints] in toml). 

Checking with tcpdump command in traefik pods, we can see that proxy protocol header is propagated as expected: ```...6..cTCP4 91.XXX.XXX.XXXX 10.41.XXX.XXX 33668 443``` but when we check traefik logs in ClientAddr we see the internal elb ip not the client real one:```{"BackendAddr":"XXX.XXX.XXX.XXX:8000","BackendName":"XXX.XXX.XXX.XXX","BackendURL":{"Scheme":"http","Opaque":"","User":null,"Host":"XXX.XXX.XXX.XXX:8000","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"ClientAddr":"10.41.XXX.XXX:61714","ClientHost":"10.41.XXX.XXX","ClientPort":"61714","ClientUsername":"-","DownstreamContentSize":108,"DownstreamStatus":202,"DownstreamStatusLine":"202 Accepted","Duration":6529152,"FrontendName":"XXXXXXXXXX","OriginContentSize":108,"OriginDuration":6397011,"OriginStatus":202,"OriginStatusLine":"202 Accepted","Overhead":132141,"RequestAddr":"XXXXXXXXXXX","RequestContentSize":176,"RequestCount":20681965,"RequestHost":"XXXXXXXX","RequestLine":"POST /ob-events/v2/invoice-payment-due HTTP/1.1","RequestMethod":"POST","RequestPath":"/ob-events/v2/invoice-payment-due","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2019-05-20T08:15:29.727365143Z","StartUTC":"2019-05-20T08:15:29.727365143Z","downstream_Access-Control-Allow-Credentials":"true","downstream_Access-Control-Allow-Origin":"https://XXXXXXXXXXXXXXXX"...```

### What is your environment & configuration (arguments, toml, provider, platform, ...)? K8s with kops in AWS

```toml
checkNewVersion = false
maxIdleConnsPerHost = 1024
defaultEntryPoints = [ "http", "https" ]
logLevel = "INFO"

[traefikLog]
  format = "json"

[accessLog]
  format = "json"
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "Authorization" = "drop"

[entryPoints]
  [entryPoints.http]
    address = "[::]:80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.http.proxyProtocol]
      trustedIPs = ["10.41.0.0/22"]
  [entryPoints.https]
    address = "[::]:443"
    [entryPoints.https.tls]
      MinVersion = "VersionTLS11"
      CipherSuites = ["TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384"]
      trustedIPs = ["10.41.0.0/22"]

[kubernetes]
namespaces = ["xxxxxx", "xxxxxx"]

[api]
  dashboard = true

[metrics]
  [metrics.statistics]
    RecentErrors = 50
  [metrics.prometheus]
    Buckets=[0.1, 0.3, 1.2, 5.0]

[acme]
email = "XXXXXXXX"
storage = "traefik/acme/account"
acmeLogging = true
entryPoint = "https"
onHostRule = false


[acme.dnsChallenge]
  provider = "route53"
        delayBeforeCheck = 15

[[acme.domains]]
  main = "XXXXXXXXXXXX"

[consul]
endpoint = "consul:8500"
watch = true
```
