### ISSUE TITLE
Priorities and rule matching doesn't work as documented with docker-compose

### ISSUE THREAD

**Issue by firatoezcan** [containous/traefik#4895]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?
I created a network with `docker network create proxy --attachable --label="traefik"` and ran the traefik container via `docker run -d -p 80:80 -p 443:443 -v /var/run/docker.sock:/var/run/docker.sock --network proxy --name traefik traefik --docker`

After that I ran my docker-compose command with this file:
```
version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/DockerfileFrontend
    restart: always
    networks: 
      - proxy
      - internal
    labels:
      - traefik.frontend.rule=Host:app.mydomain.net;PathPrefixStrip:/
      - traefik.frontend.priority=10
      - traefik.port=3000
      - traefik.docker.network=proxy
      - traefik.enable=true

  admin:
    build:
      context: ./admin
      dockerfile: ../docker/DockerfileFrontend
    restart: always
    networks: 
      - proxy
      - internal
    labels:
      - traefik.frontend.rule=Host:app.mydomain.net;PathPrefixStrip:/admin
      - traefik.frontend.priority=100
      - traefik.port=3000
      - traefik.docker.network=proxy
      - traefik.enable=true
      
networks:
  proxy:
    external: true
  internal:
    external: false
```

### What did you expect to see?
That `app.mydomain.net` is served by my frontend container and that `app.mydomain.net/admin` is served by my admin container.
This should work without priorities anyways since the first rule is shorter than the second rule

### What did you see instead?

Both routes are served by the frontend container

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.11
Codename:     maroilles
Go version:   go1.11.9
Built:        2019-04-26_08:42:33AM
OS/Arch:      linux/amd6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No further configuration other than the default
