### ISSUE TITLE
Traefik does not see containers on worker node

### ISSUE THREAD

**Issue by atomicus** [containous/traefik#4903]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x ] No

### What did you do?

I've set a swarm with:
* 1 manager
* 1 worker

Treafik is working on magnager
Service is working on both manager & worker, replicated.

Which is done in following docker-compose:
```
services:
  traefik:
    image: traefik
    command: --api --docker 
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik_cfg_v15
        target: /etc/traefik/traefik.toml
      - source: sll_key_v4
        target: /etc/traefik/ssl-key.key
      - source: sll_cert_v4
        target: /etc/traefik/ssl-cert.crt
    networks:
      - internal_network
    deploy:
      replicas: 1 #tmp
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints: [node.role == manager]

  iframe:
    image:                         xxxx
    networks:
      - internal_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=ils_internal_network
      - traefik.backend=iframe
      - traefik.frontend.backend=iframe
      - traefik.port=80
      - traefik.frontend.rule=Host:games.xxx.com
      - traefik.basic.protocol=http
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 60s 
      placement:
        constraints: [node.platform.os == linux]
networks:
  agent_network:
    driver: overlay
    attachable: true
    
  internal_network:
    driver: overlay
    attachable: true
```
### What did you expect to see?
4 frontends and 4 backends

### What did you see instead?
2 frontend & 2 backends, only one working on manager

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.11
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
logLevel = "debug"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [[entryPoints.https.tls.certificates]]
  certFile = "/etc/traefik/ssl-cert.crt"
  keyFile = "/etc/traefik/ssl-key.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "xxx.com"
watch = true
network = "web_network"
swarmMode = true
exposedByDefault = false


[accessLog]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Debug log does not say a single world about containers numbered 1 &3 which are spawned on worker node. No error messages, all looks ok, except this which is not as in configuration (i've checked contents of file on container disk, it's correct
```

time="2019-05-23T20:32:12Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"```
