### ISSUE TITLE
ERROR: Port is missing

### ISSUE THREAD

**Issue by vinistig** [containous/traefik#4913]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
Trying to configure my application at traefik v2.0.0-alpha4

### What did you expect to see?
No errors, and the container successfully registered to the traefik

### What did you see instead?
Port is missing error

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2.0.0-alpha4
```
/ $ ./traefik version
Version:      01b916eaa07e20b1b2cb324de592fa340e9f6c13
Codename:     cheddar
Go version:   go1.12.4
Built:        2019-05-27_08:18:11PM
OS/Arch:      linux/amd64
```

#### traekif.toml
```toml
[Global]                                                                                                                                                                                          
  Debug = true                                                                                                                                                                                    
  SendAnonymousUsage = false                                                                                                                                                                      
  LogLevel = "DEBUG"                                                                                                                                                                              
[Log]                                                                                                                                                                                             
  Level = "DEBUG"                                                                                                                                                                                 
defaultEntryPoints = ["http"]                                                                                                                                                                     
[EntryPoints]                                                                                                                                                                                     
  [EntryPoints.web]                                                                                                                                                                               
    Address = ":8080"                                                                                                                                                                             
    [EntryPoints.http.auth.foundation]                                                                                                                                                            
[Providers]                                                                                                                                                                                       
  [Providers.Docker]                                                                                                                                                                              
    Endpoint = "unix:///var/run/docker.sock"                                                                                                                                                      
    SwarmMode = true                                                                                                                                                                              
[Web]                                                                                                                                                                                             
  Address = ":8081"                                                                                                                                                                               
watch = true   
```
#### container service spec labels (via golang docker cli)

```
"traefik.backend":            "some-service",
"traefik.port":               "8000",
"traefik.frontend.rule":      "PathPrefixStrip: /somePath",
"traefik.frontend.protected": "false",
"traefik.docker.network":     "foundation-network",
"traefik.enable":             "true",
"traefik.docker.lbswarm":     "true",
```

### Traefik logs in DEBUG level
```
time="2019-05-27T20:28:35Z" level=error msg="port is missing" providerName=docker container=foundation-supervisor-5om7impg0ttjlagznepkut9t8

time="2019-05-27T20:28:35Z" level=error msg="port is missing" container=foundation-proxy-whjrwdou05zckpvc832uxpd8a providerName=docker

time="2019-05-27T20:28:35Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker

time="2019-05-27T20:28:35Z" level=info msg="Skipping same configuration for provider docker" providerName=docker

```
