### ISSUE TITLE
Parts of site "refused to connect"

### ISSUE THREAD

**Issue by kennyparsons** [containous/traefik#4921]
Various containers have this issue, and it appears to affect pop-ups, iframes, etc: "sub.domain.com refused to connect"
Screenshot here: https://pasteboard.co/Ih0hI6j.png

I am using V1.7.11 via docker. 

My toml is below. How can I fix this issue?

```toml
#debug = true

logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true
defaultEntryPoints = ["https", "http"]

[traefikLog]
  filePath = "/etc/traefik/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/etc/traefik/access.log"
  format = "json"

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"
  usersFile = "/shared/.htpasswd"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "myemail@gmail.com" #any email id will work
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true
onDemand = false #create certificate when container is created
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
[[acme.domains]]
   main = "domain.com"
[[acme.domains]]
   main = "*.comain.com"
[[acme.domains]]
   main = "*.files.domain.com"
[[acme.domains]]
   main = "*.transmission.domain.com"
# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.com"
watch = true
# This will hide all docker containers that don't have explicitly
# set label to "enable"
exposedbydefault = false
```
