### ISSUE TITLE
Cannot create SSL certificates on sub domains.

### ISSUE THREAD

**Issue by CrashyBang** [containous/traefik#4922]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I have been trying to get sub domains working with SSL and Cloudflare, I am using an Unraid box and I want to setup the docker containers on the automatically provisioned Unraid [macvlan ](https://docs.docker.com/network/macvlan/) (`br0`).

I actually don't think this is to do with the issue I am having but I wanted to make sure the setup I am using was clearly explained.

I think my issue is related to [#3468](https://github.com/containous/traefik/issues/3468) but I am not entirely sure.

Currently my primary domain is working with SSL but for some reason non of the sub domains work, I have tried deleting and recreating my `acme.json` as well as these two configs in my `traefik.toml`:

```toml
[[acme.domains]]
   main = ".domain.name"
[[acme.domains]]
   main = "*.domain.name"
```

```toml
[[acme.domains]]
   main = "*.domain.name"
   sans = ["domain.name"]
```

I have logged the output [here (Pastebin)](https://pastebin.com/xyW39mpa) using `DEBUG` but if I am being honest I don't understand all of it, also I tried to remove all sensitive information but let me know if I have not.

### What did you expect to see?

I want `https` to work on sub domains.

### What did you see instead?

SSL errors on sub domains.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Docker: `image: traefik:latest`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My full `traefik.toml`:

```toml
debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[traefikLog]
  filePath = "traefik.log"
  format   = "json"

[accessLog]
  filePath = "access.log"
  format = "json"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[acme]
email = "user@email.com"
storage = "acme.json"
entryPoint = "https"
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
[[acme.domains]]
   main = "domain.name"
[[acme.domains]]
   main = "*.domain.name"
```

Here is a screenshot of my Cloudflare config:

![Cloudflare](https://user-images.githubusercontent.com/2978850/58599387-2f509a80-82d4-11e9-9d08-17181831dead.PNG)

And finally here is an abbreviated version of my `docker-compose.yml` (probably not relevant but trying to be thorough):

```yaml
---
version: '3'

services:

  traefik:
    image: traefik:latest
    command: --web --docker --docker.watch --docker.domain=${DOMAIN} \
             --docker.exposedbydefault=false --acme.domains=${DOMAIN}
    container_name: traefik
    hostname: traefik
    networks:
      br0:
        ipv4_address: 192.168.1.253
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.log:/traefik.log
      - ${CONFIG}/traefik/access.log:/access.log
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
    environment:
      - CF_API_EMAIL=user@email.com
      - CF_API_KEY=xxxxxxxxxxxxxxxxxxx
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAIN}"
      traefik.port: "8080"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.ouroboros.enable: "true"
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    networks:
      br0:
        ipv4_address: 192.168.1.252
    volumes:
      - ${CONFIG}/plex:/config
      - ${DATA}/TV:/media/tv
      - ${DATA}/Movies:/media/movies
      - ${DATA}/Music:/media/music
      - ${DATA}/Anime:/media/anime
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    labels:
      traefik.enable: "true"
      traefik.port: "32400"
      traefik.frontend.rule: "Host:plex.${DOMAIN}"
      com.ouroboros.enable: "true"
    restart: unless-stopped

  plexpy:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    networks:
      br0:
        ipv4_address: 192.168.1.251
    volumes:
      - ${CONFIG}/plexpy:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8181"
      traefik.frontend.rule: "Host:tautulli.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.ouroboros.enable: "true"
    restart: unless-stopped

networks:
  br0:
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Output [here (Pastebin)](https://pastebin.com/xyW39mpa).
