### ISSUE TITLE
Docker Segment labels Sticky session

### ISSUE THREAD

**Issue by goodwillhacking** [containous/traefik#4925]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I have a docker compose deployment with a service handling both HTTP and WS requests. For the WS requests I require sticky sessions between the client and respective docker task. Sticky sessions does not seem to work for segemented label requests, both WS and HTTP.
```yml
 api-example:
    image: "api-example:${TAG}-latest"
    hostname: api-example-{{.Node.ID}}
    depends_on:
    - redis
    - loadbalancer
    env_file:
      - /home/appgaged/docker/config/base.env
      - /home/appgaged/docker/config/api-freebure.env
    ports:
    - target: 3005
      protocol: tcp
    - target: 3505
      protocol: tcp
    networks:
      - app-net
      - proxy_proxy-net
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 2
      labels:
        - 'traefik.docker.network=proxy_proxy-net'

        - 'traefik.api-http.port=3005'
        - 'traefik.api-http.frontend.rule=Host:test-api.example.com'
        - 'traefik.api-http.backend.loadbalancer.stickiness=false'

        - 'traefik.websocket.port=3505'
        - 'traefik.websocket.frontend.rule=Host:io.example.com'
        - 'traefik.websocket.backend.loadbalancer.stickiness=true'
    logging:
      driver: 'json-file'
      options:
        max-size: '200mb'
```

### What did you expect to see?
I expect to see a Cookie being set. I run an additional service to test this. Using the whoami image and the following config:
```yml
#### WHOAMI ########
  whoami:
    image: emilevauge/whoami
    hostname: whoami-{{.Node.ID}}
    ports:
    - target: 80
      protocol: tcp
    networks:
      - app-net
      - proxy_proxy-net
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 2
      labels:
        - 'traefik.docker.network=proxy_proxy-net'

        - 'traefik.port=80'
        - 'traefik.frontend.rule=Host:whoami.appgaged.com'
        - 'traefik.backend.loadbalancer.stickiness=true'
    logging:
      driver: 'json-file'
      options:
        max-size: '200mb'
```

Response:
```
Hostname: whoami-kyfo7gfn5f364axfzmnklvrtf
IP: 127.0.0.1
IP: 192.168.45.171
IP: 172.18.0.3
IP: 192.168.7.151
IP: 10.255.146.111
GET / HTTP/1.1
Host: whoami.example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: _1f00a=http://192.168.7.151:80
Dnt: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: XX.XXX.XXX.XXX
X-Forwarded-Host: whoami.example.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-proxy-0aswk6rwx58759c847dxxvbhl
X-Real-Ip: XX.XX.XXX.XXX
```
![image](https://user-images.githubusercontent.com/3004543/58750648-3659e300-8463-11e9-948c-c4e4db29e9d8.png)

### What did you see instead?
I expect to see a cookie being set in request or in app. I see nothing
![image](https://user-images.githubusercontent.com/3004543/58750810-b2a0f600-8464-11e9-8aba-fa4cd206ba1e.png)

![image](https://user-images.githubusercontent.com/3004543/58750817-c51b2f80-8464-11e9-88dc-5c4212e6e4ee.png)

I have tested this issue with none segemented services and it works. I am able to use a cookie for requests

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      v1.7.11
Codename:     maroilles
Go version:   go1.11.9
Built:        2019-04-26_08:42:33AM
OS/Arch:      linux/amd64

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# https://docs.traefik.io/user-guide/docker-and-lets-encrypt/
debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true

  [entryPoints.traefik-api]
    address = ":20000"
    [entryPoints.traefik-api.auth.digest]
      removeHeader = false
      usersFile = "/.htdigest-traefik"

  [entryPoints.traefik-prom]
    address = ":30000"

  [entryPoints.traefik-ping]
    address = ":25000"


[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "example.com"
  watch = true
  exposedbydefault = false
  swarmMode = true

[consul]
  prefix = "traefik"
  endpoint = "consul:8500"
  watch = true


[traefikLog]
  filePath = "/var/log/traefik/traefik.log"
  format = "json"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  format="json"

[api]
  entryPoint = "traefik-api"
  dashboard = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik-prom"
    buckets = [0.1,0.3,1.2,5.0]

[ping]
  entryPoint = "traefik-ping"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
