### ISSUE TITLE
Traefik not closing tcp connections, server getting unresponsive after a bit of time

### ISSUE THREAD

**Issue by kolaente** [containous/traefik#4926]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I deployed my (rather simple) go application using docker and docker-compose with some monitoring (using prometheus, not related to traefik) and traefik (also in docker) by pretty much following [this](https://docs.traefik.io/user-guide/docker-and-lets-encrypt/) guide. All in all not much, 7 containers in total (with traefik). I used [the cheapest Hetzner cloud vps](https://www.hetzner.de/cloud) which however should have more than enough ressources for my use case.

I can provide the compose files if needed.

### What did you expect to see?

Application working normally, no issues.

### What did you see instead?

After a while, the server gets totally unresponsive. Not even ssh did work anymore. When I restarted it via Hetzners web console, it started working again, but after a few days I had the same issue again. After some digging, I found this to be an error with "too many orphaned tcp connections" and thought my application was to blame, found an issue with that, fixed it, redeployed it and thought it was all good. But then, the same problem started appearing again. Being a bit short on time, I just raised all limits which got it somehow working again.

Then I finally did some more looking for the error and found this:
```
~# ss -sa
Total: 99822 (kernel 99836)
TCP:   99753 (estab 1, closed 99748, orphaned 1, synrecv 0, timewait 225/0), ports 0

Transport Total     IP        IPv6
*	  99836     -         -        
RAW	  0         0         0        
UDP	  1         1         0        
TCP	  5         2         3        
INET	  6         3         3        
FRAG	  0         0         0 
```
Notice the _99748_ closed tcp connections which don't show up in the further stats. These didn't show up in `netstat` either, which I thought is a bit weird. Then I started shutting down parts of my application, one after another, then the monitoring, checking each time if the number of closed connections had gone down (spoiler: it didn't much) until there was only traefik left. When I shut it down, I noticed this:

```
/opt/compose/traefik# docker-compose down
Stopping traefik ... done
Removing traefik ... done
Network web is external, skipping
/opt/compose/traefik# ss -sa
Total: 127 (kernel 156)
TCP:   3904 (estab 1, closed 3901, orphaned 3667, synrecv 0, timewait 234/0), ports 0

Transport Total     IP        IPv6
*	  156       -         -        
RAW	  0         0         0        
UDP	  1         1         0        
TCP	  3         2         1        
INET	  4         3         1        
FRAG	  0         0         0  
```

The number of closed tcp connections got down pretty quickly, even dropping down to ~30 after a few minutes. Even after I started bringing up my application again. So it looks like traefik is the issue here.

I'm not quite sure if this relates to #3165 since the connections didn't show up in `netstat` at all, also not sure about #4864 since my application isn't using any websockets.

### Output of `traefik version`: (_What version of Traefik are you using?_)

In Docker: 
```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

(Oh wow... I don't know why I'm using such an old version of traefik... Maybe my bug already got fixed...)
I'll update my version of traefik and see if that fixes it and update here.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "my-awesome-app.org"
watch = true
exposedByDefault = false

[acme]
email = "test@vikunja.dev"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
```

Running with this `docker-compose.yml`:
```yml
version: '2'

services:
  traefik:
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik

networks:
  web:
    external: true
````
