### ISSUE TITLE
WebDAV Windows 10 via https errors (slow, can't delete, rename etc.)

### ISSUE THREAD

**Issue by covrig** [containous/traefik#4937]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I am trying to use WebDAV (I tried multiple options for this - embedded QNAP solution, bytemark/webdav container etc.) to map a folder from a QNAP  to a Windows 10 machine over the internet. 

HTTP works fine, however HTTPS does not. I can map the drive in Windows (map network drive), however it is slow, folders are randomly unavailable, some folders/files are not visible (checked permissions and are OK), I can't delete folders or rename them, I can't copy folders.

I noticed that only the folders are buggy and I suspect some kind of path issue. Files can be added, copied, deleted or renamed.

**Other WebDAV clients work OK (e.g. WinSCP) - both on Windows or Android.** 
Only the Windows 10 embedded solution seems to have the problem (https only).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik 1.7.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]  

[entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[frontends]

  [frontends.frontend1]
  backend = "qnapwebdav"
  passHostHeader = true
    [frontends.frontend1.routes.qnap]
    rule = "Host:domain.com;"

[backends]

  [backends.qnapwebdav]
    [backends.qnapwebdav.servers.server1]
    url = "http://10.160.42.10:8008"
```
