### ISSUE TITLE
Traefik + Docker Swarm. Partial outage every swarm discovery cycle

### ISSUE THREAD

**Issue by elfenlaid** [containous/traefik#4941]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I've configured basic docker swarm cluster with traefik and consul kv. During swarm node discovery (by default every 15 seconds), traefik recreates all frontends and backends for available services, which leads to service outages (404s) for a couple of seconds.

After fronts are up I'm able to reach services till next discovery cycle. 

Also during recreation fronts and backs (besides traefik dash front/back) dissaper from dash and reaper couple seconds later.

### What did you expect to see?

Services available during swarm discovery. Services' frontends and backends persist through discovery cycles.

### What did you see instead?

Services are unreachable with 404 error code. Services' frontends and backends recreating.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
version: '3.7'


services:
  init:
    image: traefik:1.7-alpine
    networks:
      - traefik-public
    command:
      - storeconfig
      - --api
      - --logLevel=DEBUG
      - --accessLog
      - --docker
      - --docker.endPoint=http://dockersocket:2375
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.network=proxy
      - --docker.watch
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
      - --defaultentrypoints=http,https
      - --entryPoints='Name:https Address::443 TLS'
      - --entryPoints='Name:http Address::80'
      - --acme
      - --acme.email=${EMAIL?Variable EMAIL not set}
      - --acme.httpchallenge
      - --acme.httpchallenge.entrypoint=http
      - --acme.onhostrule=true
      - --acme.entrypoint=https
      - --acme.storage=traefik/acme/account
      - --acme.acmelogging
      - --constraints=tag==traefik-public
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul

  traefik:
    image: traefik:1.7-alpine
    networks:
      - traefik-public
      - traefik-docker
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress # traefik dashboard
    command:
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirect.frontend.entryPoints=http
        - traefik.redirect.frontend.redirect.entryPoint=https
        - traefik.redirect.frontend.entryPoints=https
        - traefik.frontend.rule=Host:traefik.${DOMAIN?Variable DOMAIN not set}
        - traefik.frontend.auth.basic.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    depends_on:
      - consul

  consul:
    image: consul
    command: agent -server -bootstrap-expect=1 -ui
    networks:
      - traefik-public
    volumes:
      - consul:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"server":true, "leave_on_terminate": true}'
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
      restart_policy:
        condition: on-failure

# this custom haproxy allows us to move traefik to worker nodes
# while this container listens on managers and only allows
# traefik to connect, read-only, to limited docker api calls
# https://github.com/Tecnativa/docker-socket-proxy
  dockersocket:
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      # SWARM: 1
      TASKS: 1
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

volumes:
  consul:

networks:
  traefik-docker:
  traefik-public:
    # external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
level=info msg="Skipping same configuration for provider consul"
level=debug msg="Cannot get key traefik/alias Key not found in store"
level=debug msg="Setting traefik/alias to default: traefik"
level=debug msg="Cannot list keys under \"traefik/backends/\": Key not found in store"
level=debug msg="Cannot list keys under \"traefik/frontends/\": Key not found in store"
level=debug msg="Cannot list keys under \"traefik/tls/\": Key not found in store"
level=debug msg="Configuration received from provider consul: {}"
level=info msg="Skipping same configuration for provider consul"
level=debug msg="originLabelsmap[traefik.enable:true traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.port:8080 traefik.redirect.frontend.redirect.entryPoint:https com.docker.stack.image:traefik:1.7-alpine com.docker.stack.namespace:traefik traefik.docker.network:traefik-public traefik.frontend.rule:Host:traefik.eye.middle-earth.io traefik.redirect.frontend.entryPoints:https traefik.tags:traefik-public]"
level=debug msg="allLabelsmap[:map[traefik.enable:true traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.port:8080 traefik.tags:traefik-public traefik.docker.network:traefik-public traefik.frontend.rule:Host:traefik.eye.middle-earth.io] redirect:map[traefik.frontend.redirect.entryPoint:https traefik.frontend.entryPoints:https]]"
level=debug msg="originLabelsmap[com.docker.stack.image:consul com.docker.stack.namespace:traefik traefik.docker.network:traefik-public traefik.enable:true traefik.port:8500 traefik.redirectorservice.frontend.entryPoints:http traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.frontend.rule:Host:consul.eye.middle-earth.io traefik.redirectorservice.frontend.redirect.entryPoint:https traefik.tags:traefik-public traefik.webservice.frontend.entryPoints:https]"
level=debug msg="allLabelsmap[:map[traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.frontend.rule:Host:consul.eye.middle-earth.io traefik.docker.network:traefik-public traefik.enable:true traefik.port:8500 traefik.tags:traefik-public] redirectorservice:map[traefik.frontend.redirect.entryPoint:https traefik.frontend.entryPoints:http] webservice:map[traefik.frontend.entryPoints:https]]"
level=debug msg="originLabelsmap[com.docker.stack.namespace:logstash traefik.metrics.port:9600 traefik.redirectorservice.frontend.redirect.permanent:true traefik.tags:traefik-public traefik.redirectorservice.frontend.redirect.entryPoint:https com.docker.stack.image:docker.io/elfenlaid/logstash swarmpit.service.deployment.autoredeploy:true traefik.docker.network:traefik-public traefik.enable:true traefik.metrics.frontend.entryPoints:https traefik.metrics.frontend.rule:Host:logstash.eye.middle-earth.io traefik.redirectorservice.frontend.entryPoints:http traefik.redirectorservice.frontend.rule:Host:logstash.eye.middle-earth.io]"
level=debug msg="allLabelsmap[:map[traefik.tags:traefik-public traefik.docker.network:traefik-public traefik.enable:true] metrics:map[traefik.port:9600 traefik.frontend.entryPoints:https traefik.frontend.rule:Host:logstash.eye.middle-earth.io] redirectorservice:map[traefik.frontend.redirect.permanent:true traefik.frontend.entryPoints:http traefik.frontend.redirect.entryPoint:https traefik.frontend.rule:Host:logstash.eye.middle-earth.io]]"
level=debug msg="Filtering container without port, logstash_app.1: port label is missing, please use traefik.port as default value or define port label for all segments ('traefik.<segment_name>.port')"
level=debug msg="originLabelsmap[com.docker.stack.image:tecnativa/docker-socket-proxy com.docker.stack.namespace:traefik]"
level=debug msg="allLabelsmap[:map[]]"
level=debug msg="Filtering container without port, traefik_dockersocket.rqv33kakj4swvmqik2y35hqne: port label is missing, please use traefik.port as default value or define port label for all segments ('traefik.<segment_name>.port')"
level=debug msg="originLabelsmap[traefik.enable:true traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.port:8080 traefik.redirect.frontend.redirect.entryPoint:https com.docker.stack.image:traefik:1.7-alpine com.docker.stack.namespace:traefik traefik.docker.network:traefik-public traefik.frontend.rule:Host:traefik.eye.middle-earth.io traefik.redirect.frontend.entryPoints:https traefik.tags:traefik-public]"
level=debug msg="allLabelsmap[redirect:map[traefik.frontend.entryPoints:https traefik.frontend.redirect.entryPoint:https] :map[traefik.docker.network:traefik-public traefik.frontend.rule:Host:traefik.eye.middle-earth.io traefik.tags:traefik-public traefik.enable:true traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.port:8080]]"
level=debug msg="originLabelsmap[com.docker.stack.image:consul com.docker.stack.namespace:traefik traefik.docker.network:traefik-public traefik.enable:true traefik.port:8500 traefik.redirectorservice.frontend.entryPoints:http traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.frontend.rule:Host:consul.eye.middle-earth.io traefik.redirectorservice.frontend.redirect.entryPoint:https traefik.tags:traefik-public traefik.webservice.frontend.entryPoints:https]"
level=debug msg="allLabelsmap[:map[traefik.frontend.auth.basic.users:admin:$apr1$urYfOtau$Gjbmr1.qKmCYudUKbC/Za/ traefik.frontend.rule:Host:consul.eye.middle-earth.io traefik.tags:traefik-public traefik.docker.network:traefik-public traefik.enable:true traefik.port:8500] redirectorservice:map[traefik.frontend.redirect.entryPoint:https traefik.frontend.entryPoints:http] webservice:map[traefik.frontend.entryPoints:https]]"
level=debug msg="Backend backend-traefik-consul-webservice: no load-balancer defined, fallback to 'wrr' method"
level=debug msg="Backend backend-traefik-traefik-redirect: no load-balancer defined, fallback to 'wrr' method"
level=debug msg="Backend backend-traefik-consul-redirectorservice: no load-balancer defined, fallback to 'wrr' method"
level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-consul-redirectorservice\":{\"servers\":{\"server-traefik-consul-1-1f054db510941b8693ab4f9267343456\":{\"url\":\"http://10.0.0.49:8500\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"backend-traefik-consul-webservice\":{\"servers\":{\"server-traefik-consul-1-1f054db510941b8693ab4f9267343456\":{\"url\":\"http://10.0.0.49:8500\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"backend-traefik-traefik-redirect\":{\"servers\":{\"server-traefik-traefik-ip6nkn0m4idzvreqd7uutqx38-d10745fe1c66bc5c76b494485d78c07d\":{\"url\":\"http://10.0.0.27:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-redirect-traefik-traefik-redirect\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-traefik-traefik-redirect\",\"routes\":{\"route-frontend-redirect-traefik-traefik-redirect\":{\"rule\":\"Host:traefik.eye.middle-earth.io\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"redirect\":{\"entryPoint\":\"https\"},\"auth\":{\"basic\":{}}},\"frontend-redirectorservice-traefik-consul-redirectorservice\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-traefik-consul-redirectorservice\",\"routes\":{\"route-frontend-redirectorservice-traefik-consul-redirectorservice\":{\"rule\":\"Host:consul.eye.middle-earth.io\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"redirect\":{\"entryPoint\":\"https\"},\"auth\":{\"basic\":{}}},\"frontend-webservice-traefik-consul-webservice\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-traefik-consul-webservice\",\"routes\":{\"route-frontend-webservice-traefik-consul-webservice\":{\"rule\":\"Host:consul.eye.middle-earth.io\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"auth\":{\"basic\":{}}}}}"
level=debug msg="Wiring frontend frontend-redirect-traefik-traefik-redirect to entryPoint https"
level=debug msg="Creating backend backend-traefik-traefik-redirect"
level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-redirect-traefik-traefik-redirect"
level=debug msg="Creating load-balancer wrr"
level=debug msg="Creating server server-traefik-traefik-ip6nkn0m4idzvreqd7uutqx38-d10745fe1c66bc5c76b494485d78c07d at http://10.0.0.27:8080 with weight 1"
level=debug msg="Creating route route-frontend-redirect-traefik-traefik-redirect Host:traefik.eye.middle-earth.io"
level=debug msg="Wiring frontend frontend-redirectorservice-traefik-consul-redirectorservice to entryPoint http"
level=debug msg="Creating backend backend-traefik-consul-redirectorservice"
level=debug msg="Creating entry point redirect http -> https"
level=debug msg="Frontend frontend-redirectorservice-traefik-consul-redirectorservice redirect created"
level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-redirectorservice-traefik-consul-redirectorservice"
level=debug msg="Creating load-balancer wrr"
level=debug msg="Creating server server-traefik-consul-1-1f054db510941b8693ab4f9267343456 at http://10.0.0.49:8500 with weight 1"
level=debug msg="Creating route route-frontend-redirectorservice-traefik-consul-redirectorservice Host:consul.eye.middle-earth.io"
level=debug msg="Wiring frontend frontend-webservice-traefik-consul-webservice to entryPoint https"
level=debug msg="Creating backend backend-traefik-consul-webservice"
level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-webservice-traefik-consul-webservice"
level=debug msg="Creating load-balancer wrr"
level=debug msg="Creating server server-traefik-consul-1-1f054db510941b8693ab4f9267343456 at http://10.0.0.49:8500 with weight 1"
level=debug msg="Creating route route-frontend-webservice-traefik-consul-webservice Host:consul.eye.middle-earth.io"
level=info msg="Server configuration reloaded on :443"
level=info msg="Server configuration reloaded on :8080"
level=info msg="Server configuration reloaded on :80"
level=debug msg="LoadCertificateForDomains [consul.eye.middle-earth.io]..."
level=debug msg="Looking for provided certificate to validate [consul.eye.middle-earth.io]..."
level=debug msg="No ACME certificate to generate for domains [\"consul.eye.middle-earth.io\"]."
level=debug msg="LoadCertificateForDomains [traefik.eye.middle-earth.io]..."
level=debug msg="Looking for provided certificate to validate [traefik.eye.middle-earth.io]..."
level=debug msg="No ACME certificate to generate for domains [\"traefik.eye.middle-earth.io\"]."
level=debug msg="Cannot get key traefik/alias Key not found in store"
level=debug msg="Setting traefik/alias to default: traefik"
level=debug msg="Cannot list keys under \"traefik/backends/\": Key not found in store"
level=debug msg="Cannot list keys under \"traefik/frontends/\": Key not found in store"
level=debug msg="Cannot list keys under \"traefik/tls/\": Key not found in store"
level=debug msg="Configuration received from provider consul: {}"
level=info msg="Skipping same configuration for provider consul"
```
