### ISSUE TITLE
Portainer "Execute" websocket

### ISSUE THREAD

**Issue by xavs** [containous/traefik#4946]
### Did you try using a 1.7.x configuration for the version 2.0?

- [x] Yes
- [ X ] No

### What did you do?
Used the configuration for traefik and portainer, deployed on a specific URL path https://docs.traefik.io/user-guide/examples/

### What did you expect to see?
In Portainer, I access the Menu "Containers", select one container, and then I go to "Console" and click on "Connect". This should open a web-shell. 

### What did you see instead?
Error in browser console:
WebSocket connection to '.........' failed: Error during WebSocket handshake: Unexpected response code: 400
Error in Portainer
websocketproxy: couldn't upgrade websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
I tried adding customHeaders Connection:Upgrade, but it just doesn't work

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[file]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://(.*)$"
    replacement = "https://$1"
  [entryPoints.https]
  address = ":443" #the ssl is handled by ELB
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
