### ISSUE TITLE
--providers.kubernetescrd.namespaces strange behavior

### ISSUE THREAD

**Issue by bill-within** [containous/traefik#4952]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Set the `--providers.kubernetescrd.namespaces="traefik,dev,test"` argument

### What did you expect to see?

Traefik discovering resources in those 3 namespaces, and made visible by `curl traefik-admin/api/rawdata`. traefik-admin is a service which exposes port 8080 on the traefik pods.

### What did you see instead?

Traefik did not discover resources in namespace `test`. 

However, when I switch the argument to `--providers.kubernetescrd.namespaces="traefik,test,dev"` then `test` resources are discovered and `dev` ones are not.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
            - --api
            - --ping
            - --accesslog
            - --entrypoints=Name:web Address::8000
            - --entrypoints=Name:websecure Address::4443
            - --providers.kubernetescrd
            - --metrics.prometheus
            - --tracing
            - --tracing.backend=zipkin
            - --tracing.zipkin.httpEndpoint=http://zipkin.istio-system:9411/api/v1/spans
            - --tracing.zipkin.sampleRate=.01
```

**Comment by bill-within** [comment]
It looks like this may be a generic issue with the parsing of the command-line argument - when I explicitly create a traefik.toml file containing the namespace restrictions and point the Deployment at it, everything works as expected. It's also worth noting that, at least in a GKE-managed Istio environment, the CPU usage of the traefik pods goes way way down when not including all namespaces. My cluster is a fairly bare testing arena with maybe a dozen small applications deployed across ~6 namespaces, but leaving those extra namespaces out (along with kube-system and istio-system) has taken the traefik pods' normal CPU consumption from 170-200m down to 8-11m. Memory consumption is the same (but good) - around 20Mi.

**Comment by ldez** [comment]
We have completely rewritten the flag parser in the alpha5/alpha6.
Also the syntax for entry points has been changed: https://docs.traefik.io/v2.0/routing/entrypoints/#general

Could you try with the alpha6?

**Comment by bill-within** [comment]
Nice! I've updated to alpha6 with the following config:

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  namespace: traefik
data:
  traefik.toml: |
    [providers]
    [providers.kubernetescrd]
      namespaces = ["dev", "test"]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      containers:
        - name: traefik
          image: gcr.io/within-kubernetes-1/traefik:v2.0.0-alpha6
          volumeMounts:
          - name: "config"
            mountPath: "/config"  
          args:
            - --configfile=/config/traefik.toml
            - --api
            - --accesslog
            - --entryPoints.ping.Address=:8082
            - --entryPoints.web.Address=:8000
            - --entryPoints.websecure.Address=:4443
            - --ping
            - --ping.entryPoint=ping
            - --metrics.prometheus
            - --tracing
            - --tracing.backend=zipkin
            - --tracing.zipkin.httpEndpoint=http://zipkin.istio-system:9411/api/v1/spans
            - --tracing.zipkin.sampleRate=.05
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: ping
              containerPort: 8082
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /ping
              port: ping
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: ping
              scheme: HTTP
            periodSeconds: 10
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 300m
              memory: 128Mi
```

But unfortunately, the liveness & readiness probes are failing and so it's in a crashLoopBackoff:

```
│Events:                                                                                                                                                                                                                          │
│  Type     Reason     Age                    From                                           Message                                                                                                                              │
│  ----     ------     ----                   ----                                           -------                                                                                                                              │
│  Normal   Scheduled  5m34s                  default-scheduler                              Successfully assigned traefik/traefik-565944bbb7-v29jv to gke-dev-1-default-pool-9628022b-ljxg                                       │
│  Normal   Started    4m56s (x3 over 5m32s)  kubelet, gke-dev-1-default-pool-9628022b-ljxg  Started container                                                                                                                    │
│  Warning  Unhealthy  4m42s (x5 over 5m22s)  kubelet, gke-dev-1-default-pool-9628022b-ljxg  Readiness probe failed: Get http://10.52.3.41:8082/ping: dial tcp 10.52.3.41:8082: connect: connection refused                       │
│  Normal   Pulled     4m37s (x4 over 5m32s)  kubelet, gke-dev-1-default-pool-9628022b-ljxg  Container image "gcr.io/within-kubernetes-1/traefik:v2.0.0-alpha6" already present on machine                                        │
│  Normal   Created    4m37s (x4 over 5m32s)  kubelet, gke-dev-1-default-pool-9628022b-ljxg  Created container                                                                                                                    │
│  Warning  Unhealthy  4m37s (x6 over 5m22s)  kubelet, gke-dev-1-default-pool-9628022b-ljxg  Liveness probe failed: Get http://10.52.3.41:8082/ping: dial tcp 10.52.3.41:8082: connect: connection refused                        │
│  Normal   Killing    4m37s (x3 over 5m17s)  kubelet, gke-dev-1-default-pool-9628022b-ljxg  Killing container with id docker://traefik:Container failed liveness probe.. Container will be killed and recreated.                 │
│  Warning  BackOff    20s (x18 over 3m57s)   kubelet, gke-dev-1-default-pool-9628022b-ljxg  Back-off restarting failed container 
```


Interestingly in the log for the container, I see this:

```
traefik-565944bbb7-v29jv:traefik time="2019-06-20T07:37:12Z" level=error msg="accept tcp [::]:80: use of closed network connection"
```

So maybe it's trying to use port 80 for something?

I'm probably missing something basic as it's pretty late at night here! & I will try moving the namespace limiting configs off to the command line once I can get it to pass the health checks.

**Comment by ldez** [comment]
Now, with the alpha6/alpha5 is not possible to mix TOML and CLI flags, then you need to use either flags or TOML, but the both.

**Comment by bill-within** [comment]
Hmmmm OK, with that swapped out I'm getting an insta-crash with the following in the log:

```
2019/06/20 18:24:24 command traefik error: failed to decode configuration from environment variables: field not found, node: admin
```

Deployment looks like so:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - traefik
      terminationGracePeriodSeconds: 60
      containers:
        - name: traefik
          image: gcr.io/within-kubernetes-1/traefik:v2.0.0-alpha6
          args:
            - --api
            - --accesslog
            - --entryPoints.ping.Address=:8082
            - --entryPoints.web.Address=:8000
            - --entryPoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --providers.kubernetescrd.namespaces="dev,test"
            - --ping
            - --ping.entryPoint=ping
            - --metrics.prometheus
            - --tracing
            - --tracing.backend=zipkin
            - --tracing.zipkin.httpEndpoint=http://zipkin.istio-system:9411/api/v1/spans
            - --tracing.zipkin.sampleRate=.05
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: ping
              containerPort: 8082
            - name: admin
              containerPort: 8080
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /ping
              port: ping
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: ping
              scheme: HTTP
            periodSeconds: 10
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 300m
              memory: 128Mi
```

I'll take a look at the source and see if I can figure out what's up, but if you have any pointers I'd be glad for them! Perhaps we need to explicitly set the admin entrypoint now.
