### ISSUE TITLE
Proxy headers not set in docker composer

### ISSUE THREAD

**Issue by mbrucher** [containous/traefik#4957]
I already tried getting some help on SO: https://stackoverflow.com/questions/56570126/traefik-not-setting-forward-headers but no answer there.

### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

(I did try to use 2.0, but just --docker doesn't work, so...)

### What did you do?

I have a docker composer, first with traefik:
```
  traefik:
    image: traefik:1.7
    command: --api \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --logLevel=DEBUG \
      --entrypoints='Name:http Address::80 Redirect.EntryPoint:https' \
      --entrypoints='Name:https Address::443 TLS' \
      --entrypoints='Name:preprod Address::8000 TLS' \
      --acme=true \
      --acme.storage=/etc/traefik/acme/acme.json \
      --acme.ondemand=true \
      --acme.onhostrule=true \
      --acme.entrypoint=https \
      --acme.httpchallenge \
      --acme.httpchallenge.entrypoint=http \
      --acme.domains="xxxxxx" \
      --acme.email="matthieu.brucher@gmail.com"

    networks:
      - traffic
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/acme:/etc/traefik/acme
    deploy:
      placement:
        constraints: [node.role==manager]
```
Then the server itself (flask + nginx, works properly after testing just this container):
```
  backend:
    image: backend
    networks:
      - traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.backend: "backend"
        traefik.docker.network: "traefik"
        traefik.enable: "true"
        traefik.frontend.entryPoints: "https"
        traefik.frontend.rule: "PathPrefix:/auth,/api"
        traefik.frontend.passHostHeader: "true"
        traefik.port: "8000"
```
### What did you expect to see?

Flask should have displayed 192.168.0.6 (like the direct docker container version) for the client IP.

### What did you see instead?

I expected Flask to report the client IP, unfortunately, I got for instance 2019-06-13T21:04:11.571432896Z 10.0.5.102 - - [13/Jun/2019:21:04:11 +0000] "GET /api/v0/user HTTP/1.1" 200 149 "https://192.168.0.50/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0" "10.255.0.2"

I can check that the headers are indicating X-Forwarded-For=10.255.0.2, which is wrong.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I don't have a toml file.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
```
time="2019-06-13T21:22:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v0/nouser/5c951c8930741a0009abb183\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3\"],\"Cookie\":[\"\"],\"Referer\":[\"https://192.168.0.50/\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0\"],\"X-Csrf-Token\":[\"f7fb7a1b-25b3-49c0-92ce-2a2d1206eca3\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"192.168.0.50\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:55825\",\"RequestURI\":\"/api/v0/nouser/5c951c8930741a0009abb183\",\"TLS\":null}"
```
Here, we can see RemoteAddr=10.255.0.2, but this is not correct, it should be 192.168.0.6 (not sure where this value comes form!).
