### ISSUE TITLE
Connect: permission denied socket Fedora 30

### ISSUE THREAD

**Issue by Slown61** [containous/traefik#4962]
Hello, I can not run traefik on Fedora 30. I get the following error:

```text
traefik    | time="2019-06-16T12:17:50Z" level=error msg="Failed to retrieve information of the docker client and server host: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.21/version: dial unix /var/run/docker.sock: connect: permission denied"
```

My docker.sock file has the following rights:

`srw-r--r--. 1 root docker 0 16 juin  11:45 /var/run/docker.sock`

And my docker-compose.yml file is:

```yaml
version: '2'

services:
    traefik:
        container_name: traefik
        image: traefik:latest
        command: --docker
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        labels:
            - "traefik.enable=true"
            - "traefik.port=8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:z"
            - "/home/julien/docker/traefik/traefik.toml:/etc/traefik/traefik.toml:z"
            - "/home/julien/docker/traefik/acme:/etc/traefik/acme:z"
```

Thanks for your help.
