### ISSUE TITLE
Traefik 2.0 not working with traefik-forward-auth, but works with 1.7

### ISSUE THREAD

**Issue by dalanmiller** [containous/traefik#4972]
https://github.com/thomseddon/traefik-forward-auth/issues/45

### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Attempting to set up ForwardAuth with Traefik 2.0 and this forward auth handler service written by @thomseddon.

### What did you expect to see?

ForwardAuth to succeed

### What did you see instead?

Once authenticated via Google, I get a final redirect to a URL for the traefik-forward-auth service but ultimately results in a 404. See logs at bottom. 

So the flow with the shown config below would be.

1. Go to `synology.sub.domain.com`
2. Not authenticated in this browser so sent to google 
3. Get authenticated successfully, 307 redirect happens 
4. Ultimately 404 on a URL at `auth.sub.domain.com` with a long query string.

### Output of `traefik version`: (_What version of Traefik are you using?_)

This doesn't work with the alpha AFAICT but I'm on the image created:

```
2019-04-18 00:00:21
```

Which I believe is `alpha4`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  Debug = true
  SendAnonymousUsage = false

[api]

[providers]
  [providers.file]
    watch=true
    
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "sub.domain.com"
    watch = true
    exposedByDefault = false

[entryPoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"

[http.routers]
  [http.routers.synology]
      entryPoints = ["https", "http"]
      middlewares = [ "compress", "redirect", "forward-auth" ]
      rule = "Host(`synology.sub.domain.com`)"
      service = "synology"
    
  [http.middlewares]
    [http.middlewares.compress.compress]

    [http.middlewares.redirect.redirectScheme]
      scheme = "https"

    [http.middlewares.forward-auth.forwardAuth]
      address = "https://traefik-forward-auth:4181"
      authResponseHeaders = ["X-Forwarded-User"]
      
  [http.services]
  
    [http.services.synology]
      [http.services.synology.LoadBalancer]
          [[http.services.synology.LoadBalancer.servers]]
            url = "http://192.168.1.2:5000"
            scheme = "http"
            weight= 1

[acme]
  acmeLogging = true
  email = "me@email.com"
  storage = "/acme.json"
  onHostRule = true
  entryPoint = "https"
  [acme.dnsChallenge]
    provider = "provider"

  [[acme.domains]]
    main = "sub.domain.com"
  [[acme.domains]]
    main = "*.sub.domain.com"

```
docker-compose.yml
```yml
version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nfs/docker/traefik/traefik.toml:/traefik.toml
      # - /var/docker/traefik.toml/:/traefik.toml
      - /nfs/docker/traefik/acme.json:/acme.json
      - /nfs/docker/traefik/access.log:/access.log
      # - /nfs/docker/traefik/traefik.log:/traefik.log
    restart: always
    env_file: ./traefik.env
    labels:
      - "traefik.enable=false"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - SECRET=secret

      - AUTH_HOST=auth.sub.domain.com
      - COOKIE_DOMAIN=sub.domain.com
      - INSECURE_COOKIE=true
      - WHITELIST=me@email.com
      - LOG_LEVEL=debug

    labels:
      - traefik.enable=true
      - "traefik.http.middlewares.compress=true"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik-forward-auth    | time="2019-06-11T12:12:31Z" level=debug msg="Starting with options: {\"LogLevel\":\"debug\",\"LogFormat\":\"text\",\"AuthHost\":\"auth.sub.domain.com\",\"CookieDomains\":[{\"Domain\":\"sub.domain.com\",\"DomainLen\":20,\"SubDomain\":\".sub.domain.com\",\"SubDomainLen\":21}],\"InsecureCookie\":true,\"CookieName\":\"_forward_auth\",\"CSRFCookieName\":\"_forward_auth_csrf\",\"DefaultAction\":\"auth\",\"Domains\":null,\"LifetimeString\":43200,\"Path\":\"/_oauth\",\"Whitelist\":[\"me@email.com\",\"other@email.com\"],\"Providers\":{\"Google\":{\"ClientId\":\"<omitted_ID>.apps.googleusercontent.com\",\"Scope\":\"https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email\",\"Prompt\":\"\",\"LoginURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"accounts.google.com\",\"Path\":\"/o/oauth2/auth\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"TokenURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"www.googleapis.com\",\"Path\":\"/oauth2/v3/token\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"UserURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"www.googleapis.com\",\"Path\":\"/oauth2/v2/userinfo\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"}}},\"Rules\":{},\"Lifetime\":43200000000000,\"CookieDomainsLegacy\":null,\"CookieSecureLegacy\":\"\",\"DomainsLegacy\":null,\"ClientIdLegacy\":\"<omitted_ID>.apps.googleusercontent.com\",\"PromptLegacy\":\"\"}"
traefik-forward-auth    | time="2019-06-11T12:12:31Z" level=info msg="Listening on :4181"
traefik-forward-auth    | time="2019-06-11T12:12:51Z" level=debug msg="Authenticating request" headers="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.5] Cookie:[_forward_auth_csrf=c814ce3749ab60d0d4f66d95ae9cdf27] Dnt:[1] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0] X-Forwarded-For:[192.168.1.1] X-Forwarded-Host:[synology.sub.domain.com] X-Forwarded-Method:[GET] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[8bd8f24fbe93] X-Forwarded-Uri:[/] X-Real-Ip:[192.168.1.1]]" rule=default source_ip=192.168.1.1
traefik                 | 192.168.1.1 - - [11/Jun/2019:12:12:45 +0000] "GET /_oauth?state=c814ce3749ab60d0d4f66d95ae9cdf27:https://synology.sub.domain.com/&code=4/ZgF_eoY4qYEckmNyZN9uzV-XRtZM5omfbsUVZLB8cW5S3CD_hEVW6-CkwQJmj-QScYCJqC9Rl2Vj9NQsJCT9w8g&scope=email+profile+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile HTTP/2.0" 404 19 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" 1 - - 0ms
traefik                 | time="2019-06-11T12:12:51Z" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 307" middlewareType=ForwardedAuthType middlewareName=file.forward-auth
traefik-forward-auth    | time="2019-06-11T12:12:51Z" level=debug msg="Set CSRF cookie and redirecting to google login" source_ip=192.168.1.1
traefik                 | 192.168.1.1 - - [11/Jun/2019:12:12:51 +0000] "GET / HTTP/2.0" 307 467 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" 2 "file.synology" - 2ms
traefik                 | 2019/06/11 12:12:51 server.go:3012: http: TLS handshake error from 192.168.1.1:49956: EOF
```

**Comment by dduportal** [comment]
Hi @dalanmiller , thanks for your interest in the project.

The code related to the "forward auth" middleware should not have changed since `1.7.x`. There is a possibility that the (new) order of middlewares could impact the request to the externalt "traefik-forward-auth" service: sounds like a matter of configuration.

Could you simplify your example so we can track the configuration culprit?

- Switch to http only: Remove anything related to https and http -> https redirects
- Add a simple backend which is not "traefik-forward-auth" to avoid any consequence of loop redirections (the image `containous/whoami` is a lightweight webserver pritning the request headers in the response body)
- Disable and remove any mention to the middelware others than the `forwardAuth`
- Set the `address` of the middleware `forwardAuth` to `http` proto (instead of `https`)

**Comment by nadavpld** [comment]
Experiencing the same issue.
Middleware is not using https protocol.

When middlewares is set, the requests are not entering the auth server (even when redirecting to a simple server and printing all incoming requests - nothing is being printed to the screen).

When middlewares is removed everything works fine. (i.e. when it is set, only the login endpoint is being called, when it is removed all other endpoints are being called)

```
    [http.routers]
        [http.routers.login]
            rule = "PathPrefix(`/v1/api/login`)"
            service = "login"
        [http.routers.api]
            rule = "PathPrefix(`/v1/api`)"
            middlewares = ["auth"]
            service = "api"
        [http.routers.ws]
            rule = "PathPrefix(`/socket`)"
            middlewares = ["auth"]
            service = "ws"

    [http.middlewares]
        [http.middlewares.auth.forwardAuth]
            address = "http://localhost:5200/api/authenticate"
            trustFowardHeader = true
```

**Comment by dalanmiller** [comment]
@nadavpld it appears you're using v1.7 still and this issue is with v2.0. I can confirm that I was able to get forwardAuth working just fine using v1.7 with the `traefik-forward-auth` image.

**Comment by nadavpld** [comment]
> @nadavpld it appears you're using v1.7 still and this issue is with v2.0. I can confirm that I was able to get forwardAuth working just fine using v1.7 with the `traefik-forward-auth` image.

I am using v2.0 for windows and used the configuration examples from the v2.0 alpha documentation...
Why do you think i'm using 1.7 ? Maybe this is where I went wrong..

**Comment by dalanmiller** [comment]
@dduportal I've simplified to the following:

`traefik.toml`
```
[global]
  Debug = true
  SendAnonymousUsage = false

[api]

[providers]
  [providers.file]
    watch=true
    
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "sub.domain.com"
    watch = true
    exposedByDefault = false

[entryPoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"
    
  [http.middlewares]
    [http.middlewares.forward-auth.forwardauth]
      address = "https://traefik-forward-auth:4181"
      authResponseHeaders = ["X-Forwarded-User"]
      
[acme]
  acmeLogging = true
  email = "me@email.com"
  storage = "/acme.json"
  onHostRule = true
  entryPoint = "https"
  [acme.dnsChallenge]
    provider = "provider"

  [[acme.domains]]
    main = "sub.domain.com"
  [[acme.domains]]
    main = "*.sub.domain.com"
```

`docker-compose.yml`
```
version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nfs/docker/traefik/traefik.toml:/traefik.toml
    restart: always
    env_file: ./traefik.env
    labels:
      - "traefik.enable=false"
  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - SECRET=secret

      - AUTH_HOST=auth.sub.domain.com
      - COOKIE_DOMAIN=sub.domain.com
      - INSECURE_COOKIE=true
      - WHITELIST=me@email.com
      - LOG_LEVEL=debug
    labels:
      - traefik.enable=true
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
  hello-auth:
    container_name: hello-auth
    image: containous/whoami
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.hello-auth.rule=Host(`hello-auth.sub.domain.com`)"
      - "traefik.http.routers.hello-auth.service=hello-auth"
      - "traefik.http.routers.hello-auth.entryPoints=http"
      - "traefik.http.routers.hello-auth.tls=false"

      - "traefik.http.middlewares.forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.forward-auth.forwardauth.authresponseheaders=X-Forwarded-User"

      - "traefik.http.services.hello-auth.loadbalancer.server.port=80"
```

I can access `hello-auth.sub.domain.com` via `http` and get a 200 and the container information. I am not prompted to auth via Google as I do in my original example when attempting the Synology service defined in the `traefik.toml`. 

I think I might just be overlooking something.

**Comment by dalanmiller** [comment]
I can see that the Docker labels for forward auth aren't being parsed/picked up correctly by Traefik where the `synology` router in my `traefik.toml` config _is_ being associated properly with the forward auth middleware.

```
{
  "routers": {
    "docker.hello-auth": {
      "entryPoints": ["http"],
      "service": "hello-auth",
      "rule": "Host(`hello-auth.sub.domain.com`)"
    },
    "docker.hello-http": {
      "entryPoints": ["http"],
      "service": "hello-http",
      "rule": "Host(`hello.sub.domain.com`)"
    },
    "docker.traefik-forward-auth": {
      "entryPoints": ["https"],
      "service": "traefik-forward-auth",
      "rule": "Host(`auth.sub.domain.com`)"
    },
    "file.synology": {
      "entryPoints": ["https", "http"],
      "middlewares": ["forward-auth"],
      "service": "synology",
      "rule": "Host(`synology.sub.domain.com`)",
      "tls": {}
    }
  },
  "middlewares": {
    "docker.forward-auth": {
      "forwardAuth": {
        "address": "http://traefik-forward-auth:4181",
        "authResponseHeaders": ["X-Forwarded-User"]
      }
    },
    "docker.hello-auth": {
      "forwardAuth": {
        "address": "http://traefik-forward-auth:4181",
        "authResponseHeaders": ["X-Forwarded-User", "X-Forwaded-Host"]
      }
    },
    "file.forward-auth": {
      "forwardAuth": {
        "address": "http://traefik-forward-auth:4181",
        "authResponseHeaders": ["X-Forwarded-User", "X-Forwarded-Host"]
      },
      "usedBy": ["file.synology"]
    }
  },
  "services": {
    "docker.hello-auth": {
      "loadbalancer": {
        "servers": [{ "url": "http://172.18.0.2:80" }],
        "passHostHeader": true
      },
      "usedBy": ["docker.hello-auth"],
      "serverStatus": { "http://172.18.0.2:80": "UP" }
    },
    "docker.hello-http": {
      "loadbalancer": {
        "servers": [{ "url": "http://172.18.0.11:80" }],
        "passHostHeader": true
      },
      "usedBy": ["docker.hello-http"],
      "serverStatus": { "http://172.18.0.11:80": "UP" }
    },
    "docker.traefik-forward-auth": {
      "loadbalancer": {
        "servers": [{ "url": "http://172.18.0.9:4181" }],
        "passHostHeader": true
      },
      "usedBy": ["docker.traefik-forward-auth"],
      "serverStatus": { "http://172.18.0.9:4181": "UP" }
    },
    "file.synology": {
      "loadbalancer": {
        "servers": [{ "url": "http://192.168.1.60:5000" }],
        "passHostHeader": false
      },
      "usedBy": ["file.synology"],
      "serverStatus": { "http://192.168.1.60:5000": "UP" }
    }
  }
}

```

**Comment by ldez** [comment]
The middleware need to be explicitly associated with the router.
```
labels:
      - "traefik.http.routers.my-container.middlewares=NameOfTheMiddleware@docker"
```

And middleware must have a name:

```yml
# Enable gzip compression
labels:
- "traefik.http.middlewares.test-compress.compress=true"
```

https://docs.traefik.io/v2.0/middlewares/compress/

**Comment by dduportal** [comment]
Hi @dalanmiller , with the latest 2.0 alpha 7, here is a proposal adapted configuration:

- Removed from the `traefik.toml` the `[global]` -> `debug` and `[docker]` -> `domain` directives as per https://docs.traefik.io/v2.0/reference/static-configuration/file/

- Adapted the labels to what @ldez said + alpha7 changes (associating the router to the middleware with the new naming convention for middlewares).

```yaml
version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.0.0-alpha7
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    restart: always
    # env_file: ./traefik.env
    labels:
      - "traefik.enable=false"

  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - SECRET=secret
      - AUTH_HOST=auth.sub.domain.com
      - COOKIE_DOMAIN=sub.domain.com
      - INSECURE_COOKIE=true
      - WHITELIST=me@email.com
      - LOG_LEVEL=debug
    labels:
      - traefik.enable=true
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

  hello-auth:
    container_name: hello-auth
    image: containous/whoami
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.hello-auth.rule=Host(`<DOMAIN>`)"
      - "traefik.http.routers.hello-auth.service=hello-auth"
      - "traefik.http.routers.hello-auth.entryPoints=http"
      - "traefik.http.routers.hello-auth.tls=false"
      - "traefik.http.routers.hello-auth.middlewares=hello-auth@docker"

      - "traefik.http.middlewares.hello-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.hello-auth.forwardauth.authresponseheaders=X-Forwarded-User"

      - "traefik.http.services.hello-auth.loadbalancer.server.port=80"
```

and 

```toml
[global]
  SendAnonymousUsage = false

[api]

[providers]
  [providers.file]
    watch=true

  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false

[entrypoints]
  [entrypoints.http]
    address = ":80"

  [entrypoints.https]
    address = ":443"
```

with this example on my local machine, I have a redirection happening. Can you let us know how does it behave?

**Comment by dalanmiller** [comment]
@dduportal I'm still getting the behavior where I end up with a 404 at `auth.sub.domain.com?state....`

Would you be able to share your `/api/rawdata` JSON when you have this going so I can compare? Very much appreciate your help in working through this!

**Comment by dalanmiller** [comment]
https://github.com/containous/traefik/blob/11f04a453ef9a255c4b6bd3cff7e1938ee3e16ba/pkg/middlewares/auth/forward.go#L117-L147

I seem to be triggering the above block given I'm seeing the following in the my logs:

```
traefik                 | time="2019-06-28T13:05:35Z" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 307" middlewareName=hello-auth@docker middlewareType=ForwardedAuthType
```

Which is weird since it's sending the initial redirect to the google oauth page. Moving forward with the auth process which ends in a `404`:

```
traefik                 | 192.168.1.1 - - [28/Jun/2019:13:05:35 +0000] "GET / HTTP/1.1" 307 467 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" 1 "hello-auth@docker" - 2ms
traefik                 | 192.168.1.1 - - [28/Jun/2019:13:14:12 +0000] "GET /_oauth?state=state_value&code=code_value&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&session_state=session_state_value&prompt=none HTTP/1.1" 404 19 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" 3 - - 0ms
```

**Comment by dalanmiller** [comment]
I've since tried:

❌ Completely resetting my OAuth 2.0 Client ID settings  / credentials under Google console.  
❌ Switching to `traefik-forward-auth` overlay mode to attempt to get _just_ `hello-auth.sub.domain.com` wo work and now get a `Not authorized` response from traefik.

**Comment by dduportal** [comment]
Hi @dalanmiller , here is the result with `alpha7`:

```json
{
  "routers": {
    "hello-auth@docker": {
      "entryPoints": [
        "http"
      ],
      "middlewares": [
        "hello-auth@docker"
      ],
      "service": "hello-auth",
      "rule": "Host(`<DOMAIN>`)"
    },
    "traefik-forward-auth_forward-auth@docker": {
      "entryPoints": null,
      "service": "traefik-forward-auth",
      "rule": "Host(`traefik-forward-auth-forward-auth`)"
    }
  },
  "middlewares": {
    "hello-auth@docker": {
      "forwardAuth": {
        "address": "http://traefik-forward-auth:4181",
        "authResponseHeaders": [
          "X-Forwarded-User"
        ]
      },
      "usedBy": [
        "hello-auth@docker"
      ]
    }
  },
  "services": {
    "hello-auth@docker": {
      "loadbalancer": {
        "servers": [
          {
            "url": "http://172.18.0.4:80"
          }
        ],
        "passHostHeader": true
      },
      "usedBy": [
        "hello-auth@docker"
      ],
      "serverStatus": {
        "http://172.18.0.4:80": "UP"
      }
    },
    "traefik-forward-auth@docker": {
      "loadbalancer": {
        "servers": [
          {
            "url": "http://172.18.0.3:4181"
          }
        ],
        "passHostHeader": true
      },
      "usedBy": [
        "traefik-forward-auth_forward-auth@docker"
      ],
      "serverStatus": {
        "http://172.18.0.3:4181": "UP"
      }
    }
  }
}
```

you can (and should) totally run the example I gave below to reproduce it locally, and check if you get the same output.

**Comment by dalanmiller** [comment]
@dduportal I see that this is automatically being created as a route for the middleware:

      "rule": "Host(`traefik-forward-auth-forward-auth`)"

How can I specify what I _want_ this to be? I think this is the problem as I need to tell Google which sub domain to route back to, and it's being dynamically generated. 

Also how can this possibly worth if the auto generated route doesn't have any entrypoints? 🤔

**Comment by dduportal** [comment]
Hi @dalanmiller , this rule is the default one (reference https://docs.traefik.io/v2.0/providers/docker/#defaultrule) for the service `traefik-forward-auth-forward-auth` in the `docker-compose.yml`, as there is no label `traefik.http.routers.hello-auth.rule=Host(...)"` defined, my mistake.

My understanding is that this service should have the label `traefik.enable=false` only, as you are not using a "central auth" - https://github.com/thomseddon/traefik-forward-auth#advanced , right?

**Comment by dalanmiller** [comment]
@dduportal nay. It should be enabled[0] as it needs to properly route the request depending on whether it's authenticated or not. And then, post authentication somewhere, it needs to route to the correct host. The sample config is exactly what I'm trying to achieve. 

[0] - https://github.com/thomseddon/traefik-forward-auth/blob/master/examples/docker-compose-auth-host.yml#L38

**Comment by dduportal** [comment]
Hi @dalanmiller , if my understanding is correct, the service `traefik-forward-auth` has to be exposed through Traefik to handle the oauth redirection. 
Then we (I am the source of the error :) ) are missing a few labels on this service.

Please find below an example with the latest beta1. Can you try it on your side please?

* `docker-compose.yml`:
```yml
version: "3"
services:
  traefik:
    image: traefik:v2.0.0-beta1
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - --providers.docker.exposedByDefault=false
      - --api
      - --entrypoints.http.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - SECRET=secret
      - AUTH_HOST=auth.sub.domain.com
      - COOKIE_DOMAIN=sub.domain.com
      - INSECURE_COOKIE=true
      - WHITELIST=me@email.com
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forward-auth.rule=Host(`auth.sub.domain.com`)"
      - "traefik.http.routers.forward-auth.service=forward-auth-svc"
      - "traefik.http.services.forward-auth-svc.loadbalancer.server.port=4181"

  hello-auth:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-auth.rule=Host(`sub.domain.com`)"
      - "traefik.http.routers.hello-auth.service=hello-auth"
      - "traefik.http.routers.hello-auth.middlewares=hello-auth@docker"
      - "traefik.http.middlewares.hello-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.hello-auth.forwardauth.authresponseheaders=X-Forwarded-User"
      - "traefik.http.services.hello-auth.loadbalancer.server.port=80"
```

* Accessing the webapp gives me this (already working ofr you as I understand):

```shell
curl -v -H "Host: sub.domain.com" http://localhost
* Rebuilt URL to: http://localhost/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: sub.domain.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Content-Length: 381
< Content-Type: text/html; charset=utf-8
< Date: Wed, 24 Jul 2019 13:39:33 GMT
< Location: https://accounts.google.com/o/oauth2/auth?client_id=client_id&redirect_uri=http%3A%2F%2Fauth.sub.domain.com%2F_oauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=a2ce7bcb3d80bdc8abab27778a060345%3Ahttp%3A%2F%2Fsub.domain.com%2F
< Set-Cookie: _forward_auth_csrf=a2ce7bcb3d80bdc8abab27778a060345; Path=/; Domain=sub.domain.com; Expires=Thu, 25 Jul 2019 01:39:33 GMT; HttpOnly
< 
<a href="https://accounts.google.com/o/oauth2/auth?client_id=client_id&amp;redirect_uri=http%3A%2F%2Fauth.sub.domain.com%2F_oauth&amp;response_type=code&amp;scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&amp;state=a2ce7bcb3d80bdc8abab27778a060345%3Ahttp%3A%2F%2Fsub.domain.com%2F">Temporary Redirect</a>.

* Connection #0 to host localhost left intact
```

* Trying the redirection given by the oauth, that lead to HTTP/404 before (TL;DR; it works now that the forward-auth service has the right labels):

```shell
curl -v -H "Host: auth.sub.domain.com" "http://localhost/_oauth&response_type=code&scope=https://www.googl
eapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email&state=a2ce7bcb3d80bdc8abab27778a060345:http://sub.domain.com/"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)> GET /_oauth&response_type=code&scope=https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email&state=a2ce7bcb3
d80bdc8abab27778a060345:http://sub.domain.com/ HTTP/1.1
> Host: auth.sub.domain.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Length: 234
< Content-Type: text/html; charset=utf-8
< Date: Wed, 24 Jul 2019 13:43:01 GMT< Location: /_oauth&response_type=code&scope=https:/www.googleapis.com/auth/userinfo.profile+https:/www.googleapis.com/auth/userinfo.email&state=a2ce7
bcb3d80bdc8abab27778a060345:http:/sub.domain.com/
< <a href="/_oauth&amp;response_type=code&amp;scope=https:/www.googleapis.com/auth/userinfo.profile+https:/www.googleapis.com/auth/userinfo.email&amp;st
ate=a2ce7bcb3d80bdc8abab27778a060345:http:/sub.domain.com/">Moved Permanently</a>.

* Connection #0 to host localhost left intact
```
