### ISSUE TITLE
Docker Networking in 2.0 alpha not working

### ISSUE THREAD

**Issue by RPfist** [containous/traefik#4978]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?
I use Docker as the provider and for each service that I use I have a own docker-compose file.Thats necessary because some services I use need a external database and docker-compose creates a network for each of them so i don't get any conflicts with the ports of each database instance. Then I specify with the traefik.docker.network label the docker network which is created by docker-compose for my new service.

### What did you expect to see?
I can access the service with the host I provided with the traefik.http.routers.nginx1.rule=Host(`locale.server.nginx`) label in my docker-compose file of the service.

### What did you see instead?
I get a Gateway timeout. It only works when the service and the Traefik instance are in the same docker-network.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run traefik:v2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
docker-compose of Traefik 
```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api --providers.docker
    ports:
      - "80:80" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
docker-compose of service
```yaml
version: '3'

services:
 ngnix:
   image: nginx
   labels:
      - traefik.http.routers.nginx1.rule=Host(`locale.server.nginx`)
      - traefik.docker.network=nginx_default
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
