### ISSUE TITLE
TCP proxy for MySQL connection (v2.0)

### ISSUE THREAD

**Issue by cassvail** [containous/traefik#4981]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Using docker-compose and traefik.toml to expose a mysql database through a local domain name.
The final goal is to connect to multiple database with different domain names using the same standard port 3306.
I'm am not sure if I'm missing something from the configuration or it's actually an issue.

### What did you expect to see?

Establish a connection to the database using as host
`mysql.api.local` or `mysql.api.local:3306`

### What did you see instead?

Connection error / timeout

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
    address = ":8080"
  [entryPoints.mysql]
    address = ":3306"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

[docker]
domain = "local"
watch = true
```

docker-compose.yml
```yml
version: '3'

services:
  reverseproxy:
    image: traefik:2.0-alpine
    command: --api --providers.docker
    ports:
      - 80:80
      - 8080:8080
      - 3306:3306
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - traefik
  mysql:
    image: mysql:5.7.21
    volumes:
      - ./_data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: mysql.api.local
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`mysql.api.local`)"
      - "traefik.tcp.routers.mysql.entryPoints=mysql"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
```

http://localhost:8080/api/rawdata output
```json
{
  "docker": {
    "HTTP": {
      "routers": {
        "reverseproxy_traefik": {
          "entryPoints": null,
          "service": "reverseproxy_traefik",
          "rule": "Host(`reverseproxy-traefik`)"
        }
      },
      "services": {
        "reverseproxy_traefik": {
          "loadbalancer": {
            "servers": [
              {
                "url": "http://172.29.0.2:80",
                "weight": 1
              }
            ],
            "method": "wrr",
            "passHostHeader": true
          }
        }
      }
    },
    "TCP": {
      "routers": {
        "mysql": {
          "entryPoints": [
            "mysql"
          ],
          "service": "mysql_traefik",
          "rule": "HostSNI(`mysql.api.local`)"
        }
      },
      "services": {
        "mysql_traefik": {
          "loadbalancer": {
            "servers": [
              {
                "address": "172.29.0.3:3306",
                "weight": 1
              }
            ],
            "method": "wrr"
          }
        }
      }
    },
    "TLSOptions": null,
    "TLSStores": null
  }
}
```

Thanks!
