### ISSUE TITLE
[Docs] v2 File provider - Load balancer weight must be explicitly provided

### ISSUE THREAD

**Issue by polarathene** [containous/traefik#4986]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Lost many hours trying to figure out why I couldn't get the file provider to route to a service working. I followed the examples in the docs, and searched online for examples of why other users might always be hitting `Internal Server Error`.

### What did you expect to see?

A valid response from my service which I could curl just fine directly.

### What did you see instead?

`Internal Service Error` + 500 status code (only if config enables access log).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha4
Codename:     faisselle
Go version:   go1.12.4
Built:        2019-04-17T11:38:21Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

**traefik_static.toml:**

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
  [providers.file]
    watch = true
    filename = "/config/traefik_dynamic.toml"
```

**traefik_dynamic.toml:**

```toml
[providers.file]

[http]
  [http.routers]
    [http.routers.router0]
      entryPoints = ["web"]
      service = "whoami"
      rule = "Host(`test.localhost`)"

  [http.services]
    [http.services.whoami.LoadBalancer]
     [[http.services.whoami.LoadBalancer.servers]]
        url = "http://service-hostname"
```

**docker-compose.yml:**

```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - $PWD/traefik_static.toml:/etc/traefik/traefik.toml
      - $PWD/traefik_dynamic.toml:/config/traefik_dynamic.toml
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
8.16.32.64 - - [20/Jun/2019:10:45:47 +0000] "GET / HTTP/1.1" 500 21 "-" "curl/7.58.0" 1 "file.router0" - 0ms
```

---

## Solution

Apparently, the way to fix this is ["expected" with v2](https://github.com/containous/traefik/issues/4828#issuecomment-503975556), but [isn't documented at all](https://docs.traefik.io/v2.0/routing/services/). 

Note the example for a single server, and the lack of any mention of weights being required(I noticed in the rawdata API that they weights were assigned a value of `0`, but wasn't sure how that was treated as 0 can mean no specific amount/limit in some software).

Just need to document that a weight value of `1` needs to be included.

```toml
  [http.services]
    [http.services.whoami.LoadBalancer]
     [[http.services.whoami.LoadBalancer.servers]]
        url = "http://service-hostname"
        weight = 1
```
