### ISSUE TITLE
500 Error trying to move web-ui to a prefix-path

### ISSUE THREAD

**Issue by docwhat** [containous/traefik#4994]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I used this:

```yaml
version: "3"

services:

  traefik:
    container_name: "traefik"
    image: traefik # The official Traefik docker image
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTP port
      - "9081:8080" # The Web UI (enabled by --api)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/srv/containers/traefik.toml:/traefik.toml:ro"
      - "/srv/containers/acme.json:/acme.json:rw"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:example.com;PathPrefixStrip:/traefik/"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
    read_only: true
    restart: "unless-stopped"
```

### What did you expect to see?

I expected the prefix to work.

### What did you see instead?

```
< HTTP/2 500
< content-type: text/plain; charset=utf-8
< content-length: 21
< date: Fri, 21 Jun 2019 02:39:31 GMT
<
* Connection #0 to host example.com left intact
Internal Server Error
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
# logLevel = "ERROR"
# logLevel = "WARNING"
logLevel = "INFO"
defaultEntryPoints = ["https", "http"]
sendAnonymousUsage = true

[api]
entrypoint = "traefik"
dashboard = true

[api.statistics]
recentErrors = 10

[acme]
# ....

[acme.tlsChallenge]

[entryPoints]

[entryPoints.http]
address = ":80"

[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

[entryPoints.traefik]
address = ":8080"

[entryPoints.traefik.tls]

[entryPoints.traefik.auth]

# ... and so on
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="Basic auth succeeded"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/health\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/health\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}" ForwardURL="http://172.18.0.6:8080"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.6:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.6:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="http: TLS handshake error from 172.18.0.6:33444: tls: first record does not look like a TLS handshake"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\""
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://172.18.0.6:8080, code: 500, Length: 21, duration: 1.804853ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:example.com"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.6:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.6:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}"
traefik            | time="2019-06-21T02:46:11Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/health\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Basic ZG9jd2hhdDpmaXNoY2FrZQ==\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Prefix\":[\"/traefik/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"72.77.16.240:55037\",\"RequestURI\":\"/health\",\"TLS\":null}"
```
