### ISSUE TITLE
Global default backend picks wrong container

### ISSUE THREAD

**Issue by atombender** [containous/traefik#5000]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you expect to see?

I have a global default backend ingress on Kubernetes:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: default-http-backend
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
```

And a deployment that contains two containers: Nginx on port, and a Prometheus exporter on port 9113. (See below for whole configs.) When Traefik encounters an unknown route, it routes the request to the _Prometheues exporter_ on port 9113, not the service port:

```
{
  "BackendAddr": "10.4.10.40:9113",
  "BackendName": "global-default-backend",
  "BackendURL": {
    "Scheme": "http",
    "Opaque": "",
    "User": null,
    "Host": "10.4.10.40:9113",
    "Path": "",
    "RawPath": "",
    "ForceQuery": false,
    "RawQuery": "",
    "Fragment": ""
  },
  "ClientAddr": "24.185.165.247:57546",
  "ClientHost": "24.185.165.247",
  "ClientPort": "57546",
  "ClientUsername": "-",
  "DownstreamContentSize": 152,
  "DownstreamStatus": 200,
  "DownstreamStatusLine": "200 OK",
  "Duration": 4540619,
  "FrontendName": "global-default-frontend",
  "OriginContentSize": 152,
  "OriginDuration": 3150646,
  "OriginStatus": 200,
  "OriginStatusLine": "200 OK",
  "Overhead": 1389973,
  "RequestAddr": "njshore.events",
  "RequestContentSize": 0,
  "RequestCount": 141026,
  "RequestHost": "njshore.events",
  "RequestLine": "GET / HTTP/2.0",
  "RequestMethod": "GET",
  "RequestPath": "/",
  "RequestPort": "-",
  "RequestProtocol": "HTTP/2.0",
  "RetryAttempts": 0,
  "StartLocal": "2019-06-21T14:36:12.579476907Z",
  "StartUTC": "2019-06-21T14:36:12.579476907Z",
  "downstream_Content-Length": "152",
  "downstream_Content-Type": "text/html; charset=utf-8",
  "downstream_Date": "Fri, 21 Jun 2019 14:36:12 GMT",
  "level": "info",
  "msg": "",
  "origin_Content-Length": "152",
  "origin_Content-Type": "text/html; charset=utf-8",
  "origin_Date": "Fri, 21 Jun 2019 14:36:12 GMT",
  "request_Accept": "*/*",
  "request_User-Agent": "curl/7.54.0",
  "time": "2019-06-21T14:36:12Z"
}
```

Notice the `"Host":"10.4.10.40:9113"`.

The service and its endpoints are correct:

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  name: default-http-backend
  selfLink: /api/v1/namespaces/production/endpoints/default-http-backend
subsets:
- addresses:
  - ip: 10.4.10.69
    nodeName: gke-primary-n1s4-100gb-a-3448e7c0-rckw
    targetRef:
      kind: Pod
      name: default-http-backend-595b4f998b-6m8xd
      namespace: production
      resourceVersion: "258065182"
      uid: 0c4ff0d4-9435-11e9-84bf-42010a8e023e
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: exporter
    port: 9113
    protocol: TCP
```

### What did you see instead?

Traefik should route traffic to service por t80.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

#### Deployment

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: null
  generation: 1
  labels:
    app: default-http-backend
  name: default-http-backend
  selfLink: /apis/extensions/v1beta1/namespaces/production/deployments/default-http-backend
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: default-http-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: default-http-backend
    spec:
      containers:
      - image: nginx:1.13.0
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 10m
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/404.html
          name: config
          readOnly: true
          subPath: 404.html
        - mountPath: /etc/nginx/nginx.conf
          name: config
          readOnly: true
          subPath: nginx.conf
      - args:
        - -nginx.scrape_uri=http://127.0.0.1/nginx_status
        image: fish/nginx-exporter:v0.1.0
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9113
          name: exporter
          protocol: TCP
        resources:
          limits:
            cpu: 10m
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: default-http-backend
        name: config
status: {}
```

#### Service

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9113"
    prometheus.io/probe: "true"
    prometheus.io/probemodule: http_2xx
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  creationTimestamp: null
  name: default-http-backend
  selfLink: /api/v1/namespaces/production/services/default-http-backend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: exporter
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: default-http-backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
