### ISSUE TITLE
Helm fails with "Upgrade request required" when running Rancher v2 behind Traefik

### ISSUE THREAD

**Issue by tonnenpinguin** [containous/traefik#5011]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

This is an issue for an (unanswered) [stackoverflow question](https://stackoverflow.com/questions/52700583/helm-for-rancher-not-working-with-traefik) that I think constitutes a bug in traefik.

I used a very similar setup to what's mentioned in the stackoverflow question:

One box running both traefik (v1.7) and rancher (v2.2.4). I am using the docker provider to forward traffik to rancher and the kubernetes provider to tap into the rancher-managed cluster. This part is working fine.

However, helm consistently refuses to cooperate and throws an error `error: error upgrading connection: Upgrade request required`. This happens on all helm commands.

The same happens when manually trying to get the port forwarding to work using `kubectl -n kube-system port-forward tiller-deploy-xxx 44134:44134`.

All other kubectl commands I tried work as expected.

### What did you expect to see?
I expected traefik to work with helm and forward the ports when requested (just like nginx does)

### What did you see instead?
Helm returning `error: error upgrading connection: Upgrade request required`

This might be related to https://github.com/helm/helm/issues/2419

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[accessLog]

[acme]
acmeLogging = true
email = "<EMAIL>"
storage = "acme.json"
entrypoint = "https"

  [acme.dnsChallenge]
  provider = "<PROVIDER>"
  delayBeforeCheck = 10

[[acme.domains]]
  main = "*.<DOMAIN>"
  sans = ["<DOMAIN>"]

[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "<DOMAIN>"
watch = true
exposedbydefault = false

[kubernetes]
endpoint = "<ENDPOINT>"
token = "<TOKEN>"
certAuthFilePath = "ca.crt"
namespaces = ["default"]
```

Docker compose file

```yaml
version: '2'

services:
  traefik:
    image: traefik:v1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
      - /opt/traefik/ca.crt:/ca.crt
    container_name: traefik
    env_file:
      - /opt/traefik/.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:traefik.<DOMAIN>"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=<BASIC_AUTH>"

  rancher2:
    image: rancher/rancher:latest
    container_name: rancher2
    volumes:
      - /opt/rancher/data/rancher:/var/lib/rancher
    networks:
      - web
    command: --no-cacerts
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rancher"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rancher.<DOMAIN>"
      - "traefik.port=80"

networks:
  web:
    external: true

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Short version (standard debug level)
<REMOTE_IP> - - [24/Jun/2019:14:17:05 +0000] "GET /k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller HTTP/2.0" 200 3322 "-" "helm/v0.0.0 (linux/amd64) kubernetes/$Format" 1011 "Host-rancher-xyz-1" "http://<IP>:80" 21ms
<REMOTE_IP> - - [24/Jun/2019:14:17:05 +0000] "POST /k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward HTTP/1.1" 400 139 "-" "Go-http-client/1.1" 1012 "Host-rancher-xyz-1" "http://<IP>:80" 21m

Long version (debug level "debug")
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}" ForwardURL="http://<IP>:80"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://<IP>:80, code: 200, Length: 3322, duration: 38.739521ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:rancher.<DOMAIN>"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, */*\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"<TOKEN>\"],\"User-Agent\":[\"helm/v0.0.0 (linux/amd64) kubernetes/$Format\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38194\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller\",\"TLS\":null}"
<REMOTE_IP> - - [24/Jun/2019:14:21:19 +0000] "GET /k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller HTTP/2.0" 200 3322 "-" "helm/v0.0.0 (linux/amd64) kubernetes/$Format" 7 "Host-rancher-xyz-1" "http://<IP>:80" 41ms
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}" ForwardURL="http://<IP>:80"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://<IP>:80, code: 400, Length: 139, duration: 20.495548ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:rancher.<DOMAIN>"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"<IP>:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}"
time="2019-06-24T14:21:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Authorization\":[\"<TOKEN>\"],\"Connection\":[\"Upgrade\"],\"Content-Length\":[\"0\"],\"Upgrade\":[\"SPDY/3.1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Stream-Protocol-Version\":[\"portforward.k8s.io\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"rancher.<DOMAIN>\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REMOTE_IP>:38196\",\"RequestURI\":\"/k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward\",\"TLS\":null}"
<REMOTE_IP> - - [24/Jun/2019:14:21:19 +0000] "POST /k8s/clusters/<CLUSTER>/api/v1/namespaces/kube-system/pods/tiller-deploy/portforward HTTP/1.1" 400 139 "-" "Go-http-client/1.1" 8 "Host-rancher-xyz-1" "http://<IP>:80" 24ms

```
