### ISSUE TITLE
TCP Router Rule with Host(`hostname`) leads to Error unknown rule

### ISSUE THREAD

**Issue by RPfist** [containous/traefik#5016]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
created a docker-compose file where I tried to add a TCP router for a MySQL database to access it via the hostname without exposing the port of the database itself.

### What did you expect to see?
Accessing the database via hostname over tcp

### What did you see instead?
An error in the JSON of the endpoint ip:port/api/rawdata

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.0 (alpha 7) DOCKER
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api --providers.docker
    ports:
      - "80:80"
      - "8081:8080"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    labels:
      - traefik.TCP.Routers.db.Rule=Host(`localhost`)
      - traefik.TCP.Services.db.LoadBalancer.server.Port=3306
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```json
  "tcpRouters": {
    "db@docker": {
      "entryPoints": null,
      "service": "db",
      "rule": "Host(`localhost`)",
      "error": "unknown rule Host(`localhost`)"
    }
  },
  "tcpServices": {
    "db@docker": {
      "loadbalancer": {
        "servers": [
          {
            "address": "172.21.0.2:3306"
          }
        ]
      },
      "usedBy": [
        "db@docker"
      ]
    }
  }
```
