### ISSUE TITLE
Traefik crash during/after swarm manager unavailbility

### ISSUE THREAD

**Issue by FireDrunk** [containous/traefik#5029]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
Patch the Docker UCP Manager

### What did you expect to see?
Working traefik

### What did you see instead?
Crashed / Hanging Traefik, needed redeployment before working again.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]

#############
#debug = true
#############

[docker]
watch = true
swarmMode = true
exposedbydefault = false
network = "public"

[docker.tls]
ca = "/run/secrets/ucp/ca.pem"
cert = "/run/secrets/ucp/cert.pem"
key = "/run/secrets/ucp/key.pem"
insecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.api]
    address = ":8080"
    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
        users = [
          "admin:*snip*"
        ]

  [entryPoints.metrics]
    address = ":8081"

  [entryPoints.ping]
    address = ":8082"

[api]
entrypoint = "api"

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"

[ping]
entrypoint = "ping"

[accessLog]
format = "json"
```
The Docker UCP Manage endpoint gets passed with the traefik startup.
`--docker.endpoint=tcp://<ucp-manager-dns-alias>:8443`
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
Debug logging wasn't enabled at the time.

Some more backstory:
We are running Traefik against Docker EE (UCP), via port 8443. Sometimes we have to patch, and the manager goes down for some time (usually less than 30 seconds). Traefik is usually fine with this, and just spews some errors that it lost it's connection to the docker engine, but keeps routing traffic, which is correct, because we patch the UCP Manager seperate from the UCP Workers, so containers are all online.

This morning, during patching in our testing environment, Traefik crashed during the restart of the manager.

This might not be a bug report, but I'm trying to find out how to mitigate this.
To understand this, I'm looking at the source code, and I'm trying to find the way Traefik handles unavailability of internal providers. Specifically these lines:
https://github.com/containous/traefik/blob/15b5433f1a095167134bf746f9c581d4a93eabf3/pkg/provider/docker/docker.go#L149
https://github.com/containous/traefik/blob/15b5433f1a095167134bf746f9c581d4a93eabf3/pkg/provider/docker/docker.go#L197

What happens when during this refresh interval, the provider is not responding?

We have not touched the default refresh interval, and we don't intend to (we are perfectly find with the default). We would just like to be able to set the timeout of the connection, which could be several minutes worst case (full manager reboot).
