### ISSUE TITLE
TLSOptions don't get applied - Traefik v2 with docker provider

### ISSUE THREAD

**Issue by Reamer** [containous/traefik#5032]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Using docker-compose to manage traefik. Have configured the docker and acme provider. After this a created some more services with docker-compose
Part of my config
```
version: '3.7'

services:
...
  web:
    build: ./web
    restart: always
    labels:
      - traefik.domain=nextcloud.example.com
      - traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.example.com`)
      - traefik.http.routers.nextcloud-http.EntryPoints=http
      - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.example.com`)
      - traefik.http.routers.nextcloud-https.EntryPoints=https
      - traefik.http.routers.nextcloud-https.tls=true
      - traefik.http.routers.nextcloud-https.tls.options=foo
      - traefik.http.routers.nextcloud-http.middlewares=nextcloud-redirect
      - traefik.http.middlewares.nextcloud-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.nextcloud-redirect.redirectscheme.permanent=true
      - traefik.enable=true
      - traefik.docker.network=web
    expose:
      - 80
...
```
### What did you expect to see?

My tls.options (`foo`) defined with a docker label, should be linked to the tls.options definition in my main configuration file.

### What did you see instead?

```
traefik_1  | time="2019-06-26T19:48:03+02:00" level=debug msg="unknown TLS options: foo@docker" entryPointName=https routerName=nextcloud-https@docker
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.0.0-alpha7 built on 2019-06-21T15:59:46Z"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My configuration
```toml
[Global]
    sendAnonymousUsage = true
[entrypoints]
  [entrypoints.http]
    address = ":80"
  [entrypoints.https]
    address = ":443"

[log]
  level = "DEBUG"
################################################################
# API and dashboard configuration
################################################################
[api]
  dashboard = true
################################################################
# Docker configuration backend
################################################################
[providers]
   [providers.docker]
     watch = true
     endpoint = "unix:///var/run/docker.sock"
     exposedByDefault = false
     swarmMode = false
[acme]
  email = "mymailexample.com"
  entryPoint = "https"
  acmeLogging = true
  onHostRule = true
  storage = "/etc/traefik/acme/acme.json"
  [acme.httpChallenge]
    entryPoint = "http"

[TLSOptions]

  [TLSOptions.foo]
    MinVersion = "VersionTLS12"
  [TLSOptions.default]
    MinVersion = "VersionTLS13"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```# docker-compose up --force-recreate 
Recreating traefik_traefik_1 ... done
Attaching to traefik_traefik_1
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="Traefik version 2.0.0-alpha7 built on 2019-06-21T15:59:46Z"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Static configuration loaded {\"Global\":{\"CheckNewVersion\":true,\"SendAnonymousUsage\":true},\"ServersTransport\":{\"InsecureSkipVerify\":false,\"RootCAs\":null,\"MaxIdleConnsPerHost\":200,\"ForwardingTimeouts\":null},\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}}},\"Providers\":{\"ProvidersThrottleDuration\":2000000000,\"Docker\":{\"Constraints\":\"\",\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15000000000},\"File\":null,\"Marathon\":null,\"Kubernetes\":null,\"KubernetesCRD\":null,\"Rest\":null,\"Rancher\":null},\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"Statistics\":null,\"Middlewares\":null},\"Metrics\":null,\"Ping\":null,\"Log\":{\"Level\":\"DEBUG\",\"format\":\"common\"},\"AccessLog\":null,\"Tracing\":null,\"HostResolver\":null,\"ACME\":{\"Email\":\"mymailexample.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"/etc/traefik/acme/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"RSA4096\",\"OnHostRule\":true,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null}}"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="\nStats collection is enabled.\nMany thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.\nHelp us improve Traefik by leaving this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No default certificate, generate one"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Start TCP Server" entryPointName=https
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Start TCP Server" entryPointName=http
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Start TCP Server" entryPointName=traefik
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="Starting provider *docker.Provider {\"Constraints\":\"\",\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}`)\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15000000000}"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="Starting provider *acme.Provider {\"Email\":\"mymailexample.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"/etc/traefik/acme/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"RSA4096\",\"OnHostRule\":true,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null,\"Store\":{}}"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=info msg="Testing certificate renew..." providerName=acme
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Configuration received from provider ACME: {\"HTTP\":{},\"TCP\":null,\"TLSOptions\":null,\"TLSStores\":null}" providerName=ACME
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Provider connection established with docker 18.09.6 (API 1.39)" providerName=docker
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No store is defined to add the certificate MIIGaDCCBVCgAwIBAgISA1AklLVG+HfO4s+CamwsTr7fMA0GCS, it will be added to the default store."
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) traefik.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No store is defined to add the certificate MIIGazCCBVOgAwIBAgISA2mdYkBdOp3OL7bFGwyd5E0mMA0GCS, it will be added to the default store."
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) grafana.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No store is defined to add the certificate MIIGYTCCBUmgAwIBAgISA0ZbRXKGzBB7Q9odIqGMY31iMA0GCS, it will be added to the default store."
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) www.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No store is defined to add the certificate MIIGbjCCBVagAwIBAgISA/yY9jN2SEmQKPiVzmExqcrbMA0GCS, it will be added to the default store."
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) nextcloud.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No default certificate, generate one"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" providerName=docker container=traefik_traefik-284c591c83b87d6dff4f62a6d7e6d8a7d77d1a81bc21e2c6e94f319459454626
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" container=cron_nextcloud-9f71f2f89979a5a351cc84e0c4b21e338da50336f0cef18f0be94421d2901d73 providerName=docker
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" providerName=docker container=app_nextcloud-809d59097b8afb9570adc7ba039db8bf30412516435bce9aaec03a6569e87aee
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" providerName=docker container=db_nextcloud-d61b6a8d207022049e3b1e2795c66d9c4fcdc7f954e5c927bc16d99e99645b53
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" container=redis_nextcloud-617f69090b57aee4704341b363b5a662f2c4bb53015e37e3c1df4259e55c2380 providerName=docker
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" providerName=docker container=influxdb_influxdb-71ca581651d56c0dff4bac1cad1b1a0b80e580d8cc32aa86114f1d2a439f1fb6
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Filtering disabled container" container=tor_tor-a530a71bcc09caf4e6a0fd7a996d5c8dbe42f42af47f9779c1bd256bd9c3e6a1 providerName=docker
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Configuration received from provider docker: {\"HTTP\":{\"routers\":{\"nextcloud-http\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"nextcloud-redirect\"],\"service\":\"web_nextcloud\",\"rule\":\"Host(`nextcloud.example.com`)\"},\"nextcloud-https\":{\"entryPoints\":[\"https\"],\"service\":\"web_nextcloud\",\"rule\":\"Host(`nextcloud.example.com`)\",\"tls\":{\"options\":\"foo\"}}},\"middlewares\":{\"nextcloud-redirect\":{\"redirectScheme\":{\"scheme\":\"https\",\"permanent\":true}}},\"services\":{\"web_nextcloud\":{\"loadbalancer\":{\"servers\":[{\"url\":\"http://172.22.0.2:80\"}],\"passHostHeader\":true}}}},\"TCP\":{},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) traefik.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) grafana.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) www.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="Adding certificate for domain(s) nextcloud.example.com"
traefik_1  | time="2019-06-26T20:19:52+02:00" level=debug msg="No default certificate, generate one"
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating middleware" entryPointName=http middlewareName=pipelining middlewareType=Pipelining routerName=nextcloud-http@docker serviceName=web_nextcloud
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating load-balancer" entryPointName=http routerName=nextcloud-http@docker serviceName=web_nextcloud
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating server 0 http://172.22.0.2:80" routerName=nextcloud-http@docker serverName=0 serviceName=web_nextcloud entryPointName=http
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Added outgoing tracing middleware web_nextcloud" middlewareName=tracing middlewareType=TracingForwarder entryPointName=http routerName=nextcloud-http@docker
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating middleware" entryPointName=http routerName=nextcloud-http@docker middlewareName=nextcloud-redirect@docker middlewareType=RedirectScheme
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Setting up redirection to https " entryPointName=http routerName=nextcloud-http@docker middlewareName=nextcloud-redirect@docker middlewareType=RedirectScheme
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Adding tracing to middleware" entryPointName=http routerName=nextcloud-http@docker middlewareName=nextcloud-redirect@docker
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=http
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating middleware" routerName=nextcloud-https@docker entryPointName=https serviceName=web_nextcloud middlewareName=pipelining middlewareType=Pipelining
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating load-balancer" serviceName=web_nextcloud routerName=nextcloud-https@docker entryPointName=https
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating server 0 http://172.22.0.2:80" entryPointName=https serverName=0 serviceName=web_nextcloud routerName=nextcloud-https@docker
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Added outgoing tracing middleware web_nextcloud" middlewareName=tracing entryPointName=https routerName=nextcloud-https@docker middlewareType=TracingForwarder
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Creating middleware" entryPointName=https middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="unknown TLS options: foo@docker" entryPointName=https routerName=nextcloud-https@docker
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Try to challenge certificate for domain [nextcloud.example.com] founded in HostSNI rule" providerName=acme routerName=nextcloud-https rule="Host(`nextcloud.example.com`)"
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="Looking for provided certificate(s) to validate [\"nextcloud.example.com\"]..." providerName=acme routerName=nextcloud-https rule="Host(`nextcloud.example.com`)"
traefik_1  | time="2019-06-26T20:19:53+02:00" level=debug msg="No ACME certificate generation required for domains [\"nextcloud.example.com\"]." providerName=acme routerName=nextcloud-https rule="Host(`nextcloud.example.com`)"```

**Comment by dtomcej** [comment]
Hello @Reamer,

When you reference a TLSOptions/middleware Options within docker, if you don't reference a provider, it assumes that you have created the object within the provider (aka within the docker labels).

https://docs.traefik.io/v2.0/middlewares/overview/#provider-namespace

Since you created the objects in your TOML, you need to enable the file provider

https://docs.traefik.io/v2.0/providers/file/

And then reference it via the file provider in your docker labels:

`traefik.http.routers.nextcloud-https.tls.options=foo@file`

Please let us know if that works for you.

**Comment by Reamer** [comment]
Hi @dtomcej 
Thanks for your fast response. Get it working with following changes in main configuration.
```toml
...
[providers]
   [providers.docker]
     watch = true
     endpoint = "unix:///var/run/docker.sock"
     exposedByDefault = false
     swarmMode = false
   [providers.file]
[acme]
...
[TLSOptions]
  [TLSOptions.mintls12]
    MinVersion = "VersionTLS12"
    sniStrict = true
  [TLSOptions.default]
    MinVersion = "VersionTLS13"
    sniStrict = true
```
When I change my docker label to
```
traefik.http.routers.nextcloud-https.tls.options=default@file
```
get again this message. Maybe a problem?
```
traefik_1  | time="2019-06-27T08:38:00+02:00" level=debug msg="unknown TLS options: default@file" entryPointName=https routerName=nextcloud-https@docker
```

After changing the docker label to 
```
traefik.http.routers.nextcloud-https.tls.options=mintls12@file
```
the configuration works :smile: 

If I start nextcloud without a `traefik.http.routers.nextcloud-https.tls.options` label the default tls options are used.
