### ISSUE TITLE
acme email is "required" but error or warn if not present

### ISSUE THREAD

**Issue by tabroughton** [containous/traefik#5039]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

(I'm using 1.7x config with 1.72)

### What did you do?

I have been registering new certificates with email set within the traefik.toml under the acme section but I would like to set acme email (for let's encrypt notifications etc) from docker compose - so I can have different applications (frontends) with different emails.

I tried a container label ``` - "traefik.acme.email=me@my.domain" ``` in docker-compose and checked the logs, there was no error and sure enough the label had been caught in the array ```allLabelsmap``` but I'm not sure that means traefik has used my configured email in the acme request as there are no messages that say which email is used when requesting a new certificate.  The docs do not say this is a configuration option so I assume it's not (though I would like it to be)... This is not the bug but I would like to know if it's possible.  The bug is:

To test further, I tried with no email in either the traefik.toml or the docker-compose.  Created all fresh containers. The logs for traefik shows the acme.provider starting up with no email (empty string).  When deploying my container app the request for certificate is made to let's encrypt, after the checks the certificate is issued. 

There are no warnings or errors that an email address wasn't present.

### What did you see instead?

- no warnings or errors between:

```
level=debug msg="Provider event received {...
```
(which is the start of the debug message of the caught docker container to apply traefik rules for)

and

```
...
time="2019-06-27T21:25:41Z" level=debug msg="Adding certificate for domain(s) host.my.domain"
time="2019-06-27T21:25:41Z" level=info msg="Server configuration reloaded on :80"
time="2019-06-27T21:25:41Z" level=info msg="Server configuration reloaded on :443"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik:alpine version
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[acme]
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

here is the acme section of the logs where the provider starts on traefik container start, you can see there is no email
```
...
level=info msg="Starting provider *acme.Provider {\"Email\":\"\",\"ACMELogging\":false,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":true,\"OnDemand\":false,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null,\"Store\":{}}"
time="2019-06-27T21:24:11Z" level=info msg="Testing certificate renew..."
time="2019-06-27T21:24:11Z" level=debug msg="Configuration received from provider ACME: {}"
...
```
