### ISSUE TITLE
Reload authentication usersFile on changes

### ISSUE THREAD

**Issue by marzzzello** [containous/traefik#5060]
### Do you want to request a *feature* or report a *bug*?
feature 

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I added basic/digest authentication to a frontend via `usersFile = "/path/to/.htdigest"`.
Then I started traefik. Then I added another user to the .htdigest.

### What did you expect to see?
That I can login with the new user.

### What did you see instead?
That I can not login with the new user. After I restarted Traefik I could login.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
containous/traefik:experimental-v1.7
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>
  <summary><b>traefik.toml</b></summary>

```toml
logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

sendAnonymousUsage = false

defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  directory = "/etc/traefik/rules/"
  watch = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "mydomain.tld"
  watch = true
  network = "traefik"
  exposedbydefault = false

[acme]
  email = "my@email.tld"
  storage="/etc/traefik/acme.json"
  entryPoint = "https"
  acmeLogging=true 
  [acme.dnsChallenge]
    provider = "netcup"
  [[acme.domains]]
    main = "*.mydomain.tld"
    sans = ["mydomain.tld"] 

[api]
  entryPoint = "traefik"
  dashboard = true
  [api.statistics]

[accessLog]
  filePath = "/etc/traefik/access.log"
    [accessLog.fields.names]
    "StartUTC" = "drop"
```
</details>

<details>
  <summary><b>docker-compose.yml</b></summary>

```yml
version: "3.6"
services:
  traefik:
    hostname: traefik
    image: containous/traefik:experimental-v1.7
    container_name: traefik
    restart: always
    domainname: ${DOMAIN0}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - netcup.env
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN0}, traefik.${DOMAIN1}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.auth.digest.usersFile=/shared/admin.htdigest"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./etc-traefik:/etc/traefik"
      - "./shared:/shared"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```
</details>

### If applicable, please paste the log output at DEBUG level (`--log.level=DEBUG` switch)
nothing relevant
