### ISSUE TITLE
Default certificate not being used?

### ISSUE THREAD

**Issue by MJPA** [containous/traefik#5071]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Tried changing the default certificate to a custom one using the following in traefik.yml:

```
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/default_cert.crt
        keyFile: /etc/traefik/default_cert.key
```

### What did you expect to see?

The certificate being used - ACME is disabled/not configured.

### What did you see instead?

The normal traefik default generated certificate was used - and so Chrome can't visit https sites.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha8
Codename:     faisselle
Go version:   go1.12.6
Built:        2019-07-01T17:46:52Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Config is above.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I do see `time="2019-07-08T17:06:31Z" level=debug msg="No default certificate, generate one"`
