### ISSUE TITLE
https and http to https redirect is not working with Kubernetes using traefik as ingress controller.

### ISSUE THREAD

**Issue by nistiwar** [containous/traefik#5076]
I am trying to make https and https redirect work with ingress, however to no avail since quiet sometime now. My ingress rule is as follows:
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "demo-ingress"
  namespace: "demo"
  labels:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: samplehost.example.com
    http:
     paths:
     - path: /
       backend:
         serviceName: ui
         servicePort: 80
     - path: /solr/
       backend:
         serviceName: cache
         servicePort: 8983
     - path: /VNF_DASHBOARD_BE/
       backend:
         serviceName: be
         servicePort: 80
  tls:
   - secretName: demo-tls-cert
```
Errors at traefik pods are as follows:
```
time="2019-07-10T03:34:43Z" level=error msg="Undefined entry point(s) 'https' for frontend http-https_samplehost.example.com/"
time="2019-07-10T03:34:43Z" level=error msg="Undefined entry point(s) 'https' for frontend http-https_samplehost.example.com/VNF_DASHBOARD_BE/"
time="2019-07-10T03:34:43Z" level=error msg="Undefined entry point(s) 'https' for frontend http-https_samplehost.example.com/solr/"
time="2019-07-10T03:34:43Z" level=error msg="error creating Frontend Redirect: unknown target entrypoint \"http\". Skipping frontend http-https_samplehost.example.com/..."
time="2019-07-10T03:34:43Z" level=error msg="error creating Frontend Redirect: unknown target entrypoint \"http\". Skipping frontend http-https_samplehost.example.com/VNF_DASHBOARD_BE/..."
time="2019-07-10T03:34:43Z" level=error msg="error creating Frontend Redirect: unknown target entrypoint \"http\". Skipping frontend http-https_samplehost.example.com/solr/..."
```
