### ISSUE TITLE
Traefik as Knative Ingress?

### ISSUE THREAD

**Issue by mishushakov** [containous/traefik#5081]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik support for Knative. Another, third-party product "Gloo" already did this, here are some links for reference:
https://medium.com/solo-io/gloo-by-solo-io-is-the-first-alternative-to-istio-on-knative-324753586f3a
https://knative.dev/docs/install/knative-with-gloo/

Traefik is serving me very well and I would love to use it with Knative.
Thank you so much!

**Comment by mpl** [comment]
@mishushakov Could you please elaborate on how you would see knative fit with Traefik? Are you asking if it could be another provider (such as the docker, and marathon ones)? Or could what you ask for be supported through the use of another CRD with the kubernetescrd provider?

**Comment by mishushakov** [comment]
Sure, @mpl
Unfortunately I'm not very informed about the technical implementation, since the technology is pretty new and I haven't explored the sources of it yet.

What I want as a user, is that someone, who works on Traefik will figure out, how Knative works with Ingress controllers and will add these capabilities to Traefik.

Since Gloo managed to do it (see the link above), there isn't any reason, why traefik shouldn't implement it as well.

Knative is very interesting piece of tech and I think many existing Traefik users will be looking to use it with Traefik instead of Istio. Wouldn't you like to be a part of that? Because Traefik seems to be the perfect candidate for Knative...

Thank you.

**Comment by ZCube** [comment]
I made it. It is possible to get routers and services.
https://github.com/ZCube/traefik/tree/knative-ingress

**Comment by SantoDE** [comment]
Hey @ZCube,

thanks for you work on that! Can I ask you to raise a PR with your changes? :)

**Comment by ZCube** [comment]
Hey @SantoDE.

I raised a PR! Is it OK? I have few experiences to raise a PR.

**Comment by johanbrandhorst** [comment]
What is the status of this? I would also like to see knative in traefik.

**Comment by bclermont** [comment]
As knative is becoming a standard, I really wish I could use it with traefik

**Comment by ricky26** [comment]
We're interested in using kNative too and currently enjoy using Traefik as our ingress. I had a go at writing an operator to convert the kNative resources into Traefik's Kubernetes CRDs but I think there's a core issue which isn't addressed by the PR: kNative needs to be able to add headers after traffic split (i.e. the headers can differ per service).

I'm game to contribute if I can help.

**Comment by sleighzy** [comment]
Hi. It looks like the development efforts on the linked PR have stalled. Is that work still something that will be actively pursued, or will this be implemented elsewhere?

**Comment by csabasulyok** [comment]
Also interested in this feature

**Comment by Richard87** [comment]
This feature would be epic, have been subscribed for a year on it!

Would make it way easier to run "serverless" on kubernetes without the heavy and complicated Istio stack!

**Comment by Wouter0100** [comment]
With the release of Knative 1.0, this becomes even more important :). We're "stuck" (not really stuck, just enjoying the rich feature set of Traefik) but we want to introduce Knative to this stack.

**Comment by sid-hbm** [comment]
what is the status of this work? Is there any documentation on how to install traefik on Minikube (and or k3s) and integrate it with KNative?

**Comment by ecda909** [comment]
What is the status of this work? Is there any other option for using knative alongside traefik?

**Comment by rtribotte** [comment]
Hello @ecda909,

We studied again the Knative support and unfortunately, we identified a blocker: Traefik does not support HTTP Headers manipulation for a given service.

Taking into account the following Ingress (generated by Knative):
```yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: Ingress
metadata:
  annotations:
    ...
spec:
  ...
  rules:
  - hosts:
    - hello.default.example.com
    http:
      paths:
      - splits:
        - appendHeaders:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: hello-00001
          percent: 50
          serviceName: hello-00001
          serviceNamespace: default
          servicePort: 80
        - appendHeaders:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: hello-00002
          percent: 50
          serviceName: hello-00002
          serviceNamespace: default
          servicePort: 80
    ...
status:
  ...
```

This would mean that Traefik should be able to add the `Knative-Serving-Namespace` or `Knative-Serving-Revision` with proper values associated with the targeted service.

As this is not possible, the request is not properly routed, which prevents Traefik from satisfying the Knative specification (as of now).
