### ISSUE TITLE
Slow api/dashboard when using setting auth.basic.usersFile 

### ISSUE THREAD

**Issue by mimamuh** [containous/traefik#5089]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

- Deploy `traefik@1.7` using `docker swarm`
- Enable the api and dashboard using `--api`
- Protecting the api using `basic.auth`
- Providing the user and password for `basic.auth` using the `basic.auth.usersFile` option.
- Providing the `usersFile` using `docker secret` or alternatively `docker config`:
```yml
- traefik.frontend.auth.basic.usersFile=/run/secrets/traefik_api_users_file
``` 

**Problem:** It seems using `basic.auth.usersFile` slows down the `api`. Requests take up to 30 s. The dashboard works but every request takes ages.

But when I change the setting providing the user credential via `auth.basic.users`:
```yml
# - traefik.frontend.auth.basic.usersFile=/run/secrets/traefik_api_users_file
- traefik.frontend.auth.basic=${TRAEFIK_API_USER:-admin}:${TRAEFIK_API_PASSWORD:-xyz-hash}
``` 
everything works fine. The dashboard loads fast. No issues.

### What did you expect to see?
Dashboard loads at the same speed independent if I provide the user credentials via `auth.basic.usersFile` or `auth.basic.users`.

### What did you see instead?
Loading the dashboard is super slow when I provide the user credentials via `auth.basic.usersFile`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker swarm stack file:
```yml
version: "3.7"
services:
  traefik:
    image: traefik:1.7-alpine
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # traefik dashboard
    command:
      - --docker
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.network=proxy
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
      - --entryPoints=Name:https Address::443 TLS
      - --entryPoints=Name:http Address::80 # don't force HTTPS
    secrets:
      - traefik_api_users_file
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:traefik.example.com
        - traefik.frontend.auth.basic
        - traefik.frontend.auth.basic.removeHeader=true
        - traefik.frontend.auth.basic.usersFile=/run/secrets/traefik_api_users_file
        # - traefik.frontend.auth.basic=${TRAEFIK_API_USER:-admin}:${TRAEFIK_API_PASSWORD:-xyz-hash}

networks:
  proxy:
    driver: overlay
    name: proxy

secrets:
  traefik_api_users_file:
    file: ./secrets/stack-file/traefik_api_users_file

```
