### ISSUE TITLE
New modifier section for pre-routing

### ISSUE THREAD

**Issue by geraldcroes** [containous/traefik#5098]
### Do you want to request a *feature* or report a *bug*?  
 Feature  
 
 ### What did you expect to see? 
We would like to be able to apply middleware prior to routing.
If the applied middleware would modify the request (e.g. headers), we would like to be able to route the initial request based on these modifications.

### Proposal - Add a modifier section

```toml
[http.modifiers]
   [http.modifiers.authentication]
      rule = "Host(`traefik.io`) && Path(`/protected`)"
      middleware = ["myAuthServer"]
      
[http.middlewares]
   [http.middlewares.myAuthServer.forwardauth]
      address = "someURL"
      authResponseHeaders = ["x-auth-result"]

[http.routers]
   [http.routers.unauthorized]
      rule = "Headers(`x-auth-result`, `unauthorized`)"
      service = "login"

   [http.routers.protectedPath]
      rule = "Host(`traefik.io`) && Path('/protected') && Headers(`x-auth-result`, `authorized`)"
      middleware = ["other-middleware"]
      service = "protectedService"
```
### More Information

Modifiers would act like a hook on given rules and be applied "after" TLS termination if the rule contains other information than the host itself (e.g. Path).

This modifier section could also be reused for other scenarios such as global redirection (e.g. schemeredirect)

```toml
[http.modifiers]
   [http.modifiers.https-redirect]
      rule = "Protocol(`http`)"
      middleware = ["scheme-https-only"]
```

**Comment by dtomcej** [comment]
Wouldn't `http.modifiers` and `http.middlewares` be confusing as to when they are operating?

Couldn't we use a `pre-match` or `post-match` style nomenclature to clear that up?

**Comment by cbanner** [comment]
> Wouldn't `http.modifiers` and `http.middlewares` be confusing as to when they are operating?

I agree that `modifiers` feels a bit ambiguous. I can't say that I have an intimate enough awareness of Traefik's architecture to offer a great suggestion but the model that's developed in my mind, as our team has experimented with this sort of integration, is that of middleware on the entrypoint vs. middleware on the router. The entrypoint seemed liked the most apparent entity preceding the branches of route selection.

That's a very HTTP-centric perspective I suppose but the key for viability, in my mind, is ensuring that the `pre-match` stage truly precedes any route selection. Or, in other words, that it's not a `pre-match` phase of a particular router but rather it's applied prior to match of any router.

**Comment by migolfi** [comment]
This looks great. The `modifiers` name might be ambiguous, although this approach looks great and would help solve a forward authentication use case. Another potential use case could be whitelisting or blacklisting on entrypoints to allow/block requests before they reach routing.

**Comment by ddtmachado** [comment]
Here is an alternative approach that just reuses the router structure while replacing the `service` field with a `target` that would include service, router and entrypoint as valid targets.

```yaml
## Dynamic config
http:
  routers:
    ## Regular service
    my-router:
      rule: "Host(`foo.internaldomain`) && ClientIP(`10.0.0.0/16`)"
      middlewares:
      - authorization #check user claims
      target:
        service: service-foo

    ## Direct router alias
    # Exactly as adding an OR operator on the original router, except 
    # it triggers another chain of middleware that may modify the request before
    my-router2:
      rule: "Host(`foo.externaldomain`)"
      middlewares:
      - authentication #authenticate user and inject claims
      target:
        router: my-router@docker
    
    ## Global Pre-Routing
    # Triggers middlewares then loopback to an entrypoint for evaluation
    my-router3:
      rule: "Host(`iot.externaldomain`)"
      middlewares:
      - check-headers
      - inject-keys
      target:
        entrypoint: web
```

**Comment by FireDrunk** [comment]
I think that would break internally, because middleware is applied at the router level?
If there are multiple routers using the same service, but with different middleware(s), would that mean that it will bypass the other router? I don't think a request can be handled by 2 routers.

There's already a configuration option to add middleware to the entrypoints, which automatically get prepended into each router's middleware chain.

The only thing that is missing is the use of conditionals @ddtmachado is mentioning in his example using the Router's Rule engine.

Perhaps we should combine the two?

Example configuration:
```yaml
entryPoints:
  websecure:
    address: ':443'
    http:
      middlewares:
        - rule: "HostRegexp(`internal.my.tld`, `{subdomain:[a-z]+}.internal.my.tld`)"
          apply: 
            - ip-whitelist@file
        - rule: "!HostRegexp(`internal.my.tld`, `{subdomain:[a-z]+}.internal.my.tld`)"
          apply:
            - auth@file
```

**Comment by CarlosLanderas** [comment]
Are there any plans to implement this feature? I started writing a plugin thinking pre-routing with request modification capabilities before reaching the routers was already possible

**Comment by ddtmachado** [comment]
Hey @CarlosLanderas, I would say both, this is in the roadmap and we're defintely looking for contributors :)

We have a few tasks in our roadmap that we know we won't have the resources to move forward ourself but we really would love to see them moving forward with the help of external contributors, this is one of them.

**Comment by rtribotte** [comment]
Hello all!

I want to suggest an alternative proposal to solve that use case.
It is more or less in line with the proposal of @ddtmachado, but narrowed.

I propose to introduce an option on routers to make them able to route back the request to the entryPoint muxer (on which it has been handled).
Those routers should not have a service as they would be "terminal".

A "route-back" router would execute its middleware chain, allowing request modification, and send the request back to the entryPoint muxer.
As a "route-back" router would again be able to match the request when going back to the muxer, a specific mechanism using the request context would avoid this.

Technically, an implicit middleware, is added at the very end of the "route-back" router's middleware chain and would be responsible for routing back the request to the entryPoint muxer.

Depending on the use case, the "route-back" router's rule priority should be configured precisely to control its matching over other routers (when the request hits the entryPoint muxer for the first time).

The hypothetical example below shows how this type of router could be used to rate limit requests according to the user group. 
```yaml
## Dynamic config
HTTP:
  routers:
    ...
    ## route back router handles authorization and adds an X-Claims-Group header to the request.
    foo-authorization:
      rule: Host(`foo`)
      priority: 1000 #evaluated first
      middlewares:
        - authorization #check user claims
      routeBack: true

    foo-admin:
      rule: Host(`foo`) && Headers(`X-Claims-Group`, `Admin`)
      middlewares:
        ...
        - admin-ratelimit
        ...
      service: my-foo-service

    foo-customer:
      rule: Host(`foo`) && Headers(`X-Claims-Group`, `Customer`)
      middlewares:
        ...
        - customer-ratelimit
        ...
      service: my-foo-service
    ...
```

This proposal aims to leverage most of the existing moving parts of Traefik, and hence IMHO not adding much of the existing complexity, to achieve "pre-routing" request modification, or more generically conditional middleware execution.
 
I am writing this comment to see if there is traction/feedback around this proposal.
I have a [POC](https://github.com/traefik/traefik/compare/v2.10...rtribotte:traefik:routeback) and could open a pull-request if this seems to get some interest.
