### ISSUE TITLE
OPTIONS returning 404 instead of 200

### ISSUE THREAD

**Issue by tiredofit** [containous/traefik#5101]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

Setup multiple frontends to point to the same host so that a CORS 204 Preflight check could occur. As per #1019 

````bash
    labels:
      - traefik.enable=true
      - traefik.normal.frontend.rule=Method:GET,POST,DELETE,PUT;Host:dev.api.example.com
      - traefik.normal.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-METHODS:GET, POST, OPTIONS, DELETE, PUT||Access-Control-Allow-Credentials:true||Access-Control-Allow-Headers:append,delete,entries,foreach,get,has,keys,set,values,User-Agent,Keep-Alive,Content-Type,Authorization,x-jwt-token
      - traefik.normal.port=80
      - traefik.normal.backend=dev-api-example-com-app
      - traefik.options.frontend.rule=Method:OPTIONS;Host:dev.api.example.com
      - traefik.options.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET, POST, OPTIONS, DELETE, PUT||Access-Control-Allow-Credentials:true||Access-Control-Allow-Headers:append,delete,entries,foreach,get,has,keys,set,values,User-Agent,Keep-Alive,Content-Type,Authorization,x-jwt-token
      - traefik.options.frontend.port=80
      - traefik.docker.network=proxy
      - traefik.options.backend=dev-api-example-com-options
````

### What did you expect to see?

The preflight check to complete and issue `OK`

### What did you see instead?

````bash
HTTP/2 404 
access-control-allow-credentials: true
access-control-allow-headers: append,delete,entries,foreach,get,has,keys,set,values,User-Agent,Keep-Alive,Content-Type,Authorization,x-jwt-token
access-control-allow-methods: GET, POST, OPTIONS, DELETE, PUT
access-control-allow-origin: *
content-type: text/plain; charset=utf-8
date: Mon, 15 Jul 2019 16:33:45 GMT
etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
server: nginx/1.14.2
vary: Accept-Encoding
x-powered-by: Express
content-length: 9
````

In Chrome Developer tools:
````
dev.api.example.com/:1 Failed to load resource: the server responded with a status of 404 ()
dev.example.com/:1 Access to XMLHttpRequest at 'https://dev.api.example.com/' from origin 'https://dev.rm.selfdesign.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
````

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
bash-5.0# traefik version
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

  checkNewVersion = false
  sendAnonymousUsage = false
  logLevel = "WARN"
  defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"
    compress = true
      [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$dSOFRZno$6pKCr8TboFfFJA4uNXuE5/"]
  [entryPoints.http]
    address = ":80"
    compress = true
      [entryPoints.http.redirect]
        entryPoint = "https"
        permanent = true
  [entryPoints.https]
    address = ":443"
    compress = true
  [entryPoints.https.tls]
    CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA"]
    MinVersion = "VersionTLS12"


[acme]
  email = "techsupport@example.com"
  storage = "/traefik/certs/acme.json"
  entryPoint = "https"
  onHostRule = true
  onDemand = false
  acmeLogging = true
  KeyType = "RSA4096"
  [acme.dnsChallenge]
    provider="cloudflare"
  [[acme.domains]]
     main = "example.com"
  [[acme.domains]]
     main = "example2.com"
  [[acme.domains]]
     main = "example.ca"

[traefikLog]
  filePath = "/traefik/logs/traefik.log"
  format = "common"

[accessLog]
  filePath = "/traefik/logs/access.log"
  format = "common"

[api]
  entryPoint = "traefik"
  dashboard = true

[ping]
  entryPoint = "traefik"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  DefaultRule = ""
  exposedByDefault = false
  watch = true
```
