### ISSUE TITLE
Traefik not getting SSL certificates for some domains, Let's Encrypt giving 400 error

### ISSUE THREAD

**Issue by 02JanDal** [containous/traefik#5103]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I've got Traefik setup in a Docker Swarm with Consul and Let's Encrypt. Previously everything has been working fine but now when I tried adding more domains some fail to get a SSL certificate.

### What did you expect to see?

All domains to get certificates.

### What did you see instead?

Some domains, but not all, fail to get a valid certificate from Let's Encrypt and instead use the Traefik default certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker 18.09.5 with Swarm, using the alpine version of the image.

```toml
debug = false
logLevel = "DEBUG"

insecureSkipVerify = true

defaultEntryPoints = ["https", "http"]

[entryPoints]
    [entryPoints.ping]
    address = ":8082"
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[traefikLog]
    filePath = '/var/log/traefik/traefik.log'
    format = 'json'
[accessLog]
    filePath = '/var/log/traefik/access.log'
    format = 'json'
    [accessLog.fields]
        defaultMode = 'keep'
        [accessLog.fields.headers]
            defaultMode = 'keep'
            [accessLog.fields.headers.names]
                "Authorization" = "drop"

[retry]

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[ping]
entryPoint = "ping"

[metrics]
    [metrics.influxdb]
    address = "http://influxdb:8086"
    protocol = "http"
    pushinterval = "10s"
    database = "metrics"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.tld"
watch = true
exposedByDefault = false
network = "net_web"
swarmMode = true

[acme]
email = "jan@maildomain.tld"
storage = "traefik/acme/account"
entryPoint = "https"
onHostRule = true
acmeLogging = true
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
main = "geflestudent.xyz"
sans = [
        "www.domain.xyz",
        "staging.domain.xyz",
        "pagefle.domain.xyz",
        "gris.domain.xyz",
        "gefleteknologerna.domain.xyz",
        "staging.pagefle.domain.xyz",
        "staging.gris.domain.xyz",
        "staging.gefleteknologerna.domain.xyz",
        "admin.domain.xyz",
        "matomo.domain.xyz",
        "portainer.admin.domain.xyz",
        "registry.domain.xyz"
]
[[acme.domains]]
main = "staging.otherdomain.se"
```

Some of those subdomains (in the `sans` array) are getting certificates (for example `admin` and `matomo`, other's aren't (for example `staging`). The DNS configuration (on Cloudflare) is identical for all domains).

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

The full log of a clean (cleared Consul data, reloaded configuration, started Traefik) startup and trying to load one page that's not working is available [here](https://pastebin.com/1xBaARaS) (it's been passed through `grep -i -A3 -B3 acme`). One likely relevant line therein (not how the domains mentioned above as working are not listed as errors):

```
{"level":"error","msg":"Error getting ACME certificate for domain [\"domain.xyz\" \"www.domain.xyz\" \"staging.domain.xyz\" \"pagefle.domain.xyz\" \"gris.domain.xyz\" \"gefleteknologerna.domain.xyz\" \"staging.pagefle.domain.xyz\" \"staging.gris.domain.xyz\" \"staging.gefleteknologerna.domain.xyz\" \"admin.domain.xyz\" \"matomo.domain.xyz\" \"portainer.admin.domain.xyz\" \"registry.domain.xyz\"]: cannot obtain certificates: acme: Error -\u003e One or more domains had a problem:\n[domain.xyz] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://domain.xyz/.well-known/acme-challenge/NynlPWanf5_76iKQTIzQbA2GBpK182oaNmxfSk2x1qw: Connection refused, url: \n[gefleteknologerna.domain.xyz] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://gefleteknologerna.domain.xyz/.well-known/acme-challenge/GG8JdOyzwKCXRZvE99UzKcrMjFKtEy7XdWVNlmMV1zQ: Connection refused, url: \n[gris.domain.xyz] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://gris.domain.xyz/.well-known/acme-challenge/3FSpxOYL8U67oKOF5Mvdej9w-DsSD0f-b_h72MFuQro: Connection refused, url: \n[staging.domain.xyz] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://staging.domain.xyz/.well-known/acme-challenge/4qyFTx8xJYfvzystUc37U3Zk0VSHC1vjjp4BaCYSfbw: Connection refused, url: \n[staging.gefleteknologerna.domain.xyz] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://staging.gefleteknologerna.domain.xyz/.well-known/acme-challenge/Oy0AS9i-Hce-iWY93KRrAC9nJDzocuj6ooFa8naJhro: Connection refused, url: \n","time":"2019-07-12T18:41:45Z"}
```

This issue seems similar to #2763, but not completely since some domains are getting validated successfully by Let's Encrypt. Almost sounds like a rate limit, though doesn't fit with any [mentioned](https://letsencrypt.org/docs/rate-limits/).
