### ISSUE TITLE
Traefik not making accesslog nor traefik.log files.

### ISSUE THREAD

**Issue by thepenguinthatwants** [containous/traefik#5122]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I have a working docker-compose that uses traefik alpine. I am using debian 9 as the main distro.

The problem is that its not writing any logfiles.
I then added these lines on the docker-compose but it didnt change anything.

```yml
    command:
      - --accessLog=true
      - --logLevel=INFO
      - --accessLog.filePath="/opt/traefik/access.log"
      - --traefikLog.filePath="/opt/traefik/traefik.log"
      - --traefikLog.format="json"
      - --accessLog.format="json"
```
I've tried different locations for access.log and traefik.log but nothing seems to be created. My purpose is to get it create logfiles so I can implement it with fail2ban.

### What did you expect to see?

I have traefik.frontend.auth.basic used on my docker dashboard but even if I purposely fail on login I can't see any log files created.

### What did you see instead?

Nothing.

### Output of `traefik version`: (_What version of Traefik are you using?_)

docker run traefik:alpine version
```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Debian 9 is the server I am using.

docker-compose.yml
```yml
version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:alpine
    networks:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/traefik/traefik.toml:/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/acme.json:/acme.json
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:top.example.xyz
    command:
      - --accessLog=true
      - --logLevel=INFO
      - --accessLog.filePath="/opt/traefik/access.log"
      - --traefikLog.filePath="/opt/traefik/traefik.log"
      - --traefikLog.format="json"
      - --accessLog.format="json"

networks:
  server:
    external: true
```

traefik.toml
```toml
logLevel = "INFO"
checkNewVersion = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["test:$apr1$k56KsfIu$7RI1JNkmwXpjqyaLPYuIA."]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
entrypoint="dashboard"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.xyz"
exposedByDefault = false
watch = true

[acme]
email = "example@example.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
entryPoint = "http"
```

I changed my real domain to example.
