### ISSUE TITLE
Traefik V2 (alpha8) : TLS options - Client Authentication not working ?

### ISSUE THREAD

**Issue by pbenefice** [containous/traefik#5125]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I tried to configure mutual TLS authentication following this [documentation page](https://docs.traefik.io/v2.0/https/tls/#client-authentication-mtls).
In the end I would like to use the `RequireAndVerifyClientCert` option, but for now I tried the `RequireAnyClientCert`.

> Again I'm not sure this is a bug or if I just missed / misunderstood something.

### What did you expect to see?

I expected to not be able to display the requested page with a curl where I don't provide any client certificates : `curl --insecure https://localhost`

### What did you see instead?

The whoami service I used displayed properly

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-alpha8
Codename:     faisselle
Go version:   go1.12.6
Built:        2019-07-01T17:46:52Z
OS/Arch:      linux/amd6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

*docker-compose*

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-alpha8"
    command:
      - --api
      - --log.level=DEBUG
      - --entrypoints.secure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/dyn.toml
      - --global.sendAnonymousUsage=false
    container_name: "traefik"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - "./dyn.toml:/dyn.toml"
      - "./secrets:/secrets"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: containous/whoami
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=secure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.tls.options=mutual-auth@file"
```

dyn.toml

```toml
[tls]
  [tls.options.mutual-auth]
    [tls.options.mutual-auth.clientAuth]
      #caFiles = ["/secrets/rootCA.crt"]
      #clientAuthType = "RequireAndVerifyClientCert"
      clientAuthType = "RequireAnyClientCert"
```

>    Eventually to test the RequireAndVerifyClientCert I used the following script to create test certificates : 
>
>    ```bash
>    mkdir -p secrets
>    cd secrets
>    openssl genrsa -out rootCA.key 4096
>    openssl req -x509 -new -nodes -key rootCA.key -subj "/C=FR/O=MyOrg" -sha256 -days 1024 -out rootCA.crt
>    openssl genrsa -out localhost.key 2048
>    openssl req -new -sha256 -key localhost.key -subj "/C=FR/O=MyOrg/CN=localhost" -out localhost.csr
>    openssl x509 -req -in localhost.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out localhost.crt -days 500 -sha256
>    ```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-07-19T11:26:53Z" level=info msg="Configuration loaded from flags."
time="2019-07-19T11:26:53Z" level=info msg="Traefik version 2.0.0-alpha8 built on 2019-07-01T17:46:52Z"
time="2019-07-19T11:26:53Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":false},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"secure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000},\"file\":{\"watch\":true,\"filename\":\"/dyn.toml\"}},\"api\":{\"entryPoint\":\"traefik\",\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2019-07-19T11:26:53Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-07-19T11:26:53Z" level=debug msg="No default certificate, generate one"
time="2019-07-19T11:26:53Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-07-19T11:26:53Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-07-19T11:26:53Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/dyn.toml\"}"
time="2019-07-19T11:26:53Z" level=debug msg="Start TCP Server" entryPointName=secure
time="2019-07-19T11:26:53Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}"
time="2019-07-19T11:26:53Z" level=debug msg="Configuration received from provider file: {\"http\":{},\"tcp\":{},\"tls\":{\"options\":{\"mutual-auth\":{\"clientCA\":{}}}}}" providerName=file
time="2019-07-19T11:26:53Z" level=debug msg="No default certificate, generate one"
time="2019-07-19T11:26:53Z" level=debug msg="Provider connection established with docker 18.09.2 (API 1.39)" providerName=docker
time="2019-07-19T11:26:53Z" level=debug msg="Filtering disabled container" providerName=docker container=traefik_traefik-b41b24673088f494ee2726788cb9a24e47577ca6941d7313ff164d83b751ed83
time="2019-07-19T11:26:53Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"whoami\":{\"entryPoints\":[\"secure\"],\"service\":\"whoami_traefik\",\"rule\":\"Host(`localhost`)\",\"tls\":{\"options\":\"mutual-auth@file\"}}},\"services\":{\"whoami_traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.30.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
time="2019-07-19T11:26:53Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=secure routerName=whoami@docker serviceName=whoami_traefik
time="2019-07-19T11:26:53Z" level=debug msg="Creating load-balancer" entryPointName=secure routerName=whoami@docker serviceName=whoami_traefik
time="2019-07-19T11:26:53Z" level=debug msg="Creating server 0 http://172.30.0.2:80" entryPointName=secure routerName=whoami@docker serviceName=whoami_traefik serverName=0
time="2019-07-19T11:26:53Z" level=debug msg="Added outgoing tracing middleware whoami_traefik" middlewareType=TracingForwarder middlewareName=tracing entryPointName=secure routerName=whoami@docker
time="2019-07-19T11:26:53Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=secure middlewareName=traefik-internal-recovery
time="2019-07-19T11:26:53Z" level=debug msg="No default certificate, generate one"
time="2019-07-19T11:26:53Z" level=debug msg="adding route localhost with minversion 0"
```
