### ISSUE TITLE
Using traefik:v2.0 throws error

### ISSUE THREAD

**Issue by josefglatz** [containous/traefik#5135]
Hi, I'm using the actual traefik v2.0 docker image in an test environment. After the last docker pull, the container can't start.

*The error is*: `command /traefik error: field not found, node: entrypoint`

My docker-compose.yml looks like:

```
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/traefik/acme.json:/acme.json
      - /srv/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /srv/traefik/toml.d:/srv/traefik/toml.d
      - /srv/traefik/volumes/log:/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.domain.at`)"
      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.routers.traefik-api.entrypoints=web-tls"
      - "traefik.http.routers.traefik-api.service=traefik-api"
      - "traefik.http.services.traefik-api.loadbalancer.server.port=8080"
    container_name: traefik
```

Is this a known issue? Thanks in advance
