### ISSUE TITLE
Traefik cannot see Gitlab, all networks tags set. Cannot understand issue

### ISSUE THREAD

**Issue by Locate929** [containous/traefik#5138]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?
Tried to get Gitlab to work with Traefik

### What did you expect to see?

Gitlab sign up page 

### What did you see instead?
"404 page not found"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
root@vps:/docker# docker run traefik version
Version:      v1.7.11
Codename:     maroilles
Go version:   go1.11.9
Built:        2019-04-26_08:42:33AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.traefiker]
    address = ":8080"
    [entryPoints.traefiker.auth]
      [entryPoints.traefiker.auth.basic]
        users = ["admin:<pwd>"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
	      [[entryPoints.https.tls.certificates]]
			certFile = "/certs/apache-selfsigned.crt"
			keyFile = "/certs/apache-selfsigned.key"

[api]
entrypoint="traefiker"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefiker.<DOMAIN>.com"
watch = true
network = "web"
exposedbydefault = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
https://paste.ubuntu.com/p/fPmQZh597D/
```

My docker-compose.yml file: https://paste.ee/p/LQWOn

Notice in the docker-compose.yml, I have port 6558 forwarded. That was to see if it was a problem with Gitlab or Traefik. After testing, Gitlab works (it doesnt show the page since the current docker-compose makes it set to expecting a connection from a reverse proxy but after disabling SSL & the reverse proxy options, Gitlab works as intended)

Quick Edit: Gitlab URL does appear in the Traefik dashboard so its not like Traefik cannot see it
