### ISSUE TITLE
Error parsing config file

### ISSUE THREAD

**Issue by bigslycat** [containous/traefik#5144]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I tried to create simple reverse-proxy for one host by standalone Traefik container and file provider.

### What did you expect to see?

Traefk is listen `:8080` and forward from `/` to `https://google.com`.

### What did you see instead?

I got this error:
```
dev-proxy | time="2019-07-22T19:12:37Z" level=error msg="error while parsing rule : 1:1: expected operand, found 'EOF'" entryPointName=web routerName=main@file
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-beta1
Codename:     faisselle
Go version:   go1.12.7
Built:        2019-07-19T16:04:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose.yml
```yaml
version: '3.7'

services:
  proxy:
    image: traefik:2.0.0-beta1-alpine
    ports:
      - 8080:8080
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./traefik-dynamic.yml:/dynamic-conf.yml:ro
```

traefik.yml
```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

entryPoints:
  web:
    address: ':8080'

providers:
  file:
    filename: dynamic-conf.yml
```

traefik-dynamic.yml
```yaml
http:
  routers:
    main:
      service: dev

  services:
    dev:
      loadBalancer:
        servers:
        - url: https://google.com
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
dev-proxy | time="2019-07-22T19:12:37Z" level=info msg="Configuration loaded from file: /traefik.yml"
dev-proxy | time="2019-07-22T19:12:37Z" level=info msg="Traefik version 2.0.0-beta1 built on 2019-07-19T16:04:34Z"
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Static configuration loaded {\"global\":{\"sendAnonymousUsage\":false},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"file\":{\"watch\":true,\"filename\":\"dynamic-conf.yml\"}},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
dev-proxy | time="2019-07-22T19:12:37Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="No default certificate, generating one"
dev-proxy | time="2019-07-22T19:12:37Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
dev-proxy | time="2019-07-22T19:12:37Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"dynamic-conf.yml\"}"
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Start TCP Server" entryPointName=web
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"main\":{\"service\":\"dev\"}},\"services\":{\"dev\":{\"loadBalancer\":{\"servers\":[{\"url\":\"https://google.com\"}],\"passHostHeader\":false}}}},\"tcp\":{},\"tls\":{}}" providerName=file
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Creating middleware" serviceName=dev entryPointName=web routerName=main@file middlewareName=pipelining middlewareType=Pipelining
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Creating load-balancer" routerName=main@file serviceName=dev entryPointName=web
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Creating server 0 https://google.com" entryPointName=web routerName=main@file serviceName=dev serverName=0
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Added outgoing tracing middleware dev" routerName=main@file middlewareName=tracing entryPointName=web middlewareType=TracingForwarder
dev-proxy | time="2019-07-22T19:12:37Z" level=error msg="error while parsing rule : 1:1: expected operand, found 'EOF'" entryPointName=web routerName=main@file
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
dev-proxy | time="2019-07-22T19:12:37Z" level=debug msg="No default certificate, generating one"
```
