### ISSUE TITLE
MySQL+TLS not working with v2.0.0-beta1

### ISSUE THREAD

**Issue by dduportal** [containous/traefik#5155]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Context: <https://community.containo.us/t/cant-connect-to-mysql-server-connection-refused>.

After successfully running MySQL behind Traefik in plain TCP, we tried to enable TLS encryption for MySQL connection to benefit from `HostSNI` routing, on 2 cases:

- TLS termination at Traefik level
- TLS termination at MySQL server level (TLS pass trough for Traefik)

### What did you expect to see?

Both examples working: using the `mysql` client with the option `--ssl-mode=REQUIRED` should work when going trough Traefik in both cases.

### What did you see instead?

Neither of the 2 cases work: the `mysql` client hangs once the password is sent.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-beta1
Codename:     faisselle
Go version:   go1.12.7
Built:        2019-07-19T16:04:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I've put a complete reproduction case in this gist: https://gist.github.com/dduportal/5b9e5f286b666a7cba7bd9f9ad4a1219 .

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N.A.

**Comment by dduportal** [comment]
- Tried with `mysql:8` instead of `mysql:5.7`: same behavior.
- It looks like that the `mysql` client is trying to "negociate" the fact that the connection should be plain or encrypted with the remote server - https://dev.mysql.com/doc/refman/5.7/en/encrypted-connections.html

**Comment by dduportal** [comment]
- Looks like we cannot use `HostSNI` routing with MySQL: https://bugs.mysql.com/bug.php?id=84849

**Comment by dduportal** [comment]
Tried this use case with GA release:

* `docker-compose.yml`:
```yml
version: '3'

services:
  edge:
    image: traefik:v2.0.0
    command:
      - --api=true
      - --log.level=DEBUG
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.mysql.address=:3306
      - --providers.file.filename=/traefik-tls.toml
    ports:
      - "3306:3306"
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.entrypoint=web"
      - "traefik.http.routers.api.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ./traefik-tls.toml:/traefik-tls.toml

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    labels:
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.tls=true"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.routers.mysql.service=mysql-svc"
      - "traefik.tcp.services.mysql-svc.loadbalancer.server.port=3306"
```

* `traefik-tls.toml`:
```toml
[[tls.certificates]]
  certFile = "/certs/server-cert.pem"
  keyFile = "/certs/server-key.pem"
```

Certificates generated with https://gist.github.com/dduportal/5b9e5f286b666a7cba7bd9f9ad4a1219#generate-tls-certificates-for-mysql

**Comment by dtomcej** [comment]
Do we need to have a dedicated page on our docs for this?

**Comment by sshishov** [comment]
@dduportal, please, for clean results use specified HostSNI as usually people use TLS in TCP for these purposes.

**Comment by dduportal** [comment]
Hi @sshishov , has MySQL protocol is not providing any SNI when TLS is enabled, the only possible rule for the tcp router would be ```Host(`*`)```.

However, I'm trying to put a reproduction case with tls passtrough (MySQL doing the TLS termination) instead of tls only: it will be easier for reproduction.

**Comment by dduportal** [comment]
Better reproduction case to track down the issue:

* MySQL in passtrough TLS: better diff between with or without Traefik as behavior is the same from client side
* MySQL client run in a container: reproduction independent from the host

* `docker-compose.yml`

```yml
version: '3'

services:
  edge:
    image: traefik:v2.0.0
    command:
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker
      - --entrypoints.mysql.address=:3306
    ports:
      - "3306:3306"
      - "8080:8080"
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./certs:/certs
    command:
      - --ssl-cert=/certs/server-cert.pem
      - --ssl-key=/certs/server-key.pem
      - --ssl-ca=/certs/ca.pem
      - --require_secure_transport=ON
    labels:
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.tls.passthrough=true"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.routers.mysql.service=mysql-svc"
      - "traefik.tcp.services.mysql-svc.loadbalancer.server.port=3306"
```

* `run.sh`

```bash
# Create certificates for MySQL's TLS
rm -f ./certs/* && docker run --rm -ti -v $(pwd)/certs:/certs mysql:5.7 mysql_ssl_rsa_setup --suffix=db --datadir=/certs --verbose

# Start the stack
docker-compose up -d

# Test with MySQL client -> MySQL server with TLS. Password is "root".
## It works
docker run --rm -ti --network=mysql_default mysql:5.7 mysql --host=db --port=3306 --user=root --password --ssl-mode=REQUIRED

# Test with MySQL client -> Traefik -> MySQL server with TLS passthrough. Password is "root".
# By adding an entry in the `/etc/hosts` of the container to keep the DB server hostname constant
## It is stuck after the password
docker run --rm -ti --network=mysql_default --add-host=db:172.17.0.1 mysql:5.7 mysql --host=db --port=3306 --user=root --password --ssl-mode=REQUIRED
```
