### ISSUE TITLE
[accessLog] not working on traefik:1.7

### ISSUE THREAD

**Issue by Zincr0** [containous/traefik#5163]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?

Create a traefik.toml with [accessLog]
```
debug = true
logLevel = "DEBUG"

[accessLog]
```

### What did you expect to see?

Access logs in _docker service logs [service id]_
(https://docs.traefik.io/configuration/logs/#access-logs)

### What did you see instead?

A massive spam of 'level=info msg="Skipping same configuration for provider docker"' several times per second an not a single 404/200 message.  

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
logLevel = "DEBUG"

[accessLog]

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "adminl@mydomainisnotyourbussiness.com"
storage = "acme.json"
entryPoint = "https"

[acme.dnsChallenge]
  provider = "route53"
  delayBeforeCheck = 0

[[acme.domains]]
   main = "*.mydomainisnotyourbussiness.com"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "sub.mydomainisnotyourbussiness.com"
watch = true
swarmMode = true
network = "proxy-net-prod"
exposedByDefault = false
```

A simple test with a docker registry image, traefik cannot reach the container for some reason and there are zero logs about it.

```
version: "3.7"
services:
  registry:
    image: registry:2
    deploy:
      labels:
      - "traefik.backend=docker-registry"
      - "traefik.docker.network=proxy-net-prod"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:testing.mydomainisnotyourbussiness.com"
      - "traefik.port=5000"
      - "traefik.protocol=http"
      - "traefik.frontend.priority=10"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
    name: proxy-net-prod 
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik_app-proxy.1.fhkkhs8ba3vi@server    | time="2019-07-27T20:21:36Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.fhkkhs8ba3vi@server    | time="2019-07-27T20:21:51Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.fhkkhs8ba3vi@server    | time="2019-07-27T20:22:06Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:09:56Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:10:11Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:10:26Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:10:41Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:10:56Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:11:11Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:11:26Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:11:41Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:11:56Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:12:11Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:12:26Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:12:41Z" level=info msg="Skipping same configuration for provider docker"
traefik_app-proxy.1.eh1e4t1z3bwj@server    | time="2019-07-26T14:12:56Z" level=info msg="Skipping same configuration for provider docker"
```

**Comment by dtomcej** [comment]
Hello @Zincr0, can you please provide the compose file that you run traefik with?

Thanks!

**Comment by Zincr0** [comment]
traefik.yml

```
version: '3.7'

services:
  app-proxy:
    image: traefik:1.7
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/credentials
      - AWS_REGION=some_region
      - AWS_HOSTED_ZONE_ID=some_id
    networks:
      - proxy-net
    labels:
      - "traefik.backend=traefik-proxy"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /thecredentialspath:/credentials
      - /pathto/traefik.toml:/traefik.toml
      - /pathto/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy-net:
    name: proxy-net-prod
    driver: overlay
    attachable: true

```
