### ISSUE TITLE
Local Time Zones Not Working For CLF in 1.7

### ISSUE THREAD

**Issue by jbnance** [containous/traefik#5176]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Followed the documentation here:

https://docs.traefik.io/configuration/logs/#time-zones

...to configure access logs (in common log format) to use the local time zone.

### What did you expect to see?

The timestamp in the CLF access log change to local timezone

### What did you see instead?

The timestamp in the CLF access log changed to "-" for all access log entries

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[accessLog]
  format = "json"

  [accessLog.fields]
    defaultMode = "keep"

    [accessLog.fields.names]
      "StartUTC" = "drop"

    [accessLog.fields.headers]
      [accessLog.fields.headers.names]
        "Authorization" = "drop"

[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
    address = ":443"

    [entryPoints.https.tls]
      minVersion = "VersionTLS12"

      [[entryPoints.https.tls.certificates]]
        certFile = "/run/secrets/traefik_crt"
        keyFile = "/run/secrets/traefik_key"

  [entryPoints.api]
    address = ":8443"

    [entryPoints.api.tls]
      minVersion = "VersionTLS12"

      [[entryPoints.api.tls.certificates]]
        certFile = "/run/secrets/traefik_crt"
        keyFile = "/run/secrets/traefik_key"

    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
        usersFile = "/run/secrets/api_auth_htpasswd"

  [entryPoints.ping]
    address = ":8080"

[api]
  entryPoint = "api"
  dashboard = true

[ping]
  entryPoint = "ping"

[docker]
  endpoint = "tcp://my.ucp.url:443"
  domain = "my.app.domain"
  watch = true
  swarmMode = true
  network = "myapp-traefik_net"

  [docker.tls]
    ca = "/run/secrets/bundle_ca_crt"
    cert = "/run/secrets/bundle_user_crt"
    key = "/run/secrets/bundle_user_key"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

**docker-compose.yml**

```
version: '3.3'

services:
  reverse-proxy:
    image: traefik:1.7
    networks:
      - net
    ports:
      - "14100:80"     # HTTP
      - "14101:443"    # HTTPS
      - "14102:8080"   # Ping endpoint
      - "14103:8443"   # API (HTTPS)
    secrets:
      - bundle_ca_crt
      - bundle_user_crt
      - bundle_user_key
      - traefik_crt
      - traefik_key
      - api_auth_htpasswd
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
    logging:
      driver: gelf
      options:
        gelf-address: udp://my.elk.host:12201
        tag: "myapp-traefik"
    environment:
      - "TZ=America/Chicago"
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

networks:
  net:
    driver: overlay
    attachable: true

secrets:
  bundle_ca_crt:
    file: ./bundle-ca.pem
  bundle_user_crt:
    file: ./bundle-cert.pem
  bundle_user_key:
    file: ./bundle-key.pem
  traefik_crt:
    file: ./myapp-with-chain.pem
  traefik_key:
    file: ./myapp.key
  api_auth_htpasswd:
    file: ./api-auth-htpasswd

configs:
  traefik_toml:
    file: ./traefik.toml
```

If I don't specify `"StartUTC" = "drop"` the timestamp appears in the access logs as expected (in UTC TZ).

If I change the log format from CLF to JSON with the settings above I get timestamps in my local TZ.

I have also attempted to explicitly set `"StartLocal" = "keep"` with no change in observations.

It appears that this issue was previously [reported](https://github.com/containous/traefik/issues/4158) and then closed in reference to a [comment](https://github.com/containous/traefik/issues/3870#issuecomment-440826268) but, [as was pointed out in the original report](https://github.com/containous/traefik/issues/4158#issuecomment-448233948) the referenced "fix" is for JSON only.  This report is specifically about the timezone when using the common log format.
