### ISSUE TITLE
TLS not working (always using generated default certificate)

### ISSUE THREAD

**Issue by develerik** [containous/traefik#5195]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I used this code to create an traefik ingress controller for my kubernetes cluster (the custom resource definitions are already added)

```yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-lb
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutetcps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - tlsoptions
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-lb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-lb
subjects:
  - kind: ServiceAccount
    name: traefik-lb
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-lb
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-cert
  namespace: default
data:
  example.pem: <content>
  example.key: <content>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: default
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    api: {}
    ping: {}
    entryPoints:
      websecure:
        address: ":443"
    providers:
      kubernetesCRD: {}
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /ssl/example.pem
            keyFile: /ssl/example.key
      options:
        default:
          minVersion: VersionTLS13
          sniStrict: true
      certificates:
        - certFile: /ssl/example.pem
          keyFile: /ssl/example.key
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-lb
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: ssl
          secret:
            secretName: traefik-cert
      containers:
        - name: traefik
          image: traefik:2.0
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /etc/traefik/traefik.yml
              subPath: traefik.yml
            - name: ssl
              mountPath: /ssl
          ports:
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
              hostPort: 30103
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-admin-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.example.com`)
      kind: Rule
      priority: 1
      services:
        - name: traefik-admin-svc
          port: 8080
      tls: {}
```

### What did you expect to see?

Traefik should use the defined default certificate for the route.

### What did you see instead?

Traefik logs it cannot find the certificate and generates one which it then uses instead.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-beta1
Codename:     faisselle
Go version:   go1.12.7
Built:        2019-07-19T16:04:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I just set up a fresh kubernetes cluster and applied the custom traefik resource definitions.

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false
api: {}
ping: {}
entryPoints:
  websecure:
    address: ":443"
providers:
  kubernetesCRD: {}
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /ssl/example.pem
        keyFile: /ssl/example.key
  options:
    default:
      minVersion: VersionTLS13
      sniStrict: true
  certificates:
    - certFile: /ssl/example.pem
      keyFile: /ssl/example.key
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-08-12T11:14:07Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2019-08-12T11:14:07Z" level=info msg="Traefik version 2.0.0-beta1 built on 2019-07-19T16:04:34Z"
time="2019-08-12T11:14:07Z" level=debug msg="Static configuration loaded {\"global\":{\"sendAnonymousUsage\":false},\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"kubernetesCRD\":{}},\"api\":{\"dashboard\":true},\"ping\":{},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2019-08-12T11:14:07Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-08-12T11:14:07Z" level=debug msg="No default certificate, generating one"
time="2019-08-12T11:14:07Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-08-12T11:14:07Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-08-12T11:14:07Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2019-08-12T11:14:07Z" level=info msg="Starting provider *crd.Provider {}"
time="2019-08-12T11:14:07Z" level=debug msg="Using label selector: \"\"" providerName=kubernetescrd
time="2019-08-12T11:14:07Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2019-08-12T11:14:07Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2019-08-12T11:14:08Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"routers\":{\"default/traefik-admin-route-70cbcd03eb4f61e36cea\":{\"entryPoints\":[\"websecure\"],\"service\":\"default/traefik-admin-route-70cbcd03eb4f61e36cea\",\"rule\":\"Host(`traefik.example.com`)\",\"priority\":1}},\"services\":{\"default/traefik-admin-route-70cbcd03eb4f61e36cea\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://10.32.0.2:8080\"},{\"url\":\"http://10.46.0.1:8080\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"tls\":{}}" providerName=kubernetescrd
time="2019-08-12T11:14:08Z" level=debug msg="Creating middleware" middlewareType=Pipelining serviceName=default/traefik-admin-route-70cbcd03eb4f61e36cea middlewareName=pipelining entryPointName=websecure routerName=default/traefik-admin-route-70cbcd03eb4f61e36cea@kubernetescrd
time="2019-08-12T11:14:08Z" level=debug msg="Creating load-balancer" entryPointName=websecure routerName=default/traefik-admin-route-70cbcd03eb4f61e36cea@kubernetescrd serv
iceName=default/traefik-admin-route-70cbcd03eb4f61e36cea
```

**Comment by dbsanfte** [comment]
You need to enable the file provider, it's not reading your config. Well actually it's reading your config... but then not taking any values from it. It's very strange but this fixes it:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: default
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    api: {}
    ping: {}
    entryPoints:
      websecure:
        address: ":443"
    providers:
      kubernetesCRD: {}
      file:
        filename: /etc/traefik/traefik.yml
        watch: true
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /ssl/example.pem
            keyFile: /ssl/example.key
      options:
        default:
          minVersion: VersionTLS13
          sniStrict: true
      certificates:
        - certFile: /ssl/example.pem
          keyFile: /ssl/example.key
```
