### ISSUE TITLE
Support setting the Internal Load Balancer annotation on the LoadBalancer service in the Traefik Helm chart

### ISSUE THREAD

**Issue by dbsanfte** [containous/traefik#5203]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Azure supports adding an annotation to the Load Balancer service to direct Azure Kubernetes Service to expose the LoadBalancer on a private vnet, rather than to the internet.

https://docs.microsoft.com/en-us/azure/aks/internal-lb

It would be nice to have this option in the Traefik Helm chart. All that is required is to add a flag to enable this annotation on the LB service via the values.yaml. For example:

```
apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: internal-app
```

I believe Google and AWS kubernetes services also support similar annotations. In that case you could just add all 3 Google, AWS and Azure internal load balancer annotations with one flag and it would be cloud agnostic.

**Edit:** The annotations for all the various Kubernetes clouds are here:

https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
