### ISSUE TITLE
Wildcard SSL certificate served over normal SSL certificate

### ISSUE THREAD

**Issue by CDingerdis** [containous/traefik#5206]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I've got 2 certificates, one for the root domain (example.com) and one for the wildcard subdomains (*.example.com)

Now the wildcard subdomain also supports SSL for the root domain, so traefik serve's the wildcard ssl certificate on the root domain instead of the certificate specific for the root domain

### What did you expect to see?
example.com -> root domain certificate
test1.example.com -> wildcard domain certificate
test2.example.com -> wildcard domain certificate

### What did you see instead?
example.com -> wildcard domain certificate
test1.example.com -> wildcard domain certificate
test2.example.com -> wildcard domain certificate

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.7.13 built on 2019-08-08_04:46:14PM
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
stripped version of config.toml
```toml
defaultEntryPoints = ["http","https"]
debug = false
logLevel = "INFO"
# Do not verify backend certificates (use https backends)
InsecureSkipVerify = true
[kubernetes]
  [kubernetes.ingressEndpoint]
    publishedService = "traefik-service"
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "example.crt"
        keyFile = "example.key"
      [[entryPoints.https.tls.certificates]]
        certFile = "star_example.crt"
        keyFile = "star_example.key"

[acme]
email = "servicedesk@example.nl"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
onHostRule= true
acmeLogging = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"
```

### Extra information

* Using kubernetes ingress
