### ISSUE TITLE
insecureSkipVerify: true not being applied (v2)

### ISSUE THREAD

**Issue by robertbaker** [containous/traefik#5216]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

enabled serversTransport.insecureSkipVerify: true

### What did you expect to see?

Plex works over https (with cloudflare)

### What did you see instead?

502 gateway error from cloudflare

This is because plex, emby, and other apps use a self signed cert over https and there's no way to stop that. So in 1.7, insecureSkipVerify=true solves the self signed cert issue on the backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-beta1
Codename:     faisselle
Go version:   go1.12.7
Built:        2019-07-19T16:04:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
entryPoints:
  websecure:
    address: ":443"
certificatesResolvers:
  cloudflare:
    acme:
      email: "xxx"
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare
```

docker labels:
```yaml
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${TLD}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.options=default@file"
      - "traefik.http.routers.plex.tls.certresolver=cloudflare"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
