### ISSUE TITLE
Kubernetes CRD not generate wildcard certificate with Azure DNS

### ISSUE THREAD

**Issue by ArielCCardoso** [containous/traefik#5219]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ x ] No

### What did you expect to see?
I expected Traefik to include in the Azure DNS Zone the _acme-challenge.XXXXXXXX.XX TXT record and generate a wildcard certificate.

### What did you see instead?
Traefik was expecting the _acme-challenge.api.XXXXXXXX.XX record in the Azure DNS Zone and did not generate a wildcard certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-beta1
Codename:     faisselle
Go version:   go1.12.7
Built:        2019-07-19T16:04:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[Global]
  checkNewVersion = false
  sendAnonymousUsage = true

[log]
  level = "DEBUG"
  format = "common"

[ping]

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.git]
    address = ":22"
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.prod]
    [certificatesResolvers.prod.acme]
      email = "myemail@domain.tld"
      storage = "/etc/traefik/ssl/telefonicadevops.json"
      keyType = "RSA4096"
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [certificatesResolvers.prod.acme.dnsChallenge]
        provider = "azure"
        delayBeforeCheck = 0
        disablePropagationCheck = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
IngressRoute:
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apigw
  namespace: production
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`api.XXXXXXXX.XX`)
    kind: Rule
    services:
    - name: apigw
      port: 80
  tls:
    certResolver: prod

Log:
time="2019-08-15T23:13:18Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/XXXXXXXX"
time="2019-08-15T23:13:18Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: Could not find solver for: tls-alpn-01"
time="2019-08-15T23:13:18Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: Could not find solver for: http-01"
time="2019-08-15T23:13:18Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: use dns-01 solver"
time="2019-08-15T23:13:18Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: Preparing to solve DNS-01"

time="2019-08-15T23:13:21Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: Trying to solve DNS-01"
time="2019-08-15T23:13:21Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: Checking DNS record propagation using [10.19.240.10:53]"

time="2019-08-15T23:13:22Z" level=debug msg="legolog: [INFO] [api.XXXXXXXX.XX] acme: Cleaning DNS-01 challenge"

time="2019-08-15T23:13:23Z" level=error msg="Unable to obtain ACME certificate for domains \"api.XXXXXXXX.XX\": unable to generate a certificate for the domains [api.XXXXXXXX.XX]: acme: Error -> One or more domains had a problem:\n[api.XXXXXXXX.XX] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record \"pT_rVRBtSIO8PeZ5bGgxQsrfapnIDmkqSyeWHGRok5o\" found at _acme-challenge.api.XXXXXXXX.XX, url: \n" providerName=acme.prod routerName=production/apigw-f6fd31cc375a061e3c9b rule="Host(`api.XXXXXXXX.XX`)"
```
