### ISSUE TITLE
accessLog.fields.headers.names not taking effect

### ISSUE THREAD

**Issue by alexburlton** [containous/traefik#5221]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I attempted to redact a header field using the `accessLog.fields.headers.names` config described [here](https://docs.traefik.io/v1.7/configuration/logs/#access-logs). In particular, I am trying to redact the `request_Cookie` field. I have also tried `drop` rather than `redact`, with no success.

However, setting the following works fine (the `request_Cookie` field is redacted, but so is a bunch of other stuff):

```
[accessLog.fields.headers]
  defaultMode = "redact"
```

I've also tried the following just in case, which also doesn't work:

```
[accessLog.fields.names]
  "request_Cookie" = "redact"
```

### What did you expect to see?

I expected the value of `request_Cookie` to be redacted in traefik logs

### What did you see instead?

The value of `request_Cookie` is still present.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
        users = ["REDACTED",]
[kubernetes]
[traefikLog]
  format = "json"
[accessLog]
  format = "json"
[accessLog.fields]
  defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
  defaultMode = "keep"
[accessLog.fields.headers.names]
  "request_Cookie" = "redact"
[acme]
email = "REDACTED"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
  [acme.dnsChallenge]
  provider = "digitalocean"
[api]
  entryPoint = "traefik"
  dashboard = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
