### ISSUE TITLE
traefik v2-beta1: k8s ingress broken

### ISSUE THREAD

**Issue by discostur** [containous/traefik#5222]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

We deployed traefik v2-beta1 inside our kubernetse 1.15.2 cluster and we are only getting http 404 error codes.

**Here is our traefik toml:**
```toml
# traefik.toml
debug = true
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.proxyProtocol]
    trustedIPs = ["192.168.0.0/16"]
    [entryPoints.http.forwardedHeaders]
    trustedIPs = ["192.168.0.0/16"]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.proxyProtocol]
    trustedIPs = ["192.168.0.0/16"]
    [entryPoints.https.forwardedHeaders]
    trustedIPs = ["192.168.0.0/16"]
  [entryPoints.traefik]
  address = ":8080"
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/ssl/tls.crt"
      keyFile  = "/ssl/tls.key"
[ping]
[providers.kubernetesIngress]
ingressClass = "traefik"
``` 

**Ingress config:**
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/custom-request-headers: enable:true
    kubernetes.io/ingress.class: traefik
  name: domain.com
spec:
  rules:
  - host: domain.com
    http:
      paths:
      - backend:
          serviceName: http-svc
          servicePort: 80
  tls:
  - hosts:
    - domain.com
    secretName: domain.com
``` 

Via the dashboard we can verify that all of our ingresses are loaded by traefik. However, if we try to curl our service we get only 404 http errror response codes:

```
HTTP/2 404 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
content-length: 19
date: Fri, 16 Aug 2019 15:52:48 GMT
```

The cool thing is traefik is loading the correct TLS certificate, because we get no ssl errors. We already tried to switch service backends without any luck.

Same ingress config is running without any errors with traefik 1.7.x.

**Comment by jlevesy** [comment]
Hey @discostur, 

Could you provide Traefik's logs in debug mode please ? 

Thanks !

**Comment by discostur** [comment]
@jlevesy we debugged it a little further:

```
time="2019-08-19T15:17:12Z" level=info msg="Configuration loaded from file: /config/traefik.toml"
time="2019-08-19T15:17:12Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
time="2019-08-19T15:17:12Z" level=error msg="Error configuring TLS: secret namespace/domain.com does not exist" providerName=kubernetes ingress=domain.com namespace=namespace
time="2019-08-19T15:17:12Z" level=error msg="Error configuring TLS: secret namespace/domain.com does not exist" ingress=domain.com namespace=namespace providerName=kubernetes
``` 

https://github.com/containous/traefik/blob/master/pkg/provider/kubernetes/ingress/client.go#L155

We changed the code a little bit so that traffic waits for the cache sync - then the error for loading TLS secret is gone - but the 404 error still exists ...

**Comment by discostur** [comment]
@jlevesy we also tried to debug via access log:

```
{
  "ClientAddr": "192.168.170.57:49190",
  "ClientHost": "192.168.170.57",
  "ClientPort": "49190",
  "ClientUsername": "-",
  "DownstreamContentSize": 19,
  "DownstreamStatus": 404,
  "Duration": 115434,
  "OriginContentSize": 19,
  "OriginDuration": 19716,
  "OriginStatus": 404,
  "Overhead": 95718,
  "RequestAddr": "ingress-traefik.dev:443",
  "RequestContentSize": 0,
  "RequestCount": 5,
  "RequestHost": "ingress-traefik.dev",
  "RequestMethod": "GET",
  "RequestPath": "/",
  "RequestPort": "443",
  "RequestProtocol": "HTTP/1.1",
  "RetryAttempts": 0,
  "StartLocal": "2019-08-19T16:08:03.010674068Z",
  "StartUTC": "2019-08-19T16:08:03.010674068Z",
  "entryPointName": "https",
  "level": "info",
  "msg": "",
  "time": "2019-08-19T16:08:03Z"
}
```

**Comment by dimm0** [comment]
Same here

**Comment by SantoDE** [comment]
Hey,

I tried to reproduce your issue with a local k3s setup. However, I'm unable to. Everything is working for me as expected. 

What I did was creating a local k3s cluster with  `docker-compose` and apply these 2 configurations:

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 8000
            - name: admin
              containerPort: 8080
```

```

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: whoami
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: whoami
  selector:
    app: whoami

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: whoami
  labels:
    app: whoami
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: whoami.localhost
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80
```

Can you try this again?
