### ISSUE TITLE
Composing Traefik's Service load balancing with CRD

### ISSUE THREAD

**Issue by ldez** [containous/traefik#5242]
## Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The requirements:
- be able to use a load balancing "chain" (ex: canary [service] -> mirror [service] -> round-robin [servers])
- be able to use sticky
- be able to use mirroring

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: testroute
  namespace: default

spec:
  entryPoints:
    - web

  routes:
    - match: Host(`foo.com`) && PathPrefix(`/bar`)
      kind: Rule
      priority: 12
      # Sticky cannot be define here, need to use a "TraefikService" instead
      services:
        # service in a k8s meaning
        - name: whoami
          # strategy: test # not yet implemented in Traefik "core"
          port: 80
          weight: 50
        # service in a Traefik meaning
        - tServiceName: tweetyBird # the field name `tServiceName` must be changed
          weight: 50

---

apiVersion: traefik.containo.us/v1alpha1
# the name `TraefikService` must be changed
kind: TraefikService
metadata:
  name: tweetyBird
  namespace: default

spec:
  canary:
    sticky:
      cookie:
        name: foobar
        secure: true
        httpOnly: true
    services:
      - name: whoami
        # strategy: test # not yet implemented in Traefik "core"
        port: 80
        weight: 1
      - serviceName: tata
        weight: 3

---
# not yet implemented in Traefik "core"
apiVersion: traefik.containo.us/v1alpha1
# the name `TraefikService` must be changed
kind: TraefikService
metadata:
  name: sylvester
  namespace: default

spec:
  mirror:
    main:
      name: whoami
    mirrors:
      - name: staging
        percent: 10%
      - name: dev
        percent: 20%
```
