### ISSUE TITLE
Undefined entry point(s) 'name for frontend

### ISSUE THREAD

**Issue by tinganho** [containous/traefik#5254]
Hi,

I'm trying to get entrypoints to work on the docker command line. I noticed there is a inconsistency on the naming in the docs. `defaultentrypoints` are all lowercased and `entryPoints` are camelcased https://docs.traefik.io/configuration/entrypoints/. Anyway tried all different combinations. I don't get it to register the entrypoints.

I always get "Undefined entry point(s) 'blob,queue' for frontend" on the logs.

```
  gateway:
    image: traefik
    container_name: gateway
    command:
      - --api
      - --docker
      - --docker.watch=true
      - --docker.domain=docker.localhost
      - --logLevel=DEBUG
      - --defaultentrypoints=http
      - "--entryPoints=Name:http Address::80,Name:mssql Address::1433,Name:blob Address::10000,Name:queue Address::10001"
    ports:
      - "8080:8080"
      - "80:80"
      - "10000:10000"
      - "10001:10001"
      - "1433:1433"
```
