### ISSUE TITLE
IngressRouteTCP obtains ACME cert but then continues to use Default cert

### ISSUE THREAD

**Issue by tinyzimmer** [containous/traefik#5259]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?

I'm using traefik as a k8s ingress controller, and I am playing with the TCP routing. I'm using the new CRD's for the route to a test service. It is working, however the certificate in use remains the `TRAEFIK DEFAULT CERT` after `acme` completes.

I'm using v2.0.0 for those prometheus metrics fixes in my dev environment so I'm testing this out on that version. 

### What did you expect to see?

I expected to see the `acme` generated cert in use.

### What did you see instead?

Traefik generates a default one and continues to use that instead

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-rc1
Codename:     montdor
Go version:   go1.13rc1
Built:        2019-08-26T17:47:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[serversTransport]
  insecureSkipVerify = true

[certificatesResolvers.tls.acme]
  email = "admin@my.zone.com"
  storage = "acme.json"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.tls.acme.dnsChallenge]
    provider = "route53"
    delayBeforeCheck = 0
    resolvers = ["1.1.1.1", "8.8.8.8"]

[entryPoints]
  [entryPoints.tcp]
    address = ":8443"
  [entryPoints.httpn]
    address = ":8880"
  [entryPoints.traefik]
    address = ":8080"

[http.routers]
  [http.routers.main]
    entrypoints = ["httpn", "traefik"]

[tcp.routers]
  [tcp.routers.main]
    entrypoints = ["tcp"]
    [tcp.routers.main.tls]
      certResolver = "tls"
      options = "default"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384"
    ]

[ping]

[providers.kubernetesIngress]
[providers.kubernetesCRD]

[log]
  format = "json"
  level = "info"

[api]
  dashboard = true

[metrics.prometheus]
```

Below is the ingress route:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: example-ingress
spec:
  entryPoints:
    - tcp
  routes:
  - match: HostSNI(`example.my.zone.com`)
    services:
    - name: example
      port: 2080
  tls:
    passthrough: false
    certResolver: tls
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Filtered for relevance

```
{"level":"debug","msg":"Try to challenge certificate for domain [example.my.zone.com] founded in HostSNI rule","providerName":"tls.acme","routerName":"default/example-ingress-132b6a73e1aad193c12f","rule":"HostSNI(`example.my.zone.com`)","time":"2019-08-28T02:00:37Z"}
{"level":"debug","msg":"Looking for provided certificate(s) to validate [\"example.my.zone.com\"]...","providerName":"tls.acme","routerName":"default/example-ingress-132b6a73e1aad193c12f","rule":"HostSNI(`example.my.zone.com`)","time":"2019-08-28T02:00:37Z"}
{"level":"debug","msg":"Domains [\"example.my.zone.com\"] need ACME certificates generation for domains \"example.my.zone.com\".","providerName":"tls.acme","routerName":"default/example-ingress-132b6a73e1aad193c12f","rule":"HostSNI(`example.my.zone.com`)","time":"2019-08-28T02:00:37Z"}
{"level":"debug","msg":"Loading ACME certificates [example.my.zone.com]...","providerName":"tls.acme","routerName":"default/example-ingress-132b6a73e1aad193c12f","rule":"HostSNI(`example.my.zone.com`)","time":"2019-08-28T02:00:37Z"}
{"level":"debug","msg":"Building ACME client...","providerName":"tls.acme","time":"2019-08-28T02:00:37Z"}
{"level":"debug","msg":"https://acme-staging-v02.api.letsencrypt.org/directory","providerName":"tls.acme","time":"2019-08-28T02:00:37Z"}
{"level":"info","msg":"Register...","providerName":"tls.acme","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] acme: Registering account for admin@my.zone.com","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"Using DNS Challenge provider: route53","providerName":"tls.acme","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Obtaining bundled SAN certificate","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/6126904","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Could not find solver for: tls-alpn-01","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Could not find solver for: http-01","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: use dns-01 solver","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Preparing to solve DNS-01","time":"2019-08-28T02:00:38Z"}
{"level":"debug","msg":"legolog: [INFO] Wait for route53 [timeout: 2m0s, interval: 4s]","time":"2019-08-28T02:00:38Z"}

# ...

{"level":"debug","msg":"No secret name provided","providerName":"kubernetescrd","time":"2019-08-28T02:01:13Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetescrd","time":"2019-08-28T02:01:13Z"}
{"level":"debug","msg":"No secret name provided","providerName":"kubernetescrd","time":"2019-08-28T02:01:13Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetescrd","time":"2019-08-28T02:01:13Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetes","time":"2019-08-28T02:01:13Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Trying to solve DNS-01","time":"2019-08-28T02:01:14Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]","time":"2019-08-28T02:01:14Z"}

# ...

level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetes","time":"2019-08-28T02:01:17Z"}
{"level":"debug","msg":"No secret name provided","providerName":"kubernetescrd","time":"2019-08-28T02:01:17Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetescrd","time":"2019-08-28T02:01:17Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetes","time":"2019-08-28T02:01:17Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] The server validated our request","time":"2019-08-28T02:01:18Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Cleaning DNS-01 challenge","time":"2019-08-28T02:01:18Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] acme: Validations succeeded; requesting certificates","time":"2019-08-28T02:01:18Z"}

# ...

{"level":"debug","msg":"No secret name provided","providerName":"kubernetescrd","time":"2019-08-28T02:01:21Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetescrd","time":"2019-08-28T02:01:21Z"}
{"level":"debug","msg":"Skipping Kubernetes event kind *v1.Endpoints","providerName":"kubernetes","time":"2019-08-28T02:01:21Z"}
{"level":"debug","msg":"legolog: [INFO] [example.my.zone.com] Server responded with a certificate.","time":"2019-08-28T02:01:22Z"}
{"level":"debug","msg":"Certificates obtained for domains [example.my.zone.com]","providerName":"tls.acme","routerName":"default/example-ingress-132b6a73e1aad193c12f","rule":"HostSNI(`example.my.zone.com`)","time":"2019-08-28T02:01:22Z"}
{"level":"debug","msg":"Configuration received from provider tls.acme: {\"http\":{},\"tls\":{}}","providerName":"tls.acme","time":"2019-08-28T02:01:22Z"}
{"level":"debug","msg":"Adding certificate for domain(s) example.my.zone.com","time":"2019-08-28T02:01:22Z"}
{"level":"debug","msg":"No default certificate, generating one","time":"2019-08-28T02:01:22Z"}

# ...

{"entryPointName":"tcp","level":"debug","msg":"Creating TCP server 0 at 172.19.168.47:2080","routerName":"default/example-ingress-132b6a73e1aad193c12f@kubernetescrd","serverName":0,"serviceName":"default/example-ingress-132b6a73e1aad193c12f","time":"2019-08-28T02:01:22Z"}
{"entryPointName":"tcp","level":"debug","msg":"Adding route example.my.zone.com on TCP","routerName":"default/example-ingress-132b6a73e1aad193c12f@kubernetescrd","time":"2019-08-28T02:01:22Z"}
```

And then after that whole todo I'm still using a default cert, as that final log in the second to last block suggests:

```bash
tinyzimmer@nou:~/devel (ctx: dev)$ openssl s_client -connect example.my.zone.com:8443
CONNECTED(00000003)
depth=0 CN = TRAEFIK DEFAULT CERT

verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = TRAEFIK DEFAULT CERT
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=TRAEFIK DEFAULT CERT
   i:/CN=TRAEFIK DEFAULT CERT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDRzCCAi+gAwIBAgIRAKtvAQfnyLmDU0+HhfNjJ5owDQYJKoZIhvcNAQELBQAw
HzEdMBsGA1UEAxMUVFJBRUZJSyBERUZBVUxUIENFUlQwHhcNMTkwODI4MDIxNjI5
WhcNMjAwODI3MDIxNjI5WjAfMR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VS
VDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPJg7/1ajd16Nia5VcF9
HufhRk3xgg45igq5sO2bJEti0tpekHGkdkQz7L4rIk1tFG2SwTpOQllTu1GJ+sJa
OZ85dZUEprpNL/asdqWCTbcHeYS7Ab9KULrFGieHS3LtQTtlenLacqGgfE+rKRaW
cgBUdJt3HzX+q7VGW8IhiC9MoXUS12HrIRZiQowczGnmdayo+AXLaj6edg6vyJNL
xBkQPvZ+49H0TaUhtHA1w63zsOterQSGAv0eMpQbMlq4uxR1XUuV6hKPS5TEtHXn
wzfmoQy8puUo516KMS6wCHK1DNoHm1N7VVy0WR0NPYUDBq41XaAFK0vbupHZVXHM
3BUCAwEAAaN+MHwwDgYDVR0PAQH/BAQDAgO4MAwGA1UdEwEB/wQCMAAwXAYDVR0R
BFUwU4JRZDYxMDdlMjA5MjkzOTI1NDc5MzEzNGI5OTAxYTY1YWEuODk3NmM5OTM0
NTljNjUyOTRlZTE4ZDFkZjlhYThjNTkudHJhZWZpay5kZWZhdWx0MA0GCSqGSIb3
DQEBCwUAA4IBAQAhhvBUQ/QXlZNK39LNmDjFGuWnklkd7q43PZcr7gHhfWPo6Gb5
K+g0HQ4qi5Nv1dGgFWd/HZWMD1kqrb9LVBGIHq1VFW0vvpsYOkd2QX8griAYqbsR
WM7RT964ONliN/UkzESRuhhKfqgnnUA8b8//96wRs2FOUi/IGppWvBevNAzng+1Z
0Sx5ZfsZTsf4rIpLixwWVSWuVU8kpocmg4/xb9rkXo0B4GjdKmut0sSGU4nH4FuI
DVBH49yyZ7nsMlTUM2OvtBWuhXMerB7RCjAE3MrmYSnF3lqq7VXjj6GDTXKQxWCb
xoQBd8/DKPG9xCWMWQP+tGRL3gMs0eUJwsUm
-----END CERTIFICATE-----
subject=/CN=TRAEFIK DEFAULT CERT
issuer=/CN=TRAEFIK DEFAULT CERT
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
```

EDIT: `ncat` for whatever its worth, at least shows me getting through to my service

```bash
tinyzimmer@nou:~/devel (ctx: dev)$ ncat --ssl example.my.zone.com 8443 -v
Ncat: Version 7.01 ( https://nmap.org/ncat )
Ncat: Subject: CN=TRAEFIK DEFAULT CERT
Ncat: Issuer: CN=TRAEFIK DEFAULT CERT
Ncat: SHA-1 fingerprint: 9798 1D60 386E CB46 F6A8 0827 A847 62F5 6CC7 FC6B
Ncat: Certificate verification failed (unable to get local issuer certificate).
Ncat: SSL connection to 10.212.2.146:8443.
Ncat: SHA-1 fingerprint: 9798 1D60 386E CB46 F6A8 0827 A847 62F5 6CC7 FC6B                                                                                                                                                                  

Hello world!
```
