### ISSUE TITLE
behind corporate proxy: all containers proxied

### ISSUE THREAD

**Issue by TerrorFactor** [containous/traefik#5262]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I have the same issue mentioned in https://github.com/containous/traefik/issues/1110, https://github.com/containous/traefik/issues/3978.
When I enter proxy environment variables in my Traefik container, all containers behind Traefik are unreachable, and you get an error message from the corporate proxy instead. For some reason, the traffic between Traefik and the proxied containers, passes over (or tries to pass over) the corporate proxy.
In this case: proxy is running on the docker host, on port 8080.The IP in the compose file is the ip of docker0.
If I remove the proxy environment variables from the compose file, it works perfectly, but I can't get the certificates signed.

Compose file:

```
version: "3"

services:
  traefik:
    image: traefik:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    restart: always
    labels:
      - traefik.frontend.rule=Host:monitor.example.com
      - traefik.port=8080
    environment:
      - HTTP_PROXY=172.17.0.1:8080
      - HTTPS_PROXY=172.17.0.1:8080
```

### What did you expect to see?
Traefik being able to connect to use Let's Encrypt, proxied containers available.

### What did you see instead?
Proxied containers unavailabe, error page of corporate proxy instead

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.14
Codename:     maroilles
Go version:   go1.12.8
Built:        2019-08-14_09:46:58AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
