### ISSUE TITLE
custom header to parse the Referrer in the Request headers for the kubernetes ingress

### ISSUE THREAD

**Issue by v-2vikc** [containous/traefik#5264]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?
No
### What did you do?

Unable to parse the referrer  in  the request headers while the redirect to https ( frontend UI)  > http  (backend kubernetes ingress)  

the referer in the request headers needs to be parsed to http://domain.com/console 

instead it is sending the request header as " https://domain.com/console " due to which the authentication is failing 
```
Request headers: 
Referer: https://domain.com/console
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
 InsecureSkipVerify = true
          defaultEntryPoints = ["http", "https"]
          [traefikLog]
            format = "json"
          [healthcheck]
          [entryPoints]
            [entryPoints.http]
              address = ":80"
              [entryPoints.http.redirect]
              entryPoint = "https"
            [entryPoints.https]
              address = ":443"
              compress = true
              [entryPoints.https.tls]
                minVersion = "VersionTLS12"
                cipherSuites = [
***********************************masking the ciphers*********************
              ]
          [retry]
            attempts = 3
          [forwardingTimeouts]
            dialTimeout = "10s"
          [acme]
            entryPoint = "https"
            onHostRule = true
            acmeLogging = true
            [acme.dnsChallenge]
              provider = "cloudflare"
              delayBeforeCheck = 60
          [[acme.domains]]
            main = "*.custom_domain"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
