### ISSUE TITLE
v2: Cannot get http and https entrypoints working under one `IngressRoute`

### ISSUE THREAD

**Issue by restanrm** [containous/traefik#5275]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I tried to setup an `IngressRoute` with two entrypoints (http and https), a redirection middleware and a `tls.certResolver`. 

### What did you expect to see?

I expected to be able to access the http endpoint (http://my.site.com) and be redirected to the https endpoint (https://my.site.com) with content. 

### What did you see instead?

The http endpoint redirect me to a 404 not found page (the backend service doesn't see the request). 
If I remove the `tls` section in the `IngressRoute` I'm redirected to https endpoint, but I get a 404 page again.
If I completely remove the https part in the `IngressRoute` everything works (in full http).
If I remove the `webSecure` entrypoint and the middleware, but keep the `tls` section, Nothing works (not even the http version).
If I create two `IngressRoute`,
1. only http content and redirect to https
2. only https content 

Everything works. It's kind of sad to have to create two `IngressRoutes` to do this. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-rc1
Codename:     montdor
Go version:   go1.13rc1
Built:        2019-08-26T17:47:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I'm using the KubernetesCRD definitions with kubernetes provider.

Here is my `traefik` configuration file: 
```yaml
accessLog: {}
log:
  level: DEBUG
api: {}
entryPoints:
  web:
    address: ":80"
  webSecure:
    address: ":443"
providers:
  kubernetesCRD: {}
certificatesResolvers:
  default:
    acme:
      email: "my.email.address@provider.com"
      storage: /acme.json
      tlsChallenge: {}
```

Here is my `Middleware` declaration:
```yaml
kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: https-only
  namespace: default
spec:
  redirectRegex:
    regex: ^http://(.*)
    replacement: https://${1}
#  redirectScheme:
#    scheme: https
#    permanent: true
```

And finally, here is the `IngressRoute` declaration with all the parameters: 
```yaml
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: site
spec:
  entryPoints:
  - web
  - webSecure
  routes:
  - match: Host(`my.site.com`)
    kind: Rule
    services:
    - name: site
      port: 80
    middlewares:
    - name: https-only
  tls:
    certResolver: default
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
