### ISSUE TITLE
whitelist-source-range does not work with EKS ELB 

### ISSUE THREAD

**Issue by mshivanna** [containous/traefik#5276]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [-] No

### What did you do?
Used traefik as the ingress controller with 
serviceType: LoadBalancer
externalTrafficPolicy: Local
On our ingress object these are our annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/whitelist-source-range: x.x.x.x/32
      ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
      traefik.ingress.kubernetes.io/preserve-host: "true"

### What did you expect to see?
To get access to only the whitelisted ip.

### What did you see instead?
403 forbidden when accessing the url from the whitelisted ip./

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "info"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[ping]
entryPoint = "http"
[kubernetes]
[traefikLog]
  format = "json"
[accessLog]
  format = "common"
[accessLog.fields]
  defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
  defaultMode = "keep"
[accessLog.fields.headers.names]
[api]
  entryPoint = "traefik"
  dashboard = true
```
