### ISSUE TITLE
Unable to get wildcard from godaddy with v2.0

### ISSUE THREAD

**Issue by cpw** [containous/traefik#5277]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I am testing traefik, and the ACME/LE support, and I am unable to create a valid (testing) wildcard certificate. I have the following configuration (traefik.toml):

```toml
[certificatesResolvers.forge.acme]
  email = "hushnow@goaway.com"
  storage = "/etc/traefik/acme.json"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

  [certificatesResolvers.forge.acme.dnsChallenge]
    provider = "godaddy"
    delayBeforeCheck = 0
```

and I have tried various variants of the following in a dynamicrouter.toml file:
```toml
[http.routers.routertestrp.tls]
      certResolver = "forge"
      [[http.routers.routertestrp.tls.domains]]
        main = "minecraftforge.net"
        sans = ["*.minecraftforge.net"]
```

### What did you expect to see?

I expected to see a test wildcard certificate issued.

### What did you see instead?

Errors:
```
time="2019-09-01T02:20:10Z" level=debug msg="No default certificate, generating one"
time="2019-09-01T02:20:10Z" level=debug msg="Looking for provided certificate(s) to validate [\"minecraftforge.net\" \"*.minecraftforge.net\"]..." providerName=forge.acme
time="2019-09-01T02:20:10Z" level=debug msg="No ACME certificate generation required for domains [\"minecraftforge.net\" \"*.minecraftforge.net\"]." providerName=forge.acme
time="2019-09-01T02:20:11Z" level=debug msg="legolog: [INFO] nonce error retry: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/6604129 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: \"0002gXyvVWXJP1dwRQEkM9_6aLHP46nCAAubwbB0_3AEBZA\", url: "
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/6604128"
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [minecraftforge.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/6604129"
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: use dns-01 solver"
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Could not find solver for: tls-alpn-01"
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Could not find solver for: http-01"
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: use dns-01 solver"
time="2019-09-01T02:20:12Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Preparing to solve DNS-01"
time="2019-09-01T02:20:13Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Trying to solve DNS-01"
time="2019-09-01T02:20:13Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Checking DNS record propagation using [8.8.8.8:53 8.8.4.4:53]"
time="2019-09-01T02:20:13Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
time="2019-09-01T02:20:13Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:15Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:17Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:19Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:22Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:24Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:26Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:28Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:30Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:32Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:34Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:36Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:39Z" level=debug msg="legolog: [INFO] [*.minecraftforge.net] acme: Cleaning DNS-01 challenge"
time="2019-09-01T02:20:40Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Preparing to solve DNS-01"
time="2019-09-01T02:20:40Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Trying to solve DNS-01"
time="2019-09-01T02:20:40Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Checking DNS record propagation using [8.8.8.8:53 8.8.4.4:53]"
time="2019-09-01T02:20:40Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
time="2019-09-01T02:20:40Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:42Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:45Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:47Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:49Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:51Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:53Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:55Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:20:57Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Waiting for DNS record propagation."
time="2019-09-01T02:21:00Z" level=debug msg="legolog: [INFO] [minecraftforge.net] acme: Cleaning DNS-01 challenge"
time="2019-09-01T02:21:02Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/6604128"
time="2019-09-01T02:21:03Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/6604129"
time="2019-09-01T02:21:03Z" level=error msg="Unable to obtain ACME certificate for domains \"minecraftforge.net,*.minecraftforge.net\" : unable to generate a certificate for the domains [minecraftforge.net *.minecraftforge.net]: acme: Error -> One or more domains had a problem:\n[*.minecraftforge.net] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record \"null\" found at _acme-challenge.minecraftforge.net, url: \n[minecraftforge.net] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record \"GkwPuQ2RHJkcPkw5s7yAaQv4u6jbljM346iKfQJOfG4\" found at _acme-challenge.minecraftforge.net, url: \n" providerName=forge.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2.0-rc1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "DEBUG"

[accessLog]

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamicrouters.toml"
    watch = true

[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.forge.acme]
  email = "no"
  storage = "/etc/traefik/acme.json"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

  [certificatesResolvers.forge.acme.dnsChallenge]
    provider = "godaddy"
    delayBeforeCheck = 0
```

```toml
[http]
[http.routers]
  [http.routers.routertestrp]
    entryPoints = ["web","websecure"]
    rule = "Host(`testrp.minecraftforge.net`)"
    middlewares = [ "discordredirect" ]
    [http.routers.routertestrp.tls]
      certResolver = "forge"
      [[http.routers.routertestrp.tls.domains]]
        main = "*.minecraftforge.net"
        sans = ["*.minecraftforge.net"]


[http.middlewares]
  [http.middlewares.discordredirect.redirectRegex]
    regex = "https://discord.minecraftforge.net/"
    replacement = "https://discord.gg/UvedJ9m"
    permanent = true

[http.services]
  [http.services.files.loadBalancer]
    [[http.services.files.loadBalancer.servers]]
      url = "http://files.minecraftforge.net"
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

debug logs are above.

### Things I have tried:

I have tried every combination of main and sans:
```
main="minecraftforge.net"
sans = [ "*.minecraftforge.net" ]
```
```
main="*.minecraftforge.net"
sans = [ "minecraftforge.net" ]
```
```
main="*.minecraftforge.net"
sans = [ "*.minecraftforge.net" ]
```

None of them work. They all seem to result in basically identical output.

I've cleaned the acme.json a couple of times, as well as deleting the txt record at godaddy.

Watching while it runs, I can see txt records appear, before finally being replaced by a "null" value at the end (this seems to be by design as you can't delete txt records thru godaddys API)

Reviewing the code for lego, it looks like it's trying to serially validate the DNS records, before submitting to LE for verification, but is cleaning up the TXT records first, so each LE validation only sees the "cleaned" DNS (propagation seems pretty fast) (i.e. the _next_ TXT relative to it's validation).

Searching these errors isn't turning up a lot of useful hits, here, LEGO or anywhere else.

I'd like to get this working - having a smart reverse proxy would be a big step up for us, but this LE stuff seems pretty difficult to get working properly. (My current solution : acme.sh, took about 1 minute to get working, in comparison to the about 8 hours spent on this so far).
