### ISSUE TITLE
v2.0 - Traefik thinks container is disabled on Swarm with exposedbydefault=false

### ISSUE THREAD

**Issue by tiagoad** [containous/traefik#5279]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

1. Started traefik on a Docker Swarm with the following compose service:

``` yaml
version: "3.2"
services:
  traefik:
    image: traefik:montdor
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=http"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internet
      - http
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        
networks:
  # internet access
  internet:
    external: true

  # http traffic network
  http:
    external: true
```

2. Started whoami container with the following compose:
```yaml
version: "3.2"
services:
  whoami:
    image: containous/whoami
    networks:
      - http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
        
networks:
  # http traffic network
  http:
    external: true
```

### What did you expect to see?

The container being detected by Traefik.

### What did you see instead?

The container is filtered by Traefik, even though it has the label "traefik.enable=true":

> http_traefik.1.ldwwpgs494gu@ip-10-10-30-22    | time="2019-09-02T11:16:40Z" level=debug msg="Filtering disabled container" providerName=docker container=test_whoami-muj2ubsrv25g39mf5phrvngud

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0-rc1
Codename:     montdor
Go version:   go1.13rc1
Built:        2019-08-26T17:47:29Z
OS/Arch:      linux/amd64
```
