### ISSUE TITLE
When I use  traefik 2.0-rc1 to expose the service(type: NodePort), traefik will keeps reporting errors in the pod

### ISSUE THREAD

**Issue by junshengxiedd01** [containous/traefik#5297]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

 No

### What did you do?

When I use the traefik 2.0 rc1 version to deploy service in a NodePort type, traefik will keeps reporting errors in the pod:
```
time="2019-09-04T12:30:28Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.96.0:39717: read: connection reset by peer"
time="2019-09-04T12:30:28Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.99.128:45919: read: connection reset by peer"
time="2019-09-04T12:30:28Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.98.129:20419: read: connection reset by peer"
time="2019-09-04T12:30:29Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.99.3:3814: read: connection reset by peer"
time="2019-09-04T12:30:29Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.97.131:2515: read: connection reset by peer"
```

When I modify the service to the ClusterIp type and re-execute kubectl apply -f traefik.yaml, it does not report an error.

### What did you expect to see?
No error

### What did you see instead?
```
time="2019-09-04T12:29:31Z" level=info msg="Traefik version 2.0.0-rc1 built on 2019-08-26T17:47:29Z"
time="2019-09-04T12:29:31Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-09-04T12:29:32Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-09-04T12:29:32Z" level=info msg="Starting provider *acme.Provider {\"caServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"storage\":\"acme.json\",\"keyType\":\"RSA4096\",\"Re
time="2019-09-04T12:29:32Z" level=info msg="Testing certificate renew..." providerName=default.acme
time="2019-09-04T12:29:32Z" level=info msg="Starting provider *crd.Provider {}"
time="2019-09-04T12:29:32Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2019-09-04T12:29:32Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2019-09-04T12:29:33Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.99.3:32179: read: connection reset by peer"
time="2019-09-04T12:29:33Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.97.131:14626: read: connection reset by peer"
time="2019-09-04T12:29:34Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.96.0:53407: read: connection reset by peer"
time="2019-09-04T12:29:34Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.97.2:7697: read: connection reset by peer"
time="2019-09-04T12:29:35Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.47:80->100.117.98.1:60606: read: connection reset by peer"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.0.0-rc1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0.0-rc1-alpine
          args:
            - --api=true
            - --api.dashboard=true
            - --api.debug=true
            - --global.checknewversion=false
            - --global.sendanonymoususage=false
            - --accesslog
            - --log=true
            - --log.filepath=/tmp/traefik.err.log
            - --log.level=DEBUG
            - --accesslog.filepath=/tmp/traefik.access.log
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: web
      port: 80
      nodePort: 30001
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443
  selector:
    app: traefik

---

apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.18.12.11
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: dadi-msa-k8s-node
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.15.3
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-04T12:52:31Z" level=info msg="Traefik version 2.0.0-rc1 built on 2019-08-26T17:47:29Z"
time="2019-09-04T12:52:31Z" level=debug msg="Static configuration loaded {\"global\":{\"sendAnonymousUsage\":false},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"addre
time="2019-09-04T12:52:31Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-09-04T12:52:31Z" level=debug msg="No default certificate, generating one"
time="2019-09-04T12:52:31Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-09-04T12:52:31Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2019-09-04T12:52:31Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-09-04T12:52:31Z" level=debug msg="Start TCP Server" entryPointName=web
time="2019-09-04T12:52:31Z" level=info msg="Starting provider *crd.Provider {}"
time="2019-09-04T12:52:31Z" level=debug msg="Using label selector: \"\"" providerName=kubernetescrd
time="2019-09-04T12:52:31Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2019-09-04T12:52:31Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2019-09-04T12:52:31Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.48:80->100.117.99.128:50003: read: connection reset by peer"
time="2019-09-04T12:52:31Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.48:80->100.117.98.129:6140: read: connection reset by peer"
time="2019-09-04T12:52:32Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"routers\":{\"default/simpleingressroute-03c8001524558edb33c2\":{\"entryPoints\":[\"web\"],\"mi
time="2019-09-04T12:52:32Z" level=debug msg="Creating middleware" serviceName=default/simpleingressroute-03c8001524558edb33c2 entryPointName=web middlewareName=pipelining middlewareType=Pipelining routerN
time="2019-09-04T12:52:32Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=default/simpleingressroute-03c8001524558edb33c2@kubernetescrd serviceName=default/simpleingressroute-03c8
time="2019-09-04T12:52:32Z" level=debug msg="Creating server 0 http://10.244.1.35:80" routerName=default/simpleingressroute-03c8001524558edb33c2@kubernetescrd serviceName=default/simpleingressroute-03c800
time="2019-09-04T12:52:32Z" level=debug msg="Added outgoing tracing middleware default/simpleingressroute-03c8001524558edb33c2" entryPointName=web routerName=default/simpleingressroute-03c8001524558edb33c
time="2019-09-04T12:52:32Z" level=debug msg="Creating middleware" middlewareType=ReplacePathRegex entryPointName=web routerName=default/simpleingressroute-03c8001524558edb33c2@kubernetescrd middlewareName
time="2019-09-04T12:52:32Z" level=debug msg="Adding tracing to middleware" middlewareName=default/replace-path-regex-mid@kubernetescrd entryPointName=web routerName=default/simpleingressroute-03c800152455
time="2019-09-04T12:52:32Z" level=debug msg="Creating middleware" entryPointName=web routerName=default/simpleingressroute-03c8001524558edb33c2@kubernetescrd middlewareName=default/auth-mid@kubernetescrd
time="2019-09-04T12:52:32Z" level=debug msg="Adding tracing to middleware" middlewareName=default/auth-mid@kubernetescrd entryPointName=web routerName=default/simpleingressroute-03c8001524558edb33c2@kuber
time="2019-09-04T12:52:32Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
time="2019-09-04T12:52:32Z" level=debug msg="No default certificate, generating one"
time="2019-09-04T12:52:32Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret" providerName=kubernetescrd
time="2019-09-04T12:52:32Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret" providerName=kubernetescrd
time="2019-09-04T12:52:32Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret" providerName=kubernetescrd
time="2019-09-04T12:52:32Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret" providerName=kubernetescrd
time="2019-09-04T12:52:32Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.48:80->100.117.97.2:45630: read: connection reset by peer"
time="2019-09-04T12:52:32Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.48:80->100.117.99.3:63314: read: connection reset by peer"
time="2019-09-04T12:52:32Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.48:80->100.117.96.129:5063: read: connection reset by peer"
time="2019-09-04T12:52:32Z" level=error msg="Error while Peeking first byte: read tcp 10.244.1.48:80->100.117.97.131:38765: read: connection reset by peer"

```
