### ISSUE TITLE
Multi-Level subdomains in Kubernetes

### ISSUE THREAD

**Issue by halradaideh** [containous/traefik#5304]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to create an Ingress Rule for multi level sub-domain in Kubernetes with Traefik, the Ingress object reject the syntax.

### What did you see instead?

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# ingresses.extensions "XXX" was not valid:
# * spec.rules[0].host: Invalid value: "*.*.x.y.z": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
# * spec.rules[0].host: Invalid value: "*.*.x.y.z": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: COOKIE
  name: XXX
  namespace: istio-system
spec:
  rules:
  - host: '*.*.x.y.z'
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /
  - host: x.y.z
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /

```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.12
```
