### ISSUE TITLE
Ingress with PathPrefixStrip & Root-path blocks access to other ingress with PathPrefix

### ISSUE THREAD

**Issue by bibliobeam** [containous/traefik#5308]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

In a Kubernetes cluster with Traefik as Ingress Controller, added an ingress with PathPrefixStrip & a root-path("/"). Added other ingresses with PathPrefixStrip and non-root path. All ingresses worked fine. Added a single PathPrefix with some non-root path.

### What did you expect to see?

Either 
1. Ingress with PathPrefix should forward the request to back-end.
Or
2. Traefik should explicitly reject the ingress with PathPrefixStrip & a root-path("/") combination as it is not logical.

### What did you see instead?

Accessing the front-end associated with the PathPrefix I received Got a 404 on the NodePort.

In the logs, 

1. X-Forwarded-Prefix is set to "/"
2. I see the response coming from the back-end associated with PathPrefixStrip & a root-path
     {"msg":"vulcand/oxy/forward/http: Round trip: **_$Path_Prefix_Strip_Backend_**, code: 404}

There is no hit on any of the back-ends.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

```
Kubernetes 1.13.7
_____________________________________________________________
                 Offending Ingress
_____________________________________________________________
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: $HOST
    http:
      paths:
      - backend:
          serviceName: $Service
          servicePort: $Port
        path: /
_____________________________________________________________
                 Failing Ingress
_____________________________________________________________
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: $HOST
    http:
      paths:
      - backend:
          serviceName: $Backend
          servicePort: $Port
        path: /foo

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: $Path_Prefix_Strip_Backend, code: 404, Length: 19, duration: 2.219219ms tls:version: 303, tls:resume:true, tls:csuite:c02f, tls:server:$HOST_NAME"}
```
