### ISSUE TITLE
v2: Include a minimal example in the documentation

### ISSUE THREAD

**Issue by jpillora** [containous/traefik#5318]
Hey guys,

Well done on v2 release. This project looks awesome :+1:

I'm looking for a miminal working example of proxying traffic to a localhost backend. Here's what I've got:

```yml
log:
  level: DEBUG
api:
  dashboard: true
accessLog: {}
entrypoints:
  my-entry:
    address: ":80"
http:
  routers:
    my-router:
      entryPoints:
      - "my-entry"
      service: my-service
  services:
    my-service:
      loadBalancer:
        servers:
        - url: "http://localhost:3000/"
```

I'm using the `traefik` 2.0 RC2 binary. I have a basic file server on port 3000. Performing a `GET` against `localhost` returns `404`, which I see in the access logs.

This is a request to expand the https://docs.traefik.io/v2.0/getting-started/quick-start/ page to include a minimal configuration file.

**Comment by ldez** [comment]
Hello,

- In the v2 the configuration static and the configuration dynamic cannot be mixed by default: you have to create 2 files.
- to use the `file` provider you have to enable the provider like in the v1.
  And for the v2 you have to define [the path to the dynamic configuration file](https://docs.traefik.io/v2.0/providers/file/#filename).

`traefik.yml`:

```yaml
log:
  level: DEBUG

api:
  dashboard: true

accessLog: {}

entrypoints:
  my-entry:
    address: ":80"

providers:
  file:
    filename: dynamic_conf.yml
```

`dynamic_conf.yml`:

```yaml
http:

  routers:
    my-router:
      entryPoints:
      - "my-entry"
      service: my-service

  services:
    my-service:
      loadBalancer:
        servers:
        - url: "http://localhost:3000/"
```
