### ISSUE TITLE
Traefik is using Endpoint address instead of Service IP address

### ISSUE THREAD

**Issue by majkrzak** [containous/traefik#5322]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [*] No

### What did you do?

I've exposed kubernets.default service via the traefik

### What did you expect to see?

kubernets.default service exposed via the trtaefik

### What did you see instead?

`Bad Gateway`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
iamge: traefik
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      namespace: default
      name: kubernetes
      annotations:
        kubernetes.io/ingress.class: traefik
        ingress.kubernetes.io/protocol: https
        traefik.frontend.rule.type: PathPrefixStrip
    spec:
      rules:
      - host: my.fancy.domain
        http:
          paths:
          - path: /kubernetes/
            backend:
              serviceName: kubernetes
              servicePort: https
```

### Coments with sense

Gennerally it should forward to the `10.43.0.1` internal service address, not to `127.0.0.1:6445`
Is it possible to configure it or something? Do I have to again go through sources?

**Comment by majkrzak** [comment]
```go
endpoints, exists, err := k8sClient.GetEndpoints(service.Namespace, service.Name)
if err != nil {
	log.Errorf("Error retrieving endpoints %s/%s: %v", service.Namespace, service.Name, err)
	return nil, err
}

if !exists {
	log.Warnf("Endpoints not found for %s/%s", service.Namespace, service.Name)
	break
}

if len(endpoints.Subsets) == 0 {
	log.Warnf("Endpoints not available for %s/%s", service.Namespace, service.Name)
	break
}

for _, subset := range endpoints.Subsets {
	endpointPort := endpointPortNumber(port, subset.Ports)
	if endpointPort == 0 {
		// endpoint port does not match service.
		continue
	}
	for _, address := range subset.Addresses {
		url := protocol + "://" + net.JoinHostPort(address.IP, strconv.FormatInt(int64(endpointPort), 10))
		name := url
		if address.TargetRef != nil && address.TargetRef.Name != "" {
			name = address.TargetRef.Name
		}

		templateObjects.Backends[baseName].Servers[name] = types.Server{
			URL:    url,
			Weight: weightAllocator.getWeight(r.Host, pa.Path, pa.Backend.ServiceName),
		}
	}
}```
Why it is done like that? It will be much better to use the Service.Address it will be much simpler and will work?
@ldez @timoreimann

**Comment by timoreimann** [comment]
Endpoint usage is required to implement specific features such as sticky sessions and weight-based routing. We couldn't do that if we directed traffic towards the Service directly because kube-proxy controls the request distribution (namely by implementing statistical routing only).

I don't know exactly why you're seeing `Bad Gateway`, but intuitively I wouldn't say that it has to do with the Services vs. Endpoints question: in the end, Services also rely on Endpoints (kube-proxy is effectively a watch on Endpoints that reconfigures iptables rules on changes), and it wouldn't take Endpoints into rotation that aren't ready yet. Being a similar listener to the Endpoints API, the same holds for Traefik.

The only thing that differs is how requests are routed.

**Comment by majkrzak** [comment]
The issue is with `apiserver` service. It's endpoint is 127.0.0.1:6445 (or some similar port). It simply can not work in traefik. Also why to duplicate "Service" job?

**Comment by timoreimann** [comment]
>The issue is with apiserver service. It's endpoint is `127.0.0.1:6445` (or some similar port).

Do you possibly run your master and worker components on the same (single) machine? Or why does the Service (which should look the same on all nodes) point to localhost?

What Kubernetes distro do you run on? Could you share your Service manifest?

>Also why to duplicate "Service" job?

We do not duplicate the functionality of the Service. The only thing we have in common with Services is that both that and Traefik listen for Endpoints. However, we route requests differently because we need more flexibility for certain features.

A Service forwards a request to a backing pod (and, equivalently, an endpoint) based on kube-proxy's model of distribution. If you have n pods, then each pod receives approximately every n-th request. That's what is often called statistical routing. To my knowledge, there's no way to change that with kube-proxy (though IPVS mode _may_ be able to do so).

On the contrary, Traefik needs more control over which pod (endpoint) receives a particular request. Let's take a closer look at sticky sessions: once a request has been received by a specific backend (pod / endpoint), we want all follow-up requests to also be received by that very same backend. So we encode the target backend into the cookie and leverage that information in all subsequent requests by routing the request to that specific backend. This wouldn't work if we directed traffic to the Service since it does not expose individual endpoints. Consequently, our "sticky session" would only be sticky towards the Service (which isn't a real route anyway since Service IPs are all virtual) after which statistical routing were to distribute traffic arbitrarily again.

Similar arguments hold for other features that also depend on connecting to endpoints directly.

FWIW, this is how most (all?) Ingress controllers work because even some very basic features require this level of flexibility.

**Comment by majkrzak** [comment]
Thank you for explanation.

I'm running k3os, which is quite quirky and badly documented. Hopefully I'm
able to set it up with just one config file.

About sticky sessions I've realized that if they will be enabled on Service
level it will bound the traefik to one pod.

It seems that the best solution will be define this route manually in toml.

pon., 9 wrz 2019, 01:16 użytkownik Timo Reimann <notifications@github.com>
napisał:

**Comment by timoreimann** [comment]
I don't have first hand experiences with k3os, but it seems to me that routing should be possible even when the Service points at localhost. Feel free to raise your question on one of the support channels (or go with a manual configuration, whatever you prefer).

**Comment by majkrzak** [comment]
Here is dump of service config:
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-08T14:24:22Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "156"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 5a7df0f6-d244-11e9-af98-02205cdbf4bd
spec:
  clusterIP: 10.43.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6445
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

and my traefik configuration
```toml
        defaultEntryPoints = ["https"]
        rootCAs = [ "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" ]
        logLevel = "DEBUG"
        [traefikLog]
        filePath = ""
        format   = "json"
        [accessLog]
        filePath = ""
        format = "json"
        [entryPoints]
          [entryPoints.http]
          address = ":80"
          compress = true
            [entryPoints.http.redirect]
            entryPoint = "https"
          [entryPoints.https]
          address = ":443"
          compress = true
            [entryPoints.https.tls]
            minVersion = "VersionTLS12"
            sniStrict = true
          [entryPoints.httpn]
          address = ":8080"
        [acme]
        onHostRule = true
        email = "my@mail"
        storage = "/data/acme.json"
        entryPoint = "https"
        KeyType = "EC256"
          [acme.httpChallenge]
          entryPoint = "http"
        [kubernetes]
        [api]
        entryPoint = "httpn"
        dashboard = true
```

I will raise the issue on k3os/k3s probably still today.

P.S.
Is it possible to port my traefik config to 2.0? I can not find any info about that. (especially default endpoints, auto ssl redirects, and acme)
