### ISSUE TITLE
Websocket connections result in Incorrect 'Sec-WebSocket-Accept' header value on 2.0.0-rc2

### ISSUE THREAD

**Issue by qsolutionsde** [containous/traefik#5330]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I was trying to set up an SSL termination for an http backend service which partially uses websocket connections. 

### What did you expect to see?

Working https and wss connections.

### What did you see instead?

Normal https via traefik works fine, but websocket upgrades do not work. 

Directly accessing the backend via http also works with Websockets.

The Chrome console shows the following error:

````
WebSocket connection to 'wss://...' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value
````

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.0.0-rc2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using traefik as standalone on a Debian 10 platform. Backend is also non-docker.

File-based config:

````yaml
http:
  routers:
    myroute:
      entryPoints: ['https']
      service: myservice
      rule: Host(`service.example.com`)

  services:
    myservice:
      loadBalancer:
        servers:
        - url: http://backend.local/
````

**Comment by qsolutionsde** [comment]
Static:

````yaml
serversTransport:
  forwardingTimeouts:
    dialTimeout: 60

entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

  ping:
    address: ":8082"
      
providers:
  file:
    filename: /opt/traefik/file/config.yml
    watch: true

api:
  dashboard: true
  debug: true

log:
  level: DEBUG
  filePath: /opt/traefik/log/traefik.log

accessLog:
  filePath: /opt/traefik/log/access.log
  
certificatesResolvers:
  letsencrypt:
    acme:
      email: xxx@example.com
      storage: /opt/traefik/acme.json
      dnsChallenge:
        provider: inwx
        resolvers:
         - "1.1.1.1:53"
         - "8.8.8.8:53"
````

Dynamic:
````yaml
http:
  routers:
    # redirects all http traffic to https
    redirect-ssl:
      entryPoints: ['http']
      rule: "HostRegexp(`{any:.*}`)"
      middlewares: ["redirect-https"]
      service: "dummy"
    myroute:
      entryPoints: ['https']
      service: myservice
      rule: Host(`service.example.com`)

  services:
    myservice:
      loadBalancer:
        servers:
        - url: http://backend.local/
    dummy:
      loadBalancer:
        servers:
        - url: ""

  middlewares:
    redirect-https:
      headers:
        sslRedirect: true

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
````

Just remove some personal data.

Hope that helps.

**Comment by juliens** [comment]
On your router `myroute` if you want to do TLS, you need to enable TLS.(https://docs.traefik.io/v2.0/routing/routers/#tls).
```
    myroute:
      entryPoints: ['https']
      service: myservice
      rule: Host(`service.example.com`)
      tls: {}
```

Can you retry with this?

**Comment by qsolutionsde** [comment]
Yes - was enabled. Deleted a bit too much, sorry:

````yml
    myroute:
      entryPoints: ['https']
      service: myservice
      rule: Host(`service.example.com`)
      tls: 
        certResolver: letsencrypt
````
TLS works fine - it is just the web sockets upgrade that doesn't work.
