### ISSUE TITLE
Traefik suddenly offers SSLv3

### ISSUE THREAD

**Issue by SISheogorath** [containous/traefik#5335]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I updated from 1.7.13 to version 1.7.14 of Traefik. Then run a TLS check (https://www.ssllabs.com/ssltest/) and suddenly got a rating downgrade from A+ of B.

### What did you expect to see?

I expected to see my original A+ rating to continue to be A+ due to secure defaults.

### What did you see instead?

Rating went down from A+ to B because Traefik suddenly starts to support SSLv3.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run --rm traefik:v1.7.14 version
Version:      v1.7.14
Codename:     maroilles
Go version:   go1.12.8
Built:        2019-08-14_09:46:58AM
OS/Arch:      linux/amd64
```

```
$ docker run --rm traefik:v1.7.13 version
Version:      v1.7.13
Codename:     maroilles
Go version:   go1.11.12
Built:        2019-08-08_04:46:14PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: '2'
services:
  proxy:
    image: traefik:v1.7.14
    cpu_shares: 3072
    mem_limit: 256mb
    memswap_limit: 512mb
    read_only: true
    depends_on:
      - dockersocket
    security_opt:
      - label=level:s0:c100

    ports:
    - "80:80"
    - "443:443"

    volumes:
    - "/var/srv/traefik/acme:/etc/traefik/acme"

    command: "-c /dev/null --docker --docker.endpoint=tcp://dockersocket:2375 --acme --acme.email=<redacted> --acme.storage=/etc/traefik/acme/acme.json --acme.entryPoint=https --acme.onhostrule --acme.dnsprovider=cloudflare --acme.dnschallenge --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 Compress:true TLS' --defaultentrypoints=http,https --docker.exposedbydefault=false --insecureskipverify=true"
```

I don't use an additional toml file for configuration.

I have an idea where it might comes from: 
https://github.com/containous/traefik/commit/989a59cc29f58e25c07dab2eab97f0f683cef5ab

At least this seems to be the latest change to the TLS code which might lead to autodetected SSLv3 support? As there is a cipher overlap between TLS1.0 and SSLv3 around `TLS_RSA_WITH_AES_128_CBC_SHA`, `TLS_RSA_WITH_AES_256_CBC_SHA` and `TLS_RSA_WITH_3DES_EDE_CBC_SHA`.
