### ISSUE TITLE
On demand ACME certificate for wildcard domain without wildcard certificate in traefik 2

### ISSUE THREAD

**Issue by everflux** [containous/traefik#5342]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I tried to convert a traefik 1.7 setup that is using http challenge to obtain let's encrypt TLS certificates for single hosts using a wildcard domain.
This seems to be impossible, I have to add explicit domains to a router when using a `HostRegexp` only as a rule

### What did you see instead?
Either the router is not recognized to match for the requested host or I need to add the TLS domains manually.

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik 2-rc2, docker image 8a815904a325

```
Version:      2.0.0-rc2
Codename:     montdor
Go version:   go1.13rc2
Built:        2019-09-03T20:18:16Z
OS/Arch:      linux/arm

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
http:
  routers:
    router-n2:
      entryPoints:
      - https
      middlewares:
      - secured
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.n2.example.com`)"
      tls:
        options: default
        certResolver: default
        domains:
        - main: "k8s.n2.example.com"
          sans:
          - "hello.n2.example.com"
      service: service-n2

# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
