### ISSUE TITLE
healthcheck does not respect 'scheme' setting

### ISSUE THREAD

**Issue by anlek** [containous/traefik#5345]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I setup a container to respond to `/_status` (via HTTP) and return `200` if the service is working as expected. However, when the container is still booting, this request will result in a `503` response.

### What did you expect to see?

I expected Traefik to ask the endpoint on `/_status` and when it sees a `200` response, it returns the container is 'healthy'.

### What did you see instead?

Traefik is asking for the endpoint on `/_status`, however, it's asking via **HTTPS**, even though scheme is set to HTTP.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.14
Codename:     maroilles
Go version:   go1.12.8
Built:        2019-08-14_09:46:58AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
        users = [
          "example:$apr1$XXXXXX"
        ]
  [entryPoints.http]
    address = ":80"
      # I tried disabling the redirect, in case this was causing the healthcheck to do a HTTPs request.
      # This is NOT the cause.
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
entrypoint="traefik"
  [api.statistics]
    recentErrors = 20

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[acme]
email = "info@example.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
```

### docker-compose traefik setup

```yaml
version: "3.4"
services:
  app:
    image: sweetapp:edge-v1
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.core.frontend.rule=Host:edge.example.com"
      - "traefik.core.frontend.errors.network.backend=error"
      - "traefik.core.frontend.errors.network.query=/{status}"
      - "traefik.core.frontend.errors.network.status=500-511"
      - "traefik.core.port=3000"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend.loadbalancer.stickiness.cookieName=yumyum"
      - "traefik.backend.healthcheck.path=/_status"
      - "traefik.backend.healthcheck.scheme=http"
    networks:
      edge_net:

networks:
  edge_net:
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-10T18:27:22Z" level=warning msg="Health check failed: Remove from server list. Backend: \"backend-app-green-core\" URL: \"http://172.18.0.5:3000\" Weight: 1 Reason: HTTP request failed: Get https://172.18.0.5:3000/_status: http: server gave HTTP response to HTTPS client"
time="2019-09-10T18:27:22Z" level=warning msg="Health check failed: Remove from server list. Backend: \"backend-app-blue-core\" URL: \"http://172.18.0.6:3000\" Weight: 1 Reason: HTTP request failed: Get https://172.18.0.6:3000/_status: http: server gave HTTP response to HTTPS client"
```
