### ISSUE TITLE
Version 2.0 Docs problem in Digest Middleware

### ISSUE THREAD

**Issue by einali** [containous/traefik#5352]
### Do you want to request a *feature* or report a *bug*?
Bug in docs

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
Just Follow version 2.0 documentations

### What did you expect to see?
Digest middle ware activated and authenticate for valid users.

### What did you see instead?
Authentication Error

### Output of `traefik version`: (_What version of Traefik are you using?_)
v2.0.0 RC 3

 
 

 

I think problem is this configuration is docs in 
https://docs.traefik.io/v2.0/middlewares/digestauth/
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-auth
spec:
  digestAuth:
    secret: authsecret

---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default

data:
  users: |2
    dGVzdDokYXByMSRINnVza2trVyRJZ1hMUDZld1RyU3VCa1RycUU4d2ovCnRlc3QyOiRhcHIxJGQ5
    aHI5SEJCJDRIeHdnVWlyM0hQNEVzZ2dQL1FObzAK
```
provided base64 is for basicAuth sample with apr as realm 

```
echo "dGVzdDokYXByMSRINnVza2trVyRJZ1hMUDZld1RyU3VCa1RycUU4d2ovCnRlc3QyOiRhcHIxJGQ5aHI5SEJCJDRIeHdnVWlyM0hQNEVzZ2dQL1FObzAK" | base64 -d
test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0
```
it seams right base64 code is this 
```
dGVzdDp0cmFlZmlrOmEyNjg4ZTAzMWVkYjRiZTZhMzc5N2YzODgyNjU1YzA1CnRlc3QyOnRyYWVmaWs6NTE4ODQ1ODAwZjllMmJmYjFmMWY3NDBlYzI0ZjA3NGUKCg==
```

BTW: how can i commit PR for documentations?
it seams 
[expected md file](https://github.com/containous/traefik/blob/master/docs/content/middlewares/digestauth.md)

is deprecated!!
