### ISSUE TITLE
dashboard not accessible without `api.insecure=true`

### ISSUE THREAD

**Issue by FancyBanana** [containous/traefik#5363]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

launched `Docker-compose basic example`:

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:montdor"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
```

### What did you expect to see?

dashboard at `http://localhost:8080`

### What did you see instead?

Connection reset error page

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
❯ docker run traefik:montdor version
Version:      2.0.0-rc3
Codename:     montdor
Go version:   go1.13
Built:        2019-09-10T17:10:04Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
in docker-compose file
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
