### ISSUE TITLE
Dashboard behind PathPrefix in 2.0 fails to load static assets

### ISSUE THREAD

**Issue by KiNgMaR** [containous/traefik#5374]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

The new dashboard in 2.0 does not seem to handle being put behind a `PathPrefix`. More specifically, the frontend continues to look for assets in `/dashboard` instead of `/traefik/dashboard`. Configuration:

```toml
[http.routers]
    [http.routers.api]
        entryPoints = ["http"]
        rule = "HostRegexp(`systems.{tld:[a-z0-9.-]+}`) && PathPrefix(`/traefik`)"
        service = "api@internal"
        middlewares = ["adminAuth", "traefikAcp", "securityHeaders"]

[http.middlewares]
    [http.middlewares.traefikAcp.stripPrefix]
        prefixes = ["/traefik"]
```

Generated HTML:

```html
<script type="text/javascript" src="/dashboard/js/app.b1a5516b.js"></script>
<script type="text/javascript" src="/dashboard/js/vendor.bf460595.js"></script>
```

### What did you expect to see?

The new dashboard, i.e. assets being loaded from relative paths.

### What did you see instead?

A white page, because assets are loaded with an absolute path.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
{"Version":"2.0.0-rc3","Codename":"montdor"}
```
