### ISSUE TITLE
Failed to list XXX: xxx is forbidden

### ISSUE THREAD

**Issue by zyf0330** [containous/traefik#5387]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I do nothing.
I use traefik in k8s, everything is ok. Yesteyday I upgraded backend deployment, and then cannot access it by traefik. Traefik is giving some error all the time.
I re-apply k8s config below then it works again. Every resource has no change before this time, and their created time is not changed too.
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.11
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: myns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: myns

---
# Source: traefik/templates/service.yaml

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ui
  namespace: myns
spec:
  selector:
    role: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      name: admin

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-lb
  namespace: myns
  annotations:
    traefik.ingress.kubernetes.io/affinity: 'true'
spec:
  selector:
    role: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
      nodePort: 20080
  type: NodePort

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-lb
  namespace: myns
  labels:
    role: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      role: traefik-ingress-lb
  template:
    metadata:
      labels:
        role: traefik-ingress-lb
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: traefik
                operator: In
                values:
                - 'true'
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - traefik-ingress-lb
              topologyKey: kubernetes.io/hostname
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: regcred
      containers:
      - image: docker-hub.duobeiyun.com:5000/traefik:v1.7.11
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-lb-external
  namespace: myns
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /socket.io
        backend:
          serviceName: connector-sio
          servicePort: 3000

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
It just records INFO level log.

```
E0916 01:07:33.903156       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:myns:traefik-ingress-controller" cannot list resource "ingresses" in API group "extensions" at the cluster scope
E0916 01:07:33.905982       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:myns:traefik-ingress-controller" cannot list resource "services" in API group "" at the cluster scope
E0916 01:07:33.907143       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:myns:traefik-ingress-controller" cannot list resource "endpoints" in API group "" at the cluster scope
E0916 01:07:34.904238       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:myns:traefik-ingress-controller" cannot list resource "secrets" in API group "" at the cluster scope
```
