### ISSUE TITLE
Allow merging of file and CLI configurations

### ISSUE THREAD

**Issue by duffn** [containous/traefik#5414]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In 1.7, one was allowed to use both the file provider configurations and CLI configurations simultaneously. They were merged in order to create a complete configuration. This has been removed in 2.0: https://community.containo.us/t/combining-file-and-cli-configurations/1651/2?u=duffn

I would like to have this feature in 2.0.

_Use Case_

File configurations

```toml
defaultEntryPoints = ["http","https"]

[providers.kubernetesCRD]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.http.proxyProtocol]
        trustedIPs = ["10.10.0.0/16"]

    [entryPoints.https]
    address = ":443"
    [entryPoints.https.proxyProtocol]
        trustedIPs = ["10.10.0.0/16"]

# Plus many more configurations...
```

Kubernetes deployment, where I would like to use the `DOGSTATSD_HOST_IP` environment variable in order to dynamically set the IP address of the host for Datadog metrics.

```yaml
containers:
    - name: traefik
      image: traefik:v2.0
      args:
          - --metrics.datadog
          - --metrics.datadog.address=$(DOGSTATSD_HOST_IP):8125
```

However, this is not possible with 2.0 and I must place _all_ of my configurations in the CLI configuration, which can quickly become unwieldy.
