### ISSUE TITLE
BasicAuth middleware reports error in logs despite working properly

### ISSUE THREAD

**Issue by duffn** [containous/traefik#5416]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Create a basic auth secret and use the secret with the Kubernetes CRD middleware. The basic auth _does_ in fact work, however, there are errors in the logs stating that the secret and middleware cannot be found when the container starts.

_Example application_

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: myns
  name: whoami-service-account

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: myns
  labels:
    app: whoami
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: myns
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      serviceAccountName: whoami-service-account
      containers:
        - name: whoami
          image: containous/whoami
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-route
  namespace: myns
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`subdomain.example.com`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: whoami-auth
      services:
        - name: whoami-service
          port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whoami-auth
  namespace: myns
spec:
  basicAuth:
    secret: basic-auth
    realm: whoami

---
```

### What did you expect to see?

I expect to see no errors in the logs, as the basic auth middleware does indeed work.

### What did you see instead?

These errors in the logs.

```
time="2019-09-18T14:52:01Z" level=info msg="Configuration loaded from flags."
time="2019-09-18T14:52:01Z" level=info msg="Traefik version 2.0.0 built on 2019-09-16T17:35:17Z"
time="2019-09-18T14:52:01Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2019-09-18T14:52:01Z" level=info msg="Enabling ProxyProtocol for trusted IPs [10.10.0.0/16]" entryPointName=https
time="2019-09-18T14:52:01Z" level=info msg="Enabling ProxyProtocol for trusted IPs [10.10.0.0/16]" entryPointName=http
time="2019-09-18T14:52:01Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-09-18T14:52:01Z" level=info msg="Starting provider *crd.Provider {}"
time="2019-09-18T14:52:01Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2019-09-18T14:52:01Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2019-09-18T14:52:02Z" level=error msg="Error while reading basic auth middleware: failed to load auth credentials: secret 'myns/basic-auth' not found" providerName=kubernetescrd middlewareName=myns-whoami-auth
time="2019-09-18T14:52:02Z" level=error msg="middleware \"myns-whoami-auth@kubernetescrd\" does not exist" entryPointName=http routerName=myns-whoami-ingress-route-b0ab85c9b280fdaf1ec3@kubernetescrd
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

CLI configuration.

```
- --providers.kubernetescrd
- --accesslog
- --log
- --log.level=INFO
- --entrypoints.http.Address=:80
- --entrypoints.http.proxyprotocol.trustedips=10.10.0.0/16
- --entrypoints.https.Address=:443
- --entrypoints.https.proxyprotocol.trustedips=10.10.0.0/16
- --metrics.datadog
- --metrics.datadog.address=$(DOGSTATSD_HOST_IP):8125
```
