### ISSUE TITLE
tls.options.default.clientAuth not working with docker swarm

### ISSUE THREAD

**Issue by pdbs** [containous/traefik#5417]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
in traefik.toml:
```toml
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384"]
    [tls.options.default.clientAuth]
      caFiles = ["/certs/test1.ca.crt", "/certs/test2.ca.crt"]
      clientAuthType = "RequireAndVerifyClientCert"
```

in docker compose:
```yaml
labels:
- "traefik.http.routers.xyz.tls.options=default"
```

### What did you expect to see?

Browser asking for client certificate (which is working in 1.7)

### What did you see instead?

Direct connection to docker service

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[Global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "DEBUG"

[api]
  insecure = true
  dashboard = true

[providers]
  [providers.docker]
    watch = true
    swarmMode = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_GCM_SHA384"]
    [tls.options.default.clientAuth]
      caFiles = ["/certs/test1.ca.crt", "/certs/test2.ca.crt"]
      clientAuthType = "RequireAndVerifyClientCert"

[certificatesResolvers.default.acme]
  email = "my@mailaddress"
  storage = "/certs/acme.json"
    [certificatesResolvers.default.acme.httpChallenge]
    entryPoint = "http"

```

**Comment by guirem** [comment]
Hi,

It also happens with docker without swarm.

When I disable the tls options label (ex "traefik.http.routers.xyz.tls.options=default") in docker compose, it will work again but without asking for cert that is normal behavior.

Traefik logs in debug doesn't show much but connection is neither rejected or aborted (it will timeout eventually)
> level=debug msg="Serving default certificate for request: \"xxxxxx.domain.com\""

**Comment by pdbs** [comment]
Hm, just tried with label removed, but no success: With traefik 1.7 browser asks for certificate, x-forwarded-tls-client-cert contains the client certificate - unfortunately not with 2.0. The x-forwarded-tls-client-cert header is not available. More logging in DEBUG (not only serving cert but also received client cert) would be helpful.

**Comment by jbdoumenjou** [comment]
Hi @pdbs ,

I tested the `tls.options.default.clientAuth` in a swarm cluster with different `clientAuthType` values and it seems to work as expected.
My docker-compose file:

```
version: "3.5"

services:
  traefik2:
    image: traefik:v2.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./certs/ca/MyRootCA.pem:/app/certs/ca/MyRootCA.pem
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./conf/dyn_conf.toml:/etc/traefik/conf/dyn_conf.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "443:443"
    networks:
      - webnet

  api2:
    image: containous/whoami
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - traefik.http.routers.webs.entrypoints=web-secure
        - traefik.http.routers.webs.rule=Host(`server`)
        - traefik.http.routers.webs.service=myservice
        - traefik.http.routers.webs.tls
        - traefik.http.services.myservice.loadbalancer.server.port=80
    networks:
      - webnet

networks:
  webnet:
```
My static configuration (traefik.toml):
```
# static configuration
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level="DEBUG"

[entryPoints.web-secure]
  address = ":443"

[providers.file]
    directory = "/etc/traefik/conf/"

[providers.docker]
  swarmMode = true
```

My dynamic configuration (dyn_conf.toml):
```
# dynamic configuration
[tls.options.default.clientAuth]
    caFiles = ["/app/certs/ca/MyRootCA.pem"]
# "NoClientCert", "RequestClientCert", "VerifyClientCertIfGiven" and "RequireAndVerifyClientCert".
    clientAuthType = "RequireAndVerifyClientCert"
```
I followed the documentation for [docker](https://docs.traefik.io/v2.0/providers/docker/#swarmmode) and [tls options](https://docs.traefik.io/v2.0/https/tls/#tls-options).

I tested both with swarm and a simple docker-compose and cannot reproduce the issue.
Let me known if it helps you.
