### ISSUE TITLE
Traefik 1.7.16 stuck, won't serve request with --logLevel=DEBUG 

### ISSUE THREAD

**Issue by nattster** [containous/traefik#5429]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Running traefik 1.7.16:
* inside docker container with `--logLevel=DEBUG` 
* use Docker provider

There are around 36 containers started/stopped during 19 hours period. 
It is working normally, until Traefik stopped forwarding request to any containers:
When the issue occurred, I can access traefik dashboard normally.

### What did you expect to see?
Request to docker containers work correctly.

### What did you see instead?
Connection established. But no response from traefik.

```
curl -v -k https://container.domain.com
* About to connect() to container.domain.com port 443 (#0)
*   Trying 127.0.0.1...
* Connected to hello.test (127.0.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: container.domain.com
> Accept: */*
>
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.16
Codename:     maroilles
Go version:   go1.12.9
Built:        2019-09-13_01:12:20PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/some.crt"
      keyFile = "/opt/some.key"
  [entryPoints.api]
  address = ":5566"

[api]
entryPoint = "api"

[docker]
exposedByDefault = false

```

Using docker image: traefik:v1.7.16-alpine

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-19T11:19:38Z" level=debug msg="Filtering disabled container /container.hello.com_1_f673ec0b96a5"
time="2019-09-19T11:19:38Z" level=debug msg="Filtering disabled container /container2.hello.com_1_abba792ef6b0"
```

I have try running traefik again with `debug = true` and got following
[full goroutine stack dump](https://github.com/containous/traefik/files/3631950/goroutine.txt)
![pprof001](https://user-images.githubusercontent.com/463831/65257192-08400200-db2b-11e9-9ec3-076f674b5746.png)
[pprof001.zip](https://github.com/containous/traefik/files/3631982/pprof001.zip)

**Comment by dduportal** [comment]
Hi @nattster , thanks for reporting! Could you share a reproduction case, or at least the full docker-compose / `docker build` command to help us please?

If possible, sharing the lables of the backends containers could help us as well.

Also: did you have the same behavior with `1.7.14` or `1.7.15` version?

**Comment by nattster** [comment]
I did not use docker swarm. Just docker-compose.
Full docker-compose for traefik:
```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:v1.7.16-alpine
    command: --logLevel=DEBUG
    ports:
      - "80:80"
      - "5566:5566"
      - "443:443"
    networks:
      - traefik-net
    environment:
      - http_proxy=http://someproxy:3128
      - https_proxy=http://someproxy:3128
      - no_proxy=localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,169.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local,172.18.0.0/12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /opt:/opt
    restart: always

networks:
  traefik-net:
    external: true
```

Backend containers: (container.domain.com, container2.domain.com, ...)
```yml
version: '3.4'

services:
  nginx:
    image: nginx
    restart: always
    expose:
      - "80"
    networks:
      - internal
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:container.domain.com"

networks:
  internal:
  traefik-net:
    external: true
```

I also face this issue with `1.7.14`, and before upgrading to `1.7.16`.
I don't have exact reproduction steps. 

But I just realized that I have been using traefik with `--logLevel=DEBUG` for quite sometime.
Recently, when I got more containers added/removed, this problem start to occur more frequently (everyday).
