### ISSUE TITLE
Error when multiple services are defined

### ISSUE THREAD

**Issue by simonszu** [containous/traefik#5435]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Similarly to https://github.com/containous/traefik/issues/4807 i defined multiple services for a docker container. Contrary to the linked issue i already defined each router's service. This is the list of labels i am using:

```
      traefik.enable: "true"
      traefik.http.routers.fr24-web.rule: "Host(`fr24.{{ traefik_domain }}`)"
      traefik.http.routers.fr24-web.entrypoints: "web"
      traefik.http.routers.fr24-web.middlewares: "redirect@file"
      traefik.http.routers.fr24-web-secured.rule: "Host(`fr24.{{ traefik_domain }}`)"
      traefik.http.routers.fr24-web-secured.entrypoints: "web-secure"
      traefik.http.routers.fr24-web-secured.middlewares: "auth@file"
      traefik.http.routers.fr24-web-secured.service: "fr24-web"
      traefik.http.routers.fr24-web-secured.tls.certresolver: "le"
      traefik.http.services.fr24-web.loadbalancer.server.port: "8080" 

      traefik.http.routers.frconf.rule: "Host(`frconf.{{ traefik_domain }}`)"
      traefik.http.routers.frconf.entrypoints: "web"
      traefik.http.routers.frconf.middlewares: "redirect@file"
      traefik.http.routers.frconf-secured.rule: "Host(`frconf.{{ traefik_domain }}`)"
      traefik.http.routers.frconf-secured.entrypoints: "web-secure"
      traefik.http.routers.frconf-secured.middlewares: "auth@file"
      traefik.http.routers.frconf-secured.service: "frconf"
      traefik.http.routers.frconf-secured.tls.certresolver: "le"
      traefik.http.services.frconf.loadbalancer.server.port: "8754" 
```

### What did you expect to see?
No errors, everything's working. 

### What did you see instead?
```
time="2019-09-19T11:39:10Z" level=error msg="Could not define the service name for the router: too many services" providerName=docker routerName=fr24-web
time="2019-09-19T11:39:10Z" level=error msg="Could not define the service name for the router: too many services" routerName=frconf providerName=docker
```
Note that thesse routers are the insecure routers which just should redirect to HTTPS via middleware. 
Accessing the services via browser is working fine, even the redirect. It's just these two error messages. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  web-secure: 
    address: ":443"
  traefik:
    address: ":8082"

metrics:
  prometheus: {}

accessLog: {}

certificatesResolvers:
  le:
    acme:
      email: mail@simonszu.de
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false

  file:
    directory: /conf.d
    watch: true
```
