### ISSUE TITLE
TLS option "minVersion" does not work as expected in v2

### ISSUE THREAD

**Issue by artiommocrenco** [containous/traefik#5445]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

No

### What did you do?

1. Deployed traefik v2 with Kubernetes CRD provider
2. Created IngressRoute and TLSOption (minVersion: VersionTLS12)
3. Used Qualys SSL Server Test to test the server configuration

### What did you expect to see?

I expected to see **only TLS v1.2 and v1.3** being supported by the server

### What did you see instead?

I saw that TLS **v1.0**, v1.2 and v1.3 are being **supported** by the server, but **not TLS v.1.1**

![image](https://user-images.githubusercontent.com/28516476/65371664-9a9cee80-dc6e-11e9-9259-29cbc8980650.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# traefik version
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.14

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: minversion
  namespace: "test"
spec:
  minVersion: VersionTLS12
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-tls
  namespace: "test"
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`example.com`)"
      kind: Rule
      services:
      - name: test
        port: 80
  tls:
    secretName: example-tls
    options:
      name: minversion
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by artiommocrenco** [comment]
If I set it to VersionTLS12 I get the following results from Qualys

![image](https://user-images.githubusercontent.com/28516476/65371744-7c83be00-dc6f-11e9-869c-0863c2d4635e.png)

**Comment by FossoresLP** [comment]
This happens because even though you have configured your service to use TLS 1.2 (or 1.3) as a minimum version the default router for Traefik still uses TLS 1.0 which is detected by Qualys when testing clients without SNI.

Please note that this will NOT affect any modern browsers and no user will reach your service trough TLS 1.0. The router is only used to deliver error pages when the request cannot be forwarded. Older browsers without SNI will simply not be able to access your service at all.

It would still be great if there would be a universal "Disable TLS 1.0" config option.

**Comment by FlDutchman** [comment]
The key is to set the minimum TLS version as a default tls setting:

```
tls:
  options:
    default:
      minVersion: VersionTLS12
```

**Comment by dduportal** [comment]
Hi @artiommocrenco , could you set the namespace to the value `test` in the object `IngressRoute` (key `spec.tls.options.namespace`) please?

As the default value for the namespace is `default`, the IngressRoute might be missing the tls options you created in the namespace `test.

**Comment by mpl** [comment]
Hello @artiommocrenco , to build upon what @FossoresLP and @FlDutchman have said, if any of the requests sent by your testing software are not routed by the router you defined in "test-tls", then they wont use the "minversion" option you defined, since it only applies for the aforementioned router. They will use the default tls option, for which you have not defined the minVersion. Hence the solution proposed by @FlDutchman .

Therefore, are you sure that all the requests you're sending are sent to example.com, and hence routed by "test-tls" ?

**Comment by artiommocrenco** [comment]
Sorry but I found no definition in Traefik docs about the "default router".

What it says, is that entrypoint is only a listening port, and a router is what I have control upon.

Is there something in between?

**Comment by artiommocrenco** [comment]
setting TLSOption's `spec.tls.options.namespace` does change the results above

regarding YML provided by @FlDutchman , what relation does it have to KubertnetesCRD Traefik provider?

**Comment by FlDutchman** [comment]
Sorry I didn't see at first you were using k8s. Just set minVersion in the default name and namespace as shown here in the docs: [https://docs.traefik.io/https/tls/#minimum-tls-version](https://docs.traefik.io/https/tls/#minimum-tls-version) Click on the Kubernetes field (if you open the yaml field you see my config)

**Comment by artiommocrenco** [comment]
Maybe upon "default router" you understand an IngressRoute with ```Host(`*`)``` -- I have it, but it is attached only to non-TLS entrypoint and only serve a "scheme redirect" purpose.

**Comment by artiommocrenco** [comment]
> Sorry I didn't see at first you were using k8s. Just set minVersion in the default name and namespace as shown here in the docs: https://docs.traefik.io/https/tls/#minimum-tls-version Click on the Kubernetes field (if you open the yaml field you see my config)
> 
> ```
> apiVersion: traefik.containo.us/v1alpha1
> kind: TLSOption
> metadata:
>   name: default
>   namespace: default
> 
> spec:
>   minVersion: VersionTLS12
> ```

I did it right now. I believe it is not picked up by traefik because test results did not change.

A little bit about my set up. I do not use the `default` namespace in Kubernetes at all. But I did what you said, I created the TLSOption in it with the name default.

**Comment by FlDutchman** [comment]
I'm no expert in k8s but try it with the original namespace "test" and the name default:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: "test"

spec:
  minVersion: VersionTLS12
```
