### ISSUE TITLE
unable to specify multiple TLSOptions for an IngressRoute in Kubernetes CRD provider

### ISSUE THREAD

**Issue by artiommocrenco** [containous/traefik#5447]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

No

### What did you do?

I tried to specify multiple options under one TLSOption resource like so:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: test
  namespace: "test"
spec:
  cipherSuites:
  - TLS_AES_256_GCM_SHA384
  minVersion: VersionTLS13
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-tls
  namespace: "test"
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`example.com`)"
      kind: Rule
      services:
      - name: test
        port: 80
  tls:
    secretName: test-tls
    options:
      name: test
```

and I see that only `minVersion: VersionTLS13` option is applied.

I also tried setting the options like so 

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: test1
  namespace: "test"
spec:
  cipherSuites:
  - TLS_AES_256_GCM_SHA384
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: test2
  namespace: "test"
spec:
  minVersion: VersionTLS13
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-tls
  namespace: "test"
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`example.com`)"
      kind: Rule
      services:
      - name: test
        port: 80
  tls:
    secretName: test-tls
    options:
      - name: test1
      - name: test2
```

and they are also not applied both, but, this time, traefik logs and error similar to the following:

```
E0921 09:28:04.143014       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190718183610-8e956561bbf5/tools/cache/reflector.go:98: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: v1alpha1.TLS.Options: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|options":[{"name":"m|..., bigger context ...|me":"test","port":80}]}],"tls":{"options":[{"name":"minversion"}],"secretName":"test-t|...
```

This happens because traefik does not expect an array of `options` in IngressRoute's `spec.tls.options` (whoever did this... please don't do it in the future)

### What did you expect to see?

I'd expect to be able to configure multiple TLSOptions for an IngressRoute either by specifying an array of their names in IngressRoute's `spec.tls.options` or by specifying multiple options under TLSOptions's `spec`.

### What did you see instead?

I saw no possibility to configure multiple TLSOptions for an IngressRoute in Kubernetes CRD.

#5312 might be related to this 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# traefik version
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.14

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by ldez** [comment]
Hello,

The following configuration is not valid, `options` is not a list.
 
```
  tls:
    secretName: test-tls
    options:
      - name: test1
      - name: test2
```

**Comment by artiommocrenco** [comment]
@ldez hello, you just closed an issue without reading it

**Comment by ldez** [comment]
I've read the issue, but maybe my answer is too short.

First it's not a bug, it's the expected behavior.

It's only possible to set one TLS options, because we can use only one TLS options block per router by design and it's not specific to the k8s provider.

Could you explain why you want to use multiple TLSOptions?

**Comment by artiommocrenco** [comment]
@ldez sure, I'll elaborate

I'd like to be able to configure TLS for my traefik router. 

By "configure" I understand being able to set **multiple** options, either by specifying an array of their names in IngressRoute's `spec.tls.options` (you said it is not supported, and I can understand it) **or at least by specifying multiple options under TLSOptions's spec**.

In issue description I provided 2 test cases (array of names in IngressRoute's `spec.tls.options` and a list of options in  TLSOption's `spec`, both don't work, so I assume that it is currently not possible to configure multiple TLS options for a router, which is.. unexpected!

You would like to configure multiple TLS options per router by design.

So I think its a design problem

@dtomcej @stffabi @jbdoumenjou

**Comment by artiommocrenco** [comment]
To simplify,

I would like to configure `minVersion` and `cipherSuites` for a router. And I am not able to do it in Kubernetes CRD, like, there is no way to do it, it seems.

**Comment by ldez** [comment]
In one TLS options block you can define `minVersion` **and** `cipherSuites`.

**Comment by ldez** [comment]
I think I see where there is confusion:

> TLS 1.3 cipher suites are not configurable. All supported cipher suites are safe, and if PreferServerCipherSuites is set in Config the preference order is based on the available hardware.

https://golang.org/doc/go1.12#tls_1_3

**Comment by ldez** [comment]
So I think we need add this information in the Traefik documentation.

**Comment by ldez** [comment]
Take a look to #5448

**Comment by artiommocrenco** [comment]
I can understand that, thanks a lot for putting your time to explaining this! Using 

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: test
  namespace: test
spec:
  cipherSuites:
  - TLS_RSA_WITH_AES_128_GCM_SHA256
  minVersion: VersionTLS12
```
works as expected. 

This is not a limitation of TLS protocol, its a limitation of Go crypt package.

Suddenly a Go package limitation becomes a Traefik limitation, I think Traefik team should be aware of cases like this and maybe there is sense to make a separate docs section called "Known issues".

I believe that being able to configure ciphersuites, even for TLS 1.3, is an important and basic feature a product like Traefik should support. Same as enabling TLS 1.2 without TLS 1.3 in traefik v2. 

Because I believe that Traefik is powerful, not because I am cocky! When comparing nginx/haproxy/etc. ingress controller with traefik ingress controller, I am not comparing C programming language with Go, instead I we are judging by product features
