### ISSUE TITLE
Ping doesn't work over https entry point on traefik v2

### ISSUE THREAD

**Issue by ruimarinho** [containous/traefik#5451]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you expect to see?

`https://my.domain/ping` to return 200 instead of 404.

### What did you see instead?

A 404 error.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
entryPoints:
  http:
    address: :80
  https:
    address: :443

ping:
  entryPoint: https
```

If the entryPoint is set to http, `http://my.domain/ping` works fine. This used to work correctly on 1.7.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ldez** [comment]
Hello,

In the v2 the TLS is managed on the router (https://docs.traefik.io/v2.0/routing/routers/#tls) not on the entry point.

So, with your configuration the following call works:

```console
$ curl http://127.0.0.1:443/ping
OK 
```

**Comment by ruimarinho** [comment]
It doesn't work without TLS unless I set the entryPoint to http. What is your suggestion to make it work with TLS? Something like the above?

```
http:
  routers:
    ping:
      rule: "Host(`my.domain`) && Path(`/ping`)"
      tls: {}
```

**Comment by ruimarinho** [comment]
@ldez adding a router pointing to the internal url works, but since traefik is already pushing a route (https://github.com/containous/traefik/blob/e4e2a188c5c03ba305022ab0d2797e89b4ba7701/pkg/server/router/route_appender_aggregator.go#L22) wouldn't it be easier to add route configuration to `ping` instead?

**Comment by ruimarinho** [comment]
@ldez can you reconsider opening this ticket please?

**Comment by dduportal** [comment]
Hi @ruimarinho, this issue has been closed since the challenge you had is answered: it is not possible to use https for ping with `v2.0.0`.

If you think this deserves a proposal, could you open an issue of type "feature request" (as it would be a potential enhancement), describing the proposal with some configurations and expected behaviors. I don't decide which feature is done when, but having a clear proposal would help contributors and could start discussion. Thanks a lot for your understanding!

**Comment by ruimarinho** [comment]
@dduportal I was able to get this working by using traefik-in-traefik :-) I would definitely add support for https endpoints.

```
http:
  routers:
    ping:
      rule: "Host(`example.com`) && Path(`/ping`)"
      entryPoints:
        - https
      service: ping
      tls: {}
  services:
    ping:
      loadBalancer:
        servers:
          - url: http://127.0.0.1
```
