### ISSUE TITLE
Problem for Migration from 1.7.x to v2.0

### ISSUE THREAD

**Issue by v7lin** [containous/traefik#5456]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [x] Yes
- [ ] No

### What did you do?

What's wrong? Why it doesn't work?

```shell
docker stack deploy -c <(docker-compose -f docker-swarm.yml config) traefik
```

```yaml
# 版本
version: "3.7"

# 服务
services:

  # 暂不支持设置时区
  traefik:
    image: traefik:v2.0.0
    ports:
      - 80:80
      - 443:443
#      - 8080
    networks:
      - net # traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../dev-ops-repo/traefik/acme:/etc/traefik/acme
#    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
#      - "--log.level=DEBUG"
#      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.traefikresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.traefikresolver.acme.httpchallenge.entrypoint=web"
#      - "--certificatesresolvers.traefikresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.traefikresolver.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}"
      - "--certificatesresolvers.traefikresolver.acme.storage=/etc/traefik/acme/acme.json"
#      - "--certificatesresolvers.traefikresolver.acme.storage=/etc/traefik/acme/acme-staging.json"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager # 部署位置，只在管理节点部署
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.middlewares=redirect"
        - "traefik.http.routers.traefik-secured.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.traefik-secured.entrypoints=websecure"
        - "traefik.http.routers.traefik-secured.tls.certresolver=traefikresolver"
        - "traefik.http.routers.traefik-secured.middlewares=auth"
        - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_BASIC}"

networks:
  # docker stack deploy -c <(docker-compose -f docker-swarm.yml config) traefik
  # Creating network traefik_net
  # 外部引用 "traefik_net"
  net:
    driver: overlay
    attachable: true
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
