### ISSUE TITLE
HTTP and HTTPS exist in the same router Accessing http://domain results in 404 .But accessing http://domia is normal

### ISSUE THREAD

**Issue by peiwenjian** [containous/traefik#5458]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ ] No

### What did you do?

When Entrypoints configured both HTTP and HTTPS, I set redictscheme: HTTPS, but I did not redirect to https://domain when visiting http://domian. Instead, the browser reported an error of 404

### What did you expect to see?
I want to access http://domain and redirect to https://domain

### What did you see instead?

Access http://domian without jumping https://domian, the interface shows 404

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik: v2.0
docker:18.03.1-ce
kubernetes:v1.11.2
OS: Centos7.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

config：
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: admin
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`pwjtest.zhixueyun.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: traefik
      port: 18080
    #  scheme: https
    middlewares:
    - name: admin-https
    - name: admin-auth
    #- name: admin-header
  tls:
    secretName: supersecret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-auth
spec:
  basicAuth:
    secret: authsecret
```

```
        - --api.insecure
        - --accesslog
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --entrypoints.traefik.Address=:18080
        - --api.dashboard=true
        - --providers.kubernetescrd
```
