### ISSUE TITLE
Unable to find sticky support about kubernetes CRD  on traefik v2

### ISSUE THREAD

**Issue by zhaoguangqiang** [containous/traefik#5460]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I want to use the latest traefik for my kubernetes. Before that, i test the traefik 1.7 with my kubernetes. But when i update traefik to v2.0, i found i can't use it smoothly. 

For example, unable to realize sticky support about kubernetes CRD  on traefik v2.

### What did you expect to see?

Expect "set-cookie:abc=xxxxxx" in curl response header

### What did you see instead?

Without  "set-cookie:abc=xxxxxx" in curl response header

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik v2.0

```
traefik                                            v2.0                50d512b8fa3b        6 days ago          69.1MB
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

* `traefik-config.yaml`

```yaml
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    api:
      insecure: true
      dashboard: true
    ping: {}
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    providers:
      kubernetesCRD: {}
      file:
        filename: /etc/traefik/traefik.yml
        watch: true
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /ssl/tls.crt
            keyFile: /ssl/tls.key
```

* `services.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: load-drift
  name: load-drift
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  ports:
  - name: 8010-8010
    port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: load-drift
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```console
$ curl -kv https://dal-ubuntu/myip                                                                                                                      0 < 20:34:50
*   Trying 127.0.1.1...
* Connected to dal-ubuntu (127.0.1.1) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: ncserver-ca (does not match 'dal-ubuntu')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=ncserver-ca
* 	 start date: Mon, 26 Aug 2019 03:14:18 GMT
* 	 expire date: Fri, 11 Jan 2047 03:14:18 GMT
* 	 issuer: CN=ncserver-ca
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /myip HTTP/1.1
> Host: dal-ubuntu
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: max-age=600
< Content-Length: 11
< Content-Type: text/plain
< Date: Mon, 23 Sep 2019 12:50:50 GMT
< Server: BaseHTTP/0.3 Python/2.7.12
< 
* Connection #0 to host dal-ubuntu left intact
10.244.1.10⏎                                                                 
```
