### ISSUE TITLE
Provide dnsChallenge credentials per resolver

### ISSUE THREAD

**Issue by bstuff** [containous/traefik#5472]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

multiple resolvers is 🔥
but what if I have multiple accounts

something like this:
```
[certificatesResolvers.sample1.acme]
  email = "info@example.com"
  storage = "acme/acme.json"
  [certificatesResolvers.sample1.acme.dnsChallenge]
    provider = "cloudflare"
    <API_KEY> = <.......>
[certificatesResolvers.sample2.acme]
  email = "info2@example.com"
  storage = "acme/acme.json"
  [certificatesResolvers.sample2.acme.dnsChallenge]
    provider = "cloudflare"
    <API_KEY> = <.......>
```

use case: Traefik running multiple domains that belongs to different accounts on Cloudflare

**Comment by dduportal** [comment]
Hi @bstuff , thanks for reporting this use case. This issue is labelled as "proposal" as there should be a discussion on the topics below:

It looks like that implementing this would require the following challenge to be solved:

- Disparity of behavior between DNS providers: using token, API key, instance profiles or any other way for using account credentials depends on the provider. This could cause a lot of complexity.
- Some providers make it really hard for this. Example with AWS where the client has to manage credentials between API keys, instance profiles and IAM roles. Profiles should be used in this case, but only in this case.

Finally, please note that this proposal would lead to some changes in Lego (the library used for ACME usage in Traefik), not only on Traefik.

**Comment by orblazer** [comment]
Hello, something is new for that proposal ?

I ask because i want setup traefik with multiple domains but i have multiple credentials :(
For now i am oblige to manage certificates with certbot externally to traefik.

Thanks.

**Comment by er1z** [comment]
May be a solution is to run the `lego` as a separated process? It would be really nice to have separated credentials per domain…

**Comment by debilausaure** [comment]
I have a specific use case for this, which I hope will bring interest to this feature request.

I share a server with someone, and we have two domains, one each. We use Traefik to redirect users to our respective containerized services and provide the respective certificates, which are both **wildcard** certs. 

It'd be a great value to add this feature to Traefik, since I think it matches its philosophy quite well.
Being able to configure secrets per provider would also be quite nice.

#5632 seems related

**Comment by debilausaure** [comment]
Here is an idealized `Dockerfile` that mimics the actual [DNS challenge user guide](https://docs.traefik.io/v2.0/user-guides/docker-compose/acme-dns/).

```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Arguments related to generating "domain1.ex" certificates
      - "--certificatesresolvers.domain1_resolver.acme.dnschallenge=true"
      - "--certificatesresolvers.domain1_resolver.acme.email=postmaster@domain1.ex"
      - "--certificatesresolvers.domain1_resolver.acme.storage=/letsencrypt_domain1/acme.json"
      - "--certificatesresolvers.domain1_resolver.acme.dnschallenge.provider=_domain1_provider"
      # would be best to use secrets here
      - "--certificatesresolvers.domain1_resolver.acme.dnschallenge.provider.apikey=..."
      # Arguments related to generating "domain2.ex" certificates
      - "--certificatesresolvers.domain2_resolver.acme.dnschallenge=true"
      - "--certificatesresolvers.domain2_resolver.acme.email=postmaster@domain2.ex"
      - "--certificatesresolvers.domain2_resolver.acme.storage=/letsencrypt_domain2/acme.json"
      - "--certificatesresolvers.domain2_resolver.acme.dnschallenge.provider=_domain2_provider"
      # would be best to use secrets here
      - "--certificatesresolvers.domain2_resolver.acme.dnschallenge.provider.apikey=..."

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Bind mount storing certificates for "domain1.ex"
      - "/home/domain1_postmaster/lets_encrypt:/letsencrypt_domain1"
      # Bind mount storing certificates for "domain2.ex"
      - "/home/domain2_postmaster/lets_encrypt:/letsencrypt_domain2"

  whoami_domain1:
    image: "containous/whoami"
    container_name: "whoami_domain1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain1.ex`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=domain1_resolver"

  whoami_domain2:
    image: "containous/whoami"
    container_name: "whoami_domain2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain2.ex`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=domain2_resolver"

```
