### ISSUE TITLE
TCP k8s mysql route can't  be access

### ISSUE THREAD

**Issue by swqmaven** [containous/traefik#5478]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ *] No

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik 2.0 version

```
[root@ks-allinone 2.0]# docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:26:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false


Traefik 2.0 image
```

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: traefik:v2.0
        name: traefik-ingress-lb
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
        - name: websecure
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --entrypoints.middleware.Address=:81
        - --api.insecure=true
        - --providers.kubernetescrd
        - --api
        - --api.dashboard=true
        - --accesslog
        - --log=true
        - --log.level=DEBUG
        - --log.filePath=/path/to/traefik.log
---




apiVersion: v1
kind: Service
metadata:
  name: test-mysql
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: test-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test-mysql
    spec:
      containers:
      - image: mysql:5.7.20
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1q2w3e4r
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: H89lBgAg
        ports:
        - containerPort: 3306
          name: mysql


kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      name: admin


apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-ir-tcp
  namespace: default
spec:
  entryPoints:
    - middleware
  routes:
  - match: HostSNI(`mysql.test.com`)
    services:
    - name: test-mysql
      port: 3306
      passHostHeader: true
      responseForwarding:
        # (default 100ms) Interval between flushes of the buffered response body to the client.
        flushInterval: 100ms
```

this is my k8s deployment yaml file. if config HostSNI(*) it's ok .
TCP host router can't be used none TLS endpoint?
