### ISSUE TITLE
Namespaced Middleware isn't found in k8s CRD

### ISSUE THREAD

**Issue by denysvitali** [containous/traefik#5480]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Created a namespaced service, IngressRoute and Middleware

### What did you expect to see?

I expected Traefik to find the namespaced Middleware and use it.

### What did you see instead?

<img width="478" alt="Screenshot 2019-09-24 at 13 57 59" src="https://user-images.githubusercontent.com/4939519/65509716-5c543900-ded3-11e9-8fab-c13fac358222.png">
<img width="1433" alt="Screenshot 2019-09-24 at 13 57 41" src="https://user-images.githubusercontent.com/4939519/65509725-5fe7c000-ded3-11e9-863d-c774f1e6f9ee.png">

```
middleware "redacted-namespace-redacted-ssl@kubernetescrd" does not exist
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redacted-ssl
  namespace: redacted-namespace
spec:
  customRequestHeaders:
    X-Forwarded-Proto: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-redacted-develop-integration
  namespace: redacted-namespace
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`redacted.tld`)
      priority: 12
      services:
        - name: svc-redacted-develop-integration
          port: 80
      middlewares:
        - name: redacted-ssl
  tls:
    certResolver: default
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-24T11:38:13Z" level=error msg="middleware \"redacted-namespace-redacted-ssl@kubernetescrd\" does not exist" routerName=redacted-route-redacted-develop-integration-85b69a118e55214f6fe4@kubernetescrd entryPointName=https
```

```
$ kubectl --namespace=redacted-namespace describe middleware.traefik.containo.us/redacted-ssl
Name:         redacted-ssl
Namespace:   redacted-namespace
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"traefik.containo.us/v1alpha1","kind":"Middleware","metadata":{"annotations":{},"name":"redacted-ssl","namespace":"redacted-namespace"}...
API Version:  traefik.containo.us/v1alpha1
Kind:         Middleware
Metadata:
  Creation Timestamp:  2019-09-24T11:20:22Z
  Generation:          1
  Resource Version:    692431270
  Self Link:           /apis/traefik.containo.us/v1alpha1/namespaces/redacted-namespace/middlewares/redacted-ssl
  UID:                 446d3a6c-af6f-4948-86fb-09cb84daff7c
Spec:
  Custom Request Headers:
    X - Forwarded - Proto:  https
Events:                     <none>

$ kubectl --namespace=redacted-namespace describe ingressroutes.traefik.containo.us/route-redacted-develop-integration
Name:         route-redacted-develop-integration
Namespace:    redacted-namespace
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"traefik.containo.us/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"route-redacted-develop-integr...
API Version:  traefik.containo.us/v1alpha1
Kind:         IngressRoute
Metadata:
  Creation Timestamp:  2019-09-24T09:38:15Z
  Generation:          3
  Resource Version:    692420980
  Self Link:           /apis/traefik.containo.us/v1alpha1/namespaces/redacted-namespace/ingressroutes/route-redacted-develop-integration
  UID:                 6a2c1248-31a3-4c73-a2f9-ab7566db8aee
Spec:
  Entry Points:
    https
  Routes:
    Kind:   Rule
    Match:  Host(`redacted.tld`)
    Middlewares:
      Name:    redacted-ssl
    Priority:  12
    Services:
      Name:  svc-redacted-develop-integration
      Port:  80
  Tls:
    Cert Resolver:  default
Events:             <none>
```

---

## Update

Funny enough, if I set the service's middleware to something inexistent (such as `redacted-ssl@kubernetescrd`) the previous `redacted-namespace-redacted-ssl@kubernetescrd` reappers as "valid" in the list of middlewares:
<img width="1441" alt="Screenshot 2019-09-24 at 14 03 04" src="https://user-images.githubusercontent.com/4939519/65510045-31b6b000-ded4-11e9-8f39-bda92313c117.png">

and obiovusly Traefik complains about the fact that the middleware for the specified service is missing:
```
time="2019-09-24T12:04:21Z" level=error msg="middleware \"redacted-ssl@kubernetescrd\" does not exist" entryPointName=https routerName=redacted-namespace-route-redacted-develop-integration-85b69a118e55214f6fe4@kubernetescrd
```
<img width="1433" alt="Screenshot 2019-09-24 at 14 07 16" src="https://user-images.githubusercontent.com/4939519/65510198-a7bb1700-ded4-11e9-9bba-9523b472e5ad.png">

... and the middleware appears as not configured:
<img width="482" alt="Screenshot 2019-09-24 at 14 07 51" src="https://user-images.githubusercontent.com/4939519/65510219-bc97aa80-ded4-11e9-91bb-1ea7849a47b7.png">

**Comment by dtomcej** [comment]
Hello @denysvitali,

Your middleware:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redacted-ssl
  namespace: redacted-namespace
spec:
  customRequestHeaders:
    X-Forwarded-Proto: https
```

Does not have a type in the spec. From the documentation(https://docs.traefik.io/middlewares/headers/#adding-headers-to-the-request-and-the-response)

Can you try:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: testHeader
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
```

It shows that there is no "type" for your defined middleware. This can cause cascading issues leading to what you are seeing.
