### ISSUE TITLE
Cannot remove X-Forwarded-For

### ISSUE THREAD

**Issue by denysvitali** [containous/traefik#5482]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

Given the following service and middleware, Traefik automatically adds some headers that cannot be removed as seen on the [documentation](https://docs.traefik.io/middlewares/headers/#adding-and-removing-headers).

I need to remove the `X-Forwarded-For`, `X-Forwarded-Host` and `X-Forwarded-Proto` to mimic NGINX's behavior. Unfortunately the X-Forwarded-For header cannot be removed.

The configuration I'm using should do the following:

### What did you expect to see?

```
dvitali@ded1:nginx/sites-enabled $ nc -l 0.0.0.0 8078
GET /v2/ HTTP/1.0
Host: 127.0.0.1:8078
Connection: close
User-Agent: docker/18.09.9 go/go1.11.13 git-commit/039a7df9ba kernel/4.14.141-boot2docker os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.2 \(darwin\))
Accept-Encoding: gzip
```

### What did you see instead?

Instead, `X-Forwarded-For` is kept:
```
dvitali@ded1:nginx/sites-enabled $ nc -l 0.0.0.0 8078
GET /v2/ HTTP/1.1
Host: registry.ded1.denv.it:8078
User-Agent: docker/18.09.9 go/go1.11.13 git-commit/039a7df9ba kernel/4.14.141-boot2docker os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.2 \(darwin\))
Accept-Encoding: gzip
X-Forwarded-For: 10.2.0.0
X-Test-Traefik: hello
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[http.routers]
[http.routers.registry]
    rule = "Host(`registry.company.tld`)"
    service = "registry"
    middlewares = ["ovh-registry"]
    entrypoints = ["https"]
    [http.routers.registry.tls]
      certResolver = "default"

[http.services]
[http.services.registry.LoadBalancer]
    [[http.services.registry.LoadBalancer.servers]]
      url = "http://registry.ded1.denv.it:8078"

[http.middlewares]
[http.middlewares.ovh-registry.headers]
    [http.middlewares.ovh-registry.headers.customRequestHeaders]
      X-Forwarded-For = ""
      X-Forwarded-Port = ""
      X-Forwarded-Host = ""
      X-Forwarded-Server = ""
      X-Forwarded-Proto = ""
      X-Real-Ip = ""
      X-Test-Traefik = "hello"
```

### Probably related to
#4846, #2619, #4099
