### ISSUE TITLE
traefik dies with exit code 2 when updated by watchtower on armhf

### ISSUE THREAD

**Issue by ginkel** [containous/traefik#5484]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I have deployed traefik on two Raspberry Pi devices along with containrrr/watchtower to get automatic updates. traefik is deployed as `traefik:1.7`, i.e., pinned to the 1.7 tag.

### What did you expect to see?

When watchtower updates and starts the new traefik container, traefik comes up and resumes operation.

### What did you see instead?

the traefik Docker container terminates with exit code 2 without logging any output:

```
$ docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                    PORTS                                                                                       NAMES
640c468cfa38        traefik:1.7                                 "/traefik"               20 hours ago        Exited (2) 20 hours ago                                                                                               traefik

$ docker logs traefik
<empty output>
```

`docker inspect` shows nothing unusual with the container:

```
[
    {
        "Id": "640c468cfa38af65ca752d33cdce0a9eaf8eccb0c4508d9695faec81c1270d00",
        "Created": "2019-09-24T00:14:40.673361492Z",
        "Path": "/traefik",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 2,
            "Error": "",
            "StartedAt": "2019-09-24T00:15:02.507296839Z",
            "FinishedAt": "2019-09-24T00:15:03.947876736Z"
        },
        "Image": "sha256:ec767e99332989aa141fc289fe407da80dec13e39e0588e9028f7959b07c4a61",
[...]
```

Manually starting the docker container using `docker start` succeeds:

```
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                                                                                       NAMES
640c468cfa38        traefik:1.7                                 "/traefik"               20 hours ago        Up 14 seconds       xx.xxx.x.x:80-81->80-81/tcp, xx.xxx.x.x:443->443/tcp                                        traefik
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker exec -it traefik /traefik version
Version:      v1.7.17
Codename:     maroilles
Go version:   go1.12.9
Built:        2019-09-23_06:22:08PM
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
debug = false
insecureSkipVerify = true

[entryPoints]
  [entryPoints.traefik]
  address = ":81"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [ "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA" ]

[api]
[api.statistics]
recentErrors = 10

[rest]
entryPoint = "traefik"

[metrics]
[metrics.prometheus]

[docker]
exposedbydefault = false
watch = true

[file]
directory = "/etc/traefik/rules/"
watch = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Not available ATM.
