### ISSUE TITLE
Health status not correct in api

### ISSUE THREAD

**Issue by hobbypunk90** [containous/traefik#5503]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

for my development i have a to "host system" redirecting file config:
```toml
[http]
  [http.routers]
    [http.routers.app]
      entryPoints = ["web_secure"]
      service = "app"
      rule = "PathPrefix(`/`)"
      [http.routers.app.tls]
  [http.services]
    [http.services.app]
    [http.services.app.loadBalancer.healthCheck]
      path = "/health"
      timeout = "2s"
    [[http.services.app.loadBalancer.servers]]
      url = "http://172.17.0.1:3000"
```
it works.
but when my dev environment on my host system is not running, the traefik's log says the server is down:
`Health check failed: Remove from server list. Backend: \"app@file\" URL: \"http://172.17.0.1:3000\" Weight: 1 Reason: HTTP request failed: Get http://172.17.0.1:3000/health: dial tcp 172.17.0.1:3000: connect: connection refused"
`
as expected.
But the api under `/api/services/app@file` says:
`{"loadBalancer":{"servers":[{"url":"http://172.17.0.1:3000"}],"healthCheck":{"path":"/health","timeout":"2s"},"passHostHeader":false},"status":"enabled","usedBy":["app@file"],"serverStatus":{"http://172.17.0.1:3000":"UP"},"name":"app@file","provider":"file","type":"loadbalancer"}`

i think the server status has to be something like "DOWN"?

### What did you expect to see?

`"serverStatus":{"http://172.17.0.1:3000":"DOWN"}`

### What did you see instead?

`"serverStatus":{"http://172.17.0.1:3000":"UP"}`

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# Static
[log]
  level = "DEBUG"

[entryPoints.web]
  address = ":8080"
[entryPoints.web_secure]
  address = ":8443"
[entryPoints.traefik]
  address = ":8081"
[entryPoints.ping]
  address = ":8082"
[entryPoints.postgres]
  address = ":5432"

[providers]
  [providers.file]
    directory = "/rules"
    watch = true
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

[api]

[ping]
  entryPoint = "ping"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/localhost.cert"
      keyFile = "/certs/localhost.key"
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
    ]

# Dynamic
[http]
  [http.routers]
    [http.routers.app]
      entryPoints = ["web_secure"]
      service = "app"
      rule = "PathPrefix(`/`)"
      [http.routers.app.tls]
  [http.services]
    [http.services.app]
    [http.services.app.loadBalancer.healthCheck]
      path = "/health"
      timeout = "2s"
    [[http.services.app.loadBalancer.servers]]
      url = "http://172.17.0.1:3000"
```
