### ISSUE TITLE
Unable to obtain ACME certificate for domains: cannot get ACME client get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get https://acme-staging-v02.api.letsencrypt.org/directory: dial tcp 172.65.46.172:443: i/o timeout

### ISSUE THREAD

**Issue by kdankert** [containous/traefik#5509]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I was trying to secure my https endpoints using letsencrypt. I followed the docker tls challenge guide on docs.traefik.io. 

### What did you expect to see?

An valid ssl certificate when accessing my page

### What did you see instead?

Your connection is not private message dialog.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker
      - -log.level=DEBUG
      - --entrypoints.websecure.address=:443
      - --entrypoints.ssh.address=:2222
      - --certificatesresolvers.xerocscom_challenge.acme.tlschallenge=true
      - --certificatesresolvers.xerocscom_challenge.acme.email=admin@*domain*
      # Disable for production
      - --certificatesresolvers.xerocscom_challenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/letsencrypt:/letsencrypt

  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    healthcheck:
      disable: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.*domain*'
        registry_external_url 'https://registry.gitlab.*domain*'
        registry_nginx['listen_port'] = 5100
        registry_nginx['listen_https'] = false
        gitlab_rails['packages_enabled'] = true
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.office365.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = “*username*@*domain*"
        gitlab_rails['smtp_password'] = “*password*”
        gitlab_rails['smtp_domain'] = "*domain*"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'gitlab@*domain*'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@*domain*'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    labels:
      - traefik.enable=true
      - traefik.http.services.gitlab_xerocscom.loadbalancer.server.port=80
      - traefik.http.routers.gitlab.service=gitlab_xerocscom
      - traefik.http.routers.gitlab.rule=Host(`gitlab.*domain*`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls.certresolver=xerocscom_challenge
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`gitlab.domain.com`)
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc
      - traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=2222
      - traefik.http.services.registry-svc.loadbalancer.server.port=5100
      - traefik.http.routers.registry.service=registry-svc
      - traefik.http.routers.registry.rule=Host(`registry.gitlab.*domain*`)
      - traefik.http.routers.registry.entrypoints=websecure
      - traefik.http.routers.registry.tls.certresolver=xerocscom_challenge
    ports:
      - "2222:22"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-26T18:41:40Z" level=error msg="Unable to obtain ACME certificate for domains \"gitlab.*domain*\": cannot get ACME client get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get https://acme-staging-v02.api.letsencrypt.org/directory: dial tcp 172.65.46.172:443: i/o timeout" rule="Host(`gitlab.*domain*`)" providerName=xerocscom_challenge.acme routerName=gitlab
```
