### ISSUE TITLE
Windows Authentication always pops-up

### ISSUE THREAD

**Issue by aredz** [containous/traefik#5513]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I setup Traefik using fileprovider to connect to a DNS on an IIS Hosted site with different ports.

sample FILE PROVIDER ("uat"): similar to STAGING provider just add "-staging" after "uat"

```toml
[frontends]
  #uat
  [frontends.uat]
  backend = "uat"
    [frontends.uat.routes.host]
    rule = "Host:uat.com;"
  #api-uat.com
  [frontends.api-uat]
  backend = "api-uat"
    [frontends.api-uat.routes.host]
    rule = "Host:api-uat.com;"

[backends]
  #uat
  [backends.uat]
    [backends.uat.servers.server1]
    url = "http://testserver.workgroup.com:8001"
    weight = 10
  #api-uat
  [backends.api-uat]
    [backends.api-uat.servers.server1]
    url = "http://testserver.workgroup.com:8003"
    weight = 10
```
My Website = UAT.COM
My API = API-UAT.COM

My website has a "web.config" that points to the DNS = "https://API-UAT.COM"

### What did you expect to see?

I've no problem switching proxies, it's working as expected. However when I access the website

UAT.COM, I always get the PopUp to login Username/Password (Windows Auth dialog box)

I tried changing the WEB.CONFIG to a different API DNS that is not set from Traefik, only via IIS and it only asks the User/Pass first time and it that is saved into the session.

### What did you see instead?
![image](https://user-images.githubusercontent.com/26209579/65743866-c1a96380-e139-11e9-8c36-1fbf4417c855.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.12
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by dduportal** [comment]
Hi @aredz , we are missing informations to understand what is going on in this issue.

Could you elaborate and give us elements to reproduce (how do you run traefik, with which options, provide debug log, also provide a sample of the "IIS" backend server), beause we cannot have reproduce the behavior described here.

Thanks a lot!

**Comment by aredz** [comment]
Hi @dduportal ,

I have traefik.toml below:

```
checkNewVersion = false
insecureSkipVerify = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "certs/wildcard_test_com_chain.crt"
      keyFile = "certs/wildcard_test_com.key"
      [entryPoints.https.tls.defaultCertificate]
      certFile = "certs/wildcard_test_com_chain.crt"
      keyFile = "certs/wildcard_test_com.key"

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets=[0.1,0.3,1.2,5.0]
```

docker compose sample:

```
version: '3.7'
services:
    traefik:
      image: registrysample.azurecr.io/traefik:1.7.12-windows-nano-sac1809
      command: --api --docker --docker.endpoint=npipe:////./pipe/docker_engine --configfile=traefik.toml --api --file=true --file.directory=fileprovider --file.watch=true #--logLevel=DEBUG
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        #- .:C:/etc/traefik
        - type: npipe
          source: \\.\pipe\docker_engine
          target: \\.\pipe\docker_engine
      networks:
        - frontend
networks:
  frontend:
    external:
      name: nat

volumes:
  data-volume: 
```

we have 2 solutions. 1 Web and 1 API.

The Web (http://localhost:8001) connects to the api(http://localhost:8002) via config file.

In, Traefik. 

http://localhost:8001 points to front-end "https://uat.test.com"
http://localhost:8002 points to front-end "https://api.test.com"

sample "https://uat.test.com" has a web.config file configured to point to "https://api.test.com"

accessing externally:
when I access "https://uat.test.com" I get IWA (windows authentication) multiple times before the pop-up dialog closes. when I access a new page via link from the site, I get another windows authentication pop-up that needs multiple times your access. (looks like all server controls, needs authentication. input, dropdown, images,  etc.... )

changing the web.config and accessing via the same server:
modifying the web.config file to point to "http://localhost:8002" instead of the DNS. I tested locally by accessing, "http://localhost:8001". I get windows authentication the first time (once) and when I go on to other pages, I don't need to re-input my domain (workgroup) details.

I tried changing my toml to below, and still the issue persists.

```
[frontends]
  #uat.test
  [frontends.uat.test]
  backend = "uat.test"
    [frontends.uat.test.routes.host]
    rule = "Host:uat.test;"
  #api.test.com
  [frontends.api.test]
  backend = "api.test"
    [frontends.api.test.routes.host]
    rule = "Host:api.test.com;"

[backends]
  #uat.test
  [backends.uat.test]
	[backends.uat.test.loadBalancer]
	method = "drr"
	sticky = true
	[backends.uat.test.loadBalancer.stickiness]
	cookieName = "_uatCookie"
	#[backends.uat.test.healthcheck]
    #path = "/is-up"
    #interval = "5s"
    [backends.uat.test.servers.server1]
    url = "http://testserver:8001"
    weight = 10
  #api.test
  [backends.api.test]
	#[backends.api.test.healthcheck]
	#path = "/is-up"
	#interval = "5s"
    [backends.api.test.servers.server1]
    url = "http://testserver:8002"
    weight = 10

```

Does this make sense? any config that I can use to make this work?

btw I've originally setup method = "wrr" with loadbalancer stickiness removed and stickiness cookie not setup.

All I want to do is to not have multiple 401 (Authentication issue via Windows Authentication). I just need to be authorized once, and that should be it.

P.S. I don't have access to run or change the compose file to ON the debug feature. I just got the config from our repository. And I don't think I am allowed as well to swarm new containers to test. I'm just currently working on the current container for traefik that is running and just setting up the new sites via IIS and making sure both integrates properly.
