### ISSUE TITLE
Authorization issue with both [entryPoints.https.auth.basic] and Kubernetes ingress auth-type: "basic"

### ISSUE THREAD

**Issue by PierreBeucher** [containous/traefik#5515]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I deployed Traefik on Kubernetes and configured as follow:

In `traefik.toml`:
```
    [entryPoints.https.auth.basic]
        users = ["someuser:$xxx",]
```

Then created a **Secret** and **Ingress** such as:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: myingress
 annotations:
   kubernetes.io/ingress.class: traefik
   ingress.kubernetes.io/auth-type: "basic"
   ingress.kubernetes.io/auth-secret: "mysecret" # contain auth for anotheruser:password 
spec:
 ...
```

### What did you expect to see?

One of the authentication to take precedence (such as Ingress auth config to take precedence other Traefik endpoint auth config)

### What did you see instead?

None of the authentication config worked, I kept receiving `401 Unauthorized` responses whatever login/password pair I was using. No error shown in Traefik pod. 

When using one or the other (but not both), authentication works as expected.

Documentation does not seem to specify behavior when setting both king of auth config.

### What version of Traefik are you using?

```
traefik:1.7.12-alpine
```

Deployed on Kubernetes using Helm charts `1.70.2`
