### ISSUE TITLE
Sticky sessions don't work in Docker Swarm

### ISSUE THREAD

**Issue by aleksvujic** [containous/traefik#5518]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I am using  **Traefik v2**  with Docker Swarm. I want to achieve session stickiness. Below are my docker-compose files.

**docker-compose-traefik.yml**

```
version: "3.7"

services:
  traefik:
    image: "traefik:v2.0"
    networks:
      - traefik-net
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:5000"
    ports:
      - "80:80"
      - "9000:8080"
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik-net:
    external:
      name: traefik-net
```

**docker-compose-whoami.yml**

```
version: "3.7"

services:
  whoami:
    image: "jwilder/whoami"
    networks:
      - traefik-net
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`mydomain.com`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.services.whoami.loadbalancer.server.port=8000"
        - "traefik.http.services.whoami.loadbalancer.sticky=true"
        - "traefik.http.services.whoami.loadbalancer.sticky.cookie.name=StickyCookie"
        - "traefik.http.services.whoami.loadbalancer.sticky.cookie.secure=true"

networks:
  traefik-net:
    external:
      name: traefik-net
```

I created network  `traefik-net`  with:  `docker network create -d bridge traefik-net` .

I deployed both stacks with:

1. `docker-stack deploy -c docker-compose-traefik.yml Traefik`
2. `docker-stack deploy -c docker-compose-whoami.yml Whoami`

When I visit mydomain.com:5000 it always shows different container ID. I can see the cookie in Chrome developer tools:

![cookie](https://user-images.githubusercontent.com/17112542/65754849-38cb0180-e112-11e9-8a6d-2fc6bec07440.png)

### What did you expect to see?

I expected to see same container ID on every request because session stickiness is enabled.

### What did you see instead?

Container ID was different on every request.

### Output of `traefik version`:

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-27T08:40:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,sl;q=0.8,la;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _ga=GA1.2.1010817446.1569500864; _gid=GA1.2.631194296.1569500864\"],\"Pragma\":[\"no-cache\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mydomain.com:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"9f47a7fa5894\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mydomain.com:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:54530\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2019-09-27T08:40:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,sl;q=0.8,la;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _ga=GA1.2.1010817446.1569500864; _gid=GA1.2.631194296.1569500864\"],\"Pragma\":[\"no-cache\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mydomain.com:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"9f47a7fa5894\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mydomain.com:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:54530\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://10.0.2.69:8000"
time="2019-09-27T08:40:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,sl;q=0.8,la;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _ga=GA1.2.1010817446.1569500864; _gid=GA1.2.631194296.1569500864\"],\"Pragma\":[\"no-cache\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mydomain.com:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"9f47a7fa5894\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mydomain.com:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:54530\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2019-09-27T08:40:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,sl;q=0.8,la;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _ga=GA1.2.1010817446.1569500864; _gid=GA1.2.631194296.1569500864\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"http://mydomain.com:5000/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mydomain.com:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"9f47a7fa5894\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mydomain.com:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:54530\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
time="2019-09-27T08:40:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,sl;q=0.8,la;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _ga=GA1.2.1010817446.1569500864; _gid=GA1.2.631194296.1569500864\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"http://mydomain.com:5000/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mydomain.com:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"9f47a7fa5894\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mydomain.com:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:54530\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}" ForwardURL="http://10.0.2.68:8000"
time="2019-09-27T08:40:39Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,sl;q=0.8,la;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _ga=GA1.2.1010817446.1569500864; _gid=GA1.2.631194296.1569500864\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"http://mydomain.com:5000/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mydomain.com:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"9f47a7fa5894\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mydomain.com:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:54530\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
time="2019-09-27T08:40:42Z" level=debug msg="Filtering disabled container" providerName=docker container=Traefik-traefik-ot0rzpgo3eqkk91sqz6tdu9cs
time="2019-09-27T08:40:42Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"whoami\":{\"entryPoints\":[\"web\"],\"service\":\"whoami\",\"rule\":\"Host(`mydomain.com`)\"}},\"services\":{\"whoami\":{\"loadBalancer\":{\"sticky\":{\"cookie\":{\"name\":\"StickyCookie\",\"secure\":true}},\"servers\":[{\"url\":\"http://10.0.2.69:8000\"},{\"url\":\"http://10.0.2.68:8000\"},{\"url\":\"http://10.0.2.70:8000\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
time="2019-09-27T08:40:42Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
```
