### ISSUE TITLE
IP for docker host mode container not recognized

### ISSUE THREAD

**Issue by volschin** [containous/traefik#5535]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ X] No

### What did you do?
I tried the following configuration:
```yml
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    container_name: homebridge
    restart: always
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=host"
      - "traefik.http.routers.homebridge.rule=PathPrefix(`/`)"
      - "traefik.http.routers.homebridge.entrypoints=http"
      - "traefik.http.services.homebridge.loadbalancer.passhostheader=true"
      - "traefik.http.services.homebridge.loadbalancer.sticky=true"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8080"
    volumes:
      - ./config:/homebridge
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```

The Logs says
```
time="2019-09-28T13:24:31+02:00" level=error msg="unable to find the IP address for the container \"/homebridge\": the server is ignored" providerName=docker container=homebridge-fhem-docker-fcfce91ae50874dd86b47dde44eb694c2994d9772cbbf06fff242e057ead4fcb
```

It seems related to the changes made for #487

### What did you expect to see?

I had expected to have this service outputted on my traefik entrypoint http.

### What did you see instead?

instead the traefik admin interface appears.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.1
with docker image
sha256:b875f278d36351dba0c88ed49e3d24897cfe20e5d58370322dd0a536826fe4ca
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
# (paste your configuration here)
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 06:18:36 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 06:12:41 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```yml
  proxy:
    image: traefik:2.0
    restart: always
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "8081:8080"
    networks:
      - local
      - web
    volumes:
      - ./traefik2:/etc/traefik
      - ./traefik2/acme.json:/acme.json
      - /run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro


```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by dduportal** [comment]
Hi @volschin , thanks a lot for reporting!

As for today, this use case require to define your own service and router object with the File provider, as Docker is not providing any private IP associated to the container with the network `host` that canbe routed from Traefik container.

A common pattern to solve this is to point Traefik to the IP of the `docker0` bridge, which does not change a lot and is routable from any container. It assumes that your application "homebridge" listens on all the interfaces of the host, or at least on `docker0` if you don't want to expose it on public network.

Example of configuration extrapolated from your config:

* `traefik.yml` (you can still use the TOML form of course):

```yml
(... you current config ...)
providers:
  docker: (... you current config ...)
  file:
    filename: dynamic_conf.yml
```

* File `dynamic_conf.yml`, only for the "network=host" service (the other services stays with docker label configuration):

```yml
http:
  routers:
    homebridge:
      rule: "PathPrefix(`/`)"
      entrypoints:
        - http
      service: service-id
  services:
    homebridge-svc:
      loadBalancer:
        passhostheader: true
        sticky:
         cookie: {}
        servers:
          address: "http://172.17.0.1:8080"
```

*  `docker-compose.yml`:

```yaml
version: '3'

services:
  proxy:
    image: traefik:2.0
    restart: always
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "8081:8080"
    networks:
      - local
      - web
    volumes:
      - ./traefik2:/etc/traefik
      - ./traefik2/acme.json:/acme.json
      - /run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  homebridge:
    image: oznu/homebridge:raspberry-pi
    container_name: homebridge
    restart: always
    network_mode: host
    labels:
      - "traefik.enable=false"
    volumes:
      - ./config:/homebridge
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```
