### ISSUE TITLE
Multiple middlewares of the same type overwrite each other in unexpected ways

### ISSUE THREAD

**Issue by TheZenti** [containous/traefik#5538]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I tried to apply multiple Header middlewares to the same k8s IngressRoute, like so:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingresstest
spec:
  routes:
  - match: Host(`example.com`)
    kind: Rule
    middlewares:
    - name: frameoptionsameorigin
    - name: securityheaders
      namespace: traefik
    services:
    - name: somenginx
      port: 8888
  tls:
    ...
```
Middlewares:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frameoptionsameorigin
spec:
  headers:
    customFrameOptionsValue: SAMEORIGIN

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: securityheaders
  namespace: traefik
spec:
  headers:
    contentTypeNosniff: "true"
    sslRedirect: "true"
    stsIncludeSubdomains: "true"
    stsSeconds: "31536010"
    stsPreload: "true"
    browserXssFilter: "true"
```

### What did you expect to see?

I expected both header middlewares to be merged, so both HSTS headers as well as X-Frame-Options SAMEORIGIN would be sent to clients.

### What did you see instead?

Whatever is last in the middleware list completely overrides all possible headers from previous middlewares, even if I didn't specify them. In the above example, `customFrameOptionsValue: SAMEORIGIN` is not applied:

```
accept-ranges: bytes
content-length: 69
content-type: text/plain
date: Sat, 28 Sep 2019 18:17:43 GMT
etag: "5d8f979b-45"
last-modified: Sat, 28 Sep 2019 17:25:47 GMT
server: nginx
status: 200
strict-transport-security: max-age=31536010; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```
As you can see, `x-frame-options: SAMEORIGIN` is missing.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik is running in k8s as a Deployment with the kubernetescrd provider, on CoreOS stable.

```yaml
- name: traefik
  image: traefik:v2.0
  imagePullPolicy: Always
  args:
    - --api
    - --api.dashboard=true
    - --api.insecure=true
    - --entrypoints.http.Address=:80
    - --entrypoints.https.Address=:443
    - --metrics.prometheus=true
    - --providers.kubernetescrd
    - --certificatesresolvers.default.acme.tlsChallenge=true
    - --certificatesresolvers.default.acme.email=<retracted>
    - --certificatesResolvers.default.acme.httpChallenge.entryPoint=http
    - --certificatesresolvers.default.acme.storage=/acme.json
```
