### ISSUE TITLE
ForwardAuth middleware does not resolve K8s DNS names, requires IP instead

### ISSUE THREAD

**Issue by bigwheels16** [containous/traefik#5543]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I deployed simple `whoami` app, with a deployment, a service, and ingress route, all in `default` Kubernetes namespace:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami-container
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whoami-auth-middleware

spec:
  forwardAuth:
    address: http://traefik-forward-auth-service.default.svc.cluster.local/health
    trustForwardHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-route

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami.example.com`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: whoami-auth-middleware
      services:
        - name: whoami-service
          port: 80
  tls:
    secretName: example-com-tls-cert
```

### What did you expect to see?

When I access whoami.example.com I expected a successful 200 response.

### What did you see instead?

I got a 500 response.  However, if I replace the DNS name of the Service with the IP address of the Service, then it works as expected:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whoami-auth-middleware

spec:
  forwardAuth:
    #address: http://traefik-forward-auth-service.default.svc.cluster.local/health
    address: http://10.111.12.101/health
    trustForwardHeader: true
```

I am confident the address is correct because I connected to one of the containers and was able to get a 200 response with `wget http://traefik-forward-auth-service.default.svc.cluster.local/health`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No toml file.  Running on Kubernetes 1.16:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Traefik deployment along with the forward auth app:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-ingress-route

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.example.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: traefik-dashboard-service
          port: 8080
  tls:
    secretName: example-com-tls-cert
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      hostNetwork: true
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.web.forwardedheaders.insecure=true
            - --entrypoints.websecure.forwardedheaders.insecure=true
            - --providers.kubernetescrd
            - --ping
            - --accesslog=true
            - --log=true
            - --log.level=DEBUG
            - --global.sendAnonymousUsage
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth-deployment
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
        - name: traefik-forward-auth-container
          image: docker.example.com/traefik-forward-auth:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth-service
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: traefik-forward-auth
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

When I set the Log level to debug, it appears to ONLY print DEBUG-level log statements (and not INFO-level log statements).  Maybe that is another bug?  In any case, it had quite a lot of output as it looked like it was checking the Kubernetes configuration every 2s, and it didn't seem to have anything that was related to this.  But if you need the logs I can get them for you.
