### ISSUE TITLE
Dashboard resources not loaded when using path prefix

### ISSUE THREAD

**Issue by leon-andria** [containous/traefik#5545]
In 1.7, we use path prefix (/traefik) to access the dashboard and it works pretty nice.

When we experimenting the migration to vesion 2.0.1 with Ingress Route:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboardingressroute

spec:
  entryPoints:
    - web
  routes:
  - match: Host(`localhost`) && PathPrefix(`/traefik`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
    middlewares:
      - name: test-stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /traefik

```

We can reach the dabshboard web site but all resources are not loaded properly due to URL issue. It tries to load with /dashboard/....

As it's a SPA, we guess that the baseref on the page is missing or using kind of header X-Forward-Prefix ?
