### ISSUE TITLE
Traefik 2.0 not discovering host information for services

### ISSUE THREAD

**Issue by bubthegreat** [containous/traefik#5546]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Used docker-compose to define services via labels, expecting it to route - on windows 10 with docker for windows running in swarm mode.


### What did you expect to see?
I expected to be able to navigate to app.localhost and get to my angular application serving on port 4200, or my api serving on port 8000.  I'm hoping this is just a lack of understanding configurations rather than a bug, but I thought I went through the documentation examples well enough that it was worth opening, since I'm not seeing other windows specific examples.  I assume they might be different, because windows.


### What did you see instead?

Neither were reachable, however if I accessed the port directly (localhost:4200) it routed to the correct services - just not via host name like app.localhost

Logs showed that traefik isn't picking up the configuration, but I *thought* I followed the steps in the docs. 

compose file:

```yml
version: '3'

services:
    api:
        hostname: api-crypto
        image: api-crypto
        build:
            context: ./api-crypto
            dockerfile: Dockerfile
        labels:
            - "traefik.http.routers.api.rule=Host(`api.localhost`)"
            - "traefik.http.routers.api.entrypoints=api"
        env_file:
            - .env
        ports:
            - 8000
        volumes:
            - ./data:/crypto_data
        networks:
            - traefik-pub

    app:
        hostname: app-crypto
        image: app-crypto
        build:
            context: ./app-crypto
            dockerfile: Dockerfile
        deploy:
            labels:
                - traefik.http.routers.app.rule=Host(`app.localhost`)
                - traefik.http.services.app.loadbalancer.server.port=4200
        depends_on:
            - api
        command: ng serve --host 0.0.0.0 --disable-host-check --public-host app.localhost
        ports:
            - 4200
        networks:
            - traefik-pub

    traefik:
        image: "traefik:v2.0.0-rc3"
        container_name: "traefik"
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--entrypoints.app.address=:4200"
            - "--entrypoints.api.address=:8000"
            - --providers.docker.swarmMode=true
        ports:
            # HTTP
            - "80:80"
            # HTTPS
            - "443:443"
            # Web UI
            - "8080:8080"
        networks:
            - traefik-pub
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    traefik-pub:
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.0-rc3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No toml file being used.
```toml
# (paste your configuration here)
```


### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
PS C:\Users\bubth\Development\crypto_logger> docker-compose up                                                                                                                                                                                                                             WARNING: Some services (app) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting crypto_logger_api_1 ... done                                                                                                                                                                                                                                                      Starting
traefik             ... done                                                                                                                                                                                                                                                      Starting crypto_logger_app_1 ... done                                                                                                                                                                                                                                                      Attaching to
traefik, crypto_logger_api_1, crypto_logger_app_1
traefik    | time="2019-09-29T21:49:32Z" level=info msg="Configuration loaded from flags."
traefik    | time="2019-09-29T21:49:32Z" level=info msg="Traefik version 2.0.0-rc3 built on 2019-09-10T17:10:04Z"
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"api\":{\"address\":\":8000\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"app\":{\"address\":\":4200\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"exposedByDefault\":true,\"swarmMode\":true,\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
traefik    | time="2019-09-29T21:49:32Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
traefik    | time="2019-09-29T21:49:32Z" level=info msg="\nStats collection is enabled.\nMany thanks for contributing to traefik's improvement by allowing us to receive anonymous information from your configuration.\nHelp us improve traefik by leaving this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="No default certificate, generating one"
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="Start TCP Server" entryPointName=api
traefik    | time="2019-09-29T21:49:32Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
api_1      | INFO: Started server process [6]
api_1      | INFO: Waiting for application startup.
api_1      | 2019-09-29 21:49:33,041 - crypto_logger.app - INFO - Starting the periodic task.
api_1      | INFO: Starting the periodic task.
api_1      | 2019-09-29 21:49:33,041 - crypto_logger.getters - INFO - Trying to get coin data.
api_1      | INFO: Trying to get coin data.
api_1      | INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="Start TCP Server" entryPointName=traefik
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="Start TCP Server" entryPointName=app
traefik    | time="2019-09-29T21:49:32Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"exposedByDefault\":true,\"swarmMode\":true,\"swarmModeRefreshSeconds\":15000000000}"
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="Provider connection established with docker 19.03.1 (API 1.40)" providerName=docker
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="Configuration received from provider docker: {\"http\":{},\"tcp\":{}}" providerName=docker
traefik    | time="2019-09-29T21:49:32Z" level=debug msg="No default certificate, generating one"
app_1      | WARNING: This is a simple server for use in testing or debugging Angular applications
app_1      | locally. It hasn't been reviewed for security issues.
app_1      |
app_1      | Binding this server to an open connection can result in compromising your application or
app_1      | computer. Using a different host than the one passed to the "--host" flag might result in
app_1      | websocket connection issues. You might need to use "--disableHostCheck" if that's the
app_1      | case.
app_1      | WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
api_1      | 2019-09-29 21:49:37,173 - crypto_logger.getters - INFO - Got coin data - attempting to record coin data.
api_1      | INFO: Got coin data - attempting to record coin data.
api_1      | 2019-09-29 21:49:39,032 - crypto_logger.getters - INFO - Recorded coin data.
api_1      | INFO: Recorded coin data.
api_1      | 2019-09-29 21:49:39,032 - crypto_logger.app - INFO - Waiting 600 seconds to get more data.
api_1      | INFO: Waiting 600 seconds to get more data.
traefik    | time="2019-09-29T21:49:47Z" level=debug msg="Configuration received from provider docker: {\"http\":{},\"tcp\":{}}" providerName=docker
traefik    | time="2019-09-29T21:49:47Z" level=info msg="Skipping same configuration for provider docker" providerName=docker
app_1      |
app_1      | Date: 2019-09-29T21:49:48.768Z
app_1      | Hash: 277f1645eacb4119c589
app_1      | Time: 13394ms
app_1      | chunk {main} main.js, main.js.map (main) 55.1 kB [initial] [rendered]
app_1      | chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 248 kB [initial] [rendered]
app_1      | chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
app_1      | chunk {styles} styles.js, styles.js.map (styles) 181 kB [initial] [rendered]
app_1      | chunk {vendor} vendor.js, vendor.js.map (vendor) 6.04 MB [initial] [rendered]
app_1      | ** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
app_1      | ℹ ｢wdm｣: Compiled successfully.
traefik    | time="2019-09-29T21:50:02Z" level=debug msg="Configuration received from provider docker: {\"http\":{},\"tcp\":{}}" providerName=docker
traefik    | time="2019-09-29T21:50:02Z" level=info msg="Skipping same configuration for provider docker" providerName=docker                                                                                                                                                              Gracefully stopping... (press Ctrl+C again to force)
Stopping crypto_logger_app_1 ...
Stopping crypto_logger_api_1 ...
Stopping
traefik             ... done                                                                                                                                                                                                                                                      Killing crypto_logger_app_1  ... done                                                                                                                                                                                                                                                      Killing crypto_logger_api_1  ... done                                                                                                                                                                                                                                                      PS C:\Users\bubth\Development\crypto_logger>
```
