### ISSUE TITLE
RedirectRegex ignores substituion ( and does a direct replacement)

### ISSUE THREAD

**Issue by ZetaPhoenix** [containous/traefik#5547]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Used a redirectRegex to add trailing slash before stripping it off.

Test URL: `http://testurl.com/notrailingslash`

Regex:
```yaml
http:
  middlewares:
    strip-prefix:
      chain:
        middlewares:
        - strip-prefix-1
        - strip-prefix-2

    strip-prefix-1:
      redirectRegex:
        regex: "^(https?://[^/]+/[a-z0-9_]+)$"
        replacement: "${1}/"
        permanent: true

    strip-prefix-2:
      stripPrefixRegex:
        regex:
          - "/[a-z0-9]+"
```

If I go to `http://testurl.com/notrailingslash/` and skip `strip-prefix-1`, then the intended service is routed correctly.

### What did you expect to see?

https://regex101.com/r/58sIgx/126

`http://testurl.com/notrailingslash/`

### What did you see instead?

`http://testurl.com/${1}/`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:25:50Z
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true

log:
# DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
  level: DEBUG

entryPoints:
  web:
    address: ':80'
  web-secure:
    address: ':443'

certificatesResolvers:
  letsencrypt:
    acme:
      email: ****.com
      storage: acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      dnsChallenge:
        provider: duckdns
        delayBeforeCheck: 0

providers:
  file:
    filename: dynamic_conf.yml
    watch: true
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedbydefault: false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
no logs were found related to this
```
