### ISSUE TITLE
tls.options is not applied if not named "default"

### ISSUE THREAD

**Issue by bgranvea** [containous/traefik#5553]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I'm trying to setup a route with mTLS and clientAuthType=RequireAndVerifyClientCert with Docker provider.

### What did you expect to see?
Only requests with valid client certificate should be processed.

### What did you see instead?
All requests are processed.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
api:
  insecure: true
log:
  level: DEBUG
providers:
  docker:
    swarmMode: true
    exposedByDefault: false
    network: beekeeper_common
  file:
    filename: /etc/traefik/dynamic.yml
entryPoints:
  https:
    address: :443
  https-clientcert:
    address: :1443
```

/etc/traefik/dynamic.yml:
```yaml
tls:
  options:
    client-cert:
      clientAuth:
        clientAuthType: RequireAndVerifyClientCert
        caFiles:
          - /etc/traefik/client-ca.crt
```

docker-compose.yml:
```yaml
version: "3.5"

services:
...
  beekeeper:
    ...
    deploy:
      ...
      labels:
        - traefik.enable=true
        - traefik.http.routers.beekeeper-https-clientcert.rule=Host(`myhost.iv.local`) && PathPrefix(`/beekeeper`)
        - traefik.http.routers.beekeeper-https-clientcert.entryPoints=https-clientcert
        - traefik.http.routers.beekeeper-https-clientcert.tls=true
        - traefik.http.routers.beekeeper-https-clientcert.tls.options=client-cert@file
        - traefik.http.routers.beekeeper-https-clientcert.middlewares=beekeeper-strip
        - traefik.http.routers.beekeeper-https-clientcert.service=beekeeper-https-clientcert
        - traefik.http.services.beekeeper-https-clientcert.loadbalancer.server.port=8181
        - traefik.http.middlewares.beekeeper-strip.stripprefix.prefixes=/beekeeper
```

Test:
`[root@bg-test1 ~]# curl -k -v -H "Host: myhost.iv.local" https://bg-test1:1443/beekeeper/
` 
=> response 200

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-09-30T13:09:13Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2019-09-30T13:09:13Z" level=info msg="Traefik version 2.0.1 built on 2019-09-26T16:18:03Z"
time="2019-09-30T13:09:13Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"https-clientcert\":{\"address\":\":1443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmMode\":true,\"network\":\"beekeeper_common\",\"swarmModeRefreshSeconds\":15000000000},\"file\":{\"watch\":true,\"filename\":\"/etc/traefik/dynamic.yml\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2019-09-30T13:09:13Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2019-09-30T13:09:13Z" level=debug msg="No default certificate, generating one"
time="2019-09-30T13:09:13Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-09-30T13:09:13Z" level=debug msg="Start TCP Server" entryPointName=https
time="2019-09-30T13:09:13Z" level=debug msg="Start TCP Server" entryPointName=https-clientcert
time="2019-09-30T13:09:13Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-09-30T13:09:13Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/etc/traefik/dynamic.yml\"}"
time="2019-09-30T13:09:13Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmMode\":true,\"network\":\"beekeeper_common\",\"swarmModeRefreshSeconds\":15000000000}"
time="2019-09-30T13:09:13Z" level=debug msg="Configuration received from provider file: {\"http\":{\"middlewares\":{\"admin-auth\":{\"basicAuth\":{\"users\":[\"xxxxxxxxxxxxxxx\"],\"removeHeader\":true}}}},\"tcp\":{},\"tls\":{\"options\":{\"client-cert\":{\"clientAuth\":{\"caFiles\":[\"/etc/traefik/client-ca.crt\"],\"clientAuthType\":\"RequireAndVerifyClientCert\"}}}}}" providerName=file
time="2019-09-30T13:09:13Z" level=debug msg="No default certificate, generating one"
time="2019-09-30T13:09:14Z" level=debug msg="Provider connection established with docker 19.03.2 (API 1.40)" providerName=docker
time="2019-09-30T13:09:14Z" level=debug msg="Filtering disabled container" providerName=docker container=management-traefik-2vgmpwggd2pvb883022sfgn74
time="2019-09-30T13:09:14Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"beekeeper-https-clientcert\":{\"entryPoints\":[\"https-clientcert\"],\"middlewares\":[\"beekeeper-strip\"],\"service\":\"beekeeper-https-clientcert\",\"rule\":\"Host(`myhost.iv.local`) \\u0026\\u0026 PathPrefix(`/beekeeper`)\",\"tls\":{\"options\":\"client-cert@file\"}}},\"middlewares\":{\"beekeeper-strip\":{\"stripPrefix\":{\"prefixes\":[\"/beekeeper\"]}}},\"services\":{\"beekeeper-https-clientcert\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://10.0.0.7:8181\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
time="2019-09-30T13:09:14Z" level=debug msg="Creating middleware" entryPointName=https-clientcert routerName=beekeeper-https-clientcert@docker serviceName=beekeeper-https-clientcert middlewareName=pipelining middlewareType=Pipelining
time="2019-09-30T13:09:14Z" level=debug msg="Creating load-balancer" entryPointName=https-clientcert routerName=beekeeper-https-clientcert@docker serviceName=beekeeper-https-clientcert
time="2019-09-30T13:09:14Z" level=debug msg="Creating server 0 http://10.0.0.7:8181" entryPointName=https-clientcert routerName=beekeeper-https-clientcert@docker serviceName=beekeeper-https-clientcert serverName=0
time="2019-09-30T13:09:14Z" level=debug msg="Added outgoing tracing middleware beekeeper-https-clientcert" middlewareType=TracingForwarder entryPointName=https-clientcert routerName=beekeeper-https-clientcert@docker middlewareName=tracing
time="2019-09-30T13:09:14Z" level=debug msg="Creating middleware" entryPointName=https-clientcert routerName=beekeeper-https-clientcert@docker middlewareName=beekeeper-strip@docker middlewareType=StripPrefix
time="2019-09-30T13:09:14Z" level=debug msg="Adding tracing to middleware" entryPointName=https-clientcert middlewareName=beekeeper-strip@docker routerName=beekeeper-https-clientcert@docker
time="2019-09-30T13:09:14Z" level=debug msg="Creating middleware" entryPointName=https-clientcert middlewareType=Recovery middlewareName=traefik-internal-recovery
time="2019-09-30T13:09:14Z" level=debug msg="No default certificate, generating one"
time="2019-09-30T13:09:14Z" level=debug msg="Adding route for myhost.iv.local with TLS options client-cert@file" entryPointName=https-clientcert
```

If I use "default" instead of "client-cert" as TLS options, it seems to work. The problem is that I would like to setup another HTTPS route without certificate authentication, so I cannot change the default configuration.

**Comment by jbdoumenjou** [comment]
hi @bgranvea,

To select the correct TLS options, Traefik uses HostSNI, but setting the host in the header with CURL does not set HostSNI.
* In the first step, Traefik can not find corresponding TLS options and therefore applied the default one.
* Next, it will check the host to apply HTTP routing and then route to your server.

So, you have to use a mechanism that applies HostSNI to check if the configuration works. In addition, a stricter default configuration is a good practice.

If that answers your question, I will close this issue accordingly.

**Comment by dduportal** [comment]
If it helps, you can find how to set the HostSNI with `curl` in the current article: https://hacksbrain.com/2018/08/27/testing-sni-enabled-servers-with-curl/.

**Comment by bgranvea** [comment]
thank you for your help, it works now if I set the HostSNI with curl and --resolve.

there is another problem though. I'm trying to achieve this:

- entrypoint port 443, HTTPS, no client certificate, basic authentication (for GUI)
- entrypoint port 1443, HTTPS, valid client certificate required (for API calls coming from other applications)

I tried this, but it doesn't seem to work:

```
      tls:
        options:
          # TLS configuration for entrypoint :443
          no-client-cert:
            clientAuth:
              clientAuthType: NoClientCert
          # TLS configuration for entrypoint :1443 which requires a client certificate
          default:
            clientAuth:
              clientAuthType: RequireAndVerifyClientCert
              caFiles:
                - /etc/traefik/client-ca.crt
```

```
     labels:
        - traefik.enable=true
        # https entrypoint
        - traefik.http.routers.beekeeper-https.rule=PathPrefix(`/beekeeper`)
        - traefik.http.routers.beekeeper-https.entryPoints=https
        - traefik.http.routers.beekeeper-https.tls=true
        - traefik.http.routers.beekeeper-https.tls.options=no-client-cert@file
        - traefik.http.routers.beekeeper-https.middlewares=admin-auth@file,beekeeper-strip
        - traefik.http.routers.beekeeper-https.service=beekeeper-https
        - traefik.http.services.beekeeper-https.loadbalancer.server.port=8181
        # https-clientcert entrypoint
        - traefik.http.routers.beekeeper-https-clientcert.rule=Host(`myhost.iv.local`) && PathPrefix(`/beekeeper`)
        - traefik.http.routers.beekeeper-https-clientcert.entryPoints=https-clientcert
        - traefik.http.routers.beekeeper-https-clientcert.tls=true
        - traefik.http.routers.beekeeper-https-clientcert.tls.options=default
        - traefik.http.routers.beekeeper-https-clientcert.middlewares=beekeeper-strip
        - traefik.http.routers.beekeeper-https-clientcert.service=beekeeper-https-clientcert
        - traefik.http.services.beekeeper-https-clientcert.loadbalancer.server.port=8181
        # middlewares
        - traefik.http.middlewares.beekeeper-strip.stripprefix.prefixes=/beekeeper
```

With this configuration, a request on port 443 gives me a "client certificate not found" on client side.
