### ISSUE TITLE
You can't control the order middleware applies  

### ISSUE THREAD

**Issue by danassetms** [containous/traefik#5554]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x ] No

### What did you do?

Running with multiple middleware commands you would expect them to apply in-order but they don't

### What did you expect to see?

We are using the middleware to fix headers, redirect to https, handle custom errors and handle custom 404.

For the catchall router above when we access Traefik using a host domain that belongs to us but is not specifically configured we want to show the  maintenance service.  One of the steps in the middlewares is to remove the x-powered-by: ASP.NET header.

### What did you see instead?
When we access a url that is resolved to the 404 middleware we still see the x-powered-by: ASP.NET header present and the other headers we're adding are also not present.  It looks like the order that the middlewares are applied are not the order they appear in our toml definition

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2.0.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[log]
  level = "ERROR"

[api]

[metrics]
  [metrics.prometheus]
	addEntryPointsLabels = true
	addServicesLabels = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
	
  [entryPoints.secure-web]
    address = ":443"



[providers]

  [providers.file]
    directory = "/etc/traefik/config/"
    watch = "true"

```

```toml
[file]

[http.middlewares]
	[http.middlewares.AzureHeaders.headers]
		[http.middlewares.AzureHeaders.headers.customResponseHeaders]
			X-AMS-Environment = "Azure"
			X-AMS-Gateway = "v2.0.1"
			x-aspnet-version = "" # Removes
			x-powered-by = ""
			server = ""
	[http.middlewares.redirecthttps.redirectScheme]
		scheme = "https"
	[http.middlewares.amserrors.errors]
		status = ["500-599"]
		service = "maintenance"
		query = "/error.htm"	
	[http.middlewares.ams404.errors]	
		status = ["404"]
		service = "maintenance"
		query = "/404.htm"
```

```toml
[file]

[http]
  [http.routers]		
	[http.routers.catchall]
		middlewares = ["AzureHeaders", "redirecthttps", "amserrors", "ams404"]
		entryPoints = ["secure-web", "web"]
		service = "maintenance"
		rule = "HostRegexp(`{subdomain:[a-z]+}.mydomain.com`)" 
	[http.routers.catchall.tls]
		certResolver = "myssl"


    # Add the service
    [http.services]
      [http.services.maintenance]
        [http.services.maintenance.loadBalancer]
          [[http.services.maintenance.loadBalancer.servers]]
            url = "http://server1"
          [[http.services.maintenance.loadBalancer.servers]]
            url = "http://server2"
		[http.services.maintenance.loadBalancer.healthCheck]
			path = "/health/index.html"
			interval = "10s"
			timeout = "3s"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
