### ISSUE TITLE
Allow Docker dynamic configuration for container with host or custom networks

### ISSUE THREAD

**Issue by dduportal** [containous/traefik#5559]
### Do you want to request a *feature* or report a *bug*?

Proposal/Feature

### What did you expect to see?

This proposal follows #5535.

As a Docker user,
When I start a container with an exotic network mode as `host`,
Then I want to use docker labels (dynamic configuration with Docker provider) to specify a custom IP, that might overwrite the container private IP.

Example:

```yml
services:
  webapp:
    image: mywebapp:1.0.0
    container_name: webapp
    restart: always
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`localhost`)"
      - "traefik.http.routers.webapp.service=webapp-svc"
      - "traefik.http.services.webapp-svc.loadbalancer.server.host=172.17.0.1"
      - "traefik.http.services.webapp-svc.loadbalancer.server.port=8080"
```
