### ISSUE TITLE
Entrypoint and Backend Extremely High Open Connections Not Closing (1.7)

### ISSUE THREAD

**Issue by ys-taylorchristie** [containous/traefik#5564]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

I am attempting to use traefik as a load balancer for some old cold fusion windows servers. They aren't very stable and the servers go down from time to time, which is fine - but it seems like traefik is holding open connections for a ridiculous amount of time. I've tried setting different types of timeouts, but they can't be too strict otherwise some users cant access the site (terrible, I know). 

### What did you expect to see?

I expected connections to be dropped after a while and the open connections number going down.

### What did you see instead?

Once this number reaches ~5k, even if the backends come back online traefik isn't able to send any traffic to the backends. The open connection count doesn't go back down unless i completely restart traefik. 

![image](https://user-images.githubusercontent.com/51799307/65999562-db5cea80-e45a-11e9-8adc-8bddb750ad84.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# traefik version
Version:      v1.7.16
Codename:     maroilles
Go version:   go1.12.9
Built:        2019-09-13_01:12:20PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I've masked some company specific data with x's, but the configuration is fairly simplistic. This is currently whats being ran, I tried using the timeouts (commented out) but they give me SPDY errors and numerous other errors because the timeout is too low.

```toml
[file]
watch = true

#[respondingTimeouts]
#  readTimeout = "5s"
#  writeTimeout = "5s"


#[forwardingTimeouts]
#  dialTimeout = "5s"
#  responseHeaderTimeout = "10s"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
            certFile = "/certificates/live/xx/fullchain.pem"
            keyFile = "/certificates/live/xx/privkey.pem"
        [[entryPoints.https.tls.certificates]]
            certFile = "/certificates/live/xx/fullchain.pem"
            keyFile = "/certificates/live/xx/privkey.pem"
        [[entryPoints.https.tls.certificates]]
            certFile = "/certificates/live/x/fullchain.pem"
            keyFile = "/certificates/live/x/privkey.pem"
        [[entryPoints.https.tls.certificates]]
            certFile = "/certificates/live/x/fullchain.pem"
            keyFile = "/certificates/live/x/privkey.pem"
  [entryPoints.traefik]
    address = ":8080"

[api]

# Metrics definition
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]



[frontends]
    # redirect anything if required
    [frontends.r1]
        entrypoints = ["http", "https"]
        backend = "null"
        # for this host, lets redirect somewhere else
        [frontends.r1.routes.host]
            rule = "Host:masked.com"
        [frontends.r1.redirect]
            regex = "^https?://www.(.*)"
            replacement = "https://$1"
            permanent = true
    # default catchall
    [frontends.xx]
        entrypoints = ["http", "https"]
        passHostHeader = true
        backend = "xx"



[backends]
    [backends.xx]
        # enable sticky sessions: https://docs.traefik.io/basics/#sticky-sessions
        [backends.xx.loadbalancer.stickiness]
        # enable health checks
        [backends.xx.healthcheck]
            path = "/BYPASS/HealthCheck.cfm"
            interval = "5s"
        [backends.xx.servers.ca1]
            url = "http://xx:80"
        [backends.xx.servers.ca2]
            url = "http://xx:80"
    [backends.null]
        [backends.null.servers.null]
            url = "https://1.1.1.1"
[acme]
email = "x@x.x"
storage = "acme.json"
entryPoint = "https"
#onDemand = true
    [acme.httpChallenge]
        entryPoint = "http"
```
