### ISSUE TITLE
Godaddy dns challenge fails with "could not determine authoritative nameservers"

### ISSUE THREAD

**Issue by sebkouba** [containous/traefik#5566]
I'm trying to follow the official docker with letsencryt guide using godaddy dns challenge.

### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
Tried to follow the official guide.

### What did you expect to see?
DNS entry / cert to be generated

Does traefik generate the dns entry? I tried to manually add the entry to see if it changes anything and it didn't.

### What did you see instead?
```
"Configuration received from provider docker: {\"http\":{\"routers\":{\"whoami\":{\"entryPoints\":[\"websecure\"],\"service\":\"whoami-playtime\",\"rule\":\"Host(`whoami.domain.net`)\",\"tls\":{\"certResolver\":\"mydnschallenge\"}}},\"services\":{\"whoami-playtime\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.21.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
"Creating middleware" middlewareName=pipelining middlewareType=Pipelining serviceName=whoami-playtime entryPointName=websecure routerName=whoami@docker
"Creating load-balancer" routerName=whoami@docker serviceName=whoami-playtime entryPointName=websecure
"Creating server 0 http://172.21.0.2:80" serviceName=whoami-playtime entryPointName=websecure routerName=whoami@docker serverName=0
"Added outgoing tracing middleware whoami-playtime" middlewareName=tracing middlewareType=TracingForwarder routerName=whoami@docker entryPointName=websecure
"Creating middleware" entryPointName=websecure middlewareName=traefik-internal-recovery middlewareType=Recovery
"No default certificate, generating one"
"Try to challenge certificate for domain [whoami.domain.net] founded in HostSNI rule" providerName=mydnschallenge.acme routerName=whoami rule="Host(`whoami.domain.net`)"
"Looking for provided certificate(s) to validate [\"whoami.domain.net\"]..." rule="Host(`whoami.domain.net`)" providerName=mydnschallenge.acme routerName=whoami
"Domains [\"whoami.domain.net\"] need ACME certificates generation for domains \"whoami.domain.net\"." providerName=mydnschallenge.acme routerName=whoami rule="Host(`whoami.domain.net`)"
"Loading ACME certificates [whoami.domain.net]..." providerName=mydnschallenge.acme routerName=whoami rule="Host(`whoami.domain.net`)"
"Building ACME client..." providerName=mydnschallenge.acme
"https://acme-staging-v02.api.letsencrypt.org/directory" providerName=mydnschallenge.acme
"Using DNS Challenge provider: godaddy" providerName=mydnschallenge.acme
"legolog: [INFO] [whoami.domain.net] acme: Obtaining bundled SAN certificate"
"legolog: [INFO] [whoami.domain.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/11995534"
"legolog: [INFO] [whoami.domain.net] acme: Could not find solver for: tls-alpn-01"
"legolog: [INFO] [whoami.domain.net] acme: Could not find solver for: http-01"
"legolog: [INFO] [whoami.domain.net] acme: use dns-01 solver"
"legolog: [INFO] [whoami.domain.net] acme: Preparing to solve DNS-01"
"legolog: [INFO] [whoami.domain.net] acme: Trying to solve DNS-01"
"legolog: [INFO] [whoami.domain.net] acme: Checking DNS record propagation using [127.0.0.11:53]"
"legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
"legolog: [INFO] [whoami.domain.net] acme: Waiting for DNS record propagation."
...
msg="Unable to obtain ACME certificate for domains \"whoami.domain.net\": unable to generate a certificate for the domains [whoami.domain.net]: acme: Error -> One or more domains had a problem:\n[whoami.domain.net] time limit exceeded: last error: could not determine authoritative nameservers\n" providerName=mydnschallenge.acme routerName=whoami rule="Host(`whoami.domain.net`)"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.0.1

```
official docker image:
/ # traefik version
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
## docker-compose.yml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=godaddy"
      - "--certificatesresolvers.mydnschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mydnschallenge.acme.email=my@mail.org"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "GODADDY_API_SECRET=secret"
      - "GODADDY_API_KEY=key"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain.net`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mydnschallenge"
```

I've spent hours on this and I have no idea what else I could try so I'd appreciate any hints.
