### ISSUE TITLE
Application sent CORS headers are either not overwritten, or blocked completely

### ISSUE THREAD

**Issue by joe-bowman** [containous/traefik#5567]
### Do you want to request a *feature* or report a *bug*?

Bug

`accessControlAllowOrigin` in headers middleware doesn't return a valid value if the application already sends the `Access-Control-Allow-Origin` header. 

Final response contains duplicated headers (invalid CORS response) or zero `Access-Control-Allow-Origin` headers.

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Application behind Traefik emits 'Access-Control-Allow-Origin: *' header.

Used the headers middleware with the following configuration:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-all
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowOrigin: "origin-list-or-null"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "Content-Type"
    addVaryHeader: "true"
```

Queried with curl:
```
curl localhost:80/graphql -H 'Host: my.domain' -X GET -v -H 'Origin: https://my.domain' -H'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: content-type'
```

### What did you expect to see?
```
Access-Control-Allow-Origin: https://my.domain
```

### What did you see instead?
```
Access-Control-Allow-Origin: https://my.domain
Access-Control-Allow-Origin: *
```
(the header inserted by Traefik does not replace the header sent by the application, this results in an invalid CORS configuration).

If `*` is used as the value of  `accessControlAllowOrigin`, the response contains two headers with the same value, which is also rejected by the browser.
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
```

if `null` is used, nothing happens (the documentation suggests null is valid, but this has been removed from the code - presumably for security reasons)

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.0.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

KubernetesCRD provider
Simple IngressRoute+Middleware:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-graphql
  namespace: default
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`my.domain`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: graphql-http
          port: 80
          priority: 12
      middlewares:
      - name: cors-all
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-all
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowOrigin: "origin-list-or-null"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "Content-Type"
    addVaryHeader: "true"
```

**Comment by dtomcej** [comment]
Hello @joe-bowman,

Can you provide the response of `curl -v my.domain`?

I would like to see how the raw headers look in your case. I have been able to reproduce, but am doing some further debugging on my end.

**Comment by rfasouliotis** [comment]
I am experiencing the same exact thing. My only solution has been to disable the CORS headers in the Header middleware in Traefik, and have my application behind Traefik handle CORS, or disable my application CORS handling and have the headers middleware do it.

While I do prefer the latter approach, i.e. have the middleware do it, the instructions on the CORS header implementation are not very clear. Specifically, how do you define the list of allowed origins in the middleware? Or does that list match the allowedHosts entry?

**Comment by muuvmuuv** [comment]
+1. I would also like to know what `origin-list` in `AccessControlAllowOrigin: "origin-list-or-null"` means. Using yaml and inserting a list, like:

```yaml
      headers:
        accessControlAllowOrigin: 
          - localhost
          - domain.lcl
```

results in: 

```
time="2019-11-27T10:42:14Z" level=error msg="Error occurred during watcher callback: yaml: unmarshal errors:\n  line 57: cannot unmarshal !!seq into string" providerName=file
```

**Comment by TobiasHauck** [comment]
I was also confused what the origin-list-or-null means and it turned out, that it's a REAL VALUE for the access-control-allow-origin header, which is used to automate returning the origin of the incoming request if provided - not an example value, not a placeholder.

Maybe a better value name could be provided? Something like: inherit, auto, copy

So DON'T try to do something like this:
```
headers:
  accessControlAllowOrigin: 
    - localhost
    - domain.lcl
```

or: 

```
headers:
  accessControlAllowOrigin: localhost,domain.cl
```

BUT use:
```
...
accessControlAllowOrigin: origin-list-or-null
```

which is a valid value and not a placeholder or example... :-D

**Comment by muuvmuuv** [comment]
@TobiasHauck but where is that list? I would like to add origins :D

**Comment by dtomcej** [comment]
@muuvmuuv follow https://github.com/containous/traefik/pull/5996

**Comment by dolphyvn** [comment]
I had same issue and get it fixed by using     

> customResponseHeaders:

**Comment by Ray-Eldath** [comment]
**pretty consufed** by currently undocumented, or ill-documented of what `origin-list-or-null` means before i see this issue..........

I wrongly intrepret `origin-list-or-null` as "redirect the *origin* CORS headers coming from the service, or use `null`", which leads to debugging this for such a long time. sigh.

hoping #5996 could be GA soon. (currently is still RC, IIRC)

**Comment by muuvmuuv** [comment]
Still getting this in every browser (v2.2.0 Docker Image):

```
Access to XMLHttpRequest at 'https://m8finder.lcl/api' from origin 'https://m8finder.lcl:1717' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

```yaml
http:
  routers:
    api:
      rule: "Host(`m8finder.lcl`) && PathPrefix(`/api`)"
      service: m8finder-api
      entryPoints:
        - web-secure
      middlewares:
        - restrict_access
      tls: {}

  middlewares:
    restrict_access:
      headers:
        accessControlAllowOriginList:
          - m8finder.lcl
          - m8finder.lcl:1717
```

Am I missing something?

Docker dashboard doesn't even show the new entry, fyi.

**Comment by muuvmuuv** [comment]
Okay seems that this is working:

```yaml
  middlewares:
    restrict_access:
      headers:
        sslRedirect: true
        accessControlMaxAge: 12
        addVaryHeader: true
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - OPTION
          - POST
          - GET
          - PUT
          - DELETE
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - https://m8finder.lcl
          - https://m8finder.lcl:1717
```
