### ISSUE TITLE
caServer value does nothing

### ISSUE THREAD

**Issue by prometheanfire** [containous/traefik#5583]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Configured acme certificate generation to use the staging server so I don't hit the rate limit.

### What did you expect to see?

I expect to see the `caServer` I define in the config actually be defined

### What did you see instead?

The default is used at all times.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[certificateResolvers.foor-bar.acme]
  email = 'foo@bar.com'
  storage = 'acme.json'
  caServer = 'https://acme-staging-v02.api.letsencrypt.org/directory'
  [certificatesResolvers.foo-bar.acme.dnsChallenge]
    provider = "rfc2136"
    delayBeforeCheck = '15'
    resolvers = ["ns1.gratisdns.dk:53"]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-10-05T06:09:54Z" level=info msg="Starting provider *acme.Provider {\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"acme.json\",\"keyType\":\"RSA4096\",\"dnsChallenge\":{\"provider\":\"rfc2136\",\"delayBeforeCheck\":15000000000,\"resolvers\":[\"ns1.gratisdns.dk:53\"]},\"ResolverName\":\"foo-bar\",\"store\":{},\"ChallengeStore\":{}}"
```
