### ISSUE TITLE
[Help] basic/digest auth is always needed when each request be sent.

### ISSUE THREAD

**Issue by huapox** [containous/traefik#5596]
Hi, dear all. I'm using traefik v1.7.17 in k8s with tls acme enabled, the ingress is defined as following:

```
kind: Ingress
metadata:
  name: kube-web
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: mysecret-bauth
```

Find that basic/digest auth is always needed when each request be sent.  without a session?
When i use lighttpd with http basic auth, that just need to auth once when browser reopend(just like there be session, keeped in the client browser).

Thx.
