### ISSUE TITLE
TLS via secretName Kubernetes

### ISSUE THREAD

**Issue by wattymelon** [containous/traefik#5597]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Attempted to use a (non LE) SSL Wildcard to provide SSL TLS via the secretName tag in an IngressRoute as per the documentation. 

### What did you expect to see?

Specified SSL Cert to be applied to host on IngressRoute

### What did you see instead?

TRAEFIKDEFAULT Cert and errors in console about not being able to see secret

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.0.1

Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: my-namespace
data:
  tls.crt: base 64 encoded crt file LS0tLS1CRUd....
  tls.key: base 64 encoded key file LS0tLS1CRUd....
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-app
  namespace: my-namespace
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`my-app.domain`)
    kind: Rule
    services:
    - name: my-app
      port: 1234
    middlewares:
    - name: ipwhitelist
  tls:
    secretName: mysecret
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Error configuring TLS: secret my-namespace/mysecret does not exist" ingress=my-app namespace=my-namespace providerName=kubernetescrd
```
