### ISSUE TITLE
ForwardAuth TLS set caOptional=true still ask for client cert and client key

### ISSUE THREAD

**Issue by RyukerLiu** [containous/traefik#5604]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Setting ca file and caOptional to true with no cilent key and cert.
```toml
   [http.middlewares.test-auth.forwardAuth.tls]
      ca = "/etc/vault/tls/ca.pem"
      caOptional = true
```

### What did you expect to see?

No need to set client certificate and key when setting forwardauth middleware tls `caOptional=true`

### What did you see instead?

Midlleware ERROR: TLS Certificate or Key file must be set when TLS configuration is created

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml
```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[log]
  level = "DEBUG"

[ping]

[api]
  insecure = true

[providers]
  [providers.docker]

  [providers.file]
    watch = true
    filename = "dynamic_conf.toml"
```

dynamic_conf.toml
```toml
# http routing section
[http]
  [http.routers]
     # Define a connection between requests and services
     [http.routers.to-web]
      rule = "Host(`localhost`)"
      middlewares = ["test-auth"]
      service = "myweb"
  
  [http.middlewares]
    [http.middlewares.test-auth.forwardAuth]
      address = "https://127.0.0.1:8200/v1/auth/token/lookup-self"
    [http.middlewares.test-auth.forwardAuth.tls]
      ca = "/etc/vault/tls/ca.pem"
      caOptional = true


  [http.services]
    # Define how to reach an existing service on our infrastructure
    [http.services.myweb.loadBalancer]
      [[http.services.myweb.loadBalancer.servers]]
        url = "http://localhost:8000"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
DEBU[2019-10-09T14:44:33+08:00] Added outgoing tracing middleware myweb       middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=to-web@file
DEBU[2019-10-09T14:44:33+08:00] Creating middleware                           middlewareName=test-auth@file middlewareType=ForwardedAuthType entryPointName=traefik routerName=to-web@file
ERRO[2019-10-09T14:44:33+08:00] TLS Certificate or Key file must be set when TLS configuration is created  entryPointName=traefik routerName=to-web@file
DEBU[2019-10-09T14:44:33+08:00] Creating middleware                           middlewareType=Recovery entryPointName=traefik middlewareName=traefik-internal-recovery
DEBU[2019-10-09T14:44:33+08:00] No default certificate, generating one       
```
