### ISSUE TITLE
Using several times a cert floods logs

### ISSUE THREAD

**Issue by sylr** [containous/traefik#5622]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We use a wildcard certificates that is duplicated in each namespaces it is needed for in our kubernetes cluster (v1.13.6).

In the logs traefik writes a lot of warning saying that the certificates already exists for the default entryPoint (shouldn't it be certificate store instead of entryPoint ?).

```
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
{"level":"warning","msg":"Skipping addition of certificate for domain(s) \"*.domain.com,domain.com\", to EntryPoint default, as it already exists for this Entrypoint.","time":"2019-10-10T09:44:32Z"}
```

That's 67797 in 25 minutes.

```
sylvain@ubuntu-1604-dev:~$ kubectl --context=k8s11-euw-dev -n ingress get pods traefik-v2-6bf947f58-dnn6q
NAME                         READY   STATUS    RESTARTS   AGE
traefik-v2-6bf947f58-dnn6q   1/1     Running   0          25m
sylvain@ubuntu-1604-dev:~$ kubectl --context=k8s11-euw-dev -n ingress logs traefik-v2-6bf947f58-dnn6q | grep "as it already exists for this Entrypoint." | wc -l
67797
```

### What did you expect to see?

One warning for each secrets once for all or that the log entry is turned into a debug one.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [log]
      level = "INFO"
      format = "json"
    [accessLog]
      format = "json"
    [entryPoints.http]
      address = ":80"
    [entryPoints.http-internal]
      address = ":81"
    [entryPoints.https]
      address = ":443"
    [entryPoints.traefik]
      address = ":8080"
    [entryPoints.traefik-ext]
      address = ":8081"
    [providers.kubernetesIngress]
       ingressClass = "traefik"
    [providers.kubernetesCRD]
    [providers.file]
      directory  = "/config/static"
      watch = true
    [api]
      insecure = true
      dashboard = true
      debug = true
    [metrics.prometheus]
      entryPoint = "traefik"
      buckets = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0]
```
