### ISSUE TITLE
Allow defining default list of entryPoints for kubernetes ingress provider

### ISSUE THREAD

**Issue by sylr** [containous/traefik#5624]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be useful if we could define which entryPoints are used by the kubernetes ingress provider instead of using all entryPoints.

E.G.:
```toml
[providers.kubernetesIngress]
  ingressClass = "traefik"
  entryPoints = ["http", "https"]
```

Regards.
