### ISSUE TITLE
Activating "proxied" on cloudflare subdomain A entry gives TOO_MANY_REDIRECTS error

### ISSUE THREAD

**Issue by v0idp** [containous/traefik#5629]
### What did you expect to see?

I use cloudflare proxied subdomains to redirect to my services on my raspberry pi. If I open said subdomain on my browser it should show the website

### What did you see instead?

TOO_MANY_REDIRECTS
(only if proxied is activated for said subdomain)

### alternative solution for me

I can make it only work if the only entry I have in cloudflare as host is "*"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v1.7-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
insecureskipverify = true
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[acme]
acmeLogging = true
email = "voidp@protonmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 30

[[acme.domains]]
  main = "*.kdaldal.me"
[[acme.domains]]
  main = "kdaldal.me"

[entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth]
    [entryPoints.traefik.auth.basic]
      removeHeader = true
      users = [
        "void:$apr1$mddCcrIX$e1JurLbPkBP1h1QpAjqH./",
      ]

[api]
entryPoint = "traefik"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kdaldal.me"
watch = true
exposedbydefault = false
```

container labels
```
traefik.enable: true
traefik.frontend.redirect.entryPoint: https
traefik.frontend.rule: Host:cv.kdaldal.me
traefik.port: 80
```
