### ISSUE TITLE
Need URL rewrite to add trailing slash

### ISSUE THREAD

**Issue by javefang** [containous/traefik#563]
I have a simple app, which has the following file structure at root
- script.js
- style.css
- index.html (load the other two files using relative path `script.js` and `style.css`)

Since I want to access the app via URL `http://example/app`, I proxied the web app with rule `PathStripPrefix:/app`. The problem is when I try to access URL `http://example/app` (without trailing slash), it will load "index.html" fine, but not the JS and CSS file. When I look into the debugger, it tries to load:
- http://example/script.js
- http://exmaple/style.css

Instead of (the correct one):
- http://example/app/script.js
- http://example/app/style.css

It only works when I type the original URL with a trailing slash, so `http://example/app/`. This is not a big deal for me but users sometimes find it annoying since we used to use Nginx, who sends an "301 Moved Permanently" to a URL with trailing slash when it's not there. I wonder if it is possible / makes sense to implement this in Traefik?

Thank you!

**Comment by godliness** [comment]
same issue, anyone have idea?

**Comment by godliness** [comment]
same issue, anyone have idea?

**Comment by godliness** [comment]
same issue, anyone have idea?

**Comment by godliness** [comment]
same issue, anyone have idea?

**Comment by godliness** [comment]
same issue, anyone have idea?

**Comment by godliness** [comment]
same issue, anyone have idea?

**Comment by javefang** [comment]
Think should be a feature. Although you.probably want it most of the time, and begins does it by default if you use it as reverse proxy.

Expected behaviour is explained in my original post.

**Comment by royjs** [comment]
I also have the same issue

**Comment by emilevauge** [comment]
Hi, this is due to the underlying muxer used in traefik http://www.gorillatoolkit.org/pkg/mux#Router.StrictSlash. We use it with `StrictSlash` enabled but there is an exception:
>Special case: when a route sets a path prefix using the PathPrefix() method, strict slash is ignored for that route because the redirect behavior can't be determined from a prefix alone. However, any subrouters created from that route inherit the original StrictSlash setting.

We need to work on this indeed...
As a workaround for now, I suggest to use `Host` rules instead of `Path` based rules if possible.
Any help on this is welcome ;)

**Comment by ThinkBriK** [comment]
I was able to workaround this issue using the regex on the entrypoint:
```
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "(http:\\/\\/[^\\/]+\\/([^\\?]+)[^\\/])$"
      replacement = "$1/"
```

The redirection is fine but I ran into #679 :(

**Comment by pascalandy** [comment]
Hey folks!

I'm looking for getting a response over `example.com/nginxtest`. I'm really close!

### My Nginx container
Here is my container. My stack use Docker Swarm Mode.

```
CTN_NGX_TEST="nginxtest"
WWW_SRC="/to-mount/nginx-static/starter"
WWW_DST="/usr/share/nginx/html"

docker service create \
--name "$CTN_NGX_TEST" \
--network "$NTW_FRONT" \
--mount	type=bind,src="$WWW_SRC",target="$WWW_DST" \
--label traefik.enable="true" \
--label traefik.frontend.rule="Host:example.com;PathPrefixStrip:/nginxtest" \
--label traefik.frontend.entryPoints="http" \
--label traefik.docker.network="$NTW_FRONT" \
--label traefik.backend="$CTN_NGX_TEST" \
--label traefik.backend.loadbalancer.sticky="true" \
--label traefik.weight="10" \
--label traefik.frontend.priority="10" \
--label traefik.backend.loadbalancer.method="drr" \
--label traefik.port="80" \
nginx
```

### The Issue
Here is the result:

![result1](https://cloud.githubusercontent.com/assets/6694151/22611309/d1a9bd3a-ea37-11e6-8561-82c1293acee3.png)

Now, when I click on a link, it shows: `example.com/about/about-1.html`.

See the issue ?!? The link should go here `example.com/nginxtest/about/about-1.html` (not `example.com/about/about-1.html`). **Big glitch right here!**

### Getting closer
When I manually enter `example.com/nginxtest/index.html` in my browser, I can surf normally within the website.

**Comment by juanpaps03** [comment]
same issue #1106

**Comment by pascalandy** [comment]
Glad it helped :) See my [conclusion here](https://github.com/containous/traefik/issues/1123#issuecomment-277769224).

**Comment by markhowells** [comment]
@emilevauge  I hate to just add noise to this issue - but host based routing isn't really an option for us. Our customers have too many http proxy/firewalls in the way...  Certainly we can organise html data such that the webserver container responds correctly with the full path but it pollutes the deployment - adding 'brittleness' since if we change the deployment path we have to change the data organisation to reflect the path and/or add configuration to what would otherwise be a trivial deployment...

**Comment by ldez** [comment]
Closed by #1638, in the version 1.3.0-rc3.

**Comment by kachkaev** [comment]
@ldez could you please clarify how to achieve a redirect from `http://example/app` to `http://example/app/`, as @javefang is asking? Still facing the same problem, i.e. when I open `http://example/app`, the browser tries to load css and js from `http://example/static/main.(js|css)`. What I'm looking for is some easy way to automatically add a trailing slash to `/app` if it's not entered.

My current igress spec:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: example
    http:
      paths:
      - path: /app
        backend:
          serviceName: my-app
          servicePort: http
```

There is a dirty workaround for nginx in https://github.com/kubernetes/contrib/issues/1884#issuecomment-297075677, but I haven't found anything similar for traefik.

**Comment by pascalandy** [comment]
I confirm this was resolve when Emile officially release it about 3 months ago.
I run v1.3.3 and it's all good.

**Comment by kachkaev** [comment]
@pascalandy do you mean that traefik automatically redirects from `/app` to `/app/` in your case? If yes, what does your config look like?

**Comment by pascalandy** [comment]
Enjoy this setup :)
https://github.com/pascalandy/docker-stack-this/tree/master/traefik-manager

**Comment by ldez** [comment]
@pascalandy I don't know if you have see: we created https://github.com/containous/traefik/wiki/Awesome-Traefik.
 We will very happy if you want to share your repositories in this wiki 😃

**Comment by kachkaev** [comment]
Thanks for the links guys. Not sure my k8s-specific question is answered in that material though :–)

**Comment by martinbaillie** [comment]
Not sure this was answered either. Did you find a way to go from http://example/app to http://example/app/ @kachkaev?

**Comment by kachkaev** [comment]
No, unfortunately. I still can't configure a separate backend at `/app/` and make a rule that would redirect `/app` to `/app/`. Wondering if this issue should be reopened.

**Comment by dimm0** [comment]
Figured how to make it work.
Use:
```
    ingress.kubernetes.io/rewrite-target: /<your_app>
```
DON'T use    `traefik.frontend.rule.type: PathPrefixStrip`

In traefik.toml:

```
    [entryPoints.http.redirect]
      entryPoint = "https"
```
and
```
    [entryPoints.https.redirect]
      regex = "(https:\\/\\/[^\\/]+\\/([^\\?]+)[^\\/])$"
      replacement = "$1/"
```

Everything works fine for me now.

**Comment by kachkaev** [comment]
Any ideas?

**Comment by kachkaev** [comment]
Here is my current solution for k8s until I find something better 😆 

Meet namespace `redirects`!

```yaml
## add-trailing-slash.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: add-trailing-slash
  namespace: redirects
data:
  default.conf: |
    server {
      server_name $host;
      rewrite ^(.*) $scheme://$host$1/ permanent;
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add-trailing-slash
  namespace: redirects
  labels:
    part: add-trailing-slash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        part: add-trailing-slash
    spec:
      containers:
      - name: main
        image: nginx:1.13.6-alpine
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-config
        configMap:
          name: add-trailing-slash
---
apiVersion: v1
kind: Service
metadata:
  name: add-trailing-slash
  namespace: redirects
  labels:
    part: add-trailing-slash
spec:
  ports:
  - port: 80
    name: http
  selector:
    part: add-trailing-slash
```

```bash
kubectl apply -f add-trailing-slash.yaml

CASES=(
example.com/path1
another.example.com/path2
)

for CASE in "${CASES[@]}"; do
IFS='/' read CASE_DOMAIN CASE_PATH <<< "$CASE"

echo "
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: add-trailing-slash-for-${CASE_DOMAIN}--${CASE_PATH//\//-}
  namespace: redirects
spec:
  rules:
  - host: ${CASE_DOMAIN}
    http:
      paths:
      - path: /${CASE_PATH}
        backend:
          serviceName: add-trailing-slash
          servicePort: http
" | kubectl apply -f -;
done;
```

Thankfully I don't have that many client-facing microsercices that start with `example.com/some-path`. I know the above solution is terrible, so if anyone has any better suggestions, I'll be happy throw away all of the above manifests!

**Comment by hartzell** [comment]
I've been wrestling with this and wanted to leave a note and/or get a bit of feedback.

I'm running Traefik and [SequenceServer](https://www.sequenceserver.com/) via Docker Compose, using a PathPrefixStrip rule to make the SequenceServer appear at `/sequenceserver/`.  Everything works as it should as long as that trailing slash is there.  Without it the page itself is returned but the CSS and JS resources end up being requested from `/` instead of `/sequenceserver` (they're defined via relative paths, so it's what you'd expect to happen).

I'd really like to be able to redirect `.../sequenceserver` to `.../sequenceserver/`

I thought that I could define a redirect on the https entrypoint in the traefik.toml file, but they appear to run after the frontend rules (even though they're leftmost in the [basics picture](https://docs.traefik.io/basics/)).

I was excited to discover that I could use a redirect in a frontend rule from label in a the Docker container definition, but it turns out that the PathPrefixStrip runs first and the redirect no longer matches anything.

I also messed around with defining a `[file]` section in the `traefik.toml` and trying to use dummy front and backends to solve it, but the rule from the docker container fires first (I can redirect other strings, just not the slash-less version of the one that the Docker container is using.

I'm giving up for now.  I anticipate much wailing and gnashing of teeth from the users who expect to be able to use either

If anyone else has any suggestions, I'd be happy to take them out for a test drive.

**Comment by hartzell** [comment]
@pascalandy over in pascalandy/docker-stack-this#10 asked about the `traefik.toml` I'm using, figured I'd include it here for completeness.

You'll either need to tack on an acme [[domains]] section or mention a Host rule in one of your containers to get the certs to go right.

```toml
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

# run the ping-test backend on https
# https://<blah>/ping
[ping]
entryPoint = "https"

# API backend, magic happens in the docker-compose.yml file...
# ends up on https://<blah>/api
[api]
  entryPoint = "traefik_api"
  dashboard = true
  debug = false

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik_api]     # use port 8081 to avoid conflicts with Jenkins
  address = ":8081"
    [entryPoints.traefik_api.auth.basic]
    users = ["someone:PASSWORDGOESHERE"]

# retry requests if network error
[retry]

# listen for docker containers, only expose the containers that
# request it
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[acme]
email = "someone@somewhere.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"
```

**Comment by MindTooth** [comment]
Hi,

I have the same issue with Portainer, which don't load via`/portainer` but only `/portainer/`.

This is stuff I've tried, in various configurations: (and yes, I don't really know what I'm doing here)
```
# - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer; ReplacePath: /portainer/"
# - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer/"
# - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer$$"
# - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /{portainer:portainer$$}"
# - "traefik.frontend.redirect.regex=([^/]*)$$"
# - "traefik.frontend.redirect.replacement=$$1/"
```

My goal is simple; answer to both paths, but redirect when accessing without trailing slash.

Can this be achieved?

Cheers 👍

**Comment by pascalandy** [comment]
I'm still looking for the answer :)

> Can this be achieved?

**Comment by hartzell** [comment]
@pascalandy -- did you hack not work for you or is it just to ugly to live with?

**Comment by pascalandy** [comment]
sorry @hartzell I don't understand your last comment.

**Comment by hartzell** [comment]
Sorry, wasn't clear enough.

[Up above in this discussion](https://github.com/containous/traefik/issues/563#issuecomment-382960068) I describe a way (hack...) get the URL without the trailing '/' to redirect to the version with the trailing '/'.

It boils down to setting up a "scratch" service (which will never actually get used, it can use an insignificant image, etc...) that only matches your real URL w/out the trailing '/' (e.g. `/sequenceserver` in my example above) and rewrites it to one with the trailing '/' (e.g. `"traefik.frontend.redirect.replacement=$$1/"` above).

It's not pretty, but It Works For Me(tm).

**Comment by jvenezia** [comment]
In case anyone still looses himself in this GH issue (I did..), here is a working solution:

```
      traefik.frontend.redirect.regex: "^(.*)/portainer$"
      traefik.frontend.redirect.replacement: "$1/portainer/"
      traefik.frontend.rule: "ReplacePathRegex: ^/portainer/(.*) /$1"
```

**Comment by pascalandy** [comment]
I'll try it and report :)

**Comment by eserete** [comment]
It works like a charm!

**Comment by MindTooth** [comment]
After some trial and error, I found that I needed to escape the `$` with another `$` in-front, resulting in `$$` instead.

### docker-compose.yml
```yaml
- "traefik.frontend.redirect.regex=^(.*)/portainer$$"
- "traefik.frontend.redirect.replacement=$$1/portainer/"
- "traefik.frontend.rule=ReplacePathRegex: ^/portainer/(.*) /$$1"
```

**Comment by pascalandy** [comment]
@MindTooth 

Have you tried with `PathPrefix:/portainer` ?

```
traefik.frontend.rule: "PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$1"
```

**Comment by MindTooth** [comment]
```yaml
  portainer:
    container_name: portainer
    domainname: ${DOMAINNAME:?err}
    hostname: portainer
    environment:
      - TZ=${TZ}
    image: portainer/portainer
    labels:
      - "traefik.backend=portainer"
      - "traefik.docker.network=battle_net"
      - "traefik.enable=true"
      - "traefik.port=9000"
      # - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      # - "traefik.frontend.redirect.replacement=$$1/portainer/"
      # - "traefik.frontend.rule=ReplacePathRegex: ^/portainer/(.*) /$$1"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer; ReplacePath: /portainer/"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer$$"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /{portainer:portainer$$}"
      # - "traefik.frontend.redirect.regex=([^/]*)$$"
      # - "traefik.frontend.redirect.replacement=$$1/"
      # - "traefik.passhostheader=true"
      - traefik.frontend.redirect.regex: "^(.*)/portainer$"
      - traefik.frontend.redirect.replacement: "$1/portainer/"
      - traefik.frontend.rule: "PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$1"
    networks:
      - battle_net
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer:/data
```

```sh
➜ sh up.sh
ERROR: Invalid interpolation format for "labels" option in service "portainer": "^(.*)/portainer$"
```

**Comment by MindTooth** [comment]
```yaml

  portainer:
    container_name: portainer
    domainname: ${DOMAINNAME:?err}
    hostname: portainer
    environment:
      - TZ=${TZ}
    image: portainer/portainer
    labels:
      - "traefik.backend=portainer"
      - "traefik.docker.network=battle_net"
      - "traefik.enable=true"
      - "traefik.port=9000"
      # - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      # - "traefik.frontend.redirect.replacement=$$1/portainer/"
      # - "traefik.frontend.rule=ReplacePathRegex: ^/portainer/(.*) /$$1"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer; ReplacePath: /portainer/"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer$$"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /{portainer:portainer$$}"
      # - "traefik.frontend.redirect.regex=([^/]*)$$"
      # - "traefik.frontend.redirect.replacement=$$1/"
      # - "traefik.passhostheader=true"
      - traefik.frontend.redirect.regex: "^(.*)/portainer$"
      - traefik.frontend.redirect.replacement: "$1/portainer/"
      - traefik.frontend.rule: "PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$1"
    networks:
      - battle_net
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer:/data
```

```sh
➜ sh up.sh
ERROR: Invalid interpolation format for "labels" option in service "portainer": "^(.*)/portainer$"
```
