### ISSUE TITLE
Single/default router

### ISSUE THREAD

**Issue by TeoTN** [containous/traefik#5630]
### Do you want to request a *feature* or report a *bug*?
Missing feature from traefik v1.7

Feature

### What did you expect to see?
I'd like to specify single router for all my services, or a default router configuration. I don't want to specify `rule`, `tls.options`, `tls.certResolver`, `tls.domains.main` and `tls.domains.sans` in all services' labels. In Traefik v1.7 I'd specify just once that all endpoints are TLS-protected with Let's Encrypt, and labels would basically have a rule with a subdomain and target port.
It doesn't seem to be possible with the newest Traefik version, or the docs don't include such example.

**Comment by Sarke** [comment]
https://github.com/containous/traefik/issues/4863#issuecomment-543013524

**Comment by yiwork** [comment]
I'm upvoting this. It seems like there have been several requests to bring back either single route, or single entrypoint. I'm dying with all the labels I need to define across all my apps. 

I cannot imagine what happens when an org has 100+ apps.

**Comment by schuerg** [comment]
A flexible solution would be to specify router templates like so:

```toml
[http.middlewares]
  [http.middlewares.redirect-to-https.redirectScheme]
    scheme = "https"

[http.routers]

  [http.routers.base-router1]
    entrypoints = [ "websecure" ]
    middlewares = [ "redirect-to-https" ]
    [http.routers.base-router1.tls]
      certResolver = "leresolver"
    [[http.routers.base-router1.tls.domains]]
        main = "example.com"
        sans = ["*.example.com"]

  [http.routers.traefik]
    routerTemplate = "base-router1"
    rule = "Host(`traefik.schuerg.net`)"
    service="api@internal"

```

**Comment by schuerg** [comment]
A flexible solution would be to specify router templates like so:

```toml
[http.middlewares]
  [http.middlewares.redirect-to-https.redirectScheme]
    scheme = "https"

[http.routers]

  [http.routers.base-router1]
    entrypoints = [ "websecure" ]
    middlewares = [ "redirect-to-https" ]
    [http.routers.base-router1.tls]
      certResolver = "leresolver"
    [[http.routers.base-router1.tls.domains]]
        main = "example.com"
        sans = ["*.example.com"]

  [http.routers.traefik]
    routerTemplate = "base-router1"
    rule = "Host(`traefik.example.com`)"
    service="api@internal"

```

**Comment by TeoTN** [comment]
Honestly, this is all simple key-value data structures. I think there should be an option to define mixins.
```
mixins:
  mixin-1:
    entrypoints:
      - http
    middlewares:
      - redirect-to-https
```
Validation could be done after mixin resolution

**Comment by Sarke** [comment]
Actually, @TeoTN, that's a good idea.  YAML already sort of supports this using anchors:

```yaml

x-defaults:
  mydomaincom: &mydomaincom
    rule: 'Host(`mydomain.com`, `www.mydomain.com`)'
    priority: 100
    middlewares: [mydomain-redirect]
    service: noop@file

http:
  routers:
    mydomain.com redirect:
      <<: *mydomaincom
      entryPoints: [web]
    mydomain.com ssl-redirect:
      <<: *mydomaincom
      entryPoints: [websecure]
      tls: {}
```

**Comment by gaui** [comment]
I can't get this to work, always get `404 page not found`.

```yaml
entryPoints:
  web:
    address: :80

  traefik:
    address: :8080

default-router: &default-router
  priority: 100
  rule: HostRegexp(`{host:.+}`)
  middlewares:
    - https-redirect
  service: noop@file

http:
  routers:
    default:
      <<: *default-router
      entryPoints:
        - web

    default-secure:
      <<: *default-router
      entryPoints:
        - web-secure
      tls: {}

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
```

Then on my service:

```yaml
labels:
      - traefik.enable=true
      - traefik.http.services.foo.loadbalancer.server.port=80
      - traefik.http.routers.foo.entrypoints=web-secure
      - traefik.http.routers.foo.rule=Host(`fossari.is`, `www.fossari.is`)
```

What I see in the logs:

```
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"fossari\":{\"entryPoints\":[\"web-secure\"],\"service\":\"fossari\",\"rule\":\"Host(`fossari.is`, `www.fossari.is`)\"}},\"services\":{\"fossari\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.24.0.3:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Adding certificate for domain(s) fossari.is,www.fossari.is"
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="No default certificate, generating one"
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Creating middleware" middlewareType=Pipelining middlewareName=pipelining entryPointName=web-secure routerName=fossari@docker serviceName=fossari
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Creating load-balancer" entryPointName=web-secure routerName=fossari@docker serviceName=fossari
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Creating server 0 http://172.24.0.3:80" routerName=fossari@docker serviceName=fossari serverName=0 entryPointName=web-secure
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Added outgoing tracing middleware fossari" entryPointName=web-secure routerName=fossari@docker middlewareType=TracingForwarder middlewareName=tracing
traefik_1  | time="2019-11-07T02:21:49Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=web-secure middlewareName=traefik-internal-recovery
```

**Comment by rehoutm** [comment]
Would that somehow work for Docker labels?

**Comment by majkrzak** [comment]
@schuerg the proposal you have proposed is not the best solution. @Sarke same here. It still requires to specify the template explicitly in every singe router (so it is not compatible with 1.x and does not allow you to use plain kubernetes ingress definitions)

**Imo the best will be to define the `http.routers.default` or `defaults.http.router` that will be the base configuration for every new router**

**Comment by dimm0** [comment]
I'm stuck with this for several months now, can't transition to V2 and set the default https router with default certificate...
An example in main documentation would be super helpful

**Comment by ldez** [comment]
@dimm0 the default certificate can be set without "default" router: https://docs.traefik.io/v2.0/https/tls/#default-certificate

**Comment by majkrzak** [comment]
@ldez but can acme be set like that so? And http to https promotion?

**Comment by dimm0** [comment]
Yeah, I did that, getting 404 for https... http works
I'd like a full example on default cert with http to https redirect (or acme as other here want, but should be similar)

**Comment by majkrzak** [comment]
In my case I have to setup equivalent config:
```toml
        defaultEntryPoints = ["https"]
        rootCAs = [ "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" ]
        logLevel = "DEBUG"
        [traefikLog]
        filePath = ""
        format   = "json"
        [accessLog]
        filePath = ""
        format = "json"
        [entryPoints]
          [entryPoints.http]
          address = ":80"
          compress = true
            [entryPoints.http.redirect]
            entryPoint = "https"
          [entryPoints.https]
          address = ":443"
          compress = true
            [entryPoints.https.tls]
            minVersion = "VersionTLS12"
            sniStrict = true
        [acme]
        onHostRule = true
        email = "my@ema.il"
        storage = "/data/acme.json"
        entryPoint = "https"
        KeyType = "EC256"
          [acme.httpChallenge]
          entryPoint = "http"
        [kubernetes]
        [file]
          [backends]
            [backends.kubernetes]
              [backends.kubernetes.servers.kubernetes]
              url = "https://kubernetes.default"
          [frontends]
            [frontends.kubernetes]
            backend = "kubernetes"
              [frontends.kubernetes.routes.kubernetes]
              rule = "Host:my.host"
```

**Comment by dimm0** [comment]
Here's mine in 1.7:
```
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
InsecureSkipVerify = true
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
      ]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/k8s_cert.cer"
      KeyFile = "/ssl/k8s.key"
```

**Comment by gaui** [comment]
Why did you mark my comment as off-topic? It's very much on-topic. I have this same exact problem, where I want all HTTP traffic to be routed/redirected to HTTPS, and don't want to specify a router for each one. So it's regarding the possibility to add a default router (catch all).

**Comment by ldez** [comment]
The issue is a proposal: a place to discuss about the proposition.

For specific configuration issue, the [forum](https://community.containo.us/) is a better place to do that.

**Comment by majkrzak** [comment]
@ldez you are wrong. Configuration is a part of the discussion and this issue is not only a feature request but also report of quite serious bug. It looks so that by releasing version 2 you have broken many of the features. It looks incomplete (I've beet that the code is also same messy as in 1.x) and the reasoning behind the changes are very unclear.

If you realy think it is not a bug and our comments are really out off topic please provide corresponding config for 2.x. But I hevely doubt it is possible in the current demo version...

**Comment by dduportal** [comment]
Hi @majkrzak , being though and rude is not the best way to advocate for a change of software behavior or a new feature.

If the version 2.0 breaks your setup, please stay in 1.7 and take time to discuss politely.

This issue had been proposed by the original issuer as a **feature request**. We labelled it as a "proposal" because some things might be clarified and a discussion should happen as it started before your comments.

You are not alone, and if every user ping the maintainers for their own problems or priority, the project could not even go forward as everyone as a different context.

Sharing configuration here to get help to make it work is a different thing. We would be happy to provide help on the community forum, but it is off topic from the main discussion: we want to hear proposal of user facing configuration or use case.

We hear your concern as you explained (and proposed something) in https://github.com/containous/traefik/issues/5630#issuecomment-550977391 , thanks for this. Please wait for other users or maintainers to start spending time on this particular behavior now.

Of course, if you find information hard to get on the documentation, it is open source as well and you can propose changes or write down user guides / migration guides.

**Comment by dimm0** [comment]
This case is as general as it can be: provide access to an https endpoint and redirect http to it. What can be easier? I've spent several months and numerous attempts to make this work, and I failed so far. There was no example even after this long discussion (I saw a couple in other places which take almost the whole screen, haven't tried those)

And yes, I'm on 1.7 so far..

**Comment by ldez** [comment]
> This case is as general as it can be: provide access to an https endpoint and redirect http to it.

@dimm0 you can use the "global redirection" pattern https://community.containo.us/t/global-http-to-https-redirect-in-v2/1658/3

https://github.com/containous/traefik/issues/5630#issuecomment-551274887

**Comment by majkrzak** [comment]
@ldez show an example please, cause I see there that he can not do it.

**Comment by dimm0** [comment]
Do I need 2 files? Can't do in one?
What's `url = "http://192.168.0.1"`?
Where should I put path to my certs?

**Comment by ldez** [comment]
@dimm0 @majkrzak if you want examples and explanations come to the [community forum](https://community.containo.us)

**Comment by majkrzak** [comment]
How can I get them there, if the functionality is no longer available?

**Comment by dimm0** [comment]
Is it me being stupid, or it's not covered in docs and is not obvious?
Shouldn't this example be in docs, so that people who want to use traefik V2 in most common way don't have to dig through forum?

**Comment by codestation** [comment]
> **Imo the best will be to define the `http.routers.default` or `defaults.http.router` that will be the base configuration for every new router**

IMO it would be better to define some routers then allow one of these as the default. For example i have like 50 sites, half of those are subdomains of `domain-a` and the other half are subdomains of `domain-b`. By just going with a default router it would mean that i still have to define half my sites by hand since i can have only one default.

Maybe just allowing something like:

```yml
http:
  defaultRouter: Router0
```

So any router will use `Router0@file` as a parent, merging the keys.

In my usecase i don't need a default but would declare a pair of routers in the config file, then reference it on my services like this:

``` yml
- traefik.http.routers.myrouter.parent=Router0@file
```
``` yml
- traefik.http.routers.another.parent=Router1@file
```

Or just declare Router0 as default and adding Router1@file as parent for half my services. Maybe i am using a default but i don't want it for an specific service, so that router would end as:

``` yml
- traefik.http.routers.snowflake.noParent=true
```

This way it it wouldn't break existing configs, doesn't introduce new new config blocks and only needs 3 keys: `defaultRouter`, `parent` and `noParent`.

**Comment by majkrzak** [comment]
`traefik.http.routers.snowflake.noParent=true` can be replaced with `traefik.http.routers.another.parent=null` IMO

**Comment by codestation** [comment]
Taking the idea from my previous comment i made a PoC to be able to use any other router as a base. I am currently testing on my personal server and allowed me to trim all the tls/entrypoint/middleware config.

Patch is here: https://github.com/codestation/traefik/commit/53b8f4ef724792fb4beee96f675bbd8aad1a99b6
Image with the patch (using master as a base): https://hub.docker.com/r/codestation/traefik

For example i have defined a default route on my dynamic config file called `default`:

```yml
http:
  routers:
    catchall:
      entryPoints: ["http"]
      middlewares: ["redirect"]
      rule: "HostRegexp(`{host:.+}`)"
      service: "noop"
    default:
      entryPoints: ["https"]
      middlewares: ["secureHeaders"]
      rule: "HostRegexp(`^$`)"
      service: "noop"
      tls:
        certresolver: "dns"
        domains:
          - main: "example.com"
            sans: ["*.example.com"]
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1/"
  middlewares:
    secureHeaders:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXSSFilter: true
        X-Custom-Request-Header: "X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
    redirect:
      redirectScheme:
        scheme: https
```

Then on my docker labels y only need the minimal flags:

``` yml
labels:
    - traefik.enable=true
    - traefik.http.routers.portainer.rule=Host(`portainer.example.com`)
    - traefik.http.routers.portainer.base=default@file
    - traefik.http.services.portainer.loadbalancer.server.port=9000
```

Of course i can also do it without yml files and just use any other router from any provider as my base

    traefik.http.routers.portainer.base=another-router@docker

The `@docker` can also be omitted in this case since both routers are under the same provider.

The only restriction is not be able to use a router that is already using another router as a base (to prevent a possible endless loop).

Thoughts? Improvements? I don't know much about the traefik codebase so i added the router merger when traefik is merging its config.

**Comment by majkrzak** [comment]
IMO there should be possibility to setup default base, so it wouldn't be required to pass it explicitly.

**Comment by codestation** [comment]
@majkrzak i agree, maybe something like

```yml
global:
  defaultRouter: some-router@docker
```

Or...

```yml
defaults:
  router:  some-router@docker
```

And would need something to disable it per route:

    traefik.http.routers.myroute.ignoreBase=true

I would have to check where i could add an additional key to the config file/cli.

**Comment by ldez** [comment]
FYI, we are working on something about that.

**Comment by yiwork** [comment]
Just to be clear, you guys *are* working on a method by which we can apply a set of common router configs as defaults that can be inherited by other routers?  Or are you guys actually going to restore feature of `default router` back into v2?

**Comment by ldez** [comment]
We are working on something related to the purpose of this issue.

**Comment by majkrzak** [comment]
@ldez are you serious? It was default in traefik 1

**Comment by AndrewSav** [comment]
@majkrzak, [this page](https://docs.traefik.io/v1.7/basics/) outlines how 1.7 was put together, since it did not have a concept of a _router_ three was no _default router_ either, since it is not possible to restore it, because it never existed. Hope, that makes sense.

What you probably mean is that you like the old model (entrypoint / backends / forntends) better and that's fair. It's just the old concepts do not translate one to one to traefil v2, for better or worse, so there is that.

**Comment by majkrzak** [comment]
There was no default router named default router, but by default it was routing without necessity of specifying tones of annotation in kubernetes ingress configuration. v2 breaks this concept entirely.

**Comment by ldez** [comment]
The only default configuration was the entry points, nothing else.

Maybe your speaking about configuration **on** entry points (it's neither a default configuration nor a default "router" configuration).
In v1 the entry points are are only for HTTP (no TCP, no UDP), but in v2 the entry points are now protocol neutral, so every HTTP options was been moved to middleware.

This issue is a proposal: a place to have **constructive discussion**.

I recommend to you to change the way that you interact: https://github.com/containous/traefik/blob/master/CODE_OF_CONDUCT.md

**Comment by dimm0** [comment]
Constructive proposal: could somebody from traefik team add an example to official documentation how to redirect by default all http requests to https in kubernetes ingress, and use a default cert for https?

**Comment by ldez** [comment]
It's a bit off topic but it's a constructive proposal.

First, I will add a documentation about global redirection. (a PR is coming soon)

We still recommend to use IngressRoute instead of Ingress, but if you want to use Ingress:
- you have to use the file provider to create the global redirection as explained [here](https://community.containo.us/t/global-http-to-https-redirect-in-v2/1658/3?u=ldez)

The work that we are doing to address this issue will allow you a simpler configuration in the future (without the file provider).

FYI we added Ingress annotations support in the next release (v2.2) https://github.com/containous/traefik/pull/6160

So, now, if it's possible, could we use this issue to speak about the root meaning of this topic, thanks.

**Comment by bradjones1** [comment]
@dimm0 FWIW we are running an nginx container in the traefik pod to handle HTTP before it hits Traefik; the config below for instance forwards through only ACME challenges to Traefik which is listening on 8080 (for cert-manager) and redirects the rest.

```
server {
    listen 80 default_server;

    server_name _;

    location "/.well-known/acme-challenge/" {
        proxy_pass http://localhost:8080;
    }

    location "/" {
        return 301 https://$host$request_uri;
    }
}
```

**Comment by dimm0** [comment]
Omg.. Thanks, but then it's easier to simply use nginx?

**Comment by bradjones1** [comment]
@dimm0 I mean, maybe? Depending on your use case. There are a ton of different ingress controllers. Traefik still has some compelling use cases and features, but if it's not a fit, sure use either of the nginx ones :-)

**Comment by hamiltont** [comment]
@ldez Regarding: 

> First, I will add a documentation about global redirection

Thanks!! Could I recommend you mention/add an explicit priority label for this pattern? E.g. adding `   traefik.http.routers.http-catchall.priority=1` allows a simple 'override' for the global redirect. This allows you to auto-redirect for all routers listening for TLS, without forcing 100% of your routers to listen for TLS. Any other router rule listening on HTTP will have a higher prio than 1 and will get the request before the redirect happens. 

Would also be wise to point out that pattern will break 404s if there is no matching router (e.g. if there is no router matching the request, then `curl foobar.yourdomain.com` will get an SSL error not a 404). If there is a matching router, you get 404s as expected.

**Comment by fatihyildizhan** [comment]
Hi, I want to handle and secure www too like this but this shows 404 not found page. Do you have any advice for Traefik v2.1.4?

"traefik.http.routers.web.rule=Host(domain.com) || Host(www.domain.com)"
"traefik.http.routers.web-secure.rule=Host(domain.com) || Host(www.domain.com)"

**Comment by ldez** [comment]
Hey,

We would like to share our implementation proposals.

<details>
<summary><strong>A</strong> the redirection definition on entry points</summary>

```yml
## Static configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          https: true

  websecure:
    address: ":443"
```

</details>

<details>
<summary><strong>B</strong> the default router configuration</summary>

```yml
## Static configuration
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      middlewares: # default middlewares
        - foobar
        - foobar
      tls:  # default TLS configuration
        options: foobar
        certResolver: foobar
        domains:
          - main: foo
            sans:
              - foo
              - foo
          - main: bar
            sans:
              - bar
              - bar
```

</details>

<details>
<summary><strong>C</strong> the model/kind/default/template for routers</summary>

```yml
# Dynamic configuration.
# We used File provider only the demo (it can be available on all providers)
http:
  kinds:
    kind0:
      router:
        entryPoints:
          mergePolicy: force
          value:
            - foobar
            - foobar
        middlewares:
          mergePolicy: force
          value:
            - foobar
            - foobar
        priority:
          mergePolicy: force
          value: 42
        tls:
          mergePolicy: force
          value: true
          options:
            mergePolicy: force
            value: foobar
          certResolver:
            mergePolicy: force
            value: foobar
          domains:
            mergePolicy: force
            values:
              - main: foo
                sans:
                  - foo
                  - foo
              - main: bar
                sans:
                  - bar
                  - bar
```

</details>

The A and B part will be implementation soon.

for C, we still have to think about, and we need your feedback.

**Comment by dimm0** [comment]
Is that for CRD?
How would it look in Ingress object?

**Comment by AndrewSav** [comment]
@dimm0 what "that"? A and B above is static configuration, CRD is dynamic so no relation here. For "C" Ludovic says "it can be available on all providers" so there is a hope for CRD. As I understand that will be based on the feedback that is requested above.

**Comment by dimm0** [comment]
Ah, ok
I wasn't sure which one is a static config and which one is defined in the CRD

**Comment by AndrewSav** [comment]
@ldez  My question is: is it possible to configure redirection to a url rather than to a entry point? 

How does redirection interact with entrypoints, where the entrypoint address is not just the port, but also host name?

**Comment by ldez** [comment]
>  My question is: is it possible to configure redirection to a url rather than to a entry point?

for the moment, this is not possible due to certain technical constraints but I hope to find a solution in the future.

> How does redirection interact with entrypoints, where the entrypoint address is not just the port, but also host name?

behind the scene of this new configuration there is a redirectSheme so only the port will be used, it's mainly the same behavior as Traefik v1.

**Comment by redge76** [comment]
I would also like to be able to override the default list of middleware. On my 40 containers, only one needs a specific list of middlewares.

We need the same rule as with the TLS:
"If the middleware section is user-defined, then the default configuration does not apply."

We could have some directive to specify that some midleware in not "overridable"
for example this line in an entrypoint section:
`middlewares = ["+enforce-security-headers@file","auth@file", "strip@file"]`
means that even if the middleware list is redefined in a container, the "enforce-security-headers@file" middleware is still prepended to the list of middlewares of each router associated to the named entry point.

**Comment by Xav-Pe** [comment]
I'd like to also override a default middleware. I have a middleware attached to my https entrypoint, but some websites don't work because of the ``x-frame-options: deny``. Without a default middleware override, I need to use a different entrypoint.

```yaml
http: 
  middlewares:
    middleware-secure:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        #HSTS
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        forceSTSHeader: true
```

**Comment by enys** [comment]
> I'd like to also override a default middleware. I have a middleware attached to my https entrypoint, but some websites don't work because of the `x-frame-options: deny`. Without a default middleware override with docker labels, I need to use a different entrypoint.
> 
> ```yaml
> http: 
>   middlewares:
>     middleware-secure:
>       headers:
>         frameDeny: true
>         sslRedirect: true
>         browserXssFilter: true
>         contentTypeNosniff: true
>         #HSTS
>         stsIncludeSubdomains: true
>         stsPreload: true
>         stsSeconds: 31536000
>         forceSTSHeader: true
> ```

Did anyone find a workaround for this one ?

**Comment by aronmgv** [comment]
> I'd like to also override a default middleware. I have a middleware attached to my https entrypoint, but some websites don't work because of the `x-frame-options: deny`. Without a default middleware override with docker labels, I need to use a different entrypoint.
> 
> ```yaml
> http: 
>   middlewares:
>     middleware-secure:
>       headers:
>         frameDeny: true
>         sslRedirect: true
>         browserXssFilter: true
>         contentTypeNosniff: true
>         #HSTS
>         stsIncludeSubdomains: true
>         stsPreload: true
>         stsSeconds: 31536000
>         forceSTSHeader: true
> ```

I am curious as well! Can someone tell if this is on a way to be implemented? My case is that I have attached to the default entry-point sitting on port 443 security headers to block indexing.. However I would like couple sites to be indexed. It would make sense to create another shared middleware which will be overwriting the default settings attached to the 443 entrypoint..

traefik.yml:
```yml
entryPoints:
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: default
        domains:
          - main: example.com
      middlewares:
        - private-headers@file
```

shared middlewares:
```yml
    ### SECURITY
    private-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: false
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: same-origin
        permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        customResponseHeaders:
          X-Robots-Tag: "none,noindex,nofollow,noarchive,nosnippet,notranslate,noimageindex"
          server: ""

    ### PUBLIC SITES
    public-headers:
      headers:
        permissionsPolicy: "all"
        customResponseHeaders:
          X-Robots-Tag: "all"
          server: ""
```

So entrypoint is using `private-headers` but let them be overwritten in the router via other middleware `public-headers`:
```yml
http:

  routers:
    forum.example.com:
      entryPoints:
        - websecure
      rule: Host(`forum.example.com`)
      service: forum.example.com
      middlewares:
        - public-headers

  services:
    forum.example.com:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://192.168.255.11:59111'
```

Current result is as follows:

![image](https://user-images.githubusercontent.com/6546231/205283331-38eb082b-3065-4db5-90b1-2114871f5336.png)

![image](https://user-images.githubusercontent.com/6546231/205282754-584378c0-0e99-4f4d-a3ab-25d49588f758.png)

You can see that it is not overwriting even if the public headers are listed as second.. Thanks.
