### ISSUE TITLE
 unmarshal errors:\n  line 11: cannot unmarshal !!map into []dynamic.TCPServer

### ISSUE THREAD

**Issue by Leon99** [containous/traefik#5634]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Ran Traefik with the configuration below
### What did you expect to see?
1 TCP router/service configured

### What did you see instead?
0 TCP router/service set up, error in the log

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:10:11Z
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
traefik.yml:
```yml
providers:
  file:
    directory: .
    watch: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ':80'
  web-secure:
    address: ':443'
  ping:
    address: ':8082'

ping:
  entryPoint: 'ping'

api:
  dashboard: true
  insecure: true
```
my-service.yml:
```yml
tcp:
  routers:
    Broking:
      rule: "HostSNI(`my-service.local`)"
      service: "MyService"

  services:
    MyService:
      loadBalancer:
        servers:
          address: "127.0.0.1:44327"
      tls:
        passthrough: true
```

Running on Windows 10 v1903 w/all updates

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-10-11T15:59:07+11:00" level=info msg="Configuration loaded from file: C:\\Repos\\DevTools\\traefik\\traefik.yml"
time="2019-10-11T15:59:07+11:00" level=info msg="Traefik version 2.0.2 built on 2019-10-09T19:10:11Z"
time="2019-10-11T15:59:07+11:00" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"ping\":{\"address\":\":8082\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"web-secure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"file\":{\"directory\":\".\",\"watch\":true}},\"api\":{\"insecure\":true,\"dashboard\":true},\"ping\":{\"entryPoint\":\"ping\"},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2019-10-11T15:59:07+11:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2019-10-11T15:59:07+11:00" level=debug msg="No default certificate, generating one"
time="2019-10-11T15:59:07+11:00" level=debug msg="Start TCP Server" entryPointName=web
time="2019-10-11T15:59:07+11:00" level=debug msg="Start TCP Server" entryPointName=web-secure
time="2019-10-11T15:59:07+11:00" level=debug msg="Start TCP Server" entryPointName=ping
time="2019-10-11T15:59:07+11:00" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-10-11T15:59:07+11:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-10-11T15:59:07+11:00" level=info msg="Starting provider *file.Provider {\"directory\":\".\",\"watch\":true}"
time="2019-10-11T15:59:07+11:00" level=error msg="Cannot start the provider *file.Provider: yaml: unmarshal errors:\n  line 11: cannot unmarshal !!map into []dynamic.TCPServer"
```

**Comment by ldez** [comment]
Hello,

your yaml file `my-service.yml` is invalid:
- the `tls` section must be on the `router` and not on the `service`
- the `servers` is a list

```yaml
tcp:
  routers:
    Broking:
      rule: "HostSNI(`my-service.local`)"
      service: "MyService"
      tls:
        passthrough: true

  services:
    MyService:
      loadBalancer:
        servers:
          - address: "127.0.0.1:44327"
```

https://docs.traefik.io/reference/dynamic-configuration/file/

Please join us on https://community.containo.us/ if you have more questions.
