### ISSUE TITLE
Traefik keeping DNS cache forever

### ISSUE THREAD

**Issue by danperry72** [containous/traefik#5638]
Hi,
I'm running Traefik as a loadbalancer into my kubernetes cluster, and for some reason, the traefik instances appear to cache the DNS records at the time of boot up. This is fine except sometimes I have to redeploy my kubernetes clusters and they come up with the same hostname but different IPs, leaving Traefik sending traffic to the wrong IP as it has previously cached it.

Looking at the source code i can see that there are some hardcoded values for how long this is supposed to be cached for, however I've cloned, rebuilt and redeployed the traefik binary with a shorter cache and it seems to ignore the values I am setting and is insistent on using the old IP even when left overnight to refresh.

My test is as follows:
- Have an endpoint with DNS of long-k8ma-l001.domain.co.uk -> 10.9.10.11
- Start Traefik, it caches that DNS mapping, and routing works fine.
- Redeploy the VM in question with a new IP of 10.9.10.12
- Send traffic to Traefik which continues to resolve long-k8ma-l001.domain.co.uk -> 10.9.10.11 resulting in a connection refused.
- Restart Traefik, it updates to the new DNS mapping and routing now works fine

Now, a lot of this deployment is automated and I would rather not have to restart my Traefik instances anytime a VM is moved or redeployed.
Apart from the fact that the cache seems to last forever, surely the cache duration should be configurable? It appears to be hardcoded to 30 minutes which seems like a very very long time for rapid deployment environments these days.

Here is the dynamic config
```
http:
  routers:
    {{ENV}}-http:
      rule: "HostRegexp(`{subdomain:.+}.{{ENV}}.domain.co.uk`)"
      entrypoints: ["web"]
      service: {{ENV}}-http

  services:
    {{ENV}}-http:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30000"
        - url: "http://long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30000"

tcp:
  routers:
    {{ENV}}-kubemaster:
      service: {{ENV}}-kubemaster
      rule: "HostSNI(`kubemaster.{{ENV}}.domain.co.uk`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    {{ENV}}-https:
      service: {{ENV}}-https
      rule: "HostSNI(`*`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    
  services:
    {{ENV}}-https:
      loadBalancer:
        passHostHeader: true
        servers:
        - address: "long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30443"
        - address: "long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30443"
    {{ENV}}-kubemaster:
      loadBalancer:
        passHostHeader: true
        servers:
{% for j in range(1, NUMBER_OF_K8_MASTERS) %}
        - address: "long-k8ma-{{ENV_LETTER}}00{{j}}.domain.co.uk:6443"
{% endfor %}
```

Here is the static config
```
accessLog: {}
api: {}
entryPoints:
  tcp:
    address: :8000
  web:
    address: :80
  websecure:
    address: :443
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: DEBUG
ping: {}
providers:
  file:
    directory: /etc/traefik/config
    watch: true
tracing: {}
```
