### ISSUE TITLE
Traefik/Consul catalog/Rancher labels problem

### ISSUE THREAD

**Issue by cabrinoob** [containous/traefik#564]
Hi,
I'd like to test Traefik with a Consul Catalog backend. I'am using Rancher to deploy my containers. On each node I have a consul agent and registrator which (de)registers every (dis)appearing containers.

For the test I deployed a Traefic container as explained in the documentation with this traefik.toml config : 

```toml
[web]
address = ":8080"

[consulCatalog]
endpoint = "172.18.2.88:8500"
prefix = "traefik"
```

Then, in Rancher, I deployed a `whoami` container (not yours, but `jwilder/whoami` which is almost the same) with these labels (See the fellowing screenshot) : 

![rancher](https://cloud.githubusercontent.com/assets/5182775/17212014/d98b3656-54cc-11e6-9ae3-d0a83a64d452.png)

My problem is that it seems that these labels are not taken in account. If I take a look to the Traefik GUI it seems that it is the default rule that is applied (See the next capture) :

![rule](https://cloud.githubusercontent.com/assets/5182775/17212190/0bd06d9c-54ce-11e6-82c8-b0cd57a93d3b.png)

As you can see the Host is set to `whoami.` instead of `whoami.docker.localhost`.

I have certainly missed something, because I do not understand how registrator could do to insert those labels in consul.

I'am not sure that it is the right place to post this kind of question but, thank you for your help.

**Comment by emilevauge** [comment]
Hi @cabrinoob, you need to add a `domain` parameter in the [TOML file](http://docs.traefik.io/toml/#consul-catalog-backend):
```
[consulCatalog]
endpoint = "172.18.2.88:8500"
prefix = "traefik"
domain = "mydomain.com"
```

Your host will then ba accessible using `whoami.mydomain.com`

**Comment by cabrinoob** [comment]
Ok, thank you but it does not solve my problem. Perhaps it means that labels are not considered with consul.

Because if I set these labels on my container : 

SERVICE_NAME = MoteurV3 (this one is for registrator)
traefik.frontend.rule	 = Host:mv3
traefik.backend = mv3-backend

I expect to have the rule Host:mv3.mydomain.com in the traefic UI but instead I have Host:moteurv3.mydomain.com

My frontendrule "mv3" has'nt been used here. And it's the same for the backend name, I expect to have a backend like "mv3-backend", but instead I have the default name "backend-moteurv3".

It seems that it misses something between registrator and consul to tell registrator to use the traefik labels in a proper way.

**Comment by jmahowald** [comment]
Just checking in, as I was about to try to do this myself.  So if you have any updates, please let me know. And I'll do the same.

**Comment by jmahowald** [comment]
Actually, and I don't really know because I haven't done anything yet, but I don't think the labels would matter if traefik was using consul as a backend, only when docker is a backend.   Now, how to configure it to do the equivalent in consul, I have no idea.

**Comment by keis** [comment]
How does the services look like in consul? Consul does not support labels but only tags (key and no value) so you need to make sure whatever registers your services mangles the labels correctly. traefik excepts to find tags like "traefik.foo=bar"

**Comment by jmahowald** [comment]
Traefik expects to find tags like that I think with some of the backends.  With consul catalog, it was able to find the services out of the box.  In registrator you can specify labels as well, and in those case you can attach the additional tags, but there is no need if you want something simple.


```
version: '2'
# For some reason, I can't get traefik to
# work with links, so I'm setting an explicit ip on consul
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
services:
  consul:
    # network_mode: bridge
    image: progrium/consul
    ports:
      - "8500:8500"
    command: -server -bootstrap -ui-dir /ui
    networks:
       default:
          ipv4_address: "172.16.238.10"
  registrator:
    depends_on:
      - consul
    network_mode: host
    image: gliderlabs/registrator:latest
    # If we don't use inernal, it uses the exposed ports
    # on the host, and traefik won't be able to get to those
    command: -internal consul://localhost:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  whoami1:
    depends_on:
      - registrator
    image: emilevauge/whoami
    labels:
      SERVICE_NAME: whoami
  whoami2:
    depends_on:
      - registrator
    image: emilevauge/whoami
    labels:
      SERVICE_NAME: iamyou
      SERVICE_TAGS: traefik.backend.weight=10
  traefik:
    depends_on:
      - registrator
    ports:
      - "8080:8080"
      - "8090:8090"
      - "8888:80"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
    image: mytraefik

```


And then in traefik.toml

```
logLevel = "DEBUG"
[consulCatalog]
endpoint = "172.16.238.10:8500"
prefix = "traefik"
domain = "mydomain.com"
watch = true
```

With that you could test like:

```
curl -H Host:iamyou.mydomain.com  http://127.0.0.1:8888
Hostname: f61f7a4eff8b
IP: 127.0.0.1
IP: ::1
IP: 172.16.238.3
```
