### ISSUE TITLE
ForwardAuth Headers are not the same on V2 as there were on V1.7.x

### ISSUE THREAD

**Issue by SeaLife** [containous/traefik#5648]
Bug

### What did you do?

I've created a Middleware for forwardAuth 

```yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authy.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.authy.entrypoints=https"
      - "traefik.http.routers.authy.tls"
      - "traefik.http.routers.authy.tls.certresolver=letsencrypt"

      - "traefik.http.middlewares.authy.forwardauth.address=https://auth.example.com/auth"
      - "traefik.http.middlewares.authy.forwardauth.trustForwardHeader=true"
```

### What did you expect to see?

I tested the same on v1.7.x and expected to see the following output (`x-`' Headers):

```json
{
   "host":"authy.example.com",
   "user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0",
   "accept":"image/webp,*/*",
   "accept-encoding":"gzip, deflate, br",
   "accept-language":"de,en-US;q=0.7,en;q=0.3",
   "cookie":"CASTGC=xxxxxxx",
   "x-forwarded-for":"x.x.x.x.x, 172.23.0.1",
   "x-forwarded-host":"countdown.example.com", -- THE ACTUAL ADDRESS OF THE CALLED SERVICE, NOT THE MIDDLEWARE!!!,
   "x-forwarded-method":"GET",
   "x-forwarded-port":"443",
   "x-forwarded-proto":"https",
   "x-forwarded-server":"f8d9c2ea6e51",
   "x-forwarded-uri":"/clock0.png",
   "x-real-ip":"172.23.0.1"
}
```

### What did you see instead?

I've expected to get the Headers 'x-forwarded-for', 'x-forwarded-host', ... in the same matter as in version 1.7.x

But i got the following:

```log
authy_1  | { host: 'auth.example.com',
authy_1  |   'user-agent':
authy_1  |    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0',
authy_1  |   accept:
authy_1  |    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
authy_1  |   'accept-encoding': 'gzip, deflate, br',
authy_1  |   'accept-language': 'de,en-US;q=0.7,en;q=0.3',
authy_1  |   cookie:
authy_1  |    'connect.sid=xxxxx',
authy_1  |   'upgrade-insecure-requests': '1',
authy_1  |   'x-forwarded-for': '172.18.0.1',
authy_1  |   'x-forwarded-host': 'auth.example.com',
authy_1  |   'x-forwarded-port': '443',
authy_1  |   'x-forwarded-proto': 'https',
authy_1  |   'x-forwarded-server': 'traefik.example.com',
authy_1  |   'x-real-ip': '172.18.0.1' }
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Service Docker-Compose (Middleware)
```yml
version: '3'
services:
  authy:
    image: xxxx (private, internal image, consuming these X- headers)
    volumes:
      - "/srv/docker/auth-server:/data"
      - "/etc/localtime:/etc/localtime:ro"
    hostname: auth.example.com
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authy.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.authy.entrypoints=https"
      - "traefik.http.routers.authy.tls"
      - "traefik.http.routers.authy.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.authy.middlewares=authy"

      - "traefik.http.middlewares.authy.forwardauth.address=https://auth.example.com/auth"
      - "traefik.http.middlewares.authy.forwardauth.trustForwardHeader=true"
    networks:
      - web
    environment:
      COOKIE_DOMAIN: example.com
      COOKIE_SECRET: xxxxx
      JWT_SECRET: xxxxx


networks:
  web:
    external: true
```

Traefik Compose:
```yml
version: '3.7'
services:
  traefik:
    image: traefik:v2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.dashboard.middlewares=authy"

      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.routers.https-redirect.service=dummy"
      - "traefik.http.routers.https-redirect.entrypoints=http"

      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.dummy.loadbalancer.server.url=:999"
    ports:
      - xx.xx.xx.xx:80:80
      - xx.xx.xx.xx:443:443
    networks:
      - web
    volumes:
      - "/srv/docker/traefikv2/acme:/etc/traefik/acme"
      - "/var/log/traefik_4xx:/var/log/access.log"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    hostname: traefik.example.com
    restart: unless-stopped
    env_file:
      - configuration.env
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 1m

networks:
  web:
    external:
      name: web
```

Traefik .env File
```env
TRAEFIK_ACCESSLOG=true

TRAEFIK_ACCESSLOG_FILEPATH=/var/log/access.log

TRAEFIK_API=true
#TRAEFIK_API_INSECURE=true
TRAEFIK_PING=true

#TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=ssl-expiry@example.com
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE=true
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT=http
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE=/etc/traefik/acme/acme.json
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE=false

TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS=:443

TRAEFIK_LOG_LEVEL=DEBUG

TRAEFIK_PROVIDERS_DOCKER=true
TRAEFIK_PROVIDERS_DOCKER_NETWORK=web
TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
```

PHPMyAdmin Docker Compose (using the Middleware)
```yml
version: '3.7'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.example.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=https"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.phpmyadmin.middlewares=authy"

      - "traefik.phpmyadmin.enable=true"
      - "traefik.phpmyadmin.frontend.rule=Host:phpmyadmin.example.com"
      - "traefik.phpmyadmin.port=80"
    networks:
      - web
      - db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    hostname: phpmyadmin.example.com
    restart: unless-stopped
    environment:
      - "PMA_HOST=db.example.com"
    healthcheck:
      test: curl -fs -w "%{http_code}" http://localhost:80 -o /dev/null > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5m
```

**Comment by dduportal** [comment]
Hi @SeaLife , thanks for your interest in the project and your report.

You are right, with 2.0 version of Traefik, the default behavior for trusting headers at entrypoints level had been changed.

Can you try to enable the "insecure" mode on the `forwardedHeaders` section for entrypoints (documentation reference: <https://docs.traefik.io/routing/entrypoints/#forwarded-header>) and let us know if the adapted behavior is what you expect?

**Comment by SeaLife** [comment]
Hey,

i got no issues with the Headers it self, its the content which differs between the two version.

In version 1.7.x you get the called service's host in the `x-forwarded-host`-Header, in 2.0 you get the host of the middleware.

So in 1.7.x the `x-forwarded-host` could something be like `my-service.my-domain.tld` when requesting the ForwardAuth "middleware"...

In 2.0 you get the hostname of the middleware instead of the accessed application, so `x-forwarded-host` equals to the hostname of the middleware.

I also tried the following: `traefik.http.middlewares.authy.forwardauth.trustForwardHeader=true` without any help.

Regards

**Comment by ldez** [comment]
In v1.7, forwarded-header on entrypoint is insecure by default: https://docs.traefik.io/v1.7/configuration/entrypoints/#forwarded-header

In v2.0, forwarded-header on entrypoint is secure by default: https://docs.traefik.io/routing/entrypoints/#forwarded-header

**Comment by SeaLife** [comment]
Hey,

So we tried the same with

```
TREAFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_INSECURE=true
```

But nothing changed

**Comment by dduportal** [comment]
Hi @SeaLife , to help us investigate further this issue, could you provide the logs of Traefik, in debug mode (ref. https://docs.traefik.io/v2.0/observability/logs/#level), from the initial startup to after you reproduced the error please?

**Comment by SeaLife** [comment]
I dont see why this is neccessary but here you go...
http://ix.io/1YPS

There are alot of other containers i cant just stop so i hope you can work your way through there.
Could not test this locally cuz you need a external domain name called by traefik as a forward-auth address.

I started traefik, opened the secured app and stopped traefik.


Regards
SeaLife

**Comment by dduportal** [comment]
Hi @SeaLife , thanks for the complete feedback! 

At first read, the logs indicates that there is no entrypoints named `HTTPS`:

```text
...
level=error msg="entryPoint \"https\" doesn't exist" entryPointName=https routerName=deployment-api@docker
...
```

I don't know the root cause (is it a configuration issue? Is it a bug in Traefik? In docker-compose? Something else) yet.

Also the log line defining what static configuration Traefik got from the environment variable does not mention any `forwardedHeader` even though you specified it, which explains the difference between the behavior you see (no header forwarded) and the one you want.

I also noticed that the environment variable you provided is `TREAFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_INSECURE`, while it should be `TRAEFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_INSECURE`.

Can you double-check and provide a full configuration summary? In the same time, I'll try to reproduce the behavior using environment variables configuration as you do.

**Comment by dduportal** [comment]
I confirm that the behavior on my side is different:

* `docker-compose.yml`:

```yml
version: '3.7'
services:
  traefik:
    image: traefik:v2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.dashboard.middlewares=authy"

      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.routers.https-redirect.service=dummy"
      - "traefik.http.routers.https-redirect.entrypoints=http"

      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.dummy.loadbalancer.server.url=:999"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    hostname: traefik.example.com
    restart: unless-stopped
    env_file:
      - configuration.env
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 1m
```

* `configuration.env`:

```text
TRAEFIK_ACCESSLOG=true

TRAEFIK_ACCESSLOG_FILEPATH=/var/log/access.log

TRAEFIK_API=true
#TRAEFIK_API_INSECURE=true
TRAEFIK_PING=true

#TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=ssl-expiry@example.com
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE=true
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT=http
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE=/etc/traefik/acme/acme.json
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE=false

TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS=:443
TRAEFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_INSECURE=true

TRAEFIK_LOG_LEVEL=DEBUG

TRAEFIK_PROVIDERS_DOCKER=true
TRAEFIK_PROVIDERS_DOCKER_NETWORK=web
TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
```

When I run `docker-compose up`, I got the following log line:

```text
traefik_1  | time="2019-10-16T13:22:00Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{\"insecure\":true}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"web\",\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"dashboard\":true},\"ping\":{\"entryPoint\":\"traefik\"},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"/var/log/access.log\",\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}},\"certificatesResolvers\":{\"letsencrypt\":{\"acme\":{\"email\":\"ssl-expiry@example.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/etc/traefik/acme/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"http\"}}}}}"
```

=> where the HTTPS entrypoint is created + the insecure mode is enabled on this entrypoint for the forwarded headers.


=> Please note that, if I use exactly the environment variable `TREAFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_INSECURE=true` (with the typo), then the entrypoint HTTPS   is not created, which looks like the behavior you see.

Can you check and fix it, and try again if you initial problem with headers on the auth server are ok?
