### ISSUE TITLE
Traefik v2 routes to wrong Ip, service in 2 networks

### ISSUE THREAD

**Issue by StiviiK** [containous/traefik#5657]
# Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I'm trying to using Traefik as reverse-proxy for [mailcow](https://github.com/mailcow/mailcow-dockerized). I am using their provided [docker-compose](https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml) but replaced following sections:
```yaml
 nginx-mailcow:
     ...
    #ports:
    #  - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
    #  - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
  labels:
    # Docker
    - traefik.enable=true

    # Routing
    - traefik.http.routers.mail.rule=Host(`mail.domain.tld`)
    - traefik.http.routers.mail.tls.certresolver=letsencrypt
    - traefik.http.routers.mail.tls.domains[0].main=*.domain.tld
    - traefik.http.routers.mail.tls.domains[0].sans=domain.tld
    - traefik.http.routers.mail.entrypoints=websecure
    - traefik.http.services.mail.loadBalancer.server.port=${HTTP_PORT:-80}
  restart: always
  networks:
    traefik:
    mailcow-network:
      aliases:
        - nginx
```
```yaml
networks:
  traefik:
    external: true
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mailcow
    enable_ipv6: true
    ipam:
      driver: default
    config:
      - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
      - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
```

Network configuration:
```
IP address for br-40c14096263c: 192.168.240.1
IP address for br-mailcow:      172.22.1.1 
24d2ede76dd6        none                                null                local
40c14096263c        traefik                             bridge              local  
```

### What did you expect to see?
That traefik routes to the ip of the container in the `traefik`-network subnet -> `192.168.240.*`

### What did you see instead?
Traefik routes to the ip of the container in the `br-mailcow`-network subnet -> `172.22.1.*`

### Output of `traefik version`:
```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
 traefik:
  image: traefik:latest
  container_name: traefik
  networks:
    - traefik
  command:
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    - --certificatesresolvers.letsencrypt.acme.email=...
    - --certificatesresolvers.letsencrypt.acme.storage=/var/app/acme.json
    # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=azure
    - --api
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./users.htpasswd:/var/app/users.htpasswd:ro
    - ./acme.json:/var/app/acme.json
  ports:
    - 80:80
    - 443:443
  environment:
    - AZURE_CLIENT_ID=...
    - AZURE_CLIENT_SECRET=...
    - AZURE_SUBSCRIPTION_ID=...
    - AZURE_TENANT_ID=...
    - AZURE_RESOURCE_GROUP=...
  labels:
    # Docker
    - traefik.enable=true
    
    ...
  restart: always  
```
```yaml
networks:
  traefik:
    external: true 
```
