### ISSUE TITLE
Can't connect to hostname via HTTP within Docker container

### ISSUE THREAD

**Issue by MartinMuzatko** [containous/traefik#5668]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am running both a Jenkins CD server and an app store service on the same VServer using traefik to route. My goal was to push a finished version information to our own app store to notify customers of a release. I discovered the problem, when I wanted to POST the info via HTTP to a subdomain of the server, which ended in a timeout.

I was able to reproduce with e.g. curl, but not in jenkins but any docker service!
So even from a fresh container that is not routed by traefik, I cannot connect to my server.

Outside the containers on the VPS ( I am running a bare bones ubuntu on netcup ), on my local machine or any other VPS, I can connect to the same server.

There is no firewall or other settings. docker daemon is default settings.

```
root@v22017054610049128:~/test# docker run -it node bash                                               
root@4e3da15e9a8b:/# curl https://exa.sicon.io 
curl: (7) Failed to connect to exa.sicon.io port 443: Connection timed out 
```

### What did you expect to see?

```
root@v22017054610049128:~/test# curl https://exa.sicon.io                                              
404 page not found 
```

Since I have nothing running on /, but only subdomains for the services.

### What did you see instead?

`curl: (7) Failed to connect to exa.sicon.io port 443: Connection timed out `

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.18 
Codename:     maroilles
Go version:   go1.12.10
Built:        2019-09-26_01:56:30PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

################################################################
# Entrypoints configuration
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.redirect]
      regex = "^https*://version.exa.sicon.io/(.*)"
      replacement = "https://appserver.gps-stuttgart.de/bitbucket/rest/api/1.0/$1"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/fullchain.pem"
      keyFile = "/privkey.pem"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

# Enable ping
[ping]

# Enable Docker configuration backend
[docker]
  [docker.tls]
  cert = "/fullchain.pem"
  key = "/privkey.pem"
  insecureSkipVerify = true


domain = "exa.sicon.io"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
```
