### ISSUE TITLE
memory leak with big acme.json

### ISSUE THREAD

**Issue by spunti** [containous/traefik#5670]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Configuring a "catchall" frontend, which redirects to 127.0.0.1:81 on which an apache server is listening. Acme ondemand is activated, to issue a certificate for every domain which is requested. acme.json is really big (300MB) containing 35580 certificates. I also have pprof files ready, please let me know if I can just append them or if I should send them via a privat channel.

### What did you expect to see?
no memory leak

### What did you see instead?
memory leak/now after one hour after restarting traefik it already consums 24GB of memory

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.14
Codename:     maroilles
Go version:   go1.12.8
Built:        2019-08-14_09:46:58AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
running on a debian 9 VM
```toml
#debug = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
        minVersion = "VersionTLS12"
        cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
       ]

    [entryPoints.traefik]
     address = ":8080"
       [entryPoints.traefik.auth.basic]
         users = ["user:pw"]


[traefikLog]
filePath = "/var/log/traefik.log"
format = "json"

[accessLog]
filePath = "/var/log/traefik_access.log"
format = "common"

#[accessLog.fields]
#  [accessLog.fields.names]
#    "Duration" = "keep"

[api]
entryPoint = "traefik"
dashboard = true

[api.statistics]
  recentErrors = 50

[ping]

[acme]
email = "email"
storage = "/etc/traefik.d/acme/acme.json"
entryPoint = "https"
acmeLogging = true
onDemand = true

[acme.httpChallenge]
entryPoint = "http"

[file]

[backends]
  [backends.engine-redirect-service]
    [backends.engine-redirect-service.servers.server1]
        url = "http://127.0.0.1:81"
        weight = 1

[frontends]
  [frontends.catchall]
    backend = "engine-redirect-service"
    passHostHeader = true
        priority = 1
    [frontends.catchall.routes.route0]
        rule = "HostRegexp:{catchall:.*}"
  [frontends.catchall.ratelimit]
    extractorfunc = "client.ip"
      [frontends.catchall.ratelimit.rateset.rateset1]
        period = "60s"
        average = 30
        burst = 60
      [frontends.catchall.ratelimit.rateset.rateset2]
        period = "10m"
        average = 300
        burst = 600
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
