### ISSUE TITLE
[v2] Weighted Round Robin for Docker swarm provider

### ISSUE THREAD

**Issue by ralmn** [containous/traefik#5673]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Currently with Traefik 1.7 we used the weighted round robin with docker swarm providers. But with the 2.0 version the WRR is only possible with file providers.

We use the WRR for a mechanism of zero downtime deployments for statefull application : deploy a new version without disconnect the users on old version (with deploying multiple stack).

This feature is required for our migration to traefik 2.0. 

Exemple of our mechanism : 

1. We have a swarm stack with `myApp` at version _1_ named `myAppV1` with one service `back`.
This service have this labels: 
```
- "traefik.enable=true"
- "traefik.backend.loadbalancer.stickiness=true"
- "traefik.backend.loadbalancer.stickiness.cookieName=myapp-back-traefik-sticky"
- "traefik.app.port=8080"
- "traefik.app.backend=myapp-back"
- "traefik.app.frontend.rule=Host:myapp.example.com"
- "traefik.app.frontend.entryPoints=http,https"
- "traefik.app.weight=1"
```
2. We deploying a new version of this app in stack `myAppV2` with same label of first version for the service `back`
3. We set the `traefik.app.weight` to `0` on the service `myAppV1_back`

So with this the current session continue to access to the V1 and the new ones access to the V2.

**Comment by ldez** [comment]
Hello,

We put the label `proposal` and not `enhancement`, because there are some major problems with this feature.

The goal of the proposal is to discuss about the feature.

**Comment by rdavaillaud** [comment]
Hello, 

@ldez what are those major problems you refer to?
Is there another method to do blue-green or zero downtime with docker or docker swarm and Traefik 2.x?

**Comment by ldez** [comment]
Hello,

> Is there another method to do blue-green or zero downtime with docker or docker swarm and Traefik 2.x?

you have to use the docker provider and the file provider to handle that.

**Comment by rdavaillaud** [comment]
Thanks, 

> you have to use the docker provider and the file provider to handle that

can you provide an full configuration example? I don't know how to do that.

**Comment by ldez** [comment]
https://docs.traefik.io/v2.1/routing/services/#weighted-round-robin-service

**Comment by davelowper** [comment]
I would need to use WRR for a service in a docker swarm cluster with different underlying server capabilities.
@ldez Can you please elaborate on how to combine docker provider and file provider to do this ? Or point me to relevant resources ?

The current (swarm) deploy configuration of my service looks like that:
```
deploy:
    mode: replicated
    replicas: 3
    labels:
      traefik.docker.network: traefik
      traefik.enable: 'true'

      traefik.http.services.mysvc.loadbalancer.server.port: '8069'
      traefik.http.services.mysvc.loadbalancer.sticky: 'true'
      traefik.http.services.mysvc.loadbalancer.sticky.cookie.name: sticky-mysvc
      traefik.http.services.mysvc.loadbalancer.sticky.cookie.secure: 'true'
      traefik.http.routers.mysvc.rule: (Host(`mysvc.mydomain.net`))  
      traefik.http.routers.mysvc.entrypoints: https
      traefik.http.routers.mysvc.middlewares: https_oauth@file
      traefik.http.routers.mysvc.service: mysvc
      traefik.http.routers.mysvc.tls: 'true'
      traefik.http.routers.mysvc.tls.certresolver: letsencrypt

      traefik.http.services.mysvcgraphql.loadbalancer.server.port: '8069'
      traefik.http.services.mysvcgraphql.loadbalancer.sticky: 'true'
      traefik.http.services.mysvcgraphql.loadbalancer.sticky.cookie.name: sticky-mysvc
      traefik.http.services.mysvcgraphql.loadbalancer.sticky.cookie.secure: 'true'
      traefik.http.routers.mysvcgraphql.rule: (Host(`mysvc.mydomain.net`) && ( PathPrefix(`/graphql`) || PathPrefix(`/web/image`) ))  
      traefik.http.routers.mysvcgraphql.entrypoints: https
      traefik.http.routers.mysvcgraphql.middlewares: https_default@file
      traefik.http.routers.mysvcgraphql.service: mysvc
      traefik.http.routers.mysvcgraphql.tls: 'true'
      traefik.http.routers.mysvcgraphql.tls.certresolver: letsencrypt

      traefik.http.services.mysvcchat.loadbalancer.server.port: '8072'
      traefik.http.services.mysvcchat.loadbalancer.sticky: 'true'
      traefik.http.services.mysvcchat.loadbalancer.sticky.cookie.name: sticky-mysvc
      traefik.http.services.mysvcchat.loadbalancer.sticky.cookie.secure: 'true'
      traefik.http.routers.mysvcchat.rule: (Host(`mysvc.mydomain.net`) && PathPrefix(`/longpolling`))  
      traefik.http.routers.mysvcchat.service: mysvcchat
      traefik.http.routers.mysvcchat.entrypoints: https
      traefik.http.routers.mysvcchat.tls: 'true'
      traefik.http.routers.mysvcchat.tls.certresolver: letsencrypt
```
It is deployed on worker 1 to 3, worker 1 being 4 times more powerfull than the 2 others

**Comment by evandam** [comment]
Hey folks,

New to Traefik here so could be way off, but curious if there were updates around this. I'm looking to use Traefik with the Consul Catalog provider and being able to specify things like weighted servers/services is an important features (compared to Fabio where it's trivially adding `weight=x` to your tags).

I had partial success with the file provider, but it's also easy to run into issues when a service no longer exists and the Traefik WRR service is no longer valid (ex: Canary gets promoted and there's only the live version remaining).

Ideally, being able to specify a weight per server instance would be great, but I understand if that's not how Traefik v2 is designed.

Would this be a reasonable proposal to have a WRR defined by tags rather than managing a file (would obviously need to change, but just the general idea):

```
traefik.wrr.enable=true
traefik.wrr.service=my-service-weighted
traefik.wrr.rule=PathPrefix(`/httpbin`)
traefik.wrr.middlewares=...
traefik.wrr.weight=10
```

Alternatively, I'm not sure if there could be a more elegant way to split traffic to either multiple servers or services through some new Router options, which intuitively makes a bit more sense to me at least.

**Comment by hozn** [comment]
Also interested in any workarounds (@ldez?) as similar to @evandam , we have a need for being able to add or scale down canary services dynamically in Docker Swarm.

If I'm reading things right, I suppose in the short-term we can apply a regular round robin without weighting between the canary and non-canary services, and just adjust number of services replicas to perform a crude weighting, but would be really nice to be able to fine-tune this in Traefik.

**Comment by evandam** [comment]
Just curious if any more thought has gone into this or if it's on any roadmap. Another thought I had for a workaround in the meantime would just be if the router/service for WRR wouldn't show an error if one of the upstreams does not exist or is unhealthy. Instead it would just route traffic to the other services available?

For example:

```yml
http:
  routers:
    httpbin-weighted:
      entryPoints: ["traefik"]
      service: httpbin-weighted
      rule: PathPrefix(`/`)
  services:
    httpbin-weighted:
      weighted:
        services:
          - name: httpbin-traefik@docker
            weight: 10
          - name: httpbin-canary-traefik@docker
            weight: 1
```

but if there is no canary running:

![Screen Shot 2021-08-23 at 11 42 09 AM](https://user-images.githubusercontent.com/3985383/130500555-5825fff8-27c9-4d2b-ba15-aeda0417e8f2.png)
