### ISSUE TITLE
Reaching containers in different docker networks

### ISSUE THREAD

**Issue by tbcdns** [containous/traefik#568]
Hi,

Consider the following basic example:

```yaml
---
version: '2'

services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  whoami1:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

  whoami2:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
```

I start my containers:

```bash
$ docker-compose up -d
docker-compose up -d
Creating testdock_traefik_1
Creating testdock_whoami2_1
Creating testdock_whoami1_1
```

I add a third "whoami" container directly with docker that I called whoami_out (out of docker-compose)

```bash
$ docker run -d --name whoami_out emilevauge/whoami
```
They are all registered in traefik web ui:
![image](https://cloud.githubusercontent.com/assets/1276068/17251840/9c318d58-55aa-11e6-9ec9-935c4cce7660.png)

However traefik works only for the ones started with docker-compose:

```bash
$ curl -H Host:whoami.docker.localhost http://127.0.0.1
Hostname: dea890067ec8
IP: 127.0.0.1
IP: ::1
IP: 172.19.0.3
IP: fe80::42:acff:fe13:3
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.43.0

Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.19.0.1
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Proto: http
X-Forwarded-Server: 8a52baca04f9
```

```bash
$ curl -H Host:whoami_out.docker.localhost http://127.0.0.1
Gateway Timeout
```

I understand that docker-compose creates its own network but is there a way to reach all containers?

Thanks for your help!
