### ISSUE TITLE
basicAuth middleware applying on route not specified

### ISSUE THREAD

**Issue by hwwilliams** [containous/traefik#5686]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Deployed two docker containers, one with basicAuth middleware and one without basicAuth middleware and but it was applied to both containers.

### What did you expect to see?

I expected the basicAuth middleware to only apply to the proxy-dashboard-https route I attached it to.

### What did you see instead?

I have found that when I deploy the two containers like this, going to status.domain.com will result in the same authentication prompt that proxy.domain.com has, even though the statping-https route doesn't have that middleware included. I think it has to do with the pathprefix rule because if I remove the '&& PathPrefix(`/dashboard/`) || PathPrefix(`/api`)' portion the basicAuth middleware is only pushed with the proxy-dashboard-https route and not the statping-https route.

For reference, the Statping container app that is forwarded to status.domain.com has both a /dashboard and an /api path.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

For the Traefik Docker image:
    docker run [IMAGE] version
    ex: docker run traefik version

-->

```
2.0.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I use Traefik CLI with docker command option to apply the Traefik configuration
```
      - "--log=true"
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=external"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.filename=/etc/traefik/file.yaml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leCloudflareDns.acme.dnschallenge=true"
      - "--certificatesresolvers.leCloudflareDns.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.leCloudflareDns.acme.dnschallenge.delayBeforeCheck=25"
      - "--certificatesresolvers.leCloudflareDns.acme.email=admin@domain.com"
      - "--certificatesresolvers.leCloudflareDns.acme.storage=/etc/traefik/acme.json"
```

Middlewares defined in /etc/traefik/file.yaml
```yaml
---
http:
  middlewares:
    compress-content-security:
      chain:
        middlewares:
          - "compression"
          - "content-security"

    auth-basic-proxy:
      basicAuth:
        removeHeader: true
        users:
          - "username:encrypted_password"

    compression:
      compress: {}

    content-security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        sslRedirect: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true

    redirect-https:
      redirectScheme:
        scheme: "https"
        permanent: true

tls:
  options:
    default:
      minVersion: "VersionTLS12"

    minimalTLS12:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"

    minimalTLS13:
      minVersion: "VersionTLS13"

```

Traefik container using traefik:v2.0.2
```yaml
labels:
      traefik.enable: 'true'
      traefik.http.routers.proxy-dashboard-https.rule: 'Host(`proxy.domain.com`) && PathPrefix(`/dashboard/`) || PathPrefix(`/api`)'
      traefik.http.routers.proxy-dashboard-https.middlewares: 'auth-basic-proxy@file, compress-content-security@file'
      traefik.http.routers.proxy-dashboard-https.service: 'api@internal'
      traefik.http.routers.proxy-dashboard-https.entrypoints: 'websecure'
      traefik.http.routers.proxy-dashboard-https.tls.certresolver: 'leCloudflareDns'
      traefik.http.routers.proxy-dashboard-https.tls.options: 'minimalTLS13@file'
      traefik.http.routers.proxy-dashboard-http.rule: 'Host(`proxy.domain.com`) && PathPrefix(`/dashboard/`) || PathPrefix(`/api`)'
      traefik.http.routers.proxy-dashboard-http.entrypoints: 'web'
      traefik.http.routers.proxy-dashboard-http.middlewares: 'redirect-https@file'
```

Statping container using hunterlong/statping:v0.80.63
```yaml
labels:
        traefik.enable: 'true'
        traefik.http.routers.statping-https.rule: 'Host(`status.domain.com`)'
        traefik.http.routers.statping-https.middlewares: 'compress-content-security@file'
        traefik.http.routers.statping-https.entrypoints: 'websecure'
        traefik.http.routers.statping-https.tls.certresolver: 'leCloudflareDns'
        traefik.http.routers.statping-https.tls.options: 'minimalTLS13@file'
        traefik.http.routers.statping-http.rule: 'Host(`status.domain.com`)'
        traefik.http.routers.statping-http.entrypoints: 'web'
        traefik.http.routers.statping-http.middlewares: 'redirect-https@file'
```
