### ISSUE TITLE
[docker-compose] BasicAuth middleware doesn't find user file

### ISSUE THREAD

**Issue by marwanpro** [containous/traefik#5687]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Setting up a middleware and specify a working auth_basic user file

### What did you expect to see?

I except to ask me user and password according to auth file

### What did you see instead?

`reverse-proxy_1  | time="2019-10-18T09:01:26Z" level=error msg="open /docker/torrent/basicauth: no such file or directory" entryPointName=https routerName=seedbox_proxy@docker`

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik 2.0.2 (docker-compose latest)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: "3.6"

services:

  # Reverse Proxy with Traefik
  reverse-proxy:
    image: traefik
    restart: unless-stopped
    command: 
      - --accesslog
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_proxy.rule=Host(`A`)
      - traefik.http.routers.traefik_proxy.entryPoints=https
      - traefik.http.routers.traefik_proxy.tls=true
      - traefik.http.services.traefik_svc.loadbalancer.server.port=8080

  # Seedbox with ruTorrent
  seedbox:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/torrent/config:/config
      - /docker/torrent/downloads:/downloads
      - /docker/torrent/basicauth:/docker/torrent/basicauth
    ports:
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.seedbox_mw.basicauth.usersfile=/docker/torrent/basicauth
      - traefik.http.routers.seedbox_proxy.rule=Host(`B`)
      - traefik.http.routers.seedbox_proxy.entryPoints=https   
      - traefik.http.routers.seedbox_proxy.tls=true
      - traefik.http.routers.seedbox_proxy.middlewares=seedbox_mw@docker
      - traefik.http.services.seedbox_svc.loadbalancer.server.port=80
```

```
 automne@REDACTED> /docker/reverseproxy > stat /docker/torrent/basicauth                                                                                                                                                                          Fichier : /docker/torrent/basicauth
   Taille : 69          Blocs : 8          Blocs d'E/S : 4096   fichier
Périphérique : 804h/2052d       Inœud : 135010700   Liens : 1
Accès : (0644/-rw-r--r--)  UID : (    0/    root)   GID : (    0/    root)
 Accès : 2019-10-18 14:53:43.527899539 +0200
Modif. : 2019-10-18 14:35:47.710742953 +0200
Changt : 2019-10-18 14:35:47.710742953 +0200
  Créé : 2019-10-18 09:54:59.999002688 +020
```
