### ISSUE TITLE
Unable to connect over TCP with STARTTLS

### ISSUE THREAD

**Issue by S7evinK** [containous/traefik#5688]
### Do you want to request a *feature* or report a *bug*?

Bug (or not intended to work/not possible)

### What did you do?

I'm trying to setup ejabberd with STARTTLS behind Traefik, without success so far. 
Things I've already tried:
- Let Traefik handle the certificates
- Let ejabberd handle the certificates (with `passthrough: true` on the ingress route)
- several XMPP Client Options (Require, if available, "old-style SSL"; old-style SSL at least gets to the container itself)

### What did you expect to see?

- Successful connection with openssl using STARTTLS (see below)
- Successful connection with a normal client

### What did you see instead?

Using
```bash
openssl s_client -connect domain.tld:5222 -servername domain.tld -xmpphost domain.tld
```
i'm getting the correct certificate from Traefik. This request reaches the ejabberd container: 
```bash 
Accepted connection 10.244.4.57:32900 -> 10.244.3.203:5222
```

Using
```bash
openssl s_client -connect domain.tld:5222 -servername domain.tld -xmpphost domain.tld -starttls xmpp
```
the connection gets stuck with "CONNECTED(00000003)" (similar to #4875)
Looking at the network level, Traefik seems to ACK the first XML/XMPP Packet and nothing happens after that.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
traefik.yaml
```yaml
global:
  log:
    level: debug
  api:
    insecure: true
    dashboard: true
    debug: true
  entryPoints:
    web:
      address: :80
    websecure:
      address: :443
    xmpp-c2s:
      address: :5222
    xmpp-s2s:
      address: :5269
  providers:
    kubernetesCRD:
      namespaces:
        - default
        - ejabberd
  certificatesResolvers:
      cloudflareResolver:
        acme: [...]
```
cmd args:
```
args:
- --api.insecure
- --accesslog
- --configFile=/config/traefik.yaml
- --providers.kubernetescrd
- --serverstransport.insecureskipverify
```

IngressRouteTCP:
```yaml 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ejabberd-tcp-5222
  namespace: ejabberd
spec:
  entryPoints:
  - xmpp-c2s
  routes:
  - match: "HostSNI(`*`)" # Also tried HostSNI(`domain.tld`) with the same result
    kind: Rule
    services:
    - name: ejabberd-svc
      port: 5222
      namespace: ejabberd
  tls:
    certResolver: cloudflareResolver
```
