### ISSUE TITLE
Remove certificate already exists warning

### ISSUE THREAD

**Issue by rnsv** [containous/traefik#5691]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Repeated warning message when a new Ingress object is created with secret name that already exists
### What did you expect to see?
Avoid repeated warnings as it floods the logs

### What did you see instead?
```
time="2019-10-19T03:12:01Z" level=warning msg="Skipping addition of certificate for domain(s) \"mydomain.com,*.mydomain.com\", to EntryPoint default, as it already exists for this Entrypoint.
time="2019-10-19T03:12:02Z" level=warning msg="Skipping addition of certificate for domain(s) \"mydomain.com,*.mydomain.com\", to EntryPoint default, as it already exists for this Entrypoint.
```
### Output of `traefik version`: (_What version of Traefik are you using?_)
2.0.2

```
time="2019-10-19T03:12:01Z" level=warning msg="Skipping addition of certificate for domain(s) \"mydomain.com,*.mydomain.com\", to EntryPoint default, as it already exists for this Entrypoint.
time="2019-10-19T03:12:02Z" level=warning msg="Skipping addition of certificate for domain(s) \"mydomain.com,*.mydomain.com\", to EntryPoint default, as it already exists for this Entrypoint.
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-web-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - "*.mydomain.com"
      secretName: existing-system-cert
  rules:
    - host: web.mydomain.com
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
```
