### ISSUE TITLE
middleware \"foo@file\" does not exist

### ISSUE THREAD

**Issue by hotzen** [containous/traefik#5692]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
defined basic-auth middleware in central traefik.yml file:
```
http:
  middlewares:
    kk16auth:
      basicAuth:
        realm: "KK16"
        users:
          - "..."
```

then tried to use/reference this middleware in the docker swarm docker-compose file:
```
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.openhab.rule=Host(`...`)
        - traefik.http.services.openhab.loadbalancer.server.port=8080
        - traefik.http.routers.openhab.middlewares=kk16auth@file
        - traefik.docker.network=...
```

### What did you expect to see?
labeled docker-container using basic auth using referenced middleware, as documented here 
https://docs.traefik.io/middlewares/overview/#provider-namespace
> Referencing a Middleware from Another Provider

### What did you see instead?
```
time="2019-10-19T14:59:54+02:00" level=error msg="middleware \"kk16auth@file\" does not exist" entryPointName=http routerName=kapacitor@docker
```
also tried the other way around `file@kk16auth`, because that was said in some old v2-alpha issue which lead to the same results:
```
time="2019-10-19T14:59:54+02:00" level=error msg="middleware \"file@kk16auth\" does not exist" entryPointName=http routerName=openhab@docker
```

### Output of `traefik version`:
current latest image from https://hub.docker.com/_/traefik which is
```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration

traefik.yml
```
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false

http:
  middlewares:
    kk16auth:
      basicAuth:
        realm: "..."
        users:
          - "..."

certificatesResolvers:
  letsencrypt:
    acme:
      email: ...
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

global:
  sendAnonymousUsage: false
  debug: false
  logLevel: "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
```

docker-compose.yaml excerpt
```
# https://hub.docker.com/r/openhab/openhab/
  openhab:
    image: openhab/openhab:latest-alpine
    ports:
      - "8080:8080"
    # - "8443:8443" # no need for HTTPS
      - "5007:5007" # LSP
    environment:
      - "TZ=Europe/Berlin"
      - "EXTRA_JAVA_OPTS='-Duser.timezone=Europe/Berlin -Xmx4g'"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab/addons:/openhab/addons"
      - "./openhab/conf:/openhab/conf"
      - "./openhab/userdata:/openhab/userdata"
      - "./openhab/init:/etc/cont-init.d"
    # The command node is very important. It overrides the "gosu openhab tini -s ./start.sh" command from Dockerfile and runs as root!
    command: "tini -s ./start.sh server"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.openhab.rule=Host(`...`)
        - traefik.http.services.openhab.loadbalancer.server.port=8080
        - traefik.http.routers.openhab.middlewares=kk16auth@file
        - traefik.docker.network=kk16_default
        # - traefik.http.routers.openhab.tls.certresolver=letsencrypt
```
