### ISSUE TITLE
Redirect Path to the container with first path

### ISSUE THREAD

**Issue by bruno-motacardoso** [containous/traefik#5699]
Hi everyone,

I am trying to setup a traefik container that redirects all request to ```localhost:80``` automatically to the good container like this :

### What did I expect to see?
1. When I go to  ```localhost/<container-name>/hello ```
2. Redirect to the container named <container-name>, so  ```<container-name>/hello```

### What did I see instead?
1. When I go to ```localhost/<container-name>/hello```
2. I am redirected to the ```<container-name>/<container-name>/hello```
The problem is that the path ```/<container-name>/hello``` is keeped so I want to remove ```/<container-name>```

### My traefik configuration
```yml
## traefik.yml
accessLog: {}
# Docker configuration backend
providers:
  docker:
    defaultRule: "PathPrefix(`/{{ .Name }}`)"

# API and dashboard configuration
api:
  debug: true
  insecure: true
```
Someone have an idea, how to do that ?
