### ISSUE TITLE
Can't use config file and cli parameters together.

### ISSUE THREAD

**Issue by lomkju** [containous/traefik#5704]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Tried using the traefik yml and cli parameters together.
Our k8s args passed to the ds.
```
  args = [
    "--log.level=INFO",
    "--providers.file.filename=/etc/traefik/traefik.yml",
    "--providers.kubernetesingress=true",
    "--providers.kubernetesingress.ingressclass=traefik-internal",
  ]
```

### What did you expect to see?
We expected Traefik to use the k8s provider when specifying it through the CLI.
Even changing the argument arragement didn't help. like below
```
  args = [
    "--log.level=INFO",
    "--providers.kubernetesingress=true",
    "--providers.kubernetesingress.ingressclass=traefik-internal",
    "--providers.file.filename=/etc/traefik/traefik.yml",
  ]
```
We were using the same way for our tomls before migrating to v2. Like specified a toml and passed additional parameters
We used something like this before
```
-    "--kubernetes.ingressClass=traefik-concierge",
-    "--loglevel=INFO",
-    "--configFile=/etc/traefik/traefik.toml",
-    "--kubernetes",
```

### What did you see instead?
Traefik seems to ignore the k8s CLI parameters when you specify a config (YML).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.0.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
## Static configuration

# Entrypoints
entryPoints:
  http:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: ${requestAcceptGraceTimeout}
        graceTimeOut: ${graceTimeOut}
      respondingTimeouts:
        idleTimeout: ${idleTimeout}
  https:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: ${requestAcceptGraceTimeout}
        graceTimeOut: ${graceTimeOut}
      respondingTimeouts:
        idleTimeout: ${idleTimeout}
  metrics:
    address: ":8082"

#Logging
accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      # Only add non-sensitive data here
      names:
        Accept: keep
        Accept-Encoding: keep
        Access-Control-Allow-Credentials: keep
        Access-Control-Allow-Origin: keep
        Access-Control-Request-Headers: keep
        Connection: keep
        Content-Encoding: keep
        Content-Length: keep
        Content-Type: keep
        Origin: keep
        Referer: keep
        User-Agent: keep
        X-Forwarded-For: keep
        X-Requested-With: keep

# :8080/metrics will give prometheus metrics
metrics:
  prometheus:
    entryPoint: metrics

# This is for the dashboard
# Read only
api:
  insecure: true
  dashboard: true
```
