### ISSUE TITLE
Error: "Port is missing"

### ISSUE THREAD

**Issue by gregfr** [containous/traefik#5705]
### Do you want to request a *feature* or report a *bug*?

Bug?

### What did you expect to see?

The "router" showing up in the dashboard ; the service at the url.

### What did you see instead?

Error in log "port is missing" ; `404 page not found` at the url.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.0.2

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker 18.09.8-ce on alpine 3.10.2 with portainer 1.22.1
Not using swarm mode.

```toml
# (paste your configuration here)
```

```yaml
  traefikforwardauth:
    image: thomseddon/traefik-forward-auth
    container_name: traefikforwardauth
    labels:
      - traefik.enable=true
      - traefik.port=4181
      - traefik.http.routers.traefikforwardauth.tls.certresolver=leresolver
      - traefik.http.routers.traefikforwardauth.rule=Host(`auth.domain`)
      - traefik.http.routers.traefikforwardauth.entrypoints=websecure
      - traefik.docker.network=traefik_default
    networks:
      - traefik_default
```

The `websecure` entrypoint and the `leresolver` are configured and working.

The following service works ok:

```yaml
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.tls.certresolver=leresolver
      - traefik.http.routers.whoami.rule=Host(`auth.domain`) && PathPrefix(`/whoami`)
      - traefik.http.routers.whoami.entrypoints=websecure
    networks:
      - traefik_default
```

For this one, there's no `port is missing` error. 
However it's working if I add:
```yaml
    ports:
      - 4181:4181
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```

time="2019-10-22T14:37:30Z" level=error msg="port is missing" providerName=docker container=traefikforwardauth-traefikforwardauth-53cbecb476a5f5184f162a6ddfbc45d4edf4d35c2ea3287440b93affb04b4194


```
