### ISSUE TITLE
Kubernetes backend always uses https

### ISSUE THREAD

**Issue by jaxxstorm** [containous/traefik#571]
I'm running a k8s replication controller.

my rc.yaml:

```yml
apiVersion: v1
kind: ReplicationController
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --kubernetes.endpoint="http://kubemaster:8080"
        - --logLevel=DEBUG
```

and my ingress.yaml:

```yml
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: example-service
    http:
      paths:
      - backend:
          serviceName: example-service
          servicePort: 80
```

My understanding from #334 and from #333 is that if the service port is specified correctly, it shouldn't use https to connect to the k8s API.

Despite this, I'm seeing the following errors in the logs:

```shell
time="2016-07-30T17:02:15Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://10.254.0.1:443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://10.254.0.1:443/apis/extensions/v1beta1/ingresses\" : [Get https://10.254.0.1:443/apis/extensions/v1beta1/ingresses: x509: certificate signed by unknown authority], retrying in 12.900291623s"
```

1) Why is it using https?
2) I tried passing my `ca.crt` as a volume mount which it picked up:
 `time="2016-07-30T16:57:31Z" level=debug msg="Kubernetes CA cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
time="2016-07-30T16:57:31Z" level=debug msg="Kubernetes endpoint: https://10.254.0.1:443"
` but seemed to ignore
3) Why when I specify the command line argument `--kubernetes.endpoint='host:8080` is the env var being used?
