### ISSUE TITLE
Redirect domain.com -> www.domain.com

### ISSUE THREAD

**Issue by marccampbell** [containous/traefik#572]
Are there any plans to allow for a configuration that would be able to send a 301 redirect from a frontend to another URL? In this scenario, the other frontend may or may not be on the same traefik server, and I'd like to be able to have the client honor the redirect.

I currently host my www.domain.com web site on traefik and I have the http -> https redirect enabled. Today, visitors can visit any of the following:

| Requested Host and Protocol | Result |
| --- | --- |
| http://domain.com | 301 redirect to https://domain.com |
| https://domain.com | content |
| http://www.domain.com | 301 redirect to https://www.domain.com |
| https://www.domain.com | content |

I'm wondering if there are plans to allow: 

| Requested Host and Protocol | Result |
| --- | --- |
| http://domain.com | 301 redirect to https://www.domain.com |
| https://domain.com | 301 redirect to https://www.domain.com |
| http://www.domain.com | 301 redirect to https://www.domain.com |
| https://www.domain.com | content |

**Comment by osixia** [comment]
I guess some people will also need the reverse www.domain.com -> domain.com

**Comment by lxcid** [comment]
I read the docs but have no idea how to config this kind of redirection. Any help?

**Comment by phoenix741** [comment]
I need this sort of feature to redirect from www.domain.com -> domain.com

**Comment by thibaultlambermont** [comment]
Yes it will be perfect to have the capability to redirect www.domain.com -> domain.com
I don't find how to do it.

**Comment by phoenix741** [comment]
To turn arround the problem, i use a container with nginx like this : https://github.com/Pindar/docker-nginx-redirect-301

**Comment by thibaultlambermont** [comment]
Thanks ! But it will be nice to have it directly in Traefik no?

**Comment by osixia** [comment]
I made a simple image that do the job too:
https://github.com/osixia/docker-www-redirect

Use it behind traefik and : 
  - If the requested host is www.example.org/whatever the visitor will be redirected to example.org/whatever

  - If the requested host is example.org/whatever the visitor will be redirected to www.example.org/whatever

But i'm agree have it directly in traefik would be great :)

**Comment by NiklasA** [comment]
My "ugly" workaround was it to create a docker container in Traefik, which solves the whole thing with a single HTML page. The HTML page allows it to redirect from `http(s)://www.*` to `http(s)://*`. A integrated solution in Traefik, would be very nice!

**Comment by ubershmekel** [comment]
Here's a redirecting service you can put in a `docker-compose.yml`

```
version: '2'
services:
  nginxredirect:
    image: schmunk42/nginx-redirect
    environment:
    - SERVER_REDIRECT=www.example.com
    labels:
    - "traefik.port=80"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:example.com"
    - "traefik.docker.network=reverseproxy_default"
    networks:
    - "reverseproxy_default"
    restart: always
networks:
  reverseproxy_default:
    external:
      name: reverseproxy_default
```

The network setup is based on https://github.com/containerize-my-server/reverse-proxy

**Comment by Juliens** [comment]
You can use the redirect in entrypoint configuration

https://docs.traefik.io/toml/#entrypoints-definition

```toml
 [entryPoints]
   [entryPoints.http]
   address = ":80"
     [entryPoints.http.redirect]
       regex = "^http://localhost/(.*)"
       replacement = "http://mydomain/$1"
```

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by ubershmekel** [comment]
@Juliens and @ldez is there a way to invoke this regex-replacement as docker-compose labels or is it only possible in the traefik.toml? I understand that changes to the global config file require a restart of the entire reverse proxy taking all sites down.

**Comment by Juliens** [comment]
@ubershmekel No, I'm sorry, you can't configure this regex-replacement in labels.

**Comment by ubershmekel** [comment]
If many of traefik's features are going to require a restart of the entire reverse proxy, you guys might want to reconsider the text on the readme.

> But a microservices architecture is dynamic... Services are added, removed, killed or upgraded often, eventually several times a day.
> Traditional reverse-proxies are not natively dynamic. You can't change their configuration and hot-reload easily.

I have no idea how this project works, but if there's a way to remove all the tech from the config and only ever implement options in the orchestrator layer - that would live up to the hype.

**Comment by seospace** [comment]
As it was long time ago, any news on this?

**Comment by ldez** [comment]
@seospace the issue is close.

You must use redirection:
- https://docs.traefik.io/configuration/entrypoints/#rewriting-url
- https://docs.traefik.io/configuration/backends/docker/#on-containers

**Comment by redbaron76** [comment]
As reference, this snippet redirects WWW to a NON-WWW domain as expected in a docker-compose services -> labels block:

```
...

- traefik.frontend.rule=Host:example.com,www.example.com
- traefik.frontend.redirect.regex=^https?://www.example.com/(.*)
- traefik.frontend.redirect.replacement=https://example.com/$${1}

**Comment by olexam** [comment]
I have solved this issue with URL rewrite options, but meet problem in combination of Let's encrypt and ssl termination, in this case URL rewrite options ignored:

> Note
>
> Please note that regex and replacement do not have to be set in the redirect structure if an entrypoint is defined for the redirection (they will not be used in this case).

So I have to set rewrite config in https part, the final config:

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.redirect]
    regex = "^https://example.com/(.*)"
    replacement = "https://www.example.com/$1"
    permanent = true
  [entryPoints.https.tls]
```
Hope it will be helpful.

**Comment by pgassmann** [comment]
In 1.7.0 there should be a new option `traefik.frontend.headers.SSLForceHost`

But it does not redirect https://www. as expected, even with all the following labels.

```
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:example.com,www.example.com"
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.SSLHost: "example.com"
      traefik.frontend.headers.SSLForceHost: true
      traefik.port: "80"
      traefik.protocol: "http"
```

@ldez can you reopen this issue.

**Comment by ldez** [comment]
See:
- https://github.com/containous/traefik/issues/572#issuecomment-382270057
- https://github.com/containous/traefik/issues/4087
- https://github.com/containous/traefik/pull/4138

**Comment by pgassmann** [comment]
Thank you.
It is not yet working in the latest released traefik version 1.7.4
The fix was merged 1 day after the latest release.

**Comment by alpertandogan** [comment]
With final version traefik 404 problem 

`
You end this url --->Goes to this url >RESULT
http://www.example.com/img.gif	--->https://www.example.com/img.gif	WORKS WELL
https://www.example.com/img.gif -->https://www.example.com/img.gif	WORKS WELL

http://example.com/img.gif	--->https://example.com/img.gif	404 not found
https://example.com/img.gif	--->https://example.com/img.gif	404 not found

<pre>
[entryPoints]
   [entryPoints.http]
     address = "xx.xx.xx.xx:80"
   [entryPoints.http.redirect]
     entryPoint = "https"
   [entryPoints.https]
     address = "xx.xx.xx.xx:443"
     compress = true
   [entryPoints.https.redirect]
    regex = "^https://example.com/(.*)"
    replacement = "https://www.example.com/$1"
    permanent = true
</pre>

**Comment by ReDev1L** [comment]
labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:domain.com,prefix.domain.com
      - traefik.frontend.redirect.entryPoint=https
      - traefik.frontend.redirect.permanent=true
      - traefik.frontend.redirect.regex=^https?://prefix.domain.com/(.*)
      - traefik.frontend.redirect.replacement=https://domain.com/$${1}

last two doesnt work for me, please, can someone explain why?

in traefik-ui, i see only https redirect (in details tab at frontend)

**Comment by trkoch** [comment]
> ```
 > - traefik.frontend.rule=Host:example.com,www.example.com
> - traefik.frontend.redirect.regex=^https?://www.example.com/(.*)
> - traefik.frontend.redirect.replacement=https://example.com/$${1}
> ```

While this works for sites with existing certificate, it broke certificate generation for me, and probably also renewal. I worked around by replacing `(.*)` with `([^.].*)`. This exempts all paths with leading `.`, see [regex101.com]( https://regex101.com/r/y8eFXe/1) for examples. Unfortunately Go does not support negative lookahead.

What is the canonical way to do this? It seems to be a very common requirement.

**Comment by Paul-Gd** [comment]
> ```
>     labels:
>       traefik.enable: true
>       traefik.frontend.rule: Host:www.domain.com,wtf.domain.com,domain.com
>       traefik.frontend.headers.SSLRedirect: true
>       traefik.frontend.headers.SSLForceHost: true
>       traefik.frontend.headers.SSLHost: domain.com
>       traefik.frontend.redirect.regex: .*.domain.com([/](.*))*
>       traefik.frontend.redirect.replacement: https://domain.com$${1}
>       traefik.frontend.redirect.permanent: true
> ```
> Because we dont have API subdomains on this container, that confing solved task

This doesn't work for links like `subdomain.domain.com/redirect=domain.com` because the `.*` eagerly captures anything until `domain.com`. See [regex101.com](https://regex101.com/r/OdCgvA/1).

I think the proper way to fix it is: `.*?.domain.com([/](.*))*`. Note the lazy capture operator `?`. See [regex101.com](https://regex101.com/r/xenU6X/3/) for a demo.

**Comment by joseluisq** [comment]
It works for me via `traefik.toml` file:

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    permanent = true

  [entryPoints.https]
    address = ":443"

      [entryPoints.https.redirect]
      regex = "^https://www.(.*)"
      replacement = "https://$1"
      permanent = true

      [entryPoints.https.tls]
        compress = true
```
