### ISSUE TITLE
Cannot Route To K8S Services In A Different Namespace Using ExternalName service

### ISSUE THREAD

**Issue by crhuber** [containous/traefik#5727]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a rule to route to a service `foo`  in a namespace different to where traefik is deployed. 

```
  - match: Host(`www.mydomain.com`) & PathPrefix(`/foo`)
    kind: Rule
    services:
    - name: foo
      port: 80
```
However that does not work. So I setup an external name service for `foo` in kubernetes in the traefik namespace  

```
apiVersion: v1
kind: Service
namespace: traefik
metadata:
  name: foo
spec:
  externalName: foo.ns-a.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
```

However I keep getting errors in traefik log saying 

```
traefik-68b549f5c6-b68s6 traefik time="2019-10-25T15:29:50Z" level=error msg="Cannot create service: service port not found" providerName=kubernetescrd ingress=entrynamespace=traefik serviceName=foo servicePort=80
traefik-68b549f5c6-b68s6 traefik time="2019-10-25T15:29:50Z" level=error msg="Cannot create service: service port not found" namespace=traefik providerName=kubernetescrd servicePort=80 serviceName=foo ingress=entry
```

### What did you expect to see?

I expect to be able to use an ExternalName service to be able to route to services in different namespaces. 

### What did you see instead?

```
traefik-68b549f5c6-b68s6 traefik time="2019-10-25T15:29:50Z" level=error msg="Cannot create service: service port not found" providerName=kubernetescrd ingress=entrynamespace=traefik serviceName=foo servicePort=80
traefik-68b549f5c6-b68s6 traefik time="2019-10-25T15:29:50Z" level=error msg="Cannot create service: service port not found" namespace=traefik providerName=kubernetescrd servicePort=80 serviceName=foo ingress=entry
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Kubernetes , Amazon EKS, Helm Chart
```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
