### ISSUE TITLE
HTTPS returns `404 page not found`

### ISSUE THREAD

**Issue by boldt** [containous/traefik#5729]
# Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I followed the [quick start guide ](https://docs.traefik.io/getting-started/quick-start/) and I use a basic `traefik.toml`:

**1) traefik.toml**

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[providers.docker]
```

**2) docker-compose.yml**

```yaml
version: "3.7"

services:
  traefik:
    image: traefik
    ports: 
    - "8080:8080"
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - "$PWD/traefik.toml:/etc/traefik/traefik.toml"

  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
```

The full MWE can be found here: https://github.com/boldt/traefik-v2-mwe/

### What did you see?

The call of the HTTP endpoint:

```bash
$ curl -H Host:whoami.docker.localhost http://127.0.0.1
Hostname: aa6bfee60f2d
IP: 127.0.0.1
IP: 172.29.0.4
```

**ISSUE**: Call of the HTTPS endpoint returns **404 page not found**:

```bash
curl --insecure -H Host:whoami.docker.localhost https://127.0.0.1
404 page not found
```

### What did you expect to see?

```bash
curl --insecure -H Host:whoami.docker.localhost https://127.0.0.1
Hostname: aa6bfee60f2d
IP: 127.0.0.1
IP: 172.29.0.4
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```
