### ISSUE TITLE
Unable to use file provider in IngressRoute

### ISSUE THREAD

**Issue by crhuber** [containous/traefik#5751]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I want to be able to route some traffic to a service that exists outside of Kubernetes. So, I created a file provider with the following config
```
    [http.services]
      [http.services.gateway-legacy.loadBalancer]
        [[http.services.gateway-legacy.loadBalancer.servers]]
          url = "http://gateway-lagacy.mydomain.internal/"
```

Then, in a `IngressRoute` im trying to reference `gateway-legacy` in a rule such as

```
  - match: PathPrefix(`/legacy`)
    kind: Rule
    services:
    - name: gateway-legacy@file
      providerName: file
      namespace: file
      port: 8001
```

I tried using ` providerName: file` or `namespace: file` or `gateway-legacy@file` but no combination works. 

In the logs I get 

```
error msg="Cannot create service: service not found default/gateway-legacy@file" ingress=entry-www-de namespace=default servicePort=8001 serviceName=gateway-legacy@file providerName=kubernetescrd
```

How am I supposed to route outside the cluster?

### What did you expect to see?

I should be able to use a file provider in IngressRoute

### What did you see instead?

```
error msg="Cannot create service: service not found default/gateway-legacy@file" ingress=entry-www-de namespace=default servicePort=8001 serviceName=gateway-legacy@file providerName=kubernetescrd
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [http.services]
      [http.services.gateway-legacy.loadBalancer]
        [[http.services.gateway-legacy.loadBalancer.servers]]
          url = "http://gateway-lagacy.mydomain.internal/"
```
