### ISSUE TITLE
Prometheus panic with kubernetes crd when more than one service specified

### ISSUE THREAD

**Issue by aliksend** [containous/traefik#5755]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Use more than one service in IngressRoute's Rule in my setup with prometheus metrics.

### What did you expect to see?

Working prometheus

### What did you see instead?

```json
{"level":"error","msg":"Error in Go routine: runtime error: invalid memory address or nil pointer dereference","time":"2019-10-30T19:16:00Z"}
{"level":"error","msg":"Stack: goroutine 72 [running]:\nruntime/debug.Stack(0xc00011c000, 0x24d0eaf, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x209b8c0, 0x3ee55d0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:160 +0xb1\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x25ab3d8)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:150 +0x57\npanic(0x209b8c0, 0x3ee55d0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/containous/traefik/v2/pkg/metrics.OnConfigurationUpdate(0xc000817860, 0xc000a74000, 0x5, 0x8)\n\t/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:232 +0x7ff\ngithub.com/containous/traefik/v2/pkg/server.(*Server).loadConfiguration(0xc0001ae000, 0x24bb87e, 0xd, 0xc0005ef780)\n\t/go/src/github.com/containous/traefik/pkg/server/server_configuration.go:59 +0x49a\ngithub.com/containous/traefik/v2/pkg/server.(*Server).listenConfigurations(0xc0001ae000, 0xc0001b00e0)\n\t/go/src/github.com/containous/traefik/pkg/server/server_configuration.go:249 +0x51\ngithub.com/containous/traefik/v2/pkg/server.(*Server).Start.func3(0xc0001b00e0)\n\t/go/src/github.com/containous/traefik/pkg/server/server.go:183 +0x34\ngithub.com/containous/traefik/v2/pkg/safe.(*Pool).Go.func1()\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:90 +0x7b\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x25ab3d8, 0xc000027bf0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:153 +0x57\ncreated by github.com/containous/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:147 +0x49\n","time":"2019-10-30T19:16:00Z"}

```
in logs

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      d1b491d2585e93f12325844f926dfc16649331a6
Codename:     cheddar
Go version:   go1.13.1
Built:        2019-10-31_09:33:12
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
metrics:
  prometheus:
    entryPoint: web
    addEntryPointsLabels: true
    addServicesLabels: true
```
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: abc
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`abc.com`)
    services:
    - name: service-1
      port: 9000
    - name: service-2
      port: 9000
```

### Bug location

https://github.com/containous/traefik/blob/v2.0.4/pkg/provider/kubernetes/crd/kubernetes_http.go#L78
As you can see, when you define one service, then balancerServerHTTP will be used.
But when you define multiple services then `new dynamic.Service` creates (in :93) without LoadBalancer field (so `LoadBalancer == nil`)

I receive service like that in https://github.com/containous/traefik/blob/v2.0.4/pkg/metrics/prometheus.go#L231
```
&dynamic.Service{LoadBalancer:(*dynamic.ServersLoadBalancer)(nil), Weighted:(*dynamic.WeightedRoundRobin)(0xc0005ee1a0), Mirroring:(*dynamic.Mirroring)(nil)}
```
But when i define one service, then receive like that:
```
&dynamic.Service{LoadBalancer:(*dynamic.ServersLoadBalancer)(0xc000738dc0), Weighted:(*dynamic.WeightedRoundRobin)(nil), Mirroring:(*dynamic.Mirroring)(nil)}   
```

Bug found but not sure how to fix it
