### ISSUE TITLE
Wrong certificate returned by traefik

### ISSUE THREAD

**Issue by KonradPeters** [containous/traefik#5758]
---
name: Wrong certificate returned by traefik
about: The certificate of another pod is served for a wordpress-pod

---

Bug

When we access www.<somepage>.com, the acme certificate for abc.some.page.works is returned. The certificate for abc.some.page.works works perfectly fine.

Restarting the traefik pods did not show any change. 
The two ingress configurations are the same (but with a different domain of course)

### What did you expect to see?

We expected to see the correct certificate for www.<somepage>.com

### What did you see instead?

Instead we saw the certificate for abc.some.page.works

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v 1.7.16 on Kubernetes v 1.12.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]

logLevel = "DEBUG"

[docker]
endpoint="unix://var/run/docker.sock"
watch=true
swarmmode=true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [entryPoints.admin]
  address=":8080"
   [entryPoints.on.auth]
     [entryPoints.on.auth.basic]
       users = [
         "__HTTP_BASIC_SECRET__"
       ]

[acme]
  email = "admin@XXXX.de"
  storageFile = "/etc/traefik/acme.json"
  entryPoint = "https"
  onHostRule = true
  onDemand = false

  [acme.httpChallenge]
           entryPoint = "http"

[[acme.domains]]
  main = "de.XXXX.net"

[traefikLog]
filePath = "/var/log/traefik.log"

[api]
  entryPoint = "admin"
  dashboard = true


```
