### ISSUE TITLE
Traefik v2 Middlewares not being detected

### ISSUE THREAD

**Issue by clementohNZ** [containous/traefik#5761]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Create an ingress route with a middleware that strips the prefix `/users`. The configuration below was mostly generated using the migration tool. 

**configuration for middleware and ingress route**
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: apps-services
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`example.com`) && PathPrefix(`/users/`)
      middlewares:
        - name: traefik-middlewares-backend-users-service
      priority: 0
      services:
        - name: backend-users-service
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middlewares-backend-users-service
  namespace: apps
spec:
  stripPrefix:
    prefixes:
      - /users
```

**Traefik deployment manifest**
```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress
      tier: reverse-proxy
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
        name: traefik-ingress
        tier: reverse-proxy
    spec:
      serviceAccountName: traefik-service-account
      terminationGracePeriodSeconds: 60
      volumes:
        - name: traefik-configmap
          configMap:
            name: traefik-configmap
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                      - traefik-ingress
                  - key: tier
                    operator: In
                    values:
                      - reverse-proxy
                  - key: name
                    operator: In
                    values:
                      - traefik-ingress
              topologyKey: failure-domain.beta.kubernetes.io/zone
              namespaces:
                - apps
      containers:
        - image: "traefik:v2.0.4"
          name: traefik-ingress
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 600Mi
          volumeMounts:
            - mountPath: "/config"
              name: "traefik-configmap"
          ports:
            - name: http
              containerPort: 80
            - name: dashboard
              containerPort: 8080
          args:
            - --log.level=DEBUG
            - --configfile=/config/static-config.yml
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 20
```

I have tried to no avail:

1. Putting the middlewares and ingress routes in the same `traefik` namespace.

**Middleware exists in k8s apps namespace**
```sh
$ kubectl get -n apps middlewares
NAME                                                AGE
traefik-middlewares-backend-users-service           1d
```

### What did you expect to see?

Middlewares show up in the UI and strips the `/users` prefix from requests that match `example.com/users/`

### What did you see instead?

No middlewares listed in the UI and prefix is not stripped from requests matching `example.com/users/` resulting it a 404 route from the backend Spring Boot app being shown.

<img width="1483" alt="Screen Shot 2019-11-01 at 4 30 34 PM" src="https://user-images.githubusercontent.com/15212801/68001682-017be180-fcca-11e9-9b25-dfddbba22db0.png">

<img width="680" alt="Screen Shot 2019-11-01 at 4 26 24 PM" src="https://user-images.githubusercontent.com/15212801/68001687-080a5900-fcca-11e9-9485-5c4200f6ccd4.png">

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  http:
    address: :80
  traefik:
    address: :8080
providers:
  providersThrottleDuration: 2s
  kubernetesIngress: {}
api:
  # TODO: make this secure later
  insecure: true
ping:
  entryPoint: http
log: {}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
2019-11-01T02:58:52.897708514Z time="2019-11-01T02:58:52Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
2019-11-01T02:59:06.657534851Z time="2019-11-01T02:59:06Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
2019-11-01T03:13:27.198564286Z time="2019-11-01T03:13:27Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
2019-11-01T03:26:32.856489709Z time="2019-11-01T03:26:32Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
2019-11-01T03:30:58.588070920Z time="2019-11-01T03:30:58Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
2019-11-01T03:33:12.251123279Z time="2019-11-01T03:33:12Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
2019-11-01T03:38:17.498965416Z time="2019-11-01T03:38:17Z" level=info msg="Configuration loaded from file: /config/static-config.yml"
```

**Comment by zerosym** [comment]
@clementohNZ 
I think you may be missing kubernetesCRD under your providers config here:

```yaml
providers:
  providersThrottleDuration: 2s
  kubernetesIngress: {}
```

https://docs.traefik.io/v2.0/providers/kubernetes-crd/

**Comment by clementohNZ** [comment]
Thanks @zerosym that fixed the issue! Middlewares tested and working.

For others who might look at this later, here's my up to date config.

I had to:

1. Add TLSOption resource definition
2. Update cluster role for traefik to have permissions for listing and watching new v2 resources
3. Make sure all namespaces with new resources are configured

**TLSOption CRD**
```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
```

**Updated Static Configuration for Traefik**
```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  http:
    address: :80
  traefik:
    address: :8080
providers:
  providersThrottleDuration: 2s
  kubernetesCRD:
    namespaces:
      - apps
      - traefik
api:
  # TODO: make this secure later
  insecure: true
ping:
  entryPoint: http
log: {}
```

![Traefik Dashboard with Working Middlewares](https://user-images.githubusercontent.com/15212801/68106265-ec12eb80-ff45-11e9-8e67-d951c1aaf122.png)

Will close this issue.
