### ISSUE TITLE
Version 2 accessing WebUI through PathPrefix frontend returns 404

### ISSUE THREAD

**Issue by XhstormR** [containous/traefik#5762]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In version 1.7 I have the following configuration:
```yml
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - '80:80'
    command: --api --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=PathPrefixStrip:/traefik/
```

I can access the dashboard through this url http://127.0.0.1/traefik/dashboard/, the html page returned by this url is like this:
```html
<!doctype html><html class="has-navbar-fixed-top"><head><meta charset="utf-8"><title>Traefik</title><base href="./"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/x-icon" href="./assets/images/traefik.icon.png"><link href="styles.e21e21d47be645f690e6.bundle.css" rel="stylesheet"/></head><body><app-root></app-root><script type="text/javascript" src="inline.318b50c57b4eba3d437b.bundle.js"></script><script type="text/javascript" src="polyfills.1457c99db4b6dba06e8d.bundle.js"></script><script type="text/javascript" src="scripts.ef668c5c0d42ec4c5e83.bundle.js"></script><script type="text/javascript" src="main.f341693bf9ed22060b42.bundle.js"></script></body></html>
```
One of the JS requests is http://127.0.0.1/traefik/dashboard/scripts.ef668c5c0d42ec4c5e83.bundle.js, which can be accessed normally.

In version 2.0, my configuration file became like this:
```yml
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - '80:80'
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.routers.my-app2.rule=PathPrefix(`/traefik/`)
      - traefik.http.services.my-app2.loadbalancer.server.port=8080
      - traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/traefik
      - traefik.http.routers.my-app2.middlewares=admin-stripprefix@docker
```

Same as version 1, I can access the dashboard through this url http://127.0.0.1/traefik/dashboard/, the html page returned by this url is like this:
```html
<!DOCTYPE html><html><head><title>Traefik</title><meta charset=utf-8><meta name=description content="Traefik UI"><meta name=format-detection content="telephone=no"><meta name=msapplication-tap-highlight content=no><meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width"><link rel=icon type=image/png href=statics/app-logo-128x128.png><link rel=icon type=image/png sizes=16x16 href=statics/icons/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=statics/icons/favicon-32x32.png><link rel=icon type=image/png sizes=96x96 href=statics/icons/favicon-96x96.png><link rel=icon type=image/ico href=statics/icons/favicon.ico><link href=/dashboard/css/0af0fca4.e3d6530d.css rel=prefetch><link href=/dashboard/css/0fba1f4c.0e8b0db6.css rel=prefetch><link href=/dashboard/css/3fff7aa8.0e8b0db6.css rel=prefetch><link href=/dashboard/css/4f849804.0e8b0db6.css rel=prefetch><link href=/dashboard/css/524389aa.619bfb84.css rel=prefetch><link href=/dashboard/css/5b678fb6.b61cea24.css rel=prefetch><link href=/dashboard/css/691c1182.ed0ee510.css rel=prefetch><link href=/dashboard/css/7ba452e3.37efe53c.css rel=prefetch><link href=/dashboard/css/87fca1b4.8c8c2eec.css rel=prefetch><link href=/dashboard/css/90331434.0e8b0db6.css rel=prefetch><link href=/dashboard/css/b987781a.0e8b0db6.css rel=prefetch><link href=/dashboard/css/d53c1dca.b4e7c5a7.css rel=prefetch><link href=/dashboard/js/0af0fca4.271bd48d.js rel=prefetch><link href=/dashboard/js/0fba1f4c.5a437bc7.js rel=prefetch><link href=/dashboard/js/2d21e8fd.f3d2bb6c.js rel=prefetch><link href=/dashboard/js/3fff7aa8.f8383ac0.js rel=prefetch><link href=/dashboard/js/4f849804.d43b703e.js rel=prefetch><link href=/dashboard/js/524389aa.21dfc9ee.js rel=prefetch><link href=/dashboard/js/5b678fb6.15401ef6.js rel=prefetch><link href=/dashboard/js/691c1182.b0154df3.js rel=prefetch><link href=/dashboard/js/7ba452e3.71a69a60.js rel=prefetch><link href=/dashboard/js/87fca1b4.ac9c2dc6.js rel=prefetch><link href=/dashboard/js/90331434.b2a28287.js rel=prefetch><link href=/dashboard/js/b987781a.5ff42e91.js rel=prefetch><link href=/dashboard/js/d53c1dca.d3bd8630.js rel=prefetch><link href=/dashboard/css/app.e4fba3f1.css rel=preload as=style><link href=/dashboard/js/app.6380dcf2.js rel=preload as=script><link href=/dashboard/js/vendor.49a1849c.js rel=preload as=script><link href=/dashboard/css/app.e4fba3f1.css rel=stylesheet><link rel=manifest href=manifest.json><meta name=theme-color content=#027be3><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=default><meta name=apple-mobile-web-app-title content=Traefik><link rel=apple-touch-icon href=statics/icons/apple-icon-120x120.png><link rel=apple-touch-icon sizes=180x180 href=statics/icons/apple-icon-180x180.png><link rel=apple-touch-icon sizes=152x152 href=statics/icons/apple-icon-152x152.png><link rel=apple-touch-icon sizes=167x167 href=statics/icons/apple-icon-167x167.png><link rel=mask-icon href=statics/icons/safari-pinned-tab.svg color=#027be3><meta name=msapplication-TileImage content=statics/icons/ms-icon-144x144.png><meta name=msapplication-TileColor content=#000000></head><body><div id=q-app></div><script type=text/javascript src=/dashboard/js/app.6380dcf2.js></script><script type=text/javascript src=/dashboard/js/vendor.49a1849c.js></script></body></html>
```
But one of the JS requests is http://127.0.0.1/dashboard/js/7ba452e3.71a69a60.js, which can not be accessed normally, it return 404.

![剪贴板03](https://user-images.githubusercontent.com/10527522/68028650-55012600-fcf0-11e9-961d-6ccc6459d985.jpg)

I noticed that version 1 of the js code is like this `<script type="text/javascript" src="inline.318b50c57b4eba3d437b.bundle.js">`, version 2 of the js code is like this `<link href=/dashboard/js/691c1182.b0154df3.js rel=prefetch>`

I hope that traefik's dashboard url can be configured with an PathPrefix in version 2.
