### ISSUE TITLE
[BUG] v2 Dashboard & Redirect + Middleware with no effects

### ISSUE THREAD

**Issue by DnR-iData** [containous/traefik#5765]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I came from v1.7 and trying to convert a v1 to v2 `config.toml` following the https://docs.traefik.io/migration/v1-to-v2/ link.

My goal is to use Traefik v2.0 into GKE cluster.
 

### What did you expect to see?
Access to dashboard have to work and login/pass have to be asked.
Http to Https redirection have to work.

### What did you see instead?
Tested with my v1.7 conf and no problem, but with my v2.0 config, dashboard is inaccessible (404) and http redirect to https don't work.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```output
$ kubectl exec -it  traefik-784d8c545f-5wf7f traefik version
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Where my full `kubernetes` manifest for my `Google Kubernetes Engine` cluster based on official documentation.

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller

rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutetcps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - tlsoptions
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
  type: LoadBalancer
  selector:
    app: traefik

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = false

    [ping]
      entryPoint = "web"

    [api]
      insecure = false
      dashboard = true
      debug = true

    [accessLog]
      format = "common"
      bufferingSize = 0
      [accessLog.fields]
        defaultMode = "keep"
        [accessLog.fields.names]
          "%!s(int=0)" = ""
        [accessLog.fields.headers]
          defaultMode = "keep"
          [accessLog.fields.headers.names]
            "%!s(int=0)" = ""

    # [log]
    #   level = "DEBUG"
    #   # filePath = "foobar"
    #   format = "json"

    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"

    [entryPoints]
      [entryPoints.web]
        address = ":80"
      [entryPoints.websecure]
        address = ":443"
      [entryPoints.traefik]
        address = ":8080"
        
      [http.routers]
        [http.routers.api]
          rule = "Host(`traefik.mydom.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
          entrypoints = ["traefik"]
          service = "api@internal"
          middlewares = ["myAuth"]
          [http.routers.api.tls]
        [http.routers.web]
          rule = "HostSNI(`*`)"
          entrypoints = ["web"]
          middlewares = ["redirect"]
      [http.middlewares]
        [http.middlewares.myAuth.basicAuth]
          users = [
            "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
          ]
        [http.middlewares.redirect.redirectScheme]
          scheme = "https"

    [providers]
      providersThrottleDuration = "2s"
      [providers.kubernetesCRD]
        throttleDuration = "0s"

    [certificatesResolvers]
      [certificatesResolvers.default]
        [certificatesResolvers.default.acme]
          email = "test@mydom.com"
          storage = "/etc/traefik/acme/acme.json"
          caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
          [certificatesResolvers.default.acme.httpChallenge]
            entryPoint = "web"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-acme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-config
        - name: demo-acme
          persistentVolumeClaim:
            claimName: demo-acme
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --configFile=/etc/traefik/config/traefik.toml
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/traefik/config"
              name: config
            - mountPath: /etc/traefik/acme
              name: demo-acme

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Nothing is logged when i try to access in https or via traefik endpoints.

```
$ kubectl logs -f traefik-784d8c545f-5wf7f 
kubectl logs -f traefik-784d8c545f-5wf7f 
time="2019-11-02T19:03:17Z" level=info msg="Configuration loaded from file: /etc/traefik/config/traefik.toml"
time="2019-11-02T19:09:05Z" level=error msg="Error while Peeking first byte: read tcp 10.40.0.16:8080->10.164.0.30:44296: read: connection reset by peer"
10.164.0.31 - - [02/Nov/2019:19:09:05 +0000] "GET / HTTP/1.1" - - "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" 1 - - 0ms
10.164.0.31 - - [02/Nov/2019:19:09:07 +0000] "GET / HTTP/1.1" - - "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" 2 - - 0ms
10.164.0.30 - - [02/Nov/2019:19:14:34 +0000] "GET /notls HTTP/1.1" - - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" 3 - - 0ms
10.164.0.30 - - [02/Nov/2019:19:14:35 +0000] "GET /favicon.ico HTTP/1.1" - - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" 4 - - 0ms
```

```output
# ps faux
PID   USER     TIME  COMMAND
    1 root      0:02 traefik traefik --configFile=/etc/traefik/config/traefik.toml
   24 root      0:00 sh
   31 root      0:00 ps faux
```

Thanks a lot for the help.
