### ISSUE TITLE
Traefik as Ingress on K8S with basic auth enabled for an ingress becomes extremely slow

### ISSUE THREAD

**Issue by roderik** [containous/traefik#5767]
### What did you do?

I run a K8S cluster on GKE (3x n1-standard-4 nodes in 1 zone) with an almost stock Traefik (1.7.14) installed via the stable helm chart as a single replica. ([config](https://gist.github.com/roderik/b5b8a9adac0fad349cb0d6a5b8a3b537))

I have a route which I want to protect with basic auth, which I configure as follows: (helmfile values)

```yaml
ingress_http:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Namespace }}.settlemint.com
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "httpauth"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  path: /parity
  hosts:
    - {{ .Namespace }}.settlemint.com
```

On a functional level, this works perfectly. My routes work, the ones with auth ask for passwords, etc. 

On a performance level though, we experience extreme slowdowns. 

- First requests start off at 200-300ms. Without basic auth, 10ms.
- Then we hit it with less than 100 requests per second.
- Response times (as listed in the Traefik logs) start to climb to 5-6s per request within 10 minutes with the CPU maxed out at the 4 available cores in the node it is running on

Based on a bunch of vague issues I managed to google, I disabled gzip, made sure not to set any headers, not to run in debug mode, etc.

I have not found a helm chart for v2 so I cannot check if this is fixed.
