### ISSUE TITLE
5-10 minute startup with docker provider in swarm mode

### ISSUE THREAD

**Issue by matutter** [containous/traefik#5768]
### Do you want to request a *feature* or report a *bug*?

Bug

I've been taking the [basic docker example](https://docs.traefik.io/user-guides/docker-compose/basic-example/) and applying it to docker swarm however traefik takes an incredibly long time to "start". When using traefik with the docker provider in swarm-mode (`--providers.docker.swarmMode=true`) traefik hangs for at least 5 minutes before configuring entrypoints.

### What did you do?

I've tried this on a 10 node and a single node swarm with the same results.The compose-file below is my latest attempt and its for the single-node swarm.

I've tried creating an overlay network manually before doing a `docker stack deploy` with traefik as a service.

I now run the following commands to reliably recreate the issue and get everything working after 5 minutes of waiting. I'm using 2 separate shells for this.

```bash
# print nothing when connection times out
watch -n 1 'curl -sm 2 whoami.localhost'
```

```bash
# the compose-file has all services scaled to 0 replicas
docker stack deploy -f traefik.yml test

# Start traefik - wait 5 minutes, watch the "curl" shell

docker service scale test_traefik=1 test_whoami=0

# after 5 minutes without whoami started, "404 page not found" will appear this means everything is working and any service I start is immediately detected and traefik immediately reconfigured. 
docker service scale test_traefik=1 test_whoami=1
```

### What did you expect to see?

Traefik to startup and immediately start serving dynamically configured services exactly like the `docker-compose up` version of the original example.

### What did you see instead?

Traefik will take up to ten minutes to start serving routes.I have literally been recording the times on a stopwatch. The average time is 6:16 minutes. The shortest time is 5:30 minutes. The longest time was 8:30 minutes.

When a service is started before the ~5 minutes then they are not served until after the ~5 minutes.

When a service is started after the ~5 minutes they are immediately available on their routes.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```bash
$ docker images traefik
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
traefik             latest              acc0b856f27a        5 days ago          69.3MB
traefik             v2.0.4              acc0b856f27a        5 days ago          69.3MB

$ docker run --rm traefik version                                              
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

#### 10 node swarm

```bash
~# uname -a
Linux l3.lumarch.dev 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux                                   
~# docker --version
Docker version 19.03.4, build 9013bf583a
```

#### 1 node swarm 

```bash
$ uname -a                                                                     
Linux pop-os 5.0.0-21-generic #22+system76-Ubuntu SMP Tue Jul 16 19:57:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux                                  
$ docker --version                                                             
Docker version 19.03.3, build a872fc2f86
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: "3.5"

networks:
  public:
    driver: overlay
    name: public

services:

  traefik:
    image: "traefik:latest"
    networks:
    - public
    command:
      - --log.level=DEBUG

      - --global.sendAnonymousUsage=false

      - --api.dashboard=true
      - --api.insecure=true

      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=public
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock

      - --entrypoints.http.address=:80

    deploy:
      replicas: 0
      labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.services.traefik.loadbalancer.server.port=8080

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    networks:
    - public
    deploy:
      replicas: 0
      labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=http
      - traefik.http.services.whoami.loadbalancer.server.port=80
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

> **NOTE** Last 2 lines repeat for 5 minutes, with different timestamps of course.

```
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=info msg="Configuration loaded from flags."                              
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=info msg="Traefik version 2.0.4 built on 2019-10-28T20:23:57Z"           
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":tr
ue},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\"
:10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"li
feCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providers
ThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`
)\",\"swarmMode\":true,\"network\":\"public\",\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true},\"metrics\":{
\"prometheus\":{\"buckets\":[0.1,0.3,1.2,5],\"addEntryPointsLabels\":true,\"addServicesLabels\":true,\"entryPoint\":\"metrics\"}},\"log\":{\"level\"
:\"DEBUG\",\"format\":\"common\"}}"                                                                                                                
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turn
ing this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"                                             
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=metrics
-entrypoint middlewareType=Metrics                                                                                                                 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=metr
ics-entrypoint middlewareType=Metrics                                                                                                              
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="No default certificate, generating one"                       
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Start TCP Server" entryPointName=http 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Start TCP Server" entryPointName=traefik              [34/4852]
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"            
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":
\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmMode\":true,\"network\":\"public\",\"swarmModeRefreshSecond
s\":15000000000}" 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Provider connection established with docker 19.03.3 (API 1.40)"
 providerName=docker 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"route
rs\":{\"traefik\":{\"entryPoints\":[\"http\"],\"service\":\"traefik\",\"rule\":\"Host(`traefik.localhost`)\"}},\"services\":{\"traefik\":{\"loadBala
ncer\":{\"servers\":[{\"url\":\"http://10.0.16.7:8080\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker                             
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" serviceName=traefik middlewareType=Pipelin
ing middlewareName=pipelining entryPointName=http routerName=traefik@docker                                                                        
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=http
 routerName=traefik@docker serviceName=traefik middlewareName=metrics-service                                                                      
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=traefik@
docker serviceName=traefik 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating server 0 http://10.0.16.7:8080" entryPointName=http ro
uterName=traefik@docker serviceName=traefik serverName=0 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Added outgoing tracing middleware traefik" routerName=traefik@d
ocker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http                                                                   
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=htt
p middlewareName=traefik-internal-recovery 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=metrics
-entrypoint middlewareType=Metrics 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint entryPoi
ntName=traefik middlewareType=Metrics 
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:36Z" level=debug msg="No default certificate, generating one"                       
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:51Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"route
rs\":{\"traefik\":{\"entryPoints\":[\"http\"],\"service\":\"traefik\",\"rule\":\"Host(`traefik.localhost`)\"}},\"services\":{\"traefik\":{\"loadBala
ncer\":{\"servers\":[{\"url\":\"http://10.0.16.7:8080\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker                             
test_traefik.1.tebolkqt3e7z@pop-os    | time="2019-11-03T21:37:51Z" level=info msg="Skipping same configuration for provider docker" providerName=do
cker 
```
