### ISSUE TITLE
Cloudflare provider obtains lets encrypt certs not for all domains i want it to optain for

### ISSUE THREAD

**Issue by vodolaz095** [containous/traefik#5769]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have traefik running as load balancer for docker swarm on centos 7 machine.
It receives lets encrypt certs using DNS challenge and cloudflare as DNS provider 
for services, which have full domain in frontend rule

```
"traefik.basic.frontend.rule=Host:blog.vodolaz095.life"
 ```
But it don't receives lets encrypt certs for domain bound to service with this traefik labels

```
 "traefik.frontend.rule=HostRegexp:{subdomain:[a-z0-9]*}.vodolaz095.life"
```

### What did you expect to see?
I expect traefik to obtain cert for https://vpn.vodolaz095.life/ and use it while proxing requests
to CDN (nginx container). Also i expect traefik to obtain certs for all subdomains of `vodolaz095.life` domain. and proxy traefik for nginx container. Also i want traefik to properly proxy requests to https://blog.vodolaz095.life - which is ghost blog with traefik rule label `traefik.basic.frontend.rule=Host:blog.vodolaz095.life`

### What did you see instead?
Traefik uses self signed cert for  https://vpn.vodolaz095.life/. But it proxies HTTPS requests to nginx container properly, as i expect. Also traefik proxies requests to blog.vodolaz095.life.

Issue is: why do traefik obtains certs for `blog` subdomain here, but not for `vpn` one???

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.14
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "vodolaz095.life"
watch = true
exposedByDefault = false
swarmMode = true
swarmModeRefreshSeconds = 15
network = "oldcity"


[web]
address = ":8080"

[acme]
email = "anatolij@vodolaz095.life"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

# [acme.tlsChallenge]

#[acme.httpChallenge]
#entryPoint = "http"

[acme.dnsChallenge]
provider = "cloudflare"
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
delayBeforeCheck = 5
```

Traefik is running in swarm with this config

```yaml

version: '3'

services:

  traefik:
    image: traefik:1.7.14
    ports:
      - 80:80
      - 443:443
      - 8084:8080
    networks:
      - oldcity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dockervolumes/traefik/traefik.toml:/traefik.toml
      - /opt/dockervolumes/traefik/acme.json:/acme.json
      - traefikTemp:/tmp
    environment:
      CF_API_EMAIL: "secret@example.org"
      CF_API_KEY: "valid_api_key"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == holod]

volumes:
  traefikTemp:

networks:
  oldcity:
    driver: overlay
    external: true

```

Service, for which i'm obtaining certs, is simple nginx running with this docker service file

```yaml

version: '3'

services:

  cdn:
    image: nginx:1-alpine
    networks:
      - oldcity
    volumes:
      - /srv/www/cdn:/usr/share/nginx/html:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == holod]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=oldcity"
        - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z0-9]*}.vodolaz095.life"
        - "traefik.frontend.priority=2"
        - "traefik.basic.port=80"
        - "traefik.basic.protocol=http"


networks:
  oldcity:
    driver: overlay
    external: true

```

Service, for which traefik obtained certs properly, is this 

```yaml

version: '3'

services:

  ghost:
    image: ghost:2-alpine
    depends_on:
      - mariadb
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      url: https://blog.vodolaz095.life
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: "secret"
      database__connection__password: "super_secret"
      database__connection__database: "nothing_here_move_along"
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - oldcity
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == holod]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=oldcity"
        - "traefik.basic.frontend.rule=Host:blog.vodolaz095.life"
        - "traefik.basic.port=2368"
        - "traefik.basic.protocol=http"

volumes:
  ghost:

networks:
  oldcity:
    driver: overlay
    external: true


```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
