### ISSUE TITLE
Routers shouldn't rely on services

### ISSUE THREAD

**Issue by shibumi** [containous/traefik#5771]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I have the following `traefik.yml` file:
```yaml
---

providers:
  file:
    filename: /etc/traefik/traefik.yml

log:
  level: debug

api:
  dashboard: True

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
  metrics:
    address: "127.0.0.1:8082"

metrics:
  prometheus:
    entryPoint: metrics

accessLog: {}

http:
  routers:
    common:
      rule: "Host(`censored`)"
      service: prometheus
      entryPoints:
        - web
      middlewares:
        - https-redirect
    prometheus-router:
      rule: "PathPrefix(`/prometheus`)"
      service: prometheus
      entryPoints:
        - web-secure
      tls: {}
    grafana-router:
      rule: "PathPrefix(`/grafana`)"
      service: grafana
      entryPoints:
        - web-secure
      tls: {}
    api-router:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - web-secure
      tls: {}
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
        port: 443
  services:
    prometheus:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9090/"
    grafana:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000/"

tls:
  certificates:
    - certFile: /etc/traefik/censored.cert
      keyFile: /etc/traefik/censored.key
```

My goal is to redirect all traffic that comes to port 80 to port 443 for HTTPS.
Right now, I need to use a `common`-router for this approach, this router matches my hostname and redirects all traffic to HTTPS. First I tried using this router **without a service**, but I ran into issues with serving the websites + I got error messages in the dashboard.

Now I use just a random service and everything works fine, although it shouldn't really matter, because the traffic will be redirected from one router to another and then matched by PathPrefix rules.

So I suggest that you make defining a service for a router optional or make it easier to route traffic from one router to another. The current approach is pretty tedious. Actually I would prefer a short form like this (sadly, this doesn't work.. btw I don't get any error message when configuring this like this.. so traefik is pretty difficult to debug in certain situations):

```yaml
http:
  routers:
    prometheus-router:
      rule: "PathPrefix(`/prometheus`)"
      service: prometheus
      entryPoints:
        - web
        - web-secure
      middlewares:
        - https-redirect
      tls: {}
```

This approach would allow a redirect on every router **itself**.
