### ISSUE TITLE
Traefik is not picking up its own label in Swarm mode

### ISSUE THREAD

**Issue by Hakujou** [containous/traefik#5777]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using the following docker-compose in Swarm mode:
```
version: '3.2'

networks:
  lbnet:
    driver: overlay
    attachable: true

services:
  traefik:
    image: traefik:v2.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=traefik_lbnet"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=ovh"
      - "--certificatesresolvers.letsencrypt.acme.email=mail@domain.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
    ports:
      - "80:80"
      - "443:443"
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/swarm-data/traefik/acme.json:/acme.json
    networks:
      - lbnet
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY=REDACTED"
      - "OVH_APPLICATION_SECRET=REDACTED"
      - "OVH_CONSUMER_KEY=REDACTED"
    deploy:
      replicas: 2
      labels:
        - "traefik.http.routers.api.rule=Host(`traefik.dmz.internal.domain.com`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=letsencrypt"
        - "traefik.http.routers.api.middlewares=authelia-internal-io"
      placement:
        constraints: [node.role == manager]
```

### What did you expect to see?

Dashboard should be available at provided URI and middleware enabled for it.
I also tried in insecure mode, dashboard is available at port 8080 and none of the configuration deployed on labels is present.
All labels on other containers in the Swarm are working properly.

### What did you see instead?

Labels for the traefik containers are not working, they're not seen by Traefik (configuration not present from dashboard, tried multiple middlewares which works on other containers labels, nothing is picked up by Traefik).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Swarm containers in CentOS 7. Every configuration is present above, only using command line and labels.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A.

Please let me know if you need anything else.
