### ISSUE TITLE
Traefik did not find container without traefik.http.services label

### ISSUE THREAD

**Issue by wuchihsu** [containous/traefik#5786]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Run Traefik using docker-compose then run docker container using command line.

### What did you expect to see?

See my container on Traefik dashboard.

### What did you see instead?

Did not see my container on Traefik dashboard and could not route API to it.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${TRAEFIK_PORT}:80
      - 8080:8080
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" # Traefik will listen on port 8080
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.backend.address=:80"
    networks:
      - backend
    restart: always
```

```bash
docker run\
 --name test\
 --network project_backend\
 --label traefik.enable=true\
 --label traefik.http.routers.test.rule='PathPrefix(`/api/test`)'\
 --label traefik.http.routers.test.priority=2\
 test:0.0.1
```
If I add
```bash
 --label traefik.http.services.test.loadbalancer.server.port=80\
```
will work.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik_1        | time="2019-11-06T03:56:23Z" level=debug msg="Provider event received {Status:start ID:53aba3ed8f7525751bebca57e610f9c80e41596ce95e1ba3f5c5cee8b961f77a From:test:0.0.1 Type:container Action:start Actor:{ID:53aba3ed8f7525751bebca57e610f9c80e41596ce95e1ba3f5c5cee8b961f77a Attributes:map[image:test:0.0.1 name:test traefik.enable:true traefik.http.routers.test.priority:2 traefik.http.routers.test.rule:PathPrefix(`/api/test`)]} Scope:local Time:1573012583 TimeNano:1573012583511997121}" providerName=docker
traefik_1        | time="2019-11-06T03:56:23Z" level=error msg="port is missing" container=test-53aba3ed8f7525751bebca57e610f9c80e41596ce95e1ba3f5c5cee8b961f77a providerName=docker
```
