### ISSUE TITLE
It is not possible to migrate to traefik 2.0 due to the lack of default routers configuration

### ISSUE THREAD

**Issue by majkrzak** [containous/traefik#5789]
### Do you want to request a *feature* or report a *bug*?

Bug and feature request

### What did you do?

I was trying to port 1.x configuration to 2.x

### What did you expect to see?

Possibility to port them

### What did you see instead?

> Defining a certificates resolver does not result in all routers automatically using it. Each router that is supposed to use the resolver must reference it.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
n/a
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
        defaultEntryPoints = ["https"]
        rootCAs = [ "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" ]
        logLevel = "DEBUG"
        [traefikLog]
        filePath = ""
        format   = "json"
        [accessLog]
        filePath = ""
        format = "json"
        [entryPoints]
          [entryPoints.http]
          address = ":80"
          compress = true
            [entryPoints.http.redirect]
            entryPoint = "https"
          [entryPoints.https]
          address = ":443"
          compress = true
            [entryPoints.https.tls]
            minVersion = "VersionTLS12"
            sniStrict = true
        [acme]
        onHostRule = true
        email = "my@ema.il"
        storage = "/data/acme.json"
        entryPoint = "https"
        KeyType = "EC256"
          [acme.httpChallenge]
          entryPoint = "http"
        [kubernetes]
        [file]
          [backends]
            [backends.kubernetes]
              [backends.kubernetes.servers.kubernetes]
              url = "https://kubernetes.default"
          [frontends]
            [frontends.kubernetes]
            backend = "kubernetes"
              [frontends.kubernetes.routes.kubernetes]
              rule = "Host:my.host"
```

According to the documentation it is not possible to port this into traefik 2, or it is?
