### ISSUE TITLE
Dedicated EntryPoint for Ping does not work with Traefik 2 using CLI conf

### ISSUE THREAD

**Issue by tlvenn** [containous/traefik#5797]
Using Traefik 2.0.4 with cli config:

```
--log.level=info
--entrypoints.web.address=:80
--entrypoints.websecure.address=:443
--entryPoints.traefik.address=:8080
--api.dashboard=true
--api.insecure=true
--ping=true
--ping.entryPoint="web"
--metrics=true
--metrics.prometheus=true
--metrics.prometheus.entryPoint="traefik"
--providers.kubernetesingress
--providers.kubernetescrd
```

http://server_ip:80/ping returns a 404
if i remove the `--ping.entryPoint="web"`, then http://server_ip:8080/ping works as expected

**Comment by tlvenn** [comment]
I just noticed #5326 which might explain what is going on but then the documentation need to be updated.

**Comment by ldez** [comment]
Hello,

I don't reproduce.
 
```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0.4
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--ping=true"
      - "--ping.entryPoint=web"
```

```console
$ curl localhost/ping
OK
```

The behavior in #5326 has been fixed in v2.0.0
