### ISSUE TITLE
AddPrefix middleware should not add trailing slash

### ISSUE THREAD

**Issue by aliksend** [containous/traefik#5799]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-prefix
spec:
  addPrefix:
    prefix: /a
```

### What did you expect to see?

Redirection to `/a` when I try to call `/`

### What did you see instead?

Redirection to `/a/`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.0.4
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"debug","middlewareName":"add-prefix@kubernetescrd","middlewareType":"AddPrefix","msg":"URL.Path is now /a/ (was /).","time":"2019-11-08T13:29:56Z"}   
```
