### ISSUE TITLE
TLS Option VersionTLS12 denies TLS1.1 but still allows TLS1.0

### ISSUE THREAD

**Issue by jcjwent** [containous/traefik#5800]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I use Traefik on our Kubernetes cluster and have deployed an IngressRoute with a TLS option that specifies minVersion: VersionTLS12.

When testing the security of the deployed site on ssllabs.com, I noticed that TLS1.1 is no longer accepted if I specify this option. This is correct.
However, TLS1.0 is still supported. See the outcome of https://www.ssllabs.com/ssltest/analyze.html?d=poc2.jkcencrypt.decosasp.com. 

### What did you expect to see?

I expected to see that only TLS1.2 and TLS1.3 are supported, and TLS1.1, TLS1.0 and lower not.

### What did you see instead?

I see that TLS1.1 is not supported, but TLS1.0 is.

When I don't set any VersionTLS12 at all, then TLS1.1 is supported. This indicates to me that the specified TLS option is actually applied, but that it is just not restricting TLS1.0.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My Kubernetes IngressRoute and TLSOption
```yml
# minimum TLS1.2
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: mintls12
  namespace: traefik2
spec:
  minVersion: VersionTLS12
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: poc
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`poc2.jkcencrypt.decosasp.com`)
    kind: Rule
    services:
    - name: nginxinternal
      port: 80
  tls:
    certResolver: default
    options:
      name: mintls12
      namespace: traefik2
```

**Comment by ddtmachado** [comment]
@jcjwent what the tool is reporting is that clients that do not support SNI are able to connect using `TLS1.0`.

while that is true, if you use a client without support to SNI you can also connect using TLS 1.1, 1.2 and so on. That is because without the server name Traefik is just returning a `404` with it's default certificate and there is no restriction on TLS version on your default configuration.

You can check that by hitting your service with the ip address using `openssl` and not specifying a server name:

`openssl s_client -tls1 -connect 52.136.208.255:443`

To fix that you can set the tls default option to deny clients that do not specify the server name as stated here: https://docs.traefik.io/https/tls/#strict-sni-checking

You can also set the minimum TLS version for the default config as well to affect any request that fails to hit a backend and is answered with the Traefik default certificate.

```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default

spec:
  minVersion: VersionTLS12
```

**Comment by dduportal** [comment]
Hi @jcjwent , is this answer fixing your initial issue?

**Comment by jcjwent** [comment]
@ddtmachado Thanks for your answer.

While it looked very promising I'm still stuck. I added the following to my Kubernetes envrionment:
```apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  minVersion: VersionTLS12
  sniStrict: true
```

But this does not make any difference. If I hit my server by its IP I still see the 404, and the SSLLabs site still reports TLS1.0 is allowed. As if nothing has changed. I also redeployed my Traefik deployment.

My Traefik deployment is deployed in namespace 'traefik2' (while the example adds it in 'default'). Adding the above yml to namespace 'traefik2' does not make a difference. Apart from that, I am almost identical to the Kubernetes & Let's Encrypt walkthrough on https://docs.traefik.io/user-guides/crd-acme/.

**Comment by ddtmachado** [comment]
Thanks for the feedback @jcjwent !

I just tried and can confirm it.

When setting the default tls options `minVersion` to `VersionTLS12`, Traefik will still accept connections from TLSv1 and reply with it's default certificate for unknown server names (SNI). 

Also setting `sniStrict` is only affecting the certificate selection on the router and has no effect on the initial connection, even for unknown SNI's as well.

**Comment by jcjwent** [comment]
Thank you @ddtmachado . 

So what is the state? Is this a bug?

**Comment by dduportal** [comment]
FYI, we are re-evaluating this issue and the associated behavior to determine if it is considered a bug, or if we should document and describe it (e.g. expected behavior and solution for your requirements)

**Comment by GreyXor** [comment]
Thanks @ddtmachado for explanation.
Same problem for me here, even with   
```yml
  minVersion: VersionTLS12
  sniStrict: true
```
Traefik still offer TLS 1.0, a non-SNI connection and then the self-signed certificate

**Comment by dduportal** [comment]
Hi @jcjwent @GreyXor ,

Can you try with the 3 following elements?
- Using the image `traefik:v2.1` ?
- Setting a tls option object named `default` , from the file provider (see below):
  - Enabling file provider by adding the flag `--providers.file.filename=/traefik-dynamic.yml` to Traefik Deployment
  - Mount a file (configmap?) in Traefik pod, to the path `/traefik-dynamic.yml`, containing the following directive:
```yml
tls:
  options:
    default:
      sniStrict: true
```

- Enable Traefik debug logs


And if it does not work, can you provide Traefik's log please?


Side note: it might be easier  if you use the experimental Helm chart: https://github.com/containous/traefik-helm-chart (which should soon become the official one of course)

**Comment by dduportal** [comment]
Side note: related  to https://github.com/containous/traefik/issues/5849#issuecomment-559166453

**Comment by jcjwent** [comment]
@dduportal Yes! TLS1.0 is now prohibited. My site scores an A rating now. You're the hero.

**Comment by GreyXor** [comment]
@dduportal I confirm it's working for me! 

- No more non-sni
- No more TLS 1.0
- No more traefik self-signed certificate

My dynamic_conf.toml

```toml
[tls.options]
  [tls.options.TLSOptions]
    minVersion = "VersionTLS12"
    sniStrict = true
  [tls.options.default]
    sniStrict = true
```
