### ISSUE TITLE
Easy to cause OOM with docker defaultRule

### ISSUE THREAD

**Issue by hamiltont** [containous/traefik#5804]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I made an "oops" in my configuration which resulted an endless forwarding cycle (causing Traefik to get OOM killed). This was a pretty simple oops, and one I suspect others might make too. It would be nice to have some prevention - perhaps 1) a comment in the docs 2) scan the config for this as one of a small set of "known-bad" patterns and warn the user in logs 3) detect the endless forward and prevent that

What happened: 

1. I followed the docker quickstart, and was able to get an easy setup working locally. Simple system, one container with a webserver on internal port 80
2. I added `docker.defaultRule=Host('foo.com')` and got a working domain setup without having to add any container labels
3. I enabled the dashboard in insecure mode
4. Visiting foo.com:8080 works as expected, I see the dashboard. Unfortunately, visiting foo.com:80 causes traefik to loop until it's OOM killed

I can see in a DEBUG log that the requests are forwarded to the traefik container instead of the webserver container, which makes sense because they both have the same host rule. 

As a beginner to the 2.x codebase, this took a while to debug and made learning 2.x feel like a slog. Any of the remediations mentioned above would have helped. I originally thought it was my http to https redirection and spent a while learning about middlewares and load balancers before I was able to cut down my config to a much smaller MWE.

**Comment by ldez** [comment]
Hello,

To give you an explanation of the behavior, in this case, by default, the router's entry points on the Traefik container are `traefik` (8080) and `http` (80).
So the call to `foo.com` (`http://foo.com:80`) use this router, so you are calling Traefik (on port 80), so that create an infinite loop.

`traefik` (8080) and `http` (80) are created automacally:
- `traefik` (8080) because you are using `--api.insecure`
- `http` (80) because you didn't define an explicit entry point

<details>
<summary>A more explicit example:</summary>

```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0.4
    command:
    - --api.insecure=true
    - --providers.docker
    - --log.level=DEBUG
    # - --entrypoints.http.address=:80
    # - --entrypoints.traefik.address=:8080
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.dashboard.rule: Host(`test.localhost`)
      traefik.http.routers.dashboard.entrypoints: traefik,http
```

</details>

To avoid that:

- you have to set explicit entry points on the router of the Traefik container

<details>
<summary>explicit entry points:</summary>

```yaml
version: '3'

services:
  reverseproxy:
    image: traefik:v2.0.4
    command:
    - --api.insecure=true
    - --providers.docker
    - '--providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.localhost`)'
    - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.dashboard.entrypoints: traefik
```

</details>

- or/and use the `api@internal` service. [secure-mode](https://docs.traefik.io/v2.0/operations/dashboard/#secure-mode)

<details>
<summary>api@internal service:</summary>

```yaml
version: '3'

services:
  reverseproxy:
    image: traefik:v2.0.4
    command:
    - --api
    - --providers.docker
    - '--providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.localhost`)'
    - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.dashboard.service: api@internal
```

</details>
