### ISSUE TITLE
Router Host rule is ignored

### ISSUE THREAD

**Issue by kromit** [containous/traefik#5805]
###  *bug*

`traefik` service with router rule Host(`traefik.localhost`)  is shown on `whoami` domain

[screenshot](https://i.imgur.com/hrOory8.png)

### What did you do?

```yaml
version: "3.7"

services:

  traefik:
    restart: unless-stopped
    image: traefik:v2.0
    container_name: traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=traefik   
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/etc:/etc/traefik

  whoami:
    restart: unless-stopped
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=http

```

```yaml

entrypoints:
  http:
    address: :80

  https:
    address: :443

  traefik:  # can not rename this?  
    address: :8080


api:
  insecure: true


providers:
  docker:
    exposedByDefault: false 
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by kromit** [comment]
@traefiker  WTF is is shitty bot? At least it explains why this bug went unnoticed for this long.

**Comment by ldez** [comment]
Hello,

the bot is right: to use `api@internal` correctly, the option `--api.insecure` must be false.

https://docs.traefik.io/v2.0/operations/dashboard/#secure-mode

```yaml
version: "3.7"

services:

  traefik:
    restart: unless-stopped
    image: traefik:v2.0.4
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.foo.address=:8181
      - --api=true
      # - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
    container_name: traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=foo   
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/etc:/etc/traefik

  whoami:
    restart: unless-stopped
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=http
```
