### ISSUE TITLE
replaceResponseHeaders middleware feature request

### ISSUE THREAD

**Issue by jvmlet** [containous/traefik#5809]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Would be great  to have the option to replace header the same way as it's done for `replacepathregex`, example : 

````
http:
  middlewares:
    test-replaceheaders:
      replaceResponseHeaders: // new middleware feature
        location:   //header to replace
          regex: "^/foo/(.*)"
          replacement: "/bar/$1"
 
````
