### ISSUE TITLE
The field "RequestLine" is missing in JSON Access logs since V2

### ISSUE THREAD

**Issue by DanielWeigl** [containous/traefik#5810]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

My yml configuration file looks like this:

```
# enable default access log (to stdout by default)
accessLog:
  filePath: "/logs/traefik_access.json"
  format: json
  fields:
    names:
      RequestLine: keep
      ServiceURL: drop
```
(the `ServiceURL: drop` is just to test, if traefik picks the setting correctly -> it works as expected)

### What did you expect to see?

The json access log should include the `RequestLine` as described in the documentation here https://docs.traefik.io/observability/access-logs/ as `RequestMethod + RequestPath + RequestProtocol`

### What did you see instead?

No `RequestLine` entry in the access logs, but all other fields are there

### Output of `traefik version`: (_What version of Traefik are you using?_)

we use the docker image of `traefik:v2.0.1` (`Traefik version 2.0.1 built on 2019-09-26T16:18:03Z`)

Ive searched thugh the current code, and it does not mention `RequestLine` at all - did this go missing in the V2 update? (it worked in V1 for us)
