### ISSUE TITLE
Health check: False UP positive

### ISSUE THREAD

**Issue by strarsis** [containous/traefik#5814]
### What did you do?
Defined a router and a service (weighter, load balanced) to a host that is offline (for demonstrating this bug).

### What did you expect to see?
Health check should fail for the offline host.

### What did you see instead?
Health check passed. Not only in Dashboard, but also in API/raw data section (`UP`).

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[http.routers]
  [http.routers.test1]
    rule = "Host(`example.com`)"
    entrypoints = [ "websecure" ]
    service = "test1-api"
    [http.routers.test1.tls]
      certresolver = "myhttpchallenge"

[http.services]
  [http.services.test1-api]
    [[http.services.test1-api.weighted.services]]
      name = "test1-apiv1"
      weight = 1

  [http.services.test1-apiv1]
    [http.services.test1-apiv1.loadBalancer]
      [[http.services.test1-apiv1.loadBalancer.servers]]
        # deliberate non-routing IP address, this should pass a health check!
        url = "http://192.0.2.0"
```

`docker-compose.yml`:
```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0.4
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.toml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=webmaster@example.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./conf/dynamic_conf.toml:/etc/traefik/dynamic_conf.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
````
