### ISSUE TITLE
Error with using PathPrefix

### ISSUE THREAD

**Issue by rodosskiand** [containous/traefik#5823]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

my docker-compose.yml conf:

```
version: '3'
services:
  traefik:
    image: traefik:2.0.0-rc3-alpine
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
      - "8080:8080" # The web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  echo: 
    image: echo-server:1.5.9-2
    ports:
      - 6001
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.echo.loadbalancer.server.port=6001"
      - "traefik.http.routers.echo.rule=Host(`localhost`) && PathPrefix(`/echo`)"
```

For traefik v1 it worked:

```
- "traefik.frontend.rule=Host:localhost;PathPrefixStrip:/echo"
```
### What did you expect to see?

On request localhost/echo i wanted to see response from echo-service

### What did you see instead?

I saw error: Cannot get /echo

### Output of `2.0.0-rc3-alpine`: (_What version of Traefik are you using?_)

```
 time="2019-11-13T07:37:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/echo\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"redirect_to=%252F; adminer_sid=41e6ebab91ba09970138b9a58485ae16; adminer_key=d1556ec57b7048bae092c61278c0bc4b\"],\"Pragma\":[\"no-cache\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"a4ab8fc6fb98\"],\"X-Real-Ip\":[\"172.19.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:35008\",\"RequestURI\":\"/echo\",\"TLS\":null}"
```
