### ISSUE TITLE
Dashboard does not honor X-Forwarded-Prefix

### ISSUE THREAD

**Issue by gbouthenot** [containous/traefik#5824]
### Do you want to request a *feature* or report a *bug*?
Bug:
The Traefik dashboard can not be served anywhere but from "/dashboard"

According to the documentation https://docs.traefik.io/middlewares/stripprefix/:
```
The X-Forwarded-Prefix header can be queried to build such URLs dynamically.
```
but the dashboard obviously does not honor this header.

### What did you do?
Traefik uses a router, with rule PathPrefix "/traefik/dashboard", and a middleware to strip the "/traefik" prefix.

### What did you expect to see?
curl http://127.0.0.1/traefik/dashboard/

all absolute urls should be begin with "/traefik/dashboard/" i.e. "/traefik/dashboard/js/vendor.49a1849c.js"

### What did you see instead?
the absolute urls begin with "/dashboard", i.e. asset "/dashboard/js/vendor.49a1849c.js", that lead to 404 errors and the dashboard is not functional.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.toml :
```toml
[api]
  dashboard = true
  insecure = false

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "traefik"
```

docker-compose.yml :
```yaml
version: '2.1'
services:
  traefik:
    image: traefik:v2.0.4

    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/:/etc/traefik/:ro
      - ./tmp/:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.port: 8080
      traefik.http.routers.api.rule: "PathPrefix(`/traefik/api`) || PathPrefix(`/traefik/dashboard`) || PathPrefix(`/traefik/debug`)"                                         
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.middlewares: "strip"
      traefik.http.middlewares.strip.stripprefix.prefixes: '/traefik'
networks:
  traefik:
    external: true
```
