### ISSUE TITLE
Only one server per service is identified while using consulCatalog.

### ISSUE THREAD

**Issue by saideeptalari** [containous/traefik#5850]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried using the latest v2.1.0-rc2 and consulCatalog as a provider. I've defined the `config.toml` file as below.

```toml
[api]
    insecure = true
    debug = true

[providers.consulCatalog]
    exposedByDefault = false    
    [providers.consulCatalog.endpoint]
        address = "192.168.1.200:8501"
        scheme = "https"
    [providers.consulCatalog.endpoint.tls]
        ca = "<path-to-ca>"
        cert = "<path-to-cert>"
        key = "<path-to-key>"
        insecureSkipVerify = true

```

and spawned three containers with the following consul service definition for each.
```json
{
    "service": {
        "name": "web",
        "tags": [
            "http",
            "httpd",
            "testing",
            "traefik.enable=true",
            "traefik.http.routers.web.rule=Host(`web.localhost`)"
        ],
        "port": 80,
        "checks": [
            {
                "name": "HTTPD Check",
                "http": "http://127.0.0.1/",
                "method": "GET",
                "interval": "5s"
            }
        ]
    }
}
```

I'm able to see those three nodes in consul dashboard.
![image](https://user-images.githubusercontent.com/11706429/68989353-6b1ff200-086b-11ea-87d9-625353bc05c5.png)

In traefik dashboard only one server is shown instead.
![image](https://user-images.githubusercontent.com/11706429/68989360-986ca000-086b-11ea-9293-10878e644d6c.png)

### What did you expect to see?

All the three nodes should be registered.

### What did you see instead?

Only one node being registered as a server.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.1.0-rc2
Codename:     cantal
Go version:   go1.13.4
Built:        2019-11-15T19:43:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Provided above.
```bash
sudo ./traefik --configFile config.toml
```
