### ISSUE TITLE
Healthcheck running, url rechable, but status marked still as down

### ISSUE THREAD

**Issue by pointhi** [containous/traefik#5851]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* restart docker container
* traefik detects that container is down

### What did you expect to see?

* detect that server is working again

### What did you see instead?

* does not detect that it is reachable again (marked as down)

*How traefik sees the server*
![Screenshot_2019-11-16 Traefik](https://user-images.githubusercontent.com/1652144/68995902-358eff00-0893-11ea-90d2-fa72ebfc02ac.png)

*how it actually behaves*
```
$ curl http://172.21.0.2:3000/robots.txt -v
*   Trying 172.21.0.2...
* TCP_NODELAY set
* Connected to 172.21.0.2 (172.21.0.2) port 3000 (#0)
> GET /robots.txt HTTP/1.1
> Host: 172.21.0.2:3000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: public, max-age=3600
< Content-Length: 26
< Content-Type: text/plain; charset=utf-8
< Last-Modified: Wed, 06 Nov 2019 13:51:46 GMT
< Date: Sat, 16 Nov 2019 16:05:32 GMT
< 
User-agent: *
Disallow: /
* Connection #0 to host 172.21.0.2 left intact
```

*traefik is able to reach container* 
```
$ docker exec -it traefik ping 172.21.0.2
PING 172.21.0.2 (172.21.0.2): 56 data bytes
64 bytes from 172.21.0.2: seq=0 ttl=64 time=0.063 ms
64 bytes from 172.21.0.2: seq=1 ttl=64 time=0.164 ms
64 bytes from 172.21.0.2: seq=2 ttl=64 time=0.166 ms
^C
--- 172.21.0.2 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.063/0.131/0.166 ms
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.0-rc2
Codename:     cantal
Go version:   go1.13.4
Built:        2019-11-15T19:43:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

*traefik.toml*
```toml
[global]
  checkNewVersion = false  # TODO ?
  sendAnonymousUsage = false

[log]
  level = "DEBUG"

[accessLog]

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
    watch = true

  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false


# entry points

[entryPoints.web]
  address = ":80"

[entryPoints.traefik]
  address = ":8080"


# monitoring

[ping]
  entryPoint = "traefik"

[metrics.prometheus]
  entryPoint = "traefik"
  buckets = [0.1,0.3,1.2,5.0]
  addEntryPointsLabels = true
  addServicesLabels = true

# traefik dashboard
[api]
  dashboard = true
```

*dynamic.toml*
```toml
[http.routers.api]
  entryPoints = [ "traefik" ]
  rule = "PathPrefix(`/`)"
  service = "api@internal"

[http.routers.api_web]
  entryPoints = [ "web" ]
  rule = "Host(`traefik.local`)"
  service = "api@internal"
```

*docker labels*
```
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.routers.grafana.rule: "Host(`grafana.local`)"
      traefik.http.routers.grafana.entryPoints: "web"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.http.services.grafana.loadbalancer.healthCheck.path: "/robots.txt"
      traefik.http.services.grafana.loadbalancer.healthCheck.interval: "10s"
      traefik.http.services.grafana.loadbalancer.healthCheck.timeout: "4s"
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-11-16T16:00:43Z" level=debug msg="Refreshing health check for backend: grafana@docker"
time="2019-11-16T16:00:43Z" level=debug msg="Refreshing health check for backend: submitter@docker"
172.21.0.5 - - [16/Nov/2019:16:00:47 +0000] "GET /metrics HTTP/1.1" 200 1961 "-" "-" 218 "prometheus@internal" - 2ms
time="2019-11-16T16:00:48Z" level=debug msg="Refreshing health check for backend: submitter@docker"
127.0.0.1 - - [16/Nov/2019:16:00:52 +0000] "HEAD /ping HTTP/1.1" 200 2 "-" "-" 219 "ping@internal" - 0ms
172.21.0.5 - - [16/Nov/2019:16:00:52 +0000] "GET /metrics HTTP/1.1" 200 1965 "-" "-" 220 "prometheus@internal" - 0ms
time="2019-11-16T16:00:53Z" level=debug msg="Refreshing health check for backend: grafana@docker"
time="2019-11-16T16:00:53Z" level=debug msg="Refreshing health check for backend: submitter@docker"
172.21.0.5 - - [16/Nov/2019:16:00:57 +0000] "GET /metrics HTTP/1.1" 200 1962 "-" "-" 221 "prometheus@internal" - 4ms
time="2019-11-16T16:00:58Z" level=debug msg="Refreshing health check for backend: submitter@docker"
172.21.0.5 - - [16/Nov/2019:16:01:02 +0000] "GET /metrics HTTP/1.1" 200 1963 "-" "-" 222 "prometheus@internal" - 1ms
127.0.0.1 - - [16/Nov/2019:16:01:02 +0000] "HEAD /ping HTTP/1.1" 200 2 "-" "-" 223 "ping@internal" - 0ms
time="2019-11-16T16:01:03Z" level=debug msg="Refreshing health check for backend: grafana@docker"
time="2019-11-16T16:01:03Z" level=debug msg="Refreshing health check for backend: submitter@docker"

```
