### ISSUE TITLE
Ping CLI strange behaviour

### ISSUE THREAD

**Issue by Unb9rn** [containous/traefik#5856]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I am running Traefik v2.0.5 in Docker Swarm with config file.
I was trying to set up a healthcheck with CLI, so I added ping to config file:

```
[ping]
  entryPoint = "ping"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"
  [entryPoints.ping]
    address = ":8082"
  [entryPoints.metrics]
    address = ":8083"

```

### What did you expect to see?

As per manual, 

> traefik healthcheck

 command should be working now.

### What did you see instead?
```

INFO[0000] Configuration loaded from file: /etc/traefik/traefik.toml 
Bad healthcheck status: 404 Not Found
```
:8082 of course is available. tried checking it with 
wget -S 127.0.0.1:8082/ping and got 200 OK

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.5
Codename:     montdor
Go version:   go1.13.4
Built:        2019-11-14T18:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true

[providers]
  providersThrottleDuration = 10
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    useBindPortIP = false
    exposedByDefault = false
    swarmMode = true
    watch = true

  [providers.file]
    directory = "/etc/traefik/services"
    filename = "dynamic.toml"
    watch = true    

[api]
  dashboard = true
  insecure = false

[ping]
  entryPoint = "ping"

[log]
  format = "common"
  level = "ERROR"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"
  [entryPoints.ping]
    address = ":8082"
  [entryPoints.metrics]
    address = ":8083"

[certificatesResolvers.default.acme]
  email = "admin@CHANGE.ME"
  storage = "/etc/traefik/acme/acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  keytype = "EC256"
  [certificatesResolvers.default.acme.tlsChallenge]

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
  [tls.options.mintls13]
    minVersion = "VersionTLS13"

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
    entryPoint = "metrics"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
INFO[0000] Configuration loaded from file: /etc/traefik/traefik.toml 
2019/11/18 06:35:56 traefik.go:67: command traefik error: error while building entryPoint websecure: error preparing server: error opening listener: listen tcp :443: bind: address already in use
```
