### ISSUE TITLE
Ingress gets treated as a router

### ISSUE THREAD

**Issue by Furragen** [containous/traefik#5866]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have a kubernetes cluster on which we are testing the upgrade to Traefik 2.0.
We upgraded the config of Traefik to 2.0, switched the image and the containers start normally.

### What did you expect to see?
1. Upgrade the config
2. Ingresses work just like before
3. Profit

### What did you see instead?
Somehow in the logs I can see that internally Traefik tries to convert ingress-objects to routers, middlewares and services?

Logentries like this come up:
```
level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [metrics ping web websecure]" routerName=someingress@kubernetes
Creating middleware" routerName=someingress@kubernetes serviceName=someingresssvc-http middlewareName=pipelining middlewareType=Pipelining entryPointName=websecure
```

The logs look like ingresses actually are received by Traefik but than handled as routers, which does not work at all, because Traefik does not know which endpoints it should connect the ingresses to.

The question is, why does this happen?
I expected the application traffic to just get routed to the containers like before when using ingress.
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.0.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log:
  level: DEBUG
providers:
  kubernetesIngress: {}
entryPoints:
  ping:
    address: ":9090"
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":7070"
ping:
  entryPoint: "ping"
metrics:
  prometheus:
    entryPoint: metrics
api:
  dashboard: true
tls:
  stores:
    default:
      defaultCertificate: (this setting gets ignored by the way)
        certFile: /tls.crt
        keyFile: /tls.key
http:
  routers:
    api:
      rule: Host(`some.host.com`)
      entrypoints:
        - websecure
      service: api@internal
      middlewares:
        - auth
      tls: {}
  middlewares:
    auth:
      basicAuth:
        users:
          - 'foo:bar'
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```

```
