### ISSUE TITLE
Certificates are renewed but not stored

### ISSUE THREAD

**Issue by cmizzi** [containous/traefik#5880]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a lot of certificates. Many of them are correctly renewed and stored into `consul` but others don't seem to be stored at all. Sometimes, it works great. The minute later, somes certificates are not renewed correctly. Restarting Traefik instances do not solve the bug.

### What did you expect to see?

```
time="2019-11-20T17:52:08Z" level=info msg="Renewing certificate from LE : {Main:www.example.com SANs:[example.com]}"
time="2019-11-20T17:52:08Z" level=info msg="legolog: [INFO] [www.example.com] acme: Trying renewal with 158 hours remaining"
time="2019-11-20T17:52:08Z" level=info msg="legolog: [INFO] [www.example.com, example.com] acme: Obtaining bundled SAN certificate"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme /authz-v3/975020966"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [www.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/ acme/authz-v3/975020968"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [example.com] acme: authorization already valid; skipping challe nge"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [www.example.com] acme: authorization already valid; skipping ch allenge"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [www.example.com, example.com] acme: Validations succeeded; requesting certificates"
time="2019-11-20T17:52:10Z" level=info msg="legolog: [INFO] [www.example.com] Server responded with a certificate."
time="2019-11-20T17:52:10Z" level=info msg="Renewed certificate from  LE: {Main:www.example.com SANs:[example.com]}"
time="2019-11-20T17:52:11Z" level=error msg="Datastore sync error: object lock value: expected 13648d3b-8aa9-4a32-8ec7-86fbf97a0ab1, got 0d653d64-c3e6-46ab-a68a-74051ffcbf1f, retrying in 492.746378ms"
time="2019-11-20T17:52:17Z" level=info msg="Renewing certificate in data store : {Main:www.example.com SANs:[example.com]} "
time="2019-11-20T17:52:17Z" level=info msg="Commit certificate renewed in data store : {Main:www.example.com SANs:[example.com]}"
time="2019-11-20T17:52:20Z" level=info msg="Certificate successfully renewed in data store: {Main:www.example.com SANs:[example.com]}"
```

The certificat is renewed and stored successfully. Traefik should use it.

### What did you see instead?

```
time="2019-11-20T17:52:08Z" level=info msg="Renewing certificate from LE : {Main:www.example.com SANs:[example.com]}"
time="2019-11-20T17:52:08Z" level=info msg="legolog: [INFO] [www.example.com] acme: Trying renewal with 158 hours remaining"
time="2019-11-20T17:52:08Z" level=info msg="legolog: [INFO] [www.example.com, example.com] acme: Obtaining bundled SAN certificate"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme /authz-v3/975020966"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [www.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/ acme/authz-v3/975020968"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [example.com] acme: authorization already valid; skipping challe nge"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [www.example.com] acme: authorization already valid; skipping ch allenge"
time="2019-11-20T17:52:09Z" level=info msg="legolog: [INFO] [www.example.com, example.com] acme: Validations succeeded; requesting certificates"
time="2019-11-20T17:52:10Z" level=info msg="legolog: [INFO] [www.example.com] Server responded with a certificate."
time="2019-11-20T17:52:10Z" level=info msg="Renewed certificate from  LE: {Main:www.example.com SANs:[example.com]}"
time="2019-11-20T17:52:11Z" level=error msg="Datastore sync error: object lock value: expected 13648d3b-8aa9-4a32-8ec7-86fbf97a0ab1, got 0d653d64-c3e6-46ab-a68a-74051ffcbf1f, retrying in 492.746378ms"
time="2019-11-20T17:52:17Z" level=info msg="Renewing certificate in data store : {Main:www.example.com SANs:[example.com]} "
time="2019-11-20T17:52:17Z" level=info msg="Commit certificate renewed in data store : {Main:www.example.com SANs:[example.com]}"
time="2019-11-20T17:52:20Z" level=info msg="Certificate successfully renewed in data store: {Main:www.example.com SANs:[example.com]}"
```

The certificate seems to be renew, stored but it isn't. Traefik always uses the old certificate.

![image](https://user-images.githubusercontent.com/340143/69318701-0afbc800-0c3e-11ea-9d80-28721057058a.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.14
Codename:     maroilles
Go version:   go1.12.8
Built:        2019-08-14_09:46:58AM
OS/Arch:      linux/amd64
```

```toml
defaultEntryPoints = ["http"]

[entryPoints]
        [entryPoints.http]
        address = ":80"

        [entryPoints.https]
        address = ":443"

[acme]
email = "<redacted>"
storage = "traefik/acme/account"
entryPoint = "https"
onDemand = false
onHostRule = true
acmeLogging = true

        [acme.httpChallenge]
        entryPoint = "http"

[consul]
endpoint = "consul:8500"
prefix = "traefik"
watch = true

[docker]
swarmMode = true
domain = "traefik"
endpoint = "tcp://docker-proxy:2375"
watch = true
```

I'm using a Docker Swarm stack to use Traefik. An instance lives on each server in order to be accessible from any public IP living in the swarm (even if not manager with `socat-docker`).

```yaml
version: "3.4"
services:
    traefik_init:
        image: traefik:1.7
        command: "storeconfig -c /traefik_config.toml"
        networks:
            - traefik
        environment:
            LOGSPOUT: ignore
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
        depends_on:
            - consul
        configs:
            - traefik_config.toml

    docker-proxy:
        image: rancher/socat-docker
        networks:
            - traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            LOGSPOUT: ignore
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == <redacted>
            resources:
                limits:
                    cpus: '0.10'
                    memory: 8M
                reservations:
                    cpus: '0.10'
                    memory: 8M

    traefik:
        image: traefik:1.7-alpine
        depends_on:
            - traefik_init
            - consul
        command:
            - "--logLevel=INFO"
            - "--consul"
            - "--consul.watch"
            - "--consul.endpoint=consul:8500"
            - "--consul.prefix=traefik"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik-proxy
            - traefik
        ports:
            - target: 80
              published: 80
              mode: host
            - target: 443
              published: 443
              mode: host
        deploy:
            mode: global
            update_config:
                parallelism: 10
                delay: 10s
            restart_policy:
                condition: on-failure

    consul:
        image: consul:latest
        command: agent -server -bootstrap-expect=1
        volumes:
            - "consul-data:/consul/data"
        environment:
            - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
            - CONSUL_BIND_INTERFACE=eth0
            - CONSUL_CLIENT_INTERFACE=eth0
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == <redacted>
            restart_policy:
                condition: on-failure
        networks:
            - traefik

networks:
    traefik-proxy:
        external: true
    traefik:
        driver: overlay

volumes:
    consul-data:

configs:
    traefik_config.toml:
        external: true
```
