### ISSUE TITLE
Cannot access dashboard.

### ISSUE THREAD

**Issue by shinebayar-g** [containous/traefik#5882]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Followed the doc through [here](https://docs.traefik.io/v2.0/operations/api/#configuration)

### What did you expect to see?

Traefik dashboard is protected by basic auth pop up when I visit `traefik.mydomain.test`

### What did you see instead?

Traefik dashboard isn't protected by basic auth when I visit `traefik.mydomain.test`
I get page not found 404 page.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.1.0-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
```

**Problem:**
I've tried to enable basic auth on traefik dashboard.
Here is my **docker-compose.yml**

```yaml
version: '3'

services:
  traefik:
    image: traefik:2.1
    networks:
      - webproxy
    ports:
      - "0.0.0.0:8080:80"
      - "0.0.0.0:8081:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.mydomain.test`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$3m2nQLv9$$qWJpdr/kII1bWzrif5QrR1"

networks:
  webproxy:
    driver: bridge
```

What am I doing wrong here?

https://github.com/containous/traefik/issues/5561 looks pretty similar, unfortunately I'm not even seeing popup and dashboard.

**Case 2:**

If I enable `insecure` flag in config and expose `8080` port of traefik container, I can see traefik dashboard. But basic auth still not working.

```yaml
api:
  dashboard: true
  debug: false
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
```

```yaml
version: '3'

services:
  traefik:
    image: traefik:2.1
    networks:
      - webproxy
    ports:
      - "0.0.0.0:8080:80"
      - "0.0.0.0:8081:443"
      - "0.0.0.0:8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.mydomain.test`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$3m2nQLv9$$qWJpdr/kII1bWzrif5QrR1"

networks:
  webproxy:
    driver: bridge
```
