### ISSUE TITLE
Adding multiple Host(`bla.com`, ...) or Host(`arg1.com`)||Host(`arg2.com`) break global Prefix matches

### ISSUE THREAD

**Issue by ethanbrooks** [containous/traefik#5897]
### Do you want to request a *feature* or report a *bug*?
Bug
2.0.5
### What did you do?
I created a config for the PathPrefix(`/apm`) to globally route to the apm service with a middleware to remove the path. This works fine with Host entries that have only one domain any more domains any means fails.

### What did you expect to see?
I expect it to display the root response of the apm service an all Hosts listed in the rule

### What did you see instead?
Exactly what I expected on rules with one host but for ones with multiple Hosts I get a response as if the PathPrefix is not defined.

### Output of `traefik version`:
Version:      2.0.5
Codename:     montdor
Go version:   go1.13.4
Built:        2019-11-14T18:11:01Z
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
apm:
   labels:
      traefik.enable: "true"
      traefik.docker.network: docker-traefik_private
      traefik.http.routers.apm.rule: HostRegexp(`{host:.+}`) && PathPrefix(`/apm`)
#      traefik.http.routers.apm.rule: PathPrefix(`/apm`)
      traefik.http.routers.apm.tls: "true"
      traefik.http.routers.apm.entrypoints: https, http
      traefik.http.middlewares.apm_prefix.stripprefix.prefixes: /apm
      traefik.http.middlewares.apm_prefix.stripprefix.forceslash: "false"
      traefik.http.routers.apm.middlewares: apm_prefix
nginx:
   labels:
      traefik.http.routers.bla.rule: Host(`bla.com`) # works 
      traefik.http.routers.arg.rule: Host(`arg1.com`, `arg2.com`) # fails 
      traefik.http.routers.arg.rule: Host(`arg1.com`) ||Host(`arg2.com`) # fails
      traefik.http.routers.arg.rule: (Host(`arg1.com`) ||Host(`arg2.com`)) # fails
```
