### ISSUE TITLE
RedirectScheme middleware conflicts with ACME http challenge

### ISSUE THREAD

**Issue by encombhat** [containous/traefik#5898]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I set up a RedirectScheme middleware to redirect all HTTP requests to HTTPS like this:

```
[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"
```

However, I also use ACME's httpChallenge to automatically get HTTPS certs. It appears that httpChallenge does not override middleware's redirect. As a result LetsEncrypt's httpChallenge request is redirected to HTTPS entrypoint, and that leads to a 404.

```
traefik    | time="2019-11-26T23:57:11Z" level=error msg="Error renewing certificate from LE: {<domain> []}, acme: Error -> One or more domains had a problem:\n[<domain>] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from https://<domain>/.well-known/acme-challenge/5M13Rmcuepk4SQCw-PeyueCMoj-d-3ZaGleio1nkiCk: \"<html>\\n<head><title>404 Not Found</title></head>\\n<body>\\n<center><h1>404 Not Found</h1></center>\\n<hr><center>nginx/1.17.3</center\", url: \n" providerName=http.acme
```

httpChallenge works if redirectScheme is not used for that domain.

### What did you expect to see?

certificatesResolvers.http.acme.httpChallenge overrides other middleware and/or routing when necessary. Or at least make RedirectScheme ignore subpath /.well-known/acme-challenge.

### What did you see instead?

certificatesResolvers.http.acme.httpChallenge does not override other middleware.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.0.5

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker

traefik.toml
```toml
[entryPoints]
  [entryPoints.web]
  address = ":80"
  [entryPoints.web-secure]
  address = ":443"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedbydefault = false
  network = "web"

[providers.file]
  filename = "dynamic.toml"

[certificatesResolvers.http.acme]
email = "<email>"
storage = "acme.json"
  [certificatesResolvers.http.acme.httpChallenge]
    entrypoint = "web"
```

dynamic.toml
```toml
[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"
```
