### ISSUE TITLE
Memory usage keeps growing and continuously slow growing

### ISSUE THREAD

**Issue by eaglewa** [containous/traefik#5904]
### Do you want to request a *feature* or report a *bug*?

Only my question

When I used traefik, I found the memory usage keeps growing, continuously slow growing

![](https://tva1.sinaimg.cn/large/006y8mN6gy1g9d1dqz643j317q0cotb8.jpg)

. So I use Jmeter for pressure test（traefik memeory is limited 2G)，the result is:

![image-20191127235240490](https://tva1.sinaimg.cn/large/006y8mN6gy1g9d1amqlxkj31700ccq4w.jpg)

And then I have stoped it, the memory also keep at 2G, it looks like strange.  

### Output of `traefik version`: (*What version of Traefik are you using?*)

image: traefik:v2.1.0-rc2

### What did you do?

My deployment:

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: traefik-canary
  name: traefik-canary
  namespace: microsvc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traefik-canary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: traefik-canary
        date: "1573641385"
        name: traefik-canary
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - args:
        - --configFile=/config/traefik-static.yaml
        image: traefik:v2.1.0-rc2
        imagePullPolicy: IfNotPresent
        name: traefik
        ports:
        - containerPort: 80
          name: api
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        - containerPort: 8090
          name: open
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: traefik
        name: config-volume
```

And my configMap:

```yml
apiVersion: v1
data:
  traefik-static.yaml: |
    entryPoints:
      api:
        address: ":80"
        transport:
          respondingTimeouts:
            readTimeout: 15
            writeTimeout: 15
      open:
        address: ":8090"
        forwardedHeaders:
          insecure: true
        transport:
          respondingTimeouts:
            readTimeout: 15
            writeTimeout: 15
    api:
      dashboard: true
      insecure: true
    providers:
      file:
        directory: /config
        watch: true
      kubernetesCRD: {}
    tracing:
      jaeger:
        collector:
          endpoint: http://jaeger-collector.arch.svc.cluster.local:14268/api/traces
        samplingType: probabilistic
        samplingParam: 0.3
    accessLog:
      filePath: "/log/traefik.log"
      format: json
      bufferingSize: 200
      fields:
        defaultMode: keep
        headers:
          defaultMode: keep
    metrics:
      prometheus: {}
    ping:
      entryPoint: "traefik"

  health-check.yaml: |
    http:
      routers:
        health-check:
          rule: "Path(`/ping`)"
          entryPoints:
          - api
          - open
          service: health-check
      services:
        health-check:
          loadBalancer:
            servers:
            - url: http://localhost:8080/ping    

kind: ConfigMap
metadata:
  name: traefik
  namespace: microsvc
```

**Comment by sylr** [comment]
What kind of metrics are you using to generate your graph ? If using kubernetes try `container_memory_working_set_bytes`

**Comment by eaglewa** [comment]
This is my query statement:
avg (container_memory_usage_bytes{pod_name !~ "traefik-canary.*", container_name=~"traefik"}) / 1024 / 1024

**Comment by sylr** [comment]
Try `container_memory_working_set_bytes` instead of `container_memory_usage_bytes`.

**Comment by sylr** [comment]
Could you try adding `GODEBUG: madvdontneed=1` in `env` array of your container spec section of your deployment ?

**Comment by eaglewa** [comment]
I tried your advice:
![image](https://user-images.githubusercontent.com/1741081/70062566-3c529b80-1621-11ea-8515-79e5f6f165ca.png)
but it didn't work(in last 3 hours):
![image](https://user-images.githubusercontent.com/1741081/70062525-26dd7180-1621-11ea-801c-b18abe187df1.png)

**Comment by dtomcej** [comment]
Hello @eaglewa,

Can you please provide us a pprof profile as described in this other issue?

https://github.com/containous/traefik/issues/4245#issuecomment-443258329

It will show us how the CPU and memory usage is allocated.

You can attach the zip file directly to this issue.

Thanks!

**Comment by eaglewa** [comment]
How to access debug endpoints. I add `api=debug` to my config, but I can't to access it.
![image](https://user-images.githubusercontent.com/1741081/70120294-2ab3d700-16a7-11ea-839e-465d36d89b4b.png)
![image](https://user-images.githubusercontent.com/1741081/70120321-44edb500-16a7-11ea-8e46-0765adaa2ebd.png)

**Comment by ldez** [comment]
@eaglewa there is a bug with debug endpoint in the v2.1, I fixed that in #5937.

**Comment by eaglewa** [comment]
I get it:
[profile.zip](https://github.com/containous/traefik/files/3921560/profile.zip)

![pprof001](https://user-images.githubusercontent.com/1741081/70139195-e6d3c880-16cc-11ea-947d-f62a93360e55.png)

**Comment by dtomcej** [comment]
Hello @eaglewa,

The profile you attached only has the CPU profile.

Can you get the heap profile from `debug/pprof/heap`?

Thanks!

**Comment by eaglewa** [comment]
[heap.zip](https://github.com/containous/traefik/files/3925416/heap.zip)

**Comment by jbdoumenjou** [comment]
Hi @eaglewa,

Can you take pprof (zip with all metrics) at different times of the load test ?
Can you give more information (like k8s version, how many ingresses, services, etc...) so we can reproduce it ?
Note aside, the heap in the first pprof zip was on the traefik v1.

Thanks.

**Comment by eaglewa** [comment]
OK，my traefik is v2.1.0.rc-3, and the pprof is download by debug endpoint. I can't understand why it is v1

**Comment by jbdoumenjou** [comment]
In the first zip, when I tried to analyse the heap, the nodes was related to v1 code (negroni wrap) but the second pprof provided was on the v2 code.

**Comment by dduportal** [comment]
Hi @eaglewa , can you give us a bit more informations on the context of the ifnra as asked by @jbdoumenjou please ?

> Can you give more information (like k8s version, how many ingresses, services, etc...) so we can reproduce it ?


Thanks for the 2nd pprof by the way!

**Comment by eaglewa** [comment]
traefik version: 2.1.0-rc3 
dashboard info:
![image](https://user-images.githubusercontent.com/1741081/70292637-a6ce2c00-1819-11ea-9a20-42bd45ede8fb.png)
k8s version: 1.14.8(in aliyun)
here is 2 different time metric info(download by debug endpoint):
[pprof.zip](https://github.com/containous/traefik/files/3930246/pprof.zip)
traefik uptime: 1.8day
now memory used: 6.9GB(limited 8GB)
![image](https://user-images.githubusercontent.com/1741081/70292880-6fac4a80-181a-11ea-92fd-ca1c337b4704.png)

**Comment by jbdoumenjou** [comment]
Hi @eaglewa ,

Thanks for the pprof,
Could you give us your dynamic configuration (IngressRoute, middlewares, etc..) ?
What is the scenario used to load traefik ? (request/s, type of request, etc..)

Thanks.

**Comment by eaglewa** [comment]
My dynamic conf is in top of this page.
Here is one of my IngressRoute:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: benchmark-service
  namespace: microsvc
spec:
  entryPoints:
  - api
  routes:
  - match: PathPrefix(`/api/benchmark`)
    kind: Rule
    services:
    - name: benchmark-service
      port: 80
      kind: Service
```
![image](https://user-images.githubusercontent.com/1741081/70518842-ff812a00-1b75-11ea-8ed6-98406bbfdd0b.png)
