### ISSUE TITLE
2.1.0-rc2: Is sprig still supported in toml file?

### ISSUE THREAD

**Issue by ducmthai** [containous/traefik#5908]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Run traefik as a docker container with custom traefik.toml configuration file. The docker-compose file can be found below:
```
version: "3.7"

services:
  traefik:
    image: traefik:cantal
    container_name: traefik
    networks:
      - gateway
    ports:
      - "4200:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.toml:/traefik.toml:ro
    command:
      - "--file=/traefik.toml"

networks:
  gateway:
    driver: bridge
    name: traefik_gw
    ipam:
      config:
        - subnet: 172.71.0.1/16
```

### What did you expect to see?
Traefik is up and running

### What did you see instead?
```
Starting traefik ... done                                                                                                                                                  Attaching to traefik                                                                                                                                                       traefik    | 2019/11/27 23:54:56 command traefik error: Near line 0 (last key parsed ''): bare keys cannot contain '{'                                                    
traefik exited with code 1                
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.0-rc2, or using traefik:cantal
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
{{$ports := dict 2000 "2k" 3000 "3k"}}
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.dashboard]
    address = ":8080"    
{{range $port, $name := range $ports}}
  [entryPoints.{{$port}}]
    address = ":{{$port}}"
{{end}}

[provider]
    [providers.docker]
    exposedByDefault = true

[api]
  insecure = true
  dashboard = true
  debug = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
2019/11/27 23:54:56 command traefik error: Near line 0 (last key parsed ''): bare keys cannot contain '{'
```
