### ISSUE TITLE
Feature Request: Support CUE as configuration format

### ISSUE THREAD

**Issue by shibumi** [containous/traefik#5916]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

CUE would make the configuration a lot easier. 

The project would benefit of CUE in other parts as well (validation with schemes and fixed datatypes could be a lot more easier with CUE).

I really recommend this short CUE tutorial:

https://cuelang.org/docs/tutorials/tour/

I can imagine this as third-party config adapter package. CUE is a superset of json.  (Although the best part is the validation via schemes in CUE etc).

Here is a short example from YAML to CUE with a kubernetes deployment file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
```
Same in JSON:
```json
{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "hello-kubernetes"
  },
  "spec": {
    "replicas": 3,
    "selector": {
      "matchLabels": {
        "app": "hello-kubernetes"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "hello-kubernetes"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "hello-kubernetes",
            "image": "paulbouwer/hello-kubernetes:1.5",
            "ports": [
              {
                "containerPort": 8080
              }
            ]
          }
        ]
      }
    }
  }
}
```

Here is the equivalent in CUE:
```cue
// This is a comment
apiVersion: "apps/v1"
kind:       "Deployment"
metadata name: "hello-kubernetes"
spec: {
  replicas: 3
  selector matchLabels app: "hello-kubernetes"
  template: {
    metadata labels app: "hello-kubernetes"
    spec containers: [{
      name:  "hello-kubernetes"
      image: "paulbouwer/hello-kubernetes:1.5"
      ports: [{
        containerPort: 8080
      }]
    }]
  }
}
```
