### ISSUE TITLE
Basic swarm deployments don't work

### ISSUE THREAD

**Issue by venomone** [containous/traefik#5917]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Trying to use traefik as loadblancer for my Docker Swarm application.

### What did you expect to see?

At least a router or a service at the traefik dashbaord 

### What did you see instead?

Currently there are no Services or Routers available at the traefik dashboard, everything shows 0 and routing to my app container does not work

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v.2.0.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```arguments
    command:
        - "--providers.docker.endpoint=unix:///var/run/docker.sock"
        - "--providers.docker.swarmMode=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.docker.network=backend"
        - "--api.dashboard=true"
        - "--api.insecure=true"
        - "--entrypoints.web.address=:80"
```

```
  loadbalancer:
    image: traefik:v2.0.5
    command:
        - "--providers.docker.endpoint=unix:///var/run/docker.sock"
        - "--providers.docker.swarmMode=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.docker.network=backend"
        - "--api.dashboard=true"
        - "--api.insecure=true"
        - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure


  app:
    image: blabla_latest:latest
    command: bash -c blabla
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`mydomain.com`)"
      - "traefik.http.routers.app.entrypoints=web"
    networks:
      - backend
      - uplink
    deploy:
      replicas: 3
```
