### ISSUE TITLE
Panic in accesslog middleware

### ISSUE THREAD

**Issue by sylr** [containous/traefik#5922]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a kubernetes traefik instances which panics in the accessLog middleware

### Output of `traefik version`: (_What version of Traefik are you using?_)

2af8589a

```
v2.0.5-18-g2af8589a
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    # traefik.toml
    [log]
      level = "INFO"
      format = "json"
    [accessLog]
      format = "json"
      [accessLog.fields]
        defaultMode = "keep"
    [entryPoints.http]
      address = ":80"
    [entryPoints.http-internal]
      address = ":81"
    [entryPoints.https]
      address = ":443"
    [entryPoints.traefik]
      address = ":8080"
    [entryPoints.traefik-ext]
      address = ":8081"
    [providers.kubernetesIngress]
       ingressClass = "traefik-v2"
    [providers.kubernetesCRD]
    [providers.file]
      directory  = "/config/static"
      watch = true
    [api]
      insecure = true
      dashboard = true
      debug = true
    [metrics.prometheus]
      entryPoint = "traefik"
      buckets = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x58768f]
goroutine 18618 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:610
bufio.(*Writer).WriteString(0x0, 0x24d8bdd, 0x19, 0x40c306, 0x7f3ef6644460, 0x28c4885)
	/usr/local/go/src/bufio/bufio.go:691 +0x7f
net/http.(*expectContinueReader).Read(0xc0026fffe0, 0xc00252e000, 0x8000, 0x8000, 0x7f3ef6644460, 0x0, 0x10)
	/usr/local/go/src/net/http/server.go:888 +0x13b
github.com/containous/traefik/v2/pkg/middlewares/accesslog.(*captureRequestReader).Read(0xc00286a060, 0xc00252e000, 0x8000, 0x8000, 0x1f895c0, 0x1, 0xc00252e000)
	/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/capture_request_reader.go:11 +0x51
io.(*LimitedReader).Read(0xc003199d60, 0xc00252e000, 0x8000, 0x8000, 0x0, 0xc002f37800, 0x40a1b8)
	/usr/local/go/src/io/io.go:448 +0x63
io.copyBuffer(0x28cb600, 0xc00072dd40, 0x28c7ba0, 0xc003199d60, 0xc00252e000, 0x8000, 0x8000, 0x5, 0xc002f379b0, 0x5)
	/usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net.genericReadFrom(0x28c85e0, 0xc0001221b0, 0x28c7ba0, 0xc003199d60, 0x0, 0x0, 0x23dac00)
	/usr/local/go/src/net/net.go:625 +0x9a
net.(*TCPConn).readFrom(0xc0001221b0, 0x28c7ba0, 0xc003199d60, 0xc002f379e8, 0x40a48a, 0x20db0c0)
	/usr/local/go/src/net/tcpsock_posix.go:54 +0xe2
net.(*TCPConn).ReadFrom(0xc0001221b0, 0x28c7ba0, 0xc003199d60, 0x7f3ef4401338, 0xc0001221b0, 0x1)
	/usr/local/go/src/net/tcpsock.go:103 +0x4d
io.copyBuffer(0x28c85e0, 0xc0001221b0, 0x28c7ba0, 0xc003199d60, 0x0, 0x0, 0x0, 0x21d3980, 0x7f3ef4401201, 0x7f3ef4401318)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0xc000d8efc0, 0x28c7ba0, 0xc003199d60, 0x7f3ef4401318, 0xc000d8efc0, 0x1)
	/usr/local/go/src/net/http/transport.go:1599 +0x85
bufio.(*Writer).ReadFrom(0xc00206fa80, 0x28c7ba0, 0xc003199d60, 0x7f3ef44012f8, 0xc00206fa80, 0x1)
	/usr/local/go/src/bufio/bufio.go:713 +0x34a
io.copyBuffer(0x28c43a0, 0xc00206fa80, 0x28c7ba0, 0xc003199d60, 0x0, 0x0, 0x0, 0xc002f37c38, 0x40cb78, 0x20)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0xc0021b4fa0, 0x28c43a0, 0xc00206fa80, 0x28c7ba0, 0xc003199d60, 0x0, 0xc002f37ee0, 0xc000931f40)
	/usr/local/go/src/net/http/transfer.go:400 +0x6a
net/http.(*transferWriter).writeBody(0xc0021b4fa0, 0x28c43a0, 0xc00206fa80, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:359 +0x6da
net/http.(*Request).write(0xc002402a00, 0x28c43a0, 0xc00206fa80, 0x0, 0xc002a942d0, 0xc00286a2c0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:682 +0x6d3
net/http.(*persistConn).writeLoop(0xc000d8efc0)
	/usr/local/go/src/net/http/transport.go:2207 +0x1c8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1575 +0xb23
```
