### ISSUE TITLE
RedirectScheme Middleware CRD Not Working

### ISSUE THREAD

**Issue by ystan-** [containous/traefik#5924]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Create middleware

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
spec:
  redirectScheme:
    permanent: true
    scheme: https
```

Create TLS IngressRoute
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-site
spec:
  entryPoints:
  - web-secure
  routes:
  - kind: Rule
    match: Host(`my-site.com`)
    services:
    - name: my-site
      port: 8090
  tls:
    certResolver: default
    options: {}
```

Create Redirect IngressRoute
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-site
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`my-site.com`)
    services:
    - middlewares:
      - name: redirect
      name: my-site
      port: 8090
```
### What did you expect to see?
Browsing the site with http://my-site.com should redirect to https://my-site.com

### What did you see instead?
Browsing the site with http://my-site.com loaded the site content without redirecting

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
traefik:v2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Running in Kubernetes v1.16 as deployment with 2 replicas.
```
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --serversTransport.insecureSkipVerify=true
        - --accesslog=true
        - --entrypoints.web.Address=:8000
        - --entryPoints.web-secure.Address=:4443
        - --entryPoints.web.forwardedHeaders.insecure
        - --entryPoints.web-secure.forwardedHeaders.insecure
        - --providers.kubernetescrd
        - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
        - --certificatesresolvers.default.acme.tlschallenge=true
        - --certificatesresolvers.default.acme.email=__my_email__
        - --certificatesresolvers.default.acme.storage=/lets-encrypt-data/acme.json
        - --ping
        - --log=true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
Normal traffic. No errors.
