### ISSUE TITLE
Dynamic middlewares

### ISSUE THREAD

**Issue by liemle3893** [containous/traefik#5938]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Allow to select `provider` on router which is default of source of middlewares

```yaml
http:
  middlewares:
    rfs:
      headers:
        customRequestHeaders:
          X-Script-Name: "test" # Adds
          X-Custom-Request-Header: "AACAA" # Removes
        customResponseHeaders:
          X-Custom-Response-Header: "BBABB" # Set to empty to remove
  routers:
    web:
      middlewares:
        - "rfs@file"
```

Current: `rfs@file` is used by `web@file` - which is not available.
What I need: `rfs@file` is used by `web@docker`.

Suggest solution:
```yaml
http:
  routers:
    web:
      provider: "docker"
      middlewares:
        - "rfs@file"
```

**Comment by ldez** [comment]
Hello,

you just need to reference `rfs@file` on the router in the containers labels
https://docs.traefik.io/v2.0/routing/providers/docker/#routers

**Comment by liemle3893** [comment]
@ldez Yup. But the problem is I dont want to restart/recreate container.
In case of Consul. What I need is to fetch current config, and then add `"traefik.http.routers.web.middlewares=rfs@file"` into service tag and put new config.

Is this a little to much of work?

**Comment by ldez** [comment]
Another way to do that (without restart) is the use the chain middleware:

```yml
http:
  middlewares:
    rfs:
      headers:
        customRequestHeaders:
          X-Script-Name: "test" # Adds
          X-Custom-Request-Header: "AACAA" # Removes
        customResponseHeaders:
          X-Custom-Response-Header: "BBABB" # Set to empty to remove
    common:
      chain:
        middlewares:
          - rfs
          # - ...
```

and add a reference about the chain middleware on the container:

```yml
labels:
  - "traefik.http.routers.myrouter.middlewares=common@file"
```
