### ISSUE TITLE
HTTPS redirect not working

### ISSUE THREAD

**Issue by marvincaspar** [containous/traefik#5947]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Setup letsencrypt using http challenge and use force https redirect

### What did you expect to see?

Call website with http I want to get a redirect to https

### What did you see instead?

No redirect to http

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
  traefik:
    image: traefik:v2.0
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.http.acme.httpchallenge=true"
      - "--certificatesresolvers.http.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.http.acme.email=<email>"
      - "--certificatesresolvers.http.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    volumes:
      - acme:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx:alpine
    networks:
      - web
    labels:
      traefik.docker.network: web
      traefik.enable: true

      traefik.http.routers.<name>.tls.certresolver: http
      traefik.http.routers.<name>.rule: Host(`<name>.com`,`www.<name>.com`)
      traefik.http.routers.<name>.entrypoints: web

      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.routers.<name>.middlewares: https-redirect@docker
      traefik.http.routers.<name>-secured.rule: Host(`<name>.com`,`www.<name>.com`)
      traefik.http.routers.<name>-secured.entrypoints: websecure
      traefik.http.routers.<name>-secured.tls: true
```
