### ISSUE TITLE
File Watch Doesn't Work

### ISSUE THREAD

**Issue by guiguan** [containous/traefik#595]
I am using Traefik on my osx docker installation with following config:

```toml
#...
[file]
filename = "/etc/traefik/rules.toml"
watch = true

#...
```

After I changed and saved `rules.toml`, the configuration however did not hot-reload, and I had to restart the Traefik docker container.
