### ISSUE TITLE
Dashboard Web UI additionally loads on different ports than what is specified

### ISSUE THREAD

**Issue by mcrio** [containous/traefik#5951]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Dashboard is listening on port 8443, TLS true.
Loading the dashboard on `https://domain.com:8443/dashboard/` works as expected.

Static configuration related to dashboard.
```
      - --api.dashboard=true
      - --api=true
      - --api.insecure=false
      - --entryPoints.dboard.address=:8443
```
Other entry points defined in static configuration
```
      - --entryPoints.web.address=:80
      - --entryPoints.web-secure.address=:443
```

Dynamic configuration:
```
        - "traefik.http.routers.traefik_https.rule=Host(`domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        - "traefik.http.routers.traefik_https.service=api@internal"
        - "traefik.http.routers.traefik_https.entrypoints=dboard"
        - "traefik.http.routers.traefik_https.tls=true"

```

### What did you expect to see?

Loading the dashboard on any other port than 8443 should not load the dashboard ui:
- `http://domain.com:80/dashboard/`  Should not load the Dashboard UI
- `https://domain.com:443/dashboard/` Should not load the Dashboard UI

### What did you see instead?

- `http://domain.com:80/dashboard/`  Loads the Dashboard UI and static assets
- `https://domain.com:443/dashboard/` Loads the Dashboard UI and static assets

The dashboard UI is loaded but it is not functional as it tries to fetch API data on those ports, but it does not load as API is on the specified port 8443.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik 2.1.0-rc3
```

**Comment by dduportal** [comment]
Hi @mcrio , I cannot reproduce with the following example:

```yml
version: '3'

services:

  traefik:
    image: traefik:v2.1.0-rc3
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.dashboard=true
      - --api=true
      - --api.insecure=false
      - --entryPoints.dboard.address=:8443
      - --entryPoints.web.address=:80
      - --entryPoints.web-secure.address=:443
      - --providers.docker=true
    labels:
      - traefik.http.routers.traefik_https.rule=Host(`domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - "traefik.http.routers.traefik_https.service=api@internal"
      - "traefik.http.routers.traefik_https.entrypoints=dboard"
      - "traefik.http.routers.traefik_https.tls=true"
```

```bash
$ docker-compose up -d
$ curl "https://domain.com:443/dashboard/" -k -v -o /dev/null
...
< HTTP/2 404
...
$ curl "https://domain.com:8443/dashboard/" -k -v -o /dev/null
...
< HTTP/2 200
...
```

Could you:
- enable Traefik debug log and paste here so we can verify what configuration Traefik retrieves?
- share the result of curl command, to remove the "HTTP caching" potential issues?
