### ISSUE TITLE
Traefik continues to offer the self-signed certificate even if I have a let's encrypt certificate

### ISSUE THREAD

**Issue by GreyXor** [containous/traefik#5955]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

My traefik configuration works very well. I have my let's encrypt certificate. Everything is OK

### What did you expect to see?

Even if I have a let's encrypt certificate. Traefik still continues to offer the self-signed certificate.
I can see both certificates when I use https://www.ssllabs.com/ 
The let's encrypt one and the self-signed one. My website is working and my browser using the good certificate but i just want make traefik only serve the let's encrypt certificate and forget/remove the traefik self-signed one

### What did you see instead?

Both certificate (let's encrypt and self-signed)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.6
Codename:     montdor
Go version:   go1.13.4
Built:        2019-12-02T17:24:31Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints.web]
    address = ":80"

[entryPoints.web-secure]
    address = ":443"

[api]
  dashboard = false
  insecure = false

[providers]
  [providers.docker]
    exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic_conf.toml"

[certificatesResolvers.SECRET-certResolver.acme]
  storage = "/letsencrypt/acme.json"
  email = "SECRET"
  keytype = "EC256"
  [certificatesResolvers.SECRET-certResolver.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0

```

```toml
[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
      scheme = "https"

  [http.middlewares.securityHeaders.headers]
    stsSeconds = 31536000
    stsIncludeSubdomains = true
    stsPreload = true

[tls.options]
  [tls.options.TLSOptions]
    minVersion = "VersionTLS12"
    sniStrict = true
```
```yml    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.SECRET.entrypoints=web"
      - "traefik.http.routers.SECRET.rule=Host(`SECRET.SECRET.net`)"
      - "traefik.http.routers.SECRET.middlewares=redirect@file"
      - "traefik.http.routers.SECRET-https.entrypoints=web-secure"
      - "traefik.http.routers.SECRET-https.rule=Host(`SECRET.SECRET.net`)"
      - "traefik.http.routers.SECRET-https.tls=true"
      - "traefik.http.routers.SECRET-https.middlewares=redirect@file, securityHeaders@file"
      - "traefik.http.routers.SECRET-https.tls.certresolver=SECRET-certResolver"
      - "traefik.http.routers.SECRET-https.tls.domains[0].main=*.SECRET.net"
      - "traefik.http.routers.SECRET-https.tls.domains[0].sans=SECRET.net"
      - "traefik.http.routers.SECRET-https.tls.options=TLSOptions@file"

```
