### ISSUE TITLE
traefik.enabled=true does not work with exposedByDefault false

### ISSUE THREAD

**Issue by kopax** [containous/traefik#5972]
I am following the documentation and try to get started for the first time with traefik, so no idea if I misunderstood or if this is actually a bug.

I am not able to test the following assumption:

> Expose containers by default through Traefik. If set to false, containers that don't have a `traefik.enable=true` label will be ignored from the resulting routing configuration.

### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I want to verify https://docs.traefik.io/providers/docker/#exposedbydefault and it says: 

> Expose containers by default through Traefik. If set to false, containers that don't have a `traefik.enable=true` label will be ignored from the resulting routing configuration.

I have created traefik with `docker-compose.yml`: 

```yml
services:
  reverse-proxy:
    image: traefik:v2.1
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml

```

And in `trafic.yaml`:

```
log:
  level: "DEBUG"


entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

api:
  insecure: true # enable WEB UI
  dashboard: true
  debug: true

providers:
  # providersThrottleDuration: 42
  docker:
    watch: true
    exposedByDefault: false
```

### What did you expect to see?

I expect to see the service coming in the UI

### What did you see instead?

I don't see the service in the UI.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.1

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
reverse-proxy_1  | time="2019-12-09T14:58:24Z" level=debug msg="Provider event received {Status:start ID:5588fdc08140ef2a9b80d1b8089d087dd6c6d43f1cdd390a73b19418c3888971 From:containous/whoami Type:container Action:start Actor:{ID:5588fdc08140ef2a9b80d1b8089d087dd6c6d43f1cdd390a73b19418c3888971 Attributes:map[com.docker.compose.config-hash:34af101b3078c50a768fe05bc8396f1ace30e517e3037ab8b413e5a681dd89ac com.docker.compose.container-number:1 com.docker.compose.oneoff:False com.docker.compose.project:testing com.docker.compose.service:whoami com.docker.compose.version:1.24.1 image:containous/whoami name:testing_whoami_1 traefik.enabled:true traefik.http.routers.whoami.rule:Host(`whoami.docker.localhost`)]} Scope:local Time:1575903504 TimeNano:1575903504815060203}" providerName=docker
reverse-proxy_1  | time="2019-12-09T14:58:24Z" level=error msg="Skip container whoami-testing: field not found, node: enabled" providerName=docker
```

It work fine if I comment `# exposedByDefault: false` and `# - "traefik.enabled=true"`
