### ISSUE TITLE
Traefik http to https scheme 404

### ISSUE THREAD

**Issue by Themesaul** [containous/traefik#5982]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Redirect a web from http to https

### What did you expect to see?

Put "http://foo.bar" and redirect to "https://foo.bar" in the browser

### What did you see instead?

Put "http://foo.bar" and see "404 page not found" error 

### Output of `traefik version`: 

v2.0.5

### `Static file`: 

```
[entryPoints.web]
  address = ":80"

[entryPoints.websecure]
  address = ":443"

[certificatesResolvers.lets.acme]
  email = "info@foo.bar"
  storage = "acme.json"
  [certificatesResolvers.lets.acme.httpChallenge]
    entryPoint = "web"
```

### `Dynamic file`: 

```
[http.routers]
  [http.routers.Router-0]
    entryPoints = ["web", "websecure"]
    rule = "Host(`foo.bar`)"
    service = "dashboard"
    middlewares = ["redirect"]
     [http.routers.Router-0.tls]
        certResolver = "lets"

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"
    permanent = true


[http.services]
  [http.services.dashboard.loadBalancer]
    [[http.services.dashboard.loadBalancer.servers]]
      url = "http://192.168.2.23:80"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ClovisGauzy** [comment]
@Themesaul you need to configure two separate routers, one for http who redirect to https, and one for https :

```toml
[http.routers]
  [http.routers.Router-0-insecure]
    entryPoints = "web"
    rule = "Host(`foo.bar`)"
    service = "dashboard"
    middlewares = ["redirect"]

  [http.routers.Router-0]
    entryPoints = "websecure"
    rule = "Host(`foo.bar`)"
    service = "dashboard"
    [http.routers.Router-0.tls]
      certResolver = "lets"

…
```
