### ISSUE TITLE
Enable http to https middleware by default 

### ISSUE THREAD

**Issue by kopax** [containous/traefik#5993]
# Feature

I have not found a way in traefik v2.1 to enable http to https middleware by default if https is enabled for a vhost.

So far, I have to set 4 labels for each container:

```yaml
     labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
```

I find it too verbose, especially if you have many containers, this can be more error prone.

### Purposed solution

Allowing this static configuration to enable http to https redirection for all https service by default:

```yaml

middlewares:
  redirect-to-https:
    redirectsheme:
      scheme: "https"

routers:
  redirs:
    rule: "hostregexp(`{host:.+}`)" 
    entrypoint: "web"
    middlewares: "redirect-to-https"
```
