### ISSUE TITLE
marathon and traefik 2.1 dial wrong IP and return 504 gateway timeout 

### ISSUE THREAD

**Issue by kopax** [containous/traefik#6001]
Bug

### What did you do?

I have deployed the following app on marathon: 

```yaml
{
  "id": "/whoami",
  "cpus": 0.1,
  "mem": 256.0,
  "instances": 3,
  "labels": {
    "traefik.enable": "true",
    "traefik.http.routers.whoami.rule": "Host(`traefik-testing.mydomain.com`)",
    "traefik.http.routers.whoami.entrypoints": "web"
  },
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "containous/whoami",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 80,
          "hostPort": 0,
          "name": "http-api",
          "protocol": "tcp"
        }
      ]
    }
  },
  "readinessChecks": [
    {
      "name": "readinessCheck",
      "protocol": "HTTP",
      "path": "/",
      "portName": "http-api",
      "intervalSeconds": 30,
      "timeoutSeconds": 10,
      "httpStatusCodesForReady": [200],
      "preserveLastResponse": false
    }
  ],
  "healthChecks": [
    {
      "path": "/",
      "portIndex": 0,
      "protocol": "HTTP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 10,
      "timeoutSeconds": 30,
      "maxConsecutiveFailures": 3
    }
  ]
}
```

This is the `docker-compose.yml` used to start the traefik container on `localhost`, that can reach marathon on the LAN through `http://192.168.0.22:8080`:

```yaml
version: '3'
services:
  reverse-proxy:
    image: traefik:v2.1
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./letsencrypt:/letsencrypt"
```

### What did you expect to see?

I expect to be able to succeed this command: 

```
curl -H 'Host: traefik-testing.mydomain.com' -L http://localhost
```

### What did you see instead?

Curl response:

```
Gateway Timeout
```

traefik debug log: 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

This is my `traefik.yaml`

```yaml
log:
  level: "DEBUG"
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
providers:
  marathon:
    endpoint: "http://192.168.0.22:8080"
    watch: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
reverse-proxy_1  | time="2019-12-11T13:45:56Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 212.95.74.75:31400: i/o timeout"
```

**Note: the IP it dial as nothing to do with my LAN, it is owned by my ISP and it is not even my WAN address.**

On the dashboard, IP are correctly guessed and all are reachable by telnet from traefik host.

I am out of idea, it simply does not work with marathon, any idea what is failing here? 

Thanks and best!
