### ISSUE TITLE
OR-Chained middlewares

### ISSUE THREAD

**Issue by kolaente** [containous/traefik#6007]
### Do you want to request a *feature* or report a *bug*?

Feature

Feature

### What did you expect to see?

It would be cool if traefik could support chaining middlewares with or instead of executing them one after one. Currently, there is the [chain middleware](https://docs.traefik.io/middlewares/chain/), which executes middlewares one after the other. The thing I have in mind would be to execute the first one in the list, if that fails execute the second one etc. A problem here might be a middleware does not "fail" or "succeed", it either calls the next one or does not iirc.

A bit more context on the use case:
We have one site which we want to secure using ip whitelist and basic auth, either one should work. If a user accesses the site not on the ip whitelist, it should need to complete the basic auth.

I'm not sure if a general way of doing this is a good idea or if the use case is too specific and thus, a custom thing would be better suited.

I've discussed this a bit in https://github.com/justinas/alice/issues/50

**Comment by alexandru-enciu** [comment]
Hi,

I had a simillar situation, needing to access the site via basic auth only if the client's IP is not in a whitelist. You can accomplish this with a trick:
1. Create a dummy route in your application that will always ask for basic auth.
2. Create another dummy route, that will return an HTML page, that will do a redirect from Javascript to the path at point 1.
3. Add a Traefik errors middleware, that captures 403 errors and the service is the path created at point 2.
4. Add a Traefik route for this path with a rule that matches the path and with a chained middleware: Basic auth and redirect to site's home path
5. Add a Traefik route with a check if the request has "Authorization" header. Attach the basic auth middleware to this route.
6. Add your usual Traefik route. Attach to this route a chained middleware, with the errors middleware at point 3 and the IP whitelist middleware. Attention, the order is important: the first middleware in the sequence must be the errors one, so it will capture 403 error codes from the IP whitelist middleware.

Hope this helps.

**Comment by jayheinlein** [comment]
Adding another use-case. Sadly, I don't think the above workaround covers me.

We have multiple clients, each having access to a subset of our services. We want to or-chain multiple whitelists depending on which client(s) have access to which service. This would allow both easy readability and single source-of-truth for each whitelist instead of updating all service whitelists any time we need to change a client whitelist.

For instance -
- Client A can access service 1 and 2
- Client B can only access service 2
- Service 1 has a route that uses the Client A whitelist
- Service 2 has a route that uses Client A whitelist or Client B whitelist.

Currently, we have to update every service's whitelist when a client's IPs change as they must be manually merged into a single whitelist per service. It would be very convenient to change the client's whitelist and have the OR middleware reference them by name.

**Comment by alexandru-enciu** [comment]
> Currently, we have to update every service's whitelist when a client's IPs change as they must be manually merged into a single whitelist per service.

Are you using by any chance Docker in your infrastructure?

**Comment by jayheinlein** [comment]
Yup, we're using kubernetes (v 1.11 currently). So these are all managed with the Middleware and IngressRoute CRDs

**Comment by alexandru-enciu** [comment]
There is a workaround then, depending on how you construct the final whitelist for service. For example, you could use 2 Environment variables, like $IP_CLIENTA and $IP_CLIENTB where you store the IPs. Then, create another 2 Environment variables $IP_SERVICE1=$IP_CLIENTA and $IP_SERIVCE2=$IP_CLIENTA,$IP_CLIENTB. Finally, use $IP_SERVICE1 or $IP_SERVICE2 in your middleware configuration.

**Comment by jayheinlein** [comment]
That's essentially what we're doing currently. Our deployment system does the merge of the whitelist when a service is deployed. However, if any of those whitelists change then we have to trigger the system to edit every Middleware with the new ips. If we were able to create an or-chain then we would only have to edit the client's whitelist Middleware in a single location and all the or-chains would simply point at those specific Middlewares, causing an immediate change for all services whitelisting the client.

**Comment by zingmane** [comment]
> Hi,
> 
> I had a simillar situation, needing to access the site via basic auth only if the client's IP is not in a whitelist. You can accomplish this with a trick:
> 
>     1. Create a dummy route in your application that will always ask for basic auth.
> 
>     2. Create another dummy route, that will return an HTML page, that will do a redirect from Javascript to the path at point 1.
> 
>     3. Add a Traefik errors middleware, that captures 403 errors and the service is the path created at point 2.
> 
>     4. Add a Traefik route for this path with a rule that matches the path and with a chained middleware: Basic auth and redirect to site's home path
> 
>     5. Add a Traefik route with a check if the request has "Authorization" header. Attach the basic auth middleware to this route.
> 
>     6. Add your usual Traefik route. Attach to this route a chained middleware, with the errors middleware at point 3 and the IP whitelist middleware. Attention, the order is important: the first middleware in the sequence must be the errors one, so it will capture 403 error codes from the IP whitelist middleware.
> 
> 
> Hope this helps.

There's also another solution/workaround for this problem I want to mention  -> [simple-trick-to-bypass-basic-auth](https://community.containo.us/t/traefik-v2-simple-trick-to-bypass-basic-auth/2012/4)
For a simple scenario the solution to set up a second route with additional `HeadersRegexp` rule is doing the trick.

Anyway, it would be great to have a flexible and generic way of conditional or OR-chaining middlewares.

**Comment by kolaente** [comment]
Since we now have plugins (since traefik 2.3) this is something that could be implemented using a plugin.
I did a quick search and found this which looks promising: https://github.com/kingjan1999/traefik-plugin-exception-authbasic

Havent't tried it yet, but it looks like a very good solution for my use case and maybe others.

Ping @kingjan1999

**Comment by markfqs** [comment]
A couple of other uses cases:

I use authelia in a separate container providing authentication thru Traefik Forward Auth middleware. As the container might not be healthy (or still not deployed) I would like traefik 'fails-back' or 'chain-or middleware' to either AuthBase middleware or even restrict access to a set of IPs.

I though about CircuitBreaker middleware but this is focused on service health, not middleware availability.

**Comment by jr0dd** [comment]
Is there any possibility on a fix for this? Like stacking multiple ipwhitelist middlewares in a chain? Let's say I just try adding the rfc1918 (internal ips) whitelist to the cloudflare (external ips) whitelist. Well this is causing some sort of loop within traefik and removing them from both whitelists fixed it. It appears that not only can you not have multiple whitelists in a chain, but you also can not have those same ip's in multiple whitelists.

Here are my middlewares. Services I expose to the world I also want to be able to access internally also, which currently is not possible. 

external-auth chain (ak-outpost is my forwardauth middleware)
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: external-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: cloudflare-ips
      - name: security-ak-outpost-authentik-embedded-outpost@kubernetescrd
```

cloudflare-ip whitelist
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 108.162.192.0/18
      - 131.0.72.0/22
      - 141.101.64.0/18
      - 162.158.0.0/15
      - 172.64.0.0/13
      - 173.245.48.0/20
      - 188.114.96.0/20
      - 190.93.240.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
 ```

internal-auth chain:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: rfc1918-ips
      - name: security-ak-outpost-authentik-embedded-outpost@kubernetescrd
  ```

internal-ip whitelist
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
```

**Comment by rtribotte** [comment]
Hello @jr0dd,

> It appears that not only can you not have multiple whitelists in a chain, but you also can not have those same ip's in multiple whitelists.

To clarify, I tried to use two different `ipWhiteList` middlewares with the same configuration (with and without an explicit `Chain` middleware to wrap them) on the same router, and it is working.
So, if I didn't miss something, both of your statements are not accurate.

Nonetheless, chaining `ipWhiteList` middlewares doesn’t make much sense and this issue proposal could indeed help if there is a need for declaring different sets of IPs, hence by declaring multiple `ipWhiteList` middlewares.
Otherwise, it's recommended to declare the set of allowed IPs in one place (one middleware), as the constraints should be the same in all `ipWhiteList` middlewares in a chain for a request to be able to pass through.

However, it seems that your use case can be solved by IP-based routing that has been introduced in v2.5, please take a look a the [rule documentation](https://doc.traefik.io/traefik/v2.5/routing/routers/#rule) and specifically at the new `ClientIP` rule.

**Comment by jr0dd** [comment]
> Hello @jr0dd,
> 
> > It appears that not only can you not have multiple whitelists in a chain, but you also can not have those same ip's in multiple whitelists.
> 
> To clarify, I tried to use two different `ipWhiteList` middlewares with the same configuration (with and without an explicit `Chain` middleware to wrap them) on the same router, and it is working.
> So, if I didn't miss something, both of your statements are not accurate.
> 
> Nonetheless, chaining `ipWhiteList` middlewares doesn’t make much sense and this issue proposal could indeed help if there is a need for declaring different sets of IPs, hence by declaring multiple `ipWhiteList` middlewares.
> Otherwise, it's recommended to declare the set of allowed IPs in one place (one middleware), as the constraints should be the same in all `ipWhiteList` middlewares in a chain for a request to be able to pass through.
> 
> However, it seems that your use case can be solved by IP-based routing that has been introduced in v2.5, please take a look a the [rule documentation](https://doc.traefik.io/traefik/v2.5/routing/routers/#rule) and specifically at the new `ClientIP` rule.

Thanks for your reply. I was not aware of that new middleware. That may work. I have no clue why having the same ip's in more than 1 `ipWhiteList` are now causing looping with my forwardAuth software. I have worked with one of the devs for many hours on this. As soon as I removed the rfc1918-ips from being bundled in the cloudflare-ips auth started flowing again as it should. The cookie was not returning as it should.

**Comment by ddtmachado** [comment]
For some of the use cases described here [this PR](https://github.com/traefik/traefik/pull/8857) seems like a good fit, maybe?

**Comment by rwjack** [comment]
This is still not working:

eg. I have 20 routers, with different IPs whitelisted, but all of them have the same management IPs whitelisted.

The way traefik currently works, I have to create 20 whitelists, with all management IPs + special IPs for that router:
```
  routers:
    first-router:
      rule: Host(`domain.tld`)
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
        - first-whitelist # <-----------
      service: first

  middlewares:
    first-whitelist:
      ipWhiteList:
        sourceRange:
          - "1.1.1.1" # mgmt IP 1
          - "2.2.2.2" # mgmt IP 2
          - "3.3.3.3" # special request IP 3 for "first" service
          ...
```
And imagine having this for 20 routers, if I want to add a device to the management IPs whitelist, I have to edit all 20 routers.

Instead of having a single management whitelist and special ones on a per case basis. Like this:
```
  routers:
    first-router:
      rule: Host(`domain.tld`)
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
        - management-whitelist # <--------
        - first-whitelist # <-----------
      service: first

  middlewares:
    management-whitelist:
      ipWhiteList:
        sourceRange:
          - "1.1.1.1" # mgmt IP 1
          - "2.2.2.2" # mgmt IP 2
          ...

    first-whitelist:
      ipWhiteList:
        sourceRange:
          - "3.3.3.3" # special use case IP 3 for "first" service
        ...
```
