### ISSUE TITLE
Warning for ignored namespace in cross-provider context is too noisy

### ISSUE THREAD

**Issue by sbuzonas** [containous/traefik#6033]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Define an `IngressRoute` with KubernetesCRD provider as follows:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: ingress
spec:
  entryPoints:
  - traefik
  routes:
  - kind: Rule
    match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    services:
    - kind: TraefikService
      name: api@internal
```

### What did you expect to see?

Relatively quiet logs with level for standard operation with `--log.level=WARN`

### What did you see instead?

A constant stream of warnings about the namespace "ingress" being ignored.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64
pod "traefik" deleted
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
    - --entryPoints.traefik.address=:9000
    - --entryPoints.web.address=:8000
    - --entryPoints.websecure.address=:8443
    - --api.dashboard=true
    - --ping=true
    - --providers.kubernetescrd
    - --log.level=WARN
    - --accesslog=true
    - --global.checknewversion=true
    - --global.sendanonymoususage=true
    - --providers.kubernetesingress
```

There is a section in the code somewhere that suppresses the namespace if it is `default`.   A current workaround is to explicitly specify a namespace of default for cross-provider references.

IMO this is incorrect behavior. It should suppress the messages if a namespace is not provided, or possibly if the namespace matches that of where the resource is defined.

Another thought to consider is reducing the level, warning is pretty high for something benign
