### ISSUE TITLE
SSL issue with autoscaling

### ISSUE THREAD

**Issue by vukhanhtruong** [containous/traefik#6035]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I'm using Helm chart to install Traefik on my cluster with Let's Encrypt wildcard certificate and autoscaling. SSL works fine until running a load test (using apache-benchmark), the certificate was being invalidated after spinning up the new pods.

### What did you expect to see?
SSL persistence

### Output of `traefik version`: (_What version of Traefik are you using?_)
 

```
1.7.20
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Helm

```yaml
autoscaling:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60

ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  logging: true
  email: "email@gmail.com"
  challengeType: dns-01
  staging: false
  domains:
    enabled: true
    domainsList:
      - main: "*.mydomain.com"
  dnsProvider:
    name: dreamhost
    dreamhost:
      DREAMHOST_API_KEY: KEY   
  persistence:
    enabled: false
```

Please help me out. Thank you very much.
