### ISSUE TITLE
Support for Sticky sessions across multiple ExternalNames in Kubernetes CRD

### ISSUE THREAD

**Issue by kpeiruza** [containous/traefik#6038]
### Feature Request
I've added support for Kubernetes CRD ExternalName https support on a pull request.

After testing it, I still get round-robin for ExternalNames. 

In our case, we've two standalone servers which might be LoadBalanced from a Traefik running on Kubernetes.

Our IngressRoute looks like this:
```yml
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`my.service.com`)
    services:
    - name: nexttest01
      passHostHeader: true
      port: 443
      sticky:
        cookie: {}
    - name: nexttest02
      passHostHeader: true
      port: 443
      sticky:
        cookie: {}
 ```

Feature

### What did you expect to see?
It looks like stickiness is treated on a per-service basis, so, we'd love to see Stickiness across several service endpoints.

That way, if your connection is redirected to ExternalName "nexttest01" you'll always be served by that ExternalName. Right now, it makes round-robin between both services, nexttest01 and nexttest02.

IMHO that's a nice feature to have, so we can centralize all our https-terminations and load-balancing in this Kubernetes CRD Traefik deployment.

Thank you!
