### ISSUE TITLE
Question/Proposal for defaultRouter or defaultMiddlewares for Service Discovery Providers

### ISSUE THREAD

**Issue by sodabrew** [containous/traefik#6040]
### Do you want to request a *feature* or report a *bug*?

Feature

### Where I see a gap in functionality

I'm trying out Traefik 2.1 now that the Consul Catalog provider has been merged in #5395.

I can pull in Services defined in my Consul Catalog, and the `defaultRule` template works well to map a named service from a Host header. Easy stuff is easy so far.

What I want to do now is define a set of common Middlewares for thinks like CORS headers, HTTPS redirects, IP whitelist/blacklist. It seems like I can do this inside a Traefik config file with Routers and Middlewares but only for Services that are defined inside the Traefik config file.

I do not want to duplicate my middleware configs into hundreds of services' tags in Docker or Consul, so I think maybe I'm missing something here, but... is it the case that I _cannot_ connect a Middleware defined in a traefik.yml config file to a Service that is created from a Service Discovery mechanism?

### What I'd like to see to close the gap

 I would like to have something like `defaultRouter: [specific router from http section]` or `defaultMiddlewares: [list of middlewares defined in http section]` ala `defaultRule` that already exists for service discovery providers.

One issue that comes to mind with `defaultRouter` is how that would mix with `defaultRule` because each Service needs its own rules, such as a Host header match. Adding `defaultMiddlewares` first seems like less work for this reason?

**Comment by sodabrew** [comment]
Example of what I have in mind:

```
## traefik.yml

providers:
  consulCatalog:
    endpoint:
      address: http://localhost:8500
    constraints: "Tag(`public`)"
    defaultRule: "Host(`{{ .Name }}.example.com`)"
    defaultRouter: myrouter

http:
  routers:
    myrouter:
      middlewares:
        - usefuldefaults
  middlewares:
    usefuldefaults:
      chain:
        middlewares:
          - cors 
          - retries
    retries:
      retry:
       attempts: 4
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowOrigin: "origin-list-or-null"
        accessControlMaxAge: 100
        addVaryHeader: true
        sslRedirect: true
        customFrameOptionsValue: SAME-ORIGIN
```
