### ISSUE TITLE
the service \"traefik-ingress-service@file\" does not exist" entryPointName=web-secure routerName=base-router1@file 

### ISSUE THREAD

**Issue by iwz2099** [containous/traefik#6045]
How does Traefik 2.1 configure the default SSL certificate in Kubernetes?
Where are the examples of SSL configurations issued by myself in Kubernetes?

I read the official documents are acme related configuration。
I refer to the configuration here： https://github.com/containous/traefik/tree/06df6017dfc4464b81106e22bd7fcc61de5c3786/integration/fixtures/k8s

My SSL certificate is a secret type, and configmap is mounted to the pod.

```
kubectl create secret tls traefik-cert --key=test.cn.key --cert=test.cn.pem  -n kube-system
```

my traefik.yaml :
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
      [entryPoints.web-secure]
        address = ":443"
    [providers.file]
      filename = "/dynamic-config/dynamic-conf.toml"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-conf
  namespace: kube-system
data:
  dynamic-conf.toml: |
    [http.middlewares]
      [http.middlewares.redirect-to-https.redirectScheme]
        scheme = "https"

    [http.routers]

      [http.routers.base-router1]
        entrypoints = [ "https" ]
        middlewares = [ "redirect-to-https" ]
        service = "traefik-ingress-service"
        [http.routers.base-router1.tls]
           certResolver = "default"
           [[http.routers.base-router1.tls.domains]]
             main = "test.cn"
             sans = ["*.test.cn"]

      #[http.routers.traefik]
      #routerTemplate = "base-router1"
      #rule = "Host(`traefik-cicd.test.cn`)"
      #service = "traefik-ingress-service"

    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/ssl/tls.crt"
          keyFile  = "/ssl/tls.key"
    [tls]
      [[tls.certificates]]
        certFile = "/ssl/tls.crt"
        keyFile = "/ssl/tls.key"
        stores = ["default"]
    [tls.options]
      [tls.options.default]
        maxVersion = "VersionTLS13"
        sniStrict = true
      [tls.options.maxtls12]
        maxVersion = "VersionTLS12"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      #tolerations:
      #- operator: "Exists"
      nodeSelector:
        node-role.kubernetes.io/traefik: "true"
      volumes:
      - name: ssl
        secret:
          secretName: traefik-cert
      - name: config
        configMap:
          name: traefik-conf
      - name: dynamic-config
        configMap:
          name: traefik-dynamic-conf
      containers:
      - image: traefik:v2.1
        name: traefik-ingress-lb
        volumeMounts:
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        - mountPath: "/dynamic-config"
          name: "dynamic-config"
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 500m
            memory: 600Mi
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
        - name: websecure
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --configfile=/config/traefik.toml
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --api.insecure=true
        - --providers.kubernetescrd
        - --providers.kubernetesingress=true
        - --api
        - --api.dashboard=true
        - --accesslog
        #- --certificatesresolvers.default.acme.tlsChallenge=true
        #- --certificatesResolvers.default.acme.email="email@gmail.com"
        #- --certificatesResolvers.default.acme.storage="acme.json"
        #- --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
```

Finally, the following exception occurred：
```
# kubectl  get pod -n kube-system |grep tra
traefik-7cfd87d6bd-fqm88                     1/1     Running   0          66s
traefik-7cfd87d6bd-qgtrk                     1/1     Running   0          66s
traefik-7cfd87d6bd-xljgx                     1/1     Running   0          66s
#kubectl  logs -f traefik-7cfd87d6bd-xljgx -n kube-system
time="2019-12-16T13:17:57Z" level=error msg="the service \"traefik-ingress-service@file\" does not exist" entryPointName=web-secure routerName=base-router1@file
time="2019-12-16T13:17:57Z" level=error msg="the router base-router1@file uses a non-existent resolver: default"
```
