### ISSUE TITLE
store the default tls of traefik inside kubernetes secret

### ISSUE THREAD

**Issue by fcomte** [containous/traefik#6057]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I am using traefik as a kubernetes ingress. I am using a custom certificate authority.
I would like to use a wildcard certificate for the default certificate of traefik. I would love to use kubernetes secret for storing this default certificate. If It is not possible yet, I would love to see this feature.

**Comment by dtomcej** [comment]
Hello @fcomte,

If you create your own wildcard certificate signed by your CA, and create your own secret, you can then mount the secret into the traefik pod, and use it as the default certificate:

https://docs.traefik.io/v2.1/https/tls/#default-certificate

Traefik re-creates its self-signed certificate every time it restarts, so storing that certificate in a secret wouldn't accomplish much, and it is not possible to use an external CA to sign the generated cert.

Does this solve your issue?

**Comment by bradjones1** [comment]
I think the request is more along the lines of, you would generate a default certificate for, for instance, a wildcard record using something like cert-manager, and then Traefik could use it. The question then becomes how does Traefik reload the default certificate when it is renewed. Kubernetes secrets loaded in as mounted files are only refreshed on container start, so while that is an option to start with, if the container outlives the validity of the default certificate, a restart must occur to pick up the renewed files.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by k3a** [comment]
If you don't like setting `tls.secretName` for every `IngressRoute`, it is now possible to also dynamically configure default TLS secret using `TLSStore` CRD this way:

```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: myDefaultSecretName
```

then you can just set an empty object on the tls key of IngressRoute to make the route work with TLS and use default TLS store with the configured TLS secret:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-tls-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    # ...
  tls: {}
```

TLSStore support was added by #6270 pull request :)

**Comment by bradjones1** [comment]
For others who are mixing their configuration sources - you can reference this object, like in much of the other Traefik 2.x contexts, by namespacing with an `@kubernetescrd` suffix. E.g. in your entrypoint config:

```toml
[entryPoints]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]
      options = "default@kubernetescrd"
```
