### ISSUE TITLE
Infinite redirects for admin UI

### ISSUE THREAD

**Issue by fgarcia** [containous/traefik#6060]
### What did you do?

I wanted to serve the admin pages of some services I use (Consul, RabbitMQ, Jenkins, Portainer...)

### What did you expect to see?

I can reverse-proxy all the admin pages mentioned above, except the one for Traefik

For example with Consul I get

```console
$ curl -LI http://consul.localhost | less

HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Date: Wed, 18 Dec 2019 14:20:04 GMT
Location: /ui/

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 6847
Content-Type: text/html; charset=utf-8
Date: Wed, 18 Dec 2019 14:20:04 GMT
Last-Modified: Wed, 18 Dec 2019 09:54:48 GMT
```
### What did you see instead?

```console
$ curl -LI http://traefik.localhost | less

Content-Length: 18
Content-Type: text/plain; charset=utf-8
Date: Wed, 18 Dec 2019 14:21:02 GMT
Location: http://traefik.localhost/dashboard/

HTTP/1.1 308 Permanent Redirect
Content-Length: 18
Content-Type: text/plain; charset=utf-8
Date: Wed, 18 Dec 2019 14:21:02 GMT
Location: http://traefik.localhost/dashboard/dashboard/

HTTP/1.1 308 Permanent Redirect
Content-Length: 18
Content-Type: text/plain; charset=utf-8
Date: Wed, 18 Dec 2019 14:21:02 GMT
Location: http://traefik.localhost/dashboard/dashboard/dashboard/

HTTP/1.1 308 Permanent Redirect
Content-Length: 18
Content-Type: text/plain; charset=utf-8
Date: Wed, 18 Dec 2019 14:21:02 GMT
Location: http://traefik.localhost/dashboard/dashboard/dashboard/dashboard/
:curl: (47) Maximum (50) redirects followed
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
global:
  sendAnonymousUsage: false

log:
  #level: "DEBUG"
  level: "INFO"
  format: "common"

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

  # https://containo.us/blog/back-to-traefik-2-0-2f9aa17be305/
  # [entrypoints.mongo-port]
  #   address = ":27017"

serversTransport:
  # insecureSkipVerify = true
  RootCAs: 
    - "/data/certs/ca/cloudflare_origin_rsa.pem" 

providers:
  # This is how you tell traefik that it has to get the dynamic config from a config file
  # Note that the path is the path to the file inside Docker, not insider your machine!
  # If you want do use Docker itself for this check traefik docs!
  file:
    directory: "/etc/traefik/providers.d"
    watch: true

  docker: 
    exposedbydefault: false

api:
  # enable the web UI
  insecure: true
  dashboard: true
```

```yml
http:
  routers:
    traefik:
      rule: "Host(`traefik.localhost`)"
      service: traefik

    consul:
      rule: "Host(`consul.localhost`)"
      service: consul

    rabbit:
      rule: "Host(`rabbit.localhost`)"
      service: rabbit
 
  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://localhost:8080

    consul:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8500

    rabbit:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:15672

```
