### ISSUE TITLE
invalid node traefik: no child

### ISSUE THREAD

**Issue by nicholaspearson** [containous/traefik#6062]
When running traefik in a docker swarm as follows, I get the following error:

`2019/12/18 16:32:58 command traefik error: invalid node traefik: no child`

My docker-compose consists of the following:
```yaml
services:
  traefik:
    image: traefik
    command:
      - "--api"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=stack_traefik-public"
      - "--entrypoints.http.address=:80"
    networks:
      - traefik-private
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        - "traefik.http.routers.traefik_http.service=api@internal"
        - "traefik.http.routers.traefik_http.entrypoints=http"
```

I had everything working fine on v1.7, however, when updating to v2 and updating the options, the error just won't go away.

Running Digitalocean CoreOS 2303.3.0 (stable) docker swarm (3 nodes), 1 leader and 2 agents.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by nicholaspearson** [comment]
I'm not sure what else you want?

You have the OS version, compose file, the rest of it is out the box.

Using the latest image.

**Comment by ldez** [comment]
The issue template is **important** and must be followed.

You have to click on the template link provided by the bot and edit your issue.

**Comment by ldez** [comment]
your :-1: will not help you

**Comment by nicholaspearson** [comment]
> your 👎 will not help you

There is enough information in the issue to get the problem resolved.....

**Comment by ldez** [comment]
I don't reproduce: clean your stack and restart.

Friends don't let friends use `latest`: I recommend to use an explicit version `traefik:v2.1.1` (or at least `traefik:v2.1`)

**Comment by nicholaspearson** [comment]
> I don't reproduce: clean your stack and restart.
> 
> Friends don't let friends use `latest`: I recommend to use an explicit version `traefik:v2.1.1` (or at least `traefik:v2.1`)

I've destroyed it and started and again with no luck.

I've updated to use v2.1.1, with no luck.

I even minified the options to just `--api`.

**Comment by ldez** [comment]
With your configuration:
```
--providers.docker.exposedbydefault=false
```

and with your labels, the labels are not parsed because the following label is missing:
```
- "traefik.enable=true"
```

But your error:
```
2019/12/18 16:32:58 command traefik error: invalid node traefik: no child
```
Means that you have an invalid label.

So there are something missing in your issue.

The template is really helpful :wink:

**Comment by nicholaspearson** [comment]
> With your configuration:
> 
> ```
> --providers.docker.exposedbydefault=false
> ```
> 
> and with your labels, the labels are not parsed because the following label is missing:
> 
> ```
> - "traefik.enable=true"
> ```
> 
> But your error:
> 
> ```
> 2019/12/18 16:32:58 command traefik error: invalid node traefik: no child
> ```
> 
> Means that you have an invalid label.
> 
> So there are something missing in your issue.
> 
> The template is really helpful 😉

My docker-compose is above, that is all that people need to see.

Which label is invalid?

**Comment by nicholaspearson** [comment]
I don't know how you "tried to reproduce the issue" because it was caused by:
```- /dev/null:/traefik.toml```

Please close.

**Comment by nicholaspearson** [comment]
I have done this:

```yaml
portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - traefik-private
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.backend=stack_portainer"
        - "traefik.frontend.rule=Host:swarm.domain.co.uk"
        - "traefik.port=9000"
        - "traefik.protocol=http"
        - "traefik.docker.network=stack_traefik-private"
```

However, it doesn't pickup the backend/frontends
