### ISSUE TITLE
gRPC Load Balance in Kubernetes doesn't work

### ISSUE THREAD

**Issue by imans777** [containous/traefik#6069]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
We use traefik as our API Gateway in kubernetes. There are services behind it, that use gRPC for their connections, and each service is assigned to several pods.
We used the dynamic config mentioned in the docs for gRPC and they connected as expected.
However, when we dived deeper, we saw that all the requests are being routed to the same pod, as if traefik creates one connection to the service (and therefore, one connection to one pod) and keeps that for all the incoming requests and doesn't load balance them at all!

### What did you expect to see and What did you see instead?

We tried different scenarios to narrow down the problem:
We configed the client to create multiple connections, etc. using both [ghz tool](https://ghz.sh/) and different python channels and threads, but they worked all the same, routing to same pod of service. So we assumed that this is not a client-side problem.

We used them for normal HTTP/1 requests and they worked. So we assumed this is a problem in relation to HTTP2, more specifically, gRPC.

We used these methods again to make request to the service itself directly and omit traefik in-between, and that load was balanced between pods of that service. So we assumed that it's not kubernetes' load balancing problem, but traefik's.

We then tried to define that service multiple time in dynamic config, as a cheat you could say to make it work for now, like below:
```toml
[[http.services.echo_service.loadBalancer.servers]]
  url =  "h2c://echo:50051"
[[http.services.echo_service.loadBalancer.servers]]
  url = "h2c://echo:50051"
[[http.services.echo_service.loadBalancer.servers]]
  url = "h2c://echo:50051"
```
note: echo is a light code that returns its host name (pod name) and has a prometheus metric server to see the count of incoming requests, etc.
But again, functionality the same, i.e. the incoming_request metric of one pod would change, but the others wouldn't.
We then defined multiple services, i.e. `echo1`, `echo2` and `echo3` and used them in config above. We saw that here the load was balanced between 2 pods. Considering we had 3 services, we hunched that it's total random and unreliable for production, let alone its non-feasibility for bunch of pods. 

From all above, we concluded that traefik's load balancing over gRPC doesn't work.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Official docker image from docker hub, `traefik:2.1.1`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Our dynamic config:
```toml
[http]
    [http.routers]
        [http.routers.echo_service]
        entryPoints = ['web']
        rule = "PathPrefix(`/echo.`)"
        service = "echo_service"
[http.services]
    [http.services.echo_service]
        [http.services.echo_service.loadBalancer]
            [[http.services.echo_service.loadBalancer.servers]]
                url =  "h2c://echo:50051"
```
I believe the command arguments and the static config is not important here, since we know that base things work. But if needed, I can provide them.

Thanks.
