### ISSUE TITLE
Wildcard certificate request 'duplicate' certificates (KubernetesCRD)

### ISSUE THREAD

**Issue by markus-seidl** [containous/traefik#6084]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have multiple IngressRoute, for example:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nexus
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`nexus.domain.ca`)
      kind: Rule
      services:
        - name: nexus
          port: 8081
  tls:
    certResolver: default
```

In order to have a wildcard certificate for all domains, I added a dummy IngressRoute like this:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dummy
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`imanunusedroutethatwillneverbehit.domain.ca`)
      kind: Rule
      services:
        - name: traefik
          port: 8080
  tls:
    certResolver: default
    domains:
      - main: "domain.ca"
        sans:
          - "*.domain.ca"
```

### What did you expect to see?

I expect Traefik to execute a dns challenge for domain.ca,*.domain.ca.

### What did you see instead?

Instead I see traefik also request nexus.domain.ca (among many others) additionally to the wildcard certificate.
I would expect Traefik to group these requests if there is a wildcard present.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Static:
```yaml
defaultEntryPoints:
  - "https"
api:
  dashboard: true
  insecure: true
log:
  level: INFO
accessLog: {}
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
providers:
  kubernetesCRD: {}
  file:
    filename: "/config/dynamic.yaml"
metrics:
  prometheus: {}
certificatesResolvers:
  default:
    acme:
      email: mail@mail.de
      storage: "/certs/acme.json"
      dnsChallenge:
        provider: httpreq
        delayBeforeCheck: 360
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
```

Dynamic
```yaml
# Redirect to https
# - https://community.containo.us/t/a-global-http-https-redirection/864/4
# - https://community.containo.us/t/global-http-to-https-redirect-in-v2/1658/3
http:
  routers:
    http-catchall:
      entryPoints:
        - "http"
      rule: "HostRegexp(`{host:[a-z-.]+}`)"
      middlewares:
        - redirect-http-to-https
      service: "noop"
  middlewares:
    redirect-http-to-https:
      redirectScheme:
        scheme: https
        permanent: true
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://google.de"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment]
Hello,

As the 2 ingressRoutes can be apply at different time, it's not possible "to group" requests.

You have to define the `tls.domains` for each ingressRoute who need the wildcard certificates.

So it's the expected behavior.

**Comment by markus-seidl** [comment]
Hi!

I don't understand you answer, as configuration can always be changed "at different times".
I think this behaviour is some kind of unsymmetrical, as Traefik can use wildcard certificates in the acme.json (and would not request nexus.domain.ca). Upon initial request it would request both at the same time.
Also putting this under _every_ IngressRoute would limit the usefulness of wildcard certificates, IMHO.

**Comment by tbcdns** [comment]
I think I am experiencing somehow the opposite behavior.
I am using Traefik 2.1.1 with a file provider

I first added a wildcard router:
```yaml
  wildcard:
    rule: "HostRegexp(`{subdomain:.+}.mydomain.com`)"
      priority: 1
      entryPoints:
        - https
      service: myService
      tls:
        certResolver: default
        domains:
          - main: "*.mydomain.com"
```

Later on I wanted to have a dedicated certificate for a specific subdomain:

```yaml
    specific:
      rule: "Host(`specific.mydomain.com`)"
      priority: 2
      entryPoints:
        - https
      service: specificService
      tls:
        certResolver: default
        domains:
          - main: "specific.mydomain.com"
```

I would expect traefik to execute a new dns challenge for `specific.mydomain.com` but `*.mydomain.com` is used. 

Any advices about how to force traefik to use `specific.mydomain.com`?
