### ISSUE TITLE
Router 'scheme' not working when matching service is of type 'externalName' running SSL

### ISSUE THREAD

**Issue by jeanfabrice** [containous/traefik#6091]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configure a Kubernetes service targeting an externalName on an SSL port :
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: synology
spec:
  type: ExternalName
  externalName: synology.domain.com
  ports:
    - name: https
      port: 5001
````

Configure an ingressroute to use this service:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: synology
  namespace: synology
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`synology.apps.domain.com`)
    kind: Rule
    services:
    - name: synology
      port: 5001
      scheme: https
  tls:
    certResolver: mycertresolver
    domains:
      - main: apps.domain.com
        sans:
          - "*.apps.domain.com"
```

### What did you expect to see?
Browsing https://synology.apps.domain.com/, my expectation was to display the website living at https://synology.domain.com:5001/

### What did you see instead?
An error message : 
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

It seems that #5062 didn't help in that case.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: traefik-system
data:
  traefik.toml: |
    [global]
      checkNewVersion = false
      sendAnonymousUsage = false

    [serversTransport]
      insecureSkipVerify = true

    [log]
      level = "DEBUG"

    [accessLog]
      format = "json"

    [ping]
      entryPoint = "web"
      manualRouting = true

    ################################################################
    # API configuration
    ################################################################
    [api]
    dashboard = true
    debug = true

    ################################################################
    # Metrics configuration
    ################################################################
    [metrics]
      [metrics.prometheus]
        entryPoint = "web"
        buckets = [0.1,0.3,1.2,5.0]
        addServicesLabels = true
        addEntryPointsLabels = true
        manualRouting = true

    ################################################################
    # Entrypoint configuration
    ################################################################
    [entryPoints]
      [entryPoints.web]
      address = ":8000"
      [entryPoints.websecure]
      address = ":4443"

    ################################################################
    # Kubernetes configuration
    ################################################################
    # Enable Kubernetes IngressCRD Provider.
    [providers.kubernetesCRD]

    ################################################################
    # Letsencrypt configuration
    ################################################################
    [certificatesResolvers]
      [certificatesResolvers.mycertresolver]
        [certificatesResolvers.mycertresolver.acme]
        email = "*****@domain.com"
        storage = "/acme/acme.json"
          [certificatesResolvers.mycertresolver.acme.dnsChallenge]
          provider = "route53"
          delayBeforeCheck = 5
```

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
