### ISSUE TITLE
Dashboard Secure Docs

### ISSUE THREAD

**Issue by Serrvosky** [containous/traefik#6098]
Hello everyone,

I'm trying to apply secure dashboard in a Kubernetes scenario, but something it's not ok on docs I guess.

This is my config:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
spec:
  basicAuth:
    secret: traefikusers
---
apiVersion: v1
kind: Secret
metadata:
  name: traefikusers
  namespace: default

data:
  users: |2
    dGVzdDokYXByMSRINnVza2trVyRJZ1hMUDZld1RyU3VCa1RycUU4d2ov
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  routes:
  - match: PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
```

But I'm getting this log:
```
time="2019-12-27T15:31:49Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2019-12-27T15:31:50Z" level=error msg="Error while reading basic auth middleware: failed to load auth credentials: secret 'default/traefikusers' not found" providerName=kubernetescrd middlewareName=default-traefik-auth
time="2019-12-27T15:31:50Z" level=error msg="Error while reading basic auth middleware: failed to load auth credentials: secret 'default/traefikusers' not found" middlewareName=default-traefik-auth providerName=kubernetescrd
```
 When i try to see if the secret is there with kubectl it works, but looks like traefik doesn't find it, and I guess it's because traefik is trying to find `secret default/traefikusers` instead of `secret traefikusers`

Anyone with this error too?

Thanks
