### ISSUE TITLE
Multiple port and site support

### ISSUE THREAD

**Issue by mc388** [containous/traefik#61]
It would be nice if traefik can handle multiple ports and connect different web applications to different port, such as [docker-gen](https://github.com/jwilder/docker-gen) works.

At the moment I work wich `docker-gen` and my docker-compose file from each of my application looks like this:

```
web:
  image: nginx:latest
  ports:
    - "50020:80"
    - "50021:443"
  environment:
    VIRTUAL_HOST: demo-project
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./nginx/ssl:/etc/nginx/ssl
  volumes_from:
    - php

php:
  image: mc388/docker-php:latest
  ...
```

The `docker-gen` maps this application to port 50020 and 50021. Via the `VIRTUAL_HOST` parameter the proxy knows to which port the request is forwarded. 

An other feature could be to config separate ssl certs for each web application.

If traefik can handle something like this, it would be very nice.
