### ISSUE TITLE
Request hosting example for Traefik v2

### ISSUE THREAD

**Issue by mbhoek** [containous/traefik#6102]
### Do you want to request a *feature* or report a *bug*?

Feature (Documentation)

### Introduction

I host a dockerized nginx website on https://www.DOMAIN.com using Traefik v2.

I want http://DOMAIN.com, https://DOMAIN.com and https://www.DOMAIN.com to be redirected to https://www.DOMAIN.com using Traefik v2.

### What did you expect to see?

A documented example on https://docs.traefik.io/ describing this use case. 

A very basic example is available at https://docs.traefik.io/user-guides/docker-compose/basic-example/ but this only covers hosting http without any redirection. Additional examples covering https are available at https://docs.traefik.io/user-guides/docker-compose/acme-tls/ (et al), but how to combine those with the basic example was (to me) not obvious.

### What did I come up with?

After some trial and error I came up with these labels for the the docker container:

```
labels:
  traefik.enable: 'true'
  traefik.http.routers.DOMAIN.rule: 'Host(`DOMAIN.com`)'
  traefik.http.routers.DOMAIN.entryPoints: 'http'
  traefik.http.routers.DOMAIN.middlewares: 'redirect-to-https'
  traefik.http.routers.DOMAIN-ssl.rule: 'Host(`DOMAIN.com`)'
  traefik.http.routers.DOMAIN-ssl.entryPoints: 'https'
  traefik.http.routers.DOMAIN-ssl.tls.certResolver: 'letsencrypt'
  traefik.http.routers.DOMAIN-ssl.middlewares: 'redirect-to-www'
  traefik.http.routers.www-DOMAIN.rule: 'Host(`www.DOMAIN.com`)'
  traefik.http.routers.www-DOMAIN.entryPoints: 'http'
  traefik.http.routers.www-DOMAIN.middlewares: 'redirect-to-https'
  traefik.http.routers.www-DOMAIN-ssl.rule: 'Host(`www.DOMAIN.com`)'
  traefik.http.routers.www-DOMAIN-ssl.entryPoints: 'https'
  traefik.http.routers.www-DOMAIN-ssl.tls.certResolver: 'letsencrypt'
  traefik.http.middlewares.redirect-to-https.redirectScheme.scheme: 'https'
  traefik.http.middlewares.redirect-to-www.redirectRegex.regex: '^https?://(?:www\.)?(.*)$$'
  traefik.http.middlewares.redirect-to-www.redirectRegex.replacement: 'https://www.$$1'
```

1) this assumes a certificate resolver called 'letsencrypt' is already setup elsewhere
2) this does not cover the use case where multiple TLDs (eg `org`, `net`) need to be redirected to the same main site

It works for me, but I would very much welcome a simpler way of configuring Traefik v2 for the described use case; or at least some confirmation in the documentation that this is the way to go.
