### ISSUE TITLE
Handle Redirects 301/302

### ISSUE THREAD

**Issue by solipsist01** [containous/traefik#6114]
### Do you want to request a *feature* or report a *bug*?
Hello. I don't know if this is a feature or a bug.
I would say a bug.

### What did you do?
I'm trying to reverse proxy a VMware Virtual Center appliance.

```
  http:
    routers:
      to-vmwarevc:
        entryPoints:
        - websecure
        rule: "Host(`vmwarevc.hostname.com`)"
        tls: {}
        service: vmwarevc-service
    services:
      vmwarevc-service:
        loadBalancer:
          passHostHeader:
          servers:
          - url: https://internalvc.domain.local
```

### What did you expect to see?

After landing on the initial page, i choose for the html client.
after that i get redirected to https://vmwarevc.hostname.com/ui/login
from there i get a 302 redirect to https://vmwarevc. **hostname.com** /websso/SAML2/SSO/vsphere.local?SAMLRequest=zVRdb9owFH3fr4j(somereallylonghash)

### What did you see instead?

I get redirected to https://internalvc. **domain.local** /websso/SAML2/SSO/vsphere.local?SAMLRequest=zVRdb9owFH3fr4j(somereallylonghash) instead of the proxied URL

Request header

```
Host: vmwarevc.hostname.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.9) Gecko/20100101 Goanna/4.4 Firefox/68.9 PaleMoon/28.8.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://vmwarevc.hostname.com/ui/
Cookie: <redacted>
Connection: keep-alive
```

Response Header

```
HTTP/2.0 302 Found
X-Firefox-Spdy: h2
cache-control: no-store
content-length: 0
date: Tue, 31 Dec 2019 08:28:47 GMT
location: https://virtualcenter.domain.local/websso/SAML2/SSO/vsphere.local?SAMLRequest=zVRdb9owFH3fr4j(somereallylonghash)
pragma: no-cache
server: Anonymous
strict-transport-security: max-age=30758400; includeSubDomains
x-frame-options: deny
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64
