### ISSUE TITLE
Not able to change maxconn backend configuration from marathon labels

### ISSUE THREAD

**Issue by migueleliasweb** [containous/traefik#612]
This is the example confif from https://docs.traefik.io/toml/

I could not find a way to change maxconn from marathon labels.

Tried:
- traefik.backend.maxconn with value amount=1000
- traefik.backend.(mybackendname).maxconn with value amount=1000
- traefik.backend.maxconn.amount with value 1000

None of them worked. =/

What I did wrong ?

[Example toml from docs]

``` toml
# rules
[backends]
  [backends.backend1]
    [backends.backend1.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.backend1.servers.server1]
    url = "http://172.17.0.2:80"
    weight = 10
    [backends.backend1.servers.server2]
    url = "http://172.17.0.3:80"
    weight = 1
  [backends.backend2]
    [backends.backend1.maxconn]
      amount = 10
      extractorfunc = "request.host"
```
