### ISSUE TITLE
Followed "quick start" but http "whoami" returns 404, what is wrong ?

### ISSUE THREAD

**Issue by PackElend** [containous/traefik#6120]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

followed [Quick Start](https://docs.traefik.io/getting-started/quick-start/#quick-start) in the docs

### What did you expect to see?

> `curl -H Host:whoami.docker.localhost http://127.0.0.1`
> Shows the following output:
> ```
> Hostname: a656c8ddca6c
> IP: 172.27.0.3
> #...
> ```

### What did you see instead?

```
root@Ubuntu18:~# curl -v -H Host:whoami.docker.localhost http://127.0.0.1
* Rebuilt URL to: http://127.0.0.1/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host:whoami.docker.localhost
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Mon, 30 Dec 2019 13:15:19 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 127.0.0.1 left intact
```
and

```
root@Ubuntu18:~# curl -v -H Host:whoami.docker.localhost http://172.20.0.3
* Rebuilt URL to: http://172.20.0.3/
*   Trying 172.20.0.3...
* TCP_NODELAY set
* Connected to 172.20.0.3 (172.20.0.3) port 80 (#0)
> GET / HTTP/1.1
> Host:whoami.docker.localhost
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 30 Dec 2019 11:22:42 GMT
< Content-Length: 168
< Content-Type: text/plain; charset=utf-8
<
Hostname: e3c222e6993f
IP: 127.0.0.1
IP: 172.20.0.3
RemoteAddr: 172.20.0.1:58072
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.58.0
Accept: */*
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
root@Ubuntu18:/var/traefik# docker exec -t traefik traefik version
Version:      2.0.7
Codename:     montdor
Go version:   go1.13.5
Built:        2019-12-09T17:51:21Z
OS/Arch:      linux/amd64
```
but  
```
root@Ubuntu18:~# docker run traefik version
Unable to find image 'traefik:latest' locally
latest: Pulling from library/traefik
89d9c30c1d48: Already exists
275722d2e7f6: Already exists
88ca2a78572e: Pull complete
3bf623a84bbb: Pull complete
Digest: sha256:a87b61f3254d03c4fcc0b994e2cb7af89abba8178f1fbec3bce3f4bdc080f8a6
Status: Downloaded newer image for traefik:latest
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
<details>
  <summary>docker-compose.yml</summary>
   
```
   version: "3.7"
   
   services:
     traefik-reverse-proxy:   
       # The official v2.0 Traefik docker image
       image: traefik:v2.0
       container_name: "traefik"       
       command:
         # --providers.docker  : tells Traefik to listen to docker 
         # --log.level=DEBUG : set debug level 
         # --api : Enable api/dashboard. (Default: false) / (set the docker endpoint to speak to docker's API)
         # --api.dashboard : Activate dashboard. (Default: true)
         # --api.insecure=true Enables the web UI / Traefik will listen on port 8080 by default for API request. / Activate API directly on the entryPoint named traefik. (Default: false) --> port '8080'v= entryPoint 'traefik', overrides --api
         # --api.debug=true Enable additional endpoints for debugging and profiling. (Default: false)
         --api=true
         --api.dashboard
         --api.insecure=true 
         --api.debug=true
         --providers.docker      
         --log.level=DEBUG    
         --accesslog=true    
         --accesslog.filepath=/var/traefik/access.log    
         #--entryPoints.myweb.address=:80    
         #--providers.docker.endpoint=unix:///var/run/docker.sock    
       ports:
         # The HTTP port
         - "80:80"
         # The Web UI (enabled by --api.insecure=true)
         - "8080:8080"
       volumes:
         # So that Traefik can listen to the Docker events
         - /var/run/docker.sock:/var/run/docker.sock
         - ./log:/var/traefik
       networks:
         - traefik
   
      #Tiny Go webserver that prints os information and HTTP request to output
     whoami:
       image: "containous/whoami"
       container_name: "whoami"
       labels:
         #- "traefik.enable=true"
         #- "traefik.docker.network=bridge_proxy_traefikv2"
         - "traefik.http.routers.whoami.rule=Host(`whoami.fairbnb.community`)"
         #- "traefik.http.routers.whoami.entrypoints=myweb"
         #- "traefik.http.services.whoami.loadBalancer.server.port=80"
       networks:
         - traefik
   
   
   networks:
     traefik:
       external:
         name: bridge_proxy_traefikv2
```
</details>

<details>
  <summary>API/rawdata - formatted</summary>

```
{
  "routers":
  {  
    "traefik-reverse-proxy-traefik@docker":
    {
      "service":"traefik-reverse-proxy-traefik","rule":"Host(`traefik-reverse-proxy-traefik`)",
   	  "status":"enabled","using":["http","traefik"]
    }
    ,"whoami@docker":
    { 
      "service":"whoami-traefik","rule":"Host(`whoami.fairbnb.community`)",
	  "status":"enabled","using":["http","traefik"]
    }
  },
  "services":
  {
    "traefik-reverse-proxy-traefik@docker":
	{
	  "loadBalancer":
	  {
	    "servers":[
		{
		  "url":"http://172.20.0.4:80"
		}],
	    "passHostHeader":true
	  },
      "status":"enabled","usedBy":["traefik-reverse-proxy-traefik@docker"],
	  "serverStatus":
	  {
	    "http://172.20.0.4:80":"UP"
	  }
	},
	"whoami-traefik@docker":
	{
	  "loadBalancer":
	  {
	    "servers":[
		{
		  "url":"http://172.20.0.3:80"
		}],
		"passHostHeader":true
	  },
      "status":"enabled","usedBy":["whoami@docker"],
	  "serverStatus":
	  {
		"http://172.20.0.3:80":"UP"
	  }
	}
  }
}
```
</details>

<details>
  <summary>docker lables - image versions of traefik and whoami etc.</summary>

```
root@Ubuntu18:/var/traefik# docker ps --no-trunc  --format "table {{.Names}}::{{.Command}}::{{.Ports}}::{{.Networks}}::{{.Labels}}" | awk -F:: -f docker_ps-pretty-print.awk
   NAMES          | COMMAND                                      | PORTS                  | NETWORKS               | LABELS
   whoami         | /whoami                                      | 80/tcp                 | bridge_proxy_traefikv2 | com.docker.compose.config-hash=04d3ea1924e36df000380782ee3ef53bc6ba4ea3f4fd64399471c7c289a116d0
                  |                                              |                        |                        | com.docker.compose.container-number=1
                  |                                              |                        |                        | com.docker.compose.oneoff=False
                  |                                              |                        |                        | com.docker.compose.project=traefik
                  |                                              |                        |                        | com.docker.compose.service=whoami
                  |                                              |                        |                        | com.docker.compose.version=1.24.1
                  |                                              |                        |                        | traefik.http.routers.whoami.rule=Host(`whoami.fairbnb.community`)
   traefik        | --accesslog.filepath=/var/traefik/access.log | 0.0.0.0:80->80/tcp     | bridge_proxy_traefikv2 | com.docker.compose.config-hash=c8103750c5e975be3a182063d6ecc48a3f7590d5fa3ed5730c784dc2eff23eeb
                  | --accesslog=true                             | 0.0.0.0:8080->8080/tcp |                        | com.docker.compose.container-number=1
                  | --api.dashboard                              |                        |                        | com.docker.compose.oneoff=False
                  | --api.debug=true                             |                        |                        | com.docker.compose.project=traefik
                  | --api.insecure=true                          |                        |                        | com.docker.compose.service=traefik-reverse-proxy
                  | --api=true                                   |                        |                        | com.docker.compose.version=1.24.1
                  | --log.level=DEBUG                            |                        |                        | org.opencontainers.image.description=A modern reverse-proxy
                  | --providers.docker                           |                        |                        | org.opencontainers.image.documentation=https://docs.traefik.io
                  | /entrypoint.sh                               |                        |                        | org.opencontainers.image.title=Traefik
                  |                                              |                        |                        | org.opencontainers.image.url=https://traefik.io
                  |                                              |                        |                        | org.opencontainers.image.vendor=Containous
                  |                                              |                        |                        | org.opencontainers.image.version=v2.0.7
 ```
</details>

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

<details>
  <summary>log etnries of the traefik docker | docker logs --details  --tail all  traefik </summary>

   ```
   root@Ubuntu18:/var/traefik# docker logs --details  --tail all  traefik | awk '{print $1 "\t" $2  "\t" substr($0, length($1) + length($2) + 4  ) }'
   time="2019-12-31T17:23:49Z"     level=info      msg="Configuration loaded from flags."
   time="2019-12-31T17:23:49Z"     level=info      msg="Traefik version 2.0.7 built on 2019-12-09T17:51:21Z"
   time="2019-12-31T17:23:49Z"     level=debug     msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true,\"debug\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"/var/traefik/access.log\",\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}}}"
   time="2019-12-31T17:23:49Z"     level=info      msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
   time="2019-12-31T17:23:49Z"     level=debug     msg="No default certificate, generating one"
   time="2019-12-31T17:23:49Z"     level=info      msg="Starting provider aggregator.ProviderAggregator {}"
   time="2019-12-31T17:23:49Z"     level=debug     msg="Start TCP Server" entryPointName=http
   time="2019-12-31T17:23:49Z"     level=debug     msg="Start TCP Server" entryPointName=traefik
   time="2019-12-31T17:23:49Z"     level=info      msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":15000000000}"
   time="2019-12-31T17:23:49Z"     level=debug     msg="Provider connection established with docker 19.03.5 (API 1.40)" providerName=docker
   time="2019-12-31T17:23:49Z"     level=error     msg="port is missing" providerName=docker container=discourse-main-90c80be9cb355d83097c34c033bb39c8dd1614cb3673746a8ad626464099b03a
   time="2019-12-31T17:23:49Z"     level=debug     msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"traefik-reverse-proxy-traefik\":{\"service\":\"traefik-reverse-proxy-traefik\",\"rule\":\"Host(`traefik-reverse-proxy-traefik`)\"},\"whoami\":{\"service\":\"whoami-traefik\",\"rule\":\"Host(`whoami.fairbnb.community`)\"}},\"services\":{\"traefik-reverse-proxy-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.20.0.3:80\"}],\"passHostHeader\":true}},\"whoami-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.20.0.4:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=traefik-reverse-proxy-traefik@docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami@docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining routerName=traefik-reverse-proxy-traefik@docker entryPointName=http serviceName=traefik-reverse-proxy-traefik
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating load-balancer" entryPointName=http serviceName=traefik-reverse-proxy-traefik routerName=traefik-reverse-proxy-traefik@docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating server 0 http://172.20.0.3:80" serverName=0 routerName=traefik-reverse-proxy-traefik@docker entryPointName=http serviceName=traefik-reverse-proxy-traefik
   time="2019-12-31T17:23:49Z"     level=debug     msg="Added outgoing tracing middleware traefik-reverse-proxy-traefik" middlewareName=tracing middlewareType=TracingForwarder entryPointName=http routerName=traefik-reverse-proxy-traefik@docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating middleware" middlewareType=Pipelining entryPointName=http routerName=whoami@docker serviceName=whoami-traefik middlewareName=pipelining
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating load-balancer" serviceName=whoami-traefik entryPointName=http routerName=whoami@docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating server 0 http://172.20.0.4:80" serviceName=whoami-traefik entryPointName=http routerName=whoami@docker serverName=0
   time="2019-12-31T17:23:49Z"     level=debug     msg="Added outgoing tracing middleware whoami-traefik" entryPointName=http middlewareName=tracing middlewareType=TracingForwarder routerName=whoami@docker
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
   time="2019-12-31T17:23:49Z"     level=debug     msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
   time="2019-12-31T17:23:49Z"     level=debug     msg="No default certificate, generating one"
   ```
</details>
   
<details>
  <summary>log entries of the whoami | docker logs --details  --tail all  whoami </summary>

   ```
   root@Ubuntu18:/var/traefik# docker logs --details  --tail all  whoami
    Starting up on port 80
   ```
</details>
