### ISSUE TITLE
Doc about k8s CRD session sticky

### ISSUE THREAD

**Issue by zyf0330** [containous/traefik#6133]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

PR #5711 added support for k8s CRD session sticky. But I cannot find any doc to set it.

**Comment by zyf0330** [comment]
After some test, I find solution code. This is example used in `IngressRoute`.
```
  - match: PathPrefix(`/ping`)
    kind: Rule
    services:
    - name: name
      port: 8888
      sticky:
        cookie:
          httpOnly: true
```

There are also some examples of `kind: TraefikService`at docs/content/reference/dynamic-configuration/kubernetes-crd.yml for advanced usage.
Still find nothing in official website doc.
