### ISSUE TITLE
Why the default value of passHostHeader in loadBalancer is false when I use file provider

### ISSUE THREAD

**Issue by dcalsky** [containous/traefik#6142]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```yaml
  services:
    yunsu-server:
      loadBalancer:
        sticky:
          cookie: {}
        servers:
          - url: http://yunsu-server:5000/
```
At first, I didn't set the passHostHeader, because official document tells me the passHostHeader default value is `true`. But, I found passHostHeader is not set as `true`, instead of `false` in the dashboard and result.

```yaml
  services:
    yunsu-server:
      loadBalancer:
        sticky:
          cookie: {}
        passHostHeader: true
        servers:
          - url: http://yunsu-server:5000/
```

So I append `passHostHeader: true` to dynamic config. It works.

### What did you expect to see?
The passHostHeader is true, if I don't set the passHostHeader explicitly.
![image](https://user-images.githubusercontent.com/9463958/72002572-9ed33300-3282-11ea-86c6-74aa382ff4e3.png)

### What did you see instead?

The dashboard and results show the passHostHeader is false.

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.0

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
file provider(yaml)
```yaml


  middlewares:
    yun-headers:
      headers:
        hostsProxyHeaders:
          - "X-CSRFToken"

    yun-compress:
      compress: {}

  routers:
    yunsu-server:
      rule: "Host(`yunsu.noddl.me`)"
      service: "yunsu-server"
      priority: 10
      tls:
        certresolver: myhttpchallenge
      middlewares:
        - "yun-headers"
        - "yun-compress"
  services:
    yunsu-server:
      loadBalancer:
        sticky:
          cookie: {}
        passHostHeader: true
        servers:
          - url: http://yunsu-server:5000/
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
