### ISSUE TITLE
minVersion: VersionTLS13 breaks dashboard in traefik >= 2.1

### ISSUE THREAD

**Issue by DirkTheDaring** [containous/traefik#6149]
These actually two bugs which work together to make traefik dashboard unusable in a TLS1.3 only environment

Summary 
1. First bug is that dashboard_redirect has changed for 2.1 and replies only to http request, while previous versions did not care if the requests were http or https (see appendix  2) .. so basically you cannot run dashboard over https:  anymore in 2.1. Please fix this and make the redirect work for http and https.

2. Second bug why dashboard doesn't work iswhen you enfore tls1.3 (see appendix 3).  /api does not support http/2  queries.
you get an 404 error if you try do an https://yourtls1.3enforced.site/api/overview
You can confirm that it is an bug with api if you try a telnet on the host without enforced tls.1.3
try:
enter the curl command and type the following THREE lines   3rd emtpy line where you just hit return.
```
curl telnet://localhost:8080/api/overview
GET /api/overview HTTP/1.1
Host: whatever
```

--> This will get you a 200 response

**Now try the same for  HTTP/2**
```
curl telnet://localhost:8080/api/overview
GET /api/overview HTTP/2
```
--> you get a 400 Bad Request, because the api doesn't support it. 

Conclusion: Took weeks to find out why i could not bring up 2.1 finally i understand that it is tha traefik doesn't support tls 1.3 very well. it would be wise to add a downgrade option (force HTTP/1.0)  because other services might have the same issues. Also i tested this by downgrading to tls1.2 m which makes the api bug go away, but then still the redirect bug 1 remains.

(Appendix 2)
In my own bugfix i  onlychanged http in the regex line to https (which made it work for me)
```
 middlewares:
    dashboard_redirect:
      redirectRegex:
        regex: "^(http:\\/\\/[^:\\/]+(:\\d+)?)\\/$"  # (**) this cause a http:// only
        replacement: "${1}/dashboard/"
        permanent: true
```

(Appendix 3)
```
tls:
    options:
      myTLSOptions:
        minVersion: VersionTLS13
        cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
```

**Comment by ldez** [comment]
Hello,

1. The bug was already fixed in v2.1.2 (#6078)

2. To do routing on the API/Dashboard, we strongly recommend to use `api@internal`.
More explanations here: https://community.containo.us/t/serving-traefiks-internal-dashboard-behind-traefik-itself/3457/7?u=ldez

**Comment by DirkTheDaring** [comment]
Not true, plesae reopen.
Teested with traefik:v2.1.2

**Comment by DirkTheDaring** [comment]
reloaded container (and there is no v2.1.3 )  this is not working at all

**Comment by DirkTheDaring** [comment]
```
please try it. and try to upgrade the api to v1.3 example 
log:
#        level: INFO
        level: DEBUG

global:
    checkNewVersion:    true
    sendAnonymousUsage: false

api:
    insecure:  true
    dashboard: true
    debug:     true

entrypoints:
    http:
        address: ":80"
    https:
        address: ":443"

tls:
    options:
      myTLSOptions:
        minVersion: VersionTLS13
        cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
    options:
      myTLSOptionsBogusWorkaround:
        minVersion: VersionTLS12
        cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384



certificatesResolvers:
    letsencrypt:
        acme:
            email:   my.user@domain.com
            storage: /etc/traefik/acme.json
            httpChallenge:
                entryPoint: http

providers:
    file:
        filename: "/etc/traefik/traefik.yml"
        watch: true
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false

http:
    routers:
        api:
            priority: 2147483646
            entryPoints:
                - https
            service: api@internal
            rule: PathPrefix(`/api`)
            tls:
                options: "myTLSOptionsBogusWorkaround"


        internet:
            priority: 2147483645                # The higher the number, the lower the priorirty
            entryPoints:
                - https
            rule: PathPrefix(`/`)
            service: dashboard@internal
            middlewares:
                - dashboard_redirect
                - dashboard_stripprefix
            tls:
                certResolver: letsencrypt
                options: "myTLSOptions"
                domains:
                    - main: "my.web.site"
#        debug:
#            priority: 2147483646
#            entryPoints:
#            - https
#            service: api@internal
#            rule: PathPrefix(`/debug`)

    middlewares:
        dashboard_redirect:
            redirectRegex:
                regex: "^(https:\\/\\/[^:\\/]+(:\\d+)?)\\/$"
                replacement: "${1}/dashboard/"
                permanent: true
        dashboard_stripprefix:
            stripPrefix:
                prefixes:
                    - "/dashboard/"
                    - "/dashboard"
    services:
        traefik-api:
            loadBalancer:
                servers:
                    - url: "http://localhost:8080"
                      passHostHeader: True
```

**Comment by DirkTheDaring** [comment]
The example work around the bug(s) if you try to turn tls1.3 for api, it breaks for traefik:v2.1.2

**Comment by DirkTheDaring** [comment]
Please fix this, as this really blocking deployment of Traefik v2.1

**Comment by DirkTheDaring** [comment]
and i tried all the recommendations -it just breaks

v2.0.* work fine!!!

**Comment by DirkTheDaring** [comment]
http redirects are an regression: for versions < 6.1   traefik was agnostic of http or https redirects.   
6.1.0, 6.1.1, 6.1.2   introduce the requirement for http....

**Comment by ldez** [comment]
I repeat don't use `api.insecure=true` for routing: could you use `api@internal`

**Comment by DirkTheDaring** [comment]
this file was for testing to make it easier to find the bug . Thanks for pointing out the api.insecure = true, which I changed to api.insecure = false.
This was the **one** line fix  I needed, and I find it bogus, that this works now (tested on several machines....)

But I am happy, thanks for being patient because this drove me mad that this didn't work 
Will now separate stuff again.

**Comment by ldez** [comment]
A few notes if in the future someone will read this issue.

- `cipherSuites` are ignored for TLS1.3 https://docs.traefik.io/v2.1/https/tls/#cipher-suites
- I recommend to use `directory` instead of `filename` for the file provider (see limitations https://docs.traefik.io/v2.1/providers/file/#provider-configuration)

Your testing file can be simplify a lot:
```yml
log:
  level: INFO

global:
  checkNewVersion: true
  sendAnonymousUsage: true

api: {}

entrypoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email:   my.user@domain.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http

providers:
  file:
    directory: /etc/traefik/dyn/
    watch: true
  docker:
    exposedByDefault: false
```

```yml
http:
  routers:
    api:
      rule: Host(`my.web.site`)
      # rule: PathPrefix(`/api`) && PathPrefix(`/dashboard`)
      entryPoints:
        - https
      service: api@internal
      tls:
        certResolver: letsencrypt
        options: "myTLSOptions"
        # domains:
          # - main: "my.web.site"

tls:
  options:
    myTLSOptions:
      minVersion: VersionTLS13
```
