### ISSUE TITLE
IngressRouteTCP : Host instead of HostSNI

### ISSUE THREAD

**Issue by HugoRh** [containous/traefik#6155]
### New feature

Traefik V2 is forcing the use of HostSNI for TCP ingress

``
It is important to note that the Server Name Indication is an extension of the TLS protocol. Hence, only TLS routers will be able to specify a domain name with that rule. However, non-TLS routers will have to explicitly use that rule with * (every domain) to state that every non-TLS request will be handled by the router
``

I would like the rules applied to http (Host instead of HostSNI) to work with tcp traffic.

My use case is that I have one non tls tcp service with several replica across many namespaces on k8s.
HostSNI(`*`) is not appropriate in my case (and defining as many entrypoint as needed is too heavy and not very scalable).

### What did you expect to see?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: foo
  namespace: bar
spec:
  entryPoints:                 
    - tcp
  routes:                       
  - match: Host(`test.domain.com`)           
```
 
Bonus question: Why did only HostSNI has been implemented for tcp???

Thanks !!
