### ISSUE TITLE
Cannot enable dashboard in Traefik v2

### ISSUE THREAD

**Issue by romantomjak** [containous/traefik#6157]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Followed the v2.1 documentation to enable a "secure" dashboard, but unfortunately it seems it is not possible.

### What did you expect to see?

The dashboard.

### What did you see instead?

404 page not found.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.2
Codename:     cantal
Go version:   go1.13.5
Built:        2020-01-07T18:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

/etc/traefik/traefik.toml

```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"

[api]
  dashboard = true
```

/etc/traefik/dynamic/dashboard.toml

```toml
[http.routers.my-api]
  rule = "Host(`localhost`)"
  service = "api@internal"
  middlewares = ["dashboard_ipwhitelist"]

[http.middlewares]
  [http.middlewares.dashboard_ipwhitelist.ipWhiteList]
    sourceRange = ["127.0.0.0/24"]
```

**Comment by romantomjak** [comment]
I have now discovered a working configuration, by setting the `insecure = true` flag and observing what configuration Traefik adds to make the dashboard visible.

/etc/traefik/traefik.toml

```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"

[api]
  dashboard = true
```

/etc/traefik/dynamic/dashboard.toml

```toml
[http.routers]
  [http.routers.api]
    entrypoints = ["traefik"]
    rule = "PathPrefix(`/api`)"
    service = "api@internal"
    middlewares = ["dashboard_ipwhitelist"]

  [http.routers.dashboard]
    entrypoints = ["traefik"]
    rule = "PathPrefix(`/`)"
    service = "dashboard@internal"
    middlewares = ["dashboard_redirect", "dashboard_stripprefix", "dashboard_ipwhitelist"]

[http.middlewares]
  [http.middlewares.dashboard_redirect.redirectRegex]
    regex = "`^(http://[^:/]+(:[0-9]+)?)/$`"
    replacement = "${1}/dashboard/"

  [http.middlewares.dashboard_stripprefix.stripPrefix]
    prefixes = ["/dashboard/", "/dashboard"]

  [http.middlewares.dashboard_ipwhitelist.ipWhiteList]
    sourceRange = ["127.0.0.0/24"]
```

Can the documentation be ammended to show how to correctly enable a secure dashboard? Happy to do so myself if someone points me in the right direction.
