### ISSUE TITLE
Server Side Events [SSE] problem with Traefik Kubernetes Ingress Controller on k3d

### ISSUE THREAD

**Issue by daggerok** [containous/traefik#6161]
### Do you want to request a *feature* or report a *bug*?

I think it's Bug.

### What did you do?

I have streaming CQRS app with one way data flow, and traefik ingress, deployed into [rancher k3d](https://github.com/rancher/k3d/). All http get/posts requests are working fine, except SSE. 
If I'm deploying same app in docker-for-mac, minikube or KIND or even in k3d but with NGINX ingress controller, everything is working fine.

my Traefik Ingress k8s manifest looks like so:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-traefik-k3d
  annotations:
    # kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /backend
            backend:
              serviceName: backend-service
              servicePort: "webflux"
```

my frontend k8s resource looks like so:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  template:
    metadata:
      name: frontend-service
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: daggerok/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: "webflux"
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /actuator/health
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /actuator/health
          env:
            - name: TWEETS_SERVER_HOST
              value: "backend-service"
            - name: TWEETS_SERVER_PORT
              value: "7000"
      restartPolicy: Always
  selector:
    matchLabels:
      app: frontend-service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  sessionAffinity: None
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30080
      targetPort: 8080
      name: "webflux"
  type: NodePort
---
```

### What did you expect to see?

I'm expecting to have my sse code working:

```js
        const eventSource = new EventSource(`/api/stream-tweets/${author}/?${query}`);
        eventSource.onmessage = message => {
          // processing server side events...
        };
```

### What did you see instead?

Ingress from get / post requests points of view is working fine (ie, I can open http://ip:80/ url and rest api works fine... But SSE streaming over http traefik ingress doesn't start...

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I'm using rancher k3d which is has embedded traefik ingress controller out of the box, Unfoturnately I don't know match Traefik details, but k3d version: 1.4.0 

Can you please let me know if I missed some required Traefik-related configurations or anything else that might help fix sse communication in my streaming app to work as expected over traefik ingress?

PS: I already have created another issue for k3d project: https://github.com/rancher/k3d/issues/162

Thanks

---
Regards,
Max
