### ISSUE TITLE
Redis running over TCP returning HTTP response

### ISSUE THREAD

**Issue by dantuluri** [containous/traefik#6164]
### Do you want to request a *feature* or report a *bug*?

Bug

I'm trying to use Redis with Traefik but am running into some issues. 

I followed this issue: https://github.com/containous/traefik/issues/4930 in how they configured Redis with docker compose, but when doing so and trying to PING the redis db, I get the following error:

```
Error: Protocol error, got "H" as reply type byte
```

After going through some forums and StackOverFlow, it seems like this issue may come up when instead of TCP, Traefik uses HTTP (although in the dashboard it does show up as TCP).

Here is my docker compose file:

```yml
version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false
services:

  hog:
    image: traefik:v2.1.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.redis.address=:50000
      - --providers.docker
      - --api
      - --ping=true
    ports:
      - "50000:50000"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.http.routers.api.rule=Host(`subdomain.domain.tld`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:password"

  redis:
    image: redis:5
    labels:
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`another-subdomain.domain.tld`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=50000"
      - "traefik.tcp.routers.redis.tls=true"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes", "--requirepass", "password"]
    hostname: redis
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
```

Even without a redis.conf and using the given conf, I get the same issue. Any help would be greatly appreciated.

To be clear, it seems like I'm able to connect to the DB since I get Redis' shell when I do redis-cli like the following:
```
redis-cli --no-auth-warning -h another-subdomain.domain.tld -p 50000 -a 'password' 
```
But when I do PING within that shell I get that error aforementioned.

**Comment by dtomcej** [comment]
@dantuluri Please note that the `ping` utility does not use TCP, but ICMP, which is a different layer, and uses different protocols than TCP.

**Comment by dantuluri** [comment]
Tried to connect to Redis via rq-dashboard and got a response as such:
```
redis.exceptions.InvalidResponse: Protocol Error: H, b'TTP/1.1 400 Bad Request'
```

I'll try to diagnose this issue further, but am thinking about if Traefik is really needed (what are the benefits of Traefik for a simple TCP routing?).

**Comment by dantuluri** [comment]
Followed issue #4930 and did
```
for i in `seq 1 10`; do echo 'ping' | nc subdomain.domain.tld 50000; done | uniq -c
```
And got a response something like the following:
```
 1 HTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
   1 
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
   1 
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
   1 
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
   1 
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
   1 
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
   1 
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
```
Which makes me think of where in my config am I using HTTP? According to the dashboard and my config, I should be using TCP, right? Could this be a Traefik issue or something else?

**Comment by juliens** [comment]
Hi @dantuluri 

On your router `api`, you didn't specify the entrypoints so it is attach to your `redis` entrypoint too. If you change this, it should fix your problem.

**Comment by dantuluri** [comment]
Forgot to update this issue, but yes, I did see that and fixed it accordingly. 

I thought it may because I have some firewall, but starting a simple TCP worked fine.

Here's my updated docker-compose file (still running into the HTTP issue):
```
version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false
services:

  hog:
    # The official v2.0 Traefik docker image
    image: traefik:v2.1.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.redis.address=:50000
      - --providers.docker
      - --api
      - --ping=true
    ports:
      - "50000:50000"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.http.routers.api.rule=Host(`subdomain.domain.tld`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:password"

  redis:
    image: redis:5
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.routers.redis.rule=Host(`subdomain.domain.tld`)"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=50000"
      - "traefik.tcp.routers.redis.tls=true"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
    hostname: redis
```

**Comment by dantuluri** [comment]
Hi @juliens, I took a closer look at your comments and made some respective changes (which looking at it from face value, makes sense and I'm not getting errors anymore).

However, for some odd reason when I'm trying to connect, it lags forever, meaning the operation times out everytime.

Here's my updated docker file:

```
  hog:
    image: traefik:v2.1.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.redis.address=:50000
      - --providers.docker
      - --api
      - --ping=true
    ports:
      - "80:80"
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.http.routers.api.rule=Host(`subdomain.domain.tld`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:password"
      - "traefik.http.routers.api.entrypoints=web"

  redis:
    image: redis:5
    networks:
      - proxy
    expose:
      - 6379
    ports:
      - 50000:6379
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.routers.redis.rule=Host(`subdomain.domain.tld`)"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=50000"
      - "traefik.tcp.routers.redis.tls=true"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes", "--requirepass", "password"]
    hostname: redis
    restart: always
```
