### ISSUE TITLE
Show servers with failed healthchecks in dashboard

### ISSUE THREAD

**Issue by Tyilo** [containous/traefik#6166]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Run the following `docker-compose.yml`:
```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  httpbin:
    image: kennethreitz/httpbin
    labels:
      - traefik.http.routers.httpbin.rule=Host(`httpbin.docker.localhost`)
      - "traefik.http.services.httpbin.loadbalancer.healthCheck.path=/status/500"
```

### What did you expect to see?

I would expect to see some kind of error on the dashboard (maybe under Services).

### What did you see instead?

No errors shown on the frontpage or in the services list:
![](https://i.imgur.com/ig0KNue.png)
![](https://i.imgur.com/n3Yl4ct.png)

You can only see the failing healtcheck, when opening the service's page:
![](https://i.imgur.com/F7uj9nB.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.2
Codename:     cantal
Go version:   go1.13.5
Built:        2020-01-07T18:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See `docker-compose.yml`.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A
