### ISSUE TITLE
Dynamic conf with IngressRoute broken

### ISSUE THREAD

**Issue by desmap** [containous/traefik#6167]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to use dynamic conf with IngressRoute CRD, eg:
```yml
http:
  routers:
    Router-1:
      # By default, routers listen to every entry points
      rule: "Host(`traefik.io`)"
      service: "service-1"
```
which you docs state should work: 
*IngressRoute is the CRD implementation of a Traefik HTTP router.*

### What did you expect to see?

A working IngressRoute

### What did you see instead?

404

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
kind: DaemonSet
  apiVersion: apps/v1
  metadata:
    namespace: default
    name: traefik
    labels:
      app: traefik
  spec:
    selector:
      matchLabels:
        app: traefik
    template:
      metadata:
        labels:
          app: traefik
      spec:
        terminationGracePeriodSeconds: 60
        serviceAccountName: traefik-ingress-controller
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
        - name: traefik
          image: traefik:v2.0
          args:
          - --api.insecure
          - --accesslog
          - --entrypoints.web.Address=:80
          - --providers.kubernetescrd
          ports:
          - name: web
            containerPort: 80
```
