### ISSUE TITLE
Containers deployed with Swarm Mode not merged into one Traefik Service

### ISSUE THREAD

**Issue by sirlatrom** [containous/traefik#6168]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I deployed a service with 2 replicas using Docker Swarm Mode (i.e. `docker stack deploy --compose-file docker-compose.yml tr`).

### What did you expect to see?

I expected there to be a single Traefik Service per Swarm Service, which would give non-conflicting router configurations from multiple containers from the same Swarm Service.

### What did you see instead?

Traefik logged an error saying `Router defined multiple times with different configurations`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.2
Codename:     cantal
Go version:   go1.13.5
Built:        2020-01-07T18:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

No config file.

Arguments specified in compose file.

Docker Compose file:

```yaml
version: "3.7"

services:
  reverse-proxy:
    image: traefik:v2.1.2  
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --log.level=DEBUG
      # Enabling docker provider.
      - --providers.docker=true
      # Define entrypoints.
      - --entryPoints.http.address=:80
      # Do not expose containers unless explicitly told so.
      - --providers.docker.network=bridge
      - --providers.docker.usebindportip
      - --providers.docker.exposedbydefault=false
      - --api
    networks:
      - bridge
    labels:
      # Force https everywhere.
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api.service=api@internal

  whoami:
    image: containous/whoami:dev
    labels:
      - com.docker.compose.service=whoami
      # Explicitly tell Traefik to expose this container.
      - traefik.enable=true
      # The domain the service will respond to.
      - traefik.http.routers.whoami.rule=Path(`/`)
    networks:
      - bridge
    deploy:
      replicas: 2

networks:
  bridge:
    name: bridge
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-01-14T10:26:11Z" level=info msg="Configuration loaded from flags."
time="2020-01-14T10:26:11Z" level=info msg="Traefik version 2.1.2 built on 2020-01-07T18:23:57Z"
time="2020-01-14T10:26:11Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\
"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"w
atch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"useBindPortIP\":true,\"network\":\"bridge\",\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"dashb
oard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2020-01-14T10:26:11Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2020-01-14T10:26:11Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-01-14T10:26:11Z" level=debug msg="Start TCP Server" entryPointName=http
time="2020-01-14T10:26:11Z" level=info msg="Starting provider *traefik.Provider {}"
time="2020-01-14T10:26:11Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"useBindPortIP\":tru
e,\"network\":\"bridge\",\"swarmModeRefreshSeconds\":15000000000}"
time="2020-01-14T10:26:11Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"api\":{},\"dashboard\":{}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2020-01-14T10:26:11Z" level=debug msg="No default certificate, generating one"
time="2020-01-14T10:26:11Z" level=debug msg="Provider connection established with docker 19.03.4-rc1 (API 1.40)" providerName=docker
time="2020-01-14T10:26:11Z" level=info msg="Unable to find a binding for container \"/tr_reverse-proxy.1.dnv07yu2z4g18vqn3n9sn4olp\", falling back on its internal IP/Port." providerName=docker container=tr-rever
se-proxy-1-dnv07yu2z4g18vqn3n9sn4olp-8e881f3382a0a7ce7763390a38f6cec6d42be221020724f3272c280720b9cdf7 serviceName=tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp
time="2020-01-14T10:26:11Z" level=info msg="Unable to find a binding for container \"/tr_whoami.1.2vcpq808s96zktycmmileycme\", falling back on its internal IP/Port." container=tr-whoami-1-2vcpq808s96zktycmmileyc
me-15b4a82e8b3fbe8cd74f7c700be3288b811ff738dda7e9a9776bb70b32e21229 providerName=docker serviceName=tr-whoami-1-2vcpq808s96zktycmmileycme
time="2020-01-14T10:26:11Z" level=info msg="Unable to find a binding for container \"/tr_whoami.2.ifmcvzfs391dcdm0tgfn4qq4s\", falling back on its internal IP/Port." container=tr-whoami-2-ifmcvzfs391dcdm0tgfn4qq4s-8fffd0f592050c451e93e8bc4ea747c7e640f35026c228fe20e1ad8713a2f59e serviceName=tr-whoami-2-ifmcvzfs391dcdm0tgfn4qq4s providerName=docker
time="2020-01-14T10:26:11Z" level=error msg="Router defined multiple times with different configurations in [tr-whoami-1-2vcpq808s96zktycmmileycme-15b4a82e8b3fbe8cd74f7c700be3288b811ff738dda7e9a9776bb70b32e21229 tr-whoami-2-ifmcvzfs391dcdm0tgfn4qq4s-8fffd0f592050c451e93e8bc4ea747c7e640f35026c228fe20e1ad8713a2f59e]" routerName=whoami providerName=docker
time="2020-01-14T10:26:11Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"http\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`) || PathPrefix(`/dashboard`)\"},\"https-redirect\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"https-only\"],\"service\":\"tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp\",\"rule\":\"HostRegexp(`{any:.*}`)\"}},\"middlewares\":{\"https-only\":{\"redirectScheme\":{\"scheme\":\"https\"}}},\"services\":{\"tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.17.0.4:80\"}],\"passHostHeader\":true}},\"tr-whoami-1-2vcpq808s96zktycmmileycme\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.17.0.3:80\"}],\"passHostHeader\":true}},\"tr-whoami-2-ifmcvzfs391dcdm0tgfn4qq4s\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.17.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
time="2020-01-14T10:26:12Z" level=debug msg="Creating middleware" serviceName=tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=https-redirect@docker
time="2020-01-14T10:26:12Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=https-redirect@docker serviceName=tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp
time="2020-01-14T10:26:12Z" level=debug msg="Creating server 0 http://172.17.0.4:80" routerName=https-redirect@docker serviceName=tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp serverName=0 entryPointName=http
time="2020-01-14T10:26:12Z" level=debug msg="Added outgoing tracing middleware tr-reverse-proxy-1-dnv07yu2z4g18vqn3n9sn4olp" routerName=https-redirect@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
time="2020-01-14T10:26:12Z" level=debug msg="Creating middleware" middlewareName=https-only@docker middlewareType=RedirectScheme routerName=https-redirect@docker entryPointName=http
time="2020-01-14T10:26:12Z" level=debug msg="Setting up redirection to https " routerName=https-redirect@docker entryPointName=http middlewareName=https-only@docker middlewareType=RedirectScheme
time="2020-01-14T10:26:12Z" level=debug msg="Adding tracing to middleware" entryPointName=http routerName=https-redirect@docker middlewareName=https-only@docker
time="2020-01-14T10:26:12Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=http routerName=api@docker
time="2020-01-14T10:26:12Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=http middlewareName=traefik-internal-recovery
time="2020-01-14T10:26:12Z" level=debug msg="No default certificate, generating one"
```

### Source code that could be improved

By investigating the source code, I could see that a deep comparison is done using reflection, and that e.g. differing `Service` fields would result in the above error message.

In the function , the service name is derived from two labels that the local development tool Docker Compose adds to containers it creates, namely `com.docker.compose.project` and `com.docker.compose.service`:

https://github.com/containous/traefik/blob/cac76a182ef68e4f9739632337fafa18fc9e17df/pkg/provider/docker/config.go#L327-L335

If a separate check for the `com.docker.swarm.service.name` label were added, Traefik Service objects would be correctly merged and everything works smoothly.
