### ISSUE TITLE
Whitelisting Based on http-header `X-Forwarded-For`

### ISSUE THREAD

**Issue by jiangxixin** [containous/traefik#6174]
define traefik 2.X whitelist with custom http header

when use traefik behind haproxy we could not use header 'x-forwarded-for'
so a custom header could be defined in  Whitelist middleware
for example with k8s:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: testIPwhitelist
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 192.168.1.7
    ipStrategy:
      depth: 2
      header: X-Cluster-Client
```
