### ISSUE TITLE
Poor Rating (B) at SSL Labs because of TLS 1.0/1.1 and not supported PFS

### ISSUE THREAD

**Issue by totti4ever** [containous/traefik#6175]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using traefik as reverse proxy for nextcloud and other stuff, mainly dockerized. 

For security reasons I set the minVersion of TLS to 1.2 and asked traefik to only use ECDHE ciphers

### What did you expect to see?
Passing the SSL labs TLS test with at least A

### What did you see instead?
B
This aparrently is the case because
* This server does not support Forward Secrecy with the reference browsers. Grade capped to B.  MORE INFO »
* This server supports TLS 1.0 and TLS 1.1. Grade will be capped to B from January 2020. MORE INFO »

### Output of `traefik version`: (_What version of Traefik are you using?_)
latest :-)

Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true
#  insecure: true

log:
  level: ERROR #DEBUG
accessLog:
  fields:
    defaultMode: keep
    names:
      RequestHost: keep
      

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"


certificatesResolvers:
  le:
    acme:
      email: admin@xxx.xyz
      storage: /acme.json
      httpChallenge:
        entryPoint: http
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
#      caServer: "https://acme-v02.api.letsencrypt.org/directory"


tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict : true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

        # - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        # - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        # - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        # - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        # - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        # - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        # - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        # - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
  monitor:
    address: 8080


providers:
  docker:
#    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/files"
    watch: true
``` 

``` yaml
# docker-compose.yml
      - traefik.enable=true
      - traefik.docker.network=internal

      - traefik.http.services.nextcloud-http.loadbalancer.server.port=80

      - traefik.http.middlewares.nc-redirect-wellknown.redirectregex.permanent=true
      - traefik.http.middlewares.nc-redirect-wellknown.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nc-redirect-wellknown.redirectregex.replacement=https://$$1/remote.php/dav/

# web
      - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.xxx.xyz`)
      - traefik.http.routers.nextcloud-https.entrypoints=https
      - traefik.http.routers.nextcloud-https.service=nextcloud-http
      - traefik.http.routers.nextcloud-https.tls=true
      - traefik.http.routers.nextcloud-https.tls.certresolver=le
      - traefik.http.routers.nextcloud-https.middlewares=headers-security-nc@file,nc-redirect-wellknown

```

``` yaml
# middlewares.yml
http:
  middlewares:
    redirect-https:
      redirectScheme:
        permanent: true
        scheme: https
    headers-security-nc:
      headers:
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        sslRedirect: true
        contentTypeNosniff: true
        browserXssFilter: true
        customFrameOptionsValue: SAMEORIGIN

```
