### ISSUE TITLE
Bug: Defining own defaultRule with {{ .Name }} results in <no value>

### ISSUE THREAD

**Issue by botto** [containous/traefik#6177]
### What did you do?

I'm using consul and traefik to have a default rule for routing to a specific service.  
According to the docs https://docs.traefik.io/providers/consul-catalog/#defaultrule the `{{ .Name }}` should be the service name, but this does not seem to be the case.

### What did you expect to see?
In the traefik web ui the rule should be using the service name for `Host` i.e.: `Host(demo-webapp)`

### What did you see instead?
The rule for the service shows `Host(<no value>)`

### Output of `traefik version`: (_What version of Traefik are you using?_)
`V2.1.2`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]
  insecure = true
  dashboard = true
[entryPoints]
  [entryPoints.web]
    address = ":80"
# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
  defaultRule = "Host(`{{ .Name }}`)"
  [providers.consulCatalog.endpoint]
    address = "http://127.0.0.1:8500"
```
