### ISSUE TITLE
'redirectRegex' redirects when it shouldn't. 

### ISSUE THREAD

**Issue by MohamedMSaeed** [containous/traefik#6178]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to use 'redirectRegex' but it redirects when it shouldn't. 
For instance, the following code should redirect to `https://www.bar.com` if the request was `http://www.foo.com/` 
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  creationTimestamp: null
  name: redirect-www-2
spec:
  redirectRegex:
    regex: ^http://www.foo.com/(.*)?
    replacement: https://www.bar.com${1}
    permanent: true
```
BUT, it actually redirects if the url was `http://www.foo.com/` or `https://www.foo.com/` i.e. with https or http while it should only applied if it was http.

### What did you expect to see?
It should redirect if the request starts with `http` only

### What did you see instead?
it redirects if the request is `http` or `https`!

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.6
```
