### ISSUE TITLE
HTTP Request header Client IP changed

### ISSUE THREAD

**Issue by bayucandra** [containous/traefik#6182]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
- I am using Traefik on Kubernetes environment. AWS EKS to be exact.
- Using AWS NLB as the load balancer.
- Mainly I am using Kubernetes CRD as the main provider ( Just copy and paste the CRD from documentation page )
- I am setup web and websecure entry points and route to my golang http server

### What did you expect to see?
I expect to get visitor IP address ( Public IP ) in the HTTP header received by service routed by Traefik.

### What did you see instead?
I got the following headers which only contain local IP instead:
```json
      "header": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.9,id;q=0.8",
        "Referer": "https://mydomain.xyz/",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "Uber-Trace-Id": "62a95880b3889e37:3d899ff99196915b:79a503911b840ee8:1",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
        "X-Forwarded-For": "10.32.0.1",
        "X-Forwarded-Host": "mydomain.xyz",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Prefix": "/webmin/api",
        "X-Forwarded-Proto": "https",
        "X-Forwarded-Server": "traefik-65f4f8597d-wvhxn",
        "X-Real-Ip": "10.32.0.1"
      }
```
Looks like traefik remove visitors public IP before forward to my service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik V2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
- Here is my YAML "args" of traefik Deployments in kubernetes:
```yaml
          ...
          args:
            - --api.insecure
            - --accesslog
            - --metrics.prometheus=true
            - --tracing.jaeger=true
            - --providers.kubernetesingress=true
            - --providers.file.filename=/var/lib/myconfig/dynamic_conf.yaml
            - --providers.file.watch=true
            - --providers.kubernetescrd
            - --entrypoints.web.Address=:80
            - --entryPoints.web.forwardedHeaders.insecure
            - --entrypoints.websecure.Address=:443
            - --entryPoints.websecure.forwardedHeaders.insecure
            - --entrypoints.postgresql.address=:5432
            - --entrypoints.mongodb.address=:27017
            - --entrypoints.mongodb2.address=:27018
            - --entrypoints.mongodb3.address=:27019
            - --certificatesResolvers.default.acme.dnsChallenge.provider=cloudflare
            - --certificatesResolvers.default.acme.dnsChallenge.delayBeforeCheck=0
            - --certificatesResolvers.default.acme.storage=/var/lib/my-ssl/acme.json
            ...
``` 
- I put `--entryPoints.web.forwardedHeaders.insecure` and the `websecure` too in purpose which related to problem I found. But no difference whether I put them or remove them.

- And here the NLB loadBalance service config:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: mai-traefik
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: postgresql
      port: 5432
    - protocol: TCP
      name: mongodb
      port: 27017
    - protocol: TCP
      name: mongodb2
      port: 27018
    - protocol: TCP
      name: mongodb3
      port: 27019
  selector:
    app: traefik
```
