### ISSUE TITLE
use domain for backend service instead of ip

### ISSUE THREAD

**Issue by letian0805** [containous/traefik#6183]
Does traefik support domain for backend service?
Example:
```toml
[http.services]
    [http.services.test.loadbalancer] 
        [[http.services.test.loadbalancer.servers]]
            url = "http://internal.test.com"
            weight = 100 
```
