### ISSUE TITLE
dashboard loads longer with BasicAuth & Bcrypt Hash

### ISSUE THREAD

**Issue by PackElend** [containous/traefik#6200]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Added `BasicAuth `using a  Bcrypt Hash with 15 Rounds: `$2y$15$...`

```
    volumes:         
      - /etc/passwd.docker.traefik:/etc/passwd.BasicAuth
    labels:
      - traefik.http.routers.traefik_dashboard_secure.middlewares=traefik_auth
      - traefik.http.middlewares.traefik_auth.basicauth.usersfile=/etc/passwd.BasicAuth
```
In addition `docker-compose down` lasst longer

### What did you expect to see?

same quick loading times without `BasicAuth`
No impact on `docker-compose down` time

### What did you see instead?
all take significantly longer 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
root@Ubuntu18:/# docker exec traefikV2 traefik version
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>
  <summary>static config</summary>

```
global:
  checkNewVersion: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
   debug: true

providers:
  docker:
    exposedByDefault: false
    network: bridge_proxy_traefikv2

log:
  level: DEBUG
  filePath: /var/log/traefik-log.log

accessLog:
  filePath: /var/log/traefik-access.log

certificatesResolvers:
  tlsChallenge_letsencrypt:
    acme:
      email: my.secret@gmail.com
      storage: /etc/ssl/certs/letsencrypt/acme.json
      tlsChallenge: {}
```
</details>

<details>
  <summary>dynamic config</summary>

```
services:
  traefikV2:   
    image: traefik:v2.1.1
    container_name: traefik

    
    ports:
      # The HTTP port
      - 80:80
      # The HTTPS port
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      #- "8080:8080"
    
    volumes:         
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/traefik:/var/log
      - /etc/ssl/certs/traefik/letsencrypt:/etc/ssl/certs/letsencrypt
      - /opt/traefik/traefik-config.yaml:/etc/traefik/traefik.yaml
    
    labels:
      - traefik.enable=true
      #- "traefik.docker.network=bridge_proxy_traefikv2"
      
      #---HTTP ROUTER SECTION
      - traefik.http.routers.traefik_dashboard.rule=Host(`traefik.fairbnb.community`)
      - traefik.http.routers.traefik_dashboard.service=api@internal
      
         #---HTTP SECTION
      -  traefik.http.routers.traefik_dashboard.entrypoints=web
      
      #---HTTPS ROUTER SECTION
      - traefik.http.routers.traefik_dashboard_secure.rule=Host(`traefik.fairbnb.community`)
      - traefik.http.routers.traefik_dashboard_secure.service=api@internal
           
         #---HTTPS SECTION
      -  traefik.http.routers.traefik_dashboard_secure.entrypoints=websecure      
      
         #---TLS SECTION
      -  traefik.http.routers.traefik_dashboard_secure.tls.certresolver=tlsChallenge_letsencrypt
      
      #---MIDDLEWARE SECTION
        #---redirect http to https      
      - traefik.http.middlewares.traefik_dashboard_redirect2https.redirectscheme.scheme=https
        #---adding Basic Authentication 
      - traefik.http.middlewares.traefik_auth.basicauth.usersfile=/etc/passwd.BasicAuth

    networks:
      - traefik

      
networks:
  traefik:
    external:
      name: bridge_proxy_traefikv2
```

</details>
