### ISSUE TITLE
 Websocket 403 on 2.1.2

### ISSUE THREAD

**Issue by hdhog** [containous/traefik#6214]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

Websockets upgrade to return 101

### What did you see instead?

Websocket upgrade returns 403

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.1.2 built on 2020-01-07T18:23:57Z
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.traefik]
    address = ":9090"
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"


[certificatesResolvers.own.acme]
  email = "admin@example.com"
  storage = "acme.json"
  
  caServer = "https://ca.example.com/acme/acme/directory"
  [certificatesResolvers.own.acme.httpChallenge]
    # used during the challenge
    entryPoint = "http"

[log]
  level = "DEBUG"
[tracing.jaeger]
   samplingServerURL = "http://10.210.2.61:5778/sampling"
   localAgentHostPort = "10.210.2.61:6831"

[api]
    dashboard = true
    insecure = true
[accessLog]
[providers.docker]
  watch = true
  exposedbydefault = false

```
labels
```yaml
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.lavagna-compress.compress: "true"
      traefik.http.middlewares.lavagna-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.lavagna.entrypoints: "http,https"
      traefik.http.routers.lavagna.middlewares: "sslheader,lavagna-redirect,lavagna-compress"
      traefik.http.routers.lavagna.rule: "Host(`sam-sib-kb`) || Host(`sam-sib-kb.samara.yukos.ru`)"
      traefik.http.routers.lavagna.tls: "true"
      traefik.http.routers.lavagna.tls.certresolver: "own"
      traefik.http.routers.lavagna.tls.domains[0].sans: "kb,kb.example.com"
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

[log.txt](https://github.com/containous/traefik/files/4091119/log.txt)
