### ISSUE TITLE
errors + basicauth middlewares incompatibility

### ISSUE THREAD

**Issue by geek85** [containous/traefik#6220]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have a line in docker-compose.yml with two middlewares:
- "traefik.http.routers.internal.middlewares=errorpage@file,auth1@file"

errorpage@file is an 'errors' middleware that handles 401-404 errors
auth1@file is a 'basicauth' middleware 

they are both correctly configured and work great each one alone.

### What did you expect to see?

when I'm accessing the router,
I expect to see a login screen and the fallback 401 error **if** the login is wrong.

### What did you see instead?

I see the fallback 401 error directly, no login prompt.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
static
```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.forwardedHeaders]
      insecure = true
[log]
[api]
   insecure = false
[providers]
  [providers.docker]
    exposedByDefault = false
    network = "traefik_network"
    [certificatesResolvers]
        [certificatesResolvers.HTTP]
            [certificatesResolvers.HTTP.acme]
                email = "xxx"
                [certificatesResolvers.HTTP.acme.httpChallenge]
                    entryPoint = "web"
        [certificatesResolvers.OVH]
            [certificatesResolvers.OVH.acme]
                email = "xxx"
                storage = "/letsencrypt/acme.json"
                [certificatesResolvers.OVH.acme.dnsChallenge]
                    provider = "ovh"
                    delayBeforeCheck = 10
                    resolvers = ["1.1.1.1:53", "9.9.9.9:53"]
  [providers.file]
    directory = "./dynamic/"
```
dynamic:
```toml
[http]
[http.middlewares]
    [http.middlewares.downloads_auth]
        [http.middlewares.auth1.basicAuth]
            users = ["minikea:$apr1$qkvmgVId$oygPWGg67Ndxr6yI69UyQ1"]
    [http.middlewares.errorpage]
        [http.middlewares.errorpage.errors]
            status = ["401-404"]
            service = "fallback"
            query = "/{status}.jpg"
```

```yaml
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.internal_secure.rule=Host(`internal.example.com`)"
            - "traefik.http.routers.internal_secure.entrypoints=websecure"
            - "traefik.http.routers.internal_secure.tls.certresolver=OVH"
            - "traefik.http.services.internal.loadbalancer.server.port=80"
            - "traefik.http.routers.internal_secure.middlewares=errorpage@file,auth1@file"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik    | time="2020-01-22T13:08:09Z" level=debug msg="Handling connection from xx.xx.xx.xx:30532"
traefik    | time="2020-01-22T13:08:10Z" level=debug msg="Authentication failed" middlewareName=auth1@file middlewareType=BasicAuth
traefik    | time="2020-01-22T13:08:10Z" level=error msg="Caught HTTP Status Code 401, returning error page" middlewareName=errorpage@file middlewareType=customError
```
without errorpage and failed login:
```
traefik    | time="2020-01-22T13:12:28Z" level=debug msg="Authentication failed" middlewareName=auth1@file middlewareType=BasicAuth
traefik    | time="2020-01-22T13:12:33Z" level=debug msg="Authentication failed" middlewareName=auth1@file middlewareType=BasicAuth
```
without errorpage and correct login:
```
traefik    | time="2020-01-22T13:12:44Z" level=debug msg="Authentication failed" middlewareName=auth1@file middlewareType=BasicAuth
traefik    | time="2020-01-22T13:12:49Z" level=debug msg="Authentication succeeded" middlewareName=auth1@file middlewareType=BasicAuth
```
