### ISSUE TITLE
cant add self signed wildcard cert

### ISSUE THREAD

**Issue by Elyytscha** [containous/traefik#6221]
Bug

### What did you do?

i used traefik in version 2.1.3, what i'm trying to do is adding a selfsigned wildcard certificate so traefik can serve every possible domain with a valid cert

i tried the following in /etc/traefik/traefik.toml (mounted into the container from the host, docker-compose): like stated here in the docs https://docs.traefik.io/https/tls/
```
#[tls.stores]
#  [tls.stores.default]
#     [tls.stores.default.defaultCertificate]
#      certFile = "/certs/cert.crt"
#      keyFile = "/certs/cert.key"

[[tls.certificates]]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key" 
```

```
[tls.stores]
  [tls.stores.default]
     [tls.stores.default.defaultCertificate]
      certFile = "/certs/cert.crt"
      keyFile = "/certs/cert.key"

#[[tls.certificates]]
#  certFile = "/certs/cert.crt"
#   keyFile = "/certs/cert.key" 
```

```
[tls.stores]
  [tls.stores.default]
     [tls.stores.default.defaultCertificate]
      certFile = "/certs/cert.crt"
      keyFile = "/certs/cert.key"

[[tls.certificates]]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key" 
```

```
#[tls.stores]
#  [tls.stores.default]
[tls.stores.default.defaultCertificate]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key"

[[tls.certificates]]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key" 
```

certs are mounted to /certs/ via docker-compose, they are there (when i exec into container and ls -ahl /certs i see them)

```
$ docker-compose exec traefik-proxy sh
/ # ls -ahl /certs
total 8K     
drwxr-xr-x    2 root     root          38 Jan 22 18:04 .
drwxr-xr-x    1 root     root          53 Jan 22 18:04 ..
-rwxr-xr-x    1 root     root        1.5K Jan 22 17:51 cert.crt
-rw-------    1 root     root        1.7K Jan 22 17:50 cert.key
```

### What did you expect to see?
 traefik picking up the cert and serving it on the HTTPS endpoint

### What did you see instead?

`traefik          | time="2020-01-22T18:04:23Z" level=debug msg="No default certificate, generating one"`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose attached labls and dynamic .toml config

```toml
# Secure localhost:5000 with self-signed SSL cert and
# serve it on test.localhost:4000 port
[global]
#  debug = true
#  logLevel = "DEBUG"
#  defaultEntryPoints = ["HTTPS"]
  sendanonymoususage = false

[ServersTransport]
  InsecureSkipVerify = true
  #RootCAs = ["foobar", "foobar"]
  #MaxIdleConnsPerHost = 42
  #[ServersTransport.ForwardingTimeouts]
    #DialTimeout = 42
    #ResponseHeaderTimeout = 42

[entryPoints]
  [entryPoints.HTTPS]
    address = ":443"
  [entryPoints.HTTP]
    address = ":80"
#      [entryPoints.HTTP.Transport]
#        [EntryPoints.HTTP.ProxyProtocol]
#          insecure = true
#    [entryPoints.HTTPS.tls]
#      [[entryPoints.HTTPS.tls.defaultCertificate]]
#        certFile = "/certs/cert.crt"
#        keyFile = "/certs/cert.key"

[log]
  level = "DEBUG"

#[tls.stores]
#  [tls.stores.default]
[tls.stores.default.defaultCertificate]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key"

[[tls.certificates]]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key" 

[api]
  dashboard = true
  insecure = true

[ping]
  entrypoint = "HTTP"

[providers.docker]
  # Connection to docker host system (docker.sock)
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  # This will hide all docker containers that don't have explicitly  
  # set label to "enable"
  exposedbydefault = false
  #network = "traefik-net"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Adding tracing to middleware" entryPointName=HTTPS routerName=devops-apimgmt-service@docker middlewareName=devops-apimgmt-service_stripprefix@docker
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Creating middleware" middlewareType=Pipelining entryPointName=HTTPS routerName=devops-deployment-service@docker serviceName=devops-deployment-service-devops-deployment-service middlewareName=pipelining
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Creating load-balancer" serviceName=devops-deployment-service-devops-deployment-service entryPointName=HTTPS routerName=devops-deployment-service@docker
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Creating server 0 http://192.168.64.2:8080" entryPointName=HTTPS serverName=0 routerName=devops-deployment-service@docker serviceName=devops-deployment-service-devops-deployment-service
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Added outgoing tracing middleware devops-deployment-service-devops-deployment-service" entryPointName=HTTPS routerName=devops-deployment-service@docker middlewareName=tracing middlewareType=TracingForwarder
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Creating middleware" entryPointName=HTTPS routerName=devops-deployment-service@docker middlewareName=devops-deployment-service_stripprefix@docker middlewareType=StripPrefix
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Adding tracing to middleware" entryPointName=HTTPS routerName=devops-deployment-service@docker middlewareName=devops-deployment-service_stripprefix@docker
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="Creating middleware" entryPointName=HTTPS middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik          | time="2020-01-22T18:04:23Z" level=debug msg="No default certificate, generating one"

```

EDIT: Even if it is not a bug in traefik it is still a bug in the documentation, because stateted as in the docs it does not work, i tried every way the docs suggesting here https://docs.traefik.io/https/tls/
