### ISSUE TITLE
Docker provider not picking correct network?

### ISSUE THREAD

**Issue by gust1n** [containous/traefik#6232]
### Do you want to request a *feature* or report a *bug*?
Bug (I think, otherwise misconfiguration)

### What did you do?

My issue is that when trying to proxy to a docker container with two networks, one internal docker network and one using the `macvlan` driver (with static IP), `traefik` seems to flip between using the two networks, even if I have specified which one to use.

### What did you expect to see?

I expect `traefik` to use only the network I specified.

### What did you see instead?

I can see in the dashboard that `traefik` sometimes shows the server with an IP from the internal network, and sometimes using the `macvlan` network. I see that the IPs actually change, even when no changes are made to either config or starting/stopping services.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.2
Codename:     cantal
Go version:   go1.13.5
Built:        2020-01-07T18:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Minimal sample `docker-compose-yml` config:

```yaml
version: '3.5'

  services:
    traefik:
      image: traefik:v2.1
      networks:
        outside_world:
        some_other_existing_network:
        proxy_internal:
      command:
        - --providers.docker.network=some_other_existing_network
      ports:
        - "80:80"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

    service1: #working just fine
      image: some-image-1
      networks:
        proxy_internal:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_internal
        - traefik.http.routers.service1.rule=Host(`service1.domain`)
        - traefik.http.services.service1.loadbalancer.server.port=3000

    service2: #flips between the two networks
      image: some-image-2
      networks:
        vlan50:
          ipv4_address: 10.0.50.5
       proxy_internal:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_internal
        - traefik.http.routers.service2.rule=Host(`service2.domain`)
        - traefik.http.services.service2.loadbalancer.server.port=5000

  networks:
    some_other_existing_network:
    proxy_internal:
      internal: true
    vlan50:
      driver: macvlan
      driver_opts:
        parent: eno1.50
      ipam:
        config:
          - subnet: 10.0.50.1/24
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I can provide debug logs if wanted, happy to help
