### ISSUE TITLE
HTTPS Redirect without service port

### ISSUE THREAD

**Issue by FriedCircuits** [containous/traefik#6241]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Be able to do a http to https redirect for a service that only listens on https. I tried to setup a redirect for the kubernetes dashboard but since it only listens on https the service port is not found. A workaround is to use traefik http service port and then the redriect works. This requires the redirect/middleware be in the same namespace as traefik.

### What did you expect to see?

What should happen is on the http entrypoint where you specify the middleware redirect you should be able without a service. 

### What did you see instead?

Instead it can't connect to the service port and therefore does not redirect to https

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.17 

Non- working config
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard-redirect
  namespace:  kubernetes-dashboard

spec:
  entryPoints:
  - web
  routes:
  - match: Host(`example.com`)
    kind: Rule
    services:
    - name:  kubernetes-dashboard #any service in the namespace
      port: 80
    middlewares:
      - name: https-redirect
        namespace:  kubernetes-dashboard

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.com`)
      kind: Rule
      services:
      - name: kubernetes-dashboard
        port: 443
        passHostHeader: true
  tls: {}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: kubernetes-dashboard
spec:
  redirectScheme:
    scheme: https
    permanent: false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-01-26T19:27:10Z" level=error msg="service port not found" namespace=kubernetes-dashboard ingress=kubernetes-dashboard-redirect providerName=kubernetescrd
time="2020-01-26T19:27:10Z" level=error msg="service port not found" providerName=kubernetescrd namespace=kubernetes-dashboard ingress=kubernetes-dashboard-redirect
time="2020-01-26T19:27:11Z" level=error msg="service port not found" ingress=kubernetes-dashboard-redirect namespace=kubernetes-dashboard providerName=kubernetescrd
```
