### ISSUE TITLE
ACME challenge - 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by iBobik** [containous/traefik#6246]
Tested Traefik version 2.0.7 and 2.1.3

docker-compose.yml:
```
version: "2"

services:

  proxy:
    image: traefik:v2.0
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=http
      - --certificatesResolvers.le.acme.email=bobik@ibobik.cz
      - --certificatesResolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      traefik.http.routers.http_catchall.rule: HostSNI(`*`)
      traefik.http.routers.http_catchall.entrypoints: web
      traefik.http.routers.http_catchall.middlewares: https_redirect
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https_redirect.redirectscheme.permanent: true
    volumes:
      - proxy_le:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: containous/whoami
    labels:
      traefik.enable: true
      traefik.http.routers.app.rule: Host(`$CI_ENVIRONMENT_HOSTNAME`)
      traefik.http.routers.app.entrypoints: https
      traefik.http.routers.app.tls.certresolver: le

volumes:
  proxy_le:

```

Containers log:
```
proxy_1   | time="2020-01-27T18:07:51Z" level=info msg="Configuration loaded from flags."
proxy_1   | time="2020-01-27T18:07:51Z" level=info msg="Traefik version 2.0.7 built on 2019-12-09T17:51:21Z"
proxy_1   | time="2020-01-27T18:07:51Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"le\":{\"acme\":{\"email\":\"bobik@ibobik.cz\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"http\"}}}}}"
proxy_1   | time="2020-01-27T18:07:51Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
proxy_1   | time="2020-01-27T18:07:51Z" level=debug msg="No default certificate, generating one"
proxy_1   | time="2020-01-27T18:07:52Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Start TCP Server" entryPointName=traefik
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Start TCP Server" entryPointName=http
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Start TCP Server" entryPointName=https
proxy_1   | time="2020-01-27T18:07:52Z" level=info msg="Starting provider *acme.Provider {\"email\":\"bobik@ibobik.cz\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"http\"},\"ResolverName\":\"le\",\"store\":{},\"ChallengeStore\":{}}"
proxy_1   | time="2020-01-27T18:07:52Z" level=info msg="Testing certificate renew..." providerName=le.acme
proxy_1   | time="2020-01-27T18:07:52Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}"
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Configuration received from provider le.acme: {\"http\":{},\"tls\":{}}" providerName=le.acme
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="No default certificate, generating one"
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Provider connection established with docker 19.03.5 (API 1.40)" providerName=docker
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Filtering disabled container" providerName=docker container=proxy-gitlab-ci-vm-for-every-branch-35e65e9da47528697d2480c9bb2d54fec3005c0498180096a81d41f6fa4c4d04
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"app\":{\"entryPoints\":[\"https\"],\"service\":\"whoami-gitlab-ci-vm-for-every-branch\",\"rule\":\"Host(`test.example.com`)\",\"tls\":{\"certResolver\":\"le\"}}},\"services\":{\"whoami-gitlab-ci-vm-for-every-branch\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.18.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Creating middleware" middlewareType=Pipelining entryPointName=https routerName=app@docker serviceName=whoami-gitlab-ci-vm-for-every-branch middlewareName=pipelining
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Creating load-balancer" entryPointName=https routerName=app@docker serviceName=whoami-gitlab-ci-vm-for-every-branch
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Creating server 0 http://172.18.0.2:80" routerName=app@docker serviceName=whoami-gitlab-ci-vm-for-every-branch entryPointName=https serverName=0
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Added outgoing tracing middleware whoami-gitlab-ci-vm-for-every-branch" entryPointName=https routerName=app@docker middlewareName=tracing middlewareType=TracingForwarder
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=https middlewareName=traefik-internal-recovery
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="No default certificate, generating one"
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Try to challenge certificate for domain [test.example.com] found in HostSNI rule" routerName=app providerName=le.acme rule="Host(`test.example.com`)"
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Looking for provided certificate(s) to validate [\"test.example.com\"]..." providerName=le.acme rule="Host(`test.example.com`)" routerName=app
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Domains [\"test.example.com\"] need ACME certificates generation for domains \"test.example.com\"." providerName=le.acme rule="Host(`test.example.com`)" routerName=app
proxy_1   | time="2020-01-27T18:07:52Z" level=debug msg="Loading ACME certificates [test.example.com]..." providerName=le.acme rule="Host(`test.example.com`)" routerName=app
proxy_1   | time="2020-01-27T18:07:58Z" level=debug msg="Building ACME client..." providerName=le.acme
proxy_1   | time="2020-01-27T18:07:58Z" level=debug msg="https://acme-v02.api.letsencrypt.org/directory" providerName=le.acme
proxy_1   | time="2020-01-27T18:07:58Z" level=info msg=Register... providerName=le.acme
proxy_1   | time="2020-01-27T18:07:58Z" level=debug msg="legolog: [INFO] acme: Registering account for bobik@ibobik.cz"
proxy_1   | time="2020-01-27T18:07:58Z" level=debug msg="Using HTTP Challenge provider." providerName=le.acme
proxy_1   | time="2020-01-27T18:07:58Z" level=debug msg="legolog: [INFO] [test.example.com] acme: Obtaining bundled SAN certificate"
proxy_1   | time="2020-01-27T18:07:59Z" level=debug msg="legolog: [INFO] [test.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx"
proxy_1   | time="2020-01-27T18:07:59Z" level=debug msg="legolog: [INFO] [test.example.com] acme: Could not find solver for: tls-alpn-01"
proxy_1   | time="2020-01-27T18:07:59Z" level=debug msg="legolog: [INFO] [test.example.com] acme: use http-01 solver"
proxy_1   | time="2020-01-27T18:07:59Z" level=debug msg="legolog: [INFO] [test.example.com] acme: Trying to solve HTTP-01"
proxy_1   | time="2020-01-27T18:08:05Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx"
proxy_1   | time="2020-01-27T18:08:05Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx"

```

Contents of https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx
```
{
  "identifier": {
    "type": "dns",
    "value": "test.example.com"
  },
  "status": "invalid",
  "expires": "2020-02-03T18:07:58Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from http://test.example.com/.well-known/acme-challenge/-9Dz8rQwZThbJwcTssBMuECcLRqKkjsb-B7plU06Qpo [1.2.3.4]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e503 Service Temporarily Unavailable\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody bgcolor=\\\"white\\\"\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e503 Service Tempora\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxx/Tc5dSg",
      "token": "-9Dz8rQwZThbJwcTssBMuECcLRqKkjsb-B7plU06Qpo",
      "validationRecord": [
        {
          "url": "http://test.example.com/.well-known/acme-challenge/-9Dz8rQwZThbJwcTssBMuECcLRqKkjsb-B7plU06Qpo",
          "hostname": "test.example.com",
          "port": "80",
          "addressesResolved": [
            "1.2.3.4"
          ],
          "addressUsed": "1.2.3.4"
        }
      ]
    }
  ]
}
```

Error page http://test.example.com/.well-known/acme-challenge/-9Dz8rQwZThbJwcTssBMuECcLRqKkjsb-B7plU06Qpo:

> 503 Service Temporarily Unavailable
> nginx/1.14.1
