### ISSUE TITLE
traefik 2.1.3: sockets not closed properly

### ISSUE THREAD

**Issue by ZyanKLee** [containous/traefik#6252]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Set up a monitoring system consisting of traefik with some service behind it, i.e. grafana, kibana, prometheus, authelia, alerta and others.

traefik uses authelia as a forwardAuthentication service for those tools that do not provide an authentication interfaces on their own (i.e. kibana).

### What did you expect to see?

I expected the amount of open files / sockets rising and declining with the rate of usage of the system.

### What did you see instead?

After several hours the max open files limit was reached and connections from traefik to its services aren't successful anymore - as in: the browser page stays blank and there is no error message shown. 

I recognized within grafana (after a restart of traefik, obviously) some odd measurements.

On this graph you can see the constant growth of open sockets on the host system:
![Bildschirmfoto 2020-01-28 um 15 37 05](https://user-images.githubusercontent.com/1178490/73274345-b9475f00-41e5-11ea-83d9-02dde3150bde.png)

This second graph illustrates the growth rate (`non_negative_difference`) of the two most significant timeserieses:
![Bildschirmfoto 2020-01-28 um 15 41 02](https://user-images.githubusercontent.com/1178490/73274482-ea279400-41e5-11ea-8ff2-466e02f3c7cb.png)

That nicely shows how the amount of requests relates to the number of open file descriptors. The other three timeserieses that are excluded in this view show similar behaviour but do have some more spikes that are clearly not related to the issue (or most probably closed again afterwards).

### Output of `traefik version`: (_What version of Traefik are you using?_)

docker-compose exec reverseproxy traefik version
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[providers.docker]
  exposedByDefault = false
  defaultRule = ''

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.proxyProtocol]
        insecure = true
      [entryPoints.http.forwardedHeaders]
        insecure = true

[api]
  dashboard = true
  insecure = true

[metrics]
  [metrics.prometheus]

[ping]
  entrypoint = "http"

[log]
  level = "ERROR"
```

part of the docker-compose.yaml as an example:
```yaml
---
version: "3.4"

services:

  reverseproxy:
    container_name: reverseproxy
    image: traefik:2.1.3
    restart: always
    labels:
    - "namespace=proxy"
    - "traefik.enable=true"
    - "traefik.http.routers.reverseproxy.rule=Host(`traefik.${BASEDOMAIN}`)"
    - "traefik.http.routers.reverseproxy.service=api@internal"
    - "traefik.http.routers.reverseproxy.middlewares=reverseproxy-auth@docker"
    - 'traefik.http.middlewares.reverseproxy-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${BASEDOMAIN}'
    - "traefik.http.middlewares.reverseproxy-auth.forwardauth.trustForwardHeader=true"
    - "traefik.http.middlewares.reverseproxy-auth.forwardauth.tls.insecureSkipVerify=true"
    ports:
    - 80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik/config/:/etc/traefik/
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: always
    ports:
    - 9091
    volumes:
    - ./authelia/config/configuration.yml:/etc/authelia/configuration.yml
    - authelia-data:/var/lib/authelia
    environment:
      TZ: Europe/Berlin
    labels:
    - "namespace=proxy"
    - "traefik.enable=true"
    - "traefik.http.routers.authelia.rule=Host(`auth.${BASEDOMAIN}`)"
    - "traefik.http.routers.authelia.middlewares=authelia-headers@docker,authelia-regex@docker"
    - "traefik.http.middlewares.authelia-headers.headers.customrequestheaders.X-Forwarded-Proto:https"
    - "traefik.http.middlewares.authelia-regex.redirectregex.regex=(.*rd=)(https?://?)([^/].*)"
    - "traefik.http.middlewares.authelia-regex.redirectregex.replacement=$${1}https://$${3}"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  kibana:
    container_name: kibana
    build: kibana
    image: local/kibana:latest
    restart: always
    ports:
    - 5601
    environment:
      ES_HOSTS:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
    - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    - kibana-data:/usr/share/kibana/data
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.kibana.rule=Host(`kibana.${BASEDOMAIN}`)"
    - "traefik.http.routers.kibana.middlewares=kibana-auth@docker"
    - "traefik.http.middlewares.kibana-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${BASEDOMAIN}"
    - "traefik.http.middlewares.kibana-auth.forwardauth.trustForwardHeader=true"
    - "traefik.http.middlewares.kibana-auth.forwardauth.tls.insecureSkipVerify=true"
    - "namespace=monitoring"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
found no errors in there - if absolutely needed, I can provide a privacy- and security-enhanced version of it.
```
