### ISSUE TITLE
Client authentication does not work for dashboard

### ISSUE THREAD

**Issue by joshuaavalon** [containous/traefik#6253]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Adding client authentication

```yaml
tls:
  options:
    default:
      clientAuth:
        caFiles:
          - /etc/traefik/cloudflare.pem
        clientAuthType: RequireAndVerifyClientCert
```

### What did you expect to see?

Work as before adding client authentication.

### What did you see instead?

Every other routes works except dashboard.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```yaml
entryPoints:
  http:
    address: :80
  https:
    address: :443

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic/

certificatesResolvers:
  letsEncrypt:
    acme:
      email: example@example.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
```
```yaml
http:
  routers:
    dashboard:
      entryPoints:
        - https
      rule: Host(`traefik.example.com`)
      service: api@internal
      tls:
        certresolver: letsEncrypt
        domains:
          - main: example.com
            sans:
              - "*.example.com"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

No related log is outputted.
