### ISSUE TITLE
Compression doesn't work

### ISSUE THREAD

**Issue by Shagon94** [containous/traefik#6264]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to enable compression and watched the responses, they weren't compressed

### What did you expect to see?

that the response was compressed

### What did you see instead?

the same response as from the server

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker image ls | grep traefik
traefik   v2.1.0              756dde2af7dd        7 weeks ago         70.1MB
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#dyn.toml
[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
      certFile = "/etc/certs/cert.crt"
      keyFile = "/etc/certs/privkey.key"
  [[tls.certificates]]
  certFile = "/etc/certs/cert.crt"
  keyFile = "/etc/certs/privkey.key"
```
```toml
# traefik.toml
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"

[http.routers]
  [http.routers.api]
  rule = "Host(`traefik.redpulsar.dev`)"
  service = "api"

[api]
  dashboard = true
  debug = true

[providers]
  [providers.docker]
    watch = true
  [providers.file]
    filename = "/etc/traefik/dyn.toml"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
too large
```

I've went ahead and created the following to test this out:
```yml
version: '3.3'
services:
  redpulsar:
    image: registry.gitlab.com/shagon/redpulsar:master
    container_name: redpulsar
    labels:
      - "traefik.http.routers.redpulsar.entrypoints=http"
      - "traefik.http.routers.redpulsar.rule=Host(`redpulsar.dev`)"
      - "traefik.http.routers.redpulsar.tls=false"
      - "traefik.http.routers.redpulsarTLS.entrypoints=https"
      - "traefik.http.routers.redpulsarTLS.rule=Host(`redpulsar.dev`)"
      - "traefik.http.routers.redpulsarTLS.tls=true"
      # create a rule to redirect to https
      - "traefik.http.middlewares.redpulsar-redirect-to-https.redirectscheme.scheme=https"
      # apply it on the http router
      - "traefik.http.routers.redpulsar.middlewares=redpulsar-redirect-to-https@docker"
      # create a middleware for compression
      - "traefik.http.middlewares.redpulsar-compress.compress=true"
      # apply it on the router
      - "traefik.http.routers.redpulsarTLS.middlewares=redpulsar-compress@docker"
    ports:
      - "127.0.0.1:2015:2015"

networks:
  default:
    external:
      name: traefik
```

The above will use the container built on gitlab to serve the static website. the compression on the other hand doesn't work, example:

```
$ curl https://redpulsar.dev/js/particles.min.js -I --compressed -L --resolve redpulsar.dev:443:127.0.0.1
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 23364
Content-Type: application/javascript
Date: Sun, 02 Feb 2020 19:22:24 GMT
Etag: "q536j5i10"
Last-Modified: Sun, 02 Feb 2020 18:11:29 GMT
Server: Caddy
Vary: Accept-Encoding
```

The compose for the traefik itself is:

```yml
version: "3.3"
services:
  traefik:
    image: "traefik:v2.1.0"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dyn.toml:/etc/traefik/dyn.toml
      - ./certs:/etc/certs
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.redpulsar.dev`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"

networks:
  default:
    external:
      name: traefik
```

In either case you can just omit the https part and test out compression, I couldn't make it work even with large responses, e.g. Content-Length of `23364` bytes.

if you need anything else please let me know.
