### ISSUE TITLE
Kubernetes Ingress resolved incorrectly

### ISSUE THREAD

**Issue by mishushakov** [containous/traefik#6285]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: '*.hello.ushakov.co'
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-node
          servicePort: 80
```

### What did you expect to see?

Nginx default homepage

### What did you see instead?

Wildcard domain being resolved incorrectly

<img width="409" alt="Screenshot 2020-02-06 at 16 54 35" src="https://user-images.githubusercontent.com/10400064/73954768-97935980-4902-11ea-9786-479e5b0f9a2e.png">

and `404 page not found` as the result

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes on GKE + LoadBalancer, Traefik v2.1

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:v2.1
        args:
          - --api.insecure
          - --ping
          - --entrypoints.http.Address=:80
          - --entrypoints.https.Address=:443
          - --entrypoints.smtp.address=:25
          - --entrypoints.smtp-auth.address=:587
          - --entrypoints.smtps.address=:465
          - --entrypoints.imap.address=:145
          - --entrypoints.imaps.address=:993
          - --providers.kubernetescrd
          - --providers.kubernetesingress
          - --providers.kubernetesingress.ingressclass=traefik
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          - name: traefik
            containerPort: 8080
          - name: ping
            containerPort: 8000
          - name: smtp
            containerPort: 25
          - name: smtp-auth
            containerPort: 587
          - name: smtps
            containerPort: 465
          - name: imap
            containerPort: 145
          - name: imaps
            containerPort: 993
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
```

Thanks
