### ISSUE TITLE
Traefik v2 prevents larger mvn deploy to Nexus

### ISSUE THREAD

**Issue by BSchwetzel** [containous/traefik#6289]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We are using Traefik (v2) in front of a Nexus Repository Manager. When trying to deploy some artifacts via mvn deploy (3.5 MB is already too large) we are getting an error message from Maven:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project guestbook: Failed to deploy artifacts: Could not transfer artifact de.my-company.my-department:guestbook:jar:1.0.0 from/to nexus (https://my-company-repo.internal/nexus/repository/my-department-releases/): Transfer failed for https://my-company-repo.internal/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar: Software caused connection abort: socket write error -> [Help 1]
```

Nexus itself has the following to say:

```
2020-02-07 06:51:41,962+0100 WARN  [qtp1484446092-50]  my-user org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: PUT /nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar
org.sonatype.nexus.blobstore.api.BlobStoreException: BlobId: tmp$ec5032b0-80f2-4831-9eaa-a8acea6530b2, org.eclipse.jetty.io.EofException: Early EOF, Cause: Early EOF
...
Caused by: org.eclipse.jetty.io.EofException: Early EOF
...
```

If I deploy the same artifact without traefik it obviously works, hence this report.

### What did you expect to see?
mvn deploy works normally

### What did you see instead?
mvn deploy fails due to the above errors

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik_static.yaml
```yaml
entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik
    filename: traefik_dynamic.yaml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: true
    network: "my-department"
    watch: true
log:
  level: "DEBUG"
accessLog: {}
api:
  dashboard: true
ping:
  entryPoint: "web-secure"

```

traefik_dynamic.yaml
```
http:
  routers:
    api:
      entryPoints:
        - web-secure
      middlewares:
        - dashboard-trailing-slash
        - api-auth
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: "api@internal"
      priority: 500
      tls: {}
    tls-redirect:
      entryPoints:
        - web
      middlewares:
        - tls-redirect
      service: dummy-service
      rule: HostRegexp(`{any:.*}`)
      priority: 1000

  services:
    dummy-service:
      loadBalancer:
        servers:
          - url: ""
  middlewares:
    sts:
      headers:
        stsSeconds: 15768000
    tls-redirect:
      redirectScheme:
        scheme: https
    api-auth:
      basicAuth:
        usersFile: "/run/secrets/traefik_api_users"
    dashboard-trailing-slash:
      redirectRegex:
        regex: '^(.*)/dashboard$'
        replacement: '${1}/dashboard/'
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/run/secrets/ssl_cert"
        keyFile: "/run/secrets/ssl_key"

```

Nexus Labels (from docker swarm stack file)
```
- "traefik.http.routers.nexus.rule=PathPrefix(`/nexus`)"
        - "traefik.http.routers.nexus.tls"
        - "traefik.http.routers.nexus.middlewares=sts@file"
        - "traefik.http.services.nexus.loadBalancer.server.port=8081"
        - "traefik.docker.lbswarm=true"
        - "traefik.docker.network=stack_my-department"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I included two requests, the first one uploads the jar and fails, the second one uploads the POM and succeeds.
```
time="2020-02-07T05:51:41Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip,deflate\"],\"Authorization\":[\"Basic dGhhbmtzIGZvciB0cnlpbmcgOi0p\"],\"Cache-Control\":[\"no-cache\"],\"Cache-Store\":[\"no-store\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"71920010\"],\"Expect\":[\"100-continue\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Apache-Maven/3.6.3 (Java 11.0.4-ojdkbuild; Windows 10 10.0)\"],\"X-Forwarded-Host\":[\"my-company-repo.internal\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0274be27986f\"],\"X-Real-Ip\":[\"192.168.2.34\"]},\"ContentLength\":71920010,\"TransferEncoding\":null,\"Host\":\"my-company-repo.internal\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.34:34677\",\"RequestURI\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar\",\"TLS\":null}"
time="2020-02-07T05:51:41Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip,deflate\"],\"Authorization\":[\"Basic dGhhbmtzIGZvciB0cnlpbmcgOi0p\"],\"Cache-Control\":[\"no-cache\"],\"Cache-Store\":[\"no-store\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"71920010\"],\"Expect\":[\"100-continue\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Apache-Maven/3.6.3 (Java 11.0.4-ojdkbuild; Windows 10 10.0)\"],\"X-Forwarded-Host\":[\"my-company-repo.internal\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0274be27986f\"],\"X-Real-Ip\":[\"192.168.2.34\"]},\"ContentLength\":71920010,\"TransferEncoding\":null,\"Host\":\"my-company-repo.internal\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.34:34677\",\"RequestURI\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar\",\"TLS\":null}" ForwardURL="http://10.0.1.31:8081"
time="2020-02-07T05:51:41Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip,deflate\"],\"Authorization\":[\"Basic dGhhbmtzIGZvciB0cnlpbmcgOi0p\"],\"Cache-Control\":[\"no-cache\"],\"Cache-Store\":[\"no-store\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"71920010\"],\"Expect\":[\"100-continue\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Apache-Maven/3.6.3 (Java 11.0.4-ojdkbuild; Windows 10 10.0)\"],\"X-Forwarded-Host\":[\"my-company-repo.internal\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0274be27986f\"],\"X-Real-Ip\":[\"192.168.2.34\"]},\"ContentLength\":71920010,\"TransferEncoding\":null,\"Host\":\"my-company-repo.internal\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.34:34677\",\"RequestURI\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar\",\"TLS\":null}"
192.168.2.34 - - [07/Feb/2020:05:51:41 +0000] "PUT /nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.jar HTTP/1.1" 502 11 "-" "-" 4 "nexus@docker" "http://10.0.1.31:8081" 430ms
time="2020-02-07T05:51:41Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip,deflate\"],\"Authorization\":[\"Basic dGhhbmtzIGZvciB0cnlpbmcgOi0p\"],\"Cache-Control\":[\"no-cache\"],\"Cache-Store\":[\"no-store\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"3670\"],\"Expect\":[\"100-continue\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Apache-Maven/3.6.3 (Java 11.0.4-ojdkbuild; Windows 10 10.0)\"],\"X-Forwarded-Host\":[\"my-company-repo.internal\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0274be27986f\"],\"X-Real-Ip\":[\"192.168.2.34\"]},\"ContentLength\":3670,\"TransferEncoding\":null,\"Host\":\"my-company-repo.internal\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.34:45869\",\"RequestURI\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom\",\"TLS\":null}"
time="2020-02-07T05:51:41Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip,deflate\"],\"Authorization\":[\"Basic dGhhbmtzIGZvciB0cnlpbmcgOi0p\"],\"Cache-Control\":[\"no-cache\"],\"Cache-Store\":[\"no-store\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"3670\"],\"Expect\":[\"100-continue\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Apache-Maven/3.6.3 (Java 11.0.4-ojdkbuild; Windows 10 10.0)\"],\"X-Forwarded-Host\":[\"my-company-repo.internal\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0274be27986f\"],\"X-Real-Ip\":[\"192.168.2.34\"]},\"ContentLength\":3670,\"TransferEncoding\":null,\"Host\":\"my-company-repo.internal\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.34:45869\",\"RequestURI\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom\",\"TLS\":null}" ForwardURL="http://10.0.1.31:8081"
time="2020-02-07T05:51:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip,deflate\"],\"Authorization\":[\"Basic dGhhbmtzIGZvciB0cnlpbmcgOi0p\"],\"Cache-Control\":[\"no-cache\"],\"Cache-Store\":[\"no-store\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"3670\"],\"Expect\":[\"100-continue\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Apache-Maven/3.6.3 (Java 11.0.4-ojdkbuild; Windows 10 10.0)\"],\"X-Forwarded-Host\":[\"my-company-repo.internal\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0274be27986f\"],\"X-Real-Ip\":[\"192.168.2.34\"]},\"ContentLength\":3670,\"TransferEncoding\":null,\"Host\":\"my-company-repo.internal\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.34:45869\",\"RequestURI\":\"/nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom\",\"TLS\":null}"
192.168.2.34 - - [07/Feb/2020:05:51:41 +0000] "PUT /nexus/repository/my-department-releases/de/my-company/my-department/guestbook/1.0.0/guestbook-1.0.0.pom HTTP/1.1" 201 0 "-" "-" 5 "nexus@docker" "http://10.0.1.31:8081" 239ms
```
