### ISSUE TITLE
CRDs are ignored

### ISSUE THREAD

**Issue by mishushakov** [containous/traefik#6292]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

`kubectl apply` this:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-to-https 
  namespace: traefik
spec:
  entryPoints:
    - http
  routes:
    - match: HostRegexp(`{any:.+}`)
      kind: Rule 
      services:
        - name: traefik
          port: 80  
      middlewares:
        - name: redirect-https
          namespace: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware 
metadata:
  name: redirect-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: "true"
    port: 443
```

### What did you expect to see?

CRDs being created

### What did you see instead?

Nothing

<img width="1376" alt="Screenshot 2020-02-07 at 23 18 25" src="https://user-images.githubusercontent.com/10400064/74070055-30f46580-4a00-11ea-98e3-06f97e797e12.png">

<img width="1376" alt="Screenshot 2020-02-07 at 23 18 37" src="https://user-images.githubusercontent.com/10400064/74070075-3c479100-4a00-11ea-908d-7084258d58d0.png">

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.1.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      containers:
      - name: traefik
        image: traefik:v2.1
        args:
          - --ping
          - --entrypoints.http.Address=:80
          - --entrypoints.https.Address=:443
          - --providers.kubernetescrd
          - --providers.kubernetesingress
          - --providers.kubernetesingress.ingressclass=traefik
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          - name: ping
            containerPort: 8000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
```
