### ISSUE TITLE
Whitelist SourceRange via docker-compose IS NOT respected!!

### ISSUE THREAD

**Issue by MacGyver27** [containous/traefik#6296]
Just found out that my docker config part for sourceRange is no longer working! I tested it like year ago and it worked - restricting access only to specific prefixes..
Whiteliste sourcerange via file config still works.

Was on version 1.7.16 and tested it for the latest (v1) as well 1.7.20.. this is crucial security bridge.

_Linux Debian Buster
docker -v
Docker version 19.03.5, build 633a0ea838
docker-compose -v
docker-compose version 1.25.3, build d4d1b42b_

None of the following was understood by traefik:
```yml
- traefik.frontend.whitelist.sourceRange=192.168.255.0/24
- traefik.frontend.whitelist.sourceRange=[192.168.255.0/24]
- traefik.frontend.whitelist.sourceRange=192.168.255.0/24,10.8.0.0/24
- traefik.frontend.whitelist.sourceRange=192.168.255.0/24, 10.8.0.0/24
- traefik.frontend.whitelist.sourceRange=[192.168.255.0/24,10.8.0.0/24]
- "traefik.frontend.whitelist.sourceRange=192.168.255.0/24"
- "traefik.frontend.whitelist.sourceRange=[192.168.255.0/24]"
- "traefik.frontend.whitelist.sourceRange=192.168.255.0/24,10.8.0.0/24"
- "traefik.frontend.whitelist.sourceRange=192.168.255.0/24, 10.8.0.0/24"
- "traefik.frontend.whitelist.sourceRange=[192.168.255.0/24,10.8.0.0/24]"

or
traefik.frontend.whitelist.sourceRange: 192.168.255.0/24, 10.8.0.0/24
traefik.frontend.whitelist.sourceRange: "192.168.255.0/24, 10.8.0.0/24"
traefik.frontend.whitelist.sourceRange: [192.168.255.0/24, 10.8.0.0/24]
traefik.frontend.whitelist.sourceRange: ["192.168.255.0/24", "10.8.0.0/24"]
```
