### ISSUE TITLE
Traefik v2 Kubernetes Ingress Controller doesn't update Ingress resource status

### ISSUE THREAD

**Issue by BretFisher** [containous/traefik#6303]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using Kubernetes 1.17 and traefik:2.1.4, I started a basic ingress controller. Then I create a deployment/service/ingress for a simple image `errm/cheese:cheddar` with this ingress resource:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheddar
spec:
  rules:
  - host: cheddar.192.168.76.210.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: 80
```
Everything works in terms of traffic and connects through the ingress to the cheddar service, but the `Address:` field of `kubectl get ingress` is empty.  Doing a `kubectl get ingress/cheddar -o yaml` shows an empty `status.loadBalancer` key.

### What did you expect to see?

`ingress.status.loadBalancer` filled with the service IP of the traefik proxy, similar to how NGINX ingress controller would update `ingress.status.loadBalancer`

### What did you see instead?

An empty `ingress.status.loadBalancer`

If I leave all cheddar resources, remove the traefik controller, replace with the nginx controller, it'll auto update the `ingress.status.loadBalancer` and log doing so. Then if I swap back by deleting nginx and applying traefik ingress controller resources, traefik will leave the old IP in the cheddar ingress resource and it'll be incorrect, with the wrong IP of the previous nginx ingress controller service.

```yaml
status:
  loadBalancer:
    ingress:
    - ip: 10.152.183.99
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:2.1.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

args
```yaml
- --providers.kubernetesingress=true
- --log=true
- --log.level=DEBUG
- --accesslog=true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
none
```
