### ISSUE TITLE
ReverseProxy read error during body copy: unexpected EOF

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#6308]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm serving [Odoo](https://github.com/odoo/odoo) behind Traefik.

I'm seeing random failures like this in Traefik's logs:

```
feb 12 14:23:08 example.com b94438498337[990]: 2020/02/12 13:23:08 reverseproxy.go:437: httputil: ReverseProxy read error during body copy: unexpected EOF
```

Whenever a log like that is logged, the download the user is doing gets aborted.

I'm serving hardware firmwares with this method, so you can imagine how critical this can be: an incomplete firmware being written could convert your camera in a luxury paperweight.

### What did you expect to see?

Files being downloaded correctly.

### What did you see instead?

Downloaded files are corrupted.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.4
Codename:     cantal
Go version:   go1.13.7
Built:        2020-02-06T17:10:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Ubuntu host deployed with docker compose.

Traefik deployment:

<details><summary>docker-compose.yaml</summary>

```yaml
version: "2.4"

services:
  proxy:
    image: "traefik:2.1"
    networks:
      shared:
        aliases: []
      private:
      public:
    volumes:
      - acme:/etc/traefik/acme:rw,Z
    ports:
        # HTTP port is always open
        - "80:80"

        # ACME is configured, so open HTTPS port also
        - "443:443"

    labels:
      traefik.docker.network: "inverseproxy_shared"
      traefik.enable: "true"
      # Redirect all HTTP traffic to HTTPS
      traefik.http.middlewares.force-secure.redirectscheme.permanent: "true"
      traefik.http.middlewares.force-secure.redirectscheme.scheme: "https"
      traefik.http.routers.web-global.entrypoints: "web-insecure"
      traefik.http.routers.web-global.middlewares: force-secure
      traefik.http.routers.web-global.rule: hostregexp(`{any:.+}`)

    depends_on:
      - dockersocket
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
    tty: true
    command:
          # Common options
          - --entrypoints.web-insecure.address=:80
          - --log.level=debug
          - --providers.docker.endpoint=http://dockersocket:2375
          - --providers.docker.exposedbydefault=false
          - --providers.docker.network=inverseproxy_shared
          - --providers.docker=true

          # HTTP + HTTPS
          - --entrypoints.web-main.address=:443
          - --certificatesresolvers.letsencrypt.acme.email=alerts@example.com
          - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json
          # Enable http-01 challenge
          - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web-insecure

  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped

networks:
  shared:
    internal: true
    driver_opts:
      encrypted: 1

  private:
    internal: true
    driver_opts:
      encrypted: 1

  public:
    driver_opts:
      encrypted: 1

volumes:
  acme:
```

</details>

I haven't been able to reproduce reliably this problem, I just find it happening under some environments, and not under others, while deployed practically identically.

But it seems like network unstability makes it trigger more easily. It gets triggered 100% of the times with this Fish command:

```fish
➤ while true
      trickle -L 300 -sd 100 curl https://example.com/slides/slide/something-349/download | wc --bytes
  end
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 72 13.4M   72  9.7M    0     0  71235      0  0:03:17  0:02:24  0:00:53 69784
curl: (18) transfer closed with 3811767 bytes remaining to read
10261536
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 40 13.4M   40 5577k    0     0  67837      0  0:03:27  0:01:24  0:02:03 64860
curl: (18) transfer closed with 8361447 bytes remaining to read
5711856
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 66 13.4M   66 9138k    0     0  67524      0  0:03:28  0:02:18  0:01:10 45843
curl: (18) transfer closed with 4715191 bytes remaining to read
9358112
...
```

:point_up: There you can see that each time it downloads a different size (it should be always the same) and that curl fails with `curl: (18) transfer closed with 4715191 bytes remaining to read`. Notice the usage of `trickle` to limit the connection speed.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

The process is:

1. curl asks traefik to download that file.
1. Traefik logs these lines

   ```
   feb 12 14:23:04 example.com b94438498337[990]: DEBU[2020-02-12T13:23:04Z] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/slides/slide/something-349/download\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.66.0\"],\"X-Forwarded-Host\":[\"example.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"b94438498337\"],\"X-Real-Ip\":[\"1.2.3.4\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"1.2.3.4:51722\",\"RequestURI\":\"/slides/slide/something-349/download\",\"TLS\":null}"
   feb 12 14:23:04 example.com b94438498337[990]: DEBU[2020-02-12T13:23:04Z] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/slides/slide/something-349/download\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.66.0\"],\"X-Forwarded-Host\":[\"example.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"b94438498337\"],\"X-Real-Ip\":[\"1.2.3.4\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"1.2.3.4:51722\",\"RequestURI\":\"/slides/slide/something-349/download\",\"TLS\":null}" ForwardURL="http://172.20.0.4:8069"
   feb 12 14:23:08 example.com b94438498337[990]: 2020/02/12 13:23:08 reverseproxy.go:437: httputil: ReverseProxy read error during body copy: unexpected EOF
   feb 12 14:23:08 example.com b94438498337[990]: DEBU[2020-02-12T13:23:08Z] vulcand/oxy/roundrobin/rr: completed ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/slides/slide/something-349/download\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.66.0\"],\"X-Forwarded-Host\":[\"example.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"b94438498337\"],\"X-Real-Ip\":[\"1.2.3.4\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"1.2.3.4:51722\",\"RequestURI\":\"/slides/slide/something-349/download\",\"TLS\":null}"
   ```
1. After awhile, curl, which is downloading slowly, fails with `curl: (18) transfer closed with 3811767 bytes remaining to read`

I wonder:

1. Why is the traefik <-> backend aborted with unexpected EOF?
1. Why does this only happen on some deployments?
1. Why curl only receives the failure after awhile?

I've spent 3 days trying to debug without any luck. According to #2903 (which is probably a duplicated that never got fixed really), it would work fine in nginx. This issue is so critical that we're considering the switch to nginx, but I love Traefik and I would love to be able to fix that issue instead.

Notice that I've been suffering this since 1.5, and that I asked this several times in slack without luck and [also in the forum](https://community.containo.us/t/incomplete-downloads/2066?u=yajo).

@Tecnativa TT21841
