### ISSUE TITLE
HTTP and HTTPS router to same domain and path from Kubernetes Ingress Provider

### ISSUE THREAD

**Issue by Aniem** [containous/traefik#6317]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using a build from branch master (built Feb 13th, 2020 around 18:00 UTC) of Traefik 2.x, I generated a Middleware redirecting to HTTPS, an Ingress listening on / at example.org on HTTP referencing the Middleware, and an Ingress listening on / at example.org on HTTPS with a certificate, associated to a simple whoami service

### What did you expect to see?

- `curl -vkL http://example.org` gets the HTTP router, gets Redirected to https://example.org, and shows the page provided by the whoami service
-  The Traefik Dashboard should show two routers with the same rules, two different names, one with TLS, and the other without TLS

### What did you see instead?

- the curl on http either 
  - gets redirected to the https which answers a 404 not found with the default (incorrect) certificate
  - answers directly a 404, in which case a `curl https://example.org/` answers the correct page with the correct certificate
 Both possibilities change at random over time
- Traefik Dashboard shows only one Router matching the rule `Host("example.org") && PathPrefix("/")` sometimes with TLS support, sometimes without

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      7c430e5c9de5305b2f58dce77cdf50eeba944a25
Codename:     cheddar
Go version:   go1.13.7
Built:        2020-02-13_04:06:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: force-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: false
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-http-2-notls
  namespace: trv2
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "default-force-https@kubernetescrd"
spec:
  rules:
  - host: "example.org"
    http:
      paths:
      - path: /
        backend:
          serviceName: echo-http
          servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-http-2
  namespace: default
  annotations:
    cert-manager.io/issuer: "acme-staging"
spec:
  tls:
  - hosts:
    - example.org
    secretName: test-ingress-crt
  rules:
  - host: "example.org"
    http:
      paths:
      - path: /
        backend:
          serviceName: echo-http
          servicePort: 8080
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
No relevant log output found in log in DEBUG level
