### ISSUE TITLE
Kubernetes 2.1 documentation incomplete/difficult to understand

### ISSUE THREAD

**Issue by GoingOffRoading** [containous/traefik#6322]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm moving my services from a Docker host to a Kubernetes host which includes Traefik as my edge router.  The first half of the documentation on getting started in Kubernetes (The User Guide under 2.1: https://docs.traefik.io/user-guides/crd-acme/ ) is great but things rapidly fall apart when it comes to adding services to the entree points.

### What did you expect to see?

Clear step by step guides (with snippets/code examples) on the primary use-cases and value propositions of Traefik v2.x:

- Routing of API traffic (non-port 80/443 traffic) w/TLS
- Routing of web traffic (port 80/443 traffic) w/ LetsEncrypt
- Examples of IngressRoute (the BIG 2.x feature) and Ingress, with clear explanations between the two
- Middleware examples

### What did you see instead?

User Guides & general documentation that is inconsistent with deltas not being explained.

Examples:

In the User Guides: Kubernetes and Let's Encrypt under the v2.1 Latest docs (https://docs.traefik.io/user-guides/crd-acme/) , the documentation uses a IngressRoute example that doesn't appear to work but port 80 traffic works perf if you switch to simple Ingress.  No examples of Ingress in the Kuberneres & Let's Encrypt documentation.  

The same Kubernetes guide above uses "default" in fields like "Args:  --certificatesresolvers.default.acme.tlschallenge".  But if you go to the HTTPS & TLS: Let's Encrypt section of the same v2.1 latest documentation, the API documentation here that would be used for Args uses "le" instead of "default" and appends "=true" to the field:" --certificatesResolvers.le.acme.tlsChallenge=true".  **This is not consistent and the delta is not explained/documented.**

In some examples of this section of v2.1 documentation (https://docs.traefik.io/), port 80 and 443 are labeled as web and websecure.  In others it's http and https.  Not consistent.

Redirect (http to https) are HIDDEN.  I could not find one example of an http to https redirect in the docs examples but it is mentioned once in the Migration: Traefik v1 to v2: https://docs.traefik.io/migration/v1-to-v2/  This is under a middleware example, is missing from the ACME (LetsEncrypt) example and is not explained anywhere.  Of the redirects in the Middlewares documentation (https://docs.traefik.io/middlewares/redirectscheme/), it's totally unclear what we're supposed to use.

More examples can be provided.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: traefik:v2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:27:49Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

API calls (but also experimented with toml looking for a solution)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Can provide if needed
```

### Node

**Please take this request/report seriously.**  I'm only posting here after:

- Hours of experimentation with different integration options/fields in the Traefik x2.1 documentation
- Scouring threads on Reddit, StackOverflow and Traefik Community
- Starting threads on Reddit, StackOverflow and Traefik Community
- Searching GitHub repositories 

And not really getting anywhere (outside of very basic functionality).

Given that the general internet (listed above) doesn't isn't chalk full of 2.x examples (like it is with 1.x examples), lowering the barriers of entry to getting started with 2.x will significantly aid in it's adoption.

**Comment by ldez** [comment]
Hello,

we take seriously every issue.

---

> In the User Guides: Kubernetes and Let's Encrypt under the v2.1 Latest docs (https://docs.traefik.io/user-guides/crd-acme/) , the documentation uses a IngressRoute example that doesn't appear to work

In the user guide, the ports are `8000` and `4443`.

---

> The same Kubernetes guide above uses "default" in fields like "Args: --certificatesresolvers.default.acme.tlschallenge". But if you go to the HTTPS & TLS: Let's Encrypt section of the same v2.1 latest documentation, the API documentation here that would be used for Args uses "le" instead of "default" and appends "=true" to the field:" --certificatesResolvers.le.acme.tlsChallenge=true". In one of the [Traefik blog posts](https://github.com/containous/blog-posts/blob/master/2019_09_10-101_docker/docker-compose-06.yml), they replace 'le' or 'default' with 'leresolver'. **This is not consistent and the deltas are not explained/documented.**

1. CLI flag

CLI flag for boolean can have two syntax:
```bash
--foo
# or
--foo=true
```

It's a standard with CLI flags.

2. certificatesresolvers name
`--certificatesresolvers.<name>.acme.tlschallenge`
`<name>` is the resolver name, it's a random name.

- https://docs.traefik.io/v2.1/reference/static-configuration/cli/
- https://docs.traefik.io/v2.1/https/acme/#configuration-examples section "Configuration Reference"

3. The blog posts and the documentation don't have to use the same random name.

---

> In some examples of this section of v2.1 documentation (https://docs.traefik.io/), port 80 and 443 are labeled as web and websecure. In others it's http and https. Not consistent.

We use `web` and `websecure` in all the documentation, maybe we have miss something but I don't find any entrypoint named `http` or `https`.

---

> Redirect (http to https) are HIDDEN. I could not find one example of an http to https redirect in the docs examples but it is mentioned once in the Migration: Traefik v1 to v2: https://docs.traefik.io/migration/v1-to-v2/ This is under a middleware example, is missing from the ACME (LetsEncrypt) example and is not explained anywhere. Of the redirects in the Middlewares documentation (https://docs.traefik.io/middlewares/redirectscheme/), it's totally unclear what we're supposed to use.

Redirect are not hidden, it's the middleware [redirectscheme](https://docs.traefik.io/v2.1/middlewares/redirectscheme/).

It's possible to add more examples of the use of this middleware.

- https://docs.traefik.io/v2.1/middlewares/redirectscheme/
- https://docs.traefik.io/v2.1/middlewares/overview/#configuration-example

The relation, you made, between the redirect and ACME is unclear to me.

---

Traefik is an open source project: the code, the documentation, the user guides are made by the community.

A contributor adds elements that he knows or has learned. It is a system of continuous improvement.

So everything is not perfect, and will never be perfect because of the [essence of the open source](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar), to counter this imperfection, we set up a forum, we read, sort, process the issues every day.

We (the traefik team) do [our best](https://twitter.com/jaqx0r/status/1227709121631334402), and we try every day to improve and enhance the code, the documentation, etc. . The contributors are trying to do the same.

We (the traefik team and the contributors) will try to fix some elements that you don't find clear, but it will be great if you help us by creating PRs on documentation and become a documentation contributor.

**Comment by GoingOffRoading** [comment]
@ldez I think the RedirectScheme is a good example and what I am likely struggling to convey.

If I'm understanding you and the above documentation links correctly, RedirectScheme replaces the 1.x functionality like:

```
[entryPoints.http]
address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
[entryPoints.https]
address = ":443"
  [entryPoints.https.tls]
```

But the 2.x documentation doesn't explain what this, how it works or how to configure.

Here's the Kubernetes example:

```
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirectscheme
spec:
  redirectScheme:
    scheme: https
```

scheme: https... Ok... What does that mean?  Do I need to setup something else elsewhere for the scheme "https" to mean Port 80 to port 443 (like in my Traefik 1.x example above).  Is scheme "https" already configured to do that?  How do I know any of these things?

There doesn't appear to be a community understanding of this functionality when you look at StackOverflow threads (example: https://stackoverflow.com/questions/58356714/how-to-redirect-http-to-https-with-traefik-2-0-and-docker-compose-labels ), because the comments are disagreeing with proposed solutions.  Yes, this is a Docker example, not Kubernetes.

I hope these comments are helpful... I am honestly a huge fan of the Traefik product and my use at home is so I can figure out if/where/when it's a good candidate in enterprise use cases.

**Comment by GoingOffRoading** [comment]
Also, the RedirectScheme would be a killer thing to add to the end of the Traefik Routes at the end of the User Guides: Kubernetes and Let's Encrypt: https://docs.traefik.io/user-guides/crd-acme/

Learning Goal: You've created the two services and hopefully have https working on one, now make all http requests redirect to https.

**Comment by dbsanfte** [comment]
I too have been moving from a Docker/labels to a Kubernetes IngressRoute config and the docs have been really scattered and inconsistent. There is only one end-to-end use case that I can see, this one using ACME / LetsEncrypt:

https://docs.traefik.io/user-guides/crd-acme/

But since I'm bringing my own certs, I basically had to figure things out for myself in terms of mounting them into the container as volumes, what config options to set, etc.

I love Traefik but I really agree with the OP, the Kubernetes IngressRoute docs are scatterbrained and incomplete.

**Comment by dbsanfte** [comment]
Yeah, my main gripe is basically this page:

https://docs.traefik.io/providers/kubernetes-crd/

It is written only with a LetsEncrypt example, zero mention at all of the (very common) use case of bringing your own certs.

**Comment by enriko-riba** [comment]
I am also struggling for over a week without any success. I jumped on board with v2 in a K8s environment and found no clear guide targeting new users that are struggling with basic concepts. 
I figured reading the doc for v1.x will help but soon realized they are not even closely compatible with v2.x. 

Also don't understand the focus on docker environment - I doubt there is a meaningful user base with docker in production. There is only sparse Kubernetes documentation with non complete end 2 end examples.

The difference between static/dynamic configuration is confusing the docs states you need to pick one because they are exclusive while on other places it is said you can mix them. In v2 docs the static configuration is mentioned to be the startup configuration but yet in other places the fileprovider is called static configuration. Anyway I still don't get it.

The scattered yaml (and other) examples are cut out of context providing just fragments without any clue where such fragments belong and how ti use them - the big picture is missing.

The installation was a nightmare too. We are not using Helm so I tried all the guides how to create the kubernetes crd's, rbac, deployments etc None of the guides are consistent and it always failed at some point. At the end I tried helm install. Helm worked but I had to retry several times cause the installation errored out on existing kubernetes objects. I deleted them manually one by one after repeating install and getting new errors. I wish I tried Helm on day 1 not day 3!

I still cant figure out how to enable the dashboard, getting 404 for `domain/dashboard/ `or `traefik external ip/dashboard/`

Command line args...found no docs at all, had to compile a list from examples I found and trial and error figuring out what works.

I managed to get the whoami example to work but still can't figure out how to setup a single route where the backend service is not listening on every path like:
mydomain.com/a/{b}/{c} goes to service1/api/somepath/{b}/{c} 

IMHO the good folks maintaining the docs are veterans and know how to use Traefik so they don't even recognize the issues and how inconclusive the docs are for newcomers.

I honestly appreciate all the hard work but it seems way too complicated for something claiming to be easy configurable.

**Comment by rherrick** [comment]
I'm having a similar issue trying to get the IngressRoute configuration working [as described in the documentation](https://docs.traefik.io/routing/providers/kubernetes-crd/). I copied each of the definitions from the **Configuring KubernetesCRD and Deploying/Exposing Services** configuration example. There was a syntax error in one of the configurations (I submitted a [pull request with a fix](https://github.com/containous/traefik/pull/6878)) but otherwise everything started fine. The problem is that everything seems to start fine but Traefik doesn't pick up any of the services defined in the **Whoami** block. When I start up with the [standard Ingress configuration](https://docs.traefik.io/routing/providers/kubernetes-ingress/) I can see the routing configurations to the **whoami** containers, but for the **IngressRoute** configuration I have the **api** and **dashboard** routers and the **api**, **dashboard**, and **noop** services. It's unaware of the **whoami** services, which are up and running:

```
$ kubectl get all
NAME                             READY   STATUS    RESTARTS   AGE
pod/traefik-6c4dc99559-g9djh     1/1     Running   0          3m57s
pod/whoami-67877457b8-prhbn      1/1     Running   0          3m47s
pod/whoami-67877457b8-sz7kh      1/1     Running   0          3m47s
pod/whoamitcp-5484cb886c-2bb66   1/1     Running   0          3m47s
pod/whoamitcp-5484cb886c-qcvfc   1/1     Running   0          3m47s
pod/whoamiudp-5b9d8b758d-6n6nl   1/1     Running   0          3m47s
pod/whoamiudp-5b9d8b758d-fxv6q   1/1     Running   0          3m47s

NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                      AGE
service/kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP                                      25h
service/traefik      LoadBalancer   10.107.207.137   <pending>     80:30777/TCP,8080:30928/TCP,8000:31311/TCP   3m57s
service/traefikudp   LoadBalancer   10.100.198.51    <pending>     9000:31771/UDP                               3m56s
service/whoami       ClusterIP      10.100.252.109   <none>        80/TCP                                       3m47s
service/whoamitcp    ClusterIP      10.111.159.58    <none>        8080/TCP                                     3m47s
service/whoamiudp    ClusterIP      10.104.15.198    <none>        8080/TCP                                     3m47s

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/traefik     1/1     1            1           3m57s
deployment.apps/whoami      2/2     2            2           3m47s
deployment.apps/whoamitcp   2/2     2            2           3m47s
deployment.apps/whoamiudp   2/2     2            2           3m47s

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/traefik-6c4dc99559     1         1         1       3m57s
replicaset.apps/whoami-67877457b8      2         2         2       3m47s
replicaset.apps/whoamitcp-5484cb886c   2         2         2       3m47s
replicaset.apps/whoamiudp-5b9d8b758d   2         2         2       3m47s
```

I like Traefik but it's been very difficult to get going due to the lack of solid and easy-to-run examples, along with little information on how to troubleshoot and understand things like, e.g., why the **whoami** services aren't being picked up by Traefik in the **IngressRoute** example.

**Comment by kallisti5** [comment]
v2.x is such a mess to be honest.  The documentation is scattered.. I just want the IngressRoute's to work and basic documentation on how to get there :-(

**Comment by sonisaurabh19** [comment]
> I'm having a similar issue trying to get the IngressRoute configuration working [as described in the documentation](https://docs.traefik.io/routing/providers/kubernetes-crd/). I copied each of the definitions from the **Configuring KubernetesCRD and Deploying/Exposing Services** configuration example. There was a syntax error in one of the configurations (I submitted a [pull request with a fix](https://github.com/containous/traefik/pull/6878)) but otherwise everything started fine. The problem is that everything seems to start fine but Traefik doesn't pick up any of the services defined in the **Whoami** block. When I start up with the [standard Ingress configuration](https://docs.traefik.io/routing/providers/kubernetes-ingress/) I can see the routing configurations to the **whoami** containers, but for the **IngressRoute** configuration I have the **api** and **dashboard** routers and the **api**, **dashboard**, and **noop** services. It's unaware of the **whoami** services, which are up and running:
> 
> ```
> $ kubectl get all
> NAME                             READY   STATUS    RESTARTS   AGE
> pod/traefik-6c4dc99559-g9djh     1/1     Running   0          3m57s
> pod/whoami-67877457b8-prhbn      1/1     Running   0          3m47s
> pod/whoami-67877457b8-sz7kh      1/1     Running   0          3m47s
> pod/whoamitcp-5484cb886c-2bb66   1/1     Running   0          3m47s
> pod/whoamitcp-5484cb886c-qcvfc   1/1     Running   0          3m47s
> pod/whoamiudp-5b9d8b758d-6n6nl   1/1     Running   0          3m47s
> pod/whoamiudp-5b9d8b758d-fxv6q   1/1     Running   0          3m47s
> 
> NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                      AGE
> service/kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP                                      25h
> service/traefik      LoadBalancer   10.107.207.137   <pending>     80:30777/TCP,8080:30928/TCP,8000:31311/TCP   3m57s
> service/traefikudp   LoadBalancer   10.100.198.51    <pending>     9000:31771/UDP                               3m56s
> service/whoami       ClusterIP      10.100.252.109   <none>        80/TCP                                       3m47s
> service/whoamitcp    ClusterIP      10.111.159.58    <none>        8080/TCP                                     3m47s
> service/whoamiudp    ClusterIP      10.104.15.198    <none>        8080/TCP                                     3m47s
> 
> NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/traefik     1/1     1            1           3m57s
> deployment.apps/whoami      2/2     2            2           3m47s
> deployment.apps/whoamitcp   2/2     2            2           3m47s
> deployment.apps/whoamiudp   2/2     2            2           3m47s
> 
> NAME                                   DESIRED   CURRENT   READY   AGE
> replicaset.apps/traefik-6c4dc99559     1         1         1       3m57s
> replicaset.apps/whoami-67877457b8      2         2         2       3m47s
> replicaset.apps/whoamitcp-5484cb886c   2         2         2       3m47s
> replicaset.apps/whoamiudp-5b9d8b758d   2         2         2       3m47s
> ```
> 
> I like Traefik but it's been very difficult to get going due to the lack of solid and easy-to-run examples, along with little information on how to troubleshoot and understand things like, e.g., why the **whoami** services aren't being picked up by Traefik in the **IngressRoute** example.

I am facing the same issue:

https://stackoverflow.com/questions/62780325/traefik-v2-2-ingress-route-example-not-working

**Comment by notsureifkevin** [comment]
> v2.x is such a mess to be honest. The documentation is scattered.. I just want the IngressRoute's to work and basic documentation on how to get there :-(

Hi @kallisti5 , it sounds like you have some feedback on how we can improve the documentation and I wanted to drop a note to let you know we value that feedback and we value PRs too! Documentation is an area we want to continuously improve on, as an insider we don't always have the same perspective and experiences that our community does.  Feel free to reach out to me on our forums if you'd like some ideas on how to get started.

**Comment by Zincr0** [comment]
A guide from scratch using k3s will be very helpful (the traefik v1 that uses k3s by default is outdated and a downgrade has no sense for migrations that are already using v2). 
3 days here i have been trying to set up traefik v2, and not a single example worked. I'm starting to think that traefik v2 should have an incompatible warning with kubernetes on install...

**Comment by kallisti5** [comment]
> @kevtainer
> and we value PRs too

Traefik is a company now with paid support and enterprise offerings... Why would I work for free?

**Comment by ldez** [comment]
Why would we want to offer a product for free? You have some cash you can pay for the product ;-)

Traefik is an open-source project and Traefik Labs manage the project.

Every day, we sort issues, fix bugs, add new features, manage contributor's pull requests and issues. And we do it for free.

As we share something, you can also share something. It seems honest, and in the spirit of the open-source.

**Comment by cmcga1125** [comment]
Hey! i'm struggling with the whole redirectscheme as well - If someone could help me get a function CRD/Redirect scheme working - bot for ingress and ingressroute i'd be happy to write the docs and send over a PR.

**Comment by cmcga1125** [comment]
and for what its worth - the only way i've ever gotten this to work is by configuring the default routes to use the redirect scheme - but the CRD just never seems to take configuration. i blame yaml spacing :)

example dynamic_conf.yml that is loaded like this:
```
additionalArguments:
  - "--providers.file.filename=/config/dynamic_conf.yml"
```
configmap with this data:
```
http:
  routers:
    redirecttohttps:
      entrypoints:
        - "web"
      middlewares:
        - "httpsredirect"
      rule: "HostRegexp(`{host:.+}`)"
      service: "noop"
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
  middlewares:
    httpsredirect:
      redirectScheme:
        scheme: "https"
        permanent: true
```

**Comment by omarsumadi** [comment]
If we are improving the docs, it would be good to add some section for Cert Manager.

I had to go out of my way to configure cert manager because the Cluster Issuer conflicted with my Traefik routes due to Priority.
Had to fix it like tihs:
``` yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cluster-issuer-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ""
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cluster-cert-private-key
    # Enable HTTP01 validations
    preferredChain: "ISRG Root X1"
    solvers:
      - http01:
          ingress:
            class: traefik-default-cert-manager
            ingressTemplate:
              metadata:
                  annotations:
                    "traefik.ingress.kubernetes.io/router.priority": "1000"
```

**Comment by mstaicu** [comment]
I too have some issues concerning best practices on how to run Traefik in a local single ( and distributed ) node cluster. I would like to also mention that I've heavily invested hours of trial and errors and I can't say I am certain on my usage of Traefik

I've followed two documents which got me up and running on my local ( and GCP ) k8s setup. My local cluster is made up of solely the Docker for Mac client with Kubernetes enabled, plain and simple. The info and version:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 36
  Running: 36
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: ATX4:S5J3:AAKY:BO4Z:BJUI:WORF:4G26:PNOT:SSLT:YHKH:ZSF4:ELUW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 139
  Goroutines: 121
  System Time: 2021-04-12T10:45:36.498081964Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

And the versions:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The document that I followed to get Traefik working is the [CRD guide](https://doc.traefik.io/traefik/user-guides/crd-acme). I've omitted everything https related, no Let'sEncrypt, no SSL / TLS, no k3s. I've got, from that guide, just the following object definitions: **CustomResourceDefinition**, **ClusterRole**, **ClusterRoleBinding**,  **Service**,  **ServiceAccount**, **Deployment**, **IngressRoute**. I did not get an install all the objects specified [here](https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/), but since Traefik works without them, _do I need to_?

And here are my files:

> ingress-setup.yaml

```
#
# Provides Traefik an identity for processes that run in a Pod
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
#
# Grant some permissions to Traefik to access Pods, Endpoints, and Services running in your cluster
#
# Create a 'ClusterRole' with a set of permissions which will be applied to the Traefik 'ServiceAccount'
# The 'ClusterRole' will allow Traefik to manage and watch such resources as Services, Endpoints, Secrets, and Ingresses across all namespaces in your cluster
#
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
    verbs:
      - get
      - list
      - watch
---
#
# Bind the 'ClusterRole' to the Traefik 'ServiceAccount'
# This can be done using the 'ClusterRoleBinding'
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default
---
#
# 'CustomResourceDefinition' that need to be registered (created) before you can create 'IngressRoutes' and 'Middlewares'
#
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressrouteudps.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteUDP
    plural: ingressrouteudps
    singular: ingressrouteudp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsstores.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSStore
    plural: tlsstores
    singular: tlsstore
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverstransports.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: ServersTransport
    plural: serverstransports
    singular: serverstransport
  scope: Namespaced
```

> ingress-depl.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4
          args:
            - --entrypoints.http.address=:80
            - --providers.kubernetescrd
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-srv
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: client-ingress-route
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`something`)
      kind: Rule
      services:
        - name: client-srv
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-ingress-route
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`something`) && PathPrefix(`/api/auth`)
      kind: Rule
      middlewares:
        - name: strip-auth-prefix
      services:
        - name: auth-srv
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-auth-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/auth
```

The order in which these files are applied against a cluster matters. I always apply the **ingress-setup.yaml** followed by the **ingress-depl.yaml**.

So, up until this point, everything works. I have no idea if:

1. This is the intended way of deploying Traefik in a local cluster
2. This is more of a Kubernetes specific question but, can you have both a **LoadBalancer** and a **ClusterIP** service pointing at the same deployment pod?

And now for my final question, because this is what's not working for me.

Since all the resources are created in the **default** namespace, and Traefik routes traffic according to the **IngressRoute** definitions, **why can't I reach Traefik from a pod in the cluster**? If I try to perform an HTTP request from a pod, let's say `client` to the `auth-srv` ClusterIP service, the request succeeds, but if I try to perform an HTTP request from any pod to Traefik, be it via the LoadBalancer or its ClusterIP service, I always get a 404

Can you please help me out with this one? I'm pretty sure it's a misconfiguration
