### ISSUE TITLE
wildcard domain with exclusions

### ISSUE THREAD

**Issue by opichon** [containous/traefik#633]
I need to redirect all wildcard domains to 1 backend, but excluding the subdomains 'www' and 'admin', which must be redirected to another backend.

How do I do this?

using priorities doesn't work.

```yml
www:
    labels:
        - "traefik.backend=backend1"
        - "traefik.frontend.rule=Host:www.mydomain.dev"
        - "traefik.frontend.priority=1"

admin:
        labels:
            - "traefik.backend=backend2"
            - "traefik.frontend.rule=Host:admin.mydomain.dev"
            - "traefik.frontend.priority=2"

app:
    labels:
        - "traefik.backend=backend3"
        - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z0-9]+}mydomain.local"
        - "traefik.frontend.priority=10"
```

**Comment by opichon** [comment]
priorities: a higher value means a higher priority.

```yml
www:
    labels:
        - "traefik.backend=backend1"
        - "traefik.frontend.rule=Host:www.mydomain.dev"
        - "traefik.frontend.priority=3"

admin:
        labels:
            - "traefik.backend=backend2"
            - "traefik.frontend.rule=Host:admin.mydomain.dev"
            - "traefik.frontend.priority=2"

app:
    labels:
        - "traefik.backend=backend3"
        - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z0-9]+}mydomain.local"
        - "traefik.frontend.priority=1"
```
