### ISSUE TITLE
simple c o n f i g example

### ISSUE THREAD

**Issue by basickarl** [containous/traefik#6335]
Using traefik 2.1.4.

I would like a simplistic example of a reverse proxy, the issue is that I keep getting a 404 page, I'm trying to access http://10.23.241.10:661 and want traefik to direct me to my service at http://10.23.241.10:3000: 

```
entryPoints:
  hole-1:
    address: :661

http:
  routers:
    hole-router-1:
      entryPoints:
        - hole-1
      service: hole-service

services:
  hole-service:
    loadBalancer:
      servers:
        - url: http://10.23.241.10:3000
```

What am I doing wrong.
