### ISSUE TITLE
Traefik redirecting to wrong host when empty host

### ISSUE THREAD

**Issue by kmeekva** [containous/traefik#6336]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Bing bot hit URL that requires client certificate with no SNI hostname.

### What did you expect to see?
Traefik should NOT pass request to remote service container.

### What did you see instead?
Logs in our remote container show request was passed from traefik for this request.

`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.2
Codename:     cantal
Go version:   go1.13.5
Built:        2020-01-07T18:23:57Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>
<summary>cat traefik.yml</summary>

```yml
global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  http:
    address: :80
  https:
    address: :443
  traefik:
    address: :8080
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    swarmMode: false
  file:
    directory: /etc/traefik/config
    watch: true

api:
  insecure: true
  dashboard: true
log:
  level: DEBUG
```

</details>

<details>
<summary>cat middlewares.yml</summary>

```yml
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    security-headers:
      headers:
        sslRedirect: true
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: same-origin
        featurePolicy: vibrate 'self'
        accessControlAllowOrigin: origin-list-or-null
        accessControlMaxAge: 100
        BrowserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
```

</details>

<details>
<summary>cat tls.yml</summary>

```yml
tls:
  options:
    tcgdefault:
      minVersion: VersionTLS12
      maxVersion: VersionTLS12
      clientAuth:
        caFiles:
          - /etc/traefik/config/ca-bundle.crt
        clientAuthType: RequireAndVerifyClientCert
    fastdefault:
      minVersion: VersionTLS12
      maxVersion: VersionTLS12
      clientAuth:
        caFiles:
          - /etc/traefik/config/fast-ca-bundle.crt
        clientAuthType: RequireAndVerifyClientCert
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/config/columbiagroup.com.crt
        keyFile: /etc/traefik/config/columbiagroup.com.key
```

</details>

<details>
<summary>Docker labels:</summary>

```yml
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.router_${INSTANCE}.rule=Host(`${HOST}`) && PathPrefix(`/${INSTANCE}`)"
      - "traefik.http.middlewares.${INSTANCE}-stripprefix.stripprefix.prefixes=/${INSTANCE}"
      - "traefik.http.routers.router_${INSTANCE}.entrypoints=https"
      - "traefik.http.routers.router_${INSTANCE}.tls=true"
      - "traefik.http.routers.router_${INSTANCE}.tls.options=tcgdefault@file"
      - "traefik.http.routers.router_${INSTANCE}.middlewares=${INSTANCE}-stripprefix,${INSTANCE}-passtlsclientcert"

      - "traefik.http.routers.router_${INSTANCE}_dns.rule=Host(`${INSTANCE}.columbiagroup.com`)"
      - "traefik.http.routers.router_${INSTANCE}_dns.entrypoints=https"
      - "traefik.http.routers.router_${INSTANCE}_dns.tls=true"
      - "traefik.http.routers.router_${INSTANCE}_dns.tls.options=tcgdefault@file"
      - "traefik.http.routers.router_${INSTANCE}_dns.middlewares=${INSTANCE}-passtlsclientcert"

      - "traefik.http.routers.redirect_router_${INSTANCE}.rule=Host(`${HOST}`) && PathPrefix(`/${INSTANCE}`)"
      - "traefik.http.routers.redirect_router_${INSTANCE}.entrypoints=http"
      - "traefik.http.routers.redirect_router_${INSTANCE}.middlewares=https-redirect@file"

      - "traefik.http.routers.redirect_router_${INSTANCE}_dns.rule=Host(`${INSTANCE}.columbiagroup.com`)"
      - "traefik.http.routers.redirect_router_${INSTANCE}_dns.entrypoints=http"
      - "traefik.http.routers.redirect_router_${INSTANCE}_dns.middlewares=https-redirect@file"

      - "traefik.http.middlewares.${INSTANCE}-passtlsclientcert.passtlsclientcert.pem=true"
      - "traefik.http.middlewares.${INSTANCE}-passtlsclientcert.passtlsclientcert.info.subject.commonName=true"
      - "traefik.http.middlewares.${INSTANCE}-passtlsclientcert.passtlsclientcert.info=true"
```

</details>

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-02-13T19:38:30Z" level=debug msg="Serving default certificate for request: \"\""
time="2020-02-13T19:38:31Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=tasker-passtlsclientcert@docker middlewareType=PassClientTLSCert
time="2020-02-13T19:38:31Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=tasker-passtlsclientcert@docker middlewareType=PassClientTLSCert
time="2020-02-13T19:38:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/robots.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"Keep-Alive\"],\"Pragma\":[\"no-cache\"],\"User-Agent\":[\"Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)\"],\"X-Forwarded-Host\":[\"XXX.columbiagroup.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"4276668a6949\"],\"X-Real-Ip\":[\"157.55.39.43\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"XXX.columbiagroup.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"157.55.39.43:11042\",\"RequestURI\":\"/robots.txt\",\"TLS\":null}"
```
