### ISSUE TITLE
Service IP problems when multiple docker networks

### ISSUE THREAD

**Issue by Chuckame** [containous/traefik#6339]
Same as #5657 but closed due to age...

### Do you want to request a *feature* or report a *bug*?

Bug or maybe feature request (automatic network selection).

### What did you do?

I'm working with local Docker provider. 
I have multiple networks, named :
- `traefik-network` with ip `1.1.1.0/8`: the network where traefik doing his job
- `other-network` with ip `2.2.2.0/8`: the other network where traefik is not inside, so where traefik cannot forward requests

I currently added a service named `myservice` on `traefik-network` and `other-network`, and traefik on `traefik-network`. 

### What did you expect to see?
The ip getted for `myservice` should be from the same network than traefik, here `traefik-network` (like `1.1.1.12`).

### What did you see instead?
The ip getted for `myservice` is from the `other-network` (like `2.2.2.12`) so traefik cannot forward to this service and I'm seeing `gateway timeout` from internet browser. 

### Output of `traefik version`: (_What version of Traefik are you using?_)
`2.1.4`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker compose for this bug :
```yaml
version: '3.7'

services:
  proxy:
    image: traefik:v2.1.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--log.level=DEBUG"

      - "--api.dashboard=true"
      
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"

      - "--entrypoints.http.address=:80"
    networks:
      - traefik-network

  myservice:
    image: nginx
    container_name: myservice
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myservice.rule=Host(`mydomain.fr`)'
      - 'traefik.http.services.myservice.loadbalancer.server.port=80'
      - 'traefik.http.routers.myservice.entrypoints=http'
    networks:
      - traefik-network
      - other-network

networks:
  traefik-network:
  other-network:

```
