### ISSUE TITLE
Traefik v1.7 gets out of sync in Kubernetes, some services being not served

### ISSUE THREAD

**Issue by rkojedzinszky** [containous/traefik#6342]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Traefik v1.7 is deployed with 2 replicas in Kubernetes v1.17 cluster.

### What did you expect to see?
I expect the 2 pods behave identically.

### What did you see instead?
The two pods behave differently. While one was directing traffic to a live service fine, the other returned 'Service unavailable'.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v1.7.20
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik-ingress-controller
  namespace: ingress-traefik
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - traefik-ingress-lb
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --api
        - --kubernetes
        - --entrypoints=Name:http Address::8000
        - --entrypoints=Name:https Address::8443 TLS
        - --forwardingtimeouts.dialtimeout=5s
        - --kubernetes.namespaces=xxx,yyy,zzz
        - --loglevel=DEBUG
        env:
        - name: GOGC
          value: "50"
        image: traefik:v1.7.20
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        ingress-controller: traefik
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 8888
        runAsUser: 8888
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60
```

Kubernetes is running on bare-metal, OrangePI, BananaPI, and Rock64 boards. OS is Debian Buster.

I've just enabled DEBUG level, so no relevant messages are available yet. After idenitfying the `stucked` pod, I can delete it, and the newly created one behaves as expected.
