### ISSUE TITLE
gRPC SSL Routing with IngressRoute definition

### ISSUE THREAD

**Issue by bayucandra** [containous/traefik#6344]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I am trying to setup gRPC routing with SSL. I am using "KubernetesCRD" as the provider and the routing using "IngressRoute". To achieve that, I am trying to convert the configuration on the official documentation at this URL: https://docs.traefik.io/user-guides/grpc/#with-https to "IngressRoute" way.

In Kubernetes, Traefik "IngressRoute" resolve a service as an IP address. So we will have problem with SSL CA certificate, because we have to follow the IP address of the service instead service name as the CN ( Common name )

Actually, in the Traefik issues repository, I found a person who has tried to do a similar thing, but he was using V1.x.x Traefik and "Kubernetes Ingress" instead of "IngressRoute". Here is the URL: https://github.com/containous/traefik/issues/2141 . I have tried to do a similar approach based on the discussion there, by using "ExternalName" as the service type, but it doesn't work in Traefik V.2.1.4

### What did you expect to see?
I expect there is a way to configure gRPC in backend SSL certificate by using "IngressRoute" instead of Traefik "dynamic configuration".

As mentioned above, I am trying to do "ExternalName" approach on the Kubernetes service definition. And hopefully, it solves my problem with "Backend CA certificate" which should have a reliable CN (Common Name). 

Exposing gRPC gateway with SSL is very important nowadays in my opinion. And have it well implemented with Kubernetes as one of the most used platforms, I believe is pretty essential too. Using Kubernetes ways is pretty handy for people who used to it compared to dynamic configuration ways. Hopefully, there is a better way than this "ExternalName" approach.

### What did you see instead?
- When trying to do "ExternalName" approach with "IngressRoute", Traefik can't have "https scheme" resolved at the traefik router, for services that have port other than 443. My gRPC service is running on port 5000 ( please check logs included at the end of this post )
- If I set the service `port` to 443 then `targetPort` still at 5000, the "https schemes" does works, but SSL mechanism still does not work, I saw 502 response at Traefik log.

But if I have "IngressRoute" definition to a service which the type is "ClusterIp" ( not using "ExternalName" ), any ports will still run with "https" scheme in Traefik routes with it IP address. For example resolved as https://10.31.0.10:5000. 

Currently, the only way to make it works is only by having "ClusterIP" type of service, which exposing IP address to Traefik routing, then we make IP address of the service as CN (Common name) which is not reliable ( could dynamically change in Kubernetes) , instead of "service name" which is more reliable without depending on IP address. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.4
Codename:     cantal
Go version:   go1.13.7
Built:        2020-02-06T17:10:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

**Service definition:**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: android-service
spec:
  ports:
  #If I change this line below to 443, the ExternalName resolve https scheme correctly. But the SSL mechanism also still not works
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    service-name: android-service
  type: ClusterIP
```

**Service with "ExternalName":**
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: android-service-external
spec:
  externalName: android-service
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: ExternalName
```

**The IngressRoute Definition:**
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: android-service
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grpc-endpoint.domain.com`)
      kind: Rule
      services:
        - name: android-service-external
          #This port will causing the fallback to "http" scheme instead of "https"
          port: 5000
          scheme: https
  tls:
    secretName: tls-grpc-android-frontend
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Please note, following logs are produced by gRPC request Reflection query.

**When setting "https" scheme with port 5000 ( fall back to "http" instead ):**
```
114.xxx.xxx.xxx - - [20/Feb/2020:10:28:11 +0000] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0" 502 11 "-" "-" 20653 "mai-android-service-4d344413596dc218d249@kubernetescrd" "http://android-service:5000" 265ms
```

**The same When setting the "https" scheme with port 443 and targetPort to 5000 ( "https" scheme works but SSL still not works ):**
```
114.xxx.xxx.xxx - - [20/Feb/2020:10:37:16 +0000] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0" 502 11 "-" "-" 20908 "mai-android-service-4d344413596dc218d249@kubernetescrd" "https://android-service:443" 198ms
```
