### ISSUE TITLE
Linkerd tap wss:// not working with traefik v2.1.4

### ISSUE THREAD

**Issue by ryanoolala** [containous/traefik#6350]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Tried to use linkerd dashboard with traefik v2
As linkerd uses wss:// for `linkerd tap` i'm not able to get websocket working with traefik v2. I understand that v2 is pretty new, so i'm unable to find much documentation on setting up websockets. Hope to get some help here.

### What did you expect to see?

linkerd tap to work without errors in browser console.

### What did you see instead?
`WebSocket connection to 'wss://example.com/api/tap' failed: Error during WebSocket handshake: Unexpected response code: 400`

### Output of `traefik version`:  (_What version of Traefik are you using?_)

```
2.1.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Running on EKS 1.14

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: linkerd
  namespace: linkerd
  annotations:
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:linkerd-web.linkerd.svc.cluster.local:8084
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`linkerd.example.com`)
      middlewares:
        - name: x-forwarded-proto-allow
          namespace: traefik
      kind: Rule
      services:
        - name: linkerd-web
          port: 8084
      tls: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: x-forwarded-proto-allow
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    linkerd.io/control-plane-component: web
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-web
  namespace: linkerd
spec:
  ports:
  - name: http
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: admin-http
    port: 9994
    protocol: TCP
    targetPort: 9994
  selector:
    linkerd.io/control-plane-component: web
```

aws-clb.yaml
```yaml 
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {REDACTED}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    app: traefik
  name: traefik-internal
  namespace: traefik
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 4443
    protocol: TCP
    name: https
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: traefik
---
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
