### ISSUE TITLE
[Cloudflare] Usage of CLOUDFLARE_DNS_API_TOKEN not respected.

### ISSUE THREAD

**Issue by Dextroz** [containous/traefik#6353]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Using the 1.7-alpine image. I am trying to generate certs using Cloudflare. The documentation says one can specify `CLOUDFLARE_DNS_API_TOKEN` or it's aliase `CF_DNS_API_TOKEN` alone. However, when looking at the traefik logs, it fails saying I need to provide the `CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY` vars instead?

I am attempting to use the [second example](https://go-acme.github.io/lego/dns/cloudflare/) located here.

I am passing the environment variable to traefik using ansible.
```yaml
docker_container:
    [...]
    env:
      CLOUDFLARE_DNS_API_TOKEN: "{{ dns_api_token }}"
```

### What did you expect to see?
No missing credentials and traefik uses the `CLOUDFLARE_DNS_API_TOKEN` environment variable.

### What did you see instead?
Traefik expects `CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY` instead.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.21
Codename:     maroilles
Go version:   go1.12.17
Built:        2020-02-20_05:40:23PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Provider: cloudflare.
Relevent toml config below.
```toml
[acme]
email = "{{ ssl_cert_email }}"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
  [acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0
  [[acme.domains]]
    main = "*.somedomain.com"
    sans = ["somedomain.com"]
```
