### ISSUE TITLE
Feature Request - Support inline middleware definitions in IngressRoute

### ISSUE THREAD

**Issue by cameronbraid** [containous/traefik#6356]
I often find myself writing middlewares that are single use.

Currenlty I need to generate a globally unique name for the middleware then reference it by name in the IngressRoute

I would like to be able to define the middleware spec inline in the IngressRoute

example

```
  - kind: Rule
    match: Host(`foo.example.com`)
    middlewares:
    - spec:
          redirectRegex:
              regex: ^https?://foo.example.com/(.*)
              replacement: https://bar.example.com/${1}
```
