### ISSUE TITLE
Traefik 2.1 Gateway Timeout on all routes

### ISSUE THREAD

**Issue by mahnunchik** [containous/traefik#6361]
### Do you want to request a *feature* or report a *bug*?

Traefik 2.1 Gateway Timeout on all routes.

### What did you do?

traefik.yml
```yml
version: '2.4'

services:
  traefik:
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    image: traefik:2.1
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
```

Service docker-compose.yml

```yml
version: '2.4'

services:
  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-api.rule=Host(`my.api.local`)"
```

### What did you expect to see?

My API on `my.api.local`

### What did you see instead?

504 Gateway Timeout

### Output of `traefik version`: traefik:2.1

```
Version:      2.1.4
Codename:     cantal
Go version:   go1.13.7
Built:        2020-02-06T17:10:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Described above.
