### ISSUE TITLE
Unsupported TLS versions are rejected in a non-standard way

### ISSUE THREAD

**Issue by CHTJonas** [containous/traefik#6392]
### Do you want to request a *feature* or report a *bug*?

Bug (kind of)

### What did you do?

1. Configure Traefik to reject HTTPS connections with TLS < v1.2
2. Test site served by Traefik with Qualys SSL Labs tool
3. Report is capped at grade 'B' and complains that server supports TLSv1.0 and v1.1
4. Discover that Traefik does in fact reject requests, but in a seemingly non-standard way

### What did you expect to see?

Traefik should reject the connection early on and reply with TLS alert code 70 (protocol_version) as defined by [RFC 5246](https://tools.ietf.org/html/rfc5246#page-32). See [here](https://docs.microsoft.com/en-us/archive/blogs/kaushal/ssltls-alert-protocol-the-alert-codes) for a more legible list.

Compared to an Apache web server:
```
chtjonas@server:~$ curl -v --tlsv1.1 https://my.apache.server.net/
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to my.apache.server.net (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS alert, Server hello (2):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
```

### What did you see instead?

Traefik does something weird and non-standard.

```
chtjonas@server:~$ curl -v --tlsv1.1 https://my.traefik.server.net/
*   Trying 5.6.7.8...
* TCP_NODELAY set
* Connected to my.traefik.server.net (5.6.7.8) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS handshake, Server hello (2):
* TLSv1.1 (IN), TLS handshake, Certificate (11):
* TLSv1.1 (IN), TLS handshake, Server key exchange (12):
* TLSv1.1 (IN), TLS handshake, Server finished (14):
* TLSv1.1 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.1 (OUT), TLS change cipher, Client hello (1):
* TLSv1.1 (OUT), TLS handshake, Finished (20):
* TLSv1.1 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.1 / ECDHE-RSA-AES256-SHA
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=my.traefik.server.net
*  start date: Feb  5 14:34:31 2020 GMT
*  expire date: May  5 14:34:31 2020 GMT
*  subjectAltName: host "my.traefik.server.net" matched cert's "my.traefik.server.net"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x556928371580)
* SSL_write() returned SYSCALL, errno = 32
* Failed sending HTTP2 data
* Failed sending HTTP request
* Connection #0 to host my.traefik.server.net left intact
curl: (55) SSL_write() returned SYSCALL, errno = 32
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.4
Codename:     cantal
Go version:   go1.13.7
Built:        2020-02-06T17:10:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
N/A
```

**Comment by juliens** [comment]
Thx for your report!

I was unable to reproduce your problem.
```
$ curl -v --tls-max 1.1 --tlsv1.1 https://172.17.0.6:8000/ -k
*   Trying 172.17.0.6:8000...
* TCP_NODELAY set
* Connected to 172.17.0.6 (172.17.0.6) port 8000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS alert, protocol version (582):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
```

Could you provide us a more complete reproducible case (with the static conf and the dynamic conf you use)?

**Comment by CHTJonas** [comment]
Thanks for taking the time to look into this! Here's a more detailed look at my config files:

### traefik.toml

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "ERROR"

[serversTransport]
  insecureSkipVerify = true

[providers]
  [providers.file]
    filename = "conf.toml"
  [providers.docker]
    exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

[certificatesResolvers.mydomain.acme]
  email = "admin@my-domain.net"
  storage = "acme.json"
  [certificatesResolvers.mydomain.acme.tlschallenge]
```

### conf.toml

```toml
[http.middlewares]
  [http.middlewares.redirect-insecure.redirectScheme]
    scheme = "https"
    permanent = true
  [http.middlewares.secure-login.basicAuth]
    removeHeader = true
    users = ["admin:imnottellingyoumypassword"]
```

I tried using log level `DEBUG` but it seems that the blocked requests don't show up there. I've also further discovered that this issue goes deeper:

### HTTP2 fails as described above:

```
$ curl -v --tls-max 1.0 --tlsv1.0 https://my.domain.net/
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to my.domain.net (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server key exchange (12):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / ECDHE-RSA-AES256-SHA
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=my.domain.net
*  start date: Feb  5 14:34:31 2020 GMT
*  expire date: May  5 14:34:31 2020 GMT
*  subjectAltName: host "my.domain.net" matched cert's "my.domain.net"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffd3bb1990)
> GET / HTTP/2
> Host: my.domain.net
> User-Agent: curl/7.58.0
> Accept: */*
>
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
* Connection #0 to host my.domain.net left intact
curl: (16) Error in the HTTP2 framing layer
```

### HTTP1 succeeds

```
$ curl -v --http1.1 --tls-max 1.0 --tlsv1.0 https://my.domain.net/
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to my.domain.net (1.2.3.4) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server key exchange (12):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / ECDHE-RSA-AES256-SHA
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=my.domain.net
*  start date: Feb  5 14:34:31 2020 GMT
*  expire date: May  5 14:34:31 2020 GMT
*  subjectAltName: host "my.domain.net" matched cert's "my.domain.net"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: my.domain.net
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Fri, 28 Feb 2020 12:06:26 GMT
< Location: /manage
<
* Connection #0 to host my.domain.net left intact
```

I'd say this could be a low-level security issue since an administrator may have configured a minimum TLS version for good reason, but it appears an attacker could persuade Traefik to ignore this.

**Comment by ndobbs** [comment]
I fought with TLS configuration with version `2.1.4` for awhile yesterday - I ended up with the following tls configuration. I'm still not completely sure if the initial `[tls`]` invocation is needed, but this is the config that is working by rejecting TLS versions less than 1.2 and presenting all 'A' cipher suites. Depending on your use case - you may need to add additional cipher suites.  

```
[tls]
  [tls.options]
    [tls.options.default]
       minVersion = "VersionTLS12"
       sniStrict = true
       cipherSuites = [
         "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
         "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
         "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
       ]
```

```
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to mydomain.com (1.2.3.4) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS alert, protocol version (582):
* error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
```

**Comment by CHTJonas** [comment]
No joy using that exact same TLS config @ndobbs. This is what nmap gives me:

```
Starting Nmap 7.60 ( https://nmap.org ) at 2020-02-28 13:29 UTC
Nmap scan report for my-domain.net (1.2.3.4)
Host is up (0.0013s latency).
Other addresses for my-domain.net (not scanned): 2001:41d0:801:2000::780
rDNS record for 1.2.3.4: some.server.net
PORT    STATE SERVICE  VERSION
443/tcp open  ssl/http Golang net/http server (Go-IPFS json-rpc or InfluxDB API)
| ssl-enum-ciphers:
|   TLSv1.0:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (rsa 4096) - C
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 4096) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 4096) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 4096) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 4096) - A
|     compressors:
|       NULL
|     cipher preference: client
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.1:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (rsa 4096) - C
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 4096) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 4096) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 4096) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 4096) - A
|     compressors:
|       NULL
|     cipher preference: client
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (rsa 4096) - C
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 4096) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (rsa 4096) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 4096) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 4096) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 4096) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 4096) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 4096) - A
|     compressors:
|       NULL
|     cipher preference: client
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: C
```

**Comment by juliens** [comment]
@CHTJonas 
The "tls.options" configuration needs to be in the dynamic configuration, not in the static configuration.

So you need a "traefik.toml" file
```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "ERROR"

[serversTransport]
  insecureSkipVerify = true

[providers]
  [providers.file]
    filename = "conf.toml"
  [providers.docker]
    exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers.mydomain.acme]
  email = "admin@my-domain.net"
  storage = "acme.json"
  [certificatesResolvers.mydomain.acme.tlschallenge]

[providers.file]
filename="./dynamic.toml
```

and a "dynamic.toml" file:

```toml
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
```
