### ISSUE TITLE
compress doesn't work on v2.1

### ISSUE THREAD

**Issue by zong400** [containous/traefik#6435]
bug

Bug

I want compress response data with gzip .

### What did you expect to see?

DownstreamContentSize compress .

### What did you see instead?

DownstreamContentSize doesn't compress .

![image](https://user-images.githubusercontent.com/10556584/76062549-e2b39180-5fc0-11ea-880e-a5a73f1a27a1.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.1.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
      containers:
      - image: ccr.ccs.tencentyun.com/bxrapp/traefik:v2.1.4
        name: traefik
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
        - name: websecure
          containerPort: 8443
          hostPort: 8443
        args:
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:8443
        - --api=true
        - --api.dashboard=true
        - --ping=true
        - --providers.kubernetesingress
        - --providers.kubernetescrd
        - --serversTransport.insecureSkipVerify=true
        - --log.level=INFO
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.bufferingsize=100
        - --accesslog.filepath=/accesslog/access.log
```

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gzip-compress
spec:
  compress: {}
```

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-static
  namespace: bxr-qq
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`bxrqq.banxe.cn`)
    services:
    - name: web-static
      port: 8080
    middlewares:
    - name: gzip-compress
```

![image](https://user-images.githubusercontent.com/10556584/76063069-ebf12e00-5fc1-11ea-8cff-a724c336f5cf.png)

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
