### ISSUE TITLE
Redirections `to` value should be optional

### ISSUE THREAD

**Issue by chris13524** [containous/traefik#6448]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Just like the [RedirectScheme](https://docs.traefik.io/v2.2/middlewares/redirectscheme/#scheme) middleware, you should be able to redirect by scheme and not have to specify the entrypoint.

In my situation, my entrypoint is listening on port 7443. This is exposed to the Internet via a NAT which forwards port 443 to my 7443 port. When I attempt to use the new [redirections](https://docs.traefik.io/v2.2/routing/entrypoints/#redirection) feature, I get redirected to port 7443 rather than the typical 443.

Alternatively, allow us to provide a `port` option to specify the target port just like `RedirectScheme` supports.

**Comment by ldez** [comment]
Hello,

The redirection is a shortcut to manage common cases.

You seems to have a edge case, so we recommend to use the global redirection pattern instead:

```yml
services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:7443
      - --providers.docker=true
    ports:
      - 80:80
      - 443:443
    labels:
      traefik.http.routers.http_catchall.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.http_catchall.entrypoints: web
      traefik.http.routers.http_catchall.middlewares: https_redirect
      
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https_redirect.redirectscheme.port: 443
      traefik.http.middlewares.https_redirect.redirectscheme.permanent: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

An entry point is just a port, it's protocol neutral, so you can also define an entry point on 443.

It's not possible to redirect a port by a scheme because a scheme can be used on any port, there is relation between port and scheme.

**Comment by chris13524** [comment]
While I understand the separation of concerns between entry points and HTTP routers, in this case you are already providing HTTP-specific options (the redirections feature) under this supposed "protocol neutral" entry point.

Furthermore, `redirections` just [creates a `RedirectScheme` internally](https://github.com/containous/traefik/blob/a6040c623bdb80cd53a28b5f9545c6a435f460d3/pkg/provider/traefik/internal.go#L99). Exposing these options to the developer makes sense IMO.

**Comment by ldez** [comment]
I give you an example by using a non exposed 443 port:

```yml
services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=noop
      - --entrypoints.websecure.address=:7443
      - --entrypoints.noop.address=:7443
      - --providers.docker=true
    ports:
      - 80:80
      - 7443:7443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
