### ISSUE TITLE
Feature Request: Support No-IP as DNS Provider (+ Manual DNS Provider Bug)

### ISSUE THREAD

**Issue by JettScythe** [containous/traefik#6454]
### Do you want to request a *feature* or report a *bug*?
Both. As far as feature requests go: I would like to request support for no-ip as a DNS provider

Bug

### What did you do?
Running Traefik as docker container with command 
`docker container start -i traefik` 

### What did you expect to see?
"instructions" as expressed here when manually entering a providers name: https://docs.traefik.io/v1.7/configuration/acme/#provider

### What did you see instead?

```time="2020-03-08T01:28:44Z" level=error msg="Unable to obtain ACME certificate for domains \"redacted\" : cannot get ACME client ACME challenge not specified, please select TLS or HTTP or DNS Challenge"```

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7 as documented https://jellyfin.org/docs/general/networking/traefik.html

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "WARN"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
    ]

[retry]

[api]

[acme]
acmeLogging = true
email = "redacted"
storage = "acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
    provider = ""
    delayBeforeCheck = "60"

[[acme.domains]]
  main = "redacted"

[docker]
domain = "redacted"
network = "traefik"
exposedbydefault = false

[file]
[backends]
  [backends.backend-jellyfin]
    [backends.backend-jellyfin.servers]
      [backends.backend-jellyfin.servers.server-1]
        url = "redacted"
[frontends]
  [frontends.jellyfin]
    backend = "backend-jellyfin"
    passHostHeader = true
    [frontends.jellyfin.routes]
      [frontends.jellyfin.routes.route-jellyfin-ext]
        rule = "Host:redacted"
    [frontends.jellyfin.headers]
      SSLRedirect = true
      SSLHost = "redacted"
      SSLForceHost = true
      STSSeconds = 315360000
      STSIncludeSubdomains = true
      STSPreload = true
      forceSTSHeader = true
      frameDeny = true
      contentTypeNosniff = true
      browserXSSFilter = true
      customResponseHeaders = "X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      customFrameOptionsValue = "allow-from https://example.com"
```

on OpenSUSE if it makes any difference.
