### ISSUE TITLE
kubernetesingress inline middleware via annotation(s)

### ISSUE THREAD

**Issue by travisghansen** [containous/traefik#6455]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I've just finished messing around with the upcoming `annotations` (I'm happy to help with the docs for that by the way as several things were pretty unclear) support in `v2.2` (#6074 #6160). While it's a step in the right direction it's quite cumbersome to be required to create additional resources outside the `Ingress` alone.

I propose creating an annotation that allows for defining the middleware inline in the `Ingress` object:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    ...
    traefik.ingress.kubernetes.io/router.middlewares-inline: |
      - redirectScheme:
          scheme: https
      - ipWhiteList:
          sourceRange:
          - 192.168.1.7
          - 127.0.0.1/32
      - basicAuth:
          users:
          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
  ...
```

Given that the `traefik.ingress.kubernetes.io/router.middlewares` annotation exists and that ordering is important it may be necessary to add keys to the `-inline` block to indicate `pre`/`post` the middlewares defined in the existing annotation. Something like:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traefik-v2-httpbin
  annotations:
    ...
    traefik.ingress.kubernetes.io/router.middlewares: auth@file,prefix@kuberntes-crd,cb@file
    traefik.ingress.kubernetes.io/router.middlewares-inline: |
      pre:
      - redirectScheme:
          scheme: https
      - ipWhiteList:
          sourceRange:
          - 192.168.1.7
          - 127.0.0.1/32
      post:
      - basicAuth:
          users:
          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
  ...
```
Where `pre` happens **before** all the middlewares defined in `traefik.ingress.kubernetes.io/router.middlewares` and `post` happens **after** all the middlewares defined in `traefik.ingress.kubernetes.io/router.middlewares`.

There may be other items/keys that would generally benefit from the same pattern (looking at you `tlsoptions` and maybe others).

Thanks for the consideration.
