### ISSUE TITLE
Does traefik v2 support tls option global ?

### ISSUE THREAD

**Issue by weijing24** [containous/traefik#6458]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I use traefik v2 in docker swarm. And It's very convenient turning on tls options global  in traefik v1 with this command `--entryPoints=TLS.MinVersion:VersionTLS12 TLS.CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`. But in traefik v2, I have to define `tls options` in each service label. It's very complicated. 
eg:
docker-compose.yml
```
  version: "3.4"                                                                                                    
  services:
    pgweb:                                                                                                          
      image: sosedoff/pgweb
      deploy:
        labels:
          - traefik.enable=true
          - traefik.http.routers.pgweb.rule=Host(`pgweb.test.com`)
          - traefik.http.services.pgweb.loadbalancer.server.port=8081
          - traefik.http.routers.pgweb.tls=true
          - "traefik.http.routers.pgweb.tls.options=disabletls@file"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      deploy:
        labels:
          - traefik.enable=true
          - traefik.http.routers.phpmyadmin.rule=Host(`myadmin.test.com)
          - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
          - traefik.http.routers.phpmyadmin.tls=true
          - "traefik.http.routers.phpmyadmin.tls.options=disabletls@file"
```
It means that, if I have 100 sites, I have to add 100 `traefik.http.routers.xxx.tls.options=disabletls@file` in my compose file. I have searched community and issues, but there is no solution. Is there any way to workaround this? I just want to set one label and can be used in all services.
