### ISSUE TITLE
Static redirect not working

### ISSUE THREAD

**Issue by mnul** [containous/traefik#6479]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

setup of traefik inside docker on a raspberryPi unsing docker-compose.
Setup a router to route an incoming subdomain-request to a service that uses the loadBalancer to point to a different IP(:Port) 

### What did you expect to see?
forwarding and showing the respecting web-interface of that certain IP

### What did you see instead?
404-error. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.6
Codename:     cantal
Go version:   go1.13.8
Built:        2020-02-28T17:47:20Z
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
traefik.yaml
```yaml
#Traefik.yaml
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik" # Custom docker network
    exposedByDefault: false # Only expose explicitly enabled containers
  file:
    directory: "/etc/traefik/"
    watch: true

entryPoints:
  unsecure:
    address: ":80"
  secure:
    address: ":443"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

```
my file in the traefik folder

```yaml
# staticservers.yaml
http:
  services:
    nas-web:
      loadBalancer:
        servers:
        - url: "https://10.1.0.10:91/"
    hassio:
      loadBalancer:
        servers:
        - url: "https://10.10.0.2:8123/"
    nextcloud:
      loadBalancer:
        servers:
        - url: "https://10.1.0.10/"

#####################################################

  routers:
    nas-web:
      rule: "Host(`nas.dockerpi.local`)"
      service: "nas-web"
      entryPoints:
        - "secure"
    hassio:
      rule: "Host(`ha.dockerpi.local`)"
      service: "hassio"
      entryPoints:
      - "secure"
    nextcloud:
      rule: "Host(`nc.dockerpi.local`)"
      service: "nextcloud"
      entryPoints:
      - "secure"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
none
```
### additional info
I can ping and curl all the domains and IPs from within the træfik-container without problems and errors (ignoring the wrong certificates with "-k")

I have tried to recreate this on an empty setup trying to route google.de. Result stays the same als long as I use https. On http trying to reach google (only happens with the google domain) I get to a google page giving me a 404-error by google. 

same traefik.yaml as before
staticservers.yaml
```yaml
# staticservers.yaml
http:
  services:
    test:
      loadBalancer:
        servers:
        - url: "https://www.google.de"

  routers:
    test:
      rule: "Host(`test.testpi.local`)"
      service: "test"
      entryPorts:
      - "secure"
      - "unsecure"

```
