### ISSUE TITLE
user traefik tcp for redis

### ISSUE THREAD

**Issue by yyf1986** [containous/traefik#6485]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I use traefik to proxy redis
### What did you expect to see?
I can not use traefik's entrypoint to use redis

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.6
Codename:     cantal
Go version:   go1.13.8
Built:        2020-02-28T17:40:18Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.redis]
    address = ":8081"

[log]
  level = "INFO"
  format = "json"
  
[accessLog]
  filePath = "/var/log/traefik.log"
  format = "json"

[api]
  insecure = true
  dashboard = true

[ping]

[providers.file]
  directory = "/etc/traefik/dynamic"
  watch = true
```

```
## Dynamic configuration
tcp:
  routers:
    redis:
      # won't listen to entry point web
      entryPoints:
        - "redis"
      rule: "HostSNI(`*`)"
      service: "redis"
      # will route TLS requests (and ignore non tls requests)
      tls: 
        passthrough: true

  services:
    redis:
      loadBalancer:
        servers:
          - address: "192.168.175.139:6379"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
