### ISSUE TITLE
Kubernetes - LetsEncrypt Cert in Volume, does not persist through pod restarts

### ISSUE THREAD

**Issue by GoingOffRoading** [containous/traefik#6487]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Followed the" Kubernetes and Let's Encrypt" guide found here: https://docs.traefik.io/v2.0/user-guides/crd-acme/

Setup an HTTPS redirect scheme.

Setup my services to receive 80/443 traffic through Traefik, everything works great.

I wanted the LetsEncrypt cert to persist through pod restarts (not covered in the above guide) so I 
 created a Persistent Volume, copied my working acme.json out of the existing pod and into the Persistent Volume directory (directory/cert), reconfigured the deployment configurations, relaunched the deployment (nukes old pod, creates a new one) and none of the SSL certs are working.

No errors, nothing in the logs. 

Configurations will be at the bottom.

### What did you expect to see?

After copying the working acme.json from the pod into a volume and relaunching the pod with the acme.json mounted as a volume that all of the working certs would continue to work.

### What did you see instead?

HTTPS is not working on port 443 traffic or port 80 redirected to port 443.

In the browser, the certificate shows as valid (screenshot: http://prntscr.com/rgcyxv ) but the browser is reporting "Not Secure".

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.0 Docker Image
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.http.Address=:80
            - --entrypoints.https.Address=:443
#            - --entrypoints.mqtt.Address=:1883
            - --certificatesresolvers.le.acme.email=MYEMAIL
            - --certificatesresolvers.le.acme.storage=/cert/acme.json
            - --certificatesresolvers.le.acme.httpchallenge=true
            - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
            - --providers.kubernetescrd=true
            - --providers.kubernetesIngress=true
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8080
            - name: mqtt
              containerPort: 1883
          volumeMounts:
            - name: nfs-traefik-cert
              mountPath: "/cert"
      volumes:
        - name: nfs-traefik-cert
          persistentVolumeClaim:
            claimName: nfs-traefik-cert
```

Logs: Ignore the error around MQTT... I'm experimenting with redirecting of other ports... Hence the desire for LetsEncrypt to persist between restarts

```
time="2020-03-14T18:13:44Z" level=info msg="Configuration loaded from flags."
time="2020-03-14T18:13:45Z" level=error msg="entryPoint \"mqtt\" doesn't exist" routerName=default-rabbitmq-mqtt-d1bf7990b8ad9cc03624@kubernetescrd entryPointName=mqtt
time="2020-03-14T18:13:45Z" level=error msg="no valid entryPoint for this router" routerName=default-rabbitmq-mqtt-d1bf7990b8ad9cc03624@kubernetescrd
10.32.0.1 - - [14/Mar/2020:18:13:47 +0000] "GET /api/entrypoints HTTP/2.0" 200 486 "-" "-" 1 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:47 +0000] "GET /api/overview HTTP/2.0" 200 363 "-" "-" 2 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:47 +0000] "GET /api/entrypoints HTTP/2.0" 200 486 "-" "-" 3 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:47 +0000] "GET /api/overview HTTP/2.0" 200 363 "-" "-" 4 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:50 +0000] "GET /api/overview HTTP/2.0" 200 363 "-" "-" 6 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:50 +0000] "GET /api/entrypoints HTTP/2.0" 200 486 "-" "-" 5 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:55 +0000] "GET /api/entrypoints HTTP/2.0" 200 486 "-" "-" 7 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
10.32.0.1 - - [14/Mar/2020:18:13:55 +0000] "GET /api/overview HTTP/2.0" 200 363 "-" "-" 8 "default-traefik-https-8e3796dbfaf4fa09560b@kubernetescrd" "http://10.44.0.1:8080" 0ms
```
