### ISSUE TITLE
Service HealthCheck of IngressRoute in K8s is not applied

### ISSUE THREAD

**Issue by xbaun** [containous/traefik#6496]
Bug

### What did you do?

Setup health check for an ExternalName service in Kubernetes as in the [kubernetes-crd](https://docs.traefik.io/reference/dynamic-configuration/kubernetes-crd/) example.

### What did you expect to see?

A repeated requests to the service to check if it is alive.

### What did you see instead?

No requests at all are fired.

The IngressRoute CDR gets not fully parsed in the function  [ `buildServicesLB`](https://github.com/containous/traefik/blob/37fb5298a026fdf6518fae32a5db972e446e152a/pkg/provider/kubernetes/crd/kubernetes_http.go#L182) of the Kubernetes provider. The `HealthCheck` definition should probably be copied to the [`wrrService`](https://github.com/containous/traefik/blob/a474e196eafcab677e778014fe6d40847a54d109/pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go#L75) config object. 

In the log output the `healthCheck` property of the CDR is ignored:
```
{
  "http": {
    "routers": {
      "default-httpbin-route-899fb09e8f23f84a5a74": {
        "entryPoints": [
          "web"
        ],
        "service": "default-httpbin-route-899fb09e8f23f84a5a74",
        "rule": "Host(`httpbin.org`)"
      },
      "default-traefik-dashboard-d012b7f875133eeab4e5": {
        "entryPoints": [
          "traefik"
        ],
        "service": "api@internal",
        "rule": "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      }
    },
    "services": {
      "default-httpbin-route-899fb09e8f23f84a5a74": {
        "loadBalancer": {
          "servers": [
            {
              "url": "http://httpbin.org:80"
            }
          ],
          "passHostHeader": true
        }
      }
    }
  },
  "tcp": {},
  "tls": {}
}
```

https://github.com/containous/traefik/blob/37fb5298a026fdf6518fae32a5db972e446e152a/pkg/provider/kubernetes/crd/kubernetes_http.go#L182

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
kind: Service
apiVersion: v1
metadata:
  name: httpbin-extsrv
  namespace: default
  labels:
    app: httpbin-extsrv
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: ExternalName
  externalName: httpbin.org
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`httpbin.org`)
      services:
        - healthCheck:
            path: /status/503
            intervalSeconds: 10
            timeoutSeconds: 3
          kind: Service
          name: httpbin-extsrv
          port: 80
          schema: http
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-03-16T12:32:19Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"routers\":{\"default-httpbin-route-899fb09e8f23f84a5a74\":{\"entryPoints\":[\"web\"],\"service\":\"default-httpbin-route-899fb09e8f23f84a5a74\",\"rule\":\"Host(`httpbin.org`)\"},\"default-traefik-dashboard-d012b7f875133eeab4e5\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/dashboard`) || PathPrefix(`/api`)\"}},\"services\":{\"default-httpbin-route-899fb09e8f23f84a5a74\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://httpbin.org:80\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"tls\":{}}" providerName=kubernetescrd
time="2020-03-16T12:32:19Z" level=debug msg="Added outgoing tracing middleware api@internal" routerName=default-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd middlewareType=TracingForwarder middlewareName=tracing entryPointName=traefik
time="2020-03-16T12:32:19Z" level=debug msg="Added outgoing tracing middleware ping@internal" middlewareName=tracing middlewareType=TracingForwarder routerName=ping@internal entryPointName=traefik
time="2020-03-16T12:32:19Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2020-03-16T12:32:19Z" level=debug msg="Creating middleware" routerName=default-httpbin-route-899fb09e8f23f84a5a74@kubernetescrd entryPointName=web serviceName=default-httpbin-route-899fb09e8f23f84a5a74 middlewareName=pipelining middlewareType=Pipelining
time="2020-03-16T12:32:19Z" level=debug msg="Creating load-balancer" entryPointName=web serviceName=default-httpbin-route-899fb09e8f23f84a5a74 routerName=default-httpbin-route-899fb09e8f23f84a5a74@kubernetescrd
time="2020-03-16T12:32:19Z" level=debug msg="Creating server 0 http://httpbin.org:80" entryPointName=web serviceName=default-httpbin-route-899fb09e8f23f84a5a74 routerName=default-httpbin-route-899fb09e8f23f84a5a74@kubernetescrd serverName=0
time="2020-03-16T12:32:19Z" level=debug msg="Added outgoing tracing middleware default-httpbin-route-899fb09e8f23f84a5a74" middlewareName=tracing middlewareType=TracingForwarder routerName=default-httpbin-route-899fb09e8f23f84a5a74@kubernetescrd entryPointName=web
time="2020-03-16T12:32:19Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
time="2020-03-16T12:32:19Z" level=debug msg="No default certificate, generating one"
time="2020-03-16T12:32:19Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd

```
