### ISSUE TITLE
Error extracting client certificate with TLS1.0

### ISSUE THREAD

**Issue by jvegcar** [containous/traefik#6503]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
My version of traefik is: v2.2.0-rc2
I'm using a client with authentication with his own client certificate. Connection is under TLS1.0 without using SNI.

### What did you expect to see?
Certificate arrives to traefik and traefik is able to send it to my backend into the following header: X-Forwarded-Tls-Client-Cert

If I use SNI my configuration works as expected.

### What did you see instead?

I see the following message into the traefik log, and the certificate is not passing to my backend
```
time="2020-03-17T11:06:53Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=default-addprefix@kubernetescrd middlewareType=PassClientTLSCert
time="2020-03-17T11:06:53Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=default-addprefix@kubernetescrd middlewareType=PassClientTLSCert
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

 v2.2.0-rc2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
I'm working with kubernetes CRDS I put here the relevant configuration
```yml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: addprefix
  namespace: default
spec:
  passTLSClientCert:
    info:
      subject:
        commonName: true
    pem: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: mtlsoption
  namespace: default
spec:
  minVersion: VersionTLS12
  clientAuth:
    caSecret: ca-secret
    secretNames:
      - ca-secret
    clientAuthType: VerifyClientCertIfGiven
---
apiVersion: traefik.containo.us/v1alpha1  
kind: IngressRoute  
metadata:  
  name: ingressroutetlsapi
  namespace: default
spec:  
  entryPoints:
    - websecure
  routes:
  - match: Host(`XXXXX`) && PathPrefix(`/XXX`)
    kind: Rule
    middlewares: 
    - name: addprefix
      namespace: default
    services:
    - name: device-api
      port: 80
  tls:
    secretName: ssl-secret
    options:
      name: mtlsoption
      namespace: default
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
```
time="2020-03-17T11:06:53Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=default-addprefix@kubernetescrd middlewareType=PassClientTLSCert
time="2020-03-17T11:06:53Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=default-addprefix@kubernetescrd middlewareType=PassClientTLSCert
```
