### ISSUE TITLE
middleware@file not found, when using "custom" entrypoint

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#6508]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

Apllying middleware from file is not working on "backend" entrypoint, but instead on the http, htpps entrypoint it's working as expected, without configuring something else there...

### What did you see instead?

Log:
```3e4bihx time="2020-03-17T18:50:36Z" level=debug msg="Middleware name not found in config (ResponseModifier)" entryPointName=backend routerName=somethingssl@docker middlewareName=security-headers@file middlewareType=undefined
3e4bihx time="2020-03-17T18:50:36Z" level=debug msg="Middleware name not found in config (ResponseModifier)" middlewareName=response-headers@file middlewareType=undefined entryPointName=backend routerName=somethingssl@docker
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(2.2)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[file]

## dynamic configuration
# dynamic_conf.toml

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"
    # Security-Headers
  [http.middlewares.security-headers.headers]
    ForceSTSHeader = true
    SSLRedirect = true
    STSIncludeSubdomains = true
    STSPreload = true
    STSSeconds = 315360000
  [http.middlewares.response-headers.headers.customResponseHeaders]
    X-Powered-By = "developer"
    Server = "developer"
```
```
version: '3.7'
services:
  traefik:
    image: traefik:v2.2
    command:
     - --log=true
     - --log.level=DEBUG
     - --accesslog=true
     - --accesslog.filepath=/var/log/traefik/access.log
     - --accesslog.filters.statuscodes=400-499
     - --providers.docker.exposedbydefault=false
     - --entryPoints.web.address=:80
     - --entryPoints.web-secure.address=:443
     - --entryPoints.backend.address=:50077
     - --global.sendAnonymousUsage=false
     - --global.checknewversion=false
     - --serverstransport.insecureskipverify=true
     - --providers.docker.swarmMode=true
     - --providers.docker.endpoint=unix:///var/run/docker.sock
     - --providers.docker.network=traefik_reverseproxy_net
     - --providers.file.filename=/etc/traefik/dynamic_conf.toml
     - --providers.file.watch=true
     - --certificatesResolvers.letsencrypt.acme.email=admin@someone.yolo
     - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
     - --certificatesResolvers.letsencrypt.acme.tlsChallenge=true
     - --certificatesResolvers.letsencrypt.acme.keyType=RSA4096
    ports:
     - 80:80
     - 443:443
     - 50077:50077
    volumes:
     - traefik_reverseproxy_log:/var/log/traefik
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - traefik_reverseproxy_letsencrypt:/letsencrypt
    networks:
     - net
    configs:
     -
      source: traefik_config
      target: /etc/traefik/dynamic_conf.toml
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      update_config:
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        delay: 10s
        max_attempts: 10
networks:
  net:
    driver: overlay
    driver_opts:
      opt: encrypted
volumes:
  traefik_reverseproxy_letsencrypt:
    external: true
  traefik_reverseproxy_log:
    external: true
configs:
  traefik_config:
    external: true

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
