### ISSUE TITLE
V2.0.2 - Websecure not working

### ISSUE THREAD

**Issue by Felipenho** [containous/traefik#6509]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Tried to create a HTTPS redirect

### What did you expect to see?

All the services running on port 443

### What did you see instead?

Took too long to awnser and got no response.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
A Docker Image V2.0.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik Configuration:
```yaml
version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.0.2
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
    - "traefik.http.routers.http-catchall.entrypoints=web"
    - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
    - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=luiz.siqueira@cspconsultoria.com.br"
      - "--certificatesResolvers.letsencryptresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.insecure"
      - "--api.dashboard=true"
    ports:
      - 80:80
      - 443:443
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  traefik-certificates:

networks:
  traefik-public:
    external: true
```
Service Working around Traefik
```yaml
version: "3.7"

services:
  front:
    image: linka-front-hml:1.0
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`linka.cspconsultoria.com.br`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
    - traefik-public

networks:
  traefik-public:
    external: true

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
ERR_CONNECTION_TIMED_OUT - any browser even with a A record on DNS is added.
```
