### ISSUE TITLE
Traefik Spamming Let's Encrypt because of custom error page

### ISSUE THREAD

**Issue by nalakawula** [containous/traefik#6521]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I try to create custom error page for an ingress.

### What did you expect to see?

I expect traefik not request LE SSL for custom error page

### What did you see instead?

When I check traefik log, i got long line repeated that contain:
```
{"level":"error","msg":"Unable to obtain ACME certificate for domains \"error-page\" detected thanks to rule \"Host:error-page\"  : unable to generate a certificate for the domains [error-page]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"error-page\": Domain name needs at least one dot, url: ","time":"2020-03-19T09:14:01Z"} 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.21
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here is my traefik ingress yaml:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: mysite-ns
  name: mysite
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/browser-xss-filter: 'true'
    ingress.kubernetes.io/content-type-nosniff: 'true'
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-max-age: "3000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "false"
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/custom-frame-options-value: "SAMEORIGIN"
    ingress.kubernetes.io/content-security-policy: upgrade-insecure-requests
    #traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/buffering: |-
      maxrequestbodybytes: 10485760
      memrequestbodybytes: 10485760
      maxresponsebodybytes: 10485761
      memresponsebodybytes: 10485760
      retryexpression: IsNetworkError() && Attempts() <= 2
    traefik.ingress.kubernetes.io/rate-limit: |
      extractorfunc: client.ip
      rateset:
        wlc:
          period: 1s
          average: 50
          burst: 100
    traefik.ingress.kubernetes.io/priority: "20"
    traefik.ingress.kubernetes.io/error-pages: |-
      customerror:
        status:
        - '401'
        - '403'
        - '404'
        - '429'
        - '500'
        - '503'
        # See below on where "error-pages" comes from
        backend: "20-error-page"
        query: "/{status}.html"
spec:
  rules:
  - host: mysite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apache
          servicePort: 80
  - host: error-page
    http:
      paths:
      - backend:
          serviceName: traefik-catchall
          servicePort: 80

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"error","msg":"Unable to obtain ACME certificate for domains \"error-page\" detected thanks to rule \"Host:error-page\"  : unable to generate a certificate for the domains [error-page]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"error-page\": Domain name needs at least one dot, url: ","time":"2020-03-19T09:14:01Z"} 
```
