### ISSUE TITLE
Cannot reference basicAuth middleware from service that is in a separate docker-compose with respect to Traefik

### ISSUE THREAD

**Issue by naikio** [containous/traefik#6528]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
So, i have 2 docker compose files:
Main one, with Traefik, and a WHOAMI service that is just there as a test. I have setup certificates and also basic auth works just fine (i have created an .htpasswd file)

```
...

networks:
  web:
    external: true
  monitor-net:
    external: true

    
services:

  traefik:
    image: "traefik:v2.1.0"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - web
      - monitor-net
    command:
      # DEBUG LOGS
      # - "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.toml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Certificate resolver - Let's Encrypt (LE)
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      # DEBUG CA server - uncomment for testing
      # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=example@${DOMAINNAME}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./containers/traefik/dynamic_conf.toml:/etc/traefik/dynamic_conf.toml"
      - "./containers/traefik/.htpasswd:/etc/traefik/.htpasswd"
    labels:
      # middleware redirect to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"  
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"  
      - "traefik.http.routers.http-catchall.entrypoints=web"  
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.authtraefik.basicauth.usersfile=/etc/traefik/.htpasswd"
      # Traefik dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      # - "traefik.http.routers.traefik.tls.options=strong-tls@file"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAINNAME}`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.routers.whoami.middlewares=authtraefik"
      #- "traefik.http.routers.whoami.tls.options=strong-tls@file"

```

Then i have a separate docker-compose, for a little stack with Grafana/Prometheus and other tools for monitoring my system.
Inside the Grafana service, i can reference Traefik, and create a service from there with a new domain grafana.$DOMAINNAME. THe problem is that if I add the middleware it doesn't recognize any user, and so i cannot login.

```
networks:
  monitor-net:
    external: true
...
some other services like prometheus, cadvisor, etc
...

  grafana:
    image: grafana/grafana-arm32v7-linux
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - monitor-net
    user: "104"
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`monitor.${DOMAINNAME}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.routers.traefik.middlewares=authtraefik"  --> if i remove this line, everything works fine without auth of course

```

### What did you expect to see?
Expected it to work the same way

### What did you see instead?
Authentication does not work

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.0
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-11T17:59:20Z
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
