### ISSUE TITLE
gateway 502 error 

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6529]
### Do you want to request a *feature* or report a *bug*?
Bug

version: v2.1.6
provider: Kubernetes CRD

### What did you do?
client->traefik2.16->k8spods

**conf TemminationDelay: 60000 in IngressRoute** 
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: testingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`your.domain.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: testservice
      port: 80
      TemminationDelay: 60000
```
gateway 502 in access log 

"OriginDuration":53939390(nanosecond) < TemminationDelay: 60000(millisecond)
```
{"ClientAddr":"","ClientHost":"","ClientPort":"62979","ClientUsername":"-","DownstreamContentSize":11,"DownstreamStatus":502,"Duration":54046957,"OriginContentSize":11,"OriginDuration":53939390,"OriginStatus":502,"Overhead":107567,"entryPointName":"http","level":"info","msg":"","time":"2020-03-20T14:32:49+08:00"}
```

### What did you expect to see?
I expect to be able to control the read timeout(write timeout, connect timeout) of the proxy
