### ISSUE TITLE
TLS v1.3 not working on traefik v1.7.22

### ISSUE THREAD

**Issue by richierg** [containous/traefik#6530]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Activate TLS 1.3 on traefik 1.7.22. 
The configuration below is working for traefik v1.7.21

### What did you expect to see?
TLS 1.3 enabled on traefik 1.7.22 when we set env "GODEBUG=tls13=1"

### What did you see instead?
TLS 1.2 only enabled 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.22
Codename:     maroilles
Go version:   go1.14
Built:        2020-03-18_02:12:03PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: "3.4"
services:
  traefik:
    image: traefik:v1.7.22
    environment:
      - "GODEBUG=tls13=1"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: "/srv/traefik/keys"
        target: "/certs"
        read_only: true
      - type: bind
        source: "/srv/traefik/log"
        target: "/var/log/traefik"
    deploy:
      mode: global
    networks:
      - traefik-net
      - dockersocket4traefik_net
    command: |
      --docker
      --docker.swarmmode
      --docker.domain=traefik
      --docker.endpoint="tcp://dockersocketproxy:2375"
      --docker.watch
      --api
      --entryPoints="Name:https Address::443 TLS:/certs/cert.crt,/certs/key.key TLS.CipherSuites:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
      --entryPoints="Name:traefik Address::8080 TLS:/certs/cert.crt,/certs/key.key TLS.CipherSuites:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
      --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
      --InsecureSkipVerify=true
      --logLevel="INFO"
      --traefikLog.filePath="/var/log/traefik/traefik.log"
      --accessLog.filePath="/var/log/traefik/access.log"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
