### ISSUE TITLE
Unable to create router for some containers

### ISSUE THREAD

**Issue by TheTrigger** [containous/traefik#6534]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Creating a new container through docker-compose.
I tried to create the container "manually" from portainer, but same behavior.

broken:
```yml
  workify:
    image: "registry.gitlab.com/thetrigger/workify-backend:latest"
```
working:
```yml
  workify:
    image: "containous/whoami"

```

labels:
```yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workify-backend.rule=Host(`be.workify.ncs.oibi.dev`)"
      - "traefik.http.routers.workify-backend.tls=true"
      - "traefik.http.routers.workify-backend.tls.certresolver=le"
```

The problem seems triggered by the image from ASP.NET Core 3 (tried with ubuntu and alpine)
I tried with another software that's **based on 2.2 and it's working**.

Simple 3.1 Dockerfile (not working)
```Dockerfile
# Stage 1
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /build

EXPOSE 80
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app
# Stage 2
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Workify.dll"]
```
Working 2.2:
```Dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80

[ .. omitted ..]

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build

[ .. omitted ..]
```

### What did you expect to see?

- Working router and https certificates
- ![image](https://user-images.githubusercontent.com/6072718/77188294-08b75680-6ad6-11ea-98cc-c4ce3298b3fe.png)

### What did you see instead?

- No http router and no certificates

### Output of `traefik version`: 2.1
docker: **Docker version 19.03.5, build 633a0ea838**
Traefil: **2.1.8**

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik2_default"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=-omitted-"
      - "--certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.le.acme.dnsChallenge=true"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.bufferingsize=100"
    networks:
      - traefik2_default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/traefik2/configuration/:/configuration/"
      - "/opt/traefik2/acme:/etc/traefik/acme" # chmod 600 acme
      - "/opt/traefik2/logs:/logs/"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik2_default"
      - "traefik.http.routers.api.rule=Host(`traefik.oibi.dev`)" # || Path(`/*`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=dashboardBasicAuth"
      - "traefik.http.middlewares.dashboardBasicAuth.basicauth.users=-omitted-"
      # ANY HTTP to HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"

networks:
  traefik2_default:
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

since route is ignored:
```
time="2020-03-20T16:56:31Z" level=debug msg="Serving default certificate for request: \"be.workify.ncs.oibi.dev\""
```
