### ISSUE TITLE
Service => Server => Status (Dashboard)

### ISSUE THREAD

**Issue by Fruchtgummi** [containous/traefik#6548]
I run a docker-compose with the follow attrbutes:

```
version: '3'
networks:
  traefik-proxy:
    external: true

volumes:
  arangodbdev:

services:
  arangodb:
    image: arangodb:latest
    volumes:
      - /srv/arangodb:/data
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=xxxxx-xxx
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.arangodb.entrypoints=arangodb
      - traefik.tcp.routers.arangodb.rule=HostSNI(`xx.dev.xxx.net`)
      - traefik.tcp.routers.arangodb.tls=true
      - traefik.tcp.routers.arangodb.tls.certresolver=letsencrypt
      - traefik.tcp.routers.arangodb.tls.passthrough=true
      - traefik.tco.routers.arangodb.service=arangodb@docker
      - traefik.tcp.services.arangodb.loadbalancer.server.port=8529
      - traefik.docker.network=traefik-proxy
    restart: always
```

The dashboart of traefik shows 

![image](https://user-images.githubusercontent.com/2059888/77246471-e2093500-6c27-11ea-98df-8ceeb5f3cbea.png)

the url xxxxx.xx:8529 is http not https?
