### ISSUE TITLE
Dynamic config as file for docker

### ISSUE THREAD

**Issue by Tatayoyoh** [containous/traefik#6559]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

As a DevOps, I would like to change my ReverseProxy configuration without restart my docker containers.

Maybe I missed a feature but after many tryes  it was impossible to start a docker container and link a Traefik dynamic config to it. 

Bless to the 2.2 feature #6417 it's now possible to have a global certresolver and https redirection as a default config. It's already less labels in my docker-compose. Thanks a lot for your work !

Here an example of docker-compose config
```yaml
services:
    myapp:
        ....
        container_name: "myappname"
        expose:
          - '8080'
          - '8081'
        labels:
            - traefik.enable=true
            - traefik.http.routers.myapp.rule=Host(`myapp.mydomain.io`)
            - traefik.http.routers.myapp.entrypoints=websecure
            - traefik.http.routers.myapp.service=myapp-service
            - traefik.http.services.myapp-service.loadbalancer.server.port=8081
            - traefik.docker.network=traefik_webgateway
```

The goal is to get rid of the above labels with a dynamic config file like below
```yaml
http:
  routers:
    myapp:
      rule: "Host(`myapp.mydomain.io`)"
      service: myapp-docker
      entryPoints:  
        - websecure

  services:
    myapp-docker:
      docker:
        container-name: myappname"  # links the container name
        port: 8081
        network: traefik_webgateway
        # other Docker configs 
```
