### ISSUE TITLE
Define Middlewares in Kubernetes Ingress Provider

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#6565]
Hello everyone!
After receiving you're feedback about defining middlewares inline in YAML syntax inside the Kubernetes Ingress Provider,
we discussed that matter internally again.
After re-consideration, we want to propose the following study which we'll add to our roadmap in order to increase our efforts to enhance the User Experienceon Kubernetes.
With that beeing said, our current idea is to make it possible to define middlewares (somewhat) like that

```YAML
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp
  namespace: webapp
  annotations: 
      traefik.ingress.kubernetes.io/router.middlewares-inline: |
        - redirectScheme:
            scheme: https
        - ipWhiteList:
            sourceRange:
            - 192.168.1.7
            - 127.0.0.1/32
        - basicAuth:
            users:
            - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
spec:
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: test
          servicePort: 80
```

This of course has a couple of limitations:

- You can either define middlewares inline, or reference other Middleware CR's
- There is no way to configure / guarante a chain

Therefore, this is not the final configuration but our current proposal.

Thanks for all your valuable feedback. We're eagerly listening and will continue to do so, in order to provide you with the features
