### ISSUE TITLE
Config update issues with docker-compose and tcp and tls passthrough

### ISSUE THREAD

**Issue by krufab** [containous/traefik#6584]
I found a strange behaviour which I think is a bug.
I'm using traefik v2.2-rc4 & docker 19.03.8 on Ubuntu 18.04.4 LTS

### What did you do?
I'd like to have traefik perform TLS passthrough to several TCP services.
I have valid let's encrypt certificates (*.example.com) and I've configured traefik to be executed via docker-compose and have all the services executed from another docker-compose file. The traefik network is attached to the services.
The configuration of the TCP routes and services shows up correctly in the docker dashboard.

### What did you expect to see?
I expect to have the traffic routed correctly to the services.

### What did you see instead?
In general, it seems that the traffic is routed correctly only when traefik and the services are started the first time (that is, execute ```docker-compose up```, both for the docker-compose with traefik and for the one with the services or when the service containers & network are deleted and then recreated.
So, if I only stop the containers (i.e. with ```Ctrl-C```) and perfomr ```docker-compose up -d``` again, then traffic doesn't reach anymore the services.

I performed several tests, and it seems that if a service is attached to the traefik network AND to another network, traefik (or docker) don't update the reference to the new container between restarts.
From the code below, testtcp1 works all the times (it is only connected to traefik network) while testtcp2 only works after traefik is restarted.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      2.2.0-rc4
Codename:     chevrotin
Go version:   go1.14
Built:        2020-03-19T17:31:45Z
OS/Arch:      linux/amd64

### Here is my configuration:
docker-compose.yml  for traefik
```yaml
version: "3.3"
services:
  traefik:
    image: "traefik:v2.2"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
```

And here docker-compose.yml for the services
```yaml
version: "3.3"
services:
  testtcp1:
    image: "nginx:alpine"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.testtcp1.entrypoints=websecure"
      - "traefik.tcp.routers.testtcp1.rule=HostSNI(`testtcp1.example.com`, `testtcp3.example.com`)"
      - "traefik.tcp.routers.testtcp1.service=servicetcp1"
      - "traefik.tcp.routers.testtcp1.tls.passthrough=true"
      - "traefik.tcp.services.servicetcp1.loadbalancer.server.port=443"
    networks:
      - traefik
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro

  testtcp2:
    image: "nginx:alpine"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.testtcp2.entrypoints=websecure"
      - "traefik.tcp.routers.testtcp2.rule=HostSNI(`testtcp2.example.com`)"
      - "traefik.tcp.routers.testtcp2.service=servicetcp2"
      - "traefik.tcp.routers.testtcp2.tls.passthrough=true"
      - "traefik.tcp.services.servicetcp2.loadbalancer.server.port=443"
    networks:
      - traefik
      - a_network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro


networks:
  a_network:
    driver: bridge
  traefik:
    external:
      name: traefik_default
```
default.conf - The sample nginx file containing references to the certificates
```
server {
    listen 443 ssl;
    ssl_certificate /etc/nginx/certs/fullchain.cer;
    ssl_certificate_key /etc/nginx/certs/certificate.key;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}
```
With these commands:
```bash
docker-compse up
# In another shell
curl https://testtcp1.example.com
# ok
curl https://testtcp2.example.com
# ok
curl https://testtcp3.example.com
# ok
# Ctrl-C in the first shell
docker-compose up -d
curl https://testtcp1.example.com
# ok
curl https://testtcp2.example.com
# **------>hangs**
curl https://testtcp3.example.com
# ok
```

And from the logs:
```
# first setup
level=debug msg="Adding route testtcp2.example.com on TCP" entryPointName=websecure routerName=testtcp2@docker
level=debug msg="Creating TCP server 0 at 172.28.0.2:443" entryPointName=websecure routerName=testtcp3@docker serviceName=servicetcp3 serverName=0 

# second setup
level=debug msg="Creating TCP server 0 at 172.20.0.5:443" serviceName=servicetcp2 serverName=0 entryPointName=websecure routerName=testtcp2@docker
level=debug msg="Adding route testtcp2.example.com on TCP" entryPointName=websecure routerName=testtcp2@docker

# call to old service/backend
level=error msg="Error while connection to backend: dial tcp 172.28.0.2:443: connect: connection timed out"
```

**Comment by ddtmachado** [comment]
@krufab Although I could reproduce the behavior, while removing all other variables except the routing, it doesn't seem to be an issue as you should always define which network Traefik will use to connect to the service when binding a container to multiple networks. by doing that it worked well for me.

**Traefik**

```yaml
version: "3.3"
services:
  traefik:
    image: "traefik:v2.2"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.whoami1.address=:8888"
      - "--entrypoints.whoami2.address=:8889"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"      
      - "443:443"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

**TCP services**

```yaml
version: "3.3"
services:
  testtcp1:
    image: "containous/whoamitcp:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.testtcp1.entrypoints=whoami1"
      - "traefik.tcp.routers.testtcp1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.testtcp1.service=servicetcp1"
      - "traefik.tcp.services.servicetcp1.loadbalancer.server.port=8080"
    networks:
      - traefik

  testtcp2:
    image: "containous/whoamitcp:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.testtcp2.entrypoints=whoami2"
      - "traefik.tcp.routers.testtcp2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.testtcp1.service=servicetcp2"
      - "traefik.tcp.services.servicetcp2.loadbalancer.server.port=8080"
    networks:
      - traefik
      - a_network

networks:
  a_network:
    driver: bridge
  traefik:
    external:
      name: docker_default
```

Note that when removing the `"traefik.docker.network=traefik"` label from `testtcp2` we get the issue you described because Traefik won't know which network address it should use to reach the service, eventually getting the wrong network address. With the label set I got it working every stopped/restarted the container with `docker-compose`.
