### ISSUE TITLE
CPU load with etcd provider

### ISSUE THREAD

**Issue by zoic21** [containous/traefik#6591]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Use trafik helm (1.7.20) with etcd provider whit about 1800 frontend and 2 backends

### What did you expect to see?

No excessive usage of cpu

### What did you see instead?

Usage of 6% cpu on etcd continuous and 5% on traefik pod. If I use 2 traefik pod etcd use 10% of CPU (I limit etcd maxProcs at 1 else it use 20% of cpu)

Another information add of new frontend on etcd take 1 or 2 min to appear in traefik

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.20 in with helm chart
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
replicas: 1
externalTrafficPolicy: Local
service:
  annotations:
    service.beta.kubernetes.io/ovh-loadbalancer-proxy-protocol: "v1"
whiteList:
  sourceRange:
    - 10.0.0.0/8
proxyProtocol:
  enabled: true
  trustedIPs:
    - 10.0.0.0/8
forwardedHeaders:
  enabled: true
  trustedIPs:
    - 10.0.0.0/8
kubernetes:
  namespaces:
    - dns
kvprovider:
  etcd:
    endpoint: "etcd:2379"
    watch: true
    prefix: traefik
    useAPIV3: true
dashboard:
  enabled: true
  domain: XXX
  auth:
    basic:
      XX:XX
ssl:
  enabled: true
  enforced: true
  defaultKey: XXX
  defaultCert : XXX
```

Thank in advance for your help
