### ISSUE TITLE
ACME resolve not supported on windows?

### ISSUE THREAD

**Issue by tfenster** [containous/traefik#6598]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I tried to use the Let's Encrypt ACME resolver on Windows, Traefik v2.2.0

### What did you expect to see?
Traefik request and get a LE certificate

### What did you see instead?
The logs show `The ACME resolver \"le\" is skipped from the resolvers list because: unable to get ACME account: chmod c:/etc/le/acme.json: not supported by windows` and I only get a self-signed cert when accessing Traefik. This worked very well with 1.7, what do I need to do to make it work with 2.0 again?

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:17:27Z
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Config file
```yml
 entryPoints:
   web:
     address: ":80"
   websecure:
     address: ":443"
 
certificatesResolvers:
   le:
     acme:
       email: tobias.fenster@...
       storage: c:/etc/le/acme.json
       httpChallenge:
         entryPoint: web

 log:
   level: DEBUG

```

Docker compose file:
```yml
 version: '3.7'

 services:
   reverse-proxy:
     image: traefik:2.2-windowsservercore-1809
     command: --api.insecure=true --providers.docker --providers.docker.endpoint=npipe:////./pipe/docker_engine
     ports:
       - "80:80"
       - "443:443"

     volumes:
       - c:\iac\traefik:c:/etc/traefik
       - type: npipe
         source: \\.\pipe\docker_engine
         target: \\.\pipe\docker_engine
       - le:c:\etc\le
     labels:
       - traefik.http.routers.traefik.rule=Host(`ppi-devops.germanywestcentral.cloudapp.azure.com`) && Path(`/traefik`)
       - traefik.http.routers.traefik.tls=true
       - traefik.http.routers.traefik.tls.certresolver=le
       - traefik.http.routers.traefik.entrypoints=websecure
       - traefik.http.services.traefik.loadbalancer.server.port=8080

 volumes:
   le:
     driver: local
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=info msg="Configuration loaded from file: C:\\etc\\traefik\\traefik.yml"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=info msg="Traefik version 2.2.0 built on 2020-03-25T17:17:27Z"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":1000000
0000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":
{}}},\"providers\":{\"providersThrottleDuration\":2000000000},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"le\":{\"acme\":{\"email\":\"tobias.fenster@...\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\
"c:/etc/le/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"web\"}}}}}"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=error msg="The ACME resolver \"le\" is skipped from the resolvers list because: unable to get ACME account: chmod c:/etc/le/acme.json: not supported by windows"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=debug msg="Start TCP Server" entryPointName=web
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=debug msg="Start TCP Server" entryPointName=websecure
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=info msg="Starting provider *traefik.Provider {}"
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"noop\":{}}},\"tcp\":{},\"tls\":{}}" providerName=internal
reverse-proxy_1  | time="2020-03-28T22:56:48Z" level=debug msg="No default certificate, generating one"
```
