### ISSUE TITLE
Traefik v2+ ignores declared default certificate

### ISSUE THREAD

**Issue by Sebi2020** [containous/traefik#6603]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I declared a default cert in the static configuration, which should allow me to use ONE cert for all routes/services.

### What did you expect to see?
I expected traefik to respect the setting.

```toml 
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/keys/fullchain.pem"
      keyFile  = "/keys/privkey.pem"
```

### What did you see instead?

The default traefik certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true
defaultEntryPoints = ["https","http"]
InsecureSkipVerify = true
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [redirections]
    [entryPoint]
      to = "https"
  [entryPoints.https]
  address = ":443"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  swarmMode = true
  network = "web"
  [tls]
    insescureSkipVerify = true

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/keys/fullchain.pem"
      keyFile  = "/keys/privkey.pem"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-03-30T13:04:56Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
```
