### ISSUE TITLE
Secure websocket connection yield 404 with Traefik IngressRoute (CRD)

### ISSUE THREAD

**Issue by mbrodala** [containous/traefik#6615]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have set up Traefik as Ingress controller for my Kubernetes cluster on DigitalOcean using [CRD and `IngressRoute`](https://docs.traefik.io/providers/kubernetes-crd/). This works fine for HTTP/HTTPS 

### What did you expect to see?

Connections to `wss://foo.example.org/ws` should work just fine.

### What did you see instead?

I get an error due to 404:

> WebSocket connection to 'wss://foo.example.org/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik Kubernetes service:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o .kube
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
    kompose.volume.size: 1Gi
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: traefik
  type: LoadBalancer
status:
  loadBalancer: {}
```

Traefik Kubernetes deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o .kube
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
    kompose.volume.size: 1Gi
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o .kube
        kompose.service.expose: "true"
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
        kompose.volume.size: 1Gi
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - args:
        - --log.level=DEBUG
        - --accesslog
        - --api.insecure
        - --api.dashboard
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
        - --providers.kubernetescrd
        - --certificatesResolvers.default.acme.httpchallenge.entrypoint=web
        - --certificatesresolvers.default.acme.email=info@example.org
        - --certificatesresolvers.default.acme.storage=/letsencrypt/acme.json
        image: traefik:2.2
        imagePullPolicy: ""
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /letsencrypt/
          name: letsencrypt
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: letsencrypt
        persistentVolumeClaim:
          claimName: letsencrypt
status: {}
```

Websocket service Ingress routes:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ws-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`foo.example.org`)
      kind: Rule
      services:
        - name: ws-service
          port: 80
      middlewares:
        - name: forwarded-proto-https
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ws-insecure-route
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`foo.example.org`)
      kind: Rule
      services:
        - name: ws-service
          port: 80
      middlewares:
        - name: redirect-https
```

Redirect middleware:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: "true"
```

Proto forwarding middleware:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forwarded-proto-https
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-04-01T09:28:02Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/ws\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.9,de;q=0.8\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"Upgrade\"],\"Origin\":[\"https://foo.example.org\"],\"Pragma\":[\"no-cache\"],\"Sec-Websocket-Extensions\":[\"permessage-deflate; client_max_window_bits\"],\"Sec-Websocket-Key\":[\"vZ8ntQc75OfSnZX3zpi1iQ==\"],\"Sec-Websocket-Version\":[\"13\"],\"Upgrade\":[\"websocket\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.158 Safari/537.36\"],\"X-Forwarded-Host\":[\"topo-foo.example.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-db5b797dd-4wsgb\"],\"X-Real-Ip\":[\"10.244.0.86\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"topo-foo.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.244.0.86:50446\",\"RequestURI\":\"/ws\",\"TLS\":null}"
time="2020-04-01T09:28:02Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://10.244.1.69:8080" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/ws\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.9,de;q=0.8\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"Upgrade\"],\"Origin\":[\"https://foo.example.org\"],\"Pragma\":[\"no-cache\"],\"Sec-Websocket-Extensions\":[\"permessage-deflate; client_max_window_bits\"],\"Sec-Websocket-Key\":[\"vZ8ntQc75OfSnZX3zpi1iQ==\"],\"Sec-Websocket-Version\":[\"13\"],\"Upgrade\":[\"websocket\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.158 Safari/537.36\"],\"X-Forwarded-Host\":[\"topo-foo.example.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-db5b797dd-4wsgb\"],\"X-Real-Ip\":[\"10.244.0.86\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"topo-foo.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.244.0.86:50446\",\"RequestURI\":\"/ws\",\"TLS\":null}"
time="2020-04-01T09:28:02Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/ws\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.9,de;q=0.8\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"Upgrade\"],\"Origin\":[\"https://foo.example.org\"],\"Pragma\":[\"no-cache\"],\"Sec-Websocket-Extensions\":[\"permessage-deflate; client_max_window_bits\"],\"Sec-Websocket-Key\":[\"vZ8ntQc75OfSnZX3zpi1iQ==\"],\"Sec-Websocket-Version\":[\"13\"],\"Upgrade\":[\"websocket\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.158 Safari/537.36\"],\"X-Forwarded-Host\":[\"topo-foo.example.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-db5b797dd-4wsgb\"],\"X-Real-Ip\":[\"10.244.0.86\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"topo-foo.example.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.244.0.86:50446\",\"RequestURI\":\"/ws\",\"TLS\":null}"
10.244.0.86 - - [01/Apr/2020:09:28:02 +0000] "GET /ws HTTP/1.1" 404 74 "-" "-" 200 "default-topo-backend-route-10334f91083892a48db5@kubernetescrd" "http://10.244.1.69:8080" 4ms
```

Any idea what I am doing wrong?
