### ISSUE TITLE
Traefik sends multiple ACME requests for identical hostnames

### ISSUE THREAD

**Issue by overheadhunter** [containous/traefik#6621]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've set a default certificate resolver and domain in traefiks static config in order to get a wildcard certificate via the DNS-01 challenge for my `websecure` entrypoint (see configuration below).

I've then created multiple ingresses for various subdomains.

### What did you expect to see?

I expect traefik to request the wildcard cert once and use it for all matching domains.

### What did you see instead?

Traefik correctly applies the TLS default configuration for all my ingresses using this entrypoint.

However, looking at the Cloudflare audit log it seems like traefik is attempting to complete the challenge _once for every router_.

At least I can see the creation of multiple `TXT _acme-challenge.example.com` records when traefik is started.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# ...
    spec:
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls.certresolver=letsencrypt
            - --entrypoints.websecure.http.tls.domains[0].main=*.example.com
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=0
            - --certificatesresolvers.letsencrypt.acme.email=webmaster@example.com
            - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
            - # other unrelated args...
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ingress-a
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: a.example.com
      # ...
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ingress-b
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: a.example.com
      # ...
---
```

I'm running traefik as my ingress controller for Kubernetes:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

<details>
  <summary>relevant parts of debug log</summary>
  
  ```
time="2020-04-02T11:10:38Z" level=info msg="Configuration loaded from flags."
time="2020-04-02T11:10:38Z" level=info msg="Traefik version 2.2.0 built on 2020-03-25T17:32:57Z"
...
time="2020-04-02T11:10:38Z" level=info msg="Starting provider *acme.Provider {\"email\":\"webmaster@example.com\",\"caServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"dnsChallenge\":{\"provider\":\"cloudflare\",\"resolvers\":[\"1.1.1.1:53\",\"8.8.8.8:53\"]},\"ResolverName\":\"letsencrypt\",\"store\":{},\"ChallengeStore\":{}}"
time="2020-04-02T11:10:38Z" level=info msg="Testing certificate renew..." providerName=letsencrypt.acme
time="2020-04-02T11:10:38Z" level=debug msg="Configuration received from provider letsencrypt.acme: {\"http\":{},\"tls\":{}}" providerName=letsencrypt.acme
...
time="2020-04-02T11:10:39Z" level=debug msg="Looking for provided certificate(s) to validate [\"*.example.com\"]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:39Z" level=debug msg="No default certificate, generating one"
...
time="2020-04-02T11:10:40Z" level=debug msg="Domains [\"*.example.com\"] need ACME certificates generation for domains \"*.example.com\"." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Looking for provided certificate(s) to validate [\"*.example.com\"]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Looking for provided certificate(s) to validate [\"*.example.com\"]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Looking for provided certificate(s) to validate [\"*.example.com\"]..." providerName=letsencrypt.acme
...
time="2020-04-02T11:10:40Z" level=debug msg="Domains [\"*.example.com\"] need ACME certificates generation for domains \"*.example.com\"." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Loading ACME certificates [*.example.com]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Loading ACME certificates [*.example.com]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Loading ACME certificates [*.example.com]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Loading ACME certificates [*.example.com]..." providerName=letsencrypt.acme
time="2020-04-02T11:10:40Z" level=debug msg="Loading ACME certificates [*.example.com]..." providerName=letsencrypt.acme
...
time="2020-04-02T11:10:47Z" level=info msg=Register... providerName=letsencrypt.acme
time="2020-04-02T11:10:47Z" level=debug msg="legolog: [INFO] acme: Registering account for webmaster@example.com"
time="2020-04-02T11:10:47Z" level=debug msg="Using DNS Challenge provider: cloudflare" providerName=letsencrypt.acme
time="2020-04-02T11:10:47Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Obtaining bundled SAN certificate"
time="2020-04-02T11:10:47Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Obtaining bundled SAN certificate"
time="2020-04-02T11:10:47Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Obtaining bundled SAN certificate"
time="2020-04-02T11:10:47Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Obtaining bundled SAN certificate"
time="2020-04-02T11:10:47Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Obtaining bundled SAN certificate"
...
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027538"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: use dns-01 solver"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Preparing to solve DNS-01"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: use dns-01 solver"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Preparing to solve DNS-01"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: use dns-01 solver"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Preparing to solve DNS-01"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: use dns-01 solver"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Preparing to solve DNS-01"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: use dns-01 solver"
time="2020-04-02T11:10:48Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Preparing to solve DNS-01"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] cloudflare: new record for example.com, ID 4e65b5edb59fce2e9f77195dc00542de"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Trying to solve DNS-01"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] cloudflare: new record for example.com, ID 7b51bf2211cdf957d450d7b2508dfd6a"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Trying to solve DNS-01"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Waiting for DNS record propagation."
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] [*.example.com acme: Cleaning DNS-01 challenge"
time="2020-04-02T11:11:01Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:11:02Z" level=error msg="Unable to obtain ACME certificate for domains \"*.example.com\" : unable to generate a certificate for the domains [*.example.com]: acme: Error -> One or more domains had a problem:\n[*.example.com] [*.example.com] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":81057,\\\"message\\\":\\\"The record already exists.\\\"}],\\\"messages\\\":[],\\\"result\\\":null}\"\n" providerName=letsencrypt.acme
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] cloudflare: new record for example.com, ID 0204b9f61fe6af80c5366de32720a671"
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Trying to solve DNS-01"
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]"
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Cleaning DNS-01 challenge"
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Waiting for DNS record propagation."
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:11:03Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/47027537"
time="2020-04-02T11:11:03Z" level=error msg="Unable to obtain ACME certificate for domains \"*.example.com\" : unable to generate a certificate for the domains [*.example.com]: acme: Error -> One or more domains had a problem:\n[*.example.com] [*.example.com] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":81057,\\\"message\\\":\\\"The record already exists.\\\"}],\\\"messages\\\":[],\\\"result\\\":null}\"\n" providerName=letsencrypt.acme
```
</details>
