### ISSUE TITLE
SNI not used when connecting to https services

### ISSUE THREAD

**Issue by geofffranks** [containous/traefik#6627]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When using Traefik 2.1 on Kubernetes with an IngressRoute configured to send traffic to an HTTPS backend service, Traefik fails to connect due to the issues described in https://github.com/containous/traefik/issues/3906 related to certs not containing IP SANs.  Setting InsecureSkipVerify to true can work around this, but is not an ideal solution. Can Traefik be made to send and SNI request to the backend service using the hostname passed in form the ingress service? 

Using a TCP ingress for this is also not ideal, as we are hoping to make use of the HTTP layer features of Traefik load balancing. 

### What did you expect to see?

Traefik to use the hostname requested on the inbound request to the IngressRoute as an SNI request to the backend service. Maybe this could be a feature based on whether "pass through host-header" is set in conjunction with a scheme of https?

### What did you see instead?

Traefik used the IP, and failed to validate the SSL certificate for the backend service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.1.9

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oidc-proxy
  namespace: auth-test
spec:
  routes:
  - kind: Rule
    match: "Host(`app.example.com`)"
    services:
    - kind: Service
      name: my-app
      namespace: default
      scheme: https
      port: 6443
  tls: {}
```
  config.toml: |-
    [entryPoints]
        [entryPoints.web]
            address = ":8000"

        [entryPoints.websecure]
            address = ":443"

        [entryPoints.traefik]
            address = ":8080"
    [ping]

    [accessLog]
      format = "json"

    [metrics]
      [metrics.prometheus]

    [api]
        dashboard = true

    [providers.kubernetesCRD]

    [providers]
        [providers.file]
            filename = "/etc/config/config.toml"
            watch = true

    [tls]
        [tls.options]
            [tls.options.default]
                minVersion = "VersionTLS12"
            [tls.options.mintls13]
                minVersion = "VersionTLS13"

        [tls.stores]
            [tls.stores.default]
                [tls.stores.default.defaultCertificate]
                    certFile = "/var/certs/default/tls.crt"
                    keyFile  = "/var/certs/default/tls.key"
    [serversTransport]
      insecureSkipVerify = true
```
