### ISSUE TITLE
_FILE counterpart environement variable of DO_AUTH_TOKEN don't work for Digitalocean 

### ISSUE THREAD

**Issue by v01t** [containous/traefik#6628]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Passed DO_AUTH_TOKEN_FILE=/run/secrets/do-token in docker-compose.yml / swarm

### What did you expect to see?
ACME to properly generate SSL certificate using Digitalocean provider

### What did you see instead?
`
{
  "level": "error",
  "msg": "Unable to obtain ACME certificate for domains \"sub.domain.com\": cannot get ACME client digitalocean: some credentials information are missing: DO_AUTH_TOKEN",
  "providerName": "letsencrypt.acme",
  "routerName": "example@docker",
  "rule": "Host(`sub.domain.com`)",
  "time": "2020-04-04T00:13:25Z"
}
`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
providers:
  file:
    filename: "/etc/traefik/traefik.yml"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    network: service

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@domain.com"
      storage: "/etc/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 0

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

log:
  level: warn
  format: json
  filePath: /dev/stdout
```

compose:
```
version: '3.3'

secrets:
  do-token:
    external: true

services:
  app:
    image: traefik:2.2
    deploy:
      labels:
        traefik.http.routers.traefik.rule: "Host(`sub.domain.com`)"
        traefik.http.routers.traefik.middlewares: "https-redirect@file"
        traefik.http.routers.traefik-https.rule: "Host(`sub.domain.com`)"
        traefik.http.routers.traefik-https.tls: "true"
        traefik.http.routers.traefik-https.tls.certresolver: "letsencrypt"
        traefik.http.services.traefik.loadbalancer.server.port: "8080"
    environment:
      DO_AUTH_TOKEN_FILE: "/run/secrets/do-token"
    logging:
      driver: json-file
      options:
        max-size: '50m'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - etc:/etc
      - /var/run/docker.sock:/var/run/docker.sock
```
with defined DO_AUTH_TOKEN environment variable certificates properly generated and acme challenge are successful
