### ISSUE TITLE
Add default Middlewares

### ISSUE THREAD

**Issue by Sebi2020** [containous/traefik#6634]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
It would be nice if Traefik would allow administrators to add "default" middlewares which whould be applied to all routers, which are attached to a specifiy entrypoint. I'm no sure but maybe this is a duplicate of #6441 and #6594 which mentions that Traefik 2.2 added some form of entrypoint defaults, but I haven't found any documentation on how to apply default middlewares for specific entrypoints.

If this is possible, please be a little bit more verbose about it in your documentation.

### Example
I want to apply http to https redirection to the http endpoint and gzip compression to http and https entrypoints.
By the way: The documentation was not clear about specification of TLS certificates. The current configuration seems to force the user to duplicate configuration entries:

```toml
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "path/to/cert.crt"
      keyFile  = "path/to/cert.key"
```
and
```toml
[[tls.certificates]]
  certFile = "/path/to/domain.cert"
  keyFile = "/path/to/domain.key"
  stores = ["default"]
```
It absolutly makes no sense to declare a certificate store with keyfile and certFile (and there is only one, why ever) once only to redeclare the same certificate files under `[[tls.certificates]]` which does not seem to work at all.

It would be good, if the administrator could just provide certificate paths once and refer to them by keys/stores.
