### ISSUE TITLE
Dashboard should not require content type detection being enabled

### ISSUE THREAD

**Issue by SuperSandro2000** [containous/traefik#6636]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I disabled content type detection on my https entrypoint via the middleware:

````yaml
http:
  middlewares:
    content-type:
      contentType:
        autoDetect: false

entryPoints:
  https:
    address: :443
    http:
      middlewares:
        - content-type
````

### What did you expect to see?

The dashboard should continue to work like normal.

### What did you see instead?

An empty page in Firefox with those errors:

```
The script from “https://traefik.domain.com/dashboard/js/app.3d96daf8.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dashboard
The script from “https://traefik.domain.com/dashboard/js/vendor.db0a5ec5.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dashboard
The stylesheet https://traefik.domain.com/dashboard/css/app.03db6149.css was not loaded because its MIME type, “text/plain”, is not “text/css”. dashboard
The script from “https://traefik.domain.com/dashboard/js/2b31cb68.2273be09.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dashboard
The script from “https://traefik.domain.com/dashboard/js/d2880142.1586712d.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dashboard
The stylesheet https://traefik.domain.com/dashboard/css/d2880142.dd7c0af2.css was not loaded because its MIME type, “text/plain”, is not “text/css”. dashboard
```

and a totally broken page in Chrome which was unthemed and threw those errors:

```
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "<URL>".
traefik.domain.com/:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://traefik.domain.com/dashboard/css/app.03db6149.css".
app.3d96daf8.js:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://traefik.domain.com/dashboard/css/2b31cb68.b69a4f0a.css".
app.3d96daf8.js:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://traefik.domain.com/dashboard/css/dba10db0.350172b4.css".
app.3d96daf8.js:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://domain.com/dashboard/css/491024e9.9b22e80f.css".
app.3d96daf8.js:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://traefik.domain.com/dashboard/css/3a710895.59fd009c.css".
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik in Docker with yaml file and docker provider

**Comment by rtribotte** [comment]
Hello @SuperSandro2000,

I tried this docker-compose file:
```
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.middlewares=content-type@docker
      - --log.level=DEBUG
      - --api
      - --api.dashboard=true
      - --providers.docker.exposedbydefault=false
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.content-type.contenttype.autodetect: false
    ports:
      - '443:443'
```
But, i was not able to reproduce your issue.

**Comment by SuperSandro2000** [comment]
I dug some further into the problem as I couldn't reproduce it with the above example.
It turns out that when you disable content type detection and enable compress on the entrypoint I get the bug I described in the first post. I used the docker-compose.yml from below and when I visited ``https://localhost:4433/`` in Chrome 80 I got the content type mismatch.

````
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.0
    ports:
      - 4433:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.middlewares=content-type@docker,compress@docker
      - --api
      - --providers.docker.exposedbydefault=false
    labels:
      traefik.enable: true

      traefik.http.routers.traefik.rule: Host(`localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal

      traefik.http.middlewares.content-type.contenttype.autodetect: false
      traefik.http.middlewares.compress.compress: true
````

**Comment by R-VdP** [comment]
I ran into this exact issue today.
Any hope to get this fixed any time soon?

**Comment by Yggdrasil** [comment]
I ran into this as well (on Kubernetes with Traefik v2.8.1).

According to https://doc.traefik.io/traefik/middlewares/http/contenttype/ Traefik's default behavior in the future will probably be to not autodetect the content-type. We use a set of default middlewares that includes the `autoDetect` and the `compress` middlewares, which breaks the Dashboard.

**Comment by maxlerebourg** [comment]
Please fix it, when you set Middleware on the entrypoint level, and specifically on traefik 3 (which has not `autoDetect` feature), the dashboard has just no content-type, and it's break the webUI.

**Comment by maxlerebourg** [comment]
```
---
version: '3.8'

services:
  traefik:
    image: traefik:v3.0.0-beta2
    command:
      - --api.insecure
      - --serversTransport.insecureSkipVerify
      - --entrypoints.web.address=:80
      - --entrypoints.web.asDefault
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.middlewares=crowdsec@docker
      - --entrypoints.websecure.http.tls.certresolver=cloudflare

      - --providers.docker
      - --providers.docker.swarmmode
      - --providers.docker.network=exnet
      - --providers.docker.defaultRule=Host(`{{ (split "-" .Name)._1 }}.max.lan`)

      - --providers.nomad
      - --providers.nomad.endpoint.address=http://nomad.max.lan:4646
      - --providers.nomad.stale
      - --providers.nomad.defaultRule=Host(`{{ .Name }}.max.lan`)

      - --certificatesresolvers.cloudflare.acme.dnschallenge
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=myemail@mail.com
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json

      - --experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - --experimental.plugins.bouncer.version=v1.1.10
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    environment:
      CF_DNS_API_TOKEN: cloudflare_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik:/var/log/traefik
      - /opt/traefik/certificats:/letsencrypt
    deploy:
      labels:
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik-http.rule=Host(`traefik.max.lan`)
        - traefik.http.routers.traefik-http.entrypoints=web
        - traefik.http.routers.traefik-https.rule=Host(`traefik.max.com`)
        - traefik.http.routers.traefik-https.entrypoints=websecure
        - traefik.http.routers.traefik-https.middlewares=autodetect@docker

        - traefik.http.middlewares.autodetect.contenttype=true

        - traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true
        - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecMode=alone
        - ...
      placement:
        constraints:
          - node.role == manager
    networks:
      - exnet
```

The dashboard is available on traefik.max.lan but not on the traefik.max.com.

In the console, I have `The ressource at address "https://traefik.max.com/.../tatata.js" has been bloqued because incorrect MIME type ("text/plain") (X-Content-Type-Options: nosniff). `.
My other apps have not this problem.
When I don't use the contentType middleware, I don't have any content-type and the "same" problem appear.

**Comment by rtribotte** [comment]
Hello @maxlerebourg,

Unfortunately, I tried to reproduce the problem without success. I used this minimal docker-compose:
```yml
version: '3.8'

services:
  traefik:
    image: traefik:v3.0.0-beta2
    command:
      - --api.insecure
      - --entrypoints.web.address=:80
      - --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-http.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.traefik-http.middlewares=autodetect
      - traefik.http.middlewares.autodetect.contenttype=true
```

Have you tried to expose the dashboard directly with the internal service? It is the recommended way.
```yml
- traefik.http.routers.traefik-http.service=api@internal
```

If the problem persists, can you please provide a more minimal docker-compose file?
