### ISSUE TITLE
Basic Auth with HTTPS redirect

### ISSUE THREAD

**Issue by nicedevil007** [containous/traefik#6639]
Hey guys,

I just want to achieve the Basic Auth with HTTPS redirect with an LE certificate.
Traefik is used for multiple sites in my docker environment and I only need the basic authentication on one service.

I'm at this point where I access the webpage but no HTTP authentication window opens.

Here is a part of my traefik.toml (just want to configure most of it in the labels section):

```
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
```

Here is my docker stack file of traefik itself:

```
volumes:
  data:
  letsencrypt:

networks:
  backend:
    attachable: true

services:
  app:
    image: traefik:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/etc/traefik
      - letsencrypt:/letsencrypt
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    networks:
      backend:
    ports:
      - 80:80/tcp
      - 443:443/tcp
```

And here is my example of a not working HTTPS + Basic Auth stack:

```
version: '3.7'

networks:
  backend:
    external: true
    name: traefik_backend

services:
  app:
    hostname: hello
    image: nginxdemos/hello
    restart: unless-stopped
    networks:
      backend:
    environment:
      TZ: Europe/Berlin
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_backend
      traefik.http.routers.test.entrypoints: http
      traefik.http.routers.test.rule: Host(`<DOMAIN>`)
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.routers.test.middlewares: https-redirect
      traefik.http.routers.test-secure.entrypoints: https
      traefik.http.routers.test-secure.rule: Host(`<DOMAIN>`)
      traefik.http.routers.test-secure.tls: "true"
      traefik.http.routers.test-secure.tls.certresolver: le
      traefik.http.routers.test-secure.service: test
      traefik.http.services.test.loadbalancer.server.port: 80
      traefik.http.middlewares.test-auth.basicauth.users: test:$$apr1$$xv8765sd$$5tK5JhjgW3qUEV6S4sC371
```

Can anyone tell me what am I doing wrong? I'm realy new in understanding traefik :/
