### ISSUE TITLE
Global HTTP to HTTPS redirection port is not configurable and redirects to unwanted port

### ISSUE THREAD

**Issue by den-is** [containous/traefik#6640]
Enabling global HTTP to HTTPS (web to websecure) redirects to default port configured in chart for websecure which is **[8443](https://github.com/containous/traefik-helm-chart/blob/6736a31626381a6bc769dc4f1e7e08d1d5a3e0a3/traefik/values.yaml#L97)**.

I see that there is Middleware option for [Redirect port](https://docs.traefik.io/middlewares/redirectscheme/#port) configuration.

Is it possible to have CLI flag too?
That will make configuration lightweight, working out of the box and prevent the creation of Middleware objects.

Something like: `--entrypoints.web.http.redirections.port=32443`

--------
My setup:
traefik 2.2.0 on KubernetesCRD on bare-metal
Installed using [official helm chart](https://github.com/containous/traefik-helm-chart/tree/master/traefik)

config
```yaml
image:
  tag: 2.2.0
service:
  type: NodePort
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  # for lab purposes
  traefik:
    expose: true
    nodePort: 32666
additionalArguments:
- --entrypoints.web.http.redirections.entryPoint.to=websecure
- --entrypoints.web.http.redirections.entryPoint.scheme=https
```
