### ISSUE TITLE
two ingress hosts for one kuberntes service not work

### ISSUE THREAD

**Issue by kong62** [containous/traefik#6646]
Do you want to request a feature or report a bug?
Bug

What did you do?
when I set two hosts: ka.sit.hupu.io and kibana-ingress-sit to one kubernetes service kibana, it not working. when use one of them, it work ok.
```
# cat kibana-ingress.yaml                 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: kibana-ingress
  namespace: sit
spec:
  rules:
  - host: ka.sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 5601
        path: /

# cat kibana-ingress-sit.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: kibana-ingress-sit
  namespace: sit
spec:
  rules:
  - host: ka-sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 5601
        path: /
```

Output of traefik version: (What version of Traefik are you using?)
Version:      2.1.6
