### ISSUE TITLE
Entrypoint redirection not working properly

### ISSUE THREAD

**Issue by jctiru** [containous/traefik#6651]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Setup general redirection in traefik (docker-compose.yml).
Reference: [Traefik entrypoints redirection](https://docs.traefik.io/routing/entrypoints/#redirection)
```yaml
services:
  reverse-proxy:
    image: traefik:v2.2
    networks:
      - proxy
    command:
      - --providers.docker=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entryPoints.websecure.address=:443
```

### What did you expect to see?
The redirection should happen in all routes using entrypoint web.

### What did you see instead?
The redirection behavior is unpredictable.
Take the following as example:
```yaml
version: "3"

services:
  reverse-proxy:
    image: traefik:v2.2
    networks:
      - mynetwork
      - anothernetwork
    command:
      - --providers.docker=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # HTTP
      - "traefik.http.routers.api-web.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api-web.entrypoints=web"
      - "traefik.http.routers.api-web.service=api@internal"
      - "traefik.http.routers.api-web.middlewares=traefik-auth"
      # Https
      - "traefik.http.routers.api-websecure.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api-websecure.entrypoints=websecure"
      - "traefik.http.routers.api-websecure.service=api@internal"
      - "traefik.http.routers.api-websecure.tls=true"
      - "traefik.http.routers.api-websecure.middlewares=traefik-auth"
      # Middleware
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$2y$$12$$X.JPA33qju8CzNG7g/HF6O0p8wFM96wiZSnQFaXrRM03Pg1mcYMiW"
  hello:
    image: crccheck/hello-world
    networks:
      - mynetwork
    labels:
      # HTTP
      - "traefik.http.routers.hello.rule=Host(`h.localhost`)"
      - "traefik.http.routers.hello.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.hello-websecure.rule=Host(`h.localhost`)"
      - "traefik.http.routers.hello-websecure.entrypoints=websecure"
      - "traefik.http.routers.hello-websecure.tls=true" 
  hello-another:
    image: crccheck/hello-world
    networks:
      - anothernetwork
    labels:
      # HTTP
      - "traefik.http.routers.hello-another.rule=Host(`hello-another.localhost`)"
      - "traefik.http.routers.hello-another.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.hello-another-websecure.rule=Host(`hello-another.localhost`)"
      - "traefik.http.routers.hello-another-websecure.entrypoints=websecure"
      - "traefik.http.routers.hello-another-websecure.tls=true"

networks:
  mynetwork:
    driver: bridge
  anothernetwork:
    driver: bridge

```
I have 3 services (referring to docker-compose.yml): reverse-proxy, hello and hello-another. 

If you randomly comment out the services blocks (on reverse-proxy service just comment out the labels portion) sometimes the redirection happens on some services while on other does not or sometimes does not happen at all.

I tried different setups, like commenting out reverse-proxy or hello or hello-another or combination of both. I tried documenting if specific combinations triggers or not trigger the redirection but found out that the same combination on later tests does not have consistent results. Testing just included multiple `docker-compose up` and `docker-compose down`.

I also tried experimenting on the routers rule length priority (Reference: [Routers priority](https://docs.traefik.io/routing/routers/#priority)). When I look at the dashboard, the general redirection creates another router with rule of ``HostRegexp(`{host:.+}`)``. This rule has priority of 23. I thought on my earlier tests this has an effect, in which it had like changing the rule ``Host(`h.localhost`)`` to ``Host(`hello.localhost`)`` (same 23 priority but looks like still 'overrides' the 23 priority of ``HostRegexp(`{host:.+}`)``. I thought this was the reason why the redirection doesn't happen (rules with higher priority, 23 or more, will match instead of the general redirection rule of ``HostRegexp(`{host:.+}`)``). But later tests of including/excluding services I found out that the routers rule length priority theory doesn't work consistently.

The only workaround for the general redirection to work is to remove/comment out the http portions (see the docker-compose.yml above) of the services. This will always trigger the router rule of ``HostRegexp(`{host:.+}`)`` when visiting the web entrypoint.

On a side note, you must not escape the $ signs in the hashed password of BasicAuth middleware (Reference: [BasicAuth Middleware](https://docs.traefik.io/middlewares/basicauth/)) if using Dockerrun.aws.json (ECS) for AWS Elastic Beanstalk. Just found out in the logs of traefik in the EC2 instance that the hashed password retained the double $ signs if you escaped them, thus the username-password pair won't work.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```
