### ISSUE TITLE
Traefik v2.2 dockerswarm.rocks consul bug

### ISSUE THREAD

**Issue by amarCosmospace** [containous/traefik#6655]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Updated traefik to v2.2 from 1.7 using consul from 0

### What did you expect to see?

See traefik interface

### What did you see instead?

Connexion refused and this error in logs

```
manager_traefik.1.mblzdzh75yjx@portainer-master-1 | time="2020-03-22T14:57:25Z" level=error msg="KV connection error: Key not found in store, retrying in 1.4470032s" providerName=consul
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Used this compose file https://github.com/tiangolo/dockerswarm.rocks/blob/master/docs/traefik.yml

Docker swarm docker engine 19.x

**Comment by ldez** [comment]
Hello,

dockerswarm.rocks use Traefik v1.

Traefik v1 configuration is not compatible with Traefik v2.

**Comment by amarCosmospace** [comment]
As i said i migrated it to use traefik v2.2 here is the compose file migrated
```
version: '3.7'

services:
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap-expect=1 -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.adminsecblog.rule=Host(`consul.front.sw.aze.fr`)"
        - "traefik.http.routers.adminsecblog.entrypoints=https"
        - "traefik.http.services.adminsecblog.loadbalancer.server.port=8500"
        - "traefik.http.routers.adminsecblog.tls.certresolver=certbot"
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.id
  traefik:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        # v2.1
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        # Http
        - "traefik.http.routers.traefik.rule=Host(`traefik.tools.sw.aze.fr`)"
        - "traefik.http.routers.traefik.entrypoints=http,https"
        # Enable Let's encrypt auto certificat creation
        - "traefik.http.routers.traefik.tls.certresolver=certbot"
        # Enable authentification
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=amar:$$apr1$$QdA7DpDg$$1H5uRRBnZdhbI9NwLThmX."
        # Redirect All hosts to HTTPS
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=http"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.tls"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true # set to 'false' on production
      - --api.dashboard=true # see https://docs.traefik.io/v2.0/operations/dashboard/#secure-mode for how to secure the dashboard
      - --api.debug=true # enable additional endpoints for debugging and profiling
      - --log.level=DEBUG # debug while we get it working, for more levels/info see https://docs.traefik.io/observability/logs/
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-public
      - --providers.consulcatalog=true
      - --providers.consulcatalog.endpoint.address=http://consul-leader:8500
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      - --certificatesResolvers.certbot=true
      - --certificatesResolvers.certbot.acme.httpChallenge=true
      - --certificatesResolvers.certbot.acme.httpChallenge.entrypoint=http
      - --certificatesResolvers.certbot.acme.email=web@aze.com
      - --certificatesResolvers.certbot.acme.storage=/letsencrypt/acme.json
      - --serversTransport.forwardingTimeouts.dialTimeout=3s
    networks:
      - default
      - traefik-public
    depends_on:
      - consul-leader

volumes:
  consul-data-leader:
  consul-data-replica:

networks:
  traefik-public:
    external: true
```
