### ISSUE TITLE
Chaining multiple ipwhitelist middlewares (and others?) does not work as expected

### ISSUE THREAD

**Issue by rhtenhove** [containous/traefik#6662]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

I have several ipwhitelists for different IPs and IP ranges. I want to combine some whitelists for some containers. For that reason I added two whitelist middlewares to a docker label list. This resulted in all IPs being blacklisted.
Then I tried to use a Chain, but that had the same result. I assume because that just does the same thing, but less verbose.

### What did you expect to see?
I expected to have the ip sourceranges combined to whitelist all defined addresses.

### What did you see instead?
Instead, everything is blacklisted. Not even the first or last entry is whitelisted. Even though the debug logs (see below) state that both whitelists have been created. No errors or anything peculiar.

Also the dashboard happily reports that both whitelists exist and are successful.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker version 19.03.8, build afacb8b7f0

`traefik.yaml`
```yaml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
file:
    filename: /etc/traefik/traefikfile.yaml
```

`traefikfile.yaml`
```yaml
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: "https"
        permanent: true
  routers:
    redirect-http:
      entryPoints: ["http"]
      rule: "hostregexp(`{host:.+}`)"
      middlewares: ["https-redirect"]
      service: "dummy"
  services:
    dummy:
      loadBalancer:
        servers:
        - url: ""

tls:
  certResolver: default
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      sniStrict: true
```

Labels on container
```yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.container.rule=Host(`a.fancy.site`)
      - traefik.http.routers.container.tls=true
      - traefik.http.routers.container.middlewares=a-whitelist,b-whitelist
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-04-11T18:05:56+02:00" level=debug msg="Creating middleware" entryPointName=http routerName=container@docker middlewareName=a-whitelist@docker middlewareType=IPWhiteLister
time="2020-04-11T18:05:56+02:00" level=debug msg="Setting up IPWhiteLister with sourceRange: [1.2.3.4]" middlewareName=a-whitelist@docker middlewareType=IPWhiteLister entryPointName=http routerName=container@docker
time="2020-04-11T18:05:56+02:00" level=debug msg="Adding tracing to middleware" entryPointName=http routerName=container@docker middlewareName=a-whitelist@docker
time="2020-04-11T18:05:56+02:00" level=debug msg="Creating middleware" routerName=container@docker middlewareType=IPWhiteLister middlewareName=b-whitelist@docker entryPointName=http
time="2020-04-11T18:05:56+02:00" level=debug msg="Setting up IPWhiteLister with sourceRange: [5.6.7.8]" entryPointName=http routerName=container@docker middlewareType=IPWhiteLister middlewareName=b-whitelist@docker
time="2020-04-11T18:05:56+02:00" level=debug msg="Adding tracing to middleware" routerName=container@docker middlewareName=b-whitelist@docker entryPointName=http
```

This is similar to #5538 yet that issue only addresses headers. Perhaps the Chain or Middlewares page could use a list of middleware types that can used multiple times for the same router, if any.
