### ISSUE TITLE
Missing cors header on preflight request

### ISSUE THREAD

**Issue by agravelot** [containous/traefik#6665]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to move my cors logic into traaefik, to avoid to maintain it in my codebase. But i'm facing an unwanted issue with preflight.

### What did you expect to see?

I expect traefik to return preflight request with defined cors headers.

```
HTTP/2 200
access-control-allow-headers: AUTHORIZATION
access-control-allow-methods: GET
access-control-allow-origin: <url>
cache-control: max-age=0
content-type: text/html; charset=UTF-8
date: Sun, 12 Apr 2020 10:00:37 GMT
expires: Sun, 12 Apr 2020 10:00:37 GMT
referrer-policy: same-origin
server: nginx
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

### What did you see instead?

```
HTTP/2 200
content-length: 0
date: Sun, 12 Apr 2020 09:54:50 GMT
```

Also note the request is not forwarded to nginx backend, it's what i expect to see. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: '3.7'
services:

  nginx:
    image: <placeholder>:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    restart: unless-stopped
    expose:
      - 80
    networks:
      - nginx-proxy
      - backend
    environment:
      NGINX_HOST: ${APP_URI}
      ERROR_LOG_LEVEL: ${ERROR_LOG_LEVEL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-insecure.rule=Host(`${APP_URI}`) || Host(`www.${APP_URI}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-insecure.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-insecure.middlewares=${COMPOSE_PROJECT_NAME}-https-only,${COMPOSE_PROJECT_NAME}-ratelimit,${COMPOSE_PROJECT_NAME}-headers,${COMPOSE_PROJECT_NAME}-compress"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${APP_URI}`) || Host(`www.${APP_URI}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}-https-only,${COMPOSE_PROJECT_NAME}-ratelimit,${COMPOSE_PROJECT_NAME}-retry,${COMPOSE_PROJECT_NAME}-error-check,${COMPOSE_PROJECT_NAME}-headers,${COMPOSE_PROJECT_NAME}-compress"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT,PATCH,DELETE"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlMaxAge=63072000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowHeaders=Authorization,Origin,Content-Type,Accept"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.addVaryHeader=true"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.sslProxyHeaders=https"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-compress.compress=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-only.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-only.redirectscheme.permanent=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-retry.retry.attempts=4"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-error-check.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.30 || NetworkErrorRatio() > 0.10"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-limit.buffering.maxRequestBodyBytes=20000000" # 20 Mb
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-limit.buffering.memResponseBodyBytes=20000000" # 20 Mb
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-ratelimit.ratelimit.average=1000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-ratelimit.ratelimit.burst=500"

networks:
  backend:
  nginx-proxy:
    external: true
  database-network:
    external: true
```

```yaml
global:
  checkNewVersion: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

providers:
  docker:
    exposedByDefault: false
    network: nginx-proxy

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  myhttpchallenge:
    acme:
      email: <email>
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        # https://ssl-config.mozilla.org/#server=traefik&version=2.1.2&config=intermediate&guideline=5.4
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    mintls13:
      minVersion: VersionTLS13
```

My issue looks like this one : https://community.containo.us/t/problem-with-headers-probably-forwarding/1804/13
