### ISSUE TITLE
Default router configurations/middlewares doesn't work with consul catalog

### ISSUE THREAD

**Issue by saideeptalari** [containous/traefik#6666]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I tried to use default middleware functionality as mentioned in the blog post, using the consul catalog as a provider so that I don't have to manually add tags on each consul instance.
https://containo.us/blog/traefik-2-2-ingress/

### What did you expect to see?

All the routers that are registered either directly using file provider or automatically using the consul catalog as a provider should use the defined middleware as is instead of modifying the middleware name being queried.

### What did you see instead?
The middleware that is looked up as middleware@provider instead of using the middleware directly.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]
    insecure = true
    debug = true

[http.middlewares]
  [http.middlewares.usersData.forwardAuth]
    address = "https://example.com/auth"

[entryPoints.web.http]
    middlewares=["usersData"]

[providers.consulCatalog]
    refreshInterval = "2s"
    exposedByDefault = true    
    [providers.consulCatalog.endpoint]
        address = "XXXXXX"
        token = "XXXXXX"
        scheme = "https"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
ERRO[2020-04-12T18:44:08+05:30] middleware "usersData@consulcatalog" does not exist  routerName=consul@consulcatalog entryPointName=web
ERRO[2020-04-12T18:44:08+05:30] middleware "usersData@consulcatalog" does not exist  entryPointName=web routerName=web@consulcatalog
ERRO[2020-04-12T18:44:10+05:30] middleware "usersData@consulcatalog" does not exist  entryPointName=web routerName=web@consulcatalog
ERRO[2020-04-12T18:44:10+05:30] middleware "usersData@consulcatalog" does not exist  entryPointName=web routerName=consul@consulcatalog
ERRO[2020-04-12T18:44:12+05:30] middleware "usersData@consulcatalog" does not exist  entryPointName=web routerName=consul@consulcatalog
ERRO[2020-04-12T18:44:12+05:30] middleware "usersData@consulcatalog" does not exist  entryPointName=web routerName=web@consulcatalog
ERRO[2020-04-12T18:44:14+05:30] middleware "usersData@consulcatalog" does not exist  entryPointName=web routerName=consul@consulcatalog
```
