### ISSUE TITLE
Traefik 2.2 middleware annotations on K8s ingress is never found

### ISSUE THREAD

**Issue by lucas-dehandschutter** [containous/traefik#6674]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
**Traefik service:**

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: tf

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: tf
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      namespace: tf  
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            - --log.level=DEBUG
            - --api
            - --api.insecure
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress=true
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: tf
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      nodePort: 32200
    - protocol: TCP
      port: 8080
      name: admin
      nodePort: 32201
```
**ClusterRole:**

```
---
  kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: traefik-ingress-controller
  rules:
    - apiGroups:
        - ""
      resources:
        - services
        - endpoints
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - ingresses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - ingresses/status
      verbs:
        - update
    - apiGroups:
       - traefik.containo.us
      resources:
        - middlewares
        - ingressroutes
        - traefikservices
        - ingressroutetcps
        - ingressrouteudps
        - tlsoptions
        - tlsstores
      verbs:
        - get
        - list
        - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: tf
    apiGroup: ""
```

**Middleware:**

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-security-headers
  namespace: tf
spec:
  headers:
    frameDeny: "true"
    contentTypeNosniff: "true"
    browserXssFilter: "true"
```
**Ingress:**

```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: myingress
  namespace: tf
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: traefik-security-headers
spec:
  rules:
    - http:
        paths:
          - path: /bar
            backend:
              serviceName: whoami
              servicePort: 80
          - path: /foo
            backend:
              serviceName: whoami
              servicePort: 80
```

The middleware is never detected. I tried with several providers:
traefik.ingress.kubernetes.io/router.middlewares: traefik-security-headers@tf
traefik.ingress.kubernetes.io/router.middlewares: traefik-security-headers@kubernetesrcd

### What did you expect to see?

My routes with the Middleware correctly applied to them

### What did you see instead?

![traefik](https://user-images.githubusercontent.com/3309863/79140530-6d559080-7db8-11ea-9e8c-c0de86db0e25.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-04-13T16:57:50Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:50Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:50Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:52Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:52Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:52Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:52Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:54Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:54Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:54Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:54Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:56Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:56Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:56Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:56Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:58Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:58Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:57:58Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:57:58Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:58:00Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:58:00Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:58:00Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:58:00Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:58:02Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:58:02Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-04-13T16:58:02Z" level=warning msg="Ingress tf/myingress: the apiVersion 'extensions/v1beta1' is deprecated, use 'networking.k8s.io/v1beta1' instead."
time="2020-04-13T16:58:02Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
```
