### ISSUE TITLE
CORS headers do not appear in the response

### ISSUE THREAD

**Issue by romch007** [containous/traefik#6676]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I added a middleware to a router to add CORS headers to the response, but they are not in the response.

### What did you expect to see?
```
HTTP/1.1 200 OK
Content-Length: 49
Content-Type: application/json; charset=utf-8
Date: Tue, 14 Apr 2020 06:33:43 GMT
Etag: W/"31-r56sounC0/LocNH9xvpta7B0NcA"
Vary: Accept-Encoding
X-Powered-By: Express
Access-Control-Allow-Origin: https://example.org
Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
``` 

### What did you see instead?
```
HTTP/1.1 200 Ok
Content-Length: 49
Content-Type: application/json; charset=utf-8
Date: Tue, 14 Apr 2020 06:33:43 GMT
Etag: W/"31-r56sounC0/LocNH9xvpta7B0NcA"
Vary: Accept-Encoding
X-Powered-By: Express
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
middlewares.toml :
```toml
[http]
  [http.middlewares]
    [http.middlewares.compression.compress]

    [http.middlewares.redirection.redirectscheme]
      scheme = "https"
      permanent = true
    [http.middlewares.limit.ratelimit]
      average = 100
      burst = 500
    [http.middlewares.cors.headers]
      accessControlAllowMethods= ["GET", "OPTIONS", "POST", "HEAD"]
      accessControlAllowOriginList = ["https://example.org"]
      accessControlMaxAge = 100
      addVaryHeader = true
```
docker-compose.yml :
```yaml
api:
    labels:
      ...
      - "traefik.http.routers.rest-api-s.middlewares=compression@file,limit@file,cors@file"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
proxy_1     | time="2020-04-14T06:44:21Z" level=debug msg="Creating Middleware (ResponseModifier)" entryPointName=websecure middlewareType=Headers routerName=rest-api-s@docker middlewareName=cors@file
proxy_1     | time="2020-04-14T06:44:21Z" level=debug msg="Creating middleware" routerName=rest-api-s@docker middlewareName=cors@file middlewareType=Headers entryPointName=websecure
proxy_1     | time="2020-04-14T06:44:21Z" level=debug msg="Setting up customHeaders/Cors from %v{map[] map[] false [] [GET OPTIONS POST HEAD]  [https://example.org] [] 100 false [] [] false false  map[] false 0 false false false false  false false      false}" entryPointName=websecure routerName=rest-api-s@docker middlewareName=cors@file middlewareType=Headers
proxy_1     | time="2020-04-14T06:44:21Z" level=debug msg="Adding tracing to middleware" routerName=rest-api-s@docker entryPointName=websecure middlewareName=cors@file
```

**Comment by romch007** [comment]
I'm not sure what I did but now it works.

**Comment by numToStr** [comment]
I am facing the similar issue. @romch007 How do you fixed it?

 ## Here are my configs:
middlewares.yaml

```yaml
http:
  middlewares:
    for-dev:
      chain:
        middlewares:
          - compress-it
          - cors-headers
          - security-headers
          - cache-headers
    compress-it:
      compress: {}
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        browserXssFilter: true
        stsSeconds: 15552000
        forceSTSHeader: true
    cors-headers:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        accessControlAllowMethods:
          - OPTION
          - GET
          - POST
          - PUT
          - PATCH
        accessControlAllowOriginList:
          - http://example.com
        accessControlMaxAge: 100
        addVaryHeader: true
    cache-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "no-cache, max-age=0"
```
docker-compose.yaml
```yaml
backend:
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.middlewares=for-dev@file"
```
HTTP Response
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Cache-Control: no-cache, max-age=0
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Sun, 26 Apr 2020 06:42:30 GMT
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=15552000
Vary: Accept-Encoding
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
```
