### ISSUE TITLE
Ping resulting in 503 http code during graceful shutdown

### ISSUE THREAD

**Issue by L3o-pold** [containous/traefik#6688]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Request shutdown of traefik and wait for a livenessProbe check.

It's well documented in the [1.7](https://docs.traefik.io/v1.7/configuration/ping/#using-ping-for-external-load-balancer-rotation-health-check) doc but not in the [2.x](https://docs.traefik.io/operations/ping/).

When used in a livenessProbe in k8s an 503 http code is seen as [an error](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request).

### What did you expect to see?

200 on ping request

### What did you see instead?

503 on ping request

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[ping]
  entryPoint = "ping"
[api]
  dashboard = true

[entryPoints]
  [entryPoints.ping]
    address = ":8081"
    [entryPoints.ping.transport]
      [entryPoints.ping.transport.lifeCycle]
        requestAcceptGraceTimeout = "60s"
        graceTimeOut = "2h"
```

Kubernetes example:

```yaml
livenessProbe:
  httpGet:
    path: /ping
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 2 
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-04-16T14:10:56Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=http
time="2020-04-16T14:10:56Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-04-16T14:10:56Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-04-16T14:10:56Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=http
[16/Apr/2020:14:11:00 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 18 "ping@internal" - 0ms
[16/Apr/2020:14:11:14 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 21 "ping@internal" - 0ms
```
I don't think that's really a bug since it's documented in 1.7.x but an 503 http code is not really great IMO. Maybe we can add an option in the configuration for this to avoid breaking change.
