### ISSUE TITLE
Traefik forwarding http to elasticsearch instead of https

### ISSUE THREAD

**Issue by J7mbo** [containous/traefik#6695]
### What did you do?

I am running elasticsearch on https, deployed to docker swarm. I am running traefik on another node.
I have instructed traefik to forward calls to `https://elasticsearch.mydomain.com` to the elasticsearch container, port 9200.

Elasticsearch logs state they're **getting a http request, not a https request**:

> {"type": "server", "timestamp": "2020-04-17T12:45:36,975Z", "level": "WARN", "component": "o.e.x.s.t.n.SecurityNetty4HttpServerTransport", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/10.0.1.16:9200, remoteAddress=/10.0.1.7:58656}", "cluster.uuid": "HPiffrxgRxyiezgBkLgw4w", "node.id": "k3CoO_dgRkahF5qNnfEjlQ"  }

**Traefik logs mention they're forwarding over http as well.**

The important part of the logs:

> ForwardURL="http://10.0.1.23:9200"

The full logs:

> time="2020-04-17T12:57:47Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"elasticsearch.xpacto.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"elasticsearch.xpacto.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:50025\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-04-17T12:57:47Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"elasticsearch.xpacto.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"elasticsearch.xpacto.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:50025\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://10.0.1.23:9200"
time="2020-04-17T12:57:47Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 10.0.1.23:9200: connect: connection refused"
time="2020-04-17T12:57:47Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"elasticsearch.xpacto.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"elasticsearch.xpacto.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:50025\",\"RequestURI\":\"/\",\"TLS\":null}"

---

traefik config - wildcard certs, http->https redirect
-

```
traefik:
        image: traefik:v2.2
        hostname: ${TRAEFIK_DIGITALOCEAN_NAME}
        environment:
            - DO_AUTH_TOKEN=${DIGITALOCEAN_ACCESS_TOKEN}
        command:
            # General configuration
            - --log.level=DEBUG
            # Docker configuration
            - --providers.docker.swarmMode=true
            - --providers.docker.exposedByDefault=false
            - --providers.docker.network=${DOCKER_NETWORK_NAME}
            - --providers.docker.endpoint=tcp://socket-proxy:2375
            - --providers.docker.watch=true

            # Entrypoints
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443

            # Letsencrypt setup
            - --certificatesresolvers.letsencrypt.acme.caServer=${LETSENCRYPT_ACME_ENDPOINT}
            - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
            - --certificatesresolvers.letsencrypt.acme.storage=${TRAEFIK_HOST_VOLUME_CERTS}/acme.json
            - --certificatesresolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=15
            - --certificatesresolvers.letsencrypt.acme.dnsChallenge=true
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=digitalocean
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
        ports:
            - 80:80
            - 443:443
        networks:
            - ${DOCKER_NETWORK_NAME}
            - socket-proxy
        volumes:
            - /volumes/traefik/certs/:/volumes/traefik/certs/
        deploy:
            placement:
                constraints:
                    - node.hostname==${TRAEFIK_DIGITALOCEAN_NAME}
            labels:
                # General configuration - needs to be here for the http-catchall router to fire
                - traefik.enable=true
                - traefik.http.services.traefik.loadbalancer.server.port=80

                # Middlewares
                - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
                - traefik.http.routers.http-catchall.entrypoints=http
                - traefik.http.routers.http-catchall.middlewares=https-redirect,hsts-header
                - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
                - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
                - traefik.http.middlewares.hsts-header.headers.sslredirect=true

                 # Global wildcard certificates
                - traefik.http.routers.wildcard-certs.tls.certresolver=letsencrypt
                - traefik.http.routers.wildcard-certs.entrypoints=http
                - traefik.http.routers.wildcard-certs.tls.domains[0].main=${DOMAIN}
                - traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${DOMAIN}
```

Elasticsearch config
--

```
elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        hostname: ${ELASTICSEARCH_DIGITALOCEAN_NAME}
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - xpack.security.enabled=true
            - xpack.security.transport.ssl.enabled=true
            - xpack.security.transport.ssl.key=certs/key.pem
            - xpack.security.transport.ssl.certificate=certs/cert.pem
            - xpack.security.http.ssl.enabled=true
            - xpack.security.http.ssl.key=certs/key.pem
            - xpack.security.http.ssl.certificate=certs/cert.pem
            - "ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}"
            - "ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
            - "${ELASTICSEARCH_HOST_VOLUME_CERTS}:/usr/share/elasticsearch/config/certs"
        ports:
            - "${ELASTICSEARCH_EXPOSED_PORT}:${ELASTICSEARCH_PORT}"
        networks:
            - ${DOCKER_NETWORK_NAME}
        deploy:
            placement:
                constraints:
                    - node.hostname==${ELASTICSEARCH_DIGITALOCEAN_NAME}
            labels:
                # General configuration
                - traefik.enable=true
                - traefik.http.services.elasticsearch.loadbalancer.server.port=9200
                - traefik.http.services.elasticsearch.loadbalancer.server.scheme=https
                - traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.${DOMAIN}`)

                # Https
                - traefik.http.routers.elasticsearch.entrypoints=https
                - traefik.http.routers.elasticsearch.tls=true
                - traefik.http.routers.elasticsearch.tls.certresolver=letsencrypt
```

### What did you expect to see?

I expected to see the normal output of visiting :9200, which is some json.

### What did you see instead?

Instead I get **Bad Gateway** in my browser and the above logs.

### Output of `traefik version`:

```
traefik:v2.2
```
