### ISSUE TITLE
Forwardauth middleware not working with tls passthrough

### ISSUE THREAD

**Issue by J7mbo** [containous/traefik#6700]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

**Overview**
When forwardauth is set along with tls passthrough, the forwardauth middleware is ignored and I am forwarded straight through to the website without the auth being triggered in the middle.

**Use-case - whoami is working** *(whoami is **http** on the backend)*
I'm using [authelia](https://github.com/authelia/authelia). **With a http whoami example, it works perfectly** - I can visit `https://whoami.mydomain.com` and I am first forwarded to `https://login.mydomain.com` where I have to authenticate, before being forwarded on to the whoami container.

*Note that whoami has a letsencrypt certificate for `https://whoami.mydomain.com`, but does not require TLS on the backend because it's just running on port 80, http, which is why no tls passthrough is needed.*

**Use-case - kibana is not working** *(kibana is **https** on the backend)*

I set up `https://kibana.mydomain.com`. Without a middleware, visiting this url forwards me to the kibana login as expected and it works.

However, when using the authentication middleware, I get a "bad certificate error" on the backend, and this is likely because tls passthrough needs to be enabled and I can't load Kibana.

When I enable tls passthrough on the tcp router for kibana, authelia is skipped entirely and I am forwarded straight to `https://kibana.mydomain.com` which loads correctly, without the authenticate middleware being executed!

### What did you expect to see?

I expected to see `https://login.mydomain.com`.

### What did you see instead?

I saw `https://kibana.mydomain.com`, without any authentication being required as expected from the middleware. TLS passthrough is interfering with the middleware.

### Output of `traefik version`:

```
traefik:v2.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- MacOS
- Docker swarm - one node has traefik and authelia, the other has kibana

*Note: the traefik, authelia and whoami configurations work perfectly together. The issue is with kibana which I have placed at the end.*

traefik docker-compose
---

```
traefik:
        image: traefik:v2.2
        hostname: traefik
        environment:
            - DO_AUTH_TOKEN=ABC
        command:
            # Docker configuration
            - --providers.docker.swarmMode=true
            - --providers.docker.exposedByDefault=false
            - --providers.docker.network=network
            - --providers.docker.endpoint=tcp://socket-proxy:2375
            - --providers.docker.watch=true

            # Entrypoints
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443

            # Letsencrypt setup
            - --certificatesresolvers.letsencrypt.acme.caServer=${LETSENCRYPT_ACME_ENDPOINT}
            - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
            - --certificatesresolvers.letsencrypt.acme.storage=${TRAEFIK_HOST_VOLUME_CERTS}/acme.json
            - --certificatesresolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=15
            - --certificatesresolvers.letsencrypt.acme.dnsChallenge=true
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=digitalocean
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
        ports:
            - 80:80
            - 443:443
        networks:
            - network
            - socket-proxy
        volumes:
            - /volumes/traefik/certs/:/volumes/traefik/certs/
        deploy:
            placement:
                constraints:
                    - node.hostname==${TRAEFIK_DIGITALOCEAN_NAME}
            labels:
                # General configuration - needs to be here for the http-catchall router to fire
                - traefik.enable=true
                - traefik.http.services.traefik.loadbalancer.server.port=80

                # Middlewares
                - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
                - traefik.http.routers.http-catchall.entrypoints=http
                - traefik.http.routers.http-catchall.middlewares=https-redirect,hsts-header
                - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
                - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
                - traefik.http.middlewares.hsts-header.headers.sslredirect=true

                 # Global wildcard certificates
                - traefik.http.routers.wildcard-certs.tls.certresolver=letsencrypt
                - traefik.http.routers.wildcard-certs.entrypoints=http
                - traefik.http.routers.wildcard-certs.tls.domains[0].main=${DOMAIN}
                - traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${DOMAIN}
```

authelia docker-compose
--

```
authelia:
        image: authelia/authelia
        hostname: traefik
        environment:
            - TZ=Europe/Madrid
        ports:
            - 9091:9091
        volumes:
            - /volumes/authelia:/etc/authelia/
        networks:
            - network
        deploy:
            labels:
                # General configuration
                - traefik.enable=true
                - traefik.http.services.authelia.loadbalancer.server.port=9091
                - traefik.http.routers.authelia.rule=Host(`login.${DOMAIN}`)

                # Https
                - traefik.http.routers.authelia.entrypoints=https
                - traefik.http.routers.authelia.tls=true
                - traefik.http.routers.authelia.tls.certresolver=letsencrypt

                # Middleware
                - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN}/
                - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
                - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'
```

whoami docker-compose (works perfectly)
--

```
whoami:
        image: "containous/whoami"
        hostname: traefik
        networks:
            - network
        deploy:
            labels:
                # General configuration
                - traefik.enable=true
                - traefik.http.services.whoami.loadbalancer.server.port=80

                # Https
                - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
                - traefik.http.routers.whoami.entrypoints=https
                - traefik.http.routers.whoami.tls=true
                - traefik.http.routers.whoami.tls.certresolver=letsencrypt
                - traefik.http.routers.whoami.middlewares=authelia@docker
```
-----

kibana docker-compose
--

```
kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        hostname: ${KIBANA_DIGITALOCEAN_NAME}
        environment:
            # General configuration
            - SERVER_NAME=kibana.${DOMAIN}
            - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
            - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true

            # Https in the browser - use wildcard letsencrypt certs
            - SERVER_SSL_ENABLED=true
            - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/cert.pem
            - SERVER_SSL_KEY=/usr/share/kibana/config/certs/key.pem

            # Https from elasticsearch certutil - use selfsigned certs
            - ELASTICSEARCH_SSL_CERTIFICATE=/usr/share/kibana/config/certs/selfsignedcert.pem
            - ELASTICSEARCH_SSL_KEY=/usr/share/kibana/config/certs/selfsignedkey.pem
            - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/selfsignedca.pem
        ports:
            - 5601:5601
        volumes:
            - "/certs:/usr/share/kibana/config/certs"
        networks:
            - network
        deploy:
            labels:
                # General configuration
                - traefik.enable=true
                - traefik.http.services.kibana.loadbalancer.server.port=5601
                - traefik.http.services.kibana.loadbalancer.server.scheme=https
                - traefik.http.routers.kibana.rule=Host(`kibana.${DOMAIN}`)

                # Passthrough TLS requires a tcp service / router
                - traefik.tcp.routers.kibana.rule=HostSNI(`kibana.${DOMAIN}`)
                - traefik.tcp.services.kibana.loadbalancer.server.port=5601
                - traefik.tcp.routers.kibana.tls.passthrough=true

                # Https
                - traefik.http.routers.kibana.entrypoints=https
                - traefik.http.routers.kibana.tls=true
                - traefik.http.routers.kibana.tls.certresolver=letsencrypt
                - traefik.http.routers.kibana.middlewares=authelia@docker
```

Important:
--
If I remove the three lines directly below `#Passthrough TLS requires a tcp service/router`, the following happens:

- Logs show what I have displayed below. *Note tls: unknown certificate is expected because I'm using letsencrypt's staging environment.*
- I am redirected to `https://login.mydomain.com`
- Kibana shows *Internal server error* and in the kibana logs (note **bad certificate**): 

**kibana logs:**
```
{"type":"error","@timestamp":"2020-04-18T23:07:27Z","tags":["connection","client","error"],"pid":6,"level":"error","error":{"message":"140035565897600:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 42\n","name":"Error","stack":"Error: 140035565897600:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 42\n"},"message":"140035565897600:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 42\n"}
```

**traefik logs:**
```
time="2020-04-18T23:03:00Z" level=debug msg="http: TLS handshake error from 10.0.0.2:50209: remote error: tls: unknown certificate"
time="2020-04-18T23:03:01Z" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://login.xpacto.com/. StatusCode: 302" middlewareType=ForwardedAuthType middlewareName=authelia@docker
time="2020-04-18T23:03:05Z" level=debug msg="http: TLS handshake error from 10.0.0.2:50224: remote error: tls: unknown certificate"
time="2020-04-18T23:04:21Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"rd=https%3A%2F%2Fkibana.xpacto.com%2F\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"login.xpacto.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"login.xpacto.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:50420\",\"RequestURI\":\"/?rd=https%3A%2F%2Fkibana.xpacto.com%2F\",\"TLS\":null}"
time="2020-04-18T23:04:21Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"rd=https%3A%2F%2Fkibana.xpacto.com%2F\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"login.xpacto.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"login.xpacto.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:50420\",\"RequestURI\":\"/?rd=https%3A%2F%2Fkibana.xpacto.com%2F\",\"TLS\":null}" ForwardURL="http://10.0.1.113:9091"
time="2020-04-18T23:04:21Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"rd=https%3A%2F%2Fkibana.xpacto.com%2F\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Cache-Control\":[\"max-age=0\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"login.xpacto.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"login.xpacto.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:50420\",\"RequestURI\":\"/?rd=https%3A%2F%2Fkibana.xpacto.com%2F\",\"TLS\":null}"
```

With the three lines directly below `#Passthrough TLS requires a tcp service/router` uncommented, the following happens:

```
time="2020-04-18T23:13:49Z" level=debug msg="Handling connection from 10.0.0.2:51833"
```

It goes right through to kibana.

**Comment by J7mbo** [comment]
Is this perhaps simply because tcp middlewares need to be supported?

I'm linking #6684 just in-case this is the reason. If it's true, am I right in thinking that, as of right now **middlewares only work with port 80 and 443 (http / https)?**... 

Were it to be implemented, would I simply need to add:

```
    - traefik.tcp.routers.kibana.middlewares=authelia@docker
```

or would I also need to remove the http one? This is of course assuming that this is the only thing missing to make this work with tls passthrough.

Is there any way I can support to have this implemented? I'm happy put in the work to do all the docs for it at the very least...

**Comment by J7mbo** [comment]
Update. I did some research. Here's what I found.

| Kibana Certs  | TLS Passthrough |  serversTransport.rootCAs  | result   |
| ------------- | ------------- | ------------- | ------------- |
| letsencrypt  | enabled  | none  | no auth, directly goes to kibana  |   
| letsencrypt  | enabled  | letsencrypt CAs | no auth, directly goes to kibana  | 
| letsencrypt  | disabled  | none | **kibana logs**:  <br> `:sslv3 alert bad certificate ... :SSL alert number 42` <br> **traefik logs**: <br> `500 Internal Server Error' caused by: x509: cannot validate certificate for 10.0.1.210 because it doesn't contain any IP SANs`  |
| letsencrypt  | disabled  | letsencrypt CAs | same as with previous (none), `sslv3` error in kibana and `x509` error in traefik | 
| self-signed  | disabled  | none | **kibana logs**: <br> `kibana: SSLv2 bad certificate` <br> **traefik logs**: <br> `'500 Internal Server Error' caused by: x509: certificate is valid for 127.0.0.1, not 10.0.1.215`  | 
| self-signed  | disabled  | self-signed | same as with previous (none), `sslv2` error in kibana and `x509` error in traefik | 
| self-signed  | enabled  | none | no auth, directly goes to kibana  | 
| self-signed  | enabled  | self-signed | no auth, directly goes to kibana  | 

---

Observations:

- Enabling `insecureSkipVerify` and passthrough enabled works fine, but I don't want to have to enable it.
- I found [this post from 2019](https://community.containo.us/t/insecureskipverify-explanation/2195/17) where someone had a similar issue.
- I took at look at [the code in addserver](https://github.com/containous/traefik/blob/v2.0.4/pkg/provider/docker/config.go#L200), and it looks like it's only using IP, not hostname, which is the reason for the error with the combination: self-signed, disabled, [none|self-signed]. I can't / shouldn't use IPs because docker will assign different IPs in a swarm, and docker swarm does not yet have static ipv4 address setting capabilities.
- Apparently [this traefik issue, #3906](https://github.com/containous/traefik/issues/3906), provided TLS passthrough with TCP to fix the X509 issue, which looks right because these only appear when TLS passthrough is disabled.
- But when I enable TLS passthrough, I go straight through to the service.

I hope that's enough information to help. From that above, to me, it really does look like a bug. Let me know if there's anything I'm missing.

**Comment by ldez** [comment]
duplicate of #6684

**Comment by J7mbo** [comment]
I solved this, but I don't know if this is a duplicate of #6684.

First I had to **disable passthrough**. The only config I have in kibana labels is now:

```
- traefik.enable=true
- traefik.http.services.kibana.loadbalancer.server.port=5601
- traefik.http.services.kibana.loadbalancer.server.scheme=https
```

I then had to use **file configuration** for kibana and the authelia middleware because only the file configuration allows to use  an address, as mentioned in one of the linked posts previously.

```
http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://login.mydomain.com/
        trustForwardHeaders: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
  services:
    kibana:
      loadBalancer:
        servers:
          - url: "https://kibana:5601"  <------ This is what I had to do here
  routers:
    kibana:
      middlewares: [authelia]
      rule: "Host(`kibana.mydomain.com`)"
      entryPoints: [https]
      service: kibana
      tls:
        certResolver: letsencrypt
```

Finally, as Kibana uses a self-signed cert in this test, I had to pass the self-signed cert in the traefik config (and of course use this file config):

```
- --providers.file.filename=/volumes/traefik/certs/config.yml
- --serverstransport.rootcas=/volumes/traefik/certs/selfsignedca.pem
```

@ldez I think this isn't a duplicate of the one we marked it as, as I haven't even used TLS passthrough. Is `servers.url` the only thing I was missing or have I unwittingly done something else?
