### ISSUE TITLE
Invalid manifest taken from somewhere: Cannot create service: service not found

### ISSUE THREAD

**Issue by zzvara** [containous/traefik#6702]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created the following manifest in order to be able to /ping Traefik from the outside.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 3.sigma.example.com
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`3.sigma.example.com`) && Path(`/ping`)
      kind: Rule
      services:
        - name: chart-1582136483-traefik
          port: 9000
  tls:
    certResolver: tls
```

Then, Treafik has been redeployed using `HelmReleases` as follows:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    git: https://github.com/containous/traefik-helm-chart.git
    path: traefik
    ref: master
  releaseName: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: false
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi
      storageClass: "ceph-replicated"
      path: /acme
      annotations: {}
    rollingUpdate:
      maxUnavailable: 0
    additionalArguments:
      - "--providers.kubernetesingress"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge.delaybeforecheck=60"
      - "--certificatesresolvers.dns-cloudflare.acme.email=redacted"
      - "--certificatesresolvers.dns-cloudflare.acme.storage=/acme/dns-cloudflare.json"
      - "--certificatesresolvers.tls.acme.tlschallenge=true"
      - "--certificatesresolvers.tls.acme.email=redacted"
      - "--certificatesresolvers.tls.acme.storage=/acme/tls.json"
    env:
      - name: CF_API_EMAIL
        value: redacted
      - name: CLOUDFLARE_API_KEY
        value: redacted
    ports:
      traefik:
        expose: true
      web:
        port: 80
        nodePort: 30080
      websecure:
        port: 443
        nodePort: 30443
    service:
      type: NodePort
```

Then, upgraded the above `IngressRoute`, since the service name is now `traefik` and not `chart-1582136483-traefik`:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 3.sigma.example.com
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`3.sigma.example.com`) && Path(`/ping`)
      kind: Rule
      services:
        - name: **traefik**
          port: 9000
  tls:
    certResolver: tls
```

The /ping works from the outside as many other services, but still getting errors about the previous `IngressRoute`:

In Traefik logs, these lines appear:
```
time="2020-04-19T15:44:16Z" level=error msg="Cannot create service: service not found" servicePort=80 providerName=kubernetes ingress=3.sigma.example.com namespace=kube-system serviceName=chart-1582136483-traefik
```

If I list all `IngressRoute`s in all namespaces and check them manually, there is no `IngressRoute` that matches the previous one that Traefik tries to create service for.
```
kubectl get ingressroute --all-namespaces
```

Then I have deleted Traefik including all CRDs and re-deployed with `HelmRelease`. `HelmRelease` re-created the CRDs and Traefik service. It works, but the same error appears about old manifests in Traefik logs. Could it be a Kubernetes issue?

### What did you expect to see?

No errors.

### What did you see instead?

Errors.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: 'traefik:2.2.0'
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
See `HelmRelease` above. All nodes are running Kubernetes 1.17.0.
```
