### ISSUE TITLE
lego: namedotcom issues wrong _acme-challenge domain

### ISSUE THREAD

**Issue by delandtj** [containous/traefik#6703]
Build: from master (as I thought it would be resolved with a later lego lib)
what happens :
name.com received a new TXT record for `_acme-challenge.domain.com`, but the Host entry was for `expl.testnet.domain.com` resulting of course in NXDOMAIN until timeout.

when copying the same TXT to a new record for `_acme-challenge.expl.testnet.domain.com` registration succeeded AND the TXT recort for `_acme-challenge.expl.testnet.domain.com` got removed AND NOT `_acme-challenge.domain.com`. I had to remove that by hand

**Comment by ldez** [comment]
Hello,

Could you open an issue on lego https://github.com/go-acme/lego

Thank you.

**Comment by delandtj** [comment]
hmmm, when using the lego command line, I get a cert all right, so could it be my own stupid mistake ?

Dyn:

```yaml
http:
  routers:
    explorer-entry:
      rule: "Host(`expltestnet.grid.tf`)"
      service: explorer
      entryPoints:
        - web-secure
      tls: 
        certResolver: letsencrypt
      domains:
        - main: "grid.tf"
          sans:
            - "*.grid.tf"
```
I dabbled around with `domains` even removed the `.testnet.grid.tf` subdomain to no avail 

Static:
```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      email: jan@incubaid.com
      storage: /etc/traefik/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge: 
        provider: namedotcom
```
