### ISSUE TITLE
Healthcheck issue v2.2

### ISSUE THREAD

**Issue by tle5** [containous/traefik#6706]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I configured dynamic setting as following:
```toml
[http.services]
  [http.services.rt0]
    [http.services.rt0.loadBalancer]
      [[http.services.rt0.loadBalancer.servers]]
          url = "http://192.168.10.42:9130/"
      [[http.services.rt0.loadBalancer.servers]]
          url = "http://192.168.10.43:9130/"
      [http.services.rt0.loadBalancer.healthCheck]
            path = "/hc"
            interval = "10s"
            timeout = "3s"
```
I started service at http://192.168.10.43:9130/
and service http://192.168.10.42:9130/ is stopped (actually it is not started)

In dashboard of rt0 service, I can see
```
DOWN http://192.168.10.42:9130/
UP  http://192.168.10.43:9130/
```

it is correct. But if I try press F5 every second in about 15 times, the service at http://192.168.10.42:9130/ is displayed as UP in 1-2 seconds and DOWN again. 

This is the screen I sometime saw it.
```
UP http://192.168.10.42:9130/
UP http://192.168.10.43:9130/
```
It is very strange, because I have never started the service at http://192.168.10.42:9130/ 

192.168.10.42 is windows server (2016). I couldn't duplicate issue in Linux.
I tried to execute curl from traefik host 
http://192.168.10.42:9130/hc 
It kept waiting for very long time. (although no service at http://192.168.10.42:9130)

It is version v2.2.0
