### ISSUE TITLE
Crash after long run

### ISSUE THREAD

**Issue by qiuyuzhou** [containous/traefik#6709]
```
goroutine 60569 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00e8aa6d8, 0x10100c000000000)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00e8aa6c8)
        /usr/local/go/src/sync/cond.go:56 +0x9d
net/http.(*http2pipe).Read(0xc00e8aa6c0, 0xc00ff80000, 0x7ffff, 0x80000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:3515 +0x8f
net/http.(*http2requestBody).Read(0xc00eea5050, 0xc00ff80000, 0x7ffff, 0x80000, 0x454a070, 0xc00fcdc570, 0x711963)
        /usr/local/go/src/net/http/h2_bundle.go:5876 +0xa0
golang.org/x/net/http2.(*clientStream).writeRequestBody(0xc00e8ffce0, 0x7f1a3dfd41c8, 0xc00eea5050, 0x7f1a3dfd41e8, 0xc00eea5050, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200301022130-244492dfa37a/http2/transport.go:1261 +0x651
golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200301022130-244492dfa37a/http2/transport.go:2519 +0xc5
created by golang.org/x/net/http2.bodyWriterState.scheduleBodyWrite
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200301022130-244492dfa37a/http2/transport.go:2566 +0xa1
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]
      certResolver = "myresolver"
      [[entryPoints.https.http.tls.domains]]
        main = "abc.123.site"
        sans = ["traefix.abc.123.site"]

[certificatesResolvers.myresolver.acme]
  email = "qbowater@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
    [certificatesResolvers.myresolver.acme.httpChallenge]
      entryPoint = "http"

[providers]
  [providers.file]
    directory = "/home/qbowater/traefik"
    watch = true

[api]
dashboard = true
```

```yaml
http:
  routers:
    to-ssh2:
      rule: "Host(`abc.123.site`) && PathPrefix(`/xff40m9m5ucs6wti`)"
      service: ssh2
    to-ssv2ray:
      rule: "Host(`abc.123.site`) && PathPrefix(`/kopxpkbc7f1q3me6`)"
      service: ssv2ray
  services:
    ssh2:
      loadBalancer:
        servers:
          - url: h2c://127.0.0.1:8080/xff40m9m5ucs6wti
    ssv2ray:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8090/kopxpkbc7f1q3me6
```

```yaml
http:
  routers:
    api:
      entryPoints: ["https"]
      rule: Host(`traefix.abc.123.site`)
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "charlie:$2y$10$YSABlp6pJ1oDMCtVVitb7.eJmSEvTqVvkUtftDaThcEV6F8JN9Ibq"
```
