### ISSUE TITLE
Two subdomains: Letsencrypt as certificateresolver vs nginx with certbot

### ISSUE THREAD

**Issue by DOCaCola** [containous/traefik#6728]
Potential bug

### What did you do?

I am running Traefik 2.2.
I have two subdomains which i have configured in Traefik

AA.domain.com
and
BB.domain.com

For the AA subdomain i am using the integrated Letsencrypt resolver in Traefik (which is working fine).
BB domain however is running nginx and has it's own certbot. However it appears that Traefik also tries to handle the requests to BB.domain.com/.well-known/acme-challenge/abcdefg (and fails)

Here is my basic configuration for these domains.
```yml
http:
  routers:
    routeraa:
      rule: "Host(`AA.domain.com`)"
      service: main-service
      tls:
        certResolver: myletsencrypt
      entryPoints:
      - "web"
      - "websecure"
    routerbbnginx:
      rule: "Host(`BB.domain.com`)"
      entryPoints:
      - "web"
      - "websecure"
      service: nginx-service`

```

Here is my certResolver

```yml
certificatesResolvers:
  myletsencrypt:
    acme:
      email: mail@domain.com
      storage: acme.json
      httpChallenge:
        entryPoint: web`
```

### What did you expect to see?

As i understood it from the documentation, Traefik tries to receive certificates based on matching hostnames which have a certResolver defined. However i do not have certResolver associated with BB.domain.com. Therefore i expected certResolver to pass the request to .well-known to the nginx server running BB.domain.com

### What did you see instead?

It appears that Traefik tries to handle a request to .well-known for a subdomain that hasn't a certResolver associated.

Here is the output from the Traefik log when i open the http://BB.domain.com/.well-known/acme-challenge/abcdefg url. The request to this url never reaches the nginx server.

```
time="2020-04-24T11:58:05Z" level=debug msg="Unable to split host and port: address BB.domain.com: missing port in address. Fallback to request host." providerName=myletsencrypt.acme

time="2020-04-24T11:58:05Z" level=debug msg="Retrieving the ACME challenge for token abcdefg..." providerName=myletsencrypt.acme

time="2020-04-24T11:58:05Z" level=error msg="Error getting challenge for token retrying in 616.051907ms" providerName=myletsencrypt.acme

...

time="2020-04-24T11:58:30Z" level=error msg="Error getting challenge for token retrying in 7.299364087s" providerName=myletsencrypt.acme

time="2020-04-24T11:58:37Z" level=error msg="Error getting challenge for token retrying in 24.931919645s" providerName=myletsencrypt.acme

time="2020-04-24T11:59:02Z" level=error msg="Error getting challenge for token retrying in 39.959238407s" providerName=myletsencrypt.acme

time="2020-04-24T11:59:42Z" level=error msg="Cannot retrieve the ACME challenge for token abcdefg: cannot find challenge for token abcdefg" providerName=myletsencrypt.acme`
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Running Traefik 2.2 on Docker
