### ISSUE TITLE
Error while writing to InfluxDB: Method Not Allowed

### ISSUE THREAD

**Issue by Sebclem** [containous/traefik#6730]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I try to configure the Influxdb metrics.

### What did you see instead?
I have an error i logs :
```
proxy_1  | time="2020-04-24T15:38:26Z" level=error msg="Error while writing to InfluxDB: Method Not Allowed\n" metricsProviderName=influxdb
proxy_1  | time="2020-04-24T15:38:26Z" level=info msg="[during WriteTo err Method Not Allowed\n]" metricsProviderName=influxdb
```

Nothing is written in my database.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
api: {}
providers:
  file:
    filename: dynamic_conf.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: proxy
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: si@xxx-lab.net
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http

log:
  level: DEBUG

metrics:
  influxdb:
    address: "influx.xxxxx.ovh"
    database: "traefik"
    protocol: "http"
    username: "traefik"
    password: "testtest"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
proxy_1  | time="2020-04-24T15:40:56Z" level=error msg="Error while writing to InfluxDB: Method Not Allowed\n" metricsProviderName=influxdb
proxy_1  | time="2020-04-24T15:40:56Z" level=info msg="[during WriteTo err Method Not Allowed\n]" metricsProviderName=influxdb
proxy_1  | time="2020-04-24T15:41:06Z" level=error msg="Error while writing to InfluxDB: Method Not Allowed\n" metricsProviderName=influxdb
proxy_1  | time="2020-04-24T15:41:06Z" level=info msg="[during WriteTo err Method Not Allowed\n]" metricsProviderName=influxdb
```

This is the only lines referring to influxdb
