### ISSUE TITLE
add support for HostRegexp rule in tls options for Traefik 2.2

### ISSUE THREAD

**Issue by rgssingh** [containous/traefik#6748]
Hi Team,

Currently Traefik 2.2 has only Host Rule support in tls options and due to that we are not able to set tls options on wildcard domains. The only options we have is to set it at default tls options. But in our case we have three wildcard domains with different tls options and we can't merge them.

Can you please provide the support for HostRegexp rule as well for tls options.

Thanks

**Comment by ldez** [comment]
Hello,

to manage wildcards domains you have to define `domains`.
```toml
[http.routers]
  [http.routers.routerbar]
    rule = "HostRegexp(`{any:.*}.snitest.com`)
    [http.routers.routerbar.tls]
      certResolver = "bar"
      [[http.routers.routerbar.tls.domains]]
        main = "snitest.com"
        sans = ["*.snitest.com"]
```

https://docs.traefik.io/v2.2/routing/routers/#domains
