### ISSUE TITLE
Trailing Slash issue with the dashboard

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#6751]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

Tried to access the dashboard without a trailing slash, as its configured in my IngressRoute

### What did you expect to see?
The Dashboard

### What did you see instead?
A 404

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
      --global.checknewversion
      --global.sendanonymoususage
      --entryPoints.traefik.address=:9000
      --entryPoints.web.address=:8000
      --entryPoints.websecure.address=:8443
      --api.dashboard=true
      --ping=true
      --providers.kubernetescrd
```

IngressRoute definition

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```
