### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by FL3SH** [containous/traefik#6761]
### Do you want to request a *feature* or report a *bug*?
Bug
### What did you do?
Configure traefik with kubernetsCRD using IngressRoute, IngressRouteTCP, and IngressRouteUDP.

I think it might be correlated with my IngressRouteTCP.
### What did you expect to see?
Memory usage shouldn't constantly increase until pod is killed by Kubernetes.

### What did you see instead?
Constantly increasing memory usage.

<img width="1602" alt="Screenshot 2020-05-02 at 14 54 42" src="https://user-images.githubusercontent.com/9084725/80869070-84dcb680-8c9e-11ea-8164-1050f04bf6ef.png">

 If necessary I can post more screenshots from Prometheus.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: traefik:2.2.1 (same behavior for 2.2.0)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Kubernetes CRD
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mqtt
  namespace: default
spec:
  entryPoints:
  - mqtt
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mosquitto
      port: 8883
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: radius1-udp
  namespace: default
spec:
  entryPoints:
  - radius1
  routes:
  - services:
    - name: myapp-udp
      port: 1812
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: radius2-udp
  namespace: default
spec:
  entryPoints:
  - radius2
  routes:
  - services:
    - name: myapp-udp
      port: 1813
```

IngressRoutes are quite long, let me know if I need to post them too.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
I think only applicable log that I am seeing:
```
msg="Error during connection: readfrom tcp 10.128.2.20:47420->10.128.4.15:8883: read tcp 10.128.2.20:8883->202.130.98.126:29192: read: connection reset by peer"
```
