### ISSUE TITLE
LOW: Kubernetes Ingress status field not updating

### ISSUE THREAD

**Issue by iridian-ks** [containous/traefik#6770]
### Do you want to request a *feature* or report a *bug*?

Bug (I think)

### What did you do?

1. Migrated Ingress controller from NGINX to Traefik (We need h2c)
2. Had existing Ingress rules that were working in every sense of the word

### What did you expect to see?

The Ingress rules should have their status fields updated if Traefik has decided to use them.

In Rancher, they use this status field to mark an Ingress as active or inactive.

Looks something like this:

```
# Ingres YAML
...
status:
  loadBalancer:
    ingress:
    - hostname: internal-a31ddaefe4dec11ea897802728661815-1703866244.us-west-2.elb.amazonaws.com
```

I'm actually not sure how NGINX found that LB as I wasn't using service type LoadBalancer, but using NodePort. Maybe it was resolving the DNS CNAME?

### What did you see instead?

Status fields are left empty so in Rancher even though the Ingress' are active they aren't flagged as such.

```
# Ingress YAML
...
status:
  loadBalancer: {}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ $ traefik version
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Defaults from the containous Traefik helm chart plus an extra --metric.prometheus=true flag.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by dtomcej** [comment]
Hello @iridian-ks,

By default, the Traefik v2 helm chart does not load ingress objects, only CRD objects.

If you enable the kubernetesingress provider as mentioned in the values.yaml file, you will need to add the ingress endpoint to tell traefik what endpoint to use to populate the status field:

https://docs.traefik.io/v2.2/providers/kubernetes-ingress/#ingressendpoint

Hope that helps.

**Comment by iridian-ks** [comment]
Hi @dtomcej ,

Thanks for the swift response.

I apologize for not showing all my values:

```
---

deployment:
  replicas: 2
  podAnnotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "9000"
    "prometheus.io/path": "/metrics"

service:
  type: NodePort

globalArguments: []
additionalArguments:
  - "--providers.kubernetescrd.ingressclass=traefik"
  - "--providers.kubernetesingress=true"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--metrics.prometheus=true"
```

My Ingress rules also have the `kubernetes.io/ingress.class: traefik` annotation.

I do want to mention - everything is working perfectly from a user perspective. As in, Ingress rules are working great. It's just the status field in the Ingress that isn't getting updated.
