### ISSUE TITLE
[Docs] Clarification on the PathPrefix.

### ISSUE THREAD

**Issue by Johannestegner** [containous/traefik#6771]
### Do you want to request a *feature* or report a *bug*?

Feature-ish doc update

### What did you expect to see?

When using the `PathPrefix` route rule the end `/` is quite important, else it will match _everything_ that starts with the path-prefix.

Example:

```
- kind: Rule
      match: Host(`mydomain.example`) && PathPrefix(`/rss`)
      priority: 10
      services:
        - kind: Service
          name: rss-svc
    - kind: Rule
      match: Host(`mydomain.example`)
      priority: 1
      services:
        - kind: Service
          name: non-rss-svc
``` 

Calling `mydomain.example/rss` works as expected, while `mydomain.com/rss-is-old` will route to the `rss-svc` too instead of the `non-rss-svc`.

Now, this is of course something that one could understand quite easily by testing and such, but I just now (in production) got this epiphany (and it took me a bit of debugging to get to where I understood it!).

I would like to propose a change in the documentation starting on line 260 in routing/routers/index.md from:

```
    Use a `*Prefix*` matcher if your service listens on a particular base path but also serves requests on sub-paths.
    For instance, `PathPrefix: /products` would match `/products` but also `/products/shoes` and `/products/shirts`.
    Since the path is forwarded as-is, your service is expected to listen on `/products`.
```
To include information about this.  

Alternatively, instead of using a `HasPrefix` type of check in the code, actually check if it is a "real match" on the prefix (I could not actually locate the code for the PathPrefix functionality in the current version, while I did find an [earlier implementation](https://github.com/containous/traefik/pull/2592/files#) using `HasPrefix`):

(pseudo-GO code just to give an idea to how I'd prefer it to work, but my go skills are too bad to actually write it nice):

```
splitPath := strings.Split(path, "/")
splitPathPrefix := strings.Split(pathPrefix, "/")

if len(splitPathPrefix) > len(splitPath) {
  // No match
}

for i := 0; i < len(splitPathPrefix); i++ {
  if !strings.EqualFold(splitPathPrefix[i], splitPath[i]) {
    // No match
  }
}
// Match
```
