### ISSUE TITLE
Traefik not generating TLS certificate (Error 401)

### ISSUE THREAD

**Issue by Shlokp** [containous/traefik#6782]
Bug

### What did you do?
After having to reset traefik, it can no longer generate certificates

### What did you expect to see?
Certificate for my domain on cloudflare to be issued

### What did you see instead?
Log
`level=error msg="Unable to obtain ACME certificate for domains \"*.redacted\" : unable to generate a certificate for the domains [*.redacted]: acme: Error -> One or more domains had a problem:\n[*.redacted] [*.redacted] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials\n"`

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.2 in docker on arm32 raspberry pi 4 4gb

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
docker-compose
```
version: "3.6"
services:

  traefik:
    hostname: traefik
    image: traefik:v1.7.2
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/pi/docker/traefik:/etc/traefik
      - /home/pi/docker/shared:/shared
```

toml

```
#debug = true

logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true 
defaultEntryPoints = ["https", "http"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "redacted" #any email id will work
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true 
onDemand = false #create certificate when container is created
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 5
[[acme.domains]]
   main = "redacted"
[[acme.domains]]
   main = "*.redacted"
   
# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "redacted"
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false
```

I have checked the cloudflare credentails multiple times, reset the cloudflare global api and retried, used a different cloudflare accout, changed domain and tried on a different raspberry pi.
