### ISSUE TITLE
Traefik v2 Telnet: You talk too soon

### ISSUE THREAD

**Issue by zapdos26** [containous/traefik#6786]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

So we are trying to setup an an inbound SMTP server, and see to getting the following error when the traffic goes through Traefik v2:
421 e833d73e1b94 You talk too soon

Now initially we thought this was an error with Docker, because it is stating that the Docker container received the telnet request. However upon testing telnetting directly to the Docker container IP address, the container could receive and perform requests without a problem. After further debugging, we limited it down to Traefik. Traefik was the prior step (and only step) between the local telnet request and the Docker container. We further proved this by telnetting to the Traefik IP which resulted in the error.
We believe that there is something wrong with either our docker-compose.yml or traefik.yml files, and any assistance would be greatly appreciated! We've reached out to the forums and Reddit prior, but neither could solve the issue.

### What did you expect to see?
```
telnet 172.18.0.6 25
Trying 172.18.0.6...
Connected to 172.18.0.6.
Escape character is '^]'.
220 e833d73e1b94 ESMTP NodeMailin Smtp Server
EHLO example.com
250-e833d73e1b94 Nice to meet you, [172.18.0.1]
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250 STARTTLS
QUIT
221 Bye
Connection closed by foreign host.
```

### What did you see instead?
```
 telnet 172.18.0.6 25
Trying 172.18.0.6...
Connected to 172.18.0.6.
Escape character is '^]'.
EHLO example.com
421 e833d73e1b94 You talk too soon
Connection closed by foreign host.
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.9
Codename:     cantal
Go version:   go1.14.1
Built:        2020-03-23T17:23:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
**traefik.yml**
```yml
providers:
   docker: {}
entryPoints:
   web:
     address: ":80"
   websecure:
     address: ":443"
   smtp:
     address: ":25"
 #providers:
 #  file:
 #    directory = /dynamic/
 certificatesResolvers:
   tls:
     acme:
       email: dev@example.com
       storage: /letsencrypt/acme.json
       httpChallenge: # used during the challenge
         entryPoint: web
 log:
   level: DEBUG
   filePath: /var/log/traefik.log
   format: json 
```
**docker-compose.yml**
```yml
services:
   traefik:
     image: traefik:v2.1
     container_name: traefik
     restart: always
     ports:
       - "25:25"
       - "80:80"
       - "443:443"
     labels:
       - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
       - traefik.http.routers.http-catchall.entrypoints=web
       - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
       - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml
       - /etc/traefik/acme/acme.json:/letsencrypt/acme.json
  air-dev:
     build: https://github.com/example/air.git#dev
     container_name: air-dev
     restart: always
     labels:
       - traefik.tcp.routers.air-dev_smtp.service=air-dev_smtp
       - traefik.tcp.services.air-dev_smtp.loadbalancer.server.port=25
       - traefik.tcp.routers.air-dev_smtp.entrypoints=smtp
       - traefik.tcp.routers.air-dev_smtp.rule=HostSNI(`*`)
       - traefik.http.routers.air-dev_http.service=air-dev_http
       - traefik.http.services.air-dev_http.loadbalancer.server.port=3000
       - traefik.http.routers.air-dev_http.rule=Host(`air-dev.example.com`)
       - traefik.http.routers.air-dev_http.tls=true
       - traefik.http.routers.air-dev_http.tls.certresolver=tls
     env_file: air/dev/env.env 
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Nothing in the logs
