### ISSUE TITLE
Router not created from docker labels with file provider

### ISSUE THREAD

**Issue by craph** [containous/traefik#6789]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have created a file called `services.toml` to define a service like this : 
```toml
[http]
  [http.services]
    [http.services.myservice]
      [http.services.myservice.loadBalancer]
        [[http.services.myservice.loadBalancer.servers]]
          url = "http://myservice/prod/"
```

Then I have included it in the docker-compose file of my Traefik like this : 
```yaml
version: "3"

services:

  traefik:
    image: "traefik:v2.2"
    networks:
      - traefik
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/services.toml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services.toml:/etc/traefik/services.toml"
    labels:
      - "traefik.http.routers.myservice.entrypoints=web"
      - "traefik.http.routers.myservice.rule=Host(`myservice.myserver`)"
      - "traefik.http.routers.myservice.service=myservice@file"

```

### What did you expect to see?
I want to see my router in the dashboard when I define it from labels in the Traefik docker-compose file.
And the reverse-proxy should work.

### What did you see instead?
Instead I have a 404 when I call : http://myservice.myserver/ same with : http://myservice.myserver/prod/

And I'm unable to see the routeur in the dashboard for : `myservice.myserver`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

The only way to have this working is  by writing the routeur in the file services.toml...

Can you help me with that ?

Thank you very much.

Best regards,
