### ISSUE TITLE
Traefik stops working entirely if one of the ingresses is not correctly configured.

### ISSUE THREAD

**Issue by Vad1mo** [containous/traefik#6794]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I use Traefik 2.2.1 with Cert-manager 0.15

After the initial setup with helm, I deployed an Kubernetes Ingress with an reference to a certificate. (that doesn't exist yet)

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: prometheus-operator-grafana-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure    
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: {{ .Values.grafana_domain }}
      http:
        paths:
          - backend:
              serviceName: prometheus-operator-grafana
              servicePort: 80
  tls:
    - hosts:
        - {{ .Values.grafana_domain }}
        secretName: ingress-prod-certs-tls
``` 

### What did you expect to see?

I expected now to see that traefik fails to setup the route until cert-manager requested the certificate and wrote it to `ingress-prod-certs-tls`. After that I expected traefik to create a route and recover from the failed state.

### What did you see instead?

Traefik stops serving all routes (also the ones that worked) if there is problem with only one ingress.

I the logs I see this error message telling me correctly that `ingress-prod-certs-tls ` is missing. However while it does this it stops to serve all other routes. If Cert-manager is configured to work with traefik to request certs it can't do because all ingress routes stopped working.  

`2020-05-12T06:43:26.813871706Z time="2020-05-12T06:43:26Z" level=error msg="Error configuring TLS: secret monitoring/ingress-prod-certs-tls does not exist" providerName=kubernetes ingress=prometheus-operator-grafana-ingress namespace=monitoring`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik 2.2.1
Helm Chart: 8.1.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`Kubernetes 1.17`
