### ISSUE TITLE
UDP: traefik uses wrong IP to reply

### ISSUE THREAD

**Issue by browcio** [containous/traefik#6802]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I try to use traefik as proxy in front of DNS server. Server with traefik has two IP addresses.

### What did you expect to see?
Client should receive answer from connected IP address.

### What did you see instead?
tcpdump shows that traefik accepts packet on one IP but responds to client from other. When i specify IP address in entryPoints traefik responds with correct (specified) IP.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
entryPoints:
  dns-udp:
    address: ":53/udp"
(...)
udp:
  services:
    dns-udp:
      loadBalancer:
        servers:
        - address: "BACKENDIP:53"
  routers:
    dns-udp:
      entryPoints:
        - "dns-udp"
      service: "dns-udp"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
