### ISSUE TITLE
middlware reference to kubernetes ingress annotation not working

### ISSUE THREAD

**Issue by shivpathak** [containous/traefik#6807]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1 - apply traefik CRD manifest in k8s
2 - apply traefik deployment manifest in k8s 
3 - apply demo deployment & service manifest in k8s
4 - apply middleware & ingress manifest in k8s

**Note-** I have given external-dns annotation to traefik-service so traefik pod get's resolved with name _traefik.services_

### What did you expect to see?

```
root@test:/# curl -v traefik.services/elasticsearch
*   Trying 10.10.13.54...
* TCP_NODELAY set
* Connected to traefik.services (10.10.13.54) port 80 (#0)
> GET /elasticsearch HTTP/1.1
> Host: traefik.services
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.14.2
< Date: Thu, 14 May 2020 14:23:10 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 04 Dec 2018 14:44:49 GMT
< Connection: keep-alive
< ETag: "5c0692e1-264"
< Accept-Ranges: bytes
<

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Connection #0 to host traefik.services left intact
```

### What did you see instead?

```
root@test:/# curl -v traefik.services/elasticsearch
*   Trying 10.10.13.54...
* TCP_NODELAY set
* Connected to traefik.services (10.10.13.54) port 80 (#0)
> GET /elasticsearch HTTP/1.1
> Host: traefik.services
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 14 May 2020 14:23:47 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host traefik.services left intact
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# traefik version
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

**Traefik CRD deployment**

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressrouteudps.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteUDP
    plural: ingressrouteudps
    singular: ingressrouteudp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsstores.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSStore
    plural: tlsstores
    singular: tlsstore
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced
```

**Traefik Deployment manifests**

```
---
# Source: traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.1.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: traefik
---
# Source: traefik/templates/rbac/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.1.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch
---
# Source: traefik/templates/rbac/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.1.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: capabilities
---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.1.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.services
    external-dns.alpha.kubernetes.io/ttl: "10"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
  - port: 80
    name: web
    targetPort: "web"
  - port: 443
    name: websecure
    targetPort: "websecure"
---
# Source: traefik/templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.1.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: traefik
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-8.1.4
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: traefik
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      containers:
      - image: traefik:2.2.1
        name: traefik
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - name: "traefik"
          containerPort: 9000
          protocol: TCP
        - name: "web"
          containerPort: 80
          protocol: TCP
        - name: "websecure"
          containerPort: 443
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: true
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: data
            mountPath: /data
        args:
          - "--entryPoints.traefik.address=:9000"
          - "--entryPoints.web.address=:80"
          - "--entryPoints.websecure.address=:443"
          - "--api.dashboard=true"
          - "--ping=true"
          - "--providers.kubernetescrd"
          - "--providers.kubernetescrd.namespaces=capabilities"
          - "--providers.kubernetesingress.namespaces=capabilities"
          - "--providers.kubernetesingress=true"
          - "--providers.kubernetescrd=true"
          - "--providers.kubernetescrd.ingressclass=traefik-internal"
          - "--providers.kubernetesingress.ingressclass=traefik-internal"
          - "--log.level=DEBUG"
          - "--log=true"
          - "--accesslog=true"
          - "--metrics.prometheus=true"
      volumes:
        - name: data
          emptyDir: {}
      priorityClassName: service-dependency
---
# Source: traefik/templates/dashboard-hook-ingressroute.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.1.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: traefik
spec:
  entryPoints:
    - traefik
  routes:
  - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
```

**Target deployment of Ingress**

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-es-ingress
  namespace: capabilities
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: es-test-ingress
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: es-test-ingress
    spec:
      containers:
      - name: test-es-ingress
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: es-test-ingress
  namespace: capabilities
  labels:
    app.kubernetes.io/name: es-test-ingress
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: es-test-ingress
  ports:
  - port: 80
    name: web
    targetPort: 80
```

**Ingress & Middleware config**
```---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /elasticsearch
    forceSlash: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: stripprefix@kubernetescrd
  name: test-es-ingress
  namespace: capabilities
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: es-test-ingress
          servicePort: 80
        path: /
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-05-14T14:03:43Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"middlewares\":{\"capabilities-stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/elasticsearch\"]}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=kubernetescrd
time="2020-05-14T14:03:43Z" level=debug msg="Added outgoing tracing middleware prometheus@internal" routerName=prometheus@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik
time="2020-05-14T14:03:43Z" level=debug msg="Added outgoing tracing middleware ping@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=ping@internal
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=metrics-entrypoint middlewareType=Metrics
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=web middlewareName=metrics-entrypoint
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint middlewareType=Metrics entryPointName=traefik
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=metrics-entrypoint middlewareType=Metrics
time="2020-05-14T14:03:43Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=websecure middlewareName=metrics-entrypoint
time="2020-05-14T14:03:43Z" level=debug msg="No default certificate, generating one"
time="2020-05-14T14:03:43Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-05-14T14:03:43Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-05-14T14:03:44Z" level=debug msg="Configuration received from provider kubernetes: {\"http\":{\"routers\":{\"test-es-ingress-capabilities\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"stripprefix@kubernetescrd\"],\"service\":\"capabilities-es-test-ingress-80\",\"rule\":\"PathPrefix(`/`)\"}},\"services\":{\"capabilities-es-test-ingress-80\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://10.10.12.154:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=kubernetes
time="2020-05-14T14:03:44Z" level=debug msg="Skipping Kubernetes event kind *v1beta1.Ingress" providerName=kubernetescrd
time="2020-05-14T14:03:44Z" level=debug msg="Added outgoing tracing middleware ping@internal" middlewareName=tracing middlewareType=TracingForwarder routerName=ping@internal entryPointName=traefik
time="2020-05-14T14:03:44Z" level=debug msg="Added outgoing tracing middleware prometheus@internal" entryPointName=traefik routerName=prometheus@internal middlewareName=tracing middlewareType=TracingForwarder
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=traefik
time="2020-05-14T14:03:44Z" level=debug msg="Middleware name not found in config (ResponseModifier)" routerName=test-es-ingress-capabilities@kubernetes middlewareName=stripprefix@kubernetescrd entryPointName=web middlewareType=undefined
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining serviceName=capabilities-es-test-ingress-80 entryPointName=web routerName=test-es-ingress-capabilities@kubernetes
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" serviceName=capabilities-es-test-ingress-80 middlewareName=metrics-service middlewareType=Metrics entryPointName=web routerName=test-es-ingress-capabilities@kubernetes
time="2020-05-14T14:03:44Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=test-es-ingress-capabilities@kubernetes serviceName=capabilities-es-test-ingress-80
time="2020-05-14T14:03:44Z" level=debug msg="Creating server 0 http://10.10.12.154:80" serverName=0 entryPointName=web routerName=test-es-ingress-capabilities@kubernetes serviceName=capabilities-es-test-ingress-80
time="2020-05-14T14:03:44Z" level=debug msg="Added outgoing tracing middleware capabilities-es-test-ingress-80" middlewareType=TracingForwarder routerName=test-es-ingress-capabilities@kubernetes entryPointName=web middlewareName=tracing
time="2020-05-14T14:03:44Z" level=error msg="middleware \"stripprefix@kubernetescrd\" does not exist" entryPointName=web routerName=test-es-ingress-capabilities@kubernetes
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=traefik middlewareName=metrics-entrypoint
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=web middlewareName=metrics-entrypoint
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=metrics-entrypoint middlewareType=Metrics
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=metrics-entrypoint middlewareType=Metrics
time="2020-05-14T14:03:44Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
```

**Comment by shivpathak** [comment]
I was looking at https://docs.traefik.io/middlewares/overview/#provider-namespace and found the issue myself.

**FROM**
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: stripprefix@kubernetescrd
  name: test-es-ingress
  namespace: capabilities
```
**TO**
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: capabilities-stripprefix@kubernetescrd
  name: test-es-ingress
  namespace: capabilities
```

**Conclusion-** I created the middleware named `stripprefix` in `capabilities` namespace, however internally traefik creates middleware named - `capabilities-stripprefix`

That's why when I pass annotation value `stripprefix@kubernetescrd` instead of `capabilities-stripprefix@kubernetescrd` traefik throws following error - 

```
middleware \"stripprefix@kubernetescrd\" does not exist" entryPointName=web routerName=test-es-ingress-capabilities@kubernetes
```

I am putting my finding hoping if it could help in case someone experience the same issue.
