### ISSUE TITLE
Do you have the function of URL jump

### ISSUE THREAD

**Issue by gaoyang02** [containous/traefik#6824]
### Do you want to request a *feature* or report a *bug*?
bug

Bug

### Output of `traefik version`: (_What version of Traefik are you using?_)
v2.2.0

```
(paste your output here)
```

I just want to pass traefik2.2 To enable user browser access test.com If you do, automatically jump to www.test.com 。 At present, our domain name is www.test.com , configured HTTP to jump to HTTPS through tracefik, that is, user access www.test.com It can automatically jump to https://www.test.com , using the middleware function, has been implemented. But now I want to implement user access test.com And then automatically jump to http://www.test.com It is similar to the urlwrite function of nginx, traefik2.2 Can it be realized;
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: testprd
  labels:
    k8s-app: portal

spec:
  replicas: 3
  revisionHistoryLimit: 3
  #滚动升级时70s后认为该pod就绪
  minReadySeconds: 70
  strategy:
    ##由于repliportal为3,则整个升级,pod个数在2-4个之间
    rollingUpdate:
      #滚动升级时会先启动1个pod    
      maxSurge: 1 
      #滚动升级时允许的最大Unavailable的pod个数      
      maxUnavailable: 1   
  selector:
    matchLabels:
      k8s-app: portal
  template:
    metadata:
      labels:
        k8s-app: portal
    spec:
      containers:
      - name: portal
        image: 192.168.5.25:31000/test1024/portal:build-<BUILD_TAG>
        #env:
        #- name: portal_PROFILES_ACTIVE
        #  value: "prod"  
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            memory: 4096Mi
            cpu:  2000m
          requests:
            cpu: 1000m
            memory:  2048Mi
        ports:
        #容器的端口
        - containerPort: 80
          name: portal
          protocol: TCP        
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 240
          periodSeconds: 20   
        #volumeMounts:
        #- mountPath: "/download"
        #  name: data
      imagePullSecrets:
      - name: myregistrykey    
      #volumes:
      #- name: data
      #  persistentVolumeClaim:
      #    claimName: download-pvc

apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: testprd
  labels:
    k8s-app: portal
spec:
  ports:
  #集群IP的端口
  - port: 80
    name: portal
    protocol: TCP
    #容器的端口
    targetPort: 80
  selector:
    k8s-app: portal

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: testprd
spec:
  redirectScheme:
    scheme: https

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portal-https
  namespace: testprd
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`www.test.com`,`test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: portal
      port: 80
  tls:
    secretName: 1024prodportal

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portal-http
  namespace: testprd
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`www.test.com`,`test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: portal
      port: 80
    middlewares: 
    - name: redirect-https
```
```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
