### ISSUE TITLE
Traefik 1.7.* certificate generation failure with http-01 challenge 

### ISSUE THREAD

**Issue by sureshamk** [containous/traefik#6826]
Bug
Not able to get certificates with http-01 challenge , in my case http://demo.domain.cn/.well-known/acme-challenge/token not able to access. Failed with timeout

### What did you do?
In china , in eks envionamnet i m to setting up traefik's (v1) helm chart and enabled acme for certificate via http-01 chalenge

### What did you expect to see?
I expected get the certificate

### What did you see instead?
```
{"level":"error","msg":"Error getting challenge for token retrying in 3.751851916s","time":"2020-05-19T19:31:50Z"}
{"level":"error","msg":"Error getting challenge for token retrying in 2.395949855s","time":"2020-05-19T19:31:50Z"}
{"level":"error","msg":"Error getting challenge for token retrying in 2.89233987s","time":"2020-05-19T19:31:50Z"}
{"level":"error","msg":"Error getting challenge for token retrying in 8.506557446s","time":"2020-05-19T19:31:50Z"}
{"level":"error","msg":"Unable to obtain ACME certificate for domains \"demo.domain.cn\" detected thanks to rule \"Host:demo.domain.cn\" : unable to generate a certificate for the domains [demo.domain.cn]: acme: Error -\u003e One or more domains had a problem:\n[demo.domain.cn] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://demo.domain.cn/.well-known/acme-challenge/m39cq2tLv9ESzoE4S3bFmfMoaXcZTQxcbL6l6Polwag: Error getting validation data, url: \n","time":"2020-05-19T19:31:50Z"}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
chart: traefik-1.86.2
Version:      v1.7.16
Codename:     maroilles
Go version:   go1.12.9
Built:        2019-09-13_01:12:20PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "error"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[ping]
entryPoint = "http"
[kubernetes]
  [kubernetes.ingressEndpoint]
  publishedService = "kube-system/traefik-ingress"
[traefikLog]
  format = "json"
[acme]
KeyType = "RSA4096"
email = "suresh@rrrrrrr.com"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
caServer = "https://acme-v02.api.letsencrypt.org/directory"
acmeLogging = true
  [acme.httpChallenge]
  entryPoint = "http"
[api]
  entryPoint = "traefik"
  dashboard = true
  [api.statistics]
    recentErrors = 50

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
