### ISSUE TITLE
Configuration live updates from redis are not received after redis is restarted.

### ISSUE THREAD

**Issue by sergey-komissarov** [containous/traefik#6832]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We are using traefik and redis in same kubernetes cluster. Redis is used for changing routing configuration dynamically. Everything is working fine until pod with redis is restarted. After this traefik does not receive configuration updates. Also there is nothing in debug output.

We have single pod with redis, so for reproducing it is enough to delete this pod, wait until it is restarted and update redis key with new configuration.

### What did you expect to see?

Traefik may reconnect to the redis when connection is closed.

### What did you see instead?

Nothing happened.

### Output of `traefik version`: (_What version of Traefik are you using?_)

`$ traefik version`
```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
    checkNewVersion = false
    sendAnonymousUsage = false
[accessLog]
[log]
    level = "INFO"
[api]
    dashboard = true
    insecure = true
[entryPoints.blocks]
    address = ":10080"
[entryPoints.traefik]
    address = ":10088"
[providers]
    providersThrottleDuration = "1s"
[providers.redis]
    endpoints = ["pseven-dev-redis-svc:16379"]
    rootKey = "blockrouter"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

There was no debug output after redis is restarted.
