### ISSUE TITLE
Access logs header filtering is case sensitive, headers are case insensitive per RFC

### ISSUE THREAD

**Issue by bradjones1** [containous/traefik#6837]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Specifying a header retention, skip or redaction spec in the Access Logs filtering section of [the config](https://docs.traefik.io/observability/access-logs/#limiting-the-fields) is case-sensitive to the header as received by Traefik. Per [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), header names are case insensitive and many tools now prefer lowercase header name specification to reflect this. Regardless, Traefik should normalize the header name to account for a mismatch between the header as listed in the config and the header name received over HTTP.

### What did you expect to see?

Specifying a filter for `x-forwarded-for` should match against `X-Forwarded-For`, and other case-mismatched variants.

### What did you see instead?

The header name must match the casing of the received header to be included in the filter set.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik 2.2.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[accessLog]
  format = "json"
  [accessLog.filters]
    ...
    [accessLog.fields.headers]
      defaultMode = "drop"
      [accessLog.fields.headers.names]
        "User-Agent" = "keep"
        "Content-Type" = "keep"
        "Cf-Connecting-Ip" = "keep"
        "x-forwarded-for" = "keep"
```
