### ISSUE TITLE
(feat): Support for $scheme$host$request_uri variables

### ISSUE THREAD

**Issue by lukasmrtvy** [containous/traefik#6839]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Would be great to support variables `$scheme://$host$request_uri` ( just like nginx does )

Use case -> single universal middleware:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fwd-auth
  namespace: traefik
spec:
  forwardAuth:
    address: 'https://fwdauth.example.com?uri=$scheme://$host$request_uri'
    trustForwardHeader: true
    authResponseHeaders:
       - x-resp-header
```

**Comment by SantoDE** [comment]
Hey hey,

thanks for your interest in the project :-)

Can you try to explain a bit more the use-case please? I'm wondering about your "universal middleware" part :-)

Thanks

**Comment by lukasmrtvy** [comment]
Well.., You can use something like this with nginx/nginx ingress controler in k8s
```
nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.domain.example/verify?uri=$scheme://$host$request_uri"
nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.domain.example?uri=$scheme://$host$request_uri"
```
Traefik middleware needs hardcoded uri in forwardauth mode.

**Comment by Vad1mo** [comment]
Point is that currently the auth middleware or more precisely the auth service that gets called by the middleware is blind about who is calling it. To provide a common paracticed option would be to forward the host and request_uri to the auth service.

There two ways to do this this is the one that nginx uses. In #6840 I offered another one that is a bit less flexible but would better fit with the traefik middleware concept. It would be basically enough if traefik would have the option to append the `request_uri ` to `forwardAuth.address` making the auth middleware more versatile usable. 

```yaml
http:
  middlewares:
    test-auth:
      forwardAuth:
        address: "https://example.com/auth"
        appnedRequestUri: true

```
A more flexible solution would be if traefik suppored header value mapping with gotemplate allowing the auth middleware to enrich the upstream request for the authservice to make better decisions.
