### ISSUE TITLE
Requests with URL-encoded characters are not forwarded correctly

### ISSUE THREAD

**Issue by ydubreuil** [containous/traefik#684]
It seems that Traefik doesn't forward requests with URL encoded parts correctly. Instead of forwarding requests with encoded characters straight to back-end servers, it issues a 301 Moved reponse with a Location header containing the decoded URL. In the decoded URL, double-slashes strings are replaced a single slash. This breaks the Jenkins Reverse Proxy monitor which reports a warning telling the reverse proxy set up is broken.

For example, when the following request is sent to Traefik `http://localhost:8000/administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/http%3A%2F%2Flocalhost%3A8000%2Fmanage/`, Traefik responds with a 301 containing a wrong Location response header, leading to a 404 on the next request.

Here is the network traffic between cURL and Traefik:

```
GET /administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/http%3A%2F%2Flocalhost%3A8000%2Fmanage/ HTTP/1.1
Host: localhost:8000
Authorization: Basic YWRtaW46MzJiZDM0MTJlMmFlYmVkYzgwNjQzMDUxM2VkYzA2ZGY=
User-Agent: curl/7.50.2
Accept: */*
Referer: http://localhost:8000/manage

HTTP/1.1 301 Moved Permanently
Location: /administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/http:/localhost:8000/manage/
Date: Mon, 19 Sep 2016 14:56:47 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

GET /administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/http:/localhost:8000/manage/ HTTP/1.1
Host: localhost:8000
Authorization: Basic YWRtaW46MzJiZDM0MTJlMmFlYmVkYzgwNjQzMDUxM2VkYzA2ZGY=
User-Agent: curl/7.50.2
Accept: */*
Referer: http://localhost:8000/manage

HTTP/1.1 404 Not Found
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 459
Content-Type: text/html; charset=ISO-8859-1
Date: Mon, 19 Sep 2016 14:56:47 GMT
Server: Jetty(9.2.z-SNAPSHOT)
X-Content-Type-Options: nosniff
....

```

As you can see, the first HTTP response (301) contains the incorrectly decoded URL. The response is issued by Traefik and doesn't come from Jenkins (no `Server` header and the response is not in the network capture of traffic between Traefik and Jenkins)

In case someone wants to reproduce with Jenkins, I baked a `docker-compose.yml` to launch both Traefik and Jenkins:

```
traefik:
  image: traefik:v1.0.2
  command: --web --docker
  ports:
    - "8000:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

jenkins:
  image: jenkins:2.7.4-alpine
  labels:
    - "traefik.backend=jenkins"
    - "traefik.frontend.rule=Host:localhost"
    - "traefik.port=8080"
  environment:
    - JAVA_OPTS=-Xmx256m -Dhudson.DNSMultiCast.disabled=true
  expose:
    - "8080"
```

To get the admin API token, browse http://localhost:8000/user/admin/configure

Then, launch the following curl command to reproduce: 

```
curl -iL --user "admin:$API_TOKEN" \
  -e "http://localhost:8000/manage" \
  "http://localhost:8000/administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/test"
```

Any pointer to help me digging into Traefik code to propose a fix would be greatly appreciated.
