### ISSUE TITLE
Allow to specify TLS options in static configuration

### ISSUE THREAD

**Issue by mschoettle** [containous/traefik#6849]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

With traefik v2.2 it is now possible to specify http-to-https [redirection](https://docs.traefik.io/v2.2/routing/entrypoints/#redirection) and some [TLS settings](https://docs.traefik.io/v2.2/routing/entrypoints/#tls) (such as `certResolver` and `domains`) directly in the entrypoints in the static configuration. The cert resolvers are also specified in the static configuration.

However, the [TLS options](https://docs.traefik.io/v2.2/https/tls/#tls-options) still need to be in the dynamic configuration. I think it would be clearer if these would also be specified in the static configuration together with everything else (as described above).

**Comment by nmengin** [comment]
Hey @mschoettle,

It looks like the feature you request alreday exists.
I've closed the issue accordinly.

**Comment by mschoettle** [comment]
Hey @nmengin, thanks for getting back.

Could you point me to the documentation where this feature is described? Based on the documentation on [TLS options](https://doc.traefik.io/traefik/reference/routing-configuration/http/tls/tls-options/) it looks like it is still required to be defined in the dynamic configuration.

When I use traefik, I always need to define a `tls.yaml` that is included using the file provider:

```yaml
tls:
  options:
    default:
      minVersion: VersionTLS12
      curvePreferences:
        - X25519MLKEM768
        - X25519
        - CurveP256
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    mintls13:
      minVersion: VersionTLS13
```
