### ISSUE TITLE
Traefik 2 with Let's Encrypt does not send the full chain / intermediate CA

### ISSUE THREAD

**Issue by Enrico204** [containous/traefik#6850]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I deployed a TLS-protected endpoint using Traefik with Let's Encrypt (production) as cert resolver.

Traefik correctly validates against Let's Encrypt (using DNS in my case), generates the certificate and installs it.

### What did you expect to see?

I expect Traefik to send the complete certificate chain (in this case: the website certificate + `Let's Encrypt Authority X3 `) to allow devices without LE intermediate (eg. Android 6 in certain configurations) to validate against `DST Root CA X3`.

Or, at least, have a switch to change this behavior.

### What did you see instead?

Traefik is sending the website certificate only. The `Let's Encrypt Authority X3 ` is missing.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
spec:
  entryPoints:
    - web-secure
  routes:
  - match: Host(`mywebsite.com`)
    kind: Rule
    services:
    - name: website
      port: 80
  tls:
    certResolver: default

```
