### ISSUE TITLE
Metrics are not updated during graceful shutdown

### ISSUE THREAD

**Issue by L3o-pold** [containous/traefik#6854]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Gracefully shutdown Traefik, query prometheus stats, see that `traefik_entrypoint_open_connections` and `traefik_service_open_connections` metrics do not decrease. 

### What did you expect to see?

I expect to see `traefik_entrypoint_open_connections` and `traefik_service_open_connections` metrics being updated event if Traefik is shutting down.

### What did you see instead?

I see no update in `traefik_entrypoint_open_connections` and `traefik_service_open_connections` metrics as queries never end.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[metrics]
  [metrics.prometheus]
[ping]
  entryPoint = "ping"
[api]
  dashboard = true

[entryPoints]
  [entryPoints.ping]
    address = ":8081"
    [entryPoints.ping.transport]
      [entryPoints.ping.transport.lifeCycle]
        requestAcceptGraceTimeout = "60s"
        graceTimeOut = "2h"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik_entrypoint_open_connections{entrypoint="https",method="OPTIONS",protocol="http"} 14
```

But there is no more open connections so it should not be 14 but 0 instead.

**Comment by rtribotte** [comment]
Hi @L3o-pold 

Thanks for your contribution and your interest for Traefik !

I tried to reproduce the bug you described, but had the metrics updated, and i think it's a configuration issue.

For prometheus, traefik exposes the metrics endpoint (`/metrics`) that serves the metrics.
In your configuration, the metrics endpoint cannot respond after the `requestAcceptGraceTimeout` period is exceeded, because you've set it on your "ping" entrypoint.

To have your metrics updated (the metrics endpoint still responding), you need to configure it on a specific entrypoint with a `requestAcceptGraceTimeout` that exceeds the overall durations (`requestAcceptGraceTimeout` + `graceTimeout`) sets on all other entrypoints. (In your configuration `2h61s`or so).

Is that solving your issue ?

**Comment by L3o-pold** [comment]
Hi @rtribotte 

Sorry I didn't pass the good configuration. Indead, my entrypoint have the right `requestAcceptGraceTimeout` I think.

```toml
[ping]
    [api]
      dashboard = true
    [metrics]
      [metrics.prometheus]
    [providers]
      [providers.file]
        directory = "/rules"

    [entryPoints]
      [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.transport]
          [entryPoints.traefik.transport.lifeCycle]
            requestAcceptGraceTimeout = "2h"
            graceTimeOut = "2h"
```

This configuration should be ok for fetching metrics during 2 hours.
In prometheus, I see that it can still fetch metrics, but the values remaining the same and are not updated.

**Comment by rtribotte** [comment]
Ok, if the metrics are configured on `treafik` entrypoint in your configuration, then, it must accept the requests during 2 hours after a graceful shutdown, and while others entrypoints are in the `graceTimeout` if the first config you submitted is still valid.

But if you can provide a full configuration, it will be easier to understand what's going wrong.

I'll share with you a configuration that works and makes me believe that it is working as expected.

I used this docker compose file:
```yml
version: '3.5'

services:
  traefik:
    image: traefik:2.1.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.transport.lifecycle.requestAcceptGraceTimeout=1s
      - --entrypoints.web.transport.lifecycle.graceTimeOut=10s
      - --entrypoints.metrics.address=:8282
      - --entrypoints.metrics.transport.lifecycle.requestAcceptGraceTimeout=30s
      - --entrypoints.metrics.transport.lifecycle.graceTimeOut=5s
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --metrics=true
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
    stop_grace_period: 35s
    ports:
      - '80:80'
      - '8282:8282'

  api1:
    image: containous/whoami
    labels:
      traefik.enable: 'true'
      traefik.http.routers.router0.entrypoints: web
      traefik.http.routers.router0.rule: Host(`whoami`)
    ports:
      - '8001:80'
```

Observing the metrics endpoint : `watch 'curl --raw localhost:8282/metrics -s | grep "^[^#].*open_connections"'`

Using the following scenario:
`docker-compose up -d `
--> connection on metrics entrypoint is showing
`curl http://whoami/\?wait\=10s`
--> connection on web entrypoint and on service
`docker-compose stop traefik`
--> the connection is still up, and when the connection finally end, i can see the metrics updated and showing zero opened connections until the stop grace period expires.

WDYT ?

**Comment by L3o-pold** [comment]
@rtribotte by default prometheus metrics will be exposed on the traefik entrypoint.

A more detailed configuration file:

```toml
[accessLog]
    [ping]
    [api]
      dashboard = true
    [metrics]
      [metrics.prometheus]
    [providers]
      [providers.file]
        directory = "/rules"

    [entryPoints]
      [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.transport]
          [entryPoints.traefik.transport.lifeCycle]
            requestAcceptGraceTimeout = "2h"
            graceTimeOut = "2h"

      [entryPoints.http]
        address = ":80"
        [entryPoints.http.forwardedHeaders]
          insecure = true
        [entryPoints.http.transport]
          [entryPoints.http.transport.lifeCycle]
            requestAcceptGraceTimeout = "60s"
            graceTimeOut = "2h"
```

```toml
[http.routers.varnish]
        rule = "Host(`****`)"
        service = "varnish"
        entryPoints = ["http"]
```

I'll try to reproduce on a docker-compose environment.

**Comment by rtribotte** [comment]
Hi @L3o-pold,

I share with you the configuration i used to test it outside docker-compose, and with the metrics on traefik entrypoint.
Launch a whoami service : `docker run -d -P --name wai -p 8001:80 containous/whoami`
Run ./traefik with this config :
```toml
#static conf
[entryPoints]
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.transport]
      [entryPoints.traefik.transport.lifeCycle]
        requestAcceptGraceTimeout = "30s"
        graceTimeOut = "5s"
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.transport]
      [entryPoints.web.transport.lifeCycle]
        requestAcceptGraceTimeout = "1s"
        graceTimeOut = "10s"

[metrics]
  [metrics.prometheus]

[log]
  level = "DEBUG"

[providers]
  [providers.file]
    filename = "dynamic.yml"
```

```yml
#dynamic conf
http:
  routers:
    rt:
      entryPoints:
        - "web"
      rule: "Host(`whoami`)"
      service: wai

  services:
    wai:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8001"
```

I cannot reproduce your issue, traefik metrics are served and updated accordingly to the configuration.
