### ISSUE TITLE
ClientUsername in access logs is always "-"

### ISSUE THREAD

**Issue by tompson** [containous/traefik#6862]
### Do you want to request a *feature* or report a *bug*?

Bug / Regression

This was already an [issue in 1.7](https://github.com/containous/traefik/issues/4012) and was fixed with PR #4093 but this not fixed in 2.2.x as [the code shows](https://github.com/containous/traefik/blob/master/pkg/middlewares/accesslog/logger.go#L270-L277) 

### What did you do?

Configured

```--accesslog.fields.headers.defaultMode=keep```

### What did you expect to see?

to get the `ClientUsername` in the access log 

### What did you see instead?

```
{"ClientAddr":"10.244.1.0:7491","ClientHost":"10.244.1.0",
"ClientPort":"7491","ClientUsername":"-","DownstreamContentSize":427,"...
```

`"ClientUsername":"-",` is always `"-"`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

**Comment by SantoDE** [comment]
Hello @tompson,

thanks for your interest in the project.

This is a duplicate of #6722 and therefore, I'll close that issue :-)

**Comment by tompson** [comment]
is it really a duplicate? #6722 speaks of "not logged on failure" - to me it looks like it is never logged, even on success

**Comment by notsureifkevin** [comment]
Hi Tompson,

I was able to validate that the ClientUsername is shown on the logs using this example.

```
version: '3.3'
services:
  traefik_proxy:
    image: containous/traefik:latest
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.headers.defaultmode=keep"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=foo:$$apr1$$8BTORHDg$$7bVOg9bhSM9hf6pkOeklN/"
      - "traefik.http.services.api.loadbalancer.server.port=80"
```

The logs show the user name, as you can see below:

```
traefik_proxy_1  | {"ClientAddr":"[::1]:57920","ClientHost":"::1","ClientPort":"57920","ClientUsername":"foo","DownstreamContentSize":435,"DownstreamStatus":200,"Duration":284100,"OriginContentSize":435,"OriginDuration":271200,"OriginStatus":200,"Overhead":12900,"RequestAddr":"localhost","RequestContentSize":0,"RequestCount":1,"RequestHost":"localhost","RequestMethod":"GET","RequestPath":"/api/overview","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"api@docker","StartLocal":"2020-05-29T18:04:29.31132Z","StartUTC":"2020-05-29T18:04:29.31132Z","downstream_Content-Type":"application/json","entryPointName":"web","level":"info","msg":"","origin_Content-Type":"application/json","request_Accept":"application/json, text/plain, */*","request_Accept-Encoding":"gzip, deflate","request_Accept-Language":"en-US,en;q=0.5","request_Authorization":"Basic Zm9vOnlvdXJmYWNl","request_Connection":"keep-alive","request_Dnt":"1","request_Referer":"http://localhost/dashboard/","request_User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","request_X-Forwarded-Host":"localhost","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"DESKTOP-DL2UI4O","request_X-Real-Ip":"::1","time":"2020-05-29T18:04:29Z"}
```

Would it be possible for you to share the configuration where we can reproduce the issue you're having?

**Comment by tompson** [comment]
@notsureifkevin with your configuration it works, but only if user/name password is correct - no username is logged if username is wrong

but another problem is that it looks like it only works it auth is done via traefik middleware - not when done in server behind traefik

with this configuration it does not work:

```
version: '3.3'
services:
  traefik_proxy:
    image: traefik:v2.2.1
    ports:
      - 8080:80
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.headers.defaultmode=keep"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    
  nginx:
    image: nginx
    restart: always
    volumes:
    - ./auth:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
```
