### ISSUE TITLE
DASHBOARD  API recommends adding prefix configuration

### ISSUE THREAD

**Issue by ztj1993** [containous/traefik#6872]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When I tested the traefik today, I found that DASHBOARD could not configure the API path, such as the following:
```
version: "3"
services:

  traefik:
    image: traefik:v2.2
    hostname: traefik
    container_name: traefik
    network_mode: bridge
    environment:
      - TRAEFIK_LOG=true
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_API=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER=true
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes=/traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.middlewares=traefik-strip-prefix@docker
    expose:
      - 80/tcp
      - 443/tcp
      - 8080/tcp
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8080/tcp
```
I can access dashboard, but the API path is incorrect.
It is recommended to add the API request path configuration for dashboard.
