### ISSUE TITLE
Using stickiness on IngressRoutes routes traffic between two or more services rather than routing the user to the same service

### ISSUE THREAD

**Issue by anthonyt123** [containous/traefik#6883]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Setup an IngressRoute with two services and set sticky cookies

### What did you expect to see?

A user being routed through the same service each time to reach the same set of pods running the same version of the application

### What did you see instead?

The user would be routed through both services based on the RoundRobin weighting resulting in them seeing a different version of the application based on the service they would be routed through

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: SERVICE_NAME-ingress-http
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`SERVICE_DOMAIN`)"
      kind: Rule
      services:
        - name: SERVICE_NAME
          port: 80
          sticky:
            cookie:
              httpOnly: false
              name: cookie
              secure: true
              sameSite: strict
          strategy: RoundRobin
          weight: 80
        - name: SERVICE_NAME-v2
          port: 80
          sticky:
            cookie:
              httpOnly: false
              name: cookie
              secure: true
              sameSite: strict
          strategy: RoundRobin
          weight: 20
      middlewares:
        - name: secure
          namespace: traefik
        - name: basic-auth
          namespace: traefik
```

**Comment by ddtmachado** [comment]
hello @anthonyt123 
To achieve this you need to setup a weighted round robin at the service level and then reference it on the router, see the [reference](https://docs.traefik.io/routing/providers/kubernetes-crd/#weighted-round-robin). There is also some important notes regarding mixing or chaining load-balancers on the [services doc](https://docs.traefik.io/routing/services/#sticky-sessions).

I must admit that the documentation on this is not easy to follow, but it works as expected. Here is a full example:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoamiv1
  labels:
    app: containous
    name: whoamiv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containous
      task: whoamiv1
  template:
    metadata:
      labels:
        app: containous
        task: whoamiv1
    spec:
      containers:
        - name: whoamiv1
          image: containous/whoami
          ports:
            - containerPort: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoamiv2
  labels:
    app: containous
    name: whoamiv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containous
      task: whoamiv2
  template:
    metadata:
      labels:
        app: containous
        task: whoamiv2
    spec:
      containers:
        - name: whoamiv2
          image: containous/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoamiv1
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: containous
    task: whoamiv1

---
apiVersion: v1
kind: Service
metadata:
  name: whoamiv2
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: containous
    task: whoamiv2

---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: weighted-whoami
spec:
  weighted:
    sticky:
      cookie:
        name: lvl1
    services:
      - name: whoamiv1
        port: 80
        sticky:
          cookie:
            httpOnly: false
            name: lvl2
            secure: true
            sameSite: strict
        weight: 80
      - name: whoamiv2
        port: 80
        sticky:
          cookie:
            httpOnly: false
            name: lvl2
            secure: true
            sameSite: strict
        weight: 20          

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - match: "Host(`localhost`) && PathPrefix(`/whoami`)"
      kind: Rule
      services:
        - name: weighted-whoami
          kind: TraefikService

```

I suggest heading to the [forums](https://community.containo.us/) if you have any further configuration issues on this matter.
