### ISSUE TITLE
BasicAuth middleware: headerField option doesn't seem to work

### ISSUE THREAD

**Issue by toussa** [containous/traefik#6884]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to add basic auth (with TLS) to my portainer stack. As Portainer is also using the `Authorization` header to handle JWT, I wanted to change the portainer's header name used to handle basic authentication.

### What did you expect to see?

Basic-Auth using the given `headerField` name header instead of `Authorization` to handle user authentication and allows other backend services to freely use `Authorization` (for JWT, ...)

### What did you see instead?

nothing different with or without `headerField`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik:v2.2 version
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
My server is on Debian 9.x and I'm using dowker swarm.

```console
$ docker version
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9424aeaee9
 Built:             Thu May 28 22:17:06 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.10
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9424aeaee9
  Built:            Thu May 28 22:15:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
My `stack.yml`
```yaml
version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    command:
      - --global.checknewversion=true
      - --api.dashboard=true
      - --log.level=INFO      
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.entryPoint=traefik
      - --metrics.prometheus.manualrouting=true # because we create our own router

      - --providers.file.directory=/file_provider_d #we use the file provider for common definitions and outside-docker rules
      - --providers.file.watch=true

      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.docker.swarmmoderefreshseconds=10 #default: 15s
      - --providers.docker.watch=true #default: true

      - --entrypoints.web.address=:80
      - --entryPoints.web.transport.respondingTimeouts.readTimeout=30s # default: 0s (no timeout)
      - --entryPoints.web.transport.respondingTimeouts.writeTimeout=30s # default: 0s (no timeout)
      - --entryPoints.web.transport.respondingTimeouts.idleTimeout=120s # default: 180s
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.web.http.middlewares=gzipResponseCompress@file # by default we'll compress the response

      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=30s # default: 0s (no timeout)
      - --entryPoints.websecure.transport.respondingTimeouts.writeTimeout=30s # default: 0s (no timeout)
      - --entryPoints.websecure.transport.respondingTimeouts.idleTimeout=120s # default: 180s
      - --entrypoints.websecure.http.tls.certResolver=my_resolver # let's encrypt
      - --entrypoints.websecure.http.middlewares=gzipResponseCompress@file # by default we'll compress the response
  
     # Uncomment the line to use Let's Encrypt's staging server, leave commented to go to prod.
     #- --certificatesresolvers.my_resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.my_resolver.acme.email=contact@website.com
      - --certificatesresolvers.my_resolver.acme.storage=/letsencrypt/acme.json
     # Use a TLS-ALPN-01 challenge:
      - --certificatesresolvers.my_resolver.acme.tlschallenge=true
     # DNS-01 ACME challenge rather than HTTP-01 or TLS-ALPN-01 challenge. Mandatory for wildcard certificates
      - --certificatesresolvers.my_resolver.acme.dnschallenge=true
      - --certificatesresolvers.my_resolver.acme.dnschallenge.provider=gandiv5
      - --certificatesresolvers.my_resolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53

    environment:
      - "GANDIV5_API_KEY_FILE=/run/secrets/gandiv5-api-key"
    volumes:
      - letsencrypt:/letsencrypt
      - /home/itsmemario/workspace/traefik/file_provider_d:/file_provider_d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    secrets:
      - gandiv5-api-key
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.api.rule=Host(`traefik.website.com`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.middlewares=proxyMonitoringAuth@file"
        - "traefik.http.routers.api.entryPoints=websecure"

        - "traefik.http.routers.prometheus_metrics.rule=Host(`traefik.website.com`) && PathPrefix(`/metrics`)"
        - "traefik.http.routers.prometheus_metrics.service=prometheus@internal"
        - "traefik.http.routers.prometheus_metrics.middlewares=proxyMonitoringAuth@file"
        - "traefik.http.routers.prometheus_metrics.entryPoints=websecure"

        - "traefik.http.services.dummy_api_service.loadbalancer.server.port=9999" # mandatory for docker swarm

networks:
  web:
    external: true

volumes:
  letsencrypt:

secrets:
  gandiv5-api-key:
    file: secrets/gandiv5_apikey
```
and my `file_provider_d/common_definitions.yml`

```yaml
http:
  middlewares:

    #this auth is here to protect monitoring services by traefik before they're routing to.
    proxyMonitoringAuth:
      basicAuth:
        realm: "Monitoring"
        #        removeHeader: true
        headerField: "X-MonitorAuth-User"
        users:
          - 'test:$2y$05$o8JI3KtQhvYPMMIGGiPnpOiWikTAqwOlgrGx.xOiM.K5s1nT16hFK' # test:test

    #https://docs.traefik.io/middlewares/compress/ 
    gzipResponseCompress:
      compress: {}

```
[Edit] adding some info that I hope useful:
I talked about portainer as the intent behind, but it's the same with traefik's dashboard (see above dynamic config).

Here is the request details in my chrome inspector: 
```
---------- General ----------
Request URL: https://traefik.website.com/dashboard/
Request Method: GET
Status Code: 200 
Remote Address: xx.xx.xx.xx:443
Referrer Policy: no-referrer-when-downgrade

---------- Response Headers ----------
accept-ranges: bytes
content-encoding: gzip
content-length: 796
content-type: text/html; charset=utf-8
date: Wed, 03 Jun 2020 17:50:02 GMT
last-modified: Wed, 29 Apr 2020 18:00:36 GMT
status: 200
vary: Accept-Encoding

---------- Request Headers ----------
:authority: traefik.website.com
:method: GET
:path: /dashboard/
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,es-419;q=0.6,es;q=0.5
authorization: Basic YXRpcblablablabalaE=
cache-control: no-cache
dnt: 1
pragma: no-cache
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
```
