### ISSUE TITLE
Traefik not proxying secure cockroachdb gRPC port.

### ISSUE THREAD

**Issue by razuos** [containous/traefik#6887]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

I have declared an ingress for the cockroachdb grpc service using h2c but it didn't work.

Here's my service and ingress definition:
```
---
apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: cockroach-grpc
  labels:
    app: cockroachdb
spec:
  type: LoadBalancer
  ports:
  # The main port, served by gRPC, serves Postgres-flavor SQL, internode
  # traffic and the cli.
  - port: 26257
    targetPort: 26257
    name: grpc
  selector:
    app: cockroachdb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cockroach-grpc
  annotations:
    kubernetes.io/ingress.class: traefik 
    traefik.protocol: h2c
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
  - host: cockroach.${DOMAIN}
    http:
      paths:
      - path: /
        backend:
          serviceName: cockroach-grpc
          servicePort: grpc
```
The thing is: I'm using a secure installation of CockroachDB on bare metal k8s, i'm using self signed certificates too. For the admin UI i've succesfully configured ssl passtrough using this TCP ingress route:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: cockroach-ui
spec:
  entryPoints:                  
    - websecure
  routes:                       
  - match: HostSNI(`admin.cockroach.${DOMAIN}`)         
    services:                   
    - name: cockroachdb-public-ui                 
      port: 8080                                  
  tls:                          
    passthrough: true 
```
The connection string used to connect to the db uses ssl certs, i don't think the http ingress supports ssl passthrough.
When i expose the grpc port using a regular k8s service, it works perfectly.

### What did you expect to see?

The sql shell connecting successfuly.

### What did you see instead?

The following error:
```
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

read tcp 10.0.1.2:33582->10.0.3.18:443: i/o timeout
Failed running "sql"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
time="2020-06-04T16:50:21Z" level=info msg="Traefik version 2.2.1 built on 2020-04-29T18:02:09Z"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Using as a ingress controller on k8s, here's the yaml (removing rbac definitions for better readability)
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik
    release: traefik
  name: traefik
  namespace: kube-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefik
  template:
    metadata:
      labels:
        app: traefik
        release: traefik
    spec:
      containers:
      - args:
        - --api
        - --api.insecure=true
        # Set insecure to fals to enable basic auth
        #- --api.insecure=false
        - --api.dashboard=true
        - --accesslog
        - --global.checknewversion=true
        - --entryPoints.traefik.address=:8100
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443

        # permanent redirecting of all requests on http (80) to https (443)
        # - --entrypoints.web.http.redirections.entryPoint.to=websecure
        # - --entrypoints.websecure.http.tls.certResolver=default

        # Let's Encrypt Configurtion:
        # Please note that this is the staging Let's Encrypt server configuration.
        # Once you get things working, you should remove that following line.
        # - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
        # - --certificatesresolvers.default.acme.email={YOUR-E-MAIL}
        # - --certificatesresolvers.default.acme.storage=/var/lib/traefik/acme.json
        # - --certificatesresolvers.default.acme.tlschallenge=true

        - --ping=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true

        # Use log level= INFO or DEBUG
        - --log.level=DEBUG
        image: traefik:2.2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 8100
          name: admin
          protocol: TCP
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: websecure
          protocol: TCP

        # optional storage 
        # enable this option only in case you have defined a persistence volume claim
        #volumeMounts:
        #- name: traefik-data
        #  mountPath: /var/lib/traefik

        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
    release: traefik
  name: traefik
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: traefik
    release: traefik
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: ${TRAEFIK_INGRESS_IP}
status:
  loadBalancer: {}
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
The log doesn't show anything in particular.

Thanks for the help
