### ISSUE TITLE
IngressRoute/Ingress with both http and https entrypoints

### ISSUE THREAD

**Issue by tpatrascu** [containous/traefik#6894]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured a plain IngressRoute:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute
  namespace: traefik
spec:
  routes:
  - match: Host(`myhost.mydomain.tld`)
    kind: Rule
    services:
    - name: myservice
      kind: Service
      passHostHeader: true
      port: 80
  tls:
    secretName: mysecret
```

In this setup, the https endpoint works, but the http endpoint/router points to something else than my service and returns 404. I want both http and https endpoints to be active and point to my service, I don't want to redirect to https.

Then I read this forum post https://community.containo.us/t/http-entrypoint-404s-with-2-2-0-rc2/4894/14. Don't really understand most of it, but it gave me the idea of implementing the following workaround:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute-http
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`myhost.mydomain.tld`)
    kind: Rule
    priority: 100
    services:
    - name: myservice
      kind: Service
      passHostHeader: true
      port: 80

```

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute-https
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`myhost.mydomain.tld`)
    kind: Rule
    priority: 50
    services:
    - name: myservice
      kind: Service
      passHostHeader: true
      port: 80
  tls:
    secretName: mysecret
```
So now the two ingresses should be completely separate, not really sure about the priority setting, doesn't seem to be doing anything, also doesn't work without it, but anyway, the API/dashboard tells me this:

Routers:

```
  {
    "entryPoints": [
      "web"
    ],
    "service": "traefik-myservice-http-96383b9663e8318c5cb",
    "rule": "Host(`myhost.mydomain.tld`)",
    "priority": 100,
    "status": "enabled",
    "using": [
      "web"
    ],
    "name": "traefik-myservice-http-96383b9663e8318c5cb@kubernetescrd",
    "provider": "kubernetescrd"
  },
  {
    "entryPoints": [
      "websecure"
    ],
    "service": "traefik-myservice-https-896383b9663e8318c5cb",
    "rule": "Host(`myhost.mydomain.tld`)",
    "priority": 50,
    "tls": {},
    "status": "enabled",
    "using": [
      "websecure"
    ],
    "name": "traefik-myservice-https-896383b9663e8318c5cb@kubernetescrd",
    "provider": "kubernetescrd"
  },
```

Services:

```
  {
    "loadBalancer": {
      "servers": [
        {
          "url": "http://192.168.15.20:7480"
        },
        {
          "url": "http://192.168.15.22:7480"
        },
        {
          "url": "http://192.168.15.23:7480"
        }
      ],
      "passHostHeader": true
    },
    "status": "enabled",
    "usedBy": [
      "traefik-myservice-http-896383b9663e8318c5cb@kubernetescrd"
    ],
    "serverStatus": {
      "http://192.168.15.20:7480": "UP",
      "http://192.168.15.22:7480": "UP",
      "http://192.168.15.23:7480": "UP"
    },
    "name": "traefik-myservice-http-896383b9663e8318c5cb@kubernetescrd",
    "provider": "kubernetescrd",
    "type": "loadbalancer"
  },
  {
    "loadBalancer": {
      "servers": [
        {
          "url": "http://192.168.15.20:7480"
        },
        {
          "url": "http://192.168.15.22:7480"
        },
        {
          "url": "http://192.168.15.23:7480"
        }
      ],
      "passHostHeader": true
    },
    "status": "enabled",
    "usedBy": [
      "traefik-myservice-https-896383b9663e8318c5cb@kubernetescrd"
    ],
    "serverStatus": {
      "http://192.168.15.20:7480": "UP",
      "http://192.168.15.22:7480": "UP",
      "http://192.168.15.23:7480": "UP"
    },
    "name": "traefik-myservice-https-896383b9663e8318c5cb@kubernetescrd",
    "provider": "kubernetescrd",
    "type": "loadbalancer"
  }
```

So this looks legit, the only problem is that the http service is a lie, I still get 404 on the http endpoint and have no idea where the request goes and only https works. Same issues appear when using the k8s ingress provider.

### What did you expect to see?

Both web and websecure entrypoints should go to my application k8s service, unless I explicitly want to redirect or do something else.

### What did you see instead?

When TLS is enabled on a router which matches a hostname I found no workaround for making plain http also work for that hostname. Should not require a workaround anyway.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.18.3, using the traefik helm chart version 8.2.1
