### ISSUE TITLE
Missing error message when file provider is misconfigured

### ISSUE THREAD

**Issue by andig** [containous/traefik#6896]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Condifured providers as:

```
providers:
  file:
   directory: /etc/traefik/routes.yaml
    watch: true
```

### What did you expect to see?

Error message since `directory` should really have been `filename`.

### What did you see instead?

No error, no help with finding the configuration issue.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.2.1
