### ISSUE TITLE
Documentation: Routing Provider Docker Example Config Clarification

### ISSUE THREAD

**Issue by kbrs-miaha** [containous/traefik#6898]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Visited the docs [https://docs.traefik.io/routing/providers/docker/](https://docs.traefik.io/routing/providers/docker/)

### What did you expect to see?
From the 2nd example for the [Docker Provider Docs](https://docs.traefik.io/routing/providers/docker/) I expected to see:

```yaml
version: "3"
services:
  my-container:
    # ...
    labels:
      - traefik.http.routers.my-container.rule=Host(`example.com`)
      # Tell Traefik to use the port 12345 to connect to `my-container`
      - traefik.http.services.my-container.loadbalancer.server.port=12345
```
Note change in last line:
`- traefik.http.services.my-container.loadbalancer.server.port=12345` from `my-service` to `my-container`.

### What did you see instead?

```yaml
version: "3"
services:
  my-container:
    # ...
    labels:
      - traefik.http.routers.my-container.rule=Host(`example.com`)
      # Tell Traefik to use the port 12345 to connect to `my-container`
      - traefik.http.services.my-service.loadbalancer.server.port=12345
```
The name of the service appears to be inconsistent.

### Output of `traefik version`: (_What version of Traefik are you using?_)
N/A

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
N/A
```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
N/A
```
(paste your output here)
```
