### ISSUE TITLE
Poor download performance when gzip enabled between container and traefik

### ISSUE THREAD

**Issue by hlidotbe** [containous/traefik#6905]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Setup traefik 2.0 on a single node docker swarm
- Started two basic nginx + php services (php irrelevant, not used)
- Created a test file with `dd if=/dev/urandom of=test bs=4194304 count=500`
- Tried to download the file through traefik, between container and between host and container

### What did you expect to see?

- More or less the same performances, a slight slowdown being expected for traefik overhead

### What did you see instead?

The download is 2, 2.5x slow with gzip disabled and it's capped at ~30MB/s if gzip is enabled in the container 

- container - container with gzip: ~2.5GB/s
- container - container without gzip: ~2.5GB/s
- host - container with gzip: ~2.5GB/s
- host - container without gzip: ~2.5GB/s
- host - traefik - container with gzip: ~30MB/s
- host - traefik - container withough gzip: ~1GB/s

### Output of `traefik version`: (_What version of Traefik are you using?_)

``
Version:      2.0.7
Codename:     montdor
Go version:   go1.13.5
Built:        2019-12-09T17:51:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: '3.7'

services:
  traefik:
    image: traefik:2.0
    ports:
      - 80:80
      - 443:443
      - 9090:9090
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 4000:4000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./certs:/etc/certs
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.traefik.address=:9090"
      - "--entrypoints.gulp.address=:3000"
      - "--entrypoints.gulp-ui.address=:3001"
      - "--entrypoints.gulp-weinre.address=:3002"
      - "--entrypoints.vue.address=:4000"
      - "--log=true"
      - "--log.filepath=/etc/traefik/logs/traefik.log"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.network=local_traefik"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.swarmMode=true"
    networks:
      - traefik
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
```

```nginx
worker_processes 2;
daemon off;
user www-data www-data;

events {
  worker_connections  1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  sendfile        on;

  keepalive_timeout 2;
  client_max_body_size 500m;

server {
  listen 80;

  access_log stdout;
  error_log stderr;

  gzip off;
  gzip_proxied any;
  gzip_types
        image/svg+xml
        text/css
        text/javascript
        text/xml
        text/plain
        application/javascript
        application/x-javascript
        application/json
        application/octet-stream;

  root /var/www/;
  index index.html index.php;
  client_max_body_size 200M;

  add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

  error_page 404 /index.html;

  location /robots.txt {
    return 200 "User-agent: *\nDisallow: /\n";
  }

  location / {
    autoindex on;
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php {
    ...
  }
}
}
```

This was tested on a Dell XPS laptop (Core i7-8550U with 16GB of RAM) and no swarm services running beside traefik and the two nginx containers. The same test on dedicated servers yielded the same results. edit: the same results have been obtained with Traefik 1.7 on a standard docker server.

This might be a misconfiguration or a misunderstanding of how traefik work but I did not expect that much of an impact on the download performances.
