### ISSUE TITLE
traefik.enable must be a string

### ISSUE THREAD

**Issue by rgajason** [containous/traefik#6919]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```
     labels:
        traefik.enable: true
```

### What did you expect to see?

No error

### What did you see instead?

Error during stack deploy:

```
services.reverse-proxy.deploy.labels.traefik.enable must be a string, number or null
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  format = "json"
  level = "INFO"

[accessLog]
  format = "json"

  [accessLog.fields]
    defaultMode = "keep"

    [accessLog.fields.names]
      StartUTC = "drop"

    [accessLog.fields.headers]
      [accessLog.fields.headers.names]
        Authorization = "drop"

[metrics]
  [metrics.prometheus]
    buckets = [0.1, 0.3, 1.2, 5.0]
    entryPoint = "health"

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
      permanent = true

  [entryPoints.websecure]
    address = ":443"

    [entryPoints.websecure.http.tls]

  [entryPoints.health]
    address = ":8080"

  [entryPoints.api]
    address = ":8443"

    [entryPoints.api.http.tls]

[providers]
  [providers.docker]
    constraints = "Label(`traefik_tag`, `mynet`)"
    endpoint = "tcp://my-swarm-endpoint:443"
    exposedByDefault = false
    network = "mynet"
    swarmMode = true
    watch = true

    [providers.docker.tls]
      ca = "/run/secrets/bundle_ca_crt"
      cert = "/run/secrets/bundle_user_crt"
      key = "/run/secrets/bundle_user_key"

  [providers.file]
    filename = "/etc/traefik/traefik-dynamic.toml"

# Labels on the service in the compose file complete this configuration
[api]
  dashboard = true

[ping]
  entryPoint = "health"
```

This appears to be the same or similar as #4741

### Workaround:

```
      labels:
        traefik.enable: 'true'
```

Per https://github.com/containous/traefik/issues/4741#issuecomment-480593067 I'm guessing that another workaround is using `name=value` label syntax:

```
      labels:
        - "traefik.enable=true"
```

**Comment by ldez** [comment]
Hello,

this error happen when your using swarm, I don't know why.

It works without swarm.

**Comment by mbrodala** [comment]
@rgajason What version of Docker / Docker Compose do you use? Did you update any of these recently?

**Comment by rgajason** [comment]
I can't be sure of what version of Docker we were running a year ago when I originally reported this.  My best guess would be 19.03.  When we deploy Traefik it is via `docker stack deploy ...` with a compose YAML file specifying syntax version 3.7.  For example:

```
version: '3.7'

configs:
  traefik_toml:
    file: ./traefik.toml
  traefik_dynamic_toml:
    file: ./traefik-dynamic.toml

networks:
  net:
    driver: overlay
    attachable: true

secrets:
  bundle_ca_crt:
    file: ./bundle/ca.pem
  bundle_user_crt:
    file: ./bundle/cert.pem
  bundle_user_key:
    file: ./bundle/key.pem
  traefik_crt:
    file: ./STAR.domain-with-chain.pem
  traefik_key:
    file: ./STAR.domain.key
  api_auth_htpasswd:
    file: ./api-auth-htpasswd

services:
  reverse-proxy:
    image: traefik:2.2
    networks:
      - net
    ports:
      - '10080:80'         # HTTP
      - '10443:443'        # HTTPS
      - '18080:8080'       # Ping endpoint
      - '18443:8443'       # API (HTTPS)
    secrets:
      - bundle_ca_crt
      - bundle_user_crt
      - bundle_user_key
      - traefik_crt
      - traefik_key
      - api_auth_htpasswd
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
      - source: traefik_dynamic_toml
        target: /etc/traefik/traefik-dynamic.toml
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash.host:12201
        tag: 'domain-traefik'
    environment:
      - 'TZ=America/Chicago'
    volumes:
      - 'zoneinfo:/usr/share/zoneinfo:ro'
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        traefik_tag: domain
        traefik.enable: 'true'
        traefik.http.routers.api.entrypoints: api
        traefik.http.routers.api.rule: 'Host(`domain`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
        traefik.http.routers.api.service: 'api@internal'
        traefik.http.routers.api.middlewares: apiauth
        traefik.http.middlewares.apiauth.basicauth.usersfile: /run/secrets/api_auth_htpasswd
        traefik.http.services.dummy-svc.loadbalancer.server.port: 10000

volumes:
  zoneinfo:
    external: true
```
