### ISSUE TITLE
tls.options only applied when using TOML file provider format

### ISSUE THREAD

**Issue by SPodjasek** [containous/traefik#6920]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I wanted to enforce minimum TLS version and limit possible ciphers as described here (https://docs.traefik.io/https/tls/#tls-options). My config file is in YAML format and I wasn't able to do this. After reading through existing issues (https://github.com/containous/traefik/issues/6181, https://github.com/containous/traefik/issues/5507) and community discussions (https://community.containo.us/t/unable-to-set-tls-options/2437) I've split my config file to multiple files, moved `tls` section to TOML format and it worked instantly.

I don't know if this is YAML related, but for at least one person besides me (https://community.containo.us/t/unable-to-set-tls-options/2437/7) switching from YAML to TOML solved the issue.

### Initial config file excerpt

```yaml
## /etc/traefik/traefik.yml

providers:
  docker: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
      tls:
        options: "mintls12@file"
        certResolver: leresolver
        domains:
        - main: example.io
          sans:
          - "*.example.io"
tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls12:
      minVersion: VersionTLS12
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
```

Errors seen in log file after startup:

```
time="2020-06-14T22:48:17Z" level=debug msg="unknown TLS options: mintls12@file" routerName=io-example-web@docker entryPointName=websecure
```

### Working file after split (only changes)

```yaml
## /etc/traefik/traefik.yml

providers:
  file:
    directory: "/conf/"
    watch: true
  docker: {}
```
```toml
## /conf/tls.toml
[tls.options]

  [tls.options.default]
    minVersion = "VersionTLS12"

  [tls.options.mintls12]
    minVersion = "VersionTLS12"
    curvePreferences = ["CurveP521", "CurveP384"]
    sniStrict = true
    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
    ]
```

Normal log message:

```
time="2020-06-14T23:11:07Z" level=debug msg="Adding route for example.io with TLS options mintls12@file" entryPointName=websecure
```

### Output of `traefik version`:
```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

**Comment by SantoDE** [comment]
Hello @SPodjasek,

thanks a lot for your interest in the project.

You saw the first issue, as you did put dynamic configuration in the static configuration where its not evaluated. Thus, its working in your second example as its treated correctly as dynamic configuration then.

**Comment by SPodjasek** [comment]
@SantoDE Thank you very much for this response.
To summarize:
Default config file `/etc/traefik/traefik.(to|y)ml` is considered `static` configuration and it's not possible for that configuration to be picked in any way on 'dynamic side'. 

So maybe there should be some side note about that in docs? 
I mean, my mental flow was that if I set both options in the same file (tls.options & entryPoints using this options), they should be visible and usable to each other - apparently they aren't and IMHO it's a bit confusing.

**Comment by ldez** [comment]
in the v2, the [dynamic configuration](https://docs.traefik.io/v2.2/getting-started/configuration-overview/#the-dynamic-configuration) and the [static configuration](https://docs.traefik.io/v2.2/getting-started/configuration-overview/#the-static-configuration) must be defined in separated files:

- https://docs.traefik.io/v2.2/getting-started/configuration-overview/#the-dynamic-configuration
- https://docs.traefik.io/v2.2/getting-started/configuration-overview/#the-static-configuration

**Comment by SPodjasek** [comment]
Maybe if mine initial, static config file would look just as simple as this:
```yaml
## /etc/traefik/traefik.yml

providers:
  file:
    directory: "/conf/"
    watch: true
  docker: {}
```
and every other configuration would be placed in `/conf/*` directory, despite config file format - it would work for me from the beginning.
