### ISSUE TITLE
Breaking change between v2.2.0 and v2.2.1

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6929]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I believe https://github.com/containous/traefik/commit/4da63c92370758da56cf033104c2d42aff1bc4b5 introduced a breaking change in the v2.2 line.

We have rate limiter middlewares which use to work on v2.2.0 and that do not work anymore in v2.2.1:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: data-collect-rate-limiting
spec:
  rateLimit:
    average: 30
    burst: 60
    sourceCriterion:
      requestHeaderName: X-ATT-DeviceId
      requestHost: true
```

I get this error in the logs:

```json
{"entryPointName":"https","level":"error","msg":"requestHost and RequestHeaderName are mutually exclusive","routerName":"sumo-data-collect-d93e99b443bfcfc02c94@kubernetescrd","time":"2020-06-17T08:05:00Z"}
```

And the routers that use this middleware are in error state.

CC @mpl
