### ISSUE TITLE
Can't traefik use tcp to route non-tls mysql?

### ISSUE THREAD

**Issue by webees** [containous/traefik#6943]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Experience traefik's tcp routing feature using mongo.
- Experience traefik's tcp routing feature using mysql.
- Read #4981
- Read #5155

### What did you expect to see?

Ability to connect to database through Navicat.

### What did you see instead?

![image](https://user-images.githubusercontent.com/5155291/85201260-8a668c80-b330-11ea-9f96-51118ad0c95c.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

#### traefik-docker-compose.yml
```yaml
version: "3.5"
services:
  traefik:
    restart: always
    container_name: traefik
    image: traefik:latest
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # ping
      - "1001:1001" # mysql001
      - "1002:1002" # mysql002
      - "2000:2000" # mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./config/tls:/config/tls:ro
    healthcheck:
      test: traefik healthcheck --ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  traefik:
    external: true
```

#### traefik.yml
```yaml
providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    watch: true
    directory: /etc/traefik
    debugLogGeneratedTemplate: false

log:
  level: ERROR

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  mysql001:
    address: ":1001"
  mysql002:
    address: ":1002"
  mongo:
    address: ":2000"
```

#### mysql-docker-compose.yml

```yaml
version: "3.5"

services:
  mysql001:
    restart: always
    container_name: mysql001
    image: mysql:5.7.30
    networks:
      - traefik
    ports:
      - "3306:3306"
    volumes:
      - ./mysql001:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "YES"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mysql001.rule=HostSNI(`*`)
      - traefik.tcp.routers.mysql001.entrypoints=mysql001
      - traefik.tcp.services.mysql001.loadbalancer.server.port=3306

  mysql002:
    restart: always
    container_name: mysql002
    image: mysql:5.7.30
    networks:
      - traefik
    expose:
      - 3306
    volumes:
      - ./mysql002:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "YES"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mysql002.rule=HostSNI(`*`)
      - traefik.tcp.routers.mysql002.entrypoints=mysql002
      - traefik.tcp.services.mysql002.loadbalancer.server.port=3306

networks:
  traefik:
    external: true
```

#### my.cnf
```cnf 
[mysqld]
skip_host_cache
explicit_defaults_for_timestamp = true

bind-address = 0.0.0.0
skip-name-resolve
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
There doesn't seem to be any unusual output.
```

### other

- All is well on port 3306 of mysql001.
