### ISSUE TITLE
Traefik only copies a single IP from a Kubernetes Service to the Ingress

### ISSUE THREAD

**Issue by iameli** [containous/traefik#6950]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm running Traefik on a k3s cluster using the v2 Helm Chart. I have this specified, so as to populate all of the Ingress statuses from the IPs in the LoadBalancer service:

```
--providers.kubernetesIngress.ingressEndpoint.publishedService=default/base-ingress-traefik
```

The Service in question has three IPs:

```yaml
apiVersion: v1
kind: Service
metadata
  [ ... etc  ... ]
  name: base-ingress-traefik
  namespace: default
spec:
  [ ... etc .. ]
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 194.61.20.16
    - ip: 194.61.20.198
    - ip: 194.61.20.61
```

However, Traefik is only copying one of the three IPs from the LoadBalancer to the Ingress status:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staging-livepeer-api
  namespace: default
spec: [redacted]
status:
  loadBalancer:
    ingress:
    - ip: 194.61.20.16
```

This isn't great for load balancing, I'd like all three to be there! Am I doing something wrong?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here's the Helm values:

```yaml
  deployment:
    replicas: 3
  service:
    type: LoadBalancer
  affinity: {}
  additionalArguments:
    - "--accesslog=true"
    - "--entrypoints.websecure.http.tls=true"
    - "--providers.kubernetesIngress.ingressEndpoint.publishedService=default/base-ingress-traefik"
  rbac:
    enabled: true
  service:
    annotations:
      # livepeer.live/external-dns: "true"
      external-dns.alpha.kubernetes.io/ttl: "120"
```
