### ISSUE TITLE
Bug in PathPrefix rule and matching routes

### ISSUE THREAD

**Issue by salehi** [containous/traefik#6953]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I used a PathPrefix rule to route /blog to my wordpress,
```
rule=Host(`XXX`) && PathPrefix(`/blog`)
```

### What did you expect to see?
I want only the following paths to be routed to wordpress:
* /blog
* /blog/
* /blog/X

### What did you see instead?
Every route starting with /blog routed to wordpress including:
* /blog
* /blog/
* /blog/X
* /blog-X
* /blogger

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Here is the sth like my wordpress stack:

```
version: '3.7'
services:
  nginx: 
    image: ${CI_REGISTRY_IMAGE}/ngx
    deploy:
      labels:
      - "traefik.enable=true"

      - "traefik.http.services.X.loadbalancer.server.port=80"
      - "traefik.http.services.X.loadbalancer.server.scheme=http"

      - "traefik.http.routers.X.entrypoints=web"
      - "traefik.http.routers.X.rule=Host(`XXX`) && PathPrefix(`/blog`)"

  wordpress:
    image: ${CI_REGISTRY_IMAGE}/fpm
    environment:
      WORDPRESS_DB_HOST: a
      WORDPRESS_DB_USER: a
      WORDPRESS_DB_PASSWORD: SECRET
      WORDPRESS_DB_NAME: a

  wpdb:
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=SECRET
    - MYSQL_USER=a
    - MYSQL_PASSWORD=a
    - MYSQL_DATABASE=a
    command: 
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
```
