### ISSUE TITLE
Logs flooded with "Error while Hello: bufio: buffer full"

### ISSUE THREAD

**Issue by jnsdrtlf** [containous/traefik#6956]
### Do you want to request a *feature* or report a *bug*?

**Bug**

### What did you do?

Setup two servers on [hetzner.com](https://www.hetzner.com/):
 - **CPX21**: AMD based, 3 vCPU, 4 GB RAM
 - **CX21**: Intel based, 2 vCPU, 4GB RAM

Deployed some (~7) web services using Docker Compose and Traefik.

### What did you expect to see?

They should both perform similarly

### What did you see instead?

Performance is ok on both machines (did not benchmark). However, when taking a look at the logs, the AMD (Ryzen) based server is flooded with this:

```
...
time="2020-06-23T14:05:02Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:05:51Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:06:40Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:09:40Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:16:19Z" level=error msg="Error while Hello: EOF"
time="2020-06-23T14:19:10Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:22:23Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:28:47Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:34:37Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:35:06Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:35:29Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:36:39Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:44:37Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T14:53:38Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:10:52Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:24:45Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:28:02Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:40:19Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:41:05Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:42:27Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:44:46Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:45:19Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:49:20Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:50:26Z" level=error msg="Error while Hello: bufio: buffer full"
time="2020-06-23T15:53:48Z" level=error msg="Error while Hello: bufio: buffer full"
...
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

**CX21** (Intel)
```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

**CPX21** (AMD)
```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

As this is running in production, I do not feel happy to share the complete config ;) I'll setup an example config soon, wanted to get this out there ;)

**`traefik.yml`**
```yaml
---
global:
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /foo/traefik-conf.yml
    watch: true

certificatesResolvers:
  certs-le:
    acme:
      email: foo@bar
      storage: acme.json
      # Enable for staging server
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: http


accessLog:
  filePath: "./access.log"
  bufferingSize: 100
```

**`traefik-conf.yml`**
```yaml
---
http:
  middlewares:
    secure-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    traefik-auth:
      basicAuth:
        users:
          - "user:password"
```

**docker-compose.yml**
```yaml
version: '3'
services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    container_name: traefik
    command: --docker --accesslog --logLevel="INFO"
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-conf.yml:/foo/traefik-conf.yml
      - ./acme.json:/acme.json
      - ./access.log:/access.log
    labels:
      - "traefik.enable=true"
      # HTTP Config
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.org`)"
      - "traefik.http.routers.traefik.middlewares=secure-redirect@file"
      # HTTPS Config
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.example.org`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth@file"
      - "traefik.http.routers.traefik-secure.tls.certresolver=certs-le"
      - "traefik.http.routers.traefik-secure.service=api@internal"

...
```

As the only difference between both servers is that one is based on AMD, I suspected that this might be the cause. However, I have no idea about what is going on
