### ISSUE TITLE
Bug with certificate

### ISSUE THREAD

**Issue by Hedgehogues** [containous/traefik#6957]
*bug*

### What did you do?

Hello. I think there bug with certificate. I have two entrypoints with certificate, therefore I cannot use the `[acme]`. Look, I have next config:

I generate the certificates this command and set all settings as default (with press button ENTER):

`openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out l.f.p.cert -keyout l.f.p.key`

After starting docker-compose, I go to the `a-s-s.f.p:61295` and I get next log into traefik:

`reverse-proxy_1                   | time="2020-06-24T07:52:48Z" level=debug msg="http: TLS handshake error from 109.252.101.42:2500: remote error: tls: unknown certificate"`

### What did you expect to see?

I want to use https with tls certificates

### What did you see instead?

I see http instead of https by a-s-s.f.p:61295

### Output of `traefik version`: (_1.7.24_)

With debug-level

```
`reverse-proxy_1                   | time="2020-06-24T07:52:48Z" level=debug msg="http: TLS handshake error from 109.252.101.42:2500: remote error: tls: unknown certificate"`
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```

logLevel = "DEBUG"

defaultEntryPoints = ["http", "https", "auth"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  # https is the default
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
     [[entryPoints.https.tls.certificates]]
       certFile = "/certs/l.f.p.cert"
       keyFile = "/certs/l.f.p.key"
 [entryPoints.auth]
   address = ":61295"
   [entryPoints.auth.tls]
    [[entryPoints.auth.tls.certificates]]
       certFile = "/certs/l.f.p.cert"
       keyFile = "/certs/l.f.p.key"



# [acme]
# email = "h@bk.ru"
# storageFile = "/etc/traefik/acme/acme.json"
# entryPoint = "https"


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "l.f.p"
watch = true
exposedbydefault = false
```

I use docker-compose for deploying. I have next docker-compose:

```
reverse-proxy:
        image: traefik:1.7.24
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
            - ./traefik/certs/:/certs/
        networks:
            - web
        ports:
            - "80:80"
            - "443:443"
            - "61295:61295"
            - "41371:41371"
            - "51229:51229"
            - "50100:50100"
            - "37247:37247"
    grader-v2-auth-service-stage:
        env_file:
            - test.env
        image: "84.1.9.0:443/grader-v2-auth-service:1.1.1"
        restart: always
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.backend=grader-v2-auth-service-stage"
            - "traefik.frontend.rule=Host:a-s-s.f.p"
            - "traefik.port=61295"
            - "traefik.docker.network=web"
```
