### ISSUE TITLE
REST Provider configuration clears after restart.

### ISSUE THREAD

**Issue by wiliame** [containous/traefik#6962]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Applied backends and frontends configuration via rest provider. After restarting traefik, backends and frontends dissapear.

### What did you expect to see?

An option to make it permanent after restarts or a good practice to not loose it.

### What did you see instead?

An empty provider after restart.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.24
Codename:     maroilles
Go version:   go1.14.1
Built:        2020-03-25_04:34:11PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.proxy]
  address = ":8080"
        [entryPoints.proxy.tls]
      [[entryPoints.proxy.tls.certificates]]
      certFile = "/etc/traefik/certs/xxx.crt"
      keyFile = "/etc/traefik/certs/xxx.key"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/xxx.crt"
      keyFile = "/etc/traefik/certs/xxx.key"

# API definition
# Warning: Enabling API will expose Traefik's configuration.
# It is not recommended in production,
# unless secured by authentication and authorizations

[api]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "proxy"

  # Enable Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

  # Enable debug mode.
  # This will install HTTP handlers to expose Go expvars under /debug/vars and
  # pprof profiling data under /debug/pprof/.
  # Additionally, the log level will be set to DEBUG.
  #
  # Optional
  # Default: false
  #
  debug = true

  [api.statistics]
        recentErrors = 50

# Enable REST Provider.
[rest]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "proxy"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
