### ISSUE TITLE
Ingress Status is not updated

### ISSUE THREAD

**Issue by tahirali-endurance** [containous/traefik#6963]
<!-- PLEASE FOLLOW THE ISSUE TEMPLATE TO HELP TRIAGE AND SUPPORT! -->

### Do you want to request a *feature* or report a *bug*?

<!--
DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, please refer to one of the following:

- the Traefik community forum: https://community.containo.us/

-->

Bug

<!--

The configurations between 1.X and 2.X are NOT compatible.
Please have a look here https://docs.traefik.io/v2.0/getting-started/configuration-overview/.

-->

### What did you do?
**Step # 1**

Installed Traefik with helm:

```bash
helm install traefik traefik/traefik -n ctct-system \
    --set kubernetes.ingressEndpoint.useDefaultPublishedService=true \
    --set rbac.enabled=true \
    --set logLevel=DEBUG \
    --set accessLogs.enabled=true \
    --set dashboard.enabled=true
```    

**Step # 2**
Annotate Traefik service

```bash
kubectl annotate service traefik  -n ctct-system "external-dns.alpha.kubernetes.io/hostname=example.com"
```
This creates an A record and TXT record in AWS Route53 for example.com

**Step # 3**
Deploy an app. Showing ingress configuration:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-app
  labels:
    app: hello-app
  namespace: ctct-system    
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: panda.tahir-test.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-app
          servicePort: 80
```
          
### What did you expect to see?

Treafik should be updating the status field in Ingress object.

### What did you see instead?
Status field in ingress object remains empty.

```yaml
status:
  loadBalancer: {}
```	


### Output of `traefik version`: (_What version of Traefik are you using?_)

```text
Version:  2.2.1
Codename: chevrotin
Go version: go1.14.2
Built:  2020-04-29T18:02:09Z
OS/Arch:  linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Following is configuration for Traefik Pod.
```yaml
spec:                                                                                                                                                                                                       
   containers:                                                                                                                                                                                               
   - args:                                                                                                                                                                                                   
     - --global.checknewversion                                                                                                                                                                              
     - --global.sendanonymoususage                                                                                                                                                                           
     - --entryPoints.traefik.address=:9000/tcp                                                                                                                                                               
     - --entryPoints.web.address=:8000/tcp                                                                                                                                                                   
     - --entryPoints.websecure.address=:8443/tcp                                                                                                                                                             
     - --api.dashboard=true                                                                                                                                                                                  
     - --ping=true                                                                                                                                                                                           
     - --providers.kubernetescrd                                                                                                                                                                             
     - --providers.kubernetesingress
```


### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik time="2020-06-25T17:03:03Z" level=error msg="Cannot create service: subset not found" serviceName=hello-app namespace=default providerName=kubernetes servicePort=80 ingress=hello-app  │
