### ISSUE TITLE
h2c always result in rpc error

### ISSUE THREAD

**Issue by Clement-Jean** [containous/traefik#6968]
### What did you do?

I basically followed the [grpc hc2 tutorial](https://docs.traefik.io/user-guides/grpc/) with only HTTP support.

Note: 
- my ports are well exposed in the docker images (50051 for the grpc one)

### What did you expect to see?

I wanted to access the port 81 and do a normal gRPC request.

### What did you see instead?

However, I always get the following error: `rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"`

#### traefik.toml
```
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.grpc]
    address = ":81"

[providers]
  [providers.docker]
  [providers.file]
    filename = "/etc/traefik/dynamic_conf.toml"
```

#### dynamic_conf.toml

```
[http]
    [http.routers]
      [http.routers.grpc-server]
         entryPoints = ["grpc"]
         service = "grpc-server"
         rule = "Host(`my-site.com`)"

    [http.services]
        [http.services.grpc-server]
           [http.services.grpc-server.loadBalancer]
              [[http.services.grpc-server.loadBalancer.servers]]
                 url = "h2c://grpc.my-site.com:50051"

```

#### docker-compose.yaml

```
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.2
    ports:
       - "80:80"
       - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic_conf.toml:/etc/traefik/dynamic_conf.toml
    depends_on:
      - web-server
      - grpc-server
    networks:
      - frontend
      - backend
  web-server:
    image: backend
    labels:
      - traefik.http.routers.my-container.rule=Host(`my-site.com`)
    networks:
      backend:
          aliases:
             - web.my-site.com
  grpc-server:
    image: backend-grpc
    labels:
       - traefik.http.services.grpc-server.loadbalancer.server.scheme=h2c
    networks:
       backend:
          aliases:
             - grpc.my-site.com

networks:
   frontend:
   backend:

```
