### ISSUE TITLE
Kubernetes CRD - Headers middleware doesn't work

### ISSUE THREAD

**Issue by StarpTech** [containous/traefik#6973]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Create a headers middleware:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: production
spec:
  headers:
    sslRedirect: true
    sslProxyHeaders: true
---
```

### What did you expect to see?

Should work as documented. Additionally, the whole trafik container has stopped working.

### What did you see instead?

error in the traefik container logs:

```
2020-06-28T13:22:47.927674996Z E0628 13:22:47.927478       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.Headers: dynamic.Headers.SSLProxyHeaders: ReadMapCB: expect { or n, but found t, error found in #10 byte of ...|Headers":true,"sslRe|..., bigger context ...|09db9eda0"},"spec":{"headers":{"sslProxyHeaders":true,"sslRedirect":true}}}],"kind":"MiddlewareList"|...
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traeffik: 2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I use no route or ingress, I just added the middleware.
