### ISSUE TITLE
Docker container does not register right / not available if access too early

### ISSUE THREAD

**Issue by prodigy7** [containous/traefik#6980]
Currently I try to implement a setup with different docker environments. The setup includes a Traefik Proxy (docker-compose) and different environments (docker-compose setups too). My goal is, starting the proxy and add different docker environments on the fly. Now I have a strange behaviour:

I start the traevik proxy, then env 1 and the domains does also register. Means: When I call the address ``test.mydomain.de`` in my browser, I can access env 1. But when I start the proxy, call the address then and start then env 1, I can't reach the registered address ``test.mydomain.de`` in my browser. It does looks likes somehow it is cached, that the host wasn't available and traefik doesn't try it again to reach the host.

I would expext, that adding and remove on the fly is possible and traefik handles it right. Or is something wrong in my configuration?

Thats the schema:

```
               +--------------------+
               |      Internet      |
               +--------------------+
                         |
               +--------------------+
               |   Traefik Proxy    |
               +--------------------+
                  |          |
+--------------------+     +--------------------+
|        Env 1       |     |        Env 2       |
+--------------------+     +--------------------+
           |                          |
          ...                        ...
```

Now, my setup for ``Traefik Proxy`` is the following docker-compose.yml:

```
version: '3.5'

services:
  traefik:
    restart: always
    image: traefik:2.2.1
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.mydomain.de`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.middlewares.api-basic-auth.basicauth.users=${API_AUTH}'
      - 'traefik.http.routers.api.middlewares=api-basic-auth'
    volumes:
      - ./certs:/certs
      - ./etc/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./etc/traefik/traefik-dynamic.yml:/etc/traefik/traefik-dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - 'web'
      - 'internal'

networks:
  web:
    external: true
  internal:
    name: internal
```

traefik.yml:
```
global:
  checkNewVersion: true

entryPoints:
  http:
    address: ':80'
    transport:
      lifeCycle:
        graceTimeOut: 10000000000
      respondingTimeouts:
        idleTimeout: 180000000000
    http:
      redirections:
        entryPoint:
          to: 'https'
          scheme: 'https'
          permanent: true
  https:
    address: ':443'

providers:
  providersThrottleDuration: 2000000000
  docker:
    watch: true
    endpoint: 'unix:///var/run/docker.sock'
    defaultRule: 'Host(`{{ normalize .Name }}`)'
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik-dynamic.yml

log:
  level: 'DEBUG'
  filePath: '/var/log/traefik.log'
  format: 'common'

api:
  dashboard: true

accessLog:
  filePath: '/var/log/access.log'
```

traefik-dynamic.yml:
```
tls:
  stores:
    default: {}
  certificates:
    - certFile: /certs/domain.crt.pem
      keyFile: /certs/domain.key.pem
```

Setup for ``env 1``:

docker-compose.yml
```
version: '3.5'

services:
  node:
    image: nginx:alpine
    restart: 'always'
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./srv/www:/srv/www
      - ./var/log/nginx:/var/log/nginx
    networks:
      - internal
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.node.rule=HostSNI(`test.mydomain.de`)'
      - 'traefik.http.routers.node.entrypoints=https'
      - 'traefik.http.routers.node.tls=true'

networks:
  web:
    external: true
  internal:
    external:
      name: internal
```
