### ISSUE TITLE
Inconsistent behavior of dashboard when remote ports are used

### ISSUE THREAD

**Issue by splatch** [containous/traefik#6981]
I would like to report a **bug** report, however it very well could be a documentation flaw which is not reflected. Behavior which I describe is surprising and not clear, please do not threat it as a configuration error. There is no clear indication how traefik should behave.

Bug applies to traefik **2.2.1**.

Traefik config for reference:
```toml
[api]
  dashboard = true
  debug = true
```

I have a compose file and docker provider for my services. Security is enabled, but when container is exposed via remote port console stops to work.

Vania file `docker-compose.yaml` which does work:
```yaml
  traefik:
    image: traefik:latest
    command:
      - "--log.level=DEBUG"
      - "--accessLog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "127.0.0.3:443:443"
      - "127.0.0.3:80:80"
      - "127.0.0.4:1883:1883"
      - "127.0.0.4:8883:8883"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=(Host(`local.xyz`) || Host(`dev.xyz`) || Host(`xyx`)) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:admin"
      - "traefik.docker.network=traefik-proxy"
    volumes:
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - traefik-proxy
      - xyz-internal
```

Once additional compose override `docker-compose.cloud.yaml` is added service stops to work:
```yaml
  traefik:
    labels:
      - "traefik.http.middlewares.auth.basicauth.users=remote-admin:remote-pass"
    ports:
      - "remoteip:443:443"
      - "remoteip:80:80"
      - "remoteip:1883:1883"
      - "remoteip:8883:8883"
```

Essentially `docker-compose -f docker-compose.yaml up` works as expected and dashboard is accessible after showing up HTTP basic prompt. However `docker-compose -f docker-compose.yaml -f docker-compose.cloud.yaml up` does not work and always returns HTTP 404 for `/dashobard` and `/api` endpoints.

Traefik documentation states that:
> One or more security features through middlewares like authentication (basicAuth , digestAuth, forwardAuth) or whitelisting.

Given the above configuration basic auth is enabled.
