### ISSUE TITLE
Cannot modify Host-Header with header middleware in docker-syntax for dynamic configuration

### ISSUE THREAD

**Issue by smoebody** [containous/traefik#6986]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a dynamic configuration do modify the `Host`-Header for a service. I have done this with docker-compose and the label-element like this:

```yaml
version: '3.7'
services:
  whoami:
    image: emilevauge/whoami
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_development"
      - "traefik.http.routers.whoami-http.entrypoints=http"
      - "traefik.http.routers.whoami-http.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami-http.middlewares=whoami"
      - "traefik.http.routers.whoami-http.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.middlewares.whoami.headers.customrequestheaders.Host=foobar.foobaz"

networks:
  default:
    external: true
    name: proxy_development
```

Needless to say, that traefik is also in the network `proxy_development`.

### What did you expect to see?

the output of `whoami` should be:
```
$ curl http://whoami.example.com
Hostname: 7b2b78e66fbe
IP: 127.0.0.1
IP: 10.0.8.10
GET / HTTP/1.1
Host: foobar.foobaz
User-Agent: curl/7.69.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 192.168.7.6
X-Forwarded-Host: whoami.example.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 7cb03b5ff3db
X-Real-Ip: 192.168.7.6
```

### What did you see instead?

the output of `whoami` is:
```
$ curl http://whoami.example.com
Hostname: 7b2b78e66fbe
IP: 127.0.0.1
IP: 10.0.8.10
GET / HTTP/1.1
Host: whoami.example.com
User-Agent: curl/7.69.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 192.168.7.6
X-Forwarded-Host: whoami.example.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 7cb03b5ff3db
X-Real-Ip: 192.168.7.6
```

The Host-Header has not changed, despite the header-middleware.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by SantoDE** [comment]
Hello @smoebody,

I can not reproduce your bug report. I just took your example (changed the host, and put the labels in normal configuration and not within deploy as its not on a swarm).

```
services:
  traefik:
    image: traefik:v2.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: 
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
    ports:
      - 80:80
      - 8080:8080

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-http.entrypoints=http"
      - "traefik.http.routers.whoami-http.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami-http.middlewares=whoami"
      - "traefik.http.routers.whoami-http.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.middlewares.whoami.headers.customrequestheaders.Host=foobar.foobaz"
```

and it's working just fine.

```
Hostname: 8ed9e25e578a
IP: 127.0.0.1
IP: 172.19.0.3
GET / HTTP/1.1
Host: foobar.foobaz
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en,de;q=0.9,en-US;q=0.8
Cache-Control: max-age=0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 172.19.0.1
X-Forwarded-Host: whoami.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 7e7c9dfdc13b
X-Real-Ip: 172.19.0.1
```

Therefore, I think it could be an issue with itendation or similar in your stack file and thus, I'll close that issue.

If you need more assistance, please head over to the community forum https://community.containo.us/c/traefik/traefik-v2/10 and ask your question there.
