### ISSUE TITLE
error msg="vulcand/oxy/buffer: error when reading request body, err: Maximum size &{0} was reached"

### ISSUE THREAD

**Issue by FinnFrotscher** [containous/traefik#6987]
I get this error:
```
traefik_1          
time="2020-07-01T15:22:41Z"
level=error
msg="vulcand/oxy/buffer: error when reading request body, err: Maximum size &{0} was reached"
```
on
`tyraefik:maroilles` on docker compose.

how do i fix it?

I have in terms of config:

inside docker-compose:
```

  traefik:
    image: traefik:maroilles
    command: --api --docker --docker.domain=domain.com
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.port=80
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:domain.com
      - traefik.frontend.entryPoints=http,https




  gitlab:
    image: "gitlab/gitlab-ce:latest"
    hostname: gitlab
    restart: unless-stopped
    networks:
      - traefik
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://git.domain.com"
        nginx['listen_port'] = '443'
        nginx['listen_https'] = false
        registry_external_url 'https://registry.domain.com'
        registry_nginx['listen_port'] = '443'
        registry_nginx['listen_https'] = false
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "2222:22"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.frontend.entryPoints=http,https
      - traefik.web.backend=gitlab
      - traefik.web.frontend.rule=Host:git.domain.com
      - traefik.web.port=443
      - traefik.registry.backend=gitlab
      - traefik.registry.frontend.rule=Host:registry.domain.com
      - traefik.registry.port=443
```

traefik.toml:
```
#logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.com"
exposedByDefault = false
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "finn@domain.com"
storage = "acme.json"
onHostRule = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"

[http.middlewares]
  [http.middlewares.limit.buffering]
    maxRequestBodyBytes = 1073741824
    maxResponseBodyBytes = 1073741824
    memRequestBodyBytes = 52428800
    memResponseBodyBytes = 52428800

[[acme.domains]]
  main = "domain.com"
  sans = ["registry.domain.com"]
```

The error is happening when i upload a docker image to the `registry.domain.com` (Gitlab)
