### ISSUE TITLE
Create static services using container command or label configuration

### ISSUE THREAD

**Issue by ptr727** [containous/traefik#6992]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Per my research, see my [forum post](https://community.containo.us/t/how-to-create-static-routes-using-labels-or-commands/6733), static services can only be defined in an external configuration file.

I build my containers using Ansible, and it is much easier to configure container properties vs. creating files, and writing config in a file, and mounting the file.
I would like to have the ability to configure static services using container commands or labels.

E.g. using commands:
```yaml
    command:
      - "--static.http.routers.foo.rule=PathPrefix(`/foo`)"
      - "--static.http.services.foo.loadbalancer.server.url=`http://192.168.1.100:1234`"
```

E.g. using labels in the trafik container:
```yaml
    labels:
      traefik.static.http.routers.foo.rule: "PathPrefix(`/foo`)"
      traefik.static.http.services.foo.loadbalancer.server.url: "http://192.168.1.100:1234"
```
