### ISSUE TITLE
 mTLS in browser (chrome, firefox,...) as client doesn't work!

### ISSUE THREAD

**Issue by juan-moreno** [containous/traefik#6996]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In order to use mutual TLS with browser.
Import certificate in my browser (Chrome, Firefox...) and request with Chrome/Firefox a domain whith mTLS

### What did you expect to see?

The browser shows my certificates in order to select one and establish a mTLS with Traefik

#### Chrome browser:

This site can’t provide a secure connection

infraser.nolly.internal didn’t accept your login certificate, or one may not have been provided.
Try contacting the system admin.
**ERR_BAD_SSL_CLIENT_AUTH_CERT**

#### Firefox browser:

**SSL_ERROR_BAD_CERT_ALERT**

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.4
Codename:     cantal
Go version:   go1.13.7
Built:        2020-02-06T17:10:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  file:
    filename: "configurationTLS.yml"
    watch: true
  consulCatalog:
    prefix: traefik
    refreshInterval: 5s
    requireConsistent: true
    stale: false
    cache: false
    endpoint:
      address: http://127.0.0.1:8500
    exposedByDefault: false
    defaultRule: Host(`{{ normalize .Name }}.nolly.internal`)
```

**configurationTLS.yml**

```
tls:
  certificates:
    - certFile: "infraser.nolly.internal.crt"
      keyFile: "infraser.nolly.internal.key"
  options:
    default:
      clientAuth:
        caFiles:
          - secrets/consumer1.crt
          - secrets/consumer2.crt
        clientAuthType: RequireAndVerifyClientCert
```

With curl  works fine:
```
**$** curl -i --cert $CERT --key $KEY https:/infraser.nolly.internal/_service/v0/health
HTTP/2 200 
content-type: application/json
date: Fri, 03 Jul 2020 14:51:25 GMT
server: gunicorn/19.10.0
content-length: 16

{"status":"UP"}
```
