### ISSUE TITLE
Use benefits of service discovery along with forwardAuth

### ISSUE THREAD

**Issue by nirname** [containous/traefik#6998]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Instead of using:
```yml
http:
  middlewares:
    test-auth:
      forwardAuth:
        address: "https://example.com/auth"
```

I'd rather use something like:

```yml
http:
  middlewares:
    test-auth:
      forwardAuth:
        service: my-auth-service@consulcatalog
        proto: https
        path: /auth
```

Since my auth service is represented in my service discovery as well and it might not have its own dns record.
