### ISSUE TITLE
redirectRegex middleware not working with other header middlewares

### ISSUE THREAD

**Issue by ryanoolala** [containous/traefik#7003]
### Do you want to request a *feature* or report a *bug*?

Feature or maybe Bug

### What did you expect to see?
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: root-domain-redirection
spec:
  redirectRegex:
    regex: ^https://root-domain.com/(.*)
    replacement: https://www.root-domain.com/${1}
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-security
spec:
  headers:
    forceSTSHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-domain-redirection
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`root-domain.com`)
      kind: Rule
      middlewares:
         - name: root-domain-redirection
         - name: web-security
      services:
        - name: xxx
          port: 3000
  tls: {}
```

I expect the root-domain.com HTTPS redirection to include the `strict-transport-security: max-age=15552000; includeSubDomains
` headers in order to fulfill the hsts preload list (https://hstspreload.org/) requirement, however my HTTP 301 does not include this header.

Meanwhile i've also tried doing so using chains but did not see the expected result as well.
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hsts-root-domain
spec:
  chain:
    middlewares:
    - name: web-security
    - name: root-domain-redirection
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-domain-redirection
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`root-domain.com`)
      kind: Rule
      middlewares:
         - name: hsts-root-domain
      services:
        - name: xxx
          port: 3000
  tls: {}
```
expected:
```sh
HTTP/2 308 
date: Mon, 06 Jul 2020 12:26:13 GMT
content-type: text/plain; charset=utf-8
content-length: 18
location: https://www.root-domain.com/
strict-transport-security: max-age=15552000; includeSubDomains
```

got:
```sh
HTTP/2 308 
date: Mon, 06 Jul 2020 12:26:13 GMT
content-type: text/plain; charset=utf-8
content-length: 18
location: https://www.root-domain.com/
```
