### ISSUE TITLE
Traefik returns 504 during Kubernetes rollout

### ISSUE THREAD

**Issue by mazzy89** [containous/traefik#7010]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

During high traffic peaks and a kubernetes rollout of an app, Traefik returns 504

I was able to reproduce this issue running load tests with [k6](https://k6.io/)

```js
import { check } from 'k6';
import http from 'k6/http';

export default function() {
  let res = http.get('https://myapp.info/ping');
  check(res, {
    'is status 200': (r) => r.status === 200,
    'is status 504': (r) => r.status === 504,
  });
}
```

```sh
k6 run --vus 5 -d 80s k6.js
```

Execute

```
kubectl rollout deploy/my-app
```

The results I get running the load tests when 

```
    ✗ is status 200
     ↳  97% — ✓ 474 / ✗ 12
    ✗ is status 504
     ↳  0% — ✓ 4 / ✗ 482
```

some requests unfortunately fail.

### What did you expect to see?

I would expect to see all requests get 200.

### What did you see instead?

Part of the requests return 504.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.19
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes (kops) 1.16.10

Traefik deployed via official Helm chart version `traefik-1.82.1`

```toml
    # traefik.toml
    logLevel = "info"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
      [entryPoints.prometheus]
      address = ":9100"
    [ping]
    entryPoint = "http"
    [kubernetes]
    ingressClass = "traefik-info"
      [kubernetes.ingressEndpoint]
      publishedService = "kube-system/reverse-proxy-traefik"
    [traefikLog]
      format = "json"
    [accessLog]
      format = "json"
    [accessLog.fields]
      defaultMode = "keep"
    [accessLog.fields.names]
    [accessLog.fields.headers]
      defaultMode = "keep"
    [accessLog.fields.headers.names]
    [metrics]
      [metrics.prometheus]
        entryPoint = "prometheus"
```
