### ISSUE TITLE
Miss behavior on IngressRoute TLS configuration using Traefik default certificate

### ISSUE THREAD

**Issue by felpasl** [containous/traefik#7013]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

configure first time kubernetes using default invalid certificate from traefik trying to expose  dashboard in https

### What did you see instead?

6 hours of reading and try, reading try, try again

```yaml
# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```
When I put the TLS and Domain without any values, works like tls=true in label on docker
```yaml
  tls:
    domains:
```
Without this doesn't work the default certificate.

I almost go to buy a domain and configuring letsencrypt to do an POC. 

Discover its working during an error on configure self generated certificate and put an invalid name of secret, and default cert starts working..

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:2.2.1 installed by helm package
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

kubernetes + helm

**Comment by SantoDE** [comment]
Hello @felpasl,

What do you mean by it doesn't work without the tls values? Like do you have a 404 or not a matching certificate? Like what is the exact error you're seeing?

Please also provide us your static configuration

**Comment by felpasl** [comment]
sry, return a default traefik certificate but with 404 return,

**Comment by kimpenhaus** [comment]
Same here.

Before the latest update with docker image traefik:latest (sha256:9377b64b98808a38d0665d98cf8eab0a8ccb949742cc11d05348ecaf1ff6757e)
my `static.yml` had defined entry points like this:

```
entryPoints:
  web:
    address: ":11080"
  web-secure:
    address: ":11443"
    http:
      tls: {}
```

which was working fine and serving https requests.

After the update I had to change like @felpasl said (thanks for mentioning that workaround - save me tons of work to find a working solution 👍 ) otherwise it would serve 404 on https requests.

Now it looks like:

```
entryPoints:
  web:
    address: ":11080"
  web-secure:
    address: ":11443"
    http:
      tls:
        domains:
```

and is serving https requests again.
