### ISSUE TITLE
Intermittent 404 on v2.2.2

### ISSUE THREAD

**Issue by dhaalves** [containous/traefik#7020]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
update from v2.2.1 to v2.2.2

### What did you expect to see?
middleware redirectregex working

### What did you see instead?
page not found

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.2
Codename:     chevrotin
Go version:   go1.14.4
Built:        2020-07-08T15:30:29Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker

```yml
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      # - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--metrics=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.manualrouting=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=none@uel.br"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # global redirect to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # redict-from-old-url
      - "traefik.http.middlewares.redict-from-old-url.redirectregex.permanent=true"
      - "traefik.http.middlewares.redict-from-old-url.redirectregex.regex=^https://oldname.uel.br/(.*)"
      - "traefik.http.middlewares.redict-from-old-url.redirectregex.replacement=https://newname.uel.br/gitlab/$${1}"
      - "traefik.http.routers.catch-old-url.rule=Host(`oldname.uel.br`)"
      - "traefik.http.routers.catch-old-url.entrypoints=websecure"
      - "traefik.http.routers.catch-old-url.tls.certresolver=leresolver"
      - "traefik.http.routers.catch-old-url.middlewares=redict-from-old-url"
```

**Comment by dtrv** [comment]
+1
observe quite the same but without redirectregex middleware
2.2.1 --> 2.2.2 access via entrypoint https/tls: all requests get "404 page not found"
middleware redirectscheme seems to work.
back to 2.2.1 without config changes and everything works as expected.

**Comment by ldez** [comment]
Could you share your logs?

**Comment by ldez** [comment]
I created a simplified configuration and I don't reproduce:

```yml
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.2
    container_name: traefik
    command:
      # - --log.level=DEBUG
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true

      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal

      # redict-from-old-url
      traefik.http.middlewares.redict-from-old-url.redirectregex.permanent: true
      traefik.http.middlewares.redict-from-old-url.redirectregex.regex: ^https://gitlab.uel.localhost/(.*)
      traefik.http.middlewares.redict-from-old-url.redirectregex.replacement: https://newname.uel.localhost/gitlab/$${1}

      traefik.http.routers.catch-old-url.rule: Host(`gitlab.uel.localhost`)
      traefik.http.routers.catch-old-url.entrypoints: websecure
      # traefik.http.routers.catch-old-url.tls.certresolver: leresolver
      traefik.http.routers.catch-old-url.middlewares: redict-from-old-url

  whoami:
    image: containous/whoami:v1.5.0
    labels:
      traefik.enable: true

      traefik.http.routers.app.rule: Host(`newname.uel.localhost`)
      traefik.http.routers.app.entrypoints: websecure
```

```console
$ curl -L -k https://gitlab.uel.localhost/test

Hostname: d002bff59e83
IP: 127.0.0.1
IP: 172.19.0.2
RemoteAddr: 172.19.0.3:48414
GET /gitlab/test HTTP/1.1
Host: newname.uel.localhost
User-Agent: curl/7.70.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.19.0.1
X-Forwarded-Host: newname.uel.localhost
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: b38b142a89e3
X-Real-Ip: 172.19.0.1
```

**Comment by dtrv** [comment]
WOW! A migration guide from x.x.1 to x.x.2 with breaking changes? Never expected something like this and that's why I didn't search for it. "We introduced the ability ... and enabled it by default" is quite surprising. 

I can confirm, after a quick change and setting `insecureSNI: true` https access works with 2.2.2.
Changing all router rules from `Host()` to `HostHeaders()` takes more time but I guess it will work too.

Thanks for your quick response!

**Comment by ldez** [comment]
@dtrv the change is related to a CVE, to get more information: https://github.com/containous/traefik/pull/7008

**Comment by SantoDE** [comment]
@dtrv could you please provide your example anyways? I'm curious on what is causing that in your scenario.

**Comment by dtrv** [comment]
One wildcard cert with config in `dynamic.yml`. Nothing special in `traefik.yml` .. i guess.
```
tls:
  stores:
    default:
      defaultCertificate:
          certFile: /etc/traefik/cert.crt
          keyFile: /etc/traefik/cert.key
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        # TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_AES_128_GCM_SHA256
        # TLS 1.2, strong and 256bit only
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

Ansible deployed docker containers with the following labels (as example)
```
    labels:
      traefik.enable: "true"
      traefik.http.routers.privatebin1st.entryPoints: "websecure"
      traefik.http.routers.privatebin1st.tls: "true"
      traefik.http.routers.privatebin1st.rule: "Host(`{{ privatebin_1st_fqdn }}`)"
```
`privatebin_1st_fqdn` is https://paste.in-ulm.de
All router rules have `Host()` rules with subdomains to `in-ulm.de`. None of them was working.

HTH

**Comment by SantoDE** [comment]
Thanks.

Does your certificate include this sub-domains through a wildcard or an alternative name?

**Comment by dtrv** [comment]
It wasn't long on 2.2.2 and it's on log.level ERROR ... but I can reconfigure the router rules, disable `insecureSNI` and leave a not frequently used domain on `Host()` to reproduce the behavior.

10 minutes?

**Comment by SantoDE** [comment]
Sure. I’ll have a look tomorrow in mY morning then if you provide the logs.

**Comment by Shemeikka** [comment]
Hi,

I also noticed something similar with my development setup. With v2.2.2 routing is almost always broken, returning 404 when using Host rule. With HostHeader rule or Host rule and insecureSNI true, routing works all the time.

When using Host header, routing sometimes works for few minutes until it doesn't and Traefik starts returning 404 for all requests. When Traefik is restarted, routing either doesn't work from the beginning or works for few minutes, though there have been few times when routing worked for tens of minutes.

Chrome works differently than Firefox. With Chrome, all routing fails but with Firefox, just some fails. And sometimes this is reversed. Sometimes it's just the CORS preflight (OPTIONS) requests that are returned with 404.

I'm using TLS and certs are made using mkcert so they are "valid", at least browsers and other tools work as expected. Certificate host matches the request's host.

I did a little debugging:

When request originated from browser.
```
# Traefik logs

time="2020-07-10T04:37:15Z" level=debug msg="Authentication succeeded" middlewareName=auth@file middlewareType=BasicAuth
172.102.0.1 - user [10/Jul/2020:04:37:15 +0000] "GET /api/overview HTTP/1.1" 200 445 "-" "-" 173 "api-dashboard@file" "-" 72ms
172.102.0.1 - - [10/Jul/2020:04:37:15 +0000] "GET /api/authz HTTP/1.1" 404 19 "-" "-" 174 "-" "-" 0ms
time="2020-07-10T04:37:20Z" level=debug msg="Authentication succeeded" middlewareType=BasicAuth middlewareName=auth@file
172.102.0.1 - user [10/Jul/2020:04:37:20 +0000] "GET /api/overview HTTP/1.1" 200 445 "-" "-" 175 "api-dashboard@file" "-" 73ms
```

When using curl
```
# curl -vv https://api.localhost.local/api/authz

=> Traefik logs

time="2020-07-10T04:37:24Z" level=debug msg="URL.Path is now /api/authz (was /authz)." middlewareName=add-api@file middlewareType=AddPrefix
time="2020-07-10T04:37:24Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/authz\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip\"],\"User-Agent\":[\"curl/7.58.0\"],\"X-Forwarded-Host\":[\"api.localhost.local\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Prefix\":[\"/auth\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"ba6a3f1a59f7\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.localhost.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:57326\",\"RequestURI\":\"/api/authz\",\"TLS\":null}"
time="2020-07-10T04:37:24Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://172.102.0.7:80" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/authz\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip\"],\"User-Agent\":[\"curl/7.58.0\"],\"X-Forwarded-Host\":[\"api.localhost.local\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Prefix\":[\"/auth\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"ba6a3f1a59f7\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.localhost.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:57326\",\"RequestURI\":\"/api/authz\",\"TLS\":null}"
time="2020-07-10T04:37:24Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/authz\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip\"],\"User-Agent\":[\"curl/7.58.0\"],\"X-Forwarded-Host\":[\"api.localhost.local\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Prefix\":[\"/auth\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"ba6a3f1a59f7\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.localhost.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:57326\",\"RequestURI\":\"/api/authz\",\"TLS\":null}"
127.0.0.1 - - [10/Jul/2020:04:37:24 +0000] "GET /auth/authz HTTP/2.0" 401 36 "-" "-" 177 "autsi@file" "http://172.102.0.7:80" 1ms
time="2020-07-10T04:37:24Z" level=debug msg="Remote error https://api.localhost.local/auth/authz. StatusCode: 401" middlewareType=ForwardedAuthType middlewareName=auth-request@file
172.102.0.1 - - [10/Jul/2020:04:37:24 +0000] "GET /api/authz HTTP/2.0" 401 36 "-" "-" 176 "portal-backend-https-auth@file" "-" 2ms
```

So routing work when using curl.

**Comment by jimOnAir** [comment]
Hello. I have a similar issue with HostRegexp. Before version 2.2.2 it works perfectly, and now it is not working:
```yaml
        - "traefik.http.routers.catchall-http.entrypoints=http"
        - "traefik.http.routers.catchall-http.middlewares=redirect-scheme-https@file,compress@file"
        - "traefik.http.routers.catchall-http.priority=1"
        - "traefik.http.routers.catchall-http.rule=HostRegexp(`{catchall:.*}`)"
        - "traefik.http.routers.catchall-http.service=catchall"

        - "traefik.http.routers.catchall-https.entrypoints=https"
        - "traefik.http.routers.catchall-https.middlewares=cors-allow-all-origin@file,compress@file"
        - "traefik.http.routers.catchall-https.priority=1"
        - "traefik.http.routers.catchall-https.rule=HostRegexp(`{catchall:.*}`)"
        - "traefik.http.routers.catchall-https.service=catchall"
        - "traefik.http.routers.catchall-https.tls=true"
```
I use docker swarm with hostname based rules on services (e.g.  
 ```traefik.http.routers.portal-https.rule=Host(`test.domain.tld`)```
  )
And have catchall service that captures all requests whose doesn't have configured domains.
Seems like now it just redirects all traffic to catchall service.

**Comment by SantoDE** [comment]
Morning all,

I'm trying to reproduce your issue but sadly, I just can't. For you're use-cases, are you actually trying to do [Domain Fronting](https://en.wikipedia.org/wiki/Domain_fronting) ? Or do you have "normal" http connections going from a browser to your services?

**Comment by Shemeikka** [comment]
Hi @SantoDE 

I'm not trying to do Domain fronting, just "normal" https connections from browser to services.

I'll try to make a simple setup which reproduces this behavior.

**Comment by Shemeikka** [comment]
Well, I couldn't make a simple setup that reproduces this behavior and my development setup uses proprietary code so I can't share that.

I could try to build my own version of Traefik with more logging added to routing and TLS handling if I can find correct code paths.


My static config file
```
global:
  checkNewVersion: false
  sendAnonymousUsage: false
accessLog: {}
log:
  level: DEBUG

entryPoints:
  web:
    address: ':80'

  web-secure:
    address: ':443'

api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/conf
    watch: true

  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

#serversTransport:
  #rootCAs:
  #  - /certs/traefik_ca.crt
  #insecureSkipVerify: true
```

My dynamic config file
```
http:
  routers:
    
    autsi:
      rule: "Host(`api.localhost.local`) && (
        PathPrefix(`/auth`) ||
        PathPrefix(`/authz`)
        )"
      entryPoints:
        - web-secure
      middlewares:
        - remove-auth
        #- add-authz
        - add-api
        - security-headers
      service: autsi@docker
      tls:
        domains:
          - main: "api.localhost.local"

    ivm-https:
      rule: "
        Host(`api.localhost.local`) &&
        ( PathPrefix(`/ivm`)) &&
        Method(`DELETE`, `GET`, `HEAD`, `POST`, `PUT`)
        "
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
      service: ivm@docker
      tls:
        domains:
          - main: "api.localhost.local"

    ivm-options-https:
      rule: "
        Host(`api.localhost.local`) &&
        ( PathPrefix(`/ivm`)) &&
        Method(`OPTIONS`)
        "
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
      service: ivm@docker
      tls:
        domains:
          - main: "api.localhost.local"
    
    portal-backend-https:
      rule: "
        Host(`api.localhost.local`) &&
        ( PathPrefix(`/api/users`) ||
          PathPrefix(`/api/groups`)) &&
        Method(`DELETE`, `GET`, `HEAD`, `POST`, `PUT`)
        "
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
      service: portal-backend@docker
      tls:
        domains:
          - main: "api.localhost.local"

    portal-backend-https-auth:
      rule: "
        Host(`api.localhost.local`) &&
        (PathPrefix(`/api`)) &&
        Method(`DELETE`, `GET`, `HEAD`, `POST`, `PUT`)
        "
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
        - auth-request
      service: portal-backend@docker
      tls:
        domains:
          - main: "api.localhost.local"

    portal-backend-options-https:
      rule: "
        Host(`api.localhost.local`) &&
        (PathPrefix(`/api`)) &&
        Method(`OPTIONS`)
        "
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
      service: portal-backend@docker
      tls:
        domains:
          - main: "api.localhost.local"

    portal-frontend-https:
      rule: "
        Host(`localhost.local`) &&
        (PathPrefix(`/`))
        "
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
        - route-unauthorized-error
        - route-frontend-errors
      service: portal-frontend@docker
      tls:
        domains:
          - main: "localhost.local"

  middlewares:
    add-api:
      addPrefix:
        prefix: "/api"
    add-authz:
      addPrefix:
        prefix: "/authz"
    auth-request:
      forwardAuth:
        address: "https://api.localhost.local/auth/authz"
        tls:
          insecureSkipVerify: true
    auth-static-request:
      forwardAuth:
        address: "https://api.localhost.local/auth/authz_static"
        tls:
          insecureSkipVerify: true
    remove-auth:
      stripPrefix:
        prefixes:
          - "/authz"
          - "/auth"
    route-unauthorized-error:
      errors:
        status:
          - "401"
        service: portal-frontend@docker
        query: "/signin"
    route-frontend-errors:
      errors:
        status:
          - "400"
          - "402-599"
        service: portal-frontend@docker
        query: "/"
    security-headers:
      headers:
        customResponseHeaders:
          Access-Control-Allow-Credentials: true
          Access-Control-Allow-Headers: "Content-Type, Host, Origin, X-Xsrf-Token"
          Access-Control-Allow-Methods: "DELETE, GET, OPTIONS, POST, PUT"
          Access-Control-Allow-Origin: "https://localhost.local"
          Access-Control-Expose-Headers: "Content-Type, Origin, set-cookie, x-knl-user, x-resources"
          Access-Control-Max-Age: 10
          Content-Security-Policy: "
            base-uri 'self';
            block-all-mixed-content;
            connect-src 'self' https://api.localhost.local wss://api.localhost.local;
            default-src 'none';
            font-src 'self' https://fonts.gstatic.com;
            form-action 'self';
            frame-ancestors 'none';
            img-src 'self';
            manifest-src 'self';
            script-src 'self';
            style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
            "
          Feature-Policy: "camera: 'none'; geolocation: 'none'; microphone: 'none'; usb: 'none'"
          Strict-Transport-Security: "max-age=31536000; includeSubDomains"
          # CSP frame-ancestors directive obsoletes the X-Frame-Options header
          X-Frame-Options: deny
          # Will be outdated soon as modern browsers won't support this anymore
          X-XSS-Protection: "1; mode=block"
          X-Content-Type-Options: nosniff
          X-Permitted-Cross-Domain-Policies: none
          X-Referrer-Policy: strict-origin-when-cross-origin
          # Remove following headers from response
          server: ""
    websocket-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
```

TLS config
```
tls:
  certificates:
    - certFile: /certs/localhost+5.pem
      keyFile: /certs/localhost+5-key.pem
      stores:
        - default
  stores:
    default: {}
      
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      preferServerCipherSuites: true

    #mintls13:
    #  minVersion: VersionTLS13
```

**Comment by Floeig** [comment]
This is how I reproduce the bug.
it's user based. You need at least 2 routes (like 2 websites).

1) on firefox when I got to the website I got 404 then press CTRL + SHIFT + R (not F5) and it change the 404 to the actual 200 and works for that website. then this website is working just fine.

2)Now when I go to the other website I get a 404 work until I press [CTRL] + [SHIFT] + [R] then it works for the new website but the previous website will now get a 404 for the user.

and goes on...  I hope I helped a little bit

I can provide all the doc you need I can reproduce the pattern. let me know.

**Comment by SantoDE** [comment]
@Floeig if you can provide a pattern that is locally runable to reproduce, we're more then happy!

**Comment by Floeig** [comment]
I'm using kubernetes, I guess you can install kubernetes locally now? not sure how it will go.
Well, I can copy/past my config maybe it can help you anyway.

1) Install all of the ingress routes definitions and rbac as you have in the doc 
2) I install a certificate and a TLS Option (not sure It's needed)
```yml
apiVersion: v1
kind: Secret
metadata:
  name: secretca1
  namespace: default
data:
    tls.ca: "__CERTIFICATE_CA__"
---

apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: mytlsoption
  namespace: default

spec:
  minVersion: VersionTLS12
  curvePreferences:
    - CurveP521
    - CurveP384
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  clientAuth:
    secretNames:
      - secretca1
    clientAuthType: VerifyClientCertIfGiven
  sniStrict: true
```

3) I deploy traefik
 ```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      volumes:
        - name: https-ca-certificate
          secret:
            secretName: secretca1
      restartPolicy: Always
      containers:
        - name: traefik
          image: traefik:v2.2.2
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          args:
            - --api.insecure
            - --log.level=debug
            - --ping=true
            - --accesslog.format=json
            - --accesslog.fields.defaultmode=keep
            - --global.checknewversion
            - --global.sendanonymoususage
            - --serverstransport.insecureSkipVerify=false
            - --serverstransport.rootCAs=/cert/ca.crt
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetesCRD
          securityContext: {}
          livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
          readinessProbe:
              failureThreshold: 1
              httpGet:
                path: /ping
                port: 8080
                scheme: HTTP
          volumeMounts:
            - name: https-ca-certificate
              mountPath: /cert
              readOnly: true
```
4) I create the load balancer (You probably won't locally)
 ```yml
apiVersion: v1
kind: Service
metadata: 
  name: traefik
  namespace: default
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: websecure
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: "__MY_IP__"
```

5) I let you create 2 pod & 2 services and this is my 2 ingress routes.

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`abcdef.com`) # and another name for the other service
      kind: Rule
      services:
# then we need to make 2 different routes. This is an example of the services I have the issue:
        - name: api@internal
          kind: TraefikService
# or like 
        - name: myapp-service
          namespace: myapp-namespace
          port: 80
      middlewares:
        - name: traefik-websecure-redirect
          namespace: default
    
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-websecure-ingressroute
  namespace: default
spec:
  tls:
    secretName: https-certificate
    options:
      name: mytlsoption
      namespace: default
  entryPoints:
    - websecure
  routes:
    - match: Host(`abcdef.com`) # and another name for the other service
      kind: Rule
      services:
# here as well
        - name: api@internal
          kind: TraefikService
# or like 
        - name: myapp-service
          namespace: myapp-namespace
          port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-websecure-redirect
  namespace: default
spec:
  redirectScheme:
    scheme: https
```
that's it, you won't be able to switch between thoses 2 websites unless you do [CTRL] [SHIFT] and [R] each time

I hope It will help you a bit
Let me know if you need something else.
thanks you

**Comment by SantoDE** [comment]
Hey @Floeig,

this looks like a different problem. Please open a new issue for that.

**Comment by SantoDE** [comment]
@Shemeikka thanks. Sadly, that's nothing we can easily run in order to try to fix the issue. 

Currently, after lots of checking with different members of the community (thanks @dtrv) it seems to be a "determing" issue, when a browser selects which SNI to send to Traefik. This can have many reasons and might show in strange behavior: connecting via curl is working, while trying to connect with a browser might not.

However, its nothing we can really adjust in Traefik. So, once again, we will need a good example to reproduce. Thanks for all your help!

**Comment by dhaalves** [comment]
> I created a simplified configuration and I don't reproduce:
> 
> docker-compose.yml
> ```
> $ curl -L -k https://gitlab.uel.localhost/test
> 
> Hostname: d002bff59e83
> IP: 127.0.0.1
> IP: 172.19.0.2
> RemoteAddr: 172.19.0.3:48414
> GET /gitlab/test HTTP/1.1
> Host: newname.uel.localhost
> User-Agent: curl/7.70.0
> Accept: */*
> Accept-Encoding: gzip
> X-Forwarded-For: 172.19.0.1
> X-Forwarded-Host: newname.uel.localhost
> X-Forwarded-Port: 443
> X-Forwarded-Proto: https
> X-Forwarded-Server: b38b142a89e3
> X-Real-Ip: 172.19.0.1
> ```

Try using google chrome instead of Curl.

**Comment by SantoDE** [comment]
@dhaalves is it possible for you to reproduce with google chrome? Which version?

**Comment by SantoDE** [comment]
Hello all, thanks a lot for all your feedback throughout the day. We were finally able to reproduce the bug and are working on a hotfix right now.

Our hotfix will change the default behavior (`insecureSNI`) from true to false, essentially implementing the same behavior which existed in 2.2.1, which should mitigate the issue you are facing.

Let me quickly explain how / when this issue arises:

When utilizing HTTP/2 and a wildcard TLS certificate, after the first TLS Handshake, no further SNI will be sent to the proxy if the "new" origin exists with a SAN in the certificate. In our changed default behavior, we are now matching the SNI and a Host Header to be the same value. As in that case, there is no further SNI. The matching fails and this, resulting in a 404. After the hotfix is released today, we will continue to work next week on an effective solution to address this matter.

If you're interested, more information about that particular issue can is available in the [RFC](https://httpwg.org/specs/rfc7540.html#rfc.section.9.1.1). The team apologies for all the inconvenience this may have caused so far.

**Comment by dhaalves** [comment]
> @dhaalves is it possible for you to reproduce with google chrome? Which version? I just tried but I cant. Not with chrome, not firefox, just it works everywhere

You are right, I tried to reproduce with localhost domain and it worked on all scenarios. But on my real world domain with tls letencrypt certificate it stop redirecting. See configs https://github.com/containous/traefik/issues/7020#issue-654274018

**Comment by dtrv** [comment]
> When utilizing HTTP/2 and a wildcard TLS certificate, after the first TLS Handshake, no further SNI will be sent to the proxy if the "new" origin exists with a SAN in the certificate. In our changed default behavior, we are now matching the SNI and a Host Header to be the same value. As in that case, there is no further SNI, the matching fails and this results in a 404. After the hotfix is released today, we will continue to work next week on an effective solution to address this matter.
> 
I can reproduce this behavior by using https://github.com/kontaxis/snidump and dumping the SNI from TLS handshake. When traefik gives a 404 no SNI is send. Glad you found it!

Thanks.

**Comment by chschu** [comment]
Comparing the output of the following two commands, the changed default doesn't seem to work with the `traefik:2.2.4` Docker image:

`docker run -ti traefik:2.2.4 --log.level=WARN`

`docker run -ti traefik:2.2.4 --log.level=WARN --global.insecureSNI=true`

I'd expect both command to print the insecureSNI warning, but only the second one does.

**Comment by mpatton125** [comment]
Just a note - this bit me in the arse too - however the earlier suggested fix of using "HostHeader" instead of "Host" rule has no effect.  The only change that currently mitigates this issues is "insecureSNI: true".

**Comment by placaze** [comment]
I'm seeing a weird behavious with 2.2.4.

I have a Docker Swarm with 2 wildcard certificates:
* *.subdomain1.domain.tld
* *.subdomain2.domain.tld

And 4 apps:
* app1.subdomain1.domain.tld

**Comment by AndrewSav** [comment]
Someone else [reported the same](https://community.containo.us/t/consolidated-404-issue-thread-in-versions-since-2-2-1/6865/6?u=zespri)

**Comment by nader-eloshaiker** [comment]
> I'm seeing a weird behaviour with 2.2.4.
> 
> I have a Docker Swarm with 2 wildcard certificates:
> 
> * *.subdomain1.domain.tld
> * *.subdomain2.domain.tld
> 
> And 4 apps:
> 
> * app1.subdomain1.domain.tld
> * app2.subdomain1.domain.tld
> * app3.subdomain2.domain.tld
> * app4.subdomain2.domain.tld
> 
> With version 2.2.4:
> 
> * **Default conf:** ❌ intermittent 404
> * **With `insecureSNI = false`:** ❌ intermittent 404
> * **With `insecureSNI = true` explicitly set:** ✔️ seems OK
> 
> I hope I did my tests right. It's weird because I thought `insecureSNI = true` should be the default with 2.2.4?

I can confirm this too. On 2.2.4 and had to explicitly set `insecureSNI = true` for traefik to stop returning `404`.

**Comment by Motophan** [comment]
This exact thing is happening to me. I reverted to 2.2.1 and this fixed the issue. 
If you use docker-compose change 
```
services:
  traefik:
    container_name: traefik
    image: traefik:2.2.1
```

Hope this helps :)
