### ISSUE TITLE
Traefik gives 404 for all the routes except for one at the time

### ISSUE THREAD

**Issue by Floeig** [containous/traefik#7025]
I'm using kubernetes, I guess you can install kubernetes locally now? not sure how it will go.
Well, I can copy/past my config maybe it can help you anyway.

1) Install all of the ingress routes definitions and rbac as you have in the doc 
2) I install a certificate and a TLS Option (not sure It's needed)
```yml
apiVersion: v1
kind: Secret
metadata:
  name: secretca1
  namespace: default
data:
    tls.ca: "__CERTIFICATE_CA__"
---

apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: mytlsoption
  namespace: default

spec:
  minVersion: VersionTLS12
  curvePreferences:
    - CurveP521
    - CurveP384
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  clientAuth:
    secretNames:
      - secretca1
    clientAuthType: VerifyClientCertIfGiven
  sniStrict: true
```

3) I deploy traefik
 ```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      volumes:
        - name: https-ca-certificate
          secret:
            secretName: secretca1
      restartPolicy: Always
      containers:
        - name: traefik
          image: traefik:v2.2.2
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          args:
            - --api.insecure
            - --log.level=debug
            - --ping=true
            - --accesslog.format=json
            - --accesslog.fields.defaultmode=keep
            - --global.checknewversion
            - --global.sendanonymoususage
            - --serverstransport.insecureSkipVerify=false
            - --serverstransport.rootCAs=/cert/ca.crt
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetesCRD
          securityContext: {}
          livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
          readinessProbe:
              failureThreshold: 1
              httpGet:
                path: /ping
                port: 8080
                scheme: HTTP
          volumeMounts:
            - name: https-ca-certificate
              mountPath: /cert
              readOnly: true
```
4) I create the load balancer (You probably won't locally)
 ```yml
apiVersion: v1
kind: Service
metadata: 
  name: traefik
  namespace: default
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: websecure
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: "__MY_IP__"
```

5) I let you create 2 pod & 2 services and this is my 2 ingress routes.

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`abcdef.com`) # and another name for the other service
      kind: Rule
      services:
# then we need to make 2 different routes. This is an example of the services I have the issue:
        - name: api@internal
          kind: TraefikService
# or like 
        - name: myapp-service
          namespace: myapp-namespace
          port: 80
      middlewares:
        - name: traefik-websecure-redirect
          namespace: default
    
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-websecure-ingressroute
  namespace: default
spec:
  tls:
    secretName: https-certificate
    options:
      name: mytlsoption
      namespace: default
  entryPoints:
    - websecure
  routes:
    - match: Host(`abcdef.com`) # and another name for the other service
      kind: Rule
      services:
# here as well
        - name: api@internal
          kind: TraefikService
# or like 
        - name: myapp-service
          namespace: myapp-namespace
          port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-websecure-redirect
  namespace: default
spec:
  redirectScheme:
    scheme: https
```
that's it, you won't be able to switch between thoses 2 websites unless you do [CTRL] [SHIFT] and [R] each time

I hope It will help you a bit
Let me know if you need something else.
thanks you

_Originally posted by @Floeig in https://github.com/containous/traefik/issues/7020#issuecomment-656687017_
