### ISSUE TITLE
Odd behavior with http to https redirection to :8443/tcp

### ISSUE THREAD

**Issue by gaui** [containous/traefik#7038]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Set up Traefik 2.2.4 with the built-in entryPoint redirection. Then applied a Deployment object:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my1337tech
  annotations:
    maesh.containo.us/traffic-type: http
spec:
  routes:
    - match: Host(`my1337.tech`, `www.my1337.tech`)
      kind: Rule
      services:
        - name: my1337tech
          port: 80
  tls:
    certResolver: default
    domains:
      - main: my1337.tech
        sans:
          - "*.my1337.tech"
```

Then tried cURL:

```bash
$ curl --insecure -I http://my1337.tech
HTTP/1.1 308 Permanent Redirect
Location: https://my1337.tech:8443/tcp/
Date: Mon, 13 Jul 2020 11:18:02 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

Look at the `Location: https://my1337.tech:8443/tcp/`

### What did you expect to see?

```bash
$ curl --insecure -I http://my1337.tech
HTTP/1.1 308 Permanent Redirect
Location: https://my1337.tech
Date: Mon, 13 Jul 2020 11:18:02 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

### What did you see instead?

```bash
$ curl --insecure -I http://my1337.tech
HTTP/1.1 308 Permanent Redirect
Location: https://my1337.tech:8443/tcp/
Date: Mon, 13 Jul 2020 11:18:02 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.4
Codename:     chevrotin
Go version:   go1.14.4
Built:        2020-07-10T17:26:20Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Default Traefik v2 Helm chart with the `KubernetesCRD` provider and the following Helm values:

```yaml
image:
  tag: 2.2.4

globalArguments:
  - --global.checknewversion
  - --global.sendanonymoususage

additionalArguments:
  - --log.level=DEBUG
  - --accesslog=true
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
  - --entrypoints.websecure.http.tls.certResolver=default
  - --certificatesresolvers.default.acme.email=[CENSORED]
  - --certificatesresolvers.default.acme.storage=/data/acme.json
  - --certificatesresolvers.default.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.default.acme.dnschallenge.resolvers=8.8.8.8,8.8.4.4
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
[13/Jul/2020:11:33:18 +0000] "HEAD / HTTP/1.1" 308 18 "-" "-" 40595 "web-to-websecure@internal" "-" 2ms
```
