### ISSUE TITLE
Traefik 2.2 Client TLS Errors

### ISSUE THREAD

**Issue by jamie-stinson** [containous/traefik#7045]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Copied all contents of the Traefik Kubernetes Let's Encrypt Guide to my Controller. (CRD, Services, Deployment, Ingress)
2. Removed Let's Encrypt from Args.
3. Created TLS Secret for Ingress Route.
4. Applied TLS Secret to Ingress Route.

Possible Traefik Bug?

### What did you expect to see?

Traefik creating the ingress route and applying the Secret.

### What did you see instead?

Traefik creating TLS errors and skipping events.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/arm
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

**crd.yaml**

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressrouteudps.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteUDP
    plural: ingressrouteudps
    singular: ingressrouteudp
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsstores.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSStore
    plural: tlsstores
    singular: tlsstore
  scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller

rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default

```

**services.yaml**

```
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 8000
      nodePort: 30080
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443
      nodePort: 30443
  selector:
    app: traefik

---
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami

```

**secret.yaml**

```
apiVersion: v1
data:
  tls.crt  base64 crt was here
  tls.key: base64 key was here
kind: Secret
metadata:
  creationTimestamp: null
  name: default-certificate
  namespace: default
type: kubernetes.io/tls

```

**deployment.yaml**

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --log.level=DEBUG
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80

```

**ingress.yaml**

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`request.whitebox.app`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: whoami
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`request.whitebox.app`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: whoami
      port: 80

  tls:
  - secretName: default-certificate

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-07-13T21:15:54Z" level=info msg="Configuration loaded from flags."
time="2020-07-13T21:15:54Z" level=info msg="Traefik version 2.2.1 built on 2020-04-29T18:02:09Z"
time="2020-07-13T21:15:54Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"web\":{\"address\":\":8000\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websecure\":{\"address\":\":4443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"kubernetesCRD\":{}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}}}"
time="2020-07-13T21:15:54Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-07-13T21:15:54Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-07-13T21:15:54Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2020-07-13T21:15:54Z" level=info msg="Starting provider *traefik.Provider {}"
time="2020-07-13T21:15:54Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2020-07-13T21:15:54Z" level=debug msg="Start TCP Server" entryPointName=web
time="2020-07-13T21:15:54Z" level=info msg="Starting provider *crd.Provider {}"
time="2020-07-13T21:15:54Z" level=debug msg="Using label selector: \"\"" providerName=kubernetescrd
time="2020-07-13T21:15:54Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2020-07-13T21:15:54Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2020-07-13T21:15:54Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/[^:\\\\/]+(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2020-07-13T21:15:54Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal
time="2020-07-13T21:15:54Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" entryPointName=traefik routerName=dashboard@internal middlewareType=TracingForwarder middlewareName=tracing
time="2020-07-13T21:15:54Z" level=debug msg="Creating middleware" middlewareType=StripPrefix entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
time="2020-07-13T21:15:54Z" level=debug msg="Adding tracing to middleware" middlewareName=dashboard_stripprefix@internal entryPointName=traefik routerName=dashboard@internal
time="2020-07-13T21:15:54Z" level=debug msg="Creating middleware" middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2020-07-13T21:15:54Z" level=debug msg="Setting up redirection from ^(http:\\/\\/[^:\\/]+(:\\d+)?)\\/$ to ${1}/dashboard/" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
time="2020-07-13T21:15:54Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2020-07-13T21:15:54Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2020-07-13T21:15:54Z" level=debug msg="No default certificate, generating one"
E0713 21:15:55.893573       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
time="2020-07-13T21:15:56Z" level=debug msg="http: panic serving 10.44.0.0:58372: runtime error: invalid memory address or nil pointer dereference"
time="2020-07-13T21:15:56Z" level=debug msg="goroutine 220 [running]:"
time="2020-07-13T21:15:56Z" level=debug msg="net/http.(*conn).serve.func1(0x5074180)"
time="2020-07-13T21:15:56Z" level=debug msg="\t/usr/local/go/src/net/http/server.go:1772 +0xf0"
time="2020-07-13T21:15:56Z" level=debug msg="panic(0x1a96e88, 0x37ccc68)"
time="2020-07-13T21:15:56Z" level=debug msg="\t/usr/local/go/src/runtime/panic.go:975 +0x3d4"
time="2020-07-13T21:15:56Z" level=debug msg="crypto/tls.(*Conn).serverHandshake(0x4956600, 0x0, 0x1bf6458)"
time="2020-07-13T21:15:56Z" level=debug msg="\t/usr/local/go/src/crypto/tls/handshake_server.go:41 +0x38"
time="2020-07-13T21:15:56Z" level=debug msg="crypto/tls.(*Conn).Handshake(0x4956600, 0x0, 0x0)"
time="2020-07-13T21:15:56Z" level=debug msg="\t/usr/local/go/src/crypto/tls/conn.go:1342 +0x200"
time="2020-07-13T21:15:56Z" level=debug msg="net/http.(*conn).serve(0x5074180, 0x21d4460, 0x4cd4fc0)"
time="2020-07-13T21:15:56Z" level=debug msg="\t/usr/local/go/src/net/http/server.go:1788 +0x180"
time="2020-07-13T21:15:56Z" level=debug msg="created by net/http.(*Server).Serve"
time="2020-07-13T21:15:56Z" level=debug msg="\t/usr/local/go/src/net/http/server.go:2933 +0x2d0"
E0713 21:15:56.903190       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
time="2020-07-13T21:15:57Z" level=debug msg="http: panic serving 10.44.0.0:48786: runtime error: invalid memory address or nil pointer dereference"
time="2020-07-13T21:15:57Z" level=debug msg="goroutine 260 [running]:"
time="2020-07-13T21:15:57Z" level=debug msg="net/http.(*conn).serve.func1(0x48bf860)"
time="2020-07-13T21:15:57Z" level=debug msg="\t/usr/local/go/src/net/http/server.go:1772 +0xf0"
time="2020-07-13T21:15:57Z" level=debug msg="panic(0x1a96e88, 0x37ccc68)"
time="2020-07-13T21:15:57Z" level=debug msg="\t/usr/local/go/src/runtime/panic.go:975 +0x3d4"
time="2020-07-13T21:15:57Z" level=debug msg="crypto/tls.(*Conn).serverHandshake(0x502c200, 0x0, 0x1bf6458)"
time="2020-07-13T21:15:57Z" level=debug msg="\t/usr/local/go/src/crypto/tls/handshake_server.go:41 +0x38"
time="2020-07-13T21:15:57Z" level=debug msg="crypto/tls.(*Conn).Handshake(0x502c200, 0x0, 0x0)"
time="2020-07-13T21:15:57Z" level=debug msg="\t/usr/local/go/src/crypto/tls/conn.go:1342 +0x200"
time="2020-07-13T21:15:57Z" level=debug msg="net/http.(*conn).serve(0x48bf860, 0x21d4460, 0x4cd4fc0)"
time="2020-07-13T21:15:57Z" level=debug msg="\t/usr/local/go/src/net/http/server.go:1788 +0x180"
time="2020-07-13T21:15:57Z" level=debug msg="created by net/http.(*Server).Serve"
time="2020-07-13T21:15:57Z" level=debug msg="\t/usr/local/go/src/net/http/server.go:2933 +0x2d0"
E0713 21:15:57.907857       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
time="2020-07-13T21:15:58Z" level=debug msg="http: TLS handshake error from 10.44.0.0:58384: tls: client offered only unsupported versions: []"
E0713 21:15:58.911951       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}}],"kind":"I|...
time="2020-07-13T21:15:59Z" level=debug msg="http: TLS handshake error from 10.44.0.0:48800: tls: client offered only unsupported versions: []"
E0713 21:15:59.916089       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
E0713 21:16:00.920390       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
time="2020-07-13T21:16:01Z" level=debug msg="http: TLS handshake error from 10.44.0.0:48806: tls: client offered only unsupported versions: []"
E0713 21:16:01.924527       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
E0713 21:16:02.928465       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|}],"tls":[{"secretNa|..., bigger context ...|"services":[{"name":"whoami","port":80}]}],"tls":[{"secretName":"default-certificate"}]}},{"apiVersi|...
time="2020-07-13T21:16:03Z" level=debug msg="http: TLS handshake error from 10.44.0.0:48820: tls: client offered only unsupported versions: []"

```
