### ISSUE TITLE
RedirectRegex middleware causing not found for hosts in v2.2.4

### ISSUE THREAD

**Issue by snowzach** [containous/traefik#7048]
### What did you do?
I used docker to make a basic configuration for 2 hostnames that uses Lets Encrypt for TLS and one hostname will redirect to the other. 

### What did you expect to see?
I expect any time you browse to traefik2.example.com I expect it to redirect to traefik.example.com and have it work. 

### What did you see instead?
I browse to traefik2.example.com and it redirects to traefik.example.com and then returns 404 not found. 

### Output of `traefik version`: (_What version of Traefik are you using?_)
This happens on v2.2.4 in docker. If I roll back to v2.2.2 the issue goes away.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using docker-compose
```yaml
version: '3.2'

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /data/docker/traefik/config.toml:/etc/traefik/config.toml:ro
      - /data/docker/traefik/acme.json:/acme.json
    ports:
      - "80:80"
      - "443:443"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.example.com`) || Host(`traefik2.example.com`)"
      traefik.http.routers.traefik.entrypoints: "https"
      traefik.http.routers.traefik.middlewares: "traefik-redirect"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.tls.certresolver: "letsencrypt"
      traefik.http.middlewares.traefik-redirect.redirectregex.regex: "^https://traefik2.example.com(.*)"
      traefik.http.middlewares.traefik-redirect.redirectregex.replacement: "https://traefik.example.com$${1}"
```

traefik.toml
```toml
[global]
  CheckNewVersion = true

[log]
  level = "INFO"

[api]
  dashboard = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers.letsencrypt.acme]
  email = "certs@example.com"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "http"

[providers]
  [providers.file]
    filename = "/etc/traefik/config.toml"
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    network = "hostnet"
    watch = true
    exposedbydefault = false
```

config.toml
```toml
[http]
  [http.routers]
    # Redirect everything to https
    [http.routers.https-redirect]
      entryPoints = ["http"]
      rule = "HostRegexp(`{any:.*}`)"
      priority = 1
      middlewares = ["https-redirect"]
      service = "dummy"

  [http.services]
    # redirect http -> https
    [http.services.dummy.LoadBalancer]
      [[http.services.dummy.LoadBalancer.servers]]
          url = ""

  # redirect https middleware
  [http.middlewares]
    [http.middlewares.https-redirect.redirectScheme]
      scheme = "https"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

When failing it's like it's not matching the rules
```
traefik    | 107.11.56.116 - - [14/Jul/2020:12:05:53 +0000] "GET /dashboard/ HTTP/2.0" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.
36" 18 "traefik@docker" "-" 0ms
traefik    | 107.11.56.116 - - [14/Jul/2020:12:05:53 +0000] "GET /dashboard/ HTTP/2.0" 404 19 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537
.36" 19 "-" "-" 0ms
```

**Comment by ldez** [comment]
Hello,

I don't reproduce your issue:

```yml
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.4
    command:
      # - --log.level=DEBUG
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true

      traefik.http.routers.traefik.rule: Host(`traefik.localhost`) || Host(`traefik2.localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: traefik-redirect
      traefik.http.routers.traefik.tls: true
      
      traefik.http.middlewares.traefik-redirect.redirectregex.regex: ^https://traefik2.localhost(.*)
      traefik.http.middlewares.traefik-redirect.redirectregex.replacement: https://traefik.localhost$${1}
```

<details><summary>https://traefik.localhost</summary>

```console
$ curl -k -v https://traefik.localhost
*   Trying ::1:443...
* Connected to traefik.localhost (::1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: Jul 14 12:19:05 2020 GMT
*  expire date: Jul 14 12:19:05 2021 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x560b514bb8b0)
> GET / HTTP/2
> Host: traefik.localhost
> user-agent: curl/7.70.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 302 
< content-type: text/html; charset=utf-8
< location: /dashboard/
< content-length: 34
< date: Tue, 14 Jul 2020 12:20:40 GMT
< 
<a href="/dashboard/">Found</a>.

* Connection #0 to host traefik.localhost left intact
```
</details>

<details><summary>https://traefik2.localhost</summary>

```console
$ curl -k -v  https://traefik2.localhost
*   Trying ::1:443...
* Connected to traefik2.localhost (::1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: Jul 14 12:19:05 2020 GMT
*  expire date: Jul 14 12:19:05 2021 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55f28b3718b0)
> GET / HTTP/2
> Host: traefik2.localhost
> user-agent: curl/7.70.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 302 
< location: https://traefik.localhost/
< content-type: text/plain; charset=utf-8
< content-length: 5
< date: Tue, 14 Jul 2020 12:19:31 GMT
< 
* Connection #0 to host traefik2.localhost left intact
```
</details>
