### ISSUE TITLE
when I use multi-routers.rule on one service，it works no good

### ISSUE THREAD

**Issue by wzj1223** [containous/traefik#7050]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I use `docker-compose` to run a frps service , and set mutli-routers.service.rule ,the frps worked no problem,
Only one in host can be successfully accessed.
When I visit other hosts, 404 page not found is displayed, and no content is output in the traefik log
``` yml
version: 2
services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    ports:
      - 7000:7000
    volumes:
      - /root/app/frps/frps.ini:/etc/frp/frps.ini
    labels:
      - traefik.http.routers.frps-http.rule=Host(`nas.wzjcfx.xyz`,`jellyfin.wzjcfx.xyz`,`tm.wzjcfx.xyz`,`tmm.wzjcfx.xyz`)
      - traefik.http.routers.frps-http.entrypoints=HTTPS
      - traefik.http.routers.frps-http.tls=true
      - traefik.http.routers.frps-http.service=frps-http
      - traefik.http.services.frps-http.loadbalancer.server.port=80
      - traefik.http.routers.frps-http.tls.certresolver=myresolver
    restart: always
```
### What did you expect to see?

All of the above hosts can be accessed

### What did you see instead?
Only one in host can be successfully accessed，

### Output of `traefik version`: (_What version of Traefik are you using?_)

config.yml
``` yml
entryPoints:
    HTTP:
        address: ":80"
    HTTPS:
        address: ":443"
api:
    insecure: true
    dashboard: true
ping: true
accessLog: {}
#log:
#    filePath: /var/log/traefik.log
#    level: DEBUG
certificatesResolvers:
    myresolver:
        acme:
            email: 123@qq.com
            storage: /letsencrypt/acme.json
            httpChallenge:
              # used during the challenge
                entryPoint: HTTP
            tlsChallenge: {}
            #dnsChallenge:
            #    provider: digitalocean
            #    delayBeforeCheck: 0
providers:
    file:
        directory: /etc/traefik/providers
    docker:
        defaultRule: "Host(`{{ .Name}}.wzjcfx.xyz`)"

```
traefik docker-compose.yml
``` yml
version: '2'
services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    container_name: traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
    # Enables the web UI and tells Traefik to listen to docker
    # command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/app/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /root/app/traefik/providers:/etc/traefik/providers

```

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
