### ISSUE TITLE
Add custom headers for mirroring service 

### ISSUE THREAD

**Issue by geosmart** [containous/traefik#7051]
---
name: Feature request
about: Add custom headers for mirroring service

---
the middlewares only work on router,I need to add diffrent header with the mirroring service

does mirroring service support custome request/response header ?

```yaml
http:
  middlewares:
    add-solution-headers-hello-123:
      headers:
        customRequestHeaders:
          X-Solution-Id: "sol1"
          X-Solution-Version: "1"
        customResponseHeaders:
          X-Solution-Id: "sol1"
          X-Solution-Version: "1"

  routers:
    dashboard:
      entryPoints:
        - dashboard
      rule: PathPrefix(`/`)
      service: api@internal
    default:
      entryPoints:
        - app
      rule: PathPrefix(`/`)
      service: default
      middlewares:
        - strip-router-path
      priority: 1

    router-hello-123:
      entryPoints:
        - app
      rule: HeadersWeight(`X-Version`, `1`, `0`, `0`)
      service: mirror-hello-123
      middlewares:
        - add-solution-headers-hello-123
      priority: 10


  services:
    default:
      loadBalancer:
        servers:
          - url: http://hello-123.mlp-serve/
    mirror-hello-123:
      mirroring:
        service: service-hello-123
        maxBodySize: -1
        mirrors:
          - name: mirror-service-80
            percent: 50

    mirror-service-80:
      loadBalancer:
        servers:
          - url: http://service-80.mlp-serve
      # does mirroring service support custome request/response header ?
      headers:
        customRequestHeaders:
          X-Solution-Id: "sol3"
          X-Solution-Version: "3"
        customResponseHeaders:
          X-Solution-Id: "sol3"
          X-Solution-Version: "3"
```

-->
