### ISSUE TITLE
How Routing traffic depending on path not domain in docker

### ISSUE THREAD

**Issue by mwaaas** [containous/traefik#706]
I have tried this and its not working

traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

machine:
  image: katacoda/docker-http-server
  labels:
    - "traefik.backend=machine-echo"
    - "traefik.frontend.rule=Path:machine-echo./machine"

echo:
  image: katacoda/docker-http-server:v2
  labels:
    - "traefik.backend=echo"
    - "traefik.frontend.rule=Path:echo-echo./echo"

**Comment by MBuffenoir** [comment]
very curious about this also, to route traffic to different api version ...

**Comment by emilevauge** [comment]
What is not working exactly? Have you tried `PathPrefix` or `PathPrefixStrip` rules instead?

**Comment by mwaaas** [comment]
@emilevauge I have tried using this - "traefik.frontend.rule=Path:echo-echo./echo"  I can't see the documentation of "PathPrefix" or "PathPrefixStrip"

**Comment by emilevauge** [comment]
http://docs.traefik.io/basics/#frontends

**Comment by mwaaas** [comment]
@emilevauge thanks

Finally got it, it wasn't so obvious from the documentation

traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami2"
    - "traefik.frontend.rule=Path:/test2/, */mwas/*"

**Comment by mwaaas** [comment]
@emilevauge  quick question how does one do regex for path in traefik

**Comment by romainlaisne** [comment]
Hi Guys,

I am trying to do the same but cannot make it works.
I am trying to have mydomain.dev/pma pointing on the phpmyadmin backend:

```
web:
    image: nginx
    links:
        - app
    volumes_from:
        - app
    volumes:
        - ./web/nginx.conf:/etc/nginx/nginx.conf
    labels:
        - "traefik.backend=web"
        - "traefik.frontend.rule=Host:mydomain.dev"
        - "traefik.port=80"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db
    labels:
        - "traefik.backend=phpmyadmin"
        - "traefik.frontend.rule=Host:mydomain.dev;Path:/pma"
```

Anyone having an idea how to solve this?

Thanks
