### ISSUE TITLE
K8s Minor Version String Conversion Fails

### ISSUE THREAD

**Issue by bradshjg** [containous/traefik#7061]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Applied the following deployment manifest

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: default
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.3
        name: traefik-ingress-lb
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - name: https
          containerPort: 443
        args:
        - --api
        - --ping
        - --providers.kubernetesingress
        - --providers.kubernetesingress.namespaces=default
        - --log.level=INFO
        - --entrypoints.https
        - --entrypoints.https.address=:443
        - --entrypoints.https.http.tls
```

### What did you expect to see?

I mostly expected that I'd messed up the config 😄 

### What did you see instead?

Error log lines regarding the inability to do the string conversion to an integer for the minor version of the Kubernetes server

Example:

```
time="2020-07-17T00:50:38Z" level=error msg="Error watching kubernetes events: could not determine cluster minor API version: strconv.Atoi: parsing \"16+\": invalid syntax" providerName=kubernetes
time="2020-07-17T00:50:39Z" level=error msg="Provider connection error: could not determine cluster minor API version: strconv.Atoi: parsing \"16+\": invalid syntax; retrying in 3.158846681s" providerName=kubernetes
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc2
Codename:     picodon
Go version:   go1.14.5
Built:        2020-07-15T20:22:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

(Kubernetes pod spec with health checking removed)

```yaml
      - image: traefik:v2.3
        name: traefik-ingress-lb
        ports:
        - name: https
          containerPort: 443
        args:
        - --api
        - --ping
        - --providers.kubernetesingress
        - --providers.kubernetesingress.namespaces=default
        - --log.level=INFO
        - --entrypoints.https
        - --entrypoints.https.address=:443
        - --entrypoints.https.http.tls
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A (well, I could be wrong but I think I know what the issue is)

https://github.com/containous/traefik/blob/8f2951b275d88312a1add5084fa985e5d878be7a/pkg/provider/kubernetes/ingress/client.go#L395

The Kubernetes server version is not guaranteed to be a value that can be trivially converted to an integer.

Docker UCP

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-docker-1", GitCommit:"3ffbabe840b101d7c84263431c8a18b27785929a", GitTreeState:"clean", BuildDate:"2019-05-10T17:53:06Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Docker Desktop (OSX)

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

I'm not familiar with feature detection in Kubernetes (but am willing to learn it if no one else is either :smile:), but since this is currently only used to support the `IngressClass`, would it be more appropriate to go a non-version-based route here?
