### ISSUE TITLE
How to use Traefik to transfer the real IP address of the client to the back-end application server. The log of the back-end application server obtains the real IP of the client through x-forward-for

### ISSUE THREAD

**Issue by gaoyang02** [containous/traefik#7063]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

My architecture is like this:

The front end is the ELB of Huawei cloud, which is configured with 4-layer load balancing based on TCP. ELB has public IP and private IP. The a record corresponding to the domain name of the application we want to access is the ELB elastic public IP.

Tracevik V2.2 is deployed in the k8s cluster, and I deployed it through helm. Tracevik uses the host network mode, and tracevik has opened ports such as 80, 443, 9000, and 3 instances are configured. The IP of traefik  is the IP of the host, and the port of traefik is the port of 80 443 9000 on the host;

The ELB of Huawei cloud forwards the ports of 80  443  9000 of the hosts of the three rear-end tracevik servers through the four layer forwarding mode of TCP;
I deployed a nginx deployment in k8s through the list file. The contents of the list file are as follows:
The log contents I see on the nginx container are as follows:

10.243.30.128 - - [17/Jul/2020:07:03:01 +0000] "GET /favicon.ico HTTP/1.1" 404 555 "http://nginxtest.newtest.huaxiacloud.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "100.125.64.157"

The last IP field I want to see in the nginx container log is the actual IP of the customer. This field is actually from the x-forward-for field in the nginx configuration file. 

Huawei cloud provides a solution for how to obtain real IP in ELB tcp4 layer forwarding mode, which is mainly realized by loading toa kernel module. This scheme has been verified;

My verification method is to use docker run - D - P 80:80 -- name nginx nginx on one of the k8s hosts, and then use docker logs - f container ID to see the log. The first field is the real client IP address;

My Huawei cloud ELB maps port 80 to port 80 of the host running nginx container through docker run. ELB has external network and internal network addresses. Once accessed through the external network address, the first field is the real IP;

```
The list file of nginx application deployed on the k8s cluster is as follows：


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest
  namespace: test-broker
  labels:
    k8s-app: nginxtest

spec:
  replicas: 1
  revisionHistoryLimit: 3
  #The pod is considered ready after 70 seconds of rolling upgrade
  minReadySeconds: 70
  strategy:
    ##Because repliadminii is 3, the number of pods is between 2 and 4
    rollingUpdate:
      #When rolling upgrade, one pod will be started first  
      maxSurge: 1 
      #Maximum number of unavailable pods allowed during rolling upgrade     
      maxUnavailable: 1   
  selector:
    matchLabels:
      k8s-app: nginxtest
  template:
    metadata:
      labels:
        k8s-app: nginxtest
    spec:
      containers:
      - name: nginxtest
        image: nginx
        #image: nginx
        #env:
        #- name: adminui_PROFILES_ACTIVE
        #  value: "dev"  
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            memory: 2048Mi
            cpu:  1000m
          requests:
            cpu: 500m
            memory:  1024Mi
        ports:
        #The port of the container
        - containerPort: 80
          name: nginxtest
          protocol: TCP        
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 360
          periodSeconds: 20   
        #volumeMounts:
        #- mountPath: "/download"
        #  name: data
      imagePullSecrets:
      - name: myregistrykey    
      #volumes:
      #- name: data
      #  persistentVolumeClaim:
      #    claimName: download-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginxtest
  namespace: test-broker
  labels:
    k8s-app: nginxtest
spec:
  ports:
  #Port of cluster IP
  - port: 80
    name: nginxtest
    protocol: TCP
    #The port of the container
    targetPort: 80
  selector:
    k8s-app: nginxtest
#  externalTrafficPolicy: Local
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: known-ips
  namespace: test-broker
spec:
  ipWhiteList:
    sourceRange:
    - 0.0.0.0/0
    ipstrategy:
      depth: 2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginxtest
  namespace: test-broker
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`nginxtest.newtest.huaxiacloud.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: nginxtest
      port: 80
    middlewares:
    - name: known-ips


The nginx configuration file is as follows:


user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

### What did you expect to see?
I hope to see the real IP address of the client in the log on the back-end nginx server

### What did you see instead?
The value of the x-forward-for field I see in the log of the nginx container on the back-end is 100.125.64. X, which is not the IP address of the real client;

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traefik
      release: traefik2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: traefik
        chart: traefik-7.0.0
        heritage: Helm
        release: traefik2
    spec:
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --serversTransport.insecureSkipVerify=true
        - --api.insecure
        - --accesslog
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --entrypoints.websecure.forwardedHeaders.insecure
        - --entrypoints.web.forwardedHeaders.insecure
        - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --providers.kubernetescrd
        - --certificatesresolvers.default.acme.tlschallenge
        - --certificatesresolvers.default.acme.email=gaoyang02@chinasofti.com
        - -certificatesresolvers.default.acme.storage=acme.json
        - --entryPoints.traefik.address=:9000
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
        - --api.dashboard=true
        - --ping=true
        - --providers.kubernetescrd
        image: traefik:2.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik2
        ports:
        - containerPort: 9000
          hostPort: 9000
          name: traefik
          protocol: TCP
        - containerPort: 80
          hostPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        role: ingress
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik2
      serviceAccountName: traefik2
      terminationGracePeriodSeconds: 60
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: traefik2
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by matodrobec** [comment]
Hello @gaoyang02 ,

have you found solution. My nginx config always show internal ip but I would like original and also php-fpm should show correct HTTP_X_FORWARDED_FOR with client ip

traefik conf:
```
entrypoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

  web81:
    address: ":8081"
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
```
nginx conf:
```
server {
    charset utf-8;
    root /var/www/www;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    #
    # common
    #
    index index.html index.htm;

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto  $scheme;
    proxy_set_header   X-Forwarded-Host $server_name;

```
