### ISSUE TITLE
KubernetesIngress provider does not create separate routers for HTTP, HTTPS

### ISSUE THREAD

**Issue by stuartherbert** [containous/traefik#7069]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Here's the ingress that I'm using, with the hostname changed for privacy reasons.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: test
  labels:
    app: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.tls.options: default
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: http
  tls:
  - hosts:
    - example.com
    secretName: example.com-cert
```

I'm running Traefik on K3S, with the KubernetesIngress provider enabled, and two entrypoints for port 80 and port 443.

### What did you expect to see?

I expected to be able to connect to this example website via HTTP and HTTPS.

### What did you see instead?

I could only connect to this example website via HTTPS. If I remove the tls-options annotation, I can only connect to this example website via HTTP.

According to the Traefik dashboard, the Kubernetes Ingress provider is only creating the one router. According to the Traefik docs, a single router can't support both HTTP and HTTPS simultaneously.

It looks like the Kubernetes Ingress provider needs updating to generate separate routers for HTTP and HTTP traffic?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.2.5 built on 2020-07-13T16:35:29Z
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-lb
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/instance: traefik-system
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: k3s-stack
spec:
  selector:
    matchLabels:
      app: traefik-ingress-lb
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        app.kubernetes.io/name: traefik-ingress
        app.kubernetes.io/instance: traefik-system
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: controller
        app.kubernetes.io/part-of: k3s-stack
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --api.dashboard=true
        - --providers.kubernetesingress
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --log.level=DEBUG
```
