### ISSUE TITLE
Port Error 421 in 2.2.6 -> misdirected request

### ISSUE THREAD

**Issue by bd8392** [containous/traefik#7070]
### Do you want to request a *feature* or report a *bug*?
 

Bug

### What did you do?
Updated to Traefik Version 2.2.6 -> Backend config not working anymore (other port than 80 and 443) but working on 2.2.2

### What did you expect to see?

Working config for another prot than 80 and 443 (Used Port 50077)

### What did you see instead?

Config stopped working after updated to 2.2.6 from 2.2.2. The ports 80 and 443 remained working.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.6 (version with bug)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```bash

    - --log=true
     - --log.level=DEBUG
     - --accesslog=true
     - --accesslog.filepath=/var/log/traefik/access.log
     - --accesslog.filters.statuscodes=400-499
     - --providers.docker.exposedbydefault=false
     - --entryPoints.web.address=:80
     - --entryPoints.web-secure.address=:443
     - --entryPoints.backend.address=:50077
     - --global.sendAnonymousUsage=false
     - --global.checknewversion=false
     - --serverstransport.insecureskipverify=true
     - --providers.docker.swarmMode=true
     - --providers.docker=true
     - --providers.docker.endpoint=unix:///var/run/docker.sock
     - --providers.docker.network=some_net
     - --providers.file.directory=/etc/traefik/dynamic
     - --providers.file.watch=true
     - --certificatesResolvers.letsencrypt.acme.email=someprivateinfo
     - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
     - --certificatesResolvers.letsencrypt.acme.tlsChallenge=true
     - --certificatesResolvers.letsencrypt.acme.keyType=RSA4096

```

```toml
[http]
  # Https redirect
  [http.middlewares]
    [http.middlewares.redirect.redirectScheme]
      scheme = "https"
      permanent = true
      # Security-Headers
    [http.middlewares.security-headers.headers]
      accessControlMaxAge = 100
      addVaryHeader = true
      browserXssFilter = true
      contentTypeNosniff = true
      forceSTSHeader = true
      sslRedirect = true
      stsIncludeSubdomains = true
      referrerPolicy = "same-origin"
      featurePolicy = "vibrate 'self'"
      stsSeconds = 315360000
    [http.middlewares.response-headers.headers.customResponseHeaders]
      X-Powered-By = "memyselfandi"
      Server = "memyselfandi"
      X-Frame-Options = "sameorigin"
#      Set-Cookie = "Set-Cookie: SameSite=Strict; HttpOnly; Secure"
    [http.middlewares.ratelimit-ddos.rateLimit]
      average = 1000
      burst = 500
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
The log doesn't output any error...just some info
```
