### ISSUE TITLE
Incorrect status code (403 instead 404) for unknown router

### ISSUE THREAD

**Issue by Heisenberg74** [containous/traefik#7073]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I try to reach an unknown router 

```
curl -i --insecure https://unknown-router.local
```

### What did you expect to see?
I expect to see a 404 error, as no service as served by Traefik

### What did you see instead?
I see a 403 error

```
HTTP/2 403
accept-ranges: bytes
content-type: text/html
date: Sun, 19 Jul 2020 14:07:05 GMT
etag: "5f0df1ba-396c"
last-modified: Tue, 14 Jul 2020 17:56:10 GMT
server: nginx/1.19.1
content-length: 14700
```

### Other example:
If i execute
```
curl -i --insecure https://unknown-router.local/john_doe
```
I have a 404 error, which is the correct answer as router doesn't exist
```
HTTP/2 404
accept-ranges: bytes
content-type: text/html
date: Sun, 19 Jul 2020 14:06:38 GMT
etag: "5f0df1ba-2cf5"
last-modified: Tue, 14 Jul 2020 17:56:10 GMT
server: nginx/1.19.1
content-length: 11509
```
### Output of `traefik version`: (_What version of Traefik are you using?_)
2.2.6

### Thanks

**Comment by ldez** [comment]
Hello,

Traefik never returns a 403 by it-self: he returns only 404 when a route doesn't exist.

Could you provide your configuration (full not partial) or a minimal reproducible example?

**Comment by Heisenberg74** [comment]
Here the configuration files.

### Tests
```
curl -i --insecure https://unknown-router.local/john_doe --> return 404
curl -i --insecure https://unknown-router.local/ --> return 403
```

### docker-compose.yaml
```
version: "3.8"

services:
  traefik:
    image: traefik:2.2.6
    environment:
      - "TZ=Europe/Paris"
    depends_on:
      - docker-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./volumes/traefik:/etc/traefik:ro
      - ./volumes/access-logs:/var/access-logs
      - ./volumes/certs:/certs:ro
      - ./volumes/acme:/acme
      - ./volumes/logs:/var/log
    networks:
      - traefik
      - docker-proxy
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 50m
      mode: replicated
      replicas: 1

  docker-proxy:
    environment:
      CONTAINERS: 1
      SWARM: 1
      TASKS: 1
      NODES: 1
      DISTRIBUTION: 1
      SERVICES: 1
      EXEC: 1
      NETWORKS: 1
    image: tecnativa/docker-socket-proxy
    networks:
      - docker-proxy
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 50m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  docker-proxy:
    driver: overlay
  traefik:
    external: true
    name: traefik_public

```
### traefik.yaml
```
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

ping:
  entryPoint: "traefik"

providers:
  docker:
    exposedbydefault: false
    endpoint: "tcp://docker-proxy:2375"
    network: "traefik_public"
    swarmMode: true
    swarmModeRefreshSeconds: 15
  file:
    directory: "/etc/traefik/"
    watch: true

http:
  routers:
    api:
      rule: Host(`traefik.localhost`)
      service: api@internal
      entryPoints:
        - traefik

  middlewares:
    redirect-to-nonwww:
      redirectRegex:
        regex: "^https://www.(.*)"
        replacement: "https://$1"
        permanent: true

api:
  dashboard: true

```
