### ISSUE TITLE
Is YAML newline directive is ignored?

### ISSUE THREAD

**Issue by osher** [containous/traefik#7074]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I hope I get here a good isolation of the problem...

Consider the following Yaml form, used in a file provider.

```yml
http:
  routers:
    static: 
      rule: >-
        PathPrefix(`/api`) 
        && ( 
          Host(`localhost`) 
          || HostRegexp(`front\..*`)
        )
    service: api
```

Note that `>-` in beginning of yaml multiline is a parser directive to replace new lines with spaces, squat multiple whitespaces with a single space, and trim white spaces from the end.
[info about yaml new lines](https://yaml-multiline.info/)

### What did you expect to see?

The router should be accepted.

### What did you see instead?

```
error while parsing rule PathPrefix(`/api`) && ( Host(`localhost`) || HostRegexp(`front\..*`) ): 2:21: expected ')', found newline (and 1 more errors)
```
Mind that if I put it in a single line - the rule is accepted

e.g. 

```
      rule:  PathPrefix(`/api`)  && (  Host(`localhost`) || HostRegexp(`front\..*`) )
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc2
Codename:     picodon
Go version:   go1.14.5
Built:        2020-07-15T20:22:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

static: - in docker-compose
```yaml
version: '3.4'
services:
  bus:
    image: traefik:v2.3
    volumes:
      - './bus/config:/config'
      #- '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '80:80'     #front
      - '8080:8080' #traefik dashboard
    command: >-
      --api.insecure=true
      --global.checkNewVersion=false
      --global.sendAnonymousUsage=false
      --providers.file.watch=true
      --providers.file.directory=/config
      --entryPoints.epFront.address=:80
      --entryPoints.epSvr.address=:3000
      --log.level=DEBUG
    #  --accesslog=true
    #  --providers.docker

    restart: always
```

dynamic:
```yaml
http:
  routers:
    static: 
      rule: >-
        PathPrefix(`/api`) 
        && ( 
          Host(`localhost`) 
          || HostRegexp(`front\..*`)
        )
    service: api
  services:
    api:
      loadBalancer:
        servers:
          - url: http://front:3000
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
