### ISSUE TITLE
mTLS from backend to server

### ISSUE THREAD

**Issue by mafrosis** [containous/traefik#7076]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Has there been any further thinking on:

#4260, #5146 or https://community.containo.us/t/mtls-add-client-cert-on-outbound/723

The community forum post is most specific to my exact use-case.

```
┌─────────┐      ┌──────────┐     ┌─────────┐           ┌─────────────┐
│ Client  │  ┌──▶│ HTTPS L7 │     │ Traefik │───mTLS───▶│ Destination │
│         │──┘   │    LB    │────▶│         │           │   server    │
└─────────┘      └──────────┘     └─────────┘           └─────────────┘
```

**Comment by mpl** [comment]
Duplicate of #5146
(we know #7076 is a broader scope, but we'll reopen later if needed)

**Comment by mafrosis** [comment]
@mpl To be clear, I don't want to `passTLSClientCert` through Traefik from the client onto the server. I want plain HTTPS on `router` side, and mTLS on the backend connection to the `service`.

#5146 and this issue could have the same resolution - If you ignore all the `passTLSClientCert` parts 😄 

I imagine a config might look like:

```
http:
  routers:
    mtls-proxy:
      rule: Host:backend.example.com
      service: mtls-backend

  middlewares:
    mtls:
      addTLSClientCert:
        cert: /tmp/secret.crt
        key: /tmp/secret.key

  services:
    mtls-backend:
      loadBalancer:
        servers:
          - url: http://10.10.10.1:80
```
