### ISSUE TITLE
HTTP Routers page of Dashboard refreshing with missing data

### ISSUE THREAD

**Issue by TheSpad** [containous/traefik#7077]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Load Dashboard, navigate to "HTTP Routers"

### What did you expect to see?

Dashboard should refresh periodically without error.

### What did you see instead?

After approximately 5 seconds the dashboard refreshes to display missing data and broken images, with a corresponding `http2: stream closed` error in the logs:
![Annotation 2020-07-20 142920](https://user-images.githubusercontent.com/8425502/87943323-c444c300-ca95-11ea-9418-9360cf90cefe.jpg)

Note this doesn't happen with the Services or Middleware pages. It also doesn't happen if you use the "Success/Warning/Error" tabs, only on the default "All Status" tab.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.6
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-17T16:17:36Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

tls:
  options:
    minVersion: VersionTLS12
    cipherSuites:
     - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
     - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
     - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.example.com`)"
    network: proxy
  file:
    directory: "/configs"
    watch: true

certificatesResolvers:
  dns:
    acme:
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: cert@example.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

serversTransport:
    insecureSkipVerify: true

accessLog:
  filePath: "/access.log"

log:
  level: DEBUG
```
compose
```
version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/configs:/configs:ro
      - ./data/acme.json:/acme.json
      - ./data/access.log:/access.log
    environment:
      - CF_DNS_API_TOKEN=<redacted>
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:<redacted>"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.STSHeaders.headers.STSSeconds=15768000"
      - "traefik.http.middlewares.STSHeaders.headers.STSIncludeSubdomains=true"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth,STSHeaders,internal-ipwhitelist@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls.certresolver=dns"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=example.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.example.com"

networks:
  proxy:
    external: true
```
```
Linux docker 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        dd360c7
 Built:             Mon Jun  8 20:23:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:24:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-07-20T13:42:23Z" level=debug msg="Authentication succeeded" middlewareType=BasicAuth middlewareName=traefik-auth@docker
time="2020-07-20T13:42:23Z" level=debug msg="Authentication succeeded" middlewareName=traefik-auth@docker middlewareType=BasicAuth
time="2020-07-20T13:42:23Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/overview Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc0001a8620 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/overview TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc0009f8c60}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:23Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/http/routers?search=&status=&per_page=988&page=1 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc0008cd520 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/http/routers?search=&status=&per_page=988&page=1 TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc00092c420}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:23Z" level=debug msg="Authentication succeeded" middlewareName=traefik-auth@docker middlewareType=BasicAuth
time="2020-07-20T13:42:23Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/http/routers?search=&status=&per_page=10&page=1 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc0001a9440 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/http/routers?search=&status=&per_page=10&page=1 TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc0009f9950}" middlewareType=IPWhiteLister middlewareName=internal-ipwhitelist@file
time="2020-07-20T13:42:23Z" level=debug msg="Authentication succeeded" middlewareType=BasicAuth middlewareName=traefik-auth@docker
time="2020-07-20T13:42:23Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/http/routers?search=&status=&per_page=10&page=2 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc0008cdce0 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/http/routers?search=&status=&per_page=10&page=2 TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc00092d7a0}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:23Z" level=debug msg="Authentication succeeded" middlewareName=traefik-auth@docker middlewareType=BasicAuth
time="2020-07-20T13:42:23Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/http/routers?search=&status=&per_page=10&page=3 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc00050ed40 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/http/routers?search=&status=&per_page=10&page=3 TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc0007f28a0}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:28Z" level=debug msg="Authentication succeeded" middlewareName=traefik-auth@docker middlewareType=BasicAuth
time="2020-07-20T13:42:28Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/overview Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc000a05060 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/overview TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc0009ee3c0}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:29Z" level=debug msg="Authentication succeeded" middlewareType=BasicAuth middlewareName=traefik-auth@docker
time="2020-07-20T13:42:29Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/http/routers?search=&status=&per_page=20&page=1 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc000a056c0 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/http/routers?search=&status=&per_page=20&page=1 TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc0009eeff0}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:29Z" level=error msg="http2: stream closed"
time="2020-07-20T13:42:29Z" level=debug msg="Authentication succeeded" middlewareName=traefik-auth@docker middlewareType=BasicAuth
time="2020-07-20T13:42:29Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/dashboard/statics/providers/undefined.svg Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[image/webp,*/*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Cache-Control:[max-age=0] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc000a05e80 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/dashboard/statics/providers/undefined.svg TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc0009efe60}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
time="2020-07-20T13:42:33Z" level=debug msg="Authentication succeeded" middlewareName=traefik-auth@docker middlewareType=BasicAuth
time="2020-07-20T13:42:33Z" level=debug msg="Accept 192.168.2.128: &{Method:GET URL://admin@/api/overview Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, text/plain, */*] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-GB,en;q=0.5] Authorization:[Basic YWRtaW46UFZkWDNXSXdMMFR5VWdNTVN4Wks=] Dnt:[1] Referer:[https://traefik.example.com/dashboard/] Te:[trailers] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0] X-Forwarded-Host:[traefik.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[1ff1aaf5e801] X-Real-Ip:[192.168.2.128]] Body:0xc000e804e0 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:traefik.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.2.128:11915 RequestURI:/api/overview TLS:0xc000145e40 Cancel:<nil> Response:<nil> ctx:0xc000c52900}" middlewareName=internal-ipwhitelist@file middlewareType=IPWhiteLister
```
