### ISSUE TITLE
Traefik pilot : invalid token

### ISSUE THREAD

**Issue by lfache** [containous/traefik#7078]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Just try plugin on Traefik Pilot :) 

### What did you expect to see?

Make a simple docker-compose with : 

```yaml 

version: "3.8"
services:
  reverse_proxy:
    image: traefik:2.3
    restart: unless-stopped
    command:
     --api.insecure=true
     --accesslog
     --log.level=DEBUG
     --entrypoints.web.address=:80
     --providers.docker
     --providers.docker.exposedbydefault=false
     --experimental.pilot.token="xxxxxxxxxxxxxxxxxx"
     --experimental.plugins.blockpath.modulename="github.com/containous/plugin-blockpath"
     --experimental.plugins.blockpath.version="v0.1.2"
    ports:
      # The HTTP port
      - "80:80"
      # The Admin port
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - web

networks:
  web:
    name: traefik_wan
```

Token generate on https://pilot.traefik.io/.

Traefik does not start with the following error in debug:
```
reverse_proxy_1  | 2020/07/20 13:46:45 traefik.go:75: command traefik error: failed to download plugin github.com/containous/plugin-blockpath: error: 400: {"error":"invalid token"}
```

### What did you see instead?

Download plugin on instance

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc2
Codename:     picodon
Go version:   go1.14.5
Built:        2020-07-15T20:22:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
everse_proxy_1  | 2020/07/20 13:46:45 traefik.go:75: command traefik error: failed to download plugin github.com/containous/plugin-blockpath: error: 400: {"error":"invalid token"}
```
