### ISSUE TITLE
Feature: improved syntax for docker labels

### ISSUE THREAD

**Issue by osher** [containous/traefik#7081]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to suggest for Docker Provider to support the following syntax:
(actually, it may also be applicable for KV providers as well, but I haven't used any)

```
services:
  front:
    ...
    labels:
      - traefik.http.routers.static={"priority":1,"entryPoints":["epFront"],"rule":"PathPrefix(`/`),"middlewares":["cors@file"]}
```

Which by the way can look prettier if we can use yaml parser instead JSON parser.
(every JSON is yaml - so yaml parser will parse JSON too).

```
services:
  front:
    ...
    labels:
      - traefik.http.routers.static={priority:1,entryPoints:[epFront],rule:PathPrefix(`/`),middlewares:[cors@file]}
```

Very nice to have 1:
When the config value support new lines - take advantage of that.
In case of Docker-Compose:
```
services:
  front:
    ...
    labels:
      - |
        traefik.http.routers.static=
          priority: 1,
          entryPoints: [ epFront ],
          rule: PathPrefix(`/`),
          middlewares: [ cors@file ]
```
or depends on your preference
```
    labels:
      - |
        traefik.http.routers.static={
          "priority":1,
          "entryPoints":["epFront"],
          "rule":"PathPrefix(`/`),
          "middlewares":["cors@file"]
        }
```
- mind the yaml multiline directive `|` in the beginning of the label item in the docker-compose.

All the above examples, should be understood as:

```
    labels:
      - traefik.http.routers.static.priority=1  #i.e the lowest
      - traefik.http.routers.static.entryPoints=epFront
      - traefik.http.routers.static.rule=PathPrefix(`/`)
      - traefik.http.routers.static.middlewares=cors@file
```

## Default attribute feature

Whenever the attribute expects an object but the value parses to a string,
and whenever a default attribute can be deducted from the context - use that string as the default attribute.

E.g - Understand:
```
    labels:
      - traefik.http.routers.static=PathPrefix(`/`)
```
As
```
    labels:
      - traefik.http.routers.static.rule=PathPrefix(`/`)
```
(if we can agree that `rule` would be the default attribute for router, donno yet, i'm new here, that's just my gut feeling)

## The Proposed Logic:

 - Given an assignment to a key that expects an object
 - yaml-parse it. 
 - if the result is a string (but an object is expected), and a default attribute can be deducted from the context - convert it to an object with a single attribute in that name. 
 - merge the value to the dynamic config the usual way (as if it came from file provider)

This is a fun logic to implement and test, but I don't know `golang`, otherwise I'd start a PR right away...
