### ISSUE TITLE
traefik crashes when given access to only the kubernetes secrets it requires

### ISSUE THREAD

**Issue by mattharrigan** [containous/traefik#7092]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Ran traefik with the following edits to the [ClusterRole](https://docs.traefik.io/reference/dynamic-configuration/kubernetes-crd/#rbac)
```
rules:
  - apiGroups: [""]
    resources: [services, endpoints]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch]
    resourceNames: ["tls-cert"]
```
The only secret used by traefik is `tls-cert`

### What did you expect to see?
traefik running happily

### What did you see instead?
traefik exitted with the following log:
`"Error watching kubernetes events: timed out waiting for controller caches to sync *v1.Secret in namespace \"my-namespace\"" providerName=kubernetescrd`

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.1.9
Codename:     cantal
Go version:   go1.14.1
Built:        2020-03-23T17:23:17Z
OS/Arch:      linux/amd64
```

I think its crazy to give traefik access to all secrets.

**Comment by jbdoumenjou** [comment]
Hi @mattharrigan ,

In the RBAC, you need to allow to list all secret but you can limit the get and watch verb to the specific secret.

**Comment by mattharrigan** [comment]
I think the documentation should be updated to your recommendation.

I updated the role and traefik is running. However it is also logging the following error every second

> E0724 15:27:59.004754       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190718183610-8e956561bbf5/tools/cache/reflector.go:98: Failed to watch *v1.Secret: unknown (get secrets)

**Comment by mattharrigan** [comment]
@jbdoumenjou Per the [docs](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb) list includes "full object content". To prove it, I updated the role to:

```
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [list]
```
Traefik was able to get the contents of the secret `tls-cert`, proved because browsing to the url successfully used https with the cert contained in the secret.

A minor bug report is that the logs contained "unknown" instead of the actual secret it was attempting to watch (assumed `tls-cert`), ex:

> E0724 17:26:32.519409       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190718183610-8e956561bbf5/tools/cache/reflector.go:98: Failed to watch *v1.Secret: unknown (get secrets)

I do not think this issue should be closed. Thank you
