### ISSUE TITLE
v2.2.x http request gives 404 page not found despite http to https redirect being configured 

### ISSUE THREAD

**Issue by n1ru4l** [containous/traefik#7095]
I am running traefik on a single docker node in swarm mode and I cannot get any HTTP traffic through. I am using the following config:

**docker-compose.yml**
```yaml
#
# this configuration is based on this blogpost: https://containo.us/blog/traefik-2-0-docker-101-fc2893944b9d/
#
version: "3.7"

configs:
  docker_haproxy_config:
    file: ./docker-socket-haproxy.cfg
  github_redirect_config_v2:
    file: ./github-redirect.conf
volumes:
  traefik-certificates:

networks:
  traefik-public:
    external: true
  traefik-socket-proxy:

services:
  traefik:
    image: "traefik:v2.2.5"
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://traefik-socket-proxy:2375"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.default.acme.email=laurinquast@googlemail.com"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--accesslog"
      - "--log"
      - "--api"
      - "--entrypoints.web.http.tls.certresolver=default"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-socket-proxy
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-public-https.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.traefik-public-https.entrypoints=websecure"
        - "traefik.http.routers.traefik-public-https.tls=true"
        - "traefik.http.routers.traefik-public-https.service=api@internal"
        - "traefik.http.services.traefik-public.loadbalancer.server.port=8080"

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  traefik-socket-proxy:
    image: "haproxy:2.1"
    configs:
      - source: docker_haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-socket-proxy
    deploy:
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: "containous/whoami"
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.tls.certresolver=default"

  github-redirect:
    image: "nginx:alpine"
    networks:
      - traefik-public
    configs:
      - source: github_redirect_config_v2
        target: /etc/nginx/conf.d/site.conf
        mode: 0440
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.github-redirect-secure.entrypoints=websecure"
        - "traefik.http.routers.github-redirect-secure.rule=Host(`${DOMAIN}`)"
        - "traefik.http.services.github-redirect-secure.loadbalancer.server.port=80"
        - "traefik.http.routers.github-redirect-secure.tls.certresolver=default"
```

Any HTTP request gives me the following log output (which means the request is definitely processed by traefik):

```
[23/Jul/2020:23:39:29 +0000] "GET /dashboard/ HTTP/1.1" - - "-" "-" 15 "-" "-" 0ms
```

I expect being redirected from http to http, but instead I only get a `404 page not found` error which comes from traefik.

I temporarily exposed my traefik dashboard (as there is nothing special going on right now), so please feel free to use that as verification that http -> https redirect is correctly set up.

https://traefik.n1ru4l.cloud/dashboard/#/http/routers/web-to-websecure@internal

Example:

http://whoami.n1ru4l.cloud/ (does not work, but should)
https://whoami.n1ru4l.cloud/ (does work)

![image](https://user-images.githubusercontent.com/14338007/88349043-4ad7f980-cd4f-11ea-8ed3-7560d986911e.png)
