### ISSUE TITLE
missing servers field in TraefikService

### ISSUE THREAD

**Issue by Slahser** [containous/traefik#7099]
### What did you expect to see?

Kubernetes CRD TraefikService support 

```
  services:
    service-A:
        servers:
          - url: "http://private-ip-server-1/"
          - url: "http://private-ip-server-2/"
```

pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go:59

Is there any way to combine a TraefikService and a dynamic configuration which contains `servers` above?

My scenario is some backend services are Kubernetes Service, others just urls.
