### ISSUE TITLE
error in k8s connecting to services

### ISSUE THREAD

**Issue by elgartoinf** [containous/traefik#7102]
Hello
i have a problem in k8s configuration i am not sure if it is my error, the error is the following:

i installed it using helm:
```
helm repo add traefik https://containous.github.io/traefik-helm-chart
helm repo update
kubectl create ns traefik-v2
# Install in the namespace "traefik-v2"
helm install --namespace=traefik-v2 \
    traefik traefik/traefik

```

Service ip
`tende-ui     ClusterIP      10.245.97.29    <none>           5000/TCP`

this is my ingress configuration.

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "tende"
  namespace: traefik-v2

spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: tende-ui
              servicePort: 5000
```

This is my error
```level=debug msg="'502 Bad Gateway' caused by: dial tcp 10.244.0.146:5000: connect: connection refused"```

I think the **10.244.0.146** should be **10.245.97.29**

I use version **2.2.5** and **2.2.7** and the error was the same

I thank you very much for your comments.
