### ISSUE TITLE
Issue with `dynamic.Headers.AddVaryHeader`

### ISSUE THREAD

**Issue by ivankatliarchuk** [containous/traefik#7103]
### Do you want to request a *feature* or report a *bug*?

Bug

Its a bug.

### What did you do?

Trying to update traefik version. Current is `2.2.0` and desired is `2.2.5` or `2.2.7`

### What did you expect to see?

No error with my configuration file

### What did you see instead?

```
E0727 07:30:00.296205       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.Headers: dynamic.Headers.AddVaryHeader: ReadBool: expect t or f, but found ", error found in #10 byte of ...|yHeader":"true"}}}],|..., bigger context ...|-null","accessControlMaxAge":100,"addVaryHeader":"true"}}}],"kind":"MiddlewareList","metadata":{"con|..
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.0 Everything is OK
2.2.5 Error
2.2.7 Error
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
001-static-sites.yml: |
  http:
    routers:
      static-admin-0:
        rule: "Host(`somehost`)"
        service: static-admin-0
        entryPoints:
        - web
        middlewares:
        - "host-header-s3-admin"
        - "host-header-ui-0"
        - "header-security"
        - "header-cache"
        - "compression"
    services:
      static-admin-0:
        loadBalancer:
          servers:
          - url: "http://somehost:80"
002-middleware.yml: |
  http:
    middlewares:
      host-header-ui-0:
        headers:
          customRequestHeaders:
            Connection: ""
            Authorization: ""
          customResponseHeaders:
            X-AMZ-ERROR-CODE: ""
            X-AMZ-ERROR-DETAIL-KEY: ""
            X-AMZ-ERROR-MESSAGE: ""
            X-AMZ-ID-2: ""
      host-header-s3-admin:
        headers:
          customRequestHeaders:
            Host: "somehost"
            X-Forwarded-Host: "somehost"
      header-security:
        headers:
          stsSeconds: 0
          stsIncludeSubdomains: false
          forceSTSHeader: false
          stsPreload: false
          frameDeny: false
          browserXssFilter: true
          contentTypeNosniff: true
          isDevelopment: false
      header-cache:
        headers:
          customResponseHeaders:
            X-DNS-Prefetch-Control: on
            Cache-Control: "public, max-age=60, immutable"
      compression:
        compress: {}
      www-redirect:
        redirectRegex:
          regex: "^https://host/(.*)"
          replacement: "https://www.host/$1"
          permanent: true
003-whitelist.yml: |
  http:
    middlewares:
      admin-whitelist:
        ipWhiteList:
          ipStrategy:
            depth: 1
          sourceRange:
            - "ip"
            - "ip/32"
004-admin-auth.yml: |
  http:
    middlewares:
      admin-auth:
        digestAuth:
          users:
            - "user:pwd"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
