### ISSUE TITLE
Custom response status code in errors middleware

### ISSUE THREAD

**Issue by nirname** [containous/traefik#7104]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I wish I could change response status code in error pages middleware as well.

Sometimes developers need to replace 401 or 403 status code with 404 status code due to privacy and security reasons.

When I am using errors middleware like this:

```
http:
  middlewares:
    test-errorpage:
      errors:
        status:
          - "401"
        service: serviceError
        query: "/404.html"
```

I get 404 page rendered, however 401 status code is still present in console
