### ISSUE TITLE
Kubernetes Ingress provider is ignoring TLS options set on the entrypoint 

### ISSUE THREAD

**Issue by cookandy** [containous/traefik#7126]
Hello,

I have noticed an issue where a Kubernetes `TLSOption` CRD will not be read when using the `--entrypoints.<name>.http.tls.options` startup argument.

I create the CRD below and verify that it exists in K8s.
 
 ```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: tls-option
  namespace: traefik

spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
```

I start traefik in debug mode, and include the including the `--entrypoints.<name>.http.tls.options` startup argument for my `websecure` (and `web`) entrypoints:

```
❯ kubectl get -n traefik $(kubectl get pods -n traefik --selector "app.kubernetes.io/name=traefik" --output=name) -o json | jq -r ".spec.containers[0].args"

[
  "--global.checknewversion",
  "--global.sendanonymoususage",
  "--entryPoints.traefik.address=:9000/tcp",
  "--entryPoints.web.address=:8000/tcp",
  "--entryPoints.websecure.address=:8443/tcp",
  "--api.dashboard=true",
  "--ping=true",
  "--providers.kubernetescrd",
  "--providers.kubernetesingress",
  "--entrypoints.web.http.redirections.entryPoint.to=websecure",
  "--providers.file.filename=/config/dynamic.toml",
  "--providers.file.watch=true",
  "--entrypoints.websecure.http.middlewares=traefik-https-default@kubernetescrd",
  "--entrypoints.websecure.http.tls.options=traefik-tls-option@kubernetescrd",
  "--log.level=DEBUG"
]
```

From the logs, it seems that the `tls-option` is picked up correctly

```
time="2020-07-30T21:38:11Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"routers\":{\"traefik-traefik-dashboa │
│ rd-d012b7f875133eeab4e5\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/dashboard`) || PathPrefix(`/api`)\"} │
│ },\"middlewares\":{\"traefik-https-default\":{\"headers\":{\"frameDeny\":true}}}},\"tcp\":{},\"udp\":{},\"tls\":{\"options\":{\"traefik- │
│ tls-option\":{\"minVersion\":\"VersionTLS12\",\"cipherSuites\":[\"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256\",\"TLS_ECDHE_RSA_WITH_CHACHA20_PO │
│ LY1305_SHA256\",\"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\",\"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\",\"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384\",\" │
│ TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\"],\"clientAuth\":{}}}}}" providerName=kubernetescrd
```

I deploy a simple Kubernetes Ingress without the `traefik.ingress.kubernetes.io/router.tls.options` annotation. Something like:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  name: ingress-my-app
  namespace: default
spec:
  rules:
    - host: a.foo.com
      http:
        paths:
        - backend:
            serviceName: my-app
            servicePort: server
```

The ingress is created and I can see the route in Traefik's dashboard. I can get to my service from the outside world. However, it's not using the tls options (I verified with `openssl`). I also don't see the `traefik-tls-option@kubernetescrd` option listed in the `TLS` section of the Traefik dashboard. There are also no logs in Traefik indicating it has used the TLS options.

However, if I create the same Ingress object and also include the `traefik.ingress.kubernetes.io/router.tls.options` annotation, such as

```yaml
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.options: traefik-tls-option@kubernetescrd
```

This time, I can see Traefik use the TLS option being used in the logs

```
time="2020-07-30T22:18:29Z" level=debug msg="Adding route for a.foo.com with TLS options traefik-tls-option@kubernetescrd" entryPointName=web
time="2020-07-30T22:18:29Z" level=debug msg="Adding route for a.foo.com with TLS options traefik-tls-option@kubernetescrd" entryPointName=websecure
```

I can also see the option listed in `TLS` in the admin dashboard.

### What did you expect to see?

The startup option `--entrypoints.websecure.http.tls.options=traefik-tls-option@kubernetescrd` should apply the TLS Options to the ingress object without the annotation.

### What did you see instead?

The `traefik.ingress.kubernetes.io/router.tls.options: traefik-tls-option@kubernetescrd` annotation was needed in order to use the TLS Options

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.16 using the [Helm Chart](https://github.com/containous/traefik-helm-chart) to install and set the startup arguments.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ddtmachado** [comment]
I can confirm this issue but we should probably rename it to clarify it has nothing to do with command arguments or the kubernetes CRD.

It seems that the `kubernetesIngress` provider is ignoring TLS options set on the entrypoint as it builds an empty TLS config object when the label `traefik.ingress.kubernetes.io/router.tls: "true"` is set.

We can get the same results when declaring the options and entrypoints in other ways as well, like setting up a static config and using the file provider to declare tls options:

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: "DEBUG"

api:
  #insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        options: mintls@file

providers:
  kubernetesCRD: {}
  kubernetesIngress: {}
  file:
    filename: /configs/dynamic.yml
```

With the TLSOption defined in the dynamic.yml file:

```yaml
tls:
  options:
    mintls:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
```

Then creating one routers for each kubernetes provider:

```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami

spec:
  entryPoints:
    - websecure

  routes:
  - match: Host(`whoami-crd.docker.localhost`)
    kind: Rule
    services:
    - name: whoami
      port: 80
    tls: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"    
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: whoami-ingress
spec:
  rules:
  - host: whoami.docker.localhost
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80

```

The `kubernetesCRD` router will get the correct `TLSOption` from the entrypoint.
The `kubernetesIngress` router will not, using the default `TLSOption` in the cluster.

ping @SantoDE

**Comment by rtribotte** [comment]
Hello @cookandy,
ping @ddtmachado 

After some testing, finally, i think there is no bug.

In order to let apply the entrypoint tls option to the router configured from an Ingress, no annotations regarding `TLSOptions` should be set, since the entrypoint `TLSOption` is applied to a router only when no specific one has been set in the router configuration (here on the Ingress).

The annotation `traefik.ingress.kubernetes.io/router.tls: "true"` applies a empty TLSOption, which is considered as a specific configuration.

Furthermore, the misleading behavior observed with the IngressRoute is due to a misconfiguration, the `tls` entry should be at the same level as the `routes`entry:
```yml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls: {}
```

I will close this issue as a question.

Nevertheless, thanks for your contribution and interest in Traefik !
