### ISSUE TITLE
www to non www traefik not working or bug & http to https 

### ISSUE THREAD

**Issue by adamramadhan** [containous/traefik#7128]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

i wanted to do two things, 

1. redirect http to https (good)
2. redirect all www to non www (bad)

why?

because `https://www.example.com` or `https://www.subdomain.example.com` if not redirected doest have a certificate or shouldn't have one or should redirect to its subdomain.example.com or example.com

I've checked my regex too ` '^http[s]{0,1}://www\.(.*)$'`

![image](https://user-images.githubusercontent.com/101631/89004909-6df54100-d32d-11ea-81d1-9ef72f315305.png)

here are my two files that matters the most

services.yaml
```
http:
  middlewares:
    auth:
      basicAuth:
        users:
          - 'REDACTED:REDACTED'
    redirHttps:
      redirectScheme:
        scheme: https
        permanent: true
    exampleRedirWWW:
      redirectRegex:
        regex: '^http[s]{0,1}://www\.(.*)$'
        replacement: "https://${1}"
        permanent: true
  services:
    example-main:
      loadBalancer:
        servers:
          - url: http://x
    example-tenant:
      loadBalancer:
        servers:
          - url: http://x
```

example.com.yaml
```
http:
  routers:
    example.com:
      entryPoints:
        - web
      rule: 'Host(`www.example.com`, `example.com`)'
      middlewares:
        - examplecomRedirWWW
        - redirHttps
      service: example-main
    example.com-secure:
      entryPoints:
        - websecure
      rule: 'Host(`www.example.com`, `example.com`)'
      middlewares:
        - examplecomRedirWWW
      service: example-main
      tls:
        certResolver: tls
    tenant.example.com:
      entryPoints:
        - web
      rule: 'HostRegexp(`www.{subdomain:[a-z0-9]+}.example.com`, `{subdomain:[a-z0-9]+}.example.com`)'
      service: example-tenant
      middlewares:
        - exampleRedirWWW
        - redirHttps
    tenant.example.com-secure:
      entryPoints:
        - websecure
      rule: 'HostRegexp(`www.{subdomain:[a-z0-9]+}.example.com`, `{subdomain:[a-z0-9]+}.example.com`)'
      middlewares:
        - exampleRedirWWW
      service: example-tenant
      tls:
        certResolver: cf
        domains:
          - sans:
              - '*.example.com'
```

### What did you expect to see?

```
www.example.com  -> example.com
example.com -> example.com
www.subdomain.example.com -> subdomain.example.com
subdomain.example.com -> subdomain.example.com
wwwsubdomain.example.com -> wwwsubdomain.example.com
```

### What did you see instead?

```
www.example.com  -> example.com (good)
example.com -> example.com  (good)
www.subdomain.example.com -> www.subdomain.example.com  (bad) not redirecting to non www if open via https://, but if we open via http:// it work redirect to subdomain.example.com
subdomain.example.com -> subdomain.example.com  (good)
wwwsubdomain.example.com -> ubdomain.example.com  (bad) missing `s` maybe because of the regex
```

I'm guessing its a regex problem

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)? (I think it doest matter so much in this case)

```
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

log:
  filePath: ./info.log
  level: INFO

accessLog:
  filePath: ./access.log

api:
  insecure: false
  dashboard: false

providers:
  file:
    directory: ./hosts
    watch: true

certificatesResolvers:
  tls:
    acme:
      email: security@x.com
      storage: acme-tls.json
      tlschallenge: {}

  acme-dns:
    acme:
      email: security@x.com
      storage: acme-dns.json
      dnsChallenge:
        provider: acme-dns
  web:
    acme:
      email: security@x.com
      storage: acme-web.json
      httpChallenge:
        entryPoint: web
  cf:
    acme:
      email: security@x.com
      storage: acme-cf.json
      dnsChallenge:
        provider: cloudflare
```

**Comment by rtribotte** [comment]
Hi @adamramadhan,

Thanks for your interest in Traefik

As stated in this part of the [documentation](https://docs.traefik.io/v2.2/middlewares/redirectregex/#regex), could you try with this specific syntax for your replacement : `"https://${1}"` ?

**Comment by adamramadhan** [comment]
hi @rtribotte thankyou for the reply, still no luck, after inserting wwwsubdomain.example.com it became ubdomain.example.com and when typing into https://www.subdomain.example.com it doesn't do the redirect to subdomain.example.com but surprisingly if we use `http` instead of `https` it somehow works.

**Comment by rtribotte** [comment]
Hi @adamramadhan,

I not able to reproduce your issue, i tried with this test compose file:
```yaml
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.8
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.middlewares=test-rr@docker
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls
      - --entrypoints.websecure.http.middlewares=test-rr@docker
      - --log.level=DEBUG
      - --api
      - --providers.docker.exposedbydefault=false
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: HostRegexp(`{subdomain:([a-z.]+)?}.traefik`)
      traefik.http.routers.traefik.entrypoints: web,websecure
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.test-rr.redirectregex.regex: ^http[s]{0,1}://www\.(.*)$$
      traefik.http.middlewares.test-rr.redirectregex.replacement: https://$${1}
      traefik.http.middlewares.test-rr.redirectregex.permanent: true
```

All the following requests are working for me:
```
http://www.server.traefik -> https://server.traefik
https://www.server.traefik -> https://server.traefik
http://wwwserver.traefik -> http://wwwserver.traefik
https://wwwserver.traefik -> https://wwwserver.traefik
```

I will close this issue as i cannot reproduce it.
Thus, if you need help don't hesitate to open a thread on [the community forum](https://community.containo.us/c/traefik/traefik-v2/).
