### ISSUE TITLE
CNAME flattening cannot working with custom SSL certificate, HTTPS always return 404 error

### ISSUE THREAD

**Issue by zhengchun** [containous/traefik#7133]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I enabled CNAME flattening feature, website allows HTTP and HTTPS. 

when visit website with HTTPS, SSL certificate status show success but HTTP page return 404 error.

CNAME record:

`feed.colorpea.com` point to `cname.sitemaphub.com.`

### What did you expect to see?

http://feed.colorpea.com/robots.txt 

https://feed.colorpea.com/robots.txt

both return HTTP 200 status code.

### What did you see instead?

http://feed.colorpea.com/robots.txt  [200]

https://feed.colorpea.com/robots.txt [404 error]

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.2.1 (Docker 18.09.1)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.file]
    directory = "/etc/traefik/config"
    watch = true

[hostResolver]
  cnameFlattening = true
```

http router config (/etc/traefik/config)

```toml
[http]

  [http.services]

    [http.services.feedproxy-sitemaphub-backend.loadBalancer]
      [[http.services.feedproxy-sitemaphub-backend.loadBalancer.servers]]
        url = "http://feedproxy-sitemaphub/"

  [http.routers]

    [http.routers.cname-sitemaphub-http-router]
      entryPoints = ["web","websecure"]
      rule = "Host(`cname.sitemaphub.com`)"
      service = "feedproxy-sitemaphub-backend"
```

TLS config (/etc/traefik/config)
```toml
[TLS]

  [[TLS.Certificates]]
    CertFile = "/var/lib/acme/live/feed.colorpea.com/cert"
    KeyFile = "/var/lib/acme/live/feed.colorpea.com/privkey"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Request: http://feed.colorpea.com/robots.txt
```log
time="2020-08-02T14:13:16Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/robots.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"User-Agent\":[\"Fiddler\"],\"X-Forwarded-Host\":[\"feed.colorpea.com\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"ce25722add3c\"],\"X-Real-Ip\":[\"180.162.1.53\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"feed.colorpea.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"180.162.1.53:39666\",\"RequestURI\":\"/robots.txt\",\"TLS\":null}"
time="2020-08-02T14:13:16Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/robots.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"User-Agent\":[\"Fiddler\"],\"X-Forwarded-Host\":[\"feed.colorpea.com\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"ce25722add3c\"],\"X-Real-Ip\":[\"180.162.1.53\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"feed.colorpea.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"180.162.1.53:39666\",\"RequestURI\":\"/robots.txt\",\"TLS\":null}" ForwardURL="http://feedproxy-sitemaphub/"
time="2020-08-02T14:13:16Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/robots.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"User-Agent\":[\"Fiddler\"],\"X-Forwarded-Host\":[\"feed.colorpea.com\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"ce25722add3c\"],\"X-Real-Ip\":[\"180.162.1.53\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"feed.colorpea.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"180.162.1.53:39666\",\"RequestURI\":\"/robots.txt\",\"TLS\":null}"
```

Request: https://feed.colorpea.com/robots.txt

No log to output, looks request are breaking.
