### ISSUE TITLE
Intermittent 404 on v2.2.8

### ISSUE THREAD

**Issue by beranPro** [containous/traefik#7135]
Hi guys...

### Do you want to request a feature or report a bug?
Bug

### What did you do?
i'm trying to passthrough a https tls connection through the keycloak container via TCP.
I'm doing because i want to use client authentication via x509 certificates and i didn't get it up and running via the https router.

### What did you expect to see?
i stable working connection

### What did you see instead?
I see a "part time" working connection. The first requests works fine but after some request i get a 404 in the browser.
Curl is working fine.

It's the same issue like https://github.com/containous/traefik/issues/7020

The only difference is that i'm using the tcp router.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
/ # traefik version
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

#### traefik.yml

```yaml
log:
  level: DEBUG

serversTransport:
  insecureSkipVerify: true

#accessLog: {}

api:
  dashboard: true

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
    swarmModeRefreshSeconds: 30
    network: web
  file:
    directory: /dynamic/
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
```

#### docker-compose.yml
```yaml
version: '3.8'

services:
  keycloak:
    image: jboss/keycloak
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: ingress
    volumes:
      - ./https:/etc/x509/https
      - ./tls:/etc/x509/tls
    environment:
      - KEYCLOAK_LOGLEVEL=DEBUG
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==host"
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.tcp_keycloak.entrypoints=websecure"
        - "traefik.tcp.routers.tcp_keycloak.tls.passthrough=true"
        - "traefik.tcp.routers.tcp_keycloak.rule=HostSNI(`auth.mydomain.de`)"
        - "traefik.tcp.services.tcp_keycloak.loadbalancer.server.port=8443"
    networks:
      - web
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
sometime i find some rare error debug messages
```
rocket_traefik.1.oxpixxbainkn@srvedv128    | time="2020-08-03T07:10:12Z" level=debug msg="Error while setting deadline: set tcp 10.222.1.58:43522: use of closed network connection"
rocket_traefik.1.oxpixxbainkn@srvedv128    | time="2020-08-03T07:10:37Z" level=debug msg="Error while setting deadline: set tcp 10.222.1.58:43784: use of closed network connection"
rocket_traefik.1.oxpixxbainkn@srvedv128    | time="2020-08-03T07:11:40Z" level=debug msg="Error while setting deadline: set tcp 10.222.1.58:44280: use of closed network connection"
```
