### ISSUE TITLE
Easier to use grpc with h2c in traefik2.2 

### ISSUE THREAD

**Issue by chinazj** [containous/traefik#7137]
### question

Easier to use grpc by ingressroute

### description

1.  If i want to use Grpc With h2c,Do I have to add such a configuration file?
       https://docs.traefik.io/user-guides/grpc/
2.  In traefik2.2, can I implement grpc with h2c just by using ingressroute?

thanks

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by chinazj** [comment]
like this:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grpc
spec:
  entryPoints:
    - mms
  routes:
    - kind: Rule
      match: PathPrefix(`/***`)
      services:
        - name: service-name
          port: 50052
          kind: Service
          scheme: h2c
```

if you use https，you must add cert-file.
