### ISSUE TITLE
Static CustomErrorPage Support

### ISSUE THREAD

**Issue by FireDrunk** [containous/traefik#7141]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
The abillity to allow Static pages to be returned in middleware, without requiring a configured service backend.

Some use-cases might be, that we can mount static pages from Kubernetes Configs into Traefik pods to serve them.

I understand that Traefik is not meant to serve Static content, but deploying an extra service for basic Error Page serving seems rather overkill, plus it's an extra point of failure.

I've investigated the code, and I *think* this might be done as an InternalHandler in pkg/server/service/internalhandler.go.
This way it's possible to 'redirect' requests to the internal handler. The handler would have 1 option, which is the local directory it's supposed to look in, and 1 parameter, which is which file it should 'render'.

In the CustomErrorPage middleware we could add an option to replace service with the internal service, and a parameter which file should be served.

Example:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-errorpage
spec:
  errors:
    status:
      - 500-599
    query: /{status}.html
    service:
      name: static@internal
      file: {status}.html
```

I'm willing to try and build this, if the architectural approach is accepted.
