### ISSUE TITLE
BasicAuth don't works

### ISSUE THREAD

**Issue by mehdi15** [containous/traefik#7142]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to use BasicAuth to secure the access to PhpMyadmin login interface, but it does not work. I have access to the login page without authentication. 

### What did you expect to see?

I would like to see a login/password window before having access to PhpMyadmin login interface. 

### What did you see instead?

I see directely the PhpMyadmin login interface 

### Output of `traefik version`: (_traefik:v2.2.5_)

```
traefik:v2.2.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
# phpmyadmin docker compose 

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-phpmyadmin
    depends_on:
      - web-db
    environment:
      - PMA_ABSOLUTE_URI=https://webaddr.com
      - PMA_HOST=web-db
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /sessions
    labels:
      traefik.enable: true
      # HTTP
      traefik.http.routers.api.entrypoints: http
      traefik.http.routers.api.rule: Host(`webaddr.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))

      # Middleware
      traefik.http.middlewares.api-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.api.middlewares: api-https-redirect
      
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: api
      traefik.http.middlewares.api.basicauth.removeheader: true
      traefik.http.middlewares.api.basicauth.users: "web-db-user:pass_hash"
      

      # HTTPS
      traefik.http.routers.api-sec.entrypoints: https
      traefik.http.routers.api-sec.rule: Host(`webaddr.com`)
      traefik.http.routers.api-sec.tls: true
      traefik.http.routers.api-sec.tls.certresolver: http
      traefik.http.routers.api-sec.service: api
      traefik.http.services.api.loadbalancer.server.port: 80
      traefik.docker.network: traefik_network
    networks:
      - traefik_network
      - internal
```
