### ISSUE TITLE
Connecting to Redis with non-wildcard HostSNI and/or TLS returns 400 Bad Request Code

### ISSUE THREAD

**Issue by sdan** [containous/traefik#7144]
Bug

### What did you do?
 I ran Traefik in Docker with File provider with/without TLS and with/without HostSNI for a Redis server hosted on a different server (public IP)

Whenever I either turned on TLS or I made HostSNI my domain, I would get a 400 Bad Request (as I desribe below). I tried a basic HTTP router/service and it worked well. Even the Traefik dashboard was under TLS and it worked fine, so I know TLS isn't the issue.

### What did you expect to see?

I used `redis-cli -h some.domain.tld -p 6379 -a "password"` on my local machine to test whether I could connect to Redis. If I could and query `KEYS *` and/or `PING` then I assumed it was working.

Only when HostSNI was set to `HostSNI(`*`)` and no TLS was configured within the File provider was I able to do this successfully.

### What did you see instead?

Instead I see `Error: Protocol error, got "H" as reply type byte` as the response. Looking into it a bit more: I used #4930 and ran: `for i in `seq 1 10`; do echo 'ping' | nc some.domain.tld 6379; done | uniq -c` and found the response of 
```
   1 400 Bad RequestHTTP/1.1 400 Bad Request
   1 Content-Type: text/plain; charset=utf-8
   1 Connection: close
```
Which shouldn't happen since I'm using TCP

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.2.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here is my Redis config stored in `/etc/traefik/dynamic/`
```toml
[tcp]
  # Add the router
  [tcp.routers]
    [tcp.routers.redis-router]
      entryPoints = ["redis"]
      rule = "HostSNI(`some.domain.tld`)"
      service = "redis-service"
      [tcp.routers.redis-router.tls]

  # Add the service
  [tcp.services]
    [tcp.services.redis-service]
      [tcp.services.redis-service.loadBalancer]
        [[tcp.services.redis-service.loadBalancer.servers]]
          address = "<external ip of different server>:6379"
```
Here is my Traefik entrypoint/provider config stored in `/etc/traefik/`
```toml
[entryPoints]
  [entryPoints.web]
    address = ":80" 
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.redis]
    address = ":6379"
[providers.docker]
 [providers.file]
   directory = "/etc/traefik/dynamic"
[api]
  dashboard = true
```
TLS config
```
[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/traefik/ssl/cert.pem"
        keyFile = "/etc/traefik/ssl/privkey.pem"

  [[tls.certificates]]
    certFile = "/etc/traefik/ssl/cert.pem"
    keyFile = "/etc/traefik/ssl/privkey.pem"

```
Docker-compose file:
```
version: "3.7"
    
services:
  <some service>:
    image: traefik:v2.2.8
    ports:
      - "80:80"
      - "443:443"
      - "6379:6379"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/traefik:/etc/traefik
      - /path/to/fullchain.pem:/etc/traefik/ssl/cert.pem
      - /path/to/privkey.pem:/etc/traefik/ssl/privkey.pem
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`some.domain.tld`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=<something>"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

None

**Comment by kaiffeetasse** [comment]
Same bug with minecraft, it only works in this configuration:
```
#Minecraft-TCP-Router
- "traefik.tcp.routers.minecraft-tcp.rule=HostSNI(`*`)"
- "traefik.tcp.routers.minecraft-tcp.entrypoints=mc-tcp"
#Minecraft-UDP-Router
- "traefik.udp.routers.minecraft-udp.entrypoints=mc-udp"
```
and not when using ```HostSNI(`my.domain`)``` instead.

**Comment by pidario** [comment]
Which redis version are you using? To pull this off you'll need version 6 built with TLS support and AFAIK there is no way to tell if your redis server support TLS connections. Running redis from the official docker image should do it (alpine or debian doesn't matter), but it must be at least version 6.
In my experience, redis installed from OSes package managers are usually without TLS support, so your best bet is to either use docker or build redis yourself (which is really straightforward: <https://redis.io/topics/encryption>)

I'll post here my full configuration (only the part relative to redis), but to me the only difference from my config is the missing `passthrough = true` in your tcp router. I'm using traefik version 2.3.1 but it should be working in 2.2.x as well.

static:
```toml
[providers]
[providers.file]
directory = "/etc/traefik/dynamic/"
watch = true

[entryPoints]
[entryPoints.redis]
address = ":6379"
```

dynamic:
```toml
[tcp.services]
[tcp.services.redis]
[tcp.services.redis.loadBalancer]
[[tcp.services.redis.loadBalancer.servers]]
# redis is the hostname of the redis container
address = "redis:6379"
[tcp.routers]
[tcp.routers.redis]
# of course you'll need a DNS record A pointing this domain to the loadbalancer IP address
rule = "HostSNI(`some.domain.tld`)"
service = "redis"
entryPoints = ["redis"]
[tcp.routers.redis.tls]
# this tells traefik not to terminate TLS connection here, but to forward it to redis as it is
passthrough = true
```

redis configuration:
```conf
# port is for non TLS communication (0 means disabled, so non-TLS connections are forbidden)
# I use port 6380 for between container connections and 6379 for remote access
port 6380
tls-port 6379
tls-cert-file /conf/redis.cert.pem
tls-key-file /conf/redis.key.pem
# tls-ca-cert-file /conf/chain.cert.pem
```

`redis.cert.pem` is a self-signed certificate and `redis.key.pem` is its private key of course. I don't know whether you can use let's encrypt certificates here, but since we're not talking about a website, a self-signed certificate is a good option for me.
`chain.cert.pem` is a certificate authority used for mutual authentication (client needs a certificate signed by that CA to connect), uncomment if you need a stronger authentication method.

docker-compose:
```yaml
version: "3.8"
volumes:
  redis:
services:
  traefik:
    image: traefik:2.3
    restart: always
    hostname: traefik
    container_name: traefik
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    volumes:
      - "/path/to/traefik-conf:/etc/traefik"
  redis:
    image: redis:6-alpine
    restart: always
    hostname: redis
    container_name: redis
    command: "redis-server /conf/redis.conf"
    depends_on:
      - traefik
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
    volumes:
      - "redis:/data"
      - "/path/to/redis-conf:/conf"
```

To test your setup via **redis-cli**, you must provide the `sni` switch:
`redis-cli --sni some.domain.tld -h some.domain.tld -p 6379 -a "password"`.
For mutual authentication you'll also need the `--cert` and `--key` switches.

**Comment by dunn** [comment]
I think this issue isn't Redis-specific; I'm having what looks like the same error trying to route TCP traffic to an RTMP server.

As above, when trying to route traffic on port 1935 to various services, ```HostSNI(`a.specific.domain`)``` fails while ```HostSNI(`*`)``` succeeds.  As a result TCP traffic can't be effectively handled, and multiple services listening on the same port are sent the wrong traffic.

In my case Traefik 2.4-rc1 was installed via Helm with [this patch applied to the chart](https://github.com/traefik/traefik-helm-chart/commit/9a197bcbd345cedbb90a23c0f496e539c4766ad0) and the following values:
```yaml
# namespace: traefik
image:
  tag: v2.4.0-rc1

ports:
  rtmp:
    port: 1935
    expose: true
    exposedPort: 1935
    protocol: TCP

additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik"
```

Then in my application's chart, I defined this IngressRouteTCP:
```yaml
{{- if .Values.rtmp.enabled }}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "mychart.fullname" . }}-ingressroute-rtmp
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - rtmp
  routes:
    {{- range .Values.ingress.hosts }}
    - match: HostSNI(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}-rtmp
          port: 1935
          proxyProtocol:
            version: 2
    {{- end }}
{{- end }}
```

I tried with and without `proxyProtocol` defined, and with version 1 and 2 specified.  In all cases I am unable to connect to the [RTMP server](https://github.com/arut/nginx-rtmp-module).  But when I replace the matcher with ```HostSNI(`*`)```, I can.

I'm installing into a Linode K8s cluster (LKE) running 1.18.  Helm version is
```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```
