### ISSUE TITLE
Error while Peeking first byte ; haproxy in front of Traefik with proxy-protocol

### ISSUE THREAD

**Issue by JulesTriomphe** [containous/traefik#7146]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have haproxy in front of **dockerized** Traefik in **swarm-mode** to load-balance requests to servers in a private network, with proxy-protocol to identify source IP addresses.
I perform tcp-checks for each entrypoint I use, but these result in the following errors in Traefik : `"Error while Peeking first byte: read tcp 192.168.224.3:110->10.1.1.1:52524: read: connection reset by peer"`

### What did you expect to see?

I do not expect to see an error due to haproxy tcp-checks.

### What did you see instead?

```bash
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Error while Peeking first byte: read tcp 192.168.224.3:110->10.1.1.1:52524: read: connection reset by peer"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

haproxy node is 10.1.1.1

Traefik node is 10.1.1.10

*Static conf*

```yml
entryPoints:
  ## POP3
  0110_pop3:
    address: ":110"
    proxyProtocol:
      trustedIPs:
      - "10.0.0.0/8"
    forwardedHeaders:
      trustedIPs:
      - "10.0.0.0/8"

providers:
  file:
    watch: true
    directory: /etc/traefik/dynanmic
  docker:
    endpoint: "tcp://socket:2375"
    swarmMode: true
    exposedByDefault: false
    network: public

api:
  dashboard: true
  insecure: false # default: false
  debug: false # default: false

certificatesResolvers:
  le:
    acme:
      email: xxx
      storage: /acme.json
      dnsChallenge:
        provider: xxx
        delayBeforeCheck: 10

log:
  level: DEBUG
```

Port 110 is exposed in host mode in the `docker-compose.yml` file:

```yml
## POP3
      - target: 110
        published: 110
        protocol: tcp
        mode: host
```

*haproxy conf*

```haproxy
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        # modern configuration
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets

        ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets

defaults
	log	global
	mode	http
	option	httplog

        timeout connect 1s
        timeout client 20s
        timeout server 20s
        timeout client-fin 20s
        timeout tunnel 1h

	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

listen stats
        bind :32700
        stats enable
        stats uri /
        stats hide-version
        stats auth haproxy:password
        stats refresh 1s

## POP3
frontend 0110
        bind *:110
        mode tcp
        option tcplog
        default_backend 0110

backend 0110
        balance roundrobin
        mode tcp
        option redispatch
        option tcp-check
        tcp-check connect send-proxy

        server m10 10.1.1.10:110 check send-proxy-v2 fall 3 rise 2
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Trusted connection" entryPointName=0110_pop3
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Addresses len: 12" entryPointName=0110_pop3
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Address readed: 12" entryPointName=0110_pop3
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Use header remote addr" entryPointName=0110_pop3
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Header parsed &{10.1.1.1:52524 10.1.1.10:110}" entryPointName=0110_pop3
proxy_app.0.y75ghkvn81b7@m10    | time="2020-08-05T13:53:06Z" level=debug msg="Error while Peeking first byte: read tcp 192.168.224.3:110->10.1.1.1:52524: read: connection reset by peer"
```
