### ISSUE TITLE
Docker provider not picking up some containers

### ISSUE THREAD

**Issue by yamashi** [containous/traefik#7148]
### What did you do?

I am using traefik as a reverse proxy in a docker based deployment but it doesn't pick up some containers randomly, I have to stop/start the container multiple times until it picks it up but it also causes traefik to lose other containers sometimes.

I tried updating the rules to HostHeader instead of Host but that didn't help at all.

### What did you expect to see?

All containers with traefik labels get picked up correctly and requests are redirected correctly.

### What did you see instead?

Some containers don't receive anything from traefik

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.3.0-rc3
```

This problem has always been present since I upgraded to traefik2 (2.2.1 and up) but it seems to have gotten worse with time. 

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  sendAnonymousUsage: false

log:
  level: "INFO"
  format: "common"

entryPoints:
  https:
    address: ':443'
    forwardedHeaders:
      trustedIPs:
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/12"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
        - "2400:cb00::/32"
        - "2606:4700::/32"
        - "2803:f800::/32"
        - "2405:b500::/32"
        - "2405:8100::/32"
        - "2a06:98c0::/29"
        - "2c0f:f248::/32"

metrics:
  prometheus: {}

providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
```
