### ISSUE TITLE
cross namespaces IngressRoutes and Services

### ISSUE THREAD

**Issue by jaycci** [containous/traefik#7151]
## Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created two namespaces, named "ns1" and "ns2". In "ns1", I have a "ns1/pod" and a linked "ns1/service". In "ns2", I created an IngressRoute that referenced the "ns1/service".

This is the yaml file that creates all the objects (I'm on a Kubernetes 1.18.6 cluster):
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: ns1
---
kind: Namespace
apiVersion: v1
metadata:
  name: ns2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: ns1
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  namespace: ns1
  name: whoami
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: ns2
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`whoami.dev.c1.syshawk.net`)
      kind: Rule
      services:
        - name: whoami
          namespace: ns1
          port: 80
```

### What did you expect to see?

The IngressRoute should have produced errors.

### What did you see instead?

The IngressRoute has been successfully set up, the public URL is usable and the final pod from the other namespace is reachable through the service in this other namespace.

This is a security issue that allows someone else to access data and services that could be confidential.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.2.8

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`traefik.toml`:
```toml
[serversTransport]
  insecureSkipVerify = true

[providers.kubernetesIngress]

[providers.kubernetesCRD]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.transport.respondingTimeouts]
      idleTimeout = "40s"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.transport.respondingTimeouts]
      idleTimeout = "40s"

  # 2 entrypoints for RTP (telephony), for Jitsi Meet
  [entryPoints.rtp-tcp]
    address = ":4443"
  [entryPoints.rtp-udp]
    address = ":10000/udp"

  # not documented, this is the one for the dashboard and API
  [entryPoints.traefik]
    address = "127.0.0.1:8080"

[tls.options]
  [tls.options.default]
    #minVersion = "VersionTLS13"
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    ]
    sniStrict = true

[api]
  dashboard = true
  insecure = true

[ping]
  entryPoint = "traefik"

[log]
  level = "WARN"
  format = "json"

[accessLog]
  format = "json"

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true

[global]
  checkNewVersion = false

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
    watch = true
```

`dynamic.toml`:
```toml
# This "dynamic" static conf is here to redirect
# all HTTP traffic to HTTPS
[http.routers.http-catchall]
  rule = "HostRegexp(`{host:.+}`)"
  entrypoints = [ "http" ]
  middlewares = [ "https-redirect" ]
  service = "dummy"
  # lowest possible priority so that the match can be overwritten by anyone
  priority = 1

[http.middlewares.https-redirect.redirectscheme]
  scheme = "https"

[http.services]
  # dummy service, URL will never be called
  [http.services.dummy.LoadBalancer]
    [[http.services.dummy.LoadBalancer.servers]]
      url = ""

  [http.services.gatekeeper.LoadBalancer]
    [[http.services.gatekeeper.LoadBalancer.servers]]
      url="http://127.0.0.1:3000"
```
