### ISSUE TITLE
docs out of sync with latest causing cannot unmarshal !!map into []dynamic.Server

### ISSUE THREAD

**Issue by ssbarnea** [containous/traefik#7162]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Regression caused by https://github.com/containous/traefik/pull/5373 which changed "servers:" to be a list instead of a mapping in YAML but latest (2.2.8) chokes with:

```
Cannot start the provider *file.Provider: yaml: unmarshal errors:\n  line XX: cannot unmarshal !!map into []dynamic.Server"
```

### What did you expect to see?

Documentation must assure it is valid for current version.

### What did you see instead?

Valid example.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run traefik version                                                                                                                     Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# (paste your configuration here)
http:

  routers:
    syno-https:
      rule: Host(`syno.examaple.com`)
      tls:
        certresolver: myresolver
      service: syno
      entrypoints:
        - websecure

  services:
    syno:
      loadBalancer:
        servers:
          - url: "http://192.168.44.44"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
