### ISSUE TITLE
HostRegexp escaped characters in IngressRoutes are not correctly handled

### ISSUE THREAD

**Issue by clovis-dugue** [containous/traefik#7165]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created the following IngressRoute in a Kubernetes cluster (along with the Service and Endpoint it requires) :
```yaml
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: devenv-1-bridge
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'HostRegexp(`{subdomain:^.*devenv-1\.mycluster\.local$}`)'
      services:
        - kind: Service
          name: devenv-1-bridge
          namespace: null
          passHostReader: true
          port: 13371
          responseForwarding:
            flushInterval: 5ms
          scheme: http
  tls: {}
```

### What did you expect to see?

I expected my IngressRoute to create without any issue, and answer to addresses such as https://devenv-1.mycluster.local or https://prefixdevenv-1.mycluster.local
When using the following Regexp : `^.*devenv-1.mycluster.local$` (without escaping the dots), everything works as intended. However, there are security concerns as it matches any character where dots are expected.

### What did you see instead?

My Traefik pod logs the following in a loop :
```
level=error msg="Invalid syntax for match rule: HostRegexp(`{subdomain:^.*devenv-1\\.mycluster\\.local$}`)" ingress=devenv-1-bridge namespace=default providerName=kubernetescrd
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik is installed as a dependency for a custom Helm Chart. Its values are the following

```yaml
traefik:
  enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: false
  additionalArguments:
    - "--providers.kubernetescrd.ingressclass=myapp"
    - "--providers.kubernetesingress.ingressclass=myapp"
```
