### ISSUE TITLE
Unable to access the configured URL

### ISSUE THREAD

**Issue by mrUizz** [containous/traefik#7173]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I used helm 3.0 to install traefik 2.2.8 in k8s 1.16.
I can now use the domain name traefik.path.net set in ingressroute to access the traefik UI, 
and then I want to configure other application access paths. 
The UI shows that I should be Successful, but I can't access, the return value is mostly 50*.

### What did you expect to see?
I can use the domain name configured in ingressroute to access my deployed application

### What did you see instead?
404 page not found

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker images v2.2.8

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Source: traefik/templates/dashboard-hook-ingressroute.yaml
```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: trae-traefik-dashboard
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.9.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: trae
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.path.net`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
```

Source: traefik/templates/rbac/serviceaccount.yaml
```yml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: trae-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.9.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: trae
  annotations:
``

Source: traefik/templates/rbac/clusterrole.yaml
```yml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trae-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.9.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: trae
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch
```

Source: traefik/templates/rbac/clusterrolebinding.yaml
```yml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trae-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.9.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: trae
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trae-traefik
subjects:
  - kind: ServiceAccount
    name: trae-traefik
    namespace: default
```

Source: traefik/templates/deployment.yaml
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trae-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-8.9.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: trae
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: trae
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-8.9.2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: trae
    spec:
      serviceAccountName: trae-traefik
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      containers:
      - image: traefik:2.2.8
        name: trae-traefik
        resources:
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - name: "traefik"
          containerPort: 9000
          protocol: "TCP"
        - name: "web"
          containerPort: 8000
          hostPort: 80
          protocol: "TCP"
        - name: "websecure"
          containerPort: 8443
          hostPort: 443
          protocol: "TCP"
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
          - name: data
            mountPath: /data
          - name: tmp
            mountPath: /tmp
        args:
          - "--global.checknewversion"
          - "--global.sendanonymoususage"
          - "--entryPoints.traefik.address=:9000/tcp"
          - "--entryPoints.web.address=:8000/tcp"
          - "--entryPoints.websecure.address=:8443/tcp"
          - "--api.dashboard=true"
          - "--ping=true"
          - "--providers.kubernetescrd"
          - "--providers.kubernetesingress"
      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        fsGroup: 65532
```

Source: traefik/templates/service.yaml
```yml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: trae-traefik
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-8.9.2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: trae
      annotations:
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: trae
      ports:
      - port: 9000
        name: traefik
        targetPort: "traefik"
        protocol: "TCP"
      - port: 80
        name: web
        targetPort: "web"
        protocol: "TCP"
      - port: 443
        name: websecure
        targetPort: "websecure"
        protocol: "TCP"
```

```toml
# (paste your configuration here)
```

```yml
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default

spec:
  type: LoadBalancer
  externalName: whoami.opstest.mei-shenghuo.net
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
  selector:
    app: whoami

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80

kind: IngressRoute
metadata:
  name: mygressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`whoami.path.net`)
    kind: Rule
    services:
    - name: whoami
      port: 80
      kind: Service
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
There is no output
With the current configuration,
I can access the traefik ui service through traefik.path.net,
but when I access the whoami.path.net service, it is 404, 
and when I use the NodePort: port method to access the whoami service, it is successful,
I'm sorry this might waste your time, but I have no other way now.
Thinks.
