### ISSUE TITLE
Appending secure flag to existing application cookie

### ISSUE THREAD

**Issue by tirumerla** [containous/traefik#7182]
### Do you want to request a *feature* or report a *bug*?

Bug/More of a question.

### What did you do?

Hi,

I want to append/set the "Secure;HttpOnly" flags to an application cookie that is generated in the backend by Service A which is passing it to Service B via Traefik. I have ingress routes attached to the service B as follows.
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jupyter-ingress
  namespace: kube-system
spec:
    routes:
        - match: Host(`test-xyz.com`) && PathPrefix(`/jupyter`)
          kind: Rule
          services:
            - name: proxy-public
              port: 443
    tls:
        secretName: self-signed-tls
``` 
As i understand, setting middlewares to either `headers.customResponseHeaders` or `headers.customRequestHeaders` would replace existing cookie value to the value we set. The application cookie here is a token, which is not a static value so we will not be able to use either of those header middlewares.

### What did you expect to see?

Application session cookie to be having flags "Secure;HttpOnly" when communicated across different services.

### What did you see instead?

Blank Cookie with Secure;HttpOnly flag. or No Secure;HttpOnly flags when passing between different services.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Environment
```
AWS EKS v1.16
```
Installation
```
helm install traefik traefik/traefik --values config.yaml -n kube-system
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Would be great to know if there is any way to fix it or will this be part of a future release.

Thanks.
