### ISSUE TITLE
Docker-compose: If healthcheck of some service is present - Traefik labels don't work

### ISSUE THREAD

**Issue by MacGyver27** [containous/traefik#7183]
Hi,

While I was upgrading my gitlab setup I stumbled upon problem where: if the service has present healthcheck traefik labels wont work resulting into 404.. When I remove the healthcheck it works (also removed all middleware from the entrypoint to be sure).

I basically used this docker-compose file: https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml

```yml
  gitlab:
    image: sameersbn/gitlab:latest
    container_name: gitlab.551
    restart: always
    depends_on:
    - redis
    - postgresql
    ports:
    - "55180:80"
    - "55122:22"
    volumes:
    - /docker/gitlab/gitlab:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    labels:
      # TRAEFIK 2
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.rule=HostHeader(`gitlab.example.com`)
      - traefik.http.services.gitlab.loadbalancer.server.port=80
```

Using latest `traefik 2.2.8` version.

Thanks for feedback.
