### ISSUE TITLE
It is recommended to add the container name as the default service name

### ISSUE THREAD

**Issue by ztj1993** [containous/traefik#7185]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Suppose, I have such an open docker-compose.yml, this file is for everyone to use:
```
version: "3"
services:

  filebrowser:
    image: filebrowser
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80/tcp
    labels:
      - traefik.enable=true
      - traefik.http.services.filebrowser.loadbalancer.server.port=80
      - traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_HOST:-filebrowser}`)
      - traefik.http.routers.filebrowser.entrypoints=http
```
This seems to be no problem, but if you deploy multiple traefik routers services service names will conflict, I have to use environment variables to solve this problem. I see a lot of such requests, and I suggest simplifying docker labels.

------

The above content software translation!
