### ISSUE TITLE
traefik memory usage keeps growing

### ISSUE THREAD

**Issue by paylm** [containous/traefik#7191]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```

we are notificing RSS memory of traefik process running within Kubernetes pod container keeps growing, eventually reaching the configured memory limits and getting OOMKilled .

I tried to close all log output, but the memory usage is still keeps growing without release after a few days .


```
![Image_20200818145555](https://user-images.githubusercontent.com/16893729/90480799-5f978980-e163-11ea-9b21-c34838f258dd.png)
![Image_20200818145603](https://user-images.githubusercontent.com/16893729/90480814-62927a00-e163-11ea-8a2f-4b7b6111622b.png)

![Image_20200818145613](https://user-images.githubusercontent.com/16893729/90480848-70e09600-e163-11ea-8958-b64617ccf079.png)
![Image_20200818145622](https://user-images.githubusercontent.com/16893729/90480849-7211c300-e163-11ea-8274-1576d1971207.png)

### What did you expect to see?

No unlimited memory growth/leak . 
When the business is low, memory can be recycled .

### What did you see instead?

```memory leak```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```

traefik:v1.7.12

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
--api
--kubernetes
--logLevel=FATAL
```

```
    insecureSkipVerify = true
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        #[entryPoints.http.redirect]
        #  entryPoint = "https"
        #[entryPoints.http.forwardedHeaders]
        #  trustedIPs = ["10.1.0.0/16", "172.20.0.0/16", "192.168.1.3"]
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
            CertFile = "/ssl/tls.crt"
            KeyFile = "/ssl/tls.key"
    [accessLog]
      #accesslog -> stdout
      #filePath = "/logs/traefik.access.log"
      #bufferingSize = 500
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]
```

k8s limit config
```
args:
        - '--configfile=/config/traefik.toml'
        - '--api'
        - '--kubernetes'
        - '--logLevel=FATAL'
      ports:
        - name: http
          hostPort: 80
          containerPort: 80
          protocol: TCP
        - name: https
          hostPort: 443
          containerPort: 443
          protocol: TCP
        - name: admin
          hostPort: 8080
          containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: '7'
          memory: 13Gi
        requests:
          cpu: '4'
          memory: 10Gi
      volumeMounts:
        - name: ssl
          mountPath: /ssl
        - name: config
          mountPath: /config
        - name: traefik-ingress-controller-token-d4wfj
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
          drop:
            - ALL
  restartPolicy: Always
  terminationGracePeriodSeconds: 60
  dnsPolicy: None
  nodeSelector:
    node-role.kubernetes.io/traefik: ''
  serviceAccountName: traefik-ingress-controller
  serviceAccount: traefik-ingress-controller
  nodeName: vm10-xx-xx-xxx
  hostNetwork: true
  securityContext: {}
  imagePullSecrets:
    - name: yzjharborkey
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - vm10-xx-xx-xxx
  schedulerName: default-scheduler
  tolerations:
    - operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/pid-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/unschedulable
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/network-unavailable
      operator: Exists
      effect: NoSchedule
  priorityClassName: system-node-critical
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
--logLevel=FATAL
```

**Comment by ldez** [comment]
Hello, do you still have the same problem with the latest version? [releases](https://github.com/containous/traefik/releases)

**Comment by paylm** [comment]
Has the latest version fixed this problem? We have't tried to use the latest version so far.
We found that when update of k8s nodes (about 360), the memory growth rate is very fast.

**Comment by ldez** [comment]
Have you try v1.7.26?

**Comment by paylm** [comment]
No . I have try v1.7.24 and it's still has this problem.
Now I try v1.7.26 which has any optimization about memory release ?

**Comment by emalihin** [comment]
I am also observing a memory leak in 1.7.26 since the upgrade from 1.7.14. Enabled debug and will provide heap/allocs profile tomorrow.

**Comment by emalihin** [comment]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/6379998/97411457-f83b4a00-1908-11eb-821f-0f9e7ed0d401.png">

```
(pprof) inuse_space
(pprof) top
Showing nodes accounting for 2.86GB, 87.44% of 3.27GB total
Dropped 255 nodes (cum <= 0.02GB)
Showing top 10 nodes out of 73
      flat  flat%   sum%        cum   cum%
    1.72GB 52.47% 52.47%     1.72GB 52.47%  github.com/containous/traefik/vendor/github.com/codahale/hdrhistogram.New
    0.34GB 10.35% 62.82%     0.34GB 10.35%  bytes.(*Buffer).String
    0.22GB  6.72% 69.55%     0.22GB  6.72%  regexp/syntax.(*compiler).inst
    0.21GB  6.33% 75.88%     0.21GB  6.33%  regexp.onePassCopy
    0.11GB  3.45% 79.33%     0.11GB  3.45%  github.com/containous/traefik/vendor/github.com/vulcand/oxy/utils.CopyURL
    0.07GB  2.17% 81.50%     0.08GB  2.51%  regexp.makeOnePass.func1
    0.07GB  2.09% 83.59%     0.07GB  2.09%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).replaceEscapes
    0.06GB  1.78% 85.37%     0.06GB  1.78%  github.com/containous/traefik/vendor/github.com/containous/mux.(*Router).NewRoute
    0.04GB  1.28% 86.65%     0.04GB  1.28%  github.com/containous/traefik/vendor/github.com/vulcand/oxy/forward.New
    0.03GB  0.79% 87.44%     0.03GB  0.79%  fmt.Sprintf
```

```
(pprof) alloc_space
(pprof) top
Showing nodes accounting for 776.33GB, 61.31% of 1266.28GB total
Dropped 1083 nodes (cum <= 6.33GB)
Showing top 10 nodes out of 120
      flat  flat%   sum%        cum   cum%
  143.52GB 11.33% 11.33%   143.52GB 11.33%  github.com/containous/traefik/provider/kubernetes.getAnnotationName (inline)
  120.55GB  9.52% 20.85%   120.55GB  9.52%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).replaceEscapes
   86.69GB  6.85% 27.70%   339.33GB 26.80%  github.com/containous/traefik/provider/kubernetes.(*Provider).loadIngresses
   81.83GB  6.46% 34.16%    81.83GB  6.46%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).setValue
   64.91GB  5.13% 39.29%    64.91GB  5.13%  github.com/containous/traefik/vendor/github.com/codahale/hdrhistogram.New
   63.52GB  5.02% 44.30%    90.97GB  7.18%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).setType
   61.75GB  4.88% 49.18%    61.75GB  4.88%  bytes.makeSlice
   58.14GB  4.59% 53.77%    58.14GB  4.59%  strings.(*Builder).grow (inline)
   50.20GB  3.96% 57.74%    50.20GB  3.96%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.lexSkip
   45.21GB  3.57% 61.31%   390.03GB 30.80%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).topLevel
```

**Comment by emalihin** [comment]
opened https://github.com/traefik/traefik/issues/7481 for 1.7.26

**Comment by emalihin** [comment]
@rtribotte hi, any idea what might be causing memory to grow so rapidly? should i provide more inputs to help debug it?

**Comment by emalihin** [comment]
Interesting pattern in RSS (blue line) and Working Set (yellow line) memory reported by k8s/datadog agent. Drop in the middle is OOM killer
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/6379998/98228917-e89faf00-1f61-11eb-9c11-4e91f76e34a9.png">

**Comment by rtribotte** [comment]
Hello @emalihin,

I'm willing to reopen your issue since i missed that the versions are not matching, in this issue the unusual growth of the memory usage usage happens with the v1.7.12 which seems not coherent with your case.
But before that, can you think about any change that you made other than updating Traefik ?

**Comment by emalihin** [comment]
Hi @rtribotte,

Thank you. Versions are indeed different, and so is the configuration (in my case to TLS termination is done on Traefik).

Yes i've made 2 changes on the previous (1.7.14) version, which worked ok, before upgrading to 1.7.26 - `--respondingtimeouts.idletimeout` increased from 300 to 360 to better match other timeouts in the infrastructure, and also used a `200-600` range instead of a list for `--accessLog.filters.statusCodes`.

Reverted both changes on a test env and still seeing high memory usage growth (until Thu 12:30 it was 1.7.14, after that 1.7.26, after that 1.7.26 with reduced `idletimeout` and after that 1.7.26 with reduced `idletimeout` and a list of 4 access codes for logging)
<img width="606" alt="image" src="https://user-images.githubusercontent.com/6379998/98352500-c328a900-2026-11eb-85d9-dbd416a81fa9.png">

**Comment by diegosanchez** [comment]
We are running `traefik:1.7.20`. After creating the following _ingresses_, the memory consumption of the pod skyrocketed as follows:

![image](https://user-images.githubusercontent.com/3934479/115287986-464a4100-a127-11eb-8702-93316cd1d10e.png)

The ingress:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: class-int
    ingress.kubernetes.io/protocol: h2c
  labels:
    app: app
    name: app-sidecar
  name: app-sidecar
  namespace: ns
spec:
  rules:
  - host: app-sidecar.domain.com
    http:
      paths:
      - backend:
          serviceName: app-sidecar
          servicePort: grpc
        path: /
```

Do other case use this protocol?
