### ISSUE TITLE
traefik 2.2.8 and redis kv backend set multi key not work

### ISSUE THREAD

**Issue by kkk25641463** [containous/traefik#7208]
bug

when i set multi key into redis,probably the key value config not take affect, maybe  traefik has some cache betweend redis and traefik?
The more keys import in the same time, the more bug probability happened.

### What did you expect to see?
entrypoint router can take affect

### What did you see instead?
send some http request not wort for traefik

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.2.8

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
centos 7.6

```toml
[root@localhost dynamic]# cat management.toml 
#[tcp]
#  [tcp.routers]
#    [tcp.routers.testTcp]
#      entryPoints = ["websecure"]
#      # Catch every request (only available rule for non-tls routers. See below.)
#      rule = "HostSNI(`*`)"
#      service = "testTcp"
#  [tcp.services]
#    [tcp.services.testTcp.loadBalancer]
#      [[tcp.services.testTcp.loadBalancer.servers]]
#        address = "10.3.101.21:31678"
  
[http]
  [http.routers]
    # Define a connection between requests and services
    #[http.routers.to-management]
    #  entryPoints = ["web"]
    #  rule = "PathPrefix(`/management`)"
    #  #If the rule matches, forward to the management service (declared below)
    #  service = "base-management"
    #  middlewares = ["corsHeader","keycloak","authentication"]

    #[http.routers.to-apigateway]
    #  entryPoints = ["web"]
    #  rule = "PathPrefix(`/apigateway`)"
    #  #If the rule matches, forward to the management service (declared below)
    #  service = "base-apigateway"
    #  middlewares = ["corsHeader","keycloak","authentication"]

   # [http.routers.to-login]
   #   entryPoints = ["websecure"]
   #   rule = "PathPrefix(`/authcenter/login`,`/authcenter/logout`)"
   #   service = "base-login"
   #   middlewares = ["corsHeader"]

   # [http.routers.to-authcenter]
   #   entryPoints = ["web"]
   #   rule = "PathPrefix(`/authcenter`)"
      #If the rule matches, forward to the management service (declared below)
   #   service = "base-authcenter"
   #   middlewares = ["corsHeader","keycloak","authentication"]
    
   # [http.routers.to-organization]
   #   entryPoints = ["web"]
   #   rule = "PathPrefix(`/organization`)"
      #If the rule matches, forward to the management service (declared below)
   #   service = "base-organization"
   #   middlewares = ["corsHeader","keycloak","authentication"]

    #[http.routers.to-permit-center]
    #  entryPoints = ["web"]
    #  rule = "PathPrefix(`/permit-center`)"
      #If the rule matches, forward to the management service (declared below)
    #  service = "permit-center"
    #  middlewares = ["corsHeader","keycloak","authentication"]  

   # [http.routers.to-permit-center-minio]
   #   entryPoints = ["web"]
   #   rule = "Path(`/permit-center/minio/{*}`)"
      #If the rule matches, forward to the management service (declared below)
   #   service = "permit-center"
   #   middlewares = ["corsHeader"]  

   # [http.routers.to-file]
   #   entryPoints = ["web"]
   #   rule = "PathPrefix(`/authcenter/file`)"
      #If the rule matches, forward to the management service (declared below)
   #   service = "base-authcenter"
   #   middlewares = ["corsHeader"]

    [http.routers.to-authcenter-api]
      entryPoints = ["websecure"]
      rule = "PathPrefix(`/authcenter`)"
      #If the rule matches, forward to the management service (declared below)
      service = "authcenter-api"
      middlewares = ["corsHeader","authApi","authentication"]

   # [http.routers.to-apigateway-api]
   #   entryPoints = ["websecure"]
   #   rule = "PathPrefix(`/apigateway`)"
      #If the rule matches, forward to the management service (declared below)
   #   service = "apigateway-api"
   #   middlewares = ["corsHeader","keycloak","authentication"]
    
    [http.routers.to-minio-api]
      entryPoints = ["web"]
      rule = "PathPrefix(`/`)"
      #If the rule matches, forward to the management service (declared below)
      service = "minio-api"
      #            middlewares = ["corsHeader","keycloak","authentication"]     
    
    [http.routers.to-objectstorage-api]
      entryPoints = ["websecure"]
      rule = "PathPrefix(`/`) && Method(`PUT`,`OPTIONS`) && Query(`policy={*}`)"
      #If the rule matches, forward to the management service (declared below)
      service = "objectstorage-api"
      middlewares = ["replacepath"]

    [http.routers.to-object-api]
      entryPoints = ["websecure"]
      rule = "PathPrefix(`/`)"
      #If the rule matches, forward to the management service (declared below)
      service = "apigateway-api"
      #
   # [http.routers.websocket]
   #   entryPoints = ["web"]
   #   rule = "PathPrefix(`/mpush/`) && Method(`GET`,`OPTIONS`)"
      #If the rule matches, forward to the management service (declared below)
   #   service = "mpush"
   #   middlewares = ["1272793601535496193-backendforward"]

  [http.services]
    [http.services.base-management.loadBalancer]
      [[http.services.base-management.loadBalancer.servers]]
        url = "http://10.3.101.182:8080"

    [http.services.base-login.loadBalancer]
      [[http.services.base-login.loadBalancer.servers]]
        url = "http://10.3.101.182:8090"
    
    [http.services.base-authcenter.loadBalancer]
      [[http.services.base-authcenter.loadBalancer.servers]]
        url = "http://10.3.101.182:8090"

    [http.services.base-organization.loadBalancer]
      [[http.services.base-organization.loadBalancer.servers]]
        url = "http://10.3.101.182:5008"

    [http.services.base-apigateway.loadBalancer]
      [[http.services.base-apigateway.loadBalancer.servers]]
        url = "http://10.3.101.182:5009"

    [http.services.permit-center.loadBalancer]
      [[http.services.permit-center.loadBalancer.servers]]
        url = "http://10.3.101.182:7010"

    [http.services.authcenter-api.loadBalancer]
      [[http.services.authcenter-api.loadBalancer.servers]]
        url = "http://10.3.101.102:8090"

    [http.services.apigateway-api.loadBalancer]
      [[http.services.apigateway-api.loadBalancer.servers]]
        url = "http://10.3.101.102:5009"

    [http.services.minio-api.loadBalancer]
      [[http.services.minio-api.loadBalancer.servers]]
        url = "http://10.3.101.50:9001"

    [http.services.objectstorage-api.loadBalancer]
      [[http.services.objectstorage-api.loadBalancer.servers]]
        url = "http://10.3.101.102:8080"

   # [http.services.mpush.loadBalancer]
   #   [[http.services.mpush.loadBalancer.servers]]
   #     url = "http://10.3.101.104:8008"
		
  [http.middlewares]
    [http.middlewares.keycloak]
      [http.middlewares.keycloak.forwardAuth]
        address = "http://10.3.101.50:8090/authcenter/oAuth"
        trustForwardHeader = true
        authResponseHeaders = ["X-User-Id","X-Tenant-Id","X-Tenant-Type"]
   
    [http.middlewares.authApi]
      [http.middlewares.authApi.forwardAuth]
        address = "http://10.3.101.50:8090/authcenter/oAuth"
        trustForwardHeader = true 

    [http.middlewares.authentication.forwardAuth]
        address = "http://10.3.101.50:8090/authcenter/authentication"
        trustForwardHeader = true
        authResponseHeaders = ["X-Data-Auth"] 
    
    [http.middlewares.testHeader.headers]
      [http.middlewares.testHeader.headers.customRequestHeaders]
        host = "pescoiot-daemon.apps.okd3.sypesco.com"     

   # [http.middlewares.1272793601535496193-backendforward.replacePathRegex]
   #     regex = "/mpush/"
   #     replacement = "/"    
    
    [http.middlewares.replacepath.replacePath]
      path = "/objectstorage/v1/test"    
 
    [http.middlewares.corsHeader]
      [http.middlewares.corsHeader.headers]
        accessControlAllowCredentials = true 
        accessControlAllowMethods= ["*"]
        accessControlAllowOrigin = "*"
        accessControlAllowHeaders = ["*"]
        accessControlExposeHeaders = ["*"]
        accessControlMaxAge = 3600
       #addVaryHeader = true

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
