### ISSUE TITLE
Option tls.passthrough not found // docker

### ISSUE THREAD

**Issue by flexchar** [containous/traefik#7209]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured docker service to join Traefik network and serve over TLS with _passthrough_ option.

```yml
        networks:
            - traefik
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.nginx.entrypoints=web-secure,internal'
            - 'traefik.http.routers.nginx.tls=true'
            - 'traefik.http.routers.nginx.tls.passthrough=true'
            - 'traefik.http.routers.nginx.rule=Host(`abc.xyz`)'
            - 'traefik.http.routers.nginx.service=laravel'
            - 'traefik.http.services.nginx.loadbalancer.server.port=443'      
```

### What did you expect to see?

Expected to appear on Traefik dashboard and actually work. According to [docs](https://docs.traefik.io/routing/routers/#passthrough) - the requests should be forwarded "as is", keeping all data encrypted. 

### What did you see instead?

It never appeared. Thanks to logs, seems like passthrough is not recognized. 
```time="2020-08-21T16:59:48Z" level=error msg="field not found, node: passthrough" providerName=docker container=nginx-mg-9536246b19a1f50201e15cc8d9ebd6659d9fe622c58e3df6f8890b3912f725f6```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
cat docker-compose.yml 
version: "3.8"

services:
    traefik:
        image: "traefik:v2.2.8"
        restart: always
        command:
            - "--accesslog=true"
            - "--accesslog.filepath=/var/log/traefik-access.log"
            - "--accesslog.format=json"
            - "--accesslog.filters.statuscodes=200,300-302"
            - "--accesslog.filters.retryattempts"
            - "--accesslog.filters.minduration=10ms"
            - "--log.level=DEBUG"
            - "--log.filepath=/var/log/traefik.log"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.watch"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web-secure.address=:443"
            - "--entrypoints.traefik.address=:8081"
            - "--entrypoints.internal.address=:8082"
            - "--metrics.prometheus=true"
            - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
            - "--tracing.zipkin=true"
            - "--tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans"
            - "--tracing.zipkin.sameSpan=true"
            - "--tracing.zipkin.id128Bit=true"
            - "--tracing.zipkin.sampleRate=1"
        ports:
            - "80:80"
            - "443:443"
            - "8081:8081"
            - "8082:8082"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - ./traefik-logs:/var/log
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.entrypoints=internal"
            - "traefik.http.routers.traefik.rule=Host(`traefik.dockerdev`)"
            - "traefik.http.routers.traefik.service=traefik"
            - "traefik.http.services.traefik.loadbalancer.server.port=8081"

```

The option `  - "traefik.tcp.routers.tcprouter0.tls.passthrough=true"` seems valid, it is written in Docs Docker reference
https://docs.traefik.io/reference/dynamic-configuration/docker/

The multiple docker containers that join the same network are used. Traefik connection is defined in labels. Everything works like charm while on HTTP but TLS is necessary for this very service. :)

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```time="2020-08-21T16:59:48Z" level=error msg="field not found, node: passthrough" providerName=docker container=nginx-mg-9536246b19a1f50201e15cc8d9ebd6659d9fe622c58e3df6f8890b3912f725f6```
