### ISSUE TITLE
Support multiple certificates for K8s TLSStore

### ISSUE THREAD

**Issue by raravena80** [containous/traefik#7210]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, the TLSStore K8s CRD only allows you to supply the `defaultCertificate` but not specify an array of other certificates for other domains. This is supported by Traefik as pointed in the [docs](https://docs.traefik.io/https/tls/#certificates-stores). For example:

```yaml
tls:
  certificates:
    - certFile: /path/to/domain.cert
      keyFile: /path/to/domain.key
      stores:
        - default
    # Note that since no store is defined,
    # the certificate below will be stored in the `default` store.
    - certFile: /path/to/other-domain.cert
      keyFile: /path/to/other-domain.key
```

The default certificate is defined like this (which I believe is supported in the K8s CRD)

```yaml
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "path/to/cert.crt"
      keyFile  = "path/to/cert.key"
```

Note that the docs say that you can only use the `default` certificate. They also say that's the case for K8s too.

> Traefik currently only uses the TLS Store named "default". This means that if you have two stores that are named default in different kubernetes namespaces, they may be randomly chosen. For the time being, please only configure one TLSSTore named default.

Some background: https://stackoverflow.com/questions/63560000/traefik-kubernetes-multiple-ssl-certificates
