### ISSUE TITLE
Keep a valid mirroring service if one or more mirrors are not found (in Kubernetes)

### ISSUE THREAD

**Issue by zorgzerg** [containous/traefik#7220]
### Do you want to request a *feature* or report a *bug*?

I don't know if this is a bug or a feature, but look: 

I have highload application in k8s (20 pods in production, for example), it has TraefikService like this:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: site
spec:
  mirroring:
    kind: Service
    name: site
    port: 5000
    mirrors:
      - kind: Service
        name: site-alpha
        percent: 5
        port: 5000
```
Also, I am deploying this application with new functionality and want to test it under real load (1 pod), and it has k8s Service like this:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: site-alpha
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
  selector:
    ...
```

It's allright. But! 
When I uninstall the tested version from the cluster, the `site-alpha` Service is removed too, and the TrafficService `site` becomes invalid. Production app is dead, tarefik return `404`. Sick!

Logs:
```
...
time="2020-08-27T23:51:18Z" level=error msg="Error while building TraefikService: kubernetes service not found: default/site-alpha" providerName=kubernetescrd serviceName=site
...
```

### What did you expect to see?

I would like this to be fixed:
1. If the mirror service (`site-alpha` in example) does not exist, let the traefik ignore this, just not mirror the traffic there. 
   OR
2. Add property for CRD `TraefikService` (such as `require`), like this:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: site
spec:
  mirroring:
    kind: Service
    name: site
    port: 5000
    mirrors:
      - kind: Service
        name: site-alpha
        require: false
        percent: 5
        port: 5000
```

I think this behavior will be more logical than now. 
I stay with hope, Thnx
