### ISSUE TITLE
How to implement Canary deployment?

### ISSUE THREAD

**Issue by ne1000** [containous/traefik#7223]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

kubernetes version: 1.17
traefik: 2.2.8

 I'd like to implement Canary deployment , I follow the following configuration ，but  I cannot get what I want

```yaml
apiVersion: traefik.containo.us/v1alpha1 
kind: IngressRoute
metadata:
    name: canary
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.rod.cn`)
      kind: Rule
      services:
        - name: app-v1
          port: 8080
          weight: 3   
          namespace: prod-appv1
        - name: app-v2
          prot: 8080
          weight: 1
          namespace: prod-appv2
```
how to proxy it to multiple namespaces ?
