### ISSUE TITLE
IngressRouteUDP not creating endpoints

### ISSUE THREAD

**Issue by myoung34** [containous/traefik#7228]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to set up a DNS proxy via traefik (pihole)

I have a UDP route set up that looks as expected:

![](https://cdn.zappy.app/f0bd02602e398f84c346597c243420d7.png)
![](https://cdn.zappy.app/35ba5f91798dbe7f45c48792995c475c.png)

looks fine, but udp just isnt connectable over traefik

```
± dig @pihole.cluster.local www.google.com +short +tcp | head -n 1
74.125.138.103
```
```
± dig @pihole.cluster.local www.google.com +short

; <<>> DiG 9.10.6 <<>> @pihole.cluster.local www.google.com +short
; (2 servers found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
 but inside the cluster hitting the endpoint over udp/tcp is fine:
```
 ± kubectl get endpoints | grep pihole
pihole-tcp                   10.42.2.203:443,10.42.2.203:80,10.42.2.203:53        25h
pihole-udp                   10.42.2.203:53,10.42.2.203:67
```
```
myoung@kube1:~$ dig @10.42.2.203 www.google.com +short | head -n 1
64.233.185.106
myoung@kube1:~$ dig @10.42.2.203 www.google.com +short +tcp | head -n 1
64.233.185.104
```
which makes me thing that something about traefik just isnt working over udp via reverse proxy

```
± kubectl get svc | grep -E 'traefik|pihole'
traefik-udp                  LoadBalancer   10.43.97.111    192.168.2.98   53:32588/UDP                              29h
traefik                      LoadBalancer   10.43.247.122   192.168.2.98   53:32428/TCP,80:31075/TCP,443:32735/TCP   42h
pihole-tcp                   ClusterIP      10.43.63.124    <none>         80/TCP,443/TCP,53/TCP                     61m
pihole-udp                   ClusterIP      10.43.19.228    <none>         53/UDP,67/UDP                             61m
```

```
± kubectl describe svc/traefik | grep Endpoint
Endpoints:                10.42.2.202:8853
Endpoints:                10.42.2.202:8000
Endpoints:                10.42.2.202:8443
```
```
± kubectl describe svc/traefik-udp | grep Endpoint
Endpoints:                <none>
```

### What did you expect to see?

A working endpoint exposed for the UDP service

### What did you see instead?

No endpoint for the UDP service

```
± kubectl describe svc/traefik-udp | grep Endpoint
Endpoints:                <none>
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
± kubectl exec -it traefik-85d7c864fb-hw64j traefik version
Version:      2.3.0-rc4
Codename:     picodon
Go version:   go1.15
Built:        2020-08-19T16:02:03Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik helm values.yaml:

```
  dns:
    port: 8853
    expose: true
    exposedPort: 53
    # The port protocol (TCP/UDP)
    protocol: TCP
  dnsudp:
    port: 8853
    expose: true
    exposedPort: 53
    # The port protocol (TCP/UDP)
    protocol: UDP
```

pihole ingress:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pihole-dns
spec:
  entryPoints:
    - dns
  routes:
    - kind: Rule
      match: HostSNI(`*`)
      services:
        - name: pihole-tcp
          port: 53
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: pihole-dns
spec:
  entryPoints:
    - dnsudp
  routes:
    - services:
      - name: pihole-udp
        port: 53
        passHostHeader: true
```
