### ISSUE TITLE
Missing required RBAC permission in helm template

### ISSUE THREAD

**Issue by myoung34** [containous/traefik#7232]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created v2.2 traefik on k3s via the official helm template

### What did you expect to see?

No errors

### What did you see instead?

Errors in the service about missing permissions.

Resolved by adding 

```
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
```

to ` templates/rbac/clusterrole.yaml`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
± kubectl exec -it traefik-85d7c864fb-hw64j traefik version
Version: 2.3.0-rc4
Codename: picodon
Go version: go1.15
Built: 2020-08-19T16:02:03Z
OS/Arch: linux/arm64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

not relevant

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
$ kubectl logs service/traefik-udp | tail -n 1
E0831 15:26:55.935478       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1beta1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:default:traefik" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope
```
