### ISSUE TITLE
Simplify creation of HTTP+HTTPS router

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#7235]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Almost all my deployed services listen on both HTTP and HTTPS. Most routes just use the HTTP version to apply a 301 redirection to the HTTPS version.

[The docs](https://docs.traefik.io/routing/routers/#general) clearly say:

![imagen](https://user-images.githubusercontent.com/973709/91975362-348e6780-ed17-11ea-8110-85ae6cf50502.png)

This is very disappointing, because a router might have a bunch of middlewares and other configurations, and having to repeat every single thing just because I want the 301 redirection is tedious.

I think it would be best to be able to configure a router like this:

```yaml
## Dynamic configuration
http:
  middlewares:
    forceSecure:
      forceSTSHeader: true
      sslRedirect: true

  routers:
    my-http-and-https-router:
      rule: "Host(`foo-domain`) && Path(`/foo-path/`)"
      service: service-id
      middlewares: [forceSecure]
      tls:
        # Listen on both TLS and non-TLS modes. The forceSecure middleware will upgrade all non-TLS requests anyway.
        required: false
```

This way:

1. If you want an HTTP-only router, you don't define a `tls` section.
1. If you want an HTTPS-only router, you define the `tls` section (`true` would be the default value for `tls.required`).
1. If you want an HTTP+S router, you define `tls.required=false` and, optionally, leverage a middleware to force it.
