### ISSUE TITLE
IngressRoute without a "real" service

### ISSUE THREAD

**Issue by rdxmb** [containous/traefik#7242]
# Do you want to request a *feature* or report a *bug*?

/kind feature

# What did you expect to see?

I'd like to configure an IngressRoute within Kubernetes without having a real Kubernetes Service and Pod for this.

# Why?

There are cases when you have to define a service + pod in kubernetes, just to follow the syntax rules of the IngressRoute - even when thy are not needed in practice. In the example below, the service named `dummy` will never be used for real. **But** it has to be defined **and** created, because of the syntax requirements of the IngressRoute. (If you do not define it, you'll always get a `404 page not found`)

![Screenshot_20200903_224546](https://user-images.githubusercontent.com/30314040/92165654-a8c02c80-ee37-11ea-9c64-226fefe7dee4.png)

# Possible idea

Having a keyword like `dummy` or `none` could leave the syntax rules as they are. However, it should be possible to use them without defining a kubernetes service **and** pod.

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http
spec:
  entryPoints:
    - public-http
  routes:
  - kind: Rule
    match: "Host(`example.com`)"
    middlewares:
      - name: redirect-to-https-perm
        namespace: traefik-2
    services:
    - name: dummy
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https
spec:
  entryPoints:
    - public-https
  routes:
  - kind: Rule
    match: "Host(`example.com`)"
    middlewares:
      - name: set-hsts-one-year
        namespace: traefik-2
      - name: set-hsts-preload
        namespace: traefik-2
      - name: redirect-to-www-example-com
    services:
    - name: dummy
      port: 80
  tls:
    certResolver: public
    options:
      name: min-version-12
      namespace: traefik-2
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-www-example-com
spec:
  redirectRegex:
    regex: ".*"
    replacement: "https://www.example.com"
    permanent: true
---
# dummy-service is needed, which is never used
# dummy-pod behind dummy-service is needed, which is never used
```

**Comment by rdxmb** [comment]
`services: []` would also a good idea - https://github.com/containous/traefik/pull/6739#issuecomment-621321580

**Comment by jbdoumenjou** [comment]
Hi @rdxmb ,

Concerning the redirection, you can configure it on the [entrypoints](https://docs.traefik.io/v2.2/routing/entrypoints/#http-options).
To do so, the Traefik [static configuration](https://docs.traefik.io/v2.2/getting-started/configuration-overview/#the-static-configuration) need to be updated with something like:

```yaml
# ...
containers:
        - name: traefik
          image: traefik:v2.2.8
          args:
            - --entrypoints.public-http.Address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=public-https            
            - --entrypoints.public-https.Address=:443
          # ...
```

Have you got another use case that needs to define empty or "dummy" service ?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by rdxmb** [comment]
Hi @jbdoumenjou 

thanks for your answer.

> Concerning the redirection, you can configure it on the [entrypoints](https://docs.traefik.io/v2.2/routing/entrypoints/#http-options).

Ok, but this is global for all services, isn't it? So if I have still some http-urls, this is not a way for me.

> Have you got another use case that needs to define empty or "dummy" service ?

Yes, every kind of redirect to another `Host` - no matter which is answered by another Host/Router. No matter what kind of middleware is used here, e.g. `replacePathRegex` or whatever...

**Comment by jbdoumenjou** [comment]
Hi @rdxmb ,

Could you please try a configuration like :

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`mydomain`)"
      middlewares:
        - name: redirect-to-anything
      services:
        - name: noop@internal
          kind: TraefikService
```

This will use an internal "dummy" service.
