### ISSUE TITLE
Invalid token on plugin download

### ISSUE THREAD

**Issue by lexfrei** [containous/traefik#7243]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Nothing, just found my traefik in this condition today after two fine weeks, but joining to the pilot group works well

### What did you expect to see?

Working instance

### What did you see instead?

```
time="2020-09-03T20:29:54Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
2020/09/03 20:29:55 traefik.go:76: command traefik error: failed to download plugin github.com/containous/plugin-simplecache: error: 400: {"error":"invalid token"}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc4
Codename:     picodon
Go version:   go1.15
Built:        2020-08-19T16:02:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
    checkNewVersion: true
    sendAnonymousUsage: false

certificatesResolvers:
    prodssl:
        acme:
            email: "f@lex.la"
            storage: "/acme/prod.json"
            tlsChallenge: {}

providers:
    docker:
        swarmMode: true
        watch: true
        network: "traefik"
        exposedByDefault: false
    file:
        watch: true
        filename: "/etc/traefik/traefik.yml"

api:
    dashboard: true

entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: :443
        http:
            middlewares:
                - secHeaders@file
                - cache@file
                - compress@file
    metrics:
        address: ":8082"

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5
        entryPoint: metrics

http:
    middlewares:
        auth:
            basicAuth:
                users:
                    - "lex:XXX"
        secHeaders:
            headers:
                sslRedirect: true
                stsIncludeSubdomains: true
                stspreload: true
                stsseconds: 31536000
        cache:
            plugin:
                plugin-simplecache:
                    path: /tmp
        compress:
            compress: {}

experimental:
    pilot:
        token: "XXX"
    plugins:
        plugin-simplecache:
            moduleName: "github.com/containous/plugin-simplecache"
            version: "v0.1.1"

```

My env is pretty similar to this repo:
https://github.com/lexfrei/GhostStack

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-09-03T20:29:54Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
2020/09/03 20:29:55 traefik.go:76: command traefik error: failed to download plugin github.com/containous/plugin-simplecache: error: 400: {"error":"invalid token"}
```
