### ISSUE TITLE
broken hostname resolution, especially for localhost

### ISSUE THREAD

**Issue by akvadrako** [containous/traefik#7251]
### Do you want to request a *feature* or report a *bug*?
Bug
### What did you do?
I recently upgraded my system and found that traefik is not honoring the `/etc/hosts` file like it used to.

I have configured a *service* with `url = http://localhost:809`.

### What did you expect to see?
I expected to see the proxy connect to `http://127.0.0.1:809`

### What did you see instead?
The proxy was connecting to `http://localhost.so:809/`.
Note: `.so` is the TLD for my server.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.3.0-rc4
Codename:     picodon
Go version:   go1.15
Built:        2020-08-19T16:02:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```yaml
http:
  routers:
    xxx:
      rule: "Host(`xxx`)"
      service: xxx

  services:
    xxx:
      loadBalancer:
        servers:
        - url: http://localhost:809
```

**/etc/hosts** in container
```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Official docker image on docker 19.03.12 with `--net host` on Debian 10.
