### ISSUE TITLE
traefik v2.2 http to https redirect 

### ISSUE THREAD

**Issue by DeanKamali** [containous/traefik#7253]
I'm following[ the guide](https://docs.traefik.io/routing/entrypoints/) and I'm able to access my website via HTTP and HTTPs however redirect is not working for me, any ideas on what might be wrong?

```
# IngresRoute
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: whoami
  namespace: default

spec:
  entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443

  routes:
  - match: Host(`hello.mydomain.io`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls: {}
```
