### ISSUE TITLE
[Windows] ipWhiteList middleware failed to parse IP on (local) IPv6 with zone id attached

### ISSUE THREAD

**Issue by ydder007** [containous/traefik#7270]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I set up an ipWhiteList middleware for our application and tried to access one of the routers with the middleware attached.

### What did you expect to see?
A valid service response.

### What did you see instead?
A canceled request.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

[http.services.nginx]
      [http.services.nginx.loadBalancer]
        [[http.services.NGINX.loadBalancer.servers]]
          url = "http://example.com:8080"

[http.routers.nginx]
      entryPoints = ["web", "web-secure"]
      priority = 10
      service = "nginx"
      rule = "PathPrefix(`/test`)"
      middlewares = ["whitelist"]

[http.middlewares.whitelist.ipWhiteList]
      sourceRange = ["0.0.0.0/0", "::/0"]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
RemoteAddr:[fe80::xxxx:yyy:zzz:0123%vEthernet (Default Switch)]:58904 RequestURI:/test/ TLS:0xc0003da210 Cancel:<nil> Response:<nil> ctx:0xc0008ef530}: unable to parse address: fe80::xxxx:yyyy:zzzz:0123%vEthernet (Default Switch): can't parse IP from address fe80::xxxx:yyyy:zzzz:0123%vEthernet (Default Switch)"
```
