### ISSUE TITLE
Unable to use `X-Forwarded-Proto` header in `sslProxyHeaders` setting

### ISSUE THREAD

**Issue by niksauer** [containous/traefik#7273]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Similar to https://github.com/containous/traefik/issues/1924, we would like to use a Google Cloud HTTP load balancer that handles SSL termination and forwards traffic to Traeffik using the HTTP protocol. In order to issue HTTPS redirects for plain HTTP requests, we need to setup SSL redirection based on the `X-Forwarded-Proto` header that will be set to `http` or `https` respectively. 

### What did you expect to see?

Requests that include the `X-Forwarded-Proto: https` header should not get redirected.

### What did you see instead?

When using the `X-Forwarded-Proto` header, all requests got redirected regardless of the value. This is not the case when using a different header name such as `X-Test`. 

Using the `docker-compose` environment below, here's a simple test case (remember to uncomment the other container label while testing the `X-Test` header):

```bash
$ docker-compose up

$ curl -i -H "Host: whoami.localhost" -H "X-Forwarded-Proto: http" localhost:3000
HTTP/1.1 301 Moved Permanently (CORRECT)

$ curl -i -H "Host: whoami.localhost" -H "X-Forwarded-Proto: https" localhost:3000
HTTP/1.1 301 Moved Permanently (WRONG - EXPECTED 200)

$ curl -i -H "Host: whoami.localhost" -H "X-Test: http" localhost:3000
HTTP/1.1 301 Moved Permanently (CORRECT)

$ curl -i -H "Host: whoami.localhost" -H "X-Test: https" localhost:3000
HTTP/1.1 200 OK (CORRECT)
```

I am pretty sure it has something to do with the changes made in https://github.com/containous/traefik/pull/5836. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: "3.4"

services:
  traefik:
    image: traefik:2.2.8
    container_name: traefik
    command:
      - --api
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.http.address=:3000
    ports:
      - 3000:3000 # LB
      - 8080:8080 # dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: containous/whoami
    container_name: simple-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.headers.sslredirect=true"
      - "traefik.http.middlewares.https-redirect.headers.sslproxyheaders.X-Forwarded-Proto=https"
      # - "traefik.http.middlewares.https-redirect.headers.sslproxyheaders.X-Test=https"
      - "traefik.http.routers.whoami.middlewares=https-redirect"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
