### ISSUE TITLE
error while parsing rule Host(`www.xxoo.com`) && PathPrefix(`/`: 1:39: missing ',' before newline in argument list

### ISSUE THREAD

**Issue by wiliiwin** [containous/traefik#7274]
I now use the traefix + consul method as the gateway, and docker compose to start the relevant business container. The docker compose configuration of the business container is as follows:

```
version: '3'
services:
  nginx-7890:
    container_name: nginx-7890
    image: nginx 
    ports:
      - 80
    environment:
       - SERVICE_TAGS=traefik.enable=true,traefik.http.routers.myrouter.rule=Host(`www.xxoo.com`) && PathPrefix(`/`,`/(.*)/`) && Headers(`hash`,`7890`)
,traefik.http.routers.myrouter.entrypoints=web,traefik.http.routers.myrouter.service=nginx,traefik.http.routers.myrouter.priority=42,traefik.http.servi
ces.nginx.loadbalancer.server.scheme=http,traefik.http.services.nginx.loadbalancer.healthcheck.hostname=www.xxoo.com,traefik.http.services.nginx.loadba
lancer.healthcheck.path=/,traefik.http.services.nginx.loadbalancer.healthcheck.port=80,traefik.http.services.nginx.loadbalancer.healthcheck.scheme=http
,traefik.http.services.nginx.loadbalancer.healthcheck.timeout=10,traefik.http.services.nginx.loadbalancer.server.port=80,traefik.http.services.myservic
e.loadbalancer.healthcheck.interval=10
    networks:
      - default
    restart: always
```
<img width="1624" alt="WX20200910-222127@2x" src="https://user-images.githubusercontent.com/20533148/92744418-11695500-f3b4-11ea-86ff-4401b200d1e9.png">
From the above figure, you can see that the business container has been registered to the consul

traefik.http.routers.myrouter.rule=Host(`www.xxoo.com`) && PathPrefix(`/`,`/(.*)/`) && Headers(`hash`,`7890`) 
Here, I want to achieve the flow to this container when the domain name, path and header match
However, there is an error in the web interface of traefik. The error is as follows:

<img width="1450" alt="WX20200910-222311@2x" src="https://user-images.githubusercontent.com/20533148/92745014-8f2d6080-f3b4-11ea-90bb-cbb99f38f3a0.png">

Service of docker compose service_tags are separated by commas, and the rule of traefik are also separated by commas, which leads to this error
Now I don't know how to configure it to meet the above requirements. I hope you can help me. Thank you
