### ISSUE TITLE
ReplacePathRegex middleware is not matching regex as expected

### ISSUE THREAD

**Issue by Reapor-Yurnero** [containous/traefik#7276]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Here's a docker creation configuration I used to create a container.
```bash
docker create --name brickserver-playground-deployment \
    --rm \
    -it \
    -e LOG_LEVEL="debug" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD:/app \
    -e ENABLE_SSL=false \
    --entrypoint /app/docker/start-reload.sh \
    --privileged=true \
    --label "traefik.http.routers.bs-backend.rule=Host(\"myhost\") && ( PathPrefix(\"/docs\") || PathPrefix(\"/dummy-frontend\") || PathPrefix(\"/auth\") || PathPrefix(\"/brickapi\") )" \
    --label traefik.http.routers.bs-backend.entrypoints=websecure \
    --label traefik.http.routers.bs-backend.tls=true \
    --label traefik.http.routers.bs-backend.tls.certresolver=leresolver \
    --label "traefik.http.routers.bs-backend.middlewares=test-replacepathregex" \
    --label "traefik.http.middlewares.test-replacepathregex.replacepathregex.regex=^/brickapi/(.*)" \
    --label "traefik.http.middlewares.test-replacepathregex.replacepathregex.replacement=/bar/$$1" \
    --label "traefik.docker.network=deployment_default" \
    jbkoh/playground:0.1
docker network connect deployment_default brickserver-playground-deployment
docker network connect isolated_nw brickserver-playground-deployment
docker start -ai brickserver-playground-deployment
```

### What did you expect to see?

I'm expecting the `ReplacePathRegex` to work as described in the documentation. Specifically for my regex replacement rule, requests in path `/brickapi/abc` should be updated as `/bar/abc`.

### What did you see instead?

Request with path `/brickapi/abc` is updated to `/bar/12781`. 

The server's log: `"GET /bar/12781 HTTP/1.1" 404 Not Found` 

Each time I restart the container, the integer there is different. I don't understand how could a interger be matched here.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

The docker compose file for traefik
```
  traefik:
    container_name: brickserver-traefik-deployment
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --certificatesresolvers.leresolver.acme.email=myemail
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --log=true
      - --log.filepath=/traefik.log
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/acme.json:/acme.json
        #- ./configs/traefik.toml:/traefik.toml
    labels:
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

The log is not super useful as even it's at DEBUG level I can't see the activities of the middlewares.
