### ISSUE TITLE
Dashboard still visible when using basicauth docs configuration

### ISSUE THREAD

**Issue by yfstein** [containous/traefik#7282]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Set up a new host with docker + traefik v2.
Set configuration as described in https://docs.traefik.io/v2.0/operations/api/#configuration

### What did you expect to see?

Asked for Username / password for any url ...server/api/... or ...server/dashboard/...

### What did you see instead?

404 page not found

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: "traefik:v2.2"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
#      - "--log.level=DEBUG"
  # explicitly enable the dashboard, available on the "Traefik Service" named api@internal along with the API
      - "--api.dashboard=true"
  # Enabling docker provider
      - "--providers.docker=true"
  # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
  # Traefik will listen to incoming request on the port 80 (HTTP)
      - "--entrypoints.web.address=:80"
  # Traefik will listen to incoming request on the port 443 (https)
      - "--entrypoints.websecure.address=:443"
  # Enable a http challenge named "myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
  # Tell it to use our predefined entrypoint named "web"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
  # For Debugging Purpose uncomment
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  # The email to provide to let's encrypt
      - "--certificatesresolvers.myresolver.acme.email=postmaster@domain.com"
  # Tell to store the certificate on a path under our volume
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
  # Traefik exposing port 80 (HTTP)
      - "80:80"
  # Traefik exposing port 443 (HTTPS)
      - "443:443"
  # Traefik exposing port 8080 (Doashboard)
#just needed for insecure      - "8080:8080"

    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.removeheader=true"
      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$382/C0l/$$u7FUfBJnNcnPgL2RfoRzC0"

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"

    labels:
  # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
  # The domain the service will respond to
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain.com`)"
  # Allow request only from the predefined entry point named "websecure"
      - "traefik.http.routers.whoami.entrypoints=websecure"
  # Uses the Host rule to define which certificate to issue
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Starting simple-service ... done
Recreating traefik      ... done
Attaching to simple-service, traefik
simple-service | Starting up on port 80
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Configuration loaded from flags."
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Traefik version 2.2.11 built on 2020-09-07T14:12:48Z"
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"myresolver\":{\"acme\":{\"email\":\"postmaster@domain.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"web\"}}}}}"
traefik    | time="2020-09-14T09:55:35Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Start TCP Server" entryPointName=web
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Start TCP Server" entryPointName=websecure
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Starting provider *acme.Provider {\"email\":\"postmaster@domain.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"web\"},\"ResolverName\":\"myresolver\",\"store\":{},\"ChallengeStore\":{}}"
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Testing certificate renew..." providerName=myresolver.acme
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}"
traefik    | time="2020-09-14T09:55:35Z" level=info msg="Starting provider *traefik.Provider {}"
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Configuration received from provider myresolver.acme: {\"http\":{},\"tls\":{}}" providerName=myresolver.acme
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}}},\"tcp\":{},\"tls\":{}}" providerName=internal
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Adding certificate for domain(s) whoami.domain.com"
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="No default certificate, generating one"
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Provider connection established with docker 19.03.12 (API 1.40)" providerName=docker
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Filtering disabled container" providerName=docker container=traefik-traefik-be2c5bde86d9bb8298d172a50dba821eacab9670af9680d8186e0c1374dde553
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"whoami\":{\"entryPoints\":[\"websecure\"],\"service\":\"whoami-traefik\",\"rule\":\"Host(`whoami.domain.com`)\",\"tls\":{\"certResolver\":\"myresolver\"}}},\"services\":{\"whoami-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.19.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="Adding certificate for domain(s) whoami.domain.com"
traefik    | time="2020-09-14T09:55:35Z" level=debug msg="No default certificate, generating one"
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Adding certificate for domain(s) whoami.domain.com"
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="No default certificate, generating one"
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=pipelining middlewareType=Pipelining serviceName=whoami-traefik routerName=whoami@docker
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Creating load-balancer" routerName=whoami@docker entryPointName=websecure serviceName=whoami-traefik
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Creating server 0 http://172.19.0.2:80" routerName=whoami@docker entryPointName=websecure serviceName=whoami-traefik serverName=0
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Added outgoing tracing middleware whoami-traefik" entryPointName=websecure routerName=whoami@docker middlewareName=tracing middlewareType=TracingForwarder
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Try to challenge certificate for domain [whoami.domain.com] found in HostSNI rule" providerName=myresolver.acme routerName=whoami@docker rule="Host(`whoami.domain.com`)"
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="Looking for provided certificate(s) to validate [\"whoami.domain.com\"]..." routerName=whoami@docker rule="Host(`whoami.domain.com`)" providerName=myresolver.acme
traefik    | time="2020-09-14T09:55:36Z" level=debug msg="No ACME certificate generation required for domains [\"whoami.domain.com\"]." rule="Host(`whoami.domain.com`)" providerName=myresolver.acme routerName=whoami@docker
```
