### ISSUE TITLE
Allow multiple certificates on a single entrypoint when trying to use TLS?

### ISSUE THREAD

**Issue by Wicaeed** [containous/traefik#747]
I've read through the docs and most everything I saw references the traefik.toml configuration file.

I'm trying to do this a slightly different way, by running the default docker image and then running a command to configure traefik:

```
version: '2'
services:
  traefik:
        image: traefik
        command: --web --docker --docker.domain=docker.localhost --docker.watch --logLevel=DEBUG --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS:tls/star_internaldomain_com.crt,tls/star_internaldomain_com.key TLS:tls/star_short_dom.crt,tls/star_short_dom.key' --defaultEntryPoints='http,https'
        network_mode: "host"
        ports:
           - "80:80"
           - "443:443"
           - "8080:8080"
        volumes:
           - /var/run/docker.sock:/var/run/docker.sock
           - /dev/null:/traefik.toml
           - ./tls:/tls
```

I don't get any error messages, however the config shows that only one certificate loaded:

```
traefik_1  | time="2016-10-19T01:05:38Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":{\"EntryPoint\":\"https\",\"Regex\":\"\",\"Replacement\":\"\"}},\"https\":{\"Network\":\"\",\"Address\":\":443\",\"TLS\":{\"Certificates\":[{\"CertFile\":\"tls/star_internaldomain_com.crt\",\"KeyFile\":\"tls/star_internaldomain_com.key\"}]},\"Redirect\":null}},\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"Retry\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"docker.localhost\",\"TLS\":null},\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null}"
```

What would be the proper format to use to load more than a single certificate on an entrypoint, or am I running into some sort of bug?

Thanks!
