### ISSUE TITLE
Traefik Timeout while creating Let's Encrypt client

### ISSUE THREAD

**Issue by thaume** [containous/traefik#750]
Hello there,

While creating a Traefik LB in a Kubernetes cluster, I got this error :

```shell
time="2016-10-19T14:49:50Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}"
time="2016-10-19T14:49:50Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4201b57a0 Redirect:<nil> Auth:<nil> Compress:false}"
time="2016-10-19T14:49:50Z" level=info msg="Starting server on :80"
time="2016-10-19T14:49:52Z" level=info msg="Generating ACME Account..."
time="2016-10-19T14:50:03Z" level=info msg=buildACMEClient...
time="2016-10-19T14:50:03Z" level=debug msg="Building ACME client..."
time="2016-10-19T14:50:13Z" level=error msg="Error creating TLS config get directory at 'https://acme-staging.api.letsencrypt.org/directory': failed to get \"https://acme-staging.api.letsencrypt.org/directory\": Get https://acme-staging.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-10-19T14:50:13Z" level=fatal msg="Error preparing server: get directory at 'https://acme-staging.api.letsencrypt.org/directory': failed to get \"https://acme-staging.api.letsencrypt.org/directory\": Get https://acme-staging.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

and my conf file (more or less the default one) :

```toml
    # traefik.toml
    graceTimeOut = 60
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
    [acme]
    email = "tom@blaaast.co"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "domain.com"
    sans = ["sub.domain.com"]
```

Has anybody hit this problem ? Is it Kubernetes related ? Or do I have to setup a timeout duration somewhere ? 

Thanks :)

**Comment by dddpaul** [comment]
I have  the same trouble with Traefik in Docker 1.12 Swarm mode cluster.

**Comment by emilevauge** [comment]
Strange, it seems traefik cannot connect to let's encrypt staging endpoint...
Can you curl the url `https://acme-staging.api.letsencrypt.org/directory` from within your clusters?

**Comment by dddpaul** [comment]
It's kinda related to swarm-scoped overlay networks. If I use plain old "docker run" then everything is OK.

```
docker run \
--name traefik \
--publish 80:80 --publish 443:443 --publish 8080:8080 \
--volume /var/tmp:/etc/traefik/acme \
traefik:v1.1.0-rc2 \
--entryPoints='Name:http Address::80 Redirect.EntryPoint:https' \
--entryPoints='Name:https Address::443 TLS' \
--acme.entryPoint=https \
--acme.email=my@email.com \
--acme.storage=/etc/traefik/acme/acme.json \
--acme.domains=my.domain.com \
--logLevel=DEBUG \
--web

time="2016-10-21T13:16:13Z" level=info msg="Loading ACME Account..."
time="2016-10-21T13:16:13Z" level=info msg="Loaded ACME config from store /etc/traefik/acme/acme.json"
time="2016-10-21T13:16:13Z" level=info msg=buildACMEClient...
time="2016-10-21T13:16:13Z" level=debug msg="Building ACME client..."
time="2016-10-21T13:16:13Z" level=info msg=AgreeToTOS...
```

But if I start traefik as shiny and freshy docker service in Swarm cluster then it cannot connect to letsencrypt servers:

```
docker service create \
--name traefik \
--publish 80:80 --publish 443:443 --publish 8080:8080 \
--mount type=bind,source=/var/tmp,target=/etc/traefik/acme \
--network traefik-net \
traefik:v1.1.0-rc2 \
--entryPoints='Name:http Address::80 Redirect.EntryPoint:https' \
--entryPoints='Name:https Address::443 TLS' \
--acme.entryPoint=https \
--acme.email=my@email.com \
--acme.storage=/etc/traefik/acme/acme.json \
--acme.domains=my.domain.com \
--logLevel=DEBUG \
--web

time="2016-10-21T13:11:26Z" level=debug msg="Building ACME client..."
time="2016-10-21T13:11:36Z" level=error msg="Error creating TLS config get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-10-21T13:11:36Z" level=fatal msg="Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

Network is created as `docker network create --driver=overlay traefik-net`.

**Comment by thaume** [comment]
@emilevauge the curl command is working nicely from bash

![screen shot 2016-10-21 at 15 26 02](https://cloud.githubusercontent.com/assets/1096014/19599913/ed5f9884-97a2-11e6-9dc7-f57955e47dcb.png)

From what @dddpaul experienced too, it surely looks like a Docker/Kubernetes networking error. I'll open an issue there too

**Comment by dddpaul** [comment]
It's not a bug, just firewall issue in my case. I used `--iptables=false` option for docker daemon and some custom iptables rules for proper masquerading and other things.

When I reninitialize my cluster without custom iptables rules and without `--iptables=false` option I have no problem with traefik & letsencrypt. 

Also, traefik & letsencrypt runs fine over [Miniswarm](https://github.com/aelsabbahy/miniswarm).

So, @thaume, maybe it's a firewall issue in your case too?

**Comment by thaume** [comment]
@dddpaul that sounds right ! I'll try to disable/whitelist the firewall during the container creation. I'll keep you posted

**Comment by j0hnsmith** [comment]
I saw this problem when doing some local testing on a docker-machine vagrant box so I thought I'd try on a fresh Digital Ocean machine, the problem doesn't go away, `DOCKER_OPTS` is empty. Here's everything to recreate.


```bash
docker-machine create --driver digitalocean --digitalocean-access-token=${DO_TOKEN} --digitalocean-region=nyc1 --digitalocean-size=2gb traefiktest
docker-machine scp traefik.toml /root/traefik.toml
docker-compose -p traefiktest up
```

```toml
# traefik.toml
################################################################
# Global configuration
################################################################

# Timeout in seconds.
# Duration to give active requests a chance to finish during hot-reloads
#
# Optional
# Default: 10
#
# graceTimeOut = 10

# Enable debug mode
#
# Optional
# Default: false
#
 debug = true

# Periodically check if a new version has been released
#
# Optional
# Default: true
#
# checkNewVersion = false

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
# traefikLogsFile = "log/traefik.log"

# Access logs file
#
# Optional
#
# accessLogsFile = "log/access.log"

# Log level
#
# Optional
# Default: "ERROR"
# Accepted values, in order of severity: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# Messages at and above the selected level will be logged.
#
# logLevel = "ERROR"

# Backends throttle duration: minimum duration in seconds between 2 events from providers
# before applying a new configuration. It avoids unnecessary reloads if multiples events
# are sent in a short amount of time.
#
# Optional
# Default: "2"
#
# ProvidersThrottleDuration = "5"

# If non-zero, controls the maximum idle (keep-alive) to keep per-host.  If zero, DefaultMaxIdleConnsPerHost is used.
# If you encounter 'too many open files' errors, you can either change this value, or change `ulimit` value.
#
# Optional
# Default: http.DefaultMaxIdleConnsPerHost
#
# MaxIdleConnsPerHost = 200

# If set to true invalid SSL certificates are accepted for backends.
# Note: This disables detection of man-in-the-middle attacks so should only be used on secure backend networks.
# Optional
# Default: false
#
# InsecureSkipVerify = true

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]


[acme]
email = "foo@bar.com"
storageFile = "acme.json"
onDemand = true
## Comment out for production environment!
caServer = "https://acme-staging.api.letsencrypt.org/directory"
entryPoint = "https"

[[acme.domains]]
  main = "example.com"



################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#
# Optional
#
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "docker.localhost"

# Enable watch docker changes
#
# Optional
#
watch = false

# Override default configuration template. For advanced users :)
#
# Optional
#
# filename = "docker.tmpl"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
exposedbydefault = false

# Use the IP address from the binded port instead of the inner network one. For specific use-case :)

#
# Optional
# Default: false
#
usebindportip = true

# Use Swarm Mode services as data provider
#
# Optional
# Default: false
#
swarmmode = false


# Enable docker TLS connection
#
#  [docker.tls]
#  ca = "/etc/ssl/ca.crt"
#  cert = "/etc/ssl/docker.crt"
#  key = "/etc/ssl/docker.key"
#  insecureskipverify = true
```

```yaml
# docker-compose.yml
version: '2'

services:
    traefik:
        image: traefik:v1.1.1
        command: --web --logLevel=DEBUG
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/traefik.toml:/traefik.toml
            - /root/acme.json:/acme.json

    nginx:
        image: nginx:1.11.6-alpine
        expose:
            - "80"
        volumes:
            - /tmp:/usr/share/nginx/html
        labels:
            - "traefik.enable=true"
            - "traefik.backend=nginx"
            - "traefik.port=80"
            - "traefik.frontend.rule=PathPrefix:/"
```

```
# output
Creating network "test_default" with the default driver
Creating test_nginx_1
Creating test_traefik_1
Attaching to test_nginx_1, test_traefik_1
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Traefik version v1.1.1 built on 2016-11-29_03:32:44PM" 
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Using TOML configuration file //traefik.toml" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":true,\"CheckNewVersion\":true,\"AccessLogsFile\":\$\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compr$ss\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":{\"Email\":\"foo@bar.com\",\"Domains\":[{\"Main\":\"example.com\",\"SANs\":null}],\"Storage\":\"\"$\"StorageFile\":\"acme.json\",\"OnDemand\":true,\"OnHostRule\":true,\"CAServer\":\"https://acme-staging.api.letsencrypt.org/directory\",\"EntryPoint\":\"https\"},\"Def$ultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":{\"Watch\":fals$,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"docker.localhost\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindP$rtIP\":true,\"SwarmMode\":false},\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"$onsul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null}" 
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}" 
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Starting provider *provider.Docker {\"Watch\":false,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix$///var/run/docker.sock\",\"Domain\":\"docker.localhost\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":true,\"SwarmMode\":false}" 
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":fal$e,\"Auth\":null}" 
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Starting server on :80" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Docker connection established with docker 1.12.3 (API 1.24)" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Filtering disabled container /test_traefik_1" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Load balancer method '<nil>' for backend backend-nginx: Invalid method, using default. Using default wrr." 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-nginx\":{\"servers\":{\"server-test_ngin
x_1\":{\"url\":\"http://172.18.0.2:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-PathPrefix\":{\"entryPoints\":[\"http\"],\"back
end\":\"backend-nginx\",\"routes\":{\"route-frontend-PathPrefix\":{\"rule\":\"PathPrefix:/\"}},\"passHostHeader\":true,\"priority\":0}}}" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Last docker config received more than 2s, OK" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Creating frontend frontend-PathPrefix" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Wiring frontend frontend-PathPrefix to entryPoint http" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Creating route route-frontend-PathPrefix PathPrefix:/" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Creating backend backend-nginx" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Creating load-balancer wrr" 
traefik_1  | time="2016-12-12T06:38:12Z" level=debug msg="Creating server server-test_nginx_1 at http://172.18.0.2:80 with weight 0" 
traefik_1  | time="2016-12-12T06:38:12Z" level=info msg="Server configuration reloaded on :80" 
traefik_1  | time="2016-12-12T06:38:12Z" level=error msg="Error getting ACME client: ACME client still not built, retrying in 633.231211ms" 
traefik_1  | time="2016-12-12T06:38:13Z" level=error msg="Error getting ACME client: ACME client still not built, retrying in 432.335324ms" 
traefik_1  | time="2016-12-12T06:38:13Z" level=error msg="Error getting ACME client: ACME client still not built, retrying in 1.627746117s" 
...
```

This works ok.
```bash
curl -i https://acme-staging.api.letsencrypt.org/directory

HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 372
Boulder-Request-Id: q6kRFg9EdchMSrLpdN1fkK32mP_ZpDBx4U6uA8McEQg
Replay-Nonce: i44dLh926jSJv2sX6TG760E2klTxTdNOFlBmNzKe4Ng
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 12 Dec 2016 06:58:05 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 12 Dec 2016 06:58:05 GMT
Connection: keep-alive

{
  "key-change": "https://acme-staging.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-staging.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-staging.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-staging.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-staging.api.letsencrypt.org/acme/revoke-cert"
}
```

I also pulled and ran `ubuntu:16.04`, I could `curl -i https://acme-staging.api.letsencrypt.org/directory` ok so it is possible to hit that url from inside a docker container.
