### ISSUE TITLE
Docker swarm mode, Traefik on manager node only ?

### ISSUE THREAD

**Issue by tlvenn** [containous/traefik#766]
I was reading the updated doc on how to deploy Traefik with Docker 1.12 and swarm mode when I saw that Traefik need to be deployed only on manager nodes...

For me, it's really weird to deploy a LB on manager nodes, those nodes should not deal with data plane, they should operate the control plane and they are limited to 5 in any given cluster.

Is there a current limitation with worker that forces Traefik to run on a manager ? Has an issue been created at Docker to solve this because unless I am missing something, I dont really see how that can scale at all and it seems dangerous to colocate the LB with the ochestrator...

**Comment by programster** [comment]
@tlvenn I am _guessing_ that it has to run on a manager because those nodes are responsible for the routing of requests and directing traffic. 

I can see how that can be a concern for scaling, but don't forget that the swarm docs state that you can have up to 7 managers. With the limited testing I have done, I have found that running with 5 managers works a lot better than any number lower than that (at least for redundancy and automatic failover). I haven't experimented with running the full 7 to see if this starts to cause problems. Nor have I experimeted with running traefik on more than one manager node at a time. Is this possible?

**Comment by ralphtheninja** [comment]
> I can see how that can be a concern for scaling, but don't forget that the swarm docs state that you can have up to 7 managers. With the limited testing I have done, I have found that running with 5 managers works a lot better than any number lower than that (at least for redundancy and automatic failover). I haven't experimented with running the full 7 to see if this starts to cause problems. Nor have I experimeted with running traefik on more than one manager node at a time. Is this possible?

I haven't either but want to try this setup. It sounds to me that it should work fine if traefik by e.g. `docker service create ..`. Would love to get some feedback from others.

**Comment by programster** [comment]
Well I just tried deploying traefik using [a tutorial I made a few days ago](http://blog.programster.org/using-traefik-with-docker-swarm-for-deploying-web-applications/), but this time with a scale of 3 and whoami1 with a scale of 6 and had no issues from my "light testing" (going there  in my browser). I also noticed that I get the site correctly even if I hit the leader that is _not_ running the traefik proxy.

**Comment by tlvenn** [comment]
@programster I could be wrong but I dont think it's related with traffic management but it might be related with service placement. My understanding is Traefik needs to know where a given service has been deployed and be updated of any change.

Yep that's it, looking a bit deeper, there is currently no support for swarm events within the docker event stream, this is tracked with https://github.com/docker/docker/issues/23827

However this does not explain why we simply dont just poll the data for now which is availaible with the remote API on any node that is part of the swarm. Polling while not ideal seems to be better than forcing placement of Traefik on managers imho.

And actually looking at the code, even though I dont know GO much, it seems like it's already polling for the data...

@diegofernandes Can you shed some light on the matter please ?

**Comment by vdemeester** [comment]
Træfik has to run on a manager node because it needs access to the swarm mode API — and this API is only available on a manager as of now. Even with swarm events it would probably be the same as swarm events would probably only be available on manager nodes :sweat_smile:.

The idea would be more something like what's proposed in https://github.com/docker/docker/pull/26331 (some introspection and some limitation) :angel: .

**Comment by tlvenn** [comment]
Thanks for the clarification @vdemeester.

Wouldn't it be somewhat simple to have a very light traefik-swarm-agent running on the manager(s) and exposing the needed information over a websocket ?

**Comment by tlvenn** [comment]
Btw, what is missing from the  Remote API which is available on all node of the swarm ?>https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/list-tasks

It seems like polling the tasks and resolving the services would be all that is needed.

**Comment by vdemeester** [comment]
@tlvenn 

> Wouldn't it be somewhat simple to have a very light traefik-swarm-agent running on the manager(s) and exposing the needed information over a websocket ?

It could be done I think. The current implementation is… really simple and basic and is definitely subject to enhancements in the future :stuck_out_tongue_closed_eyes: 

> Btw, what is missing from the Remote API which is available on all node of the swarm ?>https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/list-tasks
> 
> It seems like polling the tasks and resolving the services would be all that is needed.

`/tasks` is a swarm mode endpoint, and thus, only available on manager. Currently we are polling the `/service` endpoint (which is also a swarm mode endpoint) and letting the swarm mode internal load balancer doing its thing… As said above, this is simple and subject to enhancement/options.

**Comment by tlvenn** [comment]
@programster actually we could do something even simpler by running a proxy on the manager(s) on a dedicated network shared only with Traefik for security purpose. The only thing we would have to do/change is to expose with a setting the host that Traefik use to query the api and default to the localhost.

**Comment by tlvenn** [comment]
Looking at the code the endpoint is defined by `defaultDocker.Endpoint` and is already exposed if I am not wrong so it looks like nothing is really stoping the end user to use this approach.

**Comment by tlvenn** [comment]
For those interested, I created a simple docker image using caddy to proxy over the docker unix socket so you can do that:

```
docker network create --opt encrypted --driver overlay meta

docker service create --mode global --network meta --name docker-api-proxy \
--constraint 'node.role == manager' \
--mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock,ro=true \
tlvenn/docker-api-proxy

docker service create \
--name traefik \
--constraint 'node.role==worker' \
--publish 80:80 --publish 8080:8080 \
--network traefik-net \
--network meta \
traefik \
--docker \
--docker.swarmmode \
--docker.endpoint=http://docker-api-proxy \
--docker.domain=traefik \
--docker.watch \
--web
```
 It essentially create a dedicated secure network for the proxy and traefik to interact so that other containers cant suddenly talk to the manager remote API over http. The proxy is placed on all managers you have in your cluster and docker dns will round robin them transparently.

Then we simply start traefik service and we add our meta network and define the docker endpoint to reference our proxy.

**Comment by bvis** [comment]
@tlvenn thanks for your solution. This strategy seems to be right. ;)

On other hand, do you have your source code somewhere? I've seen it's not built automatically in docker hub.

**Comment by tlvenn** [comment]
@bvis I will publish the source code on github tomorrow, I want to check nginx instead of caddy since it looks like it supports unix socket as well and should result in a smaller image.

In any case, will report back fairly soon.

**Comment by pascalandy** [comment]
Looking for your source. This is great!

**Comment by psi-4ward** [comment]
@tlvenn Waiting for your source ;)

**Comment by barhun** [comment]
I've just tried to come up with a good way to scale out traefik and the best way seems to be using **socat** for creating a bidirectional byte stream between a tcp socket and the docker unix socket. Here is how I got it to work:

```bash
docker service create --name docker-proxy \
    --network proxy \
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
    --constraint 'node.role==manager' \
    rancher/socat-docker


docker service create --name traefik \
    -p 80:80 \
    -p 8080:8080 \
    --network proxy \
    --network traefik \
    traefik \
    --docker \
    --docker.swarmmode \
    --docker.endpoint=tcp://docker-proxy:2375 \
    --web
```

Docker Image: https://hub.docker.com/r/rancher/socat-docker
Source Repo: https://github.com/rancher/socat-test

**Comment by tlvenn** [comment]
Ya good idea @barhun , `socat` should be even lighter than nginx to proxy the docker unix socket over http.

**Comment by ralphtheninja** [comment]
@barhun Help me walk through this. If I understand this correctly, is the idea here to run multiple `rancher/socat-docker` (one per manager node?) and only one `traefik` instance?

**Comment by ralphtheninja** [comment]
@tlvenn @barhun what's the difference to your approaches?

**Comment by tlvenn** [comment]
It's the same thing, socat allows you to expose the docker unix socket over an http port, pretty much the same way nginx can do but socat is a much simpler process.

**Comment by bvis** [comment]
Perfect, it works like charm. Thank you all.

The good point here is that as bigger the cluster gets the better is this approach, because you can scale the traefik tasks independently from the number of managers. And you can save some heavy work from the managers.

Do you know what would happen if the proxy fails during some time?

- Does the traefik/router services work? Of course without catching events during this time.
- When the proxy goes up again, is the traefik able to restore the desired status of the system? as far as I know it should, because it checks for the status of the services continuously.

**Comment by barhun** [comment]
The difference between the solutions is that mine is using **socat** to make the Docker API remotely accessible whereas @tlvenn initially suggested to use a reverse proxy server such as **caddy**, **nginx** or **haproxy** to achieve the same result. Though all these reverse proxy solutions require configuration files to be added to the Docker image, it seems not quite a big challenge since an image will only be rebuilt occassionally and the configuration files will likely remain unchanged. Yet, *socat* only needs command-line arguments to start streaming bytes between a TCP socket and the Docker Unix socket. It is also, not surprisingly, a much lighter solution than a reverse proxy as what it does in this case is merely build a bidirectional stream from the TCP port _2375_ to the Unix socket _/var/run/docker.sock_ for an incoming connection.

Why do we need the Docker API to be remotely accessible? Because _Træfɪk_ watches Docker Swarm events and/or polls Docker Swarm services frequently - not sure if solely one (and which) is done or if both are performed for higher consistency - to automatically reconfigure itself and this process can only succeed via the Docker API over a Docker Swarm manager since the cluster state is only available to and managed by manager nodes. Thus we make the Docker API remotely accessible in order to make it available to _Træfɪk_ instances that must no more necessarily run only on manager nodes but can also run on any node which is part of the Docker Swarm cluster to enable further scalability.

We can launch as many _Træfɪk_ containers as we want and they will be able to talk to the managers via the _docker-proxy_ service which can also be scaled out to more than one instances or can be configured as a global service with the constraint `node.role==manager`  in which case one instance per manager will be scheduled. I think one is enough for all because not much traffic goes through. Since the Docker Swarm mode services are controlled and checked for status in a self-healing loop, a new instance of the _docker-proxy_ service will be scheduled if the only container belonging to the _docker-proxy_ service stops due to an internal failure or because of the manager on which it runs having gone down.

**Comment by barhun** [comment]
@bvis

> Do you know what would happen if the proxy fails during some time?
>- Does the traefik/router services work? Of course without catching events during this time.

I am not aware of the internals but Træfɪk should reconfigure only after a successful retrieval of services' state from the Docker Swarm API. It appears to me absolute nonsense to lose the already available information in case of interruptions.


> - When the proxy goes up again, is the traefik able to restore the desired status of the system? as far as I know it should, because it checks for the status of the services continuously.

Again, it is a better choice to configure frontend and backend rules according to the latest known facts without ever remembering any historical details even if not designed so.

**Comment by ralphtheninja** [comment]
@barhun Thanks for the explanation! A bit off topic, but how would you configure DNS to work well with multiple manager nodes? Multiple A records pointing to respective manager? I really like the traefik approach but have problems visualizing how _one_ A record can be used when scaling out managers and/or instances of traefik (or the docker-proxy in this case).

**Comment by barhun** [comment]
@ralphtheninja

If your nodes are behind an IaaS load balancing service such as AWS Elastic Load Balancer or Azure Load Balancer, then it should be enough to have its IP address set as the DNS record value and configure it with the backends you want your traffic forwarded to. If not, you can set multiple IP addresses per an A record. This last technique is called RR (round robin) DNS and used as a way of load distribution, load balancing and fault tolerance by returning different IP addresses for DNS queries.

https://support.cloudflare.com/hc/en-us/articles/200168916-Can-I-use-round-robin-DNS-entries-

**Comment by Yajo** [comment]
My 2 cents: you can use [`tecnativa/docker-socket-proxy`](https://hub.docker.com/r/tecnativa/docker-socket-proxy/), which includes some security enhacements to reduce Traefik's attack surface.

Just deploy this:

```yaml
version: "3.1"

services:
    proxy:
        image: traefik:1.2-alpine
        networks:
            shared:
            private:
        volumes:
            - acme:/etc/traefik/acme:rw,Z
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - dockersocket
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == worker
        tty: true
        command:
            # Use your favourite settings here, but add:
            - --Docker
            - --Docker.EndPoint=http://dockersocket:2375
            - --Docker.ExposedByDefault=false
            - --Docker.SwarmMode
            - --Docker.Watch

    dockersocket:
        image: tecnativa/docker-socket-proxy
        privileged: true
        networks:
            private:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            CONTAINERS: 1
            NETWORKS: 1
            SERVICES: 1
            SWARM: 1
            TASKS: 1
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager

networks:
    shared:
        driver_opts:
            encrypted: 1

    private:
        driver_opts:
            encrypted: 1
```

And attach your microservices to `inverseproxy_shared` network.

**Comment by vdemeester** [comment]
Also note that, at some point docker/docker#26331 could help 👼

**Comment by pascalandy** [comment]
@Yajo Thank you so much for having shared your compose v3 file. I got it now :)

**Comment by pascalandy** [comment]
Here is the complete solution folks! Enjoy :)

https://github.com/pascalandy/docker-stack-this/tree/master/traefik-socat

**Comment by Yajo** [comment]
Link down.

**Comment by pascalandy** [comment]
Updated :)

**Comment by cirocosta** [comment]
Great news! https://github.com/moby/moby/pull/32421 (support cluster events #32421) got in 👍

**Comment by diegofernandes** [comment]
Wow nice

Em sex, 26 de mai de 2017 12:41, Ciro S. Costa <notifications@github.com>
escreveu:

**Comment by baluubas** [comment]
Does the docker backend still need work to listen to these events on a worker node? Or can we make this work right now, given a recent docker version?

**Comment by bvis** [comment]
@baluubas You don't need to make traefik run in a manager node, but you need to allow traefik get the cluster events, which are only available in manager nodes. This can be done with a proxy that exposes the docker cluster events in a TCP service. You can check how it works with the next yaml file:

```
version: "3.2"

networks:
  traefik-pub:
    external: true

volumes:
  traefik-pub:
    driver: ${VOLUME_DRIVER}

services:
  docker-proxy:
    image: rancher/socat-docker
    networks:
      - traefik-pub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.10'
          memory: 8M
        reservations:
          cpus: '0.10'
          memory: 8M

  traefik-pub:
    image: traefik:v1.3.2-alpine
    networks:
      - traefik-pub
    ports:
      - mode: ingress
        target: 80
        published: 80
      - mode: ingress
        target: 443
        published: 443
      - "8080:8080"
    volumes:
      - traefik-pub:/etc/traefik/acme
    command: --docker \
      --docker.swarmmode \
      --docker.endpoint=tcp://docker-proxy:2375 \
      --docker.domain='${CLUSTER_PUBLIC_DOMAIN}' \
      --docker.watch \
      --entryPoints='Name:https Address::443 TLS' \
      --entryPoints='Name:http Address::80' \
      --acme.entrypoint=https \
      --acme=true \
      --acme.domains='${CLUSTER_PUBLIC_DOMAIN}' \
      --acme.email=${ACME_EMAIL} \
      --acme.ondemand=true \
      --acme.onhostrule=true \
      --acme.storage=/etc/traefik/acme/acme.json \
      --web
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 100M
```
