### ISSUE TITLE
Consul KV store acl tokens ?

### ISSUE THREAD

**Issue by tkald** [containous/traefik#767]
My consul KV store is protected with **acl_token**  and **encrypt** key.

Does treafik support using those? Can't find this part in manual.

So far only getting errors connecting consul KV store:
Leadership election error failed to acquire lock: Unexpected response code: 403 (Permission denied), retrying in 469.561715ms

**Comment by cyrilgdn** [comment]
Same problem :(

I tried to look if it's easy to implement but traefik seems to use [libkv](https://github.com/docker/libkv) for consul and libkv does not support ACL token yet....(see https://github.com/docker/libkv/issues/29)

**Comment by cyrilgdn** [comment]
Finally it's possible to pass a consul token with the environment variable CONSUL_HTTP_TOKEN because both traefik (for consulcatalog provider) and libkv (for consul provider) used [hashicorp api](https://github.com/hashicorp/consul/blob/master/api/) which supports this env var !

**Comment by mcapuccini** [comment]
@cyrilgdn I guess the same applies for `CONSUL_HTTP_AUTH`, right?

**Comment by cyrilgdn** [comment]
@mcapuccini From what I see in the code, yes.

**Comment by mcapuccini** [comment]
@cyrilgdn I tried and it doesn't seem to have any effect for some reason. Could you point me to the code please?

If you are familiar with Kubernetes, that's what I did:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      hostNetwork: true # workaround
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.1.2-alpine
        name: traefik-ingress-lb
        imagePullPolicy: Always
        env:
        - name: CONSUL_HTTP_AUTH
          value: "user:xxxx"
        - name: CONSUL_HTTP_SSL
          value: "true"
        volumeMounts:
          - mountPath: /etc/traefik
            name: traefik-volume
            readOnly: false
        resources:
          requests:
            cpu: 1
            memory: 1G
        args:
        - --web
        - --kubernetes
        - --configFile=/etc/traefik/traefik.toml
        - --logLevel=DEBUG
      volumes:
        - hostPath:
            path: /etc/traefik
          name: traefik-volume
      nodeSelector:
        role: edge
```

**Comment by mcapuccini** [comment]
@cyrilgdn this may be simpler to reproduce:

```bash
docker run -v $PWD:/conf -e "CONSUL_HTTP_AUTH=user:test" -e "CONSUL_HTTP_SSL=true" traefik:1.1.2-alpine --configFile=/conf/traefik.toml
2017/03/14 09:42:58 Error loading configuration: Unexpected response code: 401
```

## traefik.toml
```toml
[consul]
endpoint = "consul.mydomain.com"
watch = true
prefix = "traefik"
```
