### ISSUE TITLE
traefik:v1.1.0-rc2 with rabbitmq:3-management not working fully

### ISSUE THREAD

**Issue by LazGit** [containous/traefik#778]
I'm using traefik:v1.1.0-rc2 with rabbitmq-management using this rule :

```toml
[backends]
  [backends.rabbitmq]
    [backends.rabbitmq.LoadBalancer]
      method = "drr"
      sticky = true
    [backends.rabbitmq.servers.1]
    url = "http://x.x.x.x:15672"
    [backends.rabbitmq.servers.2]
    url = "http://x.x.x.x:15672"
    [backends.rabbitmq.servers.3]
    url = "http://x.x.x.:15672"

[frontends]
  backend = "rabbitmq"
    [frontends.rabbitmq.routes.rabbitmq]
    rule = "PathPrefixStrip: /rabbitmq"
```

When i'm using the rabbitmq manager like this url : http://127.0.0.1/rabbitmq/#/queues/%2F/task.begin
The access.log file show this : GET /api/queues///task.begin HTTP/1.1" 404

I think that the /%2F/ is replaced by a simple /. A mode like 'ProxyPass http://localhost:15672/ nocanon' is available ?

Thanks.
