### ISSUE TITLE
HTTP2 - configuration

### ISSUE THREAD

**Issue by f3l1x** [containous/traefik#790]
Could you please help me to setup up http2? Is there any special configuration for that? This tester (https://tools.keycdn.com/http2-test) told me it's not http2. Thank you for helping me.

**Comment by emilevauge** [comment]
You need to enable TLS to get http2 :)

**Comment by f3l1x** [comment]
I'm using ACME for getting SSL certificates, like this:

```
[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
```

Does it need any other setting?

**Comment by f3l1x** [comment]
ping @emilevauge

**Comment by trecloux** [comment]
@f3l1x Did you run the test using http or https ?

**Comment by f3l1x** [comment]
@trecloux Both. Any other tips?

**Comment by trecloux** [comment]
@f3l1x can you share your configuration ?

**Comment by f3l1x** [comment]
```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]

email = "email"
storage = "/path/to/acme.json"
entryPoint = "https"

[[acme.domains]]
 main = "redmine.domain.tld"
 sans = ["redmine.domain.tld"]

[file]

[backends]
  [backends.redmine]
    [backends.redmine.servers.node1]
      url = "http://{IP}"

[frontends]
  [frontends.redmine]
  backend = "redmine"
  passHostHeader = true
    [frontends.redmine.routes.entry]
    rule = "Host: redmine.domain.tld"
```
