### ISSUE TITLE
Question: Wildcard Host for Kubernetes Ingress

### ISSUE THREAD

**Issue by jwaldrip** [containous/traefik#792]
How do you create a wildcard host using kubernetes ingress? The following format does not work:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 3-0-proxy
spec:
  rules:
  - host: '*.mydomain.com'
    http:
      paths:
      - backend:
          serviceName: service-3-0-proxy
          servicePort: 80
        path: /
```
