### ISSUE TITLE
Buffering middleware breaks `chunked` encoded requests

### ISSUE THREAD

**Issue by vojtad** [containous/traefik#7930]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have deployed server from [discourse/prometheus_exporter](https://github.com/discourse/prometheus_exporter) behind Traefik.
Its client uses `Transfer-Encoding: chunked` to stream data to server. Each chunk is a valid JSON object.
Server reads these chunks, decodes JSON objects and process them.

### What did you expect to see?

We expected server to correctly parse JSON objects from each chunk sent by a client.

### What did you see instead?

Client requests are somehow buffered by Traefik and chunks are merged together in bigger chunks. This results in an invalid JSON since multiple JSON objects are simply concatenated as strings.
Server is not able to parse requests sent by a client when it is behind Traefik.

I believe this is could be due to Buffering middleware. Is there any way to alter this behaviour and pass chunks as they were originally sent to Traefik?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.5
Codename:     livarot
Go version:   go1.15.8
Built:        2021-02-18T17:21:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We run Traefik using docker-compose with docker provider set to discover services.

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "admin@example.com"
  storage = "/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  exposedByDefault = false
  network = "traefik"

[providers.file]
  filename = "/traefik_dynamic.toml"
```
