### ISSUE TITLE
Redirect to Backend Path

### ISSUE THREAD

**Issue by JaronrH** [containous/traefik#809]
I would like to be able to redirect to a specific path on the backend.  For example, I have a Docker running  NodeRed with the Dashboard add-in.  The dynamic docker will find the NodeRed flow editor but I would like another host (say, noderedui.docker.local) to redirect specifically to the /ui path of node red.

Specifically, node red is:  http://172.17.0.2:1880  I would like to have a host point to http://172.17.0.2:1880/ui

I tried the following file endpoint as an experiment but Traefik only went to http://172.17.0.2:1880 instead of http://172.17.0.2:1880/ui

```toml
[backends]
  [backends.noderedui]
    [backends.noderedui.servers.server1]
    url = "http://172.17.0.2:1880/ui"

[frontends]
  [frontends.nodereduife]
  backend = "noderedui"
  passHostHeader = true
    [frontends.nodereduife.routes.redui]
    rule = "Host:redui.docker.local"
```

Is this even possible?  Thanks!
