### ISSUE TITLE
cannot connect to docker daemon

### ISSUE THREAD

**Issue by nclundsten** [containous/traefik#813]
Hi, im having an issue, and im not really sure where i should be asking for help, hope the issue tracker is ok...

![image](http://nlundsten.com/caps/7a7fcc.png)

fedora 24, usergroup for docker set up. 

```
build: docker/reverse-proxy
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
  - "80:80"
  - "8080:8080"
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /dev/null:/traefik.toml
```

any insight, or perhaps an irc channel, that might be better for this would be appreciated.

thanks
