### ISSUE TITLE
The UI stops working after a time and have to restart the service.

### ISSUE THREAD

**Issue by ilijamt** [containous/traefik#840]
I keep getting **400 Bad Request: malformed Host header** when I try to access the services. And sometimes they work and sometimes they don't.

```bash
$ curl -H Host:hello.dev.pbp http://dev-node-02.dev.pbp/
400 Bad Request: malformed Host header
404 page not found
```

And sometimes it returns the correct data, if I do a curl on the internal docker IP directly then it works everytime.

### traefik

- v1.0.3
- v1.1.0-rc4

### Docker Image
- dockercloud/hello-world:latest

### Labels:
- traefik.backend = hello-world
- traefik.frontend.rule = Host:hello.dev.pbp
- traefik.port = 80

### config.toml
```toml
[web]
address = ":8080"

[web.statistics]
   RecentErrors = 10

[docker]
endpoint = "tcp://192.168.100.59:2375"
watch = true
swarmmode = true
```
![screenshot from 2016-11-14 13-20-54](https://cloud.githubusercontent.com/assets/1139427/20264726/53e6f19c-aa6d-11e6-8eac-564c73c42712.png)
