### ISSUE TITLE
Kubernetes Ingress support both HTTP and HTTPS from a single Ingress

### ISSUE THREAD

**Issue by pdf** [containous/traefik#8502]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

There are currently some pain points in using the Kubernetes Ingress support regarding TLS. Two relatively small changes would significantly improve the experience of working with Ingress objects backed by Traefik:

~~1. No annotation should be required to enable TLS on the Ingress - this is relatively minor, but if the Ingress specifies a `tls` key in the `spec`, TLS should be enabled without requiring further configuration via annotations. Requiring an annotation to make TLS function results in user confusion when they appear to have a correctly defined Ingress, but receive a 404 upon accessing the TLS port.~~ Split off into #8510 
2. An Ingress that is enabled for TLS/HTTPS should still respond to HTTP requests - rendering HTTP on the Ingress inactive if TLS is enabled is another significant source of user confusion (there are numerous posts floating around with people wondering why their routes appear to be broken), and the requirement to deploy two Ingresses/IngressRoutes with duplicated configuration just to enable standard operation is onerous, even if users are able to determine that's what they're meant to do.

Functional Ingress support is highly desirable, even with the existense of `IngressRoute`, primarily for integration with external tooling that expects, and/or provisions Ingress objects. The current limitations make dealing with external provisioning tools needlessly complex, requiring addtional deployment steps to provision custom objects for fully functional HTTP/HTTPS Ingresses (for `2` in particular).

**Comment by kevinpollet** [comment]
Hello @pdf and thanks for your interest in Traefik,

1. You are right and this could be an enhancement. Feel free to open a new issue to track it independently, it is better to scope issues to only one concern.

2. We are not sure to understand your expectations. The [Ingress specification](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) says that an `Ingress` with a TLS section should be secured. Why should we allow an HTTPS `Ingress` to be accessible through HTTP?

**Comment by pdf** [comment]
> 1. You are right and this could be an enhancement. Feel free to open a new issue to track it independently, it is better to scope issues to only one concern.

Sure, I can split them up.

> 2. We are not sure to understand your expectations. The [Ingress specification](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) says that an `Ingress` with a TLS section should be secured. Why should we allow an HTTPS `Ingress` to be accessible through HTTP?

The spec doesn't specify that the `Ingress` should _not_ also listen for HTTP traffic. Other ingress controllers do this (nginx for example), and a very common use-case is to be allow specifying a middleware that redirects clients requesting HTTP to HTTPS.

To expand, many helm charts, for example, allow generating an Ingress as part of the deployment. If Trafik enabled an Ingress for both HTTP and HTTPS when `tls` was enabled, it would be possible to specify annotations when deploying a chart to enable a redirect middleware for HTTP clients.

Currently, the only way to manage this with Traefik is to either deploy half the required Ingress configuration via the chart (what a mess), or to entirely disable Ingress generation for the deployment, and manually create both a HTTP Ingress/IngressRoute (with the redirection middleware), and a separate HTTPS Ingress/IngressRoute, which is a significant burden over other ingress controllers, and removes the ingress from the deployment, meaning it can't be managed by the helm lifecycle.

**Comment by kevinpollet** [comment]
> The spec doesn't specify that the Ingress should not also listen for HTTP traffic. Other ingress controllers do this (nginx for example), and a very common use-case is to allow specifying a middleware that redirects clients requesting HTTP to HTTPS.

I understand your point but exposing an `Ingress` which is meant to be secured through an `unsecured` route automatically could lead to security issues. Even if the very common use case is to redirect from HTTP to HTTPS we think that this should be an opt-in behaviour that can be enabled through an annotation for example.

> Currently, the only way to manage this with Traefik is to either deploy half the required Ingress configuration via the chart (what a mess), or to entirely disable Ingress generation for the deployment, and manually create both a HTTP Ingress/IngressRoute (with the redirection middleware), and a separate HTTPS Ingress/IngressRoute, which is a significant burden over other ingress controllers, and removes the ingress from the deployment, meaning it can't be managed by the helm lifecycle.

As explained in https://github.com/traefik/traefik/issues/8444 it is possible to specify the TLS configuration at the entrypoint level allowing the configuration of the redirection with a middleware and only one `Ingress`. Is it what you are expecting?

**Comment by pdf** [comment]
What's the verdict on this? I'm willing to invest some time into looking at implementation details, but obviously I don't want to do that if this is unlikely to be accepted.

**Comment by pdf** [comment]
Whilst our preference would be to use Traefik for Ingress, we need to move forward, and since many other ingress controllers support per-ingress HTTPS redirection, we've decided that we must evaluate other options to support this use-case when working with public Helm charts.

As such, I am no longer likely to look at contributing code for this feature, however I'll leave this open as I'm sure other parties would be interested in seeing this at some point.

**Comment by mucsi96** [comment]
Sorry my knowledge on the topic is very limited so my questions might be stupid :)

I am using the following config provided by @jakubhajek and it works perfectly.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  rules:
    - host: whoami.<FIXME>.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-https
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  rules:
    - host: whoami.<FIXME>.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

But there two point I don't understand.

From the browser network I see that the HTTP -> HTTPS redirection is happening in the browser.
This means in case of HTTP ingress why we have to provide a service? As it will be never reached due to redirection caused by middleware.

Also can't the middleware be implemented / used in a way that it can be used for both HTTP and HTTPS entrypoints. Just in case of HTTPS it would do nothing as it detects that it's running already on HTTPS. With that should be possible to use single ingress with no restriction on entrypoint (`web` or `websecure`).

**Comment by genofire** [comment]
Yes, you are correct (normal, you need also a TLS section if you use the certmanager, also an annotation for the issuer).


But your solution is really unusually. Every HelmChart only deployies one Ingress, and the current most common Ingress controller: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-side-https-enforcement-through-redirect use therefore just one annotation (and listen in both default)/

**Comment by ddfreiling** [comment]
Agree with above comment. It's needlessly complex to disable HTTP or redirect to HTTPS for a single ingress.

**Comment by dberardo-com** [comment]
any workaround to deploy on ingress to redirect http to https and listen on both endpoints ? 
so i assume this is not possible at the moment ?

**Comment by switz** [comment]
This does feel rather painful, not only is it added configuration it's also added resources to manage (two ingresses for every service) and makes the whole thing feel rather bloated. It's a common and sane use-case to auto-redirect http traffic to ssl and would be nice to be simply and easily configurable.

**Comment by zlugo** [comment]
Hey folks, sorry for responding to this old issue, but I wanted to check if there are any plans on the ingress-specific HTTPS redirect.

Traefik has clearly evolved since this issue got opened and it feels like the current behavior is already super close to what we'd need.
When creating a minimal ingress like this (for completeness: this would also require a fitting defaultCertificate via config)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: my-app.example.com
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - my-app.example.com
```

it's visible on the Traefik dashboard that two HTTP routers are being created, one on the `web` and one on the `websecure` endpoint.
From what I can see, the only thing still missing here would be to automatically generate a fitting `redirectScheme` middleware and attach it to the router on the `web` entrypoint if a certain annotation (e.g., `traefik.ingress.kubernetes.io/router.tls.redirect: "true"` is present. This would encapsulate the working, but complex/verbose config outlined in https://github.com/traefik/traefik/issues/8502#issuecomment-1242917403.

I don't have deep enough knowledge of the current implementation to judge if that's even possible or violating any current design principles, so I thought I'd share the general idea before trying to provide a PR.
