### ISSUE TITLE
Traefik not loading certificates with duplicate names (CN/SAN)

### ISSUE THREAD

**Issue by VRShiva** [containous/traefik#8503]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Traefik will only apply 1 certificate if 2 certificates are configured (on different interfaces) and both have the same CN/SAN.
This will result in all interfaces being applied the first certificate, as the second certificate is marked as a duplicate.

This situation occured when trying to replace a certificate on 1 interface but keeping the old certificate on another interface.
The new certificate has the same certificate details but is issued by a different CA and has a different thumbprint/serial number.

**2 certificates:**

**OLD:**
    Common Name: *.test.acme.net
    Subject Alternative Names: *.test.acme.net, test.acme.net
    Valid From: October 5, 2020
    Valid To: October 6, 2021
    Issuer: DigiCert SHA2 Secure Server CA
    Serial Number: 0337b97c0b3186a3a974dcb824295c5e

**NEW:**
    Common Name: *.test.acme.net
    Subject Alternative Names: *.test.acme.net, test.acme.net
    Valid From: September 9, 2021
    Valid To: October 5, 2022
    Issuer: DigiCert TLS RSA SHA256 2020 CA1
    Serial Number: 05b43188b447022854e1e4054b77fcde

**2 secrets containing the certificates:**

**OLD:**
    wildcard-test.acme.net-secret-certkey

**NEW:**
    wildcard-test.acme.net-secret-certkey-2021

### What did you see instead?

The **wildcard-test.acme.net-secret-certkey** certificate is the first certificate loaded in the default keystore
When attempting to load **wildcard-test.acme.net-secret-certkey-2021** into the store it will detect a duplicate:

"Skipping addition of certificate for domain(s) "*.test.acme.net, test.acme.net" to EntryPoint default, as it already exists for this EntryPoint."

The duplicate check seems to be done on the CN and/or SAN (DNS names), there should be an extra check on the Serial Number or Thumbprint of the certificate.

I suspect the issue is located at https://github.com/traefik/traefik/blob/master/pkg/tls/certificate.go#L190

### What version of Traefik are you using?

Traefik version 2.4.5 built on 2021-02-18T17:21:25Z

### What is your environment & configuration?

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: #{tooling-namespace}#
  name: traefik2
  labels:
    app: traefik2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik2
  template:
    metadata:
      labels:
        app: traefik2
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik2
          image: traefik:v2.4.5
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.metrics.address=:8082
            - --entrypoints.sftp.address=:20022
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --log.level=#{traefik-log-level}#
            - --providers.kubernetescrd
            - --metrics.prometheus=true
            - --metrics.prometheus.addEntryPointsLabels=true
            - --metrics.prometheus.addServicesLabels=true
            - --metrics.prometheus.entryPoint=metrics
            - --pilot.token=#{traefik-pilot-token}#
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
            - name: metrics
              containerPort: 8082
            - name: sftp
              containerPort: 20022
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
```

### If applicable, please paste the log output in DEBUG level

"Skipping addition of certificate for domain(s) "*.test.acme.net, test.acme.net" to EntryPoint default, as it already exists for this EntryPoint."
