### ISSUE TITLE
Loadbalancer.server.port ignored for TCP service provided by Docker 

### ISSUE THREAD

**Issue by sebastianheierhoff** [containous/traefik#8520]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I am running Traefik on Docker, trying to expose a TCP service from within a container based on the official nginx image. The image exposes port 80 by default (although unused by me). Traefik automatically creates a loadbalancer service addressing port 80 ignoring the "- traefik.tcp.services.nginx-nginx.loadbalancer.server.port=9000". I can achieve the desired routing to port 9000 by creating an additional service in a dynamic configuration file though.

### What did you see instead?

![2021-10-16 12_13_54-Window](https://user-images.githubusercontent.com/6094238/137583592-a6668c15-7acd-4081-ad96-148da0ab6e11.png)

### What version of Traefik are you using?

Version:      2.5.3
Codename:     livarot
Go version:   go1.17.1
Built:        2021-09-20T15:43:56Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
api:
   dashboard: true

log:
   level: DEBUG

entryPoints:
   http:
      address: ":80"
   https:
      address: ":443"

providers:
   docker:
      endpoint: "unix:///var/run/docker.sock"
      exposedByDefault: false
   file:
      filename: "/dynamic_conf.yml"
```

Add more configuration information here.
/opt/nginx/docker-compose.yml 
```yaml
version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ../traefik/data/certs:/etc/nginx/certs
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true" # enable traefik
      - "traefik.docker.network=proxy" # put it in the same network as traefik
      # tcp part
      - "traefik.tcp.routers.mytcprouter.rule=HostSNI(`<redacted>`)"
      - "traefik.tcp.routers.mytcprouter.entrypoints=https"
      - "traefik.tcp.routers.mytcprouter.tls=true"
      - "traefik.tcp.routers.mytcprouter.tls.certresolver=http"
      - "traefik.tcp.routers.mytcprouter.tls.passthrough=true"
      - "traefik.tcp.routers.mytcprouter.service=mytcpservice@file" #works
#      - "traefic.tcp.services.nginx-nginx.loadbalancer.server.port=9000" #does not work
    networks:
      - proxy
networks:
  proxy:
    external: true
```

/opt/traefik/data/dynamic_conf.yml
```yaml
<snip>
tcp:
  services:
    mytcpservice:
      loadBalancer:
        servers:
          - address: "nginx:9000"
<snip>
```

### If applicable, please paste the log output in DEBUG level

time="2021-10-16T12:15:56+02:00" level=debug msg="Creating TCP server 0 at 172.20.0.4:80" entryPointName=https routerName=mytcprouter@docker serviceName=nginx-nginx serverName=0
