### ISSUE TITLE
HA traefik (k8s) with etcd backend "Cannot unmarshall private key []"

### ISSUE THREAD

**Issue by george-angel** [containous/traefik#853]
Running on AWS/CoreOS/k8s

Following deployment manifest: (the init container must be commented out as the `storeconfig` isn't idempotent and will fail on consecutive runs.)

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: external-ingress-proxy
  name: external-ingress-proxy
  namespace: system
spec:
  selector:
    app: external-ingress-proxy
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30180
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30143
  - name: http-admin
    protocol: TCP
    port: 8080
  selector:
    k8s-app: external-ingress-proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-ingress-proxy
  namespace: system
  labels:
    k8s-app: external-ingress-proxy
spec:
  replicas: 2
  revisionHistoryLimit: 8
  template:
    metadata:
      labels:
        k8s-app: external-ingress-proxy
        name: external-ingress-proxy
#      annotations:
#        pod.beta.kubernetes.io/init-containers: '[
#          {
#            "name": "storeconfig",
#            "image": "traefik:v1.1.0-rc4",
#            "args": [ "storeconfig" ],
#            "volumeMounts": [
#              {
#                "name": "config",
#                "mountPath": "/etc/traefik",
#                "readOnly": true
#              },
#              {
#                "name": "ssl",
#                "mountPath": "/etc/ssl",
#                "readOnly": true
#              }
#            ]
#          }
#        ]'
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.1.0-rc4
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 2000Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --logLevel=ERROR
        - --kubernetes.labelselector=public-lb=traefik
        - --etcd
        - --etcd.endpoint=etcd:2379
        - --etcd.tls
        - --etcd.tls.ca=/etc/ssl/ca.pem
        - --etcd.tls.cert=/etc/ssl/k8s-worker.pem
        - --etcd.tls.key=/etc/ssl/k8s-worker-key.pem
        volumeMounts:
        - name: ssl
          mountPath: /etc/ssl
          readOnly: true
      volumes:
        - name: ssl
          hostPath:
            path: /etc/kubernetes/ssl
        - name: config
          configMap:
            name: external-ingress-proxy-config
```

Original static config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-ingress-proxy-config
  namespace: system
data:
  traefik.toml: |-
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]
    
    [etcd]
    endpoint = "etcd:2379"
    
    [etcd.tls]
    ca = "/etc/ssl/ca.pem"
    cert = "/etc/ssl/k8s-worker.pem"
    key = "/etc/ssl/k8s-worker-key.pem"
    insecureskipverify = true

    [acme]
    email = "<valid email>"
    storage = "traefik/acme/account"
    entryPoint = "https"
    OnHostRule = true
    
    [entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
    
    [web]
    address = ":8080"
    
    [kubernetes]
    labelselector = "public-lb=traefik"
```
