### ISSUE TITLE
Traefik metrics not seen by prometheus

### ISSUE THREAD

**Issue by Rachneet** [containous/traefik#8530]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I want  prometheus to scrape the metrics from traefik but it is not working. I have installed both traefik and the prom operator using the helm charts. 

I am able to access the traefik dashboard and the traefik metrics via the designated ports. I have created a dashboard-service shown below:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

  ports:
    - protocol: TCP
      port: 9000
      name: admin
    - protocol: TCP
      port: 9100
      name: metrics
```

I checked that I am able to access the metrics endpoint from inside the cluster. Next, I create a service monitor so that the traefik metrics can be scraped by prometheus. The config is shown below:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-svc-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik-dashboard
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    path: /metrics
    interval: 10s
    honorLabels: true
```

But I do not see the metrics being scraped in prometheus. Please help me.

### What did you see instead?

I did not see anything in the prometheus service discovery.

### What version of Traefik are you using?

2.5.3

### What is your environment & configuration?

Trefik is installed via helm with the following config

```yaml
image:
  name: traefik
  tag: "2.5.3"

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

additionalArguments:
  - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
  - "--certificatesresolvers.le-staging.acme.email=***"
  - "--certificatesresolvers.le-staging.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    # - "--certificatesresolvers.le.acme.tlschallenge=true"
    # - "--certificatesresolvers.le.acme.email=***"
    # - "--certificatesresolvers.le.acme.storage=/data/acme.json"

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 128Mi
  storageClass: "managed-nfs-storage"

metrics:
  prometheus:
    enabled: true
  serviceMonitor:
    # When set true and if Prometheus Operator is installed then use a ServiceMonitor to configure scraping
    enabled: true
    # Set the namespace the ServiceMonitor should be deployed
    namespace: monitoring
    # Set how frequently Prometheus should scrape
    interval: 10s

logs:
  access:
    enabled: true
    format: json

```

Add more configuration information here.
