### ISSUE TITLE
IngressRoute with middleware and tls not working

### ISSUE THREAD

**Issue by giovannicandido** [containous/traefik#8543]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Creating a IngressRoute with tls and middleware not working. Configs:

Logs:

```
time="2021-10-27T01:33:17Z" level=info msg="Configuration loaded from flags."
time="2021-10-27T01:35:22Z" level=error msg="middleware \"traefik-system-traefik-auth@kubernetescrd\" does not exist" entryPointName=web routerName=traefik-system-traefik-dashboard-d04c279f741265807d6a@kubernetescrd
time="2021-10-27T01:35:22Z" level=error msg="middleware \"traefik-system-traefik-auth@kubernetescrd\" does not exist" entryPointName=websecure routerName=traefik-system-traefik-dashboard-d04c279f741265807d6a@kubernetescrd
time="2021-10-27T13:24:34Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-http namespace=infra
time="2021-10-27T13:24:34Z" level=error msg="subset not found for infra/nexus-service" ingress=nexus-ingress-http namespace=infra providerName=kubernetescrd
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" ingress=nexus-ingress-http namespace=infra providerName=kubernetescrd
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" ingress=nexus-ingress-http namespace=infra providerName=kubernetescrd
time="2021-10-27T13:24:35Z" level=error msg="Error configuring TLS: secret infra/nexus-infra-kugelbit-com does not exist" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-http namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-http namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="Error configuring TLS: secret infra/nexus-infra-kugelbit-com does not exist" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:35Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:36Z" level=error msg="Error configuring TLS: secret infra/nexus-infra-kugelbit-com does not exist" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:36Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:36Z" level=error msg="subset not found for infra/nexus-service" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra
time="2021-10-27T13:24:36Z" level=error msg="subset not found for infra/nexus-service" ingress=nexus-ingress-http namespace=infra providerName=kubernetescrd
time="2021-10-27T13:24:36Z" level=error msg="subset not found for infra/nexus-service" namespace=infra providerName=kubernetescrd ingress=nexus-ingress-http
time="2021-10-27T13:25:01Z" level=error msg="Error configuring TLS: secret infra/nexus-infra-kugelbit-com does not exist" namespace=infra providerName=kubernetescrd ingress=nexus-ingress-tls
time="2021-10-27T13:34:49Z" level=error msg="Error configuring TLS: secret infra/nexus-infra-kugelbit-com does not exist" providerName=kubernetescrd ingress=nexus-ingress-tls namespace=infra

```

But the resources exists:

```
kubectl -n infra get svc

NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)           AGE
nexus-service   ClusterIP   10.233.60.34   <none>        80/TCP,5000/TCP   17m

kubectl -n infra get secrets

NAME                       TYPE                                  DATA   AGE
default-token-m9ltj        kubernetes.io/service-account-token   3      40m
nexus-infra-kugelbit-com   kubernetes.io/tls                     2      14m

kubectl -n infra get middleware.traefik.containo.us

NAME                   AGE
nexus-buffer-limit     26m
nexus-redirect-https   26m
```

The resources appear in traefik dashboard:

![image](https://user-images.githubusercontent.com/915892/139079651-8bf6ee2d-be4b-4203-8ebc-3c5d942d4ba5.png)
![image](https://user-images.githubusercontent.com/915892/139079789-db75b350-0475-44be-8a8f-5a6718cf399d.png)

How can I debug further this issue?

### What did you see instead?

No traffic routed to the services, so ingress not working

### What version of Traefik are you using?

Traefik version 2.5.3 installed thought helm package

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-ingress-tls
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nexus.infra.kugelbit.com`)
      kind: Rule
      services:
        - name: nexus-service
          port: 80
    - match: Host(`docker.infra.kugelbit.com`)
      kind: Rule
      services:
        - name: nexus-service
          port: 5000
      middlewares:
       - name: nexus-buffer-limit
         namespace: infra
  tls:
    secretName: nexus-infra-kugelbit-com
    domains:                       
    - main: nexus.infra.kugelbit.com            
      sans:                        
      - docker.infra.kugelbit.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-ingress-http
  namespace: infra
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nexus.infra.kugelbit.com`)
      kind: Rule
      services:
        - name: nexus-service
          port: 80
      middlewares:
        - name: nexus-redirect-https
          namespace: infra
    - match: Host(`docker.infra.kugelbit.com`)
      kind: Rule
      services:
        - name: nexus-service
          port: 5000
      middlewares:
        - name: nexus-redirect-https
          namespace: infra
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nexus-buffer-limit
  namespace: infra
spec:
  buffering:
    maxRequestBodyBytes: 1000000000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nexus-redirect-https
  namespace: infra
spec:
  redirectScheme:
    scheme: https
    permanent: true

```

### If applicable, please paste the log output in DEBUG level

How to configure k8s traefik to debug log level?
