### ISSUE TITLE
How to use pathprefixstrip and provide path value on Kubernetes Ingress

### ISSUE THREAD

**Issue by padolan** [containous/traefik#863]
I have a tomcat webapp running under kubernetes under a context root of /tomee-sample.  It is deployed to a k8s namespace "us-6000".  I've created a traefik kubernetes ingress using pathprefixstrip, matching "/us-6000/tomee-sample".  The ingress uses the pathprefixstrip annotation, and works great.

My issue is, due to the local context root, I have to duplicate the "tomee-sample" portion of the incoming url to successfully reach the app.  So while "/us-6000/tomee-sample/tomee-sample/healthcheck" works, and resolves to "/tomee-sample/healthcheck", I'd like to be able to reach it through the ingress via "/us-6000/tomee-sample/healthcheck".

Is there a way to specify the pathprefixstrip expression from within the k8s ingress configuration?  I only see examples showing an annotation without a value specified.  I've tried different combinations without success.  Here's my sample ingress yaml that works:
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: pathprefixstrip
  name: tomee-sample
  namespace: us-6000
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tomee-sample
          servicePort: 8080
        path: /us-6000/tomee-sample
status:
  loadBalancer: {}
```

I was hoping I could do something as follows:
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: pathprefixstrip:/us-6000
  name: tomee-sample
  namespace: us-6000
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tomee-sample
          servicePort: 8080
        path: /us-6000/tomee-sample
status:
  loadBalancer: {}
```
Would appreciate guidance on what I'm doing wrong, or if this feature is not yet supported via k8s ingress.
