### ISSUE TITLE
Kubernetes Nginx Deployment Panic

### ISSUE THREAD

**Issue by dweidenfeld** [containous/traefik#879]
If I make a deployment with these settings there is a panic occurring.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80
```

```
goroutine 820 [running]:
panic(0xd292c0, 0xc420229980)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1.1(0xc420611290, 0xc42060c2a0, 0xc42029d050, 0x26, 0xc42060c240)
        /go/src/github.com/containous/traefik/provider/k8s/client.go:280 +0x33f
created by github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1
        /go/src/github.com/containous/traefik/provider/k8s/client.go:286 +0xbf
```

Is it really an error, or a configuration mistake?

Thank you
