### ISSUE TITLE
Traefik security for dashboard

### ISSUE THREAD

**Issue by NiklasA** [containous/traefik#880]
First of all: Traefik is awesome!

Hi,
I will shortly describe my use cases for Traefik and then what is currently not working as expected ( maybe not supported yet :wink: ).

**My Workbench:**
- Docker version 1.12.3
- Docker-Compose version 1.9.0, build 2585387
- Traefik v1.1.0 / camembert (Docker image: containous/traefik:latest)

I have three domains:
1. one for a personal blog
2. one for a shop
3. one for Traefik

Traefik works fine for 1. / 2. (Let's Encrypt, Docker Swarm mode etc.), but I want to make the dashboard of Traefik more secure.

**Questions:**
1. It is possible to restrict Traefik dashboard to SSL only?
2. I have the issue that i can reach Traefik via each domain (1. - 3.) with url http://\<domain\>:8080/, can I limit it to a single domain?
3. How can I enable basic authentication for Traefik, that only specific user with access can see Traefik dashboard? (My current configuration does work.)

Thank you in advance. :+1: 

Niklas

**traefik.toml:**
```
logLevel="DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
email = "info@admin.example.com"
storageFile = "/etc/traefik/acme.json"
entryPoint = "https"
onDemand = true
onHostRule = true
## Comment out for production environment!
caServer = "https://acme-staging.api.letsencrypt.org/directory"

[docker]
domain = "admin.example.com"
endpoint = "unix:///var/run/docker.sock"
watch = true

[web]
  [web.auth.basic]
  users = ["admin:$apr1$bFhdoJ2K$rM8Oxwy8fYfIJZfuL4iSp0"]
```

**docker-compose.yml:**
```
version: "2"
services:
  traefik:
    command: --web --docker
    container_name: traefik
    image: containous/traefik:latest
    labels:
      - "traefik.frontend.rule=Host:admin.example.com"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - "/opt/traefik/ssl/acme.json:/etc/traefik/acme.json"
      - "/opt/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  container1:
    image: richarvey/nginx-php-fpm:php7
    labels:
      - "traefik.backend=oneExample"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:one.example.com"
      - "traefik.port=80"
      - "traefix.port=443"
      - "traefik.weight=1"
    volumes:
      - "/opt/repositories/oneexample/www-root/:/var/www/html"
  
  container2:
    image: richarvey/nginx-php-fpm:php7
    labels:
      - "traefik.backend=twoExample"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:two.example.com"
      - "traefik.port=80"
      - "traefix.port=443"
      - "traefik.weight=1"
    volumes:
      - "/opt/repositories/twoexample/www-root/:/var/www/html"
```

**Comment by emilevauge** [comment]
Hello @NiklasA 
>It is possible to restrict Traefik dashboard to SSL only?

Yes, just provide a `CertFile` and a `KeyFile` in your web section config (http://docs.traefik.io/toml/#api-backend)

>I have the issue that i can reach Traefik via each domain (1. - 3.) with url http://<domain>:8080/, can I limit it to a single domain?

No sorry. But this could be added. Could you open an issue specifically on this?

>How can I enable basic authentication for Traefik, that only specific user with access can see Traefik dashboard? (My current configuration does work.)

Follow the documentation in http://docs.traefik.io/toml/#api-backend and add:
```
[web.auth.basic]
users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]
```

**Comment by NiklasA** [comment]
Hi @emilevauge,

thank you for your fast response. Question one and two should be answered with it. Thank you and I will also create a new issue for question two.

> Follow the documentation in http://docs.traefik.io/toml/#api-backend and add:

[web.auth.basic]
users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]

I add this to my configuration, but it does not work.
[web]
  address = ":9443"
  [web.auth.basic]
  users = ["admin:$apr1$bFhdoJ2K$rM8Oxwy8fYfIJZfuL4iSp0"]

Do you know, what I did wrong?

Niklas

**Comment by emilevauge** [comment]
There seems to be an issue with your password. Is it working with `"test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"` test/test ?

**Comment by NiklasA** [comment]
Hey,

I changed the configuration, but it has no effect. 

**My Docker Logs:**
time="2016-11-24T19:58:34Z" level=info msg="Traefik version v1.1.0 built on 2016-11-18_09:20:46AM" 
time="2016-11-24T19:58:34Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml" 
time="2016-11-24T19:58:34Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":{\"EntryPoint\":\"https\",\"Regex\":\"\",\"Replacement\":\"\"},\"Auth\":null,\"Compress\":false},\"https\":{\"Network\":\"\",\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":null,\"ClientCAFiles\":null},\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":{\"Email\":\"info@example.com",\"Domains\":null,\"Storage\":\"\",\"StorageFile\":\"/etc/traefik/acme.json\",\"OnDemand\":true,\"OnHostRule\":true,\"CAServer\":\"https://acme-staging.api.letsencrypt.org/directory\",\"EntryPoint\":\"https\"},\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false},\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null}" 
time="2016-11-24T19:58:34Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4201bf8c0 Redirect:<nil> Auth:<nil> Compress:false}" 
time="2016-11-24T19:58:34Z" level=warning msg="ACME.StorageFile is deprecated, use ACME.Storage instead" 
time="2016-11-24T19:58:34Z" level=info msg="Loading ACME Account..." 
time="2016-11-24T19:58:34Z" level=info msg="Loaded ACME config from store /etc/traefik/acme.json" 
time="2016-11-24T19:58:34Z" level=debug msg="Building ACME client..." 
time="2016-11-24T19:58:34Z" level=debug msg=AgreeToTOS... 
time="2016-11-24T19:58:35Z" level=info msg="Retrieving ACME certificates..." 
time="2016-11-24T19:58:35Z" level=info msg="Retrieved ACME certificates" 
time="2016-11-24T19:58:35Z" level=debug msg="Testing certificate renew..." 
time="2016-11-24T19:58:35Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc4203633b0 Auth:<nil> Compress:false}" 
time="2016-11-24T19:58:35Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false}" 
time="2016-11-24T19:58:35Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}" 
time="2016-11-24T19:58:35Z" level=info msg="Starting server on :80" 
time="2016-11-24T19:58:35Z" level=info msg="Starting server on :443" 
time="2016-11-24T19:58:35Z" level=debug msg="Docker connection established with docker 1.12.3 (API 1.24)"

Niklas

**Comment by emilevauge** [comment]
OK @NiklasA I got it, just uncomment `--web --docker` in your compose file. You don't need argument if you use a TOML file (they override TOML configuration).

**Comment by NiklasA** [comment]
@emilevauge Thank you! Now it works!

**Comment by MihaMarkic** [comment]
>  >    It is possible to restrict Traefik dashboard to SSL only?

> Yes, just provide a CertFile and a KeyFile in your web section config (http://docs.traefik.io/toml/#api-backend)

How would one do that with Let's encrypt certificates (if possible at all)?

**Comment by nesimtunc** [comment]
Actually, it's possible to achieve. If you approach like normal docker container;

**traefik/traefik.toml**
```
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]

[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
  
[acme]  
email = "admin@example.com"  
storage = "acme.json" 
entryPoint = "https"
onDemand = false
OnHostRule = true


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.example.com"
watch = true
exposedbydefault = false
```

**traefik/docker-compose.yml**
```
version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      # - "8080:8080" we don't need this anymore, since we want traefik handle it, 
      # it will resolve from host name and traefik will proxy it , 
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:traefik.example.com" # traefik will request SSL from letsencrypt
      - "traefik.port=8080" # enable this port in so traefik can proxy it
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
  webgateway: 
    driver: bridge
```

**Comment by cgebe** [comment]
@nesimtunc Trying your solution gives me a redirection loop when accessing the dashboard subdomain.

Is there some way i can assign the dashboard to a subdomain without port incl. ssl protection?

**Comment by nesimtunc** [comment]
Sorry for the typo :D thanks for corrected it! @cgebe

**Comment by max21** [comment]
Hi,
Do you have the answer regarding your question N°2 :

"I have the issue that i can reach Traefik via each domain (1. - 3.) with url http://<domain>:8080/, can I limit it to a single domain?"

Thanks

**Comment by NiklasA** [comment]
Hi @max21,

I could get it running it with the following configuration.

**docker-compose.yml:**
```
version: "3.6"

services:
    traefik-swarm:
        deploy:
            labels:
            - "traefik.backend.loadbalancer.stickiness.cookieName=S_SESSION"
            - "traefik.backend.loadbalancer.stickiness=true"
            - "traefik.backend=traefik-dashboard"
            - "traefik.docker.network=<<SOME_NETWORK>>"
            - "traefik.enable=true"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.frontend.rule=Host: <<SOME_HOSTNAME>>"
            - "traefik.port=8080"
        [...]
        networks:
            <<SOME_NETWORK>>:
                aliases:
                    - "<<SOME_HOSTNAME>>"
```

**traefik.toml:**
```
[api]
entryPoint = "traefik-dashboard"
dashboard = true
debug = false
  [api.statistics]
  recentErrors = 10

[ping]
entryPoint = "traefik-dashboard"

[docker]
domain = "<<SOME_DOMAIN>>"
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
swarmmode = true
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  ## define entryPoint for traefik dashboard!
  [entryPoints.traefik-dashboard]
  address = ":8080"
    [entryPoints.traefik-dashboard.auth.basic]
    users = [
      "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
    ]
  [entryPoints.https]
  address = ":443"
  compress = true
  [..]

[retry]
```

I hope I could help you with that.

Gr.
Niklas
