### ISSUE TITLE
Add certain default Response Headers (but do not override if found) if app behind proxy does not return certain response headers.

### ISSUE THREAD

**Issue by jerrywoo96** [containous/traefik#8808]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Expect to see default specific headers if the app behind proxy does not return specific headers.

Currently, i am aware that we have the option to add and remove response headers from the app, and forward those to the client.

I will use the Traefik app as an example.

Traefik returns a csp header, "content-security-policy: frame-src 'self' https://traefik.io https://*.traefik.io;", but my other apps do not. if i add this csp header with a default value for my other apps, certain features in Traefik will fail to function, as the header is overriden.

I have a set of global response headers, to add by default if app does not return any.

I am proposing this feature, as it is not practical to check each and every pages of every app i add behind the proxy for headers that they return, and add them via middlewares, as it is time consuming, and that will also result in many middlewares created just to add headers that does not exist in the response and not override those if found.

**Comment by jerrywoo96** [comment]
i could suggest the following:
```
http:
  middlewares:
    AddDefaultHeaders:
      headers:
        customRequestHeaders: {} # Exists Currently To Override If Found, Add If Not Found, Or Remove If Found
        customResponseHeaders: {} # Exists Currently To Override If Found, Add If Not Found, Or Remove If Found
        addCustomResponseHeaders: {} # Add Headers if Not Found, Do Not Override If Found.
```

**Comment by rtribotte** [comment]
Hello @jerrywoo96,

Thanks for your interest in Traefik!

We labeled this issue as "proposal", which means that it needs to be refined before any implementation. While the use case is clear, we are wondering if the best option is to add a new configuration field to the Header middleware configuration.

As well, it means that it is not on our roadmap by any means, so it cannot be expected to see this implemented shortly.

In that regard, you might want to try implementing that feature with a [plugin middleware](https://pilot.traefik.io/plugins).
Please take a look at the https://github.com/traefik/plugindemo repository which is the place to start building a plugin, as well as the [pilot plugin documentation](https://doc.traefik.io/traefik-pilot/plugins/plugin-dev/).
You can take advantage of the [local mode](https://github.com/traefik/plugindemo#local-mode) to play around.

**Comment by danepowell** [comment]
I'd also like to see this, specifically to fix https://github.com/pi-hole/docker-pi-hole/issues/1163

I set `frameDeny: true` as standard security hardening, but Pi-hole which is behind the reverse proxy does need to embed some content in a frame. Pi-hole is also smart enough to manage the X-Frame-Options header itself.

So what I'd like is to only set X-Frame-Options header via Traefik if the origin app hasn't already explicitly set it.

Anyone have ideas for a better solution or workaround?

**Comment by jerrywoo96** [comment]
@danepowell 

I've coded a middleware, see if it works for you.
https://plugins.traefik.io/plugins/62f3496be2bf06d4675b9445/add-missing-headers

**Comment by jerrywoo96** [comment]
> Hello @jerrywoo96,
> 
> Thanks for implementing a new plugin! Can we consider that this issue can be closed and addressed by this new plugin?

@rtribotte 

Its abit flakey in some aspects, not a perfect implementation, some times it fails to detect an existing header and add another same header with a different value. Would still love to see this natively implemented tho. Would you be able see and check my code if it makes sense and properly implemented? Am not experienced in golang. Also could use a help to test my implementation :)

Thank you!

**Comment by danepowell** [comment]
@jerrywoo96 thanks a lot for the plugin! Unfortunately it doesn't quite work. If a header is missing, it will add the missing header (yay!). But if the header is already present in the response, it seems to add the header a second time.

For instance, here's my configuration:
```yaml
    append-security-headers:
      plugin:
        AddMissingHeaders:
          responseHeaders:
            # headers: frameDeny can break apps that use frames such as pi-hole
            # @see https://github.com/traefik/traefik/issues/8808
            X-Frame-Options: DENY
```

For the Pi-hole API token page (see https://github.com/pi-hole/docker-pi-hole/issues/1163), this causes an obviously broken response with duplicate headers:

```json
{
	"Response Headers (679 B)": {
		"headers": [
			{
				"name": "x-frame-options",
				"value": "DENY"
			},
			{
				"name": "x-frame-options",
				"value": "SAMEORIGIN"
			}
		]
	}
}
```
