### ISSUE TITLE
combine Host and HostRegexp rules

### ISSUE THREAD

**Issue by opichon** [containous/traefik#882]
Im trying to combine a HostRegexp and a Host rule on a frontend, but it doesn't work.

The main config backend is docker, with these labels on a service in a docker-compose.yml config:

```yaml
services:
    server:
        labels:
            - "traefik.backend=backend1"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.priority=1"
            - "traefik.frontend.rule=HostRegexp:{subdomain:[A-Za-z0-9-]+}.mydomain.com"
            - "traefik.port=2015"
```
This takes care of any host in the domain `mydomain.com`.

Note the use of port 2015 (caddy server on the backend)

I also want to add the host `my.domain.com` to point to the same backend.

here's what I've tried, but nothing works:

```
            - "traefik.frontend.rule=Host:my.domain.com;HostRegexp:{subdomain:[A-Za-z0-9-]+}.mydomain.com"
```

In this case, neither the wildcard nor the custom host work. Both give a "404 page not found" error.

I've also tried add ing a `[file]` config in `traefik.toml directly:

```toml
[file]
[frontends]
[frontends.mydomain]
backend = "backend1"
entryPoints = ["http", "https"]
passHostHeader = true
[frontends.mydomain.routes.main]
    rule = "Host:my.domain.com"
```

the wildcard (HostRegexp) routes work, but my.domain.com doesn't. I get a 404 page not found error.
