### ISSUE TITLE
setsockopt: invalid argument

### ISSUE THREAD

**Issue by DuckThom** [containous/traefik#8841]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Nothing in particular. The error seems to be happening without a specific action occurring.

### What did you see instead?

The entrypoints seem to die out of the blue with the error "setsockopt: invalid argument" in the logs.
After this error appears in the log, Traefik wont accept any new incoming connections. 

I've found https://github.com/traefik/traefik/issues/8071 however this was closed without a resolution. And https://community.traefik.io/t/traffic-stops-accepting-connections-on-certain-entrypoints-after-running-for-about-a-week/10390 also has not been updated since April 2021

### What version of Traefik are you using?

```
Version:      2.6.1
Codename:     cheddar
Go version:   go1.17.6
Built:        I don't remember exactly
OS/Arch:      darwin/arm64
```

### What is your environment & configuration?

System:

- OS: MacOS 11.6
- M1 (Mac Mini)

traefik.toml

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]

[certificatesResolvers.le-resolver.acme]
  email = "<redacted>"
  storage = "acme.json"
  [certificatesResolvers.le-resolver.acme.httpChallenge]
    entryPoint = "web"

[accessLog]

[log]
  level = "DEBUG"

[api]
  dashboard = true

[providers.file]
  filename = "/opt/homebrew/etc/traefik/traefik_dynamic.yml"
```

traefik_dynamic.yml

```yaml
http:
  routers:
    <redacted>:
      rule: "Host(`<redacted>`)"
      service: <redacted>
      entryPoints:
        - websecure
      tls:
        certResolver: le-resolver

  services:
    <redacted>:
      loadBalancer:
        servers:
        - url: "http://localhost:3000/"
```

### If applicable, please paste the log output in DEBUG level

Note: This is INFO level logging, I'm still collecting debug output logging

```
time="2022-03-14T07:27:22+01:00" level=error msg="set tcp 192.168.1.xxx:443->xxx.xxx.xxx.xxx:58532: setsockopt: invalid argument" entryPointName=websecure
time="2022-03-14T07:27:22+01:00" level=error msg="Error while starting server: set tcp 192.168.1.xxx:443->xxx.xxx.xxx.xxx:58532: setsockopt: invalid argument" entryPointName=websecure
time="2022-03-14T07:27:22+01:00" level=error msg="Error while starting server: set tcp 192.168.1.xxx:443->xxx.xxx.xxx.xxx:58532: setsockopt: invalid argument" entryPointName=websecure
time="2022-03-15T13:29:29+01:00" level=info msg="Testing certificate renew..." providerName=le-resolver.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-03-15T13:29:29+01:00" level=info msg="Testing certificate renew..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=le-resolver.acme
```
