### ISSUE TITLE
Let's Encrypt HTTP Challenge Error

### ISSUE THREAD

**Issue by paulkre** [containous/traefik#8878]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have used Traefik's automatic certificate registration feature with Let's Encrypt for a while now. It has always worked really well. All I had to do was to configure the TLS provider in the configuration as described in the docs. Traefik would then automatically obtain certificates for the domains listed in the ``Host(`example.com`)`` rule.

### What did you see instead?

But now when I try to add a new domain, instead of obtaining a certificate via Let's Encrypt, I get the following error:

``Unable to obtain ACME certificate for domains \"example.com\": unable to generate a certificate for the domains [example.com]: error: one or more domains had a problem:\n[example.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://example.com/.well-known/acme-challenge/V3pIUJu3... [195.1.1.1]: 503\n" rule="Host(`example.com`)" ACME CA="https://acme-v02.api.letsencrypt.org/directory``

It looks like the HTTP challenge for authorizing my request ist not working.

This also happens when I remove the `acme.json` file and try to obtain new certificates for the domains that I have previously already registered. So the HTTP challenge has worked before.

### What version of Traefik are you using?

v2.6.1

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

providers:
  file:
    directory: /config
    watch: true

certificatesResolvers:
  LetsEncrypt:
    acme:
      email: foo@bar.com
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
```

Router configuration:

```yaml
http:
  routers:
    my-router:
      rule: "Host(`example.com`)"
      service: my-service
      entryPoints: websecure
      tls:
        certResolver: LetsEncrypt
```
