### ISSUE TITLE
Limit Traefik dashboard to a single domain

### ISSUE THREAD

**Issue by NiklasA** [containous/traefik#898]
Hi,

@emilevauge asked me, whether I could open another issue (feature request) to handle my questions separatly ([Link](https://github.com/containous/traefik/issues/880#issuecomment-262748730)).

I have the issue that i can reach Traefik via each domain (1. - 3.) with url `http://<domain>:8080/`, can I limit it to a single domain? It would be nice for security reasons.

**My Workbench:**
- Docker version 1.12.3
- Docker-Compose version 1.9.0, build 2585387
- Traefik v1.1.0 / camembert (Docker image: containous/traefik:latest)

**I have three domains:**
1. one for a personal blog
2. one for a shop
3. one for Traefik

**traefik.toml:**
```
logLevel="DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
email = "info@admin.example.com"
storageFile = "/etc/traefik/acme.json"
entryPoint = "https"
onDemand = true
onHostRule = true
## Comment out for production environment!
caServer = "https://acme-staging.api.letsencrypt.org/directory"

[docker]
domain = "admin.example.com"
endpoint = "unix:///var/run/docker.sock"
watch = true

[web]
  address = ":9443"
  [web.auth.basic]
  users = ["admin:$apr1$bFhdoJ2K$rM8Oxwy8fYfIJZfuL4iSp0"]
```

**docker-compose.yml:**
```
version: "2"
services:
  traefik:
    command: --web --docker
    container_name: traefik
    image: containous/traefik:latest
    labels:
      - "traefik.frontend.rule=Host:admin.example.com"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - "/opt/traefik/ssl/acme.json:/etc/traefik/acme.json"
      - "/opt/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  container1:
    image: richarvey/nginx-php-fpm:php7
    labels:
      - "traefik.backend=oneExample"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:one.example.com"
      - "traefik.port=80"
      - "traefix.port=443"
      - "traefik.weight=1"
    volumes:
      - "/opt/repositories/oneexample/www-root/:/var/www/html"
  
  container2:
    image: richarvey/nginx-php-fpm:php7
    labels:
      - "traefik.backend=twoExample"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:two.example.com"
      - "traefik.port=80"
      - "traefix.port=443"
      - "traefik.weight=1"
    volumes:
      - "/opt/repositories/twoexample/www-root/:/var/www/html"
```

Thank you in advance.

**Comment by gjonespf** [comment]
Might be useful, but how I handle this is:
- Create a separate endpoint on e.g. 9001

`--entryPoints='Name:https-admin Address::9001 TLS:/etc/traefik/customssl/pfssc.crt,/etc/traefik/customssl/pfssc.key'`

or in TOML

```
[entryPoints.https-admin]
address = ":9001"
[entryPoints.https-admin.tls]
```

- Change port bindings on your compose for the web admin port to be internal, and add another port for the new endpoint.
- Add label to use the new entrypoint

```
traefik:
    command: --web --docker
    container_name: traefik
    image: containous/traefik:latest
    labels:
      - "traefik.frontend.rule=Host:admin.example.com"
	  - "traefik.frontend.entryPoints=https-admin"
    ports:
      - "80:80"
      - "443:443"
      - "8080"
      - "9001:9001"      
    restart: always
    volumes:
      - "/opt/traefik/ssl/acme.json:/etc/traefik/acme.json"
      - "/opt/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock" 
```  

Not sure if this is a supported scenario, but it works for me 😄 
Is this the same thing you're trying to do?  I do it this way so I can also add auth / other services which shouldn't be "public" but still using same infra.

**Comment by w3blogfr** [comment]
Solution works, but ajax cal to refresh dashboard are counted in dashboard

**Comment by gaui** [comment]
Why not be able to do something like this in TOML...

```
[web]
address = "sub.domain.tld:8080"
```

**Comment by xalexslx** [comment]
Any update?

**Comment by ldez** [comment]
The [web backend](http://v1-5.archive.docs.traefik.io/configuration/backends/web/) is now deprecated and replaced by [REST backend](http://v1-5.archive.docs.traefik.io/configuration/backends/rest/).

You can now define a dedicate entrypoint.

This feature come in v1.5.

**Comment by w3blogfr** [comment]
Rest endpoint instead web endpoint, what becomes web UI?

**Comment by ldez** [comment]
sorry wrong link: it's [api](http://v1-5.archive.docs.traefik.io/configuration/api/)

**Comment by ldez** [comment]
Web has been divided into API, REST, ping, metrics.

**Comment by cypx** [comment]
I want to limit dashboard access also, so I start with adding to my traefik.toml

```toml
[entryPoints.traefik]
address = ":8080"
rule = "Host:admin.example.com"
[entryPoints.traefik.tls]
[entryPoints.traefik.auth.basic]
users = ["admin:XXXXXXXXXXXXXXXXXXXX"]
```

But I encounter two issues:
- rule to limit host seems to be ignored
- it's not possible to get a valid certificat using let's encrypt (cause Traefik crash if I add 'entryPoint = ["https","traefik"]' on ACME config)

So I solve my problem by using a reverse proxy to access dashboard and stopping to publish 8080 port.

Traefik entrypoints in my traefik.toml now look like

```toml
[entryPoints.traefik]
address = ":8080"
[entryPoints.traefik.auth.basic]
users = ["admin:XXXXXXXXXXXXXXXXXXXX"]
```

And traefik service into my compose file is something like that

```yaml
services:
  proxy:
    image: traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/path_to/traefik.toml:/traefik.toml"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webgateway
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:admin.example.com"
```

Hope it's help.

**Comment by ldez** [comment]
@cypx `rule` is not a option for entrypoint: http://docs.traefik.io/configuration/entrypoints/

In theory, this works:

```toml
[entrypoints]
  # ...

  [entrypoints.dashboard]
    address=":8080"

  [entrypoints.api]
    address=":8081"

  # Activate API and Dashboard
  [api]
    entrypoint="api"

[file]
  [backends]
    [backends.backend1]
      [backends.backend1.servers.server1]
        url = "http://127.0.0.1:8081"

  [frontends]
    [frontends.frontend1]
      entrypoints = ["dashboard"]
      backend = "backend1"
        [frontends.frontend1.routes.route01]
        rule = "Host:admin.example.com"
```

**Comment by cypx** [comment]
@ldez 
Good to know, thanks!

**Comment by Cajga** [comment]
@ldez thanks for the example it works perfectly together with basic auth as well.

I think this solution could be further improved as it has few issues:

- additional entrypoint is defined (i do not really like that on any of my front end urls going to this port shows the dashboard)
- even if we set up basic auth there is no TLS so basic auth goes in clear text 

So I tried to improve it and moved the entrypoint port 8443 and enabled tls on that entrypoint. This works but as I do not have a valid cert (it gives the default traefik cert) it is still not perfect.

As I have let's encrypt set up for the https entrypoint I tried to use the [api] with the normal https entry point but unfortunately it screwed up the routing somehow as all the request ended up with the api dashboard.
My config and the two docker-compose file looked like this:
```
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
entrypoint = "https"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.org"
watch = true
exposedbydefault = false

[acme]
email = "***********@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"
```

The docker compose file to start the traefik container was:
```
version: '2'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - traefikext
    labels:
      - traefik.frontend.rule=Host:traefik.mydomain.org
      - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik

networks:
  traefikext:
    external: true
```

A test container docker compose file to create a second frontend for testing was:
```
version: '2'

services:
  whoami:
    image: emilevauge/whoami
    networks:
      - traefikext
    labels:
      - traefik.backend=whoami
      - traefik.frontend.rule=Host:whoami.mydomain.org
      - traefik.enable=true

networks:
  traefikext:
    external:
      name: traefikext
```

With this config even if I went to whoami.mydomain.org I ended up with the api dashboard.
So, is there a way to use the https entrypoint (with let's encrypt support) with the api?

**Comment by flesser** [comment]
@Cajga: I tried your configuration and also ran into the routing issues you described (all whoami.mydomain.org ending up with the api dashboard).

However, if I set the api entryPoint to the default (`traefik`), it worked:
```toml
[api]
  entryPoint = "traefik"
  dashboard = true
```
`traefik.mydomain.org` now routes to the Dashboard (with LetsEncrypt https) and `whoami.mydomain.org` to the whoami container.

(Maybe also add the `traefik.port=8080` label to the traefik container for explicit port configuration)

**Comment by ldez** [comment]
https://docs.traefik.io/configuration/backends/web/#deprecation-compatibility

**Comment by kickedinthehead** [comment]
Just in case anybody comes across this issue and simply wants to run the Traefik dashboard under a subdomain without having to use a port and securing it with basic authentication, the probably easiest way is to just hide it behind a nginx proxy.

A simple docker compose snippet in a docker environment could look like this:

```
traefik_dashboard:
    image: dhswt/nginx-basic-auth:1.3
    environment:
      - LISTEN_PORT=8080
      - HTPASSWD=foo:$$apr1$$Ox/eFVn5$$HHIeCQecIRD1yjP7RC2891
      - FORWARD_HOST=traefik
      - FORWARD_PORT=8080
    deploy:
      labels:
        - 'traefik.port=8080'
        - 'traefik.frontend.rule=Host:traefik.example.net'
```

Make sure to escape the dollar signs by an additional dollar sign. The image `dhswt/nginx-basic-auth:1.3` already comes with a preconfigured nginx server. It is possible to customize a stock nginx docker image as well, of course.

The environment variable `FORWARD_HOST` is pointing to the Traefik docker service. In this case it's reachable by the hostname `traefik` and needs to be adapted accordingly. It might be necessary to set the `hostname` key in the configuration of the Traefik docker service.

**Comment by Berndinox** [comment]
The additional Nginx Proxy is not necessary.

Here my working example:


```
version: "3"
 
services:
  traefik:
    image: traefik
    #command: --consul --consul.endpoint=consul:8500
    #command: storeconfig --consul --consul.endpoint=consul:8500
    networks:
      proxy:
        aliases:
            - traefik
    ports:
      - 80:80
      - 443:443
      #- 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefikdata:/etc/traefik/
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:proxy.mydomain.at"
        - "traefik.backend=traefik"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.auth.basic=foo:bar"
      replicas: 3
      #replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 45s
        monitor: 15s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s


volumes:
  traefikdata:
    driver: local-persist
    driver_opts:
      mountpoint: /data/docker/proxy

networks:
  proxy:
    external: true
```

**Comment by BirkhoffLee** [comment]
I figured out using the following configuration:

traefik.toml:
```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.redirect]
      entryPoint = "https"
      permanent = true

  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]

  [entryPoints.traefik]
    address = ":9987"
    compress = true

    [entryPoints.traefik.auth.basic]
      users = ["123:456"]

[api]
  entryPoint = "traefik"
  dashboard = true
```

docker-compose.yml:
```yaml
version: '3'

services:
  traefik:
    ......
    expose:
      - 9987
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:traefik.birkhoff.me"
      - "traefik.basic.port=9987"
      - "traefik.basic.protocol=http"
    ......
```
