### ISSUE TITLE
[Improvement] Blue/Green deployment

### ISSUE THREAD

**Issue by samber** [containous/traefik#914]
Hey guys !

What about an API route to update the constraints of a local Traefik instance ?

Example:

```
# traefik.toml
[consulCatalog]
  endpoint = 127.0.0.1:8500
  constraints = []
```

```sh
# erase old constraints
$ curl -X PUT' /api/providers/consulCatalog/constraints' -d '["tag==api-us-east", "tag!=api-blue"]'
# set/erase one constraint
$ curl -X PATCH '/api/providers/consulCatalog/constraints' -d 'tag!=api-blue'
# remove one constraint
$ curl -X DELETE '/api/providers/consulCatalog/constraints/tag!=api-blue'
# flush constraints
$ curl -X DELETE '/api/providers/consulCatalog/constraints'
```

**Comment by samber** [comment]
I would be even better to have a custom flag in provider configuration, dedicated to blue/green deployment:

- Backend configuration from kv store:
  - container 1 ```/traefik/backends/etcd/my-service/servers/my-container-1/bluegreen = v4.2```
  - container 2 ```/traefik/backends/etcd/my-service/servers/my-container-2/bluegreen = v5.0```
- Frontend configuration of a service from Traefik api or backends:
  - ```/traefik/frontends/my-service/bluegreen = v4.2```
  - Then ```/traefik/frontends/my-service/bluegreen = v5.0```
  - To rollback: ```/traefik/frontends/my-service/bluegreen = v4.2```
- UI: ```<select>``` button to switch bluegreen mode.

**Comment by WTFKr0** [comment]
I like that

**Comment by jsierles** [comment]
This looks promising. Is there a way to do blue/green deployment today, without this API?

**Comment by emilevauge** [comment]
I like this idea of a constraints API. @samber by chance, would you work on this ?

**Comment by JavaJeffG** [comment]
Support for Blue/Green deployments would be great.   We have to support many stateful legacy applications, meaning we also need Traefik's support of sticky sessions.   It would be great if there was a way with Traefik to (assuming old version is 'blue'):

* Manage a new 'green' version of a service.

* Only allow special traffic (maybe with a certain URL parameter) to hit the new 'green' version for testing purposes.

* Support a request so that all new traffic goes to the new 'green' version of the service, while continuing to send existing 'sticky' traffic to the old 'blue' version of the service.

* Support a subsequent request so that all traffic is sent to the new 'green' service.

I would not be surprised if there are lots of teams who have to support stateful applications, who would really like to be using blue/green deployments.

Thanks.

**Comment by bintut** [comment]
I am requesting a feature to support blue/green deployment when using Docker swarm mode as its backend configuration.

The idea is to support a label for source IP address(es), IP address range or subnet (or geolocation perhaps) and forward the users' traffic to a backend server intended for the green deployment. Let's say serviceA is running version 1.0.0 in the blue environment (active) at overlay network A then another serviceA is also running but this time it is on version 1.0.1 in the green environment attached to both overlay networks A and B but for selected users only whose IP addresses matches to the label.

Thank you in advance.

**Comment by bintut** [comment]
ServiceA and ServiceB are basically the same application with different Docker image tags/versions but ServiceB comes maybe with additional feature and/or minor fixes.

- Blue: ServiceA on v1.0.0 (active as catch all)
- Green: ServiceB on v1.0.1 (active selectively if _traefik.backend.allow.ipaddr_, _traefik.backend.allow.network_, and/or _traefik.backend.allow.country_ labels is/are present)

**Comment by bintut** [comment]
The [Nomad](https://www.nomadproject.io/docs/operating-a-job/update-strategies/blue-green-and-canary-deployments.html) project has support for blue/green + canary deployments. However, it is not stated there how they are going to decide whose traffic will be forwarded to the canary version or maybe I'm not yet aware of it. I hope that in Traefik using Docker swarm mode backend, the source IP address(es), source network and/or source geolocation will be supported to decide whose traffic will be forwarded to the canary version.

**Comment by mustafayildirim** [comment]
It would be great 👍

**Comment by BastienM** [comment]
I managed to come close to a workaround, while the feature is being worked on.

So far I am using a combination of Consul and File endpoint but lacks of auto-reloading, `watch = true` is not working for me and cross-endpoint communication.

### Target workflow
1. Deploy containers
2. Update `config.toml` with correct backend to use for production/preproduction
3. traefik reloads the configuration
4. Static frontends now points to correct backends

(2. could be automated via a CI's job)

### Current problem(s)
* Cannot use Consul + Consul KV (KV entries are being ignored)
* Cannot use Consul + Etcd (traefik fails to choose a endpoint)
* Cannot reference a backend from another endpoint (traefik does not recognize the backend)
* `watch = true` does not reload traefik's configuration on changes

### Suggestion(s)
* Allow frontends to cross-endpoint references backends
* Allow usage of Consul's catalog and a KV store (KV entries can override settings or at least create frontends/backends aliases)

---

### docker-compose.yml
```yaml
version: '2'
services:
  consul:
    image: consul:latest
    container_name: consul
    networks:
      - discovery
    ports:
      - "8400:8400"
      - "8500:8500"
      - "172.17.0.1:53:8600/udp"
    labels:
      SERVICE_IGNORE: "true"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    privileged: true
    networks:
      - discovery
    depends_on:
      - consul
    command: -internal=true consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    labels:
      SERVICE_IGNORE: "true"
  
  proxy:
    image: traefik
    container_name: proxy
    command: --web --file --consul --consul.endpoint=consul:8500 --consulcatalog.endpoint=consul:8500 --logLevel=DEBUG
    networks:
      - internet-gateway
      - discovery
      - proxy
    ports:
      - "80:80"
      - "443:433"
      - "8080:8080"
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config.toml:/traefik.toml
    labels:
      SERVICE_IGNORE: "true"

  app-blue:
    image: emilevauge/whoami
    networks:
      - proxy
    expose:
      - 80
    labels:
      SERVICE_NAME: "blue"
      SERVICE_TAGS: "traefik.frontend.rule=Host:blue.service.consul"

  app-green:
    image: emilevauge/whoami
    networks:
      - proxy
    expose:
      - 80
    labels:
      SERVICE_NAME: "green"
      SERVICE_TAGS: "traefik.frontend.rule=Host:green.service.consul"

networks:
  discovery:
  internet-gateway:
  proxy:
```

### config.toml
```toml
[file]
watch = true

[backends]
  [backends.production]
    [backends.production.servers.server1]
    url = "http://<app-blue_ip>:80"
  [backends.preproduction]
    [backends.preproduction.servers.server1]
    url = "http://<app_green_ip>:80"

[frontends]
  [frontends.production]
  backend = "production"
    [frontends.production.routes.route-host-production]
    rule = "Host:production.myapp.local"
  [frontends.preproduction]
  backend = "preproduction"
    [frontends.preproduction.routes.route-host-preproduction]
    rule = "Host:preproduction.myapp.local"
```
