### ISSUE TITLE
Traefik ingressroutetcp does not work with letsencrypt certs

### ISSUE THREAD

**Issue by ankycooper** [containous/traefik#9148]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I wanted to have TLS for TCP service  so I created the following

IngressRouteTCP manifest 

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mq-ingess-tcp
spec:
  entryPoints:
    - mqs
  routes:
    - match: HostSNI(`mq.example.com`)
      services:
        - name: mq
          port: 1883
  tls:
    certResolver: le-prod
    domains:
      - main: mq.example.com
        sans:
          - mq.example.com
    passthrough: false
    options:
      name: tlsoptions
      namespace: traefik
```

As the above did not generate cert I also created the following which got the Letsencrypt cert

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mq-ingess
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mq.example.com`)
      services:
        - name: mq
          port: 1883
      middlewares:
        - name: security
          namespace:  traefik
  tls:
    certResolver: le-prod
    domains:
      - main: mq.example.com
        sans:
          - mq.example.com
    options:
      name: tlsoptions
      namespace: traefik
```

### What did you see instead?

#without SNI
openssl s_client -showcerts -connect mq. example.com:443 > default traefik cert
openssl s_client -showcerts -connect mq. example.com:8883 > default traefik cert

#with SNI
openssl s_client -showcerts -connect mq. example.com:443 -servername mq. example.com > letsencrypt cert
openssl s_client -showcerts -connect mq. example.com:8883 -servername mq. example.com > NO CERT

### What version of Traefik are you using?

Traefik: 2.7.1
Helm chart: 10.23.0

### What is your environment & configuration?

```values.yaml
logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json
additionalArguments:
    #letsecrypt staging 
  - "--certificatesresolvers.le-staging=true"
  - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
  - "--certificatesresolvers.le-staging.acme.email=mymail@gmail.com"
  - "--certificatesresolvers.le-staging.acme.storage=/data/acme-s.json"
  - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  #letsecrypt PROD 
  - "--certificatesresolvers.le-prod=true"
  - "--certificatesresolvers.le-prod.acme.tlschallenge=true"
  - "--certificatesresolvers.le-prod.acme.email=mymail@gmail.com"
  - "--certificatesresolvers.le-prod.acme.storage=/data/acme-p.json"
  - "--certificatesresolvers.le-prod.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"

#enable external svc
  - "--providers.kubernetesingress.allowexternalnameservices"
  - "--providers.kubernetescrd.allowexternalnameservices"

ports:
  mqs:
    port: 18883
    # hostPort: 18883
    expose: true
    exposedPort: 8883
    # The port protocol (TCP/UDP)
    protocol: TCP
  mq:
    port: 11883
    # hostPort: 11883
    expose: true
    exposedPort: 1883
    # The port protocol (TCP/UDP)
    protocol: TCP

volumes:
 - name: traefik-config
   mountPath: /config
   type: ConfigMap

persistence:
  enabled: true
  storageClass: "managed-nfs-storage-retain" 
  name: data
  accessMode: ReadWriteOnce
  size: 512Mi
  path: /data

providers:
  kubernetesCRD:
    allowCrossNamespace: true

service:
  spec:
    externalTrafficPolicy: Local
```

**Comment by strowi** [comment]
Running into a similar problem where it works for https, but not tcp.

**Comment by strowi** [comment]
@rtribotte Yes i was trying to terminate the tcp-tls connection with traefik (also behind a hetzner-loadbalancer with proxy-protocol).
Since that didn't work, i disabled the proxyprotocol and had the same config as @ankycooper .
After some hours of testing and trying i just let cert-manager generate an ingress for the subdomain and referenced that directly:

```yaml
apiVersion: v1
items:
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRouteTCP
  metadata:
    name: emqx
  spec:
    entryPoints:
    - emqx
    routes:
    - match: HostSNI(`emqx.$TLD`)
      services:
      - name: emqx
        port: 1883
        proxyProtocol:
          version: 2
        terminationDelay: 100
        weight: 10
    tls:
      secretName: emqx.$TLD
```

Now it works. After all that i am not 100% sure i didn't mix up some configuration with the proxyprotocol somewhere. Will try to re-do this tomorrow with a fresh brain and report back.
