### ISSUE TITLE
entryPoints redirect not working

### ISSUE THREAD

**Issue by gebv** [containous/traefik#919]
I want redirect in the following case `http://mysite.com => https://www.mysite.com` and `https://mysite.com => https://www.mysite.com`.
Why is not working?

traefik config
``` toml
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "^http://mysite.com/(.*)"
      replacement = "https://www.mysite.com/$1"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
    [entryPoints.https.redirect]
      regex = "^https://mysite.com/(.*)"
      replacement = "https://www.mysite.com/$1"


[acme]
email = "..."
storageFile = "/acmestorage/acme.json"
entryPoint = "https"
[[acme.domains]]
   main = "mysite.com"
   sans = ["www.mysite.com"]

```

docker-compose for traefik
``` yml
version: "2"
services:
  proxy:
    image: traefik:v1.1.1
    command: --web --docker --docker.domain=mysite.com --logLevel=ERROR
    volumes:
      - ./config.toml:/traefik.toml
      - ./storage:/acmestorage
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - "80:80"
      - "443:443"
      - "8089:8080"
networks:
  default:
    external:
      name: internal_network
```

docker-compose for app
``` yml
version: "2"
services:
  app:
        image: golang:onbuild
        command: app.bin -config=config.json -stderrthreshold=INFO -v=0
        volumes:
          - ./state/app:/go/src/app
          - ./state/app/bin/app.bin:/usr/local/bin/app.bin
        ports:
          - 8080:80
        links:
          - postgres
          - elasticsearch
        labels:
            - "traefik.backend=mysite"
            - "traefik.port=80"
            - "traefik.frontend.rule=Host:www.mysite.com"
#
#
#
networks:
  default:
    external:
      name: internal_network
```

**Comment by set321go** [comment]
I'm having the same problem but my configuration is a bit different to yours

    defaultEntryPoints = ["http", "https"]
    [entryPoints]
          [entryPoints.http]
           address = ":80"
                [entryPoints.http.redirect]
                entryPoint = "https"
          # [entryPoints.http.auth.basic]
          # users = ["demo:junk"]
          [entryPoints.https]
          address = ":443"
              [entryPoints.https.tls]
          [entryPoints.https.auth.basic]
          users = ["demo:junk"]
     [acme]
          email = "ops@xxxx.com"
          storageFile = "/acme/acme.json"
          entryPoint = "https"
          onDemand = true
          onHostRule = true
          caServer = "https://acme-staging.api.letsencrypt.org/directory"
          [[acme.domains]]
             main = "demo.xxxx.com"
    [kubernetes]
    
then my k8s service 
    
    apiVersion: v1
    kind: Service
    metadata:
      name: traefik
      namespace: kube-system
      labels:
        k8s-app: traefik-ingress-lb
    spec:
      type: LoadBalancer
      selector:
        k8s-app: traefik-ingress-lb
      ports:
        - port: 80
          name: http
        - port: 443
          name: https

**Comment by set321go** [comment]
I was able to get my redirection working once traefik had the certificates configured correctly

**Comment by emilevauge** [comment]
@gebv Is your issue solved? Can I close this one ?

**Comment by gebv** [comment]
No, not solved my problem

**Comment by emilevauge** [comment]
@gebv your initial config is wrong. Can you have a look at what @set321go suggested?
```
[entryPoints]
      [entryPoints.http]
       address = ":80"
            [entryPoints.http.redirect]
            entryPoint = "https"
      address = ":443"
          [entryPoints.https.tls]
```

**Comment by nwwells** [comment]
I want to redirect `/` => `/ui`. is that possible?

**Comment by gebv** [comment]
@emilevauge what do you mean? I think syntax is correct

``` toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.https.redirect]
    regex = "^https://mysite.com/(.*)"
    replacement = "https://www.mysite.com/$1"
```

``` go
type GlobalConfiguration struct {
    EntryPoints               EntryPoints
    ... 
}

type EntryPoints map[string]*EntryPoint

type EntryPoint struct {
	Address  string
	TLS      *TLS
	Redirect *Redirect
    ...
}

type Redirect struct {
	EntryPoint  string
	Regex       string
	Replacement string
}
```

**Comment by gebv** [comment]
Any ideas

**Comment by avarabyeu** [comment]
@nwwells did you find the answer on your question?

**Comment by nwwells** [comment]
No.  We just stopped using traefik

**Comment by avarabyeu** [comment]
@nwwells and what was the replacement?

**Comment by nwwells** [comment]
Nginx

**Comment by ldez** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by alexsandro-xpt** [comment]
I have a same problema =/ nobody can help us?

**Comment by jibingeo** [comment]
After spending some time on this issue, I found that `http` to `https` redirection won't work if you don't have matching front-end rule. 

ie. If `https://hello.com` return `404`, then `http://hello.com` will also return `404` instead of redirecting to `https://hello.com`

**Comment by ArtyMcFly** [comment]
I'm seeing a similar issue as well, my toml is very similar to gebv's I am getting http -> https redirects as expected (`http://www.mysite.com => https://www.mysite.com`), but I am not getting `http:\\mydomain.com => http:\\www.mydomain.com`, `http:\\mydomain.com => https:\\www.mydomain.com`  or `https:\\mydomain.com => https:\\www.mydomain.com`  redirects. 


```
# traefik.toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/ca.crt"
      keyFile = "/ca.key"
    [entryPoints.https.redirect]
      regex = "^https://mysite.com/(.*)"
      replacement = "https://www.mysite.com/$1"
````

**Comment by ArtyMcFly** [comment]
I found a work around based on @jibingeo 's comments, the following is a stripped down version of my configurations:

```
services:
  static-files:
    image: mysite/mysite-static-files
    labels:
      - "traefik.backend=static-files"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:www.mysite.com,mysite.com"
  chat-server:
    image: mysite/mysite-chat
    labels:
      - "traefik.backend=chat-server"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:www.mysite.com,mysite.com;PathPrefixStrip: /chat"
  auth-server:
    image: mysite/mysite-auth-server
    depends_on:
      - database
    labels:
      - "traefik.backend=auth-server"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:www.mysite.com,mysite.com;PathPrefixStrip: /auth"
  traefik:
    image: traefik
    command: --web --docker --docker.domain=mysite.com --logLevel=ERROR
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - /home/centos/mysite-bundle.pem:/ca.crt
      - /home/centos/ca.key:/ca.key
```

and my toml

```
# traefik.toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    regex = "^http://mysite.com/(.*)"
    replacement = "https://www.mysite.com/$1"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/ca.crt"
      keyFile = "/ca.key"
    [entryPoints.https.redirect]
      regex = "^https://mysite.com/(.*)"
      replacement = "https://www.mysite.com/$1"
```

It looks like You need to include `mysite.com` and `www.mysite.com` as a front-end rule. Traefik appears to re-route correctly, but for whatever reason, it's needed as a front-end rule.
