### ISSUE TITLE
Kubernetes routing priority issue

### ISSUE THREAD

**Issue by m42u** [containous/traefik#943]
Hi guys,

We use traefik as an ingress controller in our kubernetes cluster and since we updated traefik from  `v1.0.0` to `v1.1.1` routing doesn't work anymore.
We have two backends defined as the following:
```
spec:
  rules:
    - host: "placeholder.example.com"
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 8080
            path: /api
          - backend:
              serviceName: web
              servicePort: 8080
```
And we're using `traefik.frontend.rule.type: PathPrefixStrip` (as our api serves requests on `/`)

Since `v1.1.1`, the api backend has a computed priority of 4. With this configuration, all requests are routed to the web backend even if the request starts with `/api` (which was correctly working on `v1.0.0`).

All the following requests are handled by the web backend:
- placeholder.example.com
- placeholder.example.com/
- placeholder.example.com/api
- placeholder.example.com/api/
- placeholder.example.com/api/test

If we add `path: /` on the web backend:
```
- backend:
    serviceName: api
    servicePort: 8080
  path: /api
- backend:
    serviceName: web
    servicePort: 8080
  path: /
```
The web backend has a computed priority of 1 (and the api backend still has a computed priority of 4).
Nevertheless, it doesn't work as expected because the `/` is striped on all requests on the web backend.
- placeholder.example.com works
- placeholder.example.com/test is striped so we're receiving `test` instead of `/test`
- placeholder.example.com//test works because it's striped so we're receiving `/test`
- placeholder.example.com/api/test works because `/api` is striped so we're receiving `/test` on the api backend

We saw [this PR](https://github.com/containous/traefik/pull/588) but it apparently doesn't fix priorities.

As we understand, if a backend has no priority (or priority = 0?), all requests are sent to this backend. In addition, on a backend with `path: /`, the `/` is striped so the backend will receive all the requests without the `/`.

As I said, it is correctly working on `v.1.0.0` with the first configuration.
Any idea? :)

Thanks!
