### ISSUE TITLE
Getting real client IP (X-FORWARDED-FOR) in k3s multi-server HA setup

### ISSUE THREAD

**Issue by jkotrlik** [containous/traefik#9450]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi everyone,

I've created myself the most standard K3s cluster with 3 cloud, public servers (all in "master" mode) with Traefik. I've installed cert-manager and I'm using LetsEncrypt generated wildcard SSL cert for HTTPS. I've also created a wildcard DNS record, which has all 3 public IPs in it (my aim is a proper, resilient HA cluster). There's nothing in front of the servers/traefik, no other loadbalancer, the traffic hits one of the servers directly. Now I'm having a problem with getting the real client IP in my pods (I'm using nginx inside of one of them to debug this). I'm looking at the standard X-FORWARDED-FOR and X-REAL-IP headers. I'm getting the client IP only in case the request hits the server where the Traefik pod actually runs. If it hits any of those two other servers, I get their public IP instead of the client's.

I have to say up-front that I'm not sure this is actually a bug or misconfiguration, but could easily be just the effect of how traefik is written and how it's supposed to be used. My current theory is that since the traefik "container" actually runs only on one machine, the other machines (using kube-proxy, IP tables or something else) just resend the traffic and then the traefik actually can't know that they are not the request origin. On the other hand, I would kinda expect that the traefik would be able to figure this out, or that it would perhaps add a different header with the true origin. I'm thinking possible solution would probably be to tune traefik to run a container on each server, or to add a Load Balancer (which though might not be quite possible if I go full-metal at some point in the future). I just want to be sure and want to know that I didn't overlook something and this really does not have the solution I would desire.

### What did you see instead?

When the request does not hit the machine which actually hosts the traefik pod, I get one of the other 2 public IPs of servers in my cluster.

### What version of Traefik are you using?

rancher/mirrored-library-traefik:2.6.2

/ $ traefik version
Version:      2.6.2
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-24T19:09:46Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

It's the most basic configuration the k3s applies using helm, plus I've added these to try to fight the issue:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    hostNetwork: true
    externalTrafficPolicy: Local
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,IP1,IP2,IP3"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entrypoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,IP1,IP2,IP3"
      - "--entryPoints.websecure.proxyProtocol.insecure"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,IP1,IP2,IP3"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,IP1,IP2,IP3"
```

Add more configuration information here.
