### ISSUE TITLE
Multiple frontend routes

### ISSUE THREAD

**Issue by f3l1x** [containous/traefik#957]
```toml
[frontends]
  [frontends.domain]
  backend = "domain"
  passHostHeader = true
    [frontends.domain.routes.route_1]
    rule = "Host: app.domain.cz"  
    [frontends.domain.routes.route_2]
    rule = "Host: test.domain.cz"  
    [frontends.domain.routes.route_3]
    rule = "Host: demo.domain.cz"  
    [frontends.domain.routes.route_4]
    rule = "Host: stage.domain.cz"  
    [frontends.domain.routes.route_5]
    rule = "Host: dev.domain.cz"  
```

But it returns always 404. I 

```toml
[frontends]
  [frontends.domain]
  backend = "domain"
  passHostHeader = true
    [frontends.domain.routes.route1]
    rule = "Host: app.domain.cz,test.domain.cz,demo.domain.cz,stage.domain.cz,dev.domain.cz"
```

This works like a charm.

-----

Am I wrong? I've thought that you can use more then 1 route. Thanks for an advice.
