### ISSUE TITLE
can't load middleware

### ISSUE THREAD

**Issue by dyipon** [containous/traefik#9591]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

installed latest (2.9.6) traefik binary, setuped a redirectscheme middleware, but cannot find on dashboard
                 

                                                                                                                                         

### What did you see instead?

i just get a "No data available" message on HTTP Middlewares tab

### What version of Traefik are you using?

v2.9.6

### What is your environment & configuration?

```yaml
http:                                                                                                                                                                         
 middlewares:                                                                                                                                                                   
   autoredirect:                                                                                                                                                            
      redirectScheme:                                                                                                                                                        
        scheme: https                                                                                                                                                        
        permanent: true            
        
```

Add more configuration information here.
