### ISSUE TITLE
api listening port(8080) is configurable

### ISSUE THREAD

**Issue by cherishman2005** [containous/traefik#9639]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

```
api:
  insecure: true
  dashboard: true
```

add port，such as
```
api:
  insecure: true
  dashboard: true
  port: 8081
````
