### ISSUE TITLE
docker multiple networks routing

### ISSUE THREAD

**Issue by j0hnsmith** [containous/traefik#970]
Here's an example `docker-compose.yml` that has two networks defined, one for containers that should have traefik config and one for those that shouldn't be exposed.

```yaml
version: '2'

networks:
    traefik:
        driver: bridge
    backend:
        driver: bridge

services:
    traefik:
        image: traefik:v1.1.1
        command: --web --logLevel=DEBUG
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
            - /root/acme.json:/acme.json
        networks:
            - traefik

    nginx:
        image: nginx:1.11.6-alpine
        expose:
            - "80"
        volumes:
            - /tmp:/usr/share/nginx/html
        labels:
            - "traefik.enable=true"
            - "traefik.backend=nginx"
            - "traefik.port=80"
            - "traefik.frontend.rule=PathPrefix:/"
        networks:
            - traefik

    backend_api:
        image: some_backend_api
        expose:
            - "8000"
        networks:
            - backend
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=PathPrefix:/api/"
            - "traefik.backend=backend_api"
            - "traefik.port=8000"
            - "traefik.passHostHeader=true"

    redis:
        image: redis:3.0.1
        mem_limit: 128M
        expose:
            - "6379"
        networks:
            - backend
        labels:
            - "traefik.enable=false"

    postgres:
        image: postgres:9.4.4
        environment:
            POSTGRES_PASSWORD: password
        expose:
            - "5432"
        networks:
            - backend
        labels:
            - "traefik.enable=false"
```

With a setup like this everything appears to be ok, but requests that match `PathPrefix:/api/` timeout as traefik creates the backend with the ip from the `backend` network, not the one from the `traefik` network.

This is somewhat related to #959.
