### ISSUE TITLE
Certificates are shared between entrypoints

### ISSUE THREAD

**Issue by waterler** [containous/traefik#9702]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When two entrypoints with different certificate resolvers are created they should respect them and not use certificate from other entrypoint (both domains point to same server).

If I enter app from entrypoint  "entry-two" (port 2443):
* from domain "myapp.duckdns.org:2443/myapp" it works as expected by returning duckdns domain certificate.
* from domain "mydomain.com:2443/myapp" it should return either default self signed treafik cert or duckdns one and result in browser warning.

### What did you see instead?

Traefik returns certificate from cloudflare provider for domain "mydomain.com", even though it's not configured for this entry point.

### What version of Traefik are you using?

Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

traefik.yml:
```yaml
entryPoints:
  entry-one:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "mydomain.com"
            sans:
              - "*.mydomain.com"
  entry-two:
    address: :2443
    http:
      tls:
        certResolver: duckdns
        domains:
          - main: "myapp.duckdns.org"

certificatesResolvers:
  letsencrypt:
    acme:
      email: myemail@gmail.com
      storage: /etc/traefik/acme-cloudflare.json
      dnsChallenge:
        provider: cloudflare
  duckdns:
    acme:
      storage: /etc/traefik/acme-duckdns-lan.json
      dnsChallenge:
        provider: duckdns

providers:
  file:
    directory: /etc/traefik/cfgs
```

/etc/traefik/cfgs/myapp.yml
```yaml
http:
  routers:
    myapp:
      entryPoints:
        - entry-two
      service: myapp
      rule: PathPrefix(`/myapp`)

  services:
    myapp:
      loadBalancer:
        servers:
          - url: https://myapp-ip
```

Add more configuration information here.
