### ISSUE TITLE
Feature Request: http.auth.basic for Docker services

### ISSUE THREAD

**Issue by derphilipp** [containous/traefik#971]
It would be awesome if an equivalent of
```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.auth.basic]
  users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"]
```
would be available to use with Docker services using labels, so that even "unsafe" services can be at least protected with a simple username/password gate.

Thanks for all of your hard work - I really do enjoy traefik quite a lot!
