### ISSUE TITLE
backend from two containers -> no round robin

### ISSUE THREAD

**Issue by jerCarre** [containous/traefik#976]
I try this docker-compose with traefik 1.1.2 but no round robin on the adress vslin225.
If I scale whoami, the behaviour is very strange, a round robin but not with all containers ...

```yml
traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

whoami:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:vslin225"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:vslin225"
```
