### ISSUE TITLE
Traefik with IPv6 on frontend and X-Forwarded-For

### ISSUE THREAD

**Issue by CuBiC3D** [containous/traefik#977]
I am running the latest 1.1.2 release of Traefik with docker. My GitLab container show me the last sign on IP from users. I have seen, that some users have 172.17.0.1(docker host) as their sign on IP logged. After debugging, I found out, that it was IPv6 related.
Example setup from docs on the Server:
```yml
traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"
```

Now let *domain.com* be a domain having an A and AAAA record for IPv4 and IPv6. Client have native dualstack IPv6/IPv4 WAN network.

Over IPv6 (default):
```
user@notebook:~$ curl -H Host:whoami.docker.localhost http://domain.com
Hostname: c5dd7935ecd7
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.4
IP: fe80::42:acff:fe11:4
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.47.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.17.0.1
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Proto: http
X-Forwarded-Server: 907cbcedd362
```

Over IPv4:
```
user@notebook:~$ curl -4 -H Host:whoami.docker.localhost http://domain.com
Hostname: c5dd7935ecd7
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.4
IP: fe80::42:acff:fe11:4
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.47.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 79.212.xx.xxx
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Proto: http
X-Forwarded-Server: 907cbcedd362
```

Only for IPv4 the X-Forwarded-For header has the real value. Any way to fix that?
BTW: I:heart:Traefik ;)

**Comment by Yggdrasil** [comment]
I'm running Traefik 1.2.0-rc1 with file-based config on some Amazon Ubuntu 14.04 instances and am getting the correct IPv6 addresses in X-Forwarded-For.

So, I'm not sure why it's different for you. Perhaps it's fixed in the newer versions, or maybe something about the Docker environment?

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by lvnilesh** [comment]
@yggdrasil appreciate if you can please describe your file based config. I am running into somewhat related issue https://github.com/containous/traefik/issues/1880

**Comment by timwhite** [comment]
I'm also having this issue. The fixes in #1880 seem directed at swarm mode, and I'm just using docker-compose with a single host. Any ideas?

**Comment by smueller18** [comment]
@timwhite I stumbled over the same problematic while setting up my loadbalancer. I solved the problem by using [docker-ipv6nat](https://github.com/robbertkl/docker-ipv6nat). Here is a working docker-compose which I ran on my public host obtaining following results:

```yaml
version: '2.3'

services:

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.port=80"

  ipv6nat:
    image: robbertkl/ipv6nat
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # must be a ULA range
        - subnet: fd00:dead:beef::/48
```

```
> curl -4 -H Host:whoami.docker.localhost http://<MY_PUBLIC_DOMAIN>
Hostname: fdaf799d8bc1
IP: 127.0.0.1
IP: ::1
IP: 172.18.0.2
IP: fd00:dead:beef::2
IP: fe80::42:acff:fe12:2
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.58.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 79.195.xxx.xxx
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 80d0cd2addfa
X-Real-Ip: 79.195.xxx.xxx
```

```
> curl -6 -H Host:whoami.docker.localhost http://<MY_PUBLIC_DOMAIN>
Hostname: fdaf799d8bc1
IP: 127.0.0.1
IP: ::1
IP: 172.18.0.2
IP: fd00:dead:beef::2
IP: fe80::42:acff:fe12:2
GET / HTTP/1.1
Host: whoami.docker.localhost
User-Agent: curl/7.58.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 2003:c2:xxxx:xxxx:xxxx:xxxx:xxxx:6bec
X-Forwarded-Host: whoami.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 80d0cd2addfa
X-Real-Ip: 2003:c2:xxxx:xxxx:xxxx:xxxx:xxxx:6bec
```
