### ISSUE TITLE
Pass hostname to backend when using serversTransports with TLS certificate 

### ISSUE THREAD

**Issue by marcmognol** [containous/traefik#9841]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello, below my use cases:

I have an application which is hosted in a kubernetes cluster (3 nodes).
The application is accessible only through https, and I am not able to disable https.
The certificate of this application is signed by out Root CA, and it is the same for all 3 nodes.

Now, I need to setup a load balancer in front of this cluster kubernetes. so I use the following configuration and it works like a charm:

```
http:
  routers:
    myapp:
      entryPoints:
      - websecure
      service: myapp-service
      rule: Host(`myapp.fr`) && PathPrefix(`/`)
      tls:
        domains:
          - main: myapp.fr
  services:
    myapp-service:
      loadBalancer:
        serversTransport: myapp-transport
        servers:
        - url: https://myapp-srv1.local:443
        - url: https://myapp-srv2.local:443
        - url: https://myapp-srv3.local:443
        healthCheck:
          hostname: myapp.fr
          path: /landing-page/
          interval: 15s
        sticky:
          cookie:
            secure: true
            httpOnly: true
  serversTransports:
    myapp-transport:
      insecureSkipVerify: true
tls:
  certificates:
    - certFile: /secrets/myapp.cer
      keyFile: /secrets/myapp.key
```

But the problem is the follwing:

Now, I would like to remove insecureSkipVerify to increase security. But traefik check the certificate against the server name instead of checking it with the hostname of the exposed service.

Actual:

```
  serversTransports:
    myapp-transport:
      insecureSkipVerify: true
```

Expected:
```
  serversTransports:
    myapp-transport:
      rootCAs:
        - foo.crt
        - bar.crt
```

Is it possible to change this behavior, or is there any other way to do it knowing that:
- certificate is the same on all 3 nodes (I can't change that)
- not able to disable TLS for all 3 nodes
Thanks
