### ISSUE TITLE
Stopped docker containers still have frontend and backend configuration

### ISSUE THREAD

**Issue by wader** [containous/traefik#986]
### What version of Traefik are you using (`traefik version`)?

```
Version:      v1.1.0
Codename:     camembert
Go version:   go1.7.3
Built:        2016-11-18_09:20:46AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?

```toml
#debug = true

defaultEntryPoints = ["http", "https"]

accessLogsFile = "/proc/self/fd/1"

[web]
  address = ":8080"
[web.auth.basic]
  users = ["REMOVED"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[acme]
  email = "REMOVED"
  storage = "/acme/acme.json"
  entryPoint = "https"
  OnHostRule = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedbydefault = false
  watch = true
```

### What did you do?

Start, stop and removed docker containers using docker-compose config with 4 services.

All services have there labels:
```yml
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.port=80
      - traefik.frontend.rule=Host:REMOVED.com
```

Two also have `PathPrefix` rule.

I was doing some development so I used docker-compose to rebuild and restart the services quite a bit.

### What did you expect to see?

No stopped and removed containers should still have frontend and backend configuration. I my case just some stopped and removed containers are left.

### What did you see instead?

Some stopped and removed containers still have frontend and backend configuration. The backend configurations left have URL with empty address (`http://:80`).

If I make a request matching one of the frontends with empty backend URL address i see this in the log:

```
$ curl -v https://REMOVED.com
* Rebuilt URL to: https://REMOVED.com/
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to REMOVED.com (1.2.3.4) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: REMOVED.com
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET / HTTP/1.1
> Host: REMOVED.com
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 21 Dec 2016 18:21:39 GMT
< Location: https://REMOVED.com:443/
<
* Curl_http_done: called premature == 0
* Connection #0 to host REMOVED.com left intact
```
Log:
```
traefik_1  |127.0.0.1 - - [21/Dec/2016:18:20:02 +0000] "GET / HTTP/1.1" 302 5 "" "curl/7.51.0" 16275 "" "" 0ms
traefik_1  |155.4.238.15 - - [21/Dec/2016:18:20:02 +0000] "GET / HTTP/1.1" 302 5 "" "curl/7.51.0" 16274 "Host-REMOVED" "http://:80" 1ms
```
No idea why i get a redirect response
*Update:* Probably because traefik connect to itself on port 80 and hits `entryPoints.http.redirect`

Not sure but for some reason it seems like the empty address causes traefik to connect 127.0.0.1 causing the two log lines. But that is just my speculations.

Traefik restart fixes the problem.
