### ISSUE TITLE
Frontend-based Redirect Rules

### ISSUE THREAD

**Issue by adamgoose** [containous/traefik#987]
### What version of Traefik are you using (`traefik version`)?
Latest

### What is your environment & configuration (arguments, toml...)?
dynamic file-based from confd

### What did you do?
```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "^http://(SOME|BUT|NOT|ALL|DOMAINS|HERE)/(.*)"
      replacement = "https://$1/$2"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
```

### What did you expect to see?
When `https.domain.com` is included in the regex, and said frontend has `entrypoints = http & https`, and I hit `https.domain.com`, I am successfully redirected to HTTPS.

When `http.domain.com` is *not* included in the regex, and said frontend has `entrypoints = http only`, and I hit `http.domain.com`, I should *not* be redirected, and the request *should* proxy to the proper backend.

### What did you see instead?
When `http.domain.com` is *not* included in the regex, and said frontend has `entrypoints = http only`, and I hit `http.domain.com`, I am *not* redirected, but only see a white page; the request is not proxied to the backend.

---

Suggested solution: allow for redirect to/from endpoints at the frontend config level.
