### ISSUE TITLE
Disable acme for non https endpoints

### ISSUE THREAD

**Issue by psi-4ward** [containous/traefik#989]
I use acme with `OnHostRule=true` to aquire lets encrypt certs but treafik requests certs for Host-Rules matching only on `http` Entrypoint. I would expect a host-rule filtering to the `[acme] entryPoint`

**Comment by dtomcej** [comment]
Can you provide a sample of your traefik.toml?

**Comment by psi-4ward** [comment]
Traefik Config
```toml
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "hostmaster@example.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
acmeLogging = true
OnHostRule = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = true
```

Sample Docker run
```sh
docker run \
  --name www \
  --network public \
  -l "traefik.frontend.rule=Host:test.example.com,88.99.77.66" \
  -l "traefik.frontend.entryPoints=http" \
  -l traefik.port=8043 \
  -v /opt/www:/srv/http \
  pierrezemb/gostatic --forceHTTP
```

Treafik prints now errors acquiring a Certificate for  88.99.77.66.
Apart from that I would expect Traefik to not try to acquire one for `test.example.com` and `88.99.77.66` cause of `traefik.frontend.entryPoints=http`
