### ISSUE TITLE
Trefik as a Kubernetes Ingress controller

### ISSUE THREAD

**Issue by Demonsthere** [containous/traefik#992]
Hi there, I have been using traefik as the Ingress controller in my Kubernetes environment. 
I have found that the performance is very very varying depending on the traefik version: 
on version from 1.0.0 to 1.0.2 it works just fine, using the configuration found on the website:

```yaml
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        version: v1.0.2
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik:v1.0.2
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80
        - containerPort: 8090
        args:
        - --web
        - --kubernetes
        - --web.address=:8090
      nodeSelector:
        kubeadm.alpha.kubernetes.io/role: master
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 8090
    targetPort: 8090
    name: webui
  - port: 80
    targetPort: 80
    name: api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
```
Using this I am able to access my cluster using the domain name. 
However, when using traefik version from 1.1.0 upwards, a curl to `my.domain.com/myapp` takes forever, it does not give a 404, the curl is just stuck. 
Is there some additional configuration for traefik that is now needed to work in kubernetes?
