### ISSUE TITLE
Traefik not logging into Cloudflare for certificate creation

### ISSUE THREAD

**Issue by rdmchr** [containous/traefik#9950]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I want to use traefik in combination with Let's Encrypt to automatically generate wildcard SSL certificates. I'm using Cloudflare.

### What did you see instead?

I've recently noticed that traefik is not using Let's Encrypt for certificate creation. Instead, it only serves the default certificate. This has gone unnoticed for quite some time since I use Cloudflare which issues another certificate.

I also noticed that traefik does not create the required DNS entry for Let's Encrypt. Upon further investigation (changing the `CF_API_KEY` to a wrong value) I noticed that I'm not getting any authentication error, which leads me to believe that traefik does not even try to authenticate with Cloudflare. Furthermore I looked at the https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/<ACME ID> URLs and they all say that the dns-01 challenge is `pending`.

Between test runs I made sure to delete my /letsencrypt folder, but that did not change anything.

### What version of Traefik are you using?

Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
services:
  traefik:
    image: traefik:v2.10
    restart: always
    container_name: traefik
    hostname: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://traefik-socket-proxy:2375"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.webunsecure.address=:80"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=$CLOUDFLARE_IPS"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.email=<LETS ENCRYPT EMAIL>"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=10"
      - "--certificatesresolvers.le-vpn.acme.dnschallenge=true"
      - "--certificatesresolvers.le-vpn.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le-vpn.acme.email=<LETS ENCRYPT EMAIL>"
      - "--certificatesresolvers.le-vpn.acme.storage=/letsencrypt/acme-vpn.json"
      - "--certificatesresolvers.le-vpn.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le-vpn.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.le-vpn.acme.dnschallenge.delaybeforecheck=10"
      - "--accesslog=true"
      - "--accesslog.filepath=/log/access.log"
      - "--accesslog.filters.statuscodes=200,300-399,500-599"
      - "--accessLog.bufferingSize=100"
    networks:
      - traefik-network
    ports:
      - 443:443
      - 80:80
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./log:/log"
    environment:
      - CF_API_EMAIL="<CLOUDFLARE EMAIL>"
      - CF_API_KEY=<CLOUDFLARE API KEY>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.<DOMAIN 1>`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.middlewares=authentik-proxy@docker"

  traefik-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: traefik-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - traefik-network


networks:
  traefik-network:
    external: true
    name: traefik

```

As you can see I'm running two certificate resolvers, `le` is for <DOMAIN 1> and `le-vpn` is for <DOMAIN 2>. I'm not quite sure if that's necessary, but since I was debugging I wanted to try all my options first.

### If applicable, please paste the log output in DEBUG level

Log file was too long: https://gist.github.com/rdmchr/2b3f20d6e6a8f9da6332f99486c8fd77#file-traefik-log
