### ISSUE TITLE
Support alternative remote storage for plugins

### ISSUE THREAD

**Issue by N0K0** [containous/traefik#9960]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

So here is the scenario:

I'm testing traefik in a network area which is unable to talk to the internet directly. I have access to an Artifactory instance that can mirror and cache arbitrary URLs so that:

`https://artifactory.local/public/download/github.com/wiltonsr/ldapAuth/v0.0.22`   
translates to:  
`https://plugins.traefik.io/public/download/github.com/wiltonsr/ldapAuth/v0.0.22`

From what I can see, making this variable configurable would get me a long way?
https://github.com/traefik/traefik/blob/master/pkg/plugins/client.go#L35

My first thought would be to enable reading it from the static configuration per plugin, but I do not know how the plugin client is actually implemented :sweat: :angel: 

```toml
[experimental.plugins.block]
pluginhost = "https://artifactory.local/"
modulename = "github.com/traefik/plugin-blockpath"
version = "v0.2.0"
```

PS:
Using local-plugins as a workaround, but this would be sweet to have!
