### ISSUE TITLE
Storeconfig doesn't behave as expected 

### ISSUE THREAD

**Issue by ranzbak** [containous/traefik#997]
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
I'm using the traefik docker container, and I have a toml file stored at /config/traefik.toml
My consul server is living at svc-consul:8500

```toml
# traefik.toml
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"

[consul]
  endpoint = "svc-consul:8500"
  watch = true
  prefix = "traefik"

[acme]
  email = "some@mailaddress.nl"
  storage = "traefik/acme/account" # the key where to store your certificates in the KV store
  storageFile = "acme.json"
  onDemand = true
  # caServer = "http://172.18.0.1:4000/directory"
  #caServer = "https://acme-staging.api.letsencrypt.org/directory"
  entryPoint = "https"

```

### What did you do?
execute: `/traefix storeconfig --configFile=/config/traefik.toml`

### What did you expect to see?
I expected the toml config to be stored in the consul kv store

### What did you see instead?
```
2016-12-25T11:23:57.529374915Z 2016/12/25 11:23:57 Error running traefik: Error using command storeconfig, no Key-value store defined
```

It looks like the --configFile flag is ignored
