### ISSUE TITLE
i/o timeout on first docker connection

### ISSUE THREAD

**Issue by zifeo** [containous/traefik#999]
### What version of Traefik are you using (`traefik version`)?

camembert via docker (no swarm)

### What is your environment & configuration (arguments, toml...)?

```toml
graceTimeOut = 10
debug = true
checkNewVersion = true
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "#####"
storageFile = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true

[retry]
attempts = 2

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
usebindportip = false
swarmmode = false
```

Both Traefik and containers are on the same manually created network.

Maybe related #982.

### What did you do?

Launching Owncloud via:
```yml
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:#####
      - traefik.port=80
```

### What did you expect to see?

Owncloud accessible through https.

### What did you see instead?

Timeout when establishing the first connection to that docker. **This is not always the case**. If the first url used is a 200OK then the connection is working whereas if the first url used is a redirection or another status, Traefik will timeout in loop.

```shell
traefik    | time="2016-12-26T23:48:15Z" level=debug msg="Challenge GetCertificate #####" 
traefik    | time="2016-12-26T23:48:15Z" level=debug msg="ACME got domain cert #####" 
traefik    | time="2016-12-26T23:48:43Z" level=warning msg="Error forwarding to http://172.19.0.4:80, err: dial tcp 172.19.0.4:80: i/o timeout" 
traefik    | time="2016-12-26T23:48:45Z" level=warning msg="Error forwarding to http://172.19.0.4:80, err: dial tcp 172.19.0.4:80: i/o timeout" 
traefik    | time="2016-12-26T23:48:45Z" level=debug msg="New attempt 2 for request: /status.php" 
traefik    | time="2016-12-26T23:48:47Z" level=debug msg="Challenge GetCertificate #####" 
traefik    | time="2016-12-26T23:48:47Z" level=debug msg="ACME got domain cert #####" 
traefik    | time="2016-12-26T23:49:15Z" level=warning msg="Error forwarding to http://172.19.0.4:80, err: dial tcp 172.19.0.4:80: i/o timeout" 
traefik    | time="2016-12-26T23:49:17Z" level=warning msg="Error forwarding to http://172.19.0.4:80, err: dial tcp 172.19.0.4:80: i/o timeout" 
```

After each restart events I have to manually trigger a 200OK before any other requests is issued. This is hard when multiple clients are pooling the owncloud server (e.g. `/status.php` requests).
